Samsung/ONE

- tools/tflitefile_tool/parser/tflite/tflite_tensor.py
This commit changes numpy `bool` type to `bool_` type. 
`bool` type is deprecated.
> [tools/tflitefile_tool] Fix numpy bool type

- runtime/onert/core/include/util/Utils.h
This commit fixes what might use moved args.
- Change lambda function passed by universal reference to value
- Remove unused args passed by universal reference
> [onert] Fix using after move

- infra/scripts/test_arm_nnpkg.sh
This commit removes runtime's interpreter nnpackage test.
> [infra] Remove interpreter nnpackage test

- compiler/luci/pass/src/ConvertNCHWToNHWCPass.cpp
This skips unnecessary traversal in ConvertNCHWToNHWCPass.
> [luci] Skip unnecessary traversal in ConvertNCHWToNHWCPass

- .github/workflows/deploy-github-pages.yml
This commit adds repo owner check on deploy-gtihub-pages.
---
Related issue:  #10426
> [Ci] Check repo owner on deploy-github-pages

- infra/docker/bionic/Dockerfile
- infra/docker/focal/Dockerfile
- infra/docker/jammy/Dockerfile
This commit adds user account with sudo permission in developer docker image. 
It will help to maintain file ownership and test environment.
---
Related issue: https://github.com/Samsung/ONE/issues/10425#issuecomment-1415340488
> [infra/dockerfile] Add user account and sudo permission

- compiler/luci-value-test/test.lst
This will temporary disable YUV_TO_RGB_U8_000 as sometimes fails in jammy and this makes CI unhappy.
> [luci-value-test] Temporary disable YUV_TO_RGB_U8_000

- infra/docker/jammy/Dockerfile
This commit adds sudo package installation.
Ubuntu 22.04 default image doesn't have sudo package.
> [infra/dockerfile] Install sudo in ubuntu 22.04

- res/TensorFlowLiteRecipes/FullyConnected_009/test.recipe
This commit adds FullyConnected_009 recipe.
The graph looks like below.
And, the recipe is introduced to fix the bug of _circle-opselector_.
As of now, the selected graph by _circle-opselector_ has a bug where the output shape is wrong.
Related: #10450 
> [res] Add FullyConnected_009 recipe

- compiler/luci/service/src/Nodes/CircleFullyConnected.cpp
This commit sets keep_num_dims attribute of CircleFullyConnected when cloning the node.
Related: #10450 
> [luci] Set keep_num_dims of CircleFullyConnected when cloning

- runtime/onert/core/src/exec/Executors.cc
- runtime/onert/core/src/exec/Executors.h
This commit seperates what `Executors` creates for type-aware quantization of nnpkg io.
---
For https://github.com/Samsung/ONE/issues/10002
Draft https://github.com/Samsung/ONE/pull/10329
> [onert] Seperate creating things for type-aware quant of nnpkg io

- infra/debian/compiler/rules
This commit revisits rules to change the destdir.
This change follows the CI change. At first, `destdir` should be given because default `destdir` - parent directory of working directory - cannot be accessed by docker container for permission issue. But for now, the restriction has been resolved so we don't have to override `destdir` anymore.
NOTE. This commit should be merged at the same time with the [CI change](https://github.sec.samsung.net/RS7-RuntimeNTools/nnfw_ci/pull/595).
Related: https://github.com/Samsung/ONE/issues/10425#issuecomment-1415340488
> [debian] Revisit rules

- infra/nnfw/cmake/packages/GTestConfig.cmake
This commit removes warning message by if-endif mismatching in GTest cmake.
> [infra/cmake] Remove GTest cmake warning

- .gitattributes
This commit updates .gitattributes file.
- Use binary macro instead of "-text"
- Add jar extension
- Sort binary extension
> [infra] Update binary gitattributes

- infra/nnfw/cmake/options/options_aarch64-tizen.cmake
- infra/nnfw/cmake/options/options_armv7hl-tizen.cmake
- infra/nnfw/cmake/options/options_armv7l-tizen.cmake
- packaging/nnfw.spec
This commit disables armcl (neon, cl) backend on tizen.
> [gbs] Disable armcl backend on tizen

- compiler/luci-pass-value-test/test.lst
This will add value test for forward_transpose_op with Net_Transpose_Abs_000.
> [luci/pass] Add value test for forward_transpose_op

- compiler/one-cmds/one-prepare-venv
This will freeze tensorflow_addons not to show TF version warnings.
> [one-cmds] Freeze tensorflow_addons version

- compiler/luci/pass/include/luci/Pass/QuantizeWithMinMaxPass.h
- compiler/luci/pass/src/QuantizeWithMinMaxPass.test.cpp
- compiler/luci/pass/src/QuantizedModelVerifier.test.cpp
This removes deprecated constructor of QuantizeWithMinMaxPass.
> [luci] Revisit QuantizeWithMinMaxPass

- infra/nnfw/command/prepare-model
- infra/scripts/tizen_xu4_test.sh
This commit introduces model download command on host machine.
It can be used to download models without build & install process.
---
> [infra/onert] Introduce model download dev command

- compiler/luci/pass/src/QuantizedModelVerifier.h
- compiler/luci/pass/src/QuantizedModelVerifier.test.cpp
This removes deprecated constructor of QuantizedModelVerifier.
> [luci] Revisit QuantizedModelVerifier

- compiler/one-cmds/onelib/export_constant.py
This commit introduces a script that exports CONSTANT value with given format.
Draft: #10478 
Related: https://github.com/Samsung/ONE/pull/10474#discussion_r1113763693
> [one-cmds] Introduce export_constant.py

- infra/debian/compiler/one-compiler.install
This commit installs export_constant.py script.
This PR should be merged after #10516.
Draft: https://github.com/Samsung/ONE/pull/10478
Related: https://github.com/Samsung/ONE/pull/10474#discussion_r1113763693
> [debian] Install export_constant.py

- compiler/one-cmds/one-optimize
- compiler/one-cmds/onelib/constant.py
- compiler/one-cmds/onelib/utils.py
This commit removes unnecessary O1 logics. They've become unnecessary for resolving below "Related" issue.
Draft: https://github.com/Samsung/ONE/pull/10478
Related: https://github.com/Samsung/ONE/pull/10474#discussion_r1113763693
> [one-cmds] Remove unnecessary O1 logic

- tests/scripts/command/prepare-model
- tests/scripts/onert-test
This commit changes DRIVER_PATH as test command common variable. 
By this, We can use prepare-model host command `./nnfw prepare-model`.
---
> [onert/test] Use common variable DRIVER_PATH on command

- tests/scripts/models/run_test.sh
This commit updates run_test.sh script.
- Update help message
- Remove unused function
- Simplify default test driver setting
---
> [onert/test] Revise run_test.sh

- compiler/luci/pass/include/luci/Pass/QuantizeWithMinMaxPass.h
- compiler/luci/pass/src/CircleQuantizer.cpp
- compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
- compiler/luci/pass/src/QuantizedModelVerifier.test.cpp
This uses vectoer type input/output_type in QuantizeWithMinMaxPass.
---
> [luci] Use vector type input/output_type in QuantizeWithMinMaxPass

- compiler/luci/pass/src/CircleQuantizer.cpp
- compiler/luci/pass/src/QuantizedModelVerifier.h
- compiler/luci/pass/src/QuantizedModelVerifier.test.cpp
This uses vector type input/output_type in QuantizedModelVerifier.
---
> [luci] Use vector type input/output_type in QuantizedModelVerifier

- compiler/luci/pass/src/QuantizedModelVerifier.test.cpp
- compiler/luci/pass/src/VerifyQuantizedNodeGranularity.h
- compiler/luci/pass/src/VerifyQuantizedNodeType.cpp
This allows quantization of MUL with indices (S32, S64).
---
Related to: #10534
> [luci] Support quantization of MUL with indices

- infra/packaging/preset/20221125
This commit adds _circle-opselector_ to preset 20221125.
Related: #10420 
> [preset] Add circle-opselector to preset 20221125

- infra/debian/compiler/one-compiler-dev.install
This commit installs _circle-opselector_ on one-compiler-dev package.
Related: #10420 
> [debian] Install circle-opselector

- compiler/one-cmds/tests/one-quantize_016.test
- compiler/one-cmds/tests/one-quantize_neg_021.test
- compiler/one-cmds/tests/onecc_045.cfg
- compiler/one-cmds/tests/onecc_045.test
- compiler/one-cmds/tests/onecc_neg_026.cfg
- compiler/one-cmds/tests/onecc_neg_026.test
This adds tests for multiple input/output_type in quantization.
---
> [one-cmds] Add quantiation tests for input/output_type

- compiler/one-cmds/tests/one-quantize_016.test
- compiler/one-cmds/tests/onecc_045.test
This commit skips the tests that use circledump.
Related: #10550 
> [one-cmds] Skip some tests for a while

- compiler/one-cmds/tests/one-import-onnx_002.test
This makes one-import-onnx_002.test create a unique output name.
---
Related to: https://github.com/Samsung/ONE/pull/10538#discussion_r1146956103
> [one-cmds] Rename output file

- compiler/circle-opselector/src/OpSelector.cpp
This commit fixes a misspelling of the error message.
ONE-DCO-1.0-Signed-off-by: Seungha Son linuxias@gmail.com
> [circle-opselector] Fix log misspelling

- compiler/one-cmds/tests/one-quantize_016.test
- compiler/one-cmds/tests/one-quantize_neg_021.test
- compiler/one-cmds/tests/onecc_045.test
- compiler/one-cmds/tests/onecc_neg_026.test
- compiler/one-cmds/tests/prepare_test_materials.sh
This makes tests use reshape_matmul.circle to avoid repetitive overhead.
---
Related to: https://github.com/Samsung/ONE/pull/10538#discussion_r1146956103
> [one-cmds] Use prepared file

- compiler/one-cmds/tests/prepare_test_materials.sh
This adds a missing option to create reshape_matmul.circle
---
Related to: https://github.com/Samsung/ONE/issues/10555#issuecomment-1484501455
> [one-cmds] Add missing option for reshape_matmul.circle

- compiler/nnc/backends/soft_backend/code_snippets/eigen.def
- Remove bad tailing escapes from macro definition that cause semantic errors.
> Remove bad escape

- compiler/vconone/CMakeLists.txt
This commit bumps up to 1.23.0.
> [vconone] Bump up to 1.23.0

- compiler/luci/logex/src/CircleNodeSummaryBuilder.cpp
This will revise log to show node shape in graph dump.
> [luci/logex] Show node shape with graph dump

- compiler/dio-hdf5/include/dio_hdf5/HDF5Importer.h
- compiler/dio-hdf5/src/HDF5Importer.cpp
- compiler/dio-hdf5/src/HDF5Importer.test.cpp
This adds new interface that checks buffer size when reading tensor data.
---
Related to: https://github.com/Samsung/ONE/pull/10567
> [dio-hdf5] Check buffer size in readTensor

- compiler/dio-hdf5/include/dio_hdf5/HDF5Importer.h
- compiler/dio-hdf5/src/HDF5Importer.cpp
- compiler/dio-hdf5/src/HDF5Importer.test.cpp
This removes deprecated readTensor and updates existing tests.
---
> [dio-hdf5] Remove deprecated readTensor

- compiler/circle-mpqsolver/src/bisection/BisectionSolver.cpp
- compiler/circle-mpqsolver/src/bisection/BisectionSolver.h
This commit introduce setVisqPath into BisectionSolver.
> [circle-mpqsolver] Introduce setVisqPath

- compiler/one-cmds/tests/one-quantize_neg_003.test
This fixes error message in one-quantize_neg_003.test
---
Related to: https://github.com/Samsung/ONE/issues/10555#issuecomment-1488184775
> [one-cmds] Fix error message

- compiler/circle-mpqsolver/src/bisection/VISQErrorApproximator.test.cpp
This commit removes mkstemp warning .
This one doesn't use '/tmp'.
Issue: #10580
> [circle-mpqsolver] Remove mkstemp warning

- compiler/circle-mpqsolver/src/bisection/BisectionSolver.cpp
This commit fixes too long name of the function.
See https://github.com/Samsung/ONE/pull/10432#discussion_r1109124953.
> [circle-mpqsolver] Fix too long name

- compiler/circle-mpqsolver/README.md
This commit fixes README.md due to introduction of 'visq_file'.
> [circle-mpqsolver] Fix README.md

- compiler/one-cmds/dummy-driver/CMakeLists.txt
- compiler/one-cmds/dummy-driver/src/dummyV2-compile.cpp
- compiler/one-cmds/one-codegen
- compiler/one-cmds/onecc
- compiler/one-cmds/onelib/CfgRunner.py
- compiler/one-cmds/tests/onecc_046.cfg
- compiler/one-cmds/tests/onecc_046.test
- compiler/one-cmds/tests/onecc_047.cfg
- compiler/one-cmds/tests/onecc_047.test
- compiler/one-cmds/tests/onecc_048.cfg
- compiler/one-cmds/tests/onecc_048.test
- compiler/one-cmds/tests/onecc_neg_027.cfg
- compiler/one-cmds/tests/onecc_neg_027.test
- compiler/one-cmds/tests/onecc_neg_028.cfg
- compiler/one-cmds/tests/onecc_neg_028.test
- compiler/one-cmds/tests/onecc_neg_029.cfg
- compiler/one-cmds/tests/onecc_neg_029.test
- compiler/one-cmds/tests/onecc_neg_030.cfg
- compiler/one-cmds/tests/onecc_neg_030.test
- compiler/one-cmds/tests/onecc_neg_031.test
- compiler/one-cmds/tests/onecc_neg_031.workflow.json
This commit introduces 'backends' option into one-codegen section.
Related: #10537 
> [one-cmds] Compile multiple backends with a single cfg file

- compiler/luci/pass/src/CircleOptimizer.cpp
This performs forwarding after removing redundant ops.
---
Previous ordering
`ForwardReshapeToUnaryOp -> ForwardTransposeOp -> RemoveRedundantReshape -> RemoveRedundantTranspose -> SubstituteTransposeToReshape`
This caused a problem in the below case.
Step 0 (original): Reshape -> Transpose -> Add
Step 1 (after ForwardTransposeOp): Reshape -> Add -> Transpose
Step 2 (after SubstituteTransposeToReshape): **Reshape -> Add -> Reshape**
If we reorder optimization passes as below (move Forward passes to the end),
`RemoveRedundantReshape -> RemoveRedundantTranspose -> SubstituteTransposeToReshape -> ForwardReshapeToUnaryOp -> ForwardTransposeOp`
Step 0 (original): Reshape -> Transpose -> Add
Step 1 (after …
> [luci] Reorder optimization passes

- compiler/luci/pass/src/ConvertToFakeQuantizedModelPass.cpp
This supports Sum Op in fake quantization.
---
Related to: https://github.com/Samsung/ONE/issues/10531
> [luci] Support Sum in fake quantization

- compiler/one-cmds/onecc
This commit verifies 'backend' option in onecc.
Related: https://github.com/Samsung/ONE/issues/10537#issuecomment-1498438409
> [one-cmds] Verify backend option in onecc

- runtime/libs/ndarray/src/ContiguousSpan.test.cpp
This commit removes meaningless test on ContiguousSpan.test.cpp.
> [onert/test] Fix meaningless test

- compiler/circle2circle-dredd-recipe-test/test.lst
This adds a regression test for ONNX_Mul_Mul.
---
Related to: https://github.com/Samsung/ONE/pull/10611#issuecomment-1500083991
> [circle2circle-dredd] Add REGRESS_ONNX_Mul_Mul test

- compiler/circle-opselector/src/OpSelector.cpp
This includes original output to the generated model.
> [circle-opselector] Include original output

- runtime/onert/core/src/exec/ExecutionEventEmitter.cc
- runtime/onert/core/src/exec/ExecutionEventEmitter.h
- runtime/onert/core/src/exec/IExecutionEventEmitter.h
- runtime/onert/core/src/exec/IExecutionEventListener.h
Let's introduce ExecutionListener/Emitter for recording minmax.
They are named as Listener/Emitter because ExecutorObserve{r,e} are in use.
Related: https://github.com/Samsung/ONE/issues/10604
2nd commit from Inner Repo's Draft PR
> [onert] Introduce ExecutionEvent{Emitter,Listener}

- runtime/onert/core/include/exec/MinMaxMap.h
- runtime/onert/core/include/util/MinMaxMap.h
It introduces MinMaxMap for recording maxmax.
It maps {subg_idx,op_idx} to {min,max}.
Related to #10604
> [onert] Introduce MinMaxMap

- compiler/circle-mpqsolver/src/bisection/BisectionSolver.cpp
This commit fixes bug in BisectionSolver.
> [circle-mpqsolver] Fix bug

- runtime/onert/core/src/exec/Executors.cc
This commit resolves using negative index on multi model package I/O index access.
---
Related issue: https://github.com/Samsung/ONE/issues/10621#issuecomment-1504395410
> [onert] Fix negative index bug

- compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
This inserts Quantize Op in the right way.
> [luci] Fix Quantize Op insertion in QuantizeWithMinMaxPass

- tests/nnfw_api/src/one_op_tests/Split.test.cc
It adds negative test case with negative numSplit for Split Operator.
Related: #10616
```
[ RUN      ] GenModelTest.neg_OneOp_SplitNegatveSplitNum
Error during model loading : OperationValidator failed at line 494
[       OK ] GenModelTest.neg_OneOp_SplitNegatveSplitNum (0 ms)
```
> [onert] Add negative TC for Split

- tests/nnfw_api/src/one_op_tests/StridedSlice.test.cc
Related: #10616
```
[ RUN      ] GenModelTest.neg_OneOp_StridedSlice_DifferentType
Error during model loading : OperationValidator failed at line 524
[       OK ] GenModelTest.neg_OneOp_StridedSlice_DifferentType (0 ms)
```
> [onert] Add negative TC for StridedSlice

- tests/nnfw_api/src/one_op_tests/Reverse.test.cc
Related: #10616
```
[ RUN      ] GenModelTest.neg_OneOp_ReverseV2_3D_DifferentType
Error during model loading : OperationValidator failed at line 435
[       OK ] GenModelTest.neg_OneOp_ReverseV2_3D_DifferentType (0 ms)
```
> [onert] Add negative TC for Reverse

- tests/nnfw_api/src/one_op_tests/BatchToSpaceND.test.cc
Related: #10616 
```
[ RUN      ] GenModelTest.neg_OneOp_BatchToSpaceND_DifferentType
Error during model loading : OperationValidator failed at line 138
[       OK ] GenModelTest.neg_OneOp_BatchToSpaceND_DifferentType (0 ms)
```
> [onert] Add negative TC for BatchToSpaceND

- runtime/onert/core/CMakeLists.txt
- runtime/onert/core/src/exec/MinMaxRecorder.cc
- runtime/onert/core/src/exec/MinMaxRecorder.h
It introduces MinMaxRecorder
It will not be built for Tizen and Android (not hdf5-ready).
Related: https://github.com/Samsung/ONE/issues/10604
@hseok-oh This PR contains the changes you've suggested in internal repo.
`MinMaxRecorder` inherits `ExecutionObserver`.
> [onert] Introduce exec/MinMaxRecorder

- runtime/onert/core/CMakeLists.txt
- runtime/onert/core/src/compiler/ExecutorFactory.cc
- runtime/onert/core/src/exec/ExecutorBase.h
It adds MinMaxRecorder as ExecutionObserver.
Related: #10604
> [onert] Add MinMaxRecorder Observer

- docs/conf.py
- packaging/nnfw.spec
- runtime/contrib/android/api/build.gradle
- runtime/onert/api/include/nnfw_version.h
Use version 1.22.1 on runtime.
---
Patch to release/1.22.0 branch
> [onert] Update version to 1.22.1

- compiler/circle-inspect/CMakeLists.txt
- compiler/circle-inspect/requires.cmake
> [circle-inspect] Upgrade circle schema to 0.5

- compiler/circle-tensordump/CMakeLists.txt
- compiler/circle-tensordump/requires.cmake
> [circle-tensordump] Upgrade circle schema to 0.5

- compiler/circledump/CMakeLists.txt
- compiler/circledump/README.md
- compiler/circledump/requires.cmake
> [circledump] Upgrade circle schema to 0.5

- compiler/pics/CMakeLists.txt
> [pics] Upgrade circle schema to 0.5

- compiler/circle-operator/CMakeLists.txt
- compiler/circle-operator/requires.cmake
> [circle-operator] Upgrade circle schema to 0.5

- compiler/pics/requires.cmake
This adds requires cmake file.
---
Related to: https://github.com/Samsung/ONE/pull/10672#issuecomment-1512516362
> [pics] Add requires.cmake file

- .ahub/tcchecker-tca/config.yaml
This uses mio-circle05 in tcchecker.
---
> [ahub] Use mio-circle05 in tcchecker

- compiler/luci-interpreter/src/kernels/Reshape.cpp
- compiler/luci-interpreter/src/kernels/Reshape.test.cpp
This will enable S64 dtype from shape.
> [luci-interpreter] Enable S64 shape for Reshape

- compiler/luci/import/src/Nodes/CircleReshape.cpp
This will enable to support S65 for Resape shape input.
> [luci/import] Reshape S64 for Reshape shape

- compiler/circlechef/core/CMakeLists.txt
This makes circlechef_core use mio_circle05
---
Related to: https://github.com/Samsung/ONE/issues/10680
> [circlechef] Use mio_circle05

- onert-micro/helpers/GenerateKernelsListHelper.cpp
This pr adds missing kernels in GenerateKernelsListHelper.
related to issue: #10651
> [onert-micro] Add missing kernels in GenerateKernelsListHelper

- compiler/circle-mpqsolver/README.md
- compiler/circle-mpqsolver/src/CircleMPQSolver.cpp
This commit introduces 'save_intermediate parameter' and updates readme accrodingly.
> [circle-mpqsolver] Introduce 'save_intermediate'

- compiler/circle-mpqsolver/src/core/Dumper.cpp
- compiler/circle-mpqsolver/src/core/Dumper.h
This commit implements dumper for saving intermediate results.
> [circle-mpqsolver] Implement Dumper

- packaging/nnfw.spec
This commit disables npud build on gbs build as default.
> [onert] Change default setting for npud build on gbs build

- compiler/circle-mpqsolver/src/core/SolverHooks.cpp
- compiler/circle-mpqsolver/src/core/SolverHooks.h
This commit introduces SolverHooks.
> [circle-mpqsolver] Introduce SolverHooks

- compiler/circle-mpqsolver/src/core/DumpingHooks.cpp
- compiler/circle-mpqsolver/src/core/DumpingHooks.h
This commit implements DumpingHooks for saving intermediate results.
> [circle-mpqsolver] Implement DumpingHooks

- compiler/tfldump/src/OpPrinter.cpp
This supports GeLU Op printer.
---
> [tfldump] Support GeLU Op

- compiler/luci/partition/include/luci/ConnectNode.h
- compiler/luci/partition/src/Nodes/CircleGelu.cpp
- compiler/luci/partition/src/Nodes/CircleGelu.test.cpp
This supports Gelu in luci partition.
---
> [luci/partition] Support Gelu

- compiler/circledump/src/OpPrinter.cpp
This supports Gelu in circledump.
---
> [circledump] Support Gelu Op

- runtime/onert/frontend/base_loader/include/base_loader.h
Currently, for sparse tensor type, it uses uint16 regardless of the type of array_segments_type and array_indices_type. Thus, it would be safe to throw exception for uint32 type.
> [onert] Throw exception for uint32 type of array_segment and array_index

- compiler/luci/pass/include/luci/CircleOptimizer.h
- compiler/luci/pass/src/CircleOptimizer.cpp
This enables FuseGelu algorithm in luci.
---
> [luci] Enable FuseGelu algorithm

- compiler/circle2circle/src/Circle2Circle.cpp
This adds fuse_gelu optimization option.
---
> [circle2circle] Add fuse_gelu option

- compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
This supports mixed-precision quantization of Gelu.
---
> [luci] Support mixed-precision quantization of Gelu

- compiler/circle-mpqsolver/src/MPQSolver.cpp
- compiler/circle-mpqsolver/src/MPQSolver.h
This commit implements 'set_save_intermediate' for the AMPQ task.
> [circle-mpqsolver] Implement 'set_save_intermediate'

- compiler/luci/service/src/CircleShapeInferenceRule.cpp
This will fix analysis warnings with types.
> [luci/svc] Fix analysis warnings

- compiler/circle-mpqsolver/src/CircleMPQSolver.cpp
This commit implements 'save_intermediate' option at entry level.
> [circle-mpqsolver] Implement 'save_intermediate' option

- compiler/onecc-docker/docker/Dockerfile
This commit changes the release name of one-compiler in docker file. 
The name will be changed to match the url of one-compiler release name asset.
ONE-DCO-1.0.-Signed-off-by: Seunghui Lee <shsh1004.lee@samsung.com>
Related Issue : [#10773]
> [onecc-docker] Change the release name of one-compiler in docker file

- compiler/vconone/CMakeLists.txt
This commit bumps up to 1.24.0.
Related: #10802
> [vconone] Bump up to 1.24.0

- runtime/onert/backend/cpu/CMakeLists.txt
This commit makes cpu backend position independent shared library so that other backends use cpu backend.
> [onert] Make cpu backend position independent shared library.

- runtime/onert/core/include/backend/basic/StaticTensorManager.h
- runtime/onert/core/include/backend/basic/TensorBuilder.h
- runtime/onert/core/src/backend/basic/StaticTensorManager.cc
- runtime/onert/core/src/backend/basic/TensorBuilder.cc
This commit make basic::TensorBuilder choose memory planner.
> [onert] Choose memory planner

- compiler/onecc-docker/docker/Dockerfile
This commit uses `--no-check-certificate` option when it downloads one-compiler package from GitHub Release page.
> [onecc-docker] Add no-check-certificate option

- runtime/onert/backend/train/KernelGenerator.cc
- runtime/onert/backend/train/KernelGenerator.h
- runtime/onert/backend/train/ops/ConvolutionLayer.cc
- runtime/onert/backend/train/ops/ConvolutionLayer.h
This commit implements convolution layer in train backend. The forward pass calls cpu convolution function.
Related issue: #10796
> [onert] Implement convolution layer in train backend

- compiler/one-cmds/dummy-driver/CMakeLists.txt
- compiler/one-cmds/dummy-driver/src/dummy-onnx-ext.cpp
This will introduce dummy-onnx-ext for testing one-import-onnx extension.
> [one-cmds] Introduce dummy-onnx-ext

- .ahub/tcchecker-tca/config.yaml
- add section for onert-micro
- Let's use suffix _P for positive test and _NEG for negative test
- Note that many test files are excluded from testfiles. DO NOT forget to add them after enabling test.
> tca config.yaml for onert-micro

- infra/scripts/docker_build_nncc.sh
This commit revisits docker_build_nncc script to use one-version.
Related: #10853 
> [infra] Use one-version

- compiler/one-cmds/dummy-driver/CMakeLists.txt
- compiler/one-cmds/dummy-driver/src/dummyV2-profile.cpp
- compiler/one-cmds/one-profile
- compiler/one-cmds/onecc
- compiler/one-cmds/onelib/CfgRunner.py
- compiler/one-cmds/tests/onecc_049.cfg
- compiler/one-cmds/tests/onecc_049.test
- compiler/one-cmds/tests/onecc_050.cfg
- compiler/one-cmds/tests/onecc_050.test
- compiler/one-cmds/tests/onecc_051.cfg
- compiler/one-cmds/tests/onecc_051.test
- compiler/one-cmds/tests/onecc_052.cfg
- compiler/one-cmds/tests/onecc_052.test
- compiler/one-cmds/tests/onecc_053.cfg
- compiler/one-cmds/tests/onecc_053.test
- compiler/one-cmds/tests/onecc_neg_032.cfg
- compiler/one-cmds/tests/onecc_neg_032.test
- compiler/one-cmds/tests/onecc_neg_033.cfg
- compiler/one-cmds/tests/onecc_neg_033.test
- compiler/one-cmds/tests/onecc_neg_034.cfg
- compiler/one-cmds/tests/onecc_neg_034.test
- compiler/one-cmds/tests/onecc_neg_035.cfg
- compiler/one-cmds/tests/onecc_neg_035.test
- compiler/one-cmds/tests/onecc_neg_036.test
- compiler/one-cmds/tests/onecc_neg_036.workflow.json
This commit supports multiple backends with a single cfg file on profiling.
Related: #10848 
> [one-cmds] Profile multiple backends with a single cfg file

- runtime/onert/core/include/ir/Operation.h
- runtime/onert/core/include/ir/train/ITrainableOperation.h
- runtime/onert/core/include/ir/train/TrainableOperations.h
This commit introduces ITrainableOperation that can contain training-related operation information.
- Introduce IOperation
- Introduce ITrainableOperation
- Introduce TrainableOperations
> [onert] Introduce ITrainableOperation

- runtime/onert/backend/train/KernelGenerator.cc
- runtime/onert/backend/train/KernelGenerator.h
- runtime/onert/backend/train/ops/PoolLayer.cc
- runtime/onert/backend/train/ops/PoolLayer.h
This commit implements max pool layer in train backend. The forward pass calls cpu pool layer function.
Related issue: #10796
> [onert] Implement max pool layer in train backend

- runtime/onert/core/include/compiler/train/TrainingInfo.h
This commit introduces TrainingInfo that contains training information to be used at the compilation phase.
> [onert] Introduce TrainingInfo

- compiler/one-cmds/one-import-onnx
This will fix input model path for calling one-import-onnx-ext.
> [one-cmds] Fix input path for one-import-onnx-ext

- compiler/luci/pass/src/QuantizeActivation.cpp
This will revise runtime_error message to show node name for better debugging.
> [luci/pass] Show node name for unknown node

- infra/docker/focal/Dockerfile
- This is for enable build of onert-micro on focal image
> Install gcc-arm-none-eabi into focal image

- runtime/onert/core/include/ir/train/ITrainableOperation.h
This commit revises ITrainableOperation
- Remove parameters from clone()
- Remove override methods
- Remove operations methods
> [onert] Revise ITrainableOperation

- runtime/onert/core/src/compiler/train/TrainingCompiler.cc
- runtime/onert/core/src/compiler/train/TrainingCompiler.h
This commit introduces TrainingCompiler that compiles a single model to create trainable artifacts.
> [onert] Introduce TrainingCompiler

- runtime/onert/core/include/backend/IConfig.h
- runtime/onert/core/include/backend/basic/DynamicTensorManager.h
- runtime/onert/core/include/compiler/CodeMap.h
- runtime/onert/core/include/ir/IOperation.h
- runtime/onert/core/include/ir/Operation.h
- runtime/onert/core/include/ir/Operations.h
- runtime/onert/core/include/ir/train/ITrainableOperation.h
- runtime/onert/core/src/backend/BackendContext.cc
- runtime/onert/core/src/compiler/pass/OperationPass.cc
- runtime/onert/core/src/dumper/dot/OperationNode.h
- runtime/onert/core/src/exec/ExecutionObservers.h
- runtime/onert/core/src/exec/FunctionSequence.cc
This commit separates IOperation from the Operation header.
> [onert] Separate IOperation from the Operation header

- runtime/onert/api/src/nnfw_api_internal.cc
- runtime/onert/core/include/ir/Graph.h
- runtime/onert/core/include/ir/Model.h
- runtime/onert/core/src/compiler/Compiler.cc
- runtime/onert/core/src/compiler/ExecutorFactory.cc
- runtime/onert/core/src/compiler/ExecutorFactory.h
- runtime/onert/core/src/compiler/MultiModelCompiler.cc
This commit moves custom kernel builders from Graph into Model.
> [onert] Move custom kernel builders into Model

- runtime/onert/core/src/compiler/train/pass/LossInsertionPass.cc
- runtime/onert/core/src/compiler/train/pass/LossInsertionPass.h
This commit introduces LossInsertionPass that can insert Loss operation into a subgraph.
> [onert] Introduce LossInsertionPass

- runtime/onert/core/include/backend/train/KernelGeneratorBase.h
- runtime/onert/core/src/backend/builtin/train/KernelGenerator.cc
- runtime/onert/core/src/backend/builtin/train/KernelGenerator.h
This commit introduces `builtin` backend's KernelGenerator for training.
> [onert] Introduce `builtin` backend's KernelGenerator for training

- runtime/onert/core/include/ir/train/operation/UntrainableOperation.h
This commit introduces UntrainableOperation that cannot be trainable.
> [onert] Introduce UntrainableOperation

- runtime/onert/core/include/ir/train/Operations.Include.h
- runtime/onert/core/include/ir/train/Operations.lst
- runtime/onert/core/include/ir/train/operation/ElementwiseActivation.h
- runtime/onert/core/src/ir/train/operation/ElementwiseActivation.cc
This commit introduces ElementwiseActivation operation for training.
> [onert] Introduce ElementwiseActivation operation for training

- runtime/onert/core/include/ir/operation/BinaryArithmetic.h
- runtime/onert/core/src/compiler/train/UntrainableOperationConverter.cc
- runtime/onert/core/src/compiler/train/UntrainableOperationConverter.h
This commit introduces UntrainableOperationConverter that converts operations to UntrainableOperation.
> [onert] Introduce UntrainableOperationConverter

- runtime/onert/core/src/backend/builtin/train/KernelGenerator.cc
- runtime/onert/core/src/backend/builtin/train/KernelGenerator.h
This commit make `builtin`'s KernelGenerator can access tensors for gradient.
> [onert] Access gradient tensors in builtin KernelGenerator

- runtime/onert/core/src/exec/train/TrainableExecutor.cc
- runtime/onert/core/src/exec/train/TrainableExecutor.h
This commit introduces TrainableExecutor that can run backwards.
> [onert] Introduce TrainableExecutor

- runtime/onert/core/src/compiler/train/TrainableOperationConverter.cc
- runtime/onert/core/src/compiler/train/TrainableOperationConverter.h
This commit introduces TrainableOperationConverter that can convert operations to trainable operations.
> [onert] Introduce TrainableOperationConverter

- runtime/onert/core/src/exec/train/TrainableExecutors.cc
- runtime/onert/core/src/exec/train/TrainableExecutors.h
This commit introduces TrainableExecutors to support training.
> [onert] Introduce TrainableExecutors

- runtime/onert/core/src/compiler/train/TrainingCompiler.cc
- runtime/onert/core/src/compiler/train/TrainingCompiler.h
This commit removes an unnecessary member from TrainingCompiler.
> [onert] Remove an unnecessary member from TrainingCompiler

- runtime/onert/core/src/dumper/dot/DotDumper.cc
- runtime/onert/core/src/dumper/dot/DotDumper.h
This commit make DotDumper support for LoweredTrainableGraph.
> [onert] Support DotDumper for LoweredTrainableGraph

- compiler/visq-unittest/test/testQErrorComputer.py
- compiler/visq/visq
- compiler/visq/visqlib/DumpFP32FM.py
- compiler/visq/visqlib/DumpFakeQuantFM.py
- compiler/visq/visqlib/QErrorComputer.py
This uses tensor ID as a filename to avoid too long filename error.
---
Related to: https://github.com/Samsung/ONE/issues/10941
> [visq] Use tensor ID as a filename

- compiler/visq-unittest/CMakeLists.txt
This turns off visq-unittest during landing #10950.
---
Related to: #10949
Draft PR: https://github.com/Samsung/ONE/pull/10950
> [visq-unittest] Turn off for a while

- runtime/onert/core/include/ir/train/TrainableGraph.h
- runtime/onert/core/src/ir/train/TrainableGraph.cc
This commit fixes missing override methods in TrainableGraph.
> [onert] Fix missing override methods in TrainableGraph

- compiler/visq-unittest/CMakeLists.txt
This enables visq-unittest after landing #10950.
---
Related to: https://github.com/Samsung/ONE/issues/10949
Draft PR: https://github.com/Samsung/ONE/pull/10950
> [visq-unittest] Enable tests

- compiler/one-cmds/tests/preprocess_images.py
This handles deprecation of PIL.Image.ANTIALIAS attribute.
---
Related to: https://github.com/Samsung/ONE/issues/10966
> [one-cmds] Handle PIL.Image.ANTIALIAS deprecation

- tests/tools/onert_train/src/onert_train.cc
This commit runs train_prepare instead of prepare. It will creates TrainingCompiler and TrainableExecutors.
> [tools/onert_train] Run train_prepare with train information

- runtime/onert/core/include/ir/train/Operations.lst
- runtime/onert/core/include/ir/train/operation/Conv2D.h
- runtime/onert/core/src/ir/train/operation/Conv2D.cc
This commit introduces Conv2D operation for training.
> [onert] Introduce Conv2D train operation

- runtime/onert/backend/train/ops/ConvolutionLayer.cc
- runtime/onert/backend/train/ops/ConvolutionLayer.h
- runtime/onert/backend/train/ops/PoolLayer.cc
- runtime/onert/backend/train/ops/PoolLayer.h
- runtime/onert/core/include/exec/ITrainableFunction.h
- runtime/onert/core/src/backend/builtin/train/kernel/PermuteLayer.cc
- runtime/onert/core/src/backend/builtin/train/kernel/PermuteLayer.h
This commit adds backward function to ITrainableFunction class.
TrainableExecutors will invoke backward function when it trains model.
> [onert] Add backward to ITrainableFunction

- runtime/libs/benchmark/include/benchmark/CsvWriter.h
- runtime/libs/benchmark/include/benchmark/Phase.h
- runtime/onert/core/src/ir/LayoutSet.h
- runtime/service/npud/core/Backend.h
This commit adds including cstdint header to resolve build fail on gcc 13.
---
Draft: #10952
> [onert] Include header cstdint

- compiler/luci/service/include/luci/Service/Validate.h
- compiler/luci/service/src/Validate.cpp
This introduces validate function for shape.
---
Related to: https://github.com/Samsung/ONE/issues/8739
Draft PR: https://github.com/Samsung/ONE/pull/10974
> [luci] Introduce validate_shape

- compiler/luci/pass/include/luci/DynamicBatchToSingleBatch.h
- compiler/luci/pass/src/DynamicBatchToSingleBatch.cpp
This implements dynamic_batch_to_single_batch for luci::Module.
---
Related to: https://github.com/Samsung/ONE/issues/8739
Draft PR: https://github.com/Samsung/ONE/pull/10974
> [luci] Support dynamic_batch_to_single_batch

- compiler/one-cmds/onelib/constant.py
This PR adds dynamic_batch_to_single_batch option.
---
Related to: https://github.com/Samsung/ONE/issues/8739
Draft PR: https://github.com/Samsung/ONE/pull/10974
> [one-cmds] Add dynamic_batch_to_single_batch option

- runtime/onert/core/include/compiler/train/TrainingInfo.h
- runtime/onert/core/src/compiler/CompilerFactory.cc
This commit removes the has_info variable from TrainingInfo.
The default value of trainnig_info in CompilerFactory.create() is nullptr.
Therefore, if create() is not called with TrainingInfo, it is the same with shouldTrain() == false.
Conversely, if create() is called with TrainingInfo, it is the same with shouldTrain() == true.
> [onert] Remove _has_info variable from TrainingInfo

- runtime/onert/core/src/compiler/train/LoweredTrainableGraph.cc
This commit applies converting Permute operation to trainable Permute operation.
> [onert] Convert Permute op to trainable operation

- runtime/onert/core/src/compiler/train/LoweredTrainableGraph.cc
- runtime/onert/core/src/compiler/train/TrainingCompiler.cc
- runtime/onert/core/src/compiler/train/UntrainableOperationConverter.cc
- runtime/onert/core/src/compiler/train/UntrainableOperationConverter.h
This commit makes TrainablerOperationConvert convert op instead of index.
> [onert] Change parameter of TrainableOperationConverter

- runtime/onert/backend/trix/DevContext.cc
This commit initializes model_id variable in DevContext.cc. 
It can be returned without initialization, so gcc 13 warns this.
> [onert] Initialize variable model_id

- runtime/onert/core/include/compiler/ILoweredGraph.h
- runtime/onert/core/include/compiler/LoweredGraph.h
- runtime/onert/core/include/compiler/StaticShapeInferer.h
- runtime/onert/core/include/compiler/train/LoweredTrainableGraph.h
- runtime/onert/core/src/compiler/Compiler.cc
- runtime/onert/core/src/compiler/CompilerHelpers.h
- runtime/onert/core/src/compiler/MultiModelCompiler.cc
- runtime/onert/core/src/compiler/StaticShapeInferer.cc
- runtime/onert/core/src/compiler/train/TrainingCompiler.cc
This commit allows TrainingCompiler to infer shapes based on batch size.
> [onert] Infer shapes in TrainingCompiler

- runtime/onert/backend/train/Tensor.h
This commit makes tensors in train backend not allow dynamic shape.
> [onert] Disallow dynamic shape of tensors in train backend.

- runtime/onert/core/src/exec/train/TrainableExecutor.cc
- runtime/onert/core/src/exec/train/TrainableExecutor.h
This commit implements forward and backward functions in TrainableExecutor.
TrainableExecutors will use both functions to implement inference and train
function.
~~waiting #10972 #10973~~
> [onert] Implement forward and backward function in TrainableExecutor

- runtime/onert/core/src/compiler/train/TrainableOperationConverter.cc
- runtime/onert/core/src/compiler/train/TrainableOperationConverter.h
This commit converts Pool2D Op to trainable.
Related comment: https://github.com/Samsung/ONE/pull/11003#issuecomment-1623588185
> [onert] Convert Pool2D Op to trainable

- runtime/onert/core/src/compiler/train/StaticGradientShapeInferer.cc
- runtime/onert/core/src/compiler/train/StaticGradientShapeInferer.h
- runtime/onert/core/src/compiler/train/TrainingCompiler.cc
This commit introduces StaticGradientShapeInfer that infer shapes of tensors for gradient.
> [onert] Introduce StaticGradientShapeInfer

- runtime/onert/core/include/ir/train/Operations.Include.h
- runtime/onert/core/include/ir/train/Operations.lst
- runtime/onert/core/include/ir/train/operation/FullyConnected.h
- runtime/onert/core/src/compiler/train/TrainableOperationConverter.cc
- runtime/onert/core/src/compiler/train/TrainableOperationConverter.h
- runtime/onert/core/src/ir/train/operation/FullyConnected.cc
This commit introduces FullyConnectd train operation. And FullyConnected Op is converted to trainable.
~~waiting #11018~~
> [onert] Introduce FullyConnected train operation

- runtime/onert/backend/train/TensorRegistry.h
This commit replaces constant Tensor with TrainableTensor in `train` backend.
> [onert] Replace Tensor with TrainableTensor

- infra/nnfw/cmake/buildtool/config/config_linux.cmake
This commit adds compiler flag to ignore "array-bound" and "stringop-overflow" warning message on GCC version > 12.
---
Draft: #10952
> [onert] Ignore GCC warning

- tests/tools/onert_train/src/args.cc
- tests/tools/onert_train/src/args.h
This commit adds input and expected datafile arguments and data_length. The onert_train will train a given model using input and expected datafile.
> [tools/onert_train] Add input and expected datafile arguments

- compiler/one-cmds/dummy-driver/src/dummyV2-compile.cpp
- compiler/one-cmds/one-codegen
- compiler/one-cmds/tests/one-codegen_neg_002.test
- compiler/one-cmds/tests/one-codegen_neg_003.test
- compiler/one-cmds/tests/one-codegen_neg_004.cfg
- compiler/one-cmds/tests/one-codegen_neg_004.test
- compiler/one-cmds/tests/one-codegen_neg_005.test
- compiler/one-cmds/tests/onecc_054.cfg
- compiler/one-cmds/tests/onecc_054.test
- compiler/one-cmds/tests/onecc_055.cfg
- compiler/one-cmds/tests/onecc_055.test
This commit supports overwriting commands over given configuration file on one-codegen.
Related: #10994 
> [one-cmds] Overwriting commands over given configuration on one-codegen

- compiler/one-cmds/dummy-driver/CMakeLists.txt
- compiler/one-cmds/dummy-driver/src/dummyV3-profile.cpp
- compiler/one-cmds/one-profile
- compiler/one-cmds/tests/one-profile_neg_002.test
- compiler/one-cmds/tests/one-profile_neg_003.test
- compiler/one-cmds/tests/one-profile_neg_004.cfg
- compiler/one-cmds/tests/one-profile_neg_004.test
- compiler/one-cmds/tests/one-profile_neg_005.test
- compiler/one-cmds/tests/onecc_056.cfg
- compiler/one-cmds/tests/onecc_056.test
- compiler/one-cmds/tests/onecc_057.cfg
- compiler/one-cmds/tests/onecc_057.test
This commit supports overwriting commands over given configuration file on one-profile.
Related: #10994 
> [one-cmds] Overwriting commands over given configuration on one-profile

- compiler/common-artifacts/CMakeLists.txt
- Identifies aarch64 and configures it to use the appropriate python package.
for: #11036 
draft: #10564
> Add aarch64 support to common-artifacts build

- compiler/luci-interpreter/pal/linux/pal.cmake
- introduce BUILD_ARM64_NEON option support
for: #11036 
draft: #10564
> Add aarch64 support to luci-interpreter's kernel build

- runtime/onert/backend/train/KernelGenerator.cc
This commit adds train kernels to the TrainableFnSequence.
> [onert] Add train kernels to the TrainableFnSequence

- runtime/onert/core/include/exec/Execution.h
- runtime/onert/core/src/exec/Execution.cc
This commit introduces train function in Execution. This function will be called from nnfw_api_internal apis.
> [onert] Introduce train function in Execution

- infra/command/build-docker-image
- infra/docker/bionic/Dockerfile.aarch64
- infra/docker/focal/Dockerfile.aarch64
- infra/docker/jammy/Dockerfile.aarch64
- Add Dockerfile.aarch64 for bionic, focal, and jammy
- Modify build-docker-image command to support aarch64
for: #11036
draft: #10564
> Add docker build infra support for aarch64

- compiler/common-artifacts/CMakeLists.txt
This will fix Jammy requirements list for AArch64.
> [common-artifacts] Fix requirements list for AArch64

- compiler/luci/pass/src/FuseGeluPass.test.cpp
This PR refactors FuseGeluPass.test to add more patterns at future.
> [luci/pass] Change names in FuseGeluPass.test

- compiler/one-cmds/CMakeLists.txt
This will fix ONE_UBUNTU_CODENAME_JAMMY type in CMakeLists.txt
> [one-cmds] Fix typo in CMakeLists.txt

- runtime/onert/core/include/ir/train/TrainableGraph.h
- runtime/onert/core/src/compiler/train/StaticDerivativeShapeInferer.cc
- runtime/onert/core/src/compiler/train/StaticDerivativeShapeInferer.h
- runtime/onert/core/src/ir/train/TrainableGraph.cc
This commit allows to append derivative information in TrainableGraph.
- Introduce derivative operands into TrainableGraph
- Add setting shape of derivative in ShapeDerivativeShapeInferer
> [onert] Add derivative info to TrainableGraph

- tests/tools/onert_train/test/rawdataloader.test.cc
This commit supports multiple input and expected output in rawdataloader test. This change connets sample data by input as much as data length to temporary file.
Draft : #11027
> [tools/onert_train] Support multiple input in rawdataloader test

- compiler/luci/pass/src/FuseGeluPass.cpp
This PR renames GeluPattern to GeluPattern1.
> [luci/pass] Rename GeluPattern to GeluPattern1

- runtime/onert/core/src/compiler/CompilerFactory.cc
- runtime/onert/core/src/compiler/train/TrainingCompiler.cc
- runtime/onert/core/src/compiler/train/TrainingCompiler.h
This commit uses const & keyword for saving training info in TrainingCompiler.
> [onert] Use const & for saving training info in TrainingCompiler

- runtime/onert/core/src/backend/basic/Tensor.cc
This commit adds assertion that checks dynamic memory manager is not nullptr.
> [onert] Add assertion that checks nullptr

- runtime/onert/backend/train/Tensor.h
- runtime/onert/core/include/backend/basic/train/TrainableTensor.h
- runtime/onert/core/include/backend/train/ITrainableTensor.h
- runtime/onert/core/src/backend/basic/train/TrainableTensor.cc
This commit refines TrainableTensor.
- Change ITrainableTensor to inherit IPortableTensor
- Introduce TrainableTensor into basic
- Replace train backend's TrainableTensor with TrainableTensor of basic
> [onert] Refine TrainableTensor

- runtime/onert/core/src/backend/builtin/train/Tensor.h
- runtime/onert/core/src/backend/builtin/train/TensorRegistry.h
This commit introduces builtin TensorRegistry for training.
- Introduce TrainableTensor into builtin backend
- Introduce TensorRegistry into builtin backend
> [onert] Introduce builtin TensorRegistry for training

- runtime/onert/api/src/nnfw_api_internal.cc
This commit changes the batch_size of input tensor in train_prepare
nnfw internal api. Other operation will be changed the tensor info
through Static shape inference function.
> [onert] Change the batch_size of input tensor in train_prepare

- runtime/onert/core/src/compiler/train/pass/LossInsertionPass.h
- runtime/onert/core/src/compiler/train/pass/Pass.h
This commit fixes wrong TrainingInfo namespace in Pass class.
The TrainingInfo class has been moved from ir/train to compiler/train namespace.
> [onert] Fix wrong TrainingInfo namespace in pass

- compiler/luci/pass/src/FuseGeluPass.cpp
This PR Revise GeluPattern1 to inherit from GeluPatternBase.
Note: this PR contains changes from #11060 and should be rebased after #11060 will be merged
> [luci/pass] Revise GeluPattern1 to inherit from GeluPatternBase

- compiler/circle-opselector/src/OpSelector.cpp
This commit uses a reference not to copy string.
This makes a static analysis tool happy.
> [circle-opselector] No string copy from auto type deduction

- compiler/luci/pass/src/CircleQuantizer.cpp
This commit uses a reference not to copy string.
This makes a static analysis tool happy.
> [luci] No string copy from auto type deduction

- compiler/onecc-docker/onecc-docker
This commit requests github several latest version information and filter out versions like onert-micro-0.1.0
which doesn't include onecc package.
ONE-DCO-1.0.-Signed-off-by: Dayoung Lee <dayoung.lee@samsung.com>
> [onecc-docker] Use onecc version with a certain format

- infra/nncc/cmake/options/options_aarch64-linux.cmake
- Remove BUILD_ARM64_NEON option for aarch64.
> [infra/nncc] Remove unnecessary cmake option

- runtime/onert/core/src/backend/builtin/Backend.h
- runtime/onert/core/src/backend/builtin/TensorBuilder.cc
- runtime/onert/core/src/backend/builtin/TensorBuilder.h
- runtime/onert/core/src/backend/builtin/train/KernelGenerator.cc
- runtime/onert/core/src/backend/builtin/train/KernelGenerator.h
This commit changes TensorRegistry in builtin backend.
- Remove TensorBuilders for training from builtin backend
- Replace TensorRegistry with train::TensorRegistry
> [onert] Change TensorRegistry in builtin backend

- tests/tools/onert_train/src/args.cc
- tests/tools/onert_train/src/args.h
This commit changes loss function argument type from string to int.
draft: #11035
> [tools/onert_train] Change Loss function type

- compiler/oops/requires.cmake
It introduces requires.cmake because "oops" links "pepper-str".
> [oops] Add requires.cmake

- compiler/vconone/CMakeLists.txt
This commit bumps up to 1.25.0.
Related: #11085 
> [vconone] Bump up to 1.25.0

- runtime/onert/core/src/compiler/ExecutorFactory.cc
This commit allows train backend to allocate memory for outputs of whole graph.
> [onert] Allow train backend to allocate memory for outputs

- runtime/onert/core/src/compiler/train/LoweredTrainableGraph.cc
- runtime/onert/core/src/compiler/train/pass/PermutationInsertionPass.cc
- runtime/onert/core/src/compiler/train/pass/PermutationInsertionPass.h
This commit makes Permute operation not to be inserted for outputs of trainable graph.
- Introduce PermutationInsertionPass for training and apply it
> [onert] Remove Permute op from outputs of trainable graph

- runtime/onert/backend/train/Backend.h
- runtime/onert/backend/train/BackendContext.cc
- runtime/onert/backend/train/BackendContext.h
- runtime/onert/backend/train/KernelGenerator.cc
- runtime/onert/backend/train/KernelGenerator.h
- runtime/onert/backend/train/TensorBuilder.cc
- runtime/onert/backend/train/TensorBuilder.h
- runtime/onert/core/include/backend/train/TrainableBackendContext.h
- runtime/onert/core/src/backend/builtin/train/BackendContext.cc
- runtime/onert/core/src/backend/builtin/train/BackendContext.h
- runtime/onert/core/src/backend/builtin/train/KernelGenerator.cc
- runtime/onert/core/src/backend/builtin/train/KernelGenerator.h
- runtime/onert/core/src/backend/builtin/train/TensorRegistry.h
- runtime/onert/core/src/compiler/ExecutorFactory.cc
- runtime/onert/core/src/compiler/TensorRegistries.h
- runtime/onert/core/src/exec/train/TrainableExecutor.cc
- runtime/onert/core/src/exec/train/TrainableExecutor.h
This commit unifies TensorRegistry for training.
- Unify TensorRegistry in train backend
- Unify TensorRegistry for training in builtin backend
- Use TensorRegistries for training for each backend context
> [onert] Unify TensorRegistry for training

- runtime/onert/api/include/nnfw_experimental.h
This commit adds NNFW_TRAIN_LOSS enum to nnfw experimental api. nnfw_train_info structure has a loss type as a member variable.
Draft: #11035
> [onert] Add NNFW_TRAIN_LOSS enum to nnfw experimental api

- runtime/onert/api/src/nnfw_api_internal.cc
This commit implements train_set_input in nnfw api.
It sets train input to input tensor.
draft: #11035
~~waiting #11077~~
> [onert] Implement train_set_input in nnfw api

- tests/tools/onert_train/src/args.cc
- tests/tools/onert_train/src/args.h
This commit changes optimizer argument type from string to int.
Draft: #11035
> [tools/onert_train] Change Optimizer type

- runtime/onert/core/include/ir/operation/Loss.h
- runtime/onert/core/src/ir/operation/Loss.cc
This commit introduces MEAN_SQUARED_ERROR to Loss operation. Since CATEGORICAL_CROSSENTROPY may not operate according to the model structure, the default type of loss op has also been changed to MEAN_SQUARED_ERROR.
Draft : #11035
> [onert] Introduce MEAN_SQUARED_ERROR to Loss operation

- runtime/onert/core/include/compiler/train/TrainingInfo.h
- runtime/onert/core/src/compiler/train/TrainingCompiler.cc
- runtime/onert/core/src/compiler/train/pass/LossInsertionPass.cc
This commit implements LossInsertionPass.
This function runs in the middle of constructing the trainable graph. Loss uses the original graph output as y_pred input. And it creates y_true input in the same shape and type as y_pred input. The output is Scalar tensor by default.
Draft: #11035
> [onert] Implement LossInsertionPass

- runtime/onert/core/src/ir/OperationDumper.cc
- runtime/onert/core/src/ir/OperationDumper.h
This commit implements Loss visitor function in OperationDumper.
draft: #11035
> [onert] Implement Loss visitor function in OperationDumper

- runtime/onert/core/include/compiler/StaticShapeInferer.h
- runtime/onert/core/src/compiler/StaticShapeInferer.cc
This commit implements Loss visitor function in StaticShapeInferer.
The Y_TRUE input should be the same shape as Y_PRED.
Draft: #11035
> [onert] Implement Loss visitor function in StaticShapeInferer

- runtime/onert/core/src/backend/builtin/train/BackendContext.cc
- runtime/onert/core/src/backend/builtin/train/BackendContext.h
This commit refines TrainableBackendContext in builtin backend.
- Remove generating tensors
- Remove initializing constant operands
> [onert] Refine TrainableBackendContext in builtin backend

- runtime/onert/core/src/compiler/ExecutorFactory.cc
This commit includes builtin train tensor registry in trainable executor.
> [onert] Include builtin train tensor registry in trainable executor

- runtime/onert/api/include/nnfw_experimental.h
This commit introduces NNFW_TRAIN_OPTIMIZER enum to nnfw experimental api. nnfw_train_info structure has a opt type as a member variable.
Draft : #11035
> [onert] Introduce NNFW_TRAIN_OPTIMIZER enum to nnfw experimental api

- runtime/onert/api/src/nnfw_api_internal.cc
- runtime/onert/core/src/compiler/StaticShapeInferer.cc
- runtime/onert/core/src/compiler/train/TrainingCompiler.cc
This commit changes input shape according to batch_size after loss insertion pass finished. The loss insertion pass adds new input for ground truth and it should be applied with the batch_size.
- Move batch applying code from train_prepare to TrainingCompiler
- Remove the static shape inferer for loss
> [onert] Change input shape after loss insertion pass

- compiler/common-artifacts/exclude.lst
This will exclude tcgenerate for upcommiong Net_Gelu models.
> [common-artifacts] Exclude Net_Gelu for tcgenerate

- compiler/loco/CMakeLists.txt
Let's install CanonicalNodes.lst file.
"CanonicalNodes.lst" is used in installed loco header files. 
So if we include installed loco header file, it can make build fail.
> [loco] Install CanonicalNodes.lst file

- compiler/circle2circle-dredd-recipe-test/test.lst
This will enable circle2circle fuse_gelu dredd test with Net_Gelu_000 model.
> [circle2circle/test] Dredd test for fuse_gelu

- compiler/luci/pass/src/RequantizePass.cpp
- compiler/luci/pass/src/RequantizePass.test.cpp
This revises RequantizePass.
- Merge RequantizeConst and RequantizeNonConst visitors.
- Remove redundant logics.
- Add tests.
---
> [luci/pass] Revise RequantizePass

- tests/tools/onert_train/src/onert_train.cc
This commit uses loss type argument and passes it to nnfw_train_info.
~~waiting: #11112~~
Draft: #11035
> [tools/onert_train] Use loss type argument

- compiler/luci/pass/src/helpers/TypeMapper.h
This adds missing header guard.
> [luci] Add missing header guard

- runtime/onert/core/src/compiler/ExecutorFactory.cc
This commit removes creating IOTensors of outputs.
> [onert] Remove creating IOTensors of outputs

- compiler/luci/pass/src/FuseGeluPass.cpp
This PR revises FuseGelu to use GeluPattern2.
> [luci/pass] Revise FuseGelu to use GeluPattern2

- compiler/circle-mpqsolver/src/CircleMPQSolver.cpp
This commit fixes type in metric name.
Actually it's MAE (Mean Absolute Error). Please see https://github.com/Samsung/ONE/blob/bb30405d3ed25d457af427dbd8319af4e722c1ea/compiler/circle-mpqsolver/src/core/ErrorMetric.h#L42
> [circle-mpqsolver] Fix typo in metric

- compiler/circle2circle-dredd-recipe-test/test.lst
This will enable circle2circle fuse_gelu dredd test with Net_Gelu_001 model.
> [circle2circle/test] Dredd test for fuse_gelu 2

- compiler/common-artifacts/exclude.lst
This excludes upcoming int8 recipes.
---
> [common-artifacts] Exclude int8 recipes

- runtime/onert/core/src/compiler/train/StaticDerivativeShapeInferer.cc
- runtime/onert/core/src/compiler/train/StaticDerivativeShapeInferer.h
This commit adds checking output in StaticDerivativeShapeInferer.
> [onert] Add checking output in StaticDerivativeShapeInferer

- runtime/onert/core/src/backend/builtin/train/KernelGenerator.cc
- runtime/onert/core/src/backend/builtin/train/kernel/PermuteLayer.cc
- runtime/onert/core/src/compiler/ExecutorFactory.cc
This commit make PermuteLayer exclude permutation of derivative inputs of model.
> [onert] Exclude copies of derivative inputs of model

- compiler/one-cmds/tests/one-quantize_017.test
- compiler/one-cmds/tests/one-quantize_neg_022.test
- compiler/one-cmds/tests/onecc_058.cfg
- compiler/one-cmds/tests/onecc_058.test
- compiler/one-cmds/tests/prepare_test_materials.sh
This adds tests for requantize option of one-quantize.
---
> [one-cmds] Add requantize tests

- onert-micro/luci-interpreter/CMakeLists.txt
- ENABLE_LEAKSANITIZER for enabling address sanitizer
> address sanitizer option into onert-micro

- tests/tools/onert_train/src/onert_train.cc
This commit uses optimizer type argument and passes it to nnfw_train_info structure.
draft: #11035
> [tools/onert_train] Use optimizer type argument

- tests/tools/onert_train/src/onert_train.cc
- tests/tools/onert_train/src/rawdataloader.cc
- tests/tools/onert_train/test/rawdataloader.test.cc
The tensor info of trainable graph changes the tensor info according to the batch_size during `train_prepare` function.
The onert_train tool does not need to consider the batch_size for tensorinfo. This commit therefore does not multiply batch_size to the tensor info.
~~waiting : #11112~~
Draft : #11035
Related code:
https://github.com/Samsung/ONE/blob/276bd85d67bd274b55c767612669a24eb1ca43da/runtime/onert/api/src/nnfw_api_internal.cc#L1165-L1174
> [tools/onert_train] Do not multiply batch_size to tensor info

- compiler/moco-tf/src/Canonicalization/SoftmaxCanonicalizer.h
This PR fixes typo in HEADER guard.
Related: #11177 
> [moco-tf] Fix typo in header macro

- compiler/luci/partition/include/luci/ConnectNode.h
- compiler/luci/partition/src/Nodes/CircleHardSwish.cpp
- compiler/luci/partition/src/Nodes/CircleHardSwish.test.cpp
Support HardSwish operation in luci/partition
---
> [luci/partition] Support HardSwish operation

- onert-micro/luci-interpreter/pal/mcu/PALResizeBilinear.h
- fix error: invalid conversion from 'const int*' to 'const int32_t*'
> [onert-micro] Fix build error for arm

- runtime/onert/api/src/nnfw_api.cc
- runtime/onert/api/src/nnfw_api_internal.cc
- runtime/onert/api/src/nnfw_api_internal.h
This commit changes the train_get_loss function signature to return error status in internal api. It also unifies the function implementation of train_get_loss the same as other functions.
Draft: #11035
> [onert] Change train_get_loss function signature

- runtime/onert/backend/train/KernelGenerator.cc
- runtime/onert/backend/train/KernelGenerator.h
This commit allows to use multiple GradientAppliers in a TrainableFnSequence.
> [onert] Allow to use multiple GradientAppliers

- runtime/onert/core/src/ir/train/TrainableGraph.cc
This commit fixes TrainableGraph's copy constructor doing shallow copy.
> [onert] Fix shallow copy of TrainableGraph

- runtime/onert/core/include/compiler/train/LoweredTrainableGraph.h
This commit uses trainable graph as a class member variable instead of reference in lowered trainable graph.
> [onert] Use trainable graph as a class member variable in lowered trainable graph

- runtime/onert/backend/train/ops/OperationUtils.h
This commit introduce OperationUtils header file for train kernel.
from #11217
> [onert] Introduce OperationUtils for train kernal

- compiler/visq-unittest/test/testDotBuilder.py
This removes unused Python module.
> [visq-unittest] Remove unused module

- runtime/onert/api/src/nnfw_api_internal.cc
- runtime/onert/core/include/exec/Execution.h
- runtime/onert/core/src/exec/Execution.cc
This commit implements train_set_expected in nnfw api. IT sets the expected input to loss input tensor.
Draft: #11035
> [onert] Implement train_set_expected in nnfw api

- runtime/onert/core/include/ir/train/TrainableGraph.h
- runtime/onert/core/src/ir/train/TrainableGraph.cc
This commit introduces loss map for accessing training loss value from nnfw internal api.
Draft: #11035
> [onert] Introduce loss map for training

- compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
This checks if node is a quantization target.
> [luci] Add check before QuantizeSpecialActivation

- runtime/onert/core/src/backend/builtin/train/KernelGenerator.cc
- runtime/onert/core/src/backend/builtin/train/KernelGenerator.h
- runtime/onert/core/src/compiler/ExecutorFactory.cc
This commit fixes use of partial graph to use outputs of whole graph.
> [onert] Fix use of partial graph's outputs

- runtime/onert/backend/train/Backend.h
This commit fixes optimizer being nullptr in the KernelGenerator of train backend.
> [onert] Fix optimizer being nullptr

- runtime/onert/backend/train/KernelGenerator.cc
- runtime/onert/backend/train/KernelGenerator.h
- runtime/onert/backend/train/ops/ReshapeLayer.cc
- runtime/onert/backend/train/ops/ReshapeLayer.h
This commit introduces ReshapeLayer in train backend.
Draft: #11035
> [onert] Introduce ReshapeLayer in train backend

- runtime/onert/core/src/exec/train/TrainableExecutor.cc
- runtime/onert/core/src/exec/train/TrainableExecutor.h
This commit implements getLoss function in TrainableExecutor. It finds loss output index using pred index and returns the loss value.
Draft: #11035
> [onert] Implement getLoss in TrainableExecutor

- docs/howto/how-to-build-runtime.md
This commit updates how-to-build-runtime.md.
- Change default setting to ubuntu 20.04
- Update package requirement
- Update build process
> [doc] Update runtime build document

- runtime/onert/core/src/exec/train/TrainableExecutors.cc
- runtime/onert/core/src/exec/train/TrainableExecutors.h
This commit implements getLoss function in TrainableExecutors. The nnfw api will call this function to get loss value using pred output index.
Draft: #11035
> [onert] Implement getLoss in TrainableExecutors

- compiler/circle2circle-dredd-recipe-test/test.lst
Add circle2circle-dredd-recipe-test to support HardSwish decomposing pass
---
Draft PR: #11220
> [circle2circle-dredd-recipe-test] Support HardSwish decomposing pass

- compiler/mir/unittests/ShapeRange.cpp
The macro 'INSTANTIATE_TEST_CASE_P' from GTest is deprecated.
It is recommended to use 'INSTANTIATE_TEST_SUITE_P' instead.
---
FYI, you can check the history of renaming of the macro in below link.
* Issue from GoogleTest
https://github.com/google/googletest/issues/1085
* Summary of the above issue
https://github.com/Samsung/ONE/pull/11190#issuecomment-1661274707
Related: #11177
> [mir] Replace deprecated macro with recommended

- runtime/onert/core/src/compiler/train/pass/LossInsertionPass.cc
This commit adds y_pred and loss pairs to the trainable graph loss map.
Draft: #11035
> [onert] Add y_pred and loss pairs to trainable graph loss map

- compute/cker/include/cker/train/operation/Loss.h
- compute/cker/src/train/Loss.test.cc
- runtime/onert/backend/train/KernelGenerator.cc
- runtime/onert/backend/train/ops/LossLayer.cc
- runtime/onert/backend/train/ops/LossLayer.h
This commit introduces LossMSEGrad function in train backend.
- Implements LossMSEGrad in cker
- Removed usused derivative tensors
Draft: #11035
Refer formula: https://github.com/Samsung/ONE/issues/11248#issuecomment-1674169085
> [onert] Introduce LossMSEGrad function in train backend

- compiler/one-cmds/onelib/constant.py
Add the '--decompose_hardswish' option to support HardSwish decomposing pass in one-optimize
---
Related to: #10930
> [one-cmds] Support HardSwish decomposing option

- compiler/luci/pass/src/ReplaceSubWithAddPass.cpp
Fix to add missing origin in ReplaceSubWithAddPass
---
Related to: #11265
> [luci/pass] Missing to add origin

- infra/nnfw/CMakeLists.txt
Let's update cmake minimum requirement to 3.16.3: ubuntu 20.04 default.
---
Related issue: #11229
> [infra/runtime] Update cmake minimum requirement

- runtime/onert/api/src/nnfw_api_internal.cc
This commit implements train_get_loss in nnfw api. It gets the loss value from the loss tensor corresponding to output index.
Draft: #11035
> [onert] Implement train_get_loss in nnfw api

- compiler/luci/pass/src/QuantizationUtils.cpp
- compiler/luci/pass/src/QuantizationUtils.h
- compiler/luci/pass/src/QuantizeActivation.cpp
- compiler/luci/pass/src/QuantizeDequantizeWeightsPass.cpp
- compiler/luci/pass/src/QuantizeWeights.cpp
- compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
It removes zeropoint parameters from symmetric quantization.
> [luci] Remove zeropoint from symmetric quantization

- compiler/one-cmds/tests/one-import_neg_001.test
This will revise one-import_neg_001 to handle error message with new TF.
> [one-cmds] Revise one-import negtive test for tf

- compiler/record-minmax-thread-safety-test/CMakeLists.txt
This checks record-minmax-for-thread-test before test.
---
Draft: https://github.com/Samsung/ONE/pull/11268
Related to: #11202
> [rmm-thread-safety-test] Check target before test

- compiler/one-cmds/one-import-pytorch
- compiler/one-cmds/onelib/utils.py
- compiler/one-cmds/tests/pytorch-operations/example_generator.py
This will revise to explictly import importlib sub modules.
> [one-cmds] Explict import importlib modules

- compiler/one-cmds/one-import-onnx
This will revise one-import-onnx to add alphabet prefix in remap IO names.
> [one-cmds] Add prefix to I/O names for import onnx

- compiler/one-cmds/tests/prepare_test_materials.sh
This will revise to use fixed I/O name without special character for reshape_matmul.onnx model as new TF doesn't allow.
> [one-cmds] Use fixed I/O name for reshape_matmul.onnx

- compiler/record-minmax/CMakeLists.txt
This prevents building record-minmax-for-thread-test executable.
---
Draft: https://github.com/Samsung/ONE/pull/11268
Related to: https://github.com/Samsung/ONE/issues/11202
> [record-minmax] Disble thread test

- compiler/one-cmds/tests/one-quantize_016.test
- compiler/one-cmds/tests/onecc_045.test
This will update input name for using recent updated reshape_matmul. Using T(0:0), T(0:1) is to make independent from naming convention of TF upgrade.
> [one-cmds] Update input name for reshape_matmul

- compiler/luci-value-test/test.lst
This will revise Conv2D_U8_000 to test with tolerance.
> [luci-value-test] Revise Conv2D_U8_000

- compiler/circle-mpqsolver/src/CircleMPQSolver.cpp
This commit places 'logger' right after possible initialization of 'LUCI_LOG` variable to initialize 'logger' properly.
Draft: https://github.com/Samsung/ONE/pull/11179
Related: https://github.com/Samsung/ONE/issues/11146
> [circle-mpqsolver] Fix'verbose' mode

- compiler/circle-part-value-test/CMakeLists.txt
> [circle-part-value-test] Upgrade TF to 2.12.1

- compiler/luci-pass-value-test/CMakeLists.txt
> [luci-pass-value-test] Upgrade TF to 2.12.1

- compiler/pota-quantization-value-test/CMakeLists.txt
> [pota-quantization-value-test] Upgrade TF to 2.12.1

- compiler/record-minmax-conversion-test/CMakeLists.txt
> [reocrd-minmax-conv-test] Upgrade TF to 2.12.1

- compiler/record-minmax-thread-safety-test/CMakeLists.txt
This will upgrade test environment TF to 2.12.1.
> [record-minmax-thread-safety-test] Upgrade TF to 2.12.1

- compiler/tf2tfliteV2-conversion-test/CMakeLists.txt
iThis will upgrade test environment TF to 2.12.1.
> [tf2tfliteV2-conversion-test] Upgrade TF to 2.12.1

- compiler/luci/pass/src/QuantizationUtils.cpp
- compiler/luci/pass/src/QuantizationUtils.h
Add out_type parameter to compute_sym_scale in order to support int8.
Related: https://github.com/Samsung/ONE/pull/11073, #11057
> [luci/pass] compute_sym_scale supports int8

- compiler/record-minmax/CMakeLists.txt
This will fix cmake warning about if block mis-matching.
> [record-minmax] Fix cmake warning

- infra/nncc/cmake/options/options_aarch64-darwin.cmake
> Add cmake options for macOS aarch64 build

- compiler/pota-quantization-value-test/compare_tensors.py
It add weights_only_quantization mode in compare_tensors.py. It only quantize weights. Thus, bias and so on are not checked.
Related: https://github.com/Samsung/ONE/pull/11073, https://github.com/Samsung/ONE/issues/11122, #11057
> [pota-quantization-value-test] Add weights_only_quantization

- compiler/circle-tensordump/src/Dump.cpp
It makes circle-tensordump support `int8` datatype.
Related: https://github.com/Samsung/ONE/pull/11073, https://github.com/Samsung/ONE/issues/11122, #11057
> [circledump] Support int8 datatype

- compiler/pota-quantization-value-test/test_wo_quantization.sh
It introduces test_wo_quantization.sh, which is used during weights-only quantization value test.
Related: https://github.com/Samsung/ONE/pull/11073, https://github.com/Samsung/ONE/issues/11122
> [pota-quantization-value-test] Add test_wo_quantization.sh

- compiler/one-cmds/one-import-onnx
This will introduce _sanitize_io_names step in import onnx to filter unacceptable characters in I/O names from onnx import models.
> [one-cmds] Introduce _sanitize_io_names step

- compute/cker/src/train/Loss.test.cc
This commit uses EXPECT gtest interface in cker Loss unittest. ASSERT interface fails fast and aborts the current function. So if the previous test case fails, other function cannot be tested. However, EXPECT interface continues after the failure and reports errors after all tests have been finished. This cker unittest has multiple test cases for one function. Therefore, EXPECT is more useful for performing multipel test cases.
Draft: #11035
> [onert] Use EXPECT gtest interface in cker Loss unittest

- compiler/circle-mpqsolver/src/CircleMPQSolver.cpp
- compiler/circle-mpqsolver/src/bisection/BisectionSolver.cpp
- compiler/circle-mpqsolver/src/core/SolverOutput.cpp
- compiler/circle-mpqsolver/src/core/SolverOutput.h
This commit replaces zero level logging with always printed messages.
It implements suggestion from https://github.com/Samsung/ONE/pull/11216#discussion_r1285390062.
Running `circle-mpqsolver` without 'LUCI_LOG' being defined produced the following output:
```
>> Searching mixed precision configuration 
model:/home/stanislav/repos/WorkSpaces/mobile_net_v1/model.recorded.circle
dataset: /mnt/storage/datasets/ms_coco/dataset_MB_v1_3.h5
input dtype: uint8
output dtype: uint8
algorithm: bisection (auto)
qerror metric: MAE
target qerror ratio: 0.1
>> Computing baseline qerrors
Full int16 model qerror: 7.68947e-05
Full uint8 model qerror: 0.000288324
Target qerror: 9.80376e-05
>> Running bisection(auto) algorithm
Qerror of front half: 152628
Qerror of rear half: 50324.6
Front part will be Q16, …
```
> [circle-mpqsolver] Revisit logging

- compiler/one-cmds/one-prepare-venv
This will revise one-prepare-venv to use python3.
- one-prepare-venv is for U20.04 and U22.04
> [one-cmds] Revise to use python3 for one-prepare-venv

- compiler/common-artifacts/CMakeLists.txt
This will revise for AArch64 to use TF2.12.1 and upgrade related packages.
> [common-artifacts] Revise AArch64 to use TF2.12.1

- compiler/CMakeLists.txt
This will remove not used anymore ONE_UBUNTU_CODENAME_JAMMY.
> [CFE] Remove ONE_UBUNTU_CODENAME_JAMMY

- compiler/one-cmds/CMakeLists.txt
- compiler/one-cmds/one-prepare-venv.aarch64
This will revise one-prepare-venv for AArch64
- remove Ubuntu version fron name
- update TF and related packages versions
> [one-cmds] Revise one-prepare-venv for AArch64

- compiler/luci/pass/src/QuantizeWeightsOnly.cpp
- compiler/luci/pass/src/QuantizeWeightsOnly.h
It introduces QuantizeWeightsOnly visitor.
It is subset of QuantizeWeights visitor.
It does not visit InstanceNorm, PReLU, ...
Related: https://github.com/Samsung/ONE/pull/11073, https://github.com/Samsung/ONE/issues/11057
> [luci/pass] Introduce QuantizeWeightsOnly visitor

- compiler/pota-quantization-value-test/CMakeLists.txt
Now, pota-quantization-value-test can handle weights-only test.
> [pota-quantization-value-test] Handle weights-only in CMakeLists.txt

- compiler/one-cmds/one-quantize
This commit implements ampq option processing in one-quantize.
Its correctness is tests at #11179.
Draft: #11179
Related: #11146
> [one-cmds] Add ampq option to one-quantize

- compiler/luci/pass/src/ConvertNCHWToNHWCPass.test.cpp
Initialize the std::initializer_list with brace-init-list via default member intializer is not safe since the underlying array has temporary lifetime bound to constructor.
---
Related with #11343
> [luci/pass] Initialize std::initializer_list with static variable

- compiler/luci/pass/src/VerifyQuantizedBiasScale.cpp
The abs() will typecasts float type into integer implictly.
Better to use std::abs() for float type variable.
---
Related with #11343
> [luci/pass] Use std::abs() for float type instead of abs()

- compiler/luci/pass/src/FoldAddV2Pass.test.cpp
- compiler/luci/pass/src/FoldCastPass.test.cpp
- compiler/luci/pass/src/FoldDequantizePass.test.cpp
- compiler/luci/pass/src/QuantizedModelVerifier.test.cpp
It adds template keyword to specify the type of a function.
--- 
Related with #11343
> [luci/pass] Add 'template' keyword

- compiler/luci/pass/src/QuantizedModelVerifier.test.cpp
It adds default handle to the switch statement.
---
Related with #11343
> [luci/pass] Missing default handle for switch statement

- compiler/one-cmds/one-prepare-venv.aarch64
- Build and install the tensorflow addons package directly from the source code, which is not officially released for the aarch64 environment.
> [one-cmds] Revise `one-prepare-venv.aarch64` script to build and install missing package from source code.

- compiler/one-cmds/one-import-onnx
This will fix one-import-onnx I/O names starting with numeric.
> [one-cmds] Fix import onnx I/O names with numeric

- compiler/luci/import/include/luci/Import/NodeBuilder.h
The NodeBuilderBase abstract class has a non-virtual destructor implicitly. If a virtual destructor is not defined in the base class, a derived class's destructor won't be called when it's deleted with the pointer to its base class type.
> [luci/import] Add a virtual destructor for Base class

- compiler/circledump/src/MetadataPrinter.h
The MetadataPrinter abstract class has a non-virtual destructor implicitly. If a virtual destructor is not defined in the base class, a derived class's destructor won't be called when it's deleted with the pointer to its base class type.
> [circledump] Add a virtual destructor for Base class

- compiler/circle-eval-diff/src/InputDataLoader.cpp
The compiler warns using the result of an assignment as a condition without parentheses. Let's add additional parentheses to make sure the condition is intended.
> [circle-eval-diff] Add missing parentheses

- compiler/luci/logex/src/CircleNodeSummaryBuilder.cpp
The insertion operator ('<<') has higher precedence than conditional
operator ('?'). It adds a parentheses to keep the order of operators.
> [luci/logex] Add missing parentheses

- compiler/nnc/backends/soft_backend/code_snippets/cpp_header_types.def
Use 'delete []' for freeing a array type variable.
> [nnc] Use delete w/ bracket for array type

- compiler/circle-mpqsolver/src/bisection/BisectionSolver.cpp
- compiler/circle-mpqsolver/src/core/Dumper.cpp
- compiler/circle-mpqsolver/src/core/Dumper.h
- compiler/circle-mpqsolver/src/core/DumpingHooks.cpp
- compiler/circle-mpqsolver/src/core/DumpingHooks.h
- compiler/circle-mpqsolver/src/core/SolverHooks.h
This commit dumps final error of quantization.
This will ease analysis of `circle-mpqsolver` run.
Related: #11146
> [circle-mpqsolver] Dump final qerror

- compiler/one-cmds/tests/one-quantize_018.test
- compiler/one-cmds/tests/one-quantize_019.test
- compiler/one-cmds/tests/one-quantize_020.test
This commit adds tests for ampq option of one-quantize cmd.
Its correctness is tested at https://github.com/Samsung/ONE/pull/11179.
Draft: https://github.com/Samsung/ONE/pull/11179
Related: https://github.com/Samsung/ONE/issues/11146
> [one-cmds] Add tests for ampq

- packaging/nnfw.spec
This commit fixes test install path typo:
`%{buildroot}%{test_install_dir}` -> `%{buildroot}/%{test_install_dir}`
> [infra/gbs] Fix test install path typo

- compiler/luci/pass/include/luci/Pass/QuantizeWeightsPass.h
- compiler/luci/pass/src/CircleQuantizer.cpp
- compiler/luci/pass/src/QuantizeWeightsPass.cpp
- compiler/luci/pass/src/QuantizeWeightsPass.test.cpp
It introduces QuantizeWeightsPass, which calls WeigghtsOnly visitor.
Related: https://github.com/Samsung/ONE/pull/11073, https://github.com/Samsung/ONE/issues/11057
> [luci/pass] Introduce QuantizeWeightsPass

- compiler/luci/pass/src/QuantizeWeightsPass.cpp
- compiler/luci/pass/src/QuantizeWeightsPass.test.cpp
It alters 1st negative test to check input dtype.
It also updates test graph's conv params so that it is valid.
https://github.com/Samsung/ONE/pull/11340#pullrequestreview-1597521620
> [luci/pass] Update negative test for QuantizeWeightsPass

- compute/cker/CMakeLists.txt
- compute/cker/include/cker/Types.h
- compute/cker/include/cker/eigen/eigen_gemm_eigen.h
- compute/cker/include/cker/operation/FullyConnected.h
- compute/cker/include/cker/operation/optimized/Gemm.h
- runtime/onert/backend/cpu/ops/FullyConnectedLayer.cc
- runtime/onert/backend/train/ops/FullyConnectedLayer.cc
This commit brings a FullyConnected kernel from tensorflow v2.12.1.
- The kernel is an eigen kernel for FullyConnected operation.
- The kernel supports only for float and x86.
> [onert] Bring FullyConnected kernel from tensorflow v2.12.1.

- compiler/luci/pass/src/QuantizeWeightsOnly.cpp
- compiler/luci/pass/src/QuantizeWeightsOnly.h
It add visit function for DepthwiseConv2D in QuantizeWeightsOnly.
Related: #11057
> [luci/pass] QuantizeWeightsOnly supports DepthwiseConv2D

- compiler/one-cmds/tests/one-quantize_018.test
- compiler/one-cmds/tests/one-quantize_019.test
- compiler/one-cmds/tests/one-quantize_020.test
This makes tests use different output name to avoid name conflicts.
> [one-cmds] Use different output name

- compiler/luci/service/src/ShapeInfer_StridedSlice.cpp
This will remove redundant type alias in ShapeInfer_StridedSlice.
> [luci/svc] Remove type alias

- tests/tools/onert_train/src/measure.h
- tests/tools/onert_train/src/onert_train.cc
This commit measures training speed in one step and show the time result in logs.
Draft: #11035
> [tools/onert_train] Measure training speed in one step

- compiler/circle-interpreter-test/CMakeLists.txt
- compiler/circle-interpreter-test/requires.cmake
This adds dependency on luci_value_test.
---
`circle-interpreter-test` intermittently fails as input data (generated by `luci_value_test`) does not exist. This PR resolves the issue.
> [circle-interpreter-test] Add proper dependency

- runtime/onert/core/include/exec/train/IGradientApplier.h
This commit introduces IGradientApplier, an interface that applies gradients to a trainable tensor.
> [onert] Introduce IGradientApplier

- Makefile.template
This commit updates makefile to not show intended copy fail message on x64.
---
Related issue: #11405
> [onert] Don't show intended cp fail

- runtime/onert/frontend/circle_schema/include/circle_schema_generated.h
This commit updates onert frontend to support circle schema v0.6.
---
Related issue: https://github.com/Samsung/ONE/issues/11381
Schema: #11382
> [onert] Support circle schema v0.6

- runtime/onert/api/include/nnfw.h
This PR fixes typos in nnfw.h comment
Related issue: #11404
> [onert/api] Fix : typos and wrong params name

- compiler/record-minmax/driver/Driver.cpp
- compiler/record-minmax/include/MinMaxComputer.h
- compiler/record-minmax/include/RecordMinMax.h
- compiler/record-minmax/src/MinMaxComputer.cpp
- compiler/record-minmax/src/RecordMinMax.cpp
This introduces MinMaxComputer to easily update calibration logic.
---
Related to: #11269 
Draft PR: https://github.com/Samsung/ONE/pull/11409
> [record-minmax] Revise record-minmax

- compiler/luci/service/src/ShapeInfer_StridedSlice.cpp
This will revise ShapeInfer_StridedSlice to follow original source with int64.
> [luci/svc] Revise ShapeInfer_StridedSlice with int64

- tests/tools/onert_train/src/args.cc
- tests/tools/onert_train/src/args.h
This commit adds mem_poll argument to enable memory polling.
Draft: #11035
> [tools/onert_train] Add mem_poll argument

- compiler/record-minmax/driver/Driver.cpp
This adds cmdline parameters for moving_average algorithm.
---
Related to: https://github.com/Samsung/ONE/issues/11269
Draft PR: https://github.com/Samsung/ONE/pull/11409
> [record-minmax] Add parameters for moving_average

- compiler/mio-circle06/CMakeLists.txt
- compiler/mio-circle06/README.md
- compiler/mio-circle06/example.cpp
- compiler/mio-circle06/include/mio_circle/Helper.h
- compiler/mio-circle06/include/mio_circle/Reader.h
- compiler/mio-circle06/src/Helper.cpp
- compiler/mio-circle06/src/Helper.test.cpp
- compiler/mio-circle06/src/Reader.cpp
- compiler/mio-circle06/src/Reader.test.cpp
This will introduce mio-circle06 to provide circle version 0.6.
> [mio] Introduce mio-circle06

- compiler/luci/service/src/ShapeInfer_StridedSlice.cpp
This commit updates constant zero to int64_t type explicitly on std::max. 
It will resolve build fail for 32bit target.
> [luci/service] Use explicit int64_t type zero

- runtime/onert/odc/Quantizer.test.cc
This commit updates odc quantizer negative unittest to use ASSERT_NE.
---
Related review: https://github.com/Samsung/ONE/pull/11414#discussion_r1311371592
> [onert] Use ASSERT_NE for negative test

- compiler/mio-tflite2121/CMakeLists.txt
- compiler/mio-tflite2121/README.md
- compiler/mio-tflite2121/example.cpp
- compiler/mio-tflite2121/include/mio_tflite2121/Helper.h
- compiler/mio-tflite2121/src/Helper.cpp
- compiler/mio-tflite2121/src/Helper.test.cpp
This will introduce mio-tflite1212 for tflite version 2.12.1.
> [mio] Introduce mio-tflite12121

- runtime/onert/core/src/odc/QuantizerLoader.cc
- runtime/onert/core/src/odc/QuantizerLoader.h
- runtime/onert/core/src/odc/QuantizerLoader.test.cc
This commit intrduces QuantizerLoader to bind odc module quantizer to onert core.
---
Related issue: https://github.com/Samsung/ONE/issues/11391
Draft: https://github.com/Samsung/ONE/pull/11298
> [onert] Introduce QuantizerLoader

- compiler/record-minmax/include/MinMaxObserver.h
- compiler/record-minmax/include/MinMaxVectors.h
This extracts MinMaxVectors from MinMaxObserver.
---
Related to: https://github.com/Samsung/ONE/pull/11410#issuecomment-1700518870
> [record-minmax] Extract MinMaxVectors

- compiler/one-cmds/one-quantize
- compiler/one-cmds/tests/one-quantize_021.test
- compiler/one-cmds/tests/one-quantize_neg_023.test
This adds parameters for moving_average in one-quantize.
---
Related to: https://github.com/Samsung/ONE/issues/11269
Draft PR: https://github.com/Samsung/ONE/pull/11409
> [one-cmds] Add moving_average parameters

- runtime/onert/backend/cpu/ops/ConvolutionLayer.h
It makes methods private as much as possible.
Also, it reorders the methods to make it easy to read.
> [onert] Revisit ConvolutionLayer.h

- compiler/tfl-inspect/CMakeLists.txt
- compiler/tfl-inspect/requires.cmake
- compiler/tfl-inspect/src/Reader.cpp
This will revise to use mio-tflite2121.
> [tfl-inspect] Revise to use mio-tflite2121

- compiler/tfl-verify/CMakeLists.txt
- compiler/tfl-verify/requires.cmake
This will revise to use mio-tflite2121.
> [tfl-verify] Revise to use mio-tflite2121

- compiler/tfldump/src/OpPrinter.cpp
This will enable to print TransposeConv activation function.
> [tfldump] Print TransposeConv ActFunc

- tests/nnfw_api/src/CircleGen.cc
It changes && to || for empty vector check
Related: https://github.com/Samsung/ONE/issues/11454, https://github.com/Samsung/ONE/pull/11318
> [onert] Fix nnfw_api CircleGen condition

- compiler/luci/export/src/CircleBuiltinTypesExtractor.h
- compiler/luci/import/src/Nodes/CircleTransposeConv.cpp
- compiler/luci/lang/include/luci/IR/Nodes/CircleTransposeConv.h
- compiler/luci/logex/src/CircleNodeSummaryBuilder.test.cpp
- compiler/luci/logex/src/CircleNodeSummaryBuilders.cpp
- compiler/luci/partition/src/Nodes/CircleTransposeConv.test.cpp
- compiler/luci/pass/src/FuseAddWithTConvPass.cpp
- compiler/luci/pass/src/FuseBatchNormWithTConvPass.cpp
- compiler/luci/pass/src/QuantizePreCheckerPass.test.cpp
- compiler/luci/service/src/Nodes/CircleTransposeConv.cpp
- compiler/luci/service/src/Nodes/CircleTransposeConv.test.cpp
This will revise to support TransposeConv activation.
> [luci] Support TransposeConv activation

- runtime/onert/backend/train/KernelGenerator.h
- runtime/onert/backend/train/ops/GradientApplier.cc
- runtime/onert/backend/train/ops/GradientApplier.h
- runtime/onert/core/include/exec/train/ITrainableFunction.h
- runtime/onert/core/include/exec/train/TrainableFnSequence.h
- runtime/onert/core/src/exec/train/TrainableFnSequence.cc
This commit applies IGradientApplier.
- Change GradientAppiler from inherting ITranableFunction to inherting IGradientApplier.
- Add IGradientApplier vector in TrainableFnSequence.
> [onert] Apply IGradientApplier

- compute/cker/include/cker/operation/reference/Conv.h
It adds conv2d hybrid (weight: int8 symm, in/out: f32) reference kernel.
Implementation is copied from tflite 2.13.0.
> [onert/cker] Add conv2d hybrid reference kernel

- compiler/record-minmax/CMakeLists.txt
- compiler/record-minmax/tests/MinMaxComputer.test.cpp
This adds unittests for MinMaxComputer.
---
Related to: https://github.com/Samsung/ONE/pull/11410#issuecomment-1700518870
> [record-minmax] Add MinMaxComputer unittest

- compute/cker/include/cker/operation/Conv.h
- runtime/onert/backend/cpu/ops/ConvolutionLayer.cc
- runtime/onert/backend/cpu/ops/ConvolutionLayer.h
- tests/nnfw_api/src/one_op_tests/Conv2D.test.cc
It introduces conv2d hybrid (weight: int8 symm, input/output: f32).
Related: https://github.com/Samsung/ONE/issues/11454, https://github.com/Samsung/ONE/pull/11318
> [onert] Support conv2d hybrid

- compute/cker/include/cker/operation/reference/integer_ops/DepthwiseConvHybrid.h
It introduces dconv2d hybrid (weight: i8 symm, activation: f32) kernel. Implementation is copied from tensorflow 2.13.0.
Related: https://github.com/Samsung/ONE/issues/11458, https://github.com/Samsung/ONE/pull/11463
> [onert/cker] Add dconv2d hybrid reference kernel

- runtime/onert/api/src/nnfw_api.cc
- tests/tools/onert_run/src/args.cc
- tests/tools/onert_run/src/args.h
- tests/tools/onert_run/src/onert_run.cc
This commit adds quantization option in onert_run for online quantization test.
---
Related issue: https://github.com/Samsung/ONE/issues/11391
Draft: https://github.com/Samsung/ONE/pull/11298
> [onert/test] Add quantization option in onert_run

- compute/cker/include/cker/operation/DepthwiseConv.h
- runtime/onert/backend/cpu/ops/DepthwiseConvolutionLayer.cc
- runtime/onert/backend/cpu/ops/DepthwiseConvolutionLayer.h
- tests/nnfw_api/src/one_op_tests/DepthwiseConv2D.test.cc
It supports dconv2d hybrid - weights: i8 symm, in/out: float.
#11463
> [onert] Support dconv2d hybrid

- runtime/onert/core/src/odc/QuantizerLoader.cc
This commit updates QuantizerLoader::loadLibrary to close file handle before return.
> [onert] Close file handle before return

- runtime/onert/backend/cpu/ops/ConvolutionLayer.cc
It fixes wrong condition and name in per-channel quantization.
> [onert] Fix Conv2D per-channel check condition

- runtime/onert/backend/cpu/ops/ConvolutionLayer.cc
This commit initializes ConvolutionLayer `_is_hybrid` field.
> [onert] Initialize ConvolutionLayer field

- compiler/circle-mpqsolver/src/core/ErrorMetric.cpp
This commit throws an exception at an attempt to divide by zero.
Draft: #11452
> [circle-mpqsolver] Revisit MAEMetric

- runtime/onert/backend/cpu/ops/DepthwiseConvolutionLayer.h
This commit initializes DepthwiseConvolutionLayer's `_is_hybrid` field.
> [onert] Initialize DepthwiseConvolutionLayer field

- compute/cker/include/cker/operation/Conv.h
It fixes the wrong order in ConvHybridTempArena.
> [onert] Fix the param mismatch in ConvHybridTempArena

- .ahub/sam/exclude.txt
This commit updates exclude.txt for SAM to exclude the build intermediate files.
> [infra] Exclude intermediate workspace on SAM exclude file

- compiler/luci/pass/src/FuseActivationFunctionPass.cpp
This will disable fuse activation for TransposeConv.
> [luci/pass] Disable fuse activation for TransposeConv

- compiler/luci-interpreter/src/core/KernelParams.h
- compiler/luci-interpreter/src/kernels/TransposeConv.test.cpp
- compiler/luci-interpreter/src/loader/KernelBuilder.test.cpp
- compiler/luci-interpreter/src/loader/nodes/TransposeConv.cpp
This will enable to support TransposeConv activation.
- only support NONE for now
> [luci-interpreter] Support TransposeConv activation

- compiler/circle-mpqsolver/CMakeLists.txt
- compiler/circle-mpqsolver/src/core/ErrorMetric.test.cpp
This commit adds unit tests for MAEMetric.
Draft: https://github.com/Samsung/ONE/pull/11452
> [circle-mpqsolver] Add MAEMetric unittest

- docs/conf.py
- packaging/nnfw.spec
- runtime/contrib/android/api/build.gradle
- runtime/onert/api/include/nnfw_version.h
This commit updates runtime version to 1.26.0.
---
Related issue: #11484
> [runtime] Update runtime version to 1.26.0

- infra/nnfw/cmake/packages/LuciConfig.cmake
This commit disables default path when finding luci libraries.
> [infra/nnfw] Disable default path when finding luci lib

- compiler/vconone/CMakeLists.txt
This commit bumps up to 1.26.0.
---
Related issue: #11484
> [vconone] Bump up to 1.26.0

- runtime/onert/backend/train/ops/FullyConnectedLayer.cc
This commit fixes the missed nullptr check in train::FullConnectedLayer
> [onert] Fix a missed nullptr check

- compiler/luci/pass/include/luci/Pass/XpSepActFromTransposeConvPass.h
- compiler/luci/pass/src/XpSepActFromTransposeConvPass.cpp
- compiler/luci/pass/src/XpSepActFromTransposeConvPass.test.cpp
This will introduce XpSepActFromTransposeConvPass that will separate activation function from TransposeConv.
> [luci/pass] Introduce XpSepActFromTransposeConvPass

- compiler/luci/pass/include/luci/CircleOptimizer.h
- compiler/luci/pass/src/CircleOptimizer.cpp
This will introduce XpSepActFromTransposeConv flag to enable XpSepActFromTransposeConvPass.
> [luci/pass] Introduce XpSepActFromTransposeConv

- compiler/circle2circle/src/Circle2Circle.cpp
This will revise circle2circle to handle XpSepActFromTransposeConv with exp_disable_sep_transposeconv_actfunc option.
> [circle2circle] Handle XpSepActFromTransposeConv

- compiler/circle-mpqsolver/src/core/Quantizer.test.cpp
This commit fixes size of constant operand.
Draft: https://github.com/Samsung/ONE/pull/11452
> [circle-mpqsolver] Fix size of operand

- infra/nnfw/cmake/options/options_i686-tizen.cmake
This commit updates tizen i686 cmake option to be same with x86_64.
> [infra/onert] Fix build fail on tizen i686

- packaging/nnfw.spec
This commit resolves build fail for tizen armv7hl by setting TARGET_ARCH explicitly.
> [infra/gbs] Fix build fail for tizen armv7hl

- onert-micro/luci-interpreter/src/core/CMakeLists.txt
- onert-micro/luci-interpreter/src/core/TrainingGraph.cpp
- onert-micro/luci-interpreter/src/core/TrainingGraph.h
This commit introduces TrainingGraph class.
> [onert-micro] Introduce TrainingGraph class

- onert-micro/luci-interpreter/src/core/CMakeLists.txt
- onert-micro/luci-interpreter/src/core/TrainingModule.cpp
- onert-micro/luci-interpreter/src/core/TrainingModule.h
This commit introduces TrainingModule class.
> [onert-micro] Introduce TrainingModule class

- infra/cmake/packages/LibnpySourceConfig.cmake
- infra/nncc/cmake/CfgOptionFlags.cmake
for : #11254
draft : #11530
This PR includes a new external library, which is required for q-implant and has a MIT license.
ONE-DCO-1.0-Signed-off-by: Junyeong Kang <kjy6135@naver.com>
> [infra/q-implant] Introduce q-implant Source Config

- compiler/onecc-docker/onecc-docker
This commit fix request recent version error
Changed to return the latest version containing `one-compiler-bionic_{version}_amd64.deb` in assets
ONE-DCO-1.0-Signed-off-by: profornnan <profornnan@naver.com>
Related: #11539
> [onecc-docker] Fix request recent version error

- compiler/circle-opselector/src/OpSelector.cpp
This commit fixes the bug when the operators' optional input doesn't exist.
> [circle-opselector] Bug on operators having optional input

- onert-micro/luci-interpreter/src/kernels/Builders.h
- onert-micro/luci-interpreter/src/kernels/CMakeLists.txt
- onert-micro/luci-interpreter/src/kernels/KernelBuilder.cpp
- onert-micro/luci-interpreter/src/kernels/KernelBuilder.h
This commit adds REGISTER_TRAIN_KERNEL interface in onert-micro.
> [onert-micro] Add REGISTER_TRAIN_KERNEL interface

- onert-micro/luci-interpreter/src/core/RuntimeModule.h
This commit adds training into RuntimeModule in onert-micro.
> [onert-micro] Add training into RuntimeModule

- onert-micro/luci-interpreter/src/core/RuntimeGraph.cpp
- onert-micro/luci-interpreter/src/core/RuntimeGraph.h
This commit adds training into RuntimeGraph in onert-micro.
> [onert-micro] Add training into RuntimeGraph

- onert-micro/luci-interpreter/include/luci_interpreter/Interpreter.h
- onert-micro/luci-interpreter/src/Interpreter.cpp
This commit changes allocateAndWriteInputTensor's data type.
> [onert-micro] Change allocateAndWriteInputTensor's data type

- onert-micro/luci-interpreter/src/kernels/CMakeLists.txt
This commit fixes kernels CMakeLists file for onert-micro to move above `if ENABLE_TEST` statement 
for #11264
> [onert-micro] Fix kernels CMake file

- compiler/luci-value-test/test.lst
Conv2D_U8_000 sometimes fail cause of random input value.
This will raise tolerance for value difference.
> [luci-value-test] Raise tolernace for Conv2D_U8_000

- compiler/luci-compute/CMakeLists.txt
Let's add dependency to "NEON2SSE" source. It is used for TFLite x64 computation kernel.
> [luci-compute] Download neon-to-sse source

- compiler/luci-interpreter/include/luci_interpreter/core/Tensor.h
- compiler/luci-interpreter/pal/linux/PALConv2d.h
- compiler/luci-interpreter/src/SimpleMemoryManager.cpp
This fixes int32 overflow in large Conv2D.
---
Related to: #11582 
Draft PR: #11583
> [luci-interpreter] Fix int32 overflow in large Conv2D

- compiler/luci/pass/include/luci/CircleQuantizer.h
- compiler/luci/pass/src/CircleQuantizer.cpp
This will simplify methods with LayerParams type alias.
> [luci/pass] Introduce LayerParms

- compiler/common-artifacts/exclude.lst
This adds Net_FC_Gelu_FC_000 to exclude.lst.
---
> [common-artifacts] Exclude Net_FC_Gelu_FC

- compiler/one-cmds/tests/onnx_legalize_run_compare.py
- compiler/one-cmds/validate-onnx2circle/validate_onnx2circle.py
Thils will revise to add some options to prevent issues running onnxruntime.
> [one-cmds] Add onnxruntime InferenceSession options

- compiler/luci-interpreter/src/CMakeLists.txt
- compiler/luci-interpreter/src/SimpleMemoryManager.test.cpp
This adds tests for SimpleMemoryManager.
---
Related to: https://github.com/Samsung/ONE/issues/11582
Draft PR: https://github.com/Samsung/ONE/pull/11583
> [luci-interpreter] Add SimpleMemoryManager test

- compiler/circle-mpqsolver/CMakeLists.txt
- compiler/circle-mpqsolver/src/pattern/PatternResolver.cpp
- compiler/circle-mpqsolver/src/pattern/PatternResolver.h
- compiler/circle-mpqsolver/src/pattern/PatternResolver.test.cpp
This commit introduces PatternResolver aiming to convert all recognized LayerNorm patterns to prescribed quantization patterns.
Its correctness is tested at #11560.
Draft: #11560
> [circle-mpqsolver] Introduce PatternResolver

- compiler/circle-quantizer/src/CircleQuantizer.cpp
This will tidy unused OptionHook alias.
> [circle-quantizer] Tidy unused OptionHook

- infra/nncc/cmake/CfgOptionFlags.cmake
This commit changes DOWNLOAD_LIBNPY option ON for q-implant-op-level-test
ONE-DCO-1.0-Signed-off-by: Junyeong Kang kjy6135@naver.com
> [infra/q-implant] Change DOWNLOAD_LIBNPY option

- compiler/luci/pass/include/luci/CircleQuantizer.h
- compiler/luci/pass/src/CircleQuantizer.cpp
This will introduce LayerParamsSet type and layer_params_set getter/setter in CircleQuantizer::Options.
> [luci/pass] Introduce LayerParamsSet, layer_params_set getter/setter

- compiler/luci/pass/include/luci/CircleOptimizer.h
- compiler/luci/pass/src/CircleOptimizer.cpp
This adds ReplaceWithFCGeluFC algorithm to CircleOptimizer.
---
> [luci] Add ReplaceWithFCGeluFC algorithm

- compiler/one-cmds/tests/prepare_test_materials.sh
This will revise prepare_test_materials.sh to download test model for enabling alternate names for quntization.
> [one-cmds] Revise prepare_test_materials.sh

- compiler/circle-mpqsolver/CMakeLists.txt
- compiler/circle-mpqsolver/src/core/Dumper.test.cpp
- compiler/circle-mpqsolver/src/core/TestHelper.h
- compiler/circle-mpqsolver/src/core/TestHelper.test.cpp
This commit adds unit tests for Dumper.
Draft: #11452
> [circle-mpqsolver] Add Dumper unittests

- compiler/circle-quantizer/src/CircleQuantizer.cpp
This will enable to read alternate layer params.
> [circle-quantizer] Read alternate layer params

- compiler/q-implant/include/QImplant.h
- compiler/q-implant/src/QImplant.cpp
Operators(such as transpose, reshape and etc.) can be added while model conversion. Those operators are not present at original model, so corresponding quantization parameter could not exist on `qparam.json`. For those operators, forward quantization parameter to make appropriate graph.
ONE-DCO-1.0-Signed-off-by: WooJeong Jeong <wj6349@gmail.com>
> [q-implant] Quantization Parameter forward propagation

- compiler/circle-mpqsolver/src/MPQSolver.cpp
- compiler/circle-mpqsolver/src/MPQSolver.h
- compiler/circle-mpqsolver/src/bisection/BisectionSolver.cpp
- compiler/circle-mpqsolver/src/bisection/BisectionSolver.h
This commit moves _quantizer and read_module to parent class.
Its correctness is tested at https://github.com/Samsung/ONE/pull/11560.
Draft: https://github.com/Samsung/ONE/pull/11560
> [circle-mpqsolver] Refactor BisectionSolver

- compiler/circle-mpqsolver/CMakeLists.txt
- compiler/circle-mpqsolver/src/core/DumpingHooks.test.cpp
This commit adds unit tests for DumpingHooks.
Draft: https://github.com/Samsung/ONE/pull/11452
> [circle-mpqsolver] Add DumpingHooks unittests

- compiler/circle-mpqsolver/src/MPQSolver.h
This commit fixes typo in MPQSolver.h.
> [circle-mpqsolver] Fix typo

- compiler/circle-mpqsolver/src/MPQSolver.cpp
- compiler/circle-mpqsolver/src/MPQSolver.h
This commit introduces functionality needed for `pattern` quantization.
Its correctness is tested at https://github.com/Samsung/ONE/pull/11560.
Draft: https://github.com/Samsung/ONE/pull/11560
> [circle-mpqsolver] Revisit  MPQSolver

- compiler/one-cmds/tests/rawdata2hdf5_neg_004.test
This updates error message of rawdata2hdf5_neg_004 test.
---
Related to: https://github.com/Samsung/ONE/issues/11641
> [one-cmds] Update rawdata2hdf5_neg_004 error message

- compiler/circle-mpqsolver/CMakeLists.txt
- compiler/circle-mpqsolver/src/core/Evaluator.test.cpp
This commit adds negative unit test for Evaluator
to increase test converage.
> [circle-mpqsolver] Add evaluator unittest

- compiler/luci/pass/include/luci/CircleOptimizer.h
- compiler/luci/pass/include/luci/Pass/DecomposeSoftmaxPass.h
- compiler/luci/pass/src/CircleOptimizer.cpp
- compiler/luci/pass/src/DecomposeSoftmaxPass.cpp
- compiler/luci/pass/src/DecomposeSoftmaxPass.test.cpp
This commit implements decomposition of the Softmax operation to Max, Sub, Exp, Sum, Div and possibly Mul  operations.
Its correctness is tested at #11687.
Draft: #11687
Related: #11492
> [luci/pass] Implement Softmax decomposing pass

- compiler/circle-mpqsolver/src/MPQSolver.cpp
- compiler/circle-mpqsolver/src/MPQSolver.h
- compiler/circle-mpqsolver/src/pattern/PatternSolver.cpp
- compiler/circle-mpqsolver/src/pattern/PatternSolver.h
This commit introduces PatternSolver
to get optimal mixed precision model.
Its correctness is tested at https://github.com/Samsung/ONE/pull/11560.
Draft: https://github.com/Samsung/ONE/pull/11560
> [circle-mpqsolver] Introduce PatternSolver

- compiler/circle-mpqsolver/CMakeLists.txt
- compiler/circle-mpqsolver/src/bisection/BisectionSolver.test.cpp
This commit adds negative unit test for BisectionSolver to increase test coverage.
> [circle-mpqsolver] Add BisectionSolver unittest

- compiler/circle-mpqsolver/src/bisection/BisectionSolver.cpp
This commit excludes unnecessary search process when target error is out of reasonable bounds.
Its output for `qerror_ratio = 0.0` (q16) is:
```
...
>> Computing baseline qerrors
Full int16 model qerror: 9.25156e-05
Full uint8 model qerror: 0.000252629
Target qerror: 9.25156e-05
The best configuration is int16 configuration 
```
Its output for `qerror_ratio = 1.0` (q8) is:
```
...
>> Computing baseline qerrors
Full int16 model qerror: 9.25156e-05
Full uint8 model qerror: 0.000252629
Target qerror: 0.000252629
The best configuration is uint8 configuration 
```
> [circle-mpqsolver] Revisit  BisectionSolver

- res/TensorFlowLiteRecipes/Softmax_001/test.recipe
- res/TensorFlowLiteRecipes/Softmax_001/test.rule
- res/TensorFlowLiteRecipes/Softmax_002/test.recipe
- res/TensorFlowLiteRecipes/Softmax_002/test.rule
This commit adds two models for Softmax with unit/nonunit beta.
Its correctness is tested at #11687.
Draft: #11687
Related: #11492
> [res] TensorFlowLiteRecipes for Softmax decomposition

- compiler/circle2circle/src/Circle2Circle.cpp
This commit adds an option to enable decomposition of Softmax operation.
Its correctness is tested at https://github.com/Samsung/ONE/pull/11687.
Draft: https://github.com/Samsung/ONE/pull/11687
Related: https://github.com/Samsung/ONE/issues/11492
> [circle2circle] Add decompose_softmax option

- compiler/circle2circle-dredd-recipe-test/test.lst
This commit adds dredd tests for Softmax decomposition.
Its correctness is tested at https://github.com/Samsung/ONE/pull/11687.
Draft: https://github.com/Samsung/ONE/pull/11687
Related: https://github.com/Samsung/ONE/issues/11492
> [circle2circle-dredd-recipe-test] Add Softmax decompose tests

- compiler/luci-pass-value-test/test.lst
This commit adds value tests for Softmax decomposition.
Its correctness is tested at https://github.com/Samsung/ONE/pull/11687.
Draft: https://github.com/Samsung/ONE/pull/11687
Related: https://github.com/Samsung/ONE/issues/11492
> [luci-pass-value-test] Add Softmax decompose test

- compiler/circle-mpqsolver/src/CircleMPQSolver.cpp
This commit introduces --patterns option for circle-mpqsolver and implements --LayerNorm option using PatternSolver.
Its correctness is tested at https://github.com/Samsung/ONE/pull/11560.
Draft: https://github.com/Samsung/ONE/pull/11560
> [circle-mpqsolver] Use PatternSolver

- compiler/one-cmds/how-to-use-one-commands.txt
- compiler/one-cmds/onelib/constant.py
This commit enables decompose_softmax option for one-cmds optimize.
Locally after running build onecc:
```
[onecc]
one-import-tflite=False
one-import-tf=False
one-import-bcq=False
one-import-onnx=False
one-optimize=True
one-quantize=False
one-codegen=False
one-profile=False
[one-optimize]
input_path=/home/stanislav/repos/WorkSpaces/softmax/model_original.circle
output_path=/home/stanislav/repos/WorkSpaces/softmax/model_softmax.opt.circle
decompose_softmax=True
```
produced valid attached model:
[model_softmax.opt.zip](https://github.com/Samsung/ONE/files/12890814/model_softmax.opt.zip)
Draft: https://github.com/Samsung/ONE/pull/11687
Related: https://github.com/Samsung/ONE/issues/11492
> [one-cmds] Enable decompose_softmax

- compiler/circle-mpqsolver/src/CircleMPQSolver.cpp
- compiler/circle-mpqsolver/src/MPQSolver.h
- compiler/circle-mpqsolver/src/bisection/BisectionSolver.cpp
- compiler/circle-mpqsolver/src/bisection/BisectionSolver.h
- compiler/circle-mpqsolver/src/bisection/DepthParameterizer.test.cpp
- compiler/circle-mpqsolver/src/core/DumpingHooks.h
- compiler/circle-mpqsolver/src/core/SolverHooks.h
This commit replaces <...> includes by "..." includes for 'circle-mpqsolver' included modules.
> [circle-mpqsolver] Tidy includes

- compiler/one-cmds/one-quantize
This commit addd mixed_layernorm option to one-quantize.
Running locally the following config:
```
[onecc]
one-import-tflite=False
one-import-tf=False
one-import-bcq=False
one-import-onnx=False
one-optimize=False
one-quantize=True
one-codegen=False
one-profile=False
[one-quantize]
input_path=/home/stanislav/repos/WorkSpaces/LAYER_NORM/model.circle
output_path=/home/stanislav/repos/WorkSpaces/LAYER_NORM/model.q_opt.circle
ampq=True
ampq_algorithm=pattern
u8_layernorm_with_s16_variance=True
```
produced attached model:
[model.q_opt.zip](https://github.com/Samsung/ONE/files/12891362/model.q_opt.zip)
which seems to be a valid result.
> [one-cmds] Add mixed_layernorm option to one-quantize

- compute/cker/include/cker/train/operation/MaxPool.h
- compute/cker/src/train/MaxPool.test.cc
- runtime/onert/backend/cpu/ops/PoolLayer.h
- runtime/onert/backend/train/KernelGenerator.cc
- runtime/onert/backend/train/KernelGenerator.h
- runtime/onert/backend/train/ops/PoolLayer.cc
- runtime/onert/backend/train/ops/PoolLayer.h
- runtime/onert/core/include/compiler/StaticShapeInferer.h
- runtime/onert/core/src/compiler/StaticShapeInferer.cc
This PR is to enable max2d PoolLayer for training.
This PR fills unimplemented part of PoolLayer: 
* implements shape-inference visit() for pool2d
* implelments kernel-generator visit() for pool2d
* Implements train PoolLayer op's forward, backward functions and ckernel
ONE-DCO-1.0-Signed-off-by: SeungHui Youn <sseung.youn@samsung.com> 
---------------------------------------------------
related issue : https://github.com/Samsung/ONE/issues/11427 
from draft : https://github.com/Samsung/ONE/pull/11480
> [onert] Enable max2d PoolLayer for training

- onert-micro/luci-interpreter/src/kernels/Mean.cpp
This commit fixes arm building for Mean kernel.
for https://github.com/Samsung/ONE/pull/11661#issuecomment-1757400304
> [onert-micro] Fix arm building for Mean kernel

- runtime/onert/backend/gpu_cl/CMakeLists.txt
It fixes build fail on clang > =10 by "deprecated-copy" error.
---
Draft:#11712 (ndk > 21 uses clang >= 10)
> [onert/gpu_cl] Fix compile option for clang

- compiler/minmax-embedder/CMakeLists.txt
- compiler/minmax-embedder/README.md
- compiler/minmax-embedder/include/minmax-embedder/Embedder.h
- compiler/minmax-embedder/requires.cmake
- compiler/minmax-embedder/src/Embedder.cpp
- compiler/minmax-embedder/src/Embedder.test.cpp
- compiler/minmax-embedder/src/h5/Reader.cpp
- compiler/minmax-embedder/src/h5/Reader.h
It introduces minmax-embedder, which embedds minmax recording in hdf5 to circle.
Draft: #11649
- negative test run
```
39: [==========] Running 1 test from 1 test suite.
39: [----------] Global test environment set-up.
39: [----------] 1 test from MinMaxEmbedderTest
39: [ RUN      ] MinMaxEmbedderTest.invalid_input_NEG
39: Failed to open file: not_existing
39: [       OK ] MinMaxEmbedderTest.invalid_input_NEG (0 ms)
39: [----------] 1 test from MinMaxEmbedderTest (0 ms total)
39: 
39: [----------] Global test environment tear-down
39: [==========] 1 test from 1 test suite ran. (0 ms total)
39: [  PASSED  ] 1 test.
1/1 Test #39: minmax_embedder_test .............   Passed    0.01 sec
The following tests passed: …
```
> [CFE/minmax-embedder] Introduce minmax-embedder library

- tests/tools/onert_run/src/args.cc
- tests/tools/onert_run/src/args.h
- tests/tools/onert_run/src/onert_run.cc
- tests/tools/onert_run/src/rawformatter.cc
- tests/tools/onert_run/src/rawformatter.h
This commit adds the function to dump input raw dafa. It stores automatically generated input data.
draft: #10901
> [tools/onert_run] Add the function to dump input raw data

- infra/nnfw/cmake/packages/ARMComputeConfig.cmake
This commit fixes build fail by deprecated-copy warning on clang > 10 (ex. ndk > 21)
> [infra/acl] Fix build fail on clang

- compiler/luci/pass/include/luci/Pass/FuseSliceWithTConvPass.h
- compiler/luci/pass/src/FuseSliceWithTConvPass.cpp
- compiler/luci/pass/src/FuseSliceWithTConvPass.test.cpp
This commit introduces FuseSliceWithTConvPass
for fusing slice with tconv if possible.
Its correctness is tested at #11725.
Draft: #11725
> [luci/pass] Introduce FuseSliceWithTConvPass

- res/TensorFlowLiteRecipes/Net_TConv_Slice_000/test.recipe
- res/TensorFlowLiteRecipes/Net_TConv_Slice_000/test.rule
- res/TensorFlowLiteRecipes/Net_TConv_Slice_001/test.recipe
- res/TensorFlowLiteRecipes/Net_TConv_Slice_001/test.rule
- res/TensorFlowLiteRecipes/Net_TConv_Slice_002/test.recipe
- res/TensorFlowLiteRecipes/Net_TConv_Slice_002/test.rule
- res/TensorFlowLiteRecipes/Net_TConv_Slice_003/test.recipe
- res/TensorFlowLiteRecipes/Net_TConv_Slice_003/test.rule
This commit adds models for testing TConv->Slice fusion with various parameters.
Its correctness is tested at https://github.com/Samsung/ONE/pull/11725.
Draft: https://github.com/Samsung/ONE/pull/11725
> [res] TensorFlowLiteRecipes for TConv->Slice fusion

- tests/tools/onert_train/src/args.cc
This commit changes the default learning rate value to 0.001.
> [tools/onert_train] Change default learning rate

- compiler/circledump/src/OpPrinter.cpp
OpPrinter printed enum value, not enum name for Padding.
It caused circledump's output as binary.
Now, it will print enum Padding name.
Related: https://github.com/Samsung/ONE/pull/11699#issuecomment-1772717795
With this PR, padding is printed correctly.
```
$ circledump Net_Conv_Relu6_000.circle
...
O(0:0) CONV_2D 
Padding(^@) Stride.W(1) Stride.H(1) Dilation.W(1) Dilation.H(1) Activation(NONE)
I T(0:0) Placeholder
I T(0:1) Conv2D_1
I T(0:2) Conv2D_2
O T(0:4) Conv2D_11
O(0:1) RELU6 
I T(0:4) Conv2D_11
O T(0:5) ReLU6
O(0:2) CONV_2D 
Padding(^@) Stride.W(1) Stride.H(1) Dilation.W(1) Dilation.H(1) Activation(NONE)
I T(0:5) ReLU6
I T(0:3) Conv2D_21
I T(0:2) Conv2D_2
O T(0:6) Conv2D_22
O(0:3) RELU6 
I T(0:6) Conv2D_22
O T(0:7) …
```
> [circledump] OpPrinter should print enum name for Padding

- compiler/luci/pass/include/luci/CircleOptimizer.h
- compiler/luci/pass/src/CircleOptimizer.cpp
This commit introduces FuseSliceWithTConv option.
Its correctness is tested at https://github.com/Samsung/ONE/pull/11725.
Draft: https://github.com/Samsung/ONE/pull/11725
> [luci] Introduce FuseSliceWithTConv

- docs/nnfw/howto/CrossBuildForAndroid.md
- tools/cross/install_android_ndk.sh
- tools/cross/install_android_sdk.sh
This commit updates android SDK & NDK install script
- Remove NDK install path workaround for TFLite 1.13.1
- Update SDK initial commandline tool version to same version with dockerfile
- Update SDK commandline tool install process for easy version up
- Update runtime android build documentation
> [tools] Update android SDK & NDK install script

- compiler/tflchef/proto/tflchef.proto
This introduces extype and custom_code for custom operators.
---
> [tflchef] Introduce extype and custom_code for custom operators

- compiler/circlechef/proto/circlechef.proto
This introduces extype and custom_code for custom operators.
---
> [circlechef] Introduce extype and custom_code for custom operators

- compiler/circle2circle/src/Circle2Circle.cpp
This commit adds an option to enable fusion of Slice to TConv.
Its correctness is tested at https://github.com/Samsung/ONE/pull/11725.
Draft: https://github.com/Samsung/ONE/pull/11725
> [luci/pass] Add fuse_slice_with_tconv option

- compiler/tfldump/src/OpPrinter.cpp
OpPrinter printed enum value, not enum name for Padding. It caused tfldump's output as binary.
Now, it will print enum Padding name.
It is a twin PR for `tfldump`.
Related: #11749
> [tfldump] OpPrinter should print enum name for Padding

- runtime/onert/python/api/CMakeLists.txt
This commit resolves python binding API build issue on cross build.
> [onert/python] Fix build issue on cross build

- compiler/luci/pass/include/luci/Pass/RemoveUnnecessaryAddPass.h
- compiler/luci/pass/src/RemoveUnnecessaryAddPass.cpp
- compiler/luci/pass/src/RemoveUnnecessaryAddPass.test.cpp
This commit introduces RemoveUnnecessaryAddPass
for removing Add node with zero constant operand and without activation.
Its correctness is tested at https://github.com/Samsung/ONE/pull/11770.
Draft: https://github.com/Samsung/ONE/pull/11770
Related: https://github.com/Samsung/ONE/issues/10358
> [luci/pass] Introduce RemoveUnnecessaryAddPass

- compute/cker/include/cker/train/operation/SoftMax.h
- compute/cker/src/train/SoftMax.test.cc
This commit introduces SoftMaxGrad function in cker. This commit follows the derivative formula below.
dsoftmax(xi)/dxj = softmax(xi) * (1 - softmax(xi)) (if i == j)
-softmax(xi)*softmax(xj) (if i != j)
Draft: #11742 
Gradient formula: https://github.com/Samsung/ONE/issues/11248#issuecomment-1774675483
> [onert] Introduce SoftMaxGrad function in cker

- compiler/luci/pass/src/QuantizeWeightsOnly.cpp
- compiler/luci/pass/src/QuantizeWeightsOnly.h
This commit supports QuantizeWeightsOnly for FullyConnected.
for issue:  #11772
> [one-quantize] Support QuantizeWeightsOnly for FullyConnected

- compiler/luci/pass/include/luci/CircleQuantizer.h
- compiler/luci/pass/include/luci/Pass/QuantizeWithMinMaxPass.h
- compiler/luci/pass/src/CircleQuantizer.cpp
- compiler/luci/pass/src/PropagateQParamForwardPass.cpp
- compiler/luci/pass/src/QuantizationUtils.cpp
- compiler/luci/pass/src/QuantizationUtils.h
- compiler/luci/pass/src/QuantizeActivation.cpp
- compiler/luci/pass/src/QuantizeWeights.cpp
- compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
- compiler/luci/pass/src/QuantizeWithMinMaxPass.test.cpp
This commit adds saving recorded min-max values.
for issue: https://github.com/Samsung/ONE/issues/11717
from draft: #11730
> [luci/pass] Add saving recorded min-max

- compiler/one-cmds/how-to-use-one-commands.txt
- compiler/one-cmds/onelib/constant.py
This commit enables fuse_slice_with_tconv option for one-cmds optimize.
Its correctness is tested at https://github.com/Samsung/ONE/pull/11725.
Draft: https://github.com/Samsung/ONE/pull/11725
> [one-cmds] Enable fuse_slice_with_tconv

- res/TensorFlowLiteRecipes/Net_Horizontal_FullyConnected_Add_000/test.recipe
- res/TensorFlowLiteRecipes/Net_Horizontal_FullyConnected_Add_000/test.rule
This commit adds models for testing horizontal FC pattern fusion.
for issue: https://github.com/Samsung/ONE/issues/11705
from draft: https://github.com/Samsung/ONE/pull/11739
> [res] TensorFlowLiteRecipes for horizontal FC pattern fusion

- res/TensorFlowLiteRecipes/Net_Mul_Add_000/test.recipe
- res/TensorFlowLiteRecipes/Net_Mul_Add_000/test.rule
- res/TensorFlowLiteRecipes/Net_Mul_Add_001/test.recipe
- res/TensorFlowLiteRecipes/Net_Mul_Add_001/test.rule
- res/TensorFlowLiteRecipes/Net_Mul_Add_002/test.recipe
- res/TensorFlowLiteRecipes/Net_Mul_Add_002/test.rule
- res/TensorFlowLiteRecipes/Net_Mul_Add_003/test.recipe
- res/TensorFlowLiteRecipes/Net_Mul_Add_003/test.rule
This commit adds models for testing unnecessary Add removal with various parameters.
Its correctness is tested at https://github.com/Samsung/ONE/pull/11770.
Draft: https://github.com/Samsung/ONE/pull/11770
Related: https://github.com/Samsung/ONE/issues/10358
> [res] TensorFlowLiteRecipes for unnecessary Add removal

- compiler/circle-quantizer/src/CircleQuantizer.cpp
This commit adds an option to enable saving min and max values
for issue: https://github.com/Samsung/ONE/issues/11717
from draft: https://github.com/Samsung/ONE/pull/11730
> [circle-quantizer] Add save_min_max option

- compiler/circle2circle/src/Circle2Circle.cpp
This commit adds an option to enable removal of
unnecessary add of zero constant.
Its correctness is tested at https://github.com/Samsung/ONE/pull/11770.
Draft: https://github.com/Samsung/ONE/pull/11770
Related: https://github.com/Samsung/ONE/issues/10358
> [circle2circle] Add remove_unnecessary_add option

- compiler/luci-value-test/test.lst
This will fix Conv2D_U8_000 to use addevaltol()
> [luci-value-test] Fix to use addevaltol

- compiler/one-cmds/onelib/constant.py
This commit adds fuse_slice_with_tconv option to O1 group.
Running the following `.cfg`:
```
[onecc]
one-optimize=True
include=O1
[one-optimize]
input_path=/home/stanislav/repos/WorkSpaces/fuse_tconv_slice/model_original.circle
output_path=/home/stanislav/repos/WorkSpaces/fuse_tconv_slice/model_fused_6.opt.circle
```
successfully produced `model_fused_6.opt.circle` model without Slice.
Please see attachment:
[test_pass.zip](https://github.com/Samsung/ONE/files/13187379/test_pass.zip)
Related: #10960
> [one-cmds] Add fuse_slice_with_tconv to O1 group

- compiler/circle-mpqsolver/src/core/ErrorMetric.cpp
- compiler/circle-mpqsolver/src/core/ErrorMetric.test.cpp
This commit introduces two more unitests for MAEMetric.
> [circle-mpqsolver] Add more unitests for MAEMetric

- compiler/circle-mpqsolver/src/core/ErrorMetric.cpp
- compiler/circle-mpqsolver/src/pattern/PatternResolver.cpp
This commit uses capital letters in exception messages where applicable.
---
original: https://github.com/Samsung/ONE/pull/11805#discussion_r1374243457
> [circle-mpqsolver] Normalize exceptions

- compiler/one-cmds/how-to-use-one-commands.txt
- compiler/one-cmds/onelib/constant.py
This commit enables remove_unnecessary_add option for one-cmds optimize.
Its correctness is tested at https://github.com/Samsung/ONE/pull/11770.
Draft: https://github.com/Samsung/ONE/pull/11770
Related: https://github.com/Samsung/ONE/issues/10358
> [one-cmds] Enable remove_unnecessary_add

- compiler/circle-mpqsolver/src/pattern/PatternResolver.cpp
- compiler/circle-mpqsolver/src/pattern/PatternResolver.h
- compiler/circle-mpqsolver/src/pattern/PatternResolver.test.cpp
This commit introduces Q8SoftmaxWithQ16SubExpResolver aiming to convert recognized SoftMax patterns to prescribed quantization patterns and adds tests for it.
Draft: #11737
Related: #11543
> [circle-mpqsolver] Introduce Q8SoftmaxWithQ16SubExpResolver

- compiler/circle-mpqsolver/src/pattern/PatternSolver.cpp
- compiler/circle-mpqsolver/src/pattern/PatternSolver.h
This commit introduces Q8SoftmaxWithQ16SubExp option to resolve all nodes of Softmax pattern as prescribed.
Its correctness is tested #11737.
Draft: https://github.com/Samsung/ONE/pull/11737
> [circle-mpqsolver] Introduce Q8SoftmaxWithQ16SubExp

- compiler/tflchef/core/src/CustomOp/AddV2.cpp
- compiler/tflchef/core/src/CustomOp/All.cpp
- compiler/tflchef/core/src/CustomOp/BatchMatMulV2.cpp
- compiler/tflchef/core/src/CustomOp/BroadcastTo.cpp
- compiler/tflchef/core/src/CustomOp/Erf.cpp
- compiler/tflchef/core/src/CustomOp/MatMul.cpp
- compiler/tflchef/core/src/CustomOp/MatrixBandPart.cpp
- compiler/tflchef/core/src/CustomOp/MaxPoolWithArgmax.cpp
- compiler/tflchef/core/src/OpUtils.cpp
- compiler/tflchef/core/src/OpUtils.h
This introduces a function that check codes of CustomOp to avoid duplication.
---
> [tflchef] Introduce a op util function to check custom codes

- infra/nnfw/config/gbs.conf
This commit adds tizen 8.0 profile to gbs.conf.
> [infra/gbs] Add tizen 8.0 profile

- compiler/circle-mpqsolver/src/CircleMPQSolver.cpp
This commit introduces  --u8_softmax_with_s16_sub_exp command line option to quantize Softmax patterns.
Its correctness is tested https://github.com/Samsung/ONE/pull/11737.
Draft: https://github.com/Samsung/ONE/pull/11737
> [circle-mpqsolver] Introduce u8_softmax_with_s16_sub_exp

- compute/cker/src/train/SoftMax.test.cc
This commit changes the incorrect array size of the cker test case.
Also, changes abs_error value so that the unittest does not fail.
The abs_error must be modified to use EXPECT_FLOAT_EQUAL.
Fixed #11821
> [onert] Change invalid array size in Cker test case

- compiler/circle2circle/src/Circle2Circle.cpp
This commit adds fuse_horizontal_fc_layers option to circle2circle.
for issue: https://github.com/Samsung/ONE/issues/11705
from draft: https://github.com/Samsung/ONE/pull/11739
> [circle2circle] Add fuse_horizontal_fc_layers option

- Makefile.template
This commit simplifies Makefile target dependency. 
It enables ODC build as default on native linux build.
> [infra] Update Makefile target dependency

- compiler/circle-mpqsolver/src/MPQSolver.cpp
- compiler/circle-mpqsolver/src/bisection/BisectionSolver.cpp
- compiler/circle-mpqsolver/src/bisection/BisectionSolver.test.cpp
- compiler/circle-mpqsolver/src/pattern/PatternSolver.cpp
This commit throws error on every failure to load circle model and changes tests accordingly.
Related: #11702
> [circle-mpqsolver] Revise error message

- compiler/circle-mpqsolver/CMakeLists.txt
- compiler/circle-mpqsolver/src/core/TestHelper.h
- compiler/circle-mpqsolver/src/core/TestHelper.test.cpp
- compiler/circle-mpqsolver/src/pattern/PatternResolver.test.cpp
- compiler/circle-mpqsolver/src/pattern/PatternSolver.test.cpp
This commit adds unitests for PassSolver and
moves SoftmaxTestGraph to TestHelper.
> [circle-mpqsolver] Add PassSolver unittests

- compiler/one-cmds/one-quantize
This commit adds u8_softmax_with_s16_sub_exp option to one-quantize.
Its correctness is tested https://github.com/Samsung/ONE/pull/11737.
Draft: https://github.com/Samsung/ONE/pull/11737
> [one-cmds] Add u8_softmax_with_s16_sub_exp

- compiler/one-cmds/how-to-use-one-commands.txt
- compiler/one-cmds/onelib/constant.py
This commit enables fuse_horizontal_fc_layers option for one-cmds optimize.
for issue: https://github.com/Samsung/ONE/issues/11705
from draft: https://github.com/Samsung/ONE/pull/11739
> [one-cmds] Enable fuse_horizontal_fc_layers

- compiler/luci/pass/include/luci/CircleOptimizer.h
- compiler/luci/pass/src/CircleOptimizer.cpp
This supports CSE option to circle optimizer.
---
> [luci] Support CommonSubExpressionElimination option

- res/TensorFlowLiteRecipes/CSE_Quantize_000/test.recipe
- res/TensorFlowLiteRecipes/CSE_Quantize_000/test.rule
- res/TensorFlowLiteRecipes/CSE_Quantize_001/test.recipe
- res/TensorFlowLiteRecipes/CSE_Quantize_001/test.rule
This adds recipes for CSE one Quantize Ops.
---
> [res] Add recipes for CSE on Quantize Ops

- compiler/one-cmds/tests/one-quantize_023.test
- compiler/one-cmds/tests/one-quantize_neg_024.test
- compiler/one-cmds/tests/prepare_test_materials.sh
- compiler/one-cmds/tests/rawdata2hdf5_002.test
This adds tests for multi-input quantization dataset.
---
Related to: https://github.com/Samsung/ONE/issues/11724
Draft PR: https://github.com/Samsung/ONE/pull/11831
> [one-cmds] Add multi-input quantization dataset test

- compiler/tflchef/core/src/ModelChef.cpp
- compiler/tflchef/tests/custom_erf/test.recipe
This introduces extype and custom_code for custom operators.
---
> [tflchef] Use extype and custom_code type for custom operators

- compiler/circle2circle/src/Circle2Circle.cpp
This adds common subexpression elimination option.
---
> [circle2circle] Add common subexpression elimination option

- compiler/circlechef/core/src/ModelChef.cpp
This commit includes replacing op type with custom_code if op_type is Custom or extype is Custom.
---
> [circlechef] Use extype and custom_code for custom operators

- compiler/luci-pass-value-test/test.lst
This adds test for CSE_Quantize_000.
---
> [luci-pass-value-test] Add CSE_Quantize_000

- compiler/one-cmds/how-to-use-one-commands.txt
- compiler/one-cmds/onelib/constant.py
This adds cse option to one-optimize.
---
> [one-cmds] Add common_subexpression_elimination option

- compiler/tflchef/core/src/OpUtils.cpp
This commit is for refactoring check_custom_op_value function in OpUtils. 
First, the extype is used for a while and will be removed later. 
Second, it is unnecessary to check the state of custom_code because the default value always exists.
---
> [tflchef] Refactor check_custom_op_value in OpUtils

- compiler/record-minmax/src/RecordMinMax.cpp
This fixes a bug in handling multi-input data.
---
Related to: https://github.com/Samsung/ONE/issues/11777#issuecomment-1788530346
> [record-minmax] Fix multi-input data handling

- compiler/one-cmds/onelib/constant.py
This commit adds fuse_horizontal_fc_layers to O1 group.
for issue: https://github.com/Samsung/ONE/issues/11705
> [one-cmds] Add fuse_horizontal_fc_layers to O1

- compiler/one-cmds/one-quantize
- compiler/one-cmds/tests/one-quantize_024.test
This adds save_min_max option to one-quantize.
---
Related to: https://github.com/Samsung/ONE/issues/11717
> [one-cmds] Add save_min_max option to one-quantize

- compiler/circle2circle-dredd-recipe-test/test.lst
This adds CSE tests for Quantize Op.
---
> [circle2circle-dredd] Add CSE_Quantize tests

- res/TensorFlowLiteRecipes/All_000/test.recipe
- res/TensorFlowLiteRecipes/BatchMatMulV2_000/test.recipe
- res/TensorFlowLiteRecipes/BatchMatMulV2_001/test.recipe
- res/TensorFlowLiteRecipes/BroadcastTo_000/test.recipe
- res/TensorFlowLiteRecipes/MatMul_000/test.recipe
- res/TensorFlowLiteRecipes/MatrixBandPart_000/test.recipe
- res/TensorFlowLiteRecipes/MaxPoolWithArgmax_000/test.recipe
- res/TensorFlowLiteRecipes/MaxPoolWithArgmax_001/test.recipe
- res/TensorFlowLiteRecipes/MaxPoolWithArgmax_002/test.recipe
- res/TensorFlowLiteRecipes/Net_BroadcastTo_AddV2_000/test.recipe
- res/TensorFlowLiteRecipes/Net_BroadcastTo_AddV2_001/test.recipe
- res/TensorFlowLiteRecipes/Net_FC_Gelu_FC_000/test.recipe
- res/TensorFlowLiteRecipes/Net_Gather_SparseToDense_AddV2_000/test.recipe
- res/TensorFlowLiteRecipes/Net_Gelu_000/test.recipe
- res/TensorFlowLiteRecipes/Net_Gelu_001/test.recipe
This commit includes removing extype and changing type to Custom if op type is a custom op.
---
> [res] Remove extype and Change type value to Custom for custom operators

- infra/nnfw/cmake/packages/Pybind11Config.cmake
Pybind11Config includes ExternalBuildTools for add_extdirectory. But it should be ExternalProjectTools.
> [infra/nnfw] include ExternalProjectTools in Pybind11Config

- compiler/circlechef/core/src/ModelChef.cpp
- compiler/circlechef/proto/circlechef.proto
This commit includes removing extype used for custom op because it is no longer necessary.
---
> [circlechef] Remove extype used for custom op

- compiler/luci/pass/src/CommonSubExpressionEliminationPass.cpp
- compiler/luci/pass/src/helpers/ExpressionCache.cpp
- compiler/luci/pass/src/helpers/ExpressionCache.h
- compiler/luci/pass/src/helpers/ExpressionCache.test.cpp
This uses input feature map in CSE expression.
---
Related to: https://github.com/Samsung/ONE/issues/11726
Draft PR: #11869
> [luci] Use input feature map in CSE expression.

- compiler/tflchef/core/src/ModelChef.cpp
- compiler/tflchef/core/src/OpUtils.cpp
- compiler/tflchef/proto/tflchef.proto
- compiler/tflchef/tests/custom_erf/test.recipe
This commit includes removing extype used for custom op because it is no longer necessary.
---
> [tflchef] Remove extype used for custom op

- compiler/common-artifacts/exclude.lst
This disables the test of CumSum operation until it's fully supported.
---
Realated w/ : https://github.com/Samsung/ONE/issues/11842
> [common-artifacts] Exclude CumSum operation

- compiler/one-cmds/onelib/constant.py
This adds missing comma in constant.py.
---
Related to: https://github.com/Samsung/ONE/issues/11777#issuecomment-1794041987
> [one-cmds] Add missing comma

- infra/nncc/cmake/CfgOptionFlags.cmake
This will introduce ENABLE_EXCLUDE_ME option to disable "exclude.me" flag.
> [infra/nncc] Introduce ENABLE_EXCLUDE_ME option

- compiler/CMakeLists.txt
This will enable to check exclude.me file to exclude the module.
> [compiler] Check exclude.me and exclude

- compiler/common-artifacts/exclude.lst
This adds Broadcast_To_001 to exclude.lst.
---
> [common-artifacts] Exclude Broadcast_To

- compiler/circle2circle-dredd-recipe-test/test.lst
This adds tests for CSE Transpose.
---
Related to: https://github.com/Samsung/ONE/issues/11726
Draft PR: https://github.com/Samsung/ONE/pull/11869
> [circle2circle-dredd-test] Add CSE_Transpose test

- compiler/luci-pass-value-test/test.lst
This adds a test for CSE_Transpose.
---
Related to: https://github.com/Samsung/ONE/issues/11726
Draft PR: https://github.com/Samsung/ONE/pull/11869
> [luci-pass-value-test] Add CSE_Transpose test

- compiler/luci/pass/src/CommonSubExpressionEliminationPass.test.cpp
This fixes index value in CSE Quantize test.
> [luci] Fix CSE Quantize test

- compiler/circlechef/requires.cmake
This will tidy nnkit from requires.cmake.
> [circlechef] Tidy nnkit from requires.cmake

- compiler/tflchef/requires.cmake
This will tidy nnkit from requires.cmake.
> [tflchef] Tidy nnkit from requires.cmake

- compiler/common-artifacts/exclude.lst
This disables the test of BroadcastTo operation until it's fully supported.
---
> [common-artifacts] Exclude BroadcastTo operation

- compiler/luci/export/src/CircleBuiltinTypesExtractor.h
- compiler/luci/export/src/CircleOps.lst
This adds support for CumSum operation in luci export.
---
Realated w/ : #11842 
Draft PR : #11810
> [luci/export] Support CumSum operation

- res/TensorFlowLiteRecipes/CumSum_000/test.recipe
This adds a TensorFlowLiteRecipes for CumSum operation.
---
Realated w/ : https://github.com/Samsung/ONE/issues/11842
Draft PR : https://github.com/Samsung/ONE/pull/11810
> [res] Add a TensorFlowLiteRecipes for CumSum

- compiler/common-artifacts/exclude.lst
This enables the test of cirlce optimization generation for CumSum op.
---
Realated w/ : #11842
> [common-artifacts] Enable optimization test for CumSum operation

- compiler/tflchef/core/src/OpUtils.cpp
- compiler/tflchef/core/src/OpUtils.h
This will revise check_custom_op_value with reference parameters to reduce stack memory.
> [tflchef] Revise check_custom_op_value parameters

- compiler/common-artifacts/exclude.lst
This removes CumSum operation from the exclude list.
---
Realated w/ : #11842
> [common-artifacts] Enable CumSum operation

- compiler/mir/src/mir_onnx_importer/CMakeLists.txt
This will revise to skip mir_onnx_importer build if interpreter is absent.
> [mir] Skip mir_onnx_importer build if no interpreter

- compiler/luci/pass/src/ReplaceNonConstFCWithBatchMatMulPass.cpp
- compiler/luci/pass/src/ReplaceNonConstFCWithBatchMatMulPass.test.cpp
This skips replace_non_const_fc_with_batch_matmul for const inputs.
---
Related to: https://github.com/Samsung/ONE/discussions/11941
> [luci] Skip replace_non_const_fc_with_batch_matmul for const inputs

- compiler/circle-mpqsolver/src/CircleMPQSolver.cpp
- compiler/circle-mpqsolver/src/MPQSolver.cpp
- compiler/circle-mpqsolver/src/MPQSolver.h
- compiler/circle-mpqsolver/src/core/Quantizer.cpp
- compiler/circle-mpqsolver/src/core/Quantizer.h
- compiler/circle-mpqsolver/src/pattern/PatternSolver.cpp
- compiler/circle-mpqsolver/src/pattern/PatternSolver.h
- compiler/circle-mpqsolver/src/pattern/PatternSolver.test.cpp
This adds more options to sync with one-quantize.
---
Related to: #11943
Draft PR: https://github.com/Samsung/ONE/pull/11977
> [circle-mpqsolver] Sync options with one-quantize

- res/TensorFlowLiteRecipes/Net_Trans_Reshape_Trans_000/test.recipe
- res/TensorFlowLiteRecipes/Net_Trans_Reshape_Trans_000/test.rule
This PR adds models for testing RemoveUnnecessaryTransposeNetPass.
* to resovle : https://github.com/Samsung/ONE/issues/11654 
* from draft : #11891 
> [res] Add TensorFlowLiteRecipes for TransposeReshapeTranspose pattern

- runtime/onert/core/src/ir/OperationValidator.cc
This commit allows uint8 BatchMatMul in OperationValidator.
> [onert] Allow uint8 BatchMatMul

- tests/tools/onert_train/src/args.cc
It makes data_length option mandatory not to make the user suprised.
Related: https://github.com/Samsung/ONE/issues/11892#issuecomment-1797888717
> [onert_train] Make data_length option mandatory

- runtime/onert/backend/cpu/ops/ElementwiseActivationLayer.cc
This commit fixes typo on cpu backend error message for Tanh.
> [onert] Fix typo Tanh error message

- compiler/one-cmds/one-quantize
This gives more parameters to circle-mpqsolver.
- quantized_dtype
- granularity
- TF-style_maxpool
- save_min_max
---
Related to: https://github.com/Samsung/ONE/issues/11943
Draft PR: https://github.com/Samsung/ONE/pull/11977
> [one-cmds] Add options to circle-mpqsolver

- compute/cker/include/cker/eigen/eigen_backward_spatial_convolutions.h
- compute/cker/include/cker/train/operation/Conv.h
- compute/cker/src/train/Conv.test.cc
This commit brings Conv2D kernels from tensorflow v2.12.1.
- Bring Conv2D kernels
- Add unit tests
> [cker] Bring Conv2D kernels from tensorflow v2.12.1

- runtime/onert/backend/cpu/KernelGenerator.cc
- runtime/onert/backend/cpu/ops/ConvolutionLayer.cc
- runtime/onert/backend/cpu/ops/ConvolutionLayer.h
- runtime/onert/backend/train/ops/ConvolutionLayer.cc
This commit introduces a boolean param whether to check whether to cache weights for ConvolutionLayer of cpu backend.
> [onert] Adjust whether to cache cpu conv weights

- compiler/circle2circle/src/Circle2Circle.cpp
This PR adds remove_unnecessary_transpose option to circle2circle.
* to resovle : https://github.com/Samsung/ONE/issues/11654 
* from draft : #11891  
> [circle2circle] Add remove_unnecessary_transpose option

- compiler/common-artifacts/exclude.lst
This adds BroadcastTo_002 to exclude.lst.
---
> [common-artifacts] Exclude BroadcastTo_002

- infra/command/docker-run
- infra/config/docker.configuration
This commit updates docker-run command.
- Remove cleanup function: docker image is using userID
- Set default docker image's ubuntu version
- Get more env variable from host
- EXTERNAL_DOWNLOAD_SERVER
- EXTERNAL_SERVER_USERPWD
- MODELFILE_SERVER
> [infra/command] Update docker-run and config

- runtime/onert/core/src/compiler/train/TrainingCompiler.h
It fixes the wrong description of params.
> [onert] Fix wrong doxygen comment in TrainingCompiler

- compiler/luci/import/include/luci/Import/Nodes.h
- compiler/luci/import/include/luci/Import/Nodes/CircleBroadcastTo.h
- compiler/luci/import/src/GraphBuilderRegistry.cpp
- compiler/luci/import/src/Nodes/CircleBroadcastTo.cpp
This supports import of BroadcastTo Op.
---
> [luci/import] Support BroadcastTo operation

- compiler/mir/src/mir_onnx_importer/CMakeLists.txt
This will revise to exlude mir_onnx_importer when ENABLE_EXCLUDE_ME is ON.
> [mir] Exclude mir_onnx_importer with condition

- runtime/onert/core/src/exec/train/TrainableExecutor.cc
This commit fixes bug in TrainableExecutor constructor referencing `tensor_regs` after move.
---
Draft: #12013
> [onert/train] Fix reference after move

- compiler/one-cmds/how-to-use-one-commands.txt
- compiler/one-cmds/onelib/constant.py
This PR enables remove_unnecessary_transpose for one-cmds.
* to resovle : https://github.com/Samsung/ONE/issues/11654 
* from draft : #11891  
> [one-cmds] Enable remove_unnecessary_transpose

- tests/tools/onert_train/src/args.cc
- tests/tools/onert_train/src/args.h
- tests/tools/onert_train/src/onert_train.cc
- tests/tools/onert_train/src/rawdataloader.cc
- tests/tools/onert_train/src/rawdataloader.h
- tests/tools/onert_train/test/rawdataloader.test.cc
This commit removes data_length input parameter. It calcaulates the data length value using the input and expected data files.
Related comment: https://github.com/Samsung/ONE/issues/11892#issuecomment-1797888717
> [tools/onert_train] Remove data_length parameter from onert_train tool

- compute/cker/include/cker/Types.h
This commit defines initial value of struct PoolParams fields.
---
Draft: #12013
> [cker] Set struct PoolParams initial value

- runtime/onert/core/src/compiler/train/TrainingCompiler.cc
- runtime/onert/core/src/dumper/dot/DotDumper.cc
- runtime/onert/core/src/dumper/dot/DotDumper.h
It supports dot dumping for TrainableGraph during TrainingCompiler's compilation.
```
$ GRAPH_DOT_DUMP=1 \
Product/x86_64-linux.debug/out/bin/onert_train \
mnist.circle \
--load_input:raw mnist_train.i160.bin \
--load_expected:raw mnist_train.o160.bin \
--optimizer 1 \
--data_length 160 \
--epoch 1
$ ls *.dot
-rw-rw-r-- 1 gyu gyu  578 Nov 14 10:57 after_loss_insertion-0.dot
-rw-rw-r-- 1 gyu gyu 2061 Nov 14 10:52 after_lower_subg-0.dot
-rw-rw-r-- 1 gyu gyu  843 Nov 14 10:52 before_loss_insertion-0.dot
```
(I will upload the screenshot after I got to home.)
You can see the graph in dumped dot by downloading `.dot` and opening with `xdot` or something.
[training_dots.tar.gz](https://github.com/Samsung/ONE/files/13343736/training_dot …
> [onert] Support TrainableGraph dump in dot

- compute/cker/include/cker/train/operation/Loss.h
- compute/cker/src/train/Loss.test.cc
This commit introduces Categorical Cross Entropy forward and backward kernels.
Draft: #11769 
Related issue: #11857
> [onert] Introduce CategoricalCrossEntropy kernel

- infra/scripts/compiler_modules.sh
- infra/scripts/configure_collect_nnpkgs.sh
- infra/scripts/docker_collect_nnpkg_resources.sh
This commit updates "docker_collect_nnpkg_resources.sh" to split nncc configure. 
New configure script "configure_collect_nnpkgs.sh" has similar style with "configure_compiler_coverage.sh". 
"docker_collect_nnpkg_resources.sh" will be removed.
> [infra] Revise nnpackage collection script

- res/TensorFlowLiteRecipes/Net_Conv_Mul_000/test.recipe
- res/TensorFlowLiteRecipes/Net_Conv_Mul_000/test.rule
- res/TensorFlowLiteRecipes/Net_Conv_Mul_001/test.recipe
- res/TensorFlowLiteRecipes/Net_Conv_Mul_001/test.rule
- res/TensorFlowLiteRecipes/Net_Conv_Mul_002/test.recipe
- res/TensorFlowLiteRecipes/Net_Conv_Mul_002/test.rule
- res/TensorFlowLiteRecipes/Net_Conv_Mul_003/test.recipe
- res/TensorFlowLiteRecipes/Net_Conv_Mul_003/test.rule
This commit adds models for testing Conv->Mul fusion with various parameters.
Its correctness is tested in https://github.com/Samsung/ONE/pull/11991.
Draft: https://github.com/Samsung/ONE/pull/11991
Related: https://github.com/Samsung/ONE/issues/11897
> [res] TensorFlowLiteRecipes for Conv->Mul fusion

- runtime/onert/backend/train/TensorManager.cc
- runtime/onert/backend/train/TensorManager.h
This commit aligns train tensor buffers with EIGEN_MAX_ALIGN_BYTES value. Some functions in the eigen library generate the assertion on unaligned arrays.
Fixed #11860
> [onert] Align train tensor buffers with EIGEN_MAX_ALIGN_BYTES value

- compiler/luci/pass/include/luci/CircleOptimizer.h
- compiler/luci/pass/src/CircleOptimizer.cpp
This commit introduces FuseMulWithConv option.
Its correctness is tested in https://github.com/Samsung/ONE/pull/11991.
Draft: https://github.com/Samsung/ONE/pull/11991
Related: https://github.com/Samsung/ONE/issues/11897
> [luci] Introduce FuseMulWithConv

- compiler/luci/partition/include/luci/ConnectNode.h
- compiler/luci/partition/src/Nodes/CircleBroadcastTo.cpp
- compiler/luci/partition/src/Nodes/CircleBroadcastTo.test.cpp
This supports BroadcastTo in luci partition.
---
> [luci/partition] Support BroadcastTo

- compiler/circle2circle/src/Circle2Circle.cpp
This commit adds fuse_mul_with_conv option to circle2circle.
Its correctness is tested in https://github.com/Samsung/ONE/pull/11991.
Draft: https://github.com/Samsung/ONE/pull/11991
Related: https://github.com/Samsung/ONE/issues/11897
> [circle2circle] Add fuse_mul_with_conv option

- compiler/dio-hdf5/include/dio_hdf5/HDF5Importer.h
- compiler/dio-hdf5/src/HDF5Importer.cpp
This commit declares methods of HDF5Importer as const where it's possible.
Draft: #11849
Related: #11374 
> [dio-hdf5] Revisit HDF5Importer

- res/TensorFlowLiteRecipes/BroadcastTo_001/test.recipe
This adds a recipe file for builtin BroadcastTo.
---
> Add BroadcastTo_001 

- runtime/onert/backend/train/KernelGenerator.cc
- runtime/onert/backend/train/ops/LossLayer.cc
- runtime/onert/backend/train/ops/LossMeanSquaredErrorLayer.cc
- runtime/onert/backend/train/ops/LossMeanSquaredErrorLayer.h
This commit introduces LossMeanSqauredErrorLayer in train backend. This code is from LossLayer. LossLayer becomes a base class and other loss types inherit LossLayer to implement each loss layer.
> [onert] Introduce LossMeanSquaredErrorLayer in train backend

- runtime/onert/core/src/ir/OperationDumper.cc
It prints Operands using operator<<, it shows `undefined` with decorated form instead of uint_max.
.......................................................................................
For Reviewers,
```
$ BACKENDS=cpu ONERT_LOG_ENABLE=1 Product/x86_64-linux.debug/out/bin/onert_run mnist.circle
```
```
[       LIR      ] Executor generation of Subgraph 0
[       LIR      ] * FullyConnected
[       LIR      ]   - Inputs : Input(%0) Weight(7) Bias(4294967295)
[       LIR      ]   - Output : Output(%4)
[       LIR      ] * FullyConnected
[       LIR      ]   - Inputs : Input(%4) Weight(8) Bias(4294967295)
[       LIR      ]   - Output : Output(%5)
[       LIR      ] * FullyConnected
[       LIR      ]   - Inputs : Input(%5) …
```
> [onert] Change OperationDumper's FullyConnected

- runtime/onert/core/src/compiler/pass/ConstantInsertionPass.cc
It does not replace constant operands if it has single use or no use.
.......................................................................
For Reviewers,
```
$ BACKENDS=cpu ONERT_LOG_ENABLE=1 Product/x86_64-linux.debug/out/bin/onert_run mnist.circle
```
`%1,%2,%3` are corresponding to FullyConnected's weights.
They don't need to be replaced to `%7,%8,%9`.
```
[  LoweredGraph  ] dump before mandatory passes
[   GraphDumper  ] {
[   GraphDumper  ]   %4 = @0_FullyConnected(%0, %1, %?)
[   GraphDumper  ]   %5 = @1_FullyConnected(%4, %2, %?)
[   GraphDumper  ]   %6 = @2_FullyConnected(%5, %3, %?)
[   GraphDumper  ] }
[   PassRunner   ] Start running 'ConstantInsertionPass'
[ ConstInsertPass] New operand %7 added(copy of %1) for …
```
> [onert] Replace constant when its use count >= 2

- runtime/onert/core/src/compiler/Linear.cc
With  ONERT_LOG_ENABLE=1, we can keep track of IR changes. It has its phase name as prefix. Let's use Linearize instead of GraphDumper as prefix to help the reader find which phase it is.
.......................................................................
For Reviewers,
```
$ BACKENDS=cpu ONERT_LOG_ENABLE=1 Product/x86_64-linux.debug/out/bin/onert_run mnist.circle
```
All lines are printed as `GraphDumper`.
```
...
[       LIR      ] * FullyConnected
[       LIR      ]   - Inputs : Input(%5) Weight(%9) Bias(%?)
[       LIR      ]   - Output : Output(%11)
[   GraphDumper  ] {
[   GraphDumper  ]   %4 = @0_FullyConnected(%0, %7, %?)
[   GraphDumper  ]   %5 = @1_FullyConnected(%4, %8, %?)
[   GraphDumper  ]   %11 = …
```
> [onert] Use Linearize instead of GraphDumper

- runtime/onert/core/src/compiler/ExecutorFactory.cc
It prints in what phase the GraphDumper prints the graph. That is, it is ExecutorFactory::createBackendContexts.
.......................................................................
For Reviewers,
```
$ BACKENDS=cpu ONERT_LOG_ENABLE=1 Product/x86_64-linux.debug/out/bin/onert_run mnist.circle
```
All lines are printed as `GraphDumper`.
```
[   GraphDumper  ] {
[   GraphDumper  ]   %4 = @0_FullyConnected(%0, %7, %?)
[   GraphDumper  ]   %5 = @1_FullyConnected(%4, %8, %?)
[   GraphDumper  ]   %11 = @2_FullyConnected(%5, %9, %?)
[   GraphDumper  ]   Origin(%0): 0
[   GraphDumper  ]   Origin(%4): 4
[   GraphDumper  ]   Origin(%5): 5
[   GraphDumper  ] }
[   GraphDumper  ] 
[   GraphDumper  ] {
[   GraphDumper  ]   Origin(%0): 0
[ …
```
> [onert] Add annotation for createBackendContext printed Graph

- compiler/one-cmds/one-import-onnx
This will revise one-import-onnx I/O name sanitizer with '/'
- add prefix with 'a_' is added unconditionally as sanitized name may have multiple '_'
> [one-cmds] Revise one-import-onnx I/O name sanitizier

- infra/nnfw/cmake/packages/HDF5Config.cmake
This commit fixes find_library option to find library path. 
To find hdf5 serial library, it passes path suffix "hdf5/serial". 
HDF5_CXX_LIBRARIES includes find_library's result.
By this change, we can remove creating symbolic link in install_rootfs.sh script.
---
Draft: #11776
> [infra] Fix HDF5Config.cmake

- compiler/luci/pass/src/RemoveUnnecessaryTransposeNetPass.test.cpp
This PR is to enhance RemoveUnnecessaryTransposeNetPass tests-verification by checking transpose node is removed as expected.
* motivation : https://github.com/Samsung/ONE/pull/11891#discussion_r1386125771 
* issue ( but not highly related ) :  https://github.com/Samsung/ONE/issues/11654
> [luci/pass] Enhance RemoveUnnecessaryTransposeNetPass test verification

- compiler/circle-mpqsolver/src/core/DataProvider.cpp
- compiler/circle-mpqsolver/src/core/DataProvider.h
This commit introduces H5FileDataProvider as a wrapper over dio::hdf5::HDF5Importer.
Draft: #11849
> [circle-mpqsolver] Introduce H5FileDataProvider

- infra/nncc/cmake/buildtool/cross/toolchain_aarch64-linux.cmake
This will introduce toolchain files needed for aarch64 cross compile.
---
Draft: #11776
> [infra] Add toolchain file for aarch64 cross compile

- compiler/circle-mpqsolver/src/MPQSolver.cpp
- compiler/circle-mpqsolver/src/MPQSolver.h
- compiler/circle-mpqsolver/src/bisection/BisectionSolver.cpp
- compiler/circle-mpqsolver/src/bisection/BisectionSolver.h
- compiler/circle-mpqsolver/src/pattern/PatternSolver.cpp
This commit moves _qerror_ratio and _input_data_path
from MPQSolver to BisectionSolver, as it's the only
consumer of these fields.
> [circle-mpqsolver] Revise MPQSolver

- tools/cross/install_rootfs.sh
This commit removes manual hdf5 library symbolic link creation in install_rootfs.sh. 
By updating HDF5Config.cmake, we don't need this any more.
> [tools] Remove symbolic link creation

- runtime/onert/api/src/nnfw_api_internal.cc
- runtime/onert/backend/train/KernelGenerator.cc
- runtime/onert/core/include/compiler/train/TrainingInfo.h
- runtime/onert/core/include/ir/operation/Loss.h
- runtime/onert/core/include/ir/train/LossCode.h
- runtime/onert/core/include/ir/train/LossInfo.h
- runtime/onert/core/include/ir/train/operation/Loss.h
- runtime/onert/core/src/compiler/train/TrainableOperationConverter.cc
- runtime/onert/core/src/compiler/train/pass/LossInsertionPass.cc
- runtime/onert/core/src/ir/train/LossCode.cc
- runtime/onert/core/src/ir/train/operation/Loss.cc
This commit implements LossCode and LossInfo as separated files and use the same structure in Compiler, TrainingInfo and Loss IR.
> [onert] Define LossCode and LossInfo as separated files

- compiler/circle-mpqsolver/src/CircleMPQSolver.cpp
- compiler/circle-mpqsolver/src/bisection/BisectionSolver.cpp
- compiler/circle-mpqsolver/src/bisection/BisectionSolver.h
- compiler/circle-mpqsolver/src/bisection/BisectionSolver.test.cpp
This commit uses quantizer context in constructor of BisectionSolver instead of  passing them directly.
> [circle-mpqsolver] Revise BisectionSolver

- compiler/circle-mpqsolver/src/pattern/PatternSolver.cpp
- compiler/circle-mpqsolver/src/pattern/PatternSolver.h
This commit removes unused constructor from PatternSolver.
> [circle-mpqsolver] Revise PatternSolver

- compiler/one-cmds/one-quantize
This PR improve one-quantize granularity options, by adding a word 'weight'.
related issue : https://github.com/Samsung/ONE/issues/12081
> [one-cmds] Improve help message of one-quantize granularity

- compiler/circle-mpqsolver/src/CircleMPQSolver.cpp
This PR adds a word 'weight-quanitzation' to circle-mpqsolver granularity to improve help message.
related issue : https://github.com/Samsung/ONE/issues/12081
> [circle-mpqsolver] Improve help message of circle-mpqsolver granularity

- compiler/circle-mpqsolver/CMakeLists.txt
- compiler/circle-mpqsolver/src/CircleMPQSolver.cpp
- compiler/circle-mpqsolver/src/bisection/BisectionSolver.cpp
- compiler/circle-mpqsolver/src/bisection/BisectionSolver.h
- compiler/circle-mpqsolver/src/bisection/BisectionSolver.test.cpp
- compiler/circle-mpqsolver/src/core/Evaluator.cpp
- compiler/circle-mpqsolver/src/core/Evaluator.h
- compiler/circle-mpqsolver/src/core/Evaluator.test.cpp
This commit replaces direct use of HDF5File by DataProvider in BisectionSolver and adjusts Evaluator accordingly.
This commit was tested in #11849
> [circle-mpqsolver] Use DataProvider

- compiler/circle-mpqsolver/src/MPQSolver.cpp
- compiler/circle-mpqsolver/src/MPQSolver.h
- compiler/circle-mpqsolver/src/core/Quantizer.cpp
- compiler/circle-mpqsolver/src/core/Quantizer.h
- compiler/circle-mpqsolver/src/core/Quantizer.test.cpp
This commit sets default values in Context, removes deprecated Quantizer constructor, adjusts tests and MPQSolver.
> [circle-mpqsolver] Revise Quantizer

- infra/command/format
This commit updates format command for cpp check.
- New option "clang-format-version": clang version number
- Use variable for clang-format candidate, not array
- Fix error message when clang-format is not installed to show candidate
- Remove unused variable: FILES_TO_CHECK_CPP_BY_CLANG_FORMAT_8
- Fix typo
> [infra] Revise format command

- compiler/circle-mpqsolver/src/core/Quantizer.cpp
This fixes int16 granularity as channel.
---
Related to: https://github.com/Samsung/ONE/issues/11777#issuecomment-1826997746
> [circle-mpqsolver] Set proper int16 granularity

- compiler/circle-mpqsolver/src/bisection/BisectionSolver.test.cpp
This commit removes unnecessary assignment of input/output type.
This commit was tested in https://github.com/Samsung/ONE/pull/11849
> [circle-mpqsolver] Tidy BisectionSolver test

- compiler/circle-mpqsolver/src/core/Quantizer.cpp
This commit replaces implementation of `quantize`
by another `quantize`.
This commit was tested in https://github.com/Samsung/ONE/pull/11849
> [circle-mpqsolver] Tidy Quantizer

- compiler/circle-mpqsolver/src/bisection/BisectionSolver.test.cpp
This commit adds one more unittest for BisectionSolver to increase test coverage.
This commit was tested in https://github.com/Samsung/ONE/pull/11849
> [circle-mpqsolver] Add BisectionSolver unitest

- runtime/onert/api/include/nnfw_experimental.h
- runtime/onert/api/src/nnfw_api_internal.cc
- runtime/onert/core/include/compiler/train/TrainingInfo.h
- runtime/onert/core/include/ir/train/LossInfo.h
- tests/tools/onert_train/src/onert_train.cc
This commit introduces LossReductionType for training feature. It will use SumOverBatchSize reduction type, if the reduction type is not specified.
> [onert] Introduce LossReductionType

- compiler/hermes-std/include/hermes/ConsoleReporter.h
- compiler/hermes-std/src/ConsoleReporter.cpp
This will revise to check environment variable only once per instance of ConsoleReporter.
> [hermes-std] Check getenv once per instance

- infra/debian/compiler/one-compiler.links
This will add lib link for libluci_compute.so file.
> [infra/debian] Make link for libluci_compute

- compiler/common-artifacts/exclude.lst
This removes BroadcastTo operation from the exclude list.
---
> [common-artifacts] Remove BroadcastTo operation in exclude.lst

- compiler/circle-mpqsolver/src/bisection/BisectionSolver.test.cpp
- compiler/circle-mpqsolver/src/core/Evaluator.test.cpp
- compiler/circle-mpqsolver/src/core/TestHelper.h
- compiler/circle-mpqsolver/src/core/TestHelper.test.cpp
This commit renames getSingleDataProvider as
getAllZeroSingleDataProvider for clarity.
---
Original: https://github.com/Samsung/ONE/pull/12117#discussion_r1405731891
> [circle-mpqsolver] Revise getSingleDataProvider name

- compiler/circle-mpqsolver/src/pattern/PatternSolver.h
This commit adds comment to PatternSolver constructor.
> [circle-mpqsolver] Add comment to PatternSolver

- compiler/luci/import/src/ValidateHelpers.cpp
This will revise validate_minmax method to support INT16 quantized model.
> [luci/import] Revise validate_minmax with int16

- tests/tools/onert_train/src/args.cc
- tests/tools/onert_train/src/args.h
- tests/tools/onert_train/src/onert_train.cc
This commit adds `--loss_reduction_type` option.
The default value is 0, which means to follow the model setting or
onert train setting.
~~waiting for #12105~~
> [tools/onert_train] Add loss_reduction_type option

- compute/cker/include/cker/operation/FloorMod.h
- compute/cker/src/FloorMod.test.cc
This commit Introduces kernels for FloorMod operator.
- Support element-wise FloorMod in general data type
- Support broadcast FloorMod in general data type
- Introduce validating introduced kernels
> [cker] Introduce FloorMod kernels

- compiler/common-artifacts/exclude.lst
This enables the test of circle optimization generation for BroadcastTo op.
---
> [common-artifacts] Enable optimization test for BroadcastTo op

- compute/cker/include/cker/train/operation/Loss.h
- compute/cker/src/train/Loss.test.cc
- runtime/onert/core/src/compiler/ExecutorFactory.cc
- runtime/onert/core/src/compiler/StaticShapeInferer.cc
- runtime/onert/core/src/compiler/train/pass/LossInsertionPass.cc
- runtime/onert/core/src/exec/train/TrainableExecutor.cc
- runtime/onert/core/src/exec/train/TrainableExecutor.h
This commit applies a reduction type to the Loss operation. It changes the loss output shape to match the batch size using a static shape inferer. The loss information is stored in the TrainingExecutor and the loss value is returned according to the reduction type.
> [onert] Apply reduction type to Loss

- compiler/circle-mpqsolver/src/core/Dumper.cpp
- compiler/circle-mpqsolver/src/core/Dumper.h
- compiler/circle-mpqsolver/src/core/Dumper.test.cpp
- compiler/circle-mpqsolver/src/core/DumpingHooks.cpp
This commit normalizes Dumper methods to camel notation and adjusts dependencies accordingly.
Related: #12156
> [circle-mpqsolver] Revisit Dumper

- compiler/circle-mpqsolver/src/CircleMPQSolver.cpp
- compiler/circle-mpqsolver/src/MPQSolver.cpp
- compiler/circle-mpqsolver/src/MPQSolver.h
- compiler/circle-mpqsolver/src/bisection/BisectionSolver.cpp
- compiler/circle-mpqsolver/src/pattern/PatternSolver.cpp
This commit normalizes MPQSolver methods to camel notation and adjusts dependencies accordingly.
Related: https://github.com/Samsung/ONE/issues/12156
> [circle-mpqsolver] Revisit MPQSolver

- compiler/luci-compute/src/ConvertTypes.cpp
- compiler/luci-compute/src/ConvertTypes.h
- compiler/luci-compute/src/FullyConnected.cpp
This will enable FullyConnected weights_format conversion.
> [luci-compute] Enable FullyConnected weights_format conversion

- compiler/luci/pass/src/helpers/Shape.cpp
- compiler/luci/pass/src/helpers/Shape.h
This will extract is_same_shape helper method to separaet module.
> [luci/pass] Extract is_same_shape helper method

- compiler/luci-compute/src/ConvertTypes.cpp
This will revise to throw for unknwon value with tflite_shape method.
> [luci-compute] tflite_shape throw for unknown

- compiler/luci/pass/src/FoldDepthwiseConv2DPass.cpp
This will revise FoldDepthwiseConv2DPass with luci-compute.
> [luci/pass] Revise FoldDepthwiseConv2DPass with luci-compute

- compute/cker/include/cker/operation/FloorMod.h
- runtime/onert/backend/cpu/KernelGenerator.cc
- runtime/onert/backend/cpu/ops/ElementwiseBinaryLayer.cc
- runtime/onert/backend/cpu/ops/ElementwiseBinaryLayer.h
- tests/nnfw_api/src/CircleGen.cc
- tests/nnfw_api/src/CircleGen.h
- tests/nnfw_api/src/one_op_tests/FloorMod.test.cc
This commit makes onert support FloorMod op.
- Add FloorMod unit tests to one_op_tests
- Support float and int64
- Apply FloorMod cpu kernel
> [onert] Support FloorMod

- compiler/luci-value-py-test/README.md
This commit adds README.md to luci-value-py-test.
This README is copied from `luci-value-test`.
> [luci-value-py-test] Add README.md

- compiler/luci-value-py-test/conftest.py
This commit resolves invalid escape sequence warning.
```bash
=============================== warnings summary ===============================
conftest.py:5
/home/seongwoo/ONE/compiler/luci-pass-value-py-test/conftest.py:5: DeprecationWarning: invalid escape sequence \(
p = re.compile('eval\((.*)\)')
-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
======================== 55 passed, 1 warning in 1.80s =========================
```
> [luci-value-py-test] Resolve warning

- compiler/luci-compute/CMakeLists.txt
- compiler/luci-compute/src/ConvertTypes.test.cpp
This will enable unit test with ConvertTypes methods.
> [luci-compute] Enable unit test with ConvertTypes

- infra/nncc/command/utcount
This will add a note for utcount as it is not maintained anymore.
> [infra/nncc] Note for utcount

- runtime/onert/backend/train/KernelGenerator.cc
This commit fixes using wrong shape in generating Conv2D kernel for training.
> [onert] Fix wrong shape in train Conv2D

- compiler/luci-compute/src/ConvertValues.test.cpp
This will introduce unit test for ConvertValues.
> [luci-compute] Introduce unit test for ConvertValues

- compiler/circle-mpqsolver/src/bisection/BisectionSolver.cpp
- compiler/circle-mpqsolver/src/core/DumpingHooks.cpp
- compiler/circle-mpqsolver/src/core/DumpingHooks.h
- compiler/circle-mpqsolver/src/core/DumpingHooks.test.cpp
- compiler/circle-mpqsolver/src/core/Quantizer.cpp
- compiler/circle-mpqsolver/src/core/Quantizer.h
- compiler/circle-mpqsolver/src/core/SolverHooks.h
This commit normalizes DumpingHooks methods to camel notation and adjusts dependencies accordingly.
Related: https://github.com/Samsung/ONE/issues/12156
> [circle-mpqsolver] Revisit DumpingHooks

- compiler/luci/pass/src/FoldDepthwiseConv2DPass.cpp
This will remove empty lines for to group by variables.
> [luci/pass] Remove empty lines

- compiler/luci-compute/src/DepthwiseConv2D.cpp
This will revise to make compiler happy with default case for switch.
> [luci-compute] Make compiler happy with switch default

- compiler/circle-mpqsolver/src/bisection/BisectionSolver.cpp
- compiler/circle-mpqsolver/src/core/Quantizer.cpp
- compiler/circle-mpqsolver/src/core/Quantizer.h
This commit normalizes Quantizer methods to camel notation and adjusts dependencies accordingly.
Related: #12156
> [circle-mpqsolver] Revisit Quantizer

- compiler/one-cmds/one-import-onnx
This will fix import-onnx sanitize method to also handle names starting with digit,
that was accidently removed in last change.
> [one-cmds] Fix import-onnx sanitize

- compiler/circle-mpqsolver/src/bisection/BisectionSolver.cpp
This commit moves onBeginIteration to keep it
synchronized with onEndIteration.
Draft: #12042
Related: #12020
> [circle-mpqsolver] Fix BisectionSolver

- compiler/circle-mpqsolver/src/core/DumpingHooks.cpp
- compiler/circle-mpqsolver/src/core/DumpingHooks.h
- compiler/circle-mpqsolver/src/core/SolverHooks.h
This commit  moves setting _in_iterations to false to onEndIteration
and makes onEndIteration nonconst to keep onEndIteration synchronized
with onBeginIteration.
Draft: https://github.com/Samsung/ONE/pull/12042
Related: https://github.com/Samsung/ONE/issues/12020
> [circle-mpqsolver] Fix DumpingHooks

- compiler/luci/service/src/CircleShapeInferenceRule.cpp
This will show better error message for Concatenation if input shapes are incompatible.
> [luci/service] Show better message for Concatenation

- runtime/onert/backend/cpu/ops/ElementwiseBinaryLayer.cc
- runtime/onert/backend/cpu/ops/ElementwiseUnaryLayer.cc
- runtime/onert/backend/cpu/ops/OperationUtils.h
- runtime/onert/backend/cpu/ops/ReduceLayer.cc
This commit adds static assertions to check whether bool size is 1 byte.
---
Related issue : https://github.com/Samsung/ONE/pull/12231#discussion_r1420022092
> [onert] Add static assertions to check bool size

- res/TensorFlowLiteRecipes/Net_Reshape_Mean_000/test.recipe
This commit adds models for testing reshape mean pattern fusion.
> [res] TensorFlowLiteRecipes for reshape mean pattern

- compiler/luci/pass/src/ForwardReshapeToUnaryOpPass.cpp
This commit extends ForwardReshapeToUnaryOpPass with Mul and Div ops.
> [luci/pass] Extend ForwardReshapeToUnaryOpPass with Mul and Div ops

- compiler/circle-mpqsolver/src/CircleMPQSolver.cpp
This commit moves setSaveIntermediate to general context for using it by all types of mpq solvers.
Draft: https://github.com/Samsung/ONE/pull/12042
Related: https://github.com/Samsung/ONE/issues/12020
> [circle-mpqsolver] Revisit CircleMPQSolver

- tests/tools/onert_train/src/args.cc
- tests/tools/onert_train/src/args.h
- tests/tools/onert_train/src/onert_train.cc
It introduces --export_path to specify the path to export circle.
Draft: #12246
> [tools/onert_train] Introduce --export_path option

- runtime/onert/core/include/backend/basic/BackendContextHelpers.h
- runtime/onert/core/include/backend/basic/train/TrainableBackendContextHelpers.h
On constructing TrainableTensor, OperandInfo will be used from the whole copy of original OperandInfo, not by copying listing each members.
> [onert] Copy the whole OperandInfo on TrainableTensor creation

- runtime/onert/frontend/circle/src/circle_loader.cc
It stores circle tensor index in ir::Operand during loading circle.
It is modification under `frontend`. (not under `ir`, `api`, ...)
Thus, I separated this PR.
> [onert] Store origin tensor index in ir::Operand during loading circle

- compute/cker/include/cker/train/operation/Loss.h
- compute/cker/src/train/Loss.test.cc
- runtime/onert/backend/train/ops/LossCategoricalCrossentropyLayer.cc
- runtime/onert/backend/train/ops/LossCategoricalCrossentropyLayer.h
This commit updates Categorical crossentropy implementation to apply changed output shape. The output shape is changed from [1] to [batch_size].
> [onert] Update Categorical crossentropy implementation

- runtime/onert/core/include/backend/train/ITensorRegistry.h
- runtime/onert/core/src/backend/builtin/train/TensorRegistry.h
- runtime/onert/core/src/compiler/train/TensorRegistries.h
It introduces iterateTrainableTensors in train::ITensorRegistry and TensorRegistries.
It is added for exporting circle with trained weights.
> [onert] Introduce iterateTrainableTensors

- compiler/one-cmds/tests/CMakeLists.txt
- compiler/one-cmds/tests/preprocess_images_numpy.py
This introduces preprocessing the image in numpy format to test numpy2hdf5 of one-create-quant-dataset.
---
> [one-cmds] Preprocess the image in numpy format to test numpy2hdf5

- compiler/circle2circle/src/Circle2Circle.cpp
This commit adds fuse_mul_with_div option to circle2circle.
> [circle2circle] Add fuse_mul_with_div option

- compiler/circle-mpqsolver/src/pattern/PatternSolver.cpp
This commit dumps final qconfig in PatternSolver
if save_intermediate option is on.
For `layer_norm` it produced the following qconfig :
[FinalConfiguration.mpq.zip](https://github.com/Samsung/ONE/files/13659239/FinalConfiguration.mpq.zip)
Draft: https://github.com/Samsung/ONE/pull/12042
Related: https://github.com/Samsung/ONE/issues/12020
> [circle-mpqsolver] Dump config

- runtime/onert/core/src/dumper/text/GraphDumper.cc
When dumping graph, it prints origin index also.
--------------
Did you intend to have no prefix?
_Originally posted by @ragmani in https://github.com/Samsung/ONE/pull/12267#discussion_r1423575165_
Yes. Origin is not printed during iterating operators, it is printed during iterating operands. No prefix looks better. I will push another PR for dumping graph. We can enhance log printing if necessary in forecoming PR.
_Originally posted by @glistening in https://github.com/Samsung/ONE/pull/12267#discussion_r1423592211_
> [onert] GraphDumper prints origin index

- compiler/circle-mpqsolver/src/core/DumpingHooks.h
- compiler/circle-mpqsolver/src/core/SolverHooks.h
Thos commit changes description of onBeginSolver/onEndSolver because now these methods can be called even from non-iterative solver.
Draft: https://github.com/Samsung/ONE/pull/12042
Related: https://github.com/Samsung/ONE/issues/12020
> [circle-mpqsolver] Tidy comments

- compiler/luci/pass/src/ForwardReshapeToUnaryOpPass.cpp
- compiler/luci/pass/src/ForwardReshapeToUnaryOpPass.test.cpp
This commit extends ForwardReshapeToUnaryOpPass with Mean op.
> [luci/pass] Extend ForwardReshapeToUnaryOpPass with Mean op

- runtime/onert/core/src/compiler/TensorRegistries.h
- runtime/onert/core/src/compiler/train/TensorRegistries.h
It changes auto && to const auto during iterating TensorRegistries using
for-range loop.
(Optional)
```suggestion
for (const auto &tensor_reg : _tensor_regs)
```
_Originally posted by @ragmani in https://github.com/Samsung/ONE/pull/12269#discussion_r1423615248_
> [onert] Change auto && to const auto &

- runtime/onert/api/include/nnfw_experimental.h
- runtime/onert/api/src/nnfw_api.cc
- runtime/onert/api/src/nnfw_api_internal.cc
- runtime/onert/api/src/nnfw_api_internal.h
This commit introduces nnfw_train_set_output api.
If user sets the output buffer using this function, user can obtain the output result executed with trained weight.
> [onert] Introduce nnfw_train_set_output api

- infra/debian/runtime/control
- infra/debian/runtime/nnfw-plugin-dev.install
- infra/debian/runtime/rules
This commit updates debian build.
- Enable using hdf5
- Packaging nnfw-plugin-dev (matching tizen nnfw-plugin-devel.rpm)
> [infra/onert] Update debian build

- runtime/onert/core/include/ir/Index.h
- runtime/onert/core/src/dumper/text/GraphDumper.cc
It uses width=3 for better alignment in log.
> [onert] Make log aligned using fixed width of index

- tests/tools/onert_train/src/args.cc
- tests/tools/onert_train/src/args.h
This commit adds metric argument.
It simply calculates the metric value using the variables.
> [tools/onert_train] Add metric argument

- infra/nnfw/CMakeLists.txt
- infra/nnfw/cmake/packages/ARMComputeConfig.cmake
- infra/nnfw/cmake/packages/LuciConfig.cmake
This commit changes overlay searching by using CMAKE_FIND_ROOT_PATH. 
It will simplify searching overlay and fix bug on luci library searching.
> [infra/onert] Fix cmake overlay searching

- compiler/circle-quantizer/src/CircleQuantizer.cpp
This commit prevents copying of an obejct when using auto keyword.
This warning is from our static analysis tool.
> [circle-quantizer] Prevent copy of an object

- compiler/circle-mpqsolver/src/bisection/VISQErrorApproximator.cpp
- compiler/circle-mpqsolver/src/pattern/PatternSolver.cpp
This commit prevents from copying of an object when using auto keyword.
This warning is from our static analysis tool.
> [circle-mqpsolver] Prevent copy of an object

- compiler/one-cmds/how-to-use-one-commands.txt
- compiler/one-cmds/onelib/constant.py
This commit enables fuse_mul_div option for one-cmds optimize.
> [one-cmds] Enable fuse_mul_div

- compiler/one-cmds/tests/CMakeLists.txt
This adds proper dependency for O1 in tests directory.
---
Related to: https://github.com/Samsung/ONE/pull/12278
> [one-cmds] Add dependency for O1

- runtime/onert/api/include/nnfw.h
- runtime/onert/api/src/nnfw_api_internal.cc
It ensure to mmap circle file with getting file size.
> [onert] mmap circle file for exporting circle

- runtime/onert/core/include/exec/Execution.h
- runtime/onert/core/src/exec/Execution.cc
- runtime/onert/core/src/exec/train/TrainableExecutor.cc
- runtime/onert/core/src/exec/train/TrainableExecutor.h
- runtime/onert/core/src/exec/train/TrainableExecutors.cc
- runtime/onert/core/src/exec/train/TrainableExecutors.h
It adds iterateTrainableTensors in Execution and TrainableExecutor(s).
> [onert] Add iterateTrainableTensors under exec

- infra/nnfw/cmake/CfgOptionFlags.cmake
This commit removes ENABLE_ONERT_TRAIN option.
It is not used any more.
> [infra/onert] Remove training feature option

- runtime/onert/core/include/ir/Model.h
- runtime/onert/frontend/base_loader/include/base_loader.h
- runtime/onert/frontend/circle/src/circle_loader.cc
- runtime/onert/frontend/tflite/src/tflite_loader.cc
This PR introduces a metadata field to ir::Model and related loading logic.
draft : https://github.com/Samsung/ONE/pull/12152 
issue : https://github.com/Samsung/ONE/issues/11692
> [onert] Introduce metadata to model and loader

- infra/nncc/Makefile.arm32
This will revise Makefile.arm32 to replace with luci-value-py-test.
> [infra/nncc] Revise Makefile.arm32

- tests/tools/onert_train/src/args.cc
- tests/tools/onert_train/src/args.h
This commit adds a validation_split argument.
This argument refers to the fraction of the training data to be used as validation data.
Draft: #12265
> [tools/onert_train] Add validation_split argument

- tests/tools/onert_train/src/nnfw_util.h
This commit resolves build fail by ostream without header include.
> [onert/train] Fix build fail

- docs/release/1.26/index.rst
- docs/release/1.26/release-note-1.26.0.md
This commit is a release note for 1.26.0.
Related: #12299 
> Release note 1.26.0

- infra/debian/compiler/changelog
This commit updates changelog for release 1.26.0.
Related: #12299 
> [debian] Update changelog

- compiler/pp/include/pp/IndentedStringBuilder.h
This commit adds cstdint header include.
It will resolve build fail on gcc-13.
---
Draft: #12343
> [pp] Add cstdint header include

- infra/cmake/packages/FlatBuffers-2.0/FlatBuffersConfig.cmake
This commit fixes flatc build error on gcc-13.
---
Draft: #12343
> [infra] Fix flatc build error

- tests/tools/onert_train/src/args.cc
- tests/tools/onert_train/src/onert_train.cc
This commit uses metric parameter for calculating metric value. Currently, only CATEGORICAL_ACCURACY is supported.
Draft: #12265
> [tools/onert_train] Use metric parameter

- infra/nncc/cmake/options/options_riscv64-tizen.cmake
- infra/nnfw/cmake/buildtool/config/config_riscv64-tizen.cmake
- infra/nnfw/cmake/options/options_riscv64-tizen.cmake
This commit adds RISC-V tizen cmake build config and options.
---
Draft:  #12343
> [infra] Add RISC-V tizen cmake build config and options

- runtime/onert/core/src/exec/Execution.cc
This commit removes training start and finish log. While training is running several times, the meaningless logs are repeatedly printed.
> [onert] Remove training start and finish log

- runtime/onert/api/src/nnfw_api_internal.cc
- runtime/onert/api/src/nnfw_api_internal.h
This PR adds TrainingInfo into nnfw_session.
It also initalize nnfw_session._train_info in 'load_model_from_modelfile' and 'load_model_from_nnpackage'.
issue : https://github.com/Samsung/ONE/issues/11692
draft : https://github.com/Samsung/ONE/pull/12152.
> [onert/api] Add TrainingInfo into nnfw_session

- compute/cker/include/cker/train/operation/ReduceMean.h
- compute/cker/src/train/ReduceMean.test.cc
This commit implements ReduceMean gradient kernel and test case. The formula is dLoss/dInput = (dLoss/dOutput) * (1/n), where n is the input size divided by output size.
Draft: #12358
> [onert] Implement ReduceMean gradient kernel

- runtime/onert/backend/train/TensorManager.cc
This commit changes DERIVATIVE log to BACK_PROP.
> [onert] Change DERIVATIVE log to BACK_PROP

- runtime/onert/api/include/nnfw_experimental.h
- runtime/onert/api/src/nnfw_api_internal.cc
- runtime/onert/core/include/compiler/train/TrainingInfo.h
- runtime/onert/core/include/ir/train/LossInfo.h
- tests/tools/onert_train/src/args.cc
- tests/tools/onert_train/src/nnfw_util.cc
- tests/tools/onert_train/src/onert_train.cc
This commit introduces AUTO loss reduction type. The experimental API does not have Invalid loss reduction type because the user does not have to select the INVALID type. Instead, INVALID type is changed to AUTO type. AUTO type means that the reduction option will be determined by the context. In contrast, onert ir supports both Invalid and Auto types. The default value of loss info in onert ir is Invalid type to determine whether the value has been received from the user.
> [onert] Introduce AUTO loss reduction type

- compiler/luci/pass/include/luci/CircleOptimizer.h
- compiler/luci/pass/include/luci/Pass/ResolveFormerCustomOpPass.h
- compiler/luci/pass/src/CircleOptimizer.cpp
- compiler/luci/pass/src/ResolveFormerCustomOpPass.cpp
- compiler/luci/pass/src/ResolveFormerCustomOpPass.test.cpp
This commit introduces ResolveFormerCustomOpPass to luci.
ResolveFormerCustomOpPass changes a specific custom op into a builtin op from schema version upgrade.
---
> [luci/pass] Introduce ResovleFormerCustomOpPass 

- compiler/luci/pass/src/ForwardTransposeOpPass.cpp
This will enable ForwardTransposeOpPass to support CircleLogistic Op.
> [luci/pass] Support Logistic in ForwardTransposeOpPass

- compiler/one-cmds/tests/prepare_test_materials.sh
This invokes preprocessing script for numpy files in prepare_test_materials.sh.
---
> [one-cmds] Invoke preprocessing script for numpy files 

- runtime/onert/core/src/compiler/train/StaticBackPropShapeInferer.h
This commit renames DERIVATIVE to BACK_PROP in a file name definition.
> [onert] Rename DERIVATIVE to BACK_PROP in marco definition

- compute/cker/src/train/ReduceMean.test.cc
This PR updates ReduceMeanGrad tests to consider floating point error.
related : https://github.com/Samsung/ONE/issues/12371, https://github.com/Samsung/ONE/issues/12370
> [onert/cker] Update ReduceMeanGrad to consider floating point error

- compiler/luci/pass/src/ResolveFormerCustomOpPass.cpp
This will revise esolveFormerCustomOpPass with condition check to early return false so that new CircleBroadcastTo object won't be wasted.
> [luci/pass] Revise ResolveFormerCustomOpPass with condition

- runtime/onert/api/src/nnfw_api_internal.cc
It moves model null check before dereferencing model.
> [onert/api] Move model null check from export_circle

- runtime/onert/core/include/ir/train/TrainableGraph.h
- runtime/onert/core/src/compiler/ExecutorFactory.cc
- runtime/onert/core/src/compiler/train/StaticBackwardShapeInferer.cc
- runtime/onert/core/src/compiler/train/StaticBackwardShapeInferer.h
- runtime/onert/core/src/compiler/train/TrainingCompiler.cc
- runtime/onert/core/src/ir/train/TrainableGraph.cc
This commit renames training operands from BackProp to Backward.
- back_prop -> backward_operand or bwd_operand
- BackPropShape -> BackwardShape
> [onert] Rename backward operands from BackProp to Backward

- tests/tools/onert_train/src/onert_train.cc
This commit adds vdata_length check logic.
If the user does not give the validation_split value, the vdata_length
is 0 by default and it does not execute validation loop. In this case,
the error check logic is meaningless.
> [tools/onert_train] Add vdata_length check logic

- runtime/onert/api/include/nnfw_experimental.h
- runtime/onert/api/src/nnfw_api.cc
- runtime/onert/api/src/nnfw_api_internal.cc
- runtime/onert/api/src/nnfw_api_internal.h
This PR adds `nnfw_train_set_traininfo()` API into nnfw_experimental header. 
The `nnfw_train_set_traininfo()` API is to set train_info in the session.
ONE-DCO-1.0-Signed-off-by: SeungHui Youn sseung.youn@samsung.com
related issue : https://github.com/Samsung/ONE/issues/11692
> [onert/api] Add nnfw_train_set_traininfo()

- runtime/onert/api/include/nnfw_experimental.h
- runtime/onert/api/src/nnfw_api.cc
- runtime/onert/api/src/nnfw_api_internal.cc
- runtime/onert/api/src/nnfw_api_internal.h
- tests/tools/onert_train/src/onert_train.cc
This PR removes training info from 'nnfw_train_prepare' argument.
It also makes 'nnfw_train_prepare' to use training info from session.
related : https://github.com/Samsung/ONE/issues/11692
> [onert] Remove training info from nnfw_train_prepare

- infra/debian/compiler/one-compiler.install
This commits installs one-create-quant-dataset binary to /usr/share/one/bin.
---
Related Issue : https://github.com/Samsung/ONE/issues/12374#issuecomment-1871325367
> [one-cmds] Add one-create-quant-dataset to debian package

- runtime/onert/core/include/compiler/StaticShapeInferer.h
- runtime/onert/core/src/compiler/StaticShapeInferer.cc
This commit implements DepthwiseConv2D shape inferer.
> [onert] Implement DepthwiseConv2D shape inferer

- compiler/luci/pass/src/FoldCastPass.cpp
This will revise FoldCastPass to earcky check types to skip casting,
not to unnecessary create CircleConst.
> [luci/pass] Revise FoldCastPass to early check

- compiler/luci/pass/src/FoldCastPass.cpp
This will revise FoldCastPass to use enum for possible cast types.
> [luci/pass] Revise FoldCastPass to use enum for types

- compiler/luci/pass/src/ResolveFormerCustomOpPass.test.cpp
This commit adds more unit tests for ResolveFormerCustomPass.
---
> [luci/pass] Add more unit tests for ResovleFormerCustomPass
