- compiler/vconone/CMakeLists.txt
This commit bumps up to 1.27.0.
Related: #12299
> [vconone] Bump up to 1.27.0

- compiler/one-cmds/tests/prepare_test_materials.sh
- compiler/one-cmds/tests/preprocess_images.py
This commit revises preprocess_images.py to process also numpy files.
- preprocess_images_numpy.py is very similar to preprocess_images.py. so, merge them to reduce duplicate codes.
---
> [one-cmds] Revise preprocess_images.py to process also numpy files

- runtime/onert/api/src/nnfw_api_internal.cc
- runtime/onert/core/include/ir/train/LossCode.h
- runtime/onert/core/include/ir/train/LossInfo.h
- runtime/onert/core/include/ir/train/OptimizerCode.h
- runtime/onert/core/include/ir/train/OptimizerInfo.h
- runtime/onert/core/src/ir/train/LossCode.cc
- runtime/onert/core/src/ir/train/OptimizerCode.cc
- runtime/onert/core/src/ir/train/TrainingInfo.cc
This PR renames training IR's default value from 'Invalid' to 'Undefined'. 
The word 'Undefined' is more appropriate in this case: If nobody sets training information(ir), training information is invalid because it is 'not defined' yet.
>  [onert] Rename training ir Invalid to Undefined

- runtime/onert/api/src/nnfw_api_internal.cc
- runtime/onert/api/src/nnfw_api_internal.h
- runtime/onert/core/include/ir/train/TrainingInfo.h
This commit merges _training_step into TrainingInfo. It removes duplicated variable.
related comment: https://github.com/Samsung/ONE/pull/12383#issuecomment-1871732299
> [onert] Merge _training_step into TrainingInfo

- docs/conf.py
- packaging/nnfw.spec
- runtime/contrib/android/api/build.gradle
- runtime/onert/api/include/nnfw_version.h
This commit updates runtime version to 1.27.0.
---
Related issue: https://github.com/Samsung/ONE/issues/12299
> [runtime] Update runtime version to 1.27.0

- runtime/onert/core/include/ir/train/Operations.Include.h
- runtime/onert/core/include/ir/train/Operations.lst
- runtime/onert/core/include/ir/train/operation/DepthwiseConv2D.h
- runtime/onert/core/src/compiler/train/TrainableOperationConverter.cc
- runtime/onert/core/src/compiler/train/TrainableOperationConverter.h
- runtime/onert/core/src/ir/train/operation/DepthwiseConv2D.cc
This commit introduces DepthwiseConv2D train IR.
Draft: #12392
> [onert] Introduce DepthwiseConv2D trainable operation

- infra/nnfw/config/gbs.conf
- packaging/nnfw.spec
This commit updates gbs.conf and spec file to support RISC-V gbs build.
---
Draft: #12343
> [infra] Support RISC-V gbs build

- tests/tools/onert_train/src/onert_train.cc
This PR adds logic of getting training information from the session in onert_train.
related issue : https://github.com/Samsung/ONE/issues/11692
> [tools/onert_train] Get training info from session

- tests/tools/onert_train/src/nnfw_util.cc
This PR adds *_UNDEF enum to the ostream print utility.
> [tools/onert_train] Add *_UNDEF to the dump utility

- runtime/onert/frontend/circle_traininfo/include/traininfo_loader.h
- runtime/onert/frontend/circle_traininfo/src/traininfo_loader.cc
This PR adds 'const' keyword to the traininfo metadata name.
It also adds 'extern' keyword to follow one-definition-rule.
related issue : https://github.com/Samsung/ONE/issues/11692
> [onert/frontend] Revisit traininfo metadata name

- runtime/libs/benchmark/src/Result.cpp
It makes static analyzer happy by adding & to auto. It will remove unnecessary copy.
> [runtime/benchmark] Suppress auto-causes-copy warnings

- compute/cker/include/cker/operation/Helper/MatmulBCast.h
It adds & to suppress auto causes copy warning.
Also, it fixes typo.
> [compute/cker] Fix typo and auto_causes_copy warning in MatmulBCast.h

- runtime/onert/api/include/nnfw_experimental.h
- runtime/onert/api/src/nnfw_api_internal.cc
- runtime/onert/core/include/ir/train/LossInfo.h
- runtime/onert/core/include/ir/train/TrainingInfo.h
- tests/tools/onert_train/src/args.cc
- tests/tools/onert_train/src/nnfw_util.cc
- tests/tools/onert_train/src/onert_train.cc
This PR removes AUTO from train loss reduction type.
related issue : https://github.com/Samsung/ONE/issues/12418
> [onert] Remove AUTO from train loss reduction type

- tests/tools/onert_train/src/args.cc
- tests/tools/onert_train/src/onert_train.cc
This commit changes the type number of loss and optimizer to match the enum value of `nnfw_experimental.h`.
> [tests/onert_train] Change the type number of loss and optimizer

- runtime/onert/api/include/nnfw_experimental.h
This commit removes the comments on `set_traininfo` that is no longer valid.
> [onert] Remove api comments no longer valid

- infra/docker/focal/Dockerfile
- infra/docker/focal/Dockerfile.aarch64
- infra/docker/jammy/Dockerfile
- infra/docker/jammy/Dockerfile.aarch64
This commit updates dockerfile to install clang-format-16.
---
Related issue: #12311
> [infra] Install clang-format-16 on docker

- compiler/luci/service/src/CircleShapeInferenceRule.cpp
This commit adds a logic where the shape inference of CircleTransposeConv uses a node's own shape when one of inputs is not constant.
Related: https://github.com/Samsung/ONE/issues/12429#issuecomment-1884092665
Draft: #12434
> [luci] Use own shape in the shape inference

- res/TensorFlowLiteRecipes/TransposeConv_002/test.recipe
This commit introduces TransposeConv_002 recipe for checking if non-constant out_shape can be inferred by the shape inference.
Related: https://github.com/Samsung/ONE/issues/12429#issuecomment-1884092665
Draft: #12434 
> [res] Introduce TransposeConv_002

- tests/tools/tflite_comparator/CMakeLists.txt
- tests/tools/tflite_comparator/src/args.cc
This commit removes unused boost filesystem header and dependency.
---
Found this on #12423
> [tflite_comparator] Remove unused header

- res/TensorFlowLiteRecipes/BroadcastTo_000/test.rule
This commit adds BroadcastTo_000 test.rule.
---
> [res] Add BroadcastTo_000 test.rule

- runtime/contrib/logging/CMakeLists.txt
- runtime/contrib/logging/src/nnapi_logging.cc
This commit removes boost library depdency on logging runtime.
> [runtime] Remove boost dependency on logging runtime

- infra/cmake/packages/NoniusSourceConfig.cmake
- tools/kbenchmark/Args.cc
- tools/kbenchmark/CMakeLists.txt
This commit removes boost::filesystem dependency.
It includes typo fix in cmake.
---
Related issue: #12450
> [tools/kbenchmark] Remove boost filesystem dependency

- runtime/onert/core/include/util/logging.h
This commit adds a time measurement define.
This definition is not focused on the runtime feature and may be useful for measuring the elapsed time in development.
> [onert] Add time measurement define

- runtime/contrib/tflite_classify/CMakeLists.txt
- runtime/contrib/tflite_classify/src/tflite_classify.cc
This commit removes boost:filesystem dependency.
---
Related issue: https://github.com/Samsung/ONE/issues/12450
> [contrib/tflite_classify] Remove boost dependency

- runtime/contrib/style_transfer_app/CMakeLists.txt
- runtime/contrib/style_transfer_app/src/args.cc
- runtime/contrib/style_transfer_app/src/jpeg_helper.cc
This commit removes boost::filesystem dependency.
It includes bug fix.
---
Related issue: https://github.com/Samsung/ONE/issues/12450
> [contrib/style_transfer_app] Remove boost filesystem dependency

- compiler/circle2circle-dredd-recipe-test/test.lst
This commit adds resolve_former_customop to circle2circle-dredd-recipe-test.
> [circle2circle-dredd-recipe-test] Add resolve_former_customop test

- compiler/circlechef/circle/src/CircleImport.cpp
- compiler/circlechef/circle/src/CircleImport.h
- compiler/circlechef/circle/src/Convert.h
- compiler/circlechef/circle/src/RecipeChef.cpp
> [circlechef] Revise to use size()

- compiler/circledump/src/Dump.cpp
> [circledump] Revise to use size()

- compiler/circle-inspect/src/Dump.cpp
> [cirle-inspect] Revise to use size()

- compiler/circle-operator/src/Dump.cpp
> [circle-operator] Revise to use size()

- compiler/mio-circle07/include/mio_circle/Helper.h
- compiler/mio-circle07/include/mio_circle/Reader.h
- compiler/mio-circle07/src/Reader.cpp
> [mio-circle07] Revise to use size()

- compiler/tflchef/tflite/src/Convert.h
- compiler/tflchef/tflite/src/RecipeChef.cpp
- compiler/tflchef/tflite/src/TFliteImport.cpp
- compiler/tflchef/tflite/src/TFliteImport.h
> [tflchef] Revise to use size()

- compiler/tfldump/src/Dump.cpp
- compiler/tfldump/src/Read.cpp
- compiler/tfldump/src/Read.h
> [tfldump] Revise to use size()

- compiler/tfl-inspect/src/Dump.cpp
- compiler/tfl-inspect/src/Reader.cpp
- compiler/tfl-inspect/src/Reader.h
> [tfl-inspect] Revise to use size()

- compiler/nnc/backends/acl_soft_backend/AclCppGenerator.cpp
- compiler/nnc/backends/acl_soft_backend/CMakeLists.txt
- compiler/nnc/backends/soft_backend/CMakeLists.txt
- compiler/nnc/backends/soft_backend/CPPGenerator.cpp
This will revise to use std::filesystem from boost.
> [nnc] Revise to use std::filesystem

- res/TensorFlowLiteRecipes/Net_BroadcastTo_AddV2_002/test.recipe
- res/TensorFlowLiteRecipes/Net_BroadcastTo_AddV2_002/test.rule
This commit adds Net_BroadcastTo_AddV2_002 network to TensorFlowLiteRecipes.
---
> [res] Add Net_BroadcastTo_AddV2_002

- compiler/rawdata2hdf5/rawdata2hdf5
This commit adds warning to deprecate rawdata2hdf5.
---
> [rawdata2hdf5] Add warning to deprecate rawdata2hdf5

- compute/cker/include/cker/train/operation/ReLU6.h
- compute/cker/src/train/Relu6.test.cc
This PR introduces ReLU6 gradient kernel.
issue : https://github.com/Samsung/ONE/issues/12388 
draft : https://github.com/Samsung/ONE/pull/12395 
> [cker] Introduce ReLU6 gradient kernel

- onert-micro/luci-interpreter/src/kernels/AveragePool2D.cpp
- onert-micro/luci-interpreter/src/kernels/L2Pool2D.cpp
- onert-micro/luci-interpreter/src/kernels/MaxPool2D.cpp
- onert-micro/luci-interpreter/src/kernels/Pool2DCommon.h
This commit reduces duplicate code in pool layers.
- Introduce Pool2DCommon.h that has common functions for pool layers.
- configure_kernel_CirclePool2DCommon : unifies configure function of pool layers.
- createPoolParams : unifies creating parameters of pool layers.
- Apply common function for pool layers.
---
For #11744
> [onert-micro] Reduce duplicate code in pool layers

- onert-micro/luci-interpreter/pal/common/PALAddCommon.h
- onert-micro/luci-interpreter/pal/common/PALArithmeticOpCommon.h
- onert-micro/luci-interpreter/pal/common/PALDiv.h
- onert-micro/luci-interpreter/pal/common/PALMulCommon.h
- onert-micro/luci-interpreter/pal/common/PALSub.h
- onert-micro/luci-interpreter/src/kernels/Add.test.cpp
- onert-micro/luci-interpreter/src/kernels/BinaryOpCommon.h
- onert-micro/luci-interpreter/src/kernels/Div.test.cpp
- onert-micro/luci-interpreter/src/kernels/Mul.test.cpp
- onert-micro/luci-interpreter/src/kernels/Sub.test.cpp
This commit reduces duplicate code in arithmetic kernels.
- Introduce PALArithmeticOpCommon.h that has common functions for arithmetic kernels. - Introduce arithmetic function objects. 
- Introduce `ArithmeticOp()` that unifies artithmetic kernels without broadcast. 
- Introduce `BroadcastArithmeticOp4DSlow()` that unifies artithmetic kernels with broadcast.
- Apply common functions for arithmetic kernels.
---
For #11744
> [onert-micro] Reduce duplicate code in arithmetic kernels

- infra/cmake/packages/GTestSourceConfig.cmake
This commit updates googletest version to 1.12.1.
It is used on tizen 8.
> [infra] Use googletest 1.12.1

- compute/cker/include/cker/eigen/depthwise_conv_op.h
- compute/cker/include/cker/train/operation/DepthwiseConv.h
- compute/cker/src/train/DepthwiseConv.test.cc
This commit introduces DepthwiseConv2D gradient kernel. The depthwise_conv_op.h file came from TensorFlow code. This commit transforms the depthwise_conv related code to fit onert and execute this kernel function.
Draft: #12392
> [cker] Introduce DepthwiseConv2D gradient kernel

- runtime/onert/backend/train/ops/ElementwiseActivationLayer.cc
This PR applies ReLU6Grad to ElementwiseActivationLayer.
issue : https://github.com/Samsung/ONE/issues/12388 
draft : https://github.com/Samsung/ONE/pull/12395
> [onert] Apply ReLU6Grad to ElementwiseActivationLayer

- onert-micro/luci-interpreter/pal/common/PALFullyConnectedCommon.h
- onert-micro/luci-interpreter/pal/common/Params.h
- onert-micro/luci-interpreter/src/kernels/FullyConnected.cpp
This commit enables layer-wise hybrid FC.
Need for some internal models.
> [onert-micro] Enable layer-wise hybrid FC

- onert-micro/luci-interpreter/pal/common/PALBinaryOpCommon.h
- onert-micro/luci-interpreter/pal/common/PALFloorDivCommon.h
- onert-micro/luci-interpreter/pal/common/PALFloorModCommon.h
- onert-micro/luci-interpreter/pal/common/PALMaximumCommon.h
- onert-micro/luci-interpreter/pal/common/PALMinimumCommon.h
- onert-micro/luci-interpreter/src/kernels/BinaryOpCommon.h
- onert-micro/luci-interpreter/src/kernels/FloorDiv.cpp
- onert-micro/luci-interpreter/src/kernels/FloorDiv.test.cpp
- onert-micro/luci-interpreter/src/kernels/FloorMod.cpp
- onert-micro/luci-interpreter/src/kernels/FloorMod.test.cpp
- onert-micro/luci-interpreter/src/kernels/Maximum.cpp
- onert-micro/luci-interpreter/src/kernels/Maximum.test.cpp
- onert-micro/luci-interpreter/src/kernels/Minimum.cpp
- onert-micro/luci-interpreter/src/kernels/Minimum.test.cpp
- onert-micro/luci-interpreter/src/kernels/Utils.cpp
- onert-micro/luci-interpreter/src/kernels/Utils.h
This commit reduces duplicate code in binary kernels.
* Introduce PALBinaryOpCommon.h that has common functions for binary kernels. 
* Introduce binary function objects. 
* Introduce `BinaryOp()` that unifies binary kernels without broadcast. 
* Introduce `BroadcastBinaryOp4DSlow()` that unifies binary kernels with broadcast.
* Apply common functions for binary kernels.
* Introduce `areShapesEqual()` that unifies duplicated codes related to checking shapes.
---
For #11744
> [onert-micro] Reduce duplicate code in binary kernels

- onert-micro/luci-interpreter/src/kernels/ComparisonCommon.h
- onert-micro/luci-interpreter/src/kernels/Equal.cpp
- onert-micro/luci-interpreter/src/kernels/Greater.cpp
- onert-micro/luci-interpreter/src/kernels/GreaterEqual.cpp
- onert-micro/luci-interpreter/src/kernels/Less.cpp
- onert-micro/luci-interpreter/src/kernels/LessEqual.cpp
- onert-micro/luci-interpreter/src/kernels/NotEqual.cpp
This commit reduces duplicate code in comparison kernels.
- Introduce `evalComparisonGeneric()` that unifies comparison kernels.
---
For #11744
> [onert-micro] Reduce duplicate code in comparison kernels

- runtime/onert/backend/train/ops/ConvolutionLayer.cc
- runtime/onert/backend/train/ops/FullyConnectedLayer.cc
- runtime/onert/backend/train/ops/OperationUtils.cc
- runtime/onert/backend/train/ops/OperationUtils.h
- runtime/onert/backend/train/ops/PoolLayer.cc
This PR extracts fused activation backpropagation part to OperationUtils. 
issue : https://github.com/Samsung/ONE/issues/12388 
draft : https://github.com/Samsung/ONE/pull/12395
> [onert] Extract fused activation backprop to OperationUtils

- runtime/onert/core/include/ir/train/Operations.Include.h
- runtime/onert/core/include/ir/train/Operations.lst
- runtime/onert/core/include/ir/train/operation/BinaryArithmetic.h
- runtime/onert/core/src/compiler/train/TrainableOperationConverter.cc
- runtime/onert/core/src/compiler/train/TrainableOperationConverter.h
- runtime/onert/core/src/ir/train/operation/BinaryArithmetic.cc
This commit introduces BinaryArithmetic train IR.
From draft #12417
> [onert] Introduce BinaryArithmetic trainable operation

- runtime/onert/backend/train/ops/OperationUtils.cc
This PR adds ReLU6 backpropagation(gradient) to OperationUtils. After this PR, onert supports training of fused ReLU6.
issue : https://github.com/Samsung/ONE/issues/12388 
draft : https://github.com/Samsung/ONE/pull/12395
> [onert] Add ReLU6 grad to OperationUtils

- runtime/onert/backend/train/ops/DepthwiseConvolutionLayer.cc
This PR updates DConvLayer to use backpropActivation function in OperationUtils.
> [onert] Update DConvLayer to use backpropActivation

- tests/tools/onert_train/src/dataloader.h
This PR adds a virtual destructor for the onert_train's DataLoader class. Since DataLoader is base class, it should have virtual destructor.
> [tools/onert_train] Add virtual destructor for DataLoader

- infra/cmake/packages/BoostSourceConfig.cmake
- infra/nnfw/cmake/packages/BoostConfig.cmake
This commit update boost version to 1.84,0.
Boost 1.58.0 build fails when we use C++17.
> [infra] Version up boost

- runtime/onert/core/include/odc/ICodegen.h
This commit introduces ICodegen class.
The backend target compiler and Codegen loader will refer to this file together and will be implemented with the same structure.
Co-authored-by: Sanggyu Lee <sg5.lee@samsung.com>
Related issue: #12505 
> [onert] Introduce ICodegen class

- tests/tools/onert_train/CMakeLists.txt
This PR updates onert_train to use C++17.
draft : https://github.com/Samsung/ONE/pull/12445 
in the process to resolve : https://github.com/Samsung/ONE/issues/12520
> [tools/onert_train] Update onert_train to use C++17

- compute/cker/include/cker/Types.h
- compute/cker/include/cker/train/operation/Pad.h
- compute/cker/src/train/Pad.test.cc
This commit introduces Pad op in cker/train.
---
for: https://github.com/Samsung/ONE/issues/12413
draft: https://github.com/Samsung/ONE/pull/12499
> [cker/train] Introduce Pad op in train

- tests/tools/onert_train/src/nnfw_util.cc
- tests/tools/onert_train/src/nnfw_util.h
This PR refactors print logic of training information. 
It introduces NNFW_TRAIN_* enum to string map, which is referred when dump(print) function called.
draft : https://github.com/Samsung/ONE/pull/12445 
in the process to resolve : https://github.com/Samsung/ONE/issues/12520
> [tools/onert_train] Refactor print logic of train info

- runtime/onert/core/src/compiler/train/TrainableOperationConverter.cc
- runtime/onert/core/src/compiler/train/TrainableOperationConverter.h
Let's add Pad to TrainableOperationConverter.
---
for https://github.com/Samsung/ONE/issues/12413
draft https://github.com/Samsung/ONE/pull/12499
> [onert/train] Add Pad to TrainableOperationConverter

- tests/tools/onert_run/src/args.cc
- tests/tools/onert_run/src/args.h
This commit introduces compile and cpath arguments for codegen.
Related issue : https://github.com/Samsung/ONE/issues/12505
Draft PR: https://github.com/Samsung/ONE/pull/12504
> [tools/onert_run] Introduce compile and cpath arguments

- onert-micro/luci-interpreter/src/kernels/Add.cpp
- onert-micro/luci-interpreter/src/kernels/Dequantize.cpp
- onert-micro/luci-interpreter/src/kernels/FullyConnected.cpp
- onert-micro/luci-interpreter/src/kernels/Quantize.cpp
This commit fixes building with enabled DIS_QUANT flag.
> [onert-micro] Fix building with DIS_QUANT flag

- compiler/tflchef/tflite/src/RecipeChef.cpp
This commit fixes shadows local variable problem
for https://github.com/Samsung/ONE/pull/12516#discussion_r1467466083
> [tflchef] Fix shadows local variable problem

- onert-micro/luci-interpreter/src/kernels/CMakeLists.txt
- onert-micro/luci-interpreter/src/kernels/Conv2D.cpp
- onert-micro/luci-interpreter/src/kernels/ConvolutionCommon.cpp
- onert-micro/luci-interpreter/src/kernels/ConvolutionCommon.h
- onert-micro/luci-interpreter/src/kernels/DepthwiseConv2D.cpp
This commit reduces duplicate code in convolution kernels.
- Introduce `ConvolutionCommon.h` that has functions for convolution kernels. 
- Introduce `DownsamplingConv2DKernel` that unifies Conv2D kernels for downsampling. 
- Introduce `createConvParams()` that creates `luci_interpreter_pal::ConvParams` from Conv2D op.
- Apply common functions for convolution kernels.
---
For #11744
> [onert-micro] Reduce duplicate code in convolution kernels

- compiler/luci/pass/src/ResolveCustomOpAddPass.test.cpp
This commit introduces a dummy ResolveCustomOpAddPassTest to use TEST_F.
---
> [luci/pass] Introduce a ResolveCustomOpAddPassTest class to use TEST_F

- runtime/onert/backend/cpu/ops/PadLayer.h
- runtime/onert/backend/train/ops/OperationUtils.h
- runtime/onert/backend/train/ops/PadLayer.cc
- runtime/onert/backend/train/ops/PadLayer.h
This commit adds PadLayer op to train backend.
---
for https://github.com/Samsung/ONE/issues/12413
draft https://github.com/Samsung/ONE/pull/12499
> [onert/train] Add PadLayer op to train backend

- runtime/onert/core/include/odc/ICodegen.h
- runtime/onert/core/src/odc/CodegenLoader.cc
- runtime/onert/core/src/odc/CodegenLoader.h
This commit introduces CodegenLoader class.
This class loads the backend codegen library and provides a function to get the concreate class of ICodegen class.
Co-authored-by: Sanggyu Lee <sg5.lee@samsung.com>
Related issue : #12505 
> [onert] Introduce CodegenLoader class

- runtime/onert/backend/cpu/ops/BinaryArithmeticLayer.h
- runtime/onert/backend/train/KernelGenerator.cc
- runtime/onert/backend/train/KernelGenerator.h
- runtime/onert/backend/train/ops/BinaryArithmeticLayer.cc
- runtime/onert/backend/train/ops/BinaryArithmeticLayer.h
This commit implements BinaryArithmeticLayer in train backend.
From draft https://github.com/Samsung/ONE/pull/12417
> [onert] Implement BinaryArithmeticLayer in train backend

- runtime/onert/backend/cpu/KernelGenerator.cc
- runtime/onert/backend/cpu/ops/PadLayer.cc
- runtime/onert/backend/cpu/ops/PadLayer.h
- runtime/onert/backend/train/ops/PadLayer.cc
- runtime/onert/backend/train/ops/PadLayer.h
This commit fixes handling PadData of Pad op.
_**To support PadData as Tensor and const, I move handling pointer of value from KernelGenerator to PadOp::run().**_
---
for https://github.com/Samsung/ONE/issues/12541
> [onert/cpu] Fix handling PadData of Pad op

- res/TensorFlowLiteRecipes/Net_Shape_Add_000/test.recipe
This commit adds a TensorFlowLiteRecipes for testing to fold Shape
---
Draft: #12407
> [res] Add a TensorFlowLiteRecipes to test fold Shape

- compiler/luci-pass-value-py-test/test.lst
This commit adds a fold_shape test with Net_Shape_Add_000 model to luci-pass-value-py-test
---
Draft: #12407
> [luci-pass-value-py-test] Add fold_shape test

- runtime/onert/backend/train/KernelGenerator.cc
- runtime/onert/backend/train/KernelGenerator.h
Let's add Pad op to KernelGerator in train backend.
---
for https://github.com/Samsung/ONE/issues/12413
draft https://github.com/Samsung/ONE/pull/12499
> [onert/train] Add Pad op to KernelGerator in train backend

- onert-micro/onert-micro/include/core/OMDataType.h
- onert-micro/onert-micro/include/core/OMKernelData.h
- onert-micro/onert-micro/include/core/OMKernelType.h
- onert-micro/onert-micro/include/core/reader/OMCircleReader.h
- onert-micro/onert-micro/src/core/OMDataType.cpp
- onert-micro/onert-micro/src/core/OMKernelType.cpp
- onert-micro/onert-micro/src/core/reader/OMCircleReader.cpp
This pr adds circle reader entities: CircleReader class, data types and kernel types information classes.
> [onert-micro] Add circle reader entities

- compiler/luci-interpreter/include/luci_interpreter/BuddyMemoryManager.h
This commit prevents an overflow from bit shifting.
This change is suggested by our static analysis tool.
> [luci-interpreter] Prevent overflow from bit shifting

- compiler/luci/service/src/ShapeInfer_StridedSlice.cpp
This commit prevents an overflow from bit shifting.
This change is suggested by our static analysis tool.
> [luci] Prevent overflow from bit shifting

- compiler/luci/pass/src/helpers/SparsityFormatConverter.cpp
This commit casts to larger dtype before performing arithmetic.
This change is suggested by our static analysis tool.
> [luci] Casting to larger dtype before performing arithmetic

- runtime/onert/core/include/odc/CodegenManager.h
- runtime/onert/core/src/odc/CodegenManager.cc
This commit introduces CodegenManager class.
This class runs codegen() function to load target backend library and call the codegen function.
Co-authored-by: Sanggyu Lee <sg5.lee@samsung.com>
Related issue : #12505 
> [onert] Introduce CodegenManager class

- compiler/circle2circle-dredd-recipe-test/test.lst
This commit adds a dredd test for fold_shape with Net_Shape_Add_000 model to circle2circle-dredd-recipe-test
---
Draft: #12407
> [circle2circle-dredd-recipe-test] Add fold_shape test

- compiler/tflchef/tflite/src/Op/Less.cpp
This pr adds filler for Less op.
from https://github.com/Samsung/ONE/pull/12516
> [tflchef] Add filler for Less op

- tests/tools/onert_train/src/nnfw_util.cc
- tests/tools/onert_train/src/nnfw_util.h
This PR renames function naming :toString() -> to_string(). 
This is for the consistency of nnfw_util function naming convention.
> [tools/onert_train] Rename toString() to to_string()

- runtime/libs/misc/include/misc/to_underlying.h
- tests/tools/onert_train/src/nnfw_util.h
This PR add to_underlying function to onert/libs/misc.
This function is to get underlying numeric value from enum types.
ONE-DCO-1.0-Signed-off-by: SeungHui Youn <sseung.youn@samsung.com> 
draft : https://github.com/Samsung/ONE/pull/12545 
in the process to resolve: https://github.com/Samsung/ONE/issues/12520
> [onert/libs] Add to_underlying to misc

- runtime/onert/backend/cpu/ops/PadLayer.cc
This commit initialize PadLayer's `_value`.
> [onert] Initialize PadLayer

- runtime/onert/core/src/loader/base_loader.h
This commit adds metadata buffer check in base loader.
> [onert] Check metadata buffer

- tests/tools/onert_train/src/args.cc
- tests/tools/onert_train/src/args.h
- tests/tools/onert_train/src/onert_train.cc
This PR revises Args class to hold NNFW_TRAIN_* enum directly, instead of holding integer value.
draft : https://github.com/Samsung/ONE/pull/12445 
in the process to resolve : https://github.com/Samsung/ONE/issues/12520
> [tools/onert_train] Revise args to hold NNFW_TRAIN_* enum

- runtime/onert/backend/train/ops/BinaryArithmeticLayer.cc
This commit initialize train BinaryArithmeticLayer's `_arithmetic_type`, `_activation`, and `_act_back_prop_output`.
> [onert] Initialize train BinaryArithmeticLayer

- onert-micro/onert-micro/include/core/memory/OMMemoryManager.h
- onert-micro/onert-micro/include/core/memory/OMRuntimeAllocator.h
- onert-micro/onert-micro/src/core/memory/OMMemoryManager.cpp
- onert-micro/onert-micro/src/core/memory/OMRuntimeAllocator.cpp
This pr adds core/memory part of the new onert-micro.
> [onert-micro] Add core/memory part

- runtime/onert/core/include/loader/ILoader.h
This commit introduces ILoader.
ILoader is a interface for built-in loaders and loader plugin.
---
Related issue: #12482
Draft: #12563
> [onert] Introduce ILoader

- runtime/onert/backend/train/KernelGenerator.cc
This commit fixes wrong param order of PadLayer in KernelGenerator.
---
to fix https://github.com/Samsung/ONE/issues/12590
> [onert/train] Fix wrong param order of PadLayer

- runtime/onert/api/nnfw/src/nnfw_api_internal.cc
This commit removes copy by auto in train_get_traininfo API implementation.
> [onert] Remove copy by auto in train_get_traininfo

- runtime/onert/backend/train/KernelGenerator.cc
This commit removes copy by auto in train backend KernelGenerator.
> [onert/train] Remove copy by auto in KernelGenerator

- compiler/luci/pass/src/ReplaceNonConstFCWithBatchMatMulPass.cpp
- compiler/luci/pass/src/ReplaceNonConstFCWithBatchMatMulPass.test.cpp
This replaces const-input FC with matmul.
> [luci] Replace const-input FC with matmul

- runtime/onert/api/nnfw/include/nnfw_experimental.h
- runtime/onert/api/nnfw/src/nnfw_api.cc
- runtime/onert/api/nnfw/src/nnfw_api_internal.cc
- runtime/onert/api/nnfw/src/nnfw_api_internal.h
This commit introduces nnfw_compile and nnfw_set_compiled_model_path.
It contains a detailed description of these APIs in the header file.
Co-authored-by: Sanggyu Lee <sg5.lee@samsung.com>
Related issue : #12505 
> [onert/api] Introduce nnfw_compile and nnfw_set_compiled_model_path APIs

- compute/cker/src/train/BinaryArithmetic.test.cc
This commit adds more BinaryArithmeticDistinctShape tests.
---
Relevant: https://github.com/Samsung/ONE/pull/12554#discussion_r1472298518
> [cker] Add more BinaryArithmeticDistinctShape tests

- tests/tools/onert_train/src/args.cc
- tests/tools/onert_train/src/args.h
- tests/tools/onert_train/src/onert_train.cc
This PR removes default value from onert_train's Args class. This is to use model file parameter as default value, if nothing is given from command line input.
related with: https://github.com/Samsung/ONE/issues/12520
> [tools/onert_train] Remove default value from onert_train/args

- runtime/onert/core/src/ir/train/TrainableGraph.cc
This commit fixes missing throw expression.
> [onert] Fix missing throw expression

- tests/tools/onert_run/src/args.cc
- tests/tools/onert_run/src/args.h
- tests/tools/onert_run/src/onert_run.cc
This commit implements codegen function in onert_run.
As discussed below, the `compile` string of functions and variables
has been changed to `codegen`.
https://github.com/Samsung/ONE/pull/12583#issuecomment-1920675804
Related issue : #12505 
> [tools/onert_run] Implement codegen function

- runtime/onert/core/src/loader/circle_traininfo.fbs
- runtime/onert/core/src/loader/circle_traininfo_generated.h
This PR updates circle_traininfo schema and its' generated file to include loss reduction type.
to resolve : https://github.com/Samsung/ONE/issues/12606
> [onert/core] Update circle_traininfo to support loss reduction type

- runtime/onert/core/src/loader/traininfo_loader.cc
This PR updates traininfo_loader to support loss reduction type.
to-resolve : https://github.com/Samsung/ONE/issues/12606
> [onert/core] Update traininfo_loader to support loss reduction type

- infra/nnfw/cmake/buildtool/cross/toolchain_aarch64-android.cmake
This commit fixes android toolchain setting for cmake find mode.
---
Found this on #12604
> [infra/onert] Fix cmake find mode on android

- compiler/luci/pass/src/ResolveCustomOpAddPass.cpp
This commit adds note comments to know about ResolveCustomOpAddPass.
---
> [luci/pass] Add note comments to know about ResolveCustomOpAddPass

- onert-micro/onert-micro/include/import/OMConfigureArgs.h
- onert-micro/onert-micro/include/import/OMExecutionPlanCreator.h
- onert-micro/onert-micro/include/import/OMKernelConfiguration.h
- onert-micro/onert-micro/include/import/OMKernelConfigureBuilder.h
- onert-micro/onert-micro/src/import/CMakeLists.txt
- onert-micro/onert-micro/src/import/OMExecutionPlanCreator.cpp
- onert-micro/onert-micro/src/import/OMKernelConfiguration.cpp
- onert-micro/onert-micro/src/import/OMKernelConfigureBuilder.cpp
This pr adds import entities part to the onert-micro
> [onert-micro] Add import part

- runtime/onert/api/nnapi/CMakeLists.txt
This commit strips NNAPI frontend library to reduce binary size.
> [onert] Strip NNAPI frontend library

- compiler/luci/pass/src/ResolveCustomOpAddPass.cpp
- compiler/luci/pass/src/ResolveCustomOpAddPass.test.cpp
This will revise ResolveCustomOpAddPass to process built-in BroadcastTo. 
In addition, more unit tests were added to ResolveCustomOpAddPass to test BroadcastTo-AddV2 pattern.
---
> [luci/pass] Revise ResolveCustomOpAddPass to process BroadcastTo

- res/TensorFlowLiteRecipes/Net_BroadcastTo_AddV2_002/test.rule
This commit revises Net_BroadcastTo_AddV2_002 test.rule.
---
> [res] Revise Net_BroadcastTo_AddV2_002 test.rule

- compiler/luci-pass-value-py-test/test_luci_eval.py
This commit removes unused variables in the python script.
> [luci-pass-value-py-test] Remove unused variable

- compiler/pota-quantization-value-test/compare_tensors_all.py
- compiler/pota-quantization-value-test/test_fake_wquant_with_config.sh
- compiler/pota-quantization-value-test/test_parallel_record_minmax.sh
- compiler/pota-quantization-value-test/test_quantization_with_config.sh
This commit fixes the bug where the mode was not set properly.
Related: #12526 
> [pota-quantization-value-test] Set right mode

- onert-micro/onert-micro/include/execute/OMExecuteArgs.h
- onert-micro/onert-micro/include/execute/OMKernelExecute.h
- onert-micro/onert-micro/include/execute/OMKernelExecutionBuilder.h
- onert-micro/onert-micro/include/execute/OMRuntimeKernel.h
- onert-micro/onert-micro/include/execute/OMTestUtils.h
- onert-micro/onert-micro/include/execute/OMUtils.h
- onert-micro/onert-micro/src/execute/CMakeLists.txt
- onert-micro/onert-micro/src/execute/OMKernelExecute.cpp
- onert-micro/onert-micro/src/execute/OMKernelExecutionBuilder.cpp
- onert-micro/onert-micro/src/execute/OMRuntimeKernel.cpp
- onert-micro/onert-micro/src/execute/OMTestUtils.cpp
- onert-micro/onert-micro/src/execute/OMUtils.cpp
This pr adds execute entities part to the onert-micro.
> [onert-micro] Add execute part

- compiler/luci-pass-value-py-test/test.lst
This will enable value test of remove_gather_guard option.
> [luci-pass-value-py-test] For remove_gather_guard option

- res/CircleSchema/0.7/circle_schema.fbs
- res/CircleSchema/0.8/circle_schema.fbs
This pr adds CirGru operation in circle_schema.fbs
for issue: #12320
from draft: #12319
> [res] Add GRU in CircleSchema

- compiler/luci/pass/src/SubstitutePadV2ToPadPass.cpp
This will revise SubstitutePadV2ToPadPass to support all Ops that can have ReLU fused activation.
> [luci/pass] Revise SubstitutePadV2ToPadPass

- compiler/circle2circle/src/Circle2Circle.cpp
This will enable fuse_add_with_conv option to perform Fusion of Add to Conv2D.
> [circle2circle] Enable ifuse_add_with_conv option

- runtime/onert/core/src/compiler/ExecutorFactory.cc
This commit configures the `context_data_map` using the backend
information of lgraph.
Co-authored-by: Hyeongseok Oh <hseok82.oh@samsung.com>
> [onert] Configure context_data_map using the backend info of lgraph 

- compiler/luci-pass-value-py-test/test.lst
This will enable pass value test for fuse_add_with_conv option.
> [luci-pass-value-test] Enable test for fuse_add_with_conv

- runtime/onert/core/include/ir/train/ITrainableOperation.h
- runtime/onert/core/include/ir/train/operation/BinaryArithmetic.h
- runtime/onert/core/include/ir/train/operation/Conv2D.h
- runtime/onert/core/include/ir/train/operation/DepthwiseConv2D.h
- runtime/onert/core/include/ir/train/operation/ElementwiseActivation.h
- runtime/onert/core/include/ir/train/operation/FullyConnected.h
- runtime/onert/core/include/ir/train/operation/Loss.h
- runtime/onert/core/include/ir/train/operation/Pad.h
- runtime/onert/core/include/ir/train/operation/Permute.h
- runtime/onert/core/include/ir/train/operation/Pool2D.h
- runtime/onert/core/include/ir/train/operation/Reduce.h
- runtime/onert/core/include/ir/train/operation/Reshape.h
- runtime/onert/core/include/ir/train/operation/Softmax.h
- runtime/onert/core/include/ir/train/operation/UntrainableOperation.h
This commit adds hasTrainableParameter member function to ITrainableOperation.
This member function will be used in subsequent commit to truncate nodes which are not reachable from any node with trainable parameters.
---
From draft https://github.com/Samsung/ONE/pull/12621
> [ONERT] Add hasTrainableParameter member function

- runtime/onert/api/nnfw/src/nnfw_api_internal.cc
- runtime/onert/core/include/loader/CircleLoader.h
- runtime/onert/core/include/loader/TFLiteLoader.h
- runtime/onert/core/include/loader/TrainInfoLoader.h
- runtime/onert/core/src/loader/BaseLoader.h
- runtime/onert/core/src/loader/CircleLoader.cc
- runtime/onert/core/src/loader/TFLiteLoader.cc
- runtime/onert/core/src/loader/TrainInfoLoader.cc
This commit renames loader file and namespace.
---
Related issue: https://github.com/Samsung/ONE/issues/12482
Draft: #12563
> [onert] Rename loader file and namespace

- .readthedocs.yml
This commit adds the required elements to the readthedocs config to make it work again.
ONE-DCO-1.0-Signed-off-by: Piotr Fusik <piotr@fusion-lang.org>
> [doc] Update the readthedocs configuration

- compute/cker/include/cker/eigen/redux_functor.h
- runtime/onert/backend/train/ops/ConvolutionLayer.cc
- runtime/onert/backend/train/ops/DepthwiseConvolutionLayer.cc
- runtime/onert/backend/train/ops/OperationUtils.cc
- runtime/onert/backend/train/ops/OperationUtils.h
This commit optimizes bias grad computation with multithreading.
---
From draft https://github.com/Samsung/ONE/pull/12571, https://github.com/Samsung/ONE/pull/12666
Relevant issue: https://github.com/Samsung/ONE/issues/12569
> [onert] Optimize Bias Grad Computation

- tests/nnfw_api/src/GenModelTests/one_op_trains/Conv2D.test.cc
This commit adds a Conv2D test for train as an example.
---
draft: https://github.com/Samsung/ONE/pull/12665
> [tests/nnfw_api] Add Conv2D test for train

- tests/tools/onert_train/README.md
This PR adds onert_train usage to the readme.
related : https://github.com/Samsung/ONE/issues/12605
from draft : https://github.com/Samsung/ONE/pull/12694
> [tools/onert_train] Add onert_train usage to readme

- tests/tools/onert_train/README.md
This PR adds a example to use onert_train in the readme.
> [tools/onert_train] Add onert_train usage example to readme

- runtime/onert/core/src/compiler/ShapeValidator.cc
- runtime/onert/core/src/compiler/ShapeValidator.h
- tests/nnfw_api/src/GenModelTests/one_op_tests/Conv2D.test.cc
- tests/nnfw_api/src/GenModelTests/one_op_tests/DepthwiseConv2D.test.cc
This commit forces bias operands to be either null or of rank 1, and fixes some tests violating this condition.
> [onert] Force bias rank to 1 and fix GenModelTests

- compiler/circle-tensordump/CMakeLists.txt
- compiler/circle-tensordump/requires.cmake
> [circle-tensordump] Revise to use mio-circle08

- compiler/luci/export/src/CircleBuiltinTypesExtractor.h
- compiler/luci/export/src/CircleOps.lst
This adds support for GRU operation in luci export.
> [luci/export] Support GRU operation

- compiler/circlechef/circle/src/CircleOpChefs.h
- compiler/circlechef/circle/src/CircleOpRegistry.h
- compiler/circlechef/circle/src/Op/GRU.cpp
- compiler/circlechef/circle/src/Op/GRU.h
- compiler/circlechef/core/src/Op/GRU.cpp
- compiler/circlechef/core/src/Op/GRU.h
- compiler/circlechef/core/src/OpChef.def
- compiler/circlechef/core/src/OpChefs.h
- compiler/circlechef/proto/circlechef.proto
This adds support for GRU operation in circlechef.
> [circlechef] Support GRU operation

- compiler/tflchef/core/src/Convert.cpp
- compiler/tflchef/core/src/DataChef.def
- compiler/tflchef/core/src/ModelChef.cpp
- compiler/tflchef/proto/tflchef.proto
- compiler/tflchef/tests/short_int4/test.recipe
- compiler/tflchef/tests/short_int4_quant/test.recipe
This will enable to support int4 datatype.
> [tflchef] Support int4 datatype

- compiler/tflchef/proto/tflchef.proto
This will revise INT4 TensorType to 17 to follow FB scheme.
> [tflchef] Revise INT4 TensorType

- compiler/tflchef/core/src/DataChef.def
This will revise to use specialized Int4DataChef class for INT4.
> [tflchef] Fix to use Int4DataChef

- runtime/libs/circle-schema/include/circle_traininfo.fbs
This PR removes a line to sync with inner source.
From now, traininfo schema file will be maintained here, not in inner source.
> [onert/lib] Remove a sync line from circle_traininfo schema

- compiler/luci/lang/src/DataTypeHelper.cpp
This will add empty DataTypeHelper.cpp to validate header file.
> [luci/lang] Add empty DataTypeHelper.cpp

- compiler/circle-eval-diff/src/InputDataLoader.cpp
> [circle-eval-diff] Revise to use luci::size

- compiler/circle-mpqsolver/src/core/ErrorMetric.cpp
- compiler/circle-mpqsolver/src/core/Evaluator.cpp
> [circle-mpqsolver] Revise to use luci::size

- compiler/circle-execution-plan/pal/ScratchpadHelperLinux.h
> [circle-execution-plan] Revise to use luci::size

- compiler/circle-interpreter/src/CircleInterpreter.cpp
> [circle-interpreter] Revise to use luci::size

- compiler/circle-part-driver/src/PModelsRunner.cpp
> [circle-part-driver] Revise to use luci::size

- compiler/luci-eval-driver/src/EvalDriver.cpp
> [luci-eval-driver] Revise to use luci::size

- compiler/common-artifacts/src/TestDataGenerator.cpp
> [common-artifacts] Revise to use luci::size

- compiler/dalgona/src/Dalgona.cpp
> [dalgona] Revise to use luci::size

- compiler/embedded-import-value-test/src/TestDriver.cpp
> [embedded-import-value-test] Revise to use luci::size

- compiler/luci-interpreter/include/luci_interpreter/core/DataType.h
> [luci-interpreter] Revise to use luci::size

- compiler/record-minmax/src/RecordMinMax.cpp
> [record-minmax] Revise to use luci::size

- compiler/tflchef/core/src/ModelChef.cpp
This will add assert filler for sparse with INT4 as currently we don't support this.
> [tflchef] Assert filler for sparse with INT4

- compiler/circledump/src/OpPrinter.cpp
This pr adds GRUPrinter in circledump.
> [circledump] Add GRUPrinter

- compiler/luci/service/src/CircleCloneNode.h
- compiler/luci/service/src/CircleShapeInferenceRule.cpp
- compiler/luci/service/src/CircleTypeInferenceRule.cpp
- compiler/luci/service/src/Nodes/CircleGRU.cpp
- compiler/luci/service/src/Nodes/CircleGRU.test.cpp
This adds support for GRU operation in luci service.
> [luci/service] Support GRU operation

- compiler/common-artifacts/exclude.lst
This will revise exclude.lst tcgenerate for INT4/UINT4 recipes.
> [common-artifacts] Exclude for I4/U4 recipes

- compiler/luci/partition/include/luci/ConnectNode.h
- compiler/luci/partition/src/Nodes/CircleGRU.cpp
- compiler/luci/partition/src/Nodes/CircleGRU.test.cpp
This adds support for GRU operatino in luci partition.
> [luci/partition] Support GRU Operation

- compiler/common-artifacts/exclude.lst
This disables the test of GRU operation until it's fully supported.
> [common-artifacts] Exclude GRU operation

- res/CircleRecipes/GRU_000/test.recipe
This pr adds a CircleRecipe for GRU op.
> [res] Add a CircleRecipe for GRU

- compiler/luci/pass/src/FoldDequantizePass.cpp
- compiler/luci/pass/src/FoldDequantizePass.test.cpp
This supports s4/u4 in FoldDequantizePass.
---
Draft PR: #12806
> [luci/pass] Support s4/u4 in FoldDequantizePass

- compiler/luci/pass/src/QuantizeActivation.cpp
- compiler/luci/pass/src/QuantizeActivation.h
This quantizes const input of SelectV2 Op.
---
> [luci/pass] Quantize const input of SelectV2

- compiler/luci/pass/src/QuantizeActivation.h
- compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
This removes unused fields in QuantizeActivation classes.
> [luci] Remove unused fields

- compiler/luci/pass/src/QuantizeWithPredecessorPass.cpp
- compiler/luci/pass/src/QuantizeWithPredecessorPass.h
- compiler/luci/pass/src/QuantizeWithPredecessorPass.test.cpp
This introduces a pass to quantize with predecessors.
---
> [luci/pass] Introduce QuantizeWithPredecessorPass

- compiler/luci/pass/include/luci/Pass/QuantizeOnnxFakeQuantModelPass.h
- compiler/luci/pass/src/QuantizeOnnxFakeQuantModelPass.cpp
- compiler/luci/pass/src/QuantizeOnnxFakeQuantModelPass.test.cpp
This introduces a pass to quantize onnx-fake-quantized model.
---
> [luci/pass] Introduce QuantizeOnnxFakeQuantModelPass

- compiler/luci/pass/src/QuantizationUtils.cpp
- compiler/luci/pass/src/QuantizationUtils.h
- compiler/luci/pass/src/QuantizeWeightsOnly.cpp
This commit adds INT4 weights quantization to QuantizeWeightsOnly.cpp.
> [luci] Add INT4 weights quantization to quantizer

- compiler/one-cmds/CMakeLists.txt
- Add `Command.py` of onelib to cmake.
> Add missing python file.

- compiler/luci/pass/src/CircleQuantizer.cpp
This commit enables INT4 weight quantization in circle-quantizer.
> [luci] Enable INT4 weight quantization in circle-quantizer

- compiler/common-artifacts/exclude.lst
This will add exclude tcgenerate for FullyConnected_I4_002.
> [common-artifacts] Exclude FullyConnected_I4_002

- compiler/common-artifacts/exclude.lst
This will sort for FullyConnected_I4_* models.
> [common-artifacts] Sort for FullyConnected_I4

- compiler/luci-interpreter/src/kernels/FullyConnected.cpp
- compiler/luci-interpreter/src/kernels/FullyConnected.test.cpp
This commit adds support of per-channel quantization in Hybrid INT4 FullyConnected kernel.
> [luci-interpreter] Support per-channel quantization in Hybrid INT4 FC

- infra/nncc/command/install
This commit introduces nncc install command.
It simplifies nncc install path setting on local environment by using "--prefix" option.
> [infra] Introduce nncc install command

- compiler/luci-ref-value-py-test/CMakeLists.txt
- compiler/luci-ref-value-py-test/conftest.py
- compiler/luci-ref-value-py-test/test.lst
This will enable circle model test with CircleFullyConnected_U4_002.
> [luci-ref-value-py-test] Enable circle test with FC_U4

- compiler/luci/pass/src/CopyQuantParamPass.cpp
This supports copying qparam to circle output.
> [luci] Copy qparam to circle output

- onert-micro/onert-micro/include/pal/common/PALMaxPool2DCommon.h
This commit removes unused include in MaxPool2D kernel.
> [onert-micro] Remove unused include in MaxPool2D kernel

- runtime/onert/core/include/util/ShapeInference.h
- runtime/onert/core/src/compiler/StaticShapeInferer.cc
- runtime/onert/core/src/exec/DynamicShapeInferer.cc
- runtime/onert/core/src/util/ShapeInference.cc
This commit fixes to handle batch input shape inference on Reshape operator.
---
Related issue: #12859
> [onert] Handle batch input shape inference on Reshape operator

- runtime/onert/core/include/exec/DynamicShapeInferer.h
- runtime/onert/core/src/exec/DynamicShapeInferer.cc
This commit adds Pool2D dynamic shape inference.
> [onert] Introduce Pool2D dynamic shape inference

- compiler/luci/pass/src/QuantizeOnnxQDQPass.cpp
- compiler/luci/pass/src/QuantizeOnnxQDQPass.test.cpp
This extends QuantizeOnnxQDQPass to support u8 activation and s16 const.
---
> [luci] Extend QuantizeOnnxQDQPass

- compiler/luci/pass/src/QuantizeOnnxDequantizeLinearPass.cpp
- compiler/luci/pass/src/QuantizeOnnxDequantizeLinearPass.test.cpp
This support s16 in QuantizeOnnxDequantizeLinearPass.
---
> [luci] Extend QuantizeOnnxDequantizeLinearPass

- compiler/luci/pass/src/QuantizeWithPredecessorPass.cpp
- compiler/luci/pass/src/QuantizeWithPredecessorPass.test.cpp
This supports Squeeze Op in QuantizeWithPredecessorPass.
---
> [luci] Support Squeeze in QuantizeWithPredecessorPass

- compiler/luci/pass/include/luci/CircleOptimizer.h
- compiler/luci/pass/include/luci/Pass/FoldSqueezePass.h
- compiler/luci/pass/src/CircleOptimizer.cpp
- compiler/luci/pass/src/FoldSqueezePass.cpp
- compiler/luci/pass/src/FoldSqueezePass.test.cpp
This implements constant folding for Squeeze Op.
---
Draft PR: #12865
> [luci] Add FoldSqueeze pass

- compiler/luci/pass/src/InsertQuantizeOpOnDTypeMismatch.cpp
- compiler/luci/pass/src/InsertQuantizeOpOnDTypeMismatch.h
- compiler/luci/pass/src/InsertQuantizeOpOnDTypeMismatch.test.cpp
- compiler/luci/pass/src/QuantizeOnnxFakeQuantModelPass.cpp
This inserts Quantize Op to quantize mixed-precision onnx model.
---
> [luci] Insert Quantize Op to quantize mixed-precision onnx

- runtime/onert/api/nnapi/wrapper/ANeuralNetworksExecution.cc
- runtime/onert/core/include/exec/Execution.h
- runtime/onert/core/include/exec/IODescription.h
- runtime/onert/core/include/ir/OperandInfo.h
- runtime/onert/core/src/exec/Execution.cc
- runtime/onert/core/src/exec/Execution.test.cc
- runtime/onert/core/src/exec/ExecutorBase.cc
This commit updates Execution and IODescription
- Remove input shape map in IODesciption (use InputDesc vector and updated field)
- Remove layout setting in Execution's setInput and setOutput
- Remove type setting in Execution's setInput and setOutput
- Introduce new method to set input/output type in Execution
> [onert] Update I/O info handling

- runtime/onert/core/src/exec/Execution.cc
This commit removes outdated TODO comment in Execution.cc.
---
Refer https://github.com/Samsung/ONE/pull/12867#discussion_r1568128771
> [onert] Remove outdated TODO comment

- runtime/onert/backend/train/DisposableTensorIndex.h
This commit introduces DisposableTensorIndex for tensors that are only temporarily used within a node.
> [onert] Introduce DisposableTensorIndex

- compiler/one-cmds/one-build
- compiler/one-cmds/onecc
- compiler/one-cmds/onelib/CfgRunner.py
- compiler/one-cmds/onelib/utils.py
This commit supports inline comments in the cfg file.
Related: #12884
> [one-cmds] Support inline comment in the cfg file

- runtime/onert/backend/train/ops/BackPropAccumulator.cc
- runtime/onert/backend/train/ops/BackPropAccumulator.h
This commit introduces BackPropAccumulator that sums branched back-prop tensors accumulatively.
> [onert] Introduce BackPropAccumulator

- infra/nnfw/cmake/packages/Giounix2.0Config.cmake
This commit changes the target file to "gfiledescriptorbased.h" for finding the gio-unix-2.0 header. 
"gunixfdlist.h" is moved into glib-2.0 header directory on tizen 9.0.
> [infra] Update gio-unix-2.0 header directory finding

- compiler/one-cmds/tests/onecc_059.cfg
- compiler/one-cmds/tests/onecc_059.test
This commit adds a test that checks if writing comments inside the cfg file are allowed.
> [one-cmds] Add test that checks if writing comments are enabled

- runtime/onert/core/src/loader/BaseLoader.h
This commit adds param initialization for ResizeBilinear and ResizeNearestNeighbor in BaseLoader.h
> [onert] Initialize param in BaseLoader

- runtime/onert/api/nnfw/include/nnfw.h
- runtime/onert/api/nnfw/src/nnfw_api.cc
- runtime/onert/api/nnfw/src/nnfw_api_internal.cc
- runtime/onert/api/nnfw/src/nnfw_api_internal.h
This commit removes deprecated API implementation: apply_tensorinfo. 
If nnfw_apply_tensorinfo is called, it will return NNFW_STATUS_DEPRECATED_API status value.
> [onert] Remove apply_tensorinfo

- compiler/one-cmds/one-prepare-venv
This will upgrade onnx, onnxruntime of one-prepare-venv.
> [one-cmds] Upgrade onnx, onnxruntime

- runtime/onert/api/nnapi/wrapper/ANeuralNetworksExecution.cc
This commit removes analyzer's warning by ir::Shape copy in ANeuralNetworksExecution.
> [onert] Remove copy warning in ANeuralNetworksExecution 

- runtime/onert/backend/train/DisposableTensorIndex.h
This commit fixes hash value of DisposableTensorIndex.
- Change hash value size of DisposableTensorIndex from 64-bit to 32-bit
- Add a message to a static_assert because the static_assert without message is introduced since c++17
- Add a constraint that checks overflow of hash value
> [onert] Fix hash value size of DisposableTensorIndex

- compiler/one-cmds/one-prepare-venv
- compiler/one-cmds/one-prepare-venv.aarch64
- compiler/one-cmds/one-prepare-venv.u1804
This will revise torch source override method to general way instead of `-f` which is `--find-links`. With this we can override `--index-url` so that we can use other cache servers.
> [one-cmds] Revise torch source override

- Makefile.template
- packaging/nnfw.spec
This commit disable luci build on onert build process temporarily for flatbuffer migration.
> [infra] Disable onert luci build

- compiler/one-cmds/one-prepare-venv.aarch64
- compiler/one-cmds/one-prepare-venv.u1804
This will update onnx/onnxruntime versions for U18.04 and AArch64 one-prepare-venv files.
> [one-cmds] Update onnx/onnxruntime versions

- compiler/enco/frontend/tflite/CMakeLists.txt
This commit updates enco to use FlatBuffers 23.5.26.
> [enco] Use FlatBuffers 23.5.26

- compiler/exo/CMakeLists.txt
This commit updates exo to use FlatBuffers 23.5.26.
> [exo] Use FlatBuffer 23.5.26

- compiler/mio-circle08/CMakeLists.txt
This commit updates mio-circle08 to use FlatBuffers 23.5.26.
> [mio-circle08] Use FlatBuffer 23.5.26

- compiler/mio-tflite280/CMakeLists.txt
This commit updates mio-tflite280 to use FlatBuffers 23.5.26.
> [mio-tflite280] Use FlatBuffer 23.5.26

- compiler/mir/src/mir_tflite_importer/CMakeLists.txt
This commit updates mir to use FlatBuffers 23.5.26.
> [mir] Use FlatBuffer 23.5.26

- compiler/pics/CMakeLists.txt
This commit updates pics to use FlatBuffers 23.5.26.
> [pics] Use FlatBuffer 23.5.26

- compiler/mio-tflite2121/CMakeLists.txt
This commit updates mio-tflite2121 to use FlatBuffers 23.5.26.
> [mio-tflite2121] Use FlatBuffer 23.5.26

- compiler/mio-tflite260/CMakeLists.txt
This commit updates mio-tflite260 to use FlatBuffers 23.5.26.
> [mio-tflite260] Use FlatBuffer 23.5.26

- compiler/mio-tflite/CMakeLists.txt
This commit updates mio-tflite260 to use FlatBuffers 23.5.26.
> [mio-tflite] Use FlatBuffer 23.5.26

- compiler/mio-circle07/CMakeLists.txt
This commit updates mio-circle07 to use FlatBuffers 23.5.26.
> [mio-circle07] Use FlatBuffer 23.5.26

- compiler/mio-circle06/CMakeLists.txt
This commit updates mio-circle06 to use FlatBuffers 23.5.26.
> [mio-circle06] Use FlatBuffer 23.5.26

- compiler/mio-circle05/CMakeLists.txt
This commit updates mio-circle05 to use FlatBuffers 23.5.26.
> [mio-circle05] Use FlatBuffer 23.5.26

- compiler/mio-circle04/CMakeLists.txt
This commit updates mio-circle04 to use FlatBuffers 23.5.26.
> [mio-circle04] Use FlatBuffer 23.5.26

- compiler/mio-circle/CMakeLists.txt
This commit updates mio-circle to use FlatBuffers 23.5.26.
> [mio-circle] Use FlatBuffer 23.5.26

- runtime/onert/core/src/compiler/ShapeValidator.cc
This commit updates ShapeValidator.cc to apply more strict shape validation on Conv2D, DepthwiseConv2D, and FullyConnected.
> [onert] Apply more strict shape validation check

- runtime/onert/backend/train/ops/BackPropInitializer.cc
- runtime/onert/backend/train/ops/BackPropInitializer.h
This commit introduces BackPropInitilizer that initializes buffers of back-prop tensors.
> [onert] Introduce BackPropInitializer

- runtime/onert/core/src/backend/basic/MemoryManager.cc
- runtime/onert/core/src/backend/basic/MemoryPlanner.cc
- runtime/onert/core/src/backend/basic/MemoryPlanner.h
- runtime/onert/core/src/backend/basic/MemoryPlanner.test.cc
- runtime/onert/core/src/backend/basic/MemoryPlannerFactory.cc
- runtime/onert/core/src/backend/basic/MemoryPlannerFactory.h
This commit reverts applying template to memory planners in core backend.
> [onert] Revert applying template to memory planners in core backend

- infra/debian/compiler/postinst
This commit introduces whitelist env option to the su command.
> [debian] Introduce whitelist env option to the su command

- compiler/tflite2circle/src/DataLookup.cpp
This will revise wrong op message to unsupported op with opcode name string for better problem solving.
> [tflite2circle] Revise wrong op message

- runtime/onert/backend/train/MemoryPlanner.cc
- runtime/onert/backend/train/MemoryPlanner.h
- runtime/onert/backend/train/MemoryPlannerFactory.cc
- runtime/onert/backend/train/MemoryPlannerFactory.h
This commit introduces memory planners into train backend.
> [onert] Introduce memory planners into train backend

- infra/debian/compiler/postinst
This commit revisits postinst script.
- Elaborate comments for better understanding
- Use `p` option when `w` option isn't supported in the old ubunut.
Related: https://github.com/Samsung/ONE/issues/12952#issuecomment-2089508327
> [debian] Revisit postinst script

- compiler/luci-interpreter/src/kernels/SelectV2.cpp
- compiler/luci-interpreter/src/kernels/SelectV2.h
- compiler/luci-interpreter/src/kernels/SelectV2.test.cpp
This will enable `S32(int32_t)` type of input argument in `SelectV2` operation.
---
for issue #12959
> [luci-interpreter] Enable S32 type in SelectV2 op

- infra/debian/compiler/postinst
This commit makes postinst use ubuntu codename instead of the su exit code.
Related: https://github.com/Samsung/ONE/issues/12952#issuecomment-2091797159
> [debian] Fix postinst script

- compiler/luci/pass/include/luci/CircleOptimizer.h
- compiler/luci/pass/include/luci/Pass/RemoveQDQForMixedPrecisionOpPass.h
- compiler/luci/pass/src/CircleOptimizer.cpp
- compiler/luci/pass/src/RemoveQDQForMixedPrecisionOpPass.cpp
- compiler/luci/pass/src/RemoveQDQForMixedPrecisionOpPass.test.cpp
This adds a pass to remove QDQ to simulate mixed-precision Op.
---
Related to: https://github.com/Samsung/ONE/issues/12965
Draft PR: #12966
> [luci] Remove QDQ to simulate mixed-precision Op

- runtime/onert/backend/train/DisposableTensorIndex.h
- runtime/onert/backend/train/MemoryManager.cc
- runtime/onert/backend/train/MemoryManager.h
- runtime/onert/backend/train/TensorManager.cc
- runtime/onert/backend/train/TensorManager.h
This commit introduces DisposableMemoryManager that manages memories of disposable tensors
- Introduce DisposableMemoryManager into train backend
- Add DisposableMemoryManager to TensorManager
> [onert] Introduce DisposableMemoryManager into train backend

- compiler/enco/test/tflite/CMakeLists.txt
This will revise enco/test to skip build if nnkit_tflite_backend is not found.
> [enco/test] Skip if no nnkit_tflite_backend

- runtime/onert/backend/cl_common/include/cl_common/BackendContext.h
- runtime/onert/backend/cpu/BackendContext.cc
- runtime/onert/backend/gpu_cl/BackendContext.cc
- runtime/onert/backend/ruy/BackendContext.cc
- runtime/onert/backend/train/BackendContext.cc
- runtime/onert/backend/trix/BackendContext.cc
- runtime/onert/backend/xnnpack/BackendContext.cc
- runtime/onert/core/include/backend/BackendContext.h
- runtime/onert/core/include/backend/train/TrainableBackendContext.h
- runtime/onert/core/src/backend/builtin/BackendContext.cc
- runtime/onert/core/src/backend/builtin/train/BackendContext.cc
This commit changes FunctionMap to unordered_map for the following reasons:
- Name mismatch : Although the name contains map, it was actually a vector, not a map
- Search time : Searching by key will be added, search time needed to be improved.
---
Related issue : #12945
> [onert] Change FunctionMap to unordered_map

- runtime/onert/backend/train/TensorBuilder.cc
- runtime/onert/backend/train/TensorBuilder.h
This commit introduces DisposableBackPropTensor into TensorBuilder.
- Add a member function that can register disposable tensors to be used in backwarding
- Add member functions that schedules memoies of disposable tensors for back-propagation
> [onert] Introduce DisposableBackPropTensor into TensorBuilder

- runtime/onert/backend/train/BackendContext.cc
- runtime/onert/backend/train/BackendContext.h
This commit applies BackPropInitializer layer to train backend.
BackPropInitializer layer is called at the beginning of the TrainableFnSequence that first uses the corresponding BackPropTensor.
> [onert] Apply BackPropInitializer layer

- runtime/onert/api/nnfw/src/nnfw_api_internal.cc
This commit fixes a bug that on-device quantization type setting is invalided on uint8 type.
> [onert] Fix quantization type setting bug

- compiler/circle-interpreter/src/CircleInterpreter.cpp
- compiler/luci-interpreter/include/luci_interpreter/Interpreter.h
- compiler/luci-interpreter/src/Interpreter.cpp
This PR makes a new interface `getOutputTensorSize` in the luci-interpreter.
This is to get the size of actual output size from the `_runtime_module`, which has the inferred and calculated output shape during the interprete process.
---
for issue #12979
from draft #12981
> [luci-interpreter] Add a feature to infer the output shape

- compiler/luci/pass/src/QuantizeOnnxQDQPass.cpp
This commit adds missing header inclusion needed for std::numeric_limits<int16_t>::max() call.
Signed-off-by: Piotr Kotynia <p.kotynia@partner.samsung.com>
> [luci] Add missing #include <limits>

- compiler/circle-interpreter/src/CircleInterpreter.cpp
This PR will uses the actual output tensor size calculated from luci-interpreter, which will makes the dynamic shape of model possible to generate proper output.
---
for issue https://github.com/Samsung/ONE/issues/12979
from draft #12981
> [circle-interpreter] Use the actual output tensor size

- compiler/luci-interpreter/src/Interpreter.cpp
This will change to use `luci-interpreter` methods, instead of `luci`, for better sw architecture.
---
for issue https://github.com/Samsung/ONE/issues/12979
from draft #12981
> [luci-interpreter] Change to use `luci-interface` interface

- onert-micro/externals/CMakeLists.txt
- Change the old trace $OUTPUT_FILES to $SOURCES
> Fixed error in specifying source list of library target

- runtime/onert/api/nnfw/src/nnfw_api_internal.cc
It is a missing code segment.
It makes a copy of original circle before exporting circle.
- Code from https://github.com/Samsung/ONE/pull/12246/files#diff-6062b879f8bbfea9156587d03d744ae19cc190babd74b1afbb0a5fb2d84ab4fb
- Test with the same command from https://github.com/Samsung/ONE/pull/12323#issuecomment-1862131091
> [onert/api] Make a clone circle in nnfw_train_export_circle

- infra/command/gen-coverage-report
This commit updates coverage exclusion rules to exclude code generated by flatc.
> [infra] Update coverage exclusion rule for flatc

- runtime/onert/backend/train/BackendContext.cc
- runtime/onert/backend/train/BackendContext.h
- runtime/onert/backend/train/KernelGenerator.cc
- runtime/onert/backend/train/KernelGenerator.h
This commit applies BackPropAccumulator layer to train backend.
- Add registering and planing disposable tensors for back-propagation
- Make layers use disposable tensors instread of original back-prop tensors
- Apply BackPropAccumulator layer to each BackPropTensor
> [onert] Apply BackPropAccumulator layer

- compiler/luci/pass/include/luci/CircleOptimizer.h
- compiler/luci/pass/include/luci/Pass/FoldReshapePass.h
- compiler/luci/pass/src/CircleOptimizer.cpp
- compiler/luci/pass/src/FoldReshapePass.cpp
- compiler/luci/pass/src/FoldReshapePass.test.cpp
This enables constant folding for Reshape Op.
---
Related to: https://github.com/Samsung/ONE/issues/13016
Draft PR: #13019
> [luci] Introduce FoldReshapePass

- compiler/luci/pass/src/FuseAddWithFullyConnectedPass.cpp
- compiler/luci/pass/src/FuseAddWithFullyConnectedPass.test.cpp
This sets correct qparam to bias in FuseAddWithFullyConnectedPass.
> [luci] Fix bias qparam in FuseAddWithFullyConnectedPass

- runtime/onert/core/include/ir/train/ITrainableOperation.h
- runtime/onert/core/include/ir/train/TrainableOperation.h
- runtime/onert/core/include/ir/train/operation/BinaryArithmetic.h
- runtime/onert/core/include/ir/train/operation/Conv2D.h
- runtime/onert/core/include/ir/train/operation/DepthwiseConv2D.h
- runtime/onert/core/include/ir/train/operation/ElementwiseActivation.h
- runtime/onert/core/include/ir/train/operation/FullyConnected.h
- runtime/onert/core/include/ir/train/operation/Loss.h
- runtime/onert/core/include/ir/train/operation/Pad.h
- runtime/onert/core/include/ir/train/operation/Permute.h
- runtime/onert/core/include/ir/train/operation/Pool2D.h
- runtime/onert/core/include/ir/train/operation/Reduce.h
- runtime/onert/core/include/ir/train/operation/Reshape.h
- runtime/onert/core/include/ir/train/operation/Softmax.h
- runtime/onert/core/include/ir/train/operation/UntrainableOperation.h
This commits extend TrainableOperation API with methods to disable/enable weights update of some particular trainable operations. In trainable operations is stored also status about contribution in backward propagation phase.
Draft: https://github.com/Samsung/ONE/pull/12951
Issue: https://github.com/Samsung/ONE/issues/12386
/cc @jyoungyun
> [onert] Introduce API to control trainability of operations

- runtime/onert/core/include/ir/train/TrainingInfo.h
- runtime/onert/core/src/loader/TrainInfoLoader.cc
This commit stores the indexes of trainable ops from the TrainInfo of the given circle file in the TrainingInfo IR.
Draft: #12984 
/cc @mbencer
> [onert] Store trainable ops indexes in TrainingInfo IR

- infra/command/gen-coverage-report
This commit updates excluding policy on coverage to remove test header.
> [infra] Remove test header from coverage

- runtime/contrib/detection/CMakeLists.txt
- runtime/contrib/detection/detection.cpp
- runtime/contrib/mlapse/tfl/CMakeLists.txt
- runtime/contrib/mlapse/tfl/mlapse/benchmark_runner.cc
- tests/libs/benchmark/include/benchmark/Accumulator.h
- tests/tools/tflite_run/src/tflite_run.cc
This commit moves the Accumulator class from runtime/libs/misc to tests/libs/benchmark.
---
Related issue: #13009
> [runtime/lib] Move Accumulator class

- runtime/onert/api/nnfw/include/nnfw.h
This commit introduces workspace setting API.
It can be used in runtime for internal temporary, cache file management, etc.
> [onert] Introduce workspace setting API

- tests/libs/benchmark/CMakeLists.txt
- tests/libs/benchmark/include/benchmark/RandomGenerator.h
- tests/libs/benchmark/src/RandomGenerator.cpp
- tests/libs/tflite/CMakeLists.txt
- tests/libs/tflite/include/tflite/RandomInputInitializer.h
- tests/libs/tflite/src/RandomInputInitializer.cpp
- tests/tools/onert_run/src/randomgen.cc
- tests/tools/onert_train/src/randomgen.cc
- tests/tools/tflite_comparator/src/tflite_comparator.cc
- tests/tools/tflite_run/src/tflite_run.cc
This commit moves RandomGenerator into tesets/libs/benchmark.
---
Related issue: https://github.com/Samsung/ONE/issues/13009
> [onert/test] Move RandomGenerator

- infra/nnfw/config/gbs.conf
This commit adds tizen 7.0 profile and 9.0 repo to gbs.conf.
> [infra/gbs] Add tizen 9.0 repo and 7.0 profile

- runtime/onert/backend/train/KernelGenerator.cc
- runtime/onert/backend/train/ops/BinaryArithmeticLayer.cc
- runtime/onert/backend/train/ops/BinaryArithmeticLayer.h
- runtime/onert/backend/train/ops/ConvolutionLayer.cc
- runtime/onert/backend/train/ops/ConvolutionLayer.h
- runtime/onert/backend/train/ops/DepthwiseConvolutionLayer.cc
- runtime/onert/backend/train/ops/DepthwiseConvolutionLayer.h
- runtime/onert/backend/train/ops/ElementwiseActivationLayer.cc
- runtime/onert/backend/train/ops/ElementwiseActivationLayer.h
- runtime/onert/backend/train/ops/FullyConnectedLayer.cc
- runtime/onert/backend/train/ops/FullyConnectedLayer.h
- runtime/onert/backend/train/ops/MeanLayer.cc
- runtime/onert/backend/train/ops/MeanLayer.h
- runtime/onert/backend/train/ops/PadLayer.cc
- runtime/onert/backend/train/ops/PadLayer.h
- runtime/onert/backend/train/ops/PoolLayer.cc
- runtime/onert/backend/train/ops/PoolLayer.h
- runtime/onert/backend/train/ops/ReshapeLayer.cc
- runtime/onert/backend/train/ops/ReshapeLayer.h
- runtime/onert/backend/train/ops/SoftMaxLayer.cc
- runtime/onert/backend/train/ops/SoftMaxLayer.h
- runtime/onert/core/include/ir/train/TrainableOperation.h
This PR separates forward and backward configuration of trainable ops in order to make possible disabling backward propagation of particular ops.
Draft: https://github.com/Samsung/ONE/pull/12951
Issue: https://github.com/Samsung/ONE/issues/12386
> [onert] Separate forward and backward configuration of trainable ops

- infra/nnfw/config/gbs.conf
This commit changes repo url to use latest instead of reference.
> [onert/gbs] Change repo url to use latest

- compiler/luci/logex/src/CircleNodeSummaryBuilders.cpp
This commit adds to_str() method accepting luci::Dilation. Before that change dilation was implicitly converted to bool resulting in the meaningless output in logs: "dilation(h,w): true".
Desired output is similar to to_str(luci::Stride): "stride(h,w): 1,1".
Signed-off-by: Piotr Kotynia <p.kotynia@partner.samsung.com>
> [luci/logex] Implement to_str method for Dilation

- tools/circle_plus_gen/README.md
- tools/circle_plus_gen/lib/circle_plus.py
- tools/circle_plus_gen/lib/train_param.py
- tools/circle_plus_gen/main.py
This PR adds a feature
- inject training parameters to a circle plus instance.
- export circle plus instance as a *.circle file
* related issue : https://github.com/Samsung/ONE/issues/12650
> [tools/circle_plus_gen] Add tparam inject feature

- Makefile.template
- packaging/nnfw.spec
- runtime/onert/odc/Embedder.cc
- runtime/onert/odc/Embedder.h
- runtime/onert/odc/MinMaxReader.cc
- runtime/onert/odc/MinMaxReader.h
- runtime/onert/odc/Quantizer.cc
This commit intrdocues minmax data embedder for circle model file into on-device quantizer. 
It uses raw file format to load minmax data, ant it will be saved by runtime.
---
Draft: #12903
Related issue: https://github.com/Samsung/ONE/issues/12904
> [onert/odc] Introduce minmax embedder

- tests/CMakeLists.txt
- tests/nnapi/CMakeLists.txt
- tests/tools/onert_train/CMakeLists.txt
- tools/CMakeLists.txt
- tools/kbenchmark/CMakeLists.txt
This commit updates cmake script to use c++17 for all tests and tools.
> [runtime] Use c++17 for tests and tools

- runtime/onert/core/CMakeLists.txt
- runtime/onert/core/include/util/MinMaxMap.h
- runtime/onert/core/src/compiler/ExecutorFactory.cc
- runtime/onert/core/src/exec/MinMaxData.cc
- runtime/onert/core/src/exec/MinMaxData.h
- runtime/onert/core/src/exec/MinMaxRecorder.cc
- runtime/onert/core/src/exec/MinMaxRecorder.h
This commit introduces runtime raw format minmax file recorder.
---
Draft: https://github.com/Samsung/ONE/pull/12903
Related issue: https://github.com/Samsung/ONE/issues/12904
It shares same minmax file format with #13046
> [onert] Introduce raw format minmax file

- compiler/luci-interpreter/src/kernels/BroadcastTo.cpp
- compiler/luci-interpreter/src/kernels/BroadcastTo.h
- compiler/luci-interpreter/src/kernels/BroadcastTo.test.cpp
This commit supports boolean type on BroadcastTo op. The op whose type is boolean is showed up in the LLM model.
> [luci-interpreter] Support boolean type on BroadcastTo op

- compiler/luci-interpreter/src/kernels/SelectV2.cpp
This commit supports S64 dtype on SelectV2.
> [luci-interperter] Support S64 dtype on SelectV2

- runtime/contrib/gpu_cl/CMakeLists.txt
- runtime/onert/api/nnapi/CMakeLists.txt
- runtime/onert/api/nnfw/CMakeLists.txt
- runtime/onert/api/python/CMakeLists.txt
- runtime/onert/backend/acl_cl/CMakeLists.txt
- runtime/onert/backend/acl_neon/CMakeLists.txt
- runtime/onert/backend/cpu/CMakeLists.txt
- runtime/onert/backend/ruy/CMakeLists.txt
- runtime/onert/backend/train/CMakeLists.txt
- runtime/onert/backend/trix/CMakeLists.txt
- runtime/onert/backend/xnnpack/CMakeLists.txt
- runtime/onert/core/CMakeLists.txt
- runtime/onert/loader/trix/CMakeLists.txt
- runtime/onert/odc/CMakeLists.txt
- runtime/service/npud/backend/trix/CMakeLists.txt
This commit removes cmake custom strip in cmake script. 
Strip is already supported by cmake command on release install, and used in makefile and spec file.
> [onert] Remove custom strip in cmake

- runtime/onert/api/nnapi/wrapper/ANeuralNetworksCompilation.cc
- runtime/onert/api/nnfw/src/nnfw_api_internal.cc
- runtime/onert/api/nnfw/src/nnfw_api_internal.h
- runtime/onert/core/include/compiler/Compiler.h
- runtime/onert/core/include/compiler/CompilerFactory.h
- runtime/onert/core/src/compiler/Compiler.cc
- runtime/onert/core/src/compiler/CompilerFactory.cc
- runtime/onert/core/src/compiler/MultiModelCompiler.cc
- runtime/onert/core/src/compiler/MultiModelCompiler.h
- runtime/onert/core/src/compiler/train/TrainingCompiler.cc
- runtime/onert/core/src/compiler/train/TrainingCompiler.h
- runtime/onert/core/src/exec/Execution.test.cc
This commit changes compile option vector to one compile option struct object for multimodel. 
Most compile option except backend mapping can be shared by all models, and multimodel's backend mapping to operator index is not supported yet.
> [onert] Use unified compile option for multimodel

- runtime/onert/core/src/compiler/Compiler.cc
- runtime/onert/core/src/compiler/train/TrainingCompiler.cc
This commit remove needless nullcheck for non-null. 
std::make_unique returns non-null.
> [onert] Remove null check for non-null

- runtime/onert/backend/train/BackendContext.cc
- runtime/onert/core/include/exec/train/TrainableFnSequence.h
- runtime/onert/core/include/ir/train/TrainableGraph.h
- runtime/onert/core/include/ir/train/TrainableOperation.h
- runtime/onert/core/src/compiler/train/LoweredTrainableGraph.cc
- runtime/onert/core/src/compiler/train/TrainingCompiler.cc
- runtime/onert/core/src/compiler/train/pass/LossInsertionPass.cc
- runtime/onert/core/src/exec/train/TrainableExecutor.cc
- runtime/onert/core/src/exec/train/TrainableFnSequence.cc
- runtime/onert/core/src/ir/train/TrainableGraph.cc
This commit adds logic to control training tensors allocation and enablement of operations backward propagation based on the trainability state of ops.
Draft: https://github.com/Samsung/ONE/pull/12951
Issue: https://github.com/Samsung/ONE/issues/12386
> [onert] Introduce logic to control training flow

- runtime/onert/api/nnfw/include/nnfw.h
- runtime/onert/api/nnfw/src/nnfw_api_internal.cc
- runtime/onert/api/nnfw/src/nnfw_api_internal.h
- runtime/onert/core/include/compiler/CompilerOptions.h
- runtime/onert/core/include/util/Config.lst
- runtime/onert/core/src/compiler/CompilerOptions.cc
This commit adds workspace directory compiler option and global config. It replaces session's workspace_dir field.
---
It requires #13053 merge
> [onert] Add workspace directory compiler option

- tests/nnfw_api/lib/GenModelTrain.h
This commit introduces the expects buffer to store the expected data instead of using the output buffer.
Draft: #13062
> [nnfw_api] Introduce expects buffer to the TrainCaseData

- runtime/contrib/android/api/Prebuilt.mk
This commit fixes android packaging fail by invalid path in Prebuilt.mk
---
Related issue: #13074
> [onert] Fix android packaging fail

- tests/nnfw_api/lib/GenModelTrain.h
This commit removes the unnecessary losses buffer from SessionObjectTraining.
The losses data is not automatically filled at runtime, so it is not
appropriate to be in the SessionObject.
Draft: #13062 
Requires: #13088
> [nnfw_api] Remove losses buffer from SessionObjectTraining

- runtime/onert/core/src/backend/builtin/train/KernelGenerator.cc
- runtime/onert/core/src/backend/builtin/train/kernel/PermuteLayer.cc
- runtime/onert/core/src/exec/train/TrainableExecutor.cc
This commit runs PermuteLayer when the output buffer is specified. This changes copies the output data from the model to the output buffer provided by the user.
Draft: #13062
> [onert] Run PermuteLayer in training mode

- docs/howto/how-to-cross-build-runtime-for-android.md
- infra/docker/focal/Dockerfile
This commit removes android sdk and packages for android build in ubuntu 20.04 docker image.
> [infra] Remove android sdk in ubuntu 20.04 docker image

- runtime/onert/backend/train/CMakeLists.txt
- runtime/onert/backend/train/MemoryPlanner.test.cc
This commit adds unit tests for memory planners in train backend.
> [onert] Add unit tests for memory planners

- tests/tools/onert_run/src/args.cc
- tests/tools/onert_run/src/args.h
- tests/tools/onert_run/src/onert_run.cc
- tests/tools/onert_run/src/randomgen.cc
- tests/tools/onert_run/src/randomgen.h
This commit updates random generator to support different random input on each rerun.
---
Related issue: #13008
> [onert_run] Support different random input on each rerun

- runtime/onert/odc/MinMaxReader.cc
- runtime/onert/odc/MinMaxReader.h
This commit fixes the header include of MinMaxRecorder.h/cc.
---
It will resolve build fail on gcc >= 13.
> [onert] Fix MinMaxRecorder header include

- infra/nnfw/cmake/packages/XnnpackConfig.cmake
This commit xnnpack disables assembly on tizen armv7l.
> [infra] Fix xnnpack tizen build

- runtime/onert/core/src/exporter/CircleExporter.cc
This commit changes the classic C casts to the `reinterpret_cast`.
Related comment: https://github.com/Samsung/ONE/pull/13114#discussion_r1632561605
> [onert] Use reinterpret_cast instead of the classic C casts

- runtime/onert/backend/train/optimizer/Optimizers.test.cc
This commit adds unit tests for optimizers of training.
- Add positive tests for value validation of optimizers
- Add positive tests for virtual function `getVarCount()` of `IOptimizer`
- Add negative tests for UnsupportedType, UnmatchedShape, and UndefinedOptimizerCode
> [onert] Add unit tests for optimizers

- onert-micro/onert-micro/include/OMConfig.h
- onert-micro/onert-micro/include/OMStatus.h
- onert-micro/onert-micro/include/OMTrainingInterpreter.h
- onert-micro/onert-micro/include/core/OMTrainingRuntimeModule.h
- onert-micro/onert-micro/src/OMTrainingInterpreter.cpp
- onert-micro/onert-micro/src/core/OMTrainingRuntimeModule.cpp
This pr introduces OMTrainingInterpreter, OMTrainingContext and OMTrainingRuntimeModule entities.
for issue #12873
from draft: #13107
> [onert-micro] Introduce OMTraining entities

- runtime/onert/backend/train/ops/DepthwiseConvolutionLayer.cc
This commit adds dilation check logic in dconv layer for train. The dconv layer for train does not support dilation yet.
> [onert] Add dilation check logic in DepthwiseConvolution layer for train

- runtime/onert/api/nnapi/wrapper/ANeuralNetworksCompilation.cc
- runtime/onert/api/nnfw/src/nnfw_api_internal.h
- runtime/onert/core/include/compiler/CompilerOptions.h
This commit updates CompilerOptions to remove meaningless method and public keyword, and change to struct.
> [onert] Revisits CompilerOptions

- compiler/one-cmds/dummy-driver/src/dummy-compile.cpp
- compiler/one-cmds/dummy-driver/src/dummy-profile.cpp
This commit expands the interfae of the dummy tools for test.
This will be for the target configuration test.
Draft: https://github.com/Samsung/ONE/pull/13161
> [one-cmds] Expand interface of the dummy tools for test

- tests/nnfw_api/src/GenModelTests/one_op_trains/FullyConnected.test.cc
This commit adds one op tests to validate training of FC.
- Add positive tests for value validation of FC
- Add negative tests for invalid shape and missing bias
> [onert] Add unit tests for training FC

- compiler/one-cmds/onelib/utils.py
This commit implements a funciton that gets argument parser from the given target.
Draft: https://github.com/Samsung/ONE/pull/13161
> [one-cmds] Implement get_arg_parser

- runtime/onert/api/nnfw/src/nnfw_api_internal.cc
- runtime/onert/core/src/compiler/CompilerOptions.cc
- tests/nnfw_api/src/NNPackageTests/AddModelLoaded.test.cc
This commit adds validation check and unittest for set_backends_per_operation API.
> [onert] Add validation test for set_backends_per_operation

- tools/circle_plus_gen/lib/circle_plus.py
- tools/circle_plus_gen/test/test_circle_plus.py
This PR add methods to CirclePlus class to acess circle's operator.
draft : https://github.com/Samsung/ONE/pull/13154 
related : https://github.com/Samsung/ONE/issues/13099
> [tools/circle_plus_gen] Add operator access methods to CirclePlus 

- runtime/onert/api/nnfw/src/nnfw_api_internal.cc
- runtime/onert/core/include/exporter/CircleExporter.h
- runtime/onert/core/src/exporter/CircleExporter.cc
This commit moves updateWeight function to the CircleExporter from nnfw_api_internal.cc file. It exports new circle file with updated weight data.
Draft: #13014
> [onert] Move updateWeight function to the CircleExporter

- runtime/onert/core/src/exec/MinMaxRecorder.cc
- runtime/onert/core/src/exec/MinMaxRecorder.h
This commit updates MinMaxRecorder to create dump file in handleSubgraphEnd method, not in constructor.
---
Related issue: #12904 #13039
Draft: #13013
> [onert] Create minmax dump file in handleSubgraphEnd

- runtime/onert/api/nnfw/include/nnfw_experimental.h
- runtime/onert/api/nnfw/src/nnfw_api.cc
- runtime/onert/api/nnfw/src/nnfw_api_internal.cc
- runtime/onert/api/nnfw/src/nnfw_api_internal.h
- tests/nnfw_api/src/NNPackageTests/SingleSession.test.cc
This commit updates deprecated API implementation to use common function. 
It includes unittest for deprecated API.
> [onert] Update deprecated API implementation

- runtime/onert/core/src/exec/ExecutionObservers.cc
- runtime/onert/core/src/exec/ExecutionObservers.h
This commit updates TracingObserver to write file when observer is used at least once.
--- 
Draft: #13013
> [onert] Change TracingObserver writing policy

- tests/tools/onert_train/README.md
- tests/tools/onert_train/src/args.cc
- tests/tools/onert_train/src/args.h
- tests/tools/onert_train/src/onert_train.cc
This commits adds new flags of onert_train - trainable_ops_idx. It allows to pass trainable ops indexes nnfw training.
Issue: https://github.com/Samsung/ONE/issues/12386
> [tools/onert_train] Add trainable ops support

- infra/debian/compiler/one-compiler.install
This commit installs argumentparse.py.
Related: https://github.com/Samsung/ONE/issues/13138#issuecomment-2163331272
> [debian] Install argumentparse.py

- infra/nnfw/cmake/CfgOptionFlags.cmake
- infra/nnfw/cmake/options/options_aarch64-android.cmake
- infra/nnfw/cmake/options/options_aarch64-tizen.cmake
- infra/nnfw/cmake/options/options_armv7hl-tizen.cmake
- infra/nnfw/cmake/options/options_armv7l-tizen.cmake
- infra/nnfw/cmake/options/options_i686-tizen.cmake
- infra/nnfw/cmake/options/options_riscv64-tizen.cmake
- infra/nnfw/cmake/options/options_x86_64-tizen.cmake
This commit updates default setting to use raw file format minmax dumper instead of hdf5 minmax dumper.
> [infra/onert] Disable hdf5 minmax dumper

- tests/tools/onert_train/src/nnfw_util.cc
This PR make onert_train prints trainable_ops as log.
> [tools/onert_train] Print trainable ops

- compiler/one-cmds/onelib/CfgRunner.py
This commit fixes a bug where given target is not set properly. I'll add a test for this in the next PR.
> [one-cmds] Fix bug on target feature

- onert-micro/onert-micro/include/train/losses_functions/CrossEntropy.h
- onert-micro/onert-micro/include/train/losses_functions/MSE.h
- onert-micro/onert-micro/src/train/losses_functions/CrossEntropy.cpp
- onert-micro/onert-micro/src/train/losses_functions/MSE.cpp
This pr adds losses - MSE and CrossEntropy functions.
> [onert-micro] Add losses functions

- onert-micro/onert-micro/include/train/OMBackpropExecute.h
- onert-micro/onert-micro/include/train/OMBackpropExecuteArgs.h
- onert-micro/onert-micro/include/train/OMBackpropExecutionBuilder.h
- onert-micro/onert-micro/src/train/OMBackpropExecute.cpp
- onert-micro/onert-micro/src/train/OMBackpropExecutionBuilder.cpp
This pr introduces OMBackpropExecute, OMBackpropExecuteArgs and OMBackpropExecutionBuilder entities.
> [onert-micro] Introduce OMBackpropExecute entities

- runtime/onert/core/include/ir/train/TrainableOperation.h
- runtime/onert/core/src/exec/train/TrainableExecutor.cc
- tests/nnfw_api/lib/CircleGen.cc
- tests/nnfw_api/lib/CircleGen.h
- tests/nnfw_api/lib/CirclePlusGen.cc
- tests/nnfw_api/lib/CirclePlusGen.h
- tests/nnfw_api/src/GenModelTests/one_op_trains/Conv2D.test.cc
- tests/nnfw_api/src/GenModelTests/one_op_trains/FullyConnected.test.cc
This commits disables trainability of operations by default. Missing isRequiredForBackward check added to TrainableExecutor::backwardImpl.
> [onert] Disable operations trainability by default

- runtime/onert/core/include/backend/basic/BackendContextHelpers.h
- runtime/onert/core/include/backend/basic/train/TrainableBackendContextHelpers.h
This PR removes unused variables in planTensors() and genTensors().
> [onert] Remove unused variable in planTensors, genTensors

- runtime/onert/core/src/odc/CodegenLoader.cc
This commit changes dlopen() to dlmopen() for codegen library. 
It's hard to control dependent library version with runtime's core. 
It can help to find internally linked static library version first in dynamic library. 
This feature is not supported on android.
> [onert] Use dlmopen for codegen lib

- docs/howto/how-to-use-nnfw-api.md
- docs/howto/how-to-use-specific-backend.md
- runtime/onert/api/nnfw/include/nnfw.h
- runtime/onert/api/nnfw/src/nnfw_api.cc
- runtime/onert/api/nnfw/src/nnfw_api_internal.cc
- runtime/onert/api/nnfw/src/nnfw_api_internal.h
- runtime/onert/api/python/src/nnfw_api_wrapper.cc
- tests/nnfw_api/src/NNPackageTests/SingleSession.test.cc
This commit removes deprecated nnfw_set_op_backend API implementation. 
This feature can be used by environment variable only.
> [onert] Remove nnfw_set_op_backend implementation

- onert-micro/onert-micro/include/core/train/OMTrainingHandler.h
- onert-micro/onert-micro/include/core/train/OMTrainingStorage.h
- onert-micro/onert-micro/src/core/train/OMTrainingHandler.cpp
- onert-micro/onert-micro/src/core/train/OMTrainingStorage.cpp
This pr introduces OMTrainingStorage and OMTrainingHandler entities.
> [onert-micro] Introduce OMTrainingStorage and OMTrainingHandler

- runtime/onert/api/nnfw/src/nnfw_api.cc
- runtime/onert/api/nnfw/src/nnfw_api_internal.cc
- runtime/onert/api/nnfw/src/nnfw_api_internal.h
- runtime/onert/core/include/exec/ExecutionContext.h
- runtime/onert/core/src/exec/ExecutionContext.cc
- tests/nnfw_api/src/NNPackageTests/AddModelLoaded.test.cc
- tests/nnfw_api/src/NNPackageTests/AddSessionPrepared.test.cc
This commit implements config APIs in nnfw_session. 
Session stores compile config in CompilerOptions and execution configurations in ExecutionOptions. 
ExecutionOptions is initialized from environment variable, otherwise default setting.
---
Draft: #12903
> [onert] Implement config APIs

- onert-micro/onert-micro/include/train/metrics/Accuracy.h
- onert-micro/onert-micro/include/train/metrics/CrossEntropy.h
- onert-micro/onert-micro/include/train/metrics/MAE.h
- onert-micro/onert-micro/include/train/metrics/MSE.h
- onert-micro/onert-micro/src/train/metrics/Accuracy.cpp
- onert-micro/onert-micro/src/train/metrics/CrossEntropy.cpp
- onert-micro/onert-micro/src/train/metrics/MAE.cpp
- onert-micro/onert-micro/src/train/metrics/MSE.cpp
This pr introduces metrics entities: accuracy, corssentropy, mea, mse.
> [onert-micro] Introduce Metrics

- onert-micro/onert-micro/include/core/reader/OMWeightOnlyFormatReader.h
- onert-micro/onert-micro/src/core/reader/OMWeightOnlyFormatReader.cpp
This pr adds supporting of WeightOnlyFormatReader.
> [onert-micro] Support WeightOnlyFormatReader

- onert-micro/onert-micro/include/core/OMRuntimeGraph.h
- onert-micro/onert-micro/src/core/OMRuntimeGraph.cpp
This pr extends OMRuntimeGraph api with tow new methods - getInputDataTypeSize and getOutputDataTypeSize.
> [onert-micro] Extend OMRuntimeGraph api

- onert-micro/onert-micro/include/import/OMExecutionPlanCreator.h
- onert-micro/onert-micro/src/import/OMExecutionPlanCreator.cpp
This pr adds method to create execution plan for backward graph.
> [onert-micro] Add createBackwardExecutionPlan

- onert-micro/onert-micro/src/optimize/pass/FindInplaceOpPass.cpp
This pr adds skipping FindInplaceOpPass during training.
> [onert-micro] Skip findInplaceOpPass during training

- compiler/one-cmds/tests/one-profile_005.test
This commit fixes one-profile_005 test.
Related: https://github.com/Samsung/ONE/issues/13138#issuecomment-2172464177
> [one-cmds] Fix one-profile_005 test

- onert-micro/onert-micro/include/pal/common/PALFullyConnectedInputGrad.h
- onert-micro/onert-micro/include/pal/common/PALFullyConnectedWeightGrad.h
- onert-micro/onert-micro/include/pal/common/PALReluInputGrad.h
- onert-micro/onert-micro/src/train/kernels/FullyConnected.cpp
This pr adds training for FullyConnected kernel: compute gradients for weights (+ bias) and for input tensor and for relu.
> [onert-micro] Add FullyConnected training

- onert-micro/onert-micro/include/train/train_optimizers/Adam.h
- onert-micro/onert-micro/include/train/train_optimizers/SGD.h
- onert-micro/onert-micro/src/train/train_optimizers/Adam.cpp
- onert-micro/onert-micro/src/train/train_optimizers/SGD.cpp
This pr introduces optimizers entities: SGD and Adam.
> [onert-micro] Introduce Optimizers

- runtime/onert/api/nnapi/wrapper/ANeuralNetworksCompilation.cc
- runtime/onert/api/nnapi/wrapper/ANeuralNetworksCompilation.h
This commit removes noexcept specifier from ANeuralNetworksCompilation constructor to not call terminate() when an exception occurs.
> [onert] Remove noexcept specifier from ANeuralNetworksCompilation constructor

- tests/nnfw_api/src/GenModelTests/nontrainable_op_trains/Relu6.test.cc
This commit adds some tests to validate training of ReLU6 op.
> [onert] Add unit tests for training ReLU6 op

- tests/nnfw_api/src/GenModelTests/nontrainable_op_trains/Relu.test.cc
This commit adds some tests to validate training for ReLU op.
> [onert] Add unit tests for training ReLU op

- tests/nnfw_api/src/GenModelTests/BranchModelTrain.test.cc
- tests/nnfw_api/src/GenModelTests/nontrainable_op_trains/Add.test.cc
- tests/nnfw_api/src/GenModelTests/nontrainable_op_trains/Mul.test.cc
- tests/nnfw_api/src/GenModelTests/nontrainable_op_trains/Sub.test.cc
This commit adds some tests for arithmetic ops to validate training.
- Introduce BranchModelTrain.test.cc that validates branched cases
- Add tests that validates arithmetic ops(Add, Mul, Sub)
> [onert] Add unit tests for training arithmetic ops

- runtime/onert/odc/MinMaxReader.cc
- runtime/onert/odc/Quantizer.cc
This commit fixes quantization bugs.
- Read minmax file header in readInput() mehtod
- Use individual quantizer for fake quantization because minmax-embedder modify model between fake quantizer and quantize-with-minmax.
> [onert/odc] Fix quantization bug

- runtime/onert/core/include/exporter/CircleExporter.h
- runtime/onert/core/src/exporter/CircleExporter.cc
- runtime/onert/core/src/exporter/TrainInfoBuilder.h
This commit introduces `updateMetadata` function and TrainInfoBuilder.h file. It copies the metadata of the given TrainingInfo data to the circle model.
Draft: #13014
> [onert] Add updateMetadata function to CircleExporter

- runtime/onert/core/src/compiler/pass/ConstantInsertionPass.cc
This commit modifies the code to check if the Replace Key is present in `_replace_operands_map` and allows ConstantInsertionPass to be applied even to the last remaining operand.
> [onert] Apply ConstantInsertionPass to the last remaining operand

- tests/nnfw_api/src/GenModelTests/nontrainable_op_trains/Reshape.test.cc
This commit adds some tests to validate training of Reshape op.
> [onert] Add unit tests for training Reshape op

- compiler/one-cmds/one-import-onnx
This will add 'disable_ext' option for one-import-onnx to use legacy onnx-tf package
even if one-import-onnx-ext package is installed.
> [one-cmds] Add 'disable_ext' option for import-onnx

- tests/nnfw_api/src/GenModelTests/nontrainable_op_trains/Softmax.test.cc
This commit adds some tests to validate training of Softmax op.
> [onert] Add unit tests for training Softmax op

- runtime/onert/core/src/exporter/CircleExporter.cc
This commit creates a new buffer for internally generated tensors and stores weights.
Draft: #13226 
Resolves #13221
> [onert] store the weights of the internally generated tensors

- onert-micro/onert-micro/src/train/kernels/Reshape.cpp
This pr adds Reshape training kernel.
> [onert-micro] Add Reshape training kernel

- onert-micro/onert-micro/include/pal/common/PALMaxPool2DInputGrad.h
- onert-micro/onert-micro/src/train/kernels/MaxPool2D.cpp
This pr adds MaxPool2D training kernel.
> [onert-micro] Add MaxPool2D training kernel

- onert-micro/onert-micro/include/pal/common/PALSoftmaxInputGrad.h
- onert-micro/onert-micro/src/train/kernels/Softmax.cpp
This pr adds Softmax training kernel.
> [onert-micro] Add Softmax training kernel

- compiler/one-cmds/one-import-onnx
This will fix one-import-onnx as env. var can be None.
> [one-cmds] Fix one-import-onnx

- tests/nnfw_api/src/GenModelTests/nontrainable_op_trains/Pad.test.cc
This commit adds some tests to validate training of Pad op.
> [onert] Add unit tests for training Pad op

- runtime/onert/core/src/exec/train/TrainableExecutor.cc
This commits adds additional check if operation is trainable for forward step.
> [onert] Revist trainability in TrainableExecutor

- onert-micro/onert-micro/include/pal/common/PALConv2DInputGrad.h
- onert-micro/onert-micro/include/pal/common/PALConv2DWeightGrad.h
- onert-micro/onert-micro/src/train/kernels/Conv2D.cpp
This pr adds Conv2D training kernel.
> [onert-micro] Add Conv2D training kernel

- runtime/onert/api/nnfw/include/nnfw_internal.h
- runtime/onert/api/nnfw/src/nnfw_api.cc
- runtime/onert/api/nnfw/src/nnfw_api_internal.cc
- runtime/onert/api/nnfw/src/nnfw_api_internal.h
This commit introduces `nnfw_train_export_circleplus` api to export circle+ file. This api is an internal API.
Draft: #13014
> [onert] Introduce `export_circleplus` internal API

- runtime/onert/backend/train/ops/PoolLayer.cc
- tests/nnfw_api/lib/CircleGen.cc
- tests/nnfw_api/lib/CircleGen.h
- tests/nnfw_api/src/GenModelTests/nontrainable_op_trains/MaxPool2D.test.cc
This fixes value error when training a model with MaxPool2D.
It fixs a error in arguments passing order when configuring MaxPool layer.
This PR also adds related test cases to gurantee that this fix is correct.
Co-authored-by: ragmani <ragmani0216@gmail.com>
> [onert] Fix value error when training MaxPool2D

- infra/command/gen-coverage-report
- Remove */test_models/* from coverage report for onert-micro coverage
> Remove test_models for onert-micro coverage

- onert-micro/onert-micro/include/OMTrainingInterpreter.h
- onert-micro/onert-micro/include/core/OMTrainingRuntimeModule.h
- onert-micro/onert-micro/src/OMTrainingInterpreter.cpp
- onert-micro/onert-micro/src/core/OMTrainingRuntimeModule.cpp
- 5 functions added  : run(), allocateInputs(), getInputData, getInputDataAt, getOutputDataAt
> aux funcs in OMTrainingInterpreter

- tests/tools/onert_train/src/args.cc
- tests/tools/onert_train/src/args.h
- tests/tools/onert_train/src/onert_train.cc
This commit introduces `export_circleplus` option and rename `export_path` to `export_circle` option.
Draft: #13014
> [tools/onert_train] Introduce export_circleplus option

- tools/circle_plus_gen/lib/circle_plus.py
Before
*  `m.name` is sometimes `bytes`(when reading it from file) and sometimes `string`(set it from json file).
* This problem sometimes makes an error message
* `AttributeError: 'str' object has no attribute 'decode'`
After
* `m.name` always bytes type
> [tools/circle_plus_gen] Fix type bug

- infra/docker/android-sdk/Dockerfile
- infra/docker/focal/Dockerfile
- infra/docker/jammy/Dockerfile
This commit updates dockerfiles to remove unnecessary packages and setting
- `android-sdk`
- Remove unused buildtools
- Fix cmdline-tools version directory
- Install file package
- `focal` and `jammy`
- Remove unused buildtools
- Remove sdb
- Remove unused UBUNTU_MIRROR argument
- Remove unused libgtest-dev package
> [infra] Cleanup dockerfiles

- tests/nnfw_api/lib/GenModelTrain.h
This commit changes dataset name from `outputs` to `expects`.
And it removes unused `expects` variable from TrainCaseData.
Draft: #13267
> [onert/nnfw_api] Update DataSet name of TrainCaseData

- onert-micro/CMakeLists.txt
- This enable generating traininfo header file during onert-micro build
> Enable gen traininfo schema header in onert-micro

- compiler/luci-interpreter/src/kernels/StridedSlice.cpp
This commit supports bool type in the StridedSlice.
> [luci-interperter] Support bool type in the StridedSlice

- tests/nnfw_api/lib/GenModelTrain.h
- tests/nnfw_api/src/GenModelTests/BranchModelTrain.test.cc
- tests/nnfw_api/src/GenModelTests/nontrainable_op_trains/MaxPool2D.test.cc
- tests/nnfw_api/src/GenModelTests/nontrainable_op_trains/Mean.test.cc
- tests/nnfw_api/src/GenModelTests/nontrainable_op_trains/Pad.test.cc
- tests/nnfw_api/src/GenModelTests/nontrainable_op_trains/Relu.test.cc
- tests/nnfw_api/src/GenModelTests/nontrainable_op_trains/Relu6.test.cc
- tests/nnfw_api/src/GenModelTests/nontrainable_op_trains/Reshape.test.cc
- tests/nnfw_api/src/GenModelTests/nontrainable_op_trains/Softmax.test.cc
- tests/nnfw_api/src/GenModelTests/one_op_trains/Conv2D.test.cc
- tests/nnfw_api/src/GenModelTests/one_op_trains/DepthwiseConvolution.test.cc
- tests/nnfw_api/src/GenModelTests/one_op_trains/FullyConnected.test.cc
This commit verifies the loss per epoch by updating the GenModelTrain code.
Draft: #13267
> [onert/nnfw_api] Specify loss per epoch in GenModelTrain tests

- runtime/onert/api/nnfw/include/nnfw.h
- runtime/onert/api/nnfw/src/nnfw_api_internal.cc
- tests/nnfw_api/src/NNPackageTests/AddModelLoaded.test.cc
- tests/nnfw_api/src/NNPackageTests/SessionCreated.test.cc
This commit changes some API status condition
- `nnfw_set_workspace`: should be called before model loading to support cached optimized model auto loading later
- `nnfw_set_quantization_type`, `nnfw_set_quantized_model_path`, `nnfw_quantize`, `nnfw_set_codegen_model_path`, `nnfw_codegen`: allow to be called after prepare to support full quantization with minmax data collection
> [onert] Change API status condition

- compiler/luci/export/src/CircleExporterImpl.cpp
- compiler/luci/export/src/CircleTensorExporter.cpp
- compiler/luci/pass/src/CircleQuantizer.cpp
This commit uses auto & to resolve static analysis warning.
> [luci] Use auto & instead of auto

- compiler/luci/pass/src/QuantizeWithPredecessorPass.cpp
This commit adds nullptr check to resolve static analysis error.
> [luci] Add nullptr check

- runtime/onert/core/src/exporter/CircleExporter.cc
This commit adds static_cast to std::streamsize in CircleExporter.
---
For clearing code analysis defect warning
> [onert] Add static_cast in CircleExporter

- .ahub/tcchecker-tca/config.yaml
This commit fixes compiler TC checker config.
> [infra] Fix compiler TC checker config

- onert-micro/onert-micro/include/import/helpers/OMPooingCommon.h
- onert-micro/onert-micro/src/import/CMakeLists.txt
- onert-micro/onert-micro/src/import/helpers/OMPoolingCommon.cpp
- onert-micro/onert-micro/src/import/kernels/AveragePool2D.cpp
- onert-micro/onert-micro/src/import/kernels/MaxPool2D.cpp
This pr reduces code duplication for pooling import part.
for  #13272
> [onert-micro] Reduce pooling code duplication

- compute/cker/src/train/Conv.test.cc
- tests/nnfw_api/src/GenModelTests/nontrainable_op_trains/Add.test.cc
- tests/nnfw_api/src/GenModelTests/nontrainable_op_trains/MaxPool2D.test.cc
- tests/nnfw_api/src/GenModelTests/nontrainable_op_trains/Mean.test.cc
- tests/nnfw_api/src/GenModelTests/nontrainable_op_trains/Mul.test.cc
- tests/nnfw_api/src/GenModelTests/nontrainable_op_trains/Pad.test.cc
- tests/nnfw_api/src/GenModelTests/nontrainable_op_trains/Relu.test.cc
- tests/nnfw_api/src/GenModelTests/nontrainable_op_trains/Relu6.test.cc
- tests/nnfw_api/src/GenModelTests/nontrainable_op_trains/Reshape.test.cc
- tests/nnfw_api/src/GenModelTests/nontrainable_op_trains/Softmax.test.cc
- tests/nnfw_api/src/GenModelTests/nontrainable_op_trains/Sub.test.cc
This commit adds SUCCEED() macro to unittest for TC checker workaround.
> [onert/test] Add SUCCEED to unittest

- infra/debian/compiler/changelog
This commit updates changelog for release 1.27.0.
Related: https://github.com/Samsung/ONE/issues/13283
> [debian] Update changelog for version 1.27.0

- runtime/onert/api/nnfw/src/nnfw_api_internal.cc
- runtime/onert/core/include/odc/CodegenManager.h
- runtime/onert/core/include/odc/QuantizeManager.h
- runtime/onert/core/src/odc/CodegenManager.cc
- runtime/onert/core/src/odc/QuantizeManager.cc
- runtime/onert/core/src/odc/QuantizeManager.test.cc
This commit changes CodegenManager and QuantizeManager input file setting. 
Because input file can be changed by API, CodegenManager and QuantizeManager get input file from running method parameter, not constructor.
> [onert] Change ODC input file setting

- compiler/vconone/CMakeLists.txt
This commit bumps up to 1.28.0.
Related: #13283 
> [vconone] Bump up to 1.28.0

- onert-micro/onert-micro/src/train/tests/BostonHousingTask.test.cpp
- onert-micro/onert-micro/src/train/tests/CheckpointsHandler.test.cpp
- Wrong_Loss_t to Wrong_Loss_NEG
- Wrong_magic_num_N -> Wrong_magic_num_NEG
> [onert-micro] Fix wrong negative suffix

- runtime/onert/api/nnfw/src/nnfw_api_internal.cc
- runtime/onert/api/nnfw/src/nnfw_api_internal.h
This commit updates API implementation to reset compile result (`_execution`, `_compiler_artifact`) after model reload. 
For common model load, it introduce new private method.
> [onert] Reset compile result after reload

- docs/conf.py
- packaging/nnfw.spec
- runtime/contrib/android/api/build.gradle
- runtime/onert/api/nnfw/include/nnfw_version.h
This commit bumps up to 1.28.0.
---
Related: https://github.com/Samsung/ONE/issues/13283
> [onert] Bump up to 1.28.0

- compiler/luci-interpreter/src/kernels/StridedSlice.cpp
This commit supports int64 type in StridedSlice op.
> [luci-interpreter] Support int64 type in StridedSlice op

- runtime/onert/core/include/ir/train/Index.h
This commit introduce index types for training.
- `TrainingOperationIndex` provides index of operation node for training
- `TrainingOperandIndex` provides index of operand for training
> [onert] Introduce index types for training

- infra/nnfw/python/setup.py
This commit fixes path package use in setup.py script.
Issue: https://github.com/Samsung/ONE/issues/13332
> [onert] Fix path in Python API setup.py script

- compiler/luci-interpreter/src/kernels/Transpose.cpp
This commit supports int64 dtype in the CircleTranspose.
> [luci-interpreter] Support int64 dtype in the CircleTranspose

- onert-micro/onert-micro/include/core/reader/OMWeightOnlyFormatReader.h
- onert-micro/onert-micro/include/execute/OMKernelExecutionBuilder.h
- onert-micro/onert-micro/include/import/OMKernelConfigureBuilder.h
- onert-micro/onert-micro/include/pal/common/PALL2Pool2DCommon.h
- onert-micro/onert-micro/include/pal/common/PALSplit.h
- onert-micro/onert-micro/include/pal/common/PALUtils.h
- onert-micro/onert-micro/include/pal/mcu/PALAddN.h
- onert-micro/onert-micro/src/core/OMRuntimeModule.cpp
- onert-micro/onert-micro/src/core/memory/OMMemoryManager.cpp
- onert-micro/onert-micro/src/core/memory/OMRuntimeAllocator.cpp
- onert-micro/onert-micro/src/core/train/OMTrainingHandler.cpp
- onert-micro/onert-micro/src/execute/OMRuntimeKernel.cpp
- onert-micro/onert-micro/src/execute/kernels/Split.cpp
- onert-micro/onert-micro/src/optimize/pass/FindInplaceOpPass.cpp
This draft contains fixed for svace defects.
(0 critical and 2 major remains in internal svace manager)
> Fix several svace defects

- compiler/one-cmds/onecc
- compiler/one-cmds/onelib/utils.py
This commit make onecc print available targets.
> [one-cmds] Print available target

- compiler/one-cmds/onecc
- compiler/one-cmds/tests/onecc_neg_037.test
This commit raises an error when backend and target option are given simultaneously.
> [one-cmds] Raise error when backend and target option are given

- infra/nnfw/cmake/CfgOptionFlags.cmake
- infra/nnfw/cmake/packages/BoostConfig.cmake
- infra/nnfw/cmake/packages/HDF5Config.cmake
This commit updates cmake build option to use static link for Boost and HDF5. 
It will help to use test driver on upper linux version without rebuild.
It includes removing unused boost component linking.
> [infra/onert] Use static link for Boost and HDF5

- compiler/luci-interpreter/src/kernels/NotEqual.test.cpp
- compiler/luci-interpreter/src/kernels/ReduceMax.test.cpp
- compiler/luci-interpreter/src/kernels/Transpose.test.cpp
This commit adds for recent data type support of operators.
> [luci-interpreter] Add test for NotEqual, ReduceMax, Transpose

- onert-micro/CMakeLists.txt
- onert-micro/onert-micro/src/api/onert-micro.cpp
- for cortex arm target, onert_micro_dev is deafult binary
- Fix exception for TizenRT
> [onert-micro] onert_micro_dev as default arm Target

- tests/tools/onert_run/src/args.cc
- tests/tools/onert_run/src/args.h
- tests/tools/onert_run/src/onert_run.cc
This commit allows to set input and output buffer data type to float when model is quantized.
---
Draft: #13284
> [oenrt_run] Force input/output type to float

- runtime/onert/backend/train/ops/MeanLayer.cc
This commit fixes wrong applied shape in backward of MeanLayer.
---
Applying "WIC" planner, `GenModelTrain.NonTrainableOps_FC_Mean` test failed because values of the buffer outside the range of shape of backprop tensor was not 0. This patch solves the problem.
> [onert] Fix wrong applied shape in backward of MeanLayer

- runtime/contrib/style_transfer_app/src/jpeg_helper.cc
This patch adds a size limit to the input images.
---
For #13348
> [contrib/style_transfer_app] Add size limit to input images

- runtime/onert/backend/train/ops/OperationUtils.cc
- runtime/onert/backend/train/ops/OperationUtils.h
This commit add assertion to check whether a tensor dynamic in `getShape`.
- Introduce getShape into train backend that generates nnfw::cker::Shape from a tensor
- Add the assertion in that function
---
Related to https://github.com/Samsung/ONE/pull/13351#discussion_r1666185378
> [onert] Add assertion to check whether tensor is dynamic

- infra/nnfw/CMakeLists.txt
- tests/tools/tflite_run/CMakeLists.txt
- tests/tools/tflite_run/src/args.cc
- tests/tools/tflite_run/src/args.h
This commit updates tflite_run to use arser for argument parsing instead of boost::program_options.
> [onert/test] Use arser for tflite_run argument parsing

- infra/nnfw/cmake/options/options_aarch64-tizen.cmake
- infra/nnfw/cmake/options/options_armv7hl-tizen.cmake
- infra/nnfw/cmake/options/options_armv7l-tizen.cmake
- infra/nnfw/cmake/options/options_riscv64-tizen.cmake
- infra/nnfw/cmake/options/options_x86_64-tizen.cmake
- packaging/nnfw.spec
This commit updates tizen test build
- Disables boost static linking on tizen.
- Tizen is not supporting boost library static linking.
- Use hdf5 static devel package
---
It will resolve build fail #13355
> [infra] Update tizen test build

- runtime/onert/core/include/ir/train/TrainableGraph.h
- runtime/onert/core/src/ir/train/TrainableGraph.cc
- runtime/onert/core/src/ir/train/TrainableGraph.test.cc
This commit adds essentialBackwardOrder method to TrainableGraph.
- Add essentialBackwardOrder that generates essential backwarding order used by truncateBackwardOrder method from TrainableGraph
- Divide truncateBackwardOrder to be able to truncate conditionally
- Add additional unit tests to verify backwarding order
> [onert] Add essentialBackwardOrder to TrainableGraph

- runtime/onert/core/include/ir/train/TrainableGraph.h
- runtime/onert/core/include/ir/train/UseDefChains.h
- runtime/onert/core/src/ir/train/TrainableGraph.cc
- runtime/onert/core/src/ir/verifier/Verifier.cc
- runtime/onert/core/src/ir/verifier/Verifier.h
This commit adds use-def chains to TrainableGraph.
- Add use-def chains for training to TrainableGraph
- Add verifying UseDefChains to DagChecker and EdgeChecker and apply it to TrainableGraph
> [onert] Add use-def chains to TrainableGraph

- runtime/onert/core/src/backend/builtin/IOTensor.cc
- runtime/onert/core/src/backend/builtin/IOTensor.h
- runtime/onert/core/src/backend/builtin/kernel/WhileLayer.cc
- runtime/onert/core/src/exec/ExecutorBase.cc
- runtime/onert/core/src/exec/MultiModelExecutors.cc
- runtime/onert/core/src/exec/SingleModelExecutors.cc
- runtime/onert/core/src/exec/train/TrainableExecutors.cc
This commit revisits IOTensor
- OperandInfo such as shape, type, dynamic is maintained on its own "_info" field
- Remove orig_info() and orig_layout() getter
- setTensor methods update its own "_info" field if shape is different
- Setter methods update both its own "_info" field and actual tensor
---
Draft: #13333
> [onert] Revisit IOTensor

- tests/tools/onert_run/src/args.cc
- tests/tools/onert_run/src/args.h
- tests/tools/onert_run/src/onert_run.cc
This commit adds options to change output shape for output dump. 
It helps h5diff between circle(tflite) and tvn model output: different output rank.
---
Draft: #13284
> [onert/onert_run] Reshape output shape

- runtime/onert/core/include/ir/train/ITrainableOperation.h
- runtime/onert/core/include/ir/train/TrainableGraph.h
- runtime/onert/core/include/ir/train/TrainableOperation.h
- runtime/onert/core/src/ir/train/TrainableGraph.cc
This commit adds disableBackward function in TrainableGRaph to disable backword of an op node.
> [onert] Add disabling backward to TrainableGraph

- runtime/onert/backend/train/optimizer/Optimizers.test.cc
- runtime/onert/core/include/backend/IPortableTensor.h
- runtime/onert/core/include/backend/basic/Tensor.h
- runtime/onert/core/include/backend/basic/train/TrainableTensor.h
- runtime/onert/core/src/backend/IPortableTensor.cc
- runtime/onert/core/src/backend/basic/Tensor.cc
- runtime/onert/core/src/backend/builtin/IOTensor.h
- runtime/onert/core/src/backend/builtin/UserTensor.cc
- runtime/onert/core/src/backend/builtin/UserTensor.h
This commit revisits IPortableTensor interface
- Introduce getters for tensor info
- Introduce calcOffset() to calculate offset by using tensor info
- Remove tensor info getter and calcOffset() from derived classes
- Derived classes use IPortableTensor's getters and calcOffset() instead of its own methods
---
Draft: https://github.com/Samsung/ONE/pull/13333
> [onert] Revisit IPortableTensor

- runtime/onert/backend/train/BackendContext.cc
- runtime/onert/core/src/compiler/ExecutorFactory.cc
This commit replaces btopolSortOperations with essentialBackwardOrder.
> [onert] Replace btopolSortOperations with essentialBackwardOrder

- runtime/onert/core/include/backend/IPortableTensor.h
This commit fixes typos in IPortableTensor.h.
Related: https://github.com/Samsung/ONE/pull/13368/files#r1671432747
> [onert] Fix typo in IPortableTensor.h

- runtime/onert/backend/train/ops/BinaryArithmeticLayer.cc
This commit adds missing allocation of temporary tensor in train BinaryArithmeticLayer.
> [onert] Add missing allocation in train BinaryArithmeticLayer

- runtime/onert/core/src/ir/train/TrainableGraph.cc
This commit adds the missing definition of setTrainingUseDef in TrainableGraph.
> [onert] Add missing definition in TrainableGraph

- runtime/onert/backend/train/ops/LossCategoricalCrossentropyLayer.cc
- runtime/onert/backend/train/ops/LossLayer.cc
- runtime/onert/backend/train/ops/LossMeanSquaredErrorLayer.cc
This commit moves the assertion that checks backwarding y_pred tensor from constructor to backward.
> [onert] Move assertion in loss layers

- tests/tools/tflite_comparator/CMakeLists.txt
- tests/tools/tflite_comparator/src/args.cc
- tests/tools/tflite_comparator/src/args.h
This commit updates tflite_comparator to use arser for argument parsing instead of boost::program_options.
---
Draft:  #13366
> [onert/tflite_comparator] Use arser for tflite_comparator

- runtime/onert/core/src/exporter/TrainInfoBuilder.h
This commit updates TrainInfoBuilder constructor to use reference to access training info.
> [onert] Use reference in TrainInfoBuilder

- tools/kbenchmark/Args.cc
- tools/kbenchmark/CMakeLists.txt
This commit updates kbenchmark to use arser for argument parsing instead of boost::program_options.
---
Draft: #13366
> [onert/kbenchmark] Use arser for kbenchmark

- runtime/onert/core/include/exec/IExecutor.h
- runtime/onert/core/src/backend/builtin/kernel/IfLayer.h
- runtime/onert/core/src/backend/builtin/kernel/WhileLayer.cc
- runtime/onert/core/src/exec/ExecutorBase.h
- runtime/onert/core/src/exec/MultiModelExecutors.cc
- runtime/onert/core/src/exec/MultiModelExecutors.h
- runtime/onert/core/src/exec/SingleModelExecutors.cc
- runtime/onert/core/src/exec/train/TrainableExecutor.h
- runtime/onert/core/src/exec/train/TrainableExecutors.cc
This commit revisits public header IExecutor.h to remove  dependency with IOTensor class defined in private header IOTensor.h
- Remove getInputTensors() and getOutputTensors() method
- Introduce inputSize(), outputSize(), inputInfo(), outputInfo() method to replace getInputTensors() and getOutputTensors()
- Reorder and remove unused header include in IExecutor.h
---
Draft: #13333
> [onert] Remove IOTensor dependency in IExecutor

- compiler/vconone/CMakeLists.txt
This commit bumps up to 1.27.1.
> [vconone] Bump up to 1.27.1

- docs/release/1.27/index.rst
- docs/release/1.27/release-note-1.27.1.md
This commit revists command schema feature.
- Support multiple names
- Fix invalid warning on boolean type option.
> [one-cmds] Revisit command schema feature

- compiler/arser/include/arser/arser.h
- compiler/arser/tests/arser.test.cpp
This commit updates arser to support multiline help message with alignment.
> [arser] Support multiline help message alignment

- compiler/luci-interpreter/src/kernels/CumSum.cpp
- compiler/luci-interpreter/src/kernels/CumSum.test.cpp
This commit supports int type of CumSum op.
> [luci-interpreter] Support int type of CumSum op

- runtime/onert/core/src/exec/MultiModelExecutors.cc
- runtime/onert/core/src/exec/MultiModelExecutors.h
This commit changes edge tensor type in MultiModelExecutors
- Package I/O edge: IOTensor -> UserTensor
- Change to use UserTensor to represent buffer from user. IOTensor is indirect tensor to represent executor I/O in each executor
- Edge between executor: EdgeTensor derived from IOTensor -> derived from IPortableTensor
- Change to use EdgeTensor derived from IPortableTensor to represent buffer allocated in executors
---
Draft: #13333
> [onert] Change Edge tensor type in MultiModelExecutors

- runtime/onert/core/src/exec/Execution.test.cc
- runtime/onert/core/src/exec/ExecutorBase.cc
- runtime/onert/core/src/exec/SingleModelExecutors.cc
This commit updates SingleModelExecutors to support type-aware quantization. 
It uses similar quantization/dequantization logic as that of MultiModelExecutors.
It includes unittest.
---
Draft: #13284
> [onert] Support type-aware quantization in SingleModelExecutors

- compute/cker/include/cker/operation/SplitV.h
This commit removes unused variable `split_size` in SplitV.h
`split_size` is used to update itself only.
> [onert/cker] Remove unused variable

- runtime/onert/core/src/util/ShapeInference.cc
This commit removes unused variable `num_reduce_axis` in ShapeInference.cc inferReduceShape() method. 
`num_reduce_axis` is used to update itself only.
> [onert] Remove unused variable in ShapeInference

- compute/cker/include/cker/operation/Concatenation.h
- compute/cker/include/cker/operation/StridedSlice.h
This commit marks the UNUSED_RELEASE macro as unused on release build because it is only used on assert.
> [compute/cker] Mark UNUSED_RELEASE

- docs/howto/how-to-cross-build-runtime-for-android.md
- infra/docker/android-sdk/Dockerfile
- tools/cross/install_android_ndk.sh
- tools/cross/install_android_sdk.sh
This commit is for version up NDK to latest LTS: 26.3.11579264
> [infra] Version up NDK

- runtime/onert/core/src/exec/Execution.test.cc
This commit fixes a bug in CompiledMockUpQuantModel constant data array size.
> [onert/test] Fix unittest bug in CompiledMockUpQuantModel

- runtime/onert/api/nnfw/include/nnfw.h
- runtime/onert/api/nnfw/src/nnfw_api_internal.cc
- runtime/onert/core/src/exec/Execution.cc
- runtime/onert/core/src/exec/Execution.test.cc
- tests/nnfw_api/src/GenModelTests/ModelTestDynamicTensor.test.cc
- tests/nnfw_api/src/NNPackageTests/AddSessionPrepared.test.cc
This commit updates API implementation to support float type I/O setting.
---
Draft: #13284
> [onert] Support float type I/O setting API on quantized model

- compiler/vconone/CMakeLists.txt
This commit bumps up to 1.27.2.
> [vconone] Bump up to 1.27.2

- runtime/onert/backend/train/TensorBuilder.cc
- runtime/onert/backend/train/TensorBuilder.h
This commit stores disposable tensor indices in TensorBuilder.
> [onert/training] Store disposable tensor indices in TensorBuilder

- runtime/onert/core/src/exec/train/TrainableExecutor.cc
- runtime/onert/core/src/exec/train/TrainableExecutor.h
- runtime/onert/core/src/exec/train/TrainableExecutors.cc
- runtime/onert/core/src/exec/train/TrainableExecutors.h
This commit changes the TrainableExecutor forward to be similar as the ExecutorBase execute implementation.
> [onert] Change TrainableExecutor forward call

- compiler/luci/pass/include/luci/CircleOptimizer.h
- compiler/luci/pass/include/luci/Pass/FuseAddToFullyConnectedBiasPass.h
- compiler/luci/pass/src/CircleOptimizer.cpp
- compiler/luci/pass/src/FuseAddToFullyConnectedBiasPass.cpp
- compiler/luci/pass/src/FuseAddToFullyConnectedBiasPass.test.cpp
This will introduce FuseAddToFullyConnectedBiasPass which will
fuse Add to following FullyConnected bias if possible.
> [luci/pass] Introduce FuseAddToFullyConnectedBiasPass

- compiler/luci/pass/include/luci/CircleOptimizer.h
- compiler/luci/pass/include/luci/Pass/FuseMulToFullyConnectedWeightsPass.h
- compiler/luci/pass/src/CircleOptimizer.cpp
- compiler/luci/pass/src/FuseMulToFullyConnectedWeightsPass.cpp
- compiler/luci/pass/src/FuseMulToFullyConnectedWeightsPass.test.cpp
This will introduce FuseMulToFullyConnectedWeightsPass which will
fuse Mul to following FullyConnected weights if possible.
> [luci/pass] Introduce FuseMulToFullyConnectedWeightsPass

- runtime/onert/core/src/ir/train/UseDefGenerator.cc
- runtime/onert/core/src/ir/train/UseDefGenerator.h
This commit introduces UseDefGenerator that generates UseDefChain for each opeartion from a TrainableGraph.
- Introduce UseDefGenerator
- Add a visit method for backwarding Loss op
- Add helper methods
- insertUse : insert an opeartion index as use into UseDefChain for an operand
- insertDef : insert an operation index as def into UseDefChain for an operand
- insertBackPropDef : insert use similarly insertUse, but only insert it if operand is not a constant
- initForForwardingNodes : insert UseDefChains for all forwarding operation nodes.
- initForBackwardNodes : insert UseDefChains for all backwarding operation nodes.
> [onert] Introduce UseDefGenerator

- compiler/vconone/CMakeLists.txt
This commit bumps up to 1.29.0.
---
Related issue:  #13442
> [vconone] Bump up to 1.29.0

- compiler/luci/pass/src/FuseAddToFullyConnectedBiasPass.test.cpp
- compiler/luci/pass/src/FuseMulToFullyConnectedWeightsPass.test.cpp
This will fix typos in fuse Add/Mul to FullyConnected pass unit tests.
> [luci/pass] Fix typos in FuseXxxToFC test

- runtime/onert/backend/train/KernelGenerator.cc
This commit adds throw keyword to the train kernel generator.
> [onert] Fix typo in train kernel generator

- docs/conf.py
- packaging/nnfw.spec
- runtime/contrib/android/api/build.gradle
- runtime/onert/api/nnfw/include/nnfw_version.h
- tools/release_tool/onert_version.sh
This commit bumps up to 1.29.0.
> [onert] Bump up to 1.29.0

- runtime/onert/backend/train/KernelGenerator.cc
It fixes a typo in train kernel generator.
> [onert] Fix a typo in train kernel generator

- runtime/onert/core/src/ir/train/UseDefGenerator.cc
- runtime/onert/core/src/ir/train/UseDefGenerator.h
This commit adds generating training usedefs for Reshape operation.
> [onert] Add generating training usedefs for Reshape op

- runtime/onert/api/python/package/libnnfw_api_pybind.py
This commit is replacing slower list initialization with faster numpy call to create empty inputs and outputs for a `nnfw_session`.
> [python] Speed up memory allocation of empty numpy arrays for inputs and outputs

- compiler/luci/pass/src/ConvertNCHWToNHWCPass.cpp
This removes unnecessary copy of std vector.
> [luci/pass] Remove copy of vector

- infra/debian/runtime/control
This commit removes unused runtime build dependency: boost, hdf5
>  [infra/debian] Remove unused runtime build dependency

- Makefile.template
This commit update Makefile.template's create-package command to remove arm compute library from runtime tar.gz package again.
> [infra/onert] Remove ACL from runtime package

- runtime/onert/api/python/include/nnfw_api_wrapper.h
- runtime/onert/api/python/package/libnnfw_api_pybind.py
- runtime/onert/api/python/src/nnfw_api_wrapper_pybind.cc
This commit removes calls to deprecated paths (which used `nnfw_set_op_backend` underneath) on Python bindings side.
> [python] Remove deprecated methods using nnfw_set_op_backend

- runtime/onert/core/src/ir/train/UseDefGenerator.cc
- runtime/onert/core/src/ir/train/UseDefGenerator.h
This commit adds generating training usedefs for DepthwiseConv2D operation.
> [onert] Add generating training usedefs for DepthwiseConv2D op

- runtime/onert/core/src/ir/train/UseDefGenerator.cc
- runtime/onert/core/src/ir/train/UseDefGenerator.h
This commit adds generating training usedefs for Pad op.
> [onert] Add generating training usedefs for Pad op

- runtime/onert/core/src/compiler/pass/ConstantInsertionPass.cc
- runtime/onert/core/src/compiler/pass/ConstantInsertionPass.h
This commit add original operand map to use original operand if backend layout is same. 
It will prevent removing original operand and reduce constant operand creation.
> [onert] Use original map in ConstantInsertionPass

- runtime/onert/core/src/ir/train/UseDefGenerator.cc
- runtime/onert/core/src/ir/train/UseDefGenerator.h
This commit adds generating training usedefs for BinaryArithmetic operation.
> [onert] Add generating training usedefs for BinaryArithmetic op

- runtime/onert/backend/train/TensorPlanner.cc
This commit add planning non-const tensors(forwarding non-const tensors) on train backend.
> [onert] Plan non-const tensors on train backend

- runtime/onert/core/src/ir/train/UseDefGenerator.cc
- runtime/onert/core/src/ir/train/UseDefGenerator.h
This commit adds generating training usedefs for Reduce op.
> [onert] Add generating training usedefs for Reduce op

- runtime/onert/core/src/ir/train/UseDefGenerator.cc
- runtime/onert/core/src/ir/train/UseDefGenerator.h
This commit adds generating training usedefs for Softmax operation.
> [onert] Add generating training usedefs for Softmax op

- runtime/onert/api/python/include/nnfw_api_wrapper.h
- runtime/onert/api/python/src/nnfw_api_wrapper.cc
- runtime/onert/api/python/src/nnfw_api_wrapper_pybind.cc
This commit changes the function name to avoid conflicts with Python's restricted keywords.
> [python] Change await to wait to avoid keyword use

- runtime/onert/backend/train/BackendContext.cc
- runtime/onert/backend/train/Tensor.h
- runtime/onert/backend/train/TensorBuilder.cc
- runtime/onert/backend/train/TensorBuilder.h
- runtime/onert/backend/train/ops/BinaryArithmeticLayer.cc
- runtime/onert/backend/train/ops/ConvolutionLayer.cc
- runtime/onert/backend/train/ops/DepthwiseConvolutionLayer.cc
- runtime/onert/backend/train/ops/FullyConnectedLayer.cc
- runtime/onert/backend/train/ops/PoolLayer.cc
- runtime/onert/core/include/backend/basic/BackendContextHelpers.h
- runtime/onert/core/include/backend/basic/DynamicTensorManager.h
- runtime/onert/core/include/backend/basic/StaticTensorManager.h
- runtime/onert/core/include/backend/basic/Tensor.h
- runtime/onert/core/include/backend/basic/TensorBuilder.h
- runtime/onert/core/include/backend/basic/train/TrainableBackendContextHelpers.h
- runtime/onert/core/include/backend/basic/train/TrainableTensor.h
- runtime/onert/core/src/backend/basic/DynamicTensorManager.cc
- runtime/onert/core/src/backend/basic/StaticTensorManager.cc
- runtime/onert/core/src/backend/basic/TensorBuilder.cc
- runtime/onert/core/src/backend/builtin/IOTensor.cc
- runtime/onert/core/src/backend/builtin/IOTensor.h
- runtime/onert/core/src/backend/builtin/TensorBuilder.cc
- runtime/onert/core/src/backend/builtin/TensorBuilder.h
- runtime/onert/core/src/backend/builtin/kernel/WhileLayer.cc
- runtime/onert/core/src/compiler/ExecutorFactory.cc
This commit removes layout setting for basic tensor. 
This tensor is used in builtin, cpu, ruy, xnnpack, and train backend.
---
Related issue: #13494
> [onert] Remove layout usage in basic tensor

- infra/command/format
This commit considers `fm-equalize` when formatting.
Related: #13488
> [format] Add fm-equalize

- runtime/onert/backend/train/optimizer/Adam.cc
- runtime/onert/backend/train/optimizer/SGD.cc
This commit replaces using `std::get` on tuples with using structured binding declaration in training optimizers.
> [onert] Use structured binding declaration in optimizers

- compiler/luci/service/src/CircleShapeInferenceRule.cpp
This will enable Pad shape inference with INT64 paddings.
> [luci/svc] Enable Pad SI with INT64 paddings

- compiler/luci/pass/include/luci/Pass/CanonicalizePass.h
- compiler/luci/pass/src/CanonicalizePass.cpp
- compiler/luci/pass/src/CanonicalizePass.test.cpp
This will introduce CanonicalizePass with Pad.paddings canonicalize.
> [luci/pass] Introduce CanonicalizePass with Pad

- runtime/onert/backend/train/TensorBuilder.cc
- runtime/onert/backend/train/TensorBuilder.h
This commit adds a method that can notify last used node to support releasing memory of backwarding tensors.
> [onert] Add notifyBackwardLastUse() to TensorBuilder

- compute/cker/include/cker/eigen/bias_op.h
This commit introduces Bias_Op cpu kernel.
This kernel will be used in DepthwiseConv2D operation.
Related issue: #13513 
_(added)_
_This code will be tested in DepthwiseConv2D kernel and nnapi tests._
> [onert] Introduce Bias_Op cpu kernel

- compiler/luci/pass/src/RemoveUnnecessaryReshapeNetPass.cpp
This commit adds RELU op in RemoveUnnecessaryReshapeNetPass. An internal model has this pattern: Reshape - Relu - Reshape.
> [luci] Add RELU in RemoveUnnecessaryReshapeNetPass

- runtime/onert/backend/cpu/KernelGenerator.cc
This commit removes backend layout checking in CPU backend KernelGenerator.
---
Related issue: #13494
> [onert] Remove backend layout checking in KernelGenerator

- runtime/onert/core/include/ir/train/TrainableGraph.h
- runtime/onert/core/src/compiler/ExecutorFactory.cc
- runtime/onert/core/src/compiler/train/TrainingCompiler.cc
- runtime/onert/core/src/ir/train/TrainableGraph.cc
This commit applies training usedefs to patial trainable graphs to be passed into backends.
- Add a method to TrainableGraph that initialize training usedefs
- Call the method for patial trainable graphs
> [onert] Apply usedef chains for training

- runtime/onert/backend/acl_cl/Config.cc
- runtime/onert/backend/acl_cl/Config.h
- runtime/onert/backend/acl_neon/Config.cc
- runtime/onert/backend/acl_neon/Config.h
- runtime/onert/backend/cpu/Config.cc
- runtime/onert/backend/cpu/Config.h
- runtime/onert/backend/ruy/Config.cc
- runtime/onert/backend/ruy/Config.h
- runtime/onert/backend/train/Config.cc
- runtime/onert/backend/train/Config.h
- runtime/onert/backend/trix/Config.cc
- runtime/onert/backend/trix/Config.h
- runtime/onert/backend/xnnpack/Config.cc
- runtime/onert/backend/xnnpack/Config.h
- runtime/onert/core/include/backend/IConfig.h
- runtime/onert/core/src/backend/builtin/Config.cc
- runtime/onert/core/src/backend/builtin/Config.h
- runtime/onert/core/src/compiler/HEScheduler.test.cc
- runtime/onert/core/src/compiler/LoweredGraph.cc
- runtime/onert/core/src/compiler/train/LoweredTrainableGraph.cc
- runtime/onert/core/src/exec/ExecTime.test.cc
This commit removes supportLayout function from IConfig interface.
---
Related issue: #13494
> [oenrt] Remove supportLayout function in backend config

- compiler/luci/pass/src/ConvertNCHWToNHWCPass.cpp
This removes duplicate codes in ConvertNCHWToNHWC.
> [luci/pass] Remove duplicate code

- runtime/onert/core/src/compiler/train/LoweredTrainableGraph.cc
- runtime/onert/core/src/compiler/train/pass/TrainableConstantInsertionPass.cc
- runtime/onert/core/src/compiler/train/pass/TrainableConstantInsertionPass.h
This commit introduces TrainableConstantInsertionPass that resolves shared contants issue in training.
- Introduce TrainableConstantInsertionPass that makes constant operand have only one use node.
- Apply TrainableConstantInsertionPass to training
> [onert] Introduce TrainableConstantInsertionPass

- compiler/luci/pass/include/luci/CircleOptimizer.h
- compiler/luci/pass/src/CircleOptimizer.cpp
This will extract canonicalize method with
- run before convert_nchw_to_nhwc
- also run remove dead node pass to remove unnecessary nodes
so that convert_nchw_to_nhwc have have canonicalized properties.
> [luci/pass] Extract canonicalize method

- compiler/luci-pass-value-py-test/test.lst
This will add disabled Pad_001 value test as current tflite doesn't support INT64 yet.
> [luci-pass-value-test] Add disabled Pad_001

- compiler/luci/pass/src/ConvertNCHWToNHWCPass.cpp
- compiler/luci/pass/src/ConvertNCHWToNHWCPass.test.cpp
This supports Div in ConvertNCHWToNHWC.
> [luci/pass] Support Div in ConvertNCHWToNHWC

- compute/cker/include/cker/operation/ReLU6.h
This commit adds assertion for checking input and output shapes. Their shapes should match. Otherwise, an error occurs.
> [onert] Add assertion to ReLU6

- runtime/onert/backend/train/TensorPlanner.cc
This commit adds planning back-propagated tensors used on train backend.
> [onert] Plan back-propagated tensors on train backend

- runtime/onert/backend/train/TensorPlanner.cc
This commit adds planning gradient tensors used on train backend.
> [onert] Plan gradient tensors on train backend

- compute/cker/include/cker/train/operation/DepthwiseConv.h
- runtime/onert/backend/train/ops/DepthwiseConvolutionLayer.cc
This commit sets dilation factor in DepthwiseConv train kernel. The DepthwiseConv train kernel does not support dilation value other than 1. It adds assertion to check the supported dilation value.
> [onert] Set dilation factor in DepthwiseConv train kernel

- infra/debian/runtime/control
This commit removes unused debian build dependency: dh-python, python3-all
> [infra/onert] Remove unused debian build dependency

- runtime/onert/core/include/ir/Graph.h
- runtime/onert/core/include/ir/train/TrainableGraph.h
- runtime/onert/core/src/compiler/ExecutorFactory.cc
- runtime/onert/core/src/ir/train/TrainableGraph.cc
- runtime/onert/core/src/loader/CircleLoader.cc
- runtime/onert/loader/trix/TrixLoader.cc
This commit removes setLayout function in Graph and TrainableGraph.
---
Related issue: #12130 #13494
> [onert] Remove setLayout in graph

- compiler/luci/pass/src/CanonicalizePass.cpp
- compiler/luci/pass/src/CanonicalizePass.test.cpp
This will enable Canonicalize PadV2 paddings dtype.
> [luci/pass] Canonicalize PadV2 paddings

- compiler/luci-pass-value-py-test/test.lst
This will add disabled PadV2_002 value test as current tflite doesn't support INT64 yet.
> [luci-pass-value-test] Add disabled PadV2_002

- runtime/onert/backend/train/TensorPlanner.cc
This commit fixes a typo in gradient TensorPlanner.
> [onert] Fix typo

- runtime/onert/backend/acl_cl/ConstantInitializer.cc
- runtime/onert/backend/acl_cl/KernelGenerator.cc
- runtime/onert/backend/acl_cl/KernelGenerator.h
- runtime/onert/backend/acl_cl/Optimizer.cc
- runtime/onert/backend/acl_common/AclBackendContext.h
- runtime/onert/backend/acl_common/AclConstantInitializer.cc
- runtime/onert/backend/acl_common/AclConstantInitializer.h
- runtime/onert/backend/acl_common/AclKernelGen.h
- runtime/onert/backend/acl_common/AclSubTensorAnalyzer.h
- runtime/onert/backend/acl_common/AclTensorBuilder.h
- runtime/onert/backend/acl_common/Convert.cc
- runtime/onert/backend/acl_common/Convert.h
- runtime/onert/backend/acl_common/Swizzle.h
- runtime/onert/backend/acl_neon/KernelGenerator.cc
- runtime/onert/backend/acl_neon/KernelGenerator.h
- runtime/onert/backend/acl_neon/Optimizer.cc
- runtime/onert/backend/cl_common/include/cl_common/BackendContext.h
- runtime/onert/backend/cl_common/include/cl_common/ParentInfo.h
This commit removes frontend layout checking and permutation in ACL backend.
---
> [onert] Remove frontend layout usage in ACL backend

- runtime/onert/backend/cpu/KernelGenerator.cc
- runtime/onert/backend/cpu/KernelGenerator.h
- runtime/onert/backend/cpu/ops/OperationUtils.h
- runtime/onert/backend/ruy/KernelGenerator.cc
- runtime/onert/backend/ruy/KernelGenerator.h
- runtime/onert/backend/train/BackendContext.cc
- runtime/onert/backend/train/KernelGenerator.cc
- runtime/onert/backend/train/KernelGenerator.h
- runtime/onert/backend/trix/KernelGenerator.cc
- runtime/onert/backend/trix/KernelGenerator.h
- runtime/onert/backend/xnnpack/KernelGenerator.cc
- runtime/onert/backend/xnnpack/KernelGenerator.h
This commit removes frontend layout checking and permutation in CPU, RUY, Train, Trix, XNNPack backend.
---
https://github.com/Samsung/ONE/issues/12130 https://github.com/Samsung/ONE/issues/13494
> [onert] Remove frontend layout usage in non-ACL backend

- tests/nnfw_api/src/GenModelTests/BranchModelTrain.test.cc
This commit moves a test that has existed in wrong location from BranchOps_FC_Sub to BranchOps_FC_Add.
> [nnfw_tests] Move a test from wrong location

- res/TensorFlowLiteRecipes/PadV2_002/test.recipe
This will introduce PadV2_002 tflite recipe.
> [res] Introduce PadV2_002 tflite recipe

- runtime/onert/backend/train/TensorPlanner.cc
- runtime/onert/backend/train/TensorPlanner.h
This commit adds planning disposable tensors used on train backend.
> [onert] Plan disposable tensors on train backend

- runtime/onert/core/include/backend/basic/BackendContextHelpers.h
- runtime/onert/core/include/backend/basic/train/TrainableBackendContextHelpers.h
- runtime/onert/core/include/ir/Graph.h
- runtime/onert/core/include/ir/train/TrainableGraph.h
- runtime/onert/core/include/util/ShapeInference.h
- runtime/onert/core/src/compiler/ExecutorFactory.cc
- runtime/onert/core/src/compiler/LoweredGraph.cc
- runtime/onert/core/src/compiler/ShapeValidator.cc
- runtime/onert/core/src/compiler/StaticShapeInferer.cc
- runtime/onert/core/src/compiler/pass/PermutationOperationPass.cc
- runtime/onert/core/src/compiler/train/LoweredTrainableGraph.cc
- runtime/onert/core/src/util/ShapeInference.cc
This commit removes layout field in Graph and TrainableGraph.
---
Related issue: https://github.com/Samsung/ONE/issues/12130
> [onert] Remove layout in graph

- tests/tools/onert_train/CMakeLists.txt
- tests/tools/onert_train/src/args.cc
- tests/tools/onert_train/src/args.h
- tests/tools/onert_train/src/onert_train.cc
This commit updates onert_train to use arser for argument parsing instead of boost::program_options.
> [onert/onert_train] Use arser for onert_train

- tests/tools/onert_run/CMakeLists.txt
- tests/tools/onert_run/src/args.cc
- tests/tools/onert_run/src/args.h
- tests/tools/onert_run/src/onert_run.cc
This commit updates onert_run to use arser for argument parsing instead of boost::program_options.
---
Draft:  #13366
> [onert/onert_run] Use arser for onert_run

- docs/howto/how-to-build-runtime-tizen-gbs-rpi4.md
- docs/runtime/transfer_learning.md
- tests/scripts/benchmark.sh
- tests/scripts/command/nnpkg-test
- tests/tools/onert_run/src/args.cc
- tests/tools/onert_train/README.md
- tests/tools/onert_train/src/args.cc
- tools/stab/remote.py
This commit removes "--nnpackage" and "--modelfile" options from `onert_run` and `onert_train` test drivers. 
They can be handled on last parameter without option automatically.
> [onert/test] Remove nnpackage and modelfile options

- tests/nnfw_api/src/GenModelTests/one_op_tests/DepthwiseConv2D.test.cc
This commit renames test cases to be simple and adds test cases related to Bias and Multiplier.
> [onert] Revisit DepthwiseConv2D nnfw_api test

- runtime/onert/backend/train/BackendContext.cc
- runtime/onert/backend/train/BackendContext.h
This commit rivises generating tensors for training.
- Apply TensorPlanner to train backend
- Generates only planned tensors
> [onert] Revise generating tensors for training

- compiler/onnx-tools/onnx-dump.py
- compiler/onnx-tools/onnx-ops.py
This commit fixes onnx.checker.check_model usage in onnx-dump.py and onnx-ops.py to support models with size greater than 2GB.
> [onnx-tools] Support onnx model over 2GB

- runtime/onert/core/include/compiler/OperandLowerInfo.h
- runtime/onert/core/src/compiler/ExecutorFactory.cc
- runtime/onert/core/src/compiler/LoweredGraph.cc
- runtime/onert/core/src/compiler/pass/ConstantLoweringPass.cc
- runtime/onert/core/src/compiler/pass/PermutationEliminationPass.cc
- runtime/onert/core/src/compiler/pass/PermutationInsertionPass.cc
- runtime/onert/core/src/compiler/pass/PermutationInsertionPass.h
- runtime/onert/core/src/compiler/train/LoweredTrainableGraph.cc
- runtime/onert/core/src/compiler/train/pass/TrainableConstantInsertionPass.cc
- runtime/onert/core/src/dumper/dot/DotDumper.cc
This commit updates OperandLowerInfo to use backend directly.
---
Related issue: #12130
> [onert] Simplify OperandLowerInfo

- compute/cker/include/cker/eigen/bias_op.h
To remove an unused variable warning in release build, this commit uses
maybe_unused attribute for local variable.
> [onert] Use maybe_unused attribute for local variable in bias_op kernel

- runtime/onert/core/include/backend/train/ExtraTensor.h
This PR introduces ExtraTensor.
ExtraTensor means that the tensor is only used by one operation.
draft : https://github.com/Samsung/ONE/pull/13486 
related : https://github.com/Samsung/ONE/issues/13282
> [onert] Introduce ExtraTensor

- .github/workflows/run-onert-android-build.yml
This commit updates android build workflow to use cache for externals directory.
> [github] Use cache for android externals

- runtime/onert/backend/train/KernelGenerator.cc
- runtime/onert/backend/train/KernelGenerator.h
This commit changes BackPropAccumulators to be generated only if the correspoding dispoable tensors exist.
> [onert] Generate BackPropAccumulator only if necessary

- compiler/one-cmds/onelib/utils.py
- compiler/one-cmds/tests/one-codegen_012.cfg
- compiler/one-cmds/tests/one-codegen_012.test
This commit sets env variables when running sub-command.
Related: #13588 
> [one-cmds] Set env variables when running sub-command

- .github/workflows/run-onecc-build.yml
This commit adds the onecc workflow trigger to run on commit push.
> [github] Enable onecc test workflow trigger on push evnet

- runtime/onert/backend/acl_cl/KernelGenerator.cc
- runtime/onert/backend/acl_cl/KernelGenerator.h
- runtime/onert/backend/acl_neon/KernelGenerator.cc
- runtime/onert/backend/acl_neon/KernelGenerator.h
- runtime/onert/core/src/compiler/pass/PermutationInsertionPass.cc
This commit removes Permute IR handling in acl backends. 
This IR is handled on builtin backend only because layout changes in backend is not available feature any more.
---
Related issue: https://github.com/Samsung/ONE/issues/12130 #13494
> [onert] Remove Permute IR handling in general backend

- runtime/onert/backend/train/Backend.h
- runtime/onert/backend/train/MemoryManager.cc
- runtime/onert/backend/train/MemoryManager.h
- runtime/onert/backend/train/TensorBuilder.cc
- runtime/onert/backend/train/TensorBuilder.h
- runtime/onert/backend/train/TensorManager.cc
- runtime/onert/backend/train/TensorManager.h
This commit make train backend use default cpu planner to be configured by user.
> [onert] Use default cpu planner for training

- runtime/onert/backend/train/MemoryManager.cc
- runtime/onert/backend/train/MemoryManager.h
- runtime/onert/backend/train/TensorManager.cc
- runtime/onert/backend/train/TensorManager.h
This commit moves the memory management of optimizer variables into TrainableMemoryManager. Optimizer variables have the same characteristic as TrainableTensor in that memory must not be released during training. The such fact makes it easier for TrainableMemoryManager, rather than GradientMemoryManager, to manage optimizer variables.
> [onert] Fix wrong allocation of optimizer variables

- onert-micro/onert-micro/include/OMConfig.h
- onert-micro/onert-micro/include/train/losses_functions/SparseCrossEntropy.h
- onert-micro/onert-micro/src/core/train/OMTrainingHandler.cpp
- onert-micro/onert-micro/src/train/CMakeLists.txt
- onert-micro/onert-micro/src/train/losses_functions/SparseCrossEntropy.cpp
This commit adds new loss function "SparseCrossEntropy" Since this function has different number compare to one-hot-encoded target, offset change condition was added.
ONE-DCO-1.0-Signed-off-by: Jungwoo Lee <jade.jw.lee@samsung.com>
> [onert-micro] Bring up SparseCrossEntropy Loss Function

- compiler/luci-interpreter/src/kernels/MirrorPad.cpp
This will revise MirrorPad kernel to use LUCI_INTERPRETER_CHECK instead of assert.
> [luci-interpreter] Revise MirrorPad to use LUCI_INTERPRETER_CHECK

- runtime/onert/backend/train/ExtraTensorIndex.h
This PR introduces ExtraTensorIndex.
ExtraTensorIndex will be used to identify extra tensor in tensor registry.
draft : https://github.com/Samsung/ONE/pull/13486 
related : https://github.com/Samsung/ONE/issues/13282
> [onert] Introduce ExtraTensorIndex

- runtime/onert/core/include/ir/operation/Permute.h
- runtime/onert/core/src/compiler/pass/ConstantOutputPass.cc
- runtime/onert/core/src/compiler/pass/OddOutputPass.cc
- runtime/onert/core/src/compiler/pass/PermutationInsertionPass.cc
- runtime/onert/core/src/ir/OperationDumper.cc
- runtime/onert/core/src/ir/operation/Permute.cc
- runtime/onert/core/src/ir/train/operation/Permute.cc
- runtime/onert/core/src/ir/train/operation/UntrainableOperation.test.cc
This commit removes type in Permute IR.
Permute IR represent copy operation in compilation phase, and can be changed dynamically on execution phase.
---
Related issue: https://github.com/Samsung/ONE/issues/12130
> [onert] Remove type in Permute IR

- .github/workflows/run-onert-android-build.yml
This commit updates android build workflow
- Trigger on push event
- Revise path to trigger workflow
- Add hash for external cache key matching
> [github] Update android build workflow

- compute/cker/include/cker/operation/DepthwiseConv.h
- compute/cker/src/DepthwiseConv.test.cc
This commit introduces DepthwiseConvOp in cpu kernel.
This kernel uses depthwise_conv and bias_op eigen functions.
> [onert] Introduce DepthwiseConvOp in cpu kernel

- runtime/onert/backend/train/BackendContext.cc
- runtime/onert/backend/train/BackendContext.h
- runtime/onert/core/include/backend/train/TrainableBackendContext.h
- runtime/onert/core/src/backend/builtin/train/BackendContext.cc
- runtime/onert/core/src/backend/builtin/train/BackendContext.h
- runtime/onert/core/src/compiler/ExecutorFactory.cc
This commit unifies interfaces for generating tensors.
> [onert] Unify interface for generating tensors

- .github/workflows/run-onecc-build.yml
This commit adds matrix context to onecc workflow for ubuntu 22.04  test.
> [github] Add ubuntu 22.04 test to onecc workflow

- runtime/onert/backend/cl_common/include/cl_common/BackendContext.h
- runtime/onert/core/include/backend/BackendContext.h
- runtime/onert/core/include/backend/basic/BackendContextHelpers.h
- runtime/onert/core/src/compiler/ExecutorFactory.cc
This commit removes layout info in BackendContext. Layout is always NHWC.
If not, other backend and core assume that layout is NHWC and backend has responsibility for correctness.
---
> [onert] Remove layout info in BackendContext

- compiler/tflchef/core/src/ModelChef.cpp
This will tidy GeneratedModelImpl base() and size() methods.
> [tflchef] Tidy GeneratedModelImpl

- compiler/tflchef/core/src/ModelChef.cpp
This will revise cook method to have symbol_table as parameter instead
of return value and symbol_tables as ModelChef member.
> [tflchef] Revise cook with symbol_table(s)

- compiler/tflchef/core/src/ModelChef.cpp
This will extract more methods;
- prepare_initial_buffer
- gather_operator_codes
- gather_signature_defs
> [tflchef] Extract more methods

- compiler/circledump/include/circledump/Dump.h
This will fix namespace closing comment and insert empty space like others.
> [circledump] Fix namespace closing comment

- res/TensorFlowLiteRecipes/Net_FullyConnected_Mul_003/test.recipe
- res/TensorFlowLiteRecipes/Net_FullyConnected_Mul_003/test.rule
This commit extends Net_FullyConnectedMul tflite recipes with 'no bias' case.
> [res/tfl_recipes] Add new Net_FullyConnected_Mul

- runtime/onert/core/include/backend/basic/Tensor.h
- runtime/onert/core/src/backend/basic/Tensor.cc
This commit updates dynamic allocator usage on basic tensor to reallocate when shape is changed to larger size. 
It will improve performance and reduce memory usage when tensor size is lesser by dynamic shape on inference than prepare phase.
> [onert] Reallocated tensor when size becomes larger

- tests/tools/onert_run/src/args.cc
This commit updates argument policy to allow shape_prepare and shape_run together.
> [onert/onert_run] Allow shape_prepare and shape_run together

- runtime/onert/backend/train/BackendContext.cc
- runtime/onert/backend/train/BackendContext.h
- runtime/onert/core/include/backend/train/TrainableBackendContext.h
- runtime/onert/core/src/backend/builtin/train/BackendContext.cc
- runtime/onert/core/src/backend/builtin/train/BackendContext.h
- runtime/onert/core/src/compiler/ExecutorFactory.cc
This commit unifies interfaces for generating tensors and kernels for training.
> [onert] Unify generating training tensors and kernels

- docs/howto/how-to-use-nnfw-python-api.md
- infra/nnfw/python/.gitignore
- infra/nnfw/python/README.md
- infra/nnfw/python/setup.py
- runtime/onert/api/python/package/__init__.py
- runtime/onert/api/python/package/infer.py
- runtime/onert/sample/minimal-python/src/minimal.py
- Rename python package: nnfwapi -> onert
- Native library install path: "nnfwapi/onert" -> "nnfw_onert/natvie"
- Rename binding script: "libnnfw_api_pybind.py" -> "infer.py"
- Rename binding session class: "nnfw_session" -> "session"
- Update documentation
- Update example
> [onert] Revisits python API 

- onert-micro/onert-micro/include/pal/cmsisnn/PALArgMax.h
To build onert_micro_arm target with -DKERNELS=cmsisnn, we need this header.
> [onert-micro] fix build error with cmsisnn

- compiler/tflchef/core/src/ModelChef.cpp
This will revise to remove local graph_name variable.
> [tflchef] Remove local graph_name

- compiler/luci-interpreter/pal/linux/PALConv2d.h
This adds a guard code to avoid integer overflow in optimized Conv2D kernel.
---
Related to: https://github.com/Samsung/ONE/issues/13668
> [luci-interpreter] Avoid Conv2D integer overflow

- infra/cmake/packages/FlatBuffers-23.5.26/FlatBuffersConfig.cmake
This will introduce FlatBuffersMuteable_Target method to produce
schema generated header with mutable methods.
> [infra/fb] Introduce FlatBuffersMuteable_Target

- compiler/mio-tflite2121/CMakeLists.txt
This will revise to use new schema to support file size > 2G and with mutable methods.
> [mio-tflite] Revise to use new schema with mutable

- compiler/tflchef/core/src/ModelChef.cpp
This will add finalize_ext_buffer method and members to handle data outside of limits of flatbuffres offset.
> [tflchef] Introduce finalize_ext_buffer and members

- runtime/onert/backend/cpu/ops/DepthwiseConvolutionLayer.cc
This commit fixes DepthwiseConvOp kernel usage condition. 
Eigen kernel is not supproting different width-height stride yet.
---
Resolve https://github.com/Samsung/ONE/issues/13675 and coverage test fail
> [onert] Fix DepthwiseConvOp kernel condition

- compiler/tflchef/core/src/ModelChef.cpp
- compiler/tflchef/proto/tflchef.proto
This will add ext_offset field to recipe proto to generate
Buffer data outside of flatbuffer region.
> [tflchef] Add ext_offset field to recipe proto

- compiler/tflchef/tests/ext_offset/test.recipe
This will add ext_offset enabled test recipe to generate tflite file
in format to support file size > 2G.
> [tflchef] Introduce ext_offset test recipe

- compiler/mio-circle08/CMakeLists.txt
- compiler/mio-circle08/include/mio_circle/Reader.h
- compiler/mio-circle08/src/Reader.cpp
This will revise to support ext_offset with
- enable mutable methods with generated schema
- enable to read Buffer offset/size attributes
> [mio-circle08] Revise to support ext_offset

- .github/workflows/run-onecc-build.yml
This will revuse to run onecc-build only in Samsung Org.
> [github] Run onecc-build only in Samsung Org.

- compiler/tfldump/driver/Driver.cpp
- compiler/tfldump/include/tfldump/Dump.h
- compiler/tfldump/src/Dump.cpp
This will revise to support Buffer offset;
- pass raw file data to retrieve data outside of flatbuffers area
- get flag if Buffer is from outside of flatbuffers area
- show with '*' for Buffers that are outside of flatbuffers area
> [tfldump] Reivse to support Buffer offset

- compiler/luci/export/src/SerializedData.h
This will fix typo of disabled CTOR of SerializedGraphData.
> [luci/export] Fix typo of SerializedGraphData

- compiler/luci/pass/include/luci/CircleOptimizer.h
- compiler/luci/pass/include/luci/Pass/FuseMulWithFullyConnectedPass.h
- compiler/luci/pass/src/CircleOptimizer.cpp
- compiler/luci/pass/src/FuseMulWithFullyConnectedPass.cpp
- compiler/luci/pass/src/FuseMulWithFullyConnectedPass.test.cpp
This commit introduce FuseMulWithFullyConnectedPass which will fuse Mul to previous FullyConnected if possible.
> [luci/pass] Introduce FuseMulWithFullyConnectedPass

- runtime/onert/core/include/ir/train/Checkpoint.h
This commit adds the missing ir namespace to checkpoint header file.
Draft: #13561
> [onert] Add ir namespace to checkpoint header file

- compiler/circledump/driver/Driver.cpp
- compiler/circledump/include/circledump/Dump.h
- compiler/circledump/src/Dump.cpp
This will revise to support Buffer offset for file size > 2G.
> [circledump] Resive to support Buffer offset

- compute/cker/include/cker/Types.h
- compute/cker/include/cker/operation/reference/BinaryArithmeticOps.h
- compute/cker/src/Mul.test.cc
- runtime/onert/backend/cpu/ops/BinaryArithmeticLayer.cc
This commit updates cpu backend and cker to support INT64 BinaryArithmetic operations.
> [onert/cpu] Support INT64 BinaryArithemtic operation

- runtime/onert/api/nnfw/include/nnfw_experimental.h
- runtime/onert/api/nnfw/src/nnfw_api.cc
- runtime/onert/api/nnfw/src/nnfw_api_internal.cc
- runtime/onert/api/nnfw/src/nnfw_api_internal.h
This commit introduces checkpoint apis.
- nnfw_train_import_checkpoint
- nnfw_train_export_checkpoint
Related issue: #13670 
Draft: #13561
> [onert] Introduce checkpoint apis

- compiler/luci/service/include/luci/Service/CircleShapeInference.h
- compiler/luci/service/src/CircleShapeInferenceRule.cpp
- compiler/luci/service/src/Nodes/CircleConcatenation.cpp
This migrates concat Op's shape inference rule to sinf::Algorithm.
---
Related to: https://github.com/Samsung/ONE/issues/13730#issuecomment-2300311180
> [luci] Migrate concat shape inference rule

- compute/cker/src/Mul.test.cc
This commit add big integer mul cker unittest.
---
Related issue: https://github.com/Samsung/ONE/pull/13711/files#r1726028222
> [compute/cker] Add big integer mul test

- docs/runtime/training.md
- docs/runtime/training_cnn_on_mnist.md
This commit adds a guide document on how to train a simple CNN model on MNIST using ONERT.
Draft: #13695
> [doc] Add training CNN model on MNIST

- tests/tools/onert_train/src/args.cc
- tests/tools/onert_train/src/args.h
- tests/tools/onert_train/src/onert_train.cc
This commit introduces `--checkpoint` argument for loading a checkpoint file and `--export_checkpoint` argument for exporting weight and bias data of the model to checkpoint file.
Related issue: #13670 
Draft: #13561
> [onert_train] Introduce some arguments for checkpoint apis

- compiler/luci/service/include/luci/Service/CircleShapeInference.h
- compiler/luci/service/src/CircleShapeInferenceHelper.cpp
- compiler/luci/service/src/CircleShapeInferenceHelper.h
- compiler/luci/service/src/CircleShapeInferenceRule.cpp
- compiler/luci/service/src/Nodes/CircleDiv.cpp
- compiler/luci/service/src/Nodes/CircleDiv.test.cpp
This supports dynamic shape inference for DIV Op.
---
> [luci/service] Support DIV dynamic shape inference

- compiler/common-artifacts/exclude.lst
This adds Add_STR tests to exclude.lst.
---
Draft PR: https://github.com/Samsung/ONE/pull/13750
> [common-artifacts] Add Add_STR to exclude.lst

- compiler/luci/service/include/luci/Service/CircleShapeInference.h
- compiler/luci/service/src/CircleShapeInferenceRule.cpp
- compiler/luci/service/src/Nodes/CircleAdd.cpp
- compiler/luci/service/src/Nodes/CircleAdd.test.cpp
This supports dynamic shape inference for ADD Op.
---
Draft PR: https://github.com/Samsung/ONE/pull/13750
> [luci/service] Support ADD dynamic shape inference

- compiler/luci/import/include/luci/Importer.h
- compiler/luci/import/src/Importer.cpp
This will add importModule method with raw data/size arguments.
> [luci/import] Add importModule with raw data/size

- runtime/onert/core/src/backend/builtin/kernel/PermuteLayer.cc
- runtime/onert/core/src/backend/builtin/train/kernel/PermuteLayer.cc
- runtime/onert/core/src/exec/IPermuteFunction.cc
- runtime/onert/core/src/exec/IPermuteFunction.h
- runtime/onert/core/src/exec/IPermuteFunction.test.cc
This commit moves tensor layout check from permute function to permute layer constructor to prepare removing layout interface on tensor.
---
Draft: #13747
> [onert] Remove tensor layout check on permute function

- compiler/circle-inspect/driver/Driver.cpp
- compiler/circle-inspect/src/Dump.cpp
- compiler/circle-inspect/src/Dump.h
This will revise to support extended Buffer correctly show file size > 2G.
> [circle-inspect] Revise to support extended Buffer

- onert-micro/CMakeLists.txt
- do not exit if arm compiler not found since it causes lots of CI infra failure.
> [onert-micro] do not exit when arm compiler not found

- runtime/onert/core/src/backend/builtin/KernelGenerator.cc
- runtime/onert/core/src/backend/builtin/kernel/PermuteLayer.cc
- runtime/onert/core/src/backend/builtin/kernel/PermuteLayer.h
- runtime/onert/core/src/backend/builtin/kernel/WhileLayer.cc
- runtime/onert/core/src/backend/builtin/train/KernelGenerator.cc
- runtime/onert/core/src/backend/builtin/train/kernel/PermuteLayer.cc
- runtime/onert/core/src/backend/builtin/train/kernel/PermuteLayer.h
- runtime/onert/core/src/exec/IPermuteFunction.h
- runtime/onert/core/src/exec/MultiModelExecutors.cc
- runtime/onert/core/src/exec/SingleModelExecutors.cc
This commit update PermuteLayer constructor to use parameter to set permute type. 
By this commit, permute will not use tensor layout any more.
---
Draft: https://github.com/Samsung/ONE/pull/13747
> [onert] Use constructor paramter to set permute type

- runtime/onert/api/nnfw/src/nnfw_api_internal.cc
- runtime/onert/core/include/exporter/train/CheckpointExporter.h
- runtime/onert/core/src/exporter/train/CheckpointExporter.cc
This commit introduces CheckpointExporter class to store checkpoint file. Currently, only the header and footer data are saved.
Draft: #13561
> [onert] Introduce CheckpointExporter to store checkpoint file

- compiler/luci/export/src/SerializedData.cpp
- compiler/luci/export/src/SerializedData.h
This will add clear methods to CircleExportMetadata and SerializedModelData.
> [luci/export] Introduce clear methods

- compute/cker/include/cker/eigen/depthwise_conv_op.h
This commit fixes a casting warning in the analyzer.
> [cker] Fix casting warning

- compiler/luci/service/src/Nodes/CircleAdd.cpp
- compiler/luci/service/src/Nodes/CircleBatchMatMul.cpp
- compiler/luci/service/src/Nodes/CircleConcatenation.cpp
- compiler/luci/service/src/Nodes/CircleDiv.cpp
- compiler/luci/service/src/Nodes/CircleIfOut.cpp
- compiler/luci/service/src/Nodes/CircleSoftmax.cpp
This PR explicitly marks 'sinf namespace' for each node's sinf::Algorithm::visit() function.
* background : https://github.com/Samsung/ONE/pull/13780#discussion_r1734047594
> [luci/service] Add sinf namespace for sinf::Algorithm::visit()

- runtime/onert/core/include/ir/Coordinates.h
- runtime/onert/core/src/backend/builtin/kernel/PermuteLayer.cc
- runtime/onert/core/src/backend/builtin/kernel/PermuteLayer.h
- runtime/onert/core/src/exec/IPermuteFunction.cc
- runtime/onert/core/src/ir/Coordinates.cc
This commit changes appendPermuteTasks() and convertCoordinates() function to use permute type.
---
Draft: #13797
> [onert] Use permute type on permute task and coordinate conversion

- runtime/onert/core/src/compiler/train/pass/TrainableConstantInsertionPass.cc
- runtime/onert/core/src/ir/train/UseDefGenerator.cc
This commit updates to use getUses() return's reference explicitly.
> [onert] Use getUses() reference

- compiler/luci/pass/src/FuseAddWithTConvPass.cpp
- compiler/luci/pass/src/FuseAddWithTConvPass.test.cpp
This commit changes the order of searching for the pattern and adds tests for the pass.
> [luci/pass] Refactor FuseAddWithTConvPass

- compiler/luci/service/include/luci/Service/CircleShapeInference.h
- compiler/luci/service/src/CircleShapeInferenceRule.cpp
- compiler/luci/service/src/Nodes/CircleMul.cpp
- compiler/luci/service/src/Nodes/CircleMul.test.cpp
This supports dynamic shape inference for MUL.
---
Related to: #13697 
Draft PR: #13777
> [luci/service] Support MUL dynamic shape inference

- infra/debian/runtime/rules
- infra/nnfw/cmake/CfgOptionFlags.cmake
- infra/nnfw/cmake/options/options_aarch64-android.cmake
- infra/nnfw/cmake/options/options_aarch64-tizen.cmake
- infra/nnfw/cmake/options/options_armv7hl-tizen.cmake
- infra/nnfw/cmake/options/options_armv7l-tizen.cmake
- infra/nnfw/cmake/options/options_i686-tizen.cmake
- infra/nnfw/cmake/options/options_riscv64-tizen.cmake
- infra/nnfw/cmake/options/options_x86_64-tizen.cmake
This commit disables logging runtime build in contrib directory as default.
> [onert/contrib] Disable logging runtime build as default

- compiler/luci/export/src/CircleExporterUtils.cpp
- compiler/luci/export/src/CircleExporterUtils.h
- compiler/luci/export/src/CircleTensorExporter.cpp
- compiler/luci/export/src/CircleTensorExporter.h
This will introduce clearExportInfo method and related method
to clear temporary information added to the graph.
> [luci/export] Introduce clearExportInfo and related

- compiler/circle2circle/src/Circle2Circle.cpp
This commit revises driver script for static analysis tool.
Related: #13806
> [circle2circle] Revise driver script

- compiler/luci/service/include/luci/Service/CircleShapeInference.h
- compiler/luci/service/src/CircleShapeInferenceRule.cpp
- compiler/luci/service/src/Nodes/CircleQuantize.cpp
- compiler/luci/service/src/Nodes/CircleQuantize.test.cpp
When testing dynamic shape inference, the original quantize operation successfully handles it.
I have migrated the inference code and modified shape_get function to circle_shape
draft: https://github.com/Samsung/ONE/pull/13779
first-pr: https://github.com/Samsung/ONE/pull/13794 (I fail to modify first commit message.. so I create new pull-request)
> [luci/service] Migrate Quantize shape inference rule to sinf::Algorithm

- docs/release/1.29/index.rst
- docs/release/1.29/release-note_1.29.0.md
This commit is a release note for 1.29.0.
> Release note 1.29.0

- compiler/tflchef/core/src/ModelChef.cpp
This commit adds const reference to tensor variable.
> [tflchef] Add const reference

- runtime/onert/core/src/exec/IPermuteFunction.test.cc
This commit simplifies IPermuteFunction unittest's MockUpLayer usage.
---
Draft: #13797
> [onert] Simplify IPermuteFunction unittest

- runtime/libs/circle-schema/include/circle_schema_generated.h
This commit updates `circle_schema_generated.h` to support block quantization type Q4_0, Q4_1, Q8_0, Q8_1.
---
Related issue: #13835 #13743
> [onert] Update circle schema generated header for block quantization

- runtime/onert/backend/acl_common/IACLTensor.cc
- runtime/onert/backend/acl_common/IACLTensor.h
- runtime/onert/backend/cpu/KernelGenerator.cc
- runtime/onert/backend/cpu/ops/OperationUtils.cc
- runtime/onert/backend/cpu/ops/OperationUtils.h
- runtime/onert/backend/ruy/KernelGenerator.cc
- runtime/onert/backend/ruy/ops/OperationUtils.h
- runtime/onert/backend/train/KernelGenerator.cc
- runtime/onert/backend/train/ops/OperationUtils.cc
- runtime/onert/backend/train/ops/PoolLayer.cc
- runtime/onert/backend/train/optimizer/Optimizers.test.cc
- runtime/onert/backend/trix/Convert.h
- runtime/onert/backend/xnnpack/KernelGenerator.cc
- runtime/onert/backend/xnnpack/ops/ConvolutionLayer.cc
- runtime/onert/backend/xnnpack/ops/DepthwiseConvolutionLayer.cc
- runtime/onert/backend/xnnpack/ops/FullyConnectedLayer.cc
- runtime/onert/core/include/backend/ITensor.h
- runtime/onert/core/include/backend/basic/Tensor.h
- runtime/onert/core/include/backend/basic/train/TrainableTensor.h
- runtime/onert/core/src/backend/builtin/IOTensor.cc
- runtime/onert/core/src/backend/builtin/IOTensor.h
- runtime/onert/core/src/backend/builtin/UserTensor.h
- runtime/onert/core/src/backend/builtin/kernel/PermuteLayer.cc
- runtime/onert/core/src/exec/EdgeTensor.h
- runtime/onert/core/src/exec/IPermuteFunction.cc
- runtime/onert/core/src/exec/IPermuteFunction.h
- runtime/onert/core/src/exec/IPermuteFunction.test.cc
- runtime/onert/core/src/exec/feature/MockTensor.test.h
- runtime/onert/core/src/exec/feature/nchw/Reader.h
- runtime/onert/core/src/exec/feature/nhwc/Reader.h
This commit removes layout access from ITensor and derived classes. 
Tensor classes for external buffer (IOTensor, UserTensor, EdgeTensor) and unittest remains layout information.
---
Draft: #13797
> [onert] Remove layout in ITensor

- runtime/onert/api/nnfw/src/nnfw_api_internal.cc
- runtime/onert/core/include/loader/train/CheckpointLoader.h
- runtime/onert/core/src/loader/train/CheckpointLoader.cc
This commit introduces CheckpointLoader class. It loads the checkpoint file data and updates the tensor data and training information.
Draft: #13561
> [onert] Introduce CheckpointLoader to load checkpoint file

- compiler/circle-opselector/src/ModuleIO.cpp
This will tidy unused header include.
> [circle-opselector] Tidy unused header

- compiler/luci/import/include/luci/ImporterEx.h
- compiler/luci/import/src/ImporterEx.cpp
This will revise ImportEx ctro with graph builder source and new importModule method.
> [luci/import] Revise ImportEx

- runtime/onert/odc/Embedder.cc
This commit removes unused header include in Embedder.cc
> [onert] Remove unused header include in Embedder

- runtime/onert/backend/train/LayerScopeTensorIndex.h
- runtime/onert/core/include/backend/train/LayerScopeTensor.h
This PR renames ExtraTensor to LayerSocpeTensor.
* background : https://github.com/Samsung/ONE/pull/13605#issuecomment-2274478201
> [onert] Rename ExtraTensor to LayerScopeTensor

- Makefile.template
- packaging/nnfw.spec
This commit updates build scripts to copy included headers to overlay for luci link.
---
It will build fail on #13850
> [infra/onert] Copy included headers to overlay

- compiler/luci/export/src/CircleExporterImpl.cpp
- compiler/luci/export/src/CircleExporterImpl.h
This will split exportModule method to prepare two pass execution.
> [luci/export] Split exportModule method

- compiler/luci/import/src/Nodes/CircleConst.cpp
This will split variables in Const build method to prepare extended Buffer support.
> [luci/import] Split variables in Const build

- compiler/luci/export/src/CircleExporterUtils.h
This will introduce check_size_limit method to check limit of flatbuffers size.
> [luci/export] Introduce check_size_limit

- compiler/arser/include/arser/arser.h
This commit fixes build fail in gcc 13 by adding missing include.
> [arser] Fix build fail on gcc 13

- runtime/onert/core/include/backend/train/LayerScopeTensor.h
This PR adds lifetime info to the LayerScopeTensor. Lifetime info will be used to plan and allocate buffer for LayerScopeTensor.
related : https://github.com/Samsung/ONE/issues/13282 
> [onert] Add lifetime enum to LayerScopeTensor

- compiler/luci/export/src/CircleTensorExporter.cpp
This will revise encodeOpBufferByDType for extended Buffer mode.
- store buffer content to extra map instead of creating Buffer
- return fake Buffer with offset/size of 1 and 1.
> [luci/export] Revise encodeOpBufferByDType for extended Buffer

- compiler/luci/export/src/CircleTensorExporter.cpp
This will clear model data in prepareModelData method.
- this is to clear before second pass
> [luci/export] Clear model data in prepareModelData

- compiler/fme-detect/driver/Driver.cpp
This will tidy not used header include.
> [fme-detect] Tidy not used header include

- compiler/fme-apply/driver/Driver.cpp
This will tidy not used header include.
> [fme-apply] Tidy not used header include

- compiler/luci/export/src/CircleExporterImpl.cpp
This will revise getBufferPointer() and getBufferSize() methods to handle extended Buffer contents.
> [luci/export] Revise getBuffer methods

- compiler/luci/import/include/luci/Importer.h
- compiler/luci/import/src/Importer.cpp
This will revise importModule method with circle::Module as
- make it private to prevent future isses with large model
- add some guards
- only call reader with file data and size
> [luci/import] Revise importModule method

- compiler/luci/pass/src/FuseMulWithDivPass.cpp
This will fix comment typo in FuseMulWithDivPass.
> [luci/pass] Fix typo in FuseMulWithDivPass

- docs/howto/how-to-cross-build-runtime-for-arm.md
- tools/cross/install_rootfs.sh
This commit updates rootfs script and document for ubuntu 24.04. 
Ubuntu 24.04 does not support `qemu` package any more.
> [onert/cross] Update rootfs script and document

- compiler/luci/import/src/Nodes/CircleConst.cpp
This will fix CircleConstNodeBuilder::build message for typo and
add 'CircleConst:' prefix to indicate error origination.
> [luci/import] Fix CircleConstNodeBuilder::build message

- compiler/one-cmds/onelib/utils.py
This will introduce run_ret method in utils which will return with process return code.
> [one-cmds] Introduce run_ret method in utils

- runtime/onert/core/include/ir/OperandInfo.h
- runtime/onert/core/src/ir/DataType.cc
- runtime/onert/core/src/ir/OperandInfo.cc
- runtime/onert/core/src/ir/OperandInfo.test.cc
This commit update total_size() method to calculate block quantization type operand size.
---
Related issue: #13742
Draft: #13693
> [onert] Support block quantization operand size calculation

- runtime/onert/core/src/loader/BaseLoader.h
- runtime/onert/core/src/loader/CircleLoader.cc
This commit updates CircleLoader and BaseLoader to support block quantization.
---
Related issue: #13835
> [onert] Support block quantization in CircleLoader

- runtime/onert/core/src/exporter/train/CheckpointExporter.cc
This commit exports tensor and optimizer data to the checkpoint file. It introduces DataBuffer to manage checkpoint data buffer.
Draft: #13561
> [onert] Export tensor and optimizer data to the checkpoint file

- runtime/onert/backend/train/DisposableTensorIndex.h
- runtime/onert/backend/train/MemoryPlanner.cc
- runtime/onert/backend/train/MemoryPlanner.h
- runtime/onert/backend/train/MemoryPlanner.test.cc
- runtime/onert/backend/train/MemoryPlannerFactory.cc
This PR templatize memory planners(Bump, FirstFit, WIC) in train backend. This memory planners currently only used for DisposableTensor, but it will be also used for LayerScopeTensor.
> [onert] Templatize memory planners in train backend

- runtime/onert/core/src/compiler/train/pass/TrainableConstantInsertionPass.cc
- runtime/onert/core/src/ir/train/UseDefGenerator.cc
This commit fixes the problem that occurs in loop traversal due to change of list by using copy instead of reference.
> [onert] Use getUses() copy instead of reference

- onert-micro/onert-micro/src/execute/kernels/Dequantize.cpp
- onert-micro/onert-micro/src/execute/kernels/MathCommon.cpp
- onert-micro/onert-micro/src/execute/kernels/Quantize.cpp
- Use exec SISO header for quantize/dequantize kernel
> [onert-micro] use exec sisoheader for quantize kernels

- compiler/one-cmds/tests/one-import-onnx_ext_002.test
- compiler/one-cmds/tests/one-import-onnx_ext_003.test
- compiler/one-cmds/tests/one-import-onnx_ext_004.test
- compiler/one-cmds/tests/one-import-onnx_ext_neg_001.test
- compiler/one-cmds/tests/prepare_test_materials.sh
This will add more tests for one-import-onnx-ext.
- new material download is also added in prepare_test_materials.sh
> [one-cmds] Add more tests for one-import-onnx-ext

- compiler/luci/service/include/luci/Service/CircleShapeInference.h
- compiler/luci/service/src/CircleShapeInferenceRule.cpp
- compiler/luci/service/src/Nodes/CircleNeg.cpp
- compiler/luci/service/src/Nodes/CircleNeg.test.cpp
This commit migrate Neg shape inference rule to sinf::Algorithm.
> [luci/service] Migrate Neg shape inference rule to sinf::Algorithm

- res/TensorFlowLiteRecipes/Net_Gather_SparseToDense_AddV2_000/test.recipe
This PR updates operand name of SparseToDense in Net_Gather_SparseToDense_AddV2_000.recipe.
> [res] Update operand name of Gather_SparseToDense_AddV2 recipe

- compiler/luci/export/src/CircleExporterUtils.h
This commit resolves analyzer's overflow warning.
> [luci] Fix overflow warning

- compiler/one-cmds/how-to-use-one-commands.txt
- compiler/one-cmds/onelib/constant.py
This commit adds one-cmd option for RemoveUnnecessaryCastPass.
> [one-cmds] Add an option for RemoveUnnecessaryCastPass

- nnpackage/schema/circle_schema.fbs
This commit updates circle schema to 0.9
- Introduce GGML_Q{X}_{Y} types for ggml block quantization
- Introduce weight compression type and option
---
Related issue: #13743 #13521
> [nnpackage] Update circle schema

- runtime/onert/core/src/exporter/train/CheckpointExporter.cc
- runtime/onert/core/src/loader/train/CheckpointLoader.cc
This commit fixes some warnings by static analyzer
- Implicit casting signed integer to explicit casting in loader
- Initialize fields in exporter
> [onert] Fix warnings in checkpoint loader and exporter

- runtime/libs/circle-schema/include/circle_schema_generated.h
- runtime/onert/core/src/loader/CircleLoader.cc
This commit updates circle schema generated header to apply updated block quantization naming.
> [onert] Apply updated quant name to schema header

- runtime/onert/core/src/loader/train/CheckpointLoader.cc
This commit loads tensor and optimizer data from the checkpoint file.
Draft: #13561
> [onert] Load tensor and optimizer data from the checkpoint file

- runtime/onert/api/nnapi/CMakeLists.txt
- runtime/onert/api/nnapi/compilation.cc
- runtime/onert/api/nnapi/execution.cc
- runtime/onert/api/nnapi/model.cc
- tests/nnapi/CMakeLists.txt
- tests/nnapi/include/NeuralNetworksWrapper.h
This commit changes NNAPI library to static and rename to 'onert-nnapi'.
It includes empty NNAPI function to resolve link error.
---
Related issue: #13816
> [onert] Change NNAPI library type

- infra/nnfw/cmake/packages/FlatBuffers-23.5.26/FlatBuffersConfig.cmake
This commit updates cmake script for flatbuffer library to make static library explicitly. 
It prevents build regression from sometimes building shared library.
> [infra/onert] Make flatbuffers library static explicitly

- compiler/fme-apply/src/RandomString.h
This commit resolves build fail on gcc 13 by adding missing include.
> [fme-apply] Fix build fail on gcc 13

- runtime/contrib/android/api/Prebuilt.mk
This commit updates core library path for packaging.
---
Path is changed by #13472
> [onert/android] Update lib path

- compute/cker/include/cker/eigen/xent_op.h
- compute/cker/include/cker/operation/Helper/Tensor.h
- compute/cker/include/cker/train/operation/Loss.h
- compute/cker/src/train/Loss.test.cc
This commit introduces CategoricalCrossEntropyWithLogits that computes cce loss value and gradient with nomalization(softmax).
> [cker] Introduce CategoricalCrossEntropyWithLogits

- onert-micro/training-configure-tool/src/TrainingDriverHandler.cpp
This commit fixes bug in TrainingDriverHandler.
ONE-DCO-1.0-Signed-off-by: Jungwoo Lee <jade.jw.lee@samsung.com>
> [onert-micro] Fix TrainingDriverHandler

- compiler/luci/service/src/CircleShapeInferenceHelper.cpp
- compiler/luci/service/src/CircleShapeInferenceHelper.h
- compiler/luci/service/src/Nodes/CirclePad.cpp
- compiler/luci/service/src/Nodes/CirclePad.test.cpp
This PR supports infer shape of pad operation with dynamic paddings.
> [luci/service] Support shape inference for non-const paddings

- compute/cker/include/cker/eigen/xent_op.h
- compute/cker/include/cker/train/operation/Loss.h
- compute/cker/src/train/Loss.test.cc
- runtime/onert/backend/train/ops/LossCategoricalCrossentropyLayer.cc
This commit fixes computing CCE Gradients.
- SUM_OVER_BATCH_SIZE : computes CCE gradients with sum over batch size
- SUM : computes CCE gradients with sum for each batch as it is before
> [cker] Fix computing CCE Gradient

- nnpackage/schema/circle_schema.fbs
- res/CircleSchema/0.9/circle_schema.fbs
To support RmsNorm
- RmsNorm op added to circle schema (nnpackage and res)
ONE-DCO-1.0-Signed-off-by: seockho.kim [seockho.kim@samsung.com](mailto:seockho.kim@samsung.com)
> [nnpackage,res] Add RmsNorm op to circle schema

- compiler/fme-detect/src/EqualizePatternFinder.cpp
- compiler/fme-detect/src/EqualizePatternFinder.test.cpp
This commit revises the way it finds equalize patterns.
1. Add more ops for fusubility.
2. Remove "shift" related logic.
3. Pattern's front and back are written without forwarded ops. 
Draft: #13659
> [fme-detect] Revise the way it finds patterns

- compute/cker/include/cker/train/operation/Loss.h
This commit fixes a wrong comment.
- sparse shape -> broadcast shape
> [cker] Fix wrong comment

- runtime/onert/backend/train/MemoryManager.cc
- runtime/onert/backend/train/MemoryManager.h
- runtime/onert/backend/train/MemoryPlannerFactory.cc
- runtime/onert/backend/train/MemoryPlannerFactory.h
This PR templatize memory planner factory in train backend. MemoryPlannerFactory currently used for DisposableTensorIndex, but it will be also used for LayerScopeTensorIndex.
> [onert/backend] Templatize MemoryPlannerFactory in train

- runtime/onert/core/include/backend/train/LayerScopeTensor.h
- runtime/onert/core/include/exec/train/ITrainableFunction.h
This PR adds registerLayerScopeTensors to ITrainableFunction. 'registerLayerScopeTensors` is to register LayerScopeTensor into TensorReigstry.
> [onert] Add registerLayerScopeTensors to ITrainableFuntion

- nnpackage/schema/circle_schema.fbs
- res/CircleSchema/0.9/circle_schema.fbs
This commit removes "activation function" from RmsNorm parameter schema.
> [nnpackage, res] Removed activation function from RmsNorm schema

- compiler/luci/service/include/luci/Service/CircleShapeInference.h
- compiler/luci/service/src/CircleShapeInferenceRule.cpp
- compiler/luci/service/src/Nodes/CircleRange.cpp
- compiler/luci/service/src/Nodes/CircleRange.test.cpp
This commit migrate Range shape inference rule to sinf::Algorithm.
Todo : support shape inference for non-const param of Range
ONE-DCO-1.0-Signed-off-by: Bokyeong Lee <kyeong8139@gmail.com>
> [luci/service] migrate Range shape inference rule to sinf::Algorithm

- compiler/fme-apply/src/EqualizePattern.h
- compiler/fme-apply/src/EqualizePatternCheck.cpp
- compiler/fme-apply/src/EqualizePatternCheck.test.cpp
- compiler/fme-apply/src/EqualizePatternRead.cpp
- compiler/fme-apply/src/EqualizePatternRead.test.cpp
- compiler/fme-apply/src/FMEqualizer.cpp
- compiler/fme-apply/src/FMEqualizer.h
- compiler/fme-apply/src/InsertScaleShift.cpp
- compiler/fme-apply/src/InsertScaleShift.h
- compiler/fme-apply/src/InsertScaleShift.test.cpp
- compiler/fme-apply/src/Support.Cast.cpp
- compiler/fme-apply/src/Support.Cast.h
- compiler/fme-apply/src/Support.Cast.test.cpp
- compiler/fme-apply/src/Support.Misc.cpp
- compiler/fme-apply/src/Support.Misc.h
- compiler/fme-apply/src/Support.Misc.test.cpp
- compiler/fme-apply/src/pass/FusePostScalePass.cpp
- compiler/fme-apply/src/pass/FusePostScalePass.h
- compiler/fme-apply/src/pass/FusePostScalePass.test.cpp
- compiler/fme-apply/src/pass/FusePreScalePass.cpp
- compiler/fme-apply/src/pass/FusePreScalePass.h
- compiler/fme-apply/src/pass/FusePreScalePass.test.cpp
This commit revises overall codes.
- Remove shift and Add act_scale.
- Add smooth quant algorithm.
- Find front node in person instead of forwarding scale node.
- Support more ops in fusion passes. 
Draft: #13659
> [fme-apply] Revise overall codes

- compiler/luci/service/src/Nodes/CircleStridedSlice.cpp
- compiler/luci/service/src/Nodes/CircleStridedSlice.test.cpp
This supports dynamic shape inference for StridedSlice op,
in case where the input node is dynamic or the begin/end nodes are not const.
> [luci/service] Support StridedSlice dynamic shape inference

- packaging/nnfw.pc.in
- runtime/contrib/android/api/Prebuilt.mk
- runtime/onert/api/nnfw/CMakeLists.txt
This commit renames onert library name from `libnnfw-dev.so` to `libonert.so`.
> [infra/onert] Rename onert library name

- compiler/luci/service/src/Nodes/CircleRange.cpp
This commit add comment about shape inference condition for Range.
Related: https://github.com/Samsung/ONE/pull/13987#discussion_r1753625153
> [luci/service] Add Assert about Shape Inference Condition for Range 

- compiler/fm-equalize-value-py-test/CMakeLists.txt
- compiler/fm-equalize-value-py-test/README.md
- compiler/fm-equalize-value-py-test/conftest.py
- compiler/fm-equalize-value-py-test/requires.cmake
- compiler/fm-equalize-value-py-test/test.lst
- compiler/fm-equalize-value-py-test/test_luci_eval.py
This commit introduces fm-equalize-value-py-test to ONE.
Draft: #13659
> [fm-equalize-value-py-test] Introduce tests

- compiler/luci/service/src/Nodes/CircleRange.cpp
- compiler/luci/service/src/Nodes/CircleRange.test.cpp
This commit Range op support shape inference for non-const param.
ONE-DCO-1.0-Signed-off-by: bokyeong lee <kyeong8139@gmail.com>
> [luci/service] Support Range op Shape Inference for Non-const Param 

- compiler/luci/service/include/luci/Service/CircleShapeInference.h
- compiler/luci/service/src/CircleShapeInferenceRule.cpp
- compiler/luci/service/src/Nodes/CircleLogistic.cpp
This commit migrates logistic operation to sinf::Algorithm
Related: https://github.com/Samsung/ONE/issues/13697
Draft: https://github.com/Samsung/ONE/pull/13992
ONE-DCO-1.0-Signed-off-by: Jongwon Yang <yjw963@gmail.com>
> [luci/service] Migrate logistic op to sinf::Algorithm

- compiler/one-cmds/tests/one-codegen_006.test
- compiler/one-cmds/tests/one-codegen_010.test
- compiler/one-cmds/tests/one-codegen_011.test
- compiler/one-cmds/tests/one-profile_006.test
- compiler/one-cmds/tests/one-profile_010.test
- compiler/one-cmds/tests/one-profile_011.test
- compiler/one-cmds/tests/onecc_057.test
- compiler/one-cmds/tests/onecc_neg_038.test
This commit adds missing clean envir in test.
> [one-cmds] Add missing clean envir in tests

- compiler/common-artifacts/exclude.lst
This commit is to exclude RmsNorm test until it's fully applied. 
It will be reverted once RmsNorm is fully applied.
> [common-artifacts] Exclude RmsNorm test

- compiler/luci/service/src/CircleShapeInferenceHelper.cpp
- compiler/luci/service/src/Nodes/CirclePad.test.cpp
This PR modifies the pad operation to throw exceptions for invalid paddings, replacing the previous assert conditions.
> [luci/service] Change assert to throw exception for invalid paddings

- compiler/luci/import/include/luci/Import/Nodes.h
- compiler/luci/import/include/luci/Import/Nodes/CircleRmsNorm.h
- compiler/luci/import/src/GraphBuilderRegistry.cpp
- compiler/luci/import/src/Nodes/CircleRmsNorm.cpp
This commit is to support RmsNorm operation in luci-import.
> [luci/import] Support RmsNorm operation

- runtime/onert/backend/acl_common/Convert.cc
- runtime/onert/backend/acl_common/Convert.h
- runtime/onert/backend/trix/Convert.cc
- runtime/onert/backend/trix/Convert.h
This commit removes unused backend layout helper functions.
> [onert] Remove backend layout helper

- runtime/onert/backend/train/MemoryManager.cc
- runtime/onert/backend/train/MemoryManager.h
- runtime/onert/backend/train/TensorManager.h
This PR introduces LayerScopeMemoryManager.
This Manager will be added to TensorManager and used to allocate LayerScopeTensors.
>  [onert/backend] Introduce LayerScopeMemoryManager

- runtime/onert/backend/train/MemoryPlanner.test.cc
This PR adds test ceases for LayerScopeTensorIndex based MemoryPlanner.
related : https://github.com/Samsung/ONE/pull/13892#pullrequestreview-2278797746
> [onert/backend] Add tests for LayerScopeTensorIndex planner

- tests/nnfw_api/CMakeLists.txt
- tests/nnfw_api/lib/common.cc
- tests/nnfw_api/lib/common.h
This commit introduces helper function to make block quantized buffer from float data vector.
---
Draft: #13956
Related issue: #13908
> [onert/test] Introduce block quantized buffer helper

- compiler/common-artifacts/exclude.lst
This commit is to exclude RmsNorm optimization test until it's fully applied. 
It will be reverted once RmsNorm is fully applied.
> [common-artifacts] Exclude RmsNorm optimization test

- compiler/luci/service/src/Nodes/CircleReshape.cpp
This commit improves handling `CircleConst` as the `shape` for the reshape operation.
- Use `known` explicitly instead of `static_cast` which can cause overflow.
Draft: https://github.com/Samsung/ONE/pull/13999, https://github.com/Samsung/ONE/pull/14034
Related: https://github.com/Samsung/ONE/issues/13927
ONE-DCO-1.0-Signed-off-by: Jongwon Yang <yjw963@gmail.com>
> [luci/service] Enhance handling CircleConst as reshape's shape

- compiler/luci/pass/src/QuantizeWeights.cpp
- compiler/luci/pass/src/QuantizeWeights.h
This commit adds RmsNorm to QuantizeWeights.
> [luci/pass] Add RmsNorm to QuantizeWeights

- compiler/luci/pass/src/QuantizePreCheckerPass.cpp
- compiler/luci/pass/src/QuantizePreCheckerPass.test.cpp
This commit adds RmsNorm to QuantizePreChecker pass.
> [luci/pass] Add RmsNorm to QuantizePreChecker pass

- runtime/onert/backend/train/MemoryPlanner.test.cc
This PR fix test names in MemoryPlanner.test.cc.
It makes 'neg' keywords resides in prefix of test names.
> [onert/backend] Fix test names in MemoryPlanner.test.cc

- compiler/luci/pass/src/QuantizeActivation.h
This commit adds to skip RmsNorm in QuantizeActivation.
> [luci/pass] Add to skip RmsNorm in QuantizeActivation

- compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
This commit adds RmsNorm to QuantizeWithMinMax pass.
> [luci/pass] Add RmsNorm to QuantizeWithMinMax pass

- compiler/luci/pass/src/VerifyQuantizedNodeType.cpp
- compiler/luci/pass/src/VerifyQuantizedNodeType.h
This commit adds CircleRmsNorm to VerifyQuantizedNodeType.
> [luci/pass] Add RmsNorm to VerifyQuantizedNodeType

- compiler/luci/pass/src/VerifyQuantizedNodeGranularity.h
This commit adds CircleRmsNorm to VerifyQuantizedNodeGranularity.
> [luci/pass] Add RmsNorm to VerifyQuantizedNodeGranularity

- compiler/luci/pass/src/ConvertToFakeQuantizedModelPass.cpp
This commit adds CircleRmsNorm to ConvertToFakeQuantizedModel pass.
> [luci/pass] Add RmsNorm to ConvertToFakeQuantizedModel pass

- res/CircleRecipes/RmsNorm_000/test.recipe
- res/TensorFlowLiteRecipes/Net_RmsNorm_000/test.recipe
- res/TensorFlowLiteRecipes/Net_RmsNorm_000/test.rule
This commit adds RmsNorm test recipe in CircleRecipes/TFLiteRecipes.
> [res] CircleRecipes and TFLiteRecipes added for RmsNorm

- compiler/luci/partition/include/luci/ConnectNode.h
- compiler/luci/partition/src/Nodes/CircleRmsNorm.cpp
- compiler/luci/partition/src/Nodes/CircleRmsNorm.test.cpp
This commit supports RmsNorm operation in luci partition.
> [luci/partition] Support RmsNorm operation

- compiler/luci/pass/include/luci/CircleOptimizer.h
- compiler/luci/pass/include/luci/Pass/FuseRmsNormPass.h
- compiler/luci/pass/src/CircleOptimizer.cpp
- compiler/luci/pass/src/FuseRmsNormPass.cpp
- compiler/luci/pass/src/FuseRmsNormPass.test.cpp
This commit supports RmsNorm fuse in luci pass.
> [luci/pass] Support RmsNorm Fuse

- compiler/logo/src/Passes/RemoveDeadNodeWithQueryPass.cpp
This commit fixes logic in RemoveDeadNodeWithQueryPass.
Related : https://github.com/Samsung/ONE/issues/13863
Draft : https://github.com/Samsung/ONE/pull/14051
> [logo/pass] Fix RemoveDeadNodeWithQueryPass

- compiler/circledump/src/OpPrinter.cpp
This commit supports RmsNorm operation in circledump
> [circledump] Add RmsNorm to circledump

- runtime/onert/backend/train/ops/LossLayer.cc
This commit initializes loss reduction type on LossLayer default constructor.
> [onert] Initialize loss reduction type

- .github/workflows/check-format.yml
This commit changes format check runner to ubuntu 24.04. 
It supports pre-installed clang-format-16.
> [infra/github] Change format check runner

- compiler/luci/export/src/CircleBuiltinTypesExtractor.h
- compiler/luci/export/src/CircleOps.lst
This commit supports RmsNorm operation in luci export
> [luci/export] Add RmsNorm to luci export

- nnpackage/schema/circle_schema.fbs
- res/CircleSchema/0.9/circle_schema.fbs
This commit updates circle schema for RoPE op
draft : #13978
issue : #13972
> [nnpackage,res] support RoPE operation

- compiler/luci/service/src/Nodes/CircleReshape.cpp
- compiler/luci/service/src/Nodes/CircleReshape.test.cpp
This commit prevents shape inference when the reshape tensor's dimensions are not fully known.
Related: https://github.com/Samsung/ONE/issues/13927
Draft: https://github.com/Samsung/ONE/pull/13999
ONE-DCO-1.0-Signed-off-by: Jongwon Yang <yjw963@gmail.com>
> [luci/service] Fix dynamic shape inference for reshape operation

- runtime/onert/backend/train/TensorRegistry.h
This PR adds LayerScopeTensors into TensorRegistry.
> [onert/backend] Add LayerScopeTensors into TensorRegistry

- runtime/onert/core/src/ir/OperationValidator.cc
- runtime/onert/core/src/ir/OperationValidator.h
This commit adds operation validation for Gather to check operand data type.
> [onert] Check Gather operand data type

- compiler/circle2circle/src/Circle2Circle.cpp
This commit adds 'fuse_rmsnorm' option to circle2circle.
> [circle2circle] Add fuse_rmsnorm option

- compiler/luci/import/src/GraphBuilderRegistry.cpp
This commit modifies RmsNorm comment to align to the schema
> [luci/import] Fix invalid comment of RmsNorm

- compiler/common-artifacts/exclude.lst
This commit is to exclude rope test until it's fully supported
> [common-artifacts] Exclude rope test

- compiler/luci-interpreter/src/core/KernelParams.h
- compiler/luci-interpreter/src/kernels/RmsNorm.cpp
- compiler/luci-interpreter/src/kernels/RmsNorm.h
- compiler/luci-interpreter/src/kernels/RmsNorm.test.cpp
This commit support RmsNorm operation kernel in luci-interpreter.
> [luci-interpreter] Add RmsNorm kernel
