- onert-micro/onert-micro/include/execute/OMUtils.h
- onert-micro/onert-micro/include/execute/kernels/PoolingCommon.h
- onert-micro/onert-micro/src/execute/CMakeLists.txt
- onert-micro/onert-micro/src/execute/OMUtils.cpp
- onert-micro/onert-micro/src/execute/kernels/Add.cpp
- onert-micro/onert-micro/src/execute/kernels/AveragePool2D.cpp
- onert-micro/onert-micro/src/execute/kernels/L2Pool2D.cpp
- onert-micro/onert-micro/src/execute/kernels/MaxPool2D.cpp
- onert-micro/onert-micro/src/execute/kernels/Mul.cpp
- onert-micro/onert-micro/src/execute/kernels/PoolingCommon.cpp
This pr reduces code duplication for pooling execute part and for Mul and Add ops.
> [onert-micro] Reduce code duplication

- compiler/one-cmds/dummy-driver/src/dummy-compile.cpp
- compiler/one-cmds/dummy-driver/src/dummy-compiler.cpp
- compiler/one-cmds/one-codegen
- compiler/one-cmds/one-profile
- compiler/one-cmds/onelib/argumentparse.py
- compiler/one-cmds/tests/onecc_066.cfg
- compiler/one-cmds/tests/onecc_066.ini
- compiler/one-cmds/tests/onecc_066.py
- compiler/one-cmds/tests/onecc_066.test
This commit adds warning messages on target related process.
> [one-cmds] Add warning message on target related process

- runtime/onert/api/nnfw/src/nnfw_api_internal.cc
This commit updates status and model path after quantize and codegen because these APIs loads updated model. 
It will help to support full quantization after minmax data collection.
> [onert] Update status on quantize and codegen

- tools/circle_plus_gen/README.md
- tools/circle_plus_gen/example/tparam_sgd_scce.json
- tools/circle_plus_gen/example/train_tparam.json
- tools/circle_plus_gen/how-to-write-tparam-json.md
- tools/circle_plus_gen/lib/json_parser.py
- tools/circle_plus_gen/lib/train_param.py
- tools/circle_plus_gen/main.py
This PR supports fineTuning field in input json file.
related : https://github.com/Samsung/ONE/issues/13099
> [tools/circle_plus_gen] support fine-tuning feature

- .ahub/tcchecker-tca/config.yaml
This commit fixes tc checker config file.
> [ahub] Fix tc checker config

- compiler/one-cmds/onelib/argumentparse.py
This commit adds comments about command schema.
> [one-cmds] Add comments about command schema

- runtime/onert/odc/MinMaxReader.cc
This commit add num_run, num_op, num_input overflow check in MinMaxReader.
---
For clearing code analysis defect warning
> [onert] Add overflow check in MinMaxReader

- onert-micro/onert-micro/include/onert-micro.h
- onert-micro/onert-micro/src/CMakeLists.txt
- onert-micro/onert-micro/src/api/CMakeLists.txt
- onert-micro/onert-micro/src/api/onert-micro.cpp
- onert-micro api and its implementation
> [onert-micro] onert-micro dev library

- docs/release/1.27/index.rst
- docs/release/1.27/release-note-1.27.0.md
This commit is a release note for 1.27.0.
Related: #13283
> Release note 1.27.0

- onert-micro/onert-micro/include/execute/kernels/ReluCommon.h
- onert-micro/onert-micro/src/execute/CMakeLists.txt
- onert-micro/onert-micro/src/execute/kernels/LeakyRelu.cpp
- onert-micro/onert-micro/src/execute/kernels/Relu6.cpp
- onert-micro/onert-micro/src/execute/kernels/ReluCommon.cpp
- onert-micro/onert-micro/src/import/kernels/Relu6.cpp
This pr reduces code duplication for Relu.
for #13272
> [onert-micro] Reduce Relu code duplication

- onert-micro/onert-micro/include/execute/kernels/SpacesBatchesNDCommon.h
- onert-micro/onert-micro/include/import/helpers/OMSpacesBatchesNDCommon.h
- onert-micro/onert-micro/include/pal/common/PALSpaceToBatchNDCommon.h
- onert-micro/onert-micro/src/execute/CMakeLists.txt
- onert-micro/onert-micro/src/execute/kernels/BatchToSpaceND.cpp
- onert-micro/onert-micro/src/execute/kernels/SpaceToBatchND.cpp
- onert-micro/onert-micro/src/execute/kernels/SpacesBatchesNDCommon.cpp
- onert-micro/onert-micro/src/import/CMakeLists.txt
- onert-micro/onert-micro/src/import/helpers/OMSpacesBatchesNDCommon.cpp
- onert-micro/onert-micro/src/import/kernels/SpaceToBatchND.cpp
This pr reduces code duplication for SpacesBatchesND and BatchToSpaceND.
for https://github.com/Samsung/ONE/issues/13272
> [onert-micro] Reduce SpaceToBatchND code duplication

- onert-micro/onert-micro/src/import/helpers/OMConfigureSISOKernel.cpp
- onert-micro/onert-micro/src/import/kernels/Abs.cpp
- onert-micro/onert-micro/src/import/kernels/Floor.cpp
- onert-micro/onert-micro/src/import/kernels/LogSoftmax.cpp
- onert-micro/onert-micro/src/import/kernels/Logistic.cpp
- onert-micro/onert-micro/src/import/kernels/Relu6.cpp
- onert-micro/onert-micro/src/import/kernels/Sin.cpp
This pr reduces import code duplication for Math ops.
for #13272
> [onert-micro] Reduce import Math ops code duplication

- onert-micro/onert-micro/include/pal/common/PALAveragePool2DCommon.h
- onert-micro/onert-micro/include/pal/mcu/PALAveragePool2D.h
- onert-micro/onert-micro/include/pal/mcu/PALConv2D.h
This pr adds static casts to fix types.
> [onert-micro] Fix types for building

- onert-micro/onert-micro/include/core/OMDataType.h
- onert-micro/onert-micro/include/execute/OMRuntimeKernel.h
- onert-micro/onert-micro/include/pal/common/PALSpaceToDepthCommon.h
- onert-micro/onert-micro/src/api/onert-micro.cpp
- onert-micro/onert-micro/src/execute/kernels/FloorDiv.cpp
- onert-micro/onert-micro/src/optimize/pass/FindInplaceOpPass.cpp
This will fix coverity defects.
This results in CQM 4.31
> Fix several coverity defects 

- onert-micro/onert-micro/include/execute/kernels/ArgCommon.h
- onert-micro/onert-micro/include/import/helpers/OMArgCommon.h
- onert-micro/onert-micro/src/execute/CMakeLists.txt
- onert-micro/onert-micro/src/execute/kernels/ArgCommon.cpp
- onert-micro/onert-micro/src/execute/kernels/ArgMax.cpp
- onert-micro/onert-micro/src/execute/kernels/ArgMin.cpp
- onert-micro/onert-micro/src/import/CMakeLists.txt
- onert-micro/onert-micro/src/import/helpers/OMArgCommon.cpp
- onert-micro/onert-micro/src/import/kernels/ArgMax.cpp
This pr reduces code duplication for ArgMin and ArgMax.
for https://github.com/Samsung/ONE/issues/13272
> [onert-micro] Reduce ArgMax and ArgMin code duplication

- compiler/one-cmds/onecc
- compiler/one-cmds/onelib/CfgRunner.py
- compiler/one-cmds/onelib/utils.py
This commit revises onecc script.
- Make some logic a function
- Move some attributes to dedicated file (utils.py)
- Tag type annotation
> [one-cmds] Revise onecc script

- compiler/luci-interpreter/src/kernels/NotEqual.cpp
- compiler/luci-interpreter/src/kernels/NotEqual.h
- compiler/luci-interpreter/src/kernels/ReduceMax.cpp
- compiler/luci-interpreter/src/kernels/ReduceMax.h
This commit supports bool type in NotEqual and ReduceMax op.
> [luci-interpreter] Support bool type in NotEqual and ReduceMax op

- runtime/onert/core/include/ir/train/UseDefChain.h
- runtime/onert/core/include/ir/train/UseDefChains.h
- runtime/onert/core/src/ir/train/UseDefChain.cc
This commit introduces UseDefChain that contains use-def edges between operands and operartions.
> [onert] Introduce UseDefChain

- infra/nnfw/python/.gitignore
- infra/nnfw/python/README.md
- infra/nnfw/python/setup.py
- runtime/onert/api/python/package/libnnfw_api_pybind.py
This commit updates python packaging policy.
- Seperate packaging for each supporting architecture by "--plat-name" option.
- Update source and target directory path for backend and odc library
- Add .gitignore file for packaging artifacts
> [infra] Update onert python packaging

- onert-micro/onert-micro/include/onert-micro-version.h
- verison file added since it is missing in refactoring
> [onert-micro] update onert-micro version to 2.0.0

- docs/release/onert-micro/2.0/release-note-2.0.0-pre.md
- Release Note for onert-micro 2.0.0-pre
> [onert-micro] Release Note for 2.0.0-pre

- res/TensorFlowLiteRecipes/Net_Sqrt_Div_000/test.recipe
- res/TensorFlowLiteRecipes/Net_Sqrt_Div_000/test.rule
This will introduce Net_Sqrt_Div_000 for transform test.
> [res] Introduce Net_Sqrt_Div_000 recipe

- compiler/luci/pass/include/luci/Pass/TransformSqrtDivToRsqrtMulPass.h
- compiler/luci/pass/src/TransformSqrtDivToRsqrtMulPass.cpp
- compiler/luci/pass/src/TransformSqrtDivToRsqrtMulPass.test.cpp
This will introduce TransformSqrtDivToRsqrtMulPass to convert Sqrt-Div
sequence to Rsqrt-Mul.
> [luci/pass] Introduce TransformSqrtDivToRsqrtMulPass

- compiler/luci/pass/include/luci/CircleOptimizer.h
- compiler/luci/pass/src/CircleOptimizer.cpp
This will add option to enable TransformSqrtDivToRsqrtMul.
> [luci/pass] Option to enable TransformSqrtDivToRsqrtMul

- compiler/arser/include/arser/arser.h
This commit updates error messages to print the argument name to help debugging.
> [arser] Print arg name in error message

- compiler/circle2circle/src/Circle2Circle.cpp
This will add transform_sqrt_div_to_rsqrt_mul option.
> [circle2circle] Add transform_sqrt_div_to_rsqrt_mul

- runtime/onert/backend/train/MemoryManager.cc
- runtime/onert/backend/train/MemoryManager.h
- runtime/onert/backend/train/TensorBuilder.cc
- runtime/onert/backend/train/TensorManager.cc
- runtime/onert/backend/train/TensorManager.h
- runtime/onert/core/include/backend/basic/MemoryManager.h
- runtime/onert/core/include/backend/basic/train/TrainableTensor.h
This commit introduces GradientMemoryManager that manages gradient tensors and optimizer variables.
- Introduce GradientMemoryManager
- Add setting buffers of optimizer variables to TrainableTensor
> [onert] Introduce GradientMemoryManager

- docs/release/1.27/index.rst
- docs/release/1.27/release-note-1.27.1.md
This commit is a release note for 1.27.1.
> Release note 1.27.1

- compiler/one-cmds/how-to-use-one-commands.txt
- compiler/one-cmds/onelib/constant.py
This will enable transform_sqrt_div_to_rsqrt_mul in one-cmds.
- include also to -O1 option
> [one-cmds] Enable transform_sqrt_div_to_rsqrt_mul

- runtime/onert/backend/train/ops/MeanLayer.cc
This commit corrects the shape by creating a temporary shape having the same rank as the input when _keep_dims is false because MeanGrad does not support other rank cases.
- Revert https://github.com/Samsung/ONE/pull/13351
- Fix `GenModelTrain.NonTrainableOps_FC_Mean` test case
/cc @ragmani
> [onert] Correct the shape when _keep_dims is false in backward of MeanLayer

- infra/nnfw/cmake/buildtool/cross/toolchain_aarch64-android.cmake
- infra/nnfw/cmake/packages/ARMComputeConfig.cmake
This commit updates android toolchain cmake script
- Get shared stl c++ library path by find_library
- Support ARM Compute Library build on latest NDK
> [infra] Update android build

- infra/debian/compiler/docs/one-codegen.1
- infra/debian/compiler/docs/one-profile.1
- infra/debian/compiler/docs/onecc.1
This commit updates help message of the man page.
This is a change according to #13416.
> [debian] Update help message of man page

- compiler/one-cmds/one-codegen
- compiler/one-cmds/one-profile
- compiler/one-cmds/onecc
This commit updates help message usage according to the exclusive options.
> [one-cmds] Update help message usage

- compiler/one-cmds/one-codegen
- compiler/one-cmds/one-profile
- compiler/one-cmds/tests/one-codegen_010.ini
- compiler/one-cmds/tests/one-codegen_010.test
- compiler/one-cmds/tests/one-codegen_011.ini
- compiler/one-cmds/tests/one-codegen_011.test
- compiler/one-cmds/tests/one-codegen_neg_001.test
- compiler/one-cmds/tests/one-codegen_neg_002.test
- compiler/one-cmds/tests/one-codegen_neg_003.test
- compiler/one-cmds/tests/one-profile_010.ini
- compiler/one-cmds/tests/one-profile_010.test
- compiler/one-cmds/tests/one-profile_011.ini
- compiler/one-cmds/tests/one-profile_011.test
- compiler/one-cmds/tests/one-profile_neg_001.test
- compiler/one-cmds/tests/one-profile_neg_002.test
- compiler/one-cmds/tests/one-profile_neg_003.test
This commit supports target option with command args.
> [one-cmds] Support target option with command args

- compiler/luci-interpreter/src/kernels/FullyConnected.cpp
This will tidy duplicate check in FullyConnected::configure().
> [luci-interpreter] Tidy duplicate check

- docs/release/1.27/index.rst
- docs/release/1.27/release-note-1.27.2.md
This commit is a release note for 1.27.2.
> Release note 1.27.2

- infra/debian/compiler/changelog
This commit updates changelog for 1.27.2.
> [debian] Update changelog for 1.27.2

- res/TensorFlowLiteRecipes/Net_Add_FullyConnected_000/test.recipe
- res/TensorFlowLiteRecipes/Net_Add_FullyConnected_000/test.rule
- res/TensorFlowLiteRecipes/Net_Add_FullyConnected_001/test.recipe
- res/TensorFlowLiteRecipes/Net_Add_FullyConnected_001/test.rule
- res/TensorFlowLiteRecipes/Net_Add_FullyConnected_002/test.recipe
- res/TensorFlowLiteRecipes/Net_Add_FullyConnected_002/test.rule
This will add Net_Add_FullyConnected tflite recipes.
> [res/tfl_recipes] Add Net_Add_FullyConnected

- res/TensorFlowLiteRecipes/Net_Mul_FullyConnected_000/test.recipe
- res/TensorFlowLiteRecipes/Net_Mul_FullyConnected_000/test.rule
- res/TensorFlowLiteRecipes/Net_Mul_FullyConnected_001/test.recipe
- res/TensorFlowLiteRecipes/Net_Mul_FullyConnected_001/test.rule
- res/TensorFlowLiteRecipes/Net_Mul_FullyConnected_002/test.recipe
- res/TensorFlowLiteRecipes/Net_Mul_FullyConnected_002/test.rule
This will add Net_Mul_FullyConnected tflite recipes.
> [res/tfl_recipes] Add Net_Mul_FullyConnected

- compiler/luci/pass/include/luci/CircleOptimizer.h
- compiler/luci/pass/include/luci/Pass/FoldMulPass.h
- compiler/luci/pass/src/CircleOptimizer.cpp
- compiler/luci/pass/src/FoldMulPass.cpp
- compiler/luci/pass/src/FoldMulPass.test.cpp
This will introduce FoldMulPass which will fold Mul to Constant if possible.
> [luci/pass] Introduce FoldMulPass

- compiler/circle2circle/src/Circle2Circle.cpp
This will add more fold and fuse options
- fold Mul
- fuse Add to FC bias
- fuse Mul to FC weights
> [circle2circle] More fold and fuse options

- .github/workflows/check-format.yml
- .github/workflows/check-pr-commit.yml
- .github/workflows/deploy-github-pages.yml
- .github/workflows/run-onert-micro-unit-tests.yml
This commit bumps up the version of the actions/checkout, actions/upload-artifact, and actions/setup-python
> [CI/github] Bump up actions

- docs/release/1.28/index.rst
- docs/release/1.28/release-note_1.28.0.md
This commit is release note for 1.28.0.
> Release note 1.28.0

- onert-micro/onert-micro/include/pal/common/PALL2Normalize.h
This pr fixes building for TizenRT
> [onert-micro] Fix TizenRT build

- runtime/onert/backend/train/TensorPlanner.cc
- runtime/onert/backend/train/TensorPlanner.h
This commit introduces TensorPlanner that plans all tensors associated with training.
> [onert/training] Introduce TensorPlanner

- runtime/onert/core/src/ir/train/UseDefGenerator.cc
- runtime/onert/core/src/ir/train/UseDefGenerator.h
This commit adds generating training usedefs for Conv2D operation.
> [onert] Add generating training usedefs for Conv2D op

- infra/nnfw/CMakeLists.txt
- runtime/contrib/style_transfer_app/CMakeLists.txt
- runtime/contrib/tflite_classify/CMakeLists.txt
- tests/CMakeLists.txt
- tools/CMakeLists.txt
This commit enables C++17 for all onert modules.
> [onert] Use C++17

- runtime/onert/core/src/ir/train/UseDefGenerator.cc
- runtime/onert/core/src/ir/train/UseDefGenerator.h
This commit adds generating training usedefs for ElementwiseActivation operation.
> [onert] Add generating training usedefs for ElementwiseActivation op

- runtime/onert/core/src/ir/train/UseDefGenerator.cc
- runtime/onert/core/src/ir/train/UseDefGenerator.h
This commit adds generating training usedefs for Pool2D op.
> [onert] Add generating training usedefs for Pool2D op

- runtime/onert/core/src/ir/train/UseDefGenerator.cc
- runtime/onert/core/src/ir/train/UseDefGenerator.h
This commit adds generating training usedefs for FullyConnected op.
> [onert] Add generating training usedefs for FullyConnected op

- runtime/onert/backend/train/TensorPlanner.cc
This commit adds planning trainable tensors used on train backend.
> [onert] Plan trainable tensors on train backend

- infra/scripts/test_ubuntu_runtime_mixed.sh
This commit updates test script to report unittest result.
---
It will resolve test fail #13504 #13505 #13506
> [onert/test] Report unittest result

- compiler/luci/pass/src/ConvertNCHWToNHWCPass.cpp
- compiler/luci/pass/src/ConvertNCHWToNHWCPass.test.cpp
This supports MirrorPad in ConvertNCHWToNHWC.
> [luci/pass] Support MirrorPad in ConvertNCHWToNHWC

- compiler/luci/pass/src/CircleOptimizer.cpp
This will enable CanonicalizePass to run in Optimizer.
> [luci/pass] Enable CanonicalizePass in Optimizer

- compute/cker/include/cker/operation/ReLU6.h
- runtime/onert/backend/cpu/ops/ElementwiseActivationLayer.cc
This commit uses Eigen in ReLU6 cker to apply multithreading.
> [onert] Use Eigen in ReLU6 cker

- res/TensorFlowLiteRecipes/Pad_001/test.recipe
This will introduce Pad_001 tflite recipe.
> [res] Introduce Pad_001 tflite recipe

- compute/cker/include/cker/eigen/depthwise_conv_op.h
This commit introduces LaunchDepthwiseConvOp cpu kernel.
This kernel will be used in DepthwiseConv2D operation.
Related issue: #13513
> [onert] Introduce LaunchDepthwiseConvOp cpu kernel

- compiler/luci/pass/src/ConvertNCHWToNHWCPass.cpp
This reduces duplicate codes in ConvertNCHWToNHWC.
> [luci/pass] Reduce duplicate codes

- .github/workflows/run-onert-android-build.yml
This commit introduces github workflow for runtime android build.
> [github] Introduce android build test

- runtime/onert/backend/train/TensorBuilder.cc
This commit add implementation of the notifyLastUse function in the TensorBuilder for training.
> [onert] Implement notifyLastUse in training TensorBuilder

- runtime/onert/core/src/ir/train/UseDefGenerator.test.cc
This commit adds unit tests for UseDefGenerator.
> [onert] Add unit tests for UseDefGenerator

- runtime/onert/backend/acl_cl/KernelGenerator.cc
- runtime/onert/backend/acl_common/AclKernelGen.h
- runtime/onert/backend/acl_neon/KernelGenerator.cc
- runtime/onert/backend/cpu/KernelGenerator.cc
- runtime/onert/backend/cpu/ops/ConvolutionLayer.cc
- runtime/onert/backend/ruy/KernelGenerator.cc
- runtime/onert/backend/ruy/ops/ConvolutionLayer.cc
- runtime/onert/backend/train/KernelGenerator.cc
- runtime/onert/backend/xnnpack/KernelGenerator.cc
- runtime/onert/core/include/ir/Shape.h
- runtime/onert/core/src/compiler/ShapeValidator.cc
- runtime/onert/core/src/ir/Shape.cc
- runtime/onert/core/src/util/ShapeInference.cc
- runtime/onert/core/src/util/ShapeInference.test.cc
This commit simply asFeature() function because layout is always NHWC.
---
> [onert] Simplfy asFeature

- compute/cker/include/cker/eigen/EigenSupport.h
- compute/cker/include/cker/train/operation/DepthwiseConv.h
- compute/cker/src/train/DepthwiseConv.test.cc
- runtime/onert/backend/train/ops/DepthwiseConvolutionLayer.cc
- runtime/onert/backend/train/ops/DepthwiseConvolutionLayer.h
This commit revisits DepthwiseConv train cker to change class to functions.
Related issue: #13513
> [onert] Revisit DepthwiseConv train cker

- compiler/luci/pass/src/ConvertNCHWToNHWCPass.cpp
- compiler/luci/pass/src/ConvertNCHWToNHWCPass.test.cpp
This supports S64 paddings in ConvertNCHWToNHWCPass.
---
Related to: https://github.com/Samsung/ONE/issues/13531
> [luci/pass] Support S64 paddings in ConvertNCHWToNHWC

- compiler/luci/pass/src/CanonicalizePass.cpp
This will remove duplicate codes in CanonicalizePass using template.
> [luci/pass] Tidy duplicate codes in CanonicalizePass

- .github/workflows/run-onecc-build.yml
This commit introduces onecc build & test on github workflow.
> [infra] Introduce github workflow for onecc

- onert-micro/CMakeLists.txt
- onert-micro/cmake/CheckGit.cmake
- onert-micro/git_version.h.in
This commit introduces git_version.h generation with commit hash define.
> [onert-micro] Introduce git_version.h generation

- compiler/luci-interpreter/src/kernels/MirrorPad.cpp
- compiler/luci-interpreter/src/kernels/MirrorPad.test.cpp
This will fix MirrorPad kernel implementation and unit tests.
- implementation is from onert-micro
> [luci-interpreter] Fix MirrorPad implementation

- res/TensorFlowLiteSchema/2.16.1/schema.fbs
This will introduce tflite schema 2.16.1.
> [res] Introduce tflite schema 2.16.1

- compiler/tflchef/core/src/ModelChef.cpp
This will introduce struct ModelChef to provide model chef functionality as beginning of refactoring to provide huge model generation.
> [tflchef] Introduce ModelChef

- compiler/tflchef/core/src/ModelChef.cpp
This will revise ModelChef as to move cook and cook_graph methods into member.
> [tflchef] Move cook and cook_graph into ModelChef

- compiler/tflchef/core/src/ModelChef.cpp
This will extract init method for flatbuffer_builder initialization.
> [tflchef] Extract init method

- compiler/tflchef/core/src/ModelChef.cpp
This will revise ModelChef as class
- add _ prefix to member variables
- introduce get_buffer_pointer() and _get_size()
> [tflchef] Revise ModelChef as class

- compiler/tflchef/core/src/ModelChef.cpp
This will extract cook_operands method to gather tensors.
> [tflchef] Extract cook_operands method

- compiler/tflchef/core/src/ModelChef.cpp
This will extract cook_operations method.
> [tflchef] Extract cook_operations

- runtime/onert/backend/cpu/ops/DepthwiseConvolutionLayer.cc
- runtime/onert/backend/cpu/ops/DepthwiseConvolutionLayer.h
- runtime/onert/backend/train/ops/DepthwiseConvolutionLayer.cc
- runtime/onert/backend/train/ops/DepthwiseConvolutionLayer.h
This commit uses DepthwiseConvOp cpu kernel to improve performance using multiple threads of Eigen API.
Related issue: #13513
Draft: #13407
> [onert] Use DepthwiseConvOp cpu kernel

- compiler/tflchef/core/src/ModelChef.cpp
This will revise with Buffer generation with ext_offset flag state.
> [tflchef] Revise with Buffer generation with ext_offset flag

- compiler/tfldump/src/Read.cpp
- compiler/tfldump/src/Read.h
This will revise Reader class to support Buffer offset/size attributes for file size > 2G.
> [tfldump] Revise Reader to support ext_offset

- docs/runtime/training.md
This commit adds ONERT Training document.
Draft: #13695
> [doc] Add ONERT Training document

- compiler/luci/export/include/luci/CircleExporter.h
- compiler/luci/export/include/luci/CircleFileExpContract.h
- compiler/luci/export/src/CircleExporter.cpp
- compiler/luci/export/src/CircleExporter.test.cpp
- compiler/luci/export/src/CircleExporterImpl.cpp
- compiler/luci/export/src/CircleExporterImpl.h
- compiler/luci/tester/src/WriteTester.cpp
This will tidy export with graph as this is not used anymore.
> [luci/export] Tidy export with graph

- compiler/luci/export/src/CircleExporterImpl.cpp
This will revise file description to "ONE-luci/export".
> [luci/export] Revise file description

- .github/workflows/check-format.yml
- .github/workflows/check-pr-commit.yml
- .github/workflows/run-onert-android-build.yml
- .github/workflows/run-onert-micro-unit-tests.yml
This will revuse to run all workflow jobs only in Samsung org.
> [github] Run workflow jobs only in Samsung org

- compiler/luci/service/src/CircleShapeInferenceRule.cpp
- compiler/luci/service/src/Nodes/CircleConcatenation.test.cpp
This infers dynamic shape for concat Op.
---
> [luci] Infer dynamic shape for concat

- compiler/tflite2circle/driver/Driver.cpp
- compiler/tflite2circle/include/CircleModel.h
- compiler/tflite2circle/include/TFLModel.h
- compiler/tflite2circle/src/CircleModel.cpp
This will revise CircleModel interface to pass raw file data
to access Buffer data outside of flatbuffers range.
> [tflite2circle] Revise interface to pass raw file data

- compiler/tflite2circle/src/CircleModel.cpp
This will extract a variable in Buffer build method.
> [tflite2circle] Extract variable in Buffer build

- compiler/luci-interpreter/src/kernels/InstanceNorm.cpp
- compiler/luci-interpreter/src/kernels/InstanceNorm.test.cpp
This supports InstanceNorm 3D kernel.
---
For #13700
> [luci-interpreter] Support InstanceNorm 3D kernel

- onert-micro/CMakeLists.txt
- onert-micro/onert-micro/include/core/reader/OMCircleReader.h
- onert-micro/standalone/CMakeLists.txt
This pr updates circle schema version and flatbuffer version.
from  #13719
> [onert-micro] Update schema version

- onert-micro/CMakeLists.txt
- onert-micro/training-configure-tool/CMakeLists.txt
- onert-micro/training-configure-tool/TrainingConfigureTool.cpp
- onert-micro/training-configure-tool/include/SparseBackpropagationHandler.h
- onert-micro/training-configure-tool/include/SparseBackpropagationHelper.h
- onert-micro/training-configure-tool/include/TensorRankSparseBackpropagationHandler.h
- onert-micro/training-configure-tool/include/TrainConfigData.h
- onert-micro/training-configure-tool/include/TrainingConfigureFileHandler.h
- onert-micro/training-configure-tool/include/TrainingDriverHandler.h
- onert-micro/training-configure-tool/src/SparseBackpropagationHandler.cpp
- onert-micro/training-configure-tool/src/SparseBackpropagationHelper.cpp
- onert-micro/training-configure-tool/src/TensorRankSparseBackpropagationHandler.cpp
- onert-micro/training-configure-tool/src/TrainingConfigureFileHandler.cpp
- onert-micro/training-configure-tool/src/TrainingDriverHandler.cpp
This pr supports training configure tool in onert-micro.
from draft https://github.com/Samsung/ONE/pull/13479
Note: should be merged after  #13592
> [onert-micro] Introduce training configure tool

- compiler/luci/import/include/luci/Importer.h
- compiler/luci/import/src/Importer.cpp
This will tidy unused import method that returns Graph.
> [luci/import] Tidy unused import method

- compiler/luci/import/include/luci/Import/CircleReader.h
- compiler/luci/import/src/CircleReader.cpp
This will revise CircleReader to provide direct file data access.
> [luci/import] Revise CircleReader

- compiler/circle-eval-diff/src/CircleEvalDiff.cpp
> [circle-eval-diff] Revise to use ImporterEx

- compiler/circle-execution-plan/src/CircleExecutionPlan.cpp
> [circle-exec-plan] Revise to use ImporterEx

- res/TensorFlowLiteRecipes/Net_InstanceNorm_008/test.recipe
- res/TensorFlowLiteRecipes/Net_InstanceNorm_008/test.rule
This will introduce tflite recipe for InstanNorm op with 3D input.
> [res] Introduce InstanceNorm 3D input tflite recipe

- compiler/mio-circle08/src/Reader.cpp
This will revise buffer_info() methods with assertion check and guards.
> [mio-circle] Add guards

- compiler/circle-opselector/driver/Driver.cpp
- compiler/circle-opselector/src/ModuleIO.cpp
- compiler/circle-opselector/src/ModuleIO.h
> [circle-opselector] Revise to use ImporterEx

- compiler/circle-part-driver/src/PModelsRunner.cpp
> [circle-part-driver] Revise to use ImporterEx

- compiler/common-artifacts/src/TestDataGenerator.cpp
> [cmn-arts] Revise to use ImporterEx

- compiler/fme-apply/driver/Driver.cpp
> [fme-apply] Revise to use ImporterEx

- compiler/fme-detect/driver/Driver.cpp
> [fme-detect] Revise to use ImporterEx

- compiler/record-minmax/src/RecordMinMax.cpp
> [record-minmax] Revise to use ImporterEx

- compiler/dalgona/src/Dalgona.cpp
> [dalgona] Revise to use ImporterEx

- compiler/luci/pass/src/FuseInstanceNormPass.cpp
This commit will support InstanceNorm with 3D input.
> [luci/pass] Support InstanceNorm with 3D input

- onert-micro/onert-micro/include/train/tests/OMTestUtils.h
- reflect recent internal api update(config)
> [onert-micro] Fix build error on train test

- compiler/luci/import/include/luci/Import/GraphBuilderContext.h
This will revise GraphBuilderContext to store import model has extended buffer.
> [luci/import] Revise GraphBuilderContext

- runtime/onert/core/include/ir/train/operation/UntrainableOperation.h
This commit adds space to increase readability.
> [onert] Add space to increase readability

- compiler/luci/import/src/Importer.test.cpp
This will revise Importer test to use import with buffer/size.
> [luci/import] Revise Importer test

- compiler/luci/lang/include/luci/IR/Module.h
- compiler/luci/lang/src/Module.test.cpp
This will add extended buffer accessors in Module.
> [luci/lang] Add extended buffer accessors in Module

- compiler/luci/pass/src/FuseBatchNormWithDwConvPass.cpp
This commit revises FuseBatchNormWithDwConvPass pass for static analysis tool.
Related: #13806
> [luci] Revise FuseBatchNormWithDwConvPass

- compiler/luci/pass/src/FuseBatchNormWithConvPass.cpp
This commit revises FuseBatchNormWithConvPass pass for static analysis tool.
Related: #13806 
> [pass] Revise FuseBatchNormWithConvPass

- compiler/luci/export/src/CircleTensorExporter.cpp
This will revise encodeOpBuffer method to pass SerializedModelData object.
> [luci/export] Revise encodeOpBuffer to pass SerializedModelData

- compiler/luci/pass/include/luci/CircleQuantizer.h
- compiler/luci/pass/src/CircleQuantizer.cpp
This commit revises CircleQuantizer for static analysis tool.
Related: #13806
> [luci] Revise CircleQuantizer

- compiler/luci/pass/src/CircleOptimizer.cpp
This commit refactors to reduce multiple if conditions. 
This is for static analysis tool.
Related: #13806
> [luci] Reduce multiple if conditions

- compiler/tflchef/core/src/ModelChef.cpp
This commit adds const reference to some varaibles.
This is for resolving static analysis warnings.
> [tflchef] Add const reference

- compiler/vconone/CMakeLists.txt
This commit bumps up to 1.30.0.
> [vconone] Bump up to 1.30.0

- compiler/embedded-import-value-test/src/TestDriver.cpp
> [embedded-import-value-test] Revise to use ImportEx

- compiler/luci/pass/src/ForwardTransposeOpPass.cpp
- compiler/luci/pass/src/ForwardTransposeOpPass.test.cpp
This forwards transpose across MUL with single element const.
---
Related to: https://github.com/Samsung/ONE/issues/13851
> [luci] Forward transpose across single element MUL

- onert-micro/onert-micro/include/execute/OMUtils.h
- onert-micro/onert-micro/src/execute/OMUtils.cpp
- onert-micro/onert-micro/src/execute/kernels/Add.cpp
- onert-micro/onert-micro/src/execute/kernels/Mul.cpp
- onert-micro/onert-micro/src/execute/kernels/Sub.cpp
- remove duplicated code of calculateQuantParams
> [onert-micro] Fix DC for Add, Sub Kernel

- onert-micro/onert-micro/include/import/helpers/OMFloorCommon.h
- onert-micro/onert-micro/src/import/CMakeLists.txt
- onert-micro/onert-micro/src/import/helpers/OMFloorCommon.cpp
- onert-micro/onert-micro/src/import/kernels/FloorDiv.cpp
- helper for floordiv and floormod
> [onert-micro] Floor Common Helper

- compiler/luci/export/src/SerializedData.cpp
- compiler/luci/export/src/SerializedData.h
This will revise SerializedData for extended Buffer support.
> [luci/export] Revise SerializedData for extended Buffer

- compiler/luci/import/src/ImporterEx.cpp
This will revise importVerifyModule to call importModule with raw data and size.
> [luci/import] Revise importVerifyModule

- compiler/luci/import/src/Importer.cpp
This will revise import to set Module with extended Buffer.
> [luci/import] Revise import to set Module with extended Buffer

- compiler/luci/export/src/CircleExporterImpl.cpp
- compiler/luci/export/src/CircleExporterImpl.h
This will revise exportModule with two pass for extended Buffer support.
> [luci/export] Revise exportModule

- compiler/luci/import/src/Nodes/CircleConst.cpp
This will revise CircleConstNodeBuilder::build to load extended Buffer.
> [luci/import] CircleConstNodeBuilder::build

- compiler/luci/export/src/CircleTensorExporter.cpp
- compiler/luci/export/src/SerializedData.h
This will revise SerializedModelData to have first empty_buffer as member.
> [luci/export Introdue empty_buffer as member

- compiler/luci/tester/src/ReadModule.cpp
This will revise ReadModule to call importModule with data and size.
> [luci/tester] Revise ReadModule

- compiler/luci/export/src/CircleExporterImpl.cpp
- compiler/luci/export/src/CircleTensorExporter.cpp
This will enable to check flatbuffers size limit set set flag to run extended buffer mode.
> [luci/export] Check size limit and set flag

- compiler/luci/export/src/CircleExporterUtils.h
This will revise check_size_limit argument fb as const.
> [luci/export] Revise check_size_limit

- compiler/luci/export/src/CircleExporterImpl.cpp
- compiler/luci/export/src/CircleExporterImpl.h
This will introduce finalizeWithExtendedBuffer method to generate export data.
> [luci/export] Finialize extended buffer

- docs/conf.py
- packaging/nnfw.spec
- runtime/contrib/android/api/build.gradle
- runtime/onert/api/nnfw/include/nnfw_version.h
This commit bumps up to 1.30.0
> [onert] Bump up to 1.30.0

- res/TensorFlowLiteRecipes/Net_Unnecessary_Cast_000/test.recipe
- res/TensorFlowLiteRecipes/Net_Unnecessary_Cast_000/test.rule
This commit adds Net_Unnecessary_Cast tflite recipes.
> [res/tfl_recipes] Add Net_Unnecessary_Cast

- res/TensorFlowLiteRecipes/Conv2D_006/test.recipe
This will introduce Conv2D_006 recipe for extended Buffer testing.
> [res] Introduce Conv2D_006 for extended Buffer

- compiler/luci/tester/src/ReadModule.cpp
- compiler/luci/tester/src/ReadModule.h
This will revise include header for luci::Module.
> [luci/tester] Revise include header in ReadModule

- onert-micro/onert-micro/src/import/kernels/SVDF.cpp
- Fix unreachable code in SVDF import
> [onert-micro] Fix unreachable code

- onert-micro/onert-micro/include/execute/OMUtils.h
- onert-micro/onert-micro/src/execute/OMUtils.cpp
- onert-micro/onert-micro/src/execute/kernels/Cast.cpp
- onert-micro/onert-micro/src/execute/kernels/L2Normalize.cpp
- onert-micro/onert-micro/src/execute/kernels/LogSoftmax.cpp
- onert-micro/onert-micro/src/execute/kernels/Logistic.cpp
- helper for SISO I/O getter to reduce sam DC score
> [onert-micro] SISOHeader helper for I/O

- onert-micro/CMakeLists.txt
- onert-micro/remove_stablehlo_from_cir0.8.patch
- remove stablehlo part to reduce size of generated files
> [onert-micro] fix sam GM issue

- compiler/one-cmds/one-import-onnx
This will revise one-import-onnx with _check_ext
- split _disable_ext with disable_ext option check
- _check_ext will only check extension existance
> [one-cmds] Revise one-import-onnx with _check_ext

- compiler/one-cmds/one-import-onnx
This will revise one-import-onnx with new force_ext option.
- added some comments how extension is called with force_ext and disable_ext options
> [one-cmds] Revise one-import-onnx with new force_ext

- compiler/one-cmds/one-import-onnx
- compiler/one-cmds/tests/one-import-onnx_ext_001.test
This will revise one-import-onnx with extension as
- run default conversion
- skip default if force_ext is given
- skip extension if disable_ext is given
- run extension if default fails
> [one-cmds] Revise one-import-onnx with extension

- compiler/one-cmds/one-import-onnx
This will remove unused option that was added by misunderstanding.
> [one-cmds] Remove unused option

- res/TensorFlowLiteRecipes/Net_Gather_SparseToDense_AddV2_000/test.recipe
This PR fix operand shape and filler of Net_Gather_SparseToDense_AddV2_000 recipe.
* related : https://github.com/Samsung/ONE/issues/13939
> [res] Fix Net_Gather_SparseToDense_AddV2_000 recipe

- onert-micro/onert-micro/include/import/OMUtils.h
- onert-micro/onert-micro/src/import/CMakeLists.txt
- onert-micro/onert-micro/src/import/OMUtils.cpp
- onert-micro/onert-micro/src/import/kernels/Equal.cpp
- onert-micro/onert-micro/src/import/kernels/Greater.cpp
- onert-micro/onert-micro/src/import/kernels/GreaterEqual.cpp
- onert-micro/onert-micro/src/import/kernels/Less.cpp
- onert-micro/onert-micro/src/import/kernels/LessEqual.cpp
- onert-micro/onert-micro/src/import/kernels/NotEqual.cpp
- onert-micro/onert-micro/src/import/kernels/Softmax.cpp
- TISOHeader helper defined
- apply helper to comparison kernels
> [onert-micro] TISO Header helper for import TISO kernel

- nnpackage/schema/circle_schema.fbs
This will update copyright year to latest update.
> [nnpackage] Update copyright year

- res/CircleSchema/0.9/circle_schema.fbs
This will introduce circle schema 0.9 file.
> [res] Introduce circle schema 0.9

- compiler/mio-circle08/CMakeLists.txt
This will revise to use circle schema from nnpackage.
> [mio-circle08] Use schema from nnpackage

- onert-micro/onert-micro/include/execute/OMUtils.h
- onert-micro/onert-micro/src/execute/OMUtils.cpp
- onert-micro/onert-micro/src/execute/kernels/Equal.cpp
- onert-micro/onert-micro/src/execute/kernels/Greater.cpp
- onert-micro/onert-micro/src/execute/kernels/GreaterEqual.cpp
- onert-micro/onert-micro/src/execute/kernels/Less.cpp
- onert-micro/onert-micro/src/execute/kernels/NotEqual.cpp
- tiso header helper defined
- apply this to comparison ops
> TISO header helper for comparison op

- compiler/luci/service/src/Nodes/CircleStridedSlice.cpp
This removes unintended changes for StridedSlice from https://github.com/Samsung/ONE/pull/13955
> [luci/service] Remove Unintended Changes for StridedSlice

- compute/cker/include/cker/train/Types.h
- compute/cker/include/cker/train/operation/Loss.h
- compute/cker/src/train/Loss.test.cc
- runtime/onert/backend/train/KernelGenerator.cc
- runtime/onert/backend/train/ops/LossCategoricalCrossentropyLayer.cc
- runtime/onert/backend/train/ops/LossCategoricalCrossentropyLayer.h
- runtime/onert/backend/train/ops/LossLayer.cc
- runtime/onert/backend/train/ops/LossLayer.h
- runtime/onert/backend/train/ops/LossMeanSquaredErrorLayer.cc
- runtime/onert/backend/train/ops/LossMeanSquaredErrorLayer.h
- runtime/onert/backend/train/ops/OperationUtils.cc
- runtime/onert/backend/train/ops/OperationUtils.h
This commit fixes computing MSE Gradients.
- SUM_OVER_BATCH_SIZE : computes MSE gradients with sum over batch size as it is before
- SUM : computes MSE gradients with sum for each batch
> [cker] Fix computing MSE Gradient

- res/TensorFlowLiteRecipes/Conv2D_007/test.recipe
- res/TensorFlowLiteRecipes/FullyConnected_010/test.recipe
- res/TensorFlowLiteRecipes/Net_Conv_Gelu_000/test.recipe
- res/TensorFlowLiteRecipes/Net_Conv_Pad_000/test.recipe
- res/TensorFlowLiteRecipes/Net_Conv_TConv_000/test.recipe
- res/TensorFlowLiteRecipes/Net_DConv_Conv_000/test.recipe
- res/TensorFlowLiteRecipes/Net_FullyConnected_Gelu_000/test.recipe
- res/TensorFlowLiteRecipes/Net_InstNorm_Conv_000/test.recipe
This commit adds some test networks.
Draft: #13659
> [res] Add some test networks

- compiler/fm-equalize/fmelib/ComputeParam.py
- compiler/fm-equalize/fmelib/DumpFMEParams.py
This commit adds DumpFMEParams script.
Draft: #13659 
> [fm-equalize] Add DumpFMEParams script

- compiler/onnx-tools/onnx-dump.py
This will introduce _gather_value_infos in onnx-dump.
> [onnx-tools] Introduce _gather_value_infos

- runtime/onert/backend/train/MemoryPlanner.test.cc
This PR removes commented code.
> [onert/backend] Remove commented code

- compiler/onnx-tools/CMakeLists.txt
- compiler/onnx-tools/onnx-si.py
This will introduce onnx-si.py that can produce shape-inferenced model.
> [onnx-tools] Introduce onnx-si.py for shape inference

- compiler/one-cmds/one-codegen
- compiler/one-cmds/one-profile
- compiler/one-cmds/onelib/backends.py
- compiler/one-cmds/tests/onecc_060.ini
- compiler/one-cmds/tests/onecc_neg_039.cfg
- compiler/one-cmds/tests/onecc_neg_039.ini
- compiler/one-cmds/tests/onecc_neg_039.test
This commit revises backends.py in onelib.
- Add descriptions.
- Add validation check.
> [one-cmds] Revise backends.py in onelib

- compiler/luci/export/src/CircleExporterUtils.h
This will fix check_size_limit with unsigned where existing formula was for signed value.
> [luci/export] Fix check_size_limit

- compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
This revises comments about quantization process.
> [luci/pass] Revise comments

- res/TensorFlowLiteRecipes/REGRESS_Issue_13863/test.recipe
- res/TensorFlowLiteRecipes/REGRESS_Issue_13863/test.rule
This commit adds REGRESS_Issue_13863 tflite recipe.
Related : https://github.com/Samsung/ONE/issues/13863
Draft : https://github.com/Samsung/ONE/pull/14051
> [res/tfl_recipes] Add REGRESS_Issue_13863

- runtime/onert/backend/cpu/KernelGenerator.cc
- runtime/onert/backend/cpu/ops/GGMLHelper.cc
- runtime/onert/backend/cpu/ops/GGMLHelper.h
- runtime/onert/backend/cpu/ops/GatherLayer.cc
- runtime/onert/backend/cpu/ops/GatherLayer.h
- tests/nnfw_api/lib/CircleGen.cc
- tests/nnfw_api/lib/CircleGen.h
- tests/nnfw_api/src/GenModelTests/one_op_tests/Gather.test.cc
This commit updates CPU backend to support Q4_0 Gather operation. 
It includes test for Q4_0.
---
Draft:  #13956
Related issue: #13908 #13910
> [onert/cpu] Support Q4_0 Gather

- compiler/circle2circle-dredd-recipe-test/test.lst
This commit adds a dredd_test for Issue_13863.
Related : https://github.com/Samsung/ONE/issues/13863
Draft : https://github.com/Samsung/ONE/pull/14051
> [circle2circle] Add Dredd test for Issue_13863

- tests/nnfw_api/src/GenModelTests/one_op_tests/Gather.test.cc
This commit adds Gather's negative test.
> [onert] Add Gather negative test

- res/CircleRecipes/RoPE_000/test.recipe
- res/TensorFlowLiteRecipes/Net_RoPE_000/test.recipe
- res/TensorFlowLiteRecipes/Net_RoPE_000/test.rule
This commit adds CircleRecipes and TensorFlowLiteRecipes for RoPE
> [res] add CircleRecipes and TensorFlowLiteRecipes for RoPE

- compiler/circle-inspect/driver/Driver.cpp
- compiler/circle-inspect/src/Dump.cpp
- compiler/circle-inspect/src/Dump.h
This commit intorduces new circleInspect for tensor shape.
> [circle-inspect] Introduce new circleInspect for tensor shape

- onert-micro/onert-micro/include/pal/common/PALGRUWeightGrad.h
- fix wrong gru reset logic by fixing memset size
> [onert-micro] fix wrong gru weight reset

- compiler/luci/pass/include/luci/CircleOptimizer.h
- compiler/luci/pass/include/luci/Pass/FuseRoPEPass.h
- compiler/luci/pass/src/CircleOptimizer.cpp
- compiler/luci/pass/src/FuseRoPEPass.cpp
- compiler/luci/pass/src/FuseRoPEPass.test.cpp
This commit supports RoPE for luci pass
> [luci/pass] Support RoPE Operation

- compiler/luci/service/include/luci/Service/CircleShapeInference.h
- compiler/luci/service/include/luci/Service/CircleTypeInference.h
- compiler/luci/service/src/CircleCloneNode.h
- compiler/luci/service/src/CircleShapeInferenceRule.cpp
- compiler/luci/service/src/CircleTypeInferenceRule.cpp
- compiler/luci/service/src/Nodes/CircleRoPE.cpp
- compiler/luci/service/src/Nodes/CircleRoPE.test.cpp
This commit supports RoPE for luci service
> [luci/service] Support RoPE operation

- compiler/circle2circle/src/Circle2Circle.cpp
This commit adds fuse option for RoPE
> [circle2circle] Add an option for RoPE

- compiler/luci/partition/include/luci/ConnectNode.h
- compiler/luci/partition/src/Nodes/CircleRoPE.cpp
- compiler/luci/partition/src/Nodes/CircleRoPE.test.cpp
This commit supports RoPE for luci partition
> [luci/partition] Support RoPE operation

- compiler/circle2circle-dredd-recipe-test/test.lst
This commit adds Inf_Pad to circle2circle-dredd-recipe-test
> [circle2circle-dredd-recipe-test] Add Inf_Pad test

- compiler/luci/pass/src/RemoveUnnecessaryTransposeNetPass.cpp
This PR move comment position in RemoveUnnecessaryTransposeNetPass.
* draft : https://github.com/Samsung/ONE/pull/14121 
(background) Before resolving https://github.com/Samsung/ONE/issues/13663, I'd like to trim current RemoveUnnecessaryTransposeNetPass.
> [circle2circle] Move comments in RmUnnecessaryTransNetPass

- docs/release/onert-micro/2.0/release-note-2.0.0.md
- Release Note for onert-micro 2.0.0
> [onert-micro] Release Note for onert-micro 2.0.0

- compiler/luci/pass/src/RemoveUnnecessaryTransposeNetPass.cpp
- compiler/luci/pass/src/RemoveUnnecessaryTransposeNetPass.test.cpp
This PR modifies the behavior of the RemoveUnnecessaryTransposeNetPass to operate based on the output shape of a reshape node instead of using reshape/shape nodes.
--------------
* draft : https://github.com/Samsung/ONE/pull/14121
* background : Before resolving https://github.com/Samsung/ONE/issues/13663, I'd like to trim current RemoveUnnecessaryTransposeNetPass.
> [luci/pass] Update reshape handling in RmUnnTransNetPass

- res/TensorFlowLiteRecipes/Inf_Mul_000/test.recipe
- res/TensorFlowLiteRecipes/Inf_Mul_000/test.rule
This commit adds TFLiteRecipe for dynamic shape Multiply.
> [res] Add TFLiteRecipe for dynamic shape Multiply

- res/TensorFlowLiteRecipes/Inf_Neg_000/test.recipe
- res/TensorFlowLiteRecipes/Inf_Neg_000/test.rule
This commit adds TFLiteRecipe for dynamic shape NEG
- Related : https://github.com/Samsung/ONE/issues/13998
- Related : https://github.com/Samsung/ONE/pull/13922
> [res] Add TFLiteRecipe for dynamic shape NEG

- compiler/luci/pass/src/RemoveUnnecessaryTransposeNetPass.cpp
This PR updates TaggedShapeAnaylzer methods to get vector instead of CircleNode.
* draft: https://github.com/Samsung/ONE/pull/14121
> [luci/pass] Update TaggedShapeAnaylzer methods interface

- res/TensorFlowLiteRecipes/Inf_Reshape_000/test.recipe
- res/TensorFlowLiteRecipes/Inf_Reshape_000/test.rule
This commit adds TFLiteRecipe for dynamic shape Reshape.
Related: https://github.com/Samsung/ONE/issues/13998
ONE-DCO-1.0-Signed-off-by: Jongwon Yang <yjw963@gmail.com>
> [res] Add TFLiteRecipe for dynamic shape Reshape

- compiler/luci/pass/src/FuseRoPEPass.cpp
This commit fix a wrong name for rope fuse
related : https://github.com/Samsung/ONE/pull/14099
> [luci/pass] Fix a wrong name

- compiler/luci/pass/src/ResolveCustomOpMatMulPass.cpp
- compiler/luci/pass/src/ShuffleWeightTo16x1Float32Pass.cpp
- compiler/luci/pass/src/SubstitutePackToReshapePass.cpp
- compiler/luci/pass/src/SubstituteSqueezeToReshapePass.cpp
- compiler/luci/pass/src/SubstituteStridedSliceToReshapePass.test.cpp
- compiler/luci/pass/src/SubstituteTransposeToReshapePass.cpp
Let's add origins to const node.
> [luci/pass] Add origins to const node

- compiler/luci/pass/include/luci/Pass/SubstituteExpandDimsToReshapePass.h
- compiler/luci/pass/src/SubstituteExpandDimsToReshapePass.cpp
- compiler/luci/pass/src/SubstituteExpandDimsToReshapePass.test.cpp
Let's introduces a new luci pass to substitute CircleExpandDims to CircleReshape.
---
Full draft: #14164
> [luci/pass] Introduce SubstituteExpandDimsToReshapePass

- compiler/luci/pass/src/RemoveUnnecessaryTransposeNetPass.cpp
This PR trims RemoveUnnecessaryTransposesNetPass.
- enhance some comements
- rename a varaible
- replace 'if(not cond) return false' with macro
> [luci/pass] Trim RemoveUnnecessaryTransposesNetPass

- compiler/luci/pass/include/luci/CircleOptimizer.h
- compiler/luci/pass/src/CircleOptimizer.cpp
Let's add SubstituteExpandDimsToReshape pass to CircleOptimizer.
> [luci/pass] Add SubstituteExpandDimsToReshape pass to CircleOptimizer

- compute/cker/include/cker/Types.h
- compute/cker/include/cker/operation/RoPE.h
- compute/cker/src/RoPE.test.cc
This commit introduces RoPE op in cpu kernel
> [compute/cker] Introduce RoPE op in cpu kernel

- compiler/circle2circle/src/Circle2Circle.cpp
Let's add substitute_expand_dims_to_reshape option to circle2circle cli.
> [circle2circle] Add substitute_expand_dims_to_reshape option

- runtime/onert/backend/cpu/KernelGenerator.cc
- runtime/onert/backend/cpu/KernelGenerator.h
- runtime/onert/backend/cpu/ops/OperationUtils.cc
- runtime/onert/backend/cpu/ops/OperationUtils.h
- runtime/onert/backend/cpu/ops/RoPELayer.cc
- runtime/onert/backend/cpu/ops/RoPELayer.h
This commit implements RoPE Layer in backend cpu
> [onert] Implement RoPELayer in backend cpu

- compiler/luci/service/src/CircleShapeInferenceRule.cpp
This will add missing header for build error.
> [luci/svc] Add missing header

- compiler/circle2circle-dredd-recipe-test/test.lst
Let's add a new test with expand dims and const filled shape.
---
DRAFT: #14164
> [circle2circle-dredd-recipe-test] Add ExpandDims_005

- compiler/luci/service/src/Nodes/CircleReshape.cpp
- compiler/luci/service/src/Nodes/CircleReshape.test.cpp
This will fix Reshape shape inference to refer newShape attribute.
> [luci/svc] Fix Reshape shape inference

- runtime/onert/backend/train/TensorPlanner.cc
This PR update log in TensorPlanner.
> [onert/train] Update TensorPlanner log

- compiler/fme-apply/src/FMEqualizer.cpp
- compiler/fme-apply/src/InsertScaleShift.cpp
This commit changes phase strategy and find depth.
> [fme-apply] Change phase strategy and find depth

- compiler/fme-apply/src/pass/FusePostScalePass.cpp
This commit considers FullyConnected with no bias.
> [fme-apply] Consider no bias FullyConnected

- res/TensorFlowLiteRecipes/Net_Decomposed_GRU_000/test.rule
- Add rule.test for dredd test of fuse_gru pass
draft : https://github.com/Samsung/ONE/pull/14237
issue : https://github.com/Samsung/ONE/issues/12263
> [res] test.rule for Decomposed GRU recipe

- compiler/record-minmax/include/DataBuffer.h
- compiler/record-minmax/include/DataSetIterator.h
This introduces a base class for iterator.
---
Draft PR: #14257
> [record-minmax] Introduce DataSetIterator

- compiler/luci/import/include/luci/ImporterEx.h
- compiler/luci/import/src/ImporterEx.cpp
This will revise importModule method to accept const argument.
> [luci/import] model_data as const

- compiler/record-minmax/CMakeLists.txt
- compiler/record-minmax/include/RandomIterator.h
- compiler/record-minmax/include/Utils.h
- compiler/record-minmax/src/RandomIterator.cpp
- compiler/record-minmax/src/Utils.cpp
- compiler/record-minmax/tests/Utils.test.cpp
This introduces an iterator for random data.
---
Draft PR: https://github.com/Samsung/ONE/pull/14257
> [record-minmax] Introduce RandomIterator

- compiler/record-minmax/include/DirectoryIterator.h
- compiler/record-minmax/src/DirectoryIterator.cpp
- compiler/record-minmax/src/Utils.cpp
This introduces an iterator for directory format.
---
Draft PR: https://github.com/Samsung/ONE/pull/14257
> [record-minmax] Introduce DirectoryIterator

- compiler/circle2circle/README.md
> [circle2circle] Minor doc fix

- compiler/kuma/README.md
> [kuma] Fix a typo

- compiler/tf2tfliteV2/README.md
This fixes typos and formatting.
> [tf2tfliteV2] Minor doc fix

- compiler/loco/doc/LEP_000_Dialect_Service.md
This corrects a typo and a missing article.
> [loco] Minor doc fix

- compiler/moco-log/README.md
> [moco-log] Minor doc fix

- compiler/luci/log/README.md
- compiler/luci/logex/README.md
> [luci] Minor doc fix

- compiler/moco/support/README.md
> [moco] Fix a doc typo

- compiler/moco-tf/README.md
> [moco-tf] Minor doc fix

- compiler/plier-tf/README.md
> [plier-tf] Minor doc fix

- compiler/onnx2circle/README.md
> [onnx2circle] Minor doc fix

- compiler/locoex-customop/README.md
> [locoex-customop] Improve README

- compiler/onnx-tools/onnx-dump.py
This will revise onnx-dump to show total number of nodes.
> [onnx-tools] Show total number of nodes

- compiler/circlechef/proto/circlechef.proto
This updates comment to mention circle schema.
---
Related to: https://github.com/Samsung/ONE/pull/14304#discussion_r1828966002
> [circlechef] Fix comment

- compiler/luci/pass/src/ForwardTransposeOpPass.cpp
This uses a macro for readability.
---
Related to: https://github.com/Samsung/ONE/pull/14323/files#r1849686312
> [luci] Revise ForwardTransposeOpPass.cpp

- tools/model_explorer_circle/LICENSE
This will introduce Apache 2.0 LICENSE file.
> [tools/mec] Introduce LICENSE file

- tools/model_explorer_circle/src/circle_adapter/__init__.py
It adds `__init__.py` to help making a package of circle adapter.
> [tools/model_explorer_circle] Add __init__.py for packaging

- tools/model_explorer_circle/MANIFEST.in
This will introduce initial MANIFEST.in file for package generation.
> [tools/mec] Introduce MANIFEST

- tools/model_explorer_circle/src/circle_adapter/main.py
It creates a mapping between tensors and its source node.
It will be used to represent connections between graph nodes.
---
draft: #14318 
issue: #14307
> [tools/model_explorer_circle] Create a map for tensors and its source

- tools/model_explorer_circle/MANIFEST.in
This will revise MANIFEST.in to include tests and exclude HOWTO.md.
> [tools/mec] Revise MANIFEST.in

- tools/model_explorer_circle/pyproject.toml
This will revise pyproject.toml with necessary items for package generation.
> [tools/mec] Revise pyproject.toml

- tools/model_explorer_circle/noxfile.py
This will introduce initial noxfile script for package generation and unit testing with nox.
> [tools/mec] Introduce noxfile

- tools/model_explorer_circle/src/circle_adapter/main.py
The model explorer draws edges based on the information provided by the 'IncomingEdge' API. 
By utilizing this API and a mapping from input tensors to source nodes, it adds edges accordingly.
---
draft: https://github.com/Samsung/ONE/pull/14318
issue: https://github.com/Samsung/ONE/issues/14307
> [tools/mec] Add edges between graph nodes

- infra/nnfw/config/gbs.conf
It updates gbs.conf.
- Remove not existing repository
- Add new repository: tizen 9.0, Tizen-(Unified/Base)-X
> [infra/gbs] Update gbs.conf

- .github/workflows/run-tools-mec-build.yml
This will introduce initial workflow for PR build and testing for tools/model-explorer-circle.
> [github] Add workflow for tools/model-explorer-circle

- tools/model_explorer_circle/pyproject.toml
This will update pyproject.tom for publishing to pypi.org.
> [tools/mec] Update pyproject.toml for publish

- tools/model_explorer_circle/src/circle_adapter/__init__.py
This will remove __init__ file that seem to be necessary as Adapter.
> [tools/mec] Remove __init__

- tools/model_explorer_circle/pyproject.toml
This will bump the package version from '0.0.2' to '0.1.0'.
> [tools/mec] Bump version

- tools/model_explorer_circle/src/model_explorer_circle/main.py
It adds tensor value attribute to contant tensors. 
The value of tensors will be displayed while maintaing the dimension.
---
* issue: #14375
* draft: #14381
> [tools/mec] Add tensor value attribute to constant tensors

- tools/model_explorer_circle/src/model_explorer_circle/main.py
This reverts a PR(#14393) since the fix is incomplete.
* For details : #14399
> Revert "[tools/mec] Fix the node id error for const tensors (#14393)"

- tools/model_explorer_circle/src/model_explorer_circle/main.py
Correct indexing errors for constant tensor nodes.
* For details : #14399
> [tools/mec] Fix the node id error for constant tensor

- tools/model_explorer_circle/src/model_explorer_circle/main.py
It adds the result graph to instance attribute.
The attribute will be used in unittest.
--- 
* Related w/ #14408
> [tools/mec] Add the graph as instance attribute

- tools/model_explorer_circle/tests/test_circle_adapter.py
It introduces a pytest script for testing the CircleAdapter.
---
* draft : #14408
> [tools/mec] Add unittest for CircleAdapter

- runtime/3rdparty/jsoncpp/README.md
- runtime/3rdparty/jsoncpp/json/json-forwards.h
- runtime/3rdparty/jsoncpp/json/json.h
- runtime/3rdparty/jsoncpp/jsoncpp.cpp
This commit updates jsoncpp to 1.9.6.
> [onert/3rdparty] Update jsoncpp

- tools/model_explorer_circle/tests/test_circle_adapter.py
It adds test cases for checking the number of operator and const nodes.
---
* draft : #14408
> [tools/mec] Test the number of operator and const nodes

- tools/model_explorer_circle/tests/test_circle_adapter.py
It adds test cases for checking edge connections between tensors and nodes.
---
* draft : #14408
> [tools/mec] Test if all edge connections are valid

- tools/model_explorer_circle/src/model_explorer_circle/main.py
It sets rank value to 1 when a tensor shape is not defined.
> [tools/mec] Fix rank value when shape is not defined

- tools/model_explorer_circle/src/model_explorer_circle/main.py
It update the value parsing interface to support 4-bit quantized tensors.
> [tools/mec] Support to display 4bit quantized values

- tools/model_explorer_circle/src/model_explorer_circle/main.py
It shows multiple quantization parameters if the tensor is quantized in channel-wise.
> [tools/mec] Show channel-wise quantization parameters

- tools/model_explorer_circle/src/model_explorer_circle/main.py
It introduces a common id variable which is used for Inputs, Outputs and Constant nodes.
> [tools/mec] Use common variable for node ids

- docs/runtime/on-device-compilation.md
This commit adds onert on-device compiler document.
> [onert/doc] Add onert on-device compiler document

- onert-micro/onert-micro/src/train/kernels/MaxPool2D.cpp
This commit fixes undefined behavior in training configure tool.
> [onert-micro] Fix training configure tool UB

- compiler/crew/src/PConfig.cpp
It removes a empty line bewteen header includes.
> [compiler/crew] Remove unnecessary empty line

- runtime/onert/api/nnfw/src/nnfw_api.cc
This commit removes function comment in nnfw_api.cc. 
It is duplication with comment in nnfw.h
> [onert] Remove function comment in nnfw_api.cc

- tools/model_explorer_circle/src/model_explorer_circle/main.py
It moves quantization parameters to input metadata.
---
* Wherever the quantization parameter exists (output metadata or input metadata), representaion in Model Explorer is same.
* However, the guidance of Model Explorer describes the quantization parameters might be in input metadata.
* https://github.com/google-ai-edge/model-explorer/wiki/6.-Develop-Adapter-Extension#add-inputs-metadata
```
...
Some of our built-in adapters store the following fields in inputsMetadata:
- __tensor_tag (optional): The value will serve as the name of a node's inputs shown in the "Inputs" section ...
- quantization (optional): The quantization related parameters.
...
```
> [tools/mec] Move quantization parameters to input metadata

- compiler/mir/include/mir/ops/ResizeOp.h
This will fix initializer order compilation error.
> [mir] Fix init order error

- compiler/nnc/backends/acl_soft_backend/ArtifactModel.h
- compiler/nnc/include/pass/PassData.h
This will fix initializer order compilation error.
> [nnc] Fix init order error

- compiler/luci/pass/src/QuantizeOnnxFakeQuantModelPass.cpp
This iteratively propagates qparam forward.
> [luci] Propagate qparam forward iteratively

- compiler/one-cmds/CMakeLists.txt
- compiler/one-cmds/one-prepare-venv.u2404
This commit updates cmake to support ubuntu 24.04.
---
Draft: #14514
> [one-cmds] Support ubuntu 24.04

- compiler/CMakeLists.txt
This will provide cmake flag for ubuntu 24.04 (noble).
---
Draft: #14514 
Related PR: #14526
> [CFE] Introduce cmake flag for ubuntu 24.04

- .github/workflows/generate-rootfs.yml
This commit introduces a GitHub Actions workflow to generate the rootfs
> [infra/github] Introduce workflow for rootfs generation

- res/TensorFlowLiteRecipes/Add_003/test.recipe
- res/TensorFlowLiteRecipes/Add_004/test.recipe
- res/TensorFlowLiteRecipes/Add_005/test.recipe
- res/TensorFlowLiteRecipes/Add_006/test.recipe
Let's add 4 recipes for broadcast Add.
---
For https://github.com/Samsung/ONE/issues/14554
> [res] Add TensorFlowLiteRecipes for broadcast Add

- .github/workflows/build-dev-docker.yml
- .github/workflows/run-onert-gbs-build.yml
- .github/workflows/run-tools-mec-build.yml
This commit adds a org name check to run on original repo only.
> [infra/github] Check org name for jobs

- docs/howto/how-to-build-compiler.md
This commit adds the known issues section to the compiler build instructions. The section currently describes a workaround for a potential compilation error that one might encounter when cross compiling with GCC 10.5
Related: https://github.com/Samsung/ONE/pull/14535
> [docs] Add the known issues section

- compiler/luci/partition/src/PartitionPModules.cpp
This will fix for static analysis to check null and throw.
> [luci/partition] Fix for staic analysis

- compiler/luci/pass/src/ExpandBroadcastConstPass.cpp
Let's extend the pass to support broadcast dim to all, not only the last dimension.
---
DRAFT: #14564
FOR: #14552
> [luci/pass] Extend ExpandBroadcastConstPass

- compiler/luci/pass/src/ExpandBroadcastConstPass.test.cpp
Let's add more unittest to ExpandBroadcastConstPass with axis=1 (non-lastdim).
---
For #14552
> [luci/pass] Add unittest to ExpandBroadcastConstPass

- compiler/vconone/src/version.cpp
This will update copyright year to 2025.
> [vconone] Update copyright year

- .ahub/tcchecker-tca/config.yaml
This commit updates exclude list for test count by deleting removed test.
> [onert/test] Update test count exclude list

- .github/workflows/build-docker-circle-mlir.yml
This will introduce build-docker-circle-mlir Workflow to build Docker image for circle-mlir build.
> [github] Introduce build-docker-circle-mlir

- circle-mlir/infra/docker/u2204/Dockerfile
This will revise Dockerfile with;
- install clang-format-16 for using this as local build
- update yapf to same version used in format check
> [circle-mlir] Revise Dockerfile

- runtime/onert/sample/minimal-python/experimental/src/train_step_with_dataset.py
This commit adds a sample example for session train_step.
> [onert/python] Add a sample example for session train_step

- runtime/onert/sample/minimal-python/experimental/src/train_with_dataset.py
This commit adds a sample example for session train.
> [onert/python] Add a sample example for session train

- runtime/onert/api/nnfw/src/CustomKernel.cc
- runtime/onert/api/nnfw/src/CustomKernelRegistry.cc
- runtime/onert/api/python/src/bindings/nnfw_session_bindings.cc
- runtime/onert/api/python/src/bindings/nnfw_tensorinfo_bindings.cc
- runtime/onert/api/python/src/wrapper/nnfw_api_wrapper.cc
This commit applies nested namepsace in api directory.
> [onert] Apply nested namespace in api directory.

- runtime/tests/nnapi/bridge/wrapper/ANeuralNetworksModel.cc
This commit updates NNAPI wrapper to allow modification of model on compilation and execution phase.
> [onert/test] Allow modification of model

- runtime/onert/loader/trix/TrixLoader.cc
- runtime/onert/odc/Embedder.cc
- runtime/onert/odc/Embedder.h
- runtime/onert/odc/MinMaxReader.cc
- runtime/onert/odc/MinMaxReader.h
- runtime/onert/odc/Quantizer.cc
- runtime/onert/odc/Quantizer.h
This commit applies nested namespace in loader and odc directory.
> [onert] Apply nested namespace in loader and odc directory

- tools/onnx_subgraph/docker/Dockerfile.u2204
This will introduce Dockerfile for CI PR build and test.
> [onnx-subgraph] Dockerfile for CI

- circle-mlir/CMakeLists.txt
- circle-mlir/circle-mlir/CMakeLists.txt
- circle-mlir/circle-mlir/lib/CMakeLists.txt
- circle-mlir/circle-mlir/lib/schema/CMakeLists.txt
This will enable to generate circle-schame header and target.
> [circle-mlir] Introduce circle-schema generation and target

- .github/workflows/build-docker-onnx-subgr.yml
This will fix Dockerfile path in build-docker-onnx-subgr.
> [github] Fix path in build-docker-onnx-subgr

- runtime/compute/cker/include/cker/Types.h
- runtime/compute/cker/include/cker/operation/BinaryArithmeticOps.h
- runtime/compute/cker/include/cker/operation/DepthwiseConv.h
- runtime/compute/cker/include/cker/operation/FloorMod.h
- runtime/compute/cker/include/cker/operation/Range.h
- runtime/compute/cker/include/cker/operation/SoftMax.h
- runtime/compute/ruy/include/ruy/Types.h
- runtime/onert/core/src/util/ShapeInference.cc
This commit applies if constexpr for code optimization.
> [onert] Apply if constexpr

- circle-mlir/circle-mlir/CMakeLists.txt
- circle-mlir/circle-mlir/lib/CMakeLists.txt
- circle-mlir/circle-mlir/lib/tools/CMakeLists.txt
- circle-mlir/circle-mlir/lib/tools/converter-gen/.clang-format
- circle-mlir/circle-mlir/lib/tools/converter-gen/CMakeLists.txt
- circle-mlir/circle-mlir/lib/tools/converter-gen/README.md
- circle-mlir/circle-mlir/lib/tools/converter-gen/converter_gen.cc
This will introduce converter-gen tool to generate source files from .td files.
> [circle-mlir] Introduce lib/tools/converter-gen

- circle-mlir/circle-mlir/lib/CMakeLists.txt
- circle-mlir/circle-mlir/lib/dialect/CMakeLists.txt
- circle-mlir/circle-mlir/lib/dialect/mlir/TableGen.cmake
This will introduce initial lib/dialect CMakerLists.txt with Tablegen.cmake.
> [circle-mlir] Introduce initial dialect CMakeLists

- circle-mlir/circle-mlir/lib/dialect/mlir/CircleOpInterfaces.td
- circle-mlir/circle-mlir/lib/dialect/mlir/TableGen.cmake
This will introduce CircleOpInterfaces td(target description) file
and generate necessary include files.
> [circle-mlir] Introduce CircleOpInterfaces

- circle-mlir/circle-mlir/lib/dialect/CMakeLists.txt
- circle-mlir/circle-mlir/lib/dialect/utils/DynamicShapeUtils.cpp
- circle-mlir/circle-mlir/lib/dialect/utils/DynamicShapeUtils.h
This will introduce cirmlir_dialect in lib/dialect with dynamic shape utils.
> [circle-mlir] Introduce lib/dialect/cirmlir_dialect

- circle-mlir/circle-mlir/lib/dialect/mlir/CircleShapeInferenceInterfaces.td
- circle-mlir/circle-mlir/lib/dialect/mlir/TableGen.cmake
This will add CircleShapeInferenceInterfaces.td generation to dialect.
> [circle-mlir] Add CircleShapeInferenceInterfaces

- circle-mlir/circle-mlir/lib/dialect/mlir/CircleOpEnums.td
- circle-mlir/circle-mlir/lib/dialect/mlir/TableGen.cmake
This will add CircleOpEnums generartion to dialect.
> [circle-mlir] Add CircleOpEnums

- circle-mlir/circle-mlir/lib/dialect/CMakeLists.txt
- circle-mlir/circle-mlir/lib/dialect/utils/Errors.cpp
- circle-mlir/circle-mlir/lib/dialect/utils/Errors.h
This will introduce dialect/utils/Errors for error related handlings.
> [circle-mlir] Introduce dialect Errors

- runtime/compute/cker/include/cker/operation/BroadcastTo.h
This commit inline variables to cker.
> [cker] Apply inline variables

- runtime/onert/backend/train/TensorPlanner.cc
- runtime/onert/core/include/ir/NNPkg.h
- runtime/onert/core/src/compiler/ExecutorFactory.cc
- runtime/onert/core/src/compiler/HEScheduler.cc
- runtime/onert/core/src/compiler/MultiModelCompiler.cc
- runtime/onert/core/src/compiler/train/TrainingCompiler.cc
- runtime/onert/core/src/exec/MinMaxRecorder.cc
- runtime/onert/core/src/exec/MultiModelExecutors.cc
- runtime/onert/core/src/exec/MultiModelExecutors.h
This commit applies structured binding in onert.
> [onert] Apply structured binding in onert

- circle-mlir/circle-mlir/lib/dialect/CMakeLists.txt
- circle-mlir/circle-mlir/lib/dialect/include/circle-mlir/dialect/NameUtils.h
- circle-mlir/circle-mlir/lib/dialect/src/NameUtils.cpp
This will introduce NameUtils with GetNameFromLoc method.
> [circle-mlir/dialect] Introduce NameUtils

- circle-mlir/circle-mlir/lib/dialect/CMakeLists.txt
- circle-mlir/circle-mlir/lib/dialect/utils/Padding.cpp
- circle-mlir/circle-mlir/lib/dialect/utils/Padding.h
- circle-mlir/circle-mlir/lib/dialect/utils/Padding.test.cpp
This will introduce Padding with helper method.
- dialect unit test is now enable with this change.
> [circle-mlir/dialect] Introduce Padding

- circle-mlir/circle-mlir/lib/dialect/mlir/CircleOps.td
This will introduce ConstOp and NoValueOp in CircleOps.
> [circle-mlir/dialect] Introduce ConstOp and NoValueOp

- circle-mlir/circle-mlir/lib/dialect/CMakeLists.txt
- circle-mlir/circle-mlir/lib/dialect/utils/KernelShapeUtil.cpp
- circle-mlir/circle-mlir/lib/dialect/utils/KernelShapeUtil.h
- circle-mlir/circle-mlir/lib/dialect/utils/KernelShapeUtil.test.cpp
This will introduce KernelShapeUtil with related helper methods including unit tests.
> [circle-mlir/dialect] Introduce KernelShapeUtil

- circle-mlir/circle-mlir/lib/utils/CMakeLists.txt
- circle-mlir/circle-mlir/lib/utils/include/circle-mlir/utils/SizeUtils.h
- circle-mlir/circle-mlir/lib/utils/src/SizeUtils.cpp
- circle-mlir/circle-mlir/lib/utils/src/SizeUtils.test.cpp
This will introduce SizeUtils with size conversion helper.
> [circle-mlir/utils] Introduce SizeUtils

- circle-mlir/circle-mlir/lib/dialect/CMakeLists.txt
- circle-mlir/circle-mlir/lib/dialect/include/circle-mlir/dialect/CircleDialect.h
- circle-mlir/circle-mlir/lib/dialect/src/CircleDialect.cpp
This will introduce CircleDialect with common methods used throught CIR_Ops.
> [circle-mlir/dialect] Introduce CircleDialect

- circle-mlir/circle-mlir/lib/dialect/CMakeLists.txt
- circle-mlir/circle-mlir/lib/dialect/src/ShapeInference.cpp
This will introduce ShapeInference with helpers for shape inference.
> [circle-mlir/dialect] Introduce ShapeInference

- circle-mlir/circle-mlir/lib/dialect/src/CircleDialect.cpp
This will add KernelShapeUtil and Padding helper incldues to CircleDialect.
> [circle-mlir/dialect] Add util helpers

- circle-mlir/circle-mlir/lib/dialect/mlir/CircleRewrite.td
- circle-mlir/circle-mlir/lib/dialect/mlir/TableGen.cmake
- circle-mlir/circle-mlir/lib/dialect/src/CircleDialect.cpp
This will introduce CircleRewrite to enable rewriting with td.
> [circle-mlir/dialect] Introduce CircleRewrite

- circle-mlir/circle-mlir/lib/dialect/src/CircleDialect.cpp
- circle-mlir/circle-mlir/lib/dialect/src/ConstFold.inc.cpp
This will add constant fold helpers in CircleDialect.
> [circle-mlir/dialect] Add constant fold helpers

- circle-mlir/circle-mlir/lib/utils/CMakeLists.txt
- circle-mlir/circle-mlir/lib/utils/include/circle-mlir/utils/FlatbufferOperator.h
- circle-mlir/circle-mlir/lib/utils/src/FlatbufferOperator.cpp
This will introduce FlatbufferOperator with helpers
to conversion from/to circle flatbuffers and circle MLIR.
> [circle-mlir/utils] Introduce FlatbufferOperator

- circle-mlir/infra/overlay/prepare-venv
This will introduce prepare-venv script in overlay to prepare venv for circle-mlir development.
> [circle-mlir/infra] Introduce overlay/prepare-venv

- circle-mlir/README.md
This will introduce initial README.md file.
> [circle-mlir] Initial README

- circle-mlir/externals/.clang-format
- circle-mlir/externals/.gitignore
- circle-mlir/externals/CMakeLists.txt
This will introduce initial externals with flatbuffers and abseil-cpp build.
> [circle-mlir/ext] Introduce initial externals

- circle-mlir/externals/.gitignore
- circle-mlir/externals/CMakeLists.txt
- circle-mlir/externals/onnx_quantdequant_i16.diff
This will add externals/protobuf and onnx-mlir builds.
> [circle-mlir/ext] Add protobuf and onnx-mlir build

- tools/onnx_subgraph/extract_onnx.py
Add exception protecting for file open and read
> [tools/onnx-subgraph] Add file IO exception process

- runtime/onert/core/include/exec/FunctionSequence.h
This commit applies fold expressions.
> [onert] Apply fold expressions

- circle-mlir/circle-mlir/CMakeLists.txt
- circle-mlir/circle-mlir/lib/dialect/CMakeLists.txt
This will include abseil library and add link in dialect.
> [circle-mlir] Include abseil

- circle-mlir/circle-mlir/CMakeLists.txt
- circle-mlir/circle-mlir/tools/CMakeLists.txt
- circle-mlir/circle-mlir/tools/onnx2circle/CMakeLists.txt
- circle-mlir/circle-mlir/tools/onnx2circle/src/driverDebug.cpp
- circle-mlir/circle-mlir/tools/onnx2circle/src/driverRelease.cpp
- circle-mlir/circle-mlir/tools/onnx2circle/src/onnx2circle.cpp
- circle-mlir/circle-mlir/tools/onnx2circle/src/onnx2circle.h
This will introduce initial almost empty onnx2circle tool.
> [circle-mlir/tools] Introduce initial onnx2circle

- circle-mlir/circle-mlir/lib/dialect/src/ShapeInference.cpp
This will add CustomOp inferShapes method implementation.
> [circle-mlir/dialect] Add CustomOp inferShapes

- circle-mlir/circle-mlir/lib/dialect/mlir/CircleOps.td
- circle-mlir/circle-mlir/lib/dialect/src/CircleDialect.cpp
- circle-mlir/circle-mlir/lib/dialect/src/ShapeInference.cpp
- circle-mlir/circle-mlir/lib/dialect/src/ops/AddOp.h
This will enable AddOp IR in dialect.
> [circle-mlir/dialect] Enable AddOp IR

- circle-mlir/externals/CMakeLists.txt
This will add options to build with clang and gold linker.
> [circle-mlir/ext] Enable build with clang/gold

- circle-mlir/circle-mlir/lib/pass/CMakeLists.txt
- circle-mlir/circle-mlir/lib/pass/src/ConvertHelper.cpp
- circle-mlir/circle-mlir/lib/pass/src/ConvertHelper.h
This will introduce ConvertHelper with helper methods for onnx to circle conversion.
> [circle-mlir/pass] Introduce ConvertHelper

- circle-mlir/circle-mlir/tools/onnx2circle/src/onnx2circle.cpp
This will enable onnx2circle to load ONNX model file.
> [circle-mlir/tools] Load ONNX file

- .github/workflows/run-onert-android-build.yml
- .github/workflows/run-onert-build.yml
- .github/workflows/run-onert-gbs-build.yml
- runtime/contrib/README.md
This commit updates README.md for runtime/contrib and disable workflows when contrib directory is updated.
> [onert/contrib] Update README.md and workflows

- circle-mlir/circle-mlir/lib/pass/CMakeLists.txt
- circle-mlir/circle-mlir/lib/pass/src/CirclePass.cpp
- circle-mlir/circle-mlir/lib/pass/src/ConvertONNXToCirclePass.cpp
- circle-mlir/circle-mlir/lib/pass/src/ConvertONNXToCirclePass.h
This will introduce ConvertONNXToCirclePass that will convert ONNX MLIR to Circle MLIR.
> [circle-mlir/pass] Introduce ConvertONNXToCirclePass

- circle-mlir/circle-mlir/tools/onnx2circle/src/onnx2circle.cpp
This will enable to use Circle dialect in onnx2circle tool.
> [circle-mlir/tools] Use Circle dialect in onnx2circle

- circle-mlir/models/mlir/Add_F32.onnx.mlir
- circle-mlir/models/mlir/Add_F32_0.circle.mlir
- circle-mlir/models/mlir/Add_F32_1.circle.mlir
- circle-mlir/models/mlir/Add_F32_2.circle.mlir
- circle-mlir/models/mlir/Add_F32_us.circle.mlir
This will introduce mlir test files for AddOp.
> [circle-mlir/models] Introduce AddOp test mlir files

- circle-mlir/circle-mlir/tools/onnx2circle/src/driverDebug.cpp
This will implement 'o2c-single' option for debug version,
to run single instance of 'onnx2circle' tool in testing,
so that MLIR dump in testing is readble.
Without this option, MLIR dumps in execution are overlapped
and very difficult to read.
> [circle-mlir/tools] Implement o2c-single option

- circle-mlir/circle-mlir/lib/pass/include/circle-mlir/pass/CirclePass.h
- circle-mlir/circle-mlir/lib/pass/src/CirclePass.cpp
- circle-mlir/circle-mlir/tools/onnx2circle/src/onnx2circle.cpp
This will enable to preprocessing and shape inference of ONNX model graph.
> [circle-mlir] Enable preprocessing of ONNX graph

- circle-mlir/circle-mlir/lib/pass/CMakeLists.txt
- circle-mlir/circle-mlir/lib/pass/src/CirclePass.cpp
- circle-mlir/circle-mlir/lib/pass/src/RewriteONNXPass.cpp
- circle-mlir/circle-mlir/lib/pass/src/RewriteONNXPass.h
- circle-mlir/circle-mlir/lib/pass/src/onnx/CompactReshapeConvReshape.h
This will introduce RewriteONNXPass for preprocess ONNX with conversion of
Reshape-Conv-Reshape sequence to Conv for certain conditions.
> [circle-mlir/pass] Introduce RewriteONNXPass

- circle-mlir/circle-mlir/lib/pass/CMakeLists.txt
- circle-mlir/circle-mlir/lib/pass/include/circle-mlir/pass/CirclePass.h
- circle-mlir/circle-mlir/lib/pass/src/CirclePass.cpp
- circle-mlir/circle-mlir/lib/pass/src/RewriteCirclePass.cpp
- circle-mlir/circle-mlir/lib/pass/src/RewriteCirclePass.h
- circle-mlir/circle-mlir/lib/pass/src/ShapeInferencePass.cpp
- circle-mlir/circle-mlir/lib/pass/src/ShapeInferencePass.h
- circle-mlir/circle-mlir/tools/onnx2circle/TestModels.cmake
- circle-mlir/circle-mlir/tools/onnx2circle/src/onnx2circle.cpp
- circle-mlir/circle-mlir/tools/onnx2circle/test.lst
This will execute post processing of Circle graph with
canonicalization, activation fusion and shape inference.
> [circle-mlir] Execute post process of Circle graph

- circle-mlir/circle-mlir/lib/pass/include/circle-mlir/pass/CirclePass.h
- circle-mlir/circle-mlir/lib/pass/src/CirclePass.cpp
- circle-mlir/circle-mlir/lib/pass/src/ShapeInferencePass.cpp
- circle-mlir/circle-mlir/lib/pass/src/ShapeInferencePass.h
- circle-mlir/circle-mlir/tools/onnx2circle/src/onnx2circle.cpp
This will implement shape inference validation with
'check_shapeinf' and 'check_dynshapeinf' options.
> [circle-mlir] Implement shape inference validation

- circle-mlir/circle-mlir/lib/pass/src/ConvertONNXToCirclePass.cpp
- circle-mlir/circle-mlir/lib/pass/src/ops/ConstantOp.h
This will enable ONNXConstantOp to Circle ConstOp.
> [circle-mlir/pass] Enable ConstOp conversion

- circle-mlir/circle-mlir/tools/circle-impexp/CMakeLists.txt
- circle-mlir/circle-mlir/tools/circle-impexp/README.md
- circle-mlir/circle-mlir/tools/circle-impexp/src/circleimpexp.cpp
- circle-mlir/circle-mlir/tools/circle-impexp/src/circleimpexp.h
- circle-mlir/circle-mlir/tools/circle-impexp/src/circleimpexp.test.cpp
- circle-mlir/circle-mlir/tools/circle-impexp/src/driver.cpp
This will introduce test tool for 'import' module.
> [circle-mlir/tools] Introduce circle-impexp

- circle-mlir/circle-mlir/tools-test/onnx2circle-models/.gitignore
- circle-mlir/circle-mlir/tools-test/onnx2circle-models/CMakeLists.txt
This will enable local models list for onnx2circle-models.
> [circle-mlir/tools-test] Enable local list for onnx2circle-models

- circle-mlir/circle-mlir/tools-test/onnx2circle-value-test/CMakeLists.txt
- circle-mlir/circle-mlir/tools-test/onnx2circle-value-test/exec_onnx.py
- circle-mlir/circle-mlir/tools-test/onnx2circle-value-test/util_h5_file.py
This will add exec_onnx and util_h5_file scripts for onnx2circle-value-test.
> [circle-mlir/tools-test] Add exec_onnx and util_h5_file

- circle-mlir/circle-mlir/tools-test/onnx2circle-value-test/CMakeLists.txt
- circle-mlir/circle-mlir/tools-test/onnx2circle-value-test/comp_onnx_circle.py
- circle-mlir/circle-mlir/tools-test/onnx2circle-value-test/util_validation.py
This will add comp_onnx_circle and util_validation scripts
to compare execution outputs of onnx and circle models.
> [circle-mlir/tools-test] Add comp_onnx_circle and util_validation

- circle-mlir/circle-mlir/tools-test/onnx2circle-value-test/CMakeLists.txt
- circle-mlir/circle-mlir/tools-test/onnx2circle-value-test/run_value_test.sh
- circle-mlir/circle-mlir/tools-test/onnx2circle-value-test/test.lst
This will enable onnx2circle-value-test with two AddOp models.
> [circle-mlir/tools-test] Enable onnx2circle-value-test

- circle-mlir/circle-mlir/tools-test/circle-impexp-test/CMakeLists.txt
- circle-mlir/circle-mlir/tools-test/circle-impexp-test/run_value_test.sh
This will introdue initial circle-impexp-test with dummy run_value_test.sh script,
for import module validation with value compare.
> [circle-mlir/tools-test] Introduce initial circle-impexp-test

- circle-mlir/circle-mlir/tools-test/circle-impexp-test/CMakeLists.txt
This will introduce ImportModel macro to add model import tests.
> [circle-mlir/tools-test] Introduce ImportModel macro

- circle-mlir/circle-mlir/tools-test/circle-impexp-test/CMakeLists.txt
- circle-mlir/circle-mlir/tools-test/circle-impexp-test/exec_onnx.py
This will introduce exec_onnx script to execute onnx model for circle-impexp-test.
> [circle-mlir/tools-test] Introduce exec_onnx for impexp-test

- circle-mlir/circle-mlir/tools-test/circle-impexp-test/run_import_test.sh
This will fix run_import_test.sh comment that explains about this script.
> [circle-mlir/tools-test] Fix run_import_test.sh comment

- circle-mlir/circle-mlir/tools-test/CMakeLists.txt
This will include circle-impexp-test in tools-test.
> [circle-mlir/tools-test] Include circle-impexp-test

- circle-mlir/circle-mlir/tools-test/circle-impexp-test/CMakeLists.txt
- circle-mlir/circle-mlir/tools-test/circle-impexp-test/comp_circle_circle.py
This will introduce comp_circle_circle script
to compare two circle file execution results as value test.
> [circle-mlir/tools-test] Introduce comp_circle_circle

- circle-mlir/circle-mlir/tools-test/circle-impexp-test/CMakeLists.txt
- circle-mlir/circle-mlir/tools-test/circle-impexp-test/test.lst
This will introduce initial test.lst filr for circle-impexp-test.
> [circle-mlir/tools-test] Introduce initial test.lst

- circle-mlir/circle-mlir/tools-test/circle-impexp-test/run_value_test.sh
This will implement run_value_test script to execute value tests.
> [circle-mlir/tools-test] Implement run_value_test

- circle-mlir/models/unit/Transpose_F32_R4_pm/__init__.py
This will introduce unit test model for Transpose conversion with permute().
> [circle-mlir] More unit test model for Transpose

- circle-mlir/circle-mlir/lib/pass/src/ConvertONNXToCirclePass.cpp
- circle-mlir/circle-mlir/lib/pass/src/ops/TransposeOp.h
This will enable conversion of TransposeOp.
> [circle-mlir/pass] Enable Transpose conversion

- circle-mlir/models/unit/Reshape_F32_R4_1/__init__.py
- circle-mlir/models/unit/Reshape_F32_R4_2/__init__.py
- circle-mlir/models/unit/Reshape_F32_R4_3/__init__.py
- circle-mlir/models/unit/Reshape_F32_R4_4/__init__.py
- circle-mlir/models/unit/Reshape_F32_R4_5/__init__.py
- circle-mlir/models/unit/Reshape_F32_R4_6/__init__.py
- circle-mlir/models/unit/Shape_F32_R4/__init__.py
This will introduce unit test models for Reshape and Shape Ops.
> [circle-mlir/models] Unit test models for Reshape and Shape

- circle-mlir/circle-mlir/lib/dialect/mlir/CircleOps.td
- circle-mlir/circle-mlir/lib/dialect/src/CircleDialect.cpp
- circle-mlir/circle-mlir/lib/dialect/src/ShapeInference.cpp
- circle-mlir/circle-mlir/lib/dialect/src/ops/ReshapeOp.h
- circle-mlir/circle-mlir/lib/dialect/src/ops/ShapeOp.h
This will enable IRs for ReshapeOp and ShapeOp.
> [circle-mlir/dialect] Enable IRs for ReshapeOp, ShapeOp

- circle-mlir/models/unit/Pad_Constant2d_F32_R4/__init__.py
- circle-mlir/models/unit/Pad_Constant2d_F32_R4_1/__init__.py
- circle-mlir/models/unit/Pad_Constant2d_F32_R4_t4/__init__.py
- circle-mlir/models/unit/Pad_Constant2d_F32_R4_t8/__init__.py
- circle-mlir/models/unit/Pad_Constant2d_F32_R4_v14/__init__.py
This will introduce unit tests for PadOp with constant.
> [circle-mlir/models] Introduce Pad_Constant2d

- circle-mlir/circle-mlir/lib/pass/src/ConvertONNXToCirclePass.cpp
- circle-mlir/circle-mlir/lib/pass/src/ops/ReshapeOp.h
- circle-mlir/circle-mlir/lib/pass/src/ops/ShapeOp.h
This will enable conversion of ReshapeOp and ShapeOp.
> [circle-mlir/pass] Enable ReshapeOp and ShapeOp

- circle-mlir/circle-mlir/lib/pass/src/ConvertHelper.cpp
- circle-mlir/circle-mlir/lib/pass/src/ConvertHelper.h
This will add some helper methods with TransposeOp.
> [circle-mlir/pass] Introduce helpers with TransposeOp

- circle-mlir/circle-mlir/lib/pass/src/ConvertONNXToCirclePass.cpp
- circle-mlir/circle-mlir/lib/pass/src/ops/NoneOp.h
This will enable to convert ONNXNoneOp to circle NoValueOp.
> [circle-mlir/pass] Convert NoneOp

- circle-mlir/circle-mlir/lib/dialect/mlir/CircleOps.td
- circle-mlir/circle-mlir/lib/dialect/src/CircleDialect.cpp
- circle-mlir/circle-mlir/lib/dialect/src/ShapeInference.cpp
- circle-mlir/circle-mlir/lib/dialect/src/ops/PadOp.h
This will introduce IR for PadOp.
> [circle-mlir/dialect] Introduce IR for PadOp

- circle-mlir/circle-mlir/tools-test/onnx2circle-models/test.lst
- circle-mlir/circle-mlir/tools-test/onnx2circle-value-test/test.lst
This will enable tests for ReshapeOp and ShapeOp.
> [circle-mlir/tools-test] Enable ReshapeOp and ShapeOp

- circle-mlir/circle-mlir/tools-test/CMakeLists.txt
- circle-mlir/circle-mlir/tools-test/onnx2circle-rewrite-test/CMakeLists.txt
- circle-mlir/circle-mlir/tools-test/onnx2circle-rewrite-test/README.md
- circle-mlir/circle-mlir/tools-test/onnx2circle-rewrite-test/check_circle_ops.py
- circle-mlir/circle-mlir/tools-test/onnx2circle-rewrite-test/run_circle_ops_test.sh
- circle-mlir/circle-mlir/tools-test/onnx2circle-rewrite-test/test.lst
This will introduce initial circle-rewrite-test to check rewriting circle graph works expected.
> [circle-mlir/tools-test] Introduce initial rewrite-test

- circle-mlir/circle-mlir/lib/dialect/mlir/CircleOps.td
- circle-mlir/circle-mlir/lib/dialect/src/CircleDialect.cpp
- circle-mlir/circle-mlir/lib/dialect/src/ShapeInference.cpp
- circle-mlir/circle-mlir/lib/dialect/src/ops/Conv2DOp.h
This will introduce IR for Conv2DOp.
> [circle-mlir/dialect] Introduce IR for Conv2D

- circle-mlir/circle-mlir/lib/pass/src/ConvertONNXToCirclePass.cpp
- circle-mlir/circle-mlir/lib/pass/src/ops/PadOp.h
This will enable conversion of ONNXPadOp to circle PadOp.
> [circle-mlir/pass] Convert PadOp

- circle-mlir/circle-mlir/lib/pass/src/ConvertONNXToCirclePass.cpp
- circle-mlir/circle-mlir/lib/pass/src/ops/ConvOp.h
This will enable to convert ONNXConvOp to circle Conv2DOp.
> [circle-mlir/pass] Convert Conv2DOp

- circle-mlir/models/mlir/Conv2d_F32_R4_us.circle.mlir
- circle-mlir/models/mlir/Pad_F32_R4_us.circle.mlir
This will introduce mlir unit test models for Conv2DOp, PadOp with unknown shape.
> [circle-mlir/models] Introduce Conv2D, Pad with unknown shape

- circle-mlir/README.md
In this PR, some refinements will be suggested to make the sentence sound a little bit natural.
---
- for https://github.com/Samsung/ONE/issues/14607#issuecomment-2646733235
- from the suggestions of https://github.com/Samsung/ONE/pull/14843#pullrequestreview-2680901391
> [circle-mlir] Revise README.md

- compiler/luci/service/src/Nodes/CircleAdd.cpp
- compiler/luci/service/src/Nodes/CircleBatchMatMul.cpp
- compiler/luci/service/src/Nodes/CircleConcatenation.cpp
- compiler/luci/service/src/Nodes/CircleDiv.cpp
- compiler/luci/service/src/Nodes/CircleFullyConnected.cpp
- compiler/luci/service/src/Nodes/CircleLogistic.cpp
- compiler/luci/service/src/Nodes/CircleMul.cpp
- compiler/luci/service/src/Nodes/CircleNeg.cpp
- compiler/luci/service/src/Nodes/CircleQuantize.cpp
- compiler/luci/service/src/Nodes/CircleRange.cpp
- compiler/luci/service/src/Nodes/CircleReshape.cpp
- compiler/luci/service/src/Nodes/CircleRsqrt.cpp
- compiler/luci/service/src/Nodes/CircleSoftmax.cpp
- compiler/luci/service/src/Nodes/CircleStridedSlice.cpp
This will tidy unnecessary line between namespace braces.
> [luci/service] Tidy unnecessary line

- circle-mlir/README.md
This will add referenced TensorFlow version in README.
> [circle-mlir] Revise README with TF

- circle-mlir/CMakeLists.txt
This will fix CMakeLists comment about externals local install path.
> [circle-mlir] Fix CMakeLists comment

- circle-mlir/Makefile.sample
- circle-mlir/README.md
This will revise Makefile.sample and README with build with Docker image.
> [circle-mlir] Build with Docker image

- circle-mlir/circle-mlir/tools/onnx2circle/test.lst
This will add more tests for AddOp test coverage.
> [circle-mlir/tools] AddOp tests for onnx2circle

- circle-mlir/models/unit/Div_F32_R4_C1/__init__.py
- circle-mlir/models/unit/Mul_F32_R4/__init__.py
- circle-mlir/models/unit/Sub_F32_R4/__init__.py
This will introduce test models for Div, Mul and Sub Ops.
> [circle-mlir/models] Test models for Div,Mul,Sub

- circle-mlir/circle-mlir/tools/onnx2circle/test.lst
- circle-mlir/models/mlir/Div_F32_us.circle.mlir
- circle-mlir/models/mlir/Mul_F32_R2_ds.circle.mlir
- circle-mlir/models/mlir/Mul_F32_R2_us.circle.mlir
- circle-mlir/models/mlir/Mul_F32_us.circle.mlir
- circle-mlir/models/mlir/Sub_F32_us.circle.mlir
This will enable dynamic/unknown shape inference test for Div, Mul and Sub Ops.
> [circle-mlir/tools] Test of shape-inf for Div,Mul,Sub

- circle-mlir/models/unit/Rsqrt_F32_R4/__init__.py
- circle-mlir/models/unit/Sqrt_F32_R4/__init__.py
- circle-mlir/models/unit/Tanh_F32_R4/__init__.py
This will add test models for Rsqrt, Sqrt and Tanh Ops.
> [circle-mlir/models] Add Sqrt and others

- circle-mlir/circle-mlir/lib/dialect/mlir/CircleOps.td
- circle-mlir/circle-mlir/lib/dialect/src/CircleDialect.cpp
- circle-mlir/circle-mlir/lib/dialect/src/ShapeInference.cpp
- circle-mlir/circle-mlir/lib/dialect/src/ops/SqrtOp.h
This will add IR for Sqrt and Tanh Ops.
> [circle-mlir/dialect] Add IR for Sqrt, Tanh

- circle-mlir/circle-mlir/lib/dialect/mlir/CircleOps.td
- circle-mlir/circle-mlir/lib/dialect/src/CircleDialect.cpp
- circle-mlir/circle-mlir/lib/dialect/src/ShapeInference.cpp
- circle-mlir/circle-mlir/lib/dialect/src/ops/PReluOp.h
This will add IR for ReLU, LeakyReLU, PReLU, MiniMum and Maximum Ops.
> [circle-mlir/dialect] Add IR for ReLU and others

- circle-mlir/models/unit/LeakyReLU_F32_R4/__init__.py
- circle-mlir/models/unit/LeakyReLU_F32_R4_ns/__init__.py
- circle-mlir/models/unit/PReLU_F32_R4/__init__.py
- circle-mlir/models/unit/ReLU6_F32_R4/__init__.py
- circle-mlir/models/unit/ReLU_F32_R4/__init__.py
This will add test models for LeakyReLU, PReLU, ReLU and ReLU6 Ops.
> [circle-mlir/models] Add ReLU and others

- circle-mlir/circle-mlir/lib/pass/src/ConvertONNXToCirclePass.cpp
- circle-mlir/circle-mlir/lib/pass/src/ops/ClipOp.h
- circle-mlir/circle-mlir/lib/pass/src/ops/LeakyReluOp.h
- circle-mlir/circle-mlir/lib/pass/src/ops/PReluOp.h
- circle-mlir/circle-mlir/lib/pass/src/ops/ReluOp.h
This will enable conversion of Clip, LeakyReLU, PReLU and ReLU Ops.
> [circle-mlir/pass] Enable conversion of ReLU and others

- circle-mlir/circle-mlir/lib/pass/src/ConvertONNXToCirclePass.cpp
- circle-mlir/circle-mlir/lib/pass/src/ops/SqrtOp.h
- circle-mlir/circle-mlir/lib/pass/src/ops/TanhOp.h
This will enable conversion of Sqrt and Tanh Ops.
> [circle-mlir/pass] Enable conversion of Sqrt, Tanh

- circle-mlir/circle-mlir/lib/dialect/mlir/CircleOps.td
- circle-mlir/circle-mlir/lib/dialect/src/CircleDialect.cpp
- circle-mlir/circle-mlir/lib/dialect/src/ops/RsqrtOp.h
This will introduce RsqrtOp circle IR.
> [circle-mlir/dialect] Introduce RsqrtOp IR

- circle-mlir/circle-mlir/tools/onnx2circle/test.lst
- circle-mlir/models/mlir/Rsqrt_F32_R1_C1.circle.mlir
This will add test coverage for Rsqrt Op.
> [circle-mlir/tools] Test coverage for Rsqrt

- circle-mlir/models/unit/ReduceProd_F32_R2/__init__.py
- circle-mlir/models/unit/ReduceSum_F32_R2/__init__.py
- circle-mlir/models/unit/ReduceSum_F32_R2_V11/__init__.py
- circle-mlir/models/unit/ReduceSum_F32_R2_d0/__init__.py
- circle-mlir/models/unit/ReduceSum_F32_R2_d1/__init__.py
- circle-mlir/models/unit/ReduceSum_F32_R2_d1_kd/__init__.py
- circle-mlir/models/unit/ReduceSum_F32_R4/__init__.py
This will introduce test models for ReduceProd and ReduceSum Ops.
> [circle-mlir/models] Introduce ReduceProd,ReduceSum

- circle-mlir/models/unit/ArgMax_F32_R1_v11/__init__.py
- circle-mlir/models/unit/ArgMax_F32_R2_v11_d1/__init__.py
- circle-mlir/models/unit/ArgMax_F32_R2_v11_d1_kd/__init__.py
- circle-mlir/models/unit/ArgMax_F32_R4_d1_v11/__init__.py
- circle-mlir/models/unit/ArgMax_F32_R4_kd_v11/__init__.py
- circle-mlir/models/unit/ArgMax_F32_R4_v11/__init__.py
This will introduce test models for ArgMax Op.
> [circle-mlir/models] Introduce ArgMax

- circle-mlir/circle-mlir/lib/dialect/mlir/CircleOps.td
This will introduce IR for ArgMaxOp.
> [circle-mlir/dialect] Introduce IR for ArgMax

- circle-mlir/circle-mlir/lib/dialect/mlir/CircleOps.td
- circle-mlir/circle-mlir/lib/dialect/src/ShapeInference.cpp
This will introduce IR for Mean Op.
> [circle-mlir/dialect] Introduce IR for Mean

- circle-mlir/circle-mlir/lib/dialect/mlir/CircleOps.td
This will introduce IR for Sum Op.
> [circle-mlir/dialect] Introduce IR for Sum

- circle-mlir/circle-mlir/lib/pass/src/ConvertONNXToCirclePass.cpp
- circle-mlir/circle-mlir/lib/pass/src/ops/ArgMaxOp.h
This will enable conversion of ArgMax Op.
> [circle-mlir/pass] Enable ArgMax conversion

- circle-mlir/circle-mlir/lib/pass/src/ConvertONNXToCirclePass.cpp
- circle-mlir/circle-mlir/lib/pass/src/ops/ReduceMeanOp.h
This will enable conversion of ReduceMean Op.
> [circle-mlir/pass] Enable ReduceMean conversion

- circle-mlir/circle-mlir/lib/pass/src/ConvertONNXToCirclePass.cpp
- circle-mlir/circle-mlir/lib/pass/src/ops/ReduceProdOp.h
- circle-mlir/circle-mlir/lib/pass/src/ops/ReduceSumOp.h
This will enable conversion of ReduceProd and ReduceSum Ops.
> [circle-mlir/pass] Enable ReduceProd,ReduceSum conversion

- circle-mlir/circle-mlir/tools/onnx2circle/test.lst
- circle-mlir/models/mlir/ReduceProd_I64_R1_1.circle.mlir
- circle-mlir/models/mlir/ReduceProd_I64_R1_3.circle.mlir
This will add test coverage for ReduceProd Op.
> [circle-mlir/tools] Add test coverage for ReduceProd

- circle-mlir/circle-mlir/tools-test/circle-impexp-test/test.lst
- circle-mlir/circle-mlir/tools-test/onnx2circle-models/test.lst
- circle-mlir/circle-mlir/tools-test/onnx2circle-value-test/test.lst
This will enable conversion, value and import/export tests for ArgMax Op.
> [circle-mlir/tools-test] Enable tests for ArgMax

- circle-mlir/models/unit/Cos_F32_R4/__init__.py
- circle-mlir/models/unit/CumSum_F32_R4_1/__init__.py
- circle-mlir/models/unit/CumSum_F32_R4_2/__init__.py
This will add test models for Cos and Cumsum Ops.
> [circle-mlir/models] Add Cos, Cumsum

- circle-mlir/models/unit/Gemm_F32_R2/__init__.py
- circle-mlir/models/unit/Gemm_F32_R2_C1/__init__.py
- circle-mlir/models/unit/Gemm_F32_R2_a0b1/__init__.py
- circle-mlir/models/unit/Gemm_F32_R2_a1b0/__init__.py
- circle-mlir/models/unit/Gemm_F32_R2_a1b1/__init__.py
- circle-mlir/models/unit/Gemm_F32_R2_a1b1_ta/__init__.py
- circle-mlir/models/unit/Gemm_F32_R2_a1b1_tb/__init__.py
- circle-mlir/models/unit/Gemm_F32_R2_ahbh/__init__.py
- circle-mlir/models/unit/Gemm_F32_R2_nobias/__init__.py
This will add test models for Gemm Op.
> [circle-mlir/models] Add Gemm

- circle-mlir/models/unit/MatMul_F32_R2_hw/__init__.py
- circle-mlir/models/unit/MatMul_F32_R3_11w/__init__.py
- circle-mlir/models/unit/MatMul_F32_R3_1hw/__init__.py
- circle-mlir/models/unit/MatMul_F32_R3_1hw_nobias/__init__.py
- circle-mlir/models/unit/MatMul_F32_R3_c1w/__init__.py
- circle-mlir/models/unit/MatMul_F32_R3_chw/__init__.py
- circle-mlir/models/unit/MatMul_F32_R4_111w_C11hw/__init__.py
- circle-mlir/models/unit/MatMul_F32_R4_11hw/__init__.py
- circle-mlir/models/unit/MatMul_F32_R4_11hw_nobias/__init__.py
- circle-mlir/models/unit/MatMul_F32_R4_1chw/__init__.py
- circle-mlir/models/unit/MatMul_F32_R4_nchw_nobias/__init__.py
This will add test models for MatMul Op.
> [circle-mlir/models] Add MatMul

- circle-mlir/circle-mlir/lib/dialect/mlir/CircleOps.td
- circle-mlir/circle-mlir/lib/dialect/src/CircleDialect.cpp
- circle-mlir/circle-mlir/lib/dialect/src/ShapeInference.cpp
- circle-mlir/circle-mlir/lib/dialect/src/ops/CosOp.h
This will introduce IRs for Cos and CumSum Ops.
> [circle-mlir/dialect] Introduce IRs for Cos,CumSum

- circle-mlir/circle-mlir/lib/dialect/mlir/CircleOps.td
- circle-mlir/circle-mlir/lib/dialect/src/CircleDialect.cpp
- circle-mlir/circle-mlir/lib/dialect/src/ShapeInference.cpp
- circle-mlir/circle-mlir/lib/dialect/src/ops/FullyConnectedOp.h
This will introduce IR for FullyConnected Op.
> [circle-mlir/dialect] Introduce IR for FullyConnected

- circle-mlir/circle-mlir/lib/pass/src/ConvertONNXToCirclePass.cpp
- circle-mlir/circle-mlir/lib/pass/src/ops/CosOp.h
- circle-mlir/circle-mlir/lib/pass/src/ops/CumsumOp.h
This will enable conversion of Cos and CumSum Ops.
> [circle-mlir/pass] Enable Cos,CumSum conversion

- circle-mlir/circle-mlir/lib/pass/src/ConvertONNXToCirclePass.cpp
- circle-mlir/circle-mlir/lib/pass/src/ops/GemmOp.h
- circle-mlir/circle-mlir/lib/pass/src/ops/MatMulOp.h
This will enable conversion of Gemm and MatMul Ops.
> [circle-mlir/pass] Enable Gemm,MatMul conversion

- circle-mlir/models/unit/Equal_F32_R4/__init__.py
- circle-mlir/models/unit/Equal_I64_R1/__init__.py
- circle-mlir/models/unit/Greater_F32_R2_C1/__init__.py
- circle-mlir/models/unit/Greater_F32_R4/__init__.py
This will add test models for Equal and Greater Ops.
> [circle-mlir/models] Add Equal,Greater

- circle-mlir/models/unit/Exp_F32_R0/__init__.py
- circle-mlir/models/unit/Exp_F32_R4/__init__.py
This will add test models for Exp Op.
> [circle-mlir/models] Add Exp

- circle-mlir/circle-mlir/lib/dialect/mlir/CircleOps.td
- circle-mlir/circle-mlir/lib/dialect/src/CircleDialect.cpp
- circle-mlir/circle-mlir/lib/dialect/src/ops/EqualOp.h
This will introduce IRs for Equal and Greater Ops.
> [circle-mlir/dialect] Introduce IRs for Equal,Greather

- circle-mlir/circle-mlir/lib/dialect/mlir/CircleOps.td
This will introduce IR for Exp Op.
> [circle-mlir/dialect] Introducr IR for Exp

- circle-mlir/circle-mlir/lib/dialect/mlir/CircleOps.td
- circle-mlir/circle-mlir/lib/dialect/src/CircleDialect.cpp
- circle-mlir/circle-mlir/lib/dialect/src/ops/CastOp.h
This introduces the IR for Cast operation.
> [circle-mlir/dialect] Introduce IR for Cast Op

- circle-mlir/circle-mlir/lib/pass/src/ConvertONNXToCirclePass.cpp
- circle-mlir/circle-mlir/lib/pass/src/ops/EqualOp.h
- circle-mlir/circle-mlir/lib/pass/src/ops/GreaterOp.h
This will enable conversion of Equal and Greater Ops.
> [circle-mlir/pass] Enable Equal,Greater conversion

- circle-mlir/circle-mlir/lib/pass/src/ConvertONNXToCirclePass.cpp
- circle-mlir/circle-mlir/lib/pass/src/ops/ExpOp.h
This will enable conversion of Exp Op.
> [circle-mlir/pass] Enable Exp conversion

- runtime/onert/core/src/compiler/ShapeValidator.cc
- runtime/tests/nnfw_api/src/GenModelTests/one_op_tests/Gather.test.cc
- Fix too strong shape restriction
- Add test case for rank > 4
> [onert] Ease restriction on shape validation

- circle-mlir/models/unit/Neg_F32_R4/__init__.py
- circle-mlir/models/unit/Not_F32_R4/__init__.py
This will add test models for Neg and Not Ops.
> [circle-mlir/models] Add Neg,Not

- circle-mlir/circle-mlir/lib/dialect/mlir/CircleOps.td
- circle-mlir/circle-mlir/lib/dialect/src/CircleDialect.cpp
- circle-mlir/circle-mlir/lib/dialect/src/ops/NegOp.h
This will introduce IRs for Neg and Not Ops.
> [circle-mlir/dialect] Introduce IRs for Neg,Not

- circle-mlir/circle-mlir/lib/dialect/mlir/CircleOps.td
This will introdcue IR for BatchMatMul Op.
> [circle-mlir/dialect] Introduce BatchMatMul IR

- circle-mlir/circle-mlir/tools/onnx2circle/TestModels.cmake
- circle-mlir/circle-mlir/tools/onnx2circle/test.lst
- circle-mlir/models/mlir/Custom_F32.circle.neg.mlir
This will introduce negative test of Custom Op for test coverage.
> [circle-mlir/tools] Negative test for Custom

- circle-mlir/circle-mlir/lib/pass/src/ops/MatMulOp.h
This will enable to convert MatMul to BatchMatMul for some case.
> [circle-mlir/pass] Enable to convert to BatchMatMul

- circle-mlir/circle-mlir/lib/dialect/mlir/CircleOps.td
- circle-mlir/circle-mlir/lib/dialect/src/CircleDialect.cpp
- circle-mlir/circle-mlir/lib/dialect/src/ops/SelectOp.h
This introduces the IR fo Select operation.
> [circle-mlir/dialect] Introduce IR for Select Op

- circle-mlir/circle-mlir/lib/dialect/mlir/CircleOps.td
- circle-mlir/circle-mlir/lib/dialect/src/CircleDialect.cpp
- circle-mlir/circle-mlir/lib/dialect/src/ops/SliceOp.h
This introduces the IR for Slice operation.
> [circle-mlir/dialect] Introduce IR for Slice Op

- circle-mlir/circle-mlir/lib/dialect/mlir/CircleOps.td
- circle-mlir/circle-mlir/lib/dialect/src/CircleDialect.cpp
- circle-mlir/circle-mlir/lib/dialect/src/ShapeInference.cpp
- circle-mlir/circle-mlir/lib/dialect/src/ops/StridedSliceOp.h
This introduces the IR for StridedSlice operation.
> [circle-mlir/dialect] Introduce IR for StridedSlice Op

- circle-mlir/circle-mlir/lib/pass/src/ConvertONNXToCirclePass.cpp
- circle-mlir/circle-mlir/lib/pass/src/ops/NegOp.h
- circle-mlir/circle-mlir/lib/pass/src/ops/NotOp.h
This will enable conversion of Neg and Not Ops.
> [circle-mlir/pass] Enable conversion of Neg,Not

- circle-mlir/circle-mlir/lib/pass/src/ConvertONNXToCirclePass.cpp
- circle-mlir/circle-mlir/lib/pass/src/ops/SliceOp.h
This enables conversion of the Slice operation.
> [circle-mlir/pass] Add the pass for Slice Op

- circle-mlir/models/unit/AvgPool2d_F32_R4/__init__.py
- circle-mlir/models/unit/AvgPool2d_F32_R4_p1/__init__.py
- circle-mlir/models/unit/AvgPool2d_F32_R4_p1_v11/__init__.py
- circle-mlir/models/unit/MaxPool2d_F32_R4/__init__.py
- circle-mlir/models/unit/MaxPool2d_F32_R4_k12/__init__.py
- circle-mlir/models/unit/MaxPool2d_F32_R4_p1/__init__.py
- circle-mlir/models/unit/MaxPool2d_F32_R4_p23/__init__.py
- circle-mlir/models/unit/MaxPool2d_F32_R4_p31/__init__.py
This will introduce AvgPool2d and MaxPool2d test models.
> [circle-mlir/models] Introduce AvgPool2d and MaxPool2d models

- circle-mlir/circle-mlir/lib/dialect/mlir/CircleOps.td
- circle-mlir/circle-mlir/lib/dialect/src/ShapeInference.cpp
This will introduce AveragePool2D and MaxPool2D Op IRs and related methods.
> [circle-mlir/dialect] Introduce AveragePool2D and MaxPool2D IRs

- circle-mlir/circle-mlir/lib/dialect/mlir/CircleOps.td
- circle-mlir/circle-mlir/lib/dialect/src/CircleDialect.cpp
- circle-mlir/circle-mlir/lib/dialect/src/ops/PadV2Op.h
This will introduce PadV2 Op IR and related method.
> [circle-mlir/dialect] Introduce PadV2 IR

- circle-mlir/circle-mlir/lib/pass/src/ConvertONNXToCirclePass.cpp
- circle-mlir/circle-mlir/lib/pass/src/ops/AveragePoolOp.h
- circle-mlir/circle-mlir/lib/pass/src/ops/MaxPoolSingleOutOp.h
This will enable conversion of AveragePool and MaxPoolSingleOut Ops.
> [circle-mlir/pass] Enable conversion of Pool Ops

- circle-mlir/models/unit/LogSoftmax_F32_R2/__init__.py
- circle-mlir/models/unit/Log_F32_R2/__init__.py
- circle-mlir/models/unit/Log_F32_R4/__init__.py
- circle-mlir/models/unit/Sigmoid_F32_R2/__init__.py
- circle-mlir/models/unit/Sigmoid_F32_R4/__init__.py
- circle-mlir/models/unit/Softmax_F32_R2/__init__.py
- circle-mlir/models/unit/Softmax_F32_R2_v11/__init__.py
- circle-mlir/models/unit/Softmax_F32_R3/__init__.py
- circle-mlir/models/unit/Softmax_F32_R4/__init__.py
This will add test models for Log, LogSoftmax, Sigmoid and Softmax Ops.
> [circle-mlir/models] Add Log,LogSoftmax,Sigmode,Softmax

- circle-mlir/circle-mlir/lib/dialect/mlir/CircleRewrite.td
- circle-mlir/circle-mlir/lib/dialect/src/ops/LogOp.h
This will enable fuse of Log-Softmax to LogSoftmax single Op.
> [circle-mlir/dialect] Enable fuse of LogSoftmax

- circle-mlir/circle-mlir/lib/pass/src/ConvertONNXToCirclePass.cpp
- circle-mlir/circle-mlir/lib/pass/src/ops/LogOp.h
- circle-mlir/circle-mlir/lib/pass/src/ops/SigmoidOp.h
- circle-mlir/circle-mlir/lib/pass/src/ops/SoftmaxOp.h
This will enable conversion of Log, Sigmoid and Softmax Ops.
> [circle-mlir/pass] Enable Log,Sigmoid,Softmax

- runtime/tests/nnfw_api/lib/CircleGen.cc
- runtime/tests/nnfw_api/lib/CircleGen.h
- runtime/tests/nnfw_api/src/GenModelTests/one_op_tests/BatchMatMul.test.cc
This commit adds BatchMatMul nnfw_api OP test.
---
Draft: #14905
> [onert/test] Add BatchMatMul OP test

- circle-mlir/models/unit/ConvTranspose2d_F32_R4/__init__.py
- circle-mlir/models/unit/ConvTranspose2d_F32_R4_free/__init__.py
- circle-mlir/models/unit/ConvTranspose2d_F32_R4_k4s2/__init__.py
- circle-mlir/models/unit/ConvTranspose2d_F32_R4_k4s2p1/__init__.py
- circle-mlir/models/unit/ConvTranspose2d_F32_R4_nobias/__init__.py
- circle-mlir/models/unit/ConvTranspose2d_F32_R4_op01/__init__.py
- circle-mlir/models/unit/ConvTranspose2d_F32_R4_p10/__init__.py
- circle-mlir/models/unit/ConvTranspose2d_F32_R4_p11/__init__.py
- circle-mlir/models/unit/ConvTranspose2d_F32_R4_p11_nobias/__init__.py
This will introduce ConvTranspose2d test models.
> [circle-mlir/models] Introduce ConvTranspose2d

- circle-mlir/circle-mlir/lib/dialect/mlir/CircleOps.td
- circle-mlir/circle-mlir/lib/dialect/src/CircleDialect.cpp
- circle-mlir/circle-mlir/lib/dialect/src/ShapeInference.cpp
- circle-mlir/circle-mlir/lib/dialect/src/ops/DepthwiseConv2DOp.h
- circle-mlir/circle-mlir/lib/dialect/src/ops/TransposeConvOp.h
This will add DepthwiseConv2D and TransposeConv IRs and related methods.
> [circle-mlir/dialect] Add DepthwiseConv2D,TransposeConv IRs

- circle-mlir/circle-mlir/lib/pass/src/ConvertONNXToCirclePass.cpp
- circle-mlir/circle-mlir/lib/pass/src/ops/ConvOp.h
- circle-mlir/circle-mlir/lib/pass/src/ops/ConvTransposeOp.h
This will enable to convert to Conv with group to DepthwiseConv2DOp and ConvTranspose to TransposeConv.
> [circle-mlir/pass] Convert to DepthwiseConv2DOp,TransposeConv

- circle-mlir/circle-mlir/tools/onnx2circle/test.lst
- circle-mlir/models/mlir/DepthwiseConv2d_F32_R4_us.circle.mlir
This will add shape inference test fort DepwiseConv2d Op.
> [circle-mlir/tools] Shape-inf test for DepthwiseConv2d

- circle-mlir/models/unit/Expand_B_R4_D1/__init__.py
- circle-mlir/models/unit/Expand_F32_R2/__init__.py
- circle-mlir/models/unit/Expand_F32_R2_unk/__init__.py
- circle-mlir/models/unit/Expand_F32_R3/__init__.py
- circle-mlir/models/unit/Expand_F32_R4_D0/__init__.py
- circle-mlir/models/unit/Expand_F32_R4_D1/__init__.py
- circle-mlir/models/unit/Expand_F32_R4_D3/__init__.py
- circle-mlir/models/unit/Expand_F32_R4_I1/__init__.py
- circle-mlir/models/unit/Expand_F32_R4_k/__init__.py
- circle-mlir/models/unit/Expand_I64_R4_D3/__init__.py
This will add test models for Expand Op.
> [circle-mlir/models] Add Expand

- circle-mlir/models/unit/ConstantOfShape_F32_R1/__init__.py
- circle-mlir/models/unit/ConstantOfShape_F32_node/__init__.py
- circle-mlir/models/unit/ConstantOfShape_I64_R1/__init__.py
This will add test models for ConstantOfShape.
> [circle-mlir/models] Add ConstantOfShape

- circle-mlir/models/unit/Pad_Reflection2d_F32_R4/__init__.py
- circle-mlir/models/unit/Pad_Reflection2d_F32_R4_1/__init__.py
This will add test models for Pad_Reflection2d.
> [circle-mlir/models] Add Pad_Reflection2d

- circle-mlir/models/unit/Where_F32_R3_bc/__init__.py
- circle-mlir/models/unit/Where_F32_R4/__init__.py
This will add test models for Where Op.
> [circle-mlir/models] Add Where

- circle-mlir/circle-mlir/lib/dialect/mlir/CircleOps.td
- circle-mlir/circle-mlir/lib/dialect/src/CircleDialect.cpp
- circle-mlir/circle-mlir/lib/dialect/src/ShapeInference.cpp
- circle-mlir/circle-mlir/lib/dialect/src/ops/ConcatenationOp.h
This will introduce Concatenation Op IR and necessary methods.
> [circle-mlir/dialect] Introduce Concatenationi Op IR

- circle-mlir/circle-mlir/lib/dialect/mlir/CircleOps.td
- circle-mlir/circle-mlir/lib/dialect/src/ShapeInference.cpp
This will introduce MirrorPad Op IR and necessary methods.
> [circle-mlir/dialect] Introduce MirrorPad Op IR

- circle-mlir/circle-mlir/lib/pass/src/ConvertONNXToCirclePass.cpp
- circle-mlir/circle-mlir/lib/pass/src/ops/WhereOp.h
This will enable to convert Where Op to Select or SelevtV2 Op.
> [circle-mlir/pass] Convert Where

- circle-mlir/circle-mlir/lib/dialect/mlir/CircleOps.td
- circle-mlir/circle-mlir/lib/dialect/src/CircleDialect.cpp
- circle-mlir/circle-mlir/lib/dialect/src/ops/ExpandOnnxOp.h
This will introduce ExpandOnnx Op IR and necessary methods.
> [circle-mlir/dialect] Introduce ExpandOnnx Op IR

- circle-mlir/circle-mlir/lib/pass/src/ConvertONNXToCirclePass.cpp
- circle-mlir/circle-mlir/lib/pass/src/ops/ConcatOp.h
This will enable to convert ConcatOp.
> [circle-mlir/pass] Convert ConcatOp

- circle-mlir/circle-mlir/lib/pass/src/ops/PadOp.h
This will enable to convert reflect mode Pad to MirrorPad.
> [circle-mlir/pass] Convert to MirrorPad

- circle-mlir/circle-mlir/lib/pass/src/ConvertONNXToCirclePass.cpp
- circle-mlir/circle-mlir/lib/pass/src/ops/ExpandOp.h
This will enable to convert Expand Op to ExpandOnnx Op.
> [circle-mlir/pass] Convert Expand Op

- circle-mlir/circle-mlir/lib/pass/src/ConvertONNXToCirclePass.cpp
- circle-mlir/circle-mlir/lib/pass/src/ops/ConstantOfShapeOp.h
This will enable to convert ConstantOfShape Op.
- this op input is a single value and a shape that will produce a tensor with the value of that shape.
> [circle-mlir/pass] Convert ConstantOfShape

- circle-mlir/circle-mlir/tools/onnx2circle/test.lst
- circle-mlir/models/mlir/Concat_F32_R4_R3_d1.circle.neg.mlir
- circle-mlir/models/mlir/Concat_F32_R4_d1_0.circle.neg.mlir
- circle-mlir/models/mlir/Concat_F32_R4_d1_1.circle.neg.mlir
- circle-mlir/models/mlir/Concat_F32_R4_dn3.circle.mlir
- circle-mlir/models/mlir/Concat_F32_R4_dn5.circle.neg.mlir
- circle-mlir/models/mlir/Concat_F32_R4_ds.circle.mlir
- circle-mlir/models/mlir/Concat_F32_R4_empty_0.circle.mlir
- circle-mlir/models/mlir/Concat_F32_R4_empty_1.circle.mlir
- circle-mlir/models/mlir/Concat_F32_R4_us.circle.mlir
This will add unit tests of coverage and shape inference of Concatenation Op.
> [circle-mlir] Add unit test of Concat

- circle-mlir/models/unit/Floor_F32_R4/__init__.py
This will introduce test model for Floor Op.
> [circle-mlir/models] Introduce Floor

- circle-mlir/circle-mlir/lib/dialect/mlir/CircleOps.td
- circle-mlir/circle-mlir/lib/dialect/src/CircleDialect.cpp
- circle-mlir/circle-mlir/lib/dialect/src/ops/FloorOp.h
This will introduce IRs for Floor and FloorMod and necessary methods.
> [circle-mlir/dialect] Introduce Floor,FloorMod

- circle-mlir/circle-mlir/lib/pass/src/ConvertONNXToCirclePass.cpp
- circle-mlir/circle-mlir/lib/pass/src/ops/FloorOp.h
This will enable to convert Floor Op.
> [circle-mlir/pass] Convert Floor Op

- circle-mlir/circle-mlir/lib/dialect/mlir/CircleOps.td
- circle-mlir/circle-mlir/lib/dialect/src/CircleDialect.cpp
- circle-mlir/circle-mlir/lib/dialect/src/ShapeInference.cpp
- circle-mlir/circle-mlir/lib/dialect/src/ops/ResizeOnnxOp.h
This will introduce ResizeBilinear, ResizeNearestNeighbor and temporary ResizeOnnx IR.
> [circle-mlir/dialect] Introduce Resize Related IRs

- circle-mlir/models/unit/Resize_F32_R4/__init__.py
- circle-mlir/models/unit/Resize_F32_R4_2/__init__.py
- circle-mlir/models/unit/Resize_F32_R4_linear/__init__.py
- circle-mlir/models/unit/Resize_F32_R4_linear_v11/__init__.py
- circle-mlir/models/unit/Resize_F32_R4_nearest/__init__.py
- circle-mlir/models/unit/Resize_F32_R4_unk/__init__.py
This will add Resize related test models.
> [circle-mlir/models] Add Resize related

- circle-mlir/circle-mlir/lib/pass/src/ConvertONNXToCirclePass.cpp
- circle-mlir/circle-mlir/lib/pass/src/ops/ResizeOp.h
This will enable conversion of Resize Op.
> [circle-mlir/pass] Enable Resize

- circle-mlir/circle-mlir/lib/pass/src/RewriteCirclePass.cpp
- circle-mlir/circle-mlir/lib/pass/src/opt/ConvertResizeNearestSize32.h
This will add rewrite size of ResizeNearestNeighbor to I32 for luci compatibility.
> [circle-mlir/pass] Rewrite size of ResizeNearestNeighbor

- circle-mlir/models/unit/Hardswish_F32_R4/__init__.py
- circle-mlir/models/unit/InstanceNormalization_F32_R3/__init__.py
- circle-mlir/models/unit/InstanceNormalization_F32_R4/__init__.py
- circle-mlir/models/unit/InstanceNormalization_F32_R4_rand/__init__.py
This will introduce test models for Hardswish and InstanceNormalization Op.
> [circle-mlir/models] Introduce Hardswish,InstanceNormalization

- circle-mlir/models/unit/Unsqueeze_F32_R0/__init__.py
- circle-mlir/models/unit/Unsqueeze_F32_R0_v11/__init__.py
- circle-mlir/models/unit/Unsqueeze_F32_R2_d01_v11/__init__.py
- circle-mlir/models/unit/Unsqueeze_F32_R2_d02_v11/__init__.py
- circle-mlir/models/unit/Unsqueeze_F32_R2_d13_v11/__init__.py
- circle-mlir/models/unit/Unsqueeze_F32_R3_d0/__init__.py
- circle-mlir/models/unit/Unsqueeze_F32_R3_d3/__init__.py
- circle-mlir/models/unit/Unsqueeze_F32_R3_d3_v11/__init__.py
- circle-mlir/models/unit/Unsqueeze_F32_R3_d_1/__init__.py
This will introduce test models for Unsqueeze Op.
> [circle-mlir/models] Introduce Unsqueeze

- circle-mlir/circle-mlir/lib/dialect/mlir/CircleOps.td
- circle-mlir/circle-mlir/lib/dialect/src/ShapeInference.cpp
This will add HardSwish and InstanceNorm IRs and necessary methods.
> [circle-mlir/dialect] Add HardSwish.InstanceNorm IRs

- circle-mlir/circle-mlir/lib/pass/src/ConvertONNXToCirclePass.cpp
- circle-mlir/circle-mlir/lib/pass/src/ops/HardSwishOp.h
- circle-mlir/circle-mlir/lib/pass/src/ops/InstanceNormalizationOp.h
This will enable to convert HardSwish and InstanceNormalization Ops.
> [circle-mlir/pass] Convert HardSwish,InstanceNormalizartion

- circle-mlir/models/unit/Pow_F32_R2/__init__.py
- circle-mlir/models/unit/Pow_F32_R2_3/__init__.py
- circle-mlir/models/unit/Pow_F32_R4/__init__.py
- circle-mlir/models/unit/Sin_F32_R4/__init__.py
This will introduce test models for Pow and Sin Ops.
> [circle-mlir/models] Introduce Pow,Sin

- circle-mlir/models/unit/Gather_F32_R2/__init__.py
- circle-mlir/models/unit/Gather_F32_R2_C1/__init__.py
- circle-mlir/models/unit/Gather_F32_R2_C1_2/__init__.py
This will introduce test models for Gather Op.
> [circle-mlir/models] Introduce Gather

- circle-mlir/circle-mlir/lib/dialect/mlir/CircleOps.td
- circle-mlir/circle-mlir/lib/dialect/src/CircleDialect.cpp
- circle-mlir/circle-mlir/lib/dialect/src/ops/GatherOp.h
This will add Gather IR and necessary methods.
> [circle-mlir/dialect] Add Gather IR

- circle-mlir/circle-mlir/lib/pass/src/ConvertONNXToCirclePass.cpp
- circle-mlir/circle-mlir/lib/pass/src/ops/PowOp.h
- circle-mlir/circle-mlir/lib/pass/src/ops/SinOp.h
This will enable to convert Pow and Sin Ops.
> [circle-mlir/pass] Convert Pow,Sin Ops

- circle-mlir/circle-mlir/lib/dialect/mlir/CircleOps.td
- circle-mlir/circle-mlir/lib/pass/src/ops/SliceOp.h
This will tidy internal references and update to simple notes.
> [circle-mlir] Tidy internal references

- circle-mlir/models/unit/Split_F32_R4/__init__.py
- circle-mlir/models/unit/Split_F32_R4_342/__init__.py
- circle-mlir/models/unit/Split_F32_R4_d3_v11/__init__.py
- circle-mlir/models/unit/Split_F32_R4_v11/__init__.py
- circle-mlir/models/unit/Squeeze_F32_R4/__init__.py
- circle-mlir/models/unit/Squeeze_F32_R4_axis/__init__.py
- circle-mlir/models/unit/Squeeze_F32_R4_m1/__init__.py
- circle-mlir/models/unit/Squeeze_F32_R4_m1_v11/__init__.py
- circle-mlir/models/unit/Tile_F32_R2/__init__.py
This will introduce test models for Split, Squeeze and Tile Ops.
> [circle-mlir/models] Introduce Split,Squeeze,Tile

- circle-mlir/circle-mlir/lib/pass/src/ConvertONNXToCirclePass.cpp
- circle-mlir/circle-mlir/lib/pass/src/ops/SplitOp.h
- circle-mlir/circle-mlir/lib/pass/src/ops/SqueezeOp.h
- circle-mlir/circle-mlir/lib/pass/src/ops/TileOp.h
This will enable to convert Split, Squeeze and Tile Ops.
> [circle-mlir/pass] Convert Split,Squeeze,Tile

- circle-mlir/models/unit/BatchNorm2d_F32_R4/__init__.py
- circle-mlir/models/unit/BatchNorm2d_F32_R4_rand/__init__.py
This will add test models for onnx.BatchNormalization from nn.BatchNorm2d().
> [circle-mlir/models] Add BatchNormalization

- circle-mlir/models/unit/Erf_F32_R4/__init__.py
This will add test model for onnx.Erf Op.
> [circle-mlir/models] Add Erf

- circle-mlir/models/unit/Flatten_F32_R4_0/__init__.py
- circle-mlir/models/unit/Flatten_F32_R4_1/__init__.py
This will add test models for onnx.Flatten Op.
> [circle-mlir/models] Add Flatten

- circle-mlir/models/unit/GlobalAveragePool_F32_R4/__init__.py
This will add test model for onnx.GlobalAveragePool Op.
> [circle-mlir/models] Add GlobalAveragePool

- circle-mlir/models/unit/Hardsigmoid_F32_R2/__init__.py
This will add test model for onnx.HardSigmoid Op.
> [circle-mlir/models] Add HardSigmoid

- circle-mlir/models/unit/Max_F32_R4/__init__.py
- circle-mlir/models/unit/Min_F32_R4/__init__.py
This will add test models for onnx.Max and onnx.Min Ops.
> [circle-mlir/models] Add Max,Min

- circle-mlir/models/unit/QuantizeLinear_F32_R3_i16/__init__.py
- circle-mlir/models/unit/QuantizeLinear_F32_R3_i16_cw/__init__.py
- circle-mlir/models/unit/QuantizeLinear_F32_R3_ui8/__init__.py
- circle-mlir/models/unit/QuantizeLinear_F32_R3_ui8_fq/__init__.py
- circle-mlir/models/unit/QuantizeLinear_F32_R4_i16_cw/__init__.py
- circle-mlir/models/unit/QuantizeLinear_F32_R4_ui8_cw/__init__.py
This will add models to test onnx.QuantizeLinear and onnx.DequantizeLinear Ops.
> [circle-mlir/models] Add QuantizeLinear,DequantizeLinear

- circle-mlir/models/unit/Reciprocal_F32_R4/__init__.py
This will add test model for onnx.Reciprocal Op.
> [circle-mlir/models] Add Reciprocal

- circle-mlir/models/unit/Upsample_F32_R4/__init__.py
This will add test model for onnx.Upsample Op.
> [circle-mlir/models] Add Upsample

- circle-mlir/circle-mlir/lib/pass/src/RewriteCirclePass.cpp
- circle-mlir/circle-mlir/lib/pass/src/opt/FuseAddRelu.h
- circle-mlir/circle-mlir/tools-test/onnx2circle-models/test.lst
- circle-mlir/circle-mlir/tools-test/onnx2circle-rewrite-test/test.lst
- circle-mlir/circle-mlir/tools-test/onnx2circle-value-test/test.lst
- circle-mlir/models/net/Net_AddReLUConcat_F32_R4/__init__.py
- circle-mlir/models/net/Net_AddReLUSub_F32_R4/__init__.py
- circle-mlir/models/net/Net_AddReLU_F32_R4/__init__.py
This will enable fusion of Add and Relu when Add having single use.
> [circle-mlir] Fuse Add and Relu

- circle-mlir/circle-mlir/lib/pass/src/ops/BatchNormalizationInferenceModeOp.h
This will fix BatchNormalizationInferenceMode conversion to use running_mean and running_variance.
> [circle-mlir/pass] Fix BatchNormalizationInferenceMode

- compiler/one-cmds/one-prepare-venv
- compiler/one-cmds/one-prepare-venv.aarch64
- compiler/one-cmds/one-prepare-venv.u1804
- compiler/one-cmds/one-prepare-venv.u2404
This will revise torch cpu package download URL.
> [one-cmds] Update torch cpu download URL

- .github/workflows/check-format.yml
- .github/workflows/check-pr-commit.yml
This will update check-format and check-pr-commit to use U22.04.
> [github] Update to U22.04

- compiler/nnsuite/conv/nnkit-caffe/CMakeLists.txt
- compiler/nnsuite/conv/nnkit-tflite/CMakeLists.txt
This will revise to CMake to check if test is enabled or return.
> [nnsuite] CMake check test enabled

- circle-mlir/infra/docker/u2004/Dockerfile
This will introduce Docker file for U20.04 build test.
> [circle-mlir/infra] Introduce Dockerfile for U20.04

- circle-mlir/infra/docker/u2004/Dockerfile
This will add more tidy in Dockerfile with unnecessary files.
> [circle-mlir/infra] Add more tidy in Dockerfile

- circle-mlir/README.md
This will update README with prerequisite packages.
> [circle-mlir] Update README

- .github/workflows/run-onert-cross-build.yml
- .github/workflows/run-onert-native-build.yml
This will fix workflow names for run-onert-*-build.
> [github] Fix workflow names for run-onert

- .github/workflows/run-onert-gbs-build.yml
This will revise run-onert-native-build workflow, push and pull_request order
so that it becomes same as other run-onert workflows.
> [github] Revise run-onert-native-build

- compiler/mir/include/mir/Attributes.h
This will add missing header to fix U24.04 build.
> [mir] Add missing header

- compiler/dalgona/CMakeLists.txt
This will revise python3 version to be up to 3.12 and update related message.
> [dalgona] Revise python3 version

- compiler/common-artifacts/CMakeLists.txt
This will revise overlay virtualenv preparation to split steps
with using list for necessary python packages.
> [common-artifacts] Revise overlay virtualenv preparation

- tools/onnx_subgraph/include/device.h
- tools/onnx_subgraph/include/graph.h
update macro name format of header file
> [tools/onnx-subgraph] update macro name format of header file

- runtime/onert/core/src/loader/BaseLoader.h
This commit removes ReduceAll custom OP support.
ReduceAll is handled as built-in OP.
---
Related issue: #15216
> [onert] Remove ReduceAll custom OP

- .github/workflows/run-onecc-build.yml
This will fix step name for overlay.
> [github] Fix step name for overlay

- tools/onnx_subgraph/src/lib/partition.cpp
Add subgraphs information printing function
> [tools/onnx-subgraph] Add subgraphs information printing function

- compiler/common-artifacts/CMakeLists.txt
This will remove venv with TF version number.
> [common-artifacts] Remove venv with version

- compiler/common-artifacts/CMakeLists.txt
This will revise python version check codes with 3.8 or higher
and to become same pattern for cmake version branches.
> [common-artifacts] Revise python version check

- compiler/dalgona/CMakeLists.txt
This will simplify python3 version check to follow common-artifacts.
> [dalgona] Simplify python3 check

- compiler/common-artifacts/CMakeLists.txt
This will revise version comment for Ubuntu 24.04.
> [common-artifacts] Revise version comment

- compiler/common-artifacts/CMakeLists.txt
This will fill python package list for Ubuntu 24.04
> [common-artifacts] Python package list for U24.04

- compiler/one-cmds/one-prepare-venv
This will revise one-prepare-venv to detect existance of python3.8.
> [one-cmds] Detect python3.8 existance

- compiler/one-cmds/one-prepare-venv
This will revise one-prepare-venv with extracting package version number to variables.
> [one-cmds] Extract more version to variables

- compiler/one-cmds/one-prepare-venv
This will revise one-prepare-venv to prepare update versions with Ubuntu codename.
> [one-cmds] Prepare conditial update with codename

- compiler/luci-value-py-test/test.lst
This will revise Mean_U8_000 to evaluate with tolerance 1.
> [luci-value-py-test] Revise Mean_U8_000

- compiler/one-cmds/one-prepare-venv
This will tidy comment that is now in wrong place and seems not necessary.
> [one-cmds] Tidy comment

- compiler/one-cmds/one-prepare-venv
This will relocate settings of TORCH_SOURCE_OPTION before installation.
> [one-cmds] Relocate TORCH_SOURCE_OPTION

- compiler/one-cmds/one-prepare-venv
This will revise one-prepare-venv script to prepare list of packages
and then install with single command.
> [one-cmds] Revise one-prepare-venv to install once

- compiler/one-cmds/one-prepare-venv
This will tidy one-prepare-venv spaces and unnecessary comments.
> [one-cmds] Tidy one-prepare-venv spaces and comments

- infra/docker/focal/Dockerfile
- infra/docker/jammy/Dockerfile
- infra/docker/noble/Dockerfile
This commit removes packages for format check and gbs build from the docker image.
> [infra] Remove packages for format check and gbs build in docker

- .github/workflows/build-pub-dev-docker.yml
This commit updates docker publish workflow to test before publishing.
---
Related issue: #14892
It is tested on #15280
> [infra] Update docker publish workflow

- .github/workflows/build-dev-docker.yml
- .github/workflows/build-pub-dev-docker.yml
This commit updates docker build workflow to use self-hosted runner.
> [infra] Fix docker build runner

- .github/workflows/pub-circle-int-launchpad.yml
This revises the sequence of some steps for releasing and creating pull requests for the `circle-interpreter` Debian package.
> [github] Revise the sequence of steps in the workflow

- circle-mlir/infra/overlay/prepare-venv
This will prepare-venv script to gather packages and then install at once.
> [circle-mlir/infra] Revise prepare-venv

- .github/workflows/pub-circle-int-launchpad.yml
This adds the step to build circle-interpreter from ONE repository.
> [github] Build circle-interpreter

- .github/workflows/pub-circle-int-launchpad.yml
This implements the step copying the circle-interpreter binary and its related shared object(.so) files.
> [github] Implement step for gathering files

- .github/workflows/pub-circle-int-launchpad.yml
This adds the implementation of updating changelog with description from workflow inputs
> [github] Update changelog

- tools/onnx_subgraph/src/lib/partition.cpp
Add subgraphs adjancent nodes searching code
> [tools/onnx-subgraph] Add subgraphs adjancent nodes searching code

- .github/workflows/run-circle-mlir-build.yml
This will update circle-interpreter path to latest change.
> [github] Update circle-interpreter path

- infra/docker/android-sdk/Dockerfile
- infra/docker/bionic/Dockerfile
- infra/docker/bionic/Dockerfile.aarch64
- infra/docker/focal-cross/Dockerfile
- infra/docker/focal/Dockerfile
- infra/docker/focal/Dockerfile.aarch64
- infra/docker/jammy-cross/Dockerfile
- infra/docker/jammy/Dockerfile
- infra/docker/jammy/Dockerfile.aarch64
- infra/docker/noble-cross/Dockerfile
- infra/docker/noble/Dockerfile
- infra/docker/noble/Dockerfile.aarch64
It adds pkg-config to all Docker images maintained.
---
Related w/ : https://github.com/Samsung/ONE/pull/15273/
> [infra] Add pkg-config to Docker images

- circle-mlir/infra/overlay/prepare-venv
This will revise prepare-venv package version by python3 version.
> [circle-mlir/infra] Revise prepare-venv by py3 vers

- compiler/common-artifacts/CMakeLists.txt
This will fix indentation of CMakeLists file.
> [common-artifacts] Fix indentation

- compiler/dalgona/CMakeLists.txt
This will fix indentation of CMakeLists file.
> [dalgona] Fix indentation

- compiler/one-cmds/CMakeLists.txt
This will fix indentation of CMakeLists file.
> [one-cmds] Fix indentation

- circle-mlir/circle-mlir/tools/CMakeLists.txt
- circle-mlir/circle-mlir/tools/one-import-onnx-ext/README.md
This will disable one-import-onnx-ext from build/install.
> [circle-mlir/tools] Disable one-import-onnx-ext

- compiler/circlechef/core/src/ModelChef.cpp
- compiler/circlechef/proto/circlechef.proto
This introduces MXQuantization to circlechef.
---
Draft PR: https://github.com/Samsung/ONE/pull/15259
> [circlechef] Introduce MXQuantization

- res/CircleRecipes/CircleBatchMatMul_MXFP4_000/test.recipe
- res/CircleRecipes/CircleBatchMatMul_MXINT8_000/test.recipe
This adds mx_quant info to mx types.
---
Draft PR: https://github.com/Samsung/ONE/pull/15259
> [res] Add mx_quant info to mx types.

- tools/onnx_subgraph/src/lib/partition.cpp
Add function for calculating the graph size
> [tools/onnx-subgraph] Add function for calculating the graph size

- compiler/one-cmds/CMakeLists.txt
This will fix PATH for onnx2circle tool.
> [one-cmds] Fix PATH for onnx2circle

- .github/workflows/pub-onnx2circle-launchpad.yml
This adds the initial GitHub Actions workflow to publish the `onnx2circle` Debian package to Launchpad.
> [github] Create workflow for publishing onnx2circle

- .github/workflows/pub-onnx2circle-launchpad.yml
This removes a TODO comment that has already been addressed.
> [github] Remove comment for completed job

- circle-mlir/infra/debian/onnx2circle/changelog
This updates the changelog for onnx2circle_0.3.0~202505290100.
This PR includes updated changelog after successful debian build.
It is auto-generated PR from github workflow.
> [circle-mlir/infra] Update changelog for onnx2circle

- compiler/dalgona/CMakeLists.txt
This will revise find_package also with Interpreter and to follow that from one-cmds.
> [dalgona] Revise find_package

- circle-mlir/circle-mlir/lib/pass/src/RewriteCirclePass.cpp
- circle-mlir/circle-mlir/lib/pass/src/opt/ConvertDivToMul.h
This will introduce ConvertDivToMul that will convert Div() to Mul(),
and replace ConvertDivErfToMulErf.
> [circle-mlir/pass] Replace with ConvertDivToMul

- compiler/one-cmds/one-prepare-venv
This will tidy conditions by codename in one-prepare-venv.
> [one-cmds] Tidy conditions by codename

- tools/onnx_subgraph/src/lib/partition.cpp
Add function for Depth-First Searching (DFS) build a NPU subgraph
Add function for Depth-First Searching (DFS) to build a NPU subgraph
> [tools/onnx-subgraph] Add function for Depth-First Searching (DFS)

- .github/workflows/pub-onnx2circle-launchpad.yml
- circle-mlir/circle-mlir/tools/onnx2circle/src/onnx2circle.cpp
This will set onnx2circle version to 0.4.0.
> [circle-mlir] Version up to 0.4.0

- tools/onnx_subgraph/src/lib/partition.cpp
Add function for Depth-First Searching (DFS) to build a CPU subgraph
> [tools/onnx-subgraph] Add function for DFS to build a CPU subgraph

- circle-mlir/circle-mlir/lib/dialect/mlir/CircleOps.td
- circle-mlir/circle-mlir/lib/dialect/src/ShapeInference.cpp
- circle-mlir/circle-mlir/tools/onnx2circle/test.lst
- circle-mlir/models/mlir/BatchMatMul_F32_us.circle.mlir
This will enable shape inference of BatMatMulOp and simple test.
> [circle-mlir/dialect] Enable shape-inf of BatchMatMul

- circle-mlir/circle-mlir/lib/dialect/src/ShapeInference.cpp
This will fix deprecated warnings in ShapeInference.cpp.
> [circle-mlir/dialect] Fix deprecated warnings

- runtime/infra/debian/control
- runtime/infra/debian/control.default
- runtime/infra/debian/control.trix
This commit updates debian control file's section field, priority field, and version
- Section: devel -> libs (for better categorization)
- Priority: extra -> optional (extra priority is deprecated since 4.0.1)
- Version: 3.9.8 -> 4.0.1
> [infra/onert] Update debian control file

- compiler/one-cmds/one-import-onnx
This will fix one-import-onnxx "unrecognized arguments" error.
> [one-cmds] Fix one-import-onnx error

- circle-mlir/circle-mlir/lib/dialect/src/ops/ReshapeOp.h
- circle-mlir/circle-mlir/lib/dialect/src/ops/ResizeOnnxOp.h
- circle-mlir/circle-mlir/lib/dialect/src/ops/SelectOp.h
- circle-mlir/circle-mlir/lib/dialect/src/ops/SelectV2Op.h
- circle-mlir/circle-mlir/lib/dialect/src/ops/ShapeOp.h
- circle-mlir/circle-mlir/lib/dialect/src/ops/SliceOp.h
- circle-mlir/circle-mlir/lib/dialect/src/ops/SplitVOp.h
- circle-mlir/circle-mlir/lib/dialect/src/ops/SqueezeOp.h
- circle-mlir/circle-mlir/lib/dialect/src/ops/StridedSliceOp.h
- circle-mlir/circle-mlir/lib/dialect/src/ops/TransposeConvOp.h
- circle-mlir/circle-mlir/lib/dialect/src/ops/TransposeOp.h
- circle-mlir/circle-mlir/lib/dialect/src/ops/UnsqueezeOnnxOp.h
This will fix more deprecated warnings in dialect.
> [circle-mlir/dialect] Fix deprecated warnings(2)

- circle-mlir/circle-mlir/lib/pass/src/ops/FlattenOp.h
- circle-mlir/circle-mlir/lib/pass/src/ops/GatherOp.h
- circle-mlir/circle-mlir/lib/pass/src/ops/GemmOp.h
- circle-mlir/circle-mlir/lib/pass/src/ops/GlobalAveragePoolOp.h
- circle-mlir/circle-mlir/lib/pass/src/ops/GreaterOp.h
- circle-mlir/circle-mlir/lib/pass/src/ops/HardSigmoidOp.h
- circle-mlir/circle-mlir/lib/pass/src/ops/InstanceNormalizationOp.h
- circle-mlir/circle-mlir/lib/pass/src/ops/MatMulOp.h
- circle-mlir/circle-mlir/lib/pass/src/ops/MaxPoolSingleOutOp.h
- circle-mlir/circle-mlir/lib/pass/src/ops/PadOp.h
- circle-mlir/circle-mlir/lib/pass/src/ops/QuantizeLinearOp.h
This will fix more deprecated warnings in pass.
> [circle-mlir/pass] Fix deprecated warnings(4)

- circle-mlir/circle-mlir/lib/pass/src/ops/ReciprocalOp.h
- circle-mlir/circle-mlir/lib/pass/src/ops/ReduceMaxOp.h
- circle-mlir/circle-mlir/lib/pass/src/ops/ReduceMeanOp.h
- circle-mlir/circle-mlir/lib/pass/src/ops/ReduceProdOp.h
- circle-mlir/circle-mlir/lib/pass/src/ops/ReduceSumOp.h
- circle-mlir/circle-mlir/lib/pass/src/ops/ReshapeOp.h
- circle-mlir/circle-mlir/lib/pass/src/ops/ResizeOp.h
- circle-mlir/circle-mlir/lib/pass/src/ops/ShapeOp.h
- circle-mlir/circle-mlir/lib/pass/src/ops/SliceOp.h
- circle-mlir/circle-mlir/lib/pass/src/ops/SoftmaxOp.h
- circle-mlir/circle-mlir/lib/pass/src/ops/SplitOp.h
- circle-mlir/circle-mlir/lib/pass/src/ops/SqueezeOp.h
- circle-mlir/circle-mlir/lib/pass/src/ops/TransposeOp.h
- circle-mlir/circle-mlir/lib/pass/src/ops/UnsqueezeOp.h
- circle-mlir/circle-mlir/lib/pass/src/ops/WhereOp.h
This will fix more deprecated warnings in pass.
> [circle-mlir/pass] Fix deprecated warnings(5)

- circle-mlir/circle-mlir/lib/pass/src/ConvertHelper.cpp
- circle-mlir/circle-mlir/lib/pass/src/ConvertHelper.h
- circle-mlir/circle-mlir/lib/pass/src/ConvertONNXToCirclePass.cpp
- circle-mlir/circle-mlir/lib/pass/src/ShapeInferencePass.cpp
This will fix more deprecated warnings in pass.
> [circle-mlir/pass] Fix deprecated warnings(6)

- circle-mlir/circle-mlir/tools/onnx2circle/src/onnx2circle.cpp
- circle-mlir/circle-mlir/tools/onnx2circle/src/onnx2circle.h
This will introduce option to invoke dynamicBatchToSingleBatch method.
> [circle-mlir/tools] Enable to invoke dynamicBatchToSingleBatch

- compiler/one-cmds/one-import-onnx
This will update comment with old onnx-tf to new onnx2circle.
> [one-cmds] Update one-import-onnx comment

- compiler/one-cmds/tests/one-import-bcq_neg_001.test
- compiler/one-cmds/tests/one-import-bcq_neg_002.test
- compiler/one-cmds/tests/one-import-bcq_neg_006.test
- compiler/one-cmds/tests/one-import-bcq_neg_007.test
- compiler/one-cmds/tests/one-import_neg_001.test
- compiler/one-cmds/tests/one-import_neg_003.test
- compiler/one-cmds/tests/one-import_neg_004.test
- compiler/one-cmds/tests/one-import_neg_005.test
- compiler/one-cmds/tests/one-import_neg_010.test
This will revise negative tests to support TF2.19.0 changed error messages.
> [one-cmds] Revise negative tests

- compiler/one-cmds/tests/one-optimize_002.test
- compiler/one-cmds/tests/one-quantize_009.qconf.json
- compiler/one-cmds/tests/one-quantize_012.qconf.json
- compiler/one-cmds/tests/one-quantize_013.qconf.json
This will revise test node names to support TF2.19.0.
> [one-cmds] Revise test node names

- infra/docker/focal/Dockerfile
This commit updates ubuntu 20.04 dockerfile to install lost sudo package. 
Other dockerfiles already have sudo installed.
> [infra/docker] Install sudo

- compiler/common-artifacts/CMakeLists.txt
This will revise to use python3.10 and above.
> [common-artifacts] Use python3.10 and above

- infra/docker/android-sdk/Dockerfile
This commit updates environment value setting in Dockerfile to remove legacy syntax.
> [infra] Fix dockerfile legacy environment value setting

- compiler/one-cmds/one-prepare-venv
This will tidy using lsb-release in one-prepare-venv.
> [one-cmds] Tidy using lsb-release

- compiler/common-artifacts/CMakeLists.txt
This will tidy unused python3.8 package list.
> [cmn-arts] Tidy unused python3.8 pacakge list

- compiler/one-cmds/one-prepare-venv
This will upgrade python packages in one-prepare-venv and remove unnecessary explicit installs.
> [one-cmds] Upgrade packages in one-prepare-venv

- compiler/luci/pass/src/FuseMulWithFullyConnectedPass.cpp
- compiler/luci/pass/src/FuseMulWithFullyConnectedPass.test.cpp
This commit treats 1x1x.. tensors as scalars in FuseMulWithFullyConnected pass.
Related: #15614 
> [luci] Support 1x1x.. tensors in FuseMulWithFullyConnected

- .github/workflows/pub-circle-int-launchpad.yml
This will add noble to publish target.
> [github] Enable circle-interpreter publish for noble

- circle-mlir/infra/overlay/prepare-venv
This will revise prepare-venv to check available python3.
> [circle-mlir/infra] Check available python3

- circle-mlir/infra/docker/focal/Dockerfile
- circle-mlir/infra/docker/jammy/Dockerfile
This will revise Dockerfile with packages and register launchpad.net.
> [circle-mlir/infra] Revise Dockerfile with packages

- circle-mlir/infra/docker/focal/Dockerfile
- circle-mlir/infra/docker/jammy/Dockerfile
This will revise add group/user to follow compiler/runtime
and to enable to use sudo command.
> [circle-mlir/infra] Revise add user and group

- circle-mlir/infra/docker/focal/Dockerfile
- circle-mlir/infra/docker/jammy/Dockerfile
This will tidy comment from old build-up and reduce more unnecessary files.
> [circle-mlir/infra] Tidy comment and reduce more

- circle-mlir/infra/docker/focal/Dockerfile
- circle-mlir/infra/docker/jammy/Dockerfile
This will upgrade python package versions in Dockerfile.
> [circle-mlir/infra] Upgrade python package versions in Dockerfile

- circle-mlir/infra/docker/noble/Dockerfile
This will introduce Dockerfile for noble.
> [circle-mlir/infra] Introduce Dockerfile for noble

- compiler/one-cmds/one-import-onnx
This will tidy unnecessary _remap_io_names and  _sanitize_io_names methods.
> [one-cmds] Tidy unnecessary IO methods

- .github/workflows/run-circle-mlir-build.yml
This will add noble in run-circle-mlir-build workflow.
> [github] Add noble in run-circle-mlir-build

- .github/workflows/pub-onnx2circle-launchpad.yml
This will enable noble publish for pub-onnx2circle-launchpad.
> [github] Enable noble for pub-onnx2circle-launchpad

- tools/onnx_subgraph/src/lib/partition.cpp
Determine and partition subgraphs from the given ONNX graph based on DFS strategy
> [tools/onnx-subgraph] Determine and partition subgraphs based on DFS

- res/TensorFlowLiteRecipes/Net_Transpose_Relu6_000/test.recipe
This will introduce Net_Transpose_Relu6_000 recipe for testin forward_transpose_op with Relu6 Op.
> [res] Introduce Net_Transpose_Relu6_000

- tools/onnx_subgraph/src/lib/partition.cpp
Determine and partition subgraphs from the given ONNX graph using the index of nodes
> [tools/onnx-subgraph] Determine and partition subgraphs by the index

- infra/docker/noble/Dockerfile
This will fix noble Dockerfile with sudo when -u option is given.
> [infra/docker] Revise noble Dockerfile

- infra/debian/compiler/control
This will tidy python3.10 from control file.
> [infra/debian] Revise compiler control

- infra/cmake/packages/HDF5Config.cmake
This will revise HDF5Config.cmake not to build test and examples, to speedup build.
> [infra/cmake] Revise HDF5Config.cmake

- compiler/one-cmds/onnx_legalizer.py
This will fix warnings in onnx_legalizer with python3.12.
> [one-cmds] Fix warnings in onnx_legalizer

- compiler/one-cmds/CMakeLists.txt
- compiler/one-cmds/one-prepare-venv
This will revise one-prepare-venv to support AArch64.
> [one-cmds] Revise one-prepare-venv to support AArch64

- .github/workflows/pub-onert-pypi.yml
This commit adds workflow for publishing onert python package.
> [github] Create workflow for publishing onert python package

- .github/workflows/pub-onert-pypi.yml
This commit fixes pub-onert-pypi.yml
- Typo: ipnut -> input
- Fix shellcheck report SC2155: declare and assign separately to avoid masking return values
- Fix shellcheck report SC2046: double quote to prevent globbing and word splitting
---
Draft: #15699
> [infra/onert] Fix pub-onert-pypi.yml

- circle-mlir/circle-mlir/lib/pass/src/ops/ConvOp.h
This will extract methods in ConvConv to reduce matchAndRewrite method.
> [circle-mlir/pass] Extract methods in ConvConv

- circle-mlir/circle-mlir/lib/dialect/mlir/CircleOps.td
- circle-mlir/circle-mlir/lib/dialect/src/ops/SplitVOp.h
This will introduce IR for SplitOp and related method.
> [circle-mlir/dialect] Introduce SplitOp IR

- circle-mlir/circle-mlir/lib/pass/src/ConvertHelper.cpp
- circle-mlir/circle-mlir/lib/pass/src/ConvertHelper.h
This will introduce CreateConst helper method with type and value.
Existing CreateConst method with ref. value is updated to use new method.
> [circle-mlir/pass] Introduce CreateConst with type and value

- circle-mlir/circle-mlir/lib/pass/src/ops/SplitOp.h
This will revise ConvSplit to support no second input, split.
> [circle-mlir/pass] Revise ConvSplit with no split

- circle-mlir/circle-mlir/lib/pass/src/ops/ConvOp.h
This will revise ConvConv method to check to convert to DepthwiseConv2DOp or not.
> [circle-mlir/pass] Revise ConvConv for DepthwiseConv2D

- circle-mlir/circle-mlir/lib/pass/src/ops/ConvOp.h
This will fix indentation in ConvConv.
> [circle-mlir/pass] Fix indentation in ConvConv

- circle-mlir/circle-mlir/lib/pass/src/ops/ConvOp.h
This will introduce empty splitConv method to convert to small Split-Conv-Concat network for group Conv.
> [circle-mlir/pass] Introduce splitConv

- circle-mlir/circle-mlir/lib/pass/src/ops/ConvOp.h
This will implement splitConv to convert ConvOp with group to
network of SplitOp-[ConvOp]-ConcatOp-AddOp.
> [circle-mlir/pass] Implement splitConv method of ConvConv

- docs/release/1.30/index.rst
- docs/release/1.30/release-note-1.30.0.md
This commit is release note for 1.30.0.
Related: #15459
> Release note 1.30.0

- circle-mlir/circle-mlir/lib/dialect/src/CircleDialect.cpp
- circle-mlir/circle-mlir/lib/dialect/src/ops/SplitOp.h
- circle-mlir/circle-mlir/lib/dialect/src/ops/SplitVOp.h
This will separate SplitOp verify method to own header file.
> [circle-mlir/dialect] Separate SplitOp verify

- runtime/libs/circle-schema/include/circle_schema_generated.h
This commit updates circle_schema_generated.h to the latest version.
> [onert] Update schema generated header

- compiler/circle2circle/src/Circle2Circle.cpp
This will tidy "Experimental" in convert_nchw_to_nhwc desciption.
> [circle2circle] Revise convert_nchw_to_nhwc

- packaging/nnfw.spec
- runtime/CMakeLists.txt
- runtime/infra/cmake/CfgOptionFlags.cmake
This commit introduces asan build option to cmake to decide install path.
> [onert] Introduce asan build option

- packaging/nnfw.spec
This commit removes copy operation to install target directory from workspace temporary output directory by using --prefix of install command.
> [infra/gbs] Install to prefix directory directly

- runtime/onert/api/python/package/infer/session.py
This commit fixes typo in exception handling in api `_update_inputs_tensorinfo` method.
> [onert/api] Correct typo in exception handling in session.py

- infra/command/format
This commit replaces legacy bash commands
- Replace egrep with grep -E
- Replace backticks with $(...)
> [infra/command] Remove legacy bash command

- infra/command/format
This commit adds quotes around variable or command to prevent globbing and word splitting.
> [infra/command] Add quotes

- infra/scripts/test_coverage.sh
- runtime/onert/api/nnfw/src/nnfw_session.cc
- runtime/onert/core/include/util/Config.lst
- runtime/onert/core/include/util/logging.h
- runtime/tests/scripts/test_scheduler_with_profiling.sh
- runtime/tests/scripts/test_scheduler_with_profiling_android.sh
- runtime/tests/tools/onert_run/src/onert_run.cc
- runtime/tests/tools/onert_train/src/onert_train.cc
- runtime/tests/tools/tflite_comparator/src/tflite_comparator.cc
This commit changes log flag name from ONERT_LOG_ENABLE to ENABLE_LOG.
> [onert] Change log flag name to ENABLE_LOG

- compiler/souschef/include/souschef/Data/Gaussian.h
- compiler/souschef/src/Gaussian.cpp
This supports uint4 gaussian data chef.
---
Draft PR: https://github.com/Samsung/ONE/pull/15869
> [souschef] Support uint4 gaussian data chef

- res/CircleRecipes/CircleFullyConnected_U4_003/test.recipe
This adds the CircleFullyConnected_U4_003 recipe.
---
Draft PR: https://github.com/Samsung/ONE/pull/15869
> [res] Add CircleFullyConnected_U4_003 recipe

- onert-micro/eval-driver/Driver.cpp
- onert-micro/onert-micro/include/arser/arser.h
- Implement feature for random data generation
> [onert-micro] Add selective input/output modes to Driver

- onert-micro/onert-micro/include/import/OMKernelConfigureBuilder.h
- onert-micro/onert-micro/src/core/OMKernelType.cpp
> [onert-micro] Print error log on Unknown Op

- .ahub/sam/exclude.txt
This will add excludes for circle-mlir.
> [ahub] Revise exclude for circle-mlir

- runtime/tests/tools/onert_run/src/h5formatter.cc
This commit supports INT16_SYMM type in h5formatter.
> [ONERT] Support INT16_SYMM in h5formatter

- compiler/tf2tfliteV2/tf2tfliteV2.py
This will tidy unused _v1_convert method.
> [tf2tfliteV2] Tidy _v1_convert

- compiler/tf2tfliteV2-conversion-test/testall.sh
This will remove v1 option from test command.
> [tf2tfliteV2-conv-test] Remove v1 option

- res/CircleSchema/0.10/circle_schema.fbs
Let's bump circle schema to 0.10.0.
----
Related to #15676
> [res] Bump circle schema to 0.10.0

- nnpackage/schema/circle_schema.fbs
Let's fix license year in recently updated circle_schema.fbs.
----
Related to #15676
> [nnpackage] Fix License year

- compiler/mio-tflite/CMakeLists.txt
This will revise mio-tflite to use schema from TF2.19.0.
> [mio-tflite] Use schema from TF2.19.0

- .github/workflows/build-dev-docker.yml
This commit adds condition on ubuntu docker image build to check owner and filter output is empty or not.
> [infra/github] Check repository owner and filter output

- compiler/tfl-inspect/CMakeLists.txt
- compiler/tfl-inspect/requires.cmake
- compiler/tfl-inspect/src/Reader.cpp
This will revise to use mio-tflite module.
> [tfl-inspect] Use mio-tflite

- compiler/tfl-verify/CMakeLists.txt
- compiler/tfl-verify/requires.cmake
This will revise to use mio-tflite module.
> [tfl-verify] Use mio-tflite

- runtime/tests/nnfw_api/CMakeLists.txt
- runtime/tests/nnfw_api/lib/CircleGen.h
- runtime/tests/nnfw_api/lib/GenModelTest.h
- runtime/tests/nnfw_api/lib/GenModelTrain.h
- runtime/tests/nnfw_api/lib/NNPackages.cc
- runtime/tests/nnfw_api/lib/common.cc
- runtime/tests/nnfw_api/lib/common.h
- runtime/tests/nnfw_api/lib/fixtures.h
- runtime/tests/nnfw_api/src/GenModelTests/BranchModelTrain.test.cc
- runtime/tests/nnfw_api/src/GenModelTests/General.test.cc
- runtime/tests/nnfw_api/src/GenModelTests/ModelTestDynamicTensor.test.cc
- runtime/tests/nnfw_api/src/GenModelTests/ModelTestInputReshaping.test.cc
- runtime/tests/nnfw_api/src/GenModelTests/one_op_tests/Slice.test.cc
- runtime/tests/nnfw_api/src/NNPackageTests/AddSessionPrepared.test.cc
- runtime/tests/nnfw_api/src/NNPackageTests/SingleSession.test.cc
- runtime/tests/nnfw_api/src/OdcAutoCompilation.test.cc
This commit applies strict build to nnfw api test.
> [onert/test] Apply strict build to nnfw api test

- compiler/luci-interpreter/pal/linux/PALMul.h
- compiler/luci-interpreter/pal/linux/pal.cmake
- compiler/luci-interpreter/src/kernels/Mean.cpp
- compiler/luci-interpreter/src/kernels/ReverseV2.cpp
This will revise to use TF2.19.0 kernels.
- Mean and some are changed to reflect the kernel updates
> [luci-interp] Use TF2.19.0 kernels

- compiler/circle-resizer/requires.cmake
- compiler/circle-resizer/src/CMakeLists.txt
> [circle-resizer] Use mio-circle

- compiler/common-artifacts/CMakeLists.txt
This will fix typo in cmake comment.
> [cmn_arts] Fix typo in comment

- Makefile.template
This commit includes mio-circle to Makefile.template for on-device compiler.
> [infra/onert] Update Makefile.template for mio-circle

- .github/workflows/run-onecc-build.yml
This will reduce runs for run-oncc-build for push event.
> [github] Reduce runs for run-onecc-build

- .github/workflows/run-circle-mlir-build.yml
This will reduce runs for run-circle-mlir-build for push event.
> [github] Reduce runs for run-circle-mlir-build

- compiler/circle-tensordump/CMakeLists.txt
- compiler/circle-tensordump/requires.cmake
> [circle-tensordump] Use mio-circle

- compiler/circledump/CMakeLists.txt
- compiler/circledump/README.md
- compiler/circledump/requires.cmake
> [circledump] Use mio-circle

- compiler/tflite2circle/CMakeLists.txt
- compiler/tflite2circle/requires.cmake
> [tflite2circle] Use mio-circle

- Makefile.template
This will tidy mio-circle08 from Makefile.template.
> Tidy mio-circle08 from Makefile.template

- res/TensorFlowLiteRecipes/Net_Mul_Div_002/test.recipe
- res/TensorFlowLiteRecipes/Net_Mul_Div_002/test.rule
- res/TensorFlowLiteRecipes/Net_Mul_Div_003/test.recipe
- res/TensorFlowLiteRecipes/Net_Mul_Div_003/test.rule
This will introduce more Net_Mul_Div 002 and 003.
> [res] Introduce More Net_Mul_Div

- compiler/luci/pass/include/luci/CircleOptimizer.h
- compiler/luci/pass/include/luci/Pass/RemoveUnnecessaryMulDivPass.h
- compiler/luci/pass/src/CircleOptimizer.cpp
- compiler/luci/pass/src/RemoveUnnecessaryMulDivPass.cpp
- compiler/luci/pass/src/RemoveUnnecessaryMulDivPass.test.cpp
This will introduce RemoveUnnecessaryMulDivPass files with
RemoveUnnecessaryDivPass and RemoveUnnecessaryMulPass.
> [luci/pass] Introdue RemoveUnnecessaryMulDivPass

- compiler/luci/pass/src/BatchNormPatternFinder.cpp
- compiler/luci/pass/src/ConvertNCHWToNHWCPass.cpp
- compiler/luci/pass/src/FoldGatherPass.cpp
- compiler/luci/pass/src/FoldSparseToDensePass.cpp
- compiler/luci/pass/src/ForwardReshapeToUnaryOpPass.cpp
- compiler/luci/pass/src/ForwardTransposeOpPass.cpp
- compiler/luci/pass/src/FuseBCQPass.cpp
- compiler/luci/pass/src/FuseBatchNormWithDwConvPass.cpp
- compiler/luci/pass/src/FuseInstanceNormPass.cpp
- compiler/luci/pass/src/FusePreActivationBatchNormPass.cpp
- compiler/luci/pass/src/PropagateQParamBackwardPass.cpp
- compiler/luci/pass/src/QuantizeBias.cpp
- compiler/luci/pass/src/QuantizeDequantizeWeightsPass.cpp
- compiler/luci/pass/src/QuantizeWeights.cpp
- compiler/luci/pass/src/QuantizeWeightsOnly.cpp
- compiler/luci/pass/src/ResolveCustomOpSplitVPass.test.cpp
- compiler/luci/pass/src/ShuffleWeightTo16x1Float32Pass.cpp
- compiler/luci/pass/src/SubstitutePadV2ToPadPass.cpp
- compiler/luci/pass/src/UnrollUnidirectionalSequenceLSTMPass.cpp
This will revise to use luci::must_cast for CircleConst.
> [luci/pass] Use luci::must_cast

- compiler/luci/service/src/CircleShapeInferenceRule.cpp
- compiler/luci/service/src/Nodes/CircleStridedSlice.cpp
This will revise to use luci::must_cast for CircleConst.
> [luci/service] Use luci::must_cast

- compiler/circle2circle/src/Circle2Circle.cpp
This will add remove_unnecessary_div, remove_unnecessary_mul options.
> [circle2circle] Add remove_unnecessary_div, remove_unnecessary_mul

- compiler/souschef/include/souschef/Dims.h
This will introduce shorter alias of DimsI32_t for better readability.
> [souschef] Introduce DimsI32_t

- compiler/tflchef/core/src/ModelChef.cpp
This will add alias types for better readability.
> [tflchef] Introduce alias types

- compiler/tflchef/core/src/ModelChef.cpp
This will extract buffer_sparse_f32() method from long cook_operands().
> [tflchef] Extract buffer_sparse_f32

- compiler/tflchef/core/src/ModelChef.cpp
This will extract prepare_tensor_symbols() method from cook_graph().
> [tflchef] Extract prepare_tensor_symbols

- compiler/tflchef/core/src/ModelChef.cpp
This will extract operand_quant() method from long cook_operands().
> [tflchef] Extract operand_quant

- .github/workflows/run-onecc-build.yml
This will enable to skip build test with "PR/NO TEST" label for PRs.
> [github] Enable "NO TEST" label to skip build

- compiler/tflchef/core/src/ModelChef.cpp
This will extract operand_sparsity() method from long cook_operands().
> [tflchef] Extract operand_sparsity

- compiler/vconone/CMakeLists.txt
This commit bumps up to 1.30.1.
> [vconone] Bump up to 1.30.1 

- docs/release/1.30/index.rst
- docs/release/1.30/release-note-1.30.1.md
This commit is a release note 1.30.1.
The changes has been already merged to release/1.30.1 branch.
> Release note 1.30.1

- infra/debian/compiler/postinst
This will tidy postinst file with case of bionic.
> [infra/debian] Tidy postinst for case of bionic

- compiler/one-cmds/tests/one-import_002.cfg
- compiler/one-cmds/tests/one-import_003.cfg
- compiler/one-cmds/tests/one-import_004.cfg
- compiler/one-cmds/tests/one-import_005.cfg
This will revise tests to use onecc from old one-build.
> [one-cmds] Reivse tests with onecc

- compiler/one-cmds/one-optimize
This will update one-optimize comment to use onecc.
> [one-cmds] Update one-optimize comment

- compiler/nnc/backends/acl_soft_backend/CMakeLists.txt
- compiler/nnc/backends/soft_backend/CMakeLists.txt
This will tidy bionic related changes.
> [nnc/backends] Tidy bionic

- compiler/CMakeLists.txt
This will tidy checking codename and setting related variables.
> [compiler] Tidy checking codename

- onert-micro/CMakeLists.txt
- onert-micro/externals/CMakeLists.txt
- Additionally, add dependence to it in onert_micro_arm target
> Fix wrong circle_traininfo schema path

- compiler/one-global-conf-template/README.md
- compiler/one-global-conf-template/backend/BACKEND_NAME/bin/BACKEND_NAME-compile
- compiler/one-global-conf-template/backend/BACKEND_NAME/bin/BACKEND_NAME-profile
- compiler/one-global-conf-template/backend/BACKEND_NAME/one-cmds/codegen.py
- compiler/one-global-conf-template/backend/BACKEND_NAME/one-cmds/profile.py
- compiler/one-global-conf-template/debian/control
- compiler/one-global-conf-template/debian/one-global-conf-TARGET_NAME.install
- compiler/one-global-conf-template/debian/rules
- compiler/one-global-conf-template/target/TARGET_NAME/TARGET_NAME.ini
- compiler/one-global-conf-template/tools/validate_global_conf.py
This commit provides template and guide for creating one-global-conf-* packages.
Related: #16166 
> [compiler] Provide template for one-global-conf-*

- circle-mlir/models/onnx_utils.py
This will introduce onnx_utils for processing input type for the model.
Code itself came from portion torch/onnx.
> [circle-mlir/models] Introduce onnx_utils

- circle-mlir/models/gen_models.py
This will revise to search all models in unit and net folder with @.
> [circle-mlir/models] Search all models with @
