Samsung/ONE

runtime/libs/circle-schema/include/circle_schema_generated.h

This commit updates circle schema header file to support RmsNorm and RoPE

[runtime/libs] Update circle schema to support RmsNorm and RoPE operation

---

compiler/common-artifacts/exclude.lst

This commit reverts exclude.lst to include RmsNorm optimization and test data generation.

[common-artifacts] Include RmsNorm optimization and test data generation

---

compiler/dredd-rule-lib/README.md
compiler/dredd-rule-lib/rule-lib.sh

This commit introduces new dredd-test rule for tensor shape.

[dredd] Introduce new dredd rule for tensor shape

---

onert-micro/onert-micro/include/pal/common/PALSoftmaxInputGrad.h

- Fix softmax input grad computation

[onert-micro] Revise softmax input grad

---

onert-micro/onert-micro/include/pal/common/PALGRUCommon.h
onert-micro/onert-micro/include/pal/common/PALGRUWeightGrad.h

- TizenRT platform produces tanh(x) NaN for large x
- reason behind this patch is that tanh(x) is almost 1 for x > 15

[onert_micro] workaround for tanh for tizenrt

---

compiler/circledump/src/OpPrinter.cpp

This commit adds RoPE Printer in circle dump

[circledump] Support RoPE Operation

---

compiler/common-artifacts/exclude.lst

This commit is to exclude Reshape_003 optimization test.
This recipe does not reflect the original intention.
Related: https://github.com/Samsung/ONE/issues/13927
ONE-DCO-Signed-off-by: Jongwon Yang <yjw963@gmail.com>

[common-artifacts] Exclude Reshape_003 optimization test

---

res/TensorFlowLiteRecipes/Inf_Pad_000/test.recipe
res/TensorFlowLiteRecipes/Inf_Pad_000/test.rule

This commit adds TFLiteRecipe for dynamic shape pad.

[res] Add TFLiteRecipe for dynamic shape pad

---

compiler/luci/export/src/CircleBuiltinTypesExtractor.h
compiler/luci/export/src/CircleExporterUtils.cpp
compiler/luci/export/src/CircleExporterUtils.h
compiler/luci/export/src/CircleOps.lst

This commit supports RoPE For luci export

[luci/export] Support RoPE operation

---

onert-micro/onert-micro/include/execute/OMUtils.h
onert-micro/onert-micro/src/execute/kernels/Softmax.cpp

- Add missing part for cmsisnn softmax

[onert-micro] proprocessing phase for cmsisnn Softmax

---

res/TensorFlowLiteRecipes/Inf_Quantize_000/test.recipe
res/TensorFlowLiteRecipes/Inf_Quantize_000/test.rule

This commit add TFLiteRecipe for dynamic shape Quantize.
ONE-DCO-1.0-Signed-off-by: Bokyeong Lee <kyeong8139@gmail.com>

[res] Add TFLiteRecipe for dynamic shape Quantize

---

compiler/luci/service/src/Nodes/CircleStridedSlice.cpp

This commit resolves warnings from static analysis tool.
- Init array
- Check if truncation doesn't happen when casting.

[luci] Resolve static analysis warning

---

compiler/luci/pass/src/RemoveUnnecessaryTransposeNetPass.cpp

This PR simplifies TaggedShapeAnalyzer in RemoveUnnecessaryTransposeNetPass.
By moving less-related code(`Dim`, `Shape` `flatsize()`, `inference_incomplete_shape()`) outside of TaggedShapeAnaylzer, This PR clarifies TaggedShapeAnaylzer's role.
* draft : https://github.com/Samsung/ONE/pull/14121
* background : Before resolving https://github.com/Samsung/ONE/issues/13663, I'd like to trim current RemoveUnnecessaryTransposeNetPass.

[luci/pass] Simplify TaggedShapeAnalyzer in RmUnnesTransNetPass

---

compiler/luci/pass/src/CircleOptimizer.cpp

This commit adds fuseRoPE to option_to_pass
It is to add missing code in PR #14099 

[luci/pass] Add option_to_pass for RoPE

---

compute/cker/include/cker/Types.h
compute/cker/include/cker/operation/RmsNorm.h
compute/cker/src/RmsNorm.test.cc

This commit adds RmsNorm operation to cker

[compute/cker] Add RmsNorm operation

---

compute/cker/include/cker/train/operation/MaxPool.h
compute/cker/src/train/MaxPool.test.cc

This PR fixes min-max calculation in MaxPool2D kernel.
* background : https://github.com/Samsung/ONE/pull/14086#discussion_r1777203017

[cker] Fix min-max calculation in MaxPool2D

---

compiler/luci/service/src/Nodes/CircleStridedSlice.cpp

This commit explicitly casts uint32 to int64.
This change is for resolving static analysis tool warning.

[luci] static cast from uint32 to int64

---

compiler/common-artifacts/exclude.lst

This commit excludes Inf_Mul_000 because TestDataGenerator does not support unknown dimensions.

[common-artifacts] Exclude Inf_Mul_000 recipe

---

compiler/luci/service/src/Nodes/CircleReshape.cpp

This will fix to handle 0 in shape for Reshape Op shape inference.

[luci/svc] Handle 0 in shape for Reshape Op shape inference

---

compiler/common-artifacts/exclude.lst

This will exclude Reshape_004 from test data generation, having shape input with 0.

[common-artifacts] Exclude Reshape_004

---

res/TensorFlowLiteRecipes/Reshape_004/test.recipe

This will introduce Reshape_004 tflite recipe with 0 in shape.

[res] Introduce Reshape_004 tflite recipe

---

res/TensorFlowLiteRecipes/Reshape_005/test.recipe

This commit adds TFLiteRecipe for reshape which has non-const shape.
Related: https://github.com/Samsung/ONE/issues/1519
ONE-DCO-Signed-off-by: Jongwon Yang <yjw963@gmail.com>

[res] Add TFLiteRecipe for non-const reshape

---

compiler/luci/pass/src/RemoveUnnecessaryTransposeNetPass.cpp

This PR adds the TaggedShapeAnalyzer::init() function. The init() function explicitly checks some conditions that have to be met for the analyzer.
* draft : https://github.com/Samsung/ONE/pull/14121

[luci/pass] Add TaggedShapeAnalyzer::init() in RmUnnTransNetPass

---

compiler/circle2circle-dredd-recipe-test/test.lst

This commit adds Inf_Mul_000 to circle2circle-dredd-recipe-test.
---
- Related: #13998
- Draft: #14143

[circle2circle-dredd-recipe-test] Add Inf_Mul_000 test

---

runtime/onert/backend/train/TensorManager.cc
runtime/onert/backend/train/TensorManager.h

This PR adds LayerScopeManager into TensorManager.

[onert/train] Add LayerScopeManager into TensorManager

---

compute/cker/include/cker/operation/RmsNorm.h

This commit fixes a build error coming from a missing exceptions-related include
ONE-DCO-1.0-Signed-off-by: Tomasz Dołbniak t.dolbniak@partner.samsung.com

[compute/cker] Fix a build error in RmsNorm.h

---

runtime/onert/backend/train/KernelGenerator.cc
runtime/onert/backend/train/ops/PoolLayer.cc
runtime/onert/backend/train/ops/PoolLayer.h
runtime/onert/core/src/ir/train/UseDefGenerator.cc

This commit supports averagePool2D operation for training

[onert/train] Support averagePool2D operation for training

---

runtime/onert/api/nnfw/include/nnfw_experimental.h
runtime/onert/backend/train/KernelGenerator.cc
runtime/onert/backend/train/ops/LossCategoricalCrossentropyLayer.cc
runtime/onert/backend/train/ops/LossCategoricalCrossentropyLayer.h
runtime/onert/core/include/ir/train/operation/Loss.h
runtime/onert/core/src/compiler/train/TrainableOperationConverter.cc
runtime/onert/core/src/compiler/train/pass/LossInsertionPass.cc
runtime/onert/core/src/ir/train/TrainableGraph.test.cc
runtime/onert/core/src/ir/train/UseDefGenerator.test.cc
runtime/onert/core/src/ir/train/operation/Loss.cc

This commit apply softmax automatically when using CategoricalCrossEntropy loss if models to be trained are not applied softmax.

[onert] Apply softmax to CategoricalCrossEntropy automatically

---

.github/workflows/check-pr-commit.yml

This commit extends the commit message check by adding a human-readable explanation of the failure. The message is displayed when the commit message does not contain the signoff information or when the commit body is too short.
ONE-DCO-1.0-Signed-off-by: Tomasz Dołbniak <t.dolbniak@partner.samsung.com>

[CI] Extend the commit message check

---

res/TensorFlowLiteRecipes/Inf_StridedSlice_000/test.recipe
res/TensorFlowLiteRecipes/Inf_StridedSlice_000/test.rule
res/TensorFlowLiteRecipes/Inf_StridedSlice_001/test.recipe
res/TensorFlowLiteRecipes/Inf_StridedSlice_001/test.rule

This commit adds TFLiteRecipe for dynamic shape StridedSlice.
---
- Related : #13998
- Related: #13968

[res] Add TFLiteRecipe for dynamic shape StridedSlice

---

res/TensorFlowLiteRecipes/Inf_FullyConnected_000/test.recipe
res/TensorFlowLiteRecipes/Inf_FullyConnected_000/test.rule
res/TensorFlowLiteRecipes/Inf_FullyConnected_001/test.recipe
res/TensorFlowLiteRecipes/Inf_FullyConnected_001/test.rule

This commit adds TFLiteRecipe for FullyConnected dynamic shape.
- Related : https://github.com/Samsung/ONE/issues/13998
- Related : https://github.com/Samsung/ONE/pull/13875

[res] Add TFLiteRecipe for FullyConnected dynamic shape

---

runtime/onert/core/src/loader/CircleLoader.cc

This commit adds RmsNorm operation to CircleLoader.

[onert/core] Add RmsNorm to CircleLoader

---

runtime/onert/core/src/compiler/ShapeValidator.cc
runtime/onert/core/src/compiler/ShapeValidator.h

This commit adds RmsNorm to ShapeValidator.

[onert/core] Add RmsNorm to ShapeValidator

---

runtime/onert/backend/cpu/KernelGenerator.cc
runtime/onert/backend/cpu/KernelGenerator.h
runtime/onert/backend/cpu/ops/RmsNormLayer.cc
runtime/onert/backend/cpu/ops/RmsNormLayer.h

This commit adds RmsNorm operation for cpu backend.

[onert/backend] Add RmsNorm operation for cpu backend

---

compiler/circle2circle/src/Circle2Circle.cpp

This will fix wrong enum for fuse_add_with_fully_connected.

[circle2circle] Fix wrong enum

---

runtime/onert/core/src/compiler/train/TrainableOperationConverter.cc
runtime/onert/core/src/compiler/train/TrainableOperationConverter.h

This commit removes unnecessary Loss op conversion from TrainableOperationConverter.

[onert] Remove unnecessary op conversion

---

tests/nnfw_api/lib/CircleGen.cc
tests/nnfw_api/lib/CircleGen.h
tests/nnfw_api/src/GenModelTests/one_op_tests/RmsNorm.test.cc

This commit adds RmsNorm test cases for nnfw API.

[tests/nnfw_api] Add RmsNorm test cases for nnfw API

---

compiler/circle2circle-dredd-recipe-test/test.lst

This commit adds Inf_FullyConnected tests to
circle2circle-dredd-recipe-test.
- Related : https://github.com/Samsung/ONE/issues/13998
- Related : https://github.com/Samsung/ONE/pull/13875
- Related : https://github.com/Samsung/ONE/pull/14157

[circle2circle-dredd-recipe-test] Add Inf_FullyConnected test

---

compiler/circle2circle-dredd-recipe-test/test.lst

This commit adds Inf_Neg_000 to circle2circle-dredd-recipe-test.
- Related : https://github.com/Samsung/ONE/issues/13998
- Related : https://github.com/Samsung/ONE/pull/14158

[circle2circle-dredd-recipe-test] Add Inf_Neg_000 test

---

compiler/luci/pass/src/RemoveUnnecessaryTransposeNetPass.cpp
compiler/luci/pass/src/RemoveUnnecessaryTransposeNetPass.test.cpp

This PR expands RemoveUnnecessaryTransposeNetPass to support rank expansion case.
* draft : https://github.com/Samsung/ONE/pull/14121 
* for : https://github.com/Samsung/ONE/issues/13663

[luci/pass] Support rank expansion case in RmUnnTransNetPass

---

onert-micro/onert-micro/src/train/losses_functions/SparseCrossEntropy.cpp

- Fix wrong sparse CCE loss grad computation

[onert-micro] Fix grad of Sparse Cross Entropy Loss

---

runtime/3rdparty/ggml/src/ggml.c
runtime/onert/backend/cpu/ops/FullyConnectedLayer.cc
runtime/onert/backend/cpu/ops/FullyConnectedLayer.h

This commit enables supporting Q4_0 & Q8_0 FullyConnected OP weight.
---
Related issue: #13909

[onert] Support Q4_0 & Q8_0 FC weight

---

runtime/onert/backend/train/ops/PoolLayer.cc

This commit change casting to static cast.

[train] Modify maxPool2D in training

---

compiler/common-artifacts/exclude.lst

This commit disables RmsNorm test temporarily.
It will be reverted after all related codes are applied.

[common-artifacts] Disable RmsNorm test temporarily

---

runtime/onert/backend/cpu/ExternalContext.cc
runtime/onert/backend/cpu/ExternalContext.h
runtime/onert/backend/cpu/ops/GatherLayer.cc

- Introduce thread count getter
- Count physical core on default setting and use it as thread count

[onert] Revisit CPU ExternalContext

---

.github/workflows/run-onecc-build.yml

This commit updates onecc test workflow to run without docker.

[infra/github] Test onecc without docker

---

runtime/onert/backend/cpu/ops/FullyConnectedLayer.cc
runtime/onert/backend/cpu/ops/GatherLayer.cc

This commit updates usage of ggml in Gather and FullyConnected
- Use vector for plan buffer
- Use general thread number getter

[onert/cpu] Update ggml usage

---

compiler/circlechef/circle/src/Op/RmsNorm.cpp

This commit removes beta(bias) from RmsNorm

[circlechef] Removed beta(bias) from RmsNorm

---

compiler/luci-interpreter/src/kernels/RmsNorm.cpp
compiler/luci-interpreter/src/kernels/RmsNorm.h
compiler/luci-interpreter/src/kernels/RmsNorm.test.cpp
compiler/luci-interpreter/src/loader/KernelBuilder.test.cpp
compiler/luci-interpreter/src/loader/nodes/RmsNorm.cpp

This commit removes beta(bias) of RmsNorm in kernel and loader.

[luci-interpreter] Removed beta(bias) of RmsNorm

---

res/CircleRecipes/RmsNorm_000/test.recipe

This commit removes beta from RmsNorm in circle recipe

[res/CircleRecipes] Removed beta(bias) from RmsNorm

---

compiler/luci/pass/src/FuseRmsNormPass.cpp
compiler/luci/pass/src/QuantizePreCheckerPass.cpp
compiler/luci/pass/src/QuantizePreCheckerPass.test.cpp
compiler/luci/pass/src/QuantizeWeights.cpp
compiler/luci/pass/src/VerifyQuantizedNodeGranularity.h

This commit removes beta(bias) from RmsNorm in luci pass.

[luci/pass] Removed beta(bias) from RmsNorm

---

compiler/dalgona/CMakeLists.txt

This commit updates cmake to support ubuntu 24.04. 
It requires to install python 3.8 explicitly because the default python version is 3.12.

[dalgona] Support ubuntu 24.04

---

compiler/common-artifacts/CMakeLists.txt

This commit updates cmake to support ubuntu 24.04. It requires to install python 3.8 explicitly because the default python version is 3.12.

[common-artifacts] Support ubuntu 24.04

---

compiler/luci/import/src/Nodes/CircleRmsNorm.cpp
compiler/luci/lang/include/luci/IR/Nodes/CircleRmsNorm.h
compiler/luci/lang/src/Nodes/CircleRmsNorm.test.cpp
compiler/luci/logex/src/CircleNodeSummaryBuilders.cpp
compiler/luci/partition/src/Nodes/CircleRmsNorm.cpp
compiler/luci/partition/src/Nodes/CircleRmsNorm.test.cpp

This commit removes beta(bias) from RmsNorm in luci.

[luci] Removed beta(bias) from RmsNorm

---

runtime/onert/backend/train/TensorBuilder.cc
runtime/onert/backend/train/TensorBuilder.h

This PR adds LayerScopeTensor related interface to TensorBuilder.
--------------------------------------

[onert/backend] Add LayerScopeTensor interface to TensorBuilder

---

compiler/luci-interpreter/src/loader/nodes/RmsNorm.cpp

This commit enables assertion which is temporarily disabled.

[luci-interpreter] Enable assertion of RmsNorm in loader

---

compiler/common-artifacts/exclude.lst

This commit enables RmsNorm test which was temporarily disabled.

[common-artifacts] Enable RmsNorm test

---

compiler/one-cmds/how-to-use-one-commands.txt
compiler/one-cmds/onelib/constant.py

Let's add substitute_expand_dims_to_reshape to one command.
---
DRAFT: https://github.com/Samsung/ONE/pull/14164

[one-cmds] Add substitute_expand_dims_to_reshape to one command

---

runtime/onert/core/src/loader/CircleLoader.cc

This commit supports RoPE op in circle loader

[onert] Support RoPE in circle loader

---

compute/cker/include/cker/operation/RoPE.h
compute/cker/src/RoPE.test.cc

This commit adds exception handling when input is odd number

[compute/cker] Add exception handling

---

runtime/onert/backend/train/ops/PoolLayer.cc

This commit fixes type of padding value match with declaration.

[train] Fix padding_value type

---

runtime/onert/core/src/compiler/ShapeValidator.cc

This commit fixes ShapeValidator of RmsNorm to allow rank 3 input and single gamma.

[onert/core] Fix ShapeValidator of RmsNorm

---

res/TensorFlowLiteRecipes/MaxPoolWithArgmax_000/test.rule

THis commit fixes wrong name of the rule

[recipe] Fix typo in MaxPoolWithArgmax rule

---

runtime/onert/backend/train/BackendContext.cc
runtime/onert/backend/train/BackendContext.h
runtime/onert/backend/train/TensorPlanner.cc
runtime/onert/backend/train/TensorPlanner.h

This PR adds TensorPlanner::planLayerScopeTensors() and its caller part in BackendContext.
--------------------------------------

[onert/backend] Add LayerScopeTensor Planning

---

runtime/onert/core/src/compiler/ShapeValidator.cc
runtime/onert/core/src/compiler/ShapeValidator.h

This commit adds RoPE to ShapeValidator

[onert] Add RoPE to ShapeValidator

---

compute/cker/include/cker/operation/RmsNorm.h
compute/cker/src/RmsNorm.test.cc

This commit fixes RmsNorm cker to accept 3 dimension input and single gamma.

[compute/cker] Fix RmsNorm cker

---

res/TensorFlowLiteRecipes/ExpandDims_005/test.recipe
res/TensorFlowLiteRecipes/ExpandDims_005/test.rule

This commit adds recipe for ExpandDims which has constant operand with shape.
---
WHY - does it need a new recipe, not existing ones?
This new recipe is to make a new dredd test for expand_dims operator. Currently, the existing expand_dims recipes have no 'shape' for axis - which is not allowed for current substitute_expand_dims_to_reshape pass I want to test.
To see the full draft, with dredd test passed: https://github.com/Samsung/ONE/pull/14164

[recipe] Add recipe for ExpandDims

---

packaging/nnfw.spec

It fixes build error on odc_build=0.
...........................
I would like to turn off `odc_build` because it builds `nncc`, which takes a long time.
However, building with `odc_build 0` causes the following error:
> cp: cannot stat `build/nncc/compiler/mio-circle08/gen/mio/circle/schema_generated.h': No such file or directory
> ...

[onert] fix tizen gbs build on odc_build=0

---

tests/nnfw_api/lib/CircleGen.cc
tests/nnfw_api/lib/CircleGen.h
tests/nnfw_api/src/GenModelTests/one_op_tests/RoPE.test.cc

This commit adds unit tests for RoPE

[onert/nnfw_api] Add unit tests for RoPE op

---

runtime/onert/backend/train/BackendContext.cc

This PR registers LayerScopeTensor from each layer into tensor registry.
--------------------------------------

[onert/train] Register LayerScopeTensor to registry

---

onert-micro/examples/TizenRT/Makefile

This PR adds makefile example for TizenRT
Makefile was added for the [issue](https://github.com/Samsung/ONE/issues/14184)
ONE-DCO-1.0-Signed-off-by:  Evgenii Maltsev e.maltsev@samsung.com

[onert-micro] This PR adds makefile example for TizenRT

---

compiler/fme-detect/src/EqualizePatternFinder.cpp

This commit supports one more forwardable successors.

[fme-detect] Support one more forwardable successors

---

compiler/fme-detect/src/EqualizePatternFinder.cpp

This commit doesn't forward Gelu when finding a pattern. Turns out that Gelu shouldn't have been forwarded with this case.

[fme-detect] Do not forward Gelu

---

compiler/fme-apply/src/InsertScaleShift.cpp

This commit applies missing abs to weight.

[fme-apply] Apply abs to weight

---

compiler/dalgona/src/Utils.cpp

This commit adds bool type in numpyArray function.
I needed this type when I run dalgona with LLM model (eq, logical ops)

[dalgona] Add bool type

---

compiler/dalgona/src/PostOperatorHook.h

This commit considers FullyConnected with no bias.

[dalgona] Consider no bias in FullyConnected

---

compute/cker/include/cker/operation/RmsNorm.h
compute/cker/src/RmsNorm.test.cc

This commit fixes shape assert error when running model including RMSNorm operation.
issue: https://github.com/Samsung/ONE/issues/14245

[compute/cker] Fix RMSNorm shape assert error

---

res/TensorFlowLiteRecipes/Net_Decomposed_GRU_000/test.recipe

This PR adds recipe for decomposed GRU(This recipe will be used for validating --fuse_gru pass in circle2circle)
draft : https://github.com/Samsung/ONE/pull/14237
issue : https://github.com/Samsung/ONE/issues/12263

[res] Add recipe for Decomposed GRU

---

compiler/record-minmax/include/HDF5Iterator.h
compiler/record-minmax/src/HDF5Iterator.cpp

This introduces an iterator for HDF5 format.
---
Draft PR: https://github.com/Samsung/ONE/pull/14257

[record-minmax] Introduce HDF5Iterator

---

compiler/record-minmax/include/ListFileIterator.h
compiler/record-minmax/src/ListFileIterator.cpp

This introduces an iterator for list format.
---
Draft PR: https://github.com/Samsung/ONE/pull/14257

[record-minmax] Introduce ListFileIterator

---

compiler/caffegen/README.md

This corrects typos and formatting.

[caffegen] Minor doc fix

---

compiler/angkor/README.md

This corrects a typo and formatting.

[angkor] Minor doc fix

---

compiler/mir/Readme.md

This removes trailing whitespace and adds a missing article.

[mir] Minor doc fix

---

docs/howto/how-to-use-nnfw-api.md

This fixes a broken link in the how-to-use-nnfw-api.md file.

[docs/howto] Fix broken link in 'how to use nnfw api'

---

runtime/onert/backend/cpu/ops/GatherLayer.cc

This fixes checking indices tensor shape in GatherLayer. 
If dimension count is 4 and dim(0) != 0, it should throw exception, but it didn't.

[onert/backend] Fix checking indices tensor shape in GatherLayer

---

runtime/onert/core/src/exec/MultiModelExecutors.cc

It fixes to read output, not input on interpreting `from`.

[onert] Fix multimodel connection in executors

---

nnpackage/schema/circle_schema.fbs

This adds mxfp4 and mxint8 to circle schema.
---
Draft PR: #14294

[nnpackage] Add mx dtypes to schema

---

compiler/loco/include/loco/IR/DataType.h

This adds MXFP4 and MXINT8.
---
Draft PR: https://github.com/Samsung/ONE/pull/14294

[loco] Add mx data type

---

compiler/luci/export/src/CircleExporterUtils.cpp
compiler/luci/import/src/CircleReader.cpp
compiler/luci/logex/src/CircleNodeSummaryBuilders.cpp

This supports mx type in luci.
---
Draft PR: https://github.com/Samsung/ONE/pull/14294

[luci] Support mx type

---

compiler/circlechef/circle/src/Convert.cpp
compiler/circlechef/core/src/Convert.cpp
compiler/circlechef/core/src/Convert.test.cpp
compiler/circlechef/proto/circlechef.proto

This introduces MXFP4 and MXINT8.
---
Draft PR: https://github.com/Samsung/ONE/pull/14294

[circlechef] Support mx data type

---

res/CircleRecipes/CircleBatchMatMul_MXFP4_000/test.recipe
res/CircleRecipes/CircleBatchMatMul_MXINT8_000/test.recipe

This adds mx type BMM recipes.
---
Draft PR: https://github.com/Samsung/ONE/pull/14294

[res] Add mx type BatchMatMul recipes

---

compute/cker/include/cker/operation/BatchMatMul.h
compute/cker/include/cker/operation/Helper/BatchMatMulParams.h
compute/cker/include/cker/operation/optimized/BatchMatMul.h

This commit adds an optimized version of the BatchMatMul kernel. The optimization targets the x86 architecture, in all other cases the code is compiled with existing reference kernel.
The new kernel calls the optimized::Gemm function which uses Eigen internally.
Additionally to avoid code duplication a new BatchMatMulParams struct is introduced and reused in both reference and optimized kernels.

[compute/cker] Optimize BatchMatMul for x86

---

compiler/crew/src/PConfigJson.h

This commit adds cstdint header include.
It will resolve build fail on gcc-13.

[crew] Add cstdint header include

---

compiler/souschef/src/LexicalCast.cpp

This commit adds cstdint header include.
It will resolve build fail on gcc-13.

[souschef] Add cstdint header include

---

compiler/luci/pass/src/ForwardTransposeOpPass.cpp

This relaxes assert condition in ForwardTransposeOpPass.

[luci/pass] Relax assert in ForwardTransposeOpPass

---

infra/nnfw/python/setup.py

This commit updatese python packaging to include core library "libonert_core.so"

[onert/python] Include core library in package

---

compiler/luci/pass/src/ForwardTransposeOpPass.cpp
compiler/luci/pass/src/ForwardTransposeOpPass.test.cpp

This forwards transpose Ops over binary Op (add, mul).
---
Related to: https://github.com/Samsung/ONE/issues/14322

[luci] Forward transpose over binary Op

---

compute/ruy/include/ruy/Shape.h
compute/ruy/include/ruy/Types.h
compute/ruy/include/ruy/operation/Conv.h

This commit removes UNUSED_RELEASE() macro in compute/ruy.
---
Refer #14336

[compute/ruy] Remove UNUSED_RELEASE macro

---

tools/model_explorer_circle/src/circle_adapter/main.py

It adds input, output and operators in circle model to model explorer graph as a separted nodes.
For Input and Output, it added extra nodes named as 'GraphInputs' and 'GraphOutputs'.
They are the root and the leaf node in the graph respectively.
The notation is followed the view of the `tflite` model in Model Explorer.
---
draft: #14318
issue: #14307

[tools/model_explorer_circle] Add graph nodes in circle model

---

.github/workflows/run-onert-gbs-build.yml

This commit introduces github workflow for runtime gbs build.

[github] Introduce gbs build test

---

tools/model_explorer_circle/src/circle_adapter/main.py

The const tensor in circle model are orphan node that doesn't have source node. 
So, it adds it as a separate node with special type 'pseudo_const' that is invisible in the the graph,
but is annotated at the node which uses it.
---
draft: #14318
issue: #14307

[tools/mec] Add pseudo const nodes for const tensors

---

tools/model_explorer_circle/src/circle_adapter/main.py

It adds a namespace to the operator node based on the name of its output tensor.
It helps folding graph by grouping of operators that uses same namespace.
---
* issue: https://github.com/Samsung/ONE/issues/14307
* draft: https://github.com/Samsung/ONE/pull/14318

[tools/mec] Add namespace to operator

---

tools/model_explorer_circle/src/circle_adapter/main.py

It appends the metadata of output tensor, such as tensor shapes and name, to each node.
---
* issue : #14307 
* draft : #14318

[tools/mec] Add metadata of output tensor to each node

---

tools/model_explorer_circle/src/circle_adapter/main.py

It adds the attributes of each operator such as 'StrideW', 'StrideH', and 'FusedActivationFunction' according to the operator type.
---
* issue: #14307 
* draft: #14318

[tools/mec] Add attributes of operator node

---

compute/cker/include/cker/Shape.h
compute/cker/include/cker/Types.h
compute/cker/include/cker/operation/ArgMinMax.h
compute/cker/include/cker/operation/Concatenation.h
compute/cker/include/cker/operation/FullyConnected.h
compute/cker/include/cker/operation/FullyConnectedSparse16x1.h
compute/cker/include/cker/operation/FusedBatchNorm.h
compute/cker/include/cker/operation/InstanceNorm.h
compute/cker/include/cker/operation/ReduceMean.h
compute/cker/include/cker/operation/SpaceToBatchND.h
compute/cker/include/cker/operation/SqDiff.h
compute/cker/include/cker/operation/StridedSlice.h
compute/cker/include/cker/operation/Transpose.h
compute/cker/include/cker/operation/Unpack.h
compute/cker/include/cker/operation/optimized/Conv.h
compute/cker/include/cker/operation/optimized/DepthwiseConvFloat.h
compute/cker/include/cker/operation/optimized/DepthwiseConvUint8.h
compute/cker/include/cker/operation/optimized/integer_ops/DepthwiseConvInt8.h
compute/cker/include/cker/operation/reference/Conv.h
compute/cker/include/cker/operation/reference/integer_ops/DepthwiseConvHybrid.h
compute/cker/include/cker/operation/reference/integer_ops/DepthwiseConvUInt8.h

This commit removes UNUSED_RELEASE() macro in cker.
---
Refer #14336

[compute/cker] Remove UNUSED_RELEASE macro

---

compute/cker/include/cker/ShapeIterator.h
compute/cker/include/cker/Utils.h
compute/cker/src/ShapeIterator.test.cc

This commit introduces a utility that effectively makes the Shape objects iterable. It's an iterator class which points to the individual dimensions in the shape and allows the interoperability of the Shape class and STL algorithms as well as range-based for loops. The iterator fulfills the requirements of a bidirectional iterator.
In addition this commit contains one extra utility which allows the Shape objects conversion to std::string by contatenating them with a comma.

[compute/cker] Introduce the ShapeIterator

---

.github/workflows/pub-tools-mec-pypi.yml

This will introduce workflow to publish model-explorer-circle to pypi.org.

[github] Introduce workflow to publish model-explorer-circle

---

infra/nnfw/python/setup.py

This commit updates setup parameters.
- Update description: nnfw -> onert
- Add URL
- Add license
- Add 'has_ext_modules':  update wheel naming automatically for wheel installation
- Add package dependency

[onert/python] Update setup parameters

---

tools/model_explorer_circle/HOWTO.md

Since module name was changed from 'circle_adapter' to 'module_explorer_circle',
it also needs to update the extension name in HOWTO.
---
* Related w/ : #14365

[tools/mec] Fix module name in HOWTO

---

tools/model_explorer_circle/src/model_explorer_circle/main.py

If the model is quantized, it will show quantization parameters of each tensors.
---
* issue : #14368

[tools/mec] Add quantization parameters to tensor information

---

compute/cker/include/cker/operation/optimized/BatchMatMul.h

This commit removes the obsolete parametrization of the BatchMatMul x86 optimized kernel. The reason is that the storage order attribute of the MatrixParams class is later ignored by the x86 Gemm implementation using Eigen.
ONE-DCO-1.0-Signed-off-by: Tomasz Dolbniak t.dolbniak@partner.samsung.com

[compute/cker] Remove the storage order parametrization from BatchMatMul

---

compiler/circle-interpreter/CMakeLists.txt
compiler/circle-interpreter/src/CircleInterpreter_cffi.cpp

This commit introduces a library for C-Python interaction.
Related: #14352 

[circle-interpreter] Introduce a library for C-Python interaction

---

compiler/luci/pass/src/QuantizationUtils.h

This commit add the `fp32_to_uint8_cast` in the header file.
Related Issue : https://github.com/Samsung/ONE/issues/13480
Draft PR: https://github.com/Samsung/ONE/pull/13585
ONE-DCO-1.0-Signed-off-by: y01000.you <y01000.you@samsung.com>

[luci/pass] Add fp32_to_uint8_cast to header

---

runtime/onert/core/include/odc/IQuantizer.h
runtime/onert/core/include/odc/QuantizeManager.h
runtime/onert/core/src/odc/QuantizeManager.cc
runtime/onert/odc/MinMaxReader.cc
runtime/onert/odc/MinMaxReader.h
runtime/onert/odc/Quantizer.cc
runtime/onert/odc/Quantizer.h

This PR for `odc: auto-compilation` (hidden switching mechanism) introduces changes in Quantizer, MinMaxReader and QuantizeManager. 
Introduction functions for set up of the minmax threshold and cheсking readiness for quantization. 
Function for removing minmax file also was added.
For [Issue]( https://github.com/Samsung/ONE/issues/13288). 
From [Draft](https://github.com/Samsung/ONE/pull/13530).
ONE-DCO-1.0-Signed-off-by: Evgenii Maltsev e.maltsev@samsung.com

[onert/odc] Auto-compilation. Minmax threshold and quantization Readiness

---

runtime/onert/backend/cpu/CMakeLists.txt
runtime/onert/backend/cpu/SharedMemoryOperands.cc
runtime/onert/backend/cpu/SharedMemoryOperands.h
runtime/onert/backend/cpu/SharedMemoryOperands.test.cc

This commit adds capabilities to find operands linked which Tensors which can share memory buffers. It's applicable for ops like Reshape, Squeeze and ExpandsDims (where only shape is changed and data is not modified).
Draft: https://github.com/Samsung/ONE/pull/14057

[onert] Introduce capabilities to find operands which can share memory

---

tools/model_explorer_circle/src/model_explorer_circle/main.py

This is a bug fix for faulty numbering of constant tensors' IDs.
The constant tensor's id is currently 'Input_Node_ID + 0' must start with 'Input_Node_ID + 1'.

[tools/mec] Fix the node id error for const tensors

---

.github/workflows/run-onert-gbs-build.yml

This commit fixes gbs rpm cache path.

[infra/github] Fix gbs cache path

---

compute/cker/include/cker/operation/Conv.h
compute/ruy/include/ruy/operation/Conv.h

This commit changes variable length array to vector in cker and ruy.
---
VLA fails on clang 18. (#14385)

[compute] Remove variable length array

---

compiler/luci/pass/src/FuseInstanceNormPass.cpp

This will adjust input channel as second dimension for 3D Instance Norm,
in FuseInstanceNormPass.

[luci/pass] Adjust input channel for 3D InstNorm

---

.github/workflows/run-onert-android-build.yml

This commit changes NDK version to use default version of github-hosted runner.

[infra/github] Change NDK version

---

runtime/onert/api/nnfw/src/nnfw_api_internal.cc

This commit uses c++17 filesystem to handle model paths in load_model_from_modelfile.

[onert] Use c++17 filesystem for model path handling

---

runtime/onert/api/nnfw/src/nnfw_api_internal.cc
runtime/onert/api/nnfw/src/nnfw_api_internal.h

This commit cleans up header includes in nnfw_api_internal.h/cc.
- Reorder includes
- Remove class/struct declaration in nnfw_api_internal.h
- Use header include because it is not public header

[onert] Clean up header include in nnfw_api_internal

---

runtime/onert/core/include/exec/Execution.h
runtime/onert/core/src/exec/Execution.cc

This PR for `odc:auto-compilation` introduces OdcInfo structure and input/output buffers in Execution. 
For [Issue]( https://github.com/Samsung/ONE/issues/13288). 
From [Draft](https://github.com/Samsung/ONE/pull/13530).
ONE-DCO-1.0-Signed-off-by: Evgenii Maltsev e.maltsev@samsung.com

[onert/odc] Auto-compilation. Input/output buffers in Execution

---

runtime/onert/api/nnfw/src/nnfw_api_internal.cc
runtime/onert/api/nnfw/src/nnfw_api_internal.h

This commit updates nnfw_api_internal to use filesystem path for model path.

[onert] Use filesystem path for model path

---

.github/workflows/run-onert-gbs-build.yml
infra/debian/runtime/rules
packaging/nnfw.spec
packaging/onert-plugin.pc.in
packaging/onert.pc.in

This commit updates spec file to use symbolic link for pc file. 
It changes pc file name.
It includes workflow fix to check packaging directory changes.

[infra/gbs] Symbolic link for pc file

---

tools/model_explorer_circle/src/model_explorer_circle/main.py

It adds sanitizer code for a model which have quantization parmeters but scale is not intialized.

[tools/mec] Check if a scale of quantization is None

---

tools/model_explorer_circle/src/model_explorer_circle/main.py

It changes the name of shape key in output metadata to 'tensor_shape' following the tensorflow's.

[tools/mec] Rename the shape in output metadata

---

infra/nnfw/cmake/buildtool/config/config_armv7hl-tizen.cmake
infra/nnfw/cmake/buildtool/config/config_armv7l-tizen.cmake

This commit adds 'mfp16-format=ieee' for tizen arm build.

[infra/onert] Add tizen arm build fp16 flag

---

runtime/onert/api/nnfw/src/nnfw_api.cc
runtime/onert/api/nnfw/src/nnfw_internal.cc
runtime/onert/api/nnfw/src/nnfw_session.cc
runtime/onert/api/nnfw/src/nnfw_session.h

This commit relocates API functions
- Rename internal API implementation file from nnfw_debug.cc to nnfw_internal.cc
- Move some internal API implementation to src/nnfw_internal.cc
- Rename nnfw_api_internal.h/cc to nnfw_session.h/cc

[onert] Relocate API functions

---

runtime/3rdparty/ggml/src/CMakeLists.txt

It removes the specific arch on ggml cross armv7l linux build. Previously, ggml specifies -mfpu=neon-fp-armv8, which may cause illegal instruction signal during running ggml_quantize_row_q8_0, especially compiled with gcc-13 -On, where n = 1,2,3 on odroid xu4. (ARMv7 Cortex-A15).
Related: #14391

[onert/ggml] Don't specify arch on armv7l linux build

---

infra/nnfw/cmake/CfgOptionFlags.cmake
infra/nnfw/cmake/packages/ARMComputeConfig.cmake
runtime/onert/CMakeLists.txt
tests/custom_op/CMakeLists.txt
tests/nnapi/CMakeLists.txt
tests/nnfw_api/CMakeLists.txt
tests/scripts/CMakeLists.txt
tests/tools/onert_run/CMakeLists.txt
tests/tools/onert_train/CMakeLists.txt
tests/tools/tflite_comparator/CMakeLists.txt

- Split category: project -> project, runtime, test
- Remove unused option: BUILD_TFLITE_VANILLA_RUN, BUILD_TFLITE_LOADER, BUILD_CIRCLE_LOADER
- Remove BUILD_EXT_MULTITHREAD
- Use multithread if EXTERNALS_BUILD_THREADS is set and value is not 1
- Remove INSTALL_TEST_SCRIPTS: always install test scripts
- Fix help text

[infra/onert] Cleanup cmake option for onert project

---

infra/nnfw/cmake/CfgOptionFlags.cmake

This commit removes BUILD_TFLITE_ACCURACY option.
It is not used anymore.

[infra/onert] Remove BUILD_TFLITE_ACCURACY

---

infra/debian/runtime/rules
infra/nnfw/cmake/CfgOptionFlags.cmake
packaging/nnfw.spec
runtime/onert/sample/minimal/CMakeLists.txt

This commit change minimal app build condition
- Enable build as default to check build error in CI
- Disable build on debian/rpm packaging

[infra/onert] Change minimal app build condition

---

compiler/luci-interpreter/src/kernels/Reshape.cpp
compiler/luci-interpreter/src/kernels/Reshape.test.cpp

This adds a check for num_elements.
---
Related to: #14445

[luci-interpreter] Add check for Reshape

---

infra/cmake/modules/ExternalProjectTools.cmake

This commit introduces DISABLE_EXTERNAL_WARNING option. 
It is used to disable warnings from external library build.

[infra/cmake] Introduce DISABLE_EXTERNAL_WARNING option

---

infra/nncc/CMakeLists.txt

This commit adds '-Wno-overloaded-virtual' to the strict build for workaround in gcc 13.

[infra/nncc] Fix strict build fail by overloaded-virtual

---

compiler/luci-interpreter/src/kernels/CMakeLists.txt

This commit adds workaround to avoid array-bounds error in the build process with gcc-13.

[luci-interpreter] Fix build fail by array-bounds error

---

compiler/arser/include/arser/arser.h

This commit reorders the name field to follow constructor initialization order.
---
Draft: #14450 #14440

[arser] Reorder name field

---

compiler/luci-interpreter/src/core/RuntimeGraph.h
compiler/luci-interpreter/src/loader/GraphLoader.h
compiler/luci-interpreter/src/loader/ModuleLoader.h

This commit reorders the variables to remove "-Wno-reorder" workaround.
---
Draft: #14450

[luci-interpreter] Reorder variable

---

infra/nnfw/cmake/CfgOptionFlags.cmake

This commit set cmake option "DISABLE_EXTERNAL_WARNING" to turn off warning from external.
---
Draft: #14440

[infra/onert] Turn off warning from external

---

infra/nncc/CMakeLists.txt

This commit removes "-Wno-reorder" flag from strict build.
---
Draft: #14450

[infra] Remove no-reorder from strict build

---

compiler/luci/pass/src/SubstituteExpandDimsToReshapePass.cpp
compiler/luci/pass/src/SubstituteExpandDimsToReshapePass.test.cpp

This supports scalar axis in SubstituteExpandDimsToReshapePass.

[luci] Support scalar axis in SubstituteExpandDimsToReshapePass

---

compiler/luci/pass/include/luci/Pass/QuantizeDequantizeWeightsWithGPTQPass.h
compiler/luci/pass/src/QuantizeDequantizeWeightsWithGPTQPass.cpp

This commit introduces QuantizeDequantizeWeightsWithGPTQPass for weight quant.
related issue: https://github.com/Samsung/ONE/issues/13480
related draft: https://github.com/Samsung/ONE/pull/13585
ONE-DCO-1.0-Signed-off-by: y01000.you <y01000.you@samsung.com>

[luci/pass] Introduce QuantizeDequantizeWeightsWithGPTQPass

---

infra/nnfw/cmake/CfgOptionFlags.cmake

This commit reverts turn off external build warning. 
It turns off not only external build warning but also internal build warning.
---
It reverts #14457

[infra/onert] Revert turn off external warning

---

compiler/luci/pass/src/ForwardReshapeToUnaryOpPass.cpp
compiler/luci/pass/src/ForwardReshapeToUnaryOpPass.test.cpp

This updates rank of constant after reshape is forwarded.

[luci] Fix ForwardRehsapeToUnaryOpPass bug

---

compiler/circle-input-names/CMakeLists.txt
compiler/circle-input-names/README.md
compiler/circle-input-names/requires.cmake
compiler/circle-input-names/src/circle-input-names.cpp
compiler/circle-input-names/src/circle-input-names.test.cpp

The new tool 'circle_input_names' displays the all input names of each operator in JSON format.
This will be used to generate input metadata in Model Explorer.
---
* draft : #14458
* for : #14427

[compiler/circle-input-names] Introduce a new tool displaying input names

---

runtime/onert/api/nnfw/include/nnfw.h
runtime/onert/api/nnfw/src/nnfw_api.cc
runtime/onert/api/nnfw/src/nnfw_internal.cc
runtime/onert/api/nnfw/src/nnfw_session.cc
runtime/onert/api/nnfw/src/nnfw_session.h

This commit updates API to support model file loading from model path.
---
Related issue: #14466

[onert] Support model file loading from model path

---

runtime/onert/api/nnfw/include/nnfw.h
runtime/onert/api/nnfw/src/nnfw_api.cc

This commit updates the comment of nnfw_load_model_from_file and parameter name.

[onert] Update nnfw_load_model_from_file comment and parameter

---

tests/nnfw_api/src/OdcAutoCompilation.test.cc
tests/tools/onert_run/src/onert_run.cc
tests/tools/onert_train/src/onert_train.cc
tests/tools/tflite_comparator/src/tflite_comparator.cc

This commit updates test code to use nnfw_load_model_from_file API instead of nnfw_load_model_from_modelfile internal API.

[onert/test] Use file loading API for test

---

runtime/onert/api/nnfw/include/nnfw_internal.h
runtime/onert/api/nnfw/src/nnfw_internal.cc

This commit removes model file loading internal API. 
Official API includes this functionality.

[onert] Remove modelfile loading internal API

---

tools/model_explorer_circle/src/model_explorer_circle/main.py

It adds the indexed name to variadic inputs.
(e.g. 2 inputs for CONCATENATION : 'values[0]', values[1]')

[tools/mec] Append variadic inputs names with index

---

tools/model_explorer_circle/src/model_explorer_circle/main.py

It fixes to show real operator name of custom op node.

[tools/mec] Show real operator name of custom op

---

onert-micro/onert-micro/src/train/kernels/FullyConnected.cpp
onert-micro/onert-micro/src/train/kernels/MaxPool2D.cpp

This commit fixes errors in MaxPool2D and FullyConnected training kernels.

[onert-micro] Fix MaxPool2D and FullyConnected training kernels

---

compiler/luci/pass/src/PropagateQParamBackwardPass.cpp
compiler/luci/pass/src/QuantizeOnnxFakeQuantModelPass.cpp

This propagates qparam backward in onnx-fake quant model.

[luci] Propagate qparam backward in onnx-fake quant model

---

compiler/luci/pass/src/ReplaceNonConstFCWithBatchMatMulPass.cpp
compiler/luci/pass/src/ReplaceNonConstFCWithBatchMatMulPass.test.cpp

This supports quantized inputs in ReplaceNonConstFCWithBatchMatMulPass.

[luci] Support quantized inputs in ReplaceNonConstFCWithBatchMatMulPass

---

compiler/luci/pass/src/InsertQuantizeOpOnDTypeMismatch.cpp
compiler/luci/pass/src/InsertQuantizeOpOnDTypeMismatch.h

This supports Transpose Op in InsertQuantizeOpOnDTypeMismatch.

[luci] Support Transpose in InsertQuantizeOpOnDTypeMismatch

---

infra/nnfw/cmake/buildtool/config/config_armv7hl-tizen.cmake
infra/nnfw/cmake/buildtool/config/config_armv7l-tizen.cmake

This commit removes compiler architecture flag on armv7l and armv7hl platforms. It will use default setting on gbs build.

[infra] Remove custom arch flag for tizen build

---

runtime/onert/odc/Quantizer.h

This commit add override keyword to Quantizer::setMinMaxRecordsThreshold. 
It will fix build fail on clang.

[onert] Add override to setMinMaxRecordsThreshold

---

compiler/luci/pass/src/PropagateQParamBackwardPass.cpp

This removes a redundant exception.
---
Related to: https://github.com/Samsung/ONE/issues/14503

[luci] Remove redundant exception

---

compiler/luci-interpreter/src/kernels/StridedSlice.cpp
compiler/luci-interpreter/src/kernels/StridedSlice.test.cpp

This commit removes assert that limit StrideSlice rank to 4. TF 2.8 allows to inference this operator with rank 5.
Issue: https://github.com/Samsung/ONE/issues/14165

[luci-interpreter] Relax StrideSlice rank limitations

---

docs/howto/how-to-build-compiler.md

This commit updates the documentation for building the compiler from source
- Base ubuntu version for document: 18.04 -> 20.04
- Remove required package for format check, coverage build, runtime build
- Fix workspace setting
- Update required python version for tensorflow

[doc] Update compiler build howto documentation

---

tests/tools/onert_run/CMakeLists.txt
tests/tools/onert_run/src/args.cc
tests/tools/onert_run/src/args.h
tests/tools/onert_run/src/h5formatter.cc
tests/tools/onert_run/src/nnfw_util.cc
tests/tools/onert_run/src/onert_run.cc
tests/tools/onert_run/src/rawformatter.cc
tests/tools/onert_run/src/rawformatter.h

This commit applies strict build to onert_run.
---
Related: #14440

[onert/test] Apply strict build to onert_run

---

tests/tools/onert_train/CMakeLists.txt
tests/tools/onert_train/src/args.cc
tests/tools/onert_train/src/args.h
tests/tools/onert_train/src/formatter.h
tests/tools/onert_train/src/h5formatter.cc
tests/tools/onert_train/src/measure.h
tests/tools/onert_train/src/metrics.cc
tests/tools/onert_train/src/nnfw_util.cc
tests/tools/onert_train/src/onert_train.cc
tests/tools/onert_train/src/rawformatter.cc

This commit applies strict build to onert_train..
---
Related: https://github.com/Samsung/ONE/pull/14440

[onert/test] Apply strict build to onert_train

---

tests/tools/tflite_comparator/CMakeLists.txt
tests/tools/tflite_comparator/src/tflite_comparator.cc

This commit applies strict build to tflite_comparator.
---
Related: https://github.com/Samsung/ONE/pull/14440

[onert/test] Apply strict build to tflite_comparator

---

infra/docker/focal/Dockerfile

This commit adds a manual installation of libtsan_preinit.o in ubuntu 20.04 docker image. 
It is workaround for the build failure due to missing libtsan_preinit.o in libtsan0 package.
---
Related issue: #11202

[infra/docker] Install libtsan_preinit.o manually

---

runtime/onert/api/python/include/nnfw_api_wrapper.h
runtime/onert/api/python/src/nnfw_api_wrapper.cc
runtime/onert/api/python/src/nnfw_api_wrapper_pybind.cc

This commit adds wrapping CAPIs for training
- Add the include guard for nnfw_api_wrapper.h
- Introduce the namespace onert::api::python
- Wrap CAPIs for training

[onert] Add wrapping CAPIs for training

---

runtime/onert/api/python/include/nnfw_api_wrapper.h
runtime/onert/api/python/src/nnfw_api_wrapper.cc

This commit separates prepare function from initializing session instance.

[onert/python] Separate prepare from session constructor

---

runtime/onert/api/python/package/common/basesession.py
runtime/onert/api/python/package/infer/session.py

This commit allows calling compilation(prepare) by infer session.
- Introduce recreating internal session(nnfw_session) into BaseSession
- Introduce compile function that can recreate internal session
- Modify __getattr__ of BaseSession strictly

[onert/python] Allow calling compilation by infer session

---

.github/workflows/build-dev-docker.yml
infra/docker/focal/Dockerfile
infra/docker/jammy/Dockerfile
infra/docker/noble/Dockerfile

This commit introduces a GitHub Actions workflow to build docker image and test, and push it to the docker hub.

[infra/github] Intrdocue docker build workflow

---

runtime/onert/api/python/include/nnfw_traininfo_bindings.h
runtime/onert/api/python/src/bindings/nnfw_api_wrapper_pybind.cc
runtime/onert/api/python/src/bindings/nnfw_session_bindings.cc
runtime/onert/api/python/src/bindings/nnfw_traininfo_bindings.cc

This commit binds training APIs.
- Bind trainings APIs related to session
- Bind trainings APIs related to traininfo

[onert/python] bind training APIs

---

.github/workflows/run-onert-build.yml

This commit introduces a new workflow to run x64 onert build and tests on GitHub Actions.

[infra/github] Introduce x64 onert test workflow

---

runtime/onert/core/src/loader/BaseLoader.h

This commit use the shape signature in base loader. 
if there is an unknown shape in the circle, maintain the unknown shape

[onert] Use the shape signature in baseloader

---

.gitignore
docs/howto/how-to-build-runtime.md
docs/howto/how-to-cross-build-runtime-for-arm.md

Small fixes to documentation, based on trying to cross-build to armv7l on Ubuntu 24.04 LTS.
Additionally, as python virtual env is nice to have option, add `.venv` to `.gitignore` file.
ONE-DCO-1.0-Signed-off-by: Marcin Słowiński <m.slowinski2@samsung.com>

Fix docs for cross-build

---

runtime/onert/api/python/package/experimental/train/losses/__init__.py
runtime/onert/api/python/package/experimental/train/losses/cce.py
runtime/onert/api/python/package/experimental/train/losses/loss.py
runtime/onert/api/python/package/experimental/train/losses/mse.py

This commit introduces loss API.
- cce.py : Categorical CrossEntropy Loss
- mse.py : Mean Squared Error Loss

[onert/python] Introduces loss API

---

runtime/onert/api/python/package/experimental/train/metrics/__init__.py
runtime/onert/api/python/package/experimental/train/metrics/categorical_accuracy.py
runtime/onert/api/python/package/experimental/train/metrics/metric.py
runtime/onert/api/python/package/experimental/train/metrics/registry.py

This commit introduces metric APIs.
- categorical_accuracy.py : CategoricalAccuracy class
- metric : Metric class to be provided custom metric

[onert/python] Introduce metric API

---

.github/workflows/run-onert-build.yml

This commit adds arm32/64 onert test to onert test workflow.

[infra/github] Add arm32/64 onert test

---

tools/model_explorer_circle/src/model_explorer_circle/main.py

The tensor buffer can be empty for immature model, so it needs to check if the buffer is available when it tries to fill value attribute.

[tools/mec] Add value attribute only when available

---

compiler/luci/pass/src/ExpandBroadcastConstPass.cpp
compiler/luci/pass/src/ExpandBroadcastConstPass.test.cpp

Let's fix a bug in ExpandBroadcastConstPass.
---
DRAFT: #14555
FOR: #14554

[luci/pass] Fix ExpandBroadcastConstPass

---

.github/workflows/check-format.yml
.yapfignore
infra/command/format

This commit updates format checker for python
- Use .yapfignore file in root directory instead of .FORMATDENY in each directory to ignore files from yapf
- Update yapf version to 0.43.0: update package dependency
---
Draft: #14556

[infra] Update python format checker

---

compiler/luci-pass-value-py-test/test.lst

Let's add tests for expand_broadcast_const option.
---
DRAFT: https://github.com/Samsung/ONE/pull/14555
FOR: https://github.com/Samsung/ONE/issues/14554

[luci-pass-value-py-test] Add tests for expand_broadcast_const option

---

tools/CMakeLists.txt

This commit changes adding tools directory manually in cmake instead of using macro. 
It will help to divide build process for each tool from runtime build.

[tools] Add subdirectoy manually for tools cmake

---

runtime/onert/api/python/package/experimental/train/optimizer/__init__.py
runtime/onert/api/python/package/experimental/train/optimizer/adam.py
runtime/onert/api/python/package/experimental/train/optimizer/optimizer.py
runtime/onert/api/python/package/experimental/train/optimizer/sgd.py

This commit introduces optimizer API.
- adam.py : Adam optimizer class
- sgd.py  : SGB optimizer class

[onert/python] Introduce optimizer API

---

compiler/luci/pass/src/helpers/ArrayIndex.cpp
compiler/luci/pass/src/helpers/ArrayIndex.h
compiler/luci/pass/src/helpers/ArrayIndex.test.cpp

Let's introduce Array4DIndex to help calculating 4D array index.
---
For #14552
Dr #14564
To extend the funtionality of `extend broadcast const` pass, I introduce this helper.

[luci/pass] Introduce ArrayIndex helper

---

res/TensorFlowLiteRecipes/Add_007/test.recipe
res/TensorFlowLiteRecipes/Add_008/test.recipe
res/TensorFlowLiteRecipes/Add_009/test.recipe

Let's add 3 more recipes for broadcast Add.
---
From #14564
For #14552

[res] Add TensorFlowLiteRecipes for broadcast Add

---

compiler/mir/src/mir_caffe2_importer/caffe2_importer.cpp
compiler/mir/src/mir_caffe_importer/caffe_importer.cpp
compiler/mir/src/mir_onnx_importer/ONNXImporterImpl.cpp

This commit adapts the code in mir to the changes in the Protobuf API.
Related: https://github.com/Samsung/ONE/pull/14535

[mir] Adapt to the Protobuf API changes

---

.github/workflows/build-dev-docker.yml
.github/workflows/generate-rootfs.yml
.github/workflows/run-onecc-build.yml
.github/workflows/run-onert-android-build.yml
.github/workflows/run-onert-build.yml
.github/workflows/run-onert-gbs-build.yml
.github/workflows/run-onert-micro-unit-tests.yml

This commit updates workflows to cancel running workflows including heavy overhead when a PR is update.

[infra/github] Cancel running workflow on PR update

---

compiler/locop/src/CanonicalNodeSummaryBuilder.cpp

This will fix for static analysis to check nullptr.

[locop] Fix for static analysis

---

infra/nnfw/command/copyright-check

This commit updates the copyright checker
- Use ls-files patterns to find file and exclude files
- Don't use .FORMATDENY files to exclude directory
---
Draft: #14556

[infra] Update copyright checker

---

runtime/onert/api/python/package/experimental/train/optimizer/registry.py

This commit introduces OptimizerRegistry that can create optimizers by names.

[onert/python] Introduce OptimizerRegistry

---

runtime/onert/api/python/package/experimental/train/losses/registry.py

This commit introduces LossRegistries.
- create_loss : Create a loss instance by name
- map_loss_function_to_enum : Map a loss instance to the appropriate enum value.

[onert/python] Introduce LossRegistry

---

compiler/ann-api/include/.clang-format

This commit removes .FORMATDENY file and replaces it to .clang-format's DisableFormat.
---
Draft: https://github.com/Samsung/ONE/pull/14556

[ann-api] Remove .FORMATDENY file

---

compiler/ann-ref/.clang-format

This commit removes .FORMATDENY file and replaces it to .clang-format's DisableFormat.
---
Draft: https://github.com/Samsung/ONE/pull/14556

[ann-ref] Remove .FORMATDENY file

---

runtime/3rdparty/.clang-format
tests/nnapi/bridge/include/.clang-format
tests/nnapi/src/.clang-format

This commit removes .FORMATDENY file and replaces it to .clang-format's DisableFormat.
---
Draft: https://github.com/Samsung/ONE/pull/14556

[onert] Remove .FORMATDENY file

---

onert-micro/externals/.clang-format

This commit removes .FORMATDENY file and replaces it to .clang-format's DisableFormat.
---
Draft: #14556

[onert-micro] Remove .FORMATDENY file

---

packaging/nnfw.spec

This commit changes plugin install path on ASan build. dlopen() on ASan build cannot uses RPATH setting

[infra/gbs] Workaround dlopen ASan issue

---

infra/nnfw/cmake/options/options_aarch64-tizen.cmake
infra/nnfw/cmake/options/options_armv7hl-tizen.cmake
infra/nnfw/cmake/options/options_armv7l-tizen.cmake

This commit disables XNNPack backend build on Tizen.
missing pr for https://review.tizen.org/gerrit/gitweb?p=platform/core/ml/nnfw.git;a=commit;h=a47a504ac8ce5ea212074087dee9ee90748b7979

Disable XNNPack backend on Tizen

---

packaging/nnfw.spec

This commit fixes gbs test build failure by test directory relocation.

[infra/gbs] Fix gbs test build

---

Makefile.template
infra/scripts/test_coverage.sh
packaging/nnfw.spec

This commit fixes coverage test failure by teset directory relocation.

[onert/infra] Fix coverage test failure

---

Makefile.template

This commit fixes coverage test failure due to invalid path.

[infra/onert] Fix makefile for coverage

---

runtime/onert/api/python/package/experimental/train/session.py

This commit introduces train Session.
- compile : compiling a model with hyper-parameters
- train : training with dataset as many as epoch
- train_step : training a step with one batch sample

[onert/python] Introduce train Session

---

circle-mlir/infra/docker/u2204/Dockerfile

This will introduce initial U2204 Dockerfile for CI build check.

[circle-mlir] Initial U2204 Dockerfile for CI

---

circle-mlir/CMakeLists.txt

This will introduce initial CMakeLists file.

[circle-mlir] Introduce initial CMakeLists

---

circle-mlir/infra/docker/u2204/Dockerfile

This will fix installing `clang-format-16`.
To install this format, the LLVM repository must be set up in advance.
---
for #14627, https://github.com/Samsung/ONE/issues/14607

[circle-mlir] Fix Dockerfile

---

.github/workflows/run-circle-mlir-build.yml

This will introduce initial run-circle-mlir-build Workflow to build check with circle-mlir project.

[github] Introduce initial run-circle-mlir-build

---

circle-mlir/CMakeLists.txt
circle-mlir/infra/cmake/CfgOptionFlags.cmake

This will introduce CMake configure option flags
- ENABLE_TEST to enable/disable test
- ENABLE_COVERAGE to enable/disable test coverage

[circle-mlir] Introduce CMake test option flags

---

circle-mlir/.gitignore

This will introduce circle-mlir project local gitignore
to ignore local build folder and personal Makefile.

[circle-mlir] Local gitignore

---

circle-mlir/CMakeLists.txt
circle-mlir/circle-mlir/CMakeLists.txt
circle-mlir/circle-mlir/tools-test/CMakeLists.txt
circle-mlir/circle-mlir/tools-test/check-gtest/CMakeLists.txt
circle-mlir/circle-mlir/tools-test/check-gtest/CheckGTest.test.cpp
circle-mlir/infra/cmake/GTestHelper.cmake

This will enable gtest with simple test.

[circle-mlir] Enable gtest

---

runtime/onert/core/src/util/ChromeTracingEventWriter.cc
runtime/onert/core/src/util/EventWriter.cc
runtime/onert/core/src/util/EventWriter.h

This commit ensures that `traceEvents` is generated only once and prevents the error of generating multiple `traceEvents` when using multiple nnfw sessions.

[onert] Modify ChromeTracingWriter to generate traceEvents only once

---

.github/workflows/run-circle-mlir-build.yml

This will enable test and install for un-circle-mlir-build Workflow.

[github] Enable test and install for run-circle-mlir-build

---

runtime/onert/core/include/loader/TrainInfoLoader.h
runtime/onert/core/src/exporter/CircleExporter.cc
runtime/onert/core/src/loader/TrainInfoLoader.cc

This commit applies inline variable to the metadata name.

[onert/train] Apply inline variable to the metadata name

---

runtime/onert/core/src/exec/ExecTime.h

This commit applies inline variable to class Exectime.

[onert] Apply inline variable to Exectime

---

runtime/onert/core/src/dumper/dot/OperandNode.cc
runtime/onert/core/src/dumper/dot/OperandNode.h

This commit applies inline variable to class OperandNode.

[onert] Apply inline variable to OperandNode

---

circle-mlir/CMakeLists.txt

This will pass CIRCLE_MLIR_LOCALINST environmet variable to CMake CIRCLE_MLIR_LOCALINST.

[circle-mlir] Pass CIRCLE_MLIR_LOCALINST

---

circle-mlir/CMakeLists.txt
circle-mlir/infra/cmake/TestCoverage.cmake

This will introduce cirmlir_coverage CMake interface for test coverage report generation.

[circle-mlir] Introduce cirmlir_coverage interface

---

.github/workflows/build-docker-onnx-subgr.yml

This will introduce build-docker-onnx-subgr Workflow
to generate Docker image for tools/onnx-subgraph build/test.

[github] Introduce build-docker-onnx-subgr

---

tools/onnx_subgraph/docker/Dockerfile.u2204

This will fix Dockerfile warning not to use white space separator.

[onnx_subgraph] Fix Dockerfile warning

---

infra/cmake/packages/CaffeSource.patch
infra/cmake/packages/CaffeSourceConfig.cmake

This commit patches the sources of Caffe 1.0 upon the download in order to resolve a compilation error coming from the changes of Protobuf's API.
Related issue: https://github.com/Samsung/ONE/issues/14620

[infra] Adjust the Caffe 1.0 code to the new Protobuf API

---

infra/command/format

This commit improves the format checker's latency.

[infra] Improve the format checker's latency

---

.github/workflows/build-circle-intp.yml

This will introduce build-circle-intp Workflow to build and
provide circle-interpreter as Workflow Artifact.

[github] Introduce Workflow build-circle-intp

---

circle-mlir/circle-mlir/lib/dialect/CMakeLists.txt
circle-mlir/circle-mlir/lib/dialect/mlir/TableGen.cmake

This will add circle_mlir_gen_inc target and by adding depencency, include files are actually generated.

[circle-mlir] Enable td generation

---

runtime/onert/backend/train/KernelGenerator.cc
runtime/onert/core/include/ir/train/LossInfo.h

This commit replaces LossParam with std::variant.
This commit applies std::variant to

[onert] Replace LossParam with std::variant

---

tools/onnx_subgraph/CMakeLists.txt
tools/onnx_subgraph/test_model_download.sh

historical PR:
https://github.com/Samsung/ONE/pull/14654
https://github.com/Samsung/ONE/pull/14613
Add test onnx models downloading scripts for future smoking test, downloading will happen in installing path, will not effect git status.

[tools/onnx-subgraph] Add test model downloading scripts

---

circle-mlir/infra/cmake/CfgOptionFlags.cmake

This will introduce ONNX2CIRCLE_TEST_MODELS_SINGLE option
to test one model at a time, not to mix logs for better readability
as test runs in parallel.

[circle-mlir/infra] Introduce ONNX2CIRCLE_TEST_MODELS_SINGLE

---

runtime/onert/api/nnfw/src/CustomKernelRegistry.h
runtime/onert/core/include/ir/Graph.h
runtime/onert/core/include/ir/Model.h
runtime/onert/core/include/util/ConfigSource.h
runtime/onert/core/src/compiler/HEScheduler.h
runtime/onert/core/src/dumper/dot/Node.h
runtime/onert/core/src/exec/JSONExecTime.h
runtime/onert/core/src/ir/OpCode.cc
runtime/onert/core/src/util/ConfigSource.cc
runtime/onert/core/src/util/SNPEEventWriter.cc

This commit adds todo comments about std::string_view. To use std::string_view with unordered associative containers that have std::string keys, heterogeneous lookup support is required. But, Heterogeneous lookup for unordered associative containers is supported since C++20.

[onert] Add todo comments about std::string_view

---

runtime/compute/cker/include/cker/NeonTensorUtils.h
runtime/compute/cker/include/cker/PortableTensorUtils.h
runtime/compute/cker/include/cker/operation/Pad.h
runtime/compute/cker/include/cker/operation/Tile.h
runtime/compute/cker/include/cker/operation/optimized/BinaryArithmeticOps.h

This commit applies structued binding in cker.

[cker] Apply structured binding in cker

---

runtime/compute/ARMComputeEx/arm_compute/core/utils/misc/ShapeCalculatorEx.h
runtime/compute/ARMComputeEx/src/core/CL/kernels/CLEmbeddingLookupKernel.cpp
runtime/compute/ARMComputeEx/src/core/CL/kernels/CLHashtableLookupKernel.cpp
runtime/compute/ARMComputeEx/src/core/CL/kernels/CLInstanceNormalizationLayerKernelEx.cpp
runtime/compute/ARMComputeEx/src/core/CL/kernels/CLOneHotKernel.cpp
runtime/compute/ARMComputeEx/src/core/CL/kernels/CLPadLayerKernelEx.cpp
runtime/compute/ARMComputeEx/src/core/CL/kernels/CLQuantizationSymmetricKernel.cpp
runtime/compute/ARMComputeEx/src/core/CL/kernels/CLScaleFactorSymm8Kernel.cpp
runtime/compute/ARMComputeEx/src/core/NEON/kernels/NEGEMMMatrixAccumulateBiasesKernel.cpp
runtime/compute/ARMComputeEx/src/core/NEON/kernels/NEInstanceNormalizationLayerKernelEx.cpp
runtime/compute/ARMComputeEx/src/core/NEON/kernels/NEQuantizationSymmetricKernel.cpp
runtime/compute/ARMComputeEx/src/core/UtilsEx.cpp
runtime/compute/ARMComputeEx/src/runtime/CL/functions/CLDirectTransposeConvLayer.cpp
runtime/compute/ARMComputeEx/src/runtime/CL/functions/CLGEMMMatrixAccumulateBiasesKernel.cpp
runtime/compute/ARMComputeEx/src/runtime/CL/functions/CLTransposeConvLayer.cpp

This commit applies structured binding in ARMComputeEx.

[onert] Apply structured binding in ARMComputeEx

---

circle-mlir/circle-mlir/lib/dialect/CMakeLists.txt

This will enable dialect lib with test coverage report.

[circle-mlir/dialect] Enable test coverage report

---

circle-mlir/externals/.gitignore
circle-mlir/externals/CMakeLists.txt

This will add externals/llvm-project build.

[circle-mlir/ext] Add llvm-project build

---

tools/onnx_subgraph/CMakeLists.txt
tools/onnx_subgraph/extract_onnx.py
tools/onnx_subgraph/subgraphs_ios.txt

1. subgraphs_ios.txt is node position information for onnx model splitting, it will be generated by future code,  it is used for smoking test now, and will be removed until can be generated auto
2. extract_onnx.py can split the onnx model to sub models

[tools/onnx-subgraph] Add onnx subgraph python code by given nodes

---

circle-mlir/Makefile.sample

This will introduce Makefile.sample as a sample reference Makefile
to use for building and testing circle-mlir.

[circle-mlir] Introduce Makefile.sample

---

circle-mlir/circle-mlir/lib/dialect/mlir/CircleOps.td
circle-mlir/circle-mlir/lib/dialect/src/CircleDialect.cpp
circle-mlir/circle-mlir/lib/dialect/src/ops/CustomOp.h

[circle-mlir/dialect] Add CustomOp

---

circle-mlir/infra/docker/u2204/Dockerfile
circle-mlir/infra/overlay/prepare-venv

This will revise numpy package install with version
to prevent version incompatible error using numpy==2.x.y.

[circle-mlir/infra] Revise numpy package version

---

tools/onnx_subgraph/README.md
tools/onnx_subgraph/extract_onnx.py

1. add exception process for file open and IO
2. add readme.md for previous submitting

[tools/onnx-subgraph] Add readme.md for environment and existing code

---

runtime/onert/backend/trix/Convert.h
runtime/onert/core/include/ir/Model.h
runtime/onert/core/include/ir/train/operation/UntrainableOperation.h
runtime/onert/core/src/compiler/CompilerHelpers.h
runtime/onert/core/src/exec/IPermuteFunction.cc
runtime/onert/core/src/util/ShapeInference.cc

This commit simplify code using the SFINAE technique.

[onert] Simplify code using SFINAE technique

---

circle-mlir/circle-mlir/lib/export/CMakeLists.txt
circle-mlir/circle-mlir/lib/export/include/circle-mlir/export/CircleExport.h
circle-mlir/circle-mlir/lib/export/src/CircleExport.cpp

This will introduce CircleExport to export MLIR graph to circle flatbuffer file.

[circle-mlir/export] Introduce CircleExport

---

circle-mlir/circle-mlir/lib/tools/converter-gen/CMakeLists.txt

This will revise converter-gen CMakeLists with llvm_update_compile_flags() removed
as cir_mlir_tablegen_flags() includes calling it.

[circle-mlir] Revise converter-gen CMakeLists

---

circle-mlir/externals/CMakeLists.txt

This will fix externals/CMakeLists with missing folder variables.

[circle-mlir/ext] Fix externals CMakeLists

---

circle-mlir/circle-mlir/tools-test/CMakeLists.txt
circle-mlir/circle-mlir/tools-test/gen-onnx/CMakeLists.txt
circle-mlir/circle-mlir/tools-test/gen-onnx/run_gen_onnx.py
circle-mlir/circle-mlir/tools-test/gen-onnx/run_gen_onnx.sh
circle-mlir/models/unit/Add_F32_R4/__init__.py
circle-mlir/models/unit/Add_F32_R4_C1/__init__.py

This will introduce gen-onnx test tool to generate onnx models for testing
from pytorch source code with unit test Add models.

[circle-mlir/tools-test] Introduce gen-onnx with Add models

---

circle-mlir/circle-mlir/lib/import/CMakeLists.txt
circle-mlir/circle-mlir/lib/import/include/circle-mlir/import/CircleImport.h
circle-mlir/circle-mlir/lib/import/src/CircleImport.cpp

This will introduce CircleImport to import circle mode files. Code itself is from Tensorflow flatbuffer_import.cc with little modification and removed that are not necessary at this moment.

[circle-mlir/import] Introduce CircleImport

---

circle-mlir/circle-mlir/lib/dialect/src/CircleDialect.cpp
circle-mlir/circle-mlir/lib/dialect/src/ops/ConstOp.h
circle-mlir/circle-mlir/lib/dialect/src/ops/NoValueOp.h

This will add dialect implementations for ConstOp and NoValueOp.

[circle-mlir/dialect] Add implementations for ConstOp, NoValueOp

---

circle-mlir/infra/docker/u2204/Dockerfile
circle-mlir/infra/overlay/prepare-venv

This PR adjusts the numpy version to ensure compatibility with Ubuntu 20.04 and 22.04.
The numpy version `1.26.4` was not compatible with python-3.8, which is the default version on Ubuntu 20.04.
---
Related to #14743, #14607

[circle-mlir/infra] Adjust the numpy version

---

tools/onnx_subgraph/CMakeLists.txt
tools/onnx_subgraph/single_vs_multiple_onnx.py

add single onnx inference code for verification, sub models inference code will be submitted in next PR

[tools/onnx-subgraph] add onnx inference verification code

---

runtime/compute/cker/include/cker/Shape.h
runtime/compute/ruy/include/ruy/Shape.h

This commit applies fold expressions.

[compute] Apply fold expressions

---

circle-mlir/circle-mlir/tools/onnx2circle/CMakeLists.txt
circle-mlir/circle-mlir/tools/onnx2circle/src/cmdOptions.h
circle-mlir/circle-mlir/tools/onnx2circle/src/driverDebug.cpp
circle-mlir/circle-mlir/tools/onnx2circle/src/driverRelease.cpp

This will enable options to onnx2circle tool.
- debug uses llvm:cl:opt
- release uses arser, not expose MLIR/ONNX-MLIR options

[circle-mlir/tools] Enable options to onnx2circle tool

---

runtime/onert/api/nnfw/src/nnfw_session.cc
runtime/onert/backend/train/MemoryPlannerFactory.cc
runtime/onert/backend/train/MemoryPlannerFactory.h
runtime/onert/core/include/compiler/BackendManager.h
runtime/onert/core/src/compiler/BackendManager.cc
runtime/onert/core/src/compiler/ManualScheduler.cc
runtime/onert/core/src/compiler/ManualScheduler.h
runtime/onert/core/src/exec/JSONExecTime.cc

This commit applies std::string_view in places where there is a performance benefit.

[onert] Apply std::string_view

---

tools/onnx_subgraph/single_vs_multiple_onnx.py

1. fixed input shape as default value
2. user can set the input shape dynamically with guide

[tools/onnx-subgraph] support arbitrary input shape for onnx

---

circle-mlir/circle-mlir/lib/pass/CMakeLists.txt
circle-mlir/circle-mlir/lib/pass/src/CirclePass.cpp
circle-mlir/circle-mlir/lib/pass/src/DumpCircleOpsPass.cpp
circle-mlir/circle-mlir/lib/pass/src/DumpCircleOpsPass.h

This will introduce dumpCircleOps method with DumpCircleOpsPass class
to dump Circle Ops for test and validation.

[circle-mlir/pass] Introduce dumpCircleOps

---

circle-mlir/circle-mlir/tools/onnx2circle/CMakeLists.txt
circle-mlir/circle-mlir/tools/onnx2circle/src/onnx2circle.test.cpp

This will introduce two negative unit tests for loadONNX method.

[circle-mlir/tools] Introduce unit tests for loadONNX

---

circle-mlir/circle-mlir/tools/onnx2circle/src/driverDebug.cpp

This commits changes SingleRun's member variables to inline variables.

[circle-mlir/tools] Use inline variables in SingleRun

---

runtime/compute/ARMComputeEx/arm_compute/core/CL/CLKernelLibraryEx.h
runtime/compute/ARMComputeEx/src/core/CL/CLKernelLibrary.cpp
runtime/compute/cker/include/cker/operation/Einsum.h

This commit applies std::string_view to CLKernelLibraryEx and Einsum.

[compute] Apply std::string_view

---

circle-mlir/circle-mlir/tools/onnx2circle/src/onnx2circle.cpp

This will implement save_ops option in onnx2circle tool to save Ops
to a file of input model for test and validation.

[circle-mlir/tools] Implement save_ops option

---

.github/workflows/run-circle-mlir-build.yml

This will revise run-circle-mlir-build to install one-compiler so that we have circle-interpreter.

[github] Install one-compiler for run-circle-mlir-build

---

circle-mlir/circle-mlir/lib/pass/CMakeLists.txt
circle-mlir/circle-mlir/lib/pass/src/CirclePass.cpp
circle-mlir/circle-mlir/lib/pass/src/RuntimeVerifyPass.cpp
circle-mlir/circle-mlir/lib/pass/src/RuntimeVerifyPass.h

This will introduce and execute RuntimeVerifyPass for onnx to circle conversion.
RuntimeVerifyPass will check runtime constraints for each ops, if exist.

[circle-mlir/pass] Execute RuntimeVerifyPass

---

tools/onnx_subgraph/single_vs_multiple_onnx.py

add code for multi sub graphs inference

[tools/onnx-subgraph] add multi subgraphs inference code

---

circle-mlir/circle-mlir/tools/onnx2circle/CMakeLists.txt
circle-mlir/circle-mlir/tools/onnx2circle/TestModels.cmake
circle-mlir/circle-mlir/tools/onnx2circle/src/onnx2circle.cpp
circle-mlir/circle-mlir/tools/onnx2circle/test.lst

This will enable onnx2circle tool conversion from onnx to circle and export to circle model file.
Test is also added with AddOp.

[circle-mlir/tools] Enable onnx2circle conversion and export

---

tools/model_explorer_circle/noxfile.py

The 'needs_version' object is belong to Nox module not NoxOptions.

[tools/mec] Fix noxfile.py correctly

---

circle-mlir/circle-mlir/tools-test/CMakeLists.txt
circle-mlir/circle-mlir/tools-test/onnx2circle-models/CMakeLists.txt
circle-mlir/circle-mlir/tools-test/onnx2circle-models/test.lst

This will introduce initial onnx2circle-models test that will
execute onnx2circle tool with test models with AddOp.

[circle-mlir/tools-test] Introduce onnx2circle-models

---

runtime/onert/core/src/util/EventWriter.cc
runtime/onert/core/src/util/EventWriter.h

This commit applies inline variable to class EventWriter.

[onert] Apply inline variable to EventWriter

---

circle-mlir/circle-mlir/tools-test/onnx2circle-value-test/CMakeLists.txt
circle-mlir/circle-mlir/tools-test/onnx2circle-value-test/exec_circle.py
circle-mlir/circle-mlir/tools-test/onnx2circle-value-test/make_circle_input.py

This will add exec_circle and make_circle_input script for onnx2circle-value-test.
These file are to (1) create circle input file(s) and
(2) execute circle model with the input files(s) with circle-interpreter.

[circle-mlir/tools-test] Add exec_circle and make_circle_input

---

tools/onnx_subgraph/single_vs_multiple_onnx.py

mse comparing of src model and multi sub models

[tools/onnx-subgraph] mse comparing of src model and multi sub models

---

circle-mlir/circle-mlir/tools-test/circle-impexp-test/CMakeLists.txt
circle-mlir/circle-mlir/tools-test/circle-impexp-test/run_import_test.sh

This will enable import test, for models that cannot do value test, in circle-impexp-test.

[cicle-mlir/tools-test] Enable import test

---

circle-mlir/circle-mlir/tools-test/circle-impexp-test/CMakeLists.txt
circle-mlir/circle-mlir/tools-test/circle-impexp-test/exec_circle.py

This will introduce exec_circle script in circle-impexp-test
to execute circle model with circle-interpreter.

[circle-mlir/tools-test] Introduce exec_circle

---

circle-mlir/circle-mlir/tools-test/circle-impexp-test/CMakeLists.txt
circle-mlir/circle-mlir/tools-test/circle-impexp-test/make_circle_input.py
circle-mlir/circle-mlir/tools-test/circle-impexp-test/util_h5_file.py

This will introduce make_circle_input to generate circle input
for exec_circle script from exec_onnx execution result and
necessary util_h5_file script.

[circle-mlir/tools-test] Introduce make_circle_input and util_h5_file

---

circle-mlir/circle-mlir/tools-test/circle-impexp-test/test.lst

This will enable value tests for AddOp in import/export tests.

[circle-mlir/tools-test] Enable tests for AddOp in import/export

---

circle-mlir/circle-mlir/tools/CMakeLists.txt
circle-mlir/circle-mlir/tools/one-import-onnx-ext/CMakeLists.txt
circle-mlir/circle-mlir/tools/one-import-onnx-ext/README.md
circle-mlir/circle-mlir/tools/one-import-onnx-ext/one-import-onnx-ext

This will introduce one-import-onnx-ext as extension
for one-import-onnx of compiler/one-cmds to invoke onnx2circle tool
for conversion of onnx to circle.

[circle-mlir/tools] Introduce one-import-onnx-ext

---

circle-mlir/models/unit/Transpose_F32_R4/__init__.py

This will introduce unit test model for Transpose conversion.

[circle-mlir] Introduce unit test model for Transpose

---

circle-mlir/circle-mlir/lib/dialect/mlir/CircleOps.td
circle-mlir/circle-mlir/lib/dialect/src/CircleDialect.cpp
circle-mlir/circle-mlir/lib/dialect/src/ShapeInference.cpp
circle-mlir/circle-mlir/lib/dialect/src/ops/TransposeOp.h

This will enable TransposeOp IR.

[circle-mlir/dialect] Enable TransposeOp IR

---

circle-mlir/circle-mlir/tools-test/onnx2circle-models/test.lst
circle-mlir/circle-mlir/tools-test/onnx2circle-value-test/test.lst
circle-mlir/circle-mlir/tools/onnx2circle/test.lst

This will enable shapeinf, conversion and value tests for TransposeOp.

[circle-mlir] Enable tests for TransposeOp

---

circle-mlir/circle-mlir/lib/pass/src/RewriteCirclePass.cpp
circle-mlir/circle-mlir/lib/pass/src/opt/ConvertReshapeShape32.h

This will introduce ConvertReshapeShape32 pass
to convert INT64 to INT32 of ReshapeOp shape to make compatible for circle2circle.

[circle-mlir/pass] Introduce ConvertReshapeShape32

---

circle-mlir/models/unit/Conv2d_F32_R4/__init__.py
circle-mlir/models/unit/Conv2d_F32_R4_dil/__init__.py
circle-mlir/models/unit/Conv2d_F32_R4_dil_g2/__init__.py
circle-mlir/models/unit/Conv2d_F32_R4_g2/__init__.py
circle-mlir/models/unit/Conv2d_F32_R4_g5/__init__.py
circle-mlir/models/unit/Conv2d_F32_R4_k33/__init__.py
circle-mlir/models/unit/Conv2d_F32_R4_nobias/__init__.py
circle-mlir/models/unit/Conv2d_F32_R4_p10/__init__.py
circle-mlir/models/unit/Conv2d_F32_R4_p11/__init__.py
circle-mlir/models/unit/Conv2d_F32_R4_s2/__init__.py

This will introduce unit tests for Conv2dOp.

[circle-mlir/models] Introduce Conv2d

---

tools/onnx_subgraph/README.md

guide for mse comparing of src model and multi sub models inference result

[tools/onnx-subgraph] add guide in README.md for subgraphs verification

---

circle-mlir/circle-mlir/tools/onnx2circle/TestModels.cmake

This will introduce macros for testing dynamic shape inference of ops.

[circle-mlir/tools] Enable test for dynamic shape inf

---

compiler/luci-interpreter/src/kernels/Gather.cpp
compiler/luci-interpreter/src/kernels/Gather.h
compiler/luci-interpreter/src/kernels/Gather.test.cpp

The commit extend Gather kernel implementation to support S32 (int32_t) data type.

[luci-interpreter] Support S32 for Gather

---

circle-mlir/circle-mlir/tools-test/onnx2circle-models/test.lst
circle-mlir/circle-mlir/tools-test/onnx2circle-value-test/test.lst

This will enable conversion and value test of PadOp.

[circle-mlir/tools-test] Enable tests for PadOp

---

circle-mlir/circle-mlir/tools/onnx2circle/test.lst

This will enable unit test of shape inference for Conv2DOp and PadOp.

[circle-mlir/tools] Unit test of shape inference for Conv2D, Pad

---

compiler/luci/import/include/luci/ImporterEx.h
compiler/luci/import/src/ImporterEx.cpp
compiler/luci/import/src/ImporterEx.test.cpp

This commit adds the ability to add external error handlers to the ImporterEx.
By default the class logs all messages from potential errors occurring during the call to importVerifyModule(). Users can inject their own error handler in a form of a callable satisfying the following signature:
void(const std::exception&)
The error handler should be injected using a new ImporterEx constructor.
Draft: https://github.com/Samsung/ONE/pull/14792

[luci/import] Add an error handler to ImporterEx

---

circle-mlir/circle-mlir/tools-test/onnx2circle-value-test/comp_onnx_circle.py

This commit refactores the code to use np.max instead of np.ndarray.max, simplifying the syntax while retaining equivalent functionality.

[circle-mlir] Simplify max value calculation by replacing it with np.max

---

circle-mlir/circle-mlir/tools-test/onnx2circle-value-test/util_validation.py

This commit adds a check to set PEIR to 0 when INTERVAL is 0, ensuring that division by zero is avoided.

[circle-mlir] Prevent division by zero in PEIR calculation

---

circle-mlir/Makefile.sample
circle-mlir/README.md

This will revise README and Makefile.sample file about test coverage report.

[circle-mlir] Revise README and Makefile about coverage

---

compiler/luci/service/include/luci/Service/CircleShapeInference.h
compiler/luci/service/src/Nodes/CircleOutput.cpp

This commit enables shape inference for CircleOutput node.

[luci/service] Enable CircleOutput shape inference

---

circle-mlir/README.md

This will revise README with how to dump logs of onnx2circle tool.

[circle-mlir] Dump logs in README

---

compiler/luci-interpreter/src/kernels/Gather.cpp
compiler/luci-interpreter/src/kernels/Gather.test.cpp

This supports scalar index in Gather Op.
---
Related to: https://github.com/Samsung/ONE/issues/14804

[luci-interpreter] Support scalar index in Gather

---

compiler/luci/service/src/Nodes/CircleReshape.cpp
compiler/luci/service/src/Nodes/CircleReshape.test.cpp

… inference
This commit adds checking of number of remaining elements in order to confirm if it matches expected output shape.

[luci] Add additional check of unknown dimension for Reshape

---

tools/onnx_subgraph/CMakeLists.txt
tools/onnx_subgraph/src/main.cpp

initial main.cpp for onnx model parsing

[tools/onnx-subgraph] add initial main.cpp

---

compiler/luci/service/src/Nodes/CircleReshape.test.cpp

This commit adds additional unit test for negative scenario where "0" indicates not existing input dimension.

[luci] Add additional negative unit test for Reshape

---

circle-mlir/circle-mlir/lib/pass/src/ConvertONNXToCirclePass.cpp
circle-mlir/circle-mlir/lib/pass/src/ops/ReduceMaxOp.h

This will enable conversion of ReduceMax Op
- ONNXReduceMaxOp is left as NYI for future work

[circle-mlir/pass] Enable ReduceMax conversion

---

.github/workflows/run-onecc-build.yml

This commit updates onecc build test workflow to use self-hosted runner.
---
Related issue: #14915

[infra] Use self-hosted runner for onecc build

---

.github/workflows/run-onert-cross-build.yml
.github/workflows/run-onert-native-build.yml

This commit updates onert build test workflow to use self-hosted runner.
---
Related issue: #14916 
Draft: #14756

[infra] Use self-hosted runner for onert build

---

compiler/visq-unittest/CMakeLists.txt

This commit adds dependency to add_custom_command. 
It confirms ordering of commands, then resolves random build fail.
---
Related issue: #14925

[visq-unittest] Add dependency on add_custom_command

---

compiler/common-artifacts/exclude.lst

This commit excludes Inf_Squeeze_000 because TestDataGenerator does not support unknown dimensions.
Draft: https://github.com/Samsung/ONE/pull/14882

[common-artifacts] Exclude Inf_Squeeze_000 recipe

---

circle-mlir/models/mlir/Cast_F32_F32.circle.mlir
circle-mlir/models/mlir/Cast_I64_F32_C1.circle.mlir
circle-mlir/models/mlir/Cast_I64_F32_ds.circle.mlir
circle-mlir/models/mlir/Cast_I8_I16_C1.circle.mlir

This adds MLIR test models for the Cast operation.

[circle-mlir/models] Add MLIR models for Cast Op

---

circle-mlir/circle-mlir/lib/dialect/mlir/CircleOps.td
circle-mlir/circle-mlir/lib/dialect/src/ShapeInference.cpp

This adds the shape inference interface to the Cast operation on dialect.

[circle-mlir/dialect] Add the shape inference to Cast Op

---

.github/workflows/build-dev-docker.yml
.github/workflows/build-pub-dev-docker.yml

This commit splits the dev docker image build workflow into two separate workflows: PR test and publish image. Publishing docker image workflow is triggered by workflow_dispatch, not push.
--- 
Draft: #14758

[infra] Split dev docker image build workflow

---

circle-mlir/circle-mlir/lib/pass/src/ConvertONNXToCirclePass.cpp
circle-mlir/circle-mlir/lib/pass/src/ops/CastOp.h

This enables conversion of the Cast operation.

[circle-mlir/pass] Add the pass for Cast Op

---

circle-mlir/circle-mlir/tools/onnx2circle/test.lst

This enables tests to cover and infer the shape of the Cast operation.

[circle-mlir/tools] Test coverage and shape inference for Cast Op

---

compiler/luci/service/src/CircleShapeInferenceRule.cpp
compiler/luci/service/src/Nodes/CircleSqueeze.test.cpp

This commit skip verification of squeezed dimension if such dimension is dynamic.
Draft: https://github.com/Samsung/ONE/pull/14882

[luci] Handle dynamic dimensions in Squeeze shape inference

---

infra/docker/android-sdk/Dockerfile

This commit updates the Dockerfile including buildtools for android target runtime build
- Change android tools install path to /opt/android-tools: root user (github action) cannot read /home/ubuntu
- Remove packages for format checking: they are not used in android build
---
Draft: #14758

[infra/docker] Fix android build docker image

---

circle-mlir/models/mlir/SelectV2_F32_R2.circle.mlir
circle-mlir/models/mlir/SelectV2_I32_R2.circle.mlir
circle-mlir/models/mlir/SelectV2_I64_R2.circle.mlir

This adds MLIR test models for the SelectV2 operation.

[circle-mlir/models] Add MLIR test models for SelectV2 Op

---

circle-mlir/models/mlir/StridedSlice_F32_R2_ds.circle.mlir
circle-mlir/models/mlir/StridedSlice_F32_R4_us.circle.mlir
circle-mlir/models/mlir/StridedSlice_I64_R1_C4.circle.mlir
circle-mlir/models/mlir/StridedSlice_I64_R1_C4_rev.circle.mlir
circle-mlir/models/mlir/StridedSlice_I64_R2_C4_0.circle.mlir
circle-mlir/models/mlir/StridedSlice_I64_R2_C4_1.circle.mlir
circle-mlir/models/mlir/StridedSlice_I64_R2_C4_2.circle.mlir
circle-mlir/models/mlir/StridedSlice_I64_R2_C4_3.circle.mlir
circle-mlir/models/mlir/StridedSlice_I64_R2_C4_4.circle.mlir
circle-mlir/models/mlir/StridedSlice_I64_R4_C4.circle.mlir

This adds MLIR test models for the StridedSlice operation.

[circle-mlir/models] Add MLIR test models for StridedSlice Op

---

circle-mlir/models/mlir/Slice_F32_R2_ds.circle.mlir
circle-mlir/models/mlir/Slice_F32_R3_C1_0.circle.mlir
circle-mlir/models/mlir/Slice_F32_R3_C1_1.circle.mlir
circle-mlir/models/mlir/Slice_F32_R3_C1_2.circle.mlir

This adds MLIR test models for the Slice operation.

[circle-mlir/models] Add MLIR test models for Slice Op

---

circle-mlir/models/unit/Slice_F32_R2_4/__init__.py
circle-mlir/models/unit/Slice_F32_R3_4/__init__.py
circle-mlir/models/unit/Slice_F32_R3_C2_1/__init__.py
circle-mlir/models/unit/Slice_F32_R3_C2_2/__init__.py
circle-mlir/models/unit/Slice_F32_R3_unk_1/__init__.py
circle-mlir/models/unit/Slice_F32_R3_unk_2/__init__.py
circle-mlir/models/unit/Slice_F32_R4_1/__init__.py
circle-mlir/models/unit/Slice_F32_R4_2/__init__.py
circle-mlir/models/unit/Slice_F32_R4_3/__init__.py
circle-mlir/models/unit/Slice_F32_R4_4/__init__.py
circle-mlir/models/unit/Slice_F32_R4_5/__init__.py
circle-mlir/models/unit/Slice_F32_R4_6/__init__.py
circle-mlir/models/unit/Slice_F32_R4_7/__init__.py

This adds the unit test models for Slice operation.

[circle-mlir/models] Add unit test models for Slice Op

---

circle-mlir/circle-mlir/lib/dialect/mlir/CircleOps.td
circle-mlir/circle-mlir/lib/dialect/src/CircleDialect.cpp
circle-mlir/circle-mlir/lib/dialect/src/ops/SelectV2Op.h

This introduces the IR for SelectV2 operation.

[circle-mlir/dialect] Introduce IR for SelectV2 Op

---

circle-mlir/circle-mlir/tools/onnx2circle/test.lst

This enables tests to cover the SelectV2 operation.

[circle-mlir/tools] Test coverage for SelectV2 Op

---

infra/docker/focal/Dockerfile

This commit removes the platform dependency from Dockerfile's workaround for missing libtsan_preinit.o installation. This will help to support multiple platform build in the future.
---
Draft: #14758

[infra/docker] Remove platform dependency from Dockerfile

---

runtime/onert/core/src/ir/OperationValidator.cc
runtime/onert/core/src/ir/OperationValidator.h
runtime/tests/nnfw_api/src/GenModelTests/one_op_tests/Transpose.test.cc

It adds typecheck (input type = output type) for Transpose. Also, it adds 1 negative testcase.
-----
```
$ Product/x86_64-linux.debug/out/unittest/nnfw_api_gtest
. . .
[ RUN      ] GenModelTest.neg_OneOp_Transpose_DifferentType
Error during model loading : OperationValidator failed at line 559
[       OK ] GenModelTest.neg_OneOp_Transpose_DifferentType (0 ms)
```

[onert] Add typecheck for Transpose

---

circle-mlir/circle-mlir/tools/onnx2circle/test.lst

This enables tests to cover the Slice operation.

[circle-mlir/tools] Test coverage for Slice Op

---

compiler/one-cmds/one-prepare-venv
compiler/one-cmds/one-prepare-venv.u1804

This fixes the version of the `fsspec` package in the venv environment, to resolve a version mismatch issue with Python 3.8.

[compiler/one-cmds] Fix fsspec package version in venv

---

.github/workflows/build-dev-docker.yml

This commit adds a path filtering job to check updated dockerfile and run build job only if it is changed.

[infra] Add path filter for docker build test

---

.github/workflows/build-dev-docker.yml
infra/docker/focal-cross/Dockerfile
infra/docker/jammy-cross/Dockerfile
infra/docker/noble-cross/Dockerfile

This commit introduces Dockerfiles to support cross-compilation toolchain environment to split with native build environment Dockerfile.
---
Draft: https://github.com/Samsung/ONE/pull/14758
Related issue: #14892

[infra/docker] Introduce docker image for cross build

---

tools/onnx_subgraph/include/graph.h

add onnx process function definition, implementation will be added in the cpp file in next PR

[tools/onnx-subgraph] add onnx process APIs definition

---

.github/workflows/run-onert-android-build.yml

This commit updates android build workflow to use self-hosted runner and android-sdk image. 
It will resolve build fail by too high cmake version on github-hosted runner.

[infra] Use self-hosted runner for android build

---

circle-mlir/circle-mlir/lib/pass/src/RewriteCirclePass.cpp
circle-mlir/circle-mlir/lib/pass/src/opt/ConvertMirrorPadPad32.h

This will rewrite pad of MirrorPad type to I32 for luci-interpreter compatibility.

[circle-mlir/pass] Rewrite MirrorPad

---

runtime/compute/cker/include/cker/operation/BatchMatMul.h
runtime/compute/cker/include/cker/operation/Einsum.h
runtime/onert/backend/cpu/ops/BatchMatMulLayer.cc
runtime/onert/core/src/ir/OperationValidator.cc
runtime/tests/nnfw_api/src/GenModelTests/one_op_tests/BatchMatMul.test.cc

This commit adds support for constant input BatchMatMul. 
It includes BatchMatMul constant input tests.
---
Draft: https://github.com/Samsung/ONE/pull/14905
Related issue: #14951

[onert] Support constant input BatchMatMul

---

circle-mlir/circle-mlir/lib/pass/src/ConvertONNXToCirclePass.cpp

This will enable ConvExpand to convert Expand Op, that was missed in previous change.

[circle-mlir/pass] Enable ConvExpand

---

tools/onnx_subgraph/src/lib/graph.cpp

add part of onnx process functions implementation, more implementations will be added in next PR

[tools/onnx-subgraph] add onnx process functions implementation

---

compiler/luci/pass/include/luci/CircleOptimizer.h
compiler/luci/pass/include/luci/CircleQuantizer.h
compiler/luci/pass/include/luci/DynamicBatchToSingleBatch.h
compiler/luci/pass/include/luci/ModulePass.h

This will revise header guards of exposed headers.

[luci/pass] Revise header guards

---

circle-mlir/circle-mlir/lib/dialect/mlir/CircleOps.td
circle-mlir/circle-mlir/lib/dialect/src/CircleDialect.cpp
circle-mlir/circle-mlir/lib/dialect/src/ops/UnsqueezeOnnxOp.h

This will add UnsqueezeOnnx IR used for temporary for unknown types,
and canonicalization method to convert to Reshape Op.

[circle-mlir/dialect] Add UnsqueezeOnnx

---

circle-mlir/circle-mlir/lib/pass/src/ConvertONNXToCirclePass.cpp
circle-mlir/circle-mlir/lib/pass/src/ops/UnsqueezeOp.h

This will enable to convert Unsqueeze Op.

[cicle-mlir/pass] Convert Unsqueeze Op

---

runtime/compute/cker/include/cker/Shape.h
runtime/compute/cker/include/cker/Types.h
runtime/compute/cker/include/cker/operation/Transpose.h
runtime/tests/nnfw_api/src/GenModelTests/one_op_tests/Transpose.test.cc

It supports 6D input data and perms.
Related: #14928 
```
[ RUN      ] GenModelTest.OneOp_Transpose_6D
[       OK ] GenModelTest.OneOp_Transpose_6D (0 ms)
```

[onert] Transpose supports up to 6D Tensor

---

circle-mlir/circle-mlir/lib/dialect/mlir/CircleOps.td
circle-mlir/circle-mlir/lib/dialect/src/CircleDialect.cpp
circle-mlir/circle-mlir/lib/dialect/src/ShapeInference.cpp
circle-mlir/circle-mlir/lib/dialect/src/ops/SinOp.h

This will add Pow and Sin IRs and necessary methods.

[circle-mlir/dialect] Add Pow,Sin IRs

---

tools/onnx_subgraph/include/device.h
tools/onnx_subgraph/src/lib/device.cpp
tools/onnx_subgraph/src/main.cpp

add config file parser for target device with json

[tools/onnx-subgraph] add config file parser for target device

---

circle-mlir/circle-mlir/tools-test/circle-impexp-test/test.lst
circle-mlir/circle-mlir/tools-test/onnx2circle-models/test.lst
circle-mlir/circle-mlir/tools-test/onnx2circle-value-test/test.lst

This will enable conversion, value and import/export test of onnx.Upsample.
torch.nn.Upsample is exported as onnx.Upsample for op version 9 or lower.
This test is added to check old Upsample is converted correctly.

[circle-mlir/tools-test] Enable Upsample

---

runtime/compute/cker/include/cker/Shape.h
runtime/compute/cker/include/cker/operation/Einsum.h

This commit improves type-safety and memory management by leveraging modern C++17 features.
- Replace the old union-based storage (_dims and _dims_pointer) with a std::variant that holds either a std::array (for shapes with ≤ 6 dimensions) or a std::vector (for larger shapes)
- Update constructors to initialize and resize dims_ accordingly, ensuring that small shapes use the fixed-size array and larger ones use dynamic allocation
- Implement a custom copy constructor to perform a deep copy based on the current storage type and default the move constructor
- Update various member functions (Dims, SetDim, DimsData, Resize, ReplaceWith, BuildFrom, etc.) to use the new std::variant-based storage
- Minor include reordering and addition of necessary headers (e.g., <array>, <iterator>, …

[cker] Fix `array-bounds` build error: Refactor Shape.h to use C++17 std::variant

---

tools/onnx_subgraph/src/lib/device.cpp

add functions for json config process

[tools/onnx-subgraph] add functions for json config process

---

runtime/compute/cker/include/cker/Shape.h

This commit explicitly initialize dims_ in Shape constructors to avoid uninitialized warnings.
- Set dims_ using std::array or std::vector in the (int, int32_t), (int, const int32_t*), and initializer-list constructors to ensure proper initialization before calling Resize().
- Added a check in Resize() using dims_.valueless_by_exception() to handle any uninitialized state.

[compute] Explicitly initialize dims_ in constructors to avoid uninitialized warnings

---

circle-mlir/circle-mlir/lib/dialect/src/CircleDialect.cpp
circle-mlir/circle-mlir/lib/dialect/src/ConstFold.inc.cpp
circle-mlir/circle-mlir/lib/dialect/src/NameUtils.cpp
circle-mlir/circle-mlir/lib/dialect/src/ops/CastOp.h
circle-mlir/circle-mlir/lib/dialect/src/ops/ConcatenationOp.h
circle-mlir/circle-mlir/lib/dialect/src/ops/ConstOp.h
circle-mlir/circle-mlir/lib/dialect/src/ops/FullyConnectedOp.h
circle-mlir/circle-mlir/lib/dialect/src/ops/NoValueOp.h
circle-mlir/circle-mlir/lib/export/src/CircleExport.cpp
circle-mlir/circle-mlir/lib/export/src/OpOrArgNameMapper.cpp
circle-mlir/circle-mlir/lib/import/src/CircleImport.cpp
circle-mlir/circle-mlir/lib/pass/src/opt/ConvertDivErfToMulErf.h
circle-mlir/circle-mlir/lib/pass/src/opt/ConvertMirrorPadPad32.h
circle-mlir/circle-mlir/lib/pass/src/opt/ConvertReshapeShape32.h
circle-mlir/circle-mlir/lib/pass/src/opt/ConvertResizeNearestSize32.h
circle-mlir/circle-mlir/lib/pass/src/opt/ConvertSqrtDivToRsqrt.h
circle-mlir/circle-mlir/lib/pass/src/opt/FuseFullyConnectedAdd.h
circle-mlir/circle-mlir/lib/utils/src/ConvertType.cpp
circle-mlir/circle-mlir/lib/utils/src/FlatbufferOperator.cpp

This will revise usage of type casts and isa method to prepare ONNX-MLIR upgrades.

[circle-mlir] Revise cast and isa

---

runtime/compute/cker/include/cker/Shape.h
runtime/compute/cker/src/DeathTestMacro.h
runtime/compute/cker/src/Shape.test.cc

This commit refactors dims storage initialization of Shape.

[compute/cker] Reduce duplicated code and Fix wrong shape size.

---

circle-mlir/externals/onnx_mlir_0_5_0_0.diff

This will introduce diff patch for onnx-mlir/0.5.0.0 that will patch ONNX-MLIR with
- enable I16 quantize/dequantize
- disable test build
- disable decompose ConvTranspose
- disable InstanceNorm to LayerNorm
these are used to build Dockerimage for compatibility with circle2circle.

[circle-mlir/externals] Introduce onnx_mlir_0_5_0_0.diff

---

circle-mlir/circle-mlir/lib/dialect/src/ops/Conv2DOp.h
circle-mlir/circle-mlir/lib/dialect/src/ops/ReshapeOp.h

This will revise Conv2D, Reshape to construct Adaptor with OpaqueProperties.

[circle-mlir/dialect] Adaptor with OpaqueProperties

---

runtime/compute/cker/include/cker/Shape.h

This commit allows dims_data to be nullptr when dimensions_count is 0.

[compute/cker] Fix einsum test error

---

circle-mlir/infra/docker/u2204/Dockerfile

This will revise u2204/Dockerfile with
- download onnx-mlir patch from github
- update ONNX-MLIR and llvm-project hash
- update related changes
- remove not used anymore clang-format

[circle-mlir/infra] Revise u2204/Dockerfile

---

circle-mlir/infra/docker/u2204/Dockerfile

This will revise U22.04 Dockerfile
- use numpy==1.24.3 for compatibility
- use torch+cpu not to install cuda
- update onnx-mlir build options
- relocate llvm-project cleanup

[circle-mlir] Revise U22.04 Dockerfile

---

runtime/onert/core/src/compiler/ShapeValidator.cc
runtime/onert/core/src/compiler/ShapeValidator.h
runtime/onert/core/src/ir/OperationValidator.cc
runtime/onert/core/src/ir/OperationValidator.h
runtime/onert/core/src/loader/BaseLoader.h
runtime/tests/nnfw_api/lib/CircleGen.cc
runtime/tests/nnfw_api/lib/CircleGen.h
runtime/tests/nnfw_api/src/GenModelTests/one_op_tests/BroadcastTo.test.cc

- BROADCAST_TO operation is already supported in runtime, but it was under CUSTOM operation. so it's fixed to load BROADCAST_TO directly.
- Added test cases for BROADCAST_TO operation.

[onert] Support to load BROADCAST_TO operation

---

runtime/onert/core/src/ir/OperationValidator.cc
runtime/tests/nnfw_api/src/GenModelTests/one_op_tests/BroadcastTo.test.cc

It ensures shape's type is either int32 or int64.
It also adds a negative case.
```
$ Product/x86_64-linux.debug/out/unittest/nnfw_api_gtest
...
[ RUN      ] GenModelTest.neg_OneOp_BroadcastTo_InvalidShapeType
Error during model loading : OperationValidator failed at line 159
[       OK ] GenModelTest.neg_OneOp_BroadcastTo_InvalidShapeType (0 ms)
```
Related: https://github.com/Samsung/ONE/pull/15164#discussion_r2047906033

[onert] Check shape type of BroadcastTo

---

runtime/onert/core/src/compiler/ShapeValidator.cc

It updates shape validation code for BroadcastTo.
```
$ Product/x86_64-linux.debug/out/unittest/nnfw_api_gtest
...
[ RUN      ] GenModelTest.OneOp_BroadcastTo_1D_to_2D
[       OK ] GenModelTest.OneOp_BroadcastTo_1D_to_2D (0 ms)
[ RUN      ] GenModelTest.OneOp_BroadcastTo_2D_to_3D
[       OK ] GenModelTest.OneOp_BroadcastTo_2D_to_3D (0 ms)
[ RUN      ] GenModelTest.OneOp_BroadcastTo_3D_to_3D
[       OK ] GenModelTest.OneOp_BroadcastTo_3D_to_3D (0 ms)
[ RUN      ] GenModelTest.neg_OneOp_BroadcastTo_InputOutputDifferentType
Error during model loading : OperationValidator failed at line 157
[       OK ] GenModelTest.neg_OneOp_BroadcastTo_InputOutputDifferentType (0 ms)
[ RUN      ] …
```

[onert] Revisit BroadcastTo shape validation

---

runtime/onert/api/python/package/experimental/train/losses/cce.py
runtime/onert/api/python/package/experimental/train/losses/loss.py
runtime/onert/api/python/package/experimental/train/losses/mse.py
runtime/onert/api/python/package/experimental/train/losses/registry.py
runtime/onert/api/python/package/experimental/train/metrics/categorical_accuracy.py
runtime/onert/api/python/package/experimental/train/metrics/metric.py
runtime/onert/api/python/package/experimental/train/metrics/registry.py
runtime/onert/api/python/package/experimental/train/optimizer/adam.py
runtime/onert/api/python/package/experimental/train/optimizer/optimizer.py
runtime/onert/api/python/package/experimental/train/optimizer/registry.py
runtime/onert/api/python/package/experimental/train/optimizer/sgd.py
runtime/onert/api/python/package/experimental/train/session.py

This commit adds typing annotations across training API modules.
- Applied `from typing` imports and added type hints to DataLoader methods and attributes
- Annotated LossFunction, MeanSquaredError, CategoricalCrossentropy constructors with `Literal`, `Dict` and return types
- Typed LossRegistry and MetricsRegistry: `create_*` and `map_*` methods use `str`, `Type[...]`, and enum return types
- Annotated Optimizer base class, Adam, SGD and OptimizerRegistry with `float`, `Optional`, `Dict`, and `Type[...]`
- Added precise types to TrainSession: `train_info: traininfo`, `optimizer: Optional[Optimizer]`, `loss: Optional[LossFunction]`, `metrics: List[Metric]`, `total_time: Dict[str, Union[float,List[float]]]`, and method signatures

[onert/python] Add typing annotations across training API modules

---

runtime/onert/api/python/package/common/basesession.py
runtime/onert/api/python/package/infer/session.py
runtime/onert/sample/minimal-python/src/minimal.py
runtime/onert/sample/minimal-python/src/static_shape_inference.py

This commit supports static shape modification across inference API and samples.
- common/basesession.py: add typed get_inputs_tensorinfo/get_outputs_tensorinfo helpers
- infer/session.py:
- normalize any `-1` dims to `1` then call `update_inputs_tensorinfo` in `__init__`
- remove obsolete `compile()` method
- provide `update_inputs_tensorinfo` and `infer` with full type hints
- samples:
- minimal sample: build dummy inputs from tensorinfo and use `infer`
- static_shape_inference example: demonstrate modifying input tensorinfo (e.g. batch size → 10) and running inference with static shapes

[onert/python] Support static shape modification across inference API

---

runtime/compute/cker/include/cker/Shape.h
runtime/compute/cker/include/cker/Types.h
runtime/compute/cker/include/cker/operation/StridedSlice.h
runtime/compute/cker/src/Shape.test.cc
runtime/compute/cker/src/StridedSlice.test.cc
runtime/onert/core/include/util/ShapeInference.h
runtime/onert/core/src/compiler/ShapeValidator.cc
runtime/tests/nnfw_api/src/GenModelTests/one_op_tests/StridedSlice.test.cc

- StridedSlice now supports rank 5 input tensor.
- StridedSlice now supports int32 dtype for begin, end, strides.
for https://github.com/Samsung/ONE/issues/15186

[onert] Stridedslice supports rank 5 input and int32 dtype for begin,end,stride.

---

.gitignore

This will add /debian folder to gitignore as /debian is temporary folder for multiple Debian package generation.

Add debian to gitignore

---

.github/workflows/build-docker-circle-mlir.yml

This will revise build-docker-circle-mlir workflow to build U20.04 Docker image.

[github] Add U20.04 to build-docker-circle-mlir

---

circle-mlir/infra/docker/u2004/Dockerfile

This will add CMake 3.22 to Dockerfile to meet onnx-mlir build.

[circle-mlir/infra] Add CMake 3.22 to Dockerfile

---

circle-mlir/infra/docker/u2004/Dockerfile
circle-mlir/infra/docker/u2204/Dockerfile

This revises some package versions in the Dockerfile for Ubuntu 20.04 and 22.04.
The versions now match those used in the prepare-venv script.

[circle-mlir/infra] Revise the package versions in Dockerfile

---

.github/workflows/run-circle-mlir-build.yml

This will run-circle-mlir-build to install circle-interpreter with build from source.

[github] Revise run-circle-mlir-build

---

runtime/onert/api/python/package/common/basesession.py
runtime/onert/api/python/package/infer/session.py
runtime/onert/sample/minimal-python/src/inference_benchmark.py

This commit adds inference benchmark sample and latency measurement support.
- Added `inference_benchmark.py` sample for measuring inference latency and memory usage
- Supports static shape override via `--input-shape`
- Measures MODEL_LOAD / PREPARE / EXECUTE / PEAK memory (RSS) and I/O / run latency
- Updated `session.infer()` API to optionally return latency metrics using `measure=True`
- Fixed potential memory accumulation in `set_inputs()` and `set_outputs()` by clearing internal buffers each call
- Added `_time_block()` context manager for clean latency measurement implementation

[onert/python] Support infernece benchmark

---

circle-mlir/circle-mlir/lib/utils/src/FlatbufferOperator.cpp

This will fix reference source path of FlatbufferOperator.cpp.

[circle-mlir/utils] Fix reference source

---

circle-mlir/infra/docker/u2004/Dockerfile

This revises the Dockerfile to use `-rf` option when removing directory.

[circle-mlir/infra] Revise the Dockerfile for Ubuntu-20.04

---

.github/workflows/run-circle-mlir-build.yml

This will revise run-circle-mlir-build workflow to run focal too.

[github] Add focal to cirle-mlir build

---

compiler/circle-resizer/include/CircleModel.h
compiler/circle-resizer/requires.cmake
compiler/circle-resizer/src/CMakeLists.txt
compiler/circle-resizer/src/CircleModel.cpp
compiler/circle-resizer/tests/CMakeLists.txt
compiler/circle-resizer/tests/CircleModel.test.cpp

This commit adds new CircleModel class responsible for loading and processing model in Circle model. The additional features are extraction information about input/output shapes and saving the current version to file/stream.

[circle-resizer] Add CircleModel

---

runtime/onert/api/python/package/experimental/train/session.py

This commit introduce `eval_step` and common batch logic into `_batch_step`.
- Introduce private helper `_batch_step(inputs, expecteds, update_weights)` to handle binding inputs, running session, collecting losses/metrics, and timing
- Update `train_step` to call `_batch_step(..., update_weights=True)` and expose `"train_time"`
- Add `eval_step` for forward‑only inference, calling `_batch_step(..., update_weights=False)` and exposing `"eval_time"`
For https://github.com/Samsung/ONE/issues/15172#issuecomment-2814288794

[onert/python] Introduce `eval_step`

---

circle-mlir/circle-mlir/lib/arser/include/arser/arser.h

This will explictly add missing cstdint header.

[circle-mlir/arser] Add missing cstdint header

---

compiler/circle-resizer/include/Shape.h

This commit resolves warning "circle_resizer::operator<< has not been declared within ‘circle_resizer’"

[circle-resizer] Resolve warning of operator<< for Shape

---

compiler/coco/core/include/coco/IR/Op.h

This will add missing header to fix U24.04 build.

[coco] Add missing header

---

compiler/luci-interpreter/src/kernels/GRU.cpp

This will fix delete to use array, as this fails in gcc-13, U24.04.

[luci-interpreter] Fix delete for array

---

tools/onnx_subgraph/include/partition.h
tools/onnx_subgraph/src/lib/partition.cpp
tools/onnx_subgraph/src/main.cpp

add functions definition for onnx model partition

[tools/onnx-subgraph] add functions for onnx model partition

---

compiler/circle-resizer/include/ModelEditor.h
compiler/circle-resizer/src/CMakeLists.txt
compiler/circle-resizer/src/ModelEditor.cpp
compiler/circle-resizer/tests/CMakeLists.txt
compiler/circle-resizer/tests/ModelEditor.test.cpp

This commit adds class responsible for model editing - in the current moment input resizing.

[circle-resizer] Add ModelEditor

---

compiler/nnc/include/support/CommandLine.h

This will add missing header to fix U24.04 build.

[nnc] Add missing header

---

compiler/moco/import/src/Nodes/Const.cpp
compiler/moco/import/src/Nodes/Placeholder.cpp

This will fix not to use reference for dangling variable inside callee.

[moco] Do not use reference for dangling variable

---

compiler/luci/pass/include/luci/ModulePass.h
compiler/luci/pass/src/VerifyQuantizedNodeType.h

This will revise luci::Pass to fix gcc-13 overloaded-virtual error.

[luci/pass] Revise Pass to fix gcc-13 error

---

compiler/exo/src/Circle/CircleOperationExporter.cpp
compiler/exo/src/TFLite/TFLOperationExporter.cpp

This will fix for gcc-13 overloaded-virtual option on U24.04 build.

[exo] Fix for gcc-13 overloaded-virtual

---

compiler/nnkit/actions/HDF5/Common.h

This will add missing header to fix U24.04 build.

[nnkit] Add missing header

---

compiler/plier-tf/src/Convert.cpp

This will revise not to use local variable that is used for return value.
This change is to make compiler happy with -Werror=dangling-reference option.

[plier-tf] Do not use local variable

---

compiler/circle-resizer/README.md
compiler/circle-resizer/app/CMakeLists.txt
compiler/circle-resizer/app/CircleResizer.cpp

This commit exposes a command line interface for circle-resizer application. README.md was updated to the current capabilities.

[circle-resizer] Expose cmd interface

---

compiler/mir/CMakeLists.txt
compiler/mir/src/mir_caffe2_importer/CMakeLists.txt
compiler/mir/src/mir_caffe_importer/CMakeLists.txt
compiler/mir/src/mir_onnx_importer/CMakeLists.txt

This will disable nncc_common option to prevent _GLIBCXX17_DEPRECATED warning as error.

[mir] Disable nncc_common option

---

compiler/nnc/cmake/utils.cmake

This will disable nncc_common option to prevent _GLIBCXX17_DEPRECATED warning as error.

[nnc] Disable nncc_common option

---

nnpackage/schema/circle_schema.fbs

This adds MXQuantization to circle schema.
---
Draft PR: #15259

[nnpackage] Add MXQuantization to circle schema

---

compiler/luci/export/src/CircleTensorExporter.cpp
compiler/luci/import/include/luci/Import/CircleReader.h
compiler/luci/import/src/CircleReader.cpp
compiler/luci/lang/include/luci/IR/CircleMXQuantParam.h
compiler/luci/lang/include/luci/IR/CircleNodeDecl.h

This introduces MXQuantization in luci.
---
Draft PR: https://github.com/Samsung/ONE/pull/15259

[luci] Introduce MXQuantization parameter

---

compiler/common-artifacts/CMakeLists.txt

This will prepare venv without version number.
Old one will be removed after user module migration are done.

[common-artifacts] Prepare venv without version number

---

runtime/compute/cker/include/cker/Utils.h
runtime/compute/cker/include/cker/operation/BinaryArithmeticOps.h
runtime/compute/cker/include/cker/operation/reference/BinaryArithmeticOps.h
runtime/compute/cker/src/Mul.test.cc

BinaryArithmetic op like add, mul, etc will support rank 6.
for https://github.com/Samsung/ONE/issues/15221

[compute/cker] BinaryArithmetic op supports rank 6

---

compiler/circle-interpreter-cffi-test/CMakeLists.txt

[cir-int-cffi-test] Use venv without ver num

---

compiler/circle-part-value-py-test/CMakeLists.txt

[cir-part-val-py-test] Use venv without ver num

---

compiler/circle-part-value-test/CMakeLists.txt

[cir-par-val-test] Use venv without ver num

---

compiler/dalgona-test/CMakeLists.txt

[dalgona-test] Use venv without ver num

---

compiler/fm-equalize-value-py-test/CMakeLists.txt

[fm-eq-value-py-test] Use venv without ver num

---

compiler/luci-ref-value-py-test/CMakeLists.txt

[luci-ref-value-py-test] Use venv without ver num

---

compiler/luci-value-py-test/CMakeLists.txt

[luci-value-py-test] Use venv without ver num

---

compiler/luci-value-test/CMakeLists.txt

[luci-value-test] Use venv without ver num

---

compiler/luci-pass-value-test/CMakeLists.txt

[luci-pass-value-test] Use venv without ver num

---

runtime/onert/api/python/package/infer/session.py
runtime/onert/sample/minimal-python/src/dynamic_shape_inference.py
runtime/onert/sample/minimal-python/src/static_shape_inference.py

This commit support dynamic shapes and add dynamic_shape_inference sample.
- Remove the old “replace -1 with 1” placeholder in the constructor
- In `infer()`, on first call:
- Inspect each `tensorinfo.dims` and for any `-1` replace it with the matching `inputs_array[i].shape[j]`
- Validate that any non-`-1` dims match the actual input shape, raising on mismatch
- Call `update_inputs_tensorinfo()`, then `prepare()` and `set_outputs()` once
- Bundle the above into the “auto‑dynamic” path instead of hard‑coding 1’s
- Add `dynamic_shape_inference.py` sample to show 10 runs with random shapes
- Update `minimal.py` to retain its original static‑shape example logic

[onert/python] Support dynamic shapes(on-the-fly)

---

.github/workflows/run-onert-micro-unit-tests.yml

- ubuntu 20.04 is deprecated since 2025-04-15

[workflow] use ubuntu-22.04 for onert-micro

---

.github/workflows/run-onecc-build.yml

This adds docker credentials for docker container image in the workflow.

[github] Add docker credentials in onecc build workflow

---

.github/workflows/run-onecc-build.yml

This will remove credential from run-onecc-build, as secret access is not possible from fork.

[github] Remove credential from run-onecc-build

---

compiler/q-implant-qparam-test/CMakeLists.txt

[q-implant-qparam-test] Use venv without ver num

---

compiler/record-minmax-conversion-test/CMakeLists.txt

[record-minmax-conversion-test] Use venv without ver num

---

compiler/record-minmax-thread-safety-test/CMakeLists.txt

[record-minmax-ts-test] Use venv without ver num

---

compiler/pota-quantization-value-test/CMakeLists.txt

[pota-qu-val-test] Use venv without ver num

---

compiler/fm-equalize-value-py-test/CMakeLists.txt

This will revise to use python lib from venv to numpy not found error,
when there is no numpy installed in the system.

[fm-eq-val-py-test] Fix numpy not found error

---

runtime/onert/core/src/loader/BaseLoader.h

This commit removes BatchMatMul custom OP support. 
BatchMatMul is handled as built-in OP.
---
Related issue: https://github.com/Samsung/ONE/issues/15216

[onert] Remove BatchMatMul custom OP

---

compiler/common-artifacts/CMakeLists.txt

This will revise to set PYTHON_VERSION_MINOR for cmake version >= 3.12.

[common-artifacts] Set PYTHON_VERSION_MINOR

---

compiler/pics/CMakeLists.txt

This commit adds mio-circle08 dependency.
It requires to access copied file.
It will resolve random build fail issue.

[pic] Add mio-circle08 dependency

---

compiler/common-artifacts/CMakeLists.txt

This will split python package list by python version 3.8 and 3.10.

[common-artifacts] Split python package list

---

.github/workflows/check-format.yml

This commit installs the clang-format-16 package even if it is existing in runner. 
It prevents failure when runner is upgraded and clang-format-16 package is removed.

[infra] Install clang-format-16 package anyway

---

infra/debian/circle-interpreter/copyright

This updates the `copyright` file for the `circle-interpreter` Debian package.
The format was referenced from the official Debian documentation: 
https://www.debian.org/doc/packaging-manuals/copyright-format/1.0

[infra/debian] Revise copyright file for circle-interpreter

---

infra/debian/circle-interpreter/circle-interpreter.lintian-overrides

This adds a `lintian-overrides` file to suppress the warning about the missing manpage for the `circle-interpreter` binary.

[infra/debian] Ignore manpage for circle-interpreter binary

---

runtime/onert/backend/cpu/ops/DepthwiseConvolutionLayer.cc
runtime/onert/backend/cpu/ops/DepthwiseConvolutionLayer.h
runtime/onert/backend/train/ops/DepthwiseConvolutionLayer.cc
runtime/onert/backend/train/ops/DepthwiseConvolutionLayer.h

This commit removes internal Tensor from DepthwiseConvolutionLayer.
- Delete prepareF32() and its references in CPU op and train op
- Remove `_padded_filter`, `_filter_buffers` members and related includes
- Simplify convFloat32() to always call DepthwiseConv without extra buffers

[onert] Remove internal Tensor from DepthwiseConvolutionLayer

---

compiler/common-artifacts/exclude.lst

This commit excludes Inf_StridedSlice_002 because TestDataGenerator does not support unknown dimensions. The produced model will be tested by CircleResizer.

[common-artifacts] Exclude Inf_StridedSlice_002 recipe

---

runtime/onert/core/include/exec/DynamicShapeInferer.h
runtime/onert/core/src/exec/DynamicShapeInferer.cc

This commit extends `DepthwiseConv2D` operator to support dynamic input and output shapes.

[onert] Support dynamic shapes in DepthwiseConv2D

---

runtime/onert/core/src/compiler/StaticShapeInferer.cc

This commit marks op inputs with unknown dimension as dynamic during static shape inference.

[onert] Mark op inputs with unknown dimension as dynamic

---

.github/workflows/run-circle-mlir-build.yml

This will revise run-circle-mlir-build to install circle-interpreter from launchpad nightly builds.

[github] Revise run-circle-mlir-build with circle-interpreter

---

infra/debian/circle-interpreter/rules

This removes the ONE build scripts, as the `circle-interpreter` and its related binaries will be built in the GitHub workflow.
This is necessary because Debian builds on Launchpad do not support fetching external code, such as TensorFlow, during the build process.

[infra/debian] Revise rules for circle-interpreter

---

infra/debian/circle-interpreter/circle-interpreter.install

Install the shared library files for `circle-interpreter` by copying them.

[infra/debian] Revise circle-interpreter.install script

---

infra/debian/circle-interpreter/circle-interpreter.install

This fixes the `circle-interpreter` install script, which was missing the step to copy the binary file.

[infra/debian] Fix missing binary file copy in install script

---

.github/workflows/build-circle-intp.yml

This removes all outdated content and restructures the workflow with initial jobs:
`configure`, `debian-release`, and `create-pr-on-success`.
The detailed steps will be completed in the following PRs.

[github] Clean up build-circle-intp workflow

---

.github/workflows/pub-circle-int-launchpad.yml

This updates the name of the `circle-interpreter` publishing workflow, along with its inputs.

[github] Revise workflow name and its inputs

---

.github/workflows/pub-circle-int-launchpad.yml

This implements the `configure` job to set the current version of the target `circle-interpreter` package.

[github] Add configuration for publishing circle-interpreter

---

runtime/onert/core/include/backend/basic/Tensor.h

This commit initialize Tensor size to 0 for dynamic shapes. instead of total size.

[onert] Initialize Tensor size to 0 for dynamic shapes

---

runtime/onert/backend/cl_common/include/cl_common/BackendContext.h
runtime/onert/backend/train/BackendContext.cc
runtime/onert/backend/train/TensorPlanner.cc
runtime/onert/core/include/backend/basic/BackendContextHelpers.h
runtime/onert/core/include/ir/IOperation.h
runtime/onert/core/include/ir/Operation.h
runtime/onert/core/include/ir/Shape.h
runtime/onert/core/src/compiler/ExecutorFactory.cc
runtime/onert/core/src/compiler/Fp32ToFp16Converter.cc
runtime/onert/core/src/compiler/StaticShapeInferer.cc
runtime/onert/core/src/compiler/pass/ConstantInsertionPass.cc
runtime/onert/core/src/compiler/pass/ConstantLoweringPass.cc
runtime/onert/core/src/compiler/train/StaticBackwardShapeInferer.cc
runtime/onert/core/src/compiler/train/pass/TrainableConstantInsertionPass.cc
runtime/onert/core/src/ir/Graph.cc
runtime/onert/core/src/ir/Operation.cc
runtime/onert/core/src/ir/train/TrainableGraph.cc
runtime/onert/core/src/ir/train/UseDefGenerator.cc

This commit replaces input filters with `getUsedInputSet()`
- Replace all occurrences of `op.getInputs() | ir::Remove::DUPLICATED | ir::Remove::UNDEFINED` with `op.getUsedInputSet()`
- Add `virtual OperandIndexSequence getUsedInputSet() const` to `ir::IOperation`
- Implement `getUsedInputSet()` in `Operation` to return `_inputs | ir::Remove::UNDEFINED | ir::Remove::DUPLICATED`
- Add `assert(_dimensions.size() > 0)` in `Shape::hasUnspecifiedDims()` to prevent empty dimension lists

[onert] Replace input filters with `getUsedInputSet()`

---

infra/nnfw/CMakeLists.txt
infra/nnfw/cmake/packages/EigenConfig.cmake
infra/nnfw/cmake/packages/EigenSourceConfig.cmake
infra/nnfw/cmake/packages/FlatBuffersConfig.cmake
infra/nnfw/cmake/packages/FlatBuffersSourceConfig.cmake
infra/nnfw/cmake/packages/Fp16Config.cmake
infra/nnfw/cmake/packages/Fp16SourceConfig.cmake
infra/nnfw/cmake/packages/GEMMLowpConfig.cmake
infra/nnfw/cmake/packages/GEMMLowpSourceConfig.cmake
infra/nnfw/cmake/packages/GTestConfig.cmake
infra/nnfw/cmake/packages/GTestSourceConfig copy.cmake
infra/nnfw/cmake/packages/GTestSourceConfig.cmake
infra/nnfw/cmake/packages/NEON2SSESourceConfig.cmake
infra/nnfw/cmake/packages/Pybind11Config.cmake
infra/nnfw/cmake/packages/Pybind11SourceConfig.cmake
infra/nnfw/cmake/packages/Ruy/CMakeLists.txt
infra/nnfw/cmake/packages/RuyConfig.cmake
infra/nnfw/cmake/packages/RuySourceConfig.cmake
infra/nnfw/cmake/packages/TensorFlowLite/CMakeLists.txt
infra/nnfw/cmake/packages/TensorFlowLiteConfig.cmake
infra/nnfw/cmake/packages/TensorFlowSourceConfig.cmake
runtime/contrib/android_benchmark_app/CMakeLists.txt

This commit copies cmake source config to use runtime's own config.
---
Related issue: https://github.com/Samsung/ONE/issues/15231
Draft: #15235

[infra/onert] Use runtime source config

---

.github/workflows/pub-circle-int-launchpad.yml

This introduces a matrix strategy to support multiple distributions for the `circle-interpreter` Debian release on Launchpad.

[github] Introduce matrix strategy

---

.github/workflows/pub-circle-int-launchpad.yml

This adds a missing quote in the workflow step.

[github] Add missing quote

---

.github/workflows/pub-circle-int-launchpad.yml

This adds the `prepare` step to run before building the `circle-interpreter` binary from the ONE compiler.

[github] Implement prepare step

---

compiler/one-cmds/one-prepare-venv

This will add numpy as default install package in one-prepare-venv.

[one-cmds] Add numpy to one-prepare-venv

---

circle-mlir/infra/overlay/prepare-venv

This will fix to use numpy 1.24.3.

[circle-mlir/infra] Fix numpy version to 1.24.3

---

compiler/one-cmds/one-prepare-venv

This will revise one-prepare-venv to explictly find python version supported in highest order to lowest.

[one-cmds] Revise one-prepare-venv with python version

---

runtime/onert/backend/cl_common/include/cl_common/BackendContext.h
runtime/onert/backend/train/TensorPlanner.cc
runtime/onert/core/include/backend/basic/BackendContextHelpers.h
runtime/onert/core/include/ir/IOperation.h
runtime/onert/core/include/ir/Operation.h
runtime/onert/core/src/compiler/ExecutorFactory.cc
runtime/onert/core/src/compiler/Fp32ToFp16Converter.cc
runtime/onert/core/src/compiler/pass/ConstantInsertionPass.cc
runtime/onert/core/src/compiler/train/StaticBackwardShapeInferer.cc
runtime/onert/core/src/ir/Graph.cc
runtime/onert/core/src/ir/Operation.cc
runtime/onert/core/src/ir/train/TrainableGraph.cc

This replaces all occurrences of `op.getOutputs() | ir::Remove::DUPLICATED | ir::Remove::UNDEFINED` with `op.getUsedOutputSet()`.

[onert] Replace output filters with `getUsedOutputSet()`

---

runtime/onert/core/include/backend/basic/Tensor.h
runtime/onert/core/src/backend/basic/Tensor.cc

This commit updates tensor constructor to initialize size when shape does not have unspecified dimension.

[onert] Change tensor size initialization

---

runtime/onert/core/include/ir/Shape.h

This commit removes an unnecessary assertion from `Shape::hasUnspecifiedDims()`.

[onert] Fix wrong assertion

---

.github/workflows/build-pub-dev-docker.yml
.github/workflows/run-onert-android-build.yml
.github/workflows/run-onert-cross-build.yml
.github/workflows/run-onert-native-build.yml

This commit updates onert external cache key usage
- Don't use hash in infra/cmake. It is not used on onert build any more
- Remove restore-key 'external': block sharing between runtime and compiler
- Remove restore-key 'external-onert': block sharing between different ubuntu version

[infra] Update onert external cache usage

---

.github/workflows/pub-circle-int-launchpad.yml

This grants root privileges when a job runs inside a Docker container.
Without this setting, permission errors may occur when accessing the temporary path.

[github] Enable root privilege for container usage

---

infra/debian/circle-interpreter/circle-interpreter.install
infra/debian/circle-interpreter/circle-interpreter.links

This will revise the path from `cirint` to `circletools` of `circle-interpreter` installation path.

[infra/debian] Revise the path of circle-interpreter to be installed

---

.github/workflows/pub-circle-int-launchpad.yml

This implements uploading circle-interpreter debian package to the Launchpad and github artifact.

[github] Upload package to Launchpad and artifact

---

.github/workflows/pub-circle-int-launchpad.yml

This implements the creating changelog artifact of circle-interpreter debian package from the default distro jammy.

[github] Upload changelog to github artifact

---

.github/workflows/pub-circle-int-launchpad.yml

This sets up the Git configuration before creating a pull request
to update the changelog of the `circle-interpreter` Debian package.

[github] Set up Git configuration

---

.github/workflows/pub-circle-int-launchpad.yml

This adds logic to create a pull request that updates the changelog file,
after successfully uploading the `circle-interpreter` Debian package to Launchpad.

[github] Create PR to update changelog

---

infra/debian/circle-interpreter/changelog

This sets up the initial changelog file for the `circle-interpreter` Debian package.

[infra/debian] Initial changelog for circle-interpreter

---

infra/debian/circle-interpreter/changelog

This updates the changelog for circle-interpreter_1.30.0~202505191026.
This PR includes updated changelog after successful debian build.
It is auto-generated PR from github workflow.

[infra/debian] Update changelog for circle-interpreter

---

compiler/circle-resizer-dredd-recipe-test/CMakeLists.txt
compiler/circle-resizer-dredd-recipe-test/README.md
compiler/circle-resizer-dredd-recipe-test/requires.cmake
compiler/circle-resizer-dredd-recipe-test/test.lst
compiler/circle-resizer-dredd-recipe-test/testall.sh

This commit introduces dredd tests for circle-resizer tool

[circle-resizer-dredd-recipe-test] Add circle-resizer dredd tests

---

runtime/onert/api/python/include/nnfw_exception_bindings.h
runtime/onert/api/python/include/nnfw_exceptions.h
runtime/onert/api/python/package/common/basesession.py
runtime/onert/api/python/package/infer/session.py
runtime/onert/api/python/src/bindings/nnfw_api_wrapper_pybind.cc
runtime/onert/api/python/src/bindings/nnfw_exception_bindings.cc
runtime/onert/api/python/src/wrapper/nnfw_api_wrapper.cc

This commit introduces NNFW exception bindings and comprehensive error handling.
- Add `nnfw_exception_bindings.h` and `nnfw_exceptions.h` to define C++ exception types for NNFW errors
- Bind all `NnfwError` subclasses into the Python module under a new exception submodule
- Update `nnfw_api_wrapper` to replace `exit(1)` calls with throwing the corresponding NnfwError exceptions
- Refactor `getLayout`, `getType` and `getStringType` to throw `NnfwError` on invalid inputs instead of exiting
- In Python wrappers (`BaseSession`, `session`, and convenience functions), catch generic errors and rethrow them as `OnertError` with context
- Ensure all C-API calls in Python raise `OnertError` on failure, improving robustness and traceback clarity
ONE-DCO-1.0-Signed-off-by: ragmani …

[onert/python] Introduce NNFW exception bindings

---

runtime/onert/backend/trix/CMakeLists.txt
runtime/onert/loader/trix/CMakeLists.txt

This commit replaces the use of the private cmake with the PkgConfig module. It will prevent a potential build failure caused by varying library paths.

[onert] Use PkgConfig cmake module to find TRIXEngine

---

infra/nncc/CMakeLists.txt

This will revise cmake minimum required to 3.16.

[infra/nncc] Revise cmake minumum to 3.16

---

compiler/dalgona/CMakeLists.txt

This will tidy cmake version check for python installation.
cmake is now required to be 3.16.

[dalgona] Tidy cmake version check for python

---

compiler/common-artifacts/CMakeLists.txt

This will tidy cmake version check for python installation.
cmake is now required to be 3.16.

[common-artifacts] Tidy cmake version check for python

---

compiler/one-cmds/CMakeLists.txt

This will tidy cmake version check for python installation.
cmake is now required to be 3.16.

[one-cmds] Tidy cmake version check for python

---

infra/nncc/cmake/buildtool/config/config_armv7l-tizen.cmake

For tizen build, 'mtune' and 'mfloat' are already predefined.

[infra] Remove duplicate complie options

---

circle-mlir/CMakeLists.txt

This will disable gtest and gmock from installing with '--install' command.

[cirle-mlir] Disable gtest, gmock installing

---

circle-mlir/Makefile.sample
circle-mlir/README.md

This will add install to Makefile to install release artifacts to (ONE)/build/install.

[circle-mlir] Add install to Makefile

---

.github/workflows/build-dev-docker.yml

This commit changes build command to test Dockerfile update from `build-docker-image` custom command to `docker build` commend directly.

[infra] Use docker build to test Dockerfile update

---

infra/nnfw/cmake/buildtool/config/config_armv7l-tizen.cmake

Let's use 'neon-fp-armv8' when the target architecture is armv8.

[infra] Use armv8 neon option according to target arch

---

compiler/one-cmds/CMakeLists.txt

This commit adds a dependency on cfg file creation to the destination directory. 
It prevents build fail by trying to create a cfg file in a non-existing directory.

[one-cmds] Add dependency to directory creation

---

compiler/circledump/src/Dump.cpp

This dumps MX quantization parameters.
---
Draft PR: https://github.com/Samsung/ONE/pull/15259

[circledump] Dump MX quantization parameters

---

infra/cmake/packages/Pybind11SourceConfig.cmake

This commit bumps up the version of pybind11 to latest version: 2.13.6. 
It supports detecting python on latest manylinux docker image - cmake 4.0, without Development.Embed component.

[infra] Bump up pybind11

---

infra/nnfw/cmake/packages/Pybind11SourceConfig.cmake

This commit bumps up the version of pybind11 to latest version: 2.13.6. 
It supports detecting python on latest manylinux docker image - cmake 4.0, without Development.Embed component

[infra/onert] Bump up pybind11

---

compiler/one-cmds/CMakeLists.txt

This will enable to install onnx2circle through env-var if set,
or install from circle-mlir folder if exist.

[one-cmds] Install onnx2circle through env-var

---

infra/debian/circle-interpreter/changelog

This fixes the trailer line in the changelog file for the `circle-interpreter` Debian package.

[infra/debian] Fix the trailer line of changelog

---

circle-mlir/infra/debian/onnx2circle/onnx2circle.lintian-overrides

This adds a `lintian-overrides` file for the `onnx2circle` Debian package.

[circle-mlir/infra] Create lintian-overrides file

---

circle-mlir/infra/debian/onnx2circle/onnx2circle.install
circle-mlir/infra/debian/onnx2circle/onnx2circle.links
circle-mlir/infra/debian/onnx2circle/rules

This adds the rules and its related files for the `onnx2circle` Debian package installation.

[circle-mlir/infra] Create debian rules and related files

---

.github/workflows/pub-onnx2circle-launchpad.yml

This replaces the placeholder `configure` job with an actual implementation
that generates the Debian version for the `onnx2circle` package.

[github] Implement configure job for the versioning

---

.github/workflows/pub-onnx2circle-launchpad.yml

This adds preparation steps before building `circle-mlir`.
It also installs the `circle-interpreter`, which will be used during the test step.

[github] Implement preparation steps before building circle-mlir

---

.github/workflows/run-onecc-build.yml

This will fix test log path of run-onecc-build workflow.

[github] Fix test log path of run-onecc-build

---

Makefile.template
infra/nnfw/cmake/CfgOptionFlags.cmake
infra/nnfw/cmake/buildtool/config/config_aarch64-android.cmake
infra/nnfw/cmake/buildtool/config/config_aarch64-linux.cmake
infra/nnfw/cmake/buildtool/config/config_aarch64-tizen.cmake
infra/nnfw/cmake/buildtool/config/config_armv7hl-tizen.cmake
infra/nnfw/cmake/buildtool/config/config_armv7l-tizen.cmake
infra/nnfw/cmake/buildtool/config/config_i686-tizen.cmake
infra/nnfw/cmake/buildtool/config/config_riscv64-tizen.cmake
infra/nnfw/cmake/buildtool/config/config_x86_64-linux.cmake
infra/nnfw/cmake/buildtool/config/config_x86_64-tizen.cmake
infra/nnfw/command/configure
runtime/CMakeLists.txt

This commit moves runtime root cmake into `runtime` directory.
---
Related issue: https://github.com/Samsung/ONE/issues/15231
Draft: https://github.com/Samsung/ONE/pull/15235

[infra/onert] Move runtime root cmake

---

.github/workflows/pub-onnx2circle-launchpad.yml

This adds configuration and build steps for the `circle-mlir`.

[github] Implement build script for circle-mlir

---

.github/workflows/pub-onnx2circle-launchpad.yml

This implements steps to update the changelog and generate the tarball for the `onnx2circle` Debian package.

[github] Create tarball for onnx2circle Debian package

---

.github/workflows/pub-onnx2circle-launchpad.yml

This adds a job that extracts the changelog file from the default distribution `jammy` and uploads it as a GitHub artifact.

[github] Implement job to create changelog artifact

---

.github/workflows/pub-onnx2circle-launchpad.yml
circle-mlir/circle-mlir/tools/onnx2circle/src/onnx2circle.cpp

This updates the version of `onnx2circle` from `0.2.0` to `0.3.0`,
as it now includes updated versions of `llvm-project` and `onnx-mlir`.

[circle-mlir] Bump onnx2circle version to 0.3.0

---

.github/workflows/run-onecc-build.yml

This will remove temporary fix to use "deb https://".

[CI] Remove temporary fix to use https

---

.github/workflows/run-onecc-build.yml

This will add to ensure pip in run-onecc-build workflow.

[CI] add ensurepip to run-onecc-build

---

compiler/one-cmds/CMakeLists.txt

This will revise how to get onnx2circle path as;
- first is to use explictly given ONE_ONNX2CIRCLE_PATH
- next is to use local bind install of circle-mlir
- and last is to use install of circletools/onnx2circle debian package

[one-cmds] Revise how to get onnx2circle path

---

compiler/common-artifacts/CMakeLists.txt

This will tidy duplicate checks of python version less than 3.8.

[common-artifacts] Tidy duplicate checks

---

compiler/one-cmds/CMakeLists.txt

This will revise python version check to supported ones explictly.
Although 3.12 was marked as unsupported, this update will allow it
to prepare Ubuntu 24.04 support.

[one-cmds] Revise python version check

---

compiler/CMakeLists.txt
compiler/common-artifacts/CMakeLists.txt

This will introduce ONE_PYTHON_VERSION_MINOR for modules using
common-artifacts virtual-env to utilize python 3.x minior version numnber.

[common-artifacts] Introduce ONE_PYTHON_VERSION_MINOR

---

compiler/fm-equalize-value-py-test/CMakeLists.txt

This will revise to use python minor version from common-artifacts.

[fm-eq-val-py-test] Use python version from common-artifacts

---

.github/workflows/run-circle-mlir-build.yml

This will path exclusion using '!'.

[github] Fix run-circle-mlir-build exclude

---

compiler/record-minmax/src/DirectoryIterator.cpp

This commit calls closedir to prevent memory leakage.
This is from static analysis tool.

[record-minmax] Call closedir

---

circle-mlir/circle-mlir/lib/pass/src/RewriteCirclePass.cpp
circle-mlir/circle-mlir/lib/pass/src/opt/ConvertResizeBilinearSize32.h

This will introduce ConvertResizeBilinearSize32 that will
convert int64_t size input to int32_t for luci compatibility.

[circle-mlir/pass] Introduce ConvertResizeBilinearSize32

---

runtime/onert/api/nnfw/include/nnfw_internal.h
runtime/onert/api/nnfw/src/nnfw_internal.cc
runtime/onert/api/nnfw/src/nnfw_session.cc
runtime/onert/api/nnfw/src/nnfw_session.h

This commit adds `nnfw_get_output` API as nnfw internal api for Python bindings.
- Implement `nnfw_get_output` to retrieve the output buffer and tensor info after `nnfw_run`.
- Update `nnfw_session` to include the `get_output` method.
- Add necessary error handling for invalid state and null pointers.
---
For #15342 
Draft #15455

[onert] Add `nnfw_get_output` C API for Python bindings

---

circle-mlir/infra/debian/onnx2circle/changelog

This updates the changelog for onnx2circle_0.4.0~202506100012.
This PR includes updated changelog after successful debian build.
It is auto-generated PR from github workflow.

[circle-mlir/infra] Update changelog for onnx2circle

---

runtime/onert/api/python/include/nnfw_api_wrapper.h
runtime/onert/api/python/include/nnfw_tensorinfo_bindings.h
runtime/onert/api/python/src/bindings/nnfw_api_wrapper_pybind.cc
runtime/onert/api/python/src/bindings/nnfw_session_bindings.cc
runtime/onert/api/python/src/bindings/nnfw_tensorinfo_bindings.cc
runtime/onert/api/python/src/wrapper/nnfw_api_wrapper.cc

This commit exposes internal get_output and prepare_config API in Python bindings.
- Include nnfw_internal.h in the Python API wrapper header
- Add `get_output(uint32_t index)` method to NNFW_SESSION wrapper, returning a read-only NumPy copy
- Register `get_output` and `set_prepare_config` in the pybind11 module
- Introduce `bind_nnfw_enums` to expose the NNFW_PREPARE_CONFIG enum values
---
For #15342 
Draft #15455

[onert/python] Expose internal output and prepare_config API

---

circle-mlir/circle-mlir/lib/dialect/src/ShapeInference.cpp

This revises the comment of Relu/PRelu ShapeInference.

[circle-mlir/dialect] Revise comment of shape inference

---

runtime/compute/cker/src/Shape.test.cc
runtime/compute/cker/src/StridedSlice.test.cc

This commit adds SUCCEED macro to test using EXPECT_EXIT_BY_ABRT_DEBUG_ONLY for TC checker workaround.

[onert/test] Add SUCCEED macro for  EXPECT_EXIT_BY_ABRT_DEBUG_ONLY

---

runtime/onert/core/src/compiler/ExecutorFactory.cc
runtime/onert/core/src/compiler/LoweredGraph.cc
runtime/onert/core/src/compiler/pass/PermutationEliminationPass.cc

This commit repositions LowerInfo in PermutationEliminationPass.
- Move `dumpLowerInfo()` to after all optimization passes in LoweredGraph for accurate state dumping
- In `PermutationEliminationPass`, update `lower_info`'s def_backends and use_backends:
- Transfer def_backends from input to output operands when eliminating permutes
- Transfer use_backends from output back to input operands
---
For #15342 
Draft #15455

[onert] Reposition LowerInfo in PermutationEliminationPass

---

circle-mlir/circle-mlir/tools/onnx2circle/TestModels.cmake
circle-mlir/circle-mlir/tools/onnx2circle/test.lst
circle-mlir/models/mlir/Logistics_F32_R4_db.circle.mlir

This will enable dynamic_batch_to_single_batch option validation test with Logistics_F32_R4_db.circle.mlir model.

[circle-mir] Enable dynamic_batch_to_single_batch test

---

circle-mlir/circle-mlir/lib/dialect/mlir/CircleOps.td

This will fix deprecated warnings from generated codes from td file,
that was missed in previous change.

[circle-mlir/dialect] Fix deprecated warnings for td file

---

.github/workflows/run-circle-mlir-build.yml

This updates the container name of `nnfw/circle-mlir-build` to use the revised image.

[github] Revise container name for run-circle-mlir-build workflow

---

circle-mlir/circle-mlir/lib/dialect/src/CircleDialect.cpp

This resolves the compiler warning related to the deprecated usage of absl::HexStringToBytes().

[circle-mlir/dialect] Fix deprecation warning for absl

---

.github/workflows/build-docker-onnx-subgr.yml

This updates the DockerHub repository name to use the Ubuntu distro as the tag.

[github] Revise workflow for building Docker onnx subgraph

---

.github/workflows/run-tools-onnx-subgr-build.yml

This updates the workflow to use the revised DockerHub repository name,
which includes the Ubuntu distro as the image tag.

[github] Revise workflow for running tools-onnx-subgraph

---

compiler/one-cmds/tests/one-quantize_009.qconf.json
compiler/one-cmds/tests/one-quantize_012.qconf.json
compiler/one-cmds/tests/one-quantize_013.qconf.json

This will fix test qconf alternate to be array.

[one-cmds] Fix test qconf alternate

---

compiler/fm-equalize-value-py-test/CMakeLists.txt

This will temporary disable fm-equalize-value-py-test module.

[fm-eq-val-py-test] Temporary disable

---

runtime/onert/core/src/compiler/ExecutorFactory.cc

This commit add binding internal tensor with I/O Tensors in `ExecutorFactory`.
- Add `bindInternalOutputTensors()` to attach backend-allocated tensors to IOTensors
- Assert that internal I/O indexes only refer to graph outputs
- Bind internal output tensor with IOTensor in both linear and dataflow executors
---
For #15342 
Draft #15455

[onert] Bind internal I/O tensors

---

compiler/one-cmds/one-prepare-venv

This will tidy one-prepare-venv with Ubuntu18.04 python3.8 support.

[one-cmds] Tidy python3.8 support

---

runtime/onert/api/python/package/common/basesession.py
runtime/onert/api/python/package/infer/session.py
runtime/onert/api/python/src/bindings/nnfw_session_bindings.cc
runtime/onert/api/python/src/wrapper/nnfw_api_wrapper.cc
runtime/onert/sample/minimal-python/inference_benchmark.py

This commit refactors output handling.
- Remove set_output and set_output_layout from Python bindings and wrapper
- Refactor output buffer allocation to use get_output directly
- Add output shape sync logic when input shape changes
- Separate input/output timing metrics in benchmark script
---
For #15342 
Draft #15455

[onert/python] Revisit output handling

---

runtime/onert/core/src/compiler/ExecutorFactory.cc
runtime/onert/core/src/exec/Execution.cc
runtime/onert/core/src/exec/ExecutorBase.cc
runtime/tests/nnfw_api/src/GenModelTests/ModelTestDynamicTensor.test.cc

This commit adds get_output tests.
- Use setBackendTensor for internal outputs
- Warn if API buffer is set when using internal allocation
- Update asserts for backend tensor usage
- Add tests for dynamic output buffer cases
---
For #15342 
Draft #15455

[onert] Add get_output tests

---

compiler/luci/pass/src/SubstituteTransposeToReshapePass.cpp
compiler/luci/pass/src/SubstituteTransposeToReshapePass.test.cpp

This copies qparam in SubstituteTransposeToReshapePass.

[luci/pass] Copy qparam in SubstituteTransposeToReshapePass

---

runtime/onert/core/src/exec/Execution.cc
runtime/onert/core/src/exec/MultiModelExecutors.cc
runtime/onert/core/src/exec/SingleModelExecutors.cc

This commit adds dynamic casting null check for output tensors.

[onert] Check null on output tensor dynamic casting

---

compiler/one-cmds/tests/one-quantize_020.test

This disables the one-quantize_020 test.
---
Related to: https://github.com/Samsung/ONE/issues/15625

[one-cmds] Disable one-quantize_020 test

---

compiler/one-cmds/one-import-onnx

This will revise one-import-onnx to turn off sanitize and remap-io for I/O names.

[one-cmds] Revise one-import-onnx

---

runtime/onert/core/src/util/MDTableEventWriter.cc

This commit adds default value to Operation struct in MDTableEventWriter.

[onert] Set default value to Operation struct

---

docs/howto/how-to-build-runtime-using-prebuilt-docker-image.md
docs/howto/how-to-cross-build-runtime-for-aarch64.md
docs/howto/how-to-cross-build-runtime-for-arm.md

This commit updates documents to remove supporting information for Ubuntu 20.04.

[docs/onert] Update ubuntu support version

---

.github/workflows/run-circle-mlir-build.yml

This will revise to enter virtual-env in run-circle-mlir-build for each step. And adjust Python3_ROOT_DIR to virtual-env bin.

[github] Enter venv in run-circle-mlir-build

---

.github/workflows/run-onecc-build.yml

This will revise run-onecc-build workflow to check noble too.

[github] Enable noble for run-onecc-build

---

runtime/infra/cmake/packages/Pybind11Config.cmake
runtime/onert/api/python/CMakeLists.txt

This commit updates python API cmake to support native build on manylinux. 
To support manylinux on native build, it divides pybind11 usage for native build to find pybind11 directly without custom python searching.

[onert/python] Support manylinux build

---

compiler/one-cmds/one-prepare-venv

This commit uses official version of tico.

[one-cmds] Use official version tico

---

.github/workflows/run-onecc-build.yml

This will exclude debug build in run-onecc-build Workflow.
This is to reduce runner resource.
Internal CI runs all combinations so exclusion here is OK.

[github] Exclude debug build in run-onecc-build

---

infra/debian/compiler/one-compiler.install

This commit install one-import-pytorch to one-compiler.

[infra] Install one-import-pytorch

---

.github/workflows/run-onecc-build.yml

This commit fixes run-onecc-build.yml
- SC2046: Quote this to prevent word splitting
- SC2086: Double quote to prevent globbing and word splitting

[github] Fix run-onecc-build.yml

---

.github/workflows/run-onert-micro-unit-tests.yml

This commit fixes run-onert-micro-unit-tests.yml
- SC2046: Quote this to prevent word splitting
---
Draft: #15699

[github] Fix run-onert-micro-unit-tests.yml

---

.github/workflows/pub-onnx2circle-launchpad.yml

This commit fixes pub-onnx2circle-launchpad.yml
- SC2086: Double quote to prevent globbing and word splitting
- SC2129: Consider using `{ cmd1; cmd2; } >> file` instead of individual redirects
---
Draft: #15699

[github] Fix pub-onnx2circle-launchpad.yml

---

.github/workflows/generate-rootfs.yml

This commit fixes generate-rootfs.yml
- SC2046: Quote this to prevent word splitting
---
Draft: https://github.com/Samsung/ONE/pull/15699

[infra] Fix generate-rootfs.yml

---

compiler/one-cmds/CMakeLists.txt
compiler/one-cmds/tests/one-import-pytorch_001.test
compiler/one-cmds/tests/prepare_test_materials.sh

This commit adds a simple test for one-import-pytorch.
Related: #15406

[one-cmds] Add one-import-pytorch test

---

.github/workflows/run-onert-cross-build.yml

This commit changes the cross build docker image name. 
Docker image for cross build is removed, and use same docker image as normal build.

[github] Change cross build docker image name

---

docs/howto/how-to-build-compiler.md

This will update how-to-build-compiler with python3 version installation.

[docs] Update how-to-build-compiler with python3 ver

---

runtime/onert/core/include/ir/operation/FullyConnected.h
runtime/onert/core/include/util/ShapeInference.h
runtime/onert/core/src/compiler/StaticShapeInferer.cc
runtime/onert/core/src/exec/DynamicShapeInferer.cc
runtime/onert/core/src/loader/BaseLoader.h
runtime/onert/core/src/util/ShapeInference.cc
runtime/onert/core/src/util/ShapeInference.test.cc
runtime/tests/nnapi/bridge/wrapper/OperationFactory.cc

This commit updates shape inference for FullyConnected operation with keep_num_dim option.
---
Draft: #15704

[onert] Support FullyConnected shape inference with keep_num_dim

---

docs/conf.py
packaging/nnfw.spec
runtime/contrib/android/api/build.gradle
runtime/onert/api/nnfw/include/nnfw_version.h

This commit bumps up onert version to 1.31.0.

[onert] Bump up to 1.31.0

---

circle-mlir/circle-mlir/lib/dialect/mlir/CircleOps.td
circle-mlir/circle-mlir/lib/dialect/src/ops/SplitOp.h

This will introduce SplitOp::fold() to enable folding of SplitOp.

[circle-mlir/dialect] Introduce SplitOp::fold

---

.github/workflows/pub-onert-pypi.yml

This commit fixes build fail by tagging onert python nightly package.

[github] Fix onert python package tagging

---

.github/workflows/pub-onert-pypi.yml

This commit updates python packaging workflow to publish onert python package to pypi.

[github] Publish onert python package

---

.github/workflows/pub-onert-pypi.yml

This commit allows to upload dev package to pypi if workflow is not triggered by PR.

[github] Upload dev package to pypi

---

.github/workflows/pub-onert-pypi.yml

This commit updates input description for the pypi official release.

[github] Update pypi official release input description

---

docs/howto/how-to-use-onert-python-api.md
runtime/infra/python/README.md

This commit updates documentations for onert python package
- Move python usage from packging documentation to howto
- Rename howto documention to how-to-user-onert-python-api.md
- Update package information

[doc/onert] Update python package documentation

---

compiler/luci/lang/CMakeLists.txt

This commit remove install header file name pattern. 
This pattern excludes `CircleNodes.lst` file, but it is used in other header files.

[luci/lang] Remove install header pattern

---

runtime/infra/python/setup.py

This commit bumps up python onert to 0.2.0 as dev version.

[onert/python] Bump up python onert to 0.2.0

---

.github/workflows/pub-onert-pypi.yml

This commit updates onert python packaging to use workflow branch selection. 
By this, we don't need to get input for build commit. 
And it includes changes to allow official release on release branch only.

[github/onert] Use workflow branch selection for onert python packaging

---

runtime/onert/core/include/ir/Layout.h
runtime/onert/core/src/backend/builtin/KernelGenerator.cc
runtime/onert/core/src/backend/builtin/kernel/PermuteLayer.cc
runtime/onert/core/src/backend/builtin/kernel/PermuteLayer.h
runtime/onert/core/src/backend/builtin/kernel/WhileLayer.cc
runtime/onert/core/src/backend/builtin/train/KernelGenerator.cc
runtime/onert/core/src/exec/IPermuteFunction.cc
runtime/onert/core/src/exec/IPermuteFunction.h
runtime/onert/core/src/exec/IPermuteFunction.test.cc
runtime/onert/core/src/exec/MultiModelExecutors.cc
runtime/onert/core/src/exec/SingleModelExecutors.cc
runtime/onert/core/src/ir/Coordinates.cc
runtime/onert/core/src/ir/Shape.cc

This commit renames PermuteType::COPY to PermuteType::SAME because it can include type conversion.
---
Draft: #13679

[onert] Rename permute type for same layout

---

circle-mlir/circle-mlir/lib/dialect/src/ops/SplitOp.h

This will implement splitFPTensor method with reference code from TensorFlow lite kernel.

[circle-mlir/dialect] Implement splitFPTensor method

---

circle-mlir/circle-mlir/tools-test/onnx2circle-rewrite-test/CMakeLists.txt
circle-mlir/circle-mlir/tools-test/onnx2circle-rewrite-test/check_circle_ops.py

This will revise onnx2circle-rewrite-test to include also models in 'unit' folder.

[circle-mlir/tools-test] Revise rewrite-test module path

---

circle-mlir/models/mlir/ConstSplitAdd_F32_d0.circle.mlir
circle-mlir/models/mlir/ConstSplitAdd_F32_d1.circle.mlir
circle-mlir/models/mlir/ConstSplitAdd_F32_d2.circle.mlir
circle-mlir/models/mlir/ConstSplitAdd_F32_d3.circle.mlir

This will introduce ConstSplitAdd_F32_d? circle mlir files for Split::fold validation.

[circle-mlir/models] Introduce ConstSplitAdd_F32_d?

---

circle-mlir/circle-mlir/tools-test/onnx2circle-rewrite-test/test.lst

This will enable test for Conv2D with group that converts to
Split-[Conv2D]-Concat-Add works as expected.

[circle-mlir/tools-test] Test for Conv2d_F32_R4_g4

---

runtime/onert/core/include/compiler/CompilerOptions.h

This commit adds input & output data type and layout information map in CompilerOptions to prepare permutation operation on compile phase.
---
Related issue: #13645
Draft: #13679

[onert] Add CompilerOptions field for I/O information

---

runtime/onert/api/nnfw/src/nnfw_session.cc
runtime/onert/core/include/util/logging.h
runtime/tests/tools/onert_run/src/onert_run.cc
runtime/tests/tools/onert_train/src/onert_train.cc
runtime/tests/tools/tflite_comparator/src/tflite_comparator.cc

This commit updates nnfw_set_config internal API to support ONERT_LOG_ENABLE and NUM_THREADS. 
It helps to test release onert through test drivers on tizen.

[onert] Support logging and threads setting from driver

---

packaging/nnfw.spec

This commit updates cmake option on test build to use same core build option with normal build.

[infra/gbs] Use same onert core on test build

---

compiler/one-cmds/onelib/constant.py

This will add options that exist in circle2circle but got missed somehow.

[one-cmds] Add missed options

---

runtime/onert/backend/cpu/SharedMemoryOperands.test.cc
runtime/onert/core/include/ir/operation/Permute.h
runtime/onert/core/src/compiler/pass/ConstantOutputPass.cc
runtime/onert/core/src/compiler/pass/OddOutputPass.cc
runtime/onert/core/src/compiler/pass/PermutationInsertionPass.cc
runtime/onert/core/src/ir/operation/Permute.cc
runtime/onert/core/src/ir/train/operation/Permute.cc
runtime/onert/core/src/ir/train/operation/UntrainableOperation.test.cc

This commit adds permute type to Permute IR.
Compile optimization and backend will use this type to decide optimization and kernel selection.
---
Draft: #13679
Related issue: #13645

[onert] Add permute type to Permute IR

---

runtime/onert/core/src/backend/builtin/KernelGenerator.cc
runtime/onert/core/src/backend/builtin/KernelGenerator.h
runtime/onert/core/src/backend/builtin/kernel/CallLayer.cc
runtime/onert/core/src/backend/builtin/kernel/CallLayer.h

This commit introduces Call operator builtin backend kernel.
---
Draft: https://github.com/Samsung/ONE/pull/15704
Related issue: https://github.com/Samsung/ONE/issues/15655

[onert] Support Call operator in builtin backend

---

runtime/onert/core/src/loader/BaseLoader.h
runtime/onert/core/src/loader/CircleLoader.cc

This commit updates BaseLoader to load Call operator.
---
Draft: https://github.com/Samsung/ONE/pull/15704
Related issue: https://github.com/Samsung/ONE/issues/15655

[onert] Load Call operator

---

.github/workflows/build-pub-dev-docker.yml

This commit removes ubuntu 20.04 aarch64 docker publish test in build-pub-dev-docker.yml.

[github] Remove ubuntu 20.04 aarch64 docker publish test

---

nnpackage/schema/circle_schema.fbs

This commit adds comments about GGML data type usage and quantization parameter placement.
---
Discussion about spec: #13743

[schema] Add comment for GGML data type

---

runtime/tests/nnfw_api/lib/CircleGen.cc
runtime/tests/nnfw_api/lib/CircleGen.h
runtime/tests/nnfw_api/src/GenModelTests/one_op_tests/Call.test.cc

This commit adds one-op test for Call operator.
---
Draft: https://github.com/Samsung/ONE/pull/15704
Related issue: https://github.com/Samsung/ONE/issues/15655

[onert] Add one-op test for Call

---

.github/workflows/build-pub-dev-docker.yml

This commit fixes a bug setting build platform on image publish workflow.

[github] Fix docker image build platform on publish workflow

---

runtime/onert/core/src/compiler/MultiModelCompiler.cc
runtime/onert/core/src/compiler/MultiModelCompiler.h

This commit implements to use compile options for each model in MultiModelCompiler.
---
Draft: https://github.com/Samsung/ONE/pull/13679

[onert] Set compile option for each model in MultiModelCompiler

---

Makefile.template
packaging/nnfw.spec

This commit removes needless compiler header copy.

[infra] Remove needless compiler header copy

---

runtime/infra/debian/rules

This commit adds missing `\` to the `rules` file for onert debian packaging.

[infra/onert] Fix debian packaging bug

---

runtime/onert/api/nnfw/include/nnfw_experimental.h
runtime/onert/api/nnfw/src/nnfw_api.cc
runtime/onert/api/nnfw/src/nnfw_session.cc
runtime/onert/api/nnfw/src/nnfw_session.h

This commit introduces set input & output type experimental API to support passing float data to quantized model.
New APIs should be called before preparing.
---
Draft: https://github.com/Samsung/ONE/pull/13679
Related issue: https://github.com/Samsung/ONE/issues/13645

[onert] Introduce set input & output type API

---

runtime/onert/core/src/ir/OperationDumper.cc

This commit updates dumper to print permute layout type.
---
Related issue: #13679

[onert] Dump permute type

---

runtime/infra/debian/.gitignore

This commit adds .gitignore file into onert debian directory. 
It will be useful to use symlink to debian directory in root directory.

[infra/onert] Add git ignore file to debian directory

---

infra/command/format

This commit removes deprecated format options and related variables.

[infra/command] Remove deprecated format option

---

runtime/onert/core/src/loader/BaseLoader.h

This commit updates loader to support DynamicUpdateSlice.
---
Related issue: https://github.com/Samsung/ONE/issues/15808
Draft: https://github.com/Samsung/ONE/pull/15818

[onert] Support DynamicUpdateSlice in loader

---

infra/command/format

This commit changes the usage of pushd and popd in the format command
- Remove indirect usage for pushd and popd
- Replace pushd to cd
- Replace popd to 'cd -'
- Exit if 'cd' fails

[infra/command] Change pushd & popd usage to cd

---

infra/command/format

This commit simplifies string comparator in format checker.

[infra/command] Simplify string comparator

---

infra/command/format

This commit converts FILES_TO_CHECK and related variables to arrays. 
It includes fixing potential issues with spaces in filenames by properly using array syntax.

[infra/command] File handling to use arrays instead of strings

---

runtime/onert/api/nnfw/src/nnfw_session.cc
runtime/tests/nnfw_api/src/RegressionTests.test.cc

This commit supports scalar shape in nnfw_set_inputinfo API.
---
Related issue: #15836

[onert] Support scalar shape input setting

---

runtime/onert/api/nnfw/include/nnfw_experimental.h
runtime/onert/api/nnfw/src/nnfw_session.cc

This commit updates auto compilation API implementation to use PermutationIOPass compile option internally. 
This commit includes updating API comment for user understanding. 
This update is tested on unittest: OdcAutoCompilation.test.cc
---
Related issue: https://github.com/Samsung/ONE/issues/13645
Draft: https://github.com/Samsung/ONE/pull/13679

[onert] Use PermutationIOPass on auto compilation

---

infra/command/format

This commit updates the git branch detection command by using a more precise regex pattern ('^\*').

[infra/command] Fix git branch detection

---

.gitattributes
infra/command/format

This commit revisits the end-of-file check in format checker
- Rename function name to check_endoffile
- Sort and remove redundant binary extension list
- Add circle extension in binary list
- Simplify the logic of checking end-of-file

[infra/command] Revisits end-of-file check

---

runtime/onert/api/nnfw/src/nnfw_session.cc
runtime/onert/core/include/exec/Execution.h
runtime/onert/core/src/exec/Execution.cc
runtime/tests/custom_op/FillFrom/FillFrom_runner.cc
runtime/tests/tools/onert_run/src/onert_run.cc
runtime/tests/tools/onert_train/src/h5formatter.cc
runtime/tests/tools/onert_train/src/randomgen.cc
runtime/tests/tools/onert_train/src/rawformatter.cc

This commit updates API implementation to set I/O layout before prepare, not before inference.
---
Related issue: https://github.com/Samsung/ONE/issues/13645
Draft: https://github.com/Samsung/ONE/pull/13679

[onert] Set I/O layout before prepare

---

onert-micro/onert-micro/src/execute/kernels/Mean.cpp
onert-micro/onert-micro/src/execute/kernels/ReduceProd.cpp
onert-micro/onert-micro/src/execute/kernels/Sum.cpp

Fixes unused return value for Reduce type operations.
This bug makes tests fail in Debug mode.
ONE-DCO-1.0-Signed-off-by: Denis Tarasenko <monoamind@outlook.com>

[onert-micro/onert-micro] Fix tests (Mean/ReduceProd/Sum)

---

runtime/tests/tools/onert_run/src/onert_run.cc

This commit changes read environment value to const variable.
It includes checking TRACING_MODE environment variable value.
---
For https://github.com/Samsung/ONE/pull/15857#discussion_r2250699493

[onert_run] Handle environment value to const

---

runtime/onert/core/src/backend/builtin/KernelGenerator.cc
runtime/onert/core/src/backend/builtin/train/KernelGenerator.cc

This commit updates builtin KernelGenerator to use permute node type. 
KernelGenerator's input, output, type vector has only one element becasue permute node has only one input, output, and type.
---
Draft: #13679

[onert] Use permute node type in KernelGenerator

---

.github/workflows/pub-onert-pypi.yml

This commit updates PyPI publish workflow to add PR test triggering path for python packaging files.

[github] Update PyPI publish workflow to test setup.py

---

runtime/tests/nnfw_api/lib/GenModelTest.h
runtime/tests/nnfw_api/src/GenModelTests/one_op_tests/DepthwiseConv2D.test.cc

This commit adds `allow_small_error` to context to allow error 1 from different backend kernel implementation.

[onert/test] Support small error tolerance in integer comparison

---

runtime/infra/cmake/packages/ARMComputeSourceConfig.cmake

This commit updates ARM Compute Library version to v52.3.0.

[infra/onert] Update ARM Compute Library version to v52.3.0

---

runtime/onert/core/src/compiler/Compiler.cc
runtime/onert/core/src/compiler/Compiler.h
runtime/onert/core/src/exec/Execution.test.cc

This commit removes Compiler class constructor from direct Model and use NNPkg instead. 
Compiler class owns NNPkg and uses it to get Model.
---
Draft: #15872

[onert] Use NNPkg in single model compiler

---

runtime/tests/nnfw_api/src/GenModelTests/one_op_tests/DepthwiseConv2D.test.cc

This commit allows small error in acl-cl backend test compared to expected value in DepthwiseConv2D int8 quantized test.

[onert] Allow small error in DepthwiseConv2D test

---

runtime/onert/backend/acl_cl/KernelGenerator.cc
runtime/onert/backend/acl_common/AclTensorBuilder.h
runtime/onert/backend/acl_neon/KernelGenerator.cc
runtime/onert/core/include/backend/basic/Tensor.h
runtime/onert/core/src/backend/builtin/IOTensor.h
runtime/onert/core/src/compiler/train/pass/TrainableConstantInsertionPass.cc

This commit removes outdated comment about backend layout.

[onert] Remove outdated comment about layout

---

runtime/onert/core/src/compiler/StaticShapeInferer.cc
runtime/onert/core/src/exec/DynamicShapeInferer.cc

This commit updates static and dynamic shape inference for Permute operation. 
Backend layout feature is removed and permute operation has its own type to represent permutation type, so shape inferer can calculate and decide output shape.

[onert] Implement shape inference for Permute

---

runtime/onert/api/nnfw/src/nnfw_session.cc
runtime/onert/api/nnfw/src/nnfw_session.h
runtime/onert/core/include/compiler/CompilerFactory.h
runtime/onert/core/src/compiler/Compiler.cc
runtime/onert/core/src/compiler/Compiler.h
runtime/onert/core/src/compiler/CompilerFactory.cc
runtime/onert/core/src/compiler/MultiModelCompiler.cc
runtime/onert/core/src/compiler/MultiModelCompiler.h
runtime/onert/core/src/compiler/train/TrainingCompiler.cc
runtime/onert/core/src/compiler/train/TrainingCompiler.h
runtime/onert/core/src/exec/Execution.test.cc
runtime/tests/nnapi/bridge/wrapper/ANeuralNetworksCompilation.cc

This commit refactors NNPkg from shared_ptr to unique_ptr and transfer ownership of NNPkg from session to compiler.

[onert] Refactor NNPkg ownership to use unique_ptr in compiler workflow

---

runtime/onert/core/src/compiler/MultiModelCompiler.cc

This commit enables profiling for multimodel package.

[onert] Enable multimodel profile

---

runtime/onert/api/nnfw/src/nnfw_session.h
runtime/onert/core/include/compiler/ICompiler.h
runtime/onert/core/src/compiler/Compiler.cc
runtime/onert/core/src/compiler/Compiler.h
runtime/onert/core/src/compiler/train/TrainingCompiler.cc
runtime/onert/core/src/compiler/train/TrainingCompiler.h

This commit changes ownership management of CompilerArtifact from share_ptr to unique_ptr.

[onert] Use unique_ptr to manage CompilerArtifact

---

runtime/onert/core/src/compiler/Compiler.cc
runtime/onert/core/src/exec/MultiModelExecutors.cc
runtime/onert/core/src/exec/MultiModelExecutors.h

This commit updates Compiler to handle type-aware quantization for edge by setting input data type info in compile option for each model. 
It includes removing type-aware quantization layer and tensor in MultiModelExecutors.

[onert] Handle type-aware quantization for edge on Compiler

---

runtime/onert/api/nnfw/include/nnfw.h

This commit updates API comment about deprecated nnfw_apply_tensorinfo to use nnfw_set_input_tensorinfo instead.

[onert] Fix API comment for nnfw_set_input_tensorinfo

---

circle-mlir/circle-mlir/lib/dialect/src/ops/SplitOp.h

This will fix more unsafe type conversion in SplitOp.

[circle-mlir/dialect] Fix unsafe type conversion

---

runtime/onert/api/nnfw/src/nnfw_session.cc
runtime/onert/core/include/exec/Execution.h

This commit fixes input tensor info getter API implementation to return updated tensor info by `set_input_tensorinfo` after `nnfw_prepare` called.

[onert] Fix input tensor info getter API to return updated tensor info

---

compiler/luci-interpreter/src/kernels/UnidirectionalSequenceLSTM.cpp

This commit removes a #pragma statement from kernels/UnidirectionalSequenceLSTM.cpp
This pragma used to guard the build from warnings coming from the TF but the build now works fine on newer GCC versions with strict build enabled.
Additionally this pragma was never disabled (not scoped) with a #pragma pop statement which effectively ignored this warning for the rest of the project after this particular file was compiled.
ONE-DCO-1.0-Signed-off-by: Tomasz Dołbniak <t.dolbniak@partner.samsung.com>

[luci-interpreter] Remove unnecessary pragma

---

runtime/onert/api/nnfw/src/nnfw_session.cc
runtime/onert/core/include/exec/Execution.h
runtime/onert/core/include/exec/ExecutionContext.h
runtime/onert/core/include/exec/IExecutors.h
runtime/onert/core/src/exec/Execution.cc
runtime/onert/core/src/exec/Execution.test.cc
runtime/onert/core/src/exec/MultiModelExecutors.cc
runtime/onert/core/src/exec/MultiModelExecutors.h
runtime/onert/core/src/exec/SingleModelExecutors.cc
runtime/onert/core/src/exec/SingleModelExecutors.h
runtime/onert/core/src/exec/train/TrainableExecutors.cc
runtime/onert/core/src/exec/train/TrainableExecutors.h
runtime/tests/nnapi/bridge/wrapper/ANeuralNetworksExecution.cc

This commit cleans up Execution API
- Add API to access I/O info
- Remove APIs which can be handled by new API
- Remove setInput/setOutput API used for NNAPI only
- Change IExecutors context paramter as inout and remove const to return shape inference result
- Change IODescription vector element type: use raw type instead of unique_ptr for simple copy

[onert] Clean up Execution API

---

infra/cmake/packages/ProtobufConfig.cmake
infra/cmake/packages/ProtobufSourceConfig.cmake

This commit updates the Protobuf library to a newer version due to the fixes this version contains.
In particular this version contains a fix for a linker error: 
```/usr/bin/ld: libtriv2_lib_manifest.a(Manifest.pb.cc.o): in function google::protobuf::MessageLite::~MessageLite()': /__w/NPU_Compiler/NPU_Compiler/build/overlay/include/google/protobuf/message_lite.h:171: undefined reference to google::protobuf::internal::InternalMetadata::~InternalMetadata()'```
ONE-DCO-1.0-Signed-off-by: Tomasz Dołbniak <t.dolbniak@partner.samsung.com>

[infra] Update Protobuf to 3.21.12

---

onert-micro/onert-micro/include/execute/OMTestUtils.h

This PR fixes failed in `Debug` mode tests to fail in `Release` mode as well.
I may be wrong, but there is inconsistency in tests:
currently it's possible to have successful tests in `Release`, but failed in `Debug`.
This PR fixes this possibility

[onert-micro] Fix incompatibility in tests.

---

compiler/luci/pass/include/luci/CircleOptimizer.h
compiler/luci/pass/include/luci/Pass/FuseMulWithRmsNormPass.h
compiler/luci/pass/src/CircleOptimizer.cpp
compiler/luci/pass/src/FuseMulWithRmsNormPass.cpp
compiler/luci/pass/src/FuseMulWithRmsNormPass.test.cpp

This commit adds a pass for fusing Mul with preceding RmsNorm.
issue https://github.com/Samsung/ONE/issues/15891
draft https://github.com/Samsung/ONE/pull/15930

[luci/pass] Added pass 'FuseMulWithRmsNorm'

---

runtime/onert/core/src/exec/Execution.test.cc
runtime/onert/core/src/exec/MultiModelExecutors.cc

This commit supports internal output allocation on MultiModelExecutors.
This commit includes two multimodel shape inference tests and update to pass tests
- External output buffer (default)
- Internal output buffer allocation
---
Draft: #15928

[onert] Support internal output allocation on MultiModelExecutors

---

res/TensorFlowLiteRecipes/Net_RmsNorm_001/test.recipe
res/TensorFlowLiteRecipes/Net_RmsNorm_001/test.rule

This commit adds recipe to test fusing Mul with preceding RmsNorm.
issue: https://github.com/Samsung/ONE/issues/15891
draft: https://github.com/Samsung/ONE/pull/15930

[res] Recipe added to test fusing Mul with RmsNorm

---

infra/command/gen-coverage-report

This commit adds `--ignore-errors` options to skip error message by lcov bug or acceptable condition.

[infra/command] Add ignore-error condition in lcov report

---

nnpackage/schema/circle_schema.fbs

This commit introduces RUN_MODEL operator and RunModelOptions parameter table.
---
Draft: #15704
Related issue: #15676

[nnpackage/circle] Introduce RUN_MODEL operator

---

runtime/libs/circle-schema/include/circle_schema_generated.h
runtime/onert/core/src/loader/CircleLoader.cc

This commit supports builtin RUN_MODEL operator in CircleLoader. 
It includes removing RUN_MODEL custom OP support.
---
Draft: #15704
Related issue: https://github.com/Samsung/ONE/issues/15676

[onert] Support builtin RUN_MODEL operator

---

runtime/onert/api/nnfw/src/nnfw_session.cc
runtime/onert/core/include/exec/Execution.h

This commit adds methods to access execution I/O size and output buffer. 
It removes access executors directly in nnfw session implementation except Execution constructor.
---
Draft: #15929

[onert] Access execution I/O size and buffer

---

runtime/onert/api/nnfw/src/nnfw_session.cc
runtime/onert/core/include/exec/Execution.h
runtime/onert/core/include/ir/NNPkg.h
runtime/onert/core/src/compiler/Compiler.cc
runtime/onert/core/src/exec/Execution.test.cc
runtime/tests/nnapi/bridge/wrapper/ANeuralNetworksExecution.cc

This commit replaces raw integer indices with IOIndex type when accessing input/output information in Execution and NNPkg classes.
---
Related issue: https://github.com/Samsung/ONE/pull/15940#discussion_r2299568881

[onert] Use IOIndex type for input/output indices

---

runtime/onert/core/include/ir/Model.h
runtime/onert/core/src/loader/BaseLoader.h

This commit supports loading SignatureDef map from circle/tflite model.
---
Draft: #15929
Related issue: #15369

[onert] Load SignatureDef map

---

runtime/onert/core/include/exec/IExecutors.h
runtime/onert/core/src/exec/SignatureExecutors.cc
runtime/onert/core/src/exec/SignatureExecutors.h
runtime/onert/core/src/exec/train/TrainableExecutors.h

- Introduce SignatureExecutors class to start from a specified subgraph index instead of default (0)
- Make IExecutors::entryExecutor() virtual to allow overriding
---
Draft: #15929
Related issue: #15369

[onert] Introduce SignatureExecutors class

---

runtime/onert/api/nnfw/src/nnfw_api.cc
runtime/onert/api/nnfw/src/nnfw_session.cc
runtime/onert/api/nnfw/src/nnfw_session.h

This commit adds signature setting API skeleton in nnfw_session and uses it in API implementation. 
The functions include parameter validation and state checking, but return NYI errors as the implementation is not complete yet.
---
Draft: https://github.com/Samsung/ONE/pull/15929
Related issue: https://github.com/Samsung/ONE/issues/15369

[onert] Add signature setting API to nnfw_session

---

runtime/onert/core/src/ir/OperationValidator.cc

This commit updates OperationValidator::isSameQuantParam to compare channelwise quantization parameters.

[onert] Compare channelwise quantization in OperationValidator

---

runtime/onert/api/nnfw/src/nnfw_session.cc
runtime/onert/api/nnfw/src/nnfw_session.h
runtime/onert/core/include/ir/NNPkg.h

This commit implements signature selection and related input/output getter/setter APIs.
---
Draft: https://github.com/Samsung/ONE/pull/15929
Related issue: https://github.com/Samsung/ONE/issues/15369

[onert] Implement signature selection support for prepare

---

runtime/onert/backend/acl_common/Convert.cc
runtime/tests/nnfw_api/src/GenModelTests/one_op_tests/Add.test.cc

This commit adds conversion for ACL's QSYMM16 data type to runtime's QUANT_INT16_SYMM. 
This commit includes update Add test case to use INT16 and expect success instead of failure.

[onert] Add QSYMM16 data type conversion support to ACL backend

---

onert-micro/onert-micro/src/execute/kernels/Tanh.cpp

This commit fixes missing `default` branch for `Tanh` kernel.

[onert-micro] Fix for Tanh

---

runtime/infra/cmake/CfgOptionFlags.cmake
runtime/infra/cmake/options/options_x86_64-linux.cmake
runtime/onert/backend/trix/CMakeLists.txt
runtime/onert/backend/trix/DevContext.cc

This commit replaces hardcoded TRIX request timeout with configurable build option.
---
Related issue: #15961

[onert] Make TRIX request timeout configurable

---

Makefile.template
docs/howto/how-to-cross-build-runtime-for-android.md
infra/docker/android-sdk/Dockerfile
runtime/infra/cmake/buildtool/cross/toolchain_aarch64-android.cmake

This commit is transition from custom NDK_DIR to standard CMAKE_ANDROID_NDK or ANDROID_NDK variable for Android builds. 
It updates Makefile.template, documentation, docker environment variables, and toolchain configuration.

[infra/onert] Update Android NDK configuration for cross-compilation

---

runtime/onert/core/include/backend/basic/Allocator.h
runtime/onert/core/include/util/Set.h

This commit fixes an `'uint32_t' does not name a type` errors emitted by `gcc-15` for the `Allocator.h` and `Set.h` header files
this PR fix same issue as https://github.com/Samsung/ONE/pull/15967, but in different header files
```
(...)/runtime/onert/core/include/backend/basic/Allocator.h:42:3: error: 'uint8_t' does not name a type
42 |   uint8_t *base() const { return _base.get(); }
|   ^~~~~~~
(...)/runtime/onert/core/include/backend/basic/Allocator.h:27:1: note: 'uint8_t' is defined in header '<cstdint>'; this is probably fixable by adding '#include <cstdint>'
(...)/runtime/onert/core/include/util/Set.h:81:3: error: 'uint32_t' does not name a type [-Wtemplate-body]
81 |   uint32_t size() const { return static_cast<uint32_t>(_set.size()); }
|   ^~~~~~~~ …
```

[onert] Fix the errors when building with `gcc-15`

---

runtime/onert/backend/cpu/KernelGenerator.cc
runtime/onert/backend/cpu/KernelGenerator.h
runtime/onert/core/src/backend/builtin/Backend.h
runtime/onert/core/src/backend/builtin/KernelGenerator.cc
runtime/onert/core/src/backend/builtin/KernelGenerator.h
runtime/onert/core/src/compiler/CompilerOptions.cc
runtime/onert/core/src/compiler/ManualScheduler.cc

This commit changes custom operator backend from CPU to builtin backend to remove backend dependency with handling custom operator.

[onert] Change Custom OP backend to builtin

---

runtime/onert/backend/cpu/Backend.h
runtime/onert/backend/cpu/KernelGenerator.cc
runtime/onert/backend/cpu/KernelGenerator.h
runtime/onert/backend/ruy/Backend.h
runtime/onert/backend/ruy/KernelGenerator.cc
runtime/onert/backend/ruy/KernelGenerator.h

This commit removes the custom kernel builder functionality from both the CPU and Ruy backends.
---
For https://github.com/Samsung/ONE/pull/15989#discussion_r2318352101

[onert] Remove custom kernel builder from backends

---

packaging/nnfw.spec

This commit removes strip option in cmake install. 
RPM packaging process includes strip with debuginfo packaging.

[onert/gbs] Remove strip in cmake install

---

compiler/mio-circle/CMakeLists.txt
compiler/mio-circle/include/mio_circle/Helper.h
compiler/mio-circle/include/mio_circle/Reader.h
compiler/mio-circle/src/Helper.cpp
compiler/mio-circle/src/Helper.test.cpp
compiler/mio-circle/src/Reader.cpp
compiler/mio-circle/src/Reader.test.cpp

This will enable mio-circle module with schema 0.10.0.
Codes are copied from latest mio-circle08 and modified name without number 08.

[mio-circle] Enable module with schema 0.10.0

---

compiler/circle-verify/CMakeLists.txt
compiler/circle-verify/requires.cmake

[circle-verify] Use mio-circle

---

infra/cmake/modules/ExternalSourceTools.cmake

This commit updates ExternalSource_Download to include patch file information in the stamp content alongside the URL. This ensures that when a patch file changes, the external source is properly re-downloaded and re-patched, even if the URL remains the same.

[infra] Check patch in stamp content for external sources

---

runtime/infra/cmake/modules/ExternalSourceTools.cmake

This commit updates ExternalSource_Download to include patch file information in the stamp content alongside the URL. It is a copy from compiler's ExternalSource_Download.
---
Same with #16079

[infra/onert] Check patch in stamp content for external sources

---

runtime/infra/cmake/packages/TensorFlowLite/CMakeLists.txt

This commit disables unnecessary acceleration configurations and experimental delegates. It removes dependency with flatbuffers generated headers - configuration_generated.h and headers in delegates/gpu.

[infra/onert] Limit TensorFlowLite to interpreter and NNAPI delegate

---

packaging/nnfw.spec
runtime/infra/cmake/options/options_aarch64-tizen.cmake
runtime/infra/cmake/options/options_armv7hl-tizen.cmake
runtime/infra/cmake/options/options_armv7l-tizen.cmake
runtime/infra/cmake/options/options_i686-tizen.cmake
runtime/infra/cmake/options/options_riscv64-tizen.cmake
runtime/infra/cmake/options/options_x86_64-tizen.cmake

This commit removes external libraries and generated code tar files usage
- Add python3 and python3-numpy as build requirements
- Remove external source extractions for unused TFLite build

[infra/gbs] Remove source tar files usage

---

runtime/CMakeLists.txt
runtime/infra/cmake/buildtool/cross/toolchain_aarch64-android.cmake

This commit removes workaround to find package in android build
- Add NO_CMAKE_FIND_ROOT_PATH to nnfw_find_package macro to force finding packages in host path
- Remove CMAKE_FIND_ROOT_PATH_MODE_PACKAGE setting from Android toolchain

[infra/onert] Fix nnfw_find_package

---

compiler/tflchef/core/src/ModelChef.cpp

This will revise to use DimsI32_t alias for better readability.

[tflchef] Use DimsI32_t alias

---

runtime/infra/cmake/packages/GTestSourceConfig.cmake

- Update GTest URL from release-1.12.1 to v1.15.2
- Add DIRNAME parameter to ExternalSource_Download to specify directory name as GTEST-1.15.2

[infra/onert] Update GTest version and download configuration

---

compiler/oops/CMakeLists.txt

This commit adds install command to copy header files. 
This ensures that other installed libraries that depend on oops can access its public headers, maintaining completeness of their public interfaces.

[oops] Install oops header files for dependent libraries

---

compiler/locomotiv/src/ConvertIndex.cpp
compiler/locomotiv/src/ConvertIndex.h
compiler/locomotiv/src/ConvertIndex.test.cpp
compiler/locomotiv/src/Node/DepthwiseFilterEncode.cpp
compiler/locomotiv/src/Node/FeatureDecode.cpp
compiler/locomotiv/src/Node/FeatureEncode.cpp
compiler/locomotiv/src/Node/FilterEncode.cpp
compiler/locomotiv/src/Node/MatrixDecode.cpp
compiler/locomotiv/src/Node/MatrixEncode.cpp

This commit Introduces functions to convert between loco::TensorIndex and nncc::core::ADT::tensor::Index types. Conversion is implicitly handled because loco::TensorIndex is alias of nncc::core::ADT::tensor::Index, but explicit conversion functions are added to remove alias.
---
Draft: #16124

[locomotiv] Add conversion utilities for tensor index types

---

runtime/infra/cmake/packages/TensorFlowLite/CMakeLists.txt

This commit removes NNAPI source files population and use disabled delegate version instead. 
And it comments out FP16 include directory from TFLite build configuration.

[infra/onert] Disable NNAPI delegate and Fp16 includes in TFLite

---

.github/workflows/check-format.yml

This commit replaces Docker container usage with direct script download and execution for actionlint.

[github] Update actionlint to use direct download instead of Docker

---

runtime/tests/nnfw_api/src/RegressionTests.test.cc
runtime/tests/tools/tflite_run/src/tensor_loader.cc

This commit changes variable length raw arrays to std::vector in RegressionTests.test.cc and tensor_loader.cc to prevent potential stack overflow and improve memory safety.

[onert/test] Replace C-style arrays with std::vector

---

.github/workflows/run-onert-micro-unit-tests.yml
onert-micro/onert-micro/src/core/memory/OMRuntimeAllocator.cpp

- Enable ARM build test in CI, again
- TODO: make  ReduceMaxTest.Float_4D_2axis_P works

Add arm target build test in CI
