Samsung/ONE

compiler/tf2tfliteV2-conversion-test/CMakeLists.txt, compiler/tf2tfliteV2-conversion-test/requirements.txt, compiler/tf2tfliteV2-conversion-test/requires.cmake
This commit make this module use common-artifacts
Related : #3100
=> [tf2tfliteV2-conversion-test] Use common-artifacts

compiler/record-minmax-conversion-test/CMakeLists.txt, compiler/record-minmax-conversion-test/requirements.txt, compiler/record-minmax-conversion-test/requires.cmake, compiler/record-minmax-conversion-test/testall.sh
This commit make module use common-artifacts
Related : #3100, #2743 
=> [record-minmax-conversion-test] Use common-artifacts

compiler/pota-quantization-value-test/CMakeLists.txt, compiler/pota-quantization-value-test/requirements.txt, compiler/pota-quantization-value-test/requires.cmake, compiler/pota-quantization-value-test/test_fake_wquant.sh, compiler/pota-quantization-value-test/test_quantization.sh, compiler/pota-quantization-value-test/test_record_minmax.sh
This commit make this module use common-artifacts
Related : #3100, #2743
=> [pota-quantization-value-test] Use common-artifacts

compiler/luci-value-test/CMakeLists.txt, compiler/luci-value-test/evalverify.sh, compiler/luci-value-test/requirements.txt, compiler/luci-value-test/requires.cmake
This commit make this module use common-artifacts
Related : #3100, #2743 
=> [luci-value-test] Use common-artifacts

compiler/luci/pass/src/CircleOptimizer.cpp, compiler/luci/pass/src/CircleOptimizerUtils.cpp, compiler/luci/pass/src/CircleOptimizerUtils.h
This adds check code for quantization type and granularity
---
Related to #3016
=> [luci] Add check code for quantization

compiler/luci-interpreter/include/luci_interpreter/Interpreter.h, compiler/luci-interpreter/src/Interpreter.cpp, compiler/luci-interpreter/src/loader/GraphLoader.cpp, compiler/luci-interpreter/src/loader/GraphLoader.h, compiler/luci-interpreter/src/loader/ModuleLoader.cpp, compiler/luci-interpreter/src/loader/ModuleLoader.h
This adds getTensorData to interpreter
---
Related to #2960
=> [luci-interpreter] Add getTensorData to interpreter

docs/runtime/core.md
Add a little more one-liner description for `backend` module.
=> [docs] onert: Fix for core.md

runtime/onert/core/include/exec/FunctionSequence.h
This commit fixes no member named 'DynamicInferer'.
=> [onert] Fix no member named `DynamicInferer`

runtime/onert/core/src/compiler/OperationValidator.cc, runtime/onert/core/src/compiler/OperationValidator.h
Remove code duplication for reduce operation validator
=> [onert] Remove code duplication in OperationValidator

compiler/arser/include/arser/arser.h, compiler/arser/tests/arser.test.cpp
This commit enables arser to support exit_with api
=> [arser] Support exit_with api

docs/howto/how-to-use-nnapi-binding.md
Write "How to Use NNAPI Binding" briefly as NN API has its own
documents.
=> [docs] Write "How to Use NNAPI Binding"

compiler/luci/import/include/luci/Import/Nodes.h, compiler/luci/import/include/luci/Import/Nodes/CircleSelectV2.h, compiler/luci/import/src/GraphBuilderRegistry.cpp, compiler/luci/import/src/Nodes/CircleSelectV2.cpp
Support for SelectV2 operation in luci importer.
=> [luci/import] Add SelectV2 operation

compiler/luci-interpreter/src/kernels/DepthwiseConv2D.test.cpp
This commit update `DepthwiseConv2D` operator test case.
=> [luci-interpreter] Test quantized DepthwiseConv2D kernel for MobilenetV2

compiler/luci-interpreter/src/kernels/MaxPool2D.cpp
This commit add input tensor condition check on luci/interpreter kernel.
=> [luci/interpreter]Add assert on maxPooling2D condition check.

res/TensorFlowLiteRecipes/SelectV2_000/test.recipe, res/TensorFlowLiteRecipes/SelectV2_001/test.recipe, res/TensorFlowLiteRecipes/SelectV2_002/test.recipe
Add tflchef recipes for SelectV2 operator.
=> [res] Add recipes for SelectV2 operator

compiler/luci-interpreter/src/core/KernelParams.h, compiler/luci-interpreter/src/kernels/CMakeLists.txt, compiler/luci-interpreter/src/kernels/StridedSlice.cpp, compiler/luci-interpreter/src/kernels/StridedSlice.h, compiler/luci-interpreter/src/kernels/StridedSlice.test.cpp, compiler/luci-interpreter/src/loader/KernelBuilder.cpp, compiler/luci-interpreter/src/loader/KernelBuilder.h
This commit add `StridedSlice` operation kernels on luci-interpreter.
=> [luci-interpreter]Add StridedSlice kernels on luci-interpreter

compiler/cwrap/src/Fildes.test.cpp
This will delete temporary files generated from test
=> [cwrap] delete temporary files from test

compiler/common-artifacts/CMakeLists.txt, compiler/common-artifacts/exclude.lst, compiler/common-artifacts/requires.cmake
This commit enables common-artifacts to support circle recipe
Related: #2743
=> [common-artifacts] Support circle recipe

compiler/arser/include/arser/arser.h
This will fix type mismatch with argc
=> [arser] fix type mismatch

runtime/onert/backend/cpu/ops/MinLayer.cc, runtime/onert/backend/cpu/ops/MinLayer.h, tests/nnapi/nnapi_gtest.skip.noarch.interp, tests/nnapi/specs/V1_2/minimum_quant8_nnfw.mod.py
Add quant8 support for minimum cker
ONE-DCO-1.0-Signed-off-by: Leehansol <hansolu.lee@samsung.com>
=> [onert] Add quant8 support for minimum cker

compiler/circle2circle/src/Circle2Circle.cpp
This will revise file open error to show just message and not runtime error core dump
=> [circle2circle] Revise file open error

compiler/foder/include/foder/FileLoader.h
This will revise error message to make consistant with other drivers
=> [foder] revise error message

compiler/circlechef/requires.cmake, compiler/circlechef/tools/file/CMakeLists.txt, compiler/circlechef/tools/file/Driver.cpp, compiler/circlechef/tools/reverse/CMakeLists.txt, compiler/circlechef/tools/reverse/Driver.cpp
This commit makes circlechef use arser
Related: #3001 
=> [circlechef] Use arser

compiler/tflchef/requires.cmake, compiler/tflchef/tools/file/CMakeLists.txt, compiler/tflchef/tools/file/Driver.cpp, compiler/tflchef/tools/reverse/CMakeLists.txt, compiler/tflchef/tools/reverse/Driver.cpp
This commit makes tflchef use arser
Related: #3001 
=> [tflchef] Use arser

compiler/circle-verify/CMakeLists.txt, compiler/circle-verify/requires.cmake, compiler/circle-verify/src/Driver.cpp
This commit makes circle-verify use arser
Related: #3001 
=> [circle-verify] Use arser

runtime/onert/core/src/backend/controlflow/kernel/IfLayer.cc, runtime/onert/core/src/backend/controlflow/kernel/WhileLayer.cc
This commit some dynamic_cast to polymorphic_downcast in controlflow op's kernels
=> [onert] Change some dynamic_cast to polymorphic_downcast

runtime/onert/backend/cpu/ops/MaxLayer.cc, runtime/onert/backend/cpu/ops/MaxLayer.h, tests/nnapi/nnapi_gtest.skip.noarch.interp, tests/nnapi/specs/V1_2/maximum_quant8_nnfw.mod.py
Add quant8 support for maximum cker
ONE-DCO-1.0-Signed-off-by: Leehansol <hansolu.lee@samsung.com>
=> [onert] Add quant8 support for maximum cker

compiler/circledump/CMakeLists.txt, compiler/circledump/driver/Driver.cpp, compiler/circledump/requires.cmake
This commit makes circledump use arser
Related : #3001 
=> [circledump] Use arser

compiler/one-cmds/one-quantize
This will add min/max percentile option for record-minmax
=> [record-minmax] Apply min/max percentile option

compiler/tfldump/CMakeLists.txt, compiler/tfldump/driver/Driver.cpp, compiler/tfldump/requires.cmake
This commit makes tfldump use arser
Related : #3001 
=> [tfldump] Use arser

infra/scripts/unittest_compiler_xml.sh
- Use NNCC_WORKSPACE setting
- Add execution permission
- Test only, not configure and build
=> [infra/script] Revise unittest_compiler_xml.sh

compiler/common-artifacts/CMakeLists.txt
This commit creates python venv in overlay
Related: #2359 
=> [common-artifacts] Create python venv in overlay

docs/runtime/heterogeneous-execution.md
Fix two links that have invalid header labels
=> [docs] Fix Heterogeneous Execution links

compiler/record-minmax/driver/Driver.cpp
This commit improves error handling
Related : #3193 
=> [record-minmax] improve error handling

compiler/record-minmax/src/HDF5Importer.cpp, compiler/record-minmax/src/HDF5Importer.h, compiler/record-minmax/src/RecordMinMax.cpp
This allows to process hdf5 filled with raw data
---
Related to #3213 Draft PR #3232
=> [record-minmax] Allow to process hdf5 of raw data

res/TensorFlowPythonExamples/examples/unique/__init__.py
Parent Issue : #2568
Draft PR : #2829 
This Commit will add Unique Operation related case.
=> [res/TensorFlowPythonExamples] Add unique operation case

compiler/common-artifacts/CMakeLists.txt
This commit removes unused part that generates venv in cmake
Related : #2359 
=> [common-artifacts] Remove unused part in cmake

runtime/onert/core/include/compiler/StaticShapeInference.h, runtime/onert/core/include/ir/OpSequence.h, runtime/onert/core/src/ir/OpSequence.cc, runtime/onert/frontend/base_loader/include/base_loader.h
- Initialize StaticShapeInferer::_return_has_dynamic_tensor
- Initialize OpSequence::_has_dynamic_tensor
- Initialize BaseLoader::_fd
- Move member definition place
---
For https://github.com/Samsung/ONE/issues/1635#issuecomment-659787605
=> [onert] Initialize class members

docs/howto/how-to-remote-debugging-with-visual-studio-code.md
- Copy original contents from nnfw project
=> [docs] Update how-to-remote-debugging-with-visual-studio-code.md

runtime/onert/api/src/nnfw_api.cc, runtime/onert/api/src/nnfw_api_internal.cc, runtime/onert/api/src/nnfw_api_internal.h, tests/nnfw_api/src/ValidationTestAddSessionPrepared.cc, tests/nnfw_api/src/ValidationTestFourAddModelsSetInput.cc
- Implement `nnfw_run_async`
- Implement `nnfw_await`
- Add some test cases to `nnfw_api_gtest`
=> [onert] Implement APIs for asynchronous exeuction

compiler/imgdata2hdf5/CMakeLists.txt, compiler/imgdata2hdf5/README.md, compiler/imgdata2hdf5/imgdata2hdf5.py
This adds imdata2hdf5, a tool to convert raw image data to hdf5
---
Related to #3213 Draft PR #3232
=> [imgdata2hdf5] Tool to convert raw imgdata to hdf5

compiler/arser/include/arser/arser.h
This commit implements lexical_cast for boolean type
=> [arser] Implement lexical_cast for boolean type

runtime/onert/core/src/compiler/BackendManager.cc
Load boost backend loading - by backend library naming
=> [onert] Load boost backend

compiler/arser/include/arser/arser.h, compiler/arser/tests/arser.test.cpp
This commit introduces default_value to Argument class
=> [arser] Introduce default_value method

compiler/circle-inspect/CMakeLists.txt, compiler/circle-inspect/driver/Driver.cpp, compiler/circle-inspect/requires.cmake
This commit makes circle-inspect use arser
Related : #3001 
=> [circle-inspect] Use arser

compiler/circle-inspect/src/Dump.cpp
This commit makes circle-inspect support multiple subgraphs
Related : #3278 
=> [circle-inspect] Support multiple subgraphs

runtime/libs/misc/CMakeLists.txt, runtime/onert/backend/cpu/KernelGenerator.cc, runtime/onert/core/include/backend/CustomKernelBuilder.h
Remove remain onert core header dependency with lib/misc by custom op shape
Remove install misc header
=> [onert] Remove onert core header dependency with lib/misc

compiler/circle2circle/src/Circle2Circle.cpp
This commit revises driver to apply default_value of arser
=> [circle2cirlce] Revise driver

compiler/tflite2circle/src/CircleModel.cpp
This commit makes tflite2circle support quantized_dimension
Related : #3218 
=> [tflite2circle] Support quantized_dimension

compiler/luci-interpreter/src/core/KernelParams.h, compiler/luci-interpreter/src/kernels/CMakeLists.txt, compiler/luci-interpreter/src/kernels/Squeeze.cpp, compiler/luci-interpreter/src/kernels/Squeeze.h, compiler/luci-interpreter/src/kernels/Squeeze.test.cpp, compiler/luci-interpreter/src/kernels/TestUtils.h, compiler/luci-interpreter/src/loader/KernelBuilder.cpp, compiler/luci-interpreter/src/loader/KernelBuilder.h
This commit add `Squeeze` operation kernels on luci-interpreter.
=> [luci-interpreter]Add Squeeze kernels on luci-interpreter

infra/nnfw/command/count-unittest
Add a TC stat generator script which counts the number of
total/positive/negative test cases.
=> [onert] Test: Add a script for TC stat

compiler/luci/export/src/CircleExporterImpl.cpp, compiler/luci/export/src/CircleExporterUtils.cpp, compiler/luci/export/src/CircleOperationExporter.cpp, compiler/luci/export/src/SerializedData.h
Parent Issue : #3174
Draft : #3216
This commit will enable operator version exporting
=> [luci] Export operator version

compiler/tf2tfliteV2/tf2tfliteV2.py
This will add example of input_shapes argument
=> [tf2tfliteV2] add example for input shape

compiler/one-cmds/how-to-prepare-virtualenv.txt
This will place require packages as prerequisite section
=> [one-cmd] revise prepare venv document

compiler/tflchef/core/src/ModelChef.cpp, compiler/tflchef/proto/tflchef.proto, compiler/tflchef/tflite/src/RecipeChef.cpp
This supports quantized_dimension in tflchef
---
Related to #3218 Draft PR #3320
=> [tflchef] Support quantized_dimension in tflchef

runtime/onert/core/include/ir/operation/LogSoftmax.h
This commit fixes opcode of LogSoftmax.
=> [onert] Fix opcode of LogSoftmax

compiler/circlechef/circle/src/RecipeChef.cpp, compiler/circlechef/core/src/ModelChef.cpp, compiler/circlechef/proto/circlechef.proto
This supports quantized_dimension in circlechef
---
Related to #3218 Draft PR #3320
=> [circlechef] Support quantized_dimension in circlechef

infra/packaging/preset/20200630
This commit adds EXTERNALS_BUILD_OPTION to preset 20200630
=> [packaging] Add EXTENALS_BUILD_OPTION

compiler/luci/pass/src/CircleOptimizer.cpp
This supports channel-wise quantization
=> [luci] Support channel wise quantization

compiler/tflchef/tools/file/Driver.cpp, compiler/tflchef/tools/reverse/Driver.cpp
=> [tflchef] change return value

compiler/tflite2circle/driver/Driver.cpp
=> [tflite2circle] Change return value

compiler/record-minmax/driver/Driver.cpp
=> [record-minmax] change return value

compiler/circle-verify/src/Driver.cpp
=> [circle-verify] change return value

compiler/tfldump/driver/Driver.cpp
=> [tfldump] change return value

compiler/circledump/driver/Driver.cpp
=> [circledump] change return value

compiler/circle-tensordump/driver/Driver.cpp
=> [circle-tensordump] change return value

compiler/circlechef/tools/file/Driver.cpp, compiler/circlechef/tools/reverse/Driver.cpp
=> [circlechef] change return value

compiler/one-cmds/one-codegen, compiler/one-cmds/one-import, compiler/one-cmds/one-import-tf, compiler/one-cmds/one-import-tflite, compiler/one-cmds/one-optimize, compiler/one-cmds/one-pack, compiler/one-cmds/one-quantize
This will revise exit code of one-* commands to exit 255 for usage
=> [one-cmds] revise exit code

compiler/circle-quantizer/src/CircleQuantizer.cpp
This updates help msg for channel granularity
=> [circle-quantizer] Update help msg for channel granularity

compiler/one-cmds/one-quantize
This will revise one-quantize help message with channel for granularity
=> [one-cmds] revise one-quantize help with channel

compiler/circle2circle-dredd-recipe-test/CMakeLists.txt, compiler/circle2circle-dredd-recipe-test/requires.cmake, compiler/circle2circle-dredd-recipe-test/testall.sh
This commit makes this module use common-artifacts
Related : #2743 
=> [circle2circle-dredd-recipe-test] Use common-artifacts

compiler/record-minmax/CMakeLists.txt, compiler/record-minmax/driver/Driver.cpp, compiler/record-minmax/requires.cmake
This will provide --version argument to show version information
=> [record-minmax] show version

compiler/record-minmax/CMakeLists.txt
This will enable test when ENABLE_TEST is set
=> [record-minmax] apply ENABLE_TEST switch

runtime/onert/backend/cpu/ops/SliceLayer.cc, runtime/onert/backend/cpu/ops/SliceLayer.h, tests/nnapi/nnapi_gtest.skip.aarch64-linux.cpu, tests/nnapi/nnapi_gtest.skip.armv7l-linux.cpu, tests/nnapi/nnapi_gtest.skip.x86_64-linux.cpu
Add quant8 support for slice cker
ONE-DCO-1.0-Signed-off-by: Hyo Jong Kim hue.kim@samsung.com
=> [onert] Add quant8 support for slice cker

.ahub/tcchecker-tca/config.yaml
Add configuration file for TCM tools
- Add .ahub/tcchecker-tca/config.yaml
=> Add configuration file for TCM tools

tests/scripts/benchmark_nnapi.sh, tests/scripts/common.sh, tests/scripts/test-driver.sh, tests/scripts/test_framework.sh
Remove "--runtestsh" option for test-driver.sh and related setting
=> [onert/test] Remove unused option "--runtestsh"

res/TensorFlowLiteRecipes/DepthwiseConv2D_U8_001/test.recipe
This adds TFLite recipe for channel-wise quantized deptwise conv2d
---
Related to #3218 Draft PR #3320
=> [res] TFLite recipe for CWQ depthwise conv2d

infra/packaging/res/tf2nnpkg.20200630
This will introduce --v2 option to tf2nnpkg.20200630 and use --v1 option as default
=> [infra] introduce --v2 option to tf2nnpkg.20200630

tools/nnpackage_tool/nncc-tc-to-nnpkg-tc/nncc-tc-to-nnpkg-tc.sh
This will revise nncc-tc-to-nnpkg-tc to call tf2nnpkg with --v2 option if modelfilename.v2 file exist
=> [tools] revise nncc-tc-to-nnpkg-tc

compiler/record-minmax/src/HDF5Importer.cpp
This commit adds missing header
Related : #3390 
=> [record-minmax] Add missing header

infra/cmake/packages/Pybind11Config.cmake, infra/cmake/packages/Pybind11SourceConfig.cmake, infra/nncc/CMakeLists.txt
This adds pybind11 library for dalgona project
---
Related to https://github.sec.samsung.net/STAR/nnfw/issues/11537
=> [infra] Add pybind11 library to infra

tools/tflitefile_tool/select_operator.py
flatbuffers support Finish with file_identifier.
=> [tflitefile_tool] use flatbuffers's Finish

compute/cker/include/cker/operation/FullyConnected.h
- Skip copy on NONE activation of FC Hybrid
=> Skip copy on NONE activation of FC Hybrid

res/TensorFlowLiteRecipes/TransposeConv_000/test.recipe
This commit fixes TransposeConv_000 bug
Related : #3374 
=> [res] Fix TransposeConv_000 bug

compiler/common-artifacts/exclude.lst
This commit updates exclude.lst
Related : #3374 
=> [common-artifacts] Update exclude.lst

compute/cker/include/cker/ruy/RuySupport.h
Many applications shows better performance with RUY_THREADS=1
=> Use RUY_THREADS=1

compiler/luci/import/src/Nodes/CircleTransposeConv.cpp
This commit adds validation to CircleTransposeConv
Related : #3374 
=> [luci] Add validation to CircleTransposeConv

infra/scripts/docker_build_cross_aarch64_runtime.sh, infra/scripts/docker_build_cross_arm_runtime.sh, infra/scripts/docker_build_cross_arm_runtime_release.sh, infra/scripts/docker_build_cross_coverage.sh, infra/scripts/docker_build_tizen_cross.sh
Fix invalid rootfs setting when user don't set ROOTFS_DIR
=> [infra/script] Fix ROOTFS_DIR setting bug

compiler/luci-interpreter/src/loader/CMakeLists.txt, compiler/luci-interpreter/src/loader/GraphLoader.cpp, compiler/luci-interpreter/src/loader/GraphLoader.h, compiler/luci-interpreter/src/loader/KernelBuilder.test.cpp, compiler/luci-interpreter/src/loader/ModuleLoader.cpp
Issue #1088.
Add a couple of tests of `KernelBuilder`.
=> [luci-interpreter] Add `KernelBuilder` tests

compiler/luci-value-test/evalverify.sh
This will revise how to use comment of evalverify.sh script
=> [luci-value-test] revise how to use comment

packaging/nnfw.spec
This commit adds checking libarmcl version in spec file.
=> [tizen] Add checking libarmcl version in spec file

docs/conf.py, packaging/nnfw.spec, runtime/contrib/android/api/build.gradle, runtime/onert/api/include/nnfw_version.h
=> Use version 1.7.0

docs/release/1.7/release-note-1.7.0.md
Release note for 1.7.0 is added
=> Release Note for 1.7.0

compiler/luci-interpreter/src/loader/KernelBuilder.cpp, compiler/luci-interpreter/src/loader/KernelBuilder.test.cpp
Issue #1088.
Add more tests of `KernelBuilder`.
=> [luci-interpreter] Add more `KernelBuilder` tests

runtime/onert/backend/cpu/StaticTensorManager.cc, runtime/onert/backend/cpu/TensorBuilder.cc, runtime/onert/backend/cpu/TensorBuilder.h, runtime/onert/core/include/backend/ITensorBuilder.h, runtime/onert/core/include/backend/ITensorRegistry.h, runtime/onert/core/src/backend/controlflow/DynamicTensorManager.cc, runtime/onert/core/src/backend/controlflow/KernelGenerator.cc, runtime/onert/core/src/backend/controlflow/TensorBuilder.cc, runtime/onert/core/src/backend/cpu_common/DynamicTensorManager.cc, runtime/onert/core/src/backend/cpu_common/StaticTensorManager.cc, runtime/onert/core/src/compiler/ExecutorFactory.cc, runtime/onert/core/src/exec/ExecutorBase.cc
Change External/Managed to Migrant/Native to express them better.
=> [onert] Change terms : External/Managed tensor

compiler/luci-interpreter/src/kernels/CMakeLists.txt, compiler/luci-interpreter/src/kernels/Reverse.cpp, compiler/luci-interpreter/src/kernels/Reverse.h, compiler/luci-interpreter/src/kernels/Reverse.test.cpp, compiler/luci-interpreter/src/loader/KernelBuilder.cpp, compiler/luci-interpreter/src/loader/KernelBuilder.h
Add `Reverse` kernel on luci-interpreter.
=> [luci-interpreter]Add Reverse kernel on luci-interpreter.

compiler/luci-interpreter/src/loader/KernelBuilder.test.cpp
The data type does not matter for the purpose of the tests.
=> [luci-interpreter] Remove useless DataType setting in tests

res/TensorFlowLiteRecipes/AveragePool2D_U8_000/test.recipe
Parent Issue: #1880 
Fired Issue: #3429 
This commit adds recipes for AveragePool2D_U8_000. (Derived from SOS Mine Project)
Please review this Work in Progress codes @seanshpark , @jinevening 
Thank you.
=> [res/TensorFlowLiteRecipes] Add AveragePool2D_U8_000

tests/tools/nnpackage_run/src/h5formatter.cc
Merge switch-case block of `NNFW_TYPE_TENSOR_UINT8` and
`NNFW_TYPE_TENSOR_QUANT8_ASYMM`.
=> [onert] Refine h5formatter code duplication

infra/docker/Dockerfile, infra/docker/Dockerfile.1804
- Remove ENV for proxy: proxy is pre-defined argument
- Upgrade pip after install: remove fail when install numpy
=> [infra/dockerfile] Update Dockerfile

runtime/onert/backend/cpu/ops/FullyConnectedLayer.h
Add EXPERIMENTAL_RUY_FEATURE define check for cpu::ops::FullyConnectedLayer class member _is_weights_freed
=> [onert] Fix unused class member build error

compiler/luci/pass/src/FuseBCQPass.cpp
Synced with #3449
This commit will revise `FuseBCQPass` a little bit as follow.
- Add a comment for dimension
- Do not throw runtime error
=> [luci] Revise trivial things in FuseBCQPass

runtime/onert/frontend/nnapi/wrapper/OperationFactory.cc
Generalize binary ops that does not have params to remove code
duplicaitons.
=> [onert] Refine nnapi OperationFactory binary ops

tests/tools/nnpackage_run/src/args.cc
Use `notifier` of `boost::program_options` to reduce branches in `Parse`
method rather than `if` statement for each argument.
This is for better score on CyclomaticComplexity.
=> [nnpkgrun] Refine Args impl

runtime/onert/backend/acl_cl/KernelGenerator.cc, runtime/onert/backend/acl_common/AclKernelGen.h, runtime/onert/backend/acl_neon/KernelGenerator.cc
Unify FullyConnected kernel generation function to avoid code
duplication.
=> [onert] Unify FC kernelgen of ACL backends

runtime/onert/backend/cpu/StaticTensorManager.cc, runtime/onert/core/include/backend/ITensorRegistry.h, runtime/onert/core/src/backend/cpu_common/StaticTensorManager.cc
Rename remaining Managed/External to Native/Migrant.
=> [onert] Rename to Native/Migrant

compiler/luci-interpreter/src/loader/KernelBuilder.cpp, compiler/luci-interpreter/src/loader/KernelBuilder.test.cpp
Add several more tests for `KernelBuilder`.
=> [luci-interpreter] Add more KernelBuilder tests

res/TensorFlowLiteRecipes/L2Normalize_U8_000/test.recipe
Fired Issue: #3444 
This commit adds recipes for L2Normalize_U8_000. (Derived from SOS Mine Project)
Please review this Work in Progress codes @seanshpark , @jinevening
Thank you.
=> [res/TensorFlowLiteRecipes] Add L2Normalize_U8_000

runtime/onert/backend/cpu/ops/CompareLayer.cc
In the same manner with #3386
Refine cpu backend's CompareLayer kernel dispatching to remove code
duplications. Changing switch-case to array-lookup.
This is for better score on CodeDuplication of SAM(A code quality
analysis tool).
=> [onert] cpu: Refine compareScalar kernel dispatching

infra/packaging/preset/20200630
This commit removes python virtual env creation part
Related : #3355
=> [packaging] remove python virtual env creation part

compiler/one-cmds/one-import-tf, compiler/one-cmds/one-import-tflite, compiler/one-cmds/one-optimize, compiler/one-cmds/one-pack, compiler/one-cmds/one-quantize
This will show log message when error has occurs
=> [one-cmds] Show message when error

compiler/luci/import/src/Nodes/CircleLogistic.cpp
This allows to import quantized logistics
---
Related to #3496
=> [luci] Allow importing quantized logistics

compiler/circle-tensordump/src/Dump.cpp
This supports dumping of quantized_dimension
=> [circle-tensordump] Support dumping of quantized_dimension

compute/cker/include/cker/Types.h, compute/cker/include/cker/operation/SpaceToDepth.h, runtime/onert/backend/cpu/KernelGenerator.cc, runtime/onert/backend/cpu/KernelGenerator.h, runtime/onert/backend/cpu/ops/SpaceToDepthLayer.cc, runtime/onert/backend/cpu/ops/SpaceToDepthLayer.h, runtime/onert/frontend/base_loader/include/base_loader.h, tests/nnapi/nnapi_gtest.skip.aarch64-linux.cpu, tests/nnapi/nnapi_gtest.skip.armv7l-linux.cpu, tests/nnapi/nnapi_gtest.skip.x86_64-linux.cpu
parent issue : #3474 
Support SpaceToDepth Operation in cpu backend
ONE-DCO-1.0-Signed-off-by: sungho22.lee <sungho22.lee@samsung.com>
=> [onert] Implement SpaceToDepth operation in cpu backend

compiler/circle-tensordump/src/Dump.cpp
This commit revises write_data_to_hdf5 function
=> [circle-tensordump] revise write_data_to_hdf5 function

compiler/luci/pass/src/FuseBCQPass.cpp
Parent Issue : #3481 
Draft : #3329
Function `createNoOp` can be used for later in common.
So this commit will move the function to anonymous namespace.
=> [luci] Move lambda function to anonymous namespace

compiler/.ahub/tcchecker-tca/config.yaml
- Add a `compiler/.ahub/tcchecker-tca/config.yaml` for TCM check automation.
=> Add TCM configuration file for compiler

compiler/luci/export/src/CircleOperationExporter.cpp
for #3458 
This commit update `SpaceToDepth` on luci/export.
=> [luci/export]Update SpaceToDepth export.

compiler/luci/pass/src/FuseBCQPass.cpp
Parent Issue : #3481
Draft : #3329
**For convenient review, all codes are same with original codes except two lines**
Until now, we didn't make FuseBCQPass separate for each version.
This commit will introduce BCQFuser version 1.
=> [luci] Introduce BCQFuser Version 1

compiler/locomotiv/src/Node/BiasEncode.test.cpp, compiler/locomotiv/src/Node/MatMul.test.cpp
This will revise unit tests for TCM
=> [locomotiv] Fix test for TCM

compiler/hermes/src/hermes.test.cpp
This will revise unit test to do testing
=> [hermes] fix test for TCM

compiler/locop/src/FormattedGraph.test.cpp, compiler/locop/src/FormattedTensorShape.test.cpp
This will revise unit tests for TCM
=> [locop] Fix for TCM

compiler/luci/import/src/Importer.test.cpp, compiler/luci/lang/src/Module.test.cpp, compiler/luci/lang/src/Nodes/CircleCustom.test.cpp, compiler/luci/lang/src/Nodes/CircleIf.test.cpp, compiler/luci/lang/src/Nodes/CircleWhile.test.cpp
This will revise unit tests for TCM
=> [luci] Fix for TCM

compiler/luci-interpreter/src/kernels/L2Normalize.test.cpp, compiler/luci-interpreter/src/kernels/LeakyRelu.test.cpp, compiler/luci-interpreter/src/kernels/Logistic.test.cpp, compiler/luci-interpreter/src/kernels/TransposeConv.test.cpp
This will revise unit tests for TCM
=> [luci-interpreter] Fix for TCM

infra/scripts/build-tcm.sh
- Add script to help generate tcm reports.
- A simple version for simple measurements, most of friendly features are omitted. I will supplement it as needed later.
=> Add script for build tcm result

runtime/onert/backend/cpu/Tensor.h
Append doxygen for ExternalTensor class
=> [onert/cpu] Append doxygen for ExternalTensor class

tests/scripts/CMakeLists.txt, tests/scripts/onert-test
Introduce test driver and install to [install_dir]/test
No test command yet
---
part of #3514
=> [onert/test] Introduce test driver

compiler/tf2tfliteV2/tf2tfliteV2.py
This will revise to run with python3
=> [tf2tfliteV2] Use python3

tests/tools/tflite_run/src/args.cc
Use `notifier` of `boost::program_options` to reduce branches in `Parse`
method rather than `if` statement for each argument.
This is for better score on CyclomaticComplexity.
In the same manner with #3472
=> [tfliterun] Refine Args impl

runtime/onert/core/src/ir/verifier/Verifier.cc, runtime/onert/core/src/ir/verifier/Verifier.h
Make EdgeConsistencyChecker print error message.
=> [onert] Make EdgeConsistencyChecker verbose

compute/cker/include/cker/operation/ReLU6.h, runtime/onert/backend/cpu/KernelGenerator.cc, runtime/onert/backend/cpu/KernelGenerator.h, runtime/onert/backend/cpu/ops/ReLU6Layer.cc, runtime/onert/backend/cpu/ops/ReLU6Layer.h, tests/nnapi/nnapi_gtest.skip.aarch64-linux.cpu, tests/nnapi/nnapi_gtest.skip.armv7l-linux.cpu, tests/nnapi/nnapi_gtest.skip.x86_64-linux.cpu
Add Relu6 operation
Signed-off-by: YiHyunjin <hj0412.yi@samsung.com>
=> [onert] Implement cpu backend OP(Relu6)

compiler/common-artifacts/CMakeLists.txt
This adds venv for tf 2.3.0-rc0
=> [common-artifacts] Add venv for tf 2.3.0-rc0

compiler/one-cmds/one-prepare-venv
This commit make `one-prepare-venv` to check ensurepip installation,
which is required to make venv.
---
cc @parjong
=> [one-cmds] Check ensurepip

compiler/luci-value-test/luci_eval_verifier.py, compiler/luci-value-test/tester/src/EvalTester.cpp
For #3458 
This commit update luci_eval_verifier.py and EvalTester.cpp for accepting more test cases.
1. Add more input DataType case for `If` kernel.
2. Add more output DataType case for `ArgMax` kernel.
3. Update for supporting multiple output.
=> [luci-value-test]Update luci-value-test for more test cases.

res/TensorFlowPythonModels/examples/tconv-bn/__init__.py
This commit adds tconv-bn network.
Related : #3565 
=> [TensorFlowPythonModels] Add tconv-bn network

compiler/common-artifacts/CMakeLists.txt
This commit resolve circular dependency warning.
=> [common-artifacts] resolve circular dependency

infra/packaging/preset/20200731_windows
This commit introduces 20200731 windows preset.
Related : #3390 
=> [preset] Introduce 20200731 windows preset

docs/overview/supported-operations.md
Add SLICE into doc
Signed-off-by: twoflower <chunseoklee@gmail.com>
=> Add SLICE into supported op in document

compute/cker/include/cker/Types.h, compute/cker/include/cker/operation/ResizeBilinear.h, runtime/onert/backend/cpu/KernelGenerator.cc, runtime/onert/backend/cpu/KernelGenerator.h, runtime/onert/backend/cpu/ops/ResizeBilinearLayer.cc, runtime/onert/backend/cpu/ops/ResizeBilinearLayer.h, runtime/onert/core/include/compiler/StaticShapeInference.h, runtime/onert/core/include/exec/DynamicShapeInference.h, runtime/onert/core/include/ir/operation/ResizeBilinear.h, runtime/onert/core/include/util/ShapeInference.h, runtime/onert/core/src/compiler/OperationValidator.cc, runtime/onert/core/src/compiler/OperationValidator.h, runtime/onert/core/src/compiler/StaticShapeInference.cc, runtime/onert/core/src/exec/DynamicShapeInference.cc, runtime/onert/core/src/util/ShapeInference.cc, runtime/onert/frontend/base_loader/include/base_loader.h, runtime/onert/frontend/nnapi/wrapper/OperationFactory.cc, tests/nnapi/nnapi_gtest.skip.aarch64-linux.cpu, tests/nnapi/nnapi_gtest.skip.armv7l-linux.cpu, tests/nnapi/nnapi_gtest.skip.noarch.interp, tests/nnapi/nnapi_gtest.skip.x86_64-linux.cpu, tests/nnapi/specs/V1_0/resize_bilinear_quant8_nnfw.mod.py
support ResizeBilinear cker for cpu backend
=> [onert] Add ResizeBilinear cker

compiler/luci/pass/src/FuseBCQPass.cpp
Synced with #3449
This commit is for critical bugfix and some patches which are applied for 1.6.2.
- Add a comment for dimension
- Do not throw runtime error
=> [Compiler] Bugfix and patches for FuseBCQPass in 1.7.0

res/TensorFlowLiteSchema/2.3.0/schema.fbs, res/TensorFlowLiteSchema/SCHEMA.lst
This will introduce TFlite schema file version 2.3.0
=> [res] TFlite schema 2.3.0

infra/cmake/packages/FarmhashSourceConfig.cmake
Revise farmhash note for Tensorflow version to 2.3.0
=> [infra] Revise comment for farmhash

infra/packaging/preset/20200630
Parent Issue : #3471
Draft : #3476
This commit will update 20200630 preset to include `bcq-tools`
=> [infra] Update preset 20200630

res/TensorFlowLiteRecipes/SpaceToDepth_U8_000/test.recipe
Fired Issue: #3583 
This commit adds recipes for SpaceToDepth_U8_000. (Derived from SOS Mine Project)
Please review this Work in Progress codes, @seanshpark @jinevening .
Thank you.
=> [res/TensorFlowLiteRecipes] Add SpaceToDepth_U8_000

compiler/tf2tfliteV2/tf2tfliteV2.py
This commit enables tf2tfliteV2 to support more model format.
Related : #3601 
=> [tf2tfliteV2] Support more model format

compiler/luci/import/include/luci/Import/Nodes.h, compiler/luci/import/include/luci/Import/Nodes/CircleUnique.h, compiler/luci/import/src/GraphBuilderRegistry.cpp, compiler/luci/import/src/Nodes/CircleUnique.cpp
This commit will add unique operation to luci import
=> [luci/import] Add Unique operation

compiler/one-cmds/how-to-prepare-virtualenv.txt, compiler/one-cmds/how-to-use-one-commands.txt, compiler/one-cmds/one-prepare-venv
This will revise to TensorFlow 2.3.0 version
=> [one-cmds] Use TF2.3.0

compiler/common-artifacts/CMakeLists.txt
This will revise to use TensorFlow version 2.3.0
=> [common-artifacts] Use TensorFlow 2.3.0

res/TensorFlowLiteRecipes/ResizeBilinear_U8_000/test.recipe
Fired Issue: #3497 
This commit adds recipes for ResizeBilinear_U8_000. (Derived from SOS Mine Project)
Please review this Work in Progress codes, @seanshpark @jinevening .
Thank you.
=> [res/TensorFlowLiteRecipes] Add ResizeBilinear_U8_000

tests/scripts/command/nnpkg-test
Introduce "onert-test"'s nnpkg-test command
It's copy of nnpkg_test.sh except finding "nnpackage_run" binary because "onert-test" set PATH for installed bin directory
---
part of #3514
=> [onert-test] Introduce nnpkg-test command

compiler/luci-value-test/tester/src/EvalTester.cpp
For #3458
This commit enable Scalar output write on shape file.
Scalar shape output write as a 1.
=> [luci-value-test]Scalar output write update.

compiler/one-cmds/one-prepare-venv
This commit adds user option to pip.
=> [one-cmds] Add user option to pip

runtime/onert/frontend/nnapi/wrapper/OperationFactory.cc
Unify Pool2D op creation of `OperationFactory` to reduce code
duplication.
=> [onert] Unify Pool2D ops of OperationFactory

compiler/luci/export/src/CircleOperationExporter.cpp
This commit will add unique operation to luci export
=> [luci/export] Enable Unique operation

packaging/nnfw.spec, runtime/onert/sample/minimal/src/minimal.cc
- Provide minimap-app rpm simply to test runtime on tizen platform
=> Enable minimal app on tizen

compiler/luci/logex/src/FormattedGraph.cpp
Parent Issue : #2568
Draft PR : #2829
This commit will add unique operation to luci logex
=> [luci/logex] Add unique operation

res/TensorFlowPythonExamples/examples/while_2/__init__.py
This will fix TF examples while_2 comment about execution
=> [res] Fix TF examples while_2

runtime/onert/core/include/backend/cpu_common/Tensor.h
This separates the roles of `_buffer` and `_allocator` in _Tensor.h_.
Previously,
- memory pointer can be accessed sometimes by `_buffer` and sometimes by `_allocator.base()`, which was hard to understand.
But now,
- memory pointer can be accessed _only_ by `_buffer`
- `_allocator` exists only to have shared _ownership_ of memory area
=> [onert] Separate roles of _buffer and _allocator in Tensor.h

infra/scripts/common.sh, infra/scripts/test_ubuntu_runtime.sh, infra/scripts/test_ubuntu_runtime_mixed.sh, tests/scripts/test-driver.sh
- Remove unittest related part from test-driver.sh
- Use "[install_dir]/test/onert-test unittest" command
- Update CI script to use "onert-test unittest" command
---
part of #3514
=> [onert/test] Update unittest usage

runtime/onert/core/include/ir/TypeInfo.h, runtime/onert/frontend/base_loader/include/base_loader.h, runtime/onert/frontend/circle/src/circle_loader.cc, runtime/onert/frontend/tflite/src/tflite_loader.cc
- load sparsity from tflite
- add members ir::TypeInfo for sparsity
=> [onert] Introduce sparsity (loader, ir)

compiler/luci/service/src/CircleShapeInferenceRule.cpp, compiler/luci/service/src/CircleTypeInferenceRule.cpp
Parent Issue : #2568
Draft PR : #2829
This commit will add unique operation to luci service
=> [luci/service] Add Unique operation

compiler/luci/export/src/CircleOperationExporter.cpp
for #3458 
This commit update `LocalResponseNormalization` on luci/export.
=> [luci/export]Update LocalResponseNorm export.

docs/conf.py, packaging/nnfw.spec, runtime/contrib/android/api/build.gradle, runtime/onert/api/include/nnfw_version.h
- Update version text to 1.8.0
=> Update versoion to 1.8.0

compute/cker/include/cker/operation/BatchToSpaceND.h, runtime/onert/backend/cpu/KernelGenerator.cc, runtime/onert/backend/cpu/KernelGenerator.h, runtime/onert/backend/cpu/ops/BatchToSpaceNDLayer.cc, runtime/onert/backend/cpu/ops/BatchToSpaceNDLayer.h, runtime/onert/core/include/ir/operation/BatchToSpaceND.h, runtime/onert/core/src/ir/operation/BatchToSpaceND.cc, runtime/onert/frontend/base_loader/include/base_loader.h, tests/nnapi/nnapi_gtest.skip.aarch64-linux.cpu, tests/nnapi/nnapi_gtest.skip.armv7l-linux.cpu, tests/nnapi/nnapi_gtest.skip.x86_64-linux.cpu
BatchToSpaceND from tflite
ONE-DCO-1.0-Signed-off-by: Juitem JoonWoo Kim <jw1772.kim@samsung.com>
=> [onert] BatchToSpaceND cpu backend implementation

compute/cker/include/cker/operation/FullyConnected.h, runtime/onert/backend/cpu/ops/FullyConnectedLayer.cc, runtime/onert/backend/cpu/ops/FullyConnectedLayer.h, runtime/onert/core/include/backend/IPortableTensor.h, runtime/onert/core/include/backend/cpu_common/Tensor.h, runtime/onert/core/include/ir/TypeInfo.h
It introduces fullyconnected kernel for spare 2D weight.
=> [onert] introduce fully connected kernel for sparse 2D float weight

runtime/onert/frontend/base_loader/include/base_loader.h, runtime/onert/frontend/circle/src/circle_loader.cc
Move circle specific operation load methods to cicle_loader.
- InstanceNorm
- BCQGather
- BCQFullyConnected
=> [onert] Move circle specific ops to cicle_loader

infra/scripts/common.sh, tests/scripts/command/verify-tflite, tests/scripts/models/run_test.sh
Introduce tflite file inference verification test: nnapi, tflite-loader
=> [onert/test] Introduce tflite verification test command

compiler/tf2tfliteV2/README.md, compiler/tf2tfliteV2/tf2tfliteV2.py
This commit updates README.md and help message.
=> [tf2tfliteV2] Update README.md and help message

compiler/pota-quantization-value-test/CMakeLists.txt, compiler/pota-quantization-value-test/compare_tensors.py, compiler/pota-quantization-value-test/test.lst, compiler/pota-quantization-value-test/test_record_minmax.sh
This enables quantization value test
=> [pota-value-test] Enable quantization value test

runtime/onert/core/include/ir/Operand.h, runtime/onert/core/src/compiler/Fp32ToFp16Converter.cc, runtime/onert/core/src/compiler/HEScheduler.cc, runtime/onert/core/src/compiler/Linear.cc, runtime/onert/core/src/ir/Graph.cc, runtime/onert/core/src/ir/LoweredGraph.cc, runtime/onert/core/src/ir/Operand.cc, runtime/onert/core/src/ir/pass/ConstantInsertionPass.cc, runtime/onert/core/src/ir/pass/PermutationEliminationPass.cc, runtime/onert/core/src/ir/pass/PermutationInsertionPass.cc, runtime/onert/core/src/ir/pass/PermutationOperationPass.cc, runtime/onert/core/src/ir/verifier/Verifier.cc, runtime/onert/test/graph/operand/UseDef.cc
Make Def as a single element rather than a set.
=> [onert] Revise ir::Operand's Def

infra/scripts/docker_build_nncc.sh
- Fix tar exclude file option: --except -> --exclude
- Fix option order
=> [infra/script] Fix bug in docker_build_nncc.sh

infra/scripts/test_arm_nnpkg.sh, infra/scripts/test_coverage.sh, infra/scripts/test_ubuntu_runtime.sh, infra/scripts/test_ubuntu_runtime_mixed.sh, tests/scripts/CMakeLists.txt, tests/scripts/command/prepare-model, tests/scripts/command/verify-tflite
- Change list and config install path: tests -> test
- Use installed list file: remove source dependency
=> [onert/test] Use installed list and model config

packaging/nnfw.spec, runtime/onert/sample/minimal/CMakeLists.txt
Rename minimal app: minimal -> onert-minimal-app
=> [onert/test] Rename minimal app

tests/scripts/CMakeLists.txt
Install tflite download model config for test
=> [onert/test] Install tflite download model config

tests/scripts/models/run_test.sh
Check config directory exist: set by default or option
=> [onert/test] Check config directory exist in run_test.sh

infra/scripts/test_ubuntu_runtime.sh, infra/scripts/test_ubuntu_runtime_mixed.sh, tests/custom_op/FillFrom/CMakeLists.txt
Move custom op test FillFrom_runner install directory: tests -> test
Move test FillFrom_runner to test_ubuntu_runtime_mixed.sh
=> [onert/test] Move custom op test install directory

compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
This fixes quantization for transpose conv
=> [luci] Fix quantization for transpose conv

res/TensorFlowLiteRecipes/TransposeConv_001/test.recipe
This adds a TransposeConv recipe
--
Related to #2088
=> [res] Add a TransposeConv recipe

res/TensorFlowLiteRecipes/FullyConnected_003/test.recipe
This adds a recipe for FullyConnected Op
---
Related to #2088
=> [res] Add a recipe for FullyConnected

runtime/onert/backend/cpu/ops/BatchToSpaceNDLayer.cc, runtime/onert/backend/cpu/ops/BatchToSpaceNDLayer.h, tests/nnapi/nnapi_gtest.skip.aarch64-linux.cpu, tests/nnapi/nnapi_gtest.skip.armv7l-linux.cpu, tests/nnapi/nnapi_gtest.skip.x86_64-linux.cpu
Support BatchToSpaceND quantized uint8 on cpu backend
=> [onert/cpu] Implement BatchToSpaceND quantized uint8 cpu backend

compiler/circledump/src/OpPrinter.cpp
This will enable dumping of PadV2 operation
Draft: #3566
Issue: #3362
=> [circledump] Enable PadV2 operator

compiler/circledump/src/OpPrinter.cpp
Add comment about no option in NonMaxSuppressionV4.
=> [circledump] No opt comment for NonMaxSupressionV4

compiler/luci/import/include/luci/Import/Nodes.h, compiler/luci/import/include/luci/Import/Nodes/CircleNonMaxSuppressionV4.h, compiler/luci/import/src/GraphBuilderRegistry.cpp, compiler/luci/import/src/Nodes/CircleNonMaxSuppressionV4.cpp
Support NonMaxSuppressionV4 in luci importer.
=> [luci/import] Add NonMaxSuppressionV4 op

runtime/onert/frontend/base_loader/include/base_loader.h
- This commit removes `deallocateMmappedArea` function
- `deallocateMmappedArea` is now integrated into `MMapedData` by #2764
- This function is no longer used
=> [onert] Remove unused function for munmap

compiler/luci-interpreter/src/kernels/Add.cpp, compiler/luci-interpreter/src/kernels/Add.test.cpp
For #1623 
This commit add negative tests on `Add` kernel on luci-interpreter.
=> [luci-interpreter]Negative Tests for Add kernel

res/TensorFlowPythonExamples/examples/while_3/__init__.py
This will introduce another while example slightly modified from while_2
with alternative implementation not using Size operator and
using Placeholder of i instead of constant number so that
constant folding for the operators won't happen
=> [res] TF example while_3

docs/release/1.8/release-note-1.8.0.md
Release note for 1.8.0 is added
=> Release Note for 1.8.0

compute/test/CMakeLists.txt
Disable build test_compute if ENABLE_TEST is off
=> [onert/compute] Check ENABLE_TEST for test build

compute/cker/include/cker/operation/SoftMax.h, runtime/onert/backend/cpu/ops/SoftMaxLayer.cc, runtime/onert/core/src/interp/operations/Softmax.cc
- Enable 1D float softmax
- Move 1D&2D simple softmax calculation into cker
=> [onert/cpu] Move softmax implementation

Makefile.template
Fix packaging error by removed directory "tests"
=> [onert] Fix runtime makefile for packaging

tests/nnfw_api/src/CircleGen.cc, tests/nnfw_api/src/CircleGen.h
Create a source file for CircleGen and move the implementation to it.
=> [nnfwapi] Test: Move CircleGen impl to source file

docs/conf.py, packaging/nnfw.spec, runtime/contrib/android/api/build.gradle, runtime/onert/api/include/nnfw_version.h
=> Master version to 1.9.0

compute/cker/include/cker/Types.h, compute/cker/include/cker/operation/LogSoftMax.h, runtime/onert/backend/cpu/ops/LogSoftMaxLayer.cc, runtime/onert/backend/cpu/ops/LogSoftMaxLayer.h, tests/nnapi/nnapi_gtest.skip.aarch64-linux.acl_cl, tests/nnapi/nnapi_gtest.skip.aarch64-linux.acl_neon, tests/nnapi/nnapi_gtest.skip.armv7l-linux.acl_cl, tests/nnapi/nnapi_gtest.skip.armv7l-linux.acl_neon, tests/nnapi/nnapi_gtest.skip.noarch.interp, tests/nnapi/specs/V1_2/log_softmax_nnfw.mod.py
parent issue #3495 
Add quant8 kernel and testcase for log_softmax
ONE-DCO-1.0-Signed-off-by: Leehansol <hansolu.lee@samsung.com>
=> [onert] Add log_softmax kernel to support quant8

infra/scripts/build-tcm.sh
- Fix build configuration file path on script.
=> Bug fix on TCM build script

tests/nnfw_api/src/CircleGen.cc, tests/nnfw_api/src/CircleGen.h, tests/nnfw_api/src/GenModelTests.cc
=> [nnfwapi] Test: Add a TC for COS op

res/TensorFlowLiteRecipes/NonMaxSuppressionV4_000/test.recipe, res/TensorFlowLiteRecipes/NonMaxSuppressionV4_001/test.recipe
Add recipes for NonMaxSuppressionV4 op.
=> [res] Add NonMaxSuppressionV4 recipes

res/TensorFlowPythonExamples/examples/non_max_suppression_padded/__init__.py, res/TensorFlowPythonExamples/examples/non_max_suppression_padded_2/__init__.py
Add examples for NonMaxSuppressionV4 op.
=> [res] Add examples for NonMaxSuppressionV4 op

compiler/luci/logex/src/FormattedGraph.cpp
This adds support for PadV2 operator in logex
Draft: #3566
Issue: #3362
=> [luci] Enable PadV2 operator in logex

compiler/vconone/CMakeLists.txt
This will revise compiler frontend version to 1.9.0
=> Compiler frontend version up to 1.9.0

runtime/onert/frontend/base_loader/include/base_loader.h
- MMapedData reduces load/prepare time, but increases inference time
- Use CachedData for weight tensor for inference performance
- Includes Revert "[onert] Remove unused function for munmap (#3710)"
---
- This PR partially reverts https://github.com/Samsung/ONE/pull/2764
=> [onert] Use CachedData instead of MMapedData (1.8.0)

compiler/luci/import/include/luci/Import/Nodes.h, compiler/luci/import/include/luci/Import/Nodes/CirclePadV2.h, compiler/luci/import/src/GraphBuilderRegistry.cpp, compiler/luci/import/src/Nodes/CirclePadV2.cpp
This enables import of PadV2 operator in luci
Draft: #3566
Issue: #3362
=> [luci] Enable PadV2 operator in import

res/TensorFlowPythonExamples/examples/PadV2/__init__.py
This will introduce TensorFlowPythonExamples for PadV2 op
Draft: #3566
Issue: #3362
=> [res] TensorFlowPythonExamples for PadV2

compiler/luci/export/src/CircleOperationExporter.cpp
This enables PadV2 operator in luci export
Draft: #3566
Issue: #3362
=> [luci] Enable PadV2 operator in export

res/TensorFlowPythonExamples/examples/non_max_suppression_with_scores/__init__.py, res/TensorFlowPythonExamples/examples/non_max_suppression_with_scores_2/__init__.py
Add examples for NonMaxSuppressionV5 operator.
=> [res] Add examples for NonMaxSuppressionV5 op

Makefile.template
Find directories to package by using shell's "ls" command
=> [onert] Generate test package using ls

tools/update_version/update-version.sh
Add -v option to show current version
Add execute permission
Rename script
=> [tool/update-version] Show current version

runtime/onert/frontend/base_loader/include/base_loader.h
This commit changes param ReduceType to template in base_loader.
=> [onert] Change param ReduceType to template in base_loader

tools/tflitefile_tool/model_parser.py, tools/tflitefile_tool/requirements.txt, tools/tflitefile_tool/select_operator.py
- Add requirements.txt
- Remove deprecated python path setting in code
=> [tool/tflitefile] Add requirements.txt file

compiler/circle2circle/src/Circle2Circle.cpp
This will apply disable_validation option to optimized model validation
- for real model with dynamic shape in Concat
=> [luci] Apply disable_validation to optimized model

runtime/onert/core/src/compiler/ManualScheduler.cc, tests/nnfw_api/src/RegressionTests.cc
Throw when no backends were loaded rather than assertion.
Add a regression test.
Resolve #3826
=> [onert] Throw when no backends loaded

compiler/luci/service/src/CircleShapeInferenceRule.cpp, compiler/luci/service/src/CircleTypeInferenceRule.cpp
This enables PadV2 support in services
Draft: #3566
Issue: #3362
=> [luci] Enable PadV2 operator in services

runtime/onert/core/src/compiler/HEScheduler.h, runtime/onert/core/src/exec/FunctionSequence.cc, tests/scripts/common.sh, tests/scripts/test_scheduler_with_profiling.sh
- Fix HEScheduler to make it work
- Update testing script to make it work
=> [onert] Fix HEScheduler and running script

tools/nnpackage_tool/tflite2circle/tflite2circle.sh, tools/nnpackage_tool/tflite2circle/tflitejson2circlejson.py
- Update tensorflow schema version v1.12.0 -> v1.13.1
- Remove unnecessary default value writings in json
=> [nnpackage_tool] update tflite2circle

runtime/onert/core/src/util/EventRecorder.cc, runtime/onert/core/src/util/EventRecorder.h
Introduce new write type of ChromeTracingObserver - MD Table
=> [onert/util] Introduce MDTable write type of ChromeTracingObserver

tools/nnpackage_tool/model2nnpkg/README.md, tools/nnpackage_tool/model2nnpkg/model2nnpkg.sh
Allow to set nnpackage name by option -p
=> [tool/nnpkg] Set nnpacakge name

res/TensorFlowLiteRecipes/Unique_000/test.recipe, res/TensorFlowLiteRecipes/Unique_001/test.recipe, res/TensorFlowLiteRecipes/Unique_002/test.recipe, res/TensorFlowLiteRecipes/Unique_003/test.recipe, res/TensorFlowLiteRecipes/Unique_U8_000/test.recipe, res/TensorFlowLiteRecipes/Unique_U8_001/test.recipe
Parent Issue : #1606
Draft PR : #2829 
This commit adds a correction for unique recipes that were introduced in #3410 
=> [res/TensorFlowLiteRecipes] Correct Unique recipe

compiler/luci/import/src/Nodes/CircleConst.cpp, compiler/luci/lang/src/Nodes/CircleConst.cpp, compiler/luci/pass/include/luci/CircleOptimizer.h, compiler/luci/pass/include/luci/Pass/RequantizePass.h, compiler/luci/pass/src/CircleOptimizer.cpp, compiler/luci/pass/src/RequantizePass.cpp
This supports requantization from int8 to uint8
---
Related to #3779 Draft PR #3823
=> [luci] Support for requantization from int8 to uint8

runtime/onert/core/src/backend/controlflow/TensorRegistry.h
Add ifdef guard to controlflow TensorRegistry.
=> [onert] Add ifdef guard to controlflow TensorReg

compiler/luci/logex/src/FormattedGraph.cpp
Add support for NonMaxSuppressionV5 op in luci/logex.
=> [luci/logex] Support NonMaxSuppressionV5 op

compiler/luci/import/include/luci/Import/Nodes.h, compiler/luci/import/include/luci/Import/Nodes/CircleNonMaxSuppressionV5.h, compiler/luci/import/src/GraphBuilderRegistry.cpp, compiler/luci/import/src/Nodes/CircleNonMaxSuppressionV5.cpp
Support NonMaxSuppressionV5 in luci importer.
=> [luci/import] Add NonMaxSuppressionV5 op

res/TensorFlowLiteRecipes/PadV2_000/test.recipe
This adds PadV2 model recipe
Draft: #3566
Issue: #3362
=> [res] TensorFlowLiteRecipes for PadV2

tools/nnpackage_tool/model2nnpkg/model2nnpkg.sh
Fix string comparison test bug
---
For #3870
=> [tool/model2nnpkg] Fix string comparison bug

compiler/circle2circle/src/Circle2Circle.cpp
This will fix to handle segment fault error for invalid input file
=> [circle2circle] Fix segfault for invalid input

infra/3rdparty/Eigen/fd6845384b86/URL.default, infra/cmake/packages/EigenSourceConfig.cmake
bitbucket no more support source code download service
---
Related issue: #3882
=> [infra] Update eigen download url

tests/scripts/models/run_test.sh
Fix test command warning: unary operator expected
=> [onert/test] Fix test command warning

docs/runtime/compute.md
This commit fills `compute.md` which is about compute directory.
=> [doc] Write compute.md

res/TensorFlowLiteRecipes/NonMaxSuppressionV5_000/test.recipe, res/TensorFlowLiteRecipes/NonMaxSuppressionV5_001/test.recipe
Add recipes for NonMaxSuppressionV5 op.
=> [res] Add NonMaxSuppressionV5 recipes

compiler/circle-quantizer/src/CircleQuantizer.cpp
This commit enables circle-quantizer to verify circle file.
Related : #3878
=> [circle-quantizer] verify circle file

compiler/locomotiv/src/Node/FeatureDecode.cpp, compiler/locomotiv/src/Node/FilterEncode.cpp, compiler/locomotiv/src/Node/Forward.cpp, compiler/locomotiv/src/Node/MatMul.cpp, compiler/locomotiv/src/Node/MatrixDecode.cpp
This will rename methods to reduce class lines of codes of NodeExecution
=> [locomotiv] Reduce class codes F-M

compiler/locomotiv/src/Node/TensorBroadcast.cpp, compiler/locomotiv/src/Node/TensorConcat.cpp, compiler/locomotiv/src/Node/TensorConstantPad.cpp, compiler/locomotiv/src/Node/TensorReduce.cpp, compiler/locomotiv/src/Node/TransposedConv2D.cpp
This will rename methods to reduce class lines of codes of NodeExecution
=> [locomotiv] Reduce class codes T

compiler/luci/service/src/CircleShapeInferenceRule.cpp
=> [luci] Shape inf reduce LOC A-B

compiler/luci/import/src/Nodes/CircleBatchToSpaceND.cpp, compiler/luci/import/src/Nodes/CircleMaximum.cpp, compiler/luci/import/src/Nodes/CircleReduceMax.cpp, compiler/luci/import/src/Nodes/CircleReduceMin.cpp, compiler/luci/import/src/Nodes/CircleSpaceToBatchND.cpp, compiler/luci/import/src/ValidateHelpers.cpp, compiler/luci/import/src/ValidateHelpers.h
This will introduce ValidateHelpers to reduce duplicate codes
=> [luci] Import validate helpers to reduce dup codes

compiler/luci/service/src/CircleShapeInferenceRule.cpp
This will relocate shape inference common functions to upper side of the file
=> [luci] Relocate shape inf common functions

compiler/luci/service/src/CircleShapeInferenceRule.cpp
=> [luci] Shape inf reduce LOC D-M

compiler/tflite2circle/src/CircleModel.cpp
This commit enables tflite2circle to verify tflite file.
ONE-DCO-1.0-Signed-off-by: seongwoo mhs4670go@naver.com
=> [tflite2circle] verify tflite file

compiler/record-minmax/src/RecordMinMax.cpp
This commit enables record-minmax to verify circle file.
=> [record-minmax] verify circle file

runtime/onert/backend/cpu/ops/BinaryArithmeticLayer.cc, runtime/onert/backend/cpu/ops/BinaryArithmeticLayer.h, runtime/onert/backend/cpu/ops/ElementwiseBinaryLayer.cc, runtime/onert/backend/cpu/ops/ElementwiseBinaryLayer.h, runtime/onert/backend/cpu/ops/PoolLayer.cc, runtime/onert/backend/cpu/ops/PoolLayer.h, runtime/onert/backend/cpu/ops/ReduceLayer.cc, runtime/onert/backend/cpu/ops/ReduceLayer.h
This commit moves the time of choosing kernel to configure in some cpu layers
- cpu layers : BinaryArithmeticLayer, ElementwiseBinaryLayer, PoolLayer, ReduceLayer
=> [onert] Move the time of choosing kernel to configure

tools/tflitefile_tool/select_operator.py
select_operator will support Select op.
=> [tflitefile_tool] select_operator supports Select op

compiler/luci/service/src/CircleShapeInferenceRule.cpp
=> [luci] Shape inf reduce for virtual outputs

runtime/onert/frontend/nnapi/wrapper/OperationFactory.cc
Unify comparison ops in OperationFactory
=> [nnapi] Unify comparison ops in OperationFactory

compiler/luci/service/src/CircleShapeInferenceRule.cpp
=> [luci] Shape inf reduce LOC M-R

compiler/luci/logex/src/FormattedGraph.cpp
This will relocate implementation of summary builder to reduce class LOC
=> [luci] SummaryBuilder reduce LOC 1

compiler/luci/service/src/CircleShapeInferenceRule.cpp
=> [luci] Shape inf reduce LOC S-

compiler/luci/logex/src/FormattedGraph.cpp
This will relocate implementation of summary builder to reduce class LOC
=> [luci] SummaryBuilder reduce LOC 2

tests/nnfw_api/CMakeLists.txt, tests/nnfw_api/src/GenModelTest.h, tests/nnfw_api/src/one_op_tests/Add.cc, tests/nnfw_api/src/one_op_tests/AveragePool2D.cc, tests/nnfw_api/src/one_op_tests/Cos.cc, tests/nnfw_api/src/one_op_tests/L2Normalization.cc, tests/nnfw_api/src/one_op_tests/Pad.cc, tests/nnfw_api/src/one_op_tests/PadV2.cc
- Introduce backend setting method in GenModelTest
- Backend test on one_op_tests
---
part of #3896
=> [onert/test] Operation backend test on one_op_tests

compiler/luci/export/src/CircleOperationExporter.cpp
This will extract export class methods to functions to reduce class LOC
=> [luci] Extract export class methods to functions

compiler/luci/service/src/CircleShapeInferenceRule.cpp
This will provide common methods for MirrorPad, Pad and PadV2 nodes to reduce duplicate codes
=> [luci] Shape inf common for Pad

compiler/circle-quantizer/src/CircleQuantizer.cpp
This supports requantization from int8 to uint8
---
Related to #3779 Draft PR #3823
=> [circle-quantizer] Support requantization from int8 to uint8

compiler/luci/export/src/CircleOperationExporter.cpp
This will revise OperationExporter with extracting class methods to functions to reduce class LOC
=> [luci] Extract export_node to reduce class LOC 1

compiler/luci/export/src/CircleOperationExporter.cpp
This will revise OperationExporter with extracting class methods to functions to reduce class LOC
=> [luci] Extract export_node to reduce class LOC 2

runtime/onert/backend/acl_cl/KernelGenerator.cc, runtime/onert/backend/acl_common/AclKernelGen.h, runtime/onert/backend/acl_neon/KernelGenerator.cc
This commit makes acl's KernelGenerators use generateLayer for reducing duplicated codes.
=> [onert] Make acl's KernelGenerators use generateLayer

runtime/onert/core/src/exec/feature/nchw/Reader.h, runtime/onert/core/src/exec/feature/nchw/View.h, runtime/onert/core/src/exec/feature/nhwc/Reader.h, runtime/onert/core/src/exec/feature/nhwc/View.h
For issue #3625 
This commit removes duplicated codes from Reader/View for shape::feature.
=> [onert] Remove duplicated codes from Reader/View for shape::feature

tests/nnfw_api/src/GenModelTest.h, tests/nnfw_api/src/one_op_tests/Add.cc, tests/nnfw_api/src/one_op_tests/AveragePool2D.cc, tests/nnfw_api/src/one_op_tests/Cos.cc, tests/nnfw_api/src/one_op_tests/L2Normalization.cc, tests/nnfw_api/src/one_op_tests/Pad.cc, tests/nnfw_api/src/one_op_tests/PadV2.cc, tests/nnfw_api/src/one_op_tests/While.cc
- Rename `GenModelTestData` to `GenModelTestContext`
- Let `GenModelTestContext` have the backend list
=> [nnfwapi] Aggregate TestBackends into test context

compiler/souschef/include/souschef/TensorFiller.h
This will introduce TensorFiller for common of circlechef and tflchef
=> [souschef] Introduce TensorFiller

compiler/luci/pass/include/luci/CircleOptimizer.h, compiler/luci/pass/include/luci/Pass/FuseBatchNormWithTConv.h, compiler/luci/pass/src/CircleOptimizer.cpp, compiler/luci/pass/src/FuseBatchNormWithTConv.cpp
This commit introduces FuseBatchNormWithTConv pass to luci.
Draft : #3660
Related : #3565
=> [luci] Introduce FuseBatchNormWithTConv pass

infra/scripts/tizen_xu4_test.sh
Add option "--skip-test" to skip test and install package and/or model.
=> [onert/test] Skip running test on tizen_xu4_test.sh script

compiler/luci-interpreter/src/kernels/Conv2D.cpp, compiler/luci-interpreter/src/kernels/Conv2D.test.cpp, compiler/luci-interpreter/src/kernels/Utils.cpp, compiler/luci-interpreter/src/kernels/Utils.h
For #1623
This commit add negative tests on `Conv2D` kernel on luci-interpreter.
=> [luci-interpreter]Negative Tests for Conv2D kernel

runtime/onert/core/src/ir/OperationDumper.cc
This commit reduces lines of OperationDumper.
=> [onert] Reduce lines of OperationDumper

compiler/luci-interpreter/src/loader/KernelBuilder.cpp, compiler/luci-interpreter/src/loader/KernelBuilder.test.cpp
This commit adds bias attribute to TransposeConv.
Draft : #3660
Related : #3565
=> [luci-interpreter] Add bias attribute to TransposeConv

runtime/onert/backend/acl_cl/KernelGenerator.cc, runtime/onert/backend/acl_common/AclFunction.h, runtime/onert/backend/acl_common/Convert.cc, runtime/onert/backend/acl_common/Convert.h
This commit replaces AclCLFunction with AclFunction.
=> [onert] Replace AclCLFunction with AclFunction

infra/nnfw/cmake/options/options_aarch64-tizen.cmake, infra/nnfw/cmake/options/options_armv7l-tizen.cmake
Enable to build tflite_run on tizen test package
=> [onert] Enable tflite_run on tizen build

compiler/luci/export/src/CircleOperationExporter.cpp
This will revise luci exporter class to use Context class instead of individual members
=> [luci] Use context for Exporter

tools/tflitefile_tool/select_operator.py
select_operator.py can handle LeakyReluOption for leaky_relu operation
=> [tflitefile_tool] Support leaky_relu in select_operator.py

runtime/onert/backend/acl_common/Convert.cc, runtime/onert/core/include/ir/operation/ElementwiseActivation.h, runtime/onert/core/src/ir/OperationDumper.cc, runtime/onert/frontend/base_loader/include/base_loader.h, tests/nnfw_api/src/CircleGen.cc, tests/nnfw_api/src/CircleGen.h, tests/nnfw_api/src/GenModelTest.h, tests/nnfw_api/src/one_op_tests/LeakyRelu.cc
- Update ElementwiseActivation IR: type
- Model loader
- acl common backend
---
Related issue: #3575
=> [onert] Support acl backend LeakyRelu

compiler/souschef/include/souschef/Dims.h, compiler/souschef/src/Dims.cpp
This will introduce Dims related helpers, common of circlechef and tflchef
=> [souschef] Introduce Dims

tests/tools/tflite_run/src/tflite_run.cc
tflite_run set random value for uint8 input tensor
=> [onert/test] Random uint8 input value generation for tflite_run

runtime/onert/core/src/backend/controlflow/DynamicTensorManager.cc, runtime/onert/core/src/backend/controlflow/DynamicTensorManager.h, runtime/onert/core/src/backend/cpu_common/DynamicTensorManager.cc
- Refine `planDealloc` to be one-liner
- Remove comments that are no longer valid
=> [onert] Refine DynamicTensorManager impl

runtime/onert/core/src/compiler/pass/PermutationEliminationPass.cc
Change the condition of Permutation Elimination to be more general.
=> [onert] Change Permutation Elimination condition

compute/cker/include/cker/operation/optimized/BinaryArithmeticOps.h
- Optimize qasymm8 add operation cpu backend kernel
- Share with sub operation
- Optimize qasymm8 mul operation cpu backend kernel
---
Related issue: #4008
=> [onert/cpu] Optimized cpu backend kernel for quantized arithmetic operation

runtime/onert/backend/acl_cl/ConstantInitializer.cc, runtime/onert/backend/acl_cl/ConstantInitializer.h, runtime/onert/backend/acl_common/AclConstantInitializer.cc, runtime/onert/backend/acl_common/AclConstantInitializer.h, runtime/onert/backend/acl_neon/ConstantInitializer.cc, runtime/onert/backend/acl_neon/ConstantInitializer.h, runtime/onert/core/include/backend/IConstantInitializer.h
This commit merges acl's ConstantInitializer into AclConstantInitializer for reducing duplicated codes.
=> [onert] Merge acl's ConstantInitializer into AclConstantInitializer

runtime/onert/core/src/exec/feature/nchw/Reader.h, runtime/onert/core/src/exec/feature/nchw/View.h, runtime/onert/core/src/exec/feature/nhwc/Reader.h, runtime/onert/core/src/exec/feature/nhwc/View.h
This commit makes feature::View reuses feature::Reader.
=> [onert] Make feature::View reuses feature::Reader

compiler/luci/pass/src/CircleOptimizer.cpp
This clears quantparam before doing fake quantization
=> [luci] Clear quantparam before fake quantization

compiler/common-artifacts/CMakeLists.txt
This will fix recent setuptools package problem
=> [cmn-arts] fix setuptools version

res/TensorFlowPythonExamples/examples/gelu/__init__.py, res/TensorFlowPythonExamples/examples/gelu_2/__init__.py
This will add TF examples for gelu operator
=> [res] gelu TF examples

docs/howto/how-to-introduce-a-new-operation-into-runtime.md
This adds a section for shape inference into
`how-to-introduce-a-new-operation-into-runtime.md` document.
=> [docs] Add a section for shape inference into doc

infra/scripts/docker_build_nncc.sh
This commit is temporary fix of nncc docker build script.
setuptools lastest version has got some bugs as of now.
Related : #4052 
=> [infra] temporary fix of nncc docker build script

docs/release/1.9/release-note-1.9.0.md
release note for 1.9.0
Signed-off-by: twoflower <chunseoklee@gmail.com>
=> Release note 1.9.0

tools/release_tool/git_release.sh
This commit fix minor bug related string comparison.
=> [release_tool] fix bug

compiler/luci/pass/include/luci/Pass/PropagateConcatenationQparamPass.h, compiler/luci/pass/src/CircleOptimizer.cpp, compiler/luci/pass/src/PropagateConcatenationQparamPass.cpp, compiler/luci/pass/src/PropagateConcatenationQparamPassInternal.h
This propagates concat qparam to its inputs
---
Related to #4004 Draft PR #4029
=> [luci] Propagate concat qparam to its inputs

compiler/vconone/CMakeLists.txt
This will revise vconone version to 1.10.0
=> [compiler] bump version to 1.10.0

compiler/luci/pass/src/PropagateConcatenationQparamPass.test.cpp
This is a test for concat qparam propagation
---
Related to #4004 Draft PR #4029
=> [luci] Test for concat qparam propagation

runtime/onert/core/src/exec/IPermuteFunction.h, tests/nnfw_api/src/CircleGen.cc, tests/nnfw_api/src/CircleGen.h, tests/nnfw_api/src/one_op_tests/If.cc
=> [nnfwapi] Test: Add a OneOp TC for If

docs/conf.py, packaging/nnfw.spec, runtime/contrib/android/api/build.gradle, runtime/onert/api/include/nnfw_version.h
=> Update version to 1.10.0

compiler/luci-interpreter/src/kernels/FullyConnected.cpp, compiler/luci-interpreter/src/kernels/FullyConnected.h, compiler/luci-interpreter/src/kernels/FullyConnected.test.cpp, compiler/luci-interpreter/src/kernels/Utils.h
This commit add Uint8 case `Fullyconnected` kernel.
=> [luci-interpreter]Add Uint8 Fullyconnected kernel.

docs/howto/how-to-build-compiler.md
This will fill initial version of how to build compiler document
=> [docs] How to build compiler

res/TensorFlowLiteRecipes/LogSoftmax_U8_000/test.recipe
Fired Issue: #4119 
This commit enable U8 recipe for LogSoftmax_000 Op.
Thank you.
=> [res/TensorFlowLiteRecipes] Add LogSoftmax_U8_000

compiler/luci-interpreter/src/kernels/DepthToSpace.cpp, compiler/luci-interpreter/src/kernels/DepthToSpace.test.cpp
for #1623 
This commit add Negative case for `DepthToSpace` kernel and update kernel implementaion.
=> [luci-interpreter]Negative Tests for DepthToSpace kernel

runtime/onert/backend/cpu/ops/FullyConnectedLayer.cc, runtime/onert/core/include/backend/IPortableTensor.h, runtime/onert/core/include/backend/cpu_common/Tensor.h, runtime/onert/core/include/ir/Sparsity.h, runtime/onert/core/include/ir/TypeInfo.h, runtime/onert/frontend/base_loader/include/base_loader.h
Sparsity has several members. It will have its own structure.
=> [onert] introduce ir::Sparsity

compiler/luci-interpreter/src/kernels/Prelu.cpp, compiler/luci-interpreter/src/kernels/Prelu.test.cpp
This enables broadcast in Prelu kernel
=> [luci-interpreter] Enable broadcast of Prelu

tests/nnfw_api/src/CircleGen.cc, tests/nnfw_api/src/CircleGen.h, tests/nnfw_api/src/one_op_tests/Split.cc
Add OneOp Split test
- Constant axis
- Non-constant axis
=> [onert/test] OneOp Split test

tests/scripts/models/nnfw_api_gtest/add_unspecified_rank_inputs/config.sh, tests/scripts/models/nnfw_api_gtest/input_reshaping_add/config.sh, tests/scripts/models/nnfw_api_gtest/neg/config.sh, tests/scripts/models/nnfw_api_gtest/unknown_dim_input_concat/config.sh
Remove unused model config files
=> [nnfwapi] Test : Remove unused model config files

tests/nnfw_api/README.md
- Update section Installation
- Add notice
=> [nnfwapi] Test : Update instruction

docs/howto/how-to-build-package.md
This commit will add an example for BCQ model
=> [docs] Add an example for BCQ model

compute/ARMComputeEx/src/runtime/CL/functions/CLReduceOperation.cpp
- Fix coverity 1148326
Change-Id: I98d2ff22050078bd8a392a58904b968965c1c46d
=> Fix coverity 1148326

tests/scripts/benchmark.sh
=> Script to benchamrk adb/sdb target on host

compiler/luci-interpreter/src/kernels/FullyConnected.test.cpp
This commit add test cases for `FullyConnected` kernel.
=> [luci-interpreter]Add negative test cases for FullyConnected kernel

infra/nnfw/cmake/packages/BoostConfig.cmake
Introduce boost build and install stamp
- Avoid build duplication
- Check installed boost version on overlay
=> [onert] Boost build and install stamp

runtime/onert/core/src/backend/controlflow/kernel/IfLayer.cc, runtime/onert/core/src/backend/controlflow/kernel/WhileLayer.cc, runtime/onert/core/src/exec/IPermuteFunction.h, tests/nnfw_api/src/CircleGen.cc, tests/nnfw_api/src/CircleGen.h, tests/nnfw_api/src/one_op_tests/If.cc
- Log subgraph calls during execution so we can trace the execution stack.
- Add a OneOp TC for If
This is a squashed commit of 465828c0 8aba0221 and 117a4712 .
=> [1.9.0] [onert] Add logging and test cases for Controlflow ops

docs/howto/how-to-build-runtime-tizen-gbs-rpi4.md, docs/howto/index.rst
This will introduce how to build runtine in GBS for Tizen/AARCH64 and run in RPi4
=> [docs] How to build runtime tizen gbs rpi4

runtime/onert/backend/acl_cl/KernelGenerator.cc, runtime/onert/backend/acl_neon/KernelGenerator.cc, runtime/onert/backend/cpu/ops/TransposeLayer.cc, runtime/onert/core/src/compiler/OperationValidator.cc, runtime/onert/core/src/compiler/StaticShapeInference.cc, runtime/onert/core/src/exec/DynamicShapeInference.cc, runtime/onert/core/src/util/ShapeInference.cc, runtime/onert/frontend/nnapi/execution.cc, tests/nnapi/nnapi_gtest.skip.aarch64-linux.acl_cl, tests/nnapi/nnapi_gtest.skip.aarch64-linux.acl_neon, tests/nnapi/nnapi_gtest.skip.aarch64-linux.cpu, tests/nnapi/nnapi_gtest.skip.armv7l-linux.acl_cl, tests/nnapi/nnapi_gtest.skip.armv7l-linux.acl_neon, tests/nnapi/nnapi_gtest.skip.armv7l-linux.cpu, tests/nnapi/nnapi_gtest.skip.x86_64-linux.cpu, tests/nnfw_api/src/CircleGen.cc, tests/nnfw_api/src/CircleGen.h, tests/nnfw_api/src/GenModelTest.h, tests/nnfw_api/src/one_op_tests/Transpose.cc
For #4053
This commit makes Transpose operation supports regular transpose.
- Support regular transpose
- Add nnfw tests for Transpose op
- Enable some nnapi tests for regular transpose
=> [onert] Support regular transpose with Transpose op

infra/packaging/res/tf2nnpkg.20200630
Until now, user should proceed some steps manually for applying BCQ.
This commit will update `tf2nnpkg` to do it automatically.
=> [release/1.9.0][infra] Update tf2nnpkg to apply BCQ automatically

compiler/luci/pass/src/QuantizationUtils.cpp, compiler/luci/pass/src/QuantizationUtils.h, compiler/luci/pass/src/QuantizeDequantizeWeightsPass.cpp, compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
This supports quantization of constant inputs
=> [luci] Support quantization of const inputs

compiler/luci-interpreter/src/kernels/If.cpp, compiler/luci-interpreter/src/kernels/If.test.cpp
For #1623 
This commit add negative cases for  `If` kernel on luci-interpreter.
=> [luci-interpreter]Add negative cases for If kernel

docs/release/1.9/release-note-1.9.1.md
This commit contains a 1.9.1 compiler release note.
Related : #4181
=> [release] 1.9.1 compiler release note

runtime/onert/core/include/backend/cpu_common/DynamicTensorManager.h, runtime/onert/core/include/backend/cpu_common/MemoryManager.h, runtime/onert/core/src/backend/controlflow/DynamicTensorManager.cc, runtime/onert/core/src/backend/controlflow/DynamicTensorManager.h, runtime/onert/core/src/backend/cpu_common/DynamicTensorManager.cc, runtime/onert/core/src/backend/cpu_common/MemoryManager.cc, runtime/onert/core/src/backend/cpu_common/StaticTensorManager.cc
Change key type to pointer as we are changing it to work without index.
Draft : #4175
=> [onert] Revise DynamicMemoryManager

runtime/onert/core/src/compiler/StaticShapeInference.cc, runtime/onert/core/src/exec/DynamicShapeInference.cc, runtime/onert/core/src/util/ShapeInference.cc, tests/nnfw_api/src/CircleGen.cc, tests/nnfw_api/src/CircleGen.h, tests/nnfw_api/src/one_op_tests/ArgMax.cc
For issue #4053
This commit adds nnfw_api tests for ArgMax.
=> [onert] Add nnfw_api tests for ArgMax

infra/nnfw/cmake/options/options_aarch64-android.cmake, infra/nnfw/cmake/packages/ARMComputeConfig.cmake
Enable android acl build from source code
=> [onert] Enable android acl build

docs/release/1.9/release-note-1.9.1.md
This commit updates 1.9 release note.
=> [release] Update 1.9 release note

compiler/luci-interpreter/src/kernels/Relu.test.cpp
* Make input data for quantized tests float (like in all other tests).
* Use `makeInputTensors` instead of `writeData`.
* Remove one duplicated test.
* Add output shape check to two tests.
=> [luci-interpreter] Rework Relu tests

compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
This supports quantization of reshape Op
=> [luci] Support quantization of reshape Op

compiler/one-cmds/one-quantize
This fixes invalid input arguments
=> [one-cmds] Fix invalid input arguments

compiler/one-cmds/one-import-bcq
This commit will add invalid input arguments handling codes
=> [one-cmds] Handling invalid input arguments

compiler/one-cmds/one-import-bcq
This commit will add invalid input arguments handling codes
=> [release/1.9.0][one-cmds] Handling invalid input arguments

compiler/record-minmax/src/HDF5Importer.h
This commit will add error handling code when data file is not HDF5.
=> [release/1.9.0][record-minmax] Handling error when data file is not HDF5

compiler/record-minmax/src/HDF5Importer.h
This commit will revise error message
=> [record-minmax] Revise error msg

infra/cmake/packages/RuySourceConfig.cmake, infra/nnfw/cmake/packages/RuyConfig.cmake
Move RuySource download cmake into infra/cmake/packages
---
Related issue: #1726
=> [infra] Move RuySource download cmake

res/TensorFlowLiteRecipes/Add_002/test.recipe, res/TensorFlowLiteRecipes/Concatenation_001/test.recipe, res/TensorFlowLiteRecipes/Mul_001/test.recipe, res/TensorFlowLiteRecipes/PRelu_001/test.recipe
This adds TFLiteRecipes for Ops with const input
=> [res] TFLiteRecipes for Ops with const input

compiler/luci/pass/src/PropagateConcatenationQparam.test.cpp, compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
This quantizes const input of concat
=> [luci] Quantize const input of concat

compiler/luci/import/src/Nodes/CircleConst.cpp
This commit revises the comments in create_circleconst method.
Related : #4024
=> [luci] Revise the comments in create_circleconst method

compiler/record-minmax-conversion-test/gen_h5_random_inputs.py
This generates random inputs including negative numbers
=> [record-minmax] Generate random inputs including neg numbers

runtime/onert/core/src/exec/DynamicShapeInference.cc
=> [onert] Fixing DynamicShapeInference of ArgMax

compiler/circledump/src/Dump.cpp
This commit enables circledump to dump sparse parameters.
Draft : #4190 
=> [circledump] Dump sparsity

compiler/tflchef/proto/tflchef.proto
This commit enables tflchef to cook sparsity parameters.
Draft : #4190
=> [tflchef] Cook sparsity

tests/nnfw_api/src/CircleGen.h
Make CircleGen addOperatorXXX sorted in alphabetical order.
=> [nnfwapi] Make CircleGen addOperatorXXX sorted

runtime/onert/backend/cpu/ops/ResizeBilinearLayer.cc, runtime/onert/core/src/util/ShapeInference.cc, tests/nnfw_api/src/CircleGen.cc, tests/nnfw_api/src/CircleGen.h, tests/nnfw_api/src/one_op_tests/ResizeBilinear.cc
For #4053, #4115
This commid adds nnfw_api tests for ResizeBilinear.
=> [onert] Add nnfw_api tests for ResizeBilinear

compiler/luci/lang/include/luci/IR/SparsityParam.h
This commit introduces SparsityParam.
Draft : #4190 
=> [luci] Introduce SparsityParam

compiler/luci/import/include/luci/Import/CircleReader.h, compiler/luci/import/src/CircleReader.cpp, compiler/luci/import/src/Nodes/CircleConst.cpp, compiler/luci/lang/include/luci/IR/CircleNodeDecl.h
This commit adds sparsity-related function.
Draft : #4190
=> [luci] Add sparsity-related function

compiler/tflchef/core/src/Convert.cpp, compiler/tflchef/core/src/Convert.h, compiler/tflchef/core/src/ModelChef.cpp
This commit enables tflchef to support sparsity.
Draft : #4190
=> [tflchef] Support sparsity

tools/release_tool/git_release.sh
This commit enables it to upload assets via its URL.
=> [release_tool] Support asset_url option

compiler/tflchef/tflite/src/Convert.cpp, compiler/tflchef/tflite/src/Convert.h, compiler/tflchef/tflite/src/RecipeChef.cpp
This commit enables recipechef to support sparsity.
Draft : #4190
=> [tflchef] Support sparsity of recipechef

tests/nnfw_api/src/CircleGen.cc, tests/nnfw_api/src/CircleGen.h, tests/nnfw_api/src/one_op_tests/Tile.cc
Add Tile one-op test
- 2 positive tests (1 disabled)
- 1 negative test
=> [nnfwapi] Test : Add Tile one-op test

res/TensorFlowLiteRecipes/FullyConnected_004/test.recipe
This commit adds FullyConnected network that contains sparse tensor.
Draft : #4190
=> [res] Add FullyConnected network that contains sparse tensor

compute/cker/include/cker/operation/FullyConnected.h, compute/cker/include/cker/operation/FullyConnectedSparse16x1.h, runtime/onert/backend/cpu/ops/FullyConnectedLayer.cc
It adds fullyconnected 16x1 bcsr kernel based on lpcnet code.
=> [onert] add sparse fullyconnected 16x1 kernel

compiler/souschef/include/souschef/Dims.h
This commit adds missing header in souschef.
=> [souschef] Add missing header

docs/howto/how-to-build-compiler.md
This commit updates the document about how to build compiler for
Windows.
Related : #4122 
=> [docs] How to build compiler for Windows

compiler/luci-interpreter/src/kernels/Softmax.cpp, compiler/luci-interpreter/src/kernels/Softmax.h, compiler/luci-interpreter/src/kernels/Softmax.test.cpp
For #3458 
This commit add UINT8 handling on `Softmax` kernel.
=> [luci-interpreter]Add Uint8 for Softmax kernel

runtime/onert/core/src/compiler/LoweredGraph.cc, runtime/onert/core/src/compiler/pass/PassRunner.cc, runtime/onert/core/src/compiler/pass/PassRunner.h
Introduce a utility class PassRunner.
- `PassRunner` is a composite class of `Pass`es
- This class is for grouping some passes and dumping the graph after
each pass
=> [onert] Introduce PassRunner

tests/nnfw_api/src/CircleGen.cc, tests/nnfw_api/src/CircleGen.h, tests/nnfw_api/src/one_op_tests/LogSoftmax.cc
Add LogSoftmax test cases, 1 positive 1 negative.
=> [nnfwapi] Test : Add LogSoftmax test cases

infra/scripts/docker_build_nncc.sh
Virtual environment will be created on test server
=> [infra] Remove creating virtual env on compiler package generation

compute/cker/include/cker/operation/FullyConnectedSparse16x1.h
It will introduce NEON implementation for 16x1 block sparsity fullyconnected.
=> [onert] introduce FullyConnectedSparseWeight16x1 NEON kernel

compiler/tflchef/tflite/src/Op/FullyConnected.cpp
This commit implements fullyConnected filler.
=> [tflchef] Implement FullyConnected filler

infra/nnfw/command/count-unittest
- Fix that positive TC count was actually negatives
- Pretty-print numbers
=> [infra] Fix nnfw command 'count-unittest'

compiler/tflchef/tflite/src/Op/FullyConnected.cpp
This commit revies FullyConnected filler.
=> [qtflchef] Revise FullyConnected filler

tools/release_tool/onert_version.sh
Show version with nightly suffix - latest commit's date
=> [tools] Version info for nightly

tests/scripts/common_android.sh, tests/scripts/models/run_test_android.sh, tests/scripts/test_scheduler_with_profiling_android.sh
This will introduce test_scheduler_with_profiling and related scripts for Android
=> [tests] Scheduler profile for Android

compiler/luci/export/src/CircleExporterUtils.cpp, compiler/luci/import/src/CircleReader.cpp, compiler/luci/lang/include/luci/IR/AttrFusedActFunc.h, compiler/luci/logex/src/FormattedGraph.cpp
This commit add `TANH` and `SIGN_BIT` on FusedActFunc and ActivationFunctionType
ONE-DCO-1.0-Signed-off-by: KiDeuk Bang rrstrous@nate.com
=> [luci]Add FusedActFunc and ActivationFunctionType

compute/ARMComputeEx/arm_compute/core/NEON/kernels/NECastBoolKernel.h, compute/ARMComputeEx/arm_compute/runtime/NEON/NEFunctionsEx.h, compute/ARMComputeEx/arm_compute/runtime/NEON/functions/NECastBool.h, compute/ARMComputeEx/src/core/NEON/kernels/NECastBoolKernel.cpp, compute/ARMComputeEx/src/runtime/NEON/functions/NECastBool.cpp, runtime/onert/backend/acl_neon/KernelGenerator.cc, tests/nnfw_api/src/one_op_tests/Cast.cc
For issue #4309
This commit adds an acl_neon kernel for Cast op with bool input.
=> [onert] Adds an acl_neon kernel for Cast op with bool input

runtime/onert/api/CMakeLists.txt, runtime/onert/frontend/circle/CMakeLists.txt, runtime/onert/frontend/tflite/CMakeLists.txt, tests/tools/nnpackage_run/CMakeLists.txt
Remove unnecessary dependencies of nnpackage_run.
=> [nnpkg_run] Remove unnecessary deps

runtime/onert/api/CMakeLists.txt
Link log to nnfw-dev: same with onert-core
=> [onert] Android build fail fix

runtime/onert/frontend/base_loader/include/base_loader.h, tests/nnfw_api/src/one_op_tests/Add.cc
Add "Add" operation tests - 1 positive / 3 negative.
=> [nnfwapi] Test : Add "Add" operation tests

runtime/onert/backend/cpu/Tensor.h, runtime/onert/core/include/backend/cpu_common/Tensor.h
- Add functions needed to unused-tensor's early release nnfw#11749
=> [onert] Add Tensor's reference count interfaces

runtime/onert/core/src/compiler/HEScheduler.cc
HEScheduler : Tune a parameter to be optimized for Odroid XU4.
=> [onert] HEScheduler : Tune param for Odroid XU4

compiler/luci/pass/src/FuseBatchNormWithTConv.cpp
This fixes channel index in FuseBatchNormWithTConvPass
---
Draft PR: #4351
=> [luci] Fix channel index in FuseBatchNormWithTConvPass

compiler/luci-interpreter/src/kernels/LeakyRelu.cpp, compiler/luci-interpreter/src/kernels/LeakyRelu.test.cpp
This commit Update test case for `LeakyRelu` on luci-interpreter.
1. Add Uint8 Test Case.
2. Add Negative Test Case.
=> [luci-interpreter]Add test case for LeakyRelu

compiler/luci-interpreter/src/kernels/LocalResponseNormalization.cpp, compiler/luci-interpreter/src/kernels/LocalResponseNormalization.test.cpp
This commit add negative test case for `LocalResponseNormalizaion` Kernel.
=> [luci-interpreter]Add negative case for LocalResponseNormalizaion

compiler/luci-interpreter/src/kernels/Logistic.cpp, compiler/luci-interpreter/src/kernels/Logistic.test.cpp
This commit update test case for `Logistic` on luci-interpreter
1. Add Uint8 Test case.
2. Add Negative Test case.
=> [luci-interpreter]Update test case for Logistic

docs/runtime/api.md, docs/runtime/backend-api.md
This commit fills out document `backend-api.md`.
=> [onert/docs] Write backend-api.md

compiler/common-artifacts/exclude.lst
This will remove Unique op from exclude list as it works
=> [cmn-art] enable Unique optimize

runtime/onert/backend/acl_common/AclSubTensorAnalyzer.h, tests/nnfw_api/src/one_op_tests/Concat.cc
This commit add condition to make concat subtensor
ONE-DCO-1.0-Signed-off-by: HyoJong Kim <hue.kim@samsung.com>
=> [onert] Add condition to make concat subtensor for acl_cl backend

compiler/luci/import/include/luci/Import/Nodes.h, compiler/luci/import/include/luci/Import/Nodes/CircleDequantize.h, compiler/luci/import/src/GraphBuilderRegistry.cpp, compiler/luci/import/src/Nodes/CircleDequantize.cpp
Draft : #4374
This commit is for supporting to import `Dequantize` operation in `luci`
=> [luci] Supporting to import Dequantize

compiler/luci/export/src/CircleOperationExporter.cpp
Draft : #4374
This commit is for supporting to export `Dequantize` operation in `luci`
=> [luci] Supporting to export Dequantize

compiler/luci/service/src/CircleShapeInferenceRule.cpp, compiler/luci/service/src/CircleTypeInferenceRule.cpp
Draft : #4374
This commit will introduce `luci/service` for `Dequantize` Operation.
=> [luci] Introduce luci service for Dequantize Operation

res/TensorFlowLiteRecipes/Net_TConv_Add_000/test.recipe, res/TensorFlowLiteRecipes/Net_TConv_Add_000/test.rule, res/TensorFlowLiteRecipes/Net_TConv_Add_001/test.recipe, res/TensorFlowLiteRecipes/Net_TConv_Add_001/test.rule, res/TensorFlowLiteRecipes/Net_TConv_Add_002/test.recipe, res/TensorFlowLiteRecipes/Net_TConv_Add_002/test.rule
This adds recipes and test rules for FuseAddWithTConvPass
---
Draft PR: #4375
=> [res] Add recipe and test rule for FuseAddWithTConvPass

compiler/luci/pass/include/luci/CircleOptimizer.h, compiler/luci/pass/include/luci/Pass/FuseAddWithTConvPass.h, compiler/luci/pass/src/CircleOptimizer.cpp, compiler/luci/pass/src/FuseAddWithTConvPass.cpp
This fuses Add Op with TConv Op
---
Draft PR: #4375
=> [luci] Fuse Add Op with TConv Op

compute/cker/include/cker/operation/SoftMax.h, runtime/onert/backend/cpu/ops/SoftMaxLayer.cc
Support 3D dimension for SoftMax as well as does 1D, 2D and 4D.
=> [cker] Support SoftMax Op for 3D dimension

compiler/circle2circle/src/Circle2Circle.cpp
This adds --fuse_add_with_tconv option
---
Draft PR: #4375
=> [circle2circle] Fuse add with tconv

tests/scripts/models/run_test.sh
Flatten TFLite model cache directory structure
Cache directory will be same directory structure with server
=> [onert/test] Flattened cache directory contents

compiler/luci-interpreter/src/kernels/LogSoftmax.test.cpp
This commit Add negative test case for `Logsoftmax` on luci-interpreter.
=> [luci-interpreter]Add negative case for Logsoftmax

compute/ARMComputeEx/src/core/CL/cl_kernels/arg_min_max_ex.cl
Add copyright to arg_min_max_ex.cl
=> [armcl-ex] Add copyright to arg_min_max_ex.cl

runtime/onert/core/src/compiler/Compiler.cc, runtime/onert/core/src/compiler/OperationValidator.cc, runtime/onert/core/src/compiler/OperationValidator.h, runtime/onert/core/src/compiler/ShapeValidator.cc, tests/nnfw_api/src/one_op_tests/LeakyRelu.cc
Introduce OperationValidator to check shape independent feature
Move shape independent check for ElementwiseActivation
Add negative test for LeakyRelu
---
Part of #4348
=> [onert] Introduce OperationValidator

compiler/tflchef/core/src/ModelChef.cpp, compiler/tflchef/proto/tflchef.proto, compiler/tflchef/tflite/src/RecipeChef.cpp
For #4396 
This commit add `is_variable` option on recipe for tflchef.
=> [tflchef]Add is_variable on tflchef operand

compiler/luci/logex/src/FormattedGraph.cpp
Parent Issue : #4382
Draft : #4374
This commit will introduce `Dequantize` in `luci/logex`
=> [luci] Introduce Dequantize in luci logex

compiler/tfldump/src/OpPrinter.cpp
Parent Issue : #4382
Draft : #4374
This commit will add a comment for `Dequantize` operation
=> [tfldump] Add a comment for Dequantize Operation

Makefile.template
Rename package tar nnfw-* to onert-*
=> [onert] Rename package tar

runtime/onert/core/src/ir/OperationDumper.cc, runtime/onert/core/src/ir/OperationDumper.h
- added BCQFC's operation dumper
=> [onert] Add BCQFC OperationDumper

Makefile.template
=> [onert] Fix package name typo

runtime/contrib/android/api/src/main/native/onert-native-api.cpp
Fix typo, change function name in log message.
Signed-off-by: Jaeyun <jy1210.jung@samsung.com>
=> [onert] Fix typo in log message

compiler/luci-interpreter/src/kernels/CMakeLists.txt, compiler/luci-interpreter/src/kernels/Floor.cpp, compiler/luci-interpreter/src/kernels/Floor.h, compiler/luci-interpreter/src/kernels/Floor.test.cpp, compiler/luci-interpreter/src/loader/KernelBuilder.cpp, compiler/luci-interpreter/src/loader/KernelBuilder.h, compiler/luci-interpreter/src/loader/KernelBuilder.test.cpp
Add support for Floor op in luci-interpreter.
For #1612
=> [luci-interpreter] Support for Floor op

runtime/nnapi-header/include/NeuralNetworks.h, runtime/nnapi-header/include/NeuralNetworksExtensions.h
Update NNAPI header: android-11.0.0_r3
---
Related issue: #4391
=> [onert] Update NNAPI header

tests/nnfw_api/src/CircleGen.cc, tests/nnfw_api/src/CircleGen.h, tests/nnfw_api/src/one_op_tests/FullyConnected.cc
It introduces SparsityParams and its child structures in CircleGen also.
=> [nnfw_api] Introduce FullyConnected16x1 sparsity testcase

tests/nnfw_api/src/GenModelTest.h
Show output index and element number
=> [onert/test] More fail message

compiler/bcq-tools/generate_bcq_output_arrays
This commit will revise `generate_bcq_output_arrays` to prepare new BCQ applying method.
- Update function and copyright
- Remove unused function
- Introduce new functions
=> [bcq-tools] Revise generate_bcq_output_arrays

compiler/luci/lang/src/Nodes/CircleDequantize.test.cpp
Parent Issue : #4382
Draft : #4374
This commit will add test cases in luci/lang for `CircleDequantize`
=> [luci] Add CircleDequantize test cases

compiler/luci-interpreter/src/kernels/CMakeLists.txt, compiler/luci-interpreter/src/kernels/FloorDiv.cpp, compiler/luci-interpreter/src/kernels/FloorDiv.h, compiler/luci-interpreter/src/kernels/FloorDiv.test.cpp, compiler/luci-interpreter/src/loader/KernelBuilder.cpp, compiler/luci-interpreter/src/loader/KernelBuilder.h, compiler/luci-interpreter/src/loader/KernelBuilder.test.cpp
Add support for FloorDiv op in luci-interpreter.
For #1612
=> [luci-interpreter] Support for FloorDiv op

compiler/record-minmax/src/HDF5Importer.h
This will remove "Error:" prefix as safemain will append "ERROR:" prefix
=> [record-minmax] Revise error msg again

compiler/luci/pass/include/luci/CircleOptimizer.h, compiler/luci/pass/include/luci/Pass/FoldDequantizePass.h, compiler/luci/pass/src/CircleOptimizer.cpp, compiler/luci/pass/src/FoldDequantizePass.cpp
Draft : #4374
This commit will introduce `FoldDequantize` pass in `luci`.
=> [luci] Introduce FoldDequantize pass in luci

res/TensorFlowLiteRecipes/Dequantize_000/test.recipe
Parent Issue : #4382
Draft : #4374
This commit will add a recipe for `Dequantize` opeartion
=> [res] Add recipe for Dequantize operation

compiler/circle2circle/src/Circle2Circle.cpp
Draft : #4374
This commit will introduce `FoldDequantize` pass in `circle2circle`
=> [circle2circle] Introduce FoldDequantize pass in circle2circle

compiler/luci/pass/src/CircleOptimizer.cpp, compiler/luci/pass/src/PropagateConcatenationQparam.test.cpp, compiler/luci/pass/src/QuantizationUtils.cpp, compiler/luci/pass/src/QuantizationUtils.h, compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
This supports channel-wise INT16 quantization
---
Related to: #4444 
Draft PR: #4445
=> [luci] Support channel-wise INT16 quantization

infra/nnfw/cmake/buildtool/config/config_x86_64-tizen.cmake, infra/nnfw/cmake/options/options_x86_64-tizen.cmake, packaging/nnfw.spec
=> [onert/gbs] Enable x86_64 gbs build

compiler/bcq-tools/CMakeLists.txt, compiler/bcq-tools/README.md, compiler/bcq-tools/generate_bcq_metadata
This commit will introduce new metadata generator, `generate_bcq_metadata`
=> [bcq-tools] Introduce metadata generator

compiler/luci/pass/src/FuseBCQPass.cpp
This commit will remove variables and functions which will not be used for later.
=> [luci] Remove unused variable and function

compiler/one-cmds/one-quantize
This adds support for INT16 quantized dtype
---
Related to: #4444 
Draft PR: #4445
=> [one-cmds] Support INT16 quantized dtype

compiler/one-cmds/tests/prepare_test_materials.sh
This will introduce a script to download test materials
=> [one-cmds] Script to download for test materials

compiler/one-cmds/tests/README.txt
This will introduce README file for one-cmds installation test
=> [one-cmds] Test README file

compiler/one-cmds/tests/one-import_001.test, compiler/one-cmds/tests/one-import_neg_001.test, compiler/one-cmds/tests/one-import_neg_002.test, compiler/one-cmds/tests/one-import_neg_003.test, compiler/one-cmds/tests/one-import_neg_004.test, compiler/one-cmds/tests/one-import_neg_005.test, compiler/one-cmds/tests/one-import_neg_006.test, compiler/one-cmds/tests/one-import_neg_007.test, compiler/one-cmds/tests/one-import_neg_008.test, compiler/one-cmds/tests/one-import_neg_009.test, compiler/one-cmds/tests/one-import_neg_010.test
This will introduce test scripts for one-import
=> [one-cmds] Tests for one-import

compiler/one-cmds/tests/one-optimize_001.test, compiler/one-cmds/tests/one-optimize_neg_001.test, compiler/one-cmds/tests/one-optimize_neg_002.test, compiler/one-cmds/tests/one-optimize_neg_003.test
This will introduce test scripts for one-optimize
=> [one-cmds] Tests for one-optimize

compiler/one-cmds/tests/one-pack_001.test, compiler/one-cmds/tests/one-pack_neg_001.test, compiler/one-cmds/tests/one-pack_neg_002.test, compiler/one-cmds/tests/one-pack_neg_003.test
This will introduce test scripts for one-pack
=> [one-cmds] Tests for one-pack

compiler/one-cmds/tests/one-quantize_001.test, compiler/one-cmds/tests/one-quantize_neg_001.test, compiler/one-cmds/tests/one-quantize_neg_002.test, compiler/one-cmds/tests/one-quantize_neg_003.test, compiler/one-cmds/tests/one-quantize_neg_004.test, compiler/one-cmds/tests/one-quantize_neg_005.test, compiler/one-cmds/tests/one-quantize_neg_006.test, compiler/one-cmds/tests/one-quantize_neg_007.test, compiler/one-cmds/tests/one-quantize_neg_008.test, compiler/one-cmds/tests/one-quantize_neg_009.test, compiler/one-cmds/tests/one-quantize_neg_010.test, compiler/one-cmds/tests/one-quantize_neg_011.test, compiler/one-cmds/tests/one-quantize_neg_012.test, compiler/one-cmds/tests/one-quantize_neg_013.test
This will introduce test scripts for one-quantize
=> [one-cmds] Tests for one-quantize

res/TensorFlowLiteRecipes/FullyConnected_005/test.recipe
This commit introduces FullyConnected_005 network for testing  sparsifier.
Draft: #4394 
=> [res] Introduce FullyConnected_005

compiler/luci/import/src/CircleReader.cpp, compiler/luci/lang/include/luci/IR/SparsityParam.h
This commit revises sparsity parameter.
Draft: #4394
=> [luci] Revise SparsityParam

runtime/onert/frontend/nnapi/wrapper/ANeuralNetworksModel.test.cc
- Move the test code to the same folder with implementation
- Make the test negative
=> [onert] Refine NNAPI implementation unit test

infra/scripts/docker_build_nncc.sh
Divide compiler test package from release package
=> [infra/package] Divide compiler test package

runtime/onert/core/src/util/ShapeInference.cc, runtime/onert/test/util/ShapeInference.cc
- Add negative tests
- Turn 1 positive test into negative
=> [onert] Add ShapeInference negative tests

compiler/one-cmds/tests/CMakeLists.txt, compiler/one-cmds/tests/README.txt, compiler/one-cmds/tests/prepare_test_materials.sh
Allow to call test script without changing current directory
=> [one-cmds] Allow to call test script from outside test directory

compiler/bcq-tools/generate_bcq_output_arrays
This commit will implement following things
- Introduce new arguments
- Implement BCQ version finding function
- Implement BCQ output arrays printing function when BCQ information is not found
=> [bcq-tools] Implement some unimplemented functions

compiler/bcq-tools/generate_bcq_output_arrays
This commit will implement new function to pring new output arrays for BCQ
=> [bcq-tools] Printing new output arrays for BCQ

tests/nnfw_api/src/one_op_tests/While.cc
Add a While operation test with two inputs.
=> [nnfwapi] Add a While test

compiler/luci/pass/include/luci/CircleOptimizer.h, compiler/luci/pass/include/luci/Pass/SparsifyTensorPass.h, compiler/luci/pass/src/CircleOptimizer.cpp, compiler/luci/pass/src/SparsifyTensorPass.cpp
This commit introduces SparsifyTensorPass to luci.
Draft: #4394
=> [luci] Introduce SparsifyTensorPass

infra/packaging/res/tf2nnpkg.20200630
This commit will update `tf2nnpkg` for applying BCQ
=> [infra] Update tf2nnpkg for applying BCQ

compiler/common-artifacts/exclude.lst
Parent Issue : #4151
Draft PR : #4260
This commit add `UnidirectionalSequenceLSTM` to exclusion list using TC generation.
=> [common-artifacts]Exclude from example creation.

compiler/bcq-tools/generate_bcq_output_arrays
This commit will fix wrong argument name
=> [bcq-tools] Fix wrong argument name

compiler/circle2circle/src/Circle2Circle.cpp
This commit adds sparsify-related option to circle2circle.
Draft: #4394
=> [circle2circle] Add sparsify-related option

compiler/bcq-tools/generate_bcq_output_arrays
This commit will fix wrongly inserted elements
=> [bcq-tools] Fix wrong elements

compiler/luci/logex/src/FormattedGraph.cpp
Parent Issue : #4151
Draft PR : #4260
Thic commit add log for UnidirectionslSequenceLSTM.
=> [luci/logex]Add log for UnidirectionalSequenceLSTM on luci/logex

compiler/luci/import/include/luci/Import/Nodes.h, compiler/luci/import/include/luci/Import/Nodes/CircleUnidirectionalSequenceLSTM.h, compiler/luci/import/src/GraphBuilderRegistry.cpp, compiler/luci/import/src/Nodes/CircleUnidirectionalSequenceLSTM.cpp
Parent Issue : #4151
Draft PR : #4260
This commit add `UnidirectionalSequenceLSTM` on luci/import
=> [luci/import]Add UnidirectionalSequenceLSTM on luci/import

compiler/luci/pass/src/FuseBCQPass.cpp
This commit will add more validation for BCQ information
=> [luci] Check more validation for BCQ information

compiler/one-cmds/one-import-bcq
This commit will update `one-import-bcq` to use new python script.
=> [one-cmds] Update one-import-bcq

runtime/onert/core/src/compiler/OperationValidator.cc, runtime/onert/core/src/compiler/OperationValidator.h, runtime/onert/core/src/compiler/ShapeValidator.cc
Move operation input/output data type checking from ShapeValidator to OperationValidator
=> [onert] Move data type checking

runtime/onert/core/include/compiler/StaticShapeInference.h, runtime/onert/core/include/exec/DynamicShapeInference.h, runtime/onert/core/include/util/ShapeInference.h, runtime/onert/core/src/compiler/StaticShapeInference.cc, runtime/onert/core/src/exec/DynamicShapeInference.cc, runtime/onert/core/src/util/ShapeInference.cc, runtime/onert/test/util/ShapeInference.cc
- support shape inference on BCQFullyConnected
=> [onert] Support ShapeInference on BCQFullyConnected

runtime/onert/core/src/backend/controlflow/BackendContext.h, runtime/onert/core/src/backend/controlflow/ExternalContext.h
For issue #4414
Draft issue #4395
This commit introduces ExternalContext into controlflow backend
=> [onert] Introduces ExternalContext into controlflow backend

compiler/luci/pass/src/FuseBCQPass.cpp
This commit will add more validation for `FuseBCQPass` and remove redundant code
=> [luci] Add more validation for FuseBCQPass

compiler/one-cmds/how-to-use-one-commands.txt
This commit will update how to document about BCQ
=> [one-cmds] Update how to doc

compute/cker/include/cker/operation/StridedSlice.h
when only last dimension used, we have easy accesse to index.
So I optimized it for that situation.
And tested any models. The result is an 3.5% increase in speed.
(1.233 -> 1.191)
Signed-off-by: YiHyunjin <hj0412.yi@samsung.com>
=> [onert] Optimize StridedSlice

tests/nnfw_api/src/CircleGen.cc, tests/nnfw_api/src/CircleGen.h, tests/nnfw_api/src/one_op_tests/StridedSlice.cc
It adds stridedslice support in circlegen and a testcase.
=> [onert] Add StridedSlice test and api in CircleGen

runtime/onert/core/include/util/Utils.h, runtime/onert/core/src/exec/IPermuteFunction.h
For issue #4414
Draft issue #4395 
This commit introduces a helper function ShapeLoop.
- Introdute ShapeLoop
- Apply ShapeLoop to IPermuteFunction
=> [onert] Introduces a helper function ShapeLoop

compiler/luci-interpreter/src/kernels/TestUtils.cpp
Add support of S16 type to `dequantizeTensorData` helper.
=> [luci-interpreter] Add support of S16 type to `dequantizeTensorData` helper

compiler/one-cmds/one-optimize
Parent issue : #4373 
This commit will introduce `FoldDequantizePass` in `one-optimize`
=> [one-cmds] Introduce FoldDequantize in one-optimize

compute/cker/include/cker/operation/StridedSlice.h
optimized StopForAxis(op_params, unextended_input_shape, 0, start) >>
StopForAxis(op_params, unextended_input_shape, idx, start)
And a new conditional statement was added.
Signed-off-by: YiHyunjin <hj0412.yi@samsung.com>
=> [onert] Fix optimized StridedSlice

runtime/onert/frontend/nnapi/execution.cc, runtime/onert/frontend/nnapi/wrapper/ANeuralNetworksExecution.cc, runtime/onert/frontend/nnapi/wrapper/ANeuralNetworksExecution.h
This commit supports optional input through nnapi frontend.
=> [onert] Supports optional input through nnapi frontend

runtime/onert/core/src/compiler/ExecutorFactory.cc, runtime/onert/core/src/compiler/HEScheduler.cc, runtime/onert/core/src/compiler/LoweredGraph.cc, runtime/onert/core/src/compiler/pass/ConstantInsertionPass.cc, runtime/onert/core/src/compiler/pass/PermutationOperationPass.cc, runtime/onert/core/src/ir/Graph.cc, runtime/onert/core/src/ir/GraphIterator.cc, runtime/onert/core/src/ir/verifier/Verifier.cc
Draft PR #4519
This commit allows output of operation to be undefined.
=> [onert] Allows output of operation to be undefined

compiler/one-cmds/how-to-use-one-commands.txt
Parent issue : #4373
This commit will update how to document for `FoldDequantize` optimization
=> [one-cmds] Update how to doc for FoldDequantize

res/TensorFlowPythonExamples/examples/atrous_conv2d/__init__.py, res/TensorFlowPythonExamples/examples/flatten/__init__.py, res/TensorFlowPythonExamples/examples/instance_norm/__init__.py
This will add TF examples that was missing: atrous_conv2d, flatten and instance_norm
=> [res] More TF examples

runtime/onert/backend/cpu/ops/BinaryArithmeticLayer.cc, runtime/onert/backend/cpu/ops/StridedSliceLayer.cc
Use snake_case variable names instead of camelCase
=> [onert] Codestyle fix, PR #4538 follow-up

runtime/contrib/android/api/Android.mk, runtime/contrib/android/api/Prebuilt.mk, runtime/contrib/android/api/build.gradle, runtime/contrib/android/api/prebuilt/Android.mk, runtime/contrib/android/api/prebuilt/backend_cpu/Android.mk, runtime/contrib/android/api/prebuilt/backend_cpu/libbackend_cpu.so, runtime/contrib/android/api/prebuilt/circle_loader/Android.mk, runtime/contrib/android/api/prebuilt/circle_loader/libcircle_loader.so, runtime/contrib/android/api/prebuilt/nnfw-dev/Android.mk, runtime/contrib/android/api/prebuilt/nnfw-dev/libnnfw-dev.so, runtime/contrib/android/api/prebuilt/onert_core/Android.mk, runtime/contrib/android/api/prebuilt/onert_core/libonert_core.so, runtime/contrib/android/api/prebuilt/tensorflowlite_jni/Android.mk, runtime/contrib/android/api/prebuilt/tensorflowlite_jni/libtensorflowlite_jni.so, runtime/contrib/android/api/prebuilt/tflite_loader/Android.mk, runtime/contrib/android/api/prebuilt/tflite_loader/libtflite_loader.so
Revise Android.mk files
- merge mutiple prebuilt make files into one
- append handling ext backend option
=> [contrib/android] Revise Android.mk in contrib/android

runtime/onert/frontend/base_loader/include/base_loader.h, tests/nnfw_api/src/one_op_tests/If.cc, tests/nnfw_api/src/one_op_tests/While.cc
- For If and While operation, check if subgraph index values are valid
- Add 5 negative tests for each operation
=> [onert/loader] Check if subgraph index is valid

compiler/mio-tf/CMakeLists.txt
Use tensorflow 2.3 source code to refer protobuf specification
=> [mio-tf] Use tensorflow 2.3 source code

runtime/onert/core/src/compiler/ShapeValidator.cc
- remove code printing op configure
=> [onert] Remove legacy code from ShapeValidator

runtime/onert/core/src/compiler/Linear.cc, tests/nnfw_api/src/RegressionTests.cc
Do not call planDealloc for I/O tensors since they cannot be
deallocated. They hold user-given buffers.
=> [onert] Do not call planDealloc for I/O tensors

runtime/onert/core/src/compiler/ShapeValidator.cc, runtime/onert/core/src/compiler/ShapeValidator.h
- add ShapeValidator for BCQ Operations
=> [onert] Support ShapeValidator for BCQ Operations

runtime/onert/core/include/compiler/StaticShapeInference.h, runtime/onert/core/include/exec/DynamicShapeInference.h, runtime/onert/core/include/util/ShapeInference.h, runtime/onert/core/src/compiler/StaticShapeInference.cc, runtime/onert/core/src/exec/DynamicShapeInference.cc, runtime/onert/core/src/util/ShapeInference.cc, runtime/onert/test/util/ShapeInference.cc
- FIRST.... add test for gather layer shape inference
=> [onert] Implement BCQGather's shape inference

runtime/onert/core/src/exec/DynamicShapeInference.cc
- remove assert condition which is not necessary
=> [onert] Fix incorrect assert on bcqgather dynamic shapeinferer

tests/nnfw_api/src/CircleGen.cc, tests/nnfw_api/src/CircleGen.h, tests/nnfw_api/src/one_op_tests/InstanceNorm.cc
Add basic one-op test for InstanceNorm.
=> [nnfeapi] Add one-op test for InstanceNorm

runtime/onert/core/include/ir/operation/LSTM.h, runtime/onert/core/src/compiler/ShapeValidator.cc, runtime/onert/core/src/ir/OperationDumper.cc, runtime/onert/core/src/ir/operation/LSTM.cc, runtime/onert/frontend/nnapi/wrapper/OperationFactory.cc
Draft PR #4519
This commit makes nnapi frontend supports UnidirectionalSequenceLSTM
- Introduce UnidirectionalSequenceLSTM inputs into ir::operation::LSTM
- support UnidirectionalSequenceLSTM on nnapi frontend
=> [onert] Support UnidirectionalSequenceLSTM on nnapi frontend

runtime/onert/backend/acl_cl/ConstantInitializer.cc, runtime/onert/backend/acl_cl/ConstantInitializer.h, runtime/onert/backend/acl_cl/KernelGenerator.cc, runtime/onert/backend/acl_cl/KernelGenerator.h, tests/nnfw_api/src/CircleGen.cc, tests/nnfw_api/src/CircleGen.h, tests/nnfw_api/src/one_op_tests/Reverse.cc
related pr #4152 
add one_op_tests of REVERSE_V2 for acl_cl,cpu backend
=> [onert] Add one_op_tests of REVERSE for acl_cl backend

infra/docker/Dockerfile.1804
This commit prepares android aar build
=> Dockerfile: install android sdk/ndk

runtime/onert/core/include/compiler/StaticShapeInference.h, runtime/onert/core/include/exec/DynamicShapeInference.h, runtime/onert/core/src/compiler/StaticShapeInference.cc, runtime/onert/core/src/exec/DynamicShapeInference.cc
Draft PR #4519
This commit makes LSTM operation supports dynamic tensor.
=> [onert] Supports dynamic tensor for LSTM operation.

compiler/onnx-tools/CMakeLists.txt, compiler/onnx-tools/onnx-dump.py, compiler/onnx-tools/onnx-ops.py
This will introduce onnx-dump and onnx-ops that dumps onnx model graph
and operators
=> [onnx-tools] dump graph and ops

runtime/contrib/android/api/build.gradle
=> [contrib/android] Fix bug of api/build.gradle

docs/runtime/supported-operations-backend.md
Add table document to describe supported operations on each backend
=> [doc] Add supported operation on each backend

compiler/luci-interpreter/src/kernels/Prelu.cpp, compiler/luci-interpreter/src/kernels/Prelu.h, compiler/luci-interpreter/src/kernels/Prelu.test.cpp
Issue #4339.
Add support for S16 `Prelu` operator.
=> [luci-interpreter] Support S16 Prelu op

compiler/onnx-tools/README.md
This will introduce README file for compiler/onnx-tools
=> [onnx-tools] README file

infra/packaging/preset/20200731_windows
This will add bcq-tools to 20200731_windows preset
=> [infra] Add bcq-tools to preset for Windows

docs/release/1.10/release-note-1.10.0.md
=> Release note 1.10.0

docs/conf.py, packaging/nnfw.spec, runtime/contrib/android/api/build.gradle, runtime/onert/api/include/nnfw_version.h
=> Bump to verison 1.11.0

compute/cker/include/cker/operation/Dequantize.h, runtime/onert/backend/cpu/KernelGenerator.cc, runtime/onert/backend/cpu/ops/ElementwiseUnaryLayer.cc, runtime/onert/backend/cpu/ops/ElementwiseUnaryLayer.h, runtime/onert/frontend/base_loader/include/base_loader.h, tests/nnapi/nnapi_gtest.skip.aarch64-linux.cpu, tests/nnapi/nnapi_gtest.skip.armv7l-linux.cpu, tests/nnapi/nnapi_gtest.skip.x86_64-linux.cpu
- This commit implements Dequantize UINT8 kernel for cpu backend
---
For issue #4623
=> [onert/cpu] Implement Dequantize UINT8 kernel for cpu backend

runtime/onert/frontend/base_loader/include/base_loader.h
Refactoring: introduce sparsity tensor loaing function
=> [onert] Divide sparsity info loading function

compiler/luci/pass/src/QuantizationUtils.cpp, compiler/luci/pass/src/QuantizationUtils.h, compiler/luci/pass/src/QuantizeDequantizeWeightsPass.cpp, compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
This supports quantization of a tensor shared by multiple operators
---
Related to: https://github.com/Samsung/ONE/issues/4615
=> [luci] Support quantization of shared tensor

tests/nnapi/nnapi_gtest.skip.aarch64-linux.cpu, tests/nnapi/nnapi_gtest.skip.armv7l-linux.cpu, tests/nnapi/nnapi_gtest.skip.x86_64-linux.cpu
Related issue #3851
This commit enables some LSTM tests for cpu.
=> [onert] Enables some LSTM tests for cpu

runtime/onert/core/include/ir/OperandInfo.h, runtime/onert/core/src/compiler/Linear.cc, runtime/onert/core/src/compiler/LoweredGraph.cc, runtime/onert/frontend/base_loader/include/base_loader.h
This commit allows variable tensor.
- Introduces a field checking variable tensor into OperandInfo
- Apply variable tensor
=> [onert] Allows variable tensor

compiler/record-minmax/src/RecordMinMax.cpp
This catches H5Exception and rethrows it as std exception
=> [record-minmax] Catch H5Exception to prevent runtime abort

runtime/onert/backend/cpu/KernelGenerator.cc, runtime/onert/backend/cpu/ops/LSTMLayer.cc, runtime/onert/backend/cpu/ops/LSTMLayer.h, runtime/onert/core/src/compiler/ShapeValidator.cc, runtime/onert/frontend/base_loader/include/base_loader.h, runtime/onert/frontend/circle/src/circle_loader.cc, runtime/onert/frontend/tflite/src/tflite_loader.cc
This commit supports UnidirectionalSequenceLSTM on base_loader.
- Apply variable tensor to LSTMLayer
- Support UnidirectionalSequenceLSTM on base_loader
=> [onert] Supports UnidirectionalSequenceLSTM on base_loader

tests/nnfw_api/src/one_op_tests/Concat.cc
- Delete a positive case due to duplicate
- Add three negative cases
- Invalid axis
- Invalid rank
- Invalid dimension
ONE-DCO-1.0-Signed-off-by: Hyo Jong Kim <hue.kim@samsung.com>
=> [onert] Add nnfw_api negative cases for Concat

tests/nnfw_api/src/one_op_tests/Cast.cc
- Extract CircleGen generation into a separate function
- Add two more tests
=> [nnfwapi] Add more tests for Cast op

tests/nnfw_api/src/one_op_tests/AveragePool2D.cc
A large test(To test kernels for larger size)  and a negative test
=> [nnfwapi] Add tests for AvgPool2D

compiler/luci-interpreter/src/kernels/Mul.cpp, compiler/luci-interpreter/src/kernels/Mul.h, compiler/luci-interpreter/src/kernels/Mul.test.cpp
Issue #4339.
Add support for S16 `Mul` operator.
=> [luci-interpreter] Support S16 Mul op

docs/runtime/controlflow-operations.md, docs/runtime/index.rst
Write "Controlflow Operations" document and add it to runtime docs.
=> [onert/doc] Write controlflow-operations.md

runtime/onert/core/src/compiler/OperationValidator.cc, runtime/onert/core/src/compiler/OperationValidator.h, tests/nnfw_api/src/CircleGen.cc, tests/nnfw_api/src/CircleGen.h, tests/nnfw_api/src/GenModelTest.h, tests/nnfw_api/src/one_op_tests/Add.cc
=> [OneOpTest] UINT8 tensor test

docs/release/1.10/release-note-1.10.0.md
Update release note: runtime part
=> [release/1.10.0] Update release note

compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
This quantizes constants of six more Ops
=> [luci] Quantize constants of more Ops

res/TensorFlowLiteRecipes/Greater_U8_000/test.recipe
Fired Issue: #4713 
This commit enable U8 recipe for Greater_000 Op.
Thank you.
=> [res/TensorFlowLiteRecipes] Add Greater_U8_000

res/TensorFlowLiteRecipes/Maximum_U8_000/test.recipe
Fired Issue: #4703
This commit enable U8 recipe for Maximum_000 Op.
Thank you.
=> [res/TensorFlowLiteRecipes] Add Maximum_U8_000

res/TensorFlowLiteRecipes/Minimum_U8_000/test.recipe
Fired Issue: #4706
This commit enable U8 recipe for Minimum_000 Op.
Thank you.
=> [res/TensorFlowLiteRecipes] Add Minimum_U8_000

res/TensorFlowLiteRecipes/Less_U8_000/test.recipe
Fired Issue: #4711 
This commit enable U8 recipe for Less_000 Op.
Thank you.
=> [res/TensorFlowLiteRecipes] Add Less_U8_000

docs/release/1.10/release-note-1.10.0.md
Update release note: runtime part
Co-authored-by: Sanggyu Lee <takepencil@naver.com>
---
cherry-pick 7d429808a18874fca72acbfa22d6bed4d49a2200
=> Update release note

runtime/onert/core/src/compiler/OperationValidator.cc, runtime/onert/core/src/compiler/OperationValidator.h, runtime/onert/core/src/compiler/ShapeValidator.cc, tests/nnfw_api/src/CircleGen.cc, tests/nnfw_api/src/CircleGen.h, tests/nnfw_api/src/one_op_tests/Select.cc
Move type check to operation validator
Add test for Select and SelectV2
=> [onert] Select and SelectV2 operation validator

runtime/onert/core/src/compiler/Compiler.cc, runtime/onert/core/src/ir/Graph.cc, runtime/onert/core/src/ir/OperationValidator.cc, runtime/onert/core/src/ir/OperationValidator.h, tests/nnfw_api/src/one_op_tests/Add.cc, tests/nnfw_api/src/one_op_tests/Equal.cc, tests/nnfw_api/src/one_op_tests/LeakyRelu.cc, tests/nnfw_api/src/one_op_tests/Select.cc
Move operation validator to model loading phase
=> [onert] Move operation validator to model loading phase

tests/nnfw_api/src/CircleGen.cc, tests/nnfw_api/src/GenModelTest.h, tests/nnfw_api/src/one_op_tests/Add.cc
- Support INT8 type
- Restrict zero-point and scale
=> [OneOpTest] Quantization tensor condition

infra/docker/Dockerfile.1804
- Install zip package
- Install ubuntu official gnu build tool packages 8.x version
=> [infra] Update dockerfile - ubuntu 18.04

runtime/libs/nnapi/include/NeuralNetworksShim.h, runtime/libs/nnapi/include/NeuralNetworksTypes.h
Update nnapi lib header: porting from tensorflow lite 2.3
---
Related issue: #4391
=> [onert] Update nnapi lib header

runtime/onert/api/CMakeLists.txt, runtime/onert/backend/acl_cl/CMakeLists.txt, runtime/onert/backend/acl_neon/CMakeLists.txt, runtime/onert/backend/cpu/CMakeLists.txt, runtime/onert/core/CMakeLists.txt, runtime/onert/frontend/circle/CMakeLists.txt, runtime/onert/frontend/tflite/CMakeLists.txt
- Strip with --strip-unneeded option for libraries
=> Strip unneeded for shared libraries

.style.yapf, infra/command/format
Introduce yapf format file .style.yapf
=> [infra] Introduce yapf format file

compute/cker/include/cker/operation/AddN.h, runtime/onert/backend/cpu/KernelGenerator.cc, runtime/onert/backend/cpu/KernelGenerator.h, runtime/onert/backend/cpu/ops/AddNLayer.cc, runtime/onert/backend/cpu/ops/AddNLayer.h, runtime/onert/core/include/ir/Operations.Include.h, runtime/onert/core/include/ir/Operations.lst, runtime/onert/core/include/ir/operation/AddN.h, runtime/onert/core/src/ir/OperationValidator.cc, runtime/onert/core/src/ir/OperationValidator.h, runtime/onert/core/src/ir/operation/AddN.cc, runtime/onert/frontend/base_loader/include/base_loader.h, tests/nnfw_api/src/CircleGen.cc, tests/nnfw_api/src/CircleGen.h, tests/nnfw_api/src/one_op_tests/AddN.cc
This commit implements AddN kernel for cpu backend
ONE-DCO-1.0-Signed-off-by: hansolu <hansolu.lee@samsung.com>
=> [onert] Implement AddN kernel for cpu backend

runtime/onert/core/src/ir/OperationValidator.cc, runtime/onert/core/src/ir/OperationValidator.h
- Introduce isConstant method
- Introduce isSameType method
- Introduce isValidType methods
=> [onert] Introduce private methods for OperationValidator

compiler/luci/pass/include/luci/CircleOptimizer.h, compiler/luci/pass/include/luci/Pass/FusePreActivationBatchNormPass.h, compiler/luci/pass/src/CircleOptimizer.cpp, compiler/luci/pass/src/FusePreActivationBatchNormPass.cpp, compiler/luci/pass/src/FusePreActivationBatchNormPassInternal.h
This adds a pass to fuse pre-activation batchnorm
---
Related to: #4773 
Draft PR: #4769
=> [luci] Pass to fuse pre-activation batchnrom

runtime/onert/core/src/ir/OperationValidator.cc, runtime/onert/core/src/ir/OperationValidator.h
Use _operand and _operation field
Remove _graph field
=> [onert] OperationValidator field

compiler/luci/pass/include/luci/CircleOptimizer.h, compiler/luci/pass/include/luci/Pass/MakeBatchNormGammaPositivePass.h, compiler/luci/pass/src/CircleOptimizer.cpp, compiler/luci/pass/src/MakeBatchNormGammaPositivePass.cpp
This adds a pass to make negative BN gamma to a small positive value (1e-10)
---
Draft PR: #4788
=> [luci] Make negative BN gamma to positive

runtime/onert/core/src/compiler/LoweredGraph.cc, runtime/onert/core/src/ir/Graph.cc, runtime/onert/core/src/ir/verifier/Verifier.cc, runtime/onert/core/src/ir/verifier/Verifier.h, runtime/onert/test/graph/Graph.cc, tests/nnfw_api/src/one_op_tests/Add.cc
- Add Input Output checker for Graph
- Add 1 pos and 3 neg tests
=> [onert] Add some ir::Graph tests

res/TensorFlowPythonExamples/examples/gru/__init__.py, res/TensorFlowPythonExamples/examples/lstm/__init__.py, res/TensorFlowPythonExamples/examples/rnn/__init__.py
Added LSTM, RNN and GRU keras models to res/TensorFlowPythonExamples/
for #4528
=> [res] Recurrent keras models

compiler/luci/pass/src/FusePreActivationBatchNormPass.cpp
This adds a logic to fuse add with conv for FusePreActivationBatchNormPass
---
Draft PR: #4769
=> [luci] Fuse add with conv (for FusePreActivationBatchNormPass)

compiler/bcq-tools/generate_bcq_metadata.py, compiler/bcq-tools/generate_bcq_output_arrays.py
This commit adds python extension to name of bcq-tools.
Existing file will be deprecated soon.
Draft: #4758
=> [bcq-tools] rename bcq-tools

compiler/one-cmds/CMakeLists.txt, compiler/one-cmds/one-import, compiler/one-cmds/one-import-tf, compiler/one-cmds/tests/CMakeLists.txt, compiler/one-cmds/tests/one-import_002.cfg, compiler/one-cmds/tests/one-import_002.test, compiler/one-cmds/utils.py
This commit revises one-import-tf as python script.
Draft: #4758 
=> [one-cmds] Revise one-import-tf as python script

runtime/onert/core/CMakeLists.txt, runtime/onert/core/include/ir/Coordinates.h, runtime/onert/core/src/backend/controlflow/Backend.h, runtime/onert/core/src/backend/controlflow/BackendContext.h, runtime/onert/core/src/backend/controlflow/ExternalContext.h, runtime/onert/core/src/backend/controlflow/KernelGenerator.cc, runtime/onert/core/src/backend/controlflow/KernelGenerator.h, runtime/onert/core/src/backend/controlflow/kernel/IfLayer.cc, runtime/onert/core/src/backend/controlflow/kernel/IfLayer.h, runtime/onert/core/src/backend/controlflow/kernel/PermuteLayer.cc, runtime/onert/core/src/backend/controlflow/kernel/PermuteLayer.h, runtime/onert/core/src/backend/controlflow/kernel/WhileLayer.cc, runtime/onert/core/src/backend/controlflow/kernel/WhileLayer.h, runtime/onert/core/src/exec/IPermuteFunction.h
For issue #4414
Draft PR #4395
This commit optimizes PermuteLayer of controlflow by using ruy's thread pool.
=> [onert] Optimizes PermuteLayer of controlflow by ruy

res/TensorFlowLiteRecipes/MaxPoolWithArgMax_000/test.recipe, res/TensorFlowLiteRecipes/MaxPoolWithArgMax_001/test.recipe, res/TensorFlowLiteRecipes/MaxPoolWithArgMax_002/test.recipe
Add recipes for MaxPoolWithArgMax operator
ONE-DCO-1.0-Signed-off-by: Denis Krylov <krylovdenism@gmail.com>
=> [res] Add recipes for MaxPoolWithArgMax operator

compiler/one-cmds/one-codegen
This commit revises one-codegen as python script.
Draft: #4758
=> [one-cmds] Revise one-codegen as python script

compiler/one-cmds/one-import-bcq, compiler/one-cmds/tests/one-import-bcq_neg_003.test
This commit revises one-import-bcq as python script.
Draft: #4758
=> [one-cmds] Revise one-import-bcq as python script

infra/nnfw/cmake/packages/TensorFlowLite-1.13.1/TensorFlowLiteConfig.cmake
Find updated tensorflow lite header path on tizen
---
For #4813
=> [infra] Fix tizen test package build fail

compiler/one-cmds/one-quantize, compiler/one-cmds/tests/one-quantize_neg_006.test
This commit revises one-quantize as python script.
Draft: #4758
=> [one-cmds] Revise one-quantize as python script

compute/cker/include/cker/operation/Elementwise.h, runtime/onert/backend/cpu/KernelGenerator.cc, runtime/onert/backend/cpu/ops/ElementwiseUnaryLayer.cc, runtime/onert/backend/cpu/ops/ElementwiseUnaryLayer.h, runtime/onert/core/src/ir/OperationValidator.cc, runtime/onert/frontend/base_loader/include/base_loader.h, tests/nnfw_api/src/CircleGen.cc, tests/nnfw_api/src/CircleGen.h, tests/nnfw_api/src/one_op_tests/Floor.cc
This commit implements Floor kernel for cpu backend
ONE-DCO-1.0-Signed-off-by: hansolu <hansolu.lee@samsung.com>
=> [onert] Implement Floor kernel for cpu backend

infra/command/build-docker-image, infra/config/docker.configuration, infra/nncc/config/docker.configuration, infra/nnfw/config/docker.configuration
Rename docker image: one-devtools
---
Related issue: #4735
=> [infra] Rename docker image

compiler/one-cmds/one-optimize, compiler/one-cmds/tests/one-optimize_neg_002.test, compiler/one-cmds/tests/one-optimize_neg_003.test
This commit revises one-optimize as python script.
Draft: #4758
=> [one-cmds] Revise one-optimize as python script

compiler/luci/pass/src/FusePreActivationBatchNormPass.cpp
This fuses sub with conv for FusePreActivationBatchNormPass
---
Draft PR: #4769
=> [luci] Fuse sub with conv (for FusePreActivationBatchNormPass)

res/TensorFlowLiteRecipes/Transpose_U8_000/test.recipe
Fired Issue: #4836
This commit enable U8 recipe for Transpose_000 Op.
Please review this PR, @seanshpark, @jinevening .
Thank you.
=> [res/TensorFlowLiteRecipes] Add Transpose_U8_000

tests/scripts/test_scheduler_with_profiling.sh
- Modified to generate DOT files for all profiling runs.
- Make profiling script to generate a PNG format rendered image of DOT graph file.
=> Generate PNG from DOT while profiling

compiler/one-cmds/one-import-tflite
This commit revises one-import-tflite as python script.
Draft: #4758
=> [one-cmds] Revise one-import-tflite as python script

compiler/one-cmds/one-pack, compiler/one-cmds/tests/one-pack_neg_001.test, compiler/one-cmds/tests/one-pack_neg_003.test
This commit revises one-pack as python script.
Draft: #4758
=> [one-cmds] Revise one-pack as python script

runtime/onert/backend/cpu/ops/BinaryArithmeticLayer.cc
Initialize struct Eval's filed: _need_broadcast
=> [onert/cpu] Fix uninitialized field

runtime/onert/core/src/compiler/LoweredGraph.cc
This will add missing newline to logging in LoweredGraph.cc
=> [onert] Add newline to log

runtime/onert/backend/acl_cl/KernelGenerator.cc, runtime/onert/backend/acl_common/Convert.cc, runtime/onert/backend/acl_common/Convert.h, runtime/onert/backend/acl_neon/KernelGenerator.cc, runtime/onert/backend/cpu/KernelGenerator.cc, runtime/onert/backend/cpu/ops/DepthwiseConvolutionLayer.cc, runtime/onert/backend/cpu/ops/DepthwiseConvolutionLayer.h, runtime/onert/core/include/ir/operation/DepthwiseConv2D.h, runtime/onert/core/src/ir/OperationValidator.cc, runtime/onert/core/src/ir/OperationValidator.h, runtime/onert/frontend/base_loader/include/base_loader.h, runtime/onert/frontend/nnapi/wrapper/OperationFactory.cc, tests/nnfw_api/src/CircleGen.cc, tests/nnfw_api/src/CircleGen.h, tests/nnfw_api/src/one_op_tests/DepthwiseConv2D.cc
Support depthwise convolution dilation parameter on cpu/acl-cl/acl-neon backend
---
Related issue: #4828
=> [onert] Support depthwise convolution dilation

res/PyTorchExamples/examples/div/__init__.py, res/PyTorchExamples/examples/mul/__init__.py, res/PyTorchExamples/examples/sub/__init__.py
This will introduce div, mul and sub examples for PyTorchExamples
=> [res] pth examples for div,mul,sub

res/PyTorchExamples/examples/AvgPool2d-1/__init__.py, res/PyTorchExamples/examples/AvgPool2d/__init__.py, res/PyTorchExamples/examples/ConstantPad2d-1/__init__.py, res/PyTorchExamples/examples/ConstantPad2d-2/__init__.py, res/PyTorchExamples/examples/ConstantPad2d-3/__init__.py, res/PyTorchExamples/examples/ConstantPad2d/__init__.py, res/PyTorchExamples/examples/LPPool2d/__init__.py, res/PyTorchExamples/examples/MaxPool2d/__init__.py
This will introduce AvgPool2d, LPPool2d, MaxPool2d and ConstantPad2d PyTorchExamples
=> [res] pth examples for Pool,Pad

res/PyTorchExamples/examples/Conv2d-dil/__init__.py, res/PyTorchExamples/examples/Conv2d-dw/__init__.py, res/PyTorchExamples/examples/Conv2d/__init__.py, res/PyTorchExamples/examples/ConvTranspose2d/__init__.py
This will introduce PyTorchExamples for Conv2D, Conv2D with dilation,
Conv2D depthwise and ConvTranspose2d
=> [res] PyTorchExamples for Conv2D

compiler/nnkit-tf/CMakeLists.txt, compiler/nnkit-tf/support/CMakeLists.txt
Use TensorFlow for C 1.13 for nnkit-tf support
=> [nnkit-tf] Use TensorFlow package 1.13

runtime/onert/core/src/compiler/LoweredGraph.cc
This will revert add newline to logging in LoweredGraph.cc
=> [onert] revert add newline to log

compiler/luci/pass/src/FusePreActivationBatchNormPass.test.cpp
Add a test for FusePreactivationBatchNormPass
---
Draft PR: #4769
=> [luci] Add test for FusePreActivationBatchNormPass

res/TensorFlowLiteRecipes/Net_Preactivation_BN_000/test.recipe, res/TensorFlowLiteRecipes/Net_Preactivation_BN_000/test.rule
This adds a recipe to rest FusePreActivationBatchNormPass
---
=> [res] Add recipe to test FusePreActivationBatchNormPass

compiler/luci/pass/include/luci/CircleOptimizer.h, compiler/luci/pass/include/luci/Pass/FuseActivationFunctionPass.h, compiler/luci/pass/src/CircleOptimizer.cpp, compiler/luci/pass/src/FuseActivationFunctionPass.cpp, compiler/luci/pass/src/FuseActivationFunctionPass.test.cpp, compiler/luci/pass/src/FuseActivationFunctionPassInternal.h
This adds FuseActivationFunctionPass to luci
---
Related to: https://github.com/Samsung/ONE/issues/4861
=> [luci] Fuse activation function pass

res/PyTorchExamples/examples/ELU/__init__.py, res/PyTorchExamples/examples/LeakyReLU/__init__.py, res/PyTorchExamples/examples/PReLU/__init__.py, res/PyTorchExamples/examples/ReLU/__init__.py, res/PyTorchExamples/examples/ReLU6/__init__.py, res/PyTorchExamples/examples/Sigmoid/__init__.py, res/PyTorchExamples/examples/Tanh/__init__.py
This will introduice PyTorchExamples to ReLU and several activations
=> [res] PyTorchExamples for Activations

compiler/circle2circle/src/Circle2Circle.cpp
This adds an option for FuseActivationFunctionPass
---
Related to: #4861
Draft pr: #4833
=> [circle2circle] Fuse activation function option

res/PyTorchExamples/examples/ge/__init__.py, res/PyTorchExamples/examples/gt/__init__.py, res/PyTorchExamples/examples/le/__init__.py, res/PyTorchExamples/examples/lt/__init__.py, res/PyTorchExamples/examples/ne/__init__.py
This will introduce PyTorchExamples of ge, gt, le, lt and ne
=> [res] PyTorchExamples for Comparators

compiler/bcq-tools/CMakeLists.txt, compiler/bcq-tools/generate_bcq_metadata, compiler/bcq-tools/generate_bcq_output_arrays
This commit adds removed files for backward compatibility.
=> [bcq-tools] Add removed files

res/PyTorchExamples/examples/cos/__init__.py, res/PyTorchExamples/examples/dist/__init__.py, res/PyTorchExamples/examples/floor/__init__.py, res/PyTorchExamples/examples/floor_divide/__init__.py, res/PyTorchExamples/examples/min-1/__init__.py, res/PyTorchExamples/examples/min/__init__.py, res/PyTorchExamples/examples/neg/__init__.py, res/PyTorchExamples/examples/rsqrt/__init__.py, res/PyTorchExamples/examples/sin/__init__.py, res/PyTorchExamples/examples/sqrt/__init__.py
This will introduce PyTorchExamples of cos, dist, floor, floor_divide,
min, neg, rsqrt, sin and sqrt
=> [res] PyTorchExamples for math functions and others

res/PyTorchExamples/examples/Flatten/__init__.py, res/PyTorchExamples/examples/cat-1/__init__.py, res/PyTorchExamples/examples/cat/__init__.py, res/PyTorchExamples/examples/permute/__init__.py, res/PyTorchExamples/examples/reshape/__init__.py, res/PyTorchExamples/examples/slice/__init__.py, res/PyTorchExamples/examples/split-1/__init__.py, res/PyTorchExamples/examples/split-2/__init__.py, res/PyTorchExamples/examples/split/__init__.py, res/PyTorchExamples/examples/squeeze-1/__init__.py, res/PyTorchExamples/examples/squeeze/__init__.py
This will introduce PyTorchExamples of Flatten, cat, permute, reshape,
slice, split and squeeze
=> [res] PyTorchExamples of Reshape and others

compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
This quantizes gamma/beta of INSTANCE_NORM
---
Related to: #4874
Draft PR: #4880
=> [luci] Quantize gamma/beta of INSTANCE_NORM

res/PyTorchExamples/examples/BatchNorm2d/__init__.py, res/PyTorchExamples/examples/InstanceNorm2d/__init__.py, res/PyTorchExamples/examples/LocalResponseNorm/__init__.py
This will introduce PyTorchExamples of BatchNorm2d, InstanceNorm2d and
LocalResponmseNorm
=> [res] PyTorchExamples of Norms

res/PyTorchExamples/examples/Bilinear/__init__.py, res/PyTorchExamples/examples/UpsamplingNearest2d/__init__.py
This will introduce PyTorchExamples of Bilinear and UpsamplingNearest2d
=> [res] PyTorchExamples of resize

res/PyTorchExamples/examples/AdaptiveAvgPool2d/__init__.py
Fired Issue: #4889 
This commit adds PyTorch Example of nn.AdaptiveAvgPool2d.
Please review this PR, @seanshpark, @mhs4670go  .
Thank you.
=> [res] Add PyTorchExamples of AdaptiveAvgPool2d

compiler/luci/pass/src/FuseInstanceNormPass.cpp
This adds a new pattern to FuseInstanceNormPass
---
Related to: #4874 
Draft PR: #4880
=> [luci] Fuse instance norm for FastStyleTransfer

res/TensorFlowLiteRecipes/Net_InstanceNorm_003/test.recipe, res/TensorFlowLiteRecipes/Net_InstanceNorm_003/test.rule
This adds a new TFLite recipe for instnorm network
---
Related to: #4874
Draft PR: #4880
=> [res] Add a new TFLite recipe for instnorm network

res/PyTorchExamples/examples/Softmax/__init__.py
This will introduce Softmax activation
=> [res] PyTorchExamples of Softmax

res/PyTorchExamples/examples/LogSoftmax/__init__.py
Fired Issue: #4889 
This commit adds PyTorch Example of nn.LogSoftmax.
Thank you.
=> [res] Add PyTorchExamples of LogSoftmax

res/PyTorchExamples/examples/Linear/__init__.py, res/PyTorchExamples/examples/matmul/__init__.py
Fired Issue: #4889 
This commit adds PyTorch Example of nn.Linear.
Thank you.
=> [res] Add PyTorchExamples of Linear

infra/command/build-docker-image, infra/docker/focal/Dockerfile
- Introduce ubuntu 20.04 dockerfile
- Remove deprecated command parameter: "--extension"
=> [infra] Update docker image build command

res/PyTorchExamples/examples/log/__init__.py
This commit adds PyTorch Example of log.
Thank you.
=> [res] Add PyTorchExamples of log

res/PyTorchExamples/examples/pow/__init__.py
This commit adds PyTorch Example of pow.
Thank you.
=> [res] Add PyTorchExamples of pow

res/PyTorchExamples/examples/sum/__init__.py
This commit adds PyTorch Example of sum.
Thank you.
=> [res] Add PyTorchExamples of sum

res/PyTorchExamples/examples/zeros_like/__init__.py
This commit adds PyTorch Example of zeros_like.
Thank you.
=> [res] Add PyTorchExamples of zeros_like

res/PyTorchExamples/examples/abs/__init__.py
This commit adds PyTorch Example of abs.
Thank you.
=> [res] Add PyTorchExamples of abs

res/PyTorchExamples/examples/argmax/__init__.py, res/PyTorchExamples/examples/argmin/__init__.py
This commit adds PyTorch Example of argmin & argmax.
Thank you.
=> [res] Add PyTorchExamples of argmin & argmax

runtime/onert/core/src/compiler/HEScheduler.cc
This will move static functions to anonymous namespace in
HEScheduler.cc
=> [onert] static functions to anonymous namespace

compiler/luci-interpreter/src/core/KernelParams.h, compiler/luci-interpreter/src/kernels/CMakeLists.txt, compiler/luci-interpreter/src/kernels/InstanceNorm.cpp, compiler/luci-interpreter/src/kernels/InstanceNorm.h, compiler/luci-interpreter/src/kernels/InstanceNorm.test.cpp, compiler/luci-interpreter/src/loader/KernelBuilder.cpp, compiler/luci-interpreter/src/loader/KernelBuilder.h, compiler/luci-interpreter/src/loader/KernelBuilder.test.cpp
This commit add InstanceNorm on luci-interpreter.
=> [luci-interpreter]Add InstanceNorm on luci-interpreter

compiler/luci/pass/src/FusePreActivationBatchNormPass.test.cpp
Refactoring of test code to avoid warnings from our static code analyzer
=> [luci] Refactoring test code to avoid warnings

tests/nnfw_api/src/NNPackages.cc
Fix nnfw_api_gtest error message when nnpackage is not downloaded
=> [onert/test] Fix nnfw_api_gtest error message

compiler/imgdata2hdf5/imgdata2hdf5.py
This will add copyright comment to imgdata2hdf5.py
=> [imgdata2hdf5] Add copyright

infra/packaging/preset/20200630, infra/packaging/preset/20200731_windows
This will add rawdata2hdf5 to install preset of 20200630
=> [infra] Add rawdata2hdf5 to install preset

compiler/rawdata2hdf5/rawdata2hdf5.py
Refactoring and error handling for release
---
Related to: https://github.com/Samsung/ONE/issues/4944
=> [rawdata2hdf5] Refactoring and more error handling

compiler/one-cmds/how-to-create-hdf5-dataset.txt
Add document for how to create hdf5 dataset
---
Related to: https://github.com/Samsung/ONE/issues/4944
=> [one-cmds] Document for how to create hdf5 dataset

infra/scripts/test_coverage.sh
Unzip tar file before check test is prepared
=> [onert] Fix runtime coverage test bug

compiler/rawdata2hdf5/CMakeLists.txt, compiler/rawdata2hdf5/README.md, compiler/rawdata2hdf5/rawdata2hdf5
This includes changes for release
1. Generate rawdata2hdf5 (dropped .py)
2. Improve exception handling
---
Related to: https://github.com/Samsung/ONE/issues/4944
=> [rawdata2hdf5] Preparation to be included in release

docs/runtime/supported-operations-backend.md
Update runtime backends supported operations
=> [doc] Update runtime supported operation

compiler/one-cmds/tests/rawdata2hdf5_neg_003.test, compiler/one-cmds/tests/rawdata2hdf5_neg_004.test
This adds more tests for rawdata2hdf5
=> [one-cmds] More tests for rawdata2hdf5

compiler/one-cmds/how-to-create-hdf5-dataset.txt
This fixes the document how-to-create-hdf5-dataset.txt
=> [one-cmds] Fix for document how-to-create-hdf5-dataset.txt

infra/scripts/tizen_xu4_test.sh
This commit sets arch manually in tizen tests script.
Related : #4957 
=> [infra] set arch manually in tizen test script

compiler/circlechef/circle/src/RecipeChef.cpp, compiler/circlechef/core/src/ModelChef.cpp, compiler/circlechef/proto/circlechef.proto
Parent Issue : #4372
This commit will introduce `ShapeSignature` in `circlechef`
=> [circlechef] Introduce ShapeSiganture in circlechef

compiler/tflchef/tests/shape_signature/test.recipe
Parent Issue : #4372
This commit will add a testcase for shape signature in `tflchef`
=> [tflchef] Add testcase for shape signature

compiler/one-cmds/tests/prepare_test_materials.sh
This will fix action and condition to invoke preprocess_images script
=> [one-cmds] Fix actions for image preprocess

compiler/luci-interpreter/src/kernels/TestUtils.cpp, compiler/luci-interpreter/src/kernels/TestUtils.h
This removes type conversion warning
=> [luci-interpreter] Remove type conversion warning

docs/howto/how-to-cross-build-runtime-for-arm.md
Update cross build guide for ubuntu 18.04
=> [doc] Update arm cross build document

tools/cross/install_rootfs.sh
Change default ubuntu version to 18.04
=> [tools] Update rootfs install tool

compiler/one-cmds/one-import-bcq, compiler/one-cmds/one-import-tf, compiler/one-cmds/utils.py
This commit adds model_format option to cfg.
=> [one-cmds] add model_format option to cfg

compiler/one-cmds/one-prepare-venv
This commit revises one-prepare-venv to always install package requirements.
=> [one-cmds] Revise one-prepare-venv

docs/release/1.11/release-note-1.11.0.md
This is the release note for ONE 1.11.0
=> Releae Note for ONE 1.11.0

docs/conf.py, packaging/nnfw.spec, runtime/contrib/android/api/build.gradle, runtime/onert/api/include/nnfw_version.h
Use version 1.12.0 after merging this PR
=> Use version number 1.12.0

compiler/one-cmds/tests/prepare_test_materials.sh
This will revise tests/prepare_test_material.sh to prepare TF2.x saved
model and keras model for testing
=> [one-cmds] Prepare TF2.x models

compiler/one-cmds/tests/one-build_001.cfg, compiler/one-cmds/tests/one-build_002.cfg, compiler/one-cmds/tests/one-build_neg_002.cfg, compiler/one-cmds/tests/one-build_neg_003.cfg, compiler/one-cmds/tests/one-build_neg_004.cfg, compiler/one-cmds/tests/one-import_002.cfg
This commit updates test cfg files for applying converter_version option
that is just been introduced.
=> [one-cmds] update cfg files

compiler/circlechef/tests/CMakeLists.txt, compiler/circlechef/tests/shape_signature/test.recipe
Parent Issue : #4372
This commit will add a testcase for shape signature in `circlechef`
=> [circlechef] Add testcase for shape signature

runtime/onert/api/src/nnfw_api_internal.cc
This will wrap with anonymous namespace for static functions in
nnfw_api_internal.cc
=> [onert] Use anonymous namespace for static functions

infra/scripts/test_ubuntu_runtime_mixed.sh
This commit adds setting RUY_THREADS into mixed test script.
=> [tests] Add setting RUY_THREADS into mixed test script

runtime/onert/api/src/nnfw_api_internal.cc
This will remove duplicate include of same header
=> [onert/nnfw_api] Remove duplicate include

compiler/one-cmds/tests/one-import_003.cfg, compiler/one-cmds/tests/one-import_003.test, compiler/one-cmds/tests/one-import_004.cfg, compiler/one-cmds/tests/one-import_004.test
This will introduce one-import tests for TF2.x saved model and keras model
=> [one-cmds] Test for TF2.x models

tests/nnfw_api/src/one_op_tests/DepthwiseConv2D.cc
Workaround for TCM tool reporting a false positive(no assertion).
=> [nnfwapi] Test: Workaround for TCM

runtime/libs/nnapi/include/NeuralNetworksShim.h, runtime/libs/nnapi/include/NeuralNetworksTypes.h
This commit add restriction fallowing android API LEVEL.
=> [runtime/nnapi] Add restriction about android API LEVEL

compute/cker/include/cker/CpuBackendThreadpool.h, compute/cker/include/cker/operation/DepthwiseConv.h, compute/cker/include/cker/operation/optimized/DepthwiseConvFloat.h, runtime/onert/backend/cpu/KernelGenerator.cc, runtime/onert/backend/cpu/ops/DepthwiseConvolutionLayer.cc, runtime/onert/backend/cpu/ops/DepthwiseConvolutionLayer.h, runtime/onert/core/src/interp/operations/DepthwiseConv2D.cc
Use optimized DepthwiseConv float kernel
---
Related issue: #4949
=> [onert/cpu] Optimize DepthwiseConv float kernel

runtime/onert/api/src/nnfw_api_internal.cc
This will enable ConfigSource from nnpkg configs file if exist
=> [onert/api] ConfigSource from nnpkg configs

runtime/onert/core/src/compiler/ExecutorFactory.cc
Hoist the code that sets up controlflow backend KernelGenerator, since
it does not have to repeat for each OpSequence.
=> [onert] Hoist controlflow backend KernelGen setup

runtime/onert/core/src/compiler/Compiler.cc
This will revise LOG of Compiler to show manual_scheduler_options and
also backend_for_all
=> [onert] Log for manual_scheduler_options

runtime/onert/core/src/exec/ExecTime.h, runtime/onert/core/src/exec/ExecutionObservers.h, runtime/onert/core/src/exec/JSONExecTime.cc, runtime/onert/core/src/exec/JSONExecTime.h, runtime/onert/test/core/compiler/Scheduler.cc, runtime/onert/test/core/exec/ExecTime.test.cc
This will tidy JSONExecTime method names and some comments
=> [onert] Tidy JSONExecTime names

nnpackage/examples/one_op_in_tflite/metadata/MANIFEST, nnpackage/examples/one_op_in_tflite/metadata/config.cfg, nnpackage/spec/10_packaging_and_manifest.md
This will add configs in MANIFEST as to provide configuration for onert by a file
=> [nnpackage] configs for configuration file

runtime/onert/core/include/util/logging.h, runtime/onert/core/src/compiler/ManualScheduler.cc
This will introduce WHENLOGENABLED macro to wrap only for logging codes
- use for logging ManualScheduler results
=> [onert] Introduce WHENLOGENABLED for log only codes

tools/nnpackage_tool/model2nnpkg/model2nnpkg.sh
This will revise model2nnpkg to provide configuration as an option
=> [model2nnpkg] Provide configs option

compute/ruy/CMakeLists.txt, compute/ruy/include/ruy/RuySupport.h, compute/ruy/include/ruy/Shape.h, compute/ruy/include/ruy/Types.h, compute/ruy/include/ruy/Utils.h, compute/ruy/include/ruy/operation/Conv.h
- This commit introduces compute/ruy to handler ruy kernels
- It has Conv2D ruy kernel that will be used by ruy backend
---
This kernel is tested on draft #4870
For issue #4863
=> [onert/compute] Introduce compute/ruy to handle ruy kernels

compiler/luci/lang/include/luci/IR/Nodes/CircleFullyConnected.h
This commit introduces WeightFormat attr.
Related : #4993
Draft: #5058
=> [luci] Introduce WeightFormat attr

runtime/onert/core/src/util/EventWriter.cc, runtime/onert/core/src/util/EventWriter.h
Refactor `EventWriter`.
Three specific methods were written as separate classes,  `SNPEWriter`, `ChromeTracingWriter`, and `MDWriter`.
(while working on #4903 for #4901)
=> [onert] Refactor EventWriter

compiler/common-artifacts/exclude.lst
Parent Issue : #5037
This commit will add `ReLUN1TO1` to `exclude.lst`
=> [common-artifacts] Add ReLUN1TO1 to exlucde list

compiler/luci/service/include/luci/Service/CircleShapeSignatureInference.h, compiler/luci/service/src/Nodes/CircleRelu.cpp, compiler/luci/service/src/Nodes/CircleRelu6.cpp, compiler/luci/service/src/Nodes/CircleReluN1To1.cpp
Parent Issue : #5037
This commit will introduce shape signature inference algorithm for `ReLU`, `ReLU6`, `ReLUN1To1`
=> [luci] ShapeSignature Inference Algorithm for ReLU,ReLU6,ReLUN1To1

runtime/onert/core/src/exec/ExecutorBase.cc, runtime/onert/core/src/exec/ExecutorBase.h
This will tidy ExecutionBase include files
=> [onert] Tidy ExecutionBase includes

res/TensorFlowLiteRecipes/ReLU6_dynamic_000/test.recipe, res/TensorFlowLiteRecipes/ReLUN1To1_dynamic_000/test.recipe, res/TensorFlowLiteRecipes/ReLU_dynamic_000/test.recipe
Parent Issue : #5037
This commit will add dynamic shape testcases for `ReLU`, `ReLU6`, `ReLUN1TO1`
=> [res] Add dynamic tc for ReLU, ReLU6, ReLUN1TO1

compiler/luci-interpreter/src/kernels/TransposeConv.cpp, compiler/luci-interpreter/src/kernels/TransposeConv.h, compiler/luci-interpreter/src/kernels/TransposeConv.test.cpp
This adds CWQ uint8 kernel for TConv
---
Related to: #5049
=> [luci-interpereter] CWQ uint8 kernel for TConv

compiler/luci-interpreter/src/kernels/DepthwiseConv2D.cpp, compiler/luci-interpreter/src/kernels/DepthwiseConv2D.h, compiler/luci-interpreter/src/kernels/DepthwiseConv2D.test.cpp
This adds CWQ uint8 kernel for DepthwiseConv2D
---
Related to: #5049
=> [luci-interpreter] CWQ uint8 kernel for DepthwiseConv2D

compute/cker/include/cker/operation/Elementwise.h, runtime/onert/backend/cpu/KernelGenerator.cc, runtime/onert/backend/cpu/ops/ElementwiseUnaryLayer.cc, runtime/onert/backend/cpu/ops/ElementwiseUnaryLayer.h, runtime/onert/core/include/ir/operation/ElementwiseUnary.h, runtime/onert/core/src/ir/operation/ElementwiseUnary.cc, runtime/onert/frontend/base_loader/include/base_loader.h, tests/nnfw_api/src/CircleGen.cc, tests/nnfw_api/src/CircleGen.h, tests/nnfw_api/src/one_op_tests/Square.cc
It supports SQUARE operator in cpu backend.
=> [onert] Support SQUARE in cpu backend

tests/nnfw_api/src/GenModelTest.h
- This commit supports RUY backend testing in GenModelTest
=> [nnfwapi] Support RUY backend testing in GenModelTest

docs/howto/how-to-use-specific-backend.md
- Write "How to Use Specific Backend during Inference" document
=> [docs] Write How to Use Specific Backend during Inference

compute/cker/include/cker/operation/Elementwise.h, runtime/onert/backend/cpu/KernelGenerator.cc, runtime/onert/backend/cpu/ops/ElementwiseUnaryLayer.cc, runtime/onert/backend/cpu/ops/ElementwiseUnaryLayer.h, tests/nnfw_api/src/CircleGen.cc, tests/nnfw_api/src/CircleGen.h, tests/nnfw_api/src/one_op_tests/Sqrt.cc
It supports SQRT in cpu backend.
=> [onert] Support SQRT in cpu backend

compute/cker/include/cker/Types.h, compute/cker/include/cker/operation/LeakyReLU.h, runtime/onert/backend/cpu/KernelGenerator.cc, runtime/onert/backend/cpu/ops/ElementwiseActivationLayer.cc, runtime/onert/backend/cpu/ops/ElementwiseActivationLayer.h, tests/nnfw_api/src/one_op_tests/LeakyRelu.cc
It supports LeakyReLU in cpu backend.
=> [onert] Support LeakyReLU in cpu backend

tests/scripts/benchmark_nnapi.sh, tests/scripts/test_scheduler_with_profiling.sh, tests/scripts/test_scheduler_with_profiling_android.sh
This will remove a typo looking suffix 'xX' in message string
=> [tests] Remove typo looking suffix xX

compiler/luci/pass/src/FuseBCQPass.cpp
Parent Issue : #4961 
This commit introduce two new functions to support inter-module BCQ fusing.
- Getter for `alpha` and `packed_binary_code`
- When `FuseBCQPass` supports fusing between `luci::Module`, same `luci::Const` cannot be used in different subgraph
- Copying and creating new `luci::Const` will resolve this
- BCQ information Register Function
- Same information can be shared by different subgraphs.
=> [luci] Introduce new functions in FuseBCQPass

compiler/luci/export/src/SerializedData.h, compiler/luci/service/src/CircleShapeInferenceRule.cpp
=> [luci] Fix typo for brief

compiler/exo/src/Circle/CircleExporterUtils.h, compiler/exo/src/Dialect/Service/TFLShapeInferenceRule.cpp, compiler/exo/src/TFLite/TFLExporterUtils.h
=> [exo] Fix typo for brief

compiler/moco/support/src/TFShapeInferenceHelper.cpp
=> [moco] Fix typo for brief

runtime/onert/backend/acl_cl/ConstantInitializer.cc, runtime/onert/backend/acl_cl/KernelGenerator.cc, runtime/onert/backend/acl_cl/KernelGenerator.h, runtime/onert/backend/acl_neon/KernelGenerator.cc, runtime/onert/backend/acl_neon/KernelGenerator.h, runtime/onert/backend/cpu/KernelGenerator.cc, runtime/onert/backend/cpu/KernelGenerator.h, runtime/onert/backend/ruy/KernelGenerator.cc, runtime/onert/backend/ruy/KernelGenerator.h, runtime/onert/core/include/backend/IConstantInitializer.h, runtime/onert/core/src/backend/IConstantInitializer.cc, runtime/onert/core/src/compiler/ShapeValidator.cc, runtime/onert/core/src/compiler/ShapeValidator.h
- rename _current_op_seq_layout to _current_layout as it is outdated
=> [onert] rename _current_op_seq_layout to _current_layout
