compiler/nnc/include/Definitions.h.in

[nnc] Fix typo for brief

---

compute/ARMComputeEx/src/runtime/CL/functions/CLFullyConnectedReshapingLayer.cpp
compute/ARMComputeEx/src/runtime/NEON/functions/NEFullyConnectedReshapingLayer.cpp
runtime/onert/backend/acl_common/Convert.cc
runtime/onert/core/include/ir/DataType.h
runtime/onert/core/src/ir/DataType.cc
runtime/onert/frontend/nnapi/wrapper/NNAPIConvert.cc

- Introduce new type: QUANT_INT8_SYMM_PER_CHANNEL
- Update NNAPI type conversion
- Update acl type conversion

[onert] Revise data type

---

runtime/onert/core/src/ir/OperationValidator.cc
runtime/onert/core/src/ir/OperationValidator.h
tests/nnfw_api/src/one_op_tests/ArgMax.cc

- Enable OperationValidator for ArgMax operation
- Add negative test for ArgMax
- Enable ArgMax test for int64 output

[onert] OperationValidator for ArgMax

---

compiler/luci/pass/src/FuseBCQPass.cpp

Parent Issue : #4961
This commit will update following things
- Applying BCQ to `Einsum` will be handled within `FullyConnected`
- If `do_w_x` is true, `input` of `FullyConnected` is constant. This will be supported.

[luci] Update BCQ application algorithm

---

runtime/onert/core/src/ir/OperationValidator.cc
runtime/onert/core/src/ir/OperationValidator.h

Fix build fail by IR rename: ArgMax -> ArgMinMax

[onert] Fix build fail by IR rename

---

runtime/onert/core/src/compiler/BackendManager.cc

Remove unnecessary indentation in BackendManager

[onert] Fix indentation level in BackendManager

---

tests/nnfw_api/src/ModelTestDynamicTensor.cc
tests/nnfw_api/src/fixtures.h

Use CircleGen based model files(Simple add model) where applicable.

[nnfwapi] Test : avoid downloaded model tests

---

runtime/onert/frontend/base_loader/include/base_loader.h

Revise tensorTypeToDataType function
- Reorder switch/case based on enum order
- Support TensorType_FLOAT16 and TensorType_INT16

[onert] Update base loader data type conversion

---

runtime/onert/frontend/base_loader/include/base_loader.h
runtime/onert/frontend/nnapi/wrapper/OperationFactory.cc

- Support ArgMin on loader and nnapi frontend
- Set is_arg_max param
- Remove operand type duplication in loader: handle on operation validator
---
Related issue: #5115
Part of #5132

[onert] Frontend for ArgMinMax

---

res/TensorFlowLiteRecipes/Mean_U8_dynamic_000/test.recipe
res/TensorFlowLiteRecipes/Mean_dynamic_000/test.recipe
res/TensorFlowLiteRecipes/Mean_dynamic_001/test.recipe
res/TensorFlowLiteRecipes/ReduceAny_dynamic_000/test.recipe
res/TensorFlowLiteRecipes/ReduceAny_dynamic_001/test.recipe
res/TensorFlowLiteRecipes/ReduceAny_dynamic_002/test.recipe
res/TensorFlowLiteRecipes/ReduceAny_dynamic_003/test.recipe
res/TensorFlowLiteRecipes/ReduceMax_dynamic_000/test.recipe
res/TensorFlowLiteRecipes/ReduceMin_dynamic_000/test.recipe
res/TensorFlowLiteRecipes/ReduceProd_dynamic_000/test.recipe
res/TensorFlowLiteRecipes/ReduceProd_dynamic_001/test.recipe
res/TensorFlowLiteRecipes/ReduceProd_dynamic_002/test.recipe
res/TensorFlowLiteRecipes/ReduceProd_dynamic_003/test.recipe
res/TensorFlowLiteRecipes/Sum_dynamic_000/test.recipe
res/TensorFlowLiteRecipes/Sum_dynamic_001/test.recipe

Parent issue : #5037
This commit will add dynamic testcases for following operations
- Mean
- ReduceAny
- ReduceMax
- ReduceMin
- ReduceProd
- Sum

[res] Add dynamic tc for ReduceOps

---

infra/docker/bionic/Dockerfile
infra/docker/focal/Dockerfile
infra/docker/xenial/Dockerfile

For #5061 
[Detail Comment](https://github.com/Samsung/ONE/pull/5061#discussion_r524818539)
This commit add `curl` to docker Additional Tools.

[infra/docker]Update docker script

---

docs/howto/how-to-introduce-a-new-operation-into-runtime.md

- Update cpu's KernelGenerator example code as it is outdated

[docs] update example code in docs

---

docs/howto/index.rst

- Update `index.rst`
- Rearrange orders of topics

Update index of how-to- documents

---

docs/runtime/index.rst

- Update `index.rst` of runtime documents
- Rearrange order of documents

Update index of runtime documents

---

docs/release/1.10/index.rst
docs/release/1.11/index.rst
docs/release/1.5/index.rst
docs/release/1.6/index.rst
docs/release/1.7/index.rst
docs/release/1.8/index.rst
docs/release/1.9/index.rst

- Add missing `index.rst`s for each release folder
- Update `index.rst` of main folder

Update index of release documents

---

runtime/onert/backend/acl_common/Convert.cc

Update exception message for more information

[onert/acl] Update exception message

---

runtime/onert/backend/cpu/ops/BatchMatMulLayer.cc
runtime/onert/core/src/ir/OperationValidator.cc

Check BatchMatMul input/output tensor type in operation validator

[onert] Check BatchMatmul tensor type

---

compiler/luci/pass/include/luci/CircleOptimizer.h
compiler/luci/pass/include/luci/Pass/RemoveRedundantTransposePass.h
compiler/luci/pass/src/CircleOptimizer.cpp
compiler/luci/pass/src/RemoveRedundantTranspose.cpp
compiler/luci/pass/src/RemoveRedundantTranspose.test.cpp

Parent Issue : #5062 
Draft : #5074 
#
This commit introduce pass/RemoveRedundantTranspose on luci/pass.

[luci/pass]Introduce pass/RemoveRedundantTranspose on luci/pass.

---

runtime/onert/frontend/base_loader/include/base_loader.h

Sort operation loading methods declaration ascending in base loader

[onert] Sort baseloader operation loading methods

---

compiler/circle2circle/src/Circle2Circle.cpp

Parent Issue : #5062
Draft : #5074
This commit introduce `RemoveRedundantTranspose` pass in `circle2circle`

[circle2circle]Introduce RemoveRedundantTranspose pass in circle2circle

---

compiler/oops/include/oops/InternalExn.h

This will revise CTORs for int to uint type conversion

[oops] Revise CTOR for type conversion

---

runtime/onert/core/src/ir/OperationValidator.cc
tests/nnfw_api/src/one_op_tests/AddN.cc

Check all operand type are same for AddN operation

[onert] Check same data type for AddN operation

---

docs/release/1.11/release-note-1.11.1.md

Release Note for ONE 1.11.1

---

compiler/pota-quantization-value-test/CMakeLists.txt
compiler/pota-quantization-value-test/gen_h5_explicit_inputs.py
compiler/pota-quantization-value-test/test_record_minmax.sh

This generates input h5 file from circle model

[pota-value-test] Generate input h5 from circle

---

runtime/onert/backend/xnnpack/Backend.h
runtime/onert/backend/xnnpack/BackendContext.h
runtime/onert/backend/xnnpack/ConstantInitializer.cc
runtime/onert/backend/xnnpack/ConstantInitializer.h
runtime/onert/backend/xnnpack/KernelGenerator.cc
runtime/onert/backend/xnnpack/KernelGenerator.h
runtime/onert/backend/xnnpack/StaticTensorManager.cc
runtime/onert/backend/xnnpack/StaticTensorManager.h
runtime/onert/backend/xnnpack/Tensor.cc
runtime/onert/backend/xnnpack/Tensor.h
runtime/onert/backend/xnnpack/TensorBuilder.cc
runtime/onert/backend/xnnpack/TensorBuilder.h
runtime/onert/backend/xnnpack/ops/ConvolutionLayer.cc
runtime/onert/backend/xnnpack/ops/ConvolutionLayer.h
runtime/onert/backend/xnnpack/ops/DepthwiseConvolutionLayer.cc
runtime/onert/backend/xnnpack/ops/DepthwiseConvolutionLayer.h
runtime/onert/backend/xnnpack/ops/Layer.h

Eliminate permuation on xnnpack if possible

[onert] Enable xnnpack to eliminate permuation

---

docs/conf.py
packaging/nnfw.spec
runtime/contrib/android/api/build.gradle
runtime/onert/api/include/nnfw_version.h

ONERT version bump to 1.11.1

---

runtime/onert/backend/cpu/ops/DepthToSpaceLayer.cc

Use switch-case to call DepthToSpace kernel for each type

[onert/cpu] Switch-case for DepthToSpace

---

infra/scripts/docker_build_cross_aarch64_runtime.sh
infra/scripts/docker_build_cross_arm_runtime.sh
infra/scripts/docker_build_cross_arm_runtime_release.sh
infra/scripts/docker_build_cross_coverage.sh
infra/scripts/docker_build_nncc.sh
infra/scripts/docker_build_test_x64.sh
infra/scripts/docker_build_tizen_cross.sh
infra/scripts/docker_collect_nnpkg_resources.sh
infra/scripts/docker_coverage_report.sh

- Add some information about docker image name for easy use

[onert] Add comment about docker image name

---

tests/nnfw_api/src/main.cc

Allow testing without downloaded models. This is for the open-source
contributers(non-Samsung members).

[nnfwapi] Allow testing without downloaded models

---

res/CircleRecipes/InstanceNorm_001/test.recipe

This adds a recipe for InstanceNorm Op
---
Related to: #5121
Draft PR: #5197

[res] Add a recipe for InstanceNorm Op

---

compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp

This adds quantization algorithm for InstanceNorm Op
---
Related to: #5121
Draft PR: #5197

[luci] Quantization algorithm for InstanceNorm

---

docs/howto/how-to-add-a-new-operation.md

doc: fix typo in how-to-add-a-new-operation.md

---

runtime/onert/backend/cpu/ops/ConcatLayer.cc
runtime/onert/core/src/ir/OperationValidator.cc
runtime/onert/core/src/ir/OperationValidator.h
tests/nnfw_api/src/one_op_tests/Concat.cc

Support more type for Concat operation: int8
Add one op test for various types
---
Related issue: #4664

[onert] Support int8 Concat

---

runtime/onert/backend/acl_cl/ConstantInitializer.h
runtime/onert/backend/acl_neon/ConstantInitializer.h
runtime/onert/backend/cpu/ConstantInitializer.h
runtime/onert/backend/ruy/ConstantInitializer.h

- edit constant initializer header guard from _COMPILER_ to _BACKEND_

[onert] update some header guard names

---

compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp

This supports CWQ for PRelu alpha
---
Related to: #5121
Draft PR: https://github.com/Samsung/ONE/pull/5119

[luci] CWQ for PRelu alpha

---

infra/docker/bionic/Dockerfile
infra/docker/focal/Dockerfile
infra/docker/xenial/Dockerfile

Install clang-format-8 to prepare c++ format check version up
---
Related issue: #5131

[infra] Install clang-format-8 in devloper docker image

---

tests/tools/tflite_loader/CMakeLists.txt
tests/tools/tflite_loader/src/tflite_loader.cc

Remove unused function executeGraph
Remove unused headers and dependency

[onert/test] Remove unused function in tflite loader test tool

---

compiler/luci/pass/include/luci/CircleOptimizer.h
compiler/luci/pass/include/luci/Pass/ReplaceMulAddWithDepthwiseConvPass.h
compiler/luci/pass/src/CircleOptimizer.cpp
compiler/luci/pass/src/ReplaceMulAddWithDepthwiseConvPass.cpp

This adds a pass to replace mul/add with depthwise conv
---
Draft PR: #5244

[luci] Add pass to replace mul/add with depthwise conv

---

runtime/onert/backend/xnnpack/ConstantInitializer.cc
runtime/onert/backend/xnnpack/ConstantInitializer.h
runtime/onert/backend/xnnpack/KernelGenerator.cc
runtime/onert/backend/xnnpack/KernelGenerator.h
runtime/onert/backend/xnnpack/ops/FullyConnectedLayer.cc
runtime/onert/backend/xnnpack/ops/FullyConnectedLayer.h
runtime/onert/backend/xnnpack/ops/Layer.h
tests/nnfw_api/src/one_op_tests/FullyConnected.cc

Add FullyConnected Op on xnnpack for float32

[onert] Add FullyConnected Op on xnnpack

---

compiler/circle2circle/src/Circle2Circle.cpp

This adds an option for ReplaceMulAddWithDepthwiseConv
---
Draft PR: #5244

[circle2circle] Add option for ReplaceMulAddWithDepthwiseConv

---

compiler/circle2circle/src/Circle2Circle.cpp

Parent Issue : #5180
Draft : #5182
#
This commit introduce `SubstitutePackToReshape` on Circle2Circle.

[Circle2Circle]Introduce SubstitutePackToReshape

---

compiler/one-cmds/how-to-use-one-commands.txt
compiler/one-cmds/one-optimize

This adds an option for ReplaceMulAddWithDepthwiseConvPass
---
Draft PR: #5244

[one-cmds] Add option for ReplaceMulAddWithDepthwiseConv

---

compute/ruy/include/ruy/NeonTensorUtils.h
compute/ruy/include/ruy/PortableTensorUtils.h
compute/ruy/include/ruy/TensorUtils.h
compute/ruy/include/ruy/Types.h
compute/ruy/include/ruy/neon/neon_check.h
compute/ruy/include/ruy/operation/FullyConnected.h
runtime/onert/backend/ruy/KernelGenerator.cc
runtime/onert/backend/ruy/KernelGenerator.h
runtime/onert/backend/ruy/ops/FullyConnectedLayer.cc
runtime/onert/backend/ruy/ops/FullyConnectedLayer.h
runtime/onert/backend/ruy/ops/OperationUtils.h
tests/nnfw_api/src/one_op_tests/FullyConnected.cc

- This commit supports FullyConnected operation on ruy backend
- ruy backend only supports FullyConnected with FP32 input
---
Related issue #4482

[onert] Support FullyConnected operation on ruy backend

---

compiler/circle2circle/src/Circle2Circle.cpp

This adds cw keyword to replace_mul_add_width_depthwise_conv.

[circle2circle] Add cw keyword to replace_mul_add_width_depthwise_conv.

---

compiler/one-cmds/how-to-use-one-commands.txt
compiler/one-cmds/one-optimize

This add cw keyword to replace_mul_add_width_depthwise_conv.

[one-cmds] Add cw keyword to replace_mul_add_width_depthwise_conv

---

compiler/luci/service/src/Validate.cpp

Parent Issue : #4796
This commit will change method for getting shape and dtype in `luci` validation.
More specifically, `loco::shape_get` and `loco::dtype_get` to shape and dtype of circle node.

[luci] Change method for getting shape/dtype in luci validation

---

.clang-format.8
infra/command/format

- ."clang-format.8" : clang-format style file for clang-format-8
---
Part of #5223 
Related issue: #5131

[infra] Infra for clang-format-8 migration on each directory

---

tools/.clang-format
tools/kbenchmark/kernels/acl_cl/Convolution.cpp
tools/kbenchmark/kernels/acl_cl/TransposeConv.cpp
tools/kbenchmark/kernels/acl_neon/Convolution.cpp
tools/kbenchmark/kernels/acl_neon/TransposeConv.cpp
tools/tflite_accuracy/src/tflite_accuracy.cc

Use clang-format-8 style for tools

[tools] Update clang-format

---

runtime/contrib/.clang-format
runtime/contrib/TFLiteSharp/TFLiteNative/include/tflite_log.h
runtime/contrib/TFLiteSharp/TFLiteNative/include/tflite_nativewrapper.h
runtime/contrib/android/api/src/main/native/onert-native-api.cpp
runtime/contrib/android/api/src/main/native/onert-native-api.h
runtime/contrib/android_benchmark_app/cpp/ndk_main.cpp
runtime/contrib/android_tflite/builtin_ops_jni.cc
runtime/contrib/heap_trace/src/cl_create_buffer_stub.cc
runtime/contrib/heap_trace/src/memory_pool_for_symbol_searcher_internals.h
runtime/contrib/heap_trace/src/trace.cc
runtime/contrib/heap_trace/src/trace.h
runtime/contrib/heap_trace/tests/src/cl_release_mem_object_interception_test.cc
runtime/contrib/heap_trace/tests/src/malloc_interception_test.cc
runtime/contrib/heap_trace/tests/src/realloc_interception_test.cc
runtime/contrib/heap_trace/tests/src/symbol_searcher_test.cc
runtime/contrib/heap_trace/tests/src/trace_test.cc
runtime/contrib/labs/jniacl/src/jniacl_main.cc
runtime/contrib/labs/opencl_test/src/opencl_test.cc
runtime/contrib/labs/tflite_examples/src/conv.cpp
runtime/contrib/style_transfer_app/src/bitmap_helper.cc
runtime/contrib/style_transfer_app/src/jpeg_helper.cc
runtime/contrib/style_transfer_app/src/style_transfer_app.cc
runtime/contrib/tflite_classify/src/ImageClassifier.cc
runtime/contrib/tflite_classify/src/InferenceInterface.cc
runtime/contrib/tflite_classify/src/tflite_classify.cc

Use clang-format-8 style for runtime/contrib

[runtime/contrib] Update clang-format

---

runtime/libs/.clang-format
runtime/libs/benchmark/src/CsvWriter.cpp
runtime/libs/benchmark/src/MemoryPoller.cpp
runtime/libs/benchmark/src/Result.cpp
runtime/libs/misc/include/misc/feature/Index.h
runtime/libs/misc/include/misc/feature/Shape.h
runtime/libs/misc/include/misc/kernel/Shape.h
runtime/libs/misc/include/misc/tensor/Object.h
runtime/libs/misc/include/misc/tensor/Zipper.h
runtime/libs/misc/src/tensor/Comparator.cpp
runtime/libs/nnapi/include/NeuralNetworksShim.h
runtime/libs/nnapi/include/NeuralNetworksTypes.h
runtime/libs/rua/dyn/src/DynamicBinder.cpp
runtime/libs/tflite/include/tflite/Diff.h
runtime/libs/tflite/include/tflite/RandomTestRunner.h
runtime/libs/tflite/include/tflite/TensorLogger.h
runtime/libs/tflite/src/Diff.cpp
runtime/libs/tflite/src/RandomTestRunner.cpp

Use clang-format-8 style for runtime/libs

[onert/libs] Update clang-format

---

tests/.clang-format
tests/custom_op/FillFrom/FillFrom_runner.cc
tests/nnfw_api/.clang-format
tests/tools/nnpackage_run/src/allocation.h
tests/tools/nnpackage_run/src/h5formatter.cc
tests/tools/nnpackage_run/src/nnfw_util.cc
tests/tools/nnpackage_run/src/nnpackage_run.cc
tests/tools/nnpackage_run/src/randomgen.cc
tests/tools/tflite_loader/src/tflite_loader.cc
tests/tools/tflite_run/src/bin_image.cc
tests/tools/tflite_run/src/tensor_loader.cc
tests/tools/tflite_run/src/tflite_run.cc
tests/tools/tflite_vanilla_run/src/tflite_vanilla_run.cc

Use clang-format-8 style for tests/

[onert/test] Update clang-format

---

runtime/onert/core/src/util/EventCollector.h

- Fix coverity defect on EventCollector.

Fix defect 1217377: uninitialized members

---

tests/tools/tflite_loader/src/tflite_loader.cc

- Support all input type
- Implement comparison function for all data type (copy from GenModelTest.h)
- Support thread setting environment variable
---
Part of #5212

[onert/test] TFlite model test support all input type

---

docs/release/1.12/index.rst
docs/release/1.12/release-note-1.12.0.md

- Release Note for ONE 1.12.0
- index.rst added

Release Note for ONE 1.12.0

---

tests/nnfw_api/src/ValidationTestMultipleSessions.cc

Workaround for TCM tool (no assertion)

[release/1.12.0] [test/nnfw_api] Test: Workaround for TCM

---

runtime/onert/backend/acl_neon/BackendContext.cc
runtime/onert/backend/cpu/ops/ArgMinMaxLayer.cc
runtime/onert/backend/cpu/ops/LSTMLayer.cc
runtime/onert/backend/ruy/Config.cc
runtime/onert/backend/xnnpack/Config.cc
runtime/onert/core/include/exec/IExecutor.h
runtime/onert/core/src/backend/cpu_common/Tensor.cc
runtime/onert/core/src/compiler/pass/Pass.h
runtime/onert/core/src/ir/OpSequence.cc
runtime/onert/core/src/ir/OperationValidator.cc

- Fix namespace typo
- Add namespace comment for anonymous

[onert] Fix namespace comment

---

compiler/luci/lang/include/luci/IR/Nodes/CircleReshape.h

This will fix comment for Reshape 'shape' input

[luci] Fix comment for Reshape 'shape' input

---

tests/nnfw_api/src/ValidationTestMultipleSessions.cc

Workaround for TCM tool (no assertion)

[test/nnfw_api] Test: Workaround for TCM

---

compiler/bino/.clang-format
compiler/bino/include/bino.h

Use clang-format-8 style for bino

[bino] Update clang-format version

---

compiler/circlechef/.clang-format
compiler/circlechef/core/src/ModelChef.cpp
compiler/circlechef/core/src/Op/BCQFullyConnected.cpp
compiler/circlechef/core/src/Op/BCQGather.cpp
compiler/circlechef/core/src/Op/BatchMatMul.cpp
compiler/circlechef/tools/file/Driver.cpp
compiler/circlechef/tools/reverse/Driver.cpp

Use clang-format-8 style for circlechef

[circlechef] Update clang-format version

---

compiler/circle2circle/.clang-format
compiler/circle2circle/src/Circle2Circle.cpp
compiler/circle2circle/src/TestHelper.h

Use clang-format-8 style for circle2circle

[circle2circle] Update clang-format version

---

compiler/angkor/.clang-format
compiler/angkor/include/nncc/core/ADT/feature/Overlay.h
compiler/angkor/include/nncc/core/ADT/feature/Shape.h
compiler/angkor/include/nncc/core/ADT/kernel/Overlay.h
compiler/angkor/include/nncc/core/ADT/kernel/Shape.h
compiler/angkor/include/nncc/core/ADT/tensor/Overlay.h
compiler/angkor/include/nncc/core/ADT/tensor/View.h
compiler/angkor/src/ADT/feature/Overlay.test.cpp
compiler/angkor/src/ADT/kernel/Overlay.test.cpp
compiler/angkor/src/ADT/tensor/Overlay.test.cpp

Use clang-format-8 style for angkor

[angkor] Update clang-format version

---

compiler/arser/.clang-format
compiler/arser/include/arser/arser.h
compiler/arser/tests/arser.test.cpp

Use clang-format-8 style for arser

[arser] Update clang-format version

---

compiler/cwrap/.clang-format
compiler/cwrap/src/Fildes.test.cpp

Use clang-format-8 style for cwrap

[cwrap] Update clang-format version

---

compiler/common-artifacts/.clang-format
compiler/common-artifacts/src/TestDataGenerator.cpp

Use clang-format-8 style for common-artifacts

[common-artifacts] Update clang-format version

---

docs/release/1.12/release-note-1.12.1.md

This commit contains a 1.12.1 compiler release note.
Related : #5376 

[release] 1.12.1 compiler release note

---

compiler/enco/.clang-format
compiler/enco/core/src/ANN/Binder.h
compiler/enco/core/src/ANN/Context.test.cpp
compiler/enco/core/src/ANN/IR/Operation.h
compiler/enco/core/src/AsmCode.h
compiler/enco/core/src/Backend.cpp
compiler/enco/core/src/CodeIndex.h
compiler/enco/core/src/CppGen/Host.cpp
compiler/enco/core/src/CppGen/Subnet.cpp
compiler/enco/core/src/Support/Debugging.cpp
compiler/enco/core/src/Transforms/Split.cpp
compiler/enco/core/src/Transforms/Split.h
compiler/enco/frontend/caffe/src/Context.h
compiler/enco/frontend/caffe/src/Layer/Convolution.cpp
compiler/enco/frontend/tflite/src/Context.cpp
compiler/enco/frontend/tflite/src/Context.h
compiler/enco/frontend/tflite/src/GraphBuilderRegistry.h
compiler/enco/frontend/tflite/src/Op/AveragePool2D.cpp
compiler/enco/frontend/tflite/src/Op/Conv2D.cpp
compiler/enco/frontend/tflite/src/Op/DepthwiseConv2D.cpp
compiler/enco/frontend/tflite/src/Op/MaxPool2D.cpp

Use clang-format-8 style for enco

[enco] Update clang-format version

---

compiler/exo/.clang-format
compiler/exo/src/Circle/CircleExporterImpl.cpp
compiler/exo/src/Circle/CircleExporterUtils.cpp
compiler/exo/src/Circle/CircleOperationExporter.cpp
compiler/exo/src/Conversion/DepthwiseConv2DConverter.cpp
compiler/exo/src/Dialect/IR/CircleNodes.h
compiler/exo/src/Dialect/IR/TFLNodes.h
compiler/exo/src/Dialect/Service/TFLShapeInferenceRule.test.cpp
compiler/exo/src/GraphBlock.h
compiler/exo/src/LoggingContext.cpp
compiler/exo/src/Pass/FoldTransposeOfConstPass.cpp
compiler/exo/src/Pass/FuseBiasAddPass.cpp
compiler/exo/src/Pass/FuseInstanceNormPass.cpp
compiler/exo/src/Pass/FuseReluPass.test.cpp
compiler/exo/src/Pass/MergeConcatNodesPass.cpp
compiler/exo/src/Pass/ShapeInferencePass.cpp
compiler/exo/src/Pass/TypeInferencePass.cpp
compiler/exo/src/ProgressReporter.h
compiler/exo/src/TFLite/TFLExporterImpl.cpp
compiler/exo/src/TFLite/TFLExporterImpl.test.cpp
compiler/exo/src/TFLite/TFLExporterUtils.cpp
compiler/exo/src/TFLite/TFLOperationExporter.cpp
compiler/exo/src/TFLite/TFLTensorExporter.cpp
compiler/exo/src/TestGraph.h

Use clang-format-8 style for exo

[exo] Update clang-format version

---

compiler/locomotiv/.clang-format
compiler/locomotiv/include/locomotiv/Session.h
compiler/locomotiv/src/Node/AvgPool2D.cpp
compiler/locomotiv/src/Node/AvgPool2D.test.cpp
compiler/locomotiv/src/Node/BiasAdd.cpp
compiler/locomotiv/src/Node/Conv2D.cpp
compiler/locomotiv/src/Node/Conv2D.test.cpp
compiler/locomotiv/src/Node/DepthwiseConv2D.cpp
compiler/locomotiv/src/Node/DepthwiseConv2D.test.cpp
compiler/locomotiv/src/Node/DepthwiseFilterEncode.cpp
compiler/locomotiv/src/Node/DepthwiseFilterEncode.test.cpp
compiler/locomotiv/src/Node/FeatureCodec.test.cpp
compiler/locomotiv/src/Node/FeatureDecode.cpp
compiler/locomotiv/src/Node/FeatureEncode.cpp
compiler/locomotiv/src/Node/FilterEncode.cpp
compiler/locomotiv/src/Node/FilterEncode.test.cpp
compiler/locomotiv/src/Node/MatrixCodec.test.cpp
compiler/locomotiv/src/Node/MatrixDecode.cpp
compiler/locomotiv/src/Node/MatrixEncode.cpp
compiler/locomotiv/src/Node/MaxPool2D.cpp
compiler/locomotiv/src/Node/MaxPool2D.test.cpp
compiler/locomotiv/src/Node/TensorConcat.cpp
compiler/locomotiv/src/Node/TransposedConv2D.cpp
compiler/locomotiv/src/Node/TransposedConv2D.test.cpp
compiler/locomotiv/src/NodeExecution.h

Use clang-format-8 style for locomotiv

[locomotiv] Update clang-format version

---

compiler/locop/.clang-format
compiler/locop/src/FormattedTensorShape.cpp
compiler/locop/src/NodeSummary.cpp

Use clang-format-8 style for locop

[locop] Update clang-format version

---

compiler/logo/.clang-format
compiler/logo/src/Passes/ConstantFoldingPass.cpp
compiler/logo/src/Passes/SimplifyDomainConversionPass.cpp

Use clang-format-8 style for logo

[logo] Update clang-format version

---

compiler/loco/.clang-format
compiler/loco/include/loco/IR/Nodes.h
compiler/loco/include/loco/IR/Padding2D.h
compiler/loco/src/IR/Graph.test.cpp
compiler/loco/src/Service/CanonicalShapeInferenceRule.cpp
compiler/loco/src/Service/GraphBuilder.h
compiler/loco/src/Service/GraphTestcase.h
compiler/loco/src/Service/MultiDialectShapeInferenceRule.test.cpp
compiler/loco/src/Service/TypeInference.test.cpp
compiler/loco/src/tensorflow.test.cpp

Use clang-format-8 style for loco

[loco] Update clang-format version

---

compiler/tf2tfliteV2/tf2tfliteV2.py

This supports input_shapes with --v2 option
---
Related to: #5387

[tf2tfliteV2] Support input_shapes with --v2 option

---

compiler/nest/.clang-format
compiler/nest/core/include/nest/expr/AddNode.h
compiler/nest/core/include/nest/expr/DerefNode.h
compiler/nest/core/include/nest/expr/MulNode.h
compiler/nest/core/src/Block.test.cpp
compiler/nest/core/src/Closure.test.cpp
compiler/nest/core/src/Expr.test.cpp
compiler/nest/core/src/Ret.test.cpp
compiler/nest/core/src/expr/AddNode.test.cpp
compiler/nest/core/src/expr/DerefNode.test.cpp
compiler/nest/core/src/expr/MulNode.test.cpp
compiler/nest/core/src/stmt/PushNode.test.cpp

Use clang-format-8 style for nest

[nest] Update clang-format version

---

compiler/nnkit-intf/.clang-format
compiler/nnkit-intf/tensor/include/nnkit/TensorContext.h

Use clang-format-8 style for nnkit-inf

[nnkit-inf] Update clang-format version

---

compiler/nnkit-onnxrt/.clang-format
compiler/nnkit-onnxrt/support/include/nnkit/support/onnx/TensorSet.h

Use clang-format-8 style for nnkit-onnxrt

[nnkit-onnxrt] Update clang-format version

---

compiler/nnsuite/.clang-format
compiler/nnsuite/conv/model/src/RandomModel.cpp
compiler/nnsuite/conv/nnkit-caffe/ConvBackend.test.cpp
compiler/nnsuite/conv/nnkit-tflite/ConvBackend.cpp
compiler/nnsuite/conv/nnkit-tflite/ConvBackend.test.cpp

Use clang-format-8 style for nnsuite

[nnsuite] Update clang-format version

---

compiler/nnop/.clang-format
compiler/nnop/include/nnop/PadInfo.h
compiler/nnop/include/nnop/StrideInfo.h

Use clang-format-8 style for nnop

[nnop] Update clang-format version

---

compiler/nnkit-tf/.clang-format
compiler/nnkit-tf/support/include/nnkit/support/tf/TensorContext.h
compiler/nnkit-tf/support/include/nnkit/support/tf/TensorDataMap.h
compiler/nnkit-tf/support/src/Backend.cpp
compiler/nnkit-tf/support/src/Runner.cpp

Use clang-format-8 style for nnkit-tf

[nnkit-tf] Update clang-format version

---

compiler/mir2loco/.clang-format
compiler/mir2loco/src/mir2loco.test.cpp

Use clang-format-8 style for mir2loco

[mir2loco] Update clang-format version

---

compiler/luci-interpreter/src/kernels/Prelu.cpp
compiler/luci-interpreter/src/kernels/Prelu.h
compiler/luci-interpreter/src/kernels/Prelu.test.cpp
compiler/luci-interpreter/src/kernels/Utils.h

Support PReLU with CWQ alpha argument and layer-wise quantized input/output

[luci-interpreter] Support PReLU with channel-wise quantization

---

compiler/oneco/.clang-format
compiler/oneco/src/GraphBuilder.h
compiler/oneco/src/GraphBuilderContext.h
compiler/oneco/src/GraphBuilderRegistry.h
compiler/oneco/src/Op/Constant.h
compiler/oneco/src/Op/Identity.h

Use clang-format-8 style for oneco

[oneco] Update clang-format version

---

compiler/oops/.clang-format
compiler/oops/include/oops/InternalExn.h
compiler/oops/include/oops/UserExn.h

Use clang-format-8 style for oops

[oops] Update clang-format version

---

compiler/record-minmax/.clang-format
compiler/record-minmax/driver/Driver.cpp
compiler/record-minmax/include/RecordFunction.h

Use clang-format-8 style for record-minmax

[record-minmax] Update clang-format version

---

compiler/tfinfo-v2/.clang-format
compiler/tfinfo-v2/include/tfinfo-v2/TensorSignature.h
compiler/tfinfo-v2/src/TFInfo_v2.test.cpp
compiler/tfinfo-v2/src/TensorInfoLoader.cpp

Use clang-format-8 style for tfinfo-v2

[tfinfo-v2] Update clang-format version

---

compiler/tfkit/.clang-format
compiler/tfkit/src/PackCommand.cpp
compiler/tfkit/src/Support.hpp
compiler/tfkit/src/UnpackCommand.cpp

Use clang-format-8 style for tfkit

[tfkit] Update clang-format version

---

compiler/tflchef/.clang-format
compiler/tflchef/core/src/ModelChef.cpp
compiler/tflchef/core/src/Op/BidirectionalSequenceLSTM.cpp
compiler/tflchef/core/src/Op/BidirectionalSequenceLSTM.h
compiler/tflchef/core/src/Op/LocalResponseNormalization.h
compiler/tflchef/core/src/Op/Squeeze.cpp
compiler/tflchef/core/src/Op/StridedSlice.cpp
compiler/tflchef/core/src/Op/UnidirectionalSequenceLSTM.cpp
compiler/tflchef/core/src/Op/UnidirectionalSequenceLSTM.h
compiler/tflchef/tools/file/Driver.cpp
compiler/tflchef/tools/reverse/Driver.cpp

Use clang-format-8 style for tflchef

[tflchef] Update clang-format version

---

compiler/tfldump/.clang-format
compiler/tfldump/src/OpPrinter.cpp

Use clang-format-8 style for tfldump

[tfldump] Update clang-format version

---

compiler/tfinfo/.clang-format
compiler/tfinfo/include/nnkit/support/tftestinfo/ParsedTensor.h

Use clang-format-8 style for tfinfo

[tfinfo] Update clang-format version

---

compiler/nnkit/.clang-format
compiler/nnkit/actions/HDF5/Export.cpp
compiler/nnkit/tools/run/nnkit-run.cpp

Use clang-format-8 style for nnkit

[nnkit] Update clang-format version

---

tests/tools/nnpackage_run/src/h5formatter.cc
tools/nnpackage_tool/gen_golden/gen_golden.py

It supports int8 load and dump in nnpkg_run and gen_golden.

[nnpkg_run, gen_golden] Support int8 input and output

---

runtime/onert/core/src/ir/Shape.cc

- Rename params
- Refine if and assert conditions

[onert] Refine permuteShape implementation

---

tools/nnpackage_tool/gen_golden/gen_golden.py

gen_golden will generate [-127,127] random input for int8 input type.

[gen_golden] Support int8 quantization random input

---

compute/cker/include/cker/Types.h
compute/cker/include/cker/Utils.h
compute/cker/include/cker/operation/SoftMax.h
runtime/onert/backend/cpu/ops/SoftMaxLayer.cc
runtime/onert/backend/cpu/ops/SoftMaxLayer.h

Use tensorflow lite 2.3 softmax quantized data kernel

[cker] Update quantization softmax kernel

---

runtime/onert/backend/cpu/ops/FullyConnectedLayer.cc

- This commit releases freed weight of fullyconnected layer immediately

[onert] Release freed weight of fullyconnected layer immediately

---

compute/cker/include/cker/operation/Quantize.h

This commit removes duplicated function MultiplyByQuantizedMultiplier4Rows

[cker] Remove duplicated function

---

compute/cker/include/cker/operation/Quantize.h
runtime/onert/backend/cpu/ops/QuantizeLayer.cc
tests/nnfw_api/src/one_op_tests/Quantize.cc

It supports quantize operator (int8 to uint8).

[onert] Support quantize operator (int8 to uint8)

---

runtime/onert/core/src/backend/builtin/BackendContext.cc

Make builtin backend reuse `cpu_common::genTensors`. This should have
been done earlier, but may have been forgotten.

[onert] Make builtin backend reuse `genTensors`

---

compiler/luci/pass/include/luci/CircleOptimizer.h
compiler/luci/pass/include/luci/Pass/ConvertNCHWToNHWCPass.h
compiler/luci/pass/src/CircleOptimizer.cpp
compiler/luci/pass/src/ConvertNCHWToNHWCPass.cpp

This introduces a pass to convert NCHW to NHWC for ADD Op.
---

[luci] Convert NCHW to NHWC for ADD

---

compiler/luci/pass/src/ConvertNCHWToNHWCPass.cpp

This updates format of ConvertNCHWToNHWCPass.cpp.

[luci] Update format of ConvertNCHWToNHWCPass.cpp

---

compute/cker/include/cker/operation/optimized/BinaryArithmeticOps.h
runtime/onert/backend/cpu/ops/BinaryArithmeticLayer.cc
tests/nnfw_api/src/CircleGen.cc
tests/nnfw_api/src/CircleGen.h
tests/nnfw_api/src/one_op_tests/Mul.cc

Mul supports both of int8 and uint8 quantization.

[onert] Support Mul int8 quantization

---

runtime/onert/core/include/compiler/GraphLowerInfo.h
runtime/onert/core/include/compiler/LoweredGraph.h
runtime/onert/core/include/compiler/OpSequenceLowerInfo.h

Fix ifdef guards correctly. (Fix for #5493)

[onert] Fix ifdef guards

---

compute/cker/include/cker/operation/optimized/BinaryArithmeticOps.h
runtime/onert/backend/cpu/ops/BinaryArithmeticLayer.cc
tests/nnfw_api/src/CircleGen.cc
tests/nnfw_api/src/CircleGen.h
tests/nnfw_api/src/one_op_tests/Sub.cc

It supports Sub int8 quantization.

[onert] Support Sub int8 quantization

---

compiler/luci/pass/src/ConvertNCHWToNHWCPass.cpp

This converts NCHW to NHWC for CIRCLEINPUT and CIRCLEOUTPUT
---

[luci] Convert NCHW to NHWC (CIRCLEINPUT, CIRCLEOUTPUT)

---

compiler/luci/pass/src/FuseInstanceNormPass.cpp

This commit will remove `shape_get` and `dtype_get` of loco in `FuseInstanceNormPass`

[luci] Remove shape/dtype getter of loco in FuseInstanceNormPass

---

compiler/luci/pass/src/ConvertNCHWToNHWCPass.test.cpp

This introduces tests for ConvertNCHWToNHWCPass.
---

[luci] Introduce tests for ConvertNCHWToNHWCPass

---

compiler/luci/pass/src/ResolveCustomOpMatMulPass.cpp

This commit will remove shape and dtype getter of loco in `ResolveCustomOpMatMulPass`

[luci] Remove shape/dtype getter of loco in ResolveCustomOpMatMulPass

---

tests/nnfw_api/CMakeLists.txt

Add nnpackage model will be installed for validation test

[onert/test] Install add nnpackage model for test

---

runtime/onert/core/include/ir/TypeInfo.h
runtime/onert/frontend/base_loader/include/base_loader.h

: Introduce loadQuantization()
: Remove shape parameter from loadSparsity

[onert] Make base_loader to  Sparsity and Quantization in similar way

---

compiler/luci/pass/src/ConvertNCHWToNHWCPass.test.cpp

This performs refactoring of ConvertNCHWToNHWCPass test.

[luci] Refactoring of ConvertNCHWToNHWCPass test

---

compiler/luci/import/src/PostImport.cpp

This commit will update shape and dtype validation in `PostImport` as following.
- CircleIf : Consider unknown dimension
- CircleWhile : Consider unknown dimension + Remove redundant checks

[luci] Update shape/dtype validation in PostImport

---

compiler/luci/pass/include/luci/CircleOptimizer.h
compiler/luci/pass/include/luci/Pass/RemoveUnnecessarySplitPass.h
compiler/luci/pass/src/CircleOptimizer.cpp
compiler/luci/pass/src/RemoveUnnecessarySplitPass.cpp
compiler/luci/pass/src/RemoveUnnecessarySplitPass.test.cpp

For #5456 
This commit will introduce `RemoveUnnecessarySplitPass` on luci/pass.

[luci/pass] Introduce RemoveUnnecessarySplitPass on luci/pass

---

runtime/onert/backend/cpu/ops/PadLayer.cc
tests/nnfw_api/src/one_op_tests/Pad.cc

This commit enables quantized Pad(Pad/PadV2) operation
---
Related issue: #4664

[onert] Support quantized Pad operation

---

runtime/onert/frontend/base_loader/include/base_loader.h

`onert` assumes zero_point is in range of int32_t.
Thus, it throws error when it sees out-of-range zeropoint.

[onert] throws error when zero_point is out of int32 range

---

infra/scripts/tizen_xu4_test.sh
tests/scripts/CMakeLists.txt
tests/scripts/command/prepare-model
tests/scripts/models/nnfw_api_gtest/add/config.sh
tests/scripts/models/nnfw_api_gtest/add_invalid_manifest/config.sh
tests/scripts/models/nnfw_api_gtest/add_no_manifest/config.sh
tests/scripts/models/nnfw_api_gtest/if_dynamic/config.sh
tests/scripts/models/nnfw_api_gtest/while_dynamic/config.sh

This commit removes config script to download nnpackage and update related test script

[infra] Remove nnpackage download config script

---

compiler/luci/pass/src/ConvertNCHWToNHWCPass.cpp
compiler/luci/pass/src/ConvertNCHWToNHWCPass.test.cpp

This supports MUL in ConvertNCHWToNHWCPass.
---

[luci] ConvertNCHWToNHWC Pass for MUL Op

---

compiler/luci/pass/src/CircleTypeInferencePass.cpp

Until now, `loco::postorder_traversal` and `loco::output_nodes` were used for getting candidates.
However, some nodes were not inferred even they are not dead nodes.
For example, `While_002` test has following graph.
```
+-- CircleWhileOut(ofm1) -- CircleOutput
CircleWhile --+
+-- CircleWhileOut(ofm2)
```
In the above graph, `ofm2` is not used for graph output but it is not dead node because it is essential virtual circle node.
As a result, it is not checked by current traversal and then it becomes to have invalid type.
To prevent this, this commit will change the traversal method.

[luci] Change candidates for circle type inference pass

---

compiler/luci/pass/src/ConvertNCHWToNHWCPass.cpp
compiler/luci/pass/src/ConvertNCHWToNHWCPass.test.cpp

This supports PAD in ConvertNCHWToNHWCPass.
---

[luci] ConvertNCHWToNHWC Pass for PAD Op

---

compiler/luci/service/src/Validate.cpp

Until now, unknown dimension is not considered at shape validation.
This commit will apply those consideration to shape validation codes.

[luci] Update shape validation code

---

compiler/one-cmds/one-optimize
compiler/one-cmds/utils.py

This commit updates one-cmds' optimization option.
Related : #5556 

[one-cmds] Update one-cmds' optimization option

---

compiler/luci/pass/src/SubstitutePackToReshapePass.cpp

Until now, unknown dimension is not considered in `SubstitutePackToReshapePass`.
However, if `Pack` operation has less or equal than one unknown dimension,
the pass is still applicable.
This commit will support it.

[luci] Support unknown dimension in SubstitutePackToReshapePass

---

compiler/one-cmds/how-to-prepare-virtualenv.txt
compiler/one-cmds/one-prepare-venv

This will revise one-prepare-venv to install onnx import related
packages.

[one-cmds] Revise one-prepare-venv for onnx

---

compiler/one-cmds/one-import-onnx

This will introduce one-import-onnx to convert onnx to circle file.

[one-cmds] Introduce one-import-onnx

---

compiler/one-cmds/one-build.template.cfg

This will add one-import-onnx item as False to config template.

[one-cmds] Add one-import-onnx to cfg template

---

compiler/one-cmds/tests/prepare_test_materials.sh

This will revise prepare_test_materials script to prepare
one-import-onnx basic onnx test model.

[one-cmds] Revise prepare test materials

---

compiler/luci/pass/src/ResolveCustomOpMatMulPass.cpp

If there is no `bias` in `FullyConnected`, there are two ways to represent it.
- Create constant node and fill it with 0
- Create `CircleOutputExclude` and do nothing
Until now, first way is used but it is inefficient and unknown dimension should be considered.
Therefore this commit will change it to second way, which is more efficient and simple.

[luci] Remove redundant constant creation in ResolveCustomOpMatMulPass

---

compiler/circle2circle/src/Circle2Circle.cpp

This adds option for ConvertNCHWToNHWC pass.
---

[circle2circle] Add option for ConvertNCHWToNHWC pass

---

runtime/onert/core/src/compiler/LoweredGraph.cc

Refine `LoweredGraph::dumpLowerInfo`.
- Refine implementations to be more readable
- Print less lines for an operand entry

[onert] Refine LoweredGraph::dumpLowerInfo

---

compiler/luci/pass/src/FuseInstanceNormPass.cpp

Related Issue : #5501
This commit will update following things in `FuseInstanceNormPass`.
- If some dimension is unknown, `FuseInstanceNormPass` cannot be applied
- Reshape of `CircleConst` creates redundant `CircleReshape`. Thus just reshape the `CircleConst`

[luci] Update logic of FuseInstanceNormPass

---

compiler/circle2circle/src/Circle2Circle.cpp

For #5575 
This commit will introduce `RemoveUnneccesaryReshape` on circle2circle.

[circle2circle] Introduce RemoveUnneccesaryReshape on circle2circle.

---

compiler/one-cmds/tests/prepare_test_materials.sh

This will revise prepare_test_materials shell script to download
onnx_conv2d_conv2d.onnx model.

[one-cmds] Revise prepare_test_materials script

---

compiler/luci/service/src/CircleShapeInferenceRule.cpp

This supports shape inference for int64 SparseToDense.
---
Related to : #5598
Draft PR: #5621

[luci] Shape inference for int64 SparseToDense

---

res/TensorFlowLiteRecipes/Net_Conv_Add_Mul_000/test.recipe
res/TensorFlowLiteRecipes/Net_Conv_Add_Mul_000/test.rule
res/TensorFlowLiteRecipes/Net_Conv_Add_Mul_001/test.recipe
res/TensorFlowLiteRecipes/Net_Conv_Add_Mul_001/test.rule
res/TensorFlowLiteRecipes/Net_Conv_Add_Mul_002/test.recipe
res/TensorFlowLiteRecipes/Net_Conv_Add_Mul_002/test.rule
res/TensorFlowLiteRecipes/Net_Conv_Add_Mul_003/test.recipe
res/TensorFlowLiteRecipes/Net_Conv_Add_Mul_003/test.rule

Parent Issue : #5618
This commit will introduce new test cases for validating `FuseBatchNormWithConvPass`.

[res] Introduce FuseBatchNormWithConv test cases

---

compiler/one-cmds/one-optimize
compiler/one-cmds/utils.py

This will enable convert_nchw_to_nhwc option in one-build and
one-optimize.

[one-cmds] Add convert_nchw_to_nhwc option

---

compiler/one-cmds/one-optimize
compiler/one-cmds/utils.py

For #5575 
This commit will update `one-cmd` option for RemoveUnnecessaryReshape.

[one-cmd] Add option for RemoveUnnecessaryReshape

---

compute/cker/include/cker/operation/Conv.h
compute/cker/include/cker/operation/reference/Conv.h
runtime/onert/backend/cpu/ops/ConvolutionLayer.cc
runtime/onert/backend/cpu/ops/ConvolutionLayer.h
runtime/onert/core/src/ir/OperationValidator.cc
tests/nnfw_api/src/one_op_tests/Conv2D.cc

: Introduce convQuant8PerChannel
: Add two positive and two negative testcases for int8

[onert] Support Conv2D int8 channel-wise quantization

---

compiler/one-cmds/one-build
compiler/one-cmds/tests/one-build_neg_003.test

This will revise one-build section error message.

[one-cmds] Revise one-build section error message

---

compiler/luci/pass/include/luci/Pass/FuseBatchNormWithConvPass.h
compiler/luci/pass/src/FuseBatchNormWithConvPass.cpp

Parent Issue : #5618
This commit will introduce `FuseBatchNormWithConvPass`.

[luci] Introduce FuseBatchNormWithConvPass

---

compiler/luci/pass/src/FoldSparseToDensePass.test.cpp
compiler/luci/pass/src/PassTestGraphs.h
compiler/luci/pass/src/PassTestUtils.h

This adds tests for FoldSparseToDensePass.
---
Related to : #5598
Draft PR: #5621

[luci] Tests for FoldSparseToDense Pass

---

runtime/onert/core/include/compiler/PermuteFactor.h
runtime/onert/core/src/compiler/PermuteFactor.cc
runtime/onert/core/src/compiler/pass/ConstantInsertionPass.cc

Leave some log messages of ConstantInsertionPass.

[onert] Logging in ConstantInsertionPass

---

compiler/luci/import/include/luci/Import/Nodes.h
compiler/luci/import/include/luci/Import/Nodes/CircleFakeQuant.h
compiler/luci/import/src/GraphBuilderRegistry.cpp
compiler/luci/import/src/Nodes/CircleFakeQuant.cpp

This will enable import of FAKE_QUANT Op.

[luci] Import FAKE_QUANT

---

compiler/luci/logex/src/FormattedGraph.cpp

This will enable logging for CircleFakeQuant IR.

[luci] Enable LOG for CircleFakeQuant

---

compiler/tfldump/src/OpPrinter.cpp

This will enable tflite file dump of FAKE_QUANT Op.

[tfldump] Enable FAKE_QUANT

---

compiler/luci/export/src/CircleOperationExporter.cpp

This will enable export of CircleFakeQuant node.

[luci] Export CircleFakeQuant

---

compiler/circledump/src/OpPrinter.cpp

This will enable circle file dump of FAKE_QUANT Op.

[circledump] Enable FAKE_QUANT

---

compiler/common-artifacts/exclude.lst

This will add exclude item for tcgenerate Slice_001.

[common-artifacts] Add exclude for Slice_001

---

compiler/circle2circle/src/Circle2Circle.cpp

This adds an option to fold SparseToDense op.
---
Related to : #5598
Draft PR: #5621

[circle2circle] Option to fold SparseToDense op

---

compiler/common-artifacts/exclude.lst

This will add tcgenerate(FakeQuant_000) to exclude list.

[common-artifacts] Exclude FakeQuant_000

---

res/TensorFlowLiteRecipes/Slice_001/test.recipe

This will add Slice_001 tflite recipe with negative begin.

[res] Add Slice_001 recipe

---

compiler/common-artifacts/exclude.lst

This will add exclude list of tcgenerate(ExpandDims_004)

[common-artifacts] Add exclude ExpandDims_004

---

compiler/one-cmds/how-to-use-one-commands.txt
compiler/one-cmds/one-optimize
compiler/one-cmds/utils.py

This supports folding SparseToDense Op.
---
Related to : #5598
Draft PR: #5621

[one-cmds] Support folding SparseToDense Op

---

res/TensorFlowLiteRecipes/ExpandDims_004/test.recipe

This will add ExpandDims_004 tfl recipe where axis(second input) is -1.

[res] Add ExpandDims_004 recipe

---

compiler/luci/pass/include/luci/CircleOptimizer.h
compiler/luci/pass/include/luci/Pass/FoldAddV2Pass.h
compiler/luci/pass/src/CircleOptimizer.cpp
compiler/luci/pass/src/FoldAddV2Pass.cpp

This adds a Pass to fold AddV2 operator.
---
Draft PR: #5677

[luci] Pass to fold AddV2 operator

---

compiler/tflchef/tflite/src/Op/Maximum.cpp
compiler/tflchef/tflite/src/Op/Minimum.cpp

This commit updates Maximum, Minimum filler.

[tflchef] Update Maximum, Minimum filler

---

runtime/onert/core/src/ir/OperationValidator.cc

Fix Pad(v2) op validation, make it follow NN API spec.

[onert] Fix Pad(v2) op validation

---

compiler/circle2circle/src/Circle2Circle.cpp

This adds an option to fold AddV2 operator.
---
Draft PR: #5677

[circle2circle] Option to fold AddV2 operator

---

compiler/one-cmds/how-to-use-one-commands.txt
compiler/one-cmds/one-optimize
compiler/one-cmds/utils.py

This supports the fold_add_v2 option.
---
Draft PR: #5677

[one-cmds] Support for fold_add_v2 option

---

compiler/luci/pass/src/FoldAddV2Pass.test.cpp

This adds tests for FoldAddV2 pass.
---
Draft PR: #5677

[luci] Test for FoldAddV2 pass

---

compiler/luci/pass/src/ConvertNCHWToNHWCPass.cpp

This replaces assert to skip code.
---
For #5709

[luci] Bug fix for ConvertNCHWToNHWCPass

---

compiler/luci/pass/include/luci/CircleOptimizer.h
compiler/luci/pass/include/luci/Pass/FoldCastPass.h
compiler/luci/pass/src/CircleOptimizer.cpp
compiler/luci/pass/src/FoldCastPass.cpp

This introduces a pass to fold Cast op.
---
Draft PR: #5707

[luci] Introduce a pass to fold Cast op

---

compiler/circle2circle/src/Circle2Circle.cpp

This adds option to fold Cast op.
---
Draft PR: #5707

[circle2circle] Add option to fold Cast op

---

compiler/luci/pass/src/helpers/NodeFiller.cpp
compiler/luci/pass/src/helpers/NodeFiller.h

This commit introudces NodeFiller helper class. This class is from
`FuseInstanceNormPass`. It will help developers to implement optimization pass.
Related: #5599
Draft: #5698

[luci] Introudce NodeFiller class

---

compiler/one-cmds/how-to-use-one-commands.txt
compiler/one-cmds/one-optimize
compiler/one-cmds/utils.py

This supports FoldCast pass in one-cmds.
---
Draft PR: #5707

[one-cmds] Support for FoldCast pass

---

compiler/luci/pass/src/helpers/NodeFiller.test.cpp

This commit adds NodeFiller related test.

[luci] Add NodeFiller test

---

compiler/luci/pass/src/FuseInstanceNormPass.cpp

This commit revises FuseInstanceNormPass to use internal NodeFiller.

[luci] Revise FuseInstanceNormPass

---

compiler/luci/pass/src/ResolveCustomOpBatchMatMulPass.test.cpp

This commit adds ResolveCustomOpBatchMatMulPass test.

[luci] Add ResolveCustomOpBatchMatMulPass test

---

compiler/luci/pass/src/ConvertNCHWToNHWCPass.cpp
compiler/luci/pass/src/ConvertNCHWToNHWCPass.test.cpp

This supports Relu6 in ConvertNCHWToNHWCPass.

[luci] Support Relu6 in ConvertNCHWToNHWCPass

---

compiler/luci/pass/src/FoldAddV2Pass.test.cpp
compiler/luci/pass/src/FoldCastPass.test.cpp
compiler/luci/pass/src/FoldSparseToDensePass.test.cpp
compiler/luci/pass/src/PassTestGraphs.h

This refactors constant folding tests.
---
Related to: https://github.com/Samsung/ONE/issues/5700

[luci] Refactoring constant folding tests

---

compiler/luci/pass/include/luci/CircleOptimizer.h
compiler/luci/pass/include/luci/Pass/TransformMinMaxToRelu6Pass.h
compiler/luci/pass/src/CircleOptimizer.cpp
compiler/luci/pass/src/TransformMinMaxToRelu6Pass.cpp
compiler/luci/pass/src/TransformMinMaxToRelu6Pass.test.cpp

This commit introduces TransformMinMaxToRelu6Pass to luci.
Related: #5599 
Draft: #5698 

[luci] Introduce TransformMinMaxToRelu6Pass

---

compiler/luci-pass-value-test/.gitignore
compiler/luci-pass-value-test/CMakeLists.txt
compiler/luci-pass-value-test/README.md
compiler/luci-pass-value-test/eval_driver.sh
compiler/luci-pass-value-test/eval_result_verifier.py
compiler/luci-pass-value-test/requires.cmake
compiler/luci-pass-value-test/test.lst

This will introduce luci-pass-value-test that will compare reference
values from execution of tflite and circle file that was generated with
certain optimization option.

[luci-pass-value-test] Introduce Pass value test

---

compiler/luci-value-test/.gitignore

This will add gitignore file to ignore local only file: test.local.lst

[luci-value-test] Add gitignore

---

compiler/luci-interpreter/src/kernels/Conv2D.cpp

This adds a fallback logic to avoid std::bad_alloc.

[luci-interpreter] Conv2D fallback logic for std::bad_alloc

---

compiler/luci/pass/include/luci/CircleOptimizer.h
compiler/luci/pass/include/luci/Pass/FuseBatchNormWithDwConvPass.h
compiler/luci/pass/src/CircleOptimizer.cpp
compiler/luci/pass/src/FuseBatchNormWithDwConvPass.cpp

This will introduce FuseBatchNormWithDwConvPass that will fuse Mul+Add
into DepthwiseConv2D for sequence of DepthwiseConv2D+Mul+Add
for certain conditions.

[luci] Introduce FuseBatchNormWithDwConvPass

---

compiler/luci/import/include/luci/Import/Nodes.h
compiler/luci/import/include/luci/Import/Nodes/CircleBidirectionalSequenceLSTM.h
compiler/luci/import/src/GraphBuilderRegistry.cpp
compiler/luci/import/src/Nodes/CircleBidirectionalSequenceLSTM.cpp

This pull request adds BidirectionalSequenceLSTM operation to luci/IR
ONE-DCO-1.0-Signed-off-by: venkat.iyervenkat.iyer@samsung.com

[luci/import] Add BidirectionalSequenceLSTM operation

---

compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp

This enables to quantize bias shared by multiple nodes.

[luci] Quantize bias shared by multiple nodes.

---

compiler/one-cmds/how-to-use-one-commands.txt
compiler/one-cmds/one-optimize
compiler/one-cmds/utils.py

For #5703 
This will introduce `SubstituteTransposeToReshape` option on one-optimize.

[one-cmd] Add SubstituteTransposeToReshape option on optimize

---

compiler/luci/pass/src/RemoveRedundantTransposePass.cpp

Parent Issue : #5777
Current `RemoveRedundantTransposePass` has following problems
- The pass is ended right after the pass is applied to only one node.
- Checking `CircleTranspose` is done twice.
As a result, if there are a lot of nodes to apply this pass, much time is needed.
To make this pass faster, this commit will revise following things.
- Do not break right after this pass is applied for a node. Apply this pass as much as possible at once.
- Filtering `CircleTranspose` first and then execute internal function.

[luci] Revise RemoveRedundantTransposePass

---

compiler/luci/pass/src/ConvertNCHWToNHWCPass.cpp
compiler/luci/pass/src/ConvertNCHWToNHWCPass.test.cpp

This will enable conversion to NHWC for CircleLeakyRelu.

[luci] Enable convert to NHWC for LeakyRelu

---

compiler/one-cmds/how-to-use-one-commands.txt
compiler/one-cmds/one-optimize
compiler/one-cmds/utils.py

For #5266 
This commit will introduce `RemoveRedundantReshape` on one-cmd.

[one-cmd] Introduce RemoveRedundantReshape option.

---

compiler/luci/pass/src/ConvertNCHWToNHWCPass.cpp
compiler/luci/pass/src/ConvertNCHWToNHWCPass.test.cpp

This will enable conversion to NHWC for CircleNeg.

[luci] Enable convert to NHWC for Neg

---

res/TensorFlowLiteRecipes/Net_Preactivation_BN_000/test.recipe

This will revise Net_Preactivation_BN_000 tflite recipe to accept input
values for value testing.

[res] Revise Net_Preactivation_BN_000 tflite recipe

---

docs/runtime/backend-api.md

Update Backend API in `backend-api.md`.

[onert/docs] Update backend-api.md

---

res/TensorFlowLiteRecipes/Net_Reshape_Reshape_000/test.recipe
res/TensorFlowLiteRecipes/Net_Reshape_Reshape_000/test.rule

This will introduce tflite recipe Net_Reshape_Reshape_000
composed of Reshape-Reshape Ops.

[res] Introduce tfl recipe Net_Reshape_Reshape_000

---

res/TensorFlowLiteRecipes/Squeeze_001/test.recipe

This will introduce Squeeze_001 tflite recipe with empty
squeeze_options.

[res] Introduce Squeeze_001 tfl recipe

---

res/TensorFlowLiteRecipes/Net_Squeeze_Squeeze_000/test.recipe
res/TensorFlowLiteRecipes/Net_Squeeze_Squeeze_000/test.rule

This will introduce Net_Squeeze_Squeeze_000 tflite recipe that has two
continued Squeeze operators.

[res] Introduce Net_Squeeze_Squeeze_000 tfl recipe

---

compiler/circle2circle/src/Circle2Circle.cpp

This will enable substitute_squeeze_to_reshape option.

[circle2circle] Enable substitute_squeeze_to_reshape

---

compiler/luci/pass/src/ConvertNCHWToNHWCPass.cpp
compiler/luci/pass/src/ConvertNCHWToNHWCPass.test.cpp

This supports CONCAT in CovnertNCHWToNHWCPass.
---
Related to: https://github.com/Samsung/ONE/issues/5845

[luci] Support CONCAT in ConvertNCHWToNHWCPass

---

compiler/luci/logex/src/FormattedGraph.cpp

This commit implements luci logex for BidirectionalSequenceLSTM operation.
ONE-DCO-1.0-Signed-off-by: venkat.iyervenkat.iyer@samsung.com

[luci/logex] Add BidirectionalSequenceLSTM operation

---

compiler/circle2circle/src/Circle2Circle.cpp

This will enable forward_reshape_to_unaryop option.

[circle2circle] Enable forward_reshape_to_unaryop option

---

compiler/luci/service/include/luci/Service/Nodes/CircleConst.h
compiler/luci/service/src/Nodes/CircleConst.cpp
compiler/luci/service/src/Nodes/CircleConst.test.cpp

This will introduce clone method for CircleConst node.

[luci] Introduce clone for CircleConst

---

compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp

This fixes indentation in QuantizeWithMinMaxPass.
---
Related to: https://github.com/Samsung/ONE/issues/5785

[luci] Fix indentation in QuantizeWithMinMaxPass

---

compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp

This supports copy-based quantization for instnorm Op.
---
Related to: https://github.com/Samsung/ONE/issues/5785

[luci] Copy-based quantization for instnorm

---

compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp

This supports copy-based quantization for PRelu op.
--- 
Related to: #5785

[luci] Copy-based quantization for PRelu

---

tests/tools/tflite_loader/src/tflite_loader.cc

Compare float value in tflite-loader test by using misc::fp32 library (same with nnapi-test)

[onert/test] Compare float value using misc library

---

compiler/circle2circle/src/Circle2Circle.cpp

This will introduce --O1 option to replace --all.

[circle2circle] Introduce --O1

---

compiler/luci/pass/src/PropagateConcatenationQparam.test.cpp
compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp

This supports copy-based propagation of concat qparam.
---
Related to: #5785

[luci] Copy-based propagation of concat qparam

---

compiler/one-cmds/how-to-use-one-commands.txt
compiler/one-cmds/one-optimize
compiler/one-cmds/utils.py

This will enable --O1 option to replace --all.

[one-cmds] Add option --O1

---

compiler/circle2circle/src/Circle2Circle.cpp

This will removed not used anymore --all option.

[circle2circle] Remove --all option

---

compiler/luci-pass-value-test/README.md

This will revise README.md file using bullets to fix formats.

[luci-pass-value-test] Revise README.md

---

compiler/record-minmax/driver/Driver.cpp
compiler/record-minmax/include/RecordMinMax.h
compiler/record-minmax/src/RecordMinMax.cpp

This runs record-minmax without input data.
---
Related to: #5886
Draft PR: #5897

[record-minmax] Run without input data

---

compiler/.ahub/tcchecker-tca/config.yaml

This will revise config.yml to include luci-eval-driver and
luci-pass-value-test.

[compiler-ahub] Revise config

---

compiler/luci/pass/src/ConvertNCHWToNHWCPass.cpp
compiler/luci/pass/src/ConvertNCHWToNHWCPass.test.cpp

This will enable ReLU for convert NCHW to NHWC Pass.

[luci] Enable ReLU for convert to NHWC

---

res/TensorFlowLiteRecipes/Net_Conv_Min_Max_000/test.recipe
res/TensorFlowLiteRecipes/Net_Conv_Min_Max_000/test.rule
res/TensorFlowLiteRecipes/Net_Conv_Relu6_000/test.recipe
res/TensorFlowLiteRecipes/Net_Conv_Relu6_000/test.rule

This will introduce two recipes of small network of Conv with Min/Max
and Conv with ReLU6.

[res] Introduce recipe for Conv with Min/Max and ReLU6

---

compiler/tflchef/core/src/ModelChef.cpp

This commit revises the way it cooks custom operator to fix wrong result.
Until now, it found out custom op's opcode index by `tflite::BuiltinOperator_CUSTOM`. But to find out correct one, it need to consider `operation.type()`.
I added `custom_code_vec` attribute to `CookParams`, which is used in `cook_graph`.
Related : #5786
Draft: #5814

[tflchef] Revise the way it cooks custom operator

---

compiler/one-cmds/how-to-use-one-commands.txt
compiler/one-cmds/one-optimize
compiler/one-cmds/utils.py

This commit introduce `--remove-strided-slice` command for `ONE` project
Signed-off-by: Anton Zhukov <anton.v.zhukov@gmail.com>
For https://github.com/Samsung/ONE/pull/5721
Draft: https://github.com/Samsung/ONE/pull/5876

[one-cmds] Intruduce --remove-strided-slice command desciption

---

infra/cmake/packages/AbseilSourceConfig.cmake
infra/nnfw/cmake/packages/TensorFlowLite-2.3.0/TensorFlowLite/CMakeLists.txt
infra/nnfw/cmake/packages/TensorFlowLite-2.3.0/TensorFlowLiteConfig.cmake

This commit update abseil-cpp (google c++ extension) version: used in TensorFlow Lite

[infra] Update external library abseil-cpp version

---

compiler/one-cmds/CMakeLists.txt
compiler/one-cmds/validate-onnx2circle/CMakeLists.txt
compiler/one-cmds/validate-onnx2circle/README.md
compiler/one-cmds/validate-onnx2circle/validate_onnx2circle.py

This will introduce experimental onnx to circle conversion-optimization
validation tool to check model conversion and optimization is valid
through executing two models and comparing the results.

[one-cmds] Experimental onnx2circle validation

---

runtime/onert/backend/acl_cl/BackendContext.cc
runtime/onert/backend/acl_neon/BackendContext.cc
runtime/onert/core/include/backend/cpu_common/BackendContextHelpers.h
runtime/onert/core/src/compiler/StaticShapeInferer.cc

Remove redundant indentation in the serveral places.

[onert] Remove redundant indentation

---

compiler/luci/pass/src/CircleShapeInferencePass.test.cpp
compiler/luci/pass/src/ConvertNCHWToNHWCPass.test.cpp
compiler/luci/pass/src/FoldAddV2Pass.test.cpp
compiler/luci/pass/src/FoldCastPass.test.cpp
compiler/luci/pass/src/FoldSparseToDensePass.test.cpp
compiler/luci/pass/src/ForwardReshapeToUnaryOpPass.test.cpp
compiler/luci/pass/src/FuseActivationFunctionPass.test.cpp
compiler/luci/pass/src/FuseInstanceNormPass.test.cpp
compiler/luci/pass/src/FusePreActivationBatchNormPass.test.cpp
compiler/luci/pass/src/PropagateQuantParamPass.test.cpp
compiler/luci/pass/src/RemoveRedundantReshape.test.cpp
compiler/luci/pass/src/RemoveRedundantTransposePass.test.cpp
compiler/luci/pass/src/RemoveUnnecessaryReshapePass.test.cpp
compiler/luci/pass/src/RemoveUnnecessarySlicePass.test.cpp
compiler/luci/pass/src/RemoveUnnecessarySplitPass.test.cpp
compiler/luci/pass/src/ReplaceMulAddWithDepthwiseConvPass.test.cpp
compiler/luci/pass/src/ResolveCustomOpBatchMatMulPass.test.cpp
compiler/luci/pass/src/ShuffleWeightTo16x1Float32Pass.test.cpp
compiler/luci/pass/src/SubstitutePackToReshapePass.test.cpp
compiler/luci/pass/src/SubstituteSqueezeToReshapePass.test.cpp
compiler/luci/pass/src/SubstituteTransposeToReshapePass.test.cpp
compiler/luci/pass/src/TransformMinMaxToRelu6Pass.test.cpp

This will add more luci Pass tests for coverage with name method.

[luci] More tests for Pass name

---

compiler/luci/lang/src/Nodes/CircleConst.test.cpp

This will add unit tests for CircleConst IR.

[luci] Tests for CircleConst IR

---

compiler/luci/service/src/Nodes/CircleConst.test.cpp

This will revise and add more tests for CircleConst::clone method.

[luci] More tests for CircleConst::clone

---

infra/scripts/test_coverage.sh

This commit fix coverage test to log tflite tensor data on nnapi-frontend (tflite) test

[infra] Fix tensor logging library coverage test

---

runtime/libs/misc/include/misc/RandomGenerator.h
runtime/libs/misc/src/RandomGenerator.cpp

This commit introduces RandomGenerator for int8 type

[onert/lib] RandomGenerator for int8 type

---

compiler/logo/src/Passes/ConstantFoldingPass.test.cpp
compiler/logo/src/Passes/SimplifyDomainConversionPass.test.cpp

This will add simple test for name and run methods of
ConstantFoldingPass and SimplifyDomainConversionPass.

[logo] Simple test for name and run

---

compiler/logo-core/src/Phase.test.cpp

This will introduce simple test for Phase.

[logo-core] Simple test for Phase

---

compiler/tflchef/tools/console/Driver.cpp

This will introduce entry_stream method to make test code easy.

[tflchef] Revise entry for testing

---

compiler/circlechef/tools/console/Driver.cpp

This will introduce entry_stream method to make test code easy.

[circlechef] Revise entry for testing

---

compiler/tflchef/tools/console/CMakeLists.txt
compiler/tflchef/tools/console/Driver.test.cpp

This will add console driver unit test.

[tflchef] Add console test

---

compiler/circlechef/tools/console/CMakeLists.txt
compiler/circlechef/tools/console/Driver.test.cpp

This will add console driver unit test.

[circlechef] Add console test

---

compiler/luci/tester/src/ReadTester.cpp
compiler/luci/tester/src/WriteTester.cpp

This will revise ReadTester and WriteTester to use Phase for multiple
Passes.

[luci] Use Phase for tester

---

compiler/foder/CMakeLists.txt

This will add link to nncc_coverage for correct coverage.

[foder] Correct test coverage

---

compiler/arser/CMakeLists.txt

This will revise CMakeLists file; use nncc_coverage option and test to
use arser lib for include folder.

[arser] Revise CMakeLists

---

compiler/loco/requires.cmake

This will add requires.cmake file for loco.

[loco] Add requires.cmake file

---

compiler/luci/tester/CMakeLists.txt
compiler/luci/tester/src/ReadTester.test.cpp
compiler/luci/tester/src/WriteTester.test.cpp

This will introduce unit test codes for read/write tester.

[luci] Unit test codes for tester

---

compiler/luci/pass/src/CircleOptimizer.test.cpp

This will introduce simple test for CircleOptimizer.

[luci] Introduce test for CircleOptimizer

---

compiler/luci/pass/src/CircleOptimizerUtils.test.cpp

This will introduce test for CircleOptimizerUtils methods.

[luci] Introduce test for CircleOptimizerUtils

---

compiler/luci/pass/src/ModulePhase.test.cpp

This will introduce unit test for ModulePhase.

[luci] Introduce test for ModulePhase

---

compiler/circle-quantizer/src/CircleQuantizer.cpp

This will revise exclusive option check to reduce duplicate codes.

[circle-quantizer] Revise exclusive option check

---

compiler/record-minmax/CMakeLists.txt

This will revise CMakeLists to gather test source file list.

[record-minmax] Revise cmake for test source files

---

docs/release/1.13/index.rst
docs/release/1.13/release-note-1.13.0.md
docs/release/index.rst

- Release Note for ONE 1.13.0
- index.rst added

Release Note for ONE 1.13.0

---

compiler/vconone/CMakeLists.txt

This will bump up version to 1.14.0

[compiler] Bump version to 1.14.0

---

compiler/luci/pass/src/ForwardReshapeToUnaryOpPass.cpp

This will revise ForwardReshapeToUnaryOpPass as to extract
local clone_shape method.

[luci] Revise ForwardReshapeToUnaryOpPass

---

compiler/luci/import/src/Nodes/CircleResizeBilinear.cpp
compiler/luci/import/src/Nodes/CircleResizeNearestNeighbor.cpp
compiler/luci/import/src/Nodes/CircleSqueeze.cpp

This will remove unnecessary includes in import.

[luci] Remove unnecessary includes

---

compute/cker/include/cker/operation/Reduce.h

I fixed OptimizedReduceSum.
Corrected the offset setting.

[onert] Fix OptimizedReduceSum

---

compiler/luci/import/src/Nodes/CircleCustom.cpp
compiler/luci/lang/include/luci/IR/Nodes/CircleCustom.h
compiler/luci/lang/src/Nodes/CircleCustom.test.cpp
compiler/luci/pass/src/FoldAddV2Pass.test.cpp
compiler/luci/pass/src/ResolveCustomOpBatchMatMulPass.test.cpp

This will revise CircleCustom Op to provide number of outputs.

[luci] numOutputs for CircleCustom

---

compiler/luci/pass/src/FuseBCQPass.cpp

This will assign names for new nodes in FuseBCQPass.

[luci] Names for new nodes in FuseBCQPass

---

compiler/luci/pass/src/ConvertNCHWToNHWCPass.test.cpp
compiler/luci/pass/src/FoldAddV2Pass.test.cpp
compiler/luci/pass/src/FoldCastPass.test.cpp
compiler/luci/pass/src/FoldSparseToDensePass.test.cpp
compiler/luci/pass/src/ForwardReshapeToUnaryOpPass.test.cpp
compiler/luci/pass/src/FuseActivationFunctionPass.test.cpp
compiler/luci/pass/src/FusePreActivationBatchNormPass.test.cpp

This will set names for nodes in Pass test.

[luci] Names of nodes in Pass test

---

compiler/luci/pass/src/RemoveRedundantReshape.test.cpp
compiler/luci/pass/src/RemoveRedundantTransposePass.test.cpp
compiler/luci/pass/src/RemoveUnnecessaryReshapePass.test.cpp
compiler/luci/pass/src/RemoveUnnecessarySlicePass.test.cpp
compiler/luci/pass/src/RemoveUnnecessarySplitPass.test.cpp
compiler/luci/pass/src/ReplaceMulAddWithDepthwiseConvPass.test.cpp

This will set names for nodes in Pass test.

[luci] Names of nodes in Pass test (2)

---

compiler/luci/pass/src/ResolveCustomOpBatchMatMulPass.test.cpp
compiler/luci/pass/src/ShuffleWeightTo16x1Float32Pass.test.cpp
compiler/luci/pass/src/SubstitutePackToReshapePass.test.cpp
compiler/luci/pass/src/SubstituteSqueezeToReshapePass.test.cpp
compiler/luci/pass/src/SubstituteTransposeToReshapePass.test.cpp
compiler/luci/pass/src/TransformMinMaxToRelu6Pass.test.cpp

This will set names for nodes in Pass test.

[luci] Names of nodes in Pass test (3)

---

compiler/luci/pass/src/ConvertNCHWToNHWCPass.cpp

This will assign names for new nodes in ConvertNCHWToNHWCPass.

[luci] Names for new nodes in ConvertNCHWToNHWCPass

---

compiler/luci/export/src/CircleTensorExporter.cpp

This will revise CircleTensorContext and name validation code to handle unique name for Tensors.

[luci] Revise export CircleTensorContext

---

compiler/luci/tester/CMakeLists.txt

This will revise tester cmake for unit testing to use variable for
tester source files.

[luci] Revise tester cmake for unit testing

---

runtime/libs/tflite/include/tflite/RandomInputInitializer.h
runtime/libs/tflite/src/RandomInputInitializer.cpp
runtime/libs/tflite/src/RandomTestRunner.cpp
tests/tools/tflite_run/src/tflite_run.cc

This commit introduces tflite random input initizlizer and copy input initializer
---
Part of #5971

[onert/lib] Introduce tflite input initializer

---

compiler/luci-interpreter/src/kernels/CMakeLists.txt
compiler/luci-interpreter/src/loader/CMakeLists.txt

This will revise test to build with ENABLE_TEST is set.

[luci-interpreter] Revise test build

---

compiler/luci/tester/CMakeLists.txt
compiler/luci/tester/src/ReadModule.cpp
compiler/luci/tester/src/ReadModule.h

This will introduce ReadModule in tester for common of Readtester and WriteTester.

[luci] Introduce ReadModule in tester

---

compiler/luci/import/src/Nodes/CircleReshape.cpp

This will add S32 condition check for Reshape shape input.

[luci] Revise Reshape import

---

compiler/luci/tester/src/ReadTester.cpp
compiler/luci/tester/src/WriteTester.cpp

This will revise ReadTester and WriteTester to use ReadModule.

[luci] Revise Tester to use ReadModule

---

compiler/luci/import/include/luci/Import/GraphBuilder.h

This will introduce validate method to check number of inputs and single
output.

[luci] Validate for number of inputs/outputs

---

compiler/luci/export/src/CircleTensorExporter.cpp

This will introduce template method has_same_elements() and revise
has_same_values method to use this.

[luci] Use template for has_same_values

---

compiler/luci/import/src/Nodes/CircleAbs.cpp
compiler/luci/import/src/Nodes/CircleAdd.cpp
compiler/luci/import/src/Nodes/CircleArgMax.cpp
compiler/luci/import/src/Nodes/CircleArgMin.cpp
compiler/luci/import/src/Nodes/CircleAveragePool2D.cpp

[luci] Revise import validate for A-Ops

---

compiler/luci/import/src/Nodes/CircleFakeQuant.cpp
compiler/luci/import/src/Nodes/CircleFill.cpp
compiler/luci/import/src/Nodes/CircleFloor.cpp
compiler/luci/import/src/Nodes/CircleFloorDiv.cpp
compiler/luci/import/src/Nodes/CircleFloorMod.cpp
compiler/luci/import/src/Nodes/CircleFullyConnected.cpp

[luci] Revise import validate for F-Ops

---

compiler/luci/import/src/Nodes/CircleL2Normalize.cpp
compiler/luci/import/src/Nodes/CircleL2Pool2D.cpp
compiler/luci/import/src/Nodes/CircleLeakyRelu.cpp
compiler/luci/import/src/Nodes/CircleLess.cpp
compiler/luci/import/src/Nodes/CircleLessEqual.cpp
compiler/luci/import/src/Nodes/CircleLocalResponseNormalization.cpp
compiler/luci/import/src/Nodes/CircleLog.cpp
compiler/luci/import/src/Nodes/CircleLogSoftmax.cpp
compiler/luci/import/src/Nodes/CircleLogicalAnd.cpp
compiler/luci/import/src/Nodes/CircleLogicalNot.cpp
compiler/luci/import/src/Nodes/CircleLogicalOr.cpp
compiler/luci/import/src/Nodes/CircleLogistic.cpp

[luci] Revise import validate for L-Ops

---

compiler/luci/import/src/Nodes/CircleMatrixDiag.cpp
compiler/luci/import/src/Nodes/CircleMatrixSetDiag.cpp
compiler/luci/import/src/Nodes/CircleMaxPool2D.cpp
compiler/luci/import/src/Nodes/CircleMean.cpp
compiler/luci/import/src/Nodes/CircleMirrorPad.cpp
compiler/luci/import/src/Nodes/CircleMul.cpp
compiler/luci/import/src/Nodes/CircleNeg.cpp
compiler/luci/import/src/Nodes/CircleNotEqual.cpp

[luci] Revise import validate for MN-Ops

---

compiler/luci/import/src/Nodes/CircleOneHot.cpp
compiler/luci/import/src/Nodes/CirclePRelu.cpp
compiler/luci/import/src/Nodes/CirclePad.cpp
compiler/luci/import/src/Nodes/CirclePadV2.cpp
compiler/luci/import/src/Nodes/CirclePow.cpp

[luci] Revise import validate for OP-Ops

---

compiler/luci/import/src/Nodes/CircleRange.cpp
compiler/luci/import/src/Nodes/CircleRank.cpp
compiler/luci/import/src/Nodes/CircleReduceAny.cpp
compiler/luci/import/src/Nodes/CircleReduceProd.cpp
compiler/luci/import/src/Nodes/CircleRelu.cpp
compiler/luci/import/src/Nodes/CircleRelu6.cpp
compiler/luci/import/src/Nodes/CircleReluN1To1.cpp
compiler/luci/import/src/Nodes/CircleResizeBilinear.cpp
compiler/luci/import/src/Nodes/CircleResizeNearestNeighbor.cpp
compiler/luci/import/src/Nodes/CircleReverseSequence.cpp
compiler/luci/import/src/Nodes/CircleReverseV2.cpp
compiler/luci/import/src/Nodes/CircleRound.cpp
compiler/luci/import/src/Nodes/CircleRsqrt.cpp

[luci] Revise import validate for R-Ops

---

compiler/luci/import/src/Nodes/CircleScatterNd.cpp
compiler/luci/import/src/Nodes/CircleSegmentSum.cpp
compiler/luci/import/src/Nodes/CircleSelect.cpp
compiler/luci/import/src/Nodes/CircleSelectV2.cpp
compiler/luci/import/src/Nodes/CircleShape.cpp
compiler/luci/import/src/Nodes/CircleSin.cpp
compiler/luci/import/src/Nodes/CircleSlice.cpp
compiler/luci/import/src/Nodes/CircleSoftmax.cpp
compiler/luci/import/src/Nodes/CircleSpaceToDepth.cpp
compiler/luci/import/src/Nodes/CircleSparseToDense.cpp
compiler/luci/import/src/Nodes/CircleSqrt.cpp
compiler/luci/import/src/Nodes/CircleSquare.cpp
compiler/luci/import/src/Nodes/CircleSquaredDifference.cpp
compiler/luci/import/src/Nodes/CircleSqueeze.cpp
compiler/luci/import/src/Nodes/CircleStridedSlice.cpp
compiler/luci/import/src/Nodes/CircleSub.cpp
compiler/luci/import/src/Nodes/CircleSum.cpp

[luci] Revise import validate for S-Ops

---

compiler/luci/pass/src/QuantizeDequantizeWeightsPass.cpp

This will revise QuantizeDequantizeWeightsPass to use
iterate_per_channel method to reduce duplicate codes.

[luci] Revise QuantizeDequantizeWeightsPass to use iterate

---

compiler/luci/pass/src/QuantizeDequantizeWeightsPass.cpp

This will revise QuantizeDequantizeWeightsPass cal_minmax_per_channel
method to use iterate_per_channel method to reduce duplicate codes.

[luci] Revise QuantizeDequantizeWeightsPass cal_minmax

---

compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp

This will introduce iterate_per_channel to iterate loop to reduce
duplicate codes in QuantizeWithMinMaxPass.

[luci] Introduce iterate_per_channel for QuantizeWithMinMax

---

compiler/luci/pass/src/MakeBatchNormGammaPositivePass.cpp

This will revise MakeBatchNormGammaPositivePass to find pattern
beginning with CircleAdd.

[luci] Revise MakeBatchNormGammaPositivePass

---

compiler/luci/pass/src/BatchNormPatternFinder.cpp
compiler/luci/pass/src/BatchNormPatternFinder.h
compiler/luci/pass/src/BatchNormPatternFinder.test.cpp

This will introduce common BatchNormPatternFinder with is_batchnorm_add and
is_batchnorm_mul methods for Passes.

[luci] Introduce BatchNormPatternFinder

---

compiler/record-minmax/src/RecordMinMax.cpp

This will extract common codes in profileData to a function.

[record-minmax] Extract common profileData

---

compiler/luci/pass/src/ConvertNCHWToNHWCPass.cpp

This will extract common code in ConvertNCHWToNHWCPass with Relu type.

[luci] Extract common ConvertNCHWToNHWCPass

---

compiler/luci/pass/src/MakeBatchNormGammaPositivePass.cpp

This will add simple discription of MakeBatchNormGammaPositivePass.

[luci] Add MakeBatchNormGammaPositivePass discription

---

compiler/enco/cli/CMakeLists.txt
compiler/enco/cli/src/Driver.cpp
compiler/enco/core/CMakeLists.txt
compiler/enco/core/src/ANN/Context.cpp
compiler/enco/core/src/ANN/IR/OperandInventory.cpp
compiler/enco/core/src/ANN/IR/OperationInventory.cpp
compiler/enco/core/src/ANN/IR/WeightInventory.cpp
compiler/enco/core/src/Backend.cpp
compiler/enco/core/src/CppGen/Host.cpp
compiler/enco/core/src/CppGen/Subnet.cpp
compiler/enco/core/src/Session.cpp
compiler/enco/core/src/Transforms/FeatureUnification.cpp
compiler/enco/core/src/Transforms/GlobalDataGeneration.cpp
compiler/enco/core/src/Transforms/Split.cpp
compiler/enco/frontend/caffe/CMakeLists.txt
compiler/enco/frontend/caffe/src/Entry.cpp
compiler/enco/frontend/caffe/src/GraphBuilderRegistry.cpp
compiler/enco/frontend/tflite/CMakeLists.txt
compiler/enco/frontend/tflite/src/Entry.cpp
compiler/enco/frontend/tflite/src/Frontend.test.cpp
compiler/enco/frontend/tflite/src/GraphBuilderRegistry.h
compiler/enco/test/basic/000/CMakeLists.txt
compiler/enco/test/basic/000/enco.test.cpp
compiler/enco/test/binder.cpp
compiler/enco/test/caffe/CMakeLists.txt
compiler/enco/test/tflite/CMakeLists.txt

[enco] Remove stdex

---

compiler/loco/CMakeLists.txt
compiler/loco/requires.cmake
compiler/loco/src/ADT/AnnotatedItem.test.cpp
compiler/loco/src/IR/CanonicalDialect.cpp
compiler/loco/src/IR/Dialect.test.cpp
compiler/loco/src/IR/Graph.cpp
compiler/loco/src/IR/PermutingCodec.cpp
compiler/loco/src/IR/Verifier.test.cpp
compiler/loco/src/Service/CanonicalShapeInferenceRule.test.cpp
compiler/loco/src/Service/GraphBuilder.h
compiler/loco/src/Service/GraphTestcase.h
compiler/loco/src/Service/ShapeInference.cpp
compiler/loco/src/Service/TypeInference.cpp
compiler/loco/src/tensorflow.test.cpp

[loco] Remove stdex

---

compiler/locomotiv/CMakeLists.txt
compiler/locomotiv/requires.cmake
compiler/locomotiv/src/NodeDataImpl.cpp
compiler/locomotiv/src/UserData.cpp

[locomotiv] Remove stdex

---

compiler/locop/CMakeLists.txt
compiler/locop/src/CanonicalNodeSummaryBuilder.cpp
compiler/locop/src/ExampleGraph.h
compiler/locop/src/FormattedGraph.cpp
compiler/locop/src/FormattedGraph.test.cpp
compiler/locop/src/FormattedTensorShape.test.cpp
compiler/locop/src/GenericNodeSummaryBuilder.test.cpp
compiler/locop/src/NodeSummary.cpp

[locop] Remove stdex

---

compiler/hermes/CMakeLists.txt
compiler/hermes/requires.cmake
compiler/hermes/src/core/MessageBuffer.cpp
compiler/hermes/src/core/Source.cpp

[hermes] Remove stdex

---

compiler/luci/pass/src/RemoveRedundantTransposePass.cpp

This will revise RemoveRedundantTransposePass 'perm'
variable name to match its node.

[luci] Revise RemoveRedundantTransposePass variable

---

runtime/libs/tflite/include/tflite/OutputResetter.h
runtime/libs/tflite/src/OutputResetter.cpp
runtime/libs/tflite/src/RandomTestRunner.cpp

This commit introduces tflite output resetter

[onert/lib] Introduce tflite output resetter

---

compiler/nnkit-caffe/backend/CMakeLists.txt
compiler/nnkit-caffe/backend/Module.cpp

[nnkit=caffe] Remove stdex

---

compiler/nnkit-misc/backend/CMakeLists.txt
compiler/nnkit-misc/backend/src/BackendPlugin.cpp

[nnkit-misc] Remove stdex

---

compiler/nnkit-onnxrt/backend/Backend.cpp
compiler/nnkit-onnxrt/backend/CMakeLists.txt
compiler/nnkit-onnxrt/requires.cmake
compiler/nnkit-onnxrt/support/CMakeLists.txt
compiler/nnkit-onnxrt/support/src/Runner.cpp

[nnkit-onnxrt] Remove stdex

---

compiler/nnkit-tf/backend/Backend.cpp
compiler/nnkit-tf/backend/CMakeLists.txt
compiler/nnkit-tf/requires.cmake
compiler/nnkit-tf/support/CMakeLists.txt

[nnkit-tf] Remove stdex

---

compiler/nnsuite/conv/nnkit-caffe/CMakeLists.txt
compiler/nnsuite/conv/nnkit-caffe/ConvBackend.cpp
compiler/nnsuite/conv/nnkit-tflite/CMakeLists.txt
compiler/nnsuite/conv/nnkit-tflite/Entry.cpp

[nnsuite] Remove stdex

---

compiler/oneco/CMakeLists.txt
compiler/oneco/requires.cmake
compiler/oneco/src/Frontend.cpp
compiler/oneco/src/GraphBuilderRegistry.h

[oneco] Remove stdex

---

compiler/tfkit/CMakeLists.txt
compiler/tfkit/src/ConvertCommand.cpp
compiler/tfkit/src/Main.cpp
compiler/tfkit/src/Support.cpp

[tfkit] Remove stdex

---

infra/packaging/preset/20200630
infra/packaging/preset/20200731_windows

This will remove stdex item as it's not used anymore.
ONE-DCO-Signed-off-by: SaeHie Park <saehie.park@gmail.com>

[infra/preset] Remove stdex

---

infra/scripts/compiler_modules.sh
infra/scripts/docker_collect_nnpkg_resources.sh

This will remove stdex item as it's not used anymore.
ONE-DCO-Signed-off-by: SaeHie Park <saehie.park@gmail.com>

[infra/scripts] Remove stdex

---

compiler/luci/import/include/luci/Import/Nodes/CircleCustom.h
compiler/luci/import/src/Nodes/CircleCustom.cpp

This will revise import of CircleCustom with GraphBuilderMultiOutput.

[luci] Revise import of CircleCustom

---

compiler/luci/import/include/luci/Import/Nodes/CircleIf.h
compiler/luci/import/src/Nodes/CircleIf.cpp

This will revise import of CircleIf with GraphBuilderMultiOutput.

[luci] Revise import of CircleIf

---

compiler/luci/import/include/luci/Import/Nodes/CircleNonMaxSuppressionV4.h
compiler/luci/import/include/luci/Import/Nodes/CircleNonMaxSuppressionV5.h
compiler/luci/import/src/Nodes/CircleNonMaxSuppressionV4.cpp
compiler/luci/import/src/Nodes/CircleNonMaxSuppressionV5.cpp

This will revise import of CircleNonMaxSuppressionV4 and
CircleNonMaxSuppressionV5 with GraphBuilderMultiOutput.

[luci] Revise Import of CircleNonMaxSuppressionV4/5

---

compiler/luci/import/include/luci/Import/Nodes/CircleSplit.h
compiler/luci/import/include/luci/Import/Nodes/CircleSplitV.h
compiler/luci/import/src/Nodes/CircleSplit.cpp
compiler/luci/import/src/Nodes/CircleSplitV.cpp

This will revise import of CircleSplit and CircleSplitV with
GraphBuilderMultiOutput.

[luci] Revise Import of CircleSplit/V

---

compiler/luci/import/include/luci/Import/Nodes/CircleTopKV2.h
compiler/luci/import/src/Nodes/CircleTopKV2.cpp

This will revise import of CircleTopKV2 with GraphBuilderMultiOutput.

[luci] Revise Import of CircleTopKV2

---

compiler/luci/import/include/luci/Import/Nodes/CircleUnique.h
compiler/luci/import/include/luci/Import/Nodes/CircleUnpack.h
compiler/luci/import/src/Nodes/CircleUnique.cpp
compiler/luci/import/src/Nodes/CircleUnpack.cpp

This will revise import of CircleUnique and CircleUnpack with GraphBuilderMultiOutput.

[luci] Revise Import of CircleUnique/CircleUnpack

---

compiler/luci/import/include/luci/Import/Nodes/CircleBidirectionalSequenceLSTM.h
compiler/luci/import/src/Nodes/CircleBidirectionalSequenceLSTM.cpp

This will revise import of CircleBidirectionalSequenceLSTM with
GraphBuilderMultiOutput.

[luci] Revise import of CircleBidirectionalSequenceLSTM

---

compiler/luci/import/src/Nodes/CircleBidirectionalSequenceLSTM.cpp

This will revise import validate of CircleBidirectionalSequenceLSTM also
to check number of outputs to be 2.

[luci] Revise import validate of CircleBidirectionalSequenceLSTM

---

runtime/onert/frontend/base_loader/include/base_loader.h

This enables `base_loader` to handle one buffer shared by multiple tensors.
For related comment : [1. here](https://github.sec.samsung.net/STAR/nnfw/issues/12049#issuecomment-1001199) and [2. here](https://github.sec.samsung.net/STAR/nnfw/issues/12049#issuecomment-1001574)
An example in circle or tflite model are as follows:
- model buffer
- buffer 25 of **10 MB** weight
- subgraph 0:
- tensor 1 points buffer 25
- tensor 2 points buffer 25
- subgraph 1:
- tensor 3 points buffer 25
- tensor 4 points buffer 25
Current:
- `ir::Data` for tensor 1 is created and so does for tensor 2, 3, and 4,
resulting in **40 MB** memory consumption.
With this commit:
- `ir::Data` for tensor 1 is created and tensor 2, 3, and 4 share
the created `ir::Data`, resulting in **10 MB** memory consumption. …

[onert] Handle a buffer shared by tensors during model loading

---

compiler/luci/pass/src/test/TestShape.h
compiler/luci/pass/src/test/TestShape.test.cpp

This will introduce Shape related types and methods for unit testing.

[luci] Introduce Shape related for unit tests

---

compiler/luci/pass/src/test/TestFirstNode.h
compiler/luci/pass/src/test/TestFirstNode.test.cpp

This will introduce TestFirstNode providing first_node method that will
return first node of a type in the graph.

[luci] Introduce TestFirstNode

---

compiler/luci/pass/src/BatchNormPatternFinder.test.cpp

This will revise BatchNormPatternFinder pass test with TestIOGraph.

[luci] Revise BatchNormPatternFinder test

---

compiler/luci/pass/src/ForwardReshapeToUnaryOpPass.test.cpp

This will revise ForwardReshapeToUnaryOpPass with TestIOGraph.

[luci] Revise ForwardReshapeToUnaryOpPass test

---

compiler/luci/pass/src/FuseActivationFunctionPass.test.cpp

This will revise FuseActivationFunctionPass test with TestIOGraph.

[luci] Revise FuseActivationFunctionPass test

---

compiler/luci/pass/src/RemoveUnnecessarySlicePass.test.cpp

This will revise RemoveUnnecessarySlicePass test with TestIOGraph.

[luci] Revise RemoveUnnecessarySlicePass test

---

compiler/luci/pass/src/ResolveCustomOpBatchMatMulPass.test.cpp

This will revise ResolveCustomOpBatchMatMulPass test with TestIOGraph.

[luci] Revise ResolveCustomOpBatchMatMulPass test

---

compiler/luci/pass/src/ShuffleWeightTo16x1Float32Pass.test.cpp

This will revise ShuffleWeightTo16x1Float32Pass test with TestIOGraph.

[luci] Revise ShuffleWeightTo16x1Float32Pass test

---

compiler/luci/pass/src/RemoveUnnecessaryReshapePass.test.cpp

This will revise RemoveUnnecessaryReshapePass test with TestIOGraph.

[luci] Revise RemoveUnnecessaryReshapePass test

---

compiler/luci/pass/src/RemoveUnnecessaryStridedSlicePass.test.cpp

This will revise RemoveUnnecessaryStridedSlicePass test with
TestIOGraph.

[luci] Revise RemoveUnnecessaryStridedSlicePass test

---

compiler/luci/pass/src/RemoveUnnecessarySplitPass.test.cpp

This will revise RemoveUnnecessarySplitPass test with TestIOGraph.

[luci] Revise RemoveUnnecessarySplitPass test

---

compiler/luci/service/include/luci/Service/CircleShapeInference.h
compiler/luci/service/include/luci/Service/CircleTypeInference.h
compiler/luci/service/src/CircleShapeInference.cpp
compiler/luci/service/src/CircleTypeInference.cpp

This commit removes deprecated source codes which are not used.

[luci] Remove deprecated codes

---

compiler/luci/import/src/Importer.cpp

Parent Issue : #6080
Draft : #6101
This commit will add `CircleNodeOrigin` to built op with following options.
- If origin metadata exists : add origin according to metadata
- If origin metadata not exists : add origin using operator index

[luci/import] Add origin to built op

---

compiler/luci/export/src/CircleExportMetadata.cpp
compiler/luci/import/src/CircleImportMetadata.cpp

As `luci/profile/README.md` has detailed explanation about current comments,
they can be removed.
This commit remove them and just leave simple comments.

[luci/import] Remove duplicate comments

---

compiler/one-cmds/how-to-use-one-commands.txt
compiler/one-cmds/one-build.template.cfg
compiler/one-cmds/one-optimize
compiler/one-cmds/one-quantize
compiler/one-cmds/utils.py

This commit adds profiling option to one-cmds.
Related: #6080 
Draft: #6186 

[one-cmds] Add profiling option

---

runtime/libs/tflite/src/RandomTestRunner.cpp

This commit moves I/O value setting from compile() to run(), and moves NNAPI setting from run() to compile().
---
Part of #5971

[onert/lib] Revise RandomTestRunner compile and run method

---

compiler/one-cmds/one-codegen

This commit fixes one-codegen bug.

[one-cmds] Fix one-codegen bug

---

runtime/onert/core/src/compiler/ExecutorFactory.cc

After splitting partial graphs, LoweredGraph should not have reference
of `Data` which prevents unnecessary const data from being freed.

[onert] Deref LoweredGraph operand data reference

---

docs/release/1.14/index.rst
docs/release/1.14/release-note-1.14.0.md

- Release Note for ONE 1.13.0
- index.rst added

Release Note for ONE 1.14.0

---

res/TensorFlowLiteRecipes/Part_Sqrt_Rsqrt_000/test.recipe
res/TensorFlowLiteRecipes/Part_Sqrt_Rsqrt_001/test.recipe
res/TensorFlowLiteRecipes/Part_Sqrt_Rsqrt_002/test.recipe
res/TensorFlowLiteRecipes/Part_Sqrt_Rsqrt_003/test.recipe
res/TensorFlowLiteRecipes/Part_Sqrt_Rsqrt_004/test.recipe

This will introduce TF lite recipes with Sqrt/Rsqrt for partitioning.

[res] TF lite recipes with Sqrt/Rsqrt for partioning

---

res/TensorFlowLiteRecipes/Part_Sqrt_Rsqrt_Add_000/test.recipe
res/TensorFlowLiteRecipes/Part_Sqrt_Rsqrt_Add_001/test.recipe
res/TensorFlowLiteRecipes/Part_Sqrt_Rsqrt_Add_002/test.recipe
res/TensorFlowLiteRecipes/Part_Sqrt_Rsqrt_Add_003/test.recipe
res/TensorFlowLiteRecipes/Part_Sqrt_Rsqrt_Add_004/test.recipe

This will introduce TF lite recipes with Sqrt/Rsqrt/Add for
partitioning.

[res] TF lite recipes with Sqrt/Rsqrt/Add for partitioning

---

compiler/vconone/CMakeLists.txt

This will bump up version to 1.15.0

[Compiler] Bump version to 1.15.0

---

compiler/luci-interpreter/src/core/KernelParams.h
compiler/luci-interpreter/src/kernels/CMakeLists.txt
compiler/luci-interpreter/src/kernels/Pack.cpp
compiler/luci-interpreter/src/kernels/Pack.h
compiler/luci-interpreter/src/kernels/Pack.test.cpp
compiler/luci-interpreter/src/loader/KernelBuilder.cpp
compiler/luci-interpreter/src/loader/KernelBuilder.h

For #6262
This commit will introduce `Pack` kernel to enable evaluation `CirclePack`.

[luci-interpreter] Introduce Pack kernel

---

docs/conf.py
packaging/nnfw.spec
runtime/contrib/android/api/build.gradle
runtime/onert/api/include/nnfw_version.h

[onert] Bump to 1.15.0

---

compiler/luci/partition/src/PartitionIR.h
compiler/luci/partition/src/PartitionIR.test.cpp

This will introduce luci partition IRs for node and graph.

[luci] Introduce partition IRs

---

compiler/luci/partition/src/CircleNodeClone.cpp
compiler/luci/partition/src/CircleNodeClone.h
compiler/luci/partition/src/CircleNodeClone.test.cpp

This will introduce clone_node method to get a copy of a node.

[luci] Introduce clone node

---

compiler/luci/partition/src/CircleNodeClone.cpp

This will support more node types for CloneNode.

[luci] More node types for CloneNode

---

compiler/luci/partition/src/PartitionIR.cpp
compiler/luci/partition/src/PartitionIR.h

This will add some helper methods for PGraphs.

[luci] Add helper methods for PGraphs

---

compiler/luci/partition/src/PartitionIRDump.cpp
compiler/luci/partition/src/PartitionIRDump.h

This will introduce dump to stream of PGraphs and types for debugging.

[luci] Dump of PGraphs for debugging

---

.ahub/tcchecker-tca/config.yaml

This commit updates configuration file to search basic backend unittest

[infra] Update configuration file for TCM tools

---

compiler/luci/partition/src/CircleNodeClone.cpp
compiler/luci/partition/src/CircleNodeClone.h

This will introduce clone_connect method to connect cloned nodes.

[luci] Connect clones in partition

---

compiler/luci/partition/src/PartitionIR.cpp
compiler/luci/partition/src/PartitionIR.h
compiler/luci/partition/src/PartitionIRDump.cpp
compiler/luci/partition/src/PartitionIRDump.h

This will rename partition IR to PGroup and PGroups.

[luci] Rename to PGroup and PGroups

---

compiler/circle-partitioner/src/CirclePartitioner.cpp

This will add arser options for circle-partitioner.

[circle-partitioner] Add arser options

---

compiler/circle-partitioner/src/HelperPath.cpp
compiler/circle-partitioner/src/HelperPath.h

This will introduce HelperPath with path related helper functions.

[circle-partitioner] Introduce HelperPath

---

compiler/circle-partitioner/src/HelperStrings.cpp
compiler/circle-partitioner/src/HelperStrings.h

This will introduce HelperStrings with string related helper functions.

[circle-partitioner] Introduce HelperStrings

---

compiler/crew/CMakeLists.txt
compiler/crew/README.md
compiler/crew/include/crew/PConfigIni.h
compiler/crew/requires.cmake
compiler/crew/src/PConfigIni.cpp
compiler/crew/src/PConfigIni.test.cpp

This will introduce initial crew library that will provide
config ini/json file import/export functionalities.

[crew] Introduce initial crew library

---

compiler/luci/partition/src/Partition.cpp

This will revise partition apply method to produce pgroups and dump
pgroups object.

[luci] Call produce_pgroups in apply

---

compiler/circle-partitioner/CMakeLists.txt
compiler/circle-partitioner/requires.cmake
compiler/circle-partitioner/src/CirclePartitioner.cpp

This will enable to load circle model in circle-partitioner.

[circle-partitioner] Load circle model

---

compiler/crew/include/crew/PConfigIniDump.h
compiler/crew/src/PConfigIniDump.cpp
compiler/crew/src/PConfigIniDump.test.cpp

This will introduce dump of PConfigIni for store and debugging.

[crew] Introduce PConfigIniDump

---

compiler/circle-part-driver/CMakeLists.txt
compiler/circle-part-driver/requires.cmake
compiler/circle-part-driver/src/Driver.cpp

This will add log print of input arguments.

[circle-part-driver] Log input arguments

---

compiler/luci/partition/src/PartitionMerge.cpp
compiler/luci/partition/src/PartitionMerge.h

This will introduce PartitionMerge that provides merge_pgroups method to
merge PGroup in PGroups with certain conditions.

[luci] Introduce PartitionMerge

---

compiler/crew/src/PConfigJson.cpp
compiler/crew/src/PConfigJson.h
compiler/crew/src/PConfigJson.test.cpp

This will introduce PConfigJson for export to json format.

[crew] Introduce PConfigJson

---

compiler/luci/partition/src/Partition.cpp

This will revise apply to call merge_groups to merge PGroup for some
condition.

[luci] Call merge_groups in partition apply

---

compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp

This removes clang-format off/on flags.

[luci] Remove clang-format off/on flags

---

compiler/luci-interpreter/src/kernels/CMakeLists.txt
compiler/luci-interpreter/src/kernels/SquaredDifference.cpp
compiler/luci-interpreter/src/kernels/SquaredDifference.h
compiler/luci-interpreter/src/kernels/SquaredDifference.test.cpp
compiler/luci-interpreter/src/loader/KernelBuilder.cpp
compiler/luci-interpreter/src/loader/KernelBuilder.h
compiler/luci-interpreter/src/loader/KernelBuilder.test.cpp

This will enable float of SquaredDifference.

[luci-interpreter] Enable float SquaredDifference

---

compiler/crew/include/crew/PConfigIni.h
compiler/crew/src/PConfigIni.cpp
compiler/crew/src/PConfigIni.test.cpp

This will introduce write_ini and find methods in PConfigIni.

[crew] Introduce write ini and find in PConfigIni

---

compiler/luci/partition/src/Partition.cpp
compiler/luci/partition/src/Partition.test.cpp

This will enable produce of PartedModules in partiton apply method.

[luci] Produce PartedModules in partition apply

---

compiler/crew/include/crew/PConfig.h
compiler/crew/src/PConfig.cpp

This will introduce read_ini method to read init file and fill PConfig
structure.

[crew] Introduce read_ini method

---

compiler/circle-partitioner/src/CirclePartitioner.cpp

This will introduce load_model method for better readability.

[circle-partitioner] Introduce load_model

---

compiler/circle-part-driver/src/Driver.cpp

This will add a comment about input/output file names.

[circle-part-driver] Comment about file names

---

compiler/luci/pass/src/QuantizedModelVerifier.test.cpp
compiler/luci/pass/src/VerifyQuantizedNodeChannelWiseGranularity.h
compiler/luci/pass/src/VerifyQuantizedNodeLayerWiseGranularity.h
compiler/luci/pass/src/VerifyQuantizedNodeS16Type.h
compiler/luci/pass/src/VerifyQuantizedNodeU8Type.h

This verifies quantization of logistic operator.
---

[luci] Verify quantization of logistic

---

compiler/crew/include/crew/PConfig.h
compiler/crew/src/PConfig.cpp

This will introduce write_ini method that stream write PConfig to config ini format.

[crew] Introduce write_ini method

---

compiler/circle-part-driver/CMakeLists.txt
compiler/circle-part-driver/requires.cmake
compiler/circle-part-driver/src/PModelsRunner.cpp
compiler/circle-part-driver/src/PModelsRunner.h

This will implement load_config that loads config ini file and prepares
models to run list.

[circle-part-driver] Implement load_config

---

compiler/circle-partitioner/CMakeLists.txt
compiler/circle-partitioner/requires.cmake
compiler/circle-partitioner/src/CirclePartitioner.cpp
compiler/circle-partitioner/src/PartitionRead.cpp
compiler/circle-partitioner/src/PartitionRead.h

This will enable circle-partitioner to read partition config ini file.

[circle-partitioner] Read partition config ini

---

compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
compiler/luci/pass/src/QuantizedModelVerifier.test.cpp
compiler/luci/pass/src/VerifyQuantizedNodeChannelWiseGranularity.h
compiler/luci/pass/src/VerifyQuantizedNodeLayerWiseGranularity.h
compiler/luci/pass/src/VerifyQuantizedNodeS16Type.h
compiler/luci/pass/src/VerifyQuantizedNodeU8Type.h

This supports quantization of slice op.
---

[luci] Support quantization of slice

---

compiler/luci-interpreter/src/loader/KernelBuilder.cpp
compiler/luci-interpreter/src/loader/KernelBuilder.h
compiler/luci-interpreter/src/loader/KernelBuilder.test.cpp

This will reorder kernel Sub operatator related codes.

[luci-interpreter] Reorder Sub

---

compiler/crew/include/crew/PConfig.h
compiler/crew/src/PConfig.cpp

This will introduce write_json method to stream out json format from
PConfig object.

[crew] Introduce write_json

---

compiler/luci/service/include/luci/Service/CircleNodeClone.h
compiler/luci/service/src/CircleNodeClone.cpp
compiler/luci/service/src/CircleNodeClone.test.cpp

This will introduce CircleNodeClone to clone CircleNode in Service

[luci] CircleNodeClone in Service

---

compiler/circle-part-driver/CMakeLists.txt
compiler/circle-part-driver/src/PModelsRunner.cpp
compiler/circle-part-driver/src/PModelsRunner.h

This will implement load_inputs method to load input data from files.

[circle-part-driver] Implement load_inputs

---

compiler/circle-part-eval/parts/Part_Sqrt_Rsqrt_000.part
compiler/circle-part-eval/parts/Part_Sqrt_Rsqrt_001.part
compiler/circle-part-eval/parts/Part_Sqrt_Rsqrt_002.part
compiler/circle-part-eval/parts/Part_Sqrt_Rsqrt_003.part
compiler/circle-part-eval/parts/Part_Sqrt_Rsqrt_Add_000.part
compiler/circle-part-eval/parts/Part_Sqrt_Rsqrt_Add_001.part
compiler/circle-part-eval/parts/Part_Sqrt_Rsqrt_Add_002.part
compiler/circle-part-eval/parts/Part_Sqrt_Rsqrt_Add_003.part
compiler/circle-part-eval/parts/Part_Sqrt_Rsqrt_Add_004.part

This will introduce Sqrt_Rsqrt and Sqrt_Rsqrt_Add partition files to
test differenct cases of partitioning.

[circle-part-eval] Introduce Sqrt_Rsqrt part files

---

compiler/luci/pass/src/QuantizedModelVerifier.test.cpp

This tidies Logistic test in QuantizedModelVerifier.test.cpp.

[luci] Tidy Logistic test in QuantizedModelVerifier.test.cpp

---

compiler/circle-partitioner/src/CirclePartitioner.cpp

This will revise options for circle-partitioner as
- use positional for partiton too
- change output to work folder

[circle-partitioner] Revise options

---

compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
compiler/luci/pass/src/QuantizedModelVerifier.test.cpp
compiler/luci/pass/src/VerifyQuantizedNodeChannelWiseGranularity.h
compiler/luci/pass/src/VerifyQuantizedNodeLayerWiseGranularity.h
compiler/luci/pass/src/VerifyQuantizedNodeS16Type.h
compiler/luci/pass/src/VerifyQuantizedNodeU8Type.h

This supports quantization of softmax op.
---

[circle-quantizer] Support quantization of softmax

---

compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
compiler/luci/pass/src/QuantizedModelVerifier.test.cpp
compiler/luci/pass/src/VerifyQuantizedNodeChannelWiseGranularity.h
compiler/luci/pass/src/VerifyQuantizedNodeLayerWiseGranularity.h
compiler/luci/pass/src/VerifyQuantizedNodeS16Type.h
compiler/luci/pass/src/VerifyQuantizedNodeU8Type.h

This supports quantization of tanh op.
---

[luci] Support quantization of tanh

---

compiler/circle-part-driver/src/PModelsRunner.cpp

This will implement save_outputs method in PModelsRunner.

[circle-part-driver] Implement save_outputs

---

compiler/circle-partitioner/src/CirclePartitioner.cpp
compiler/circle-partitioner/src/PartitionExport.cpp
compiler/circle-partitioner/src/PartitionExport.h

This will enable export of connection information to ini and json
formats.

[circle-partitioner] Export connection information

---

compiler/circle-part-driver/CMakeLists.txt
compiler/circle-part-driver/requires.cmake
compiler/circle-part-driver/src/PModelsRunner.cpp
compiler/circle-part-driver/src/PModelsRunner.h

This will implement PModelsRunner::run the models in _models_to_run with
luci-interpreter.

[circle-part-driver] Implement PModelsRunner::run

---

compiler/luci/service/src/Nodes/CircleConst.cpp

This will revise CircleConst clone method to use copy_common_attributes
method.

[luci] Revise CircleConst clone method

---

compiler/circle-part-eval/part_eval_all.sh

This will introduce part_eval_all.sh script to run all evaluation
test items.

[circle-part-eval] Introduce part_eval_all script

---

compiler/.ahub/tcchecker-tca/config.yaml

This will add crew library to ahub testcase folder.

[ahub] Add crew

---

compiler/luci/pass/src/QuantizedModelVerifier.test.cpp
compiler/luci/pass/src/VerifyQuantizedNodeChannelWiseGranularity.h
compiler/luci/pass/src/VerifyQuantizedNodeLayerWiseGranularity.h
compiler/luci/pass/src/VerifyQuantizedNodeS16Type.h
compiler/luci/pass/src/VerifyQuantizedNodeU8Type.h

This verifies quantization of transpose op.
---

[luci] Verify quantization of transpose

---

compiler/circle-part-eval/test.lst

This will add test list file with items for partition evaluation test.

[circle-part-eval] Add test list

---

infra/packaging/preset/20210406
infra/packaging/preset/20210406_windows

This commit adds 20210406 preset.
Related: https://github.com/Samsung/ONE/pull/6438#issuecomment-813780053

[preset] Add 20210406 preset

---

compiler/common-artifacts/CMakeLists.txt

This will add intentations for readability.

[common-artifacts] Add intents to cmake

---

compiler/luci/pass/src/QuantizedModelVerifier.test.cpp
compiler/luci/pass/src/VerifyQuantizedNodeChannelWiseGranularity.h
compiler/luci/pass/src/VerifyQuantizedNodeLayerWiseGranularity.h
compiler/luci/pass/src/VerifyQuantizedNodeS16Type.h
compiler/luci/pass/src/VerifyQuantizedNodeU8Type.h

This verifies quantization of reshape op.
---

[luci] Verify quantization of reshape op

---

compiler/circle-part-eval/CMakeLists.txt

This will enable evaluation of partition with test list.

[circle-part-eval] Run evaluation

---

infra/packaging/res/tf2nnpkg.20210406

This commit adds tf2nnpkg.20210406 for 20210406 preset.

[packaging] Add tf2nnpkg.20210406

---

compiler/luci/partition/src/CircleOpCode.cpp

This will simplify QueryOpCode with CIRCLE_NODE.

[luci] Simplify partition QueryOpCode

---

compiler/luci/partition/src/CircleNodeConnect.cpp
compiler/luci/partition/src/ConnectNode.cpp
compiler/luci/partition/src/ConnectNode.h

This will separate ConnectNode class to it's own file.

[luci] Separate ConnectNode class

---

compiler/circle-partitioner/src/CirclePartitioner.cpp

This will introduce and invoke validate_module to validate input model before patitioning.

[luci] Introduce validate_module

---

compiler/luci/partition/src/Nodes/CircleAdd.cpp
compiler/luci/partition/src/Nodes/CircleConst.cpp
compiler/luci/partition/src/Nodes/CircleDiv.cpp
compiler/luci/partition/src/Nodes/CircleMean.cpp
compiler/luci/partition/src/Nodes/CircleMul.cpp
compiler/luci/partition/src/Nodes/CirclePow.cpp
compiler/luci/partition/src/Nodes/CircleRsqrt.cpp
compiler/luci/partition/src/Nodes/CircleSqrt.cpp
compiler/luci/partition/src/Nodes/CircleSquaredDifference.cpp
compiler/luci/partition/src/Nodes/CircleSub.cpp

This will introduce ConnectNode visit file for each nodes.

[luci] Separate ConnectNode for each nodes

---

compiler/luci/service/src/Nodes/CircleAdd.cpp
compiler/luci/service/src/Nodes/CircleConst.cpp
compiler/luci/service/src/Nodes/CircleDiv.cpp
compiler/luci/service/src/Nodes/CircleMean.cpp
compiler/luci/service/src/Nodes/CircleMul.cpp

This will add nullptr check for clone node creation.

[luci] Check nullptr for clone

---

compiler/luci/service/src/CircleNodeClone.test.cpp

This will set FusedActFunc for simple add test graph.

[luci] Set FusedActFunc for test graph

---

compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
compiler/luci/pass/src/QuantizedModelVerifier.test.cpp
compiler/luci/pass/src/VerifyQuantizedNodeChannelWiseGranularity.h
compiler/luci/pass/src/VerifyQuantizedNodeLayerWiseGranularity.h
compiler/luci/pass/src/VerifyQuantizedNodeS16Type.h
compiler/luci/pass/src/VerifyQuantizedNodeU8Type.h

This commit supports quantization of floor operation
and the unit test.
-------------
For #6367

[luci] Support quantization of floor

---

compiler/luci/service/src/Nodes/CircleAdd.test.cpp
compiler/luci/service/src/Nodes/CircleDiv.test.cpp
compiler/luci/service/src/Nodes/CircleMul.test.cpp
compiler/luci/service/src/Nodes/CircleSub.test.cpp

This will add clone tests for Add,Div,Mul and Sub ops.

[luci] Add clone tests for Add,Div,Mul,Sub

---

compiler/luci/service/src/Nodes/CircleMean.test.cpp
compiler/luci/service/src/Nodes/CirclePow.test.cpp
compiler/luci/service/src/Nodes/CircleRsqrt.test.cpp
compiler/luci/service/src/Nodes/CircleSqrt.test.cpp
compiler/luci/service/src/Nodes/CircleSquaredDifference.test.cpp

This will add clone tests for Mean,Pow,Rsqrt,Sqrt and SquaredDifference Ops.

[luci] Add clone tests for Mean,Pow and others

---

compiler/luci/service/src/CircleCloneNode.h
compiler/luci/service/src/Nodes/CircleAbs.cpp
compiler/luci/service/src/Nodes/CircleAbs.test.cpp

This will enable clone of CircleAbs.

[luci] Enable clone of CircleAbs

---

compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
compiler/luci/pass/src/QuantizedModelVerifier.test.cpp
compiler/luci/pass/src/VerifyQuantizedNodeChannelWiseGranularity.h
compiler/luci/pass/src/VerifyQuantizedNodeLayerWiseGranularity.h
compiler/luci/pass/src/VerifyQuantizedNodeS16Type.h
compiler/luci/pass/src/VerifyQuantizedNodeU8Type.h

This supports quantization of greater op.
---

[luci] Support quantization of greater

---

compiler/luci/service/src/CircleCloneNode.h
compiler/luci/service/src/Nodes/CircleArgMax.cpp
compiler/luci/service/src/Nodes/CircleArgMax.test.cpp
compiler/luci/service/src/Nodes/CircleArgMin.cpp
compiler/luci/service/src/Nodes/CircleArgMin.test.cpp

This will enable clone of CircleMax,CircleMin.

[luci] Enable clone of CircleMax,CircleMin

---

infra/packaging/build

This commit updates default preset to 20210406.

[preset] Update default preset

---

compiler/luci/pass/src/QuantizedModelVerifier.test.cpp
compiler/luci/pass/src/VerifyQuantizedNodeChannelWiseGranularity.h
compiler/luci/pass/src/VerifyQuantizedNodeLayerWiseGranularity.h
compiler/luci/pass/src/VerifyQuantizedNodeS16Type.h
compiler/luci/pass/src/VerifyQuantizedNodeU8Type.h

This supports quantization of GreaterEqual Op.
---

[luci] Support quantization of GreaterEqual

---

compiler/luci/service/src/CircleCloneNode.h
compiler/luci/service/src/Nodes/CircleBatchMatMul.cpp
compiler/luci/service/src/Nodes/CircleBatchMatMul.test.cpp

This will enable clone of CircleBatchMatMul.

[luci] Enable clone of CircleBatchMatMul

---

compiler/luci/service/src/CircleCloneNode.h
compiler/luci/service/src/Nodes/CircleAddN.cpp
compiler/luci/service/src/Nodes/CircleAddN.test.cpp

This will enable clone of CircleAddN.

[luci] Enable clone of CircleAddN

---

compiler/luci/pass/src/RemoveUnnecessarySplitPass.test.cpp
compiler/luci/pass/src/ResolveCustomOpBatchMatMulPass.test.cpp
compiler/luci/pass/src/ShuffleWeightTo16x1Float32Pass.test.cpp
compiler/luci/testhelper/include/luci/test/TestIOGraph.h

This commit rewrites init for TestIGraph and TestOGraph.
-----------
Derived from #6494

[luci] Revisit testhelper

---

compiler/luci/service/src/CircleCloneNode.h
compiler/luci/service/src/Nodes/CircleAveragePool2D.cpp
compiler/luci/service/src/Nodes/CircleAveragePool2D.test.cpp

This will enable clone of CircleAveragePool2D.

[luci] Enable clone of CircleAveragePool2D

---

compiler/luci/service/src/CircleCloneNode.h
compiler/luci/service/src/Nodes/CircleBatchToSpaceND.cpp
compiler/luci/service/src/Nodes/CircleBatchToSpaceND.test.cpp

This will enable clone of CircleBatchToSpaceND.

[luci] Enable clone of CircleBatchToSpaceND

---

compiler/luci/service/src/CircleCloneNode.h
compiler/luci/service/src/Nodes/CircleConv2D.cpp
compiler/luci/service/src/Nodes/CircleConv2D.test.cpp

This will enable clone of CircleConv2D.

[luci] Enable clone of CircleConv2D

---

compiler/luci/service/src/CircleCloneNode.h
compiler/luci/service/src/Nodes/CircleElu.cpp
compiler/luci/service/src/Nodes/CircleElu.test.cpp

This will enable clone of CircleElu.

[luci] Enable clone of CircleElu

---

compiler/luci/service/src/CircleCloneNode.h
compiler/luci/service/src/Nodes/CircleFloor.cpp
compiler/luci/service/src/Nodes/CircleFloor.test.cpp
compiler/luci/service/src/Nodes/CircleFloorDiv.cpp
compiler/luci/service/src/Nodes/CircleFloorDiv.test.cpp
compiler/luci/service/src/Nodes/CircleFloorMod.cpp
compiler/luci/service/src/Nodes/CircleFloorMod.test.cpp

This will enable clone of CircleFloor, CircleFloorDiv and
CircleFloorMod.

[luci] Enable clone of CircleFloor and others

---

compiler/luci/pass/src/QuantizedModelVerifier.test.cpp

This commit adds a helper function to create dummy node.
For #6367

[luci] Add A Helper To Create Dummy Node

---

compiler/luci/service/src/CircleCloneNode.h
compiler/luci/service/src/Nodes/CircleCeil.cpp
compiler/luci/service/src/Nodes/CircleCeil.test.cpp
compiler/luci/service/src/Nodes/CircleCos.cpp
compiler/luci/service/src/Nodes/CircleCos.test.cpp
compiler/luci/service/src/Nodes/CircleExp.cpp
compiler/luci/service/src/Nodes/CircleExp.test.cpp
compiler/luci/service/src/Nodes/CircleLog.cpp
compiler/luci/service/src/Nodes/CircleLog.test.cpp

This will enable clone of CircleCeil, CircleCos, CircleExp and
CircleLog.

[luci] Enable clone of CircleCeil and others

---

compiler/luci/service/src/CircleCloneNode.h
compiler/luci/service/src/Nodes/CircleNeg.cpp
compiler/luci/service/src/Nodes/CircleNeg.test.cpp
compiler/luci/service/src/Nodes/CircleSin.cpp
compiler/luci/service/src/Nodes/CircleSin.test.cpp
compiler/luci/service/src/Nodes/CircleTanh.cpp
compiler/luci/service/src/Nodes/CircleTanh.test.cpp
compiler/luci/service/src/Nodes/CircleTopKV2.cpp
compiler/luci/service/src/Nodes/CircleTopKV2.test.cpp

This will enable clone of CircleNeg, CircleSin, CircleTanh and
CircleTopKV2.

[luci] Enable clone of CircleNeg and others

---

compiler/luci/service/src/CircleCloneNode.h
compiler/luci/service/src/Nodes/CircleDepthToSpace.cpp
compiler/luci/service/src/Nodes/CircleDepthToSpace.test.cpp
compiler/luci/service/src/Nodes/CircleSpaceToBatchND.cpp
compiler/luci/service/src/Nodes/CircleSpaceToBatchND.test.cpp
compiler/luci/service/src/Nodes/CircleSpaceToDepth.cpp
compiler/luci/service/src/Nodes/CircleSpaceToDepth.test.cpp

This will enable clone of CircleDepthToSpace, CircleSpaceToBatchND and
CircleSpaceToDepth.

[luci] Enable clone of CircleDepthToSpace and others

---

compiler/luci/service/src/CircleCloneNode.h
compiler/luci/service/src/Nodes/CircleCast.cpp
compiler/luci/service/src/Nodes/CircleCast.test.cpp
compiler/luci/service/src/Nodes/CircleConcatenation.cpp
compiler/luci/service/src/Nodes/CircleConcatenation.test.cpp

This will enable clone of CircleCast and CircleConcatenation.

[luci] Enable clone of CircleCast ant other

---

compiler/luci/service/src/CircleCloneNode.h
compiler/luci/service/src/Nodes/CircleReduceAny.cpp
compiler/luci/service/src/Nodes/CircleReduceAny.test.cpp
compiler/luci/service/src/Nodes/CircleReduceMax.cpp
compiler/luci/service/src/Nodes/CircleReduceMax.test.cpp
compiler/luci/service/src/Nodes/CircleReduceMin.cpp
compiler/luci/service/src/Nodes/CircleReduceMin.test.cpp
compiler/luci/service/src/Nodes/CircleReduceProd.cpp
compiler/luci/service/src/Nodes/CircleReduceProd.test.cpp

This will enable clone of CircleReduceAny, CircleReduceMax,
CircleReduceMin and CircleReduceProd.

[luci] Enable clone of CircleReduceAny and others

---

compiler/luci/pass/src/QuantizedModelVerifier.test.cpp
compiler/luci/pass/src/VerifyQuantizedNodeChannelWiseGranularity.h
compiler/luci/pass/src/VerifyQuantizedNodeLayerWiseGranularity.h
compiler/luci/pass/src/VerifyQuantizedNodeS16Type.h
compiler/luci/pass/src/VerifyQuantizedNodeU8Type.h

This commit enables div operation's quantization unit test.
DCO-ONE-1.0-Signed-off-by: Dayoung Lee <dayg502@gmail.com>
---------------------------
For #6367
Need #6509

[luci] Verify quantization of Div 

---

compiler/luci/service/src/CircleCloneNode.h
compiler/luci/service/src/Nodes/CircleDepthwiseConv2D.cpp
compiler/luci/service/src/Nodes/CircleDepthwiseConv2D.test.cpp
compiler/luci/service/src/Nodes/CircleFullyConnected.cpp
compiler/luci/service/src/Nodes/CircleFullyConnected.test.cpp

This will enable clone of CircleDepthwiseConv2D and
CircleFullyConnected.

[luci] Enable clone of CircleDepthwiseConv2D and other

---

compiler/luci/service/src/CircleCloneNode.h
compiler/luci/service/src/Nodes/CircleDequantize.cpp
compiler/luci/service/src/Nodes/CircleDequantize.test.cpp
compiler/luci/service/src/Nodes/CircleFakeQuant.cpp
compiler/luci/service/src/Nodes/CircleFakeQuant.test.cpp

This will enable clone of CircleDequantize and CircleFakeQuant.

[luci] Enable clone of CircleDequantize and other

---

compiler/luci/service/src/CircleCloneNode.h
compiler/luci/service/src/Nodes/CircleGather.cpp
compiler/luci/service/src/Nodes/CircleGather.test.cpp
compiler/luci/service/src/Nodes/CircleGatherNd.cpp
compiler/luci/service/src/Nodes/CircleGatherNd.test.cpp

This will enable clone of CircleGather and CircleGatherNd.

[luci] Enable clone of CircleGather, CircleGatherNd

---

compiler/luci/service/src/CircleCloneNode.h
compiler/luci/service/src/Nodes/CircleLogicalAnd.cpp
compiler/luci/service/src/Nodes/CircleLogicalAnd.test.cpp
compiler/luci/service/src/Nodes/CircleLogicalNot.cpp
compiler/luci/service/src/Nodes/CircleLogicalNot.test.cpp
compiler/luci/service/src/Nodes/CircleLogicalOr.cpp
compiler/luci/service/src/Nodes/CircleLogicalOr.test.cpp

This will enable clone of CircleLogicalAnd, CircleLogicalNot and
CircleLogicalOr.

[luci] Enable clone of CircleLogicalAnd and others

---

compiler/luci/service/src/CircleCloneNode.h
compiler/luci/service/src/Nodes/CircleExpandDims.cpp
compiler/luci/service/src/Nodes/CircleExpandDims.test.cpp
compiler/luci/service/src/Nodes/CircleFill.cpp
compiler/luci/service/src/Nodes/CircleFill.test.cpp

This will enable clone of CircleExpandDims and CircleFill.

[luci] Enable clone of CircleExpandDims and CircleFill

---

compiler/luci/service/src/CircleCloneNode.h
compiler/luci/service/src/Nodes/CircleL2Normalize.cpp
compiler/luci/service/src/Nodes/CircleL2Normalize.test.cpp
compiler/luci/service/src/Nodes/CircleL2Pool2D.cpp
compiler/luci/service/src/Nodes/CircleL2Pool2D.test.cpp

This will enable clone of CircleL2Normalize and CircleL2Pool2D.

[luci] Enable clone of CircleL2Normalize, CircleL2Pool2D

---

compiler/luci/service/src/CircleCloneNode.h
compiler/luci/service/src/Nodes/CircleLocalResponseNormalization.cpp
compiler/luci/service/src/Nodes/CircleLocalResponseNormalization.test.cpp

This will enable clone of CircleLocalResponseNormalization.

[luci] Enable clone of CircleLocalResponseNormalization

---

compiler/arser/include/arser/arser.h
compiler/arser/tests/arser.test.cpp

This commit enables arser to use short option.
Related : #4433

[arser] Support short option

---

compiler/luci-interpreter/src/kernels/BatchToSpaceND.cpp
compiler/luci-interpreter/src/kernels/BatchToSpaceND.h
compiler/luci-interpreter/src/kernels/BatchToSpaceND.test.cpp
compiler/luci-interpreter/src/kernels/CMakeLists.txt
compiler/luci-interpreter/src/loader/KernelBuilder.cpp
compiler/luci-interpreter/src/loader/KernelBuilder.h

For #6500
This commit will introduce `BatchToSpaceND` kernel to enable evaluation `CircleBatchToSpaceND`.

[luci-interpreter] Introduce BatchToSpaceND kernel

---

compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
compiler/luci/pass/src/QuantizedModelVerifier.test.cpp
compiler/luci/pass/src/VerifyQuantizedNodeChannelWiseGranularity.h
compiler/luci/pass/src/VerifyQuantizedNodeLayerWiseGranularity.h
compiler/luci/pass/src/VerifyQuantizedNodeS16Type.h
compiler/luci/pass/src/VerifyQuantizedNodeU8Type.h

This commit enables floor div operation's quantization unit test.
DCO-ONE-1.0-Signed-off-by: Dayoung Lee <dayg502@gmail.com>
--------------
For #6367 
Ready after #6503 is merged

[luci] Support quantization of FloorDiv 

---

compiler/luci/service/src/CircleCloneNode.h
compiler/luci/service/src/Nodes/CircleMatrixDiag.cpp
compiler/luci/service/src/Nodes/CircleMatrixDiag.test.cpp
compiler/luci/service/src/Nodes/CircleMatrixSetDiag.cpp
compiler/luci/service/src/Nodes/CircleMatrixSetDiag.test.cpp

This will enable clone of CircleMatrixDiag and CircleMatrixSetDiag.

[luci] Enable clone of CircleMatrixDiag, CircleMatrixSetDiag

---

compiler/luci/service/src/CircleCloneNode.h
compiler/luci/service/src/Nodes/CircleNonMaxSuppressionV4.cpp
compiler/luci/service/src/Nodes/CircleNonMaxSuppressionV4.test.cpp
compiler/luci/service/src/Nodes/CircleNonMaxSuppressionV5.cpp
compiler/luci/service/src/Nodes/CircleNonMaxSuppressionV5.test.cpp

This will enable clone of CircleNonMaxSuppressionV4,
CircleNonMaxSuppressionV5.

[luci] Enable clone of CircleNonMaxSuppressionV4/V5

---

compiler/luci/service/src/CircleCloneNode.h
compiler/luci/service/src/Nodes/CircleTranspose.cpp
compiler/luci/service/src/Nodes/CircleTranspose.test.cpp
compiler/luci/service/src/Nodes/CircleTransposeConv.cpp
compiler/luci/service/src/Nodes/CircleTransposeConv.test.cpp

This will enable clone of CircleTranspose and CircleTransposeConv.

[luci] Enable clone of CircleTranspose and other

---

compiler/luci/service/src/CircleCloneNode.h
compiler/luci/service/src/Nodes/CircleUnique.cpp
compiler/luci/service/src/Nodes/CircleUnique.test.cpp
compiler/luci/service/src/Nodes/CircleUnpack.cpp
compiler/luci/service/src/Nodes/CircleUnpack.test.cpp
compiler/luci/service/src/Nodes/CircleWhere.cpp
compiler/luci/service/src/Nodes/CircleWhere.test.cpp
compiler/luci/service/src/Nodes/CircleZerosLike.cpp
compiler/luci/service/src/Nodes/CircleZerosLike.test.cpp

This will enable clone of CircleUnique, CircleUnpack, CircleWhere and
CircleZerosLike.

[luci] Enable clone of CircleUnique and others

---

compiler/luci/service/src/CircleCloneNode.h
compiler/luci/service/src/Nodes/CircleBCQFullyConnected.cpp
compiler/luci/service/src/Nodes/CircleBCQFullyConnected.test.cpp
compiler/luci/service/src/Nodes/CircleBCQGather.cpp
compiler/luci/service/src/Nodes/CircleBCQGather.test.cpp

This will enable clone of CircleBCQFullyConnected and CircleBCQGather.

[luci] Enable clone of CircleBCQFullyConnected and other

---

compiler/luci/service/src/CircleCloneNode.h
compiler/luci/service/src/Nodes/CircleLogSoftmax.cpp
compiler/luci/service/src/Nodes/CircleLogSoftmax.test.cpp
compiler/luci/service/src/Nodes/CircleLogistic.cpp
compiler/luci/service/src/Nodes/CircleLogistic.test.cpp
compiler/luci/service/src/Nodes/CircleSlice.cpp
compiler/luci/service/src/Nodes/CircleSlice.test.cpp
compiler/luci/service/src/Nodes/CircleSoftmax.cpp
compiler/luci/service/src/Nodes/CircleSoftmax.test.cpp

This will enable clone of CircleLogSoftmax, CircleLogistic, CircleSlice
and CircleSoftmax.

[luci] Enable clone of CircleLogSoftmax and others

---

compiler/luci/service/src/CircleCloneNode.h
compiler/luci/service/src/Nodes/CircleMaxPool2D.cpp
compiler/luci/service/src/Nodes/CircleMaxPool2D.test.cpp
compiler/luci/service/src/Nodes/CircleMaximum.cpp
compiler/luci/service/src/Nodes/CircleMaximum.test.cpp
compiler/luci/service/src/Nodes/CircleMinimum.cpp
compiler/luci/service/src/Nodes/CircleMinimum.test.cpp
compiler/luci/service/src/Nodes/CircleMirrorPad.cpp
compiler/luci/service/src/Nodes/CircleMirrorPad.test.cpp

This will enable clone of CircleMaxPool2D, CircleMaximum, CircleMinimum
and CircleMirrorPad.

[luci] Enable clone of CircleMaxPool2D and others

---

compiler/luci/service/src/CircleCloneNode.h
compiler/luci/service/src/Nodes/CircleOneHot.cpp
compiler/luci/service/src/Nodes/CircleOneHot.test.cpp
compiler/luci/service/src/Nodes/CirclePack.cpp
compiler/luci/service/src/Nodes/CirclePack.test.cpp
compiler/luci/service/src/Nodes/CirclePad.cpp
compiler/luci/service/src/Nodes/CirclePad.test.cpp
compiler/luci/service/src/Nodes/CirclePadV2.cpp
compiler/luci/service/src/Nodes/CirclePadV2.test.cpp

This will enable clone of CircleOneHot, CirclePack, CirclePad and
CirclePadV2.

[luci] Enable clone of CircleOneHot and others

---

compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
compiler/luci/pass/src/QuantizedModelVerifier.test.cpp
compiler/luci/pass/src/VerifyQuantizedNodeChannelWiseGranularity.h
compiler/luci/pass/src/VerifyQuantizedNodeLayerWiseGranularity.h
compiler/luci/pass/src/VerifyQuantizedNodeS16Type.h
compiler/luci/pass/src/VerifyQuantizedNodeU8Type.h

This commit verifies quantization of rsqrt operation.
-----
For #6367

[luci] Verify quantization of Rsqrt

---

compiler/luci/service/src/CircleCloneNode.h
compiler/luci/service/src/Nodes/CircleSparseToDense.cpp
compiler/luci/service/src/Nodes/CircleSparseToDense.test.cpp
compiler/luci/service/src/Nodes/CircleSplit.cpp
compiler/luci/service/src/Nodes/CircleSplit.test.cpp
compiler/luci/service/src/Nodes/CircleSplitV.cpp
compiler/luci/service/src/Nodes/CircleSplitV.test.cpp

This will enable clone of CircleSparseToDense, CircleSplit and
CircleSplitV.

[luci] Enable clone of CircleSparseToDense and others

---

compiler/luci/service/src/CircleCloneNode.h
compiler/luci/service/src/Nodes/CircleCustom.cpp
compiler/luci/service/src/Nodes/CircleCustom.test.cpp

This will enable clone of CircleCustom.

[luci] Enable clone of CircleCustom

---

compiler/luci/service/src/CircleCloneNode.h
compiler/luci/service/src/Nodes/CircleRange.cpp
compiler/luci/service/src/Nodes/CircleRange.test.cpp
compiler/luci/service/src/Nodes/CircleRank.cpp
compiler/luci/service/src/Nodes/CircleRank.test.cpp

This will enable clone of CircleRange and CircleRank.

[luci] Enable clone of CircleRange and other

---

compiler/luci/service/src/CircleCloneNode.h
compiler/luci/service/src/Nodes/CircleReverseSequence.cpp
compiler/luci/service/src/Nodes/CircleReverseSequence.test.cpp
compiler/luci/service/src/Nodes/CircleReverseV2.cpp
compiler/luci/service/src/Nodes/CircleReverseV2.test.cpp
compiler/luci/service/src/Nodes/CircleRound.cpp
compiler/luci/service/src/Nodes/CircleRound.test.cpp

This will enable clone for CircleReverseSequence, CircleReverseV2 and
CircleRound.

[luci] Enable clone for CircleReverseSequence and others

---

compiler/luci/service/src/CircleCloneNode.h
compiler/luci/service/src/Nodes/CircleInstanceNorm.cpp
compiler/luci/service/src/Nodes/CircleInstanceNorm.test.cpp

This will enable clone for CircleInstanceNorm.

[luci] Enable clone for CircleInstanceNorm

---

compiler/luci/service/src/CircleCloneNode.h
compiler/luci/service/src/Nodes/CircleUnidirectionalSequenceLSTM.cpp
compiler/luci/service/src/Nodes/CircleUnidirectionalSequenceLSTM.test.cpp

This will enable clone for CircleUnidirectionalSequenceLSTM.

[luci] Enable clone for CircleUnidirectionalSequenceLSTM

---

compiler/luci/service/src/Nodes/CircleAveragePool2D.test.cpp

This will add CircleAveragePool2D clone test with attributes value
testing.

[luci] Add test attributes of AvgPool2D clone

---

compiler/record-minmax-conversion-test/gen_h5_random_inputs.py

This allows to generate random boolean inputs.
---
Draft PR: #6526

[record-minmax-test] Generate random boolean input

---

compiler/arser/include/arser/arser.h

This commit applies short option to help message and `exit_with` method.
Related: #4433 

[arser] Apply short option

---

compiler/souschef/src/Gaussian.cpp

This commit adds unified gaussian generator of tensor data.
related issue #6576 

[souschef] Introduce unified gaussian generator

---

compiler/souschef/src/Gaussian.cpp

This commit replaces gaussian generator functions with unified generator.
related issue #6576

[souschef] Use unified gaussian generator

---

compiler/vconone/src/version.cpp

This commit updates copyright notice.

[vconone] Update copyright notice

---

compiler/luci/import/src/Nodes/CircleRsqrt.cpp

This supports importing quantized input for RSQRT.

[luci] Support importing quantized input for RSQRT

---

compiler/record-minmax/src/HDF5Importer.cpp

This accepts bool type input from h5.
---
Draft PR: #6526

[record-minmax] Accept bool type input from h5

---

compiler/record-minmax/src/RecordMinMax.cpp

This generates random bool-type input data.
---
Draft PR: #6526

[record-minmax] Generate random bool input data

---

compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
compiler/luci/pass/src/QuantizedModelVerifier.test.cpp
compiler/luci/pass/src/VerifyQuantizedNodeChannelWiseGranularity.h
compiler/luci/pass/src/VerifyQuantizedNodeLayerWiseGranularity.h
compiler/luci/pass/src/VerifyQuantizedNodeS16Type.h
compiler/luci/pass/src/VerifyQuantizedNodeU8Type.h

This commit verifies quantization of sqrt.
----
For #6367

 [luci] Verify quantization of Sqrt

---

compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
compiler/luci/pass/src/QuantizedModelVerifier.test.cpp
compiler/luci/pass/src/VerifyQuantizedNodeChannelWiseGranularity.h
compiler/luci/pass/src/VerifyQuantizedNodeLayerWiseGranularity.h
compiler/luci/pass/src/VerifyQuantizedNodeS16Type.h
compiler/luci/pass/src/VerifyQuantizedNodeU8Type.h

This supports quantization of BatchToSpaceND op.
---

[luci] Support quantization of BatchToSpaceND

---

compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
compiler/luci/pass/src/QuantizedModelVerifier.test.cpp
compiler/luci/pass/src/VerifyQuantizedNodeChannelWiseGranularity.h
compiler/luci/pass/src/VerifyQuantizedNodeLayerWiseGranularity.h
compiler/luci/pass/src/VerifyQuantizedNodeS16Type.h
compiler/luci/pass/src/VerifyQuantizedNodeU8Type.h

This supports quantization of StridedSlice op.
---

[luci] Support quantization of StridedSlice

---

compiler/arser/include/arser/arser.h

This commit makes arser print short option properly.
Even though #6535,  #6572 have been merged, arser didn't print the short option properly because they were just about an interface-related changes. From this PR, I expect arser will be able to fully support a short option.
I think it is a bit hard to review the changes but I will try to explain it as much as I can.
Here are changes that I think is important.
- `Argument` class has introduced `_short_name`, `_long_name`, `_names`.
- `_name` has been divided into `_short_name` and `_long_name` because `arser` got to support multiple names.
- `_names` vector includes `_short_name` and `_long_name`. This variable is for pretty printing.
- Validation of arguments given by users.
- Multiple names requires more thorough validation than it used …

[arser] Make arser print short option properly

---

compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
compiler/luci/pass/src/QuantizedModelVerifier.test.cpp
compiler/luci/pass/src/VerifyQuantizedNodeChannelWiseGranularity.h
compiler/luci/pass/src/VerifyQuantizedNodeLayerWiseGranularity.h
compiler/luci/pass/src/VerifyQuantizedNodeS16Type.h
compiler/luci/pass/src/VerifyQuantizedNodeU8Type.h

This supports quantization of DepthToSpace op.
---

[luci] Support quantization of DepthToSpace

---

compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
compiler/luci/pass/src/QuantizedModelVerifier.test.cpp
compiler/luci/pass/src/VerifyQuantizedNodeChannelWiseGranularity.h
compiler/luci/pass/src/VerifyQuantizedNodeLayerWiseGranularity.h
compiler/luci/pass/src/VerifyQuantizedNodeS16Type.h
compiler/luci/pass/src/VerifyQuantizedNodeU8Type.h

This commit supports quantization of Pow and its verification.
-----
For #6367
Includes #6581 (The commit doesn't contain functional relations, but many merge conflicts are expected.)

[luci] Support quantization of Pow

---

compiler/luci/pass/src/QuantizedModelVerifier.test.cpp

This commit adds ommitted SimpleTestGraph inheritances.
--------------
Related to ##6586

[luci] Add SimpleTestGraph inheritances

---

compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
compiler/luci/pass/src/QuantizedModelVerifier.test.cpp
compiler/luci/pass/src/VerifyQuantizedNodeChannelWiseGranularity.h
compiler/luci/pass/src/VerifyQuantizedNodeLayerWiseGranularity.h
compiler/luci/pass/src/VerifyQuantizedNodeS16Type.h
compiler/luci/pass/src/VerifyQuantizedNodeU8Type.h

This supports quantization of SpaceToDepth op.
---

[luci] Support quantization of SpaceToDepth

---

compiler/luci/testhelper/include/luci/test/TestIOGraph.h

This will rename variable name in TestOGraphlet.

[luci] Rename variable for TestOGraphlet

---

compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
compiler/luci/pass/src/QuantizedModelVerifier.test.cpp
compiler/luci/pass/src/VerifyQuantizedNodeChannelWiseGranularity.h
compiler/luci/pass/src/VerifyQuantizedNodeLayerWiseGranularity.h
compiler/luci/pass/src/VerifyQuantizedNodeS16Type.h
compiler/luci/pass/src/VerifyQuantizedNodeU8Type.h

This suppports quantization of SpaceToBatchND.
---

[luci] Support quantization of SpaceToBatchND

---

compiler/luci/pass/src/QuantizedModelVerifier.test.cpp
compiler/luci/pass/src/VerifyQuantizedNodeChannelWiseGranularity.h
compiler/luci/pass/src/VerifyQuantizedNodeLayerWiseGranularity.h
compiler/luci/pass/src/VerifyQuantizedNodeS16Type.h
compiler/luci/pass/src/VerifyQuantizedNodeU8Type.h

This verifies quantization of Split Op.
---

[luci] Verify quantization of Split

---

compiler/arser/include/arser/arser.h

This commit makes arser follow the One Definition Rule.
There are three changes to accomplish this.
- define header guard
- make non-template function inline
- move non-template function related `Arser` to inside its method (`operator<<`)
Related: #6592 

[arser] Make arser follow ODR

---

compiler/luci-interpreter/src/loader/KernelBuilder.cpp
compiler/luci-interpreter/src/loader/KernelBuilder.h

This revises error msg for NYI nodes.

[luci-interpreter] Revise error msg for NYI nodes

---

compiler/luci/partition/src/ConnectNode.test.cpp
compiler/luci/partition/src/ConnectNode.test.h

This will introduce TestIsOGraph class for connection test providing
arbitrary N input with template.

[luci] Introduce TestIsOGraph for connection test

---

compiler/luci/partition/src/Nodes/CircleMean.cpp
compiler/luci/partition/src/Nodes/CirclePow.cpp
compiler/luci/partition/src/Nodes/CircleRsqrt.cpp
compiler/luci/partition/src/Nodes/CircleSqrt.cpp
compiler/luci/partition/src/Nodes/CircleSquaredDifference.cpp

This will revise partition connect method for nodes Mean, Pow, Rsqrt,
Sqrt and SquaredDifference.

[luci] Revise partition connection for nodes Mean and others

---

docs/release/1.15/index.rst
docs/release/1.15/release-note-1.15.0.md

- Release Note for ONE 1.15.0
Signed-off-by: twoflower <chunseoklee@gmail.com>

Release Note for ONE 1.15.0

---

docs/conf.py
packaging/nnfw.spec
runtime/contrib/android/api/build.gradle
runtime/onert/api/include/nnfw_version.h

ONERT version strings to 1.16.0

Bump to 1.16.0

---

.ahub/tcchecker-tca/config.yaml

- To fix a bug on analysis hub integration.

Update TCM config

---

infra/scripts/build-tcm.sh

- Update tool package to `tca-standalone-1.0.0.jar`.

Update TCM script

---

compiler/luci/partition/src/ConnectNode.h
compiler/luci/partition/src/Nodes/CircleNeg.cpp
compiler/luci/partition/src/Nodes/CircleNeg.test.cpp
compiler/luci/partition/src/Nodes/CircleNonMaxSuppressionV4.cpp
compiler/luci/partition/src/Nodes/CircleNonMaxSuppressionV4.test.cpp
compiler/luci/partition/src/Nodes/CircleNonMaxSuppressionV5.cpp
compiler/luci/partition/src/Nodes/CircleNonMaxSuppressionV5.test.cpp

This will enable connection of cloned nodes for CircleNeg,
CircleNonMaxSuppressionV4 and CircleNonMaxSuppressionV5.

[luci] Clone connect for Neg and others

---

compiler/luci/partition/src/ConnectNode.h
compiler/luci/partition/src/Nodes/CircleLess.cpp
compiler/luci/partition/src/Nodes/CircleLess.test.cpp
compiler/luci/partition/src/Nodes/CircleLessEqual.cpp
compiler/luci/partition/src/Nodes/CircleLessEqual.test.cpp

This will ernable connection of cloned nodes for CircleLess and
CircleLessEqual.

[luci] Clone connect for Less and LessEqual

---

compiler/luci/partition/src/ConnectNode.h
compiler/luci/partition/src/Nodes/CircleFullyConnected.cpp
compiler/luci/partition/src/Nodes/CircleFullyConnected.test.cpp

This will enable connection of cloned nodes for CircleFullyConnected.

[luci] Clone connect for FullyConnected

---

compiler/luci/partition/src/ConnectNode.h
compiler/luci/service/src/CircleCloneNode.h

This will add comment of clone/connect for CircleInput and CircleOutput.

[luci] Comment of clone/connect

---

compiler/one-cmds/one-prepare-venv

This will revise one-prepare-venv script with common PIP_OPTIONS for pip
options.

[one-cmds] Revise one-prepare-venv with PIP_OPTIONS

---

compiler/one-cmds/one-prepare-venv

This will introduce version variable to interested packages in
one-prepare-venv. And with version information URL.

[one-cmds] Introduce version variable to one-prepare-venv

---

compiler/one-cmds/one-build.template.cfg

Tihs commit adds model_format option to cfg template.

[one-cmds] Add model_format option to cfg template

---

infra/packaging/preset/20210406

This commit adds dev tools to preset 20210406.
Related: #6717 

[preset] Add dev tools to preset 20210406

---

compiler/luci-interpreter/src/kernels/Utils.cpp

This enables to support more fused activation functions.

[luci-interpreter] Support more fused activation functions

---

compiler/souschef/include/souschef/Data/Explicit.h
compiler/souschef/src/Explicit.cpp

This will introduce explicit data generator for string type.

[souschef] Introduce string type explicit data

---

compiler/one-cmds/one-build
compiler/one-cmds/one-codegen
compiler/one-cmds/one-import
compiler/one-cmds/one-import-bcq
compiler/one-cmds/one-import-onnx
compiler/one-cmds/one-import-tf
compiler/one-cmds/one-import-tflite
compiler/one-cmds/one-optimize
compiler/one-cmds/one-pack
compiler/one-cmds/one-quantize

This commit adds readlink command when one sciprt finds script path,
which resolves symbolic link.
Related: https://github.com/Samsung/ONE/issues/6773#issuecomment-838282720

[one-cmds] Add readlink command

---

compiler/rawdata2hdf5/rawdata2hdf5

This commit adds readlink command when one sciprt finds script path,
which resolves symbolic link.
Related: #6773 (comment)

[rawdata2hdf5] Add readlink command

---

debian/one-compiler.install

This commit removes deprecated files from install script.

[debian] Remove deprecated files

---

compiler/luci/pass/src/TransformMinMaxToRelu6Pass.cpp

This will fix TransformMinMaxToRelu6Pass comment about Miminum inputs.

[luci] Fix TransformMinMaxToRelu6Pass comment

---

compiler/luci/pass/include/luci/Pass/TransformMinReluToRelu6Pass.h
compiler/luci/pass/src/TransformMinReluToRelu6Pass.cpp
compiler/luci/pass/src/TransformMinReluToRelu6Pass.test.cpp

This will introduce TransformMinReluToRelu6Pass that will transform
Mininum(6)+ReLU to ReLU6 Op.

[luci] Introduce TransformMinReluToRelu6Pass

---

compiler/luci/pass/include/luci/CircleOptimizer.h
compiler/luci/pass/src/CircleOptimizer.cpp

This will enable transform_min_relu_to_relu6 option.

[luci] Enable transform_min_relu_to_relu6

---

compiler/circle2circle/src/Circle2Circle.cpp

This will revise transform_min_max_to_relu6 help message with numbers
for actual minimum and maximum values.

[circle2circle] Revise transform_min_max_to_relu6 help

---

res/TensorFlowLiteRecipes/Net_Conv_Min_Relu_000/test.recipe
res/TensorFlowLiteRecipes/Net_Conv_Min_Relu_000/test.rule

This will introduce Net_Conv_Min_Relu_000 recipe to check transformation
of Min(6)+ReLU to ReLU6.

[res] Introduce Net_Conv_Min_Relu_000 recipe

---

compiler/one-cmds/how-to-use-one-commands.txt
compiler/one-cmds/utils.py

This will add transform_min_relu_to_relu6 transformation option.

[one-cmds] Add transform_min_relu_to_relu6 option

---

compiler/luci/pass/include/luci/CircleOptimizer.h
compiler/luci/pass/src/CircleOptimizer.cpp

This will enable RemoveFakeQuantPass transformation by option.

[luci] Enable RemoveFakeQuantPass option

---

compiler/circle2circle/src/Circle2Circle.cpp

This will enable remove_fakequant transformation option.

[circle2circle] Enable remove_fakequant

---

compiler/luci-eval-driver/CMakeLists.txt

This commit add install command.

[luci-eval-driver] Install binary

---

res/TensorFlowLiteRecipes/Net_Conv_FakeQuant_000/test.recipe
res/TensorFlowLiteRecipes/Net_Conv_FakeQuant_000/test.rule

This will introduce Net_Conv_FakeQuant_000 having Conv2D-FakeQuant
to test remove_fakequant transformation option.

[res] Introduce Net_Conv_FakeQuant_000

---

debian/one-compiler.install

This commit installs conv_mixin_1.8.0.patch.

[debian] Install patch file

---

debian/one-compiler.install

This commit installs nnpkg tools.

[debian] Install nnpkg tools

---

debian/postrm

This commit adds postrm script. This script removes virtualenv file at the end of `apt purge` step.

[debian] Add postrm script

---

compiler/circledump/src/Read.h

This commit fixes static warnings in `circledump`.

[circledump] Fix static warnings

---

debian/one-compiler-dev.install
debian/one-compiler-dev.links
debian/one-compiler.links

This commit adds symlinks and tflchef tool to one-compiler-dev package.

[debian] Add symlink and tflchef tool

---

compiler/luci/pass/src/CircleOptimizer.cpp

This will revise sub options for ConvertNCHWToNHWC to use
NCHW_to_NHWC_input_shape, NCHW_to_NHWC_output_shape.

[luci] Revise sub options for ConvertNCHWToNHWC

---

compiler/circle2circle/src/Circle2Circle.cpp

This will introduce two sub options for convert_nchw_to_nhwc to convert
NCHW to NHWC for inputs and outputs.

[circle2circle] Sub options for convert_nchw_to_nhwc

---

debian/postrm

This commit revises postrm script.

[debian] Revise postrm script

---

debian/one-compiler-dev.install
debian/one-compiler-dev.links

This commit adds tflchef tools to one-compiler-dev package.

[debian] Add tflchef tools

---

compiler/one-cmds/utils.py

This commit revises the way one-optimize receive options.
Related: #6842 

[one-cmds] Revise the way one-optimize receive options

---

.ahub/tcchecker-tca/config.yaml

This will add recent modules added to dev or test.

[AHub] Revise compiler test modules

---

docs/release/1.16/index.rst
docs/release/1.16/release-note-1.16.0.md

Release Note for ONE 1.16.0

---

infra/scripts/build-tcm.sh

- Update package information for v1.0.2
- Add optional parameter [test_target] to support new TCM config for
AHUB support.

Update TCM build script.

---

docs/release/1.10/index.rst
docs/release/1.11/index.rst
docs/release/1.12/index.rst
docs/release/1.13/index.rst
docs/release/1.14/index.rst
docs/release/1.15/index.rst
docs/release/1.5/index.rst
docs/release/1.6/index.rst
docs/release/1.7/index.rst
docs/release/1.8/index.rst
docs/release/1.9/index.rst
docs/release/index.rst

Following: https://github.com/Samsung/ONE/pull/6860#issuecomment-844688990
- Add missing links in main index file.
- Fix invalid titles in sub index file.

Fix typos in release documents.

---

.ahub/sam/exclude.txt

This commit adds comment for each exclude file list.
---
For https://github.com/Samsung/ONE/pull/6863#discussion_r635778619
Comment and empty line looks available for this file.

[SAM] Add comments for exclude list

---

debian/changelog

This commit changes distribution value to stable one.

[debian] Change distribution value

---

docs/release/1.16/index.rst
docs/release/1.16/release-note-1.16.1.md

- Release Note for ONE 1.16.1
- index.rst updated

Release Note for ONE 1.16.1

---

debian/changelog

This commit adds 1.16.1 changelog.

[debian] Add 1.16.1 changelog

---

infra/cmake/modules/ExternalSourceTools.cmake

This commit enable retrying when external source download is failed.

[infra] Retry if external source download fails

---

compiler/one-cmds/one-prepare-venv

This commit add #6809 related comments.

[one-cmds] Add comments

---

res/TensorFlowLiteRecipes/Quantize_000/test.recipe

This will introduce Quantize recipe for testing Quantize Op.

[res] Introduce Quantize recipe

---

compiler/luci/logex/src/FormattedGraph.cpp

This will enable logex to dump CircleQuantize.

[luci] Enable logex of CircleQuantize

---

compiler/luci/service/src/CircleCloneNode.h
compiler/luci/service/src/Nodes/CircleQuantize.cpp
compiler/luci/service/src/Nodes/CircleQuantize.test.cpp

This will enable clone of CircleQuantize.

[luci] Enable clone of CircleQuantize

---

compiler/luci/export/src/CircleOperationExporter.cpp

This will enable export of CircleQuantize.

[luci] Enable export of CircleQuantize

---

compiler/luci/pass/include/luci/Pass/RemoveQuantDequantSeqPass.h
compiler/luci/pass/src/RemoveQuantDequantSeqPass.cpp
compiler/luci/pass/src/RemoveQuantDequantSeqPass.test.cpp

This will introduce RemoveQuantDequantSeqPass that will remove
Quantize-Dequantize sequence for experiament.

[luci] Introduce RemoveQuantDequantSeqPass

---

compiler/one-cmds/one-import-tflite
compiler/one-cmds/one-optimize

This will remove unused tempfile from import.

[one-cmds] Remove unused import tempfile

---

compiler/one-cmds/how-to-use-one-commands.txt
compiler/one-cmds/utils.py

This will add remove_quantdequant optimization option.

[one-cmds] Add remove_quantdequant option

---

res/TensorFlowLiteRecipes/Net_Conv_QuantDequant_000/test.recipe
res/TensorFlowLiteRecipes/Net_Conv_QuantDequant_000/test.rule

This will introduce Net_Conv_QuantDequant_000 test model to test
remove_quantdequant optimization option.

[res] Introduce Net_Conv_QuantDequant_000

---

compiler/luci/service/src/CircleCloneNode.cpp
compiler/luci/service/src/CircleCloneNode.h
compiler/luci/service/src/Nodes/CircleL2Normalize.cpp
compiler/luci/service/src/Nodes/CircleL2Pool2D.cpp
compiler/luci/service/src/Nodes/CircleLeakyRelu.cpp
compiler/luci/service/src/Nodes/CircleLess.cpp
compiler/luci/service/src/Nodes/CircleLessEqual.cpp
compiler/luci/service/src/Nodes/CircleLocalResponseNormalization.cpp
compiler/luci/service/src/Nodes/CircleLog.cpp
compiler/luci/service/src/Nodes/CircleLogSoftmax.cpp
compiler/luci/service/src/Nodes/CircleLogicalAnd.cpp
compiler/luci/service/src/Nodes/CircleLogicalNot.cpp
compiler/luci/service/src/Nodes/CircleLogicalOr.cpp
compiler/luci/service/src/Nodes/CircleLogistic.cpp
compiler/luci/service/src/Nodes/CircleMatrixDiag.cpp
compiler/luci/service/src/Nodes/CircleMatrixSetDiag.cpp
compiler/luci/service/src/Nodes/CircleMaxPool2D.cpp
compiler/luci/service/src/Nodes/CircleMaximum.cpp
compiler/luci/service/src/Nodes/CircleMean.cpp
compiler/luci/service/src/Nodes/CircleMinimum.cpp
compiler/luci/service/src/Nodes/CircleMirrorPad.cpp
compiler/luci/service/src/Nodes/CircleMul.cpp
compiler/luci/service/src/Nodes/CircleNeg.cpp
compiler/luci/service/src/Nodes/CircleNonMaxSuppressionV4.cpp
compiler/luci/service/src/Nodes/CircleNonMaxSuppressionV5.cpp
compiler/luci/service/src/Nodes/CircleNotEqual.cpp

This will group CloneNode to smaller subclass for KLMN.

[luci] Group CloneNode to small subclass for KLMN

---

compiler/luci/service/src/CircleCloneNode.cpp
compiler/luci/service/src/CircleCloneNode.h
compiler/luci/service/src/Nodes/CircleOneHot.cpp
compiler/luci/service/src/Nodes/CirclePRelu.cpp
compiler/luci/service/src/Nodes/CirclePack.cpp
compiler/luci/service/src/Nodes/CirclePad.cpp
compiler/luci/service/src/Nodes/CirclePadV2.cpp
compiler/luci/service/src/Nodes/CirclePow.cpp
compiler/luci/service/src/Nodes/CircleQuantize.cpp
compiler/luci/service/src/Nodes/CircleRange.cpp
compiler/luci/service/src/Nodes/CircleRank.cpp
compiler/luci/service/src/Nodes/CircleReduceAny.cpp
compiler/luci/service/src/Nodes/CircleReduceMax.cpp
compiler/luci/service/src/Nodes/CircleReduceMin.cpp
compiler/luci/service/src/Nodes/CircleReduceProd.cpp
compiler/luci/service/src/Nodes/CircleRelu.cpp
compiler/luci/service/src/Nodes/CircleRelu6.cpp
compiler/luci/service/src/Nodes/CircleReluN1To1.cpp
compiler/luci/service/src/Nodes/CircleReshape.cpp
compiler/luci/service/src/Nodes/CircleResizeBilinear.cpp
compiler/luci/service/src/Nodes/CircleResizeNearestNeighbor.cpp
compiler/luci/service/src/Nodes/CircleReverseSequence.cpp
compiler/luci/service/src/Nodes/CircleReverseV2.cpp
compiler/luci/service/src/Nodes/CircleRound.cpp
compiler/luci/service/src/Nodes/CircleRsqrt.cpp

This will group CloneNode to smaller subclass for OPQR.

[luci] Group CloneNode to small subclass for OPQR

---

compiler/luci/import/src/Nodes/CircleElu.cpp

This commit will Add more type on CircleElu import validate.

[luci/import] Add more type on CircleElu validate phase

---

compiler/circle2circle/src/Circle2Circle.cpp

This will add change_outputs option to change outputs of the model.

[circle2circle] Support change_outputs option

---

compiler/one-cmds/one-optimize
compiler/one-cmds/tests/one-optimize_002.test
compiler/one-cmds/tests/one-optimize_neg_004.test

This will enable change_outputs option in one-optimize.

[one-cmds] Enable change_outputs option

---

compiler/luci/logex/src/FormattedGraph.cpp

This will relocate CircleQuantize alphabetical order in logex.

[luci] Relocate CircleQuantize in logex

---

compiler/luci-interpreter/src/loader/KernelBuilder.cpp

This will move static function to anonymous namespace.

[luci-interpreter] Move static to anonymous

---

runtime/onert/api/include/nnfw_experimental.h
runtime/onert/api/src/nnfw_api.cc
runtime/onert/api/src/nnfw_api_internal.cc
runtime/onert/api/src/nnfw_api_internal.h
runtime/onert/core/include/compiler/Compiler.h
runtime/onert/core/include/compiler/LoweredGraph.h
runtime/onert/core/include/exec/Execution.h
runtime/onert/core/include/exec/IExecutor.h
runtime/onert/core/include/ir/Graph.h
runtime/onert/core/include/ir/OperandIndexSequence.h
runtime/onert/core/src/compiler/Compiler.cc
runtime/onert/core/src/compiler/LoweredGraph.cc
runtime/onert/core/src/exec/ExecutorBase.cc
runtime/onert/core/src/exec/ExecutorBase.h
runtime/onert/core/src/exec/LinearExecutor.cc
runtime/onert/core/src/interp/InterpExecutor.h
runtime/onert/frontend/base_loader/include/base_loader.h
runtime/onert/frontend/circle/src/circle_loader.cc
runtime/onert/frontend/tflite/src/tflite_loader.cc
tests/nnfw_api/CMakeLists.txt
tests/nnfw_api/src/NNPackages.cc
tests/nnfw_api/src/NNPackages.h
tests/nnfw_api/src/ValidationTestPipelineSession.cc
tests/nnfw_api/src/fixtures.h

- Add multiple executions to support for pipeline
- Add Input/Output Operand Name for Partial Graph IO Description
Signed-off-by: sungho22.lee <sungho22.lee@samsung.com>

[onert] Multiple Executions for Pipeline

---

compiler/luci-interpreter/src/loader/KernelBuilder.cpp
compiler/luci-interpreter/src/loader/KernelBuilder.h

This will revise KernelBuilder to use KernelBuilderHelper.

[luci-interpreter] Use KernelBuilderHelper

---

compiler/luci/export/src/CircleOperationExporter.cpp

This will extract ExportHelper as separate class from OperationExporter.

[luci] Extract ExportHelper

---

compiler/luci-interpreter/src/loader/KernelBuilder.cpp

This will sortKernelBuilder members in alphabetical order.

[luci-interpreter] Sort KernelBuilder members in order

---

compiler/luci-interpreter/src/loader/KernelBuilderHelper.h

This will introduce accessors in KernelBuilderHelper.

[luci-interpreter] Accessors in KernelBuilderHelper

---

compiler/luci/export/src/CircleOperationExporter.cpp

This will extract OpExporterLet with group ABC IR exports to reduce

[luci] Extract OpExporterLet with group ABC

---

compiler/circle-partitioner/CMakeLists.txt

This will fix configuration error for release and analysis.

[circle-partitioner] Fix configuration error

---

compiler/circle-partitioner-test/CMakeLists.txt
compiler/circle-partitioner-test/README.md
compiler/circle-partitioner-test/parts/Net_InstanceNorm_003.part
compiler/circle-partitioner-test/requires.cmake
compiler/circle-partitioner-test/test.lst

This will introduce circle-partitioner-test from circle-partitioner test separation.

[circle-partitioner-test] Introduce test for circle-partitioner

---

res/TensorFlowLiteRecipes/Net_InstanceNorm_001/test.rule
res/TensorFlowLiteRecipes/Net_InstanceNorm_002/test.rule
res/TensorFlowLiteRecipes/Net_InstanceNorm_003/test.rule

This will fix comment for Net_InstanceNorm rule files.

[res] Fix comment for Net_InstanceNorm rule files

---

compiler/luci/export/src/CircleOperationExporter.cpp

This will extract OpExporterLet with group CIRC, VIRT (circle only,
virtuals) exports to reduce class LoC violation score.

[luci] Extract OpExporterLet with group CIRC,VIRT

---

compiler/luci/logex/src/FormattedGraph.cpp

This will commonize IMPLEMENT macro and add undef.

[luci] Common IMPLEMENT macro in logex

---

infra/docker/focal/Dockerfile

This commit updates focal Dockerfile.
Related: #6978 

[docker] Update focal Dockerfile

---

compiler/locomotiv/src/Node/Pull.cpp
compiler/locomotiv/src/Node/Pull.test.cpp
compiler/locomotiv/src/Node/ReLU6.cpp

This will tidy deprecated codes in locomotiv.

[locomotiv] Tidy deprecated codes

---

runtime/onert/api/src/nnfw_api_internal.cc
tests/nnfw_api/src/ValidationTestPipelineSession.cc

- Add the pipeline test case
- Handle the exceptions for the existing api

Add the test case for pipeline

---

compiler/luci/logex/src/FormattedGraph.cpp

This will sort FormattedGraph methods of logex.

[luci] Sort FormattedGraph of logex

---

compiler/luci/logex/src/FormattedGraph.cpp

This will revise _tbl member to private for CircleNodeSummaryBuilderBase.

[luci] Revise member to private

---

compiler/record-minmax/src/RecordMinMax.cpp

This will revise log for every record in profileData method.

[record-minmax] Log for every record

---

tools/model_partition_tool/Graph.py
tools/model_partition_tool/README.md
tools/model_partition_tool/graph_analysis.py
tools/model_partition_tool/runtime_stats.py
tools/model_partition_tool/test_partition.py

Add scripts for Graph partitioning. The algorithm is a heuristic that mixes topological sorting, followed by a variant of the Fiduccia Mattheyses algorithm (see https://en.wikipedia.org/wiki/Fiduccia%E2%80%93Mattheyses_algorithm).
Note that the data for the algorithm comes from the TFlite model and a chrome trace output from running nnpackage_run.
The partitions approximate a MinMax split of execution times, such that they can be pipelined.
Signed-off-by: venkat.iyer venkat.iyer@samsung.com

[model_partition] Add scripts for runtime-driven, heuristic-based model partitioning

---

compiler/luci/pass/src/ConvertNCHWToNHWCPass.cpp
compiler/luci/pass/src/ConvertNCHWToNHWCPass.test.cpp

This supports MEAN in ConvertNCHWToNHWCPass.
---
Related to: https://github.com/Samsung/ONE/issues/7068

[luci] Support MEAN in ConvertNCHWToNHWCPass

---

compiler/luci/pass/src/FuseInstanceNormPass.cpp

This will extract InstanceNorm pattern match for version 2 to separate
method.

[luci] Extract InstNorm match for version 2

---

compiler/luci/pass/src/FuseInstanceNormPass.cpp

This will add version comment to InstNorm pattern.

[luci] Add version comment for InstNorm pattern

---

compiler/luci-interpreter/src/kernels/CMakeLists.txt
compiler/luci-interpreter/src/kernels/Square.cpp
compiler/luci-interpreter/src/kernels/Square.h
compiler/luci-interpreter/src/kernels/Square.test.cpp
compiler/luci-interpreter/src/loader/KernelBuilder.cpp

This will enable Square operator.

[luci-interpreter] Enable Square

---

compiler/luci/pass/include/luci/CircleOptimizer.h
compiler/luci/pass/include/luci/Pass/ReplaceSubWithAddPass.h
compiler/luci/pass/src/CircleOptimizer.cpp
compiler/luci/pass/src/ReplaceSubWithAddPass.cpp
compiler/luci/pass/src/ReplaceSubWithAddPass.test.cpp

Parent Issue : #7081 
Draft : #7082 
This commit introduces `ReplaceSubWithAddPass` in `luci`.

[luci] Introduce ReplaceSubWithAddPass

---

compiler/luci/pass/src/FuseInstanceNormPass.cpp

This will inteoduce FuseInstanceNorm class with apply() method that
will do actual replace sub-network with on InstanceNorm node.
- This change will apply with Version_0 pattern.

[luci] Introduce FuseInstanceNorm class

---

compiler/luci/pass/src/FuseInstanceNormPass.cpp

This will revise to use FuseInstanceNorm directly and remove
not used anymore fuse_instance_norm() method.

[luci] Use FuseInstanceNorm directly

---

res/TensorFlowLiteRecipes/Net_InstanceNorm_004/test.recipe
res/TensorFlowLiteRecipes/Net_InstanceNorm_004/test.rule

This will introduce Net_InstanceNorm_004 recipe that is like the model
from TensorFlow 1.15.3

[res] Introduce Net_InstanceNorm_004

---

compiler/luci/pass/src/FuseInstanceNormPass.cpp

This will instroduce InstanceNormPattern::match method for Version_3.

[luci] InstanceNormPattern::match for Version_3

---

compiler/luci/pass/src/FuseInstanceNormPass.cpp

This will revise FuseInstanceNormPass::run() method as extract
fuse_instance_norm() method with target CircleAdd node and
PatternVersion hint so that finding Add node and pattern matching
is separated.
- Version_Unknown is introduced as hint to let fuse_instance_norm method manage the pattern.

[luci] Extract fuse_instance_norm with Add and hint

---

compiler/luci/pass/src/FuseInstanceNormPass.cpp

This will enable fuse if InstanceNormalization pattern Version_3.

[luci] Fuse InstanceNorm pattern Version_3

---

compiler/luci-interpreter/src/kernels/InstanceNorm.cpp
compiler/luci-interpreter/src/kernels/InstanceNorm.test.cpp

This supports a single gamma/beta in InstanceNorm.

[luci-interpreter] Support single gamma/beta in InstanceNorm

---

compiler/luci/pass/src/FuseInstanceNormPass.cpp
compiler/luci/pass/src/FuseInstanceNormPass.test.cpp

This will deprecate fuse InstanceNormalization pattern Version_1.

[luci] Deprecate FuseInstNorm pattern V1

---

compiler/luci/pass/src/FuseInstanceNormPass.cpp

This will add fuse InstanceNormalization Version_4 comment.

[luci] Add FuseInstNorm version 4 comment

---

res/TensorFlowLiteRecipes/Net_InstanceNorm_005/test.recipe
res/TensorFlowLiteRecipes/Net_InstanceNorm_005/test.rule

This will introduce Net_InstanceNorm_005 recipe to testing pattern
Version_4 of fuse InstanceNorm.

[res] Introduce Net_InstanceNorm_005 recipe

---

compiler/luci/pass/src/FuseInstanceNormPass.cpp

This will enable fuse InstanceNormalization for pattern Version_4.

[luci] Enable fuse InstNorm for pattern Version_4

---

compiler/luci/pass/src/FuseInstanceNormPass.cpp

This will revise Version_0 to Version_1 to make numberings smooth.

[luci] Revise fuse InstNorm pass Version_0 to 1

---

compiler/one-cmds/one-prepare-venv

This will enable to provide additional pip install options.

[one-cmds] Enable additional pip install options

---

runtime/onert/api/include/nnfw_experimental.h
runtime/onert/api/src/nnfw_api.cc
runtime/onert/api/src/nnfw_api_internal.cc
runtime/onert/api/src/nnfw_api_internal.h
runtime/onert/core/include/exec/Execution.h
runtime/onert/core/include/exec/IODescription.h
runtime/onert/core/src/exec/Execution.cc
tests/nnfw_api/src/ValidationTestPipelineSession.cc

Add multisession structure and async apis to support pipelining of multi execution
ONE-DCO-1.0-Signed-off-by: hansolu <hansolu.lee@samsung.com>

[onert] Async apis for pipelining of Multiexecution

---

compiler/one-cmds/one-prepare-venv

This will remove comment about old version of onnx-tf issue.

[one-cmds] Remove comment about old version of onnx-tf

---

compiler/circle-partitioner/README.md

This will revise readme with descriptions about how circle-partitioner works.
ONE-DCO-1.0-ONE-DCO-1.0-ONE-DCO-1.0-ONE-DCO-1.0-ONE-DCO-1.0-Signed-off-by: SaeHie Park <saehie.park@gmail.com>

[circle-partitioner] Add readme descriptions

---

compiler/luci/pass/src/FuseInstanceNormPass.cpp

This will introduce post_fusion method in FuseInstanceNormPass to
provide post processing after InstanceNormalization fusion.

[luci] Introduce FuseInstNorm post_fusion

---

compiler/luci/pass/src/FuseInstanceNormPass.cpp

This will revise FuseInstanceNorm apply method to void type.

[luci] Revise return void for apply of FuseInstanceNorm

---

res/TensorFlowLiteRecipes/Net_InstanceNorm_006/test.recipe
res/TensorFlowLiteRecipes/Net_InstanceNorm_006/test.rule

This will introduce Net_InstanceNorm_006 recipe that has scala gamma and beta.

[res] Introduce Net_InstanceNorm_006

---

compiler/luci/pass/src/FuseInstanceNormPass.cpp

This will enable match beta, gamma channel for FuseInstanceNorm as post
process.

[luci] Add match beta, gamma channel for FuseInstanceNorm

---

res/TensorFlowLiteRecipes/Part_Add_Sub_001/test.recipe

This will introduce Part_Add_Sub_001 that has long and special
characters in node name.

[res] Introduce Part_Add_Sub_001

---

compiler/luci/partition/include/luci/Partition.h

This will revise PartitionTable to have type for comply and add byopnames;

[luci] Revise PartitionTable

---

compiler/record-minmax/include/RecordMinMax.h
compiler/record-minmax/src/RecordMinMax.cpp

This supports record-minmax to accept raw data.
---
Related to: #7132
Draft PR: #7158

[record-minmax] Support calibration using raw data

---

infra/packaging/preset/20210706
infra/packaging/preset/20210706_windows
infra/packaging/res/tf2nnpkg.20210706

This will introduce preset 20210707 with new pepper-csv2vec module.

[infra] Introduce preset 20210706

---

compiler/luci/partition/include/luci/PartitionDump.h
compiler/luci/partition/src/PartitionDump.cpp

This will add PartitionTable class dump into luci::partition.

[luci] Add PartitionTable dump

---

runtime/onert/backend/gpu_cl/open_cl/ClCommandQueue.cc
runtime/onert/backend/gpu_cl/open_cl/ClKernel.h
runtime/onert/backend/gpu_cl/open_cl/GpuObject.h
runtime/onert/backend/gpu_cl/open_cl/InferenceContext.h

Initialize uninitialized variables.
Assert if the value to divide by is zero.

[onert] Resolve svace for UNINIT and DIVIDE_BY_ZERO

---

compiler/luci/partition/src/PartitionDump.cpp

This will enable dump of PartitionTable byopnames items.

[luci] Dump PartitionTable byopnames

---

infra/packaging/build

This will update default PRESET to 20210706.

[infra] Update default PRESET

---

compiler/circle-partitioner/src/PartitionRead.cpp

This will revise to read section by comply and enable to set group by opname.

[circle-partitioner] Read comply and enable group by name

---

compiler/luci/partition/src/PartitionPGroups.cpp

This will revise produce_pgroups to set group by comply type given:
OPCODE or OPNAME.

[luci] Revise produce_pgroups with comply

---

compiler/luci/service/include/luci/Service/Validate.h
compiler/luci/service/src/Validate.cpp

This will introduce validate method for Module.

[luci] Introduce Module validate method

---

compiler/circle-partitioner/src/CirclePartitioner.cpp

This will revise CirclePartitioner to use methods in luci.

[circle-partitioner] Use methods from luci

---

runtime/onert/backend/gpu_cl/open_cl/Arguments.cc
runtime/onert/backend/gpu_cl/open_cl/MemoryManagement.cc
runtime/onert/backend/gpu_cl/open_cl/TensorType.cc

Removed unreachable points in the flow.

[onert] Resolve svace for UNREACHABLE

---

compiler/luci/partition/CMakeLists.txt
compiler/luci/partition/include/luci/PartitionValidate.h
compiler/luci/partition/src/PartitionValidate.cpp
compiler/luci/requires.cmake

This will introduce validate method for PartitionTable using
pepper-csv2vec module.

[luci] Introduce validate for PartitionTable

---

compiler/circle-partitioner/src/CirclePartitioner.cpp

This will revise to use PartitionTable validate from luci and remove
local implementation.

[circle-partitioner] Revise PartitionTable validate

---

compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp

This quantizes fused Tanh with special values.

[circle-quantizer] Quantize fused Tanh using pre-determined values.

---

runtime/onert/backend/gpu_cl/Config.cc
runtime/onert/backend/gpu_cl/Config.h
runtime/onert/backend/gpu_cl/open_cl/GpuObject.h
runtime/onert/backend/gpu_cl/open_cl/OpenclWrapper.cc
runtime/onert/backend/gpu_cl/open_cl/OpenclWrapper.h
runtime/onert/backend/gpu_cl/open_cl/Util.cc
runtime/onert/backend/gpu_cl/open_cl/Util.h

Initialize uninitialized variables.
Implemented UnloadOpenCL.

[onert] Resolve svace for UNINIT and RESOURCE_LEAK 

---

tools/release_tool/onert_version.sh

This commit removes commit date on nightly build tar file name.

[tools] Remove commit date on nightly build tar file name

---

compiler/luci/pass/src/PropagateQuantParamPass.cpp
compiler/luci/pass/src/PropagateQuantParamPass.test.cpp

This propagates quantparam in a forward direction.

[circle-quantizer] Propagate quantparam forward direction

---

compiler/common-artifacts/src/TestDataGenerator.cpp

This will enable to support bool type for random data.

[common-artifacts] Support bool for random data

---

res/TensorFlowLiteRecipes/Net_If_Add_Sub_000/test.recipe

This will introduce Net_If_Add_Sub_000 recipe for partitioning IF node.

[res] Introduce Net_If_Add_Sub_000

---

compiler/luci-interpreter/src/loader/GraphLoader.cpp

This will enable loading BOOL tensor type.

[luci-interpreter] Support load BOOL tensor type

---

res/TensorFlowPythonExamples/examples/cond_1/__init__.py

This will introduce TF python example of cond inside cond.

[res] TF py examples of cond_1

---

compiler/common-artifacts/CMakeLists.txt

This will revise cmake message for input.h5/expcedted.h5 generation.

[common-artifacts] Revise input/expected message

---

compiler/luci/partition/src/PartitionIR.cpp
compiler/luci/partition/src/PartitionIR.h

This will introduce GroupKey for group key string instead of std::string.

[luci] Use GroupKey for std::string

---

compiler/luci/partition/src/ConnectNode.test.h

This will introduce NodeIsOsGraphletT and TestIsOsGraph to support
arbitrary number of inputs and outputs.

[luci] Introduce TestIsOsGraph in partition

---

infra/debian/compiler/postinst

This commit revies postinst script.
Related: #7230 

[infra] Revise postinst

---

compiler/luci/partition/src/ConnectNode.test.h

This will revise TestIsOGraph::init to use variable g for same code.

[luci] Use variable for same code

---

compiler/luci/service/src/CircleCloneNode.h
compiler/luci/service/src/Nodes/CircleIf.cpp
compiler/luci/service/src/Nodes/CircleIf.test.cpp
compiler/luci/service/src/Nodes/CircleIfOut.cpp
compiler/luci/service/src/Nodes/CircleIfOut.test.cpp

This will enable clone for CircleIf and CircleIfOut nodes.

[luci] Clone for CircleIf and CircleIfOut

---

compiler/luci/service/src/Validate.cpp

This will add graph dump log to validate for Module method to help debugging.

[luci/service] Add graph dump to validate Module

---

res/TensorFlowLiteRecipes/Part_If_Add_Sub_001/test.recipe

This will introduce Part_If_Add_Sub_001 recipe that has IF inside IF node.

[res] Introduce Part_If_Add_Sub_001

---

compiler/luci/partition/src/ConnectNode.h

This will introduce const_iterator of CloneContext.
- for better understading of used codes.

[luci/partition] Introduce const_iterator of CloneContext

---

compiler/luci/partition/src/PartitionPModules.cpp

This will introduce dummy clone_ifnode_subgraphs method that will clone
subgraphs of If node and revise build_graph method to call it.

[luci/partition] Introduce clone_ifnode_subgraphs

---

compiler/luci/partition/src/ConnectNode.h
compiler/luci/partition/src/Nodes/CircleIf.cpp
compiler/luci/partition/src/Nodes/CircleIf.test.cpp

This will enable connect of cloned CircleIf node.

[luci/partition] Enable connect of CircleIf

---

compiler/luci/partition/src/ConnectNode.h
compiler/luci/partition/src/Nodes/CircleIfOut.cpp
compiler/luci/partition/src/Nodes/CircleIfOut.test.cpp

This will enable connect of cloned CircleIfOut node.

[luci/partition] Enable connect of CircleIfOut

---

compiler/luci/pass/include/luci/Pass/SubstituteStridedSliceToReshapePass.h
compiler/luci/pass/src/SubstituteStridedSliceToReshapePass.cpp
compiler/luci/pass/src/SubstituteStridedSliceToReshapePass.test.cpp

This adds a pass to Convert StridedSlice to Reshape when
StridedSlice meets a certain condition.
for #7232
draft: #7235

[luci] Add Pass to Convert StridedSlice to Reshape

---

compiler/luci/partition/src/PartitionPModules.cpp

This will enable recursive clone of subgraphs for CircleIf then and else.

[luci/partition] Enable recursive clone of subgraphs

---

compiler/circle-part-value-test/parts/Part_If_Add_Sub_000.001.part
compiler/circle-part-value-test/parts/Part_If_Add_Sub_001.001.part
compiler/circle-part-value-test/test.lst

This will enable test for If node with subgraphs and another If inside subgraph.

[circle-part-value-test] Add test for If

---

res/TensorFlowLiteRecipes/StridedSlice_003/test.recipe
res/TensorFlowLiteRecipes/StridedSlice_003/test.rule

This adds StridedSlice_003, where StridedSlice will be replaced
to Reshape with SubstituteStridedSliceToReshape pass.
issue #7232
draft #7235

[TensorflowLiteRecipes] Add StridedSlice_003

---

compiler/circle2circle/src/Circle2Circle.cpp

This adds "--substitute_strided_slice_to_reshape" option to circle2circle.
issue #7232
draft #7235

[Circle2Circle] Add "--substitute_strided_slice_to_reshape" Option

---

compiler/circle2circle-dredd-recipe-test/test.lst

This adds StridedSlice_003 into circle2circle-dredd-recipe-test.
issue #7232
draft #7235

[circle2circle-dredd-recipe-test] Add StridedSlice_003

---

compiler/luci/pass/src/QuantizedModelVerifier.cpp

This improves error msg in QuantizedModelVerifier.

[luci] Improve error msg of QuantizedModelVerifier

---

compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
compiler/luci/pass/src/QuantizedModelVerifier.test.cpp
compiler/luci/pass/src/VerifyQuantizedNodeChannelWiseGranularity.h
compiler/luci/pass/src/VerifyQuantizedNodeLayerWiseGranularity.h
compiler/luci/pass/src/VerifyQuantizedNodeS16Type.h
compiler/luci/pass/src/VerifyQuantizedNodeU8Type.h

This makes QuantizeWithMinMaxPass process UNPACK op.

[luci] Add UNPACK in QuantizeWithMinMaxPass

---

compiler/one-cmds/how-to-use-one-commands.txt
compiler/one-cmds/utils.py

This removed trailing spaces in two files of one-build.
For https://github.com/Samsung/ONE/pull/7291#discussion_r674461529

[one-build] Remove Trailing Spaces

---

compiler/one-cmds/how-to-use-one-commands.txt
compiler/one-cmds/utils.py

This adds a new option, `substitute_strided_slice_to_reshape`
into one-build.
issue #7232
draft #7235

[one-build] Add an option, "substitute_strided_slice_to_reshape"

---

compiler/luci-interpreter/src/kernels/CMakeLists.txt
compiler/luci-interpreter/src/kernels/Cast.cpp
compiler/luci-interpreter/src/kernels/Cast.h
compiler/luci-interpreter/src/kernels/Cast.test.cpp

This commit adds kernel for Cast with corresponding unit tests.
--------------------
For: #7261
Draft: #7262

[luci-interpreter] Add Cast kernel

---

compiler/one-cmds/CMakeLists.txt
compiler/one-cmds/onecc

This code is copy from one-build.
Change the driver name from one-build to onecc
Add onecc to CMakeLists
Draft PR: #7303

[onecc] Add onecc driver

---

compiler/luci/pass/src/ConvertNCHWToNHWCPass.cpp
compiler/luci/pass/src/ConvertNCHWToNHWCPass.test.cpp

This will revise NCHWToNHWCPass to support scalar beta to CircleAdd node.

[luci] Revise NCHWToNHWCPass Add to support scalar beta

---

compiler/luci/pass/src/ConvertNCHWToNHWCPass.cpp
compiler/luci/pass/src/ConvertNCHWToNHWCPass.test.cpp

This will revise to support Rsqrt node in NCHWToNHWCPass.

[luci] Support Rsqrt in NCHWToNHWCPass

---

compiler/luci/pass/src/ConvertNCHWToNHWCPass.cpp

This adds annotation for NHWC operators.
The annotated operators are not converted.
---
Related to: #7314

[luci] Add annotation for NHWC operators.

---

compiler/luci/pass/src/VerifyQuantizedNodeChannelWiseGranularity.h
compiler/luci/pass/src/VerifyQuantizedNodeLayerWiseGranularity.h

This supports optional bias in quantizer.

[circle-quantizer] Support optional bias in quantizer
