Samsung/ONE

compiler/luci/pass/src/QuantizedModelVerifier.test.cpp
This commit adds a helper macro to a SimpleTestGraph with wrong type node.
Unlike the existing function TEST_WITH_WRONG_TYPE, this macro enables users to specify
the node to be tested.
----
For #6652
=> [luci] Add a helper macro to QuantizedModelVerifier test

compiler/luci/pass/src/QuantizedModelVerifier.test.cpp
This commit renames a test which targets an input node, not a dimension node.
Therefore the name is changed from 'ArgMax_wrong_dimension_type_NEG' to 'ArgMax_wrong_input_type_NEG'.
----
From #6652
=> [luci] Rename Argmax QuantizedModelVerifier Test

infra/scripts/build_android_runtime_release.sh
This commit removes checking pre-built arm compute library is installed.
Android build doesn't require pre-built arm compute library any more.
=> [infra] Remove deprecated acl checking on android build test

compiler/luci/pass/src/QuantizedModelVerifier.test.cpp, compiler/luci/pass/src/VerifyQuantizedNodeChannelWiseGranularity.h, compiler/luci/pass/src/VerifyQuantizedNodeLayerWiseGranularity.h, compiler/luci/pass/src/VerifyQuantizedNodeS16Type.h, compiler/luci/pass/src/VerifyQuantizedNodeU8Type.h
This commit supports quantization and its unittest of ResizeNearestNeighbor operation.
=> [luci] Support quantization of ResizeNearestNeighbor

compiler/luci-interpreter/src/kernels/CMakeLists.txt, compiler/luci-interpreter/src/kernels/PadV2.cpp, compiler/luci-interpreter/src/kernels/PadV2.h, compiler/luci-interpreter/src/kernels/PadV2.test.cpp, compiler/luci-interpreter/src/loader/KernelBuilder.cpp, compiler/luci-interpreter/src/loader/KernelBuilder.h, compiler/luci-interpreter/src/loader/KernelBuilder.test.cpp
This commit introduces PadV2 kernel to enable evaluation of CirclePadV2.
For #6661 
=> [luci-interpreter] Introduce PadV2 kernel

compiler/luci/pass/src/QuantizedModelVerifier.test.cpp
This commit adds an interface for getting argmax SimpleTestGraph dimension node
----
Originated from #6657
=> [luci] Add an ArgMax SimpleTestGraph dimension getter

compiler/luci/partition/src/ConnectNode.h, compiler/luci/partition/src/Nodes/CircleAbs.cpp, compiler/luci/partition/src/Nodes/CircleAbs.test.cpp, compiler/luci/partition/src/Nodes/CircleAddN.cpp, compiler/luci/partition/src/Nodes/CircleAddN.test.cpp
This will enable connection of cloned nodes for CircleAbs and
CircleAddN.
=> [luci] Clone connect for Abs, AddN

compiler/luci/partition/src/ConnectNode.h, compiler/luci/partition/src/Nodes/CircleConv2D.cpp, compiler/luci/partition/src/Nodes/CircleConv2D.test.cpp, compiler/luci/partition/src/Nodes/CircleCos.cpp, compiler/luci/partition/src/Nodes/CircleCos.test.cpp, compiler/luci/partition/src/Nodes/CircleCustom.cpp, compiler/luci/partition/src/Nodes/CircleCustom.test.cpp
This will enable connection of cloned nodes for CircleConv2D, CircleCos
and CircleCustom.
=> [luci] Clone connect for Conv2D and others

compiler/luci/partition/src/ConnectNode.h, compiler/luci/partition/src/Nodes/CircleElu.cpp, compiler/luci/partition/src/Nodes/CircleElu.test.cpp, compiler/luci/partition/src/Nodes/CircleEqual.cpp, compiler/luci/partition/src/Nodes/CircleEqual.test.cpp, compiler/luci/partition/src/Nodes/CircleExp.cpp, compiler/luci/partition/src/Nodes/CircleExp.test.cpp
This will enable connection of cloned nodes for CircleElu, CircleEqual
and CircleExp.
=> [luci] Clone connect for Elu and others

compiler/luci/partition/src/ConnectNode.h, compiler/luci/partition/src/Nodes/CircleL2Normalize.cpp, compiler/luci/partition/src/Nodes/CircleL2Normalize.test.cpp, compiler/luci/partition/src/Nodes/CircleL2Pool2D.cpp, compiler/luci/partition/src/Nodes/CircleL2Pool2D.test.cpp, compiler/luci/partition/src/Nodes/CircleLeakyRelu.cpp, compiler/luci/partition/src/Nodes/CircleLeakyRelu.test.cpp
This will enable connection of cloned nodes for CircleL2Normalize,
CircleL2Pool2D and CircleLeakyRelu.
=> [luci] Clone connect for L2Normalize and others

compiler/luci/partition/src/ConnectNode.h, compiler/luci/partition/src/Nodes/CircleMaxPool2D.cpp, compiler/luci/partition/src/Nodes/CircleMaxPool2D.test.cpp, compiler/luci/partition/src/Nodes/CircleMaximum.cpp, compiler/luci/partition/src/Nodes/CircleMaximum.test.cpp, compiler/luci/partition/src/Nodes/CircleMinimum.cpp, compiler/luci/partition/src/Nodes/CircleMinimum.test.cpp, compiler/luci/partition/src/Nodes/CircleMirrorPad.cpp, compiler/luci/partition/src/Nodes/CircleMirrorPad.test.cpp
This will enable connection of cloned nodes for CircleMaxPool2D,
CircleMaximum, CircleMinimum and CircleMirrorPad.
=> [luci] Clone connect for MaxPool2D and others

compiler/luci/partition/src/ConnectNode.h, compiler/luci/partition/src/Nodes/CirclePRelu.cpp, compiler/luci/partition/src/Nodes/CirclePRelu.test.cpp, compiler/luci/partition/src/Nodes/CircleRange.cpp, compiler/luci/partition/src/Nodes/CircleRange.test.cpp, compiler/luci/partition/src/Nodes/CircleRank.cpp, compiler/luci/partition/src/Nodes/CircleRank.test.cpp
This will enable connection of cloned nodes for CirclePRelu, CircleRange
and CircleRank.
=> [luci] Clone connect for PRelu and others

compiler/luci/partition/src/ConnectNode.h, compiler/luci/partition/src/Nodes/CircleRelu.cpp, compiler/luci/partition/src/Nodes/CircleRelu.test.cpp, compiler/luci/partition/src/Nodes/CircleRelu6.cpp, compiler/luci/partition/src/Nodes/CircleRelu6.test.cpp, compiler/luci/partition/src/Nodes/CircleReluN1To1.cpp, compiler/luci/partition/src/Nodes/CircleReluN1To1.test.cpp
This will enable connection of cloned nodes for CircleRelu, CircleRelu6
and CircleReluN1To1.
=> [luci] Clone connect for Relu and others

compiler/luci/partition/src/ConnectNode.h, compiler/luci/partition/src/Nodes/CircleScatterNd.cpp, compiler/luci/partition/src/Nodes/CircleScatterNd.test.cpp, compiler/luci/partition/src/Nodes/CircleSegmentSum.cpp, compiler/luci/partition/src/Nodes/CircleSegmentSum.test.cpp
This will enable connection of cloned nodes for CircleScatterNd and
CircleSegmentSum.
=> [luci] Clone connect for ScatterNd and other

compiler/luci/partition/src/ConnectNode.h, compiler/luci/partition/src/Nodes/CircleSplit.cpp, compiler/luci/partition/src/Nodes/CircleSplit.test.cpp, compiler/luci/partition/src/Nodes/CircleSplitV.cpp, compiler/luci/partition/src/Nodes/CircleSplitV.test.cpp
This will enable connection of cloned nodes for CircleSplit and
CircleSplitV.
=> [luci] Clone connect for Split and other

compiler/luci/pass/src/QuantizedModelVerifier.test.cpp
Add a negative test which sets wrong dtype on dimension node,
which has been temporarily removed by #6637.
-----
From #6652
=> [luci] Revive an ArgMax QuantizedModelVerifier test of wrong type dim

compiler/luci/partition/src/ConnectNode.h, compiler/luci/partition/src/Nodes/CircleSum.cpp, compiler/luci/partition/src/Nodes/CircleSum.test.cpp, compiler/luci/partition/src/Nodes/CircleTanh.cpp, compiler/luci/partition/src/Nodes/CircleTanh.test.cpp, compiler/luci/partition/src/Nodes/CircleTile.cpp, compiler/luci/partition/src/Nodes/CircleTile.test.cpp
This will enable connection of cloned nodes for CircleSum, CircleTanh
and CirleTile.
=> [luci] Clone connect for Sum and others

compiler/luci/partition/src/ConnectNode.h, compiler/luci/partition/src/Nodes/CircleUnpack.cpp, compiler/luci/partition/src/Nodes/CircleUnpack.test.cpp, compiler/luci/partition/src/Nodes/CircleWhere.cpp, compiler/luci/partition/src/Nodes/CircleWhere.test.cpp, compiler/luci/partition/src/Nodes/CircleZerosLike.cpp, compiler/luci/partition/src/Nodes/CircleZerosLike.test.cpp
This will enable connection of cloned nodes for CircleUnpack,
CircleWhere and CircleZerosLike.
=> [luci] Clone connect for Unpack and others

compiler/luci/partition/src/ConnectNode.h, compiler/luci/partition/src/Nodes/CircleBCQFullyConnected.cpp, compiler/luci/partition/src/Nodes/CircleBCQFullyConnected.test.cpp, compiler/luci/partition/src/Nodes/CircleBCQGather.cpp, compiler/luci/partition/src/Nodes/CircleBCQGather.test.cpp, compiler/luci/partition/src/Nodes/CircleInstanceNorm.cpp, compiler/luci/partition/src/Nodes/CircleInstanceNorm.test.cpp
This will enable connection of cloned nodes for CircleBCQFullyConnected,
CircleBCQGather and CircleInstanceNorm.
=> [luci] Clone connect for BCQFullyConnected and others

compiler/luci/partition/src/ConnectNode.h, compiler/luci/partition/src/Nodes/CircleArgMax.cpp, compiler/luci/partition/src/Nodes/CircleArgMax.test.cpp, compiler/luci/partition/src/Nodes/CircleArgMin.cpp, compiler/luci/partition/src/Nodes/CircleArgMin.test.cpp
This will enable connection of cloned nodes for CircleArgMax and
CircleArgMin.
=> [luci] Clone connect for ArgMax, ArgMin

compiler/luci/partition/src/ConnectNode.h, compiler/luci/partition/src/Nodes/CircleCast.cpp, compiler/luci/partition/src/Nodes/CircleCast.test.cpp, compiler/luci/partition/src/Nodes/CircleCeil.cpp, compiler/luci/partition/src/Nodes/CircleCeil.test.cpp, compiler/luci/partition/src/Nodes/CircleConcatenation.cpp, compiler/luci/partition/src/Nodes/CircleConcatenation.test.cpp
This will enable connection of cloned nodes for CircleCast, CiecleCeil
and CircleConcatenation.
=> [luci] Clone connect for Cast and others

compiler/luci/partition/src/ConnectNode.h, compiler/luci/partition/src/Nodes/CircleDepthToSpace.cpp, compiler/luci/partition/src/Nodes/CircleDepthToSpace.test.cpp, compiler/luci/partition/src/Nodes/CircleDepthwiseConv2D.cpp, compiler/luci/partition/src/Nodes/CircleDepthwiseConv2D.test.cpp, compiler/luci/partition/src/Nodes/CircleDequantize.cpp, compiler/luci/partition/src/Nodes/CircleDequantize.test.cpp
This will enable connection of cloned nodes for CircleDepthToSpace,
CircleDepthwiseConv2D and CircleDequantize.
=> [luci] Clone connect for DepthToSpace and others

compiler/luci/partition/src/ConnectNode.h, compiler/luci/partition/src/Nodes/CircleExpandDims.cpp, compiler/luci/partition/src/Nodes/CircleExpandDims.test.cpp, compiler/luci/partition/src/Nodes/CircleFakeQuant.cpp, compiler/luci/partition/src/Nodes/CircleFakeQuant.test.cpp, compiler/luci/partition/src/Nodes/CircleFill.cpp, compiler/luci/partition/src/Nodes/CircleFill.test.cpp
This will enable connection of cloned nodes for CircleExpandDims,
CircleFakeQuant and CircleFill.
=> [luci] Clone connect for ExpandDims and others

compiler/luci/partition/src/ConnectNode.h, compiler/luci/partition/src/Nodes/CircleGather.cpp, compiler/luci/partition/src/Nodes/CircleGather.test.cpp, compiler/luci/partition/src/Nodes/CircleGatherNd.cpp, compiler/luci/partition/src/Nodes/CircleGatherNd.test.cpp
This will enable connection of cloned nodes for CircleGather and
CircleGatherNd.
=> [luci] Clone connect for Gather and GatherNd

compiler/luci/partition/src/ConnectNode.h, compiler/luci/partition/src/Nodes/CircleReduceAny.cpp, compiler/luci/partition/src/Nodes/CircleReduceAny.test.cpp, compiler/luci/partition/src/Nodes/CircleReduceMax.cpp, compiler/luci/partition/src/Nodes/CircleReduceMax.test.cpp, compiler/luci/partition/src/Nodes/CircleReduceMin.cpp, compiler/luci/partition/src/Nodes/CircleReduceMin.test.cpp, compiler/luci/partition/src/Nodes/CircleReduceProd.cpp, compiler/luci/partition/src/Nodes/CircleReduceProd.test.cpp
This will enable connection of cloned nodes for CircleReduceAny, CircleReduceMax,
CircleReduceMin and CircleReduceProd.
=> [luci] Clone connect for ReduceAny and others

compiler/luci/partition/src/ConnectNode.h, compiler/luci/partition/src/Nodes/CircleLogSoftmax.cpp, compiler/luci/partition/src/Nodes/CircleLogSoftmax.test.cpp, compiler/luci/partition/src/Nodes/CircleMatrixDiag.cpp, compiler/luci/partition/src/Nodes/CircleMatrixDiag.test.cpp, compiler/luci/partition/src/Nodes/CircleMatrixSetDiag.cpp, compiler/luci/partition/src/Nodes/CircleMatrixSetDiag.test.cpp
This will enable connection of cloned nodes for CircleLogSoftmax,
CircleMatrixDiag and CircleMatrixSetDiag.
=> [luci] Clone connect for LogSoftmax and others

compiler/luci/partition/src/ConnectNode.h, compiler/luci/partition/src/Nodes/CirclePad.cpp, compiler/luci/partition/src/Nodes/CirclePad.test.cpp, compiler/luci/partition/src/Nodes/CirclePadV2.cpp, compiler/luci/partition/src/Nodes/CirclePadV2.test.cpp
This will enable connection of cloned nodes for CirclePad and
CirclePadV2.
=> [luci] Clone connect for Pad and PadV2

compiler/luci/partition/src/ConnectNode.h, compiler/luci/partition/src/Nodes/CircleAveragePool2D.cpp, compiler/luci/partition/src/Nodes/CircleAveragePool2D.test.cpp, compiler/luci/partition/src/Nodes/CircleBatchMatMul.cpp, compiler/luci/partition/src/Nodes/CircleBatchMatMul.test.cpp, compiler/luci/partition/src/Nodes/CircleBatchToSpaceND.cpp, compiler/luci/partition/src/Nodes/CircleBatchToSpaceND.test.cpp
This will enable connection of cloned nodes for CircleAveragePool2D,
CircleBatchMatMul and CircleBatchToSpaceND.
=> [luci] Clone connect for AveragePool2D and others

compiler/luci/partition/src/ConnectNode.h, compiler/luci/partition/src/Nodes/CircleFloor.cpp, compiler/luci/partition/src/Nodes/CircleFloor.test.cpp, compiler/luci/partition/src/Nodes/CircleFloorDiv.cpp, compiler/luci/partition/src/Nodes/CircleFloorDiv.test.cpp, compiler/luci/partition/src/Nodes/CircleFloorMod.cpp, compiler/luci/partition/src/Nodes/CircleFloorMod.test.cpp
This will enable connection of cloned nodes for CircleFloor,
CircleFloorDiv and CircleFloorMod.
=> [luci] Clone connect for Floor and others

compiler/luci/partition/src/ConnectNode.h, compiler/luci/partition/src/Nodes/CircleGreater.cpp, compiler/luci/partition/src/Nodes/CircleGreater.test.cpp, compiler/luci/partition/src/Nodes/CircleGreaterEqual.cpp, compiler/luci/partition/src/Nodes/CircleGreaterEqual.test.cpp
This will enable connection of cloned nodes for CircleGreater and
CircleGreaterEqual.
=> [luci] Clone connect for Greater and GreaterEqual

compiler/luci/partition/src/ConnectNode.h, compiler/luci/partition/src/Nodes/CircleLogicalAnd.cpp, compiler/luci/partition/src/Nodes/CircleLogicalAnd.test.cpp, compiler/luci/partition/src/Nodes/CircleLogicalNot.cpp, compiler/luci/partition/src/Nodes/CircleLogicalNot.test.cpp, compiler/luci/partition/src/Nodes/CircleLogicalOr.cpp, compiler/luci/partition/src/Nodes/CircleLogicalOr.test.cpp
This will enable connection of cloned nodes for CircleLogicalAnd,
CircleLogicalNot and CircleLogicalOr.
=> [luci] Clone connect for LogicalAnd and others

compiler/luci/partition/src/ConnectNode.h, compiler/luci/partition/src/Nodes/CircleReverseSequence.cpp, compiler/luci/partition/src/Nodes/CircleReverseSequence.test.cpp, compiler/luci/partition/src/Nodes/CircleReverseV2.cpp, compiler/luci/partition/src/Nodes/CircleReverseV2.test.cpp, compiler/luci/partition/src/Nodes/CircleRound.cpp, compiler/luci/partition/src/Nodes/CircleRound.test.cpp
This will enable connection of cloned nodes for CircleReverseSequence,
CircleReverseV2 and CircleRound.
=> [luci] Clone connect for ReverseSequence and others

compiler/luci/partition/src/ConnectNode.h, compiler/luci/partition/src/Nodes/CircleSelect.cpp, compiler/luci/partition/src/Nodes/CircleSelect.test.cpp, compiler/luci/partition/src/Nodes/CircleSelectV2.cpp, compiler/luci/partition/src/Nodes/CircleSelectV2.test.cpp, compiler/luci/partition/src/Nodes/CircleShape.cpp, compiler/luci/partition/src/Nodes/CircleShape.test.cpp
This will enable connection of cloned nodes for CircleSelect,
CircleSelectV2 and CircleShape.
=> [luci] Clone connect for Select and others

compiler/luci/partition/src/ConnectNode.h, compiler/luci/partition/src/Nodes/CircleSpaceToBatchND.cpp, compiler/luci/partition/src/Nodes/CircleSpaceToBatchND.test.cpp, compiler/luci/partition/src/Nodes/CircleSpaceToDepth.cpp, compiler/luci/partition/src/Nodes/CircleSpaceToDepth.test.cpp, compiler/luci/partition/src/Nodes/CircleSparseToDense.cpp, compiler/luci/partition/src/Nodes/CircleSparseToDense.test.cpp
This will enable connection of cloned nodes for CircleSpaceToBatchND,
CircleSpaceToDepth and CircleSparseToDense.
=> [luci] Clone connect for SpaceToBatchND and others

compiler/luci/partition/src/ConnectNode.h, compiler/luci/partition/src/Nodes/CircleSquare.cpp, compiler/luci/partition/src/Nodes/CircleSquare.test.cpp, compiler/luci/partition/src/Nodes/CircleSqueeze.cpp, compiler/luci/partition/src/Nodes/CircleSqueeze.test.cpp, compiler/luci/partition/src/Nodes/CircleStridedSlice.cpp, compiler/luci/partition/src/Nodes/CircleStridedSlice.test.cpp
This will enable connection of cloned nodes for CircleSquare,
CircleSqueeze and CircleStridedSlice.
=> [luci] Clone connect for Square and others

compiler/luci/partition/src/ConnectNode.h, compiler/luci/partition/src/Nodes/CircleTopKV2.cpp, compiler/luci/partition/src/Nodes/CircleTopKV2.test.cpp, compiler/luci/partition/src/Nodes/CircleTranspose.cpp, compiler/luci/partition/src/Nodes/CircleTranspose.test.cpp, compiler/luci/partition/src/Nodes/CircleTransposeConv.cpp, compiler/luci/partition/src/Nodes/CircleTransposeConv.test.cpp
This will enable connection of cloned nodes for CircleTopKV2,
CircleTranspose and CircleTransposeConv.
=> [luci] Clone connect for TopKV2 and others

compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp, compiler/luci/pass/src/QuantizedModelVerifier.test.cpp, compiler/luci/pass/src/VerifyQuantizedNodeChannelWiseGranularity.h, compiler/luci/pass/src/VerifyQuantizedNodeLayerWiseGranularity.h, compiler/luci/pass/src/VerifyQuantizedNodeS16Type.h, compiler/luci/pass/src/VerifyQuantizedNodeU8Type.h
This supports quantization of LocalResponseNormalization Op.
---
Related to: https://github.com/Samsung/ONE/issues/6704
=> [luci] Support quantization of LocalResponseNormalization

compiler/luci/partition/src/ConnectNode.h, compiler/luci/partition/src/Nodes/CircleSplitOut.cpp, compiler/luci/partition/src/Nodes/CircleSplitOut.test.cpp, compiler/luci/partition/src/Nodes/CircleSplitVOut.cpp, compiler/luci/partition/src/Nodes/CircleSplitVOut.test.cpp
This will enable connection of cloned nodes for CircleSplitOut and
CircleSplitVOut.
=> [luci] Clone connect for SplitOut and SplitVOut

compiler/luci/partition/src/ConnectNode.h, compiler/luci/partition/src/Nodes/CircleLocalResponseNormalization.cpp, compiler/luci/partition/src/Nodes/CircleLocalResponseNormalization.test.cpp, compiler/luci/partition/src/Nodes/CircleLog.cpp, compiler/luci/partition/src/Nodes/CircleLog.test.cpp, compiler/luci/partition/src/Nodes/CircleLogistic.cpp, compiler/luci/partition/src/Nodes/CircleLogistic.test.cpp
This will enable connection of cloned ndoes for
CircleLocalResponseNormalization, CircleLog and CircleLogistic.
=> [luci] Clone connect for Log and others

compiler/luci/partition/src/ConnectNode.h, compiler/luci/partition/src/Nodes/CircleNotEqual.cpp, compiler/luci/partition/src/Nodes/CircleNotEqual.test.cpp, compiler/luci/partition/src/Nodes/CircleOneHot.cpp, compiler/luci/partition/src/Nodes/CircleOneHot.test.cpp, compiler/luci/partition/src/Nodes/CirclePack.cpp, compiler/luci/partition/src/Nodes/CirclePack.test.cpp
This will enable connection of cloned nodes for CircleNotEqual,
CircleOneHot and CirclePack.
=> [luci] Clone connect for NotEqual and others

compiler/luci/partition/src/ConnectNode.h, compiler/luci/partition/src/Nodes/CircleSin.cpp, compiler/luci/partition/src/Nodes/CircleSin.test.cpp, compiler/luci/partition/src/Nodes/CircleSlice.cpp, compiler/luci/partition/src/Nodes/CircleSlice.test.cpp, compiler/luci/partition/src/Nodes/CircleSoftmax.cpp, compiler/luci/partition/src/Nodes/CircleSoftmax.test.cpp
This will enable connection of cloned nodes for CircleSin, CircleSlice
and CircleSoftmax.
=> [luci] Clone connect for Sin and others

compiler/luci/partition/src/ConnectNode.h, compiler/luci/partition/src/Nodes/CircleUnidirectionalSequenceLSTM.cpp, compiler/luci/partition/src/Nodes/CircleUnidirectionalSequenceLSTM.test.cpp, compiler/luci/partition/src/Nodes/CircleUnique.cpp, compiler/luci/partition/src/Nodes/CircleUnique.test.cpp
This will enable connection of cloned nodes for CircleUnique and
CircleUnidirectionalSequenceLSTM.
=> [luci] Clone connect for Unique and other

compiler/luci/partition/src/ConnectNode.h, compiler/luci/partition/src/Nodes/CircleCustomOut.cpp, compiler/luci/partition/src/Nodes/CircleCustomOut.test.cpp, compiler/luci/partition/src/Nodes/CircleNonMaxSuppressionV4Out.cpp, compiler/luci/partition/src/Nodes/CircleNonMaxSuppressionV4Out.test.cpp, compiler/luci/partition/src/Nodes/CircleNonMaxSuppressionV5Out.cpp, compiler/luci/partition/src/Nodes/CircleNonMaxSuppressionV5Out.test.cpp
This will enable connection of clone nodes for CircleCustomOut,
CircleNonMaxSuppressionV4Out and CircleNonMaxSuppressionV5Out.
=> [luci] Clone connect for CustomOut and others

compiler/luci/partition/src/ConnectNode.h, compiler/luci/partition/src/Nodes/CircleOutputDummy.cpp, compiler/luci/partition/src/Nodes/CircleOutputExclude.cpp
This will add empty connection for CircleOutputDummy and
CircleOutputExclude. These two has no inputs so doesn't
do any actions.
=> [luci] Clone empty for OutputDummy and OutputExclude

compiler/luci/partition/src/ConnectNode.h, compiler/luci/partition/src/Nodes/CircleTopKV2Out.cpp, compiler/luci/partition/src/Nodes/CircleTopKV2Out.test.cpp, compiler/luci/partition/src/Nodes/CircleUniqueOut.cpp, compiler/luci/partition/src/Nodes/CircleUniqueOut.test.cpp, compiler/luci/partition/src/Nodes/CircleUnpackOut.cpp, compiler/luci/partition/src/Nodes/CircleUnpackOut.test.cpp
This will enable connection of clone nodes for CircleTopKV2Out,
CircleUniqueOut and CircleUnpackOut.
=> [luci] Clone connect for TopKV2Out and others

compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
This commit refactors `overwrite_quantparam` method to be able to accept any circle node.
It's required for #6721 
Parent issue #6661 
=> [circle-quantizer] Refactor overwrite_quantparam

compiler/luci/env/CMakeLists.txt, compiler/luci/export/CMakeLists.txt, compiler/luci/import/CMakeLists.txt, compiler/luci/lang/CMakeLists.txt, compiler/luci/log/CMakeLists.txt, compiler/luci/logex/CMakeLists.txt, compiler/luci/partition/CMakeLists.txt, compiler/luci/pass/CMakeLists.txt, compiler/luci/profile/CMakeLists.txt, compiler/luci/service/CMakeLists.txt
This commit makes luci header files installed to `include` dir.
Related: #6726
=> [luci] Install header files

compiler/luci-interpreter/src/CMakeLists.txt
This commit makes luci-interpreter header files installed to `include`
dir.
Related: #6726
=> [luci-interpreter] Install header files

compiler/loco/CMakeLists.txt
This commit makes loco header files installed to `include` dir.
Related: #6726 
=> [loco] Install header files

compiler/circle-tensordump/CMakeLists.txt
This commit adds `install` command.
Related: #6717 
=> [circle-tensordump] Install circle-tensordump

compiler/circledump/CMakeLists.txt
This commit adds `install` command.
Related: #6717 
=> [circledump] Install circledump

infra/scripts/docker_build_nncc.sh
This commit adds dump tools to exclude list of compiler packaging.
Related: #6717 
=> [infra] Add dump tools to exclude list

compiler/luci/pass/src/QuantizationUtils.h, compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp, compiler/luci/pass/src/QuantizedModelVerifier.test.cpp, compiler/luci/pass/src/VerifyQuantizedNodeChannelWiseGranularity.h, compiler/luci/pass/src/VerifyQuantizedNodeLayerWiseGranularity.h, compiler/luci/pass/src/VerifyQuantizedNodeS16Type.h, compiler/luci/pass/src/VerifyQuantizedNodeU8Type.h
This commit adds support for quantization of PadV2.
Requires #6725 
For #6661 
=> [circle-quantizer] Support quantization of PadV2

compiler/luci/service/src/CircleShapeInferenceRule.cpp
This will add assert on invalid shape for Conv2D and Pool2D types.
=> [luci] Add assert on invalid shape

compiler/luci/service/src/CircleShapeInferenceRule.cpp
This will revise Conv2D shape inference with more information.
=> [luci] More debug info on Conv2D shape inf

compiler/foder/include/foder/FileLoader.h
This commit removes `delete` keyword of move members.
I just wanted the class to be not copyable. Turns out that move members shouldn't be deleted at any conditions.
For more details, please refer to https://stackoverflow.com/a/38820178/8741151.
=> [foder] Do not delete move members

compiler/souschef/src/LexicalCast.cpp
This will introduce to_number for string type.
=> [souschef] to_number for string

compiler/circlechef/core/src/DataChef.def, compiler/circlechef/core/src/ModelChef.cpp
This will relocate DataChef.def back to circhechef as to reduce
change dependency and it's not used in souschef.
=> [circlechef] Relocate DataChef.def

compiler/tflchef/core/src/DataChef.def, compiler/tflchef/core/src/ModelChef.cpp
This will relocate DataChef.def back to tflchef as to reduce change
dependency and it's not used in souschef.
=> [tflchef] Relocate DataChef.def

compiler/tflchef/proto/tflchef.proto
This will introduce STRING TensorType in proto file.
=> [tflchef] Add STRING TensorType in proto

compiler/circlechef/proto/circlechef.proto
This will introduce STRING TensorType in proto file.
=> [circlechef] Add STRING TensorType in proto

compiler/common-artifacts/exclude.lst
This will add exclude items for upcomming STRING TensorType support.
=> [common-artifacts] Exclude for STRING TensorType

compiler/luci/lang/include/luci/IR/Nodes/CircleConst.h, compiler/luci/lang/src/Nodes/CircleConst.cpp, compiler/luci/lang/src/Nodes/CircleConst.test.cpp
This will enable support of STRING TensorType for CircleConst.
=> [luci] Support STRING in Const

compiler/luci/import/src/Nodes/CircleConst.cpp
This will remove static function keyword and move to anonymous
namespace.
=> [luci] Remove static function keyword

compiler/luci/service/src/CircleShapeInferenceRule.cpp
This will add assert check of dimensions used in shape inference of conv, pool.
ONE-DCO-1.0-ONE-DCO-1.0-ONE-DCO-1.0-Signed-off-by: SaeHie Park <saehie.park@gmail.com>
=> [luci] Assert check in shape inference

compiler/luci/import/src/CircleReader.cpp, compiler/luci/import/src/Nodes/CircleConst.cpp
This will enable import of STRING TensorType CircleConst.
=> [luci] Enable import of STRING TensorType Const

compiler/luci/import/src/GraphBuilderMultiOutput.cpp, compiler/luci/lang/include/luci/IR/Nodes/CircleCustom.h
This will revise CircleCustom to have 0 input or 0 output but not both.
=> [luci] Revise CircleCustom to have 0 in, 0 out

compiler/luci/export/src/CircleExporterUtils.cpp, compiler/luci/export/src/CircleTensorExporter.cpp
This will enable export of STRING TensorType of CircleConst.
=> [luci] Enable export for STRING TensorType Const

compiler/common-artifacts/exclude.lst
This will remove exclude item for STRING TensorType of circle2circle
optimization test.
=> [common-artifacts] Remove exclude item for STRING

compiler/one-cmds/CMakeLists.txt, compiler/one-cmds/conv_mixin_1.8.0.patch, compiler/one-cmds/one-prepare-venv
This will upgrade venv onnx-tf to 1.8.0 with a minor patch for
DepthwiseConv2D conversion.
=> [one-cmds] Upgrade venv onnx-tf to 1.8.0

compiler/circle2circle/src/Circle2Circle.cpp
This will enable transform_min_relu_to_relu6 option.
=> [circle2circle] Enable transform_min_relu_to_relu6

compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp, compiler/luci/pass/src/VerifyQuantizedNodeS16Type.h, compiler/luci/pass/src/VerifyQuantizedNodeU8Type.h
This sets scale to integer for Ops with integer output.
---
Related to: https://github.com/Samsung/ONE/issues/6804
=> [luci] Quantize Ops with an integer output

compiler/luci/pass/include/luci/Pass/RemoveFakeQuantPass.h, compiler/luci/pass/src/RemoveFakeQuantPass.cpp, compiler/luci/pass/src/RemoveFakeQuantPass.test.cpp
This will introduce RemoveFakeQuantPass that will remove all FakeQuant
Ops in the graph.
=> [luci] Introduce RemoveFakeQuantPass

compiler/common-artifacts/exclude.lst
This will exclude Net_Conv_FakeQuant_000 test data generation.
=> [common-artifacts] Exclude Net_Conv_FakeQuant_000

compiler/one-cmds/one-prepare-venv
This commit let users use venv python even though users run with sudo.
Related: https://github.com/Samsung/ONE/issues/6793#issuecomment-840306866
=> [one-cmds] Revise one-prepare-venv

compiler/one-cmds/how-to-use-one-commands.txt, compiler/one-cmds/utils.py
This will enable remove_fakequant option to remove FakeQuant Ops.
=> [one-cmds] Enable remove_fakequant

debian/rules
This commit relocates dh_install command. `dh_install` should be run at the end.
=> [debian] Relocate dh_install command

debian/one-compiler.install
This commit installs luci-eval-driver.
=> [debian] install luci-eval-driver

infra/command/format
This commit ignores debian/rules permission checking.
`rules` file should have execute permission for package building.
=> [infra] Ignore debian/rules permission checking

infra/packaging/res/tf2nnpkg.20210406
This commit updates `tf2nnpkg.20210406` not to use `generate_bcq_output_arrays`
and `generate_bcq_metadata`, which are deprecated.
=> [infra] Update tf2nnpkg.20210406 not to use deprecated scripts

compiler/circle-tensordump/src/Dump.cpp
This commit fixes static analysis warnings in `circle-tensordump`.
=> [circle-tensordump] Fix static warnings

debian/one-compiler-test.install, debian/one-compiler.install
This commit removes `luci_eval_driver` from one-compiler.install list.
=> [debian] Fix install list

compiler/luci/pass/include/luci/CircleOptimizer.h
This will introduce two sub option enums for ConvertNCHWToNHWC to
convert also with I/O that will replace 'preserve' sub options.
=> [luci] Introduce NCHW to NHWC convert sub option enums

compiler/one-cmds/utils.py
This will remove not used anymore nchw_to_nhwc preserve options.
=> [one-cmds] Remove nchw_to_nhwc preserve options

compiler/circle2circle/src/Circle2Circle.cpp
This will remove not used anymore nchw_to_nhwc preserve options.
=> [luci] Remove nchw_to_nhwc preserve options

compiler/luci/pass/include/luci/CircleOptimizer.h
This will remove not used anymore NCHW_to_NHWC_preserve_input_shape and
NCHW_to_NHWC_preserve_output_shape option enums.
=> [luci] Remove unused optimization options

compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
This commit adds support for MirrorPad quantization.
=> [circle-quantizer] Add support for MirrorPad

compiler/luci-interpreter/src/core/KernelParams.h, compiler/luci-interpreter/src/kernels/CMakeLists.txt, compiler/luci-interpreter/src/kernels/MirrorPad.cpp, compiler/luci-interpreter/src/kernels/MirrorPad.h, compiler/luci-interpreter/src/loader/KernelBuilder.cpp, compiler/luci-interpreter/src/loader/KernelBuilder.h
This commit adds quantization-only support for MirrorPad op in luci-interpreter.
=> [luci-interpreter] Support for MirrorPad in luci-interpreter

compiler/one-cmds/one-build, compiler/one-cmds/utils.py
This commit makes configparser preserve the case.
Related: #6854 
=> [one-cmds] Make configparser preserve the case

.ahub/tcchecker-tca/config.yaml
- Merge config.yaml for both compiler and runtime
- Rename test target as NN_Runtime and NN_Compiler
=> Merge TCM configuration for AHub run

compiler/circledump/src/OpPrinter.cpp
This commit resotres ostream state of boolalpha.
=> [circledump] Restore ostream state

compiler/tfldump/src/OpPrinter.cpp
This commit restores ostream state of boolplpha.
=> [tfldump] Restore ostream state

.ahub/sam/advanced.cfg, .ahub/sam/exclude.txt
This commit adds SAM configuration scripts. The content locations and
definition defined by AHUB.
---
With this, we can run SAM analysis with SVACE
Tested in draft #6851
See https://github.com/Samsung/ONE/pull/6851#issuecomment-844701787 for detail
=> [SAM] Run SAM on AHUB

.ahub/tcchecker-tca/config.yaml
- Exclude base TC set from TCM in order to bypass the limitation of not
considering base TC count while generating analysis report.
=> Update NN_Runtime TCM configuration to exclude base TC set in anlysis

infra/docker/bionic/Dockerfile
This commit adds debian build tool to docker file.
Related: #6764 
=> [docker] Install debian build tool

compiler/luci/pass/src/QuantizedModelVerifier.test.cpp, compiler/luci/pass/src/VerifyQuantizedNodeChannelWiseGranularity.h, compiler/luci/pass/src/VerifyQuantizedNodeLayerWiseGranularity.h, compiler/luci/pass/src/VerifyQuantizedNodeS16Type.h, compiler/luci/pass/src/VerifyQuantizedNodeU8Type.h
This commit adds coverage tests for MirrorPad.
For #6856 
=> [circle-quantizer] Add coverage tests for MirrorPad

compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
This commit makes MirrorPad case follow alphabetical order.
For #6856 
=> [circle-quantizer] Follow order for MirrorPad

compiler/circle-tensordump/src/Dump.cpp
This commit adds nullptr checking codes for tensor name in `circle-tensordump`.
=> [circle-tensordump] nullptr check for tensor name

compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp, compiler/luci/pass/src/VerifyQuantizedNodeS16Type.h, compiler/luci/pass/src/VerifyQuantizedNodeU8Type.h
This quantizes Softmax using fixed values (min: 0, max: 1).
=> [luci] Quantize Softmax using fixed values

debian/control
This commit adds python3-things to one-compiler's dependencies.
=> [debian] Add python3-things to dependencies

infra/docker/bionic/Dockerfile
This commit adds python3-all to bionic docker container that is one of debian build tool.
=> [docker] Install python3-all

debian/changelog
This commit adds 1.16.1 changelog.
Related: #6886 
=> [debian] Add 1.16.1 changelog

compiler/vconone/CMakeLists.txt
This will bump version to 1.16.1 for release/1.16.0 branch.
=> [vconone] Bump version 1.16.1

compiler/vconone/CMakeLists.txt
This will bump compiler version to 1.16.1 as to follow release/1.16.0 branch.
=> Compiler FE bump version to 1.16.1

compiler/one-cmds/one-codegen
This commit extends the point where `one-codegen` finds backends.
=> [one-cmds] Extends the point where codegen finds backends

compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp, compiler/luci/pass/src/VerifyQuantizedNodeS16Type.h, compiler/luci/pass/src/VerifyQuantizedNodeU8Type.h
This manually sets scale/zp of special Ops.
=> [circle-quantizer] Manually set scale/zp of special Ops

compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
This quantizes const input before bias is quantized.
=> [luci] Quantize const input before bias quantization

debian/rules
This commit overrides dh_builddeb to change the place where *.deb
pakcage is generated.
Related: #6764 
=> [debian] Override dh_builddeb

compiler/vconone/CMakeLists.txt
This will bump version to 1.16.1 for next patch release.
=> [vconone] Bump version to 1.16.1

infra/scripts/docker_build_nncc.sh
This commit updates docker_build_nncc script for debian packaging.
For reviewers' information,
`--no-lintian` : Do not run `lintian`(Static analysis tool for Debian packages).
`-us -uc`: No singing.
`--buildinfo-option=-ubuild --changes-option=-ubuild`: For changing the directory where `*.deb` files are generated.
Related: #6764 
=> [infra] Update docker_build_nncc script

compiler/common-artifacts/exclude.lst
This will exclude Quantize recipe while landing codes.
=> [common-artifacts] Exclude Quantize recipe

compiler/one-cmds/one-prepare-venv
This commit removes ln command that makes venv python's symbolic link.
Related: #6902 
=> [one-cmds] Remove python symbolic link

compiler/luci/service/include/luci/Service/CircleShapeInference.h, compiler/luci/service/include/luci/Service/CircleTypeInference.h, compiler/luci/service/src/CircleShapeInferenceRule.cpp, compiler/luci/service/src/CircleTypeInferenceRule.cpp
This will revise shape and dtype inference for CircleQuantize.
=> [luci] Reviese shape/dtype inference for CircleQuantize

compiler/luci/partition/src/ConnectNode.h, compiler/luci/partition/src/Nodes/CircleQuantize.cpp, compiler/luci/partition/src/Nodes/CircleQuantize.test.cpp
This will enable connection of CircleQuantize for model partition.
=> [luci] Connection of CircleQuantize for partition

compiler/common-artifacts/exclude.lst
This will remove exclude item to enble Quantize Op of circle2circle.
=> [common-artifacts] Enable Quantize for circle2circle

compiler/common-artifacts/exclude.lst
This will add Net_Conv_QuantDequant_000 to exclude list.
=> [common-artifacts] Exclude Net_Conv_QuantDequant_000

compiler/luci/pass/include/luci/CircleOptimizer.h, compiler/luci/pass/src/CircleOptimizer.cpp
This will introduce RemoveQuantDequantSeq enum and connect with
RemoveQuantDequantSeqPass.
=> [luci] Introduce RemoveQuantDequantSeq

compiler/circle2circle/src/Circle2Circle.cpp
This will add remove_quantdequant option to enable RemoveQuantDequantSeq
algorithm.
=> [circle2circle] Support remove_quantdequant

compiler/one-cmds/tests/one-import-bcq_001.test, compiler/one-cmds/tests/one-import_neg_001.test, compiler/one-cmds/tests/one-import_neg_002.test, compiler/one-cmds/tests/one-import_neg_003.test, compiler/one-cmds/tests/one-import_neg_004.test, compiler/one-cmds/tests/one-import_neg_005.test, compiler/one-cmds/tests/one-import_neg_006.test, compiler/one-cmds/tests/one-import_neg_007.test, compiler/one-cmds/tests/one-import_neg_008.test, compiler/one-cmds/tests/one-import_neg_009.test, compiler/one-cmds/tests/one-import_neg_010.test
This will fix remove log file with correct name.
- also remove rm command when there is no log generated
=> [one-cmds] Fix remove log file

compiler/one-cmds/one-import-onnx, compiler/one-cmds/tests/one-build_011.cfg, compiler/one-cmds/tests/one-build_011.test, compiler/one-cmds/tests/one-build_neg_006.cfg, compiler/one-cmds/tests/one-build_neg_006.test
This will add save_intermediate option to import_onnx to save
intermediate tflite file in output folder.
=> [one-cmds] Provide save_intermediate for import_onnx

infra/docker/bionic/Dockerfile
Let's upgrade git version on bionic docker.
Github checkout action requires v2.18, but ubuntu bionic's default git version is v2.17.1.
=> [Infra/docker] Upgrade git version

compiler/luci/service/src/CircleCloneNode.cpp, compiler/luci/service/src/CircleCloneNode.h, compiler/luci/service/src/Nodes/CircleAbs.cpp, compiler/luci/service/src/Nodes/CircleAdd.cpp, compiler/luci/service/src/Nodes/CircleAddN.cpp, compiler/luci/service/src/Nodes/CircleArgMax.cpp, compiler/luci/service/src/Nodes/CircleArgMin.cpp, compiler/luci/service/src/Nodes/CircleAveragePool2D.cpp, compiler/luci/service/src/Nodes/CircleBatchMatMul.cpp, compiler/luci/service/src/Nodes/CircleBatchToSpaceND.cpp, compiler/luci/service/src/Nodes/CircleCast.cpp, compiler/luci/service/src/Nodes/CircleCeil.cpp, compiler/luci/service/src/Nodes/CircleConst.cpp, compiler/luci/service/src/Nodes/CircleConv2D.cpp, compiler/luci/service/src/Nodes/CircleCos.cpp, compiler/luci/service/src/Nodes/CircleCustom.cpp
This will group CloneNode to smaller subclass for ABC to reduce LoC of
CloneNode class.
=> Group CloneNode to smaller subclass for ABC

compiler/luci/service/src/CircleCloneNode.cpp, compiler/luci/service/src/CircleCloneNode.h, compiler/luci/service/src/Nodes/CircleDepthToSpace.cpp, compiler/luci/service/src/Nodes/CircleDepthwiseConv2D.cpp, compiler/luci/service/src/Nodes/CircleDequantize.cpp, compiler/luci/service/src/Nodes/CircleDiv.cpp, compiler/luci/service/src/Nodes/CircleElu.cpp, compiler/luci/service/src/Nodes/CircleEqual.cpp, compiler/luci/service/src/Nodes/CircleExp.cpp, compiler/luci/service/src/Nodes/CircleExpandDims.cpp, compiler/luci/service/src/Nodes/CircleFakeQuant.cpp, compiler/luci/service/src/Nodes/CircleFill.cpp, compiler/luci/service/src/Nodes/CircleFloor.cpp, compiler/luci/service/src/Nodes/CircleFloorDiv.cpp, compiler/luci/service/src/Nodes/CircleFloorMod.cpp, compiler/luci/service/src/Nodes/CircleFullyConnected.cpp
This will group CloneNode to smaller subclass for DEF.
=> Group CloneNode to smaller subclass for DEF

compiler/luci/service/src/CircleCloneNode.cpp, compiler/luci/service/src/CircleCloneNode.h, compiler/luci/service/src/Nodes/CircleGather.cpp, compiler/luci/service/src/Nodes/CircleGatherNd.cpp, compiler/luci/service/src/Nodes/CircleGreater.cpp, compiler/luci/service/src/Nodes/CircleGreaterEqual.cpp
This will group CloneNode to smaller subclass for GHIJ.
=> Group CloneNode to small subclass for GHIJ

packaging/nnfw.spec
We have adopted armcompute library v21.02.
ref: https://github.com/Samsung/ONE/pull/6241
And now, The armcompute library was uploaded on tizen package repository.
=> [one] modify nnfw.spec file for applying armcl v21.02.

compiler/luci/import/src/CircleImportMetadata.h
Parent Issue : #6952
Draft : #6953
This commit introduces getter of `source_table` in `CircleImportMetadata.h`.
=> [luci/import] Introduce getter of source_table

compiler/one-cmds/one-prepare-venv
This will prevent apply patch for onnx when patch is already applied.
=> [one-cmds] Prevent reverse patch for onnx

compiler/luci/lang/include/luci/IR/Module.h
Parent Issue : #6952 
Draft : #6953
This commit introduces `source_table` metadata in `luci::Module`.
=> [luci/lang] Introduce source_table metadata in Module

compiler/luci/import/src/Importer.cpp
Parent issue : #6952
Draft : #6953 
This commit generates `source_table` to `luci::Module` by
- Copying `source_table` metadata in circle model if it is included
- Creating new `source_table` with imported circle nodes otherwise
=> [luci/import] Generate source_table to Module

compiler/luci/export/src/CircleExporterImpl.cpp, compiler/luci/export/src/SerializedData.h
Parent issue : #6952
Draft : #6953
Until now, newly generated `source_table` was exported.
From now on, this commit enable exporting `source_table` in `luci::Module`.
=> [luci/export] Export source_table in Module

compute/cker/include/cker/operation/optimized/Conv.h
related issue : #5799
A segmentation fault occurs when the quantized mobilenet model is executed using different threads.
Add mutex to use gemmlowp in different threads.
Signed-off-by: sungho22.lee <sungho22.lee@samsung.com>
=> [onert] Add mutex for multi-threading

compiler/luci/export/src/CircleOperationExporter.cpp, compiler/luci/export/src/SerializedData.h
Parent issue : #6952
Draft : #6953
As `source_table` in `luci::Module` is overwritten, `add_source_table` has no effect.
This commit removes the function.
=> [luci/export] Remove no-effect function

runtime/onert/api/include/nnfw_experimental.h, runtime/onert/api/src/nnfw_api.cc, runtime/onert/api/src/nnfw_api_internal.cc, runtime/onert/api/src/nnfw_api_internal.h, runtime/onert/core/include/compiler/Compiler.h, runtime/onert/core/src/compiler/Compiler.cc
Reconfigure backend allocation at runtime. This feature entails changes to `nnfw` source and header files, as well as the onert `Compiler` module.
Signed-off-by: venkat.iyer venkat.iyer@samsung.com
=> [onert] Reallocate backends to operations at runtime

compute/cker/include/cker/Types.h, runtime/onert/backend/cpu/ops/PoolLayer.cc
Remove activation, padding_type
Add initilization for others
=> Fix coverity 1229862 : uinit variable in PoolParams

compiler/luci/pass/src/VerifyQuantizedNodeS16Type.h, compiler/luci/pass/src/VerifyQuantizedNodeU8Type.h
Since `bias` is optional, sometimes `CircleFullyConnected` does not have `bias`.
However, current verification code did not consider it.
This commit will fix it.
=> [luci] Verify bias only when FullyConnected has it

compiler/luci/service/include/luci/Service/ChangeOutputs.h, compiler/luci/service/src/ChangeOutputs.cpp, compiler/luci/service/src/ChangeOutputs.test.cpp
This will introduce change_outputs experimental method of luci to
change output nodes by node name.
- only work for first subgraph (main graph)
=> [luci] Introduce change_outputs

compiler/one-cmds/one-prepare-venv
This will revise one-prepare-venv to handle already applied patch for
onnx-tf package.
=> [one-cmds] Handle already applied patch in prepare-venv

compiler/luci/service/src/CircleCloneNode.cpp, compiler/luci/service/src/CircleCloneNode.h, compiler/luci/service/src/Nodes/CircleWhere.cpp, compiler/luci/service/src/Nodes/CircleZerosLike.cpp
This will fix CloneNode typo in enum class CN as WXYZ as V is declared two times.
=> [luci] Fix CloneNode typo in enum CN

compiler/luci/logex/src/FormattedGraph.cpp
group ABC CircleNodes to reduce class LoC violation.
=> [luci] Extract to SummaryBuilderLet with group ABC

compiler/luci/logex/src/FormattedGraph.cpp
group DEF CircleNodes to reduce class LoC violation.
=> [luci] Extract to SummaryBuilderLet with group DEF

compiler/luci/logex/src/FormattedGraph.cpp
group GHIJ CircleNodes to reduce class LoC violation.
=> [luci] Extract to SummaryBuilderLet with group GHIJ

compiler/bcq-tools/generate_bcq_metadata.py
To resolve #6979 
From TensorFlow 2.4.0, API for `AttrValue` is changed.
This commit will fix it.
=> [bcq-tools] Fix TensorFlow API Error

compiler/luci/logex/src/FormattedGraph.cpp
group KLMN CircleNodes to reduce class LoC violation.
=> [luci] Extract to SummaryBuilderLet with group KLMN

compiler/luci-interpreter/src/loader/CMakeLists.txt, compiler/luci-interpreter/src/loader/KernelBuilderHelper.cpp, compiler/luci-interpreter/src/loader/KernelBuilderHelper.h
This will introduce KernelBuilderHelper that is extracted from
KernelBuilder part to help build kernels.
=> [luci-interpreter] Introduce KernelBuilderHelper

compiler/luci/logex/src/FormattedGraph.cpp
group OPQR CircleNodes to reduce class LoC violation.
=> [luci] Extract to SummaryBuilderLet with group OPQR

compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp, compiler/luci/pass/src/VerifyQuantizedNodeS16Type.h, compiler/luci/pass/src/VerifyQuantizedNodeU8Type.h
This makes input/output of StridedSlice have the same scale and zp.
=> [circle-quantizer] Use the same scales for input/output of StridedSlice

compiler/luci/logex/src/FormattedGraph.cpp
group STUV, WXYZ CircleNodes to reduce class LoC violation.
=> [luci] Extract to SummaryBuilderLet with group STUV,WXYZ

compiler/luci/logex/src/FormattedGraph.cpp
group CIRC, VIRT(circle only and virtual) CircleNodes to reduce class LoC violation.
=> [luci] Extract to SummaryBuilderLet with group CIRC,VIRT

compiler/record-minmax/include/RecordFunction.h
This commit fixes computation of percentile 0 and 100.
=> [record-minmax] Fix boundary percentile cases

compiler/luci-interpreter/src/loader/KernelBuilder.cpp, compiler/luci-interpreter/src/loader/KernelBuilder.h
This will extract KernelBuilderLet for circle IR group ABC to reduce
ONE-DCO-1.0-Signed-off-by: SaeHie Park saehie.park@gmail.com
=> [luci-interpreter] Extract KernelBuilderLet for group ABC

compiler/luci/export/src/CircleOperationExporter.cpp
This will extract OpExporterLet with group DEF IR exports to reduce
=> [luci] Extract OpExporterLet with group DEF

compiler/luci-interpreter/src/loader/KernelBuilder.cpp, compiler/luci-interpreter/src/loader/KernelBuilder.h
This will extract KernelBuilderLet for circle IR group DEF to reduce
=> [luci-interpreter] Extract KernelBuilderLet for group DEF

compiler/luci-interpreter/src/loader/KernelBuilder.cpp, compiler/luci-interpreter/src/loader/KernelBuilder.h
This will extract KernelBuilderLet for circle IR group GHIJ, KLMN to reduce
=> [luci-interpreter] Extract KernelBuilderLet for group GHIJ,KLMN

compiler/luci-interpreter/src/loader/KernelBuilder.cpp, compiler/luci-interpreter/src/loader/KernelBuilder.h
This will extract KernelBuilderLet for circle IR group OPQR to
reduce class LoC violation score.
=> [luci-interpreter] Extract KernelBuilderLet for group OPQR

compiler/luci/import/src/Nodes/CircleSquaredDifference.cpp
This will fix import of SquaredDifference to support U8/S16 tensor types.
=> [luci] Supprt import U8/S16 for SquaredDifference

compiler/luci/export/src/CircleOperationExporter.cpp
This will extract OpExporterLet with group GHIJ, KLMN IR exports to reduce
=> [[luci] Extract OpExporterLet with group GHIJ,KLMN

compiler/luci-interpreter/src/loader/KernelBuilder.cpp, compiler/luci-interpreter/src/loader/KernelBuilder.h
This will extract KernelBuilderLet for circle IR group STUV to
reduce class LoC violation score.
=> [luci-interpreter] Extract KernelBuilderLet for group STUV

compiler/luci/export/src/CircleOperationExporter.cpp
This will extract OpExporterLet with group OPQR IR exports to
reduce class LoC violation score.
=> [luci] Extract OpExporterLet with group OPQR

compiler/luci-interpreter/src/loader/GraphLoader.cpp, compiler/luci-interpreter/src/loader/KernelBuilder.cpp, compiler/luci-interpreter/src/loader/KernelBuilder.h, compiler/luci-interpreter/src/loader/KernelBuilder.test.cpp
This will revise KernelBuild class not to inherit from Visitor as not
needed anymore and rename visit method to build.
=> [luci-interpreter] Revise KernelBuilder

compiler/luci/export/src/CircleOperationExporter.cpp
This will extract OpExporterLet with group STUV, WXYZ IR exports to
reduce class LoC violation score.
=> [luci] Extract OpExporterLet with group STUV,WXYZ

compiler/luci/profile/src/CircleNodeOrigin.cpp, compiler/luci/profile/src/CircleNodeOrigin.test.cpp
Originated from #7008
Until now, `has_origin` returned `true` when `sources()` is not empty.
However, empty `sources()` actually means that there are no origin information.
So this commit will update `has_origin` to return `false` when `sources()` is empty.
=> [luci/profile] Update logic of has_origin

compiler/luci/service/src/CircleCloneNode.cpp
This will add undef for CNVISIT_GRP in CircleCloneNode.
=> [luci] Add undef for CNVISIT_GRP

compiler/luci/export/src/CircleOperationExporter.cpp
This will tidy OperationExporter class as
- remove inherit from visitor as needless now
- rename visit() to export_node()
- tidy unused visit() codes
- add undef of VISIT_OE macro
=> [luci] Tidy OperationExporter class

infra/scripts/docker_build_nncc.sh
This commit adds ubuntu codename info when `dch` writes changelog.
Related: #6978 
=> [infra] Add ubuntu codename info

compiler/one-cmds/one-build, compiler/one-cmds/one-codegen, compiler/one-cmds/one-import-bcq, compiler/one-cmds/one-import-onnx, compiler/one-cmds/one-import-tf, compiler/one-cmds/one-import-tflite, compiler/one-cmds/one-optimize, compiler/one-cmds/one-pack, compiler/one-cmds/one-quantize
This will add flush write execution to show log immediatly for long
execution commands, such as record-minmax.
=> [one-cmds] Flush commands

infra/docker/focal/Dockerfile
This commit adds `dh-python` to focal Dockerfile.
Related: #6978 
=> [infra] Add dh-python to focal Dockerfile

compiler/luci/logex/src/FormattedGraph.cpp
This will add missing IRs for logex SummaryBuilder.
=> [luci] Add missing IRs for logex SummaryBuilder

debian/docs/one-build.1, debian/docs/one-codegen.1, debian/docs/one-import-bcq.1, debian/docs/one-import-onnx.1, debian/docs/one-import-tf.1, debian/docs/one-import-tflite.1, debian/docs/one-optimize.1, debian/docs/one-pack.1, debian/docs/one-quantize.1, debian/one-compiler.manpages
This commit adds ONE compiler manapges.
It is kind of hard to review them because they are written in `nroff` form. So, to make it easier, please use `man` command.
1. Copy contents of each file to local machine
2. `man ./copied_file.1`
3. Review
Related: #6910 
=> [debian] Add ONE compiler manpages

compiler/luci/logex/src/FormattedGraph.cpp
This will revise CircleNodeSummaryBuilderBase::build method just to
return false
- to make all IRs to be implemented
- to make current SummaryBuilderLet to work properly
=> [luci] Revise base build method to return false

compiler/luci/pass/src/QuantizationUtils.cpp
This sets the minimum value (1e-9) of scale for int16 quantization.
=> [luci] Set minimum value of scale for Q16

compiler/one-cmds/tests/one-import_neg_003.test
This will revise one-import_neg_003.test also for TF2.5.0.
=> [one-cmds] Revise one-import_neg_003.test for TF 2.5.0

compiler/luci/pass/src/FuseBatchNormWithDwConvPass.cpp
This support more activation functions in FuseBatchNormWithDwConvPass.
=> [luci] Support more activation functions in FuseBatchNormWithDwConvPass

compiler/luci/pass/src/FuseInstanceNormPass.cpp
This will relocate CHECK_OR_FALSE macro outside of method.
=> [luci] Relocate CHECK_OR_FALSE outside of method

compiler/luci/pass/src/FuseInstanceNormPass.cpp
This will extract is_add_input_mul_const() method FuseInstanceNormPass
to check input of Add is Mul/Const.
=> [luci] Extract is_add_input_mul_const for FuseInstNorm

compiler/luci/pass/src/FuseInstanceNormPass.cpp
This will fix FuseInstNorm final pattern comment that was copied from
moco project.
=> [luci] Fix FuseInstNorm final pattern comment

compiler/luci/pass/src/FuseInstanceNormPass.cpp
This will fix name for fused InstNorm node to be unique for multiple
instances.
=> [luci] Fix name for fused InstNorm node

compiler/luci/pass/src/FuseInstanceNormPass.cpp
This will extract InstanceNorm pattern match for version 0 and 1 to its
own method.
=> [luci] Extract InstNorm match for version 0,1

compiler/luci-interpreter/src/loader/KernelBuilder.cpp
This will revise error message to show node name to help finding the
problem.
=> [luci-interpreter] Node name for unsupported op msg

compiler/circle2circle/src/Circle2Circle.cpp
Parent Issue : #7081 
Draft : #7082 
This commit enables `ReplaceSubWithAdd` in `circle2circle`.
=> [circle2circle] Enable ReplaceSubWithAdd

compiler/luci/pass/src/FuseInstanceNormPass.cpp
This will provide FuseInstanceNorm::apply() method for pattern version 1 and 2.
=> [luci] Provide ver 1,2 for FuseInstanceNorm::apply

compiler/luci/pass/src/FuseInstanceNormPass.cpp
This will add Version_3 pattern as comment of FuseInstanceNormPass.
=> [luci] FuseInstNorm Version_3 pattern comment

compiler/luci/pass/src/FuseInstanceNormPass.cpp
This will revise shape check for Version 3 InstanceNormalization pattern
from version 0 where real models don't match.
=> [luci] Remove shape check for V3 InstNorm pattern

compiler/luci/pass/src/FuseInstanceNormPass.cpp
This will remove additional brace and indentation in
FuseInstanceNormPass.
=> [luci] Remove indentation in FuseInstanceNormPass

compiler/luci/pass/src/FuseInstanceNormPass.cpp
This will tidy FuseInstanceNormPass::run method without version as it
can be moved inside fuse_instance_norm method.
=> [luci] Tidy FuseInstanceNormPass run without version

runtime/onert/backend/gpu_cl/open_cl/AccessType.h, runtime/onert/backend/gpu_cl/open_cl/Arguments.cc, runtime/onert/backend/gpu_cl/open_cl/Buffer.h, runtime/onert/backend/gpu_cl/open_cl/ClDevice.cc, runtime/onert/backend/gpu_cl/open_cl/ClKernel.h, runtime/onert/backend/gpu_cl/open_cl/ClMemory.cc, runtime/onert/backend/gpu_cl/open_cl/DeviceInfo.cc, runtime/onert/backend/gpu_cl/open_cl/DeviceInfo.h, runtime/onert/backend/gpu_cl/open_cl/GpuObject.h, runtime/onert/backend/gpu_cl/open_cl/Shape.h, runtime/onert/backend/gpu_cl/open_cl/Tensor.cc
uint32_t is always greater than or equal to 0. So the '0 <= i' conditional statement is not needed.
=> Reslove Svace/Covertiy Defect

infra/cmake/packages/Opencl_HeadersConfig.cmake, tests/nnfw_api/CMakeLists.txt
TEST_GPU_CL_BACKEND was not enable because Opencl_Headers was not found on gbs build.
So, Fixed by adding nnas_find_package(Opencl_Headers QUIET).
=> [onert] Fix gbs build for nnfw_api_gtest

tools/tflitefile_tool/requirements.txt
This commit fixes 'flatbuffers' version for `tflitefile` tools, like
`select_operator.py`.
---
Due to https://github.com/Samsung/ONE/issues/7086
Not sure `requirements.txt` is only for `select_operator.py`
=> [tool/tflitefile] Fix requirements.txt

compiler/luci/logex/src/FormattedGraph.cpp
This will revise to log for Mem value only if summary method of the CLASS is handled.
This is to prevent multiple Mem logs where dynamic_cast itself is
executed by multiple times as ther are multiple 'SummaryBuilderLet' classes.
=> [luci] Fix to print Mem comment only once

runtime/onert/backend/gpu_cl/Backend.h, runtime/onert/backend/gpu_cl/open_cl/ClKernel.h
F16 is not implemented yet, so it is fixed as F32.
Currently, when reading and writing images, it is reading and writing in multiples of 16 bytes.
There is still a memory issue, not a 16byte multiple in cpu memory.
=> [onert] Fix runtime test

compiler/tflite2circle/src/CircleModel.cpp
This commit fixes error message.
runtime_error prints `ERROR: ` comment by default.
=> [tflite2circle] Fix error message

compiler/tfkit/src/Support.cpp
This commit removes redundant ERROR string from errer message.
Related: #7152
=> [tfkit] Remove redundant "ERROR" string

compiler/record-minmax/src/RecordMinMax.cpp
This commit removes redundant ERROR string from error message.
Related: #7152 
=> [record-minmax] Remove redundant "ERROR" string

compiler/pepper-csv2vec/CMakeLists.txt, compiler/pepper-csv2vec/README.md, compiler/pepper-csv2vec/include/pepper/csv2vec.h, compiler/pepper-csv2vec/src/pepper-csv2vec.cpp, compiler/pepper-csv2vec/src/pepper-csv2vec.test.cpp
This will introduce pepper module csv2vec that will return vector from
CSV format text and some related helper methods.
=> [pepper-csv2vec] Introduce csv2vec

compiler/foder/include/foder/FileLoader.h
This commit removes redundant ERROR message from error message.
Related: #7152
=> [foder] Remove redundant "ERROR" string

compiler/onnxkit/src/Support.cpp
This commit removes redundant ERROR string from error message.
Related: #7152
=> [onnxkit] Remove redundant "ERROR" string

compiler/circle-partitioner/src/PartitionRead.cpp
This will revise parse_table method to read main '[partition]' section
first then read other sections.
- to prevent default group settings when orders are inverted
=> [circle-partitioner] Separate section reading

compiler/record-minmax/driver/Driver.cpp
This adds input_data_format option to record-minmax.
---
Related to: #7132
Draft PR: #7158
=> [record-minmax] Add input_data_format option to record-minmax

compiler/luci/partition/src/Partition.test.cpp, compiler/luci/partition/src/PartitionPGroups.test.cpp, compiler/luci/partition/src/PartitionPModules.test.cpp
This will revise paritioner test codes to have OPCODE comply as default.
=> [luci] Set default comply for test codes

infra/scripts/compiler_modules.sh, infra/scripts/docker_collect_nnpkg_resources.sh
This will add new pepper-csv2vec module to build scripts.
=> [infra] Add pepper-csv2vec to scripts

compiler/pepper-csv2vec/src/pepper-csv2vec.cpp, compiler/pepper-csv2vec/src/pepper-csv2vec.test.cpp
This will eanble int32_t type for csv_to_vector.
=> [csv2vec] Enable int32_t type for csv_to_vector

compiler/circle-part-value-test/parts/Part_Add_Sub_000.001.part, compiler/circle-part-value-test/parts/Part_Add_Sub_001.part, compiler/circle-part-value-test/test.lst
This will enable basic value test for comply OPNAME with simple Add-Sub model.
=> [circle-partition] Enable value test with comply OPNAME

compiler/circle-partitioner/README.md
This will update readme about using '_' to override default group.
=> [circle-partitioner] Update readme about using '_'

debian/rules
This will revise debian build preset to latest 20210706.
=> [debian] Revise preset to 20210706

compiler/luci/pass/CMakeLists.txt, compiler/luci/pass/src/CircleOptimizer.cpp
This will revise CircleOptimizer to use pepper-csv2vec.
=> [luci] Use pepper-csv2vec

compiler/circle-partitioner/CMakeLists.txt, compiler/circle-partitioner/requires.cmake, compiler/circle-partitioner/src/CirclePartitioner.cpp, compiler/circle-partitioner/src/PartitionRead.cpp
This will revise to use pepper-csv2vec csv_to_vector method.
=> [circle-partitioner] Use pepper-csv2vec

compiler/luci/pass/src/helpers/Strings.h, compiler/luci/pass/src/helpers/Strings.test.cpp
This will remove relocated to pepper-csv2vec module for method csv_to_vector.
=> [luci] Remove relocated csv_to_vector

res/TensorFlowLiteRecipes/Part_Add_Sub_002/test.recipe
This will introduce Part_Add_Sub_002 recipe that will have shared
constant input to Add and Sub nodes.
=> [res] Introduce Part_Add_Sub_002 recipe

infra/nnfw/cmake/CfgOptionFlags.cmake, infra/nnfw/cmake/options/options_x86_64-darwin.cmake, infra/nnfw/cmake/options/options_x86_64-linux.cmake, infra/nnfw/cmake/options/options_x86_64-tizen.cmake, runtime/onert/backend/gpu_cl/CMakeLists.txt
DO NOT use gpu_cl on x86_64 arch. not tested yet.
=> Disable gpu_cl backend on x86_64

compiler/luci/partition/src/PartitionMerge.cpp
This will re vise is_input_same method for partition merge to skip for CircleConst.
=> [luci] Revise is_input_same for partition merge

compiler/luci/pass/src/VerifyQuantizedNodeChannelWiseGranularity.h
This verifies optional bias in FC layer.
=> [circle-quantizer] Verify optional bias in FC layer.

compiler/circle-part-value-test/CMakeLists.txt, compiler/circle-part-value-test/test.lst
This will revise cmake to save expected paritioned models count of partitioning.
ONE-DCO-1.0-ONE-DCO-1.0-Signed-off-by: SaeHie Park <saehie.park@gmail.com>
=> [circle-part-value-test] Save expected count

compiler/one-cmds/one-prepare-venv
This commit removes virtualenv installation command.
> python3 -m venv "${DRIVER_PATH}/venv"
Since we use `venv` package to create virtual env folder, there is no need to install `virtualenv` package.
Related: #7218 
=> [one-cmds] Remove virtualenv installation command

compiler/circle-part-value-test/part_eval_one.py
This will revise circle-part-value-test to check also number of output
partitioned models generated with expected number.
=> [circle-partitioner] Test check number of output models

compiler/circle-part-value-test/parts/Net_InstanceNorm_003.003.part, compiler/circle-part-value-test/parts/Part_Add_Sub_002.001.part, compiler/circle-part-value-test/parts/Part_Add_Sub_002.002.part, compiler/circle-part-value-test/test.lst
This will add more tests for circle-partitioner for comply=opname.
=> [circle-partitioner] More tests for OPNAME

compiler/common-artifacts/src/TestDataGenerator.cpp
This will revise data generation only for main graph as other subgraphs
are invoked from main graph.
=> [common-artifacts] Data generation only for main graph

compiler/luci/logex/src/FormattedGraph.cpp
This will revise CircleNodeSummaryBuilderBase::build to show node name.
=> [luci] Show name with node summary

compiler/souschef/src/LexicalCast.cpp
This will revise to_number for bool type as atoi will fail if not a number.
=> [souschef] Revise bool to_number

compiler/luci/import/src/GraphBuilderMultiOutput.cpp
This will add a note in GraphBuilderMultiOutput as CxxxOut may have same
node name.
=> [luci] Add note in GraphBuilderMultiOutput

compiler/luci/testhelper/include/luci/test/TestIOGraph.h
This will add num_outputs attribute for TestOsGraphlet.
=> [luci] Add num_outputs for TestOsGraphlet

compiler/tflchef/tests/explicit_bool/test.recipe
This will introduce test recipe for explicit filler for boolean type.
=> [tflchef] Test for explicit filler for boolean

compiler/luci/export/src/CircleTensorExporter.cpp
Parent Issue : #7256
Buffer index 0 is used for special purpose.
Therefore, we should not use it without special purpose.
This commit will fix it.
=> [luci] Fix wrong buffer id allocation

compiler/circle-part-driver/src/PModelsRunner.cpp
This will add log message at save_outputs method to help debugging.
=> [circle-part-driver] Add log at save_outputs

compiler/luci/partition/src/PartitionPModules.cpp
This will revise produce_pmodules to add graph to module before calling
build_graph method.
=> [luci/partition] Revise produce_pmodules

compiler/luci/partition/src/PartitionCleanup.cpp, compiler/luci/partition/src/PartitionPGroups.cpp
This will remove check for single graph as to support multiple subgraphs.
=> [luci/partition] Remove check for single graph

compiler/circle-part-driver/src/PModelsRunner.cpp
This will remove check for single graph as to support multiple subgraphs.
=> [circle-part-driver] Remove check for single graph

compiler/luci/pass/include/luci/CircleOptimizer.h, compiler/luci/pass/src/CircleOptimizer.cpp, compiler/luci/pass/src/CircleOptimizer.test.cpp
This adds SubstituteStridedSliceToReshape pass to CircleOptimizer.
issue #7232
draft #7235
=> [luci] Add SubstituteStridedSliceToReshape pass to CircleOptimizser

compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
This fixes a bug in fused TANH quantization.
=> [circle-quantizer] Fix bug in fused TANH quantization

compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp, compiler/luci/pass/src/VerifyQuantizedNodeS16Type.h, compiler/luci/pass/src/VerifyQuantizedNodeU8Type.h
This adds null check into code related to quantization.
From https://github.com/Samsung/ONE/pull/7284#discussion_r674459810, I tried to add similar checks to other operations.
=> [luci] Add Null Check

compiler/luci-interpreter/src/loader/KernelBuilder.cpp, compiler/luci-interpreter/src/loader/KernelBuilder.test.cpp
This commit adds Cast's kernel builder with corresponding unit test.
----------------------
For:  #7261
Draft: #7262
=> [luci-interpreter] Add Cast kernel builder

compiler/luci-interpreter/src/loader/KernelBuilder.test.cpp
Add check for kernel value is not null.
=> [luci-interpreter] Check kernel not null

compiler/luci/pass/src/ConvertNCHWToNHWCPass.cpp, compiler/luci/pass/src/ConvertNCHWToNHWCPass.test.cpp
This supports PadV2 in ConvertNCHWToNHWC.
---
Related to: https://github.com/Samsung/ONE/issues/7314
=> [luci] Support PadV2 in ConvertNCHWToNHWC

compiler/one-cmds/one-import, compiler/one-cmds/tests/one-import_006.test
This commit adds onnx model case.
It invokes the one-import-onnx model when the parameter is onnx.
It contains the test case for onnx param.
=> [one-import] Support onnx as input parameter

compiler/luci/pass/src/ConvertNCHWToNHWCPass.cpp, compiler/luci/pass/src/ConvertNCHWToNHWCPass.test.cpp
This will revise to support SquaredDifference node in NCHWToNHWCPass.
=> [luci] Support SquaredDifference in NCHWToNHWCPass

compiler/luci/service/src/Validate.cpp
This will revise VirtualNodeDetector to include CircleOutputDummy and
CircleOutputExclude.
=> [luci] Revise VirtualNodeDetector

compiler/luci/service/src/Validate.cpp
This will revise validate_name to skip virtual nodes.
=> [luci] Revise validate_name

compiler/one-cmds/one-build
one-build is an end user tool.
It would be good to suppress traceback by default.
Related: #7297
=> [one-cmds] Suppress trackback on error from one-build

compiler/common-artifacts/exclude.lst
This commit excludes MaxPoolWithArgmax in addition to MaxPoolWithArgMax.
Related issue: #7306 
=> [common-artifacts] Exclude MaxPoolWithArgmax from test data generation

.ahub/sam/exclude.txt
This commit updates SAM exclude list: directory removed.
---
Directory `runtime/libs/tflite/port` removed at #7353
(I should have done https://github.com/Samsung/ONE/issues/6889 early :sob:)
=> [SAM] Update exclude list

compiler/tf2tfliteV2/tf2tfliteV2.py
It suppresses tensorflow log from tf2tfliteV2.py like:
2021-07-28 12:05:18.756969: I tensorflow/core/platform/cpu_feature_guard.cc:  ..
To enable them in other operations, rebuild TensorFlow with the appropriate   ..
2021-07-28 12:05:18.778068: I tensorflow/core/platform/profile_utils/cpu_util ..
2021-07-28 12:05:18.778668: I tensorflow/compiler/xla/service/service.cc:168] ..
2021-07-28 12:05:18.778693: I tensorflow/compiler/xla/service/service.cc:176] ..
=> [one-cmds] Suppress tensorflow verbose log from tf2tfliteV2.py

compiler/bcq-tools/generate_bcq_metadata.py
It suppresses traceback from generate_bcq_metadata.py.
=> [bcq-tools] Suppress trackback on error from generate_bcq_metadata.py

compiler/one-cmds/one-codegen, compiler/one-cmds/one-import-bcq, compiler/one-cmds/one-import-onnx, compiler/one-cmds/one-import-tflite, compiler/one-cmds/one-optimize, compiler/one-cmds/one-pack, compiler/one-cmds/one-quantize, compiler/one-cmds/onecc
It suppresses traceback from one-xxx and its nesting python implementation,
which is invoked by subprocess.Popen(...).
For #7297
=> [one-cmds] Suppress trackback on error from one-xxx and onecc

compiler/common-artifacts/exclude.lst
This will revise to exclude Part_While_000 and Part_While_001 while code
lands and will be removed afterwards.
=> [common-artifacts] Exclude Part_While

compiler/luci/service/src/Validate.cpp
This will fix typo in validate_shape_dtype method.
=> [luci] Fix typo in validate_shape_dtype

compiler/one-cmds/utils.py
This commit allows to add verbose option to all one-xxx tools.
=> [one-cmds] Add verbose option to utils

compiler/luci/pass/src/ConvertNCHWToNHWCPass.test.cpp
This adds a test for ConvertNCHWToNHWC pre/post-reshape.
---
Related to: https://github.com/Samsung/ONE/pull/7377#issuecomment-892414228
=> [luci] Add test for ConvertNCHWToNHWC pre/post-reshape

compiler/circle2circle/src/Circle2Circle.cpp
This commit introduce some changes in Circle2Circle.cpp for using FuseMeanWithMean pass
issue #7335
related PR  #7354
=> [circle2circle] Introduce FuseMeanWithMean in circle2circle

compiler/one-cmds/CMakeLists.txt, infra/debian/compiler/one-compiler.install
This commit adds onecc.template.cfg file to debian package.
It will be installed under /usr/share/one/bin/.
=> [onecc] Add onecc.template.cfg to debian package

compiler/luci/partition/src/ConnectNode.h, compiler/luci/partition/src/Nodes/CircleWhile.cpp, compiler/luci/partition/src/Nodes/CircleWhile.test.cpp, compiler/luci/partition/src/Nodes/CircleWhileOut.cpp, compiler/luci/partition/src/Nodes/CircleWhileOut.test.cpp
This will enable partition connect for CircleWhile and CircleWhileOut nodes.
=> [luci] Enable partition connect for While

compiler/luci-value-test/test.lst
This will enable value testing of Part_While models for WHILE with float32.
=> [luci-value-test] Enable Part_While tests

res/TensorFlowLiteRecipes/MaxPoolWithArgmax_000/test.recipe, res/TensorFlowLiteRecipes/MaxPoolWithArgmax_001/test.recipe, res/TensorFlowLiteRecipes/MaxPoolWithArgmax_002/test.recipe
This commit changes operation MaxPoolWithArgMax to MaxPoolWithArgmax
to comply with tflite files.
Related issue: #7306
ONE-DCO-1.0-Signed-off-by: Maksim Bronnikov max120199@gmail.com
=> [res] Fix typo in MaxPoolWithArgMax recipes

compiler/circle-part-value-test/parts/Part_While_000.part, compiler/circle-part-value-test/parts/Part_While_001.part, compiler/circle-part-value-test/test.lst
This will enable circle-partitioner value test for Part_While_000 and
Part_While_001 models.
=> [circle-partitioner] Enable value test for Part_While

compiler/record-minmax/driver/Driver.cpp, compiler/record-minmax/include/RecordMinMax.h, compiler/record-minmax/src/RecordMinMax.cpp
This supports directory as an input data format.
---
Related to: #7398
Draft PR: #7401
=> [record-minmax] Support directory as an input data format

compiler/luci/pass/src/VerifyQuantizedNodeChannelWiseGranularity.h, compiler/luci/pass/src/VerifyQuantizedNodeLayerWiseGranularity.h, compiler/luci/pass/src/VerifyQuantizedNodeS16Type.h, compiler/luci/pass/src/VerifyQuantizedNodeU8Type.h
This commit adds Cast Quantization checks and improves Reshape.
Related issue: #7229
=> [circle-quantized] Improve quant verification for Cast and Reshape

compiler/circle2circle-dredd-recipe-test/test.lst
This will enable dredd test for REGRESS_ONNX_Conv_BN_001 model.
=> [circle2circle] Dredd test for ONNX_CONV_BN_001

compiler/common-artifacts/exclude.lst
This will add comments for While as reasons of exclusion.
=> [common-artifacts] Comments for While

compiler/circle2circle-dredd-recipe-test/test.lst
This will enable regression test for ONNX import
- REGRESS_ONNX_Conv_BN_Relu6_001
=> [circle2circle] Enable REGRESS_ONNX_Conv_BN_Relu6_001

compiler/one-cmds/onecc
When user run `onecc -C`, several steps are done by configuration.
In this case, it would be better to print driver name that the error
occurred in.
=> [onecc] Print driver name in error message

compiler/record-minmax/src/MinMaxObserver.cpp
This commit adds type check exceptions for Reshape and Cast operations.
Related issue: #7229
=> [record-mimax] Add more exceptions for quantization

compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
This commit adjusts Cast attributes after quantization.
Related issue: #7229
Requested by https://github.com/Samsung/ONE/pull/7387#issuecomment-893116766
=> [luci] Fix Cast attributes after quantization

compiler/one-cmds/tests/onecc_neg_003.test
This commit will fix onecc_neg_003.test typo.
---
resolve #7426
=> [one-cmd] Fix typo

compiler/circle-quantizer/src/CircleQuantizer.cpp
Error messages will be printed to cerr.
1 approval please
=> [circle-quantizer] print error to cerr, not cout

tests/nnfw_api/src/ValidationTestPipelineSession.cc
This commit resolve "no assertion" on tcm analysys by adding `SUCCEED()`
=> Fix No_Assertion Error on TCM Analysis

runtime/onert/backend/gpu_cl/KernelGenerator.cc, runtime/onert/backend/gpu_cl/KernelGenerator.h, runtime/onert/backend/gpu_cl/open_cl/Operations.h, runtime/onert/backend/gpu_cl/open_cl/Spi.h, runtime/onert/backend/gpu_cl/open_cl/kernels/Relu.cc, runtime/onert/backend/gpu_cl/open_cl/kernels/Relu.h, runtime/onert/backend/gpu_cl/open_cl/selectors/SimpleSelectors.h, tests/nnfw_api/src/CircleGen.cc, tests/nnfw_api/src/CircleGen.h, tests/nnfw_api/src/one_op_tests/Relu.cc, tests/nnfw_api/src/one_op_tests/Relu6.cc
1. For gpu_cl, supports Relu, Relu6 and Leakyrelu.
2. Adds testcases.
Signed-off-by: H. Kim <hyunjun2.kim@samsung.com>
Signed-off-by: jw1772.kim <jw1772.kim@samsung.com>
=> [onert][gpu_cl] Add relu, relu6 and leakyrelu operations.

compiler/luci/pass/src/ConvertNCHWToNHWCPass.cpp
This will revise toNHWC for Ops with one x() to use convert_unary_x method.
=> [luci] Revise toNHWC to use convert_unary_x

compiler/bcq-tools/generate_bcq_metadata.py
It prepend `generate_bcq_metadata.py` to error messages.
1 Approval Please since it is basically same change to #7439, though I split this into two to conform `compiler/*` rule imposed by maintainer.
@mhs4670go or @jinevening
=> [generate_bcq_metatdata] Prepend tool name to error messages

infra/command/gen-coverage-report
This is a workdaround to resolve line coverage problem.
gpu_cl's open_cl(depth1) folder contains tflite's opencl files. This
commit will remove those files from coverage test.
=> remove tflite's open_cl files from coverage test

compiler/one-cmds/one-build, compiler/one-cmds/one-codegen, compiler/one-cmds/one-import, compiler/one-cmds/one-import-bcq, compiler/one-cmds/one-import-onnx, compiler/one-cmds/one-import-tf, compiler/one-cmds/one-import-tflite, compiler/one-cmds/one-optimize, compiler/one-cmds/one-pack, compiler/one-cmds/one-quantize, compiler/one-cmds/onecc, compiler/one-cmds/utils.py
`one-xxx` will prepend its name to messages from uncaught errors.
`onecc` (the caller) does not prepend backend names for callee any longer.
It means `one-xxx` will get prepended error messages when it is executed
directly, not through `onecc`.
Related: #7422
First part of #7427
=> [one-cmds] Prepend module name to error message by its own

compiler/tf2tfliteV2/tf2tfliteV2.py
It prepends tf2tfliteV2.py to message from uncaught errors.
=> [tf2tfliteV2] Prepend tf2tfliteV2 to error message

compiler/one-cmds/one-codegen, compiler/one-cmds/one-import-bcq, compiler/one-cmds/one-import-onnx, compiler/one-cmds/one-import-tf, compiler/one-cmds/one-import-tflite, compiler/one-cmds/one-optimize, compiler/one-cmds/one-pack, compiler/one-cmds/one-quantize
It prepends module name to error messages from c++ executables
(e.g. `circle_quantizer`, `record_minmax`, ....).
Related: #7422
A part of #7427
=> [one-cmds] Prepend name to error message from c++/bash executables

compiler/tflite2circle/driver/Driver.cpp
It writes errors to stderr, not to stdout.
One of twin from #7442
=> [tflite2circle] Write errors to stderr, not to stdout

compiler/luci-interpreter/src/kernels/CMakeLists.txt, compiler/luci-interpreter/src/kernels/PRelu.cpp, compiler/luci-interpreter/src/kernels/PRelu.h, compiler/luci-interpreter/src/kernels/PRelu.test.cpp, compiler/luci-interpreter/src/loader/KernelBuilder.cpp, compiler/luci-interpreter/src/loader/KernelBuilder.test.cpp
This commit renames Prelu->PRelu class and .cpp/.h files to support configurable build.
Draft: https://github.com/Samsung/ONE/pull/7304
=> [luci-interpreter] Rename Prelu->PRelu

compiler/circle2circle/src/Circle2Circle.cpp
This commit adds an option to enable FuseTransposeWithMean pass to circle2circle.
Signed-off-by: Andrey Kvochko <a.kvochko@samsung.com>
-----
Issue: #7335 
Draft: #7437
=> [circle2circle] Add fuse_transpose_with_mean option

res/TensorFlowLiteRecipes/Net_Mean_Mean_000/test.recipe, res/TensorFlowLiteRecipes/Net_Mean_Mean_000/test.rule, res/TensorFlowLiteRecipes/Net_Mean_Mean_001/test.recipe, res/TensorFlowLiteRecipes/Net_Mean_Mean_001/test.rule, res/TensorFlowLiteRecipes/Net_Mean_Transpose_Mean_000/test.recipe, res/TensorFlowLiteRecipes/Net_Mean_Transpose_Mean_000/test.rule
This commit adds resources for fuse_mean_with_mean pass tests.
related issue #7335
=> [res] Add Tflite Net with Mean + Mean model

compiler/circle2circle-dredd-recipe-test/test.lst
This will enable dredd test for REGRESS_ONNX_Conv_BN_MeanMean_001 model.
Signed-off-by: Andrey Kvochko <a.kvochko@samsung.com>
----
Issue: #7335 
Draft: #7437
=> [circle2circle] Dredd test for ONNX_Conv_BN_MeanMean_001

compiler/luci-interpreter/src/kernels/CMakeLists.txt, compiler/luci-interpreter/src/kernels/ReverseV2.cpp, compiler/luci-interpreter/src/kernels/ReverseV2.h, compiler/luci-interpreter/src/kernels/ReverseV2.test.cpp, compiler/luci-interpreter/src/loader/KernelBuilder.cpp, compiler/luci-interpreter/src/loader/KernelBuilder.test.cpp
This commit renames Reverse -> ReverseV2 class and .cpp/.h files to support configurable build.
Draft: https://github.com/Samsung/ONE/pull/7304
=> [luci-interpreter] Rename Reverse -> ReverseV2

compiler/record-minmax/src/MinMaxObserver.cpp
This commit adds filter that rejects numbers that are too small.
Such numbers are produced by MaxPoolWithArgmax resolving pass.
related issue: #7229
=> [record-minmax] Reject extremely small numbers from statistics

tools/nnpackage_tool/model2nnpkg/model2nnpkg.sh
`model2nnpkg.sh` will print its name for stdout message.
ONE approval please
Related: #7422
=> [model2nnpkg.sh] Print name for stdout message

compiler/one-cmds/one-build, compiler/one-cmds/one-codegen, compiler/one-cmds/one-import-bcq, compiler/one-cmds/one-import-onnx, compiler/one-cmds/one-import-tf, compiler/one-cmds/one-import-tflite, compiler/one-cmds/one-optimize, compiler/one-cmds/one-pack, compiler/one-cmds/one-quantize, compiler/one-cmds/onecc, compiler/one-cmds/utils.py
Previously, all messages from both stdout and stderr are merged when it
is executed via subprocess.Popen.
Now, it is distinguished.
ONE approval please
=> [one-cmds] Distinguish stdout and stderr message from Popen

compiler/one-cmds/utils.py
This commit changes the action way to use store_true instead of store_const.
The store_true means if the option is specified, assign the value True to verbose.
Not specifying it implies False.
The actual operation is the same as before.
=> [one-cmds] Use store_true in one-cmd utils

compiler/one-cmds/one-import-onnx, compiler/one-cmds/one-quantize
This commit fixes wrong commands.
Related: #7485 
=> [one-cmds] Fix wrong commands

infra/debian/compiler/one-compiler.install
This commit installs one-profile binary to /usr/share/one/bin.
=> [one-cmds] Add one-profile to debian package

infra/debian/compiler/docs/one-codegen.1
This commit fixes one-codegen man page.
=> [infra] Fix one-codegen man page

compiler/bcq-tools/generate_bcq_metadata.py
It fixes import error raised during exception handling.
Related: #7490
=> [one-cmds] Add missing import os error in generate_bcq_metadata.py

compiler/tf2tfliteV2/tf2tfliteV2.py
This commit redirects the error message to std.err.
=> [tf2tfliteV2] Redirect the error message

compiler/one-cmds/utils.py
This commit redirects _safemain's error message to stderr.
=> [one-cmds] Redirect _safemain's error message

compiler/loco/include/loco/IR/NodeMixins.h
This commit resolves return type conflicts in arity(void) methods which trigger a compiler error when using arm-none-eabi-gcc.
=> [luci][loco] Resolve return type conflict in arity(void) methods

compiler/luci/lang/include/luci/IR/CircleNodeMixins.h
This commit resolves return type conflict in arity(void) methods which trigger a compiler error when using arm-none-eabi-gcc.
=> [luci] Resolve return type conflict in arity(void) methods

compiler/one-cmds/utils.py
This commit changes the utils file to add the verbose option to tf2tfliteV2.
=> [one-cmds] Add verbose option to tf2tfliteV2 command

compiler/one-cmds/one-optimize
This commit applies the verbose option to one-optimize.
If --verbose option is specified, it passes the verbose option to circle2circle.
=> [one-cmds] Apply verbose option to one-optimize

compiler/circle-quantizer/src/CircleQuantizer.cpp
This commit adds verbose option.
If the --verbose option is specified, it prints out the detail logs.
=> [circle-quantizer] Add verbose operation

compiler/one-cmds/one-quantize
This commit applies verbose operation to one-quantize.
If --verbose is specified, it pass the verbose option to native modules.
=> [one-cmds] Apply verbose operation to one-quantize

compiler/record-minmax/driver/Driver.cpp
This commit adds verbose option.
If the --verbose option is specified, it prints out the detail logs.
=> [record-minmax] Apply verbose operation

compiler/one-cmds/one-import-onnx
This commit controls the tensorflow logs from onnx_tf.
If the --verbose option is specified, the tensorflow logs is shown.
By default, the tensorflow logs from onnx_tf are not displayed.
=> [one-cmds] Apply verbose option to one-import-onnx

compiler/circle2circle/src/Circle2Circle.cpp
This commit adds option to enable ResolveCustomOpMaxPoolWithArgmax pass.
related issue #7229
=> [circle2circle] Add resolve_customop_max_pool_with_argmax option

compiler/luci/pass/include/luci/Pass/SubstitutePadV2ToPadPass.h, compiler/luci/pass/src/SubstitutePadV2ToPadPass.cpp
This introduces `SubstitutePadV2ToPadPass` pass that converts `PadV2` op under a certain condition to `Pad` op.
For #7477
Draft #7478 
=> [luci] Introduce SubstitutePadV2ToPadPass

compiler/one-cmds/how-to-use-one-commands.txt, compiler/one-cmds/utils.py
This commit adds option to control ResolveMaxPoolWithArgmax pass in one-cmds.
related issue: #7229 
=> [one-cmds] Add resolve MaxPoolWithArgmax option

infra/docker/bionic/Dockerfile
This commit adds gcc-arm-none-eabi build tool on CI
=> [infra] Add gcc-arm-none-eabi build tool on CI

compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
If Pad is a product of MaxPoolWithArgmax operator
do not fit constant value into quantization range.
Quantize whole pad using input quantization parameters.
related issue: #7229
=> [circle-quantizer] Infer Pad quantization from input in special case

compiler/circle2circle-dredd-recipe-test/CMakeLists.txt
This removes unnecessary trailing space in CMakeLists.txt file.
=> [circle2circle-dredd-recipe-test] Remove Trailing Space

compiler/luci/pass/src/ResolveCustomOpMaxPoolWithArgmaxPass.cpp
This PR fixes typo in ResolveCustomOpMaxPoolWithArgmax description.
related issue #7229
fix for https://github.com/Samsung/ONE/pull/7471#discussion_r690042478
=> [luci] Fix typo in ResolveCustomOpMaxPoolWithArgmax

compiler/circle2circle/src/Circle2Circle.cpp
This commit changes the verbose behavior.
The LUCI_LOG value set by the user should have higher priority
than the value of --verbose option.
Related issue: #7521
=> [circle2circle] Change the verbose behavior

compiler/circle-quantizer/src/CircleQuantizer.cpp
This commit changes the verbose behavior.
The LUCI_LOG value set by the user should have higher priority
than the value of --verbose option.
Related issue: #7521
=> [circle-quantizer] Change the verbose behavior

compiler/record-minmax/driver/Driver.cpp
This commit changes the verbose behavior.
The LUCI_LOG value set by the user should have higher priority
than the value of --verbose option.
Related issue: #7521
=> [record-minmax] Change the verbose behavior

compiler/luci/pass/src/ResolveCustomOpMaxPoolWithArgmaxPass.cpp
This PR introduces adjustment coefficients compensating
quantization error to fix floor/cast computation.
related issue #7229 
=> [luci] Adjust coefficients in ResolveCustomOpMaxPoolWithArgmax pass

docs/conf.py, packaging/nnfw.spec, runtime/contrib/android/api/build.gradle, runtime/onert/api/include/nnfw_version.h
=> [runtime] Bump to version 1.17.0

compiler/luci/pass/src/SubstitutePadV2ToPadPass.cpp
This adds code to check if `MaxPool2D` is only-successor of `PadV2` in `SubstitutePadV2ToPadPass.cpp`.
For #7477
Draft #7478
(I will add test code in next PR.)
=> [luci] Check if MaxPool2D is Only-Successor

compiler/circle2circle-dredd-recipe-test/test.lst
This commit adds MaxPoolWithArgmax to the test list.
related issue: #7229 
=> [circle2circle-dredd-recipe-test] Add MaxPoolWithArgmax tests

compiler/luci/pass/src/ResolveCustomOpMaxPoolWithArgmaxPass.cpp
This commit adds requantization node in ResolveCustomOpMaxPoolWithArgmax
to force circle-quantizer produce tensors with real scales after floor instead of 1.0.
related issue #7229
=> [luci] Requantize tensor after floor op in ResolveCustomOpMaxPoolWithArgmax pass

compiler/luci/pass/src/ResolveCustomOpMaxPoolWithArgmaxPass.cpp
This commit reduces various versions of float type name to one style.
related issue  #7229.
Fix for https://github.com/Samsung/ONE/pull/7517#discussion_r691745509
=> [luci] Fix comments in ResolveCustomOpMaxPoolWithArgmax pass

compiler/vconone/CMakeLists.txt
This commit bumps version to 1.17.0.
=> [vconone] Bump version to 1.17.0

tools/release_tool/onert_version.sh
This commit change the way it prints nightly version.
Related: https://github.com/Samsung/ONE/issues/7421#issuecomment-901785804
=> [tools] Update onert_version.sh

compiler/one-cmds/onecc, compiler/one-cmds/onecc.template.cfg, compiler/one-cmds/tests/onecc_021.cfg, compiler/one-cmds/tests/onecc_021.test
This commit adds profile option to onecc.
It contains the test case for one-profile though onecc.
=> [one-cmds] Add profile option to onecc

compiler/luci/pass/include/luci/CircleOptimizer.h, compiler/luci/pass/src/CircleOptimizer.cpp
This adds SubstitutePadV2ToPad into CircleOptimizer.
For #7477
Draft #7478
=> [luci] Add SubstitutePadV2ToPad into CircleOptimizer

compiler/circle2circle/src/Circle2Circle.cpp
This adds 'SubstitutePadV2ToPad' optimization into Circle2Circle.
For #7477
Draft #7478
=> [circle2circle] Add SubstitutePadV2ToPad optimization

infra/scripts/docker_build_nncc.sh
This commit revisits debian nightly versioning.
Related: https://github.com/Samsung/ONE/issues/7543#issuecomment-902455460
=> [infra] Update docker build nncc script

tests/nnapi/src/TestMain.cpp
This commit disables custom argument for nnapi_gtest. Sometimes test fail by unexpected trash argument.
=> [onert/test] Disable NNAPI gtest custom argument

infra/scripts/docker_build_nncc.sh
This commit fixes docker build nncc script. `-c` option ignores outside environment variables.
=> [infra] Fix docker build nncc script

infra/debian/runtime/changelog
Use 1.17.0 in runtime debian package
=> Update runtime debian pkg version to 1.17.0

compiler/luci/pass/src/SubstitutePadV2ToPadPass.test.cpp
This commit removes unused member variable in `SubstitutePadV2ToPadPassTest`.
=> [luci] Remove unused member variable in SubstitutePadV2ToPadPassTest

compiler/one-cmds/how-to-use-one-commands.txt, compiler/one-cmds/utils.py
This adds '--substitute_padv2_to_pad' option for _one-optimize_.
For #7477
Draft #7478
=> [one-cmds] Add '--substitute_padv2_to_pad' Option

res/TensorFlowLiteRecipes/PadV2_001/test.recipe, res/TensorFlowLiteRecipes/PadV2_001/test.rule
This adds `PadV2_001` recipe and rule file into `res/TensorFlowLiteRecipes`.
This model has `PadV2`, which will be converted into `Pad` by `SubstitutePadV2ToPad` pass.
The rule file will be checked by dredd test later.
For #7477
Draft #7478
=> [res] Add PadV2_001

compiler/vconone/CMakeLists.txt
This commit bumps up to 1.18.0.
=> [vconone] Bump up to 1.18.0

docs/conf.py, packaging/nnfw.spec, runtime/contrib/android/api/build.gradle, runtime/onert/api/include/nnfw_version.h
=> [runtime] Bump to 1.18.0

compiler/one-cmds/one-profile
The common code for executing command in process is encapsulated in
utils.py. Let's use this function like all other one-cmds.
1 Approval Please
=> [one-cmds] Use utils._run instead of subprocess.Popen

compiler/mio-tflite/CMakeLists.txt
This commit adds TensorFlow include directories to mio_tflite_inc target with INTERFACE scope to allow usage of TF headers with `target_link_libraries(<target> mio_tflite_inc)`.
For #7505 
Draft #7582 
=> [mio-tflite] Add header interfaces for TF and GEMMLowp

compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
This commit adds support for const input quantization for Exp op.
=> [luci] Support const input quantization for Exp

compiler/one-cmds/tests/one-import_neg_002.test
This will revise one-import_neg_002.test with TF2.6.0 error message that
has changed since TF2.3.0.
=> [one-cmds] Revise one-import_neg_002.test

compiler/luci/pass/CMakeLists.txt, compiler/luci/pass/include/luci/CircleOptimizer.h, compiler/luci/pass/include/luci/Pass/FoldDepthwiseConv2DPass.h, compiler/luci/pass/src/CircleOptimizer.cpp, compiler/luci/pass/src/CircleOptimizer.test.cpp, compiler/luci/pass/src/FoldDepthwiseConv2DPass.cpp, compiler/luci/pass/src/FoldDepthwiseConv2DPass.test.cpp
This commit introduces FoldDepthwiseConv2D pass for folding of DepthwiseConv2D nodes with constant inputs.
For #7505 
Requires mio-tflite: #7581
=> [luci] Introduce FoldDepthwiseConv2D pass

compiler/luci/pass/src/SubstituteSqueezeToReshapePass.cpp
This commit adds passing of Squeeze's `quantparam` to Reshape in SubstituteSqueezeToReshapePass.
--------------------------
For: #7594
=> [luci/pass] Add quantparam passing in SubstituteSqueezeToReshapePass

compiler/luci/pass/src/ConvertNCHWToNHWCPass.cpp, compiler/luci/pass/src/ConvertNCHWToNHWCPass.test.cpp
This supports NHWC const for binary Ops (Add, Mul, Sub) in CovertNCHWToNHWC.
---
Related to: https://github.com/Samsung/ONE/issues/7609
=> [luci] Support NHWC const for binary Ops in ConvertNCHWToNHWC

compiler/circle2circle/src/Circle2Circle.cpp
This commit renames 'fold_depthwise_conv_2d' option in circle2circle into 'fold_dwconv' to be more consistent with other option names.
For #7505 
=> [circle2circle] Rename DConv fold option as 'fold_dwconv'

compiler/one-cmds/how-to-use-one-commands.txt, compiler/one-cmds/utils.py
This commit adds `fold_depthwise_conv_2d` optimization option to `one-build` config.
For #7505 
=> [one-cmds] Add Fold DepthwiseConv2D optimization option

.ahub/tcchecker-tca/config.yaml, tests/nnfw_api/src/one_op_tests/AveragePool2D.cc
This commit changes AveragePool2D negative test to parameter test.
=> [oenrt/test] Update AveragePool2D test

compiler/luci-interpreter/src/loader/KernelBuilder.cpp, compiler/luci-interpreter/src/loader/KernelBuilderHelper.h
This PR moves collectOutputNodes function to prepare splitting of
KernelBuilder.cpp to smaller files.
Related issue: #7288
Related DRAFT: #7605
=> [luci-interpreter] Move collectOutputNodes function

compiler/luci/pass/include/luci/CircleOptimizer.h, compiler/luci/pass/include/luci/Pass/SubstituteSplitVToSplitPass.h, compiler/luci/pass/src/CircleOptimizer.cpp, compiler/luci/pass/src/SubstituteSplitVToSplitPass.cpp, compiler/luci/pass/src/SubstituteSplitVToSplitPass.test.cpp
This adds a pass to substitute SplitV to Split.
---
Related to: #7610
Draft PR: #7621
=> [luci] Add pass to substitute SplitV to Split

compiler/circle2circle/src/Circle2Circle.cpp
This adds substitute splitv to split option.
---
Related to: #7610
Draft PR: #7621
=> [circle2circle] Add substitute splitv to split option

compiler/luci-value-test/CMakeLists.txt
This will revise luci-value-test to run in TF2.6.0 virt-environment.
=> [luci] Use TF2.6.0 for value test

compiler/luci-pass-value-test/CMakeLists.txt
This will revise luci-pass-value-test to use TF2.6.0 virt-environment.
=> [luci] Use TF2.6.0 for pass value test

compiler/pota-quantization-value-test/CMakeLists.txt
This will revise pota-quantization-value-test to run in TF2.6.0 virt-environment.
=> [pota-quant] Revise value test with TF2.6.0

compiler/one-cmds/how-to-use-one-commands.txt, compiler/one-cmds/utils.py
This adds substitute splitv to split option.
---
Related to: #7610
Draft PR: #7621
=> [one-cmds] Add substitute splitv to split option

compiler/luci-interpreter/src/kernels/SplitV.cpp
This commit fixes comparison of integers in SplitV kernel.
----------------------
Draft: #7640
=> [luci-interpreter] Fix integer comparison

compiler/mio-tflite260/CMakeLists.txt, compiler/mio-tflite260/README.md, compiler/mio-tflite260/example.cpp
This will introduce mio-tflite260 for providing 2.6.0 version.
As modules using mio-tflite needs to be ugpraded at once,
actual version will be changed to 2.6.0 when all dependent modules
uses mio-tflite260.
=> [mio-tflite260] Introduce mio-tflite260

compiler/circle-part-value-test/CMakeLists.txt
This will revise circle-part-value-test to use TF2.6.0 virt-environment.
=> [circle/partition] Use TF2.6.0 virt-env for value test

compiler/circle2circle/src/Circle2Circle.cpp
This commit adds CLI option for expansion of constant inputs to circle2circle.
For #7602 
=> [circle2circle] Add option for ExpandBroadcastConst pass

.ahub/tcchecker-tca/config.yaml
This commit removes file excludes for tcchecker. Remain excluded tests use parameter for negative tests.
=> [onert/test] Clean test file excludes for tcchecker

compiler/tfldump/CMakeLists.txt, compiler/tfldump/requires.cmake
This will revise tfldump to use mio_tflite260.
=> [tfldump] Use mio_tflite260

compiler/tflite2circle/CMakeLists.txt, compiler/tflite2circle/requires.cmake
This will revise tflite2circle to use mio_tflite260.
=> [tflite2circle] Use mio_tflite260

compiler/one-cmds/tests/one-import_neg_006.test
This will revise to skip one-import_neg_006 test for TF2.6.0 upgrade.
=> [one-cmds] Skip import_neg_006 test

compiler/luci-interpreter/src/kernels/Conv2D.test.cpp
This PR adds kernel unittest for conv2d pointwise operation.
Found that this case is not covered by unit tests during debug of #7650.
=> [luci-interpreter] Add kernel test with pointwise conv2d

compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp, compiler/luci/pass/src/QuantizedModelVerifier.test.cpp, compiler/luci/pass/src/VerifyQuantizedNodeChannelWiseGranularity.h, compiler/luci/pass/src/VerifyQuantizedNodeLayerWiseGranularity.h, compiler/luci/pass/src/VerifyQuantizedNodeS16Type.h, compiler/luci/pass/src/VerifyQuantizedNodeU8Type.h
This commit adds quantization support with verification for `SplitV` op.
---------------------------
For: #6331
=> [luci] Quantize and verify SplitV op

compiler/one-cmds/one-codegen
This enables to find backend command from system path.
=> [one-cmds] Enable finding backend command from system path

compiler/luci-interpreter/include/luci_interpreter/Interpreter.h, compiler/luci-interpreter/src/Interpreter.cpp, compiler/luci-interpreter/src/core/RuntimeGraph.cpp, compiler/luci-interpreter/src/core/RuntimeGraph.h, compiler/luci-interpreter/src/core/RuntimeModule.h, compiler/luci-interpreter/src/kernels/CMakeLists.txt, compiler/luci-interpreter/src/kernels/If.test.cpp, compiler/luci-interpreter/src/kernels/While.test.cpp, compiler/luci-interpreter/src/loader/GraphLoader.cpp, compiler/luci-interpreter/src/loader/GraphLoader.h, compiler/luci-interpreter/src/loader/KernelBuilder.test.cpp, compiler/luci-interpreter/src/loader/ModuleLoader.cpp, compiler/luci-interpreter/src/loader/ModuleLoader.h
This commit extends Interpreter, RuntimeGraph, GraphLoader and ModuleLoader interfaces with MemoryManager configuration. (add it to parameter). This is second step of merging changes from pull request #7408. First step pr #7587
issue #7355
=> [luci-interpreter] Extend Interpreter interface with MemoryManager configuration

compiler/luci-interpreter/src/loader/GraphLoader.cpp
This PR enables loading of int8 constants.
related issue #7677 
=> [luci-interpreter] Support int8 constants loading

compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
This commit adds missed `visit` method for SplitVOut node.
In addition to: #7665
=> [luci] Add missed SpliVOut quantization visit

compiler/one-cmds/how-to-use-one-commands.txt, compiler/one-cmds/utils.py
This commit adds `expand_broadcast_const` transformation option to `one-build` config.
For #7602 
=> [one-cmds] Add Expand Broadcast Const transformation

compiler/luci/pass/src/ExpandBroadcastConstPass.cpp
From second loop, current code is not reachable
because the function is always returned at first iteration.
This commit will fix it.
=> [luci] Fix unreachable loop in ExpandBroadcastConstPass

compiler/luci-interpreter/src/kernels/AveragePool2D.cpp, compiler/luci-interpreter/src/kernels/AveragePool2D.h, compiler/luci-interpreter/src/kernels/AveragePool2D.test.cpp, compiler/luci-interpreter/src/kernels/TestUtils.cpp, compiler/luci-interpreter/src/kernels/TestUtils.h, compiler/luci-interpreter/src/kernels/Utils.cpp
This pr enables int8 AveragePool2D operation.
Related issue: #7677
=> [luci-interpreter] Support int8 AveragePool2D

compiler/luci-interpreter/src/kernels/FullyConnected.cpp, compiler/luci-interpreter/src/kernels/FullyConnected.h, compiler/luci-interpreter/src/kernels/FullyConnected.test.cpp, compiler/luci-interpreter/src/kernels/TestUtils.cpp, compiler/luci-interpreter/src/kernels/TestUtils.h, compiler/luci-interpreter/src/kernels/Utils.cpp
This pr enables int8 FullyConnected operation.
Related issue: #7677
=> [luci-interpreter] Support int8 FullyConnected

compiler/luci/pass/include/luci/CircleOptimizer.h, compiler/luci/pass/src/CircleOptimizer.cpp
This supports multiple values for an AlgorithmParameter.
---
=> [luci] Support multiple values for AlgorithmParameter

tools/release_tool/onert_version.sh
It uses `date` to get build timestamp. It means it uses the default
timezone setting. It will specify to use UTC time.
=> [onert_version.sh] Use UTC time explicitly for timestamp

compiler/luci-interpreter/src/kernels/DepthwiseConv2D.cpp, compiler/luci-interpreter/src/kernels/DepthwiseConv2D.h, compiler/luci-interpreter/src/kernels/DepthwiseConv2D.test.cpp
This PR enables int8 quantizer depthwise conv2d.
Related issue #7677 
=> [luci-interpreter] Support int8 depthwise conv2d

compiler/luci/pass/src/ResolveCustomOpAddPass.cpp, compiler/luci/pass/src/ResolveCustomOpBatchMatMulPass.cpp, compiler/luci/pass/src/ResolveCustomOpBatchMatMulPass.test.cpp, compiler/luci/pass/src/ResolveCustomOpMatMulPass.cpp, compiler/luci/pass/src/ResolveCustomOpMaxPoolWithArgmaxPass.cpp
This will revise to use bracket for flatbuffers include.
=> [luci/pass] Use bracket for flatbuffers include

compiler/tflchef/core/src/CustomOp/AddV2.cpp, compiler/tflchef/core/src/CustomOp/All.cpp, compiler/tflchef/core/src/CustomOp/BatchMatMulV2.cpp, compiler/tflchef/core/src/CustomOp/BroadcastTo.cpp, compiler/tflchef/core/src/CustomOp/MatMul.cpp, compiler/tflchef/core/src/CustomOp/MatrixBandPart.cpp, compiler/tflchef/core/src/CustomOp/MaxPoolWithArgmax.cpp
This will revise to use bracket for flatbuffers include.
=> [tflchef] Use bracket for flatbuffers include

compiler/circledump/CMakeLists.txt
This will revise to use with version flatbuffres-1.10.
=> [circledump] Revise to use flatbuffers-1.10

compiler/luci-interpreter/src/loader/KernelBuilder.cpp
This commit makes `KernelBuilder`'s logic easier to understand and reduces reallocations.
=> [luci-interpreter] Simplify KernelBuilder.cpp

infra/cmake/packages/FlatBuffersConfig.cmake
This will remove versionless name for FlatBuffers library.
=> [infra] FlatBuffersConfig remove old versionless

compiler/luci-interpreter/include/luci_interpreter/BuddyMemoryManager.h, compiler/luci-interpreter/src/BuddyMemoryManager.cpp, compiler/luci-interpreter/src/BuddyMemoryManager.test.cpp, compiler/luci-interpreter/src/CMakeLists.txt
This pr adds BuddyMemoryManager to luci_interpreter. This manager is implementation of buddy memory allocator(https://en.wikipedia.org/wiki/Buddy_memory_allocation).
Related issue: #7571
=> [luci-interpreter] Introduce BuddyMemoryManager

compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
This fixes warning in propagate_pad_v2_quantparam.
=> [luci] Fix warning of pad_v2 const quantization

compiler/enco/frontend/tflite/CMakeLists.txt
=> [enco] Use explit flatbuffers ver 1.10

compiler/exo/CMakeLists.txt
=> [exo] Use explit flatbuffers ver 1.10

compiler/luci/pass/CMakeLists.txt
=> [luci/pass] Use explit flatbuffers ver 1.10

compiler/mio-circle/CMakeLists.txt
=> [mio-circle] Use explit flatbuffers ver 1.10

compiler/mir/src/mir_tflite_importer/CMakeLists.txt
=> [mir/tflite_imp] Use explit flatbuffers ver 1.10

compiler/pota-quantization-value-test/CMakeLists.txt
=> [pota-quant-val-test] Use explit flatbuffers ver 1.10

compiler/mio-tflite/CMakeLists.txt
=> [mio-tflite] Use explit flatbuffers ver 1.10

compiler/luci-interpreter/src/kernels/Softmax.cpp, compiler/luci-interpreter/src/kernels/Softmax.test.cpp
This PR enables Softmax for int8 datatype.
related issue: #7677
=> [luci-interpreter] Enable Softmax for int8

compiler/luci-interpreter/src/BuddyMemoryManager.cpp
This pr adds an assert to the buddy memory manager constructor.
=> [luci-interpreter] Add assert in BuddyMemoryManager

compiler/circle2circle/src/Circle2Circle.cpp
This supports the fuse_add_with_fully_connected option.
---
Related to: #7724
Draft PR: #7746
=> [circle2circle] Support Fuse Add with FC

compiler/luci-interpreter/pal/linux/PALArgMax.h, compiler/luci-interpreter/pal/linux/PALResizeBilinear.h, compiler/luci-interpreter/pal/linux/pal.cmake, compiler/luci-interpreter/pal/mcu/pal.cmake
This PR moves TF version from 2.3.0 to 2.6.0.
related issue: #7288
=> [luci-interpreter] Bump used TF version to 2.6.0

compiler/luci-interpreter/src/CMakeLists.txt
This PR moves buddy allocator below ENABLE_TEST check.
=> [luci-interpreter] Fix BuddyAllocator tests build

infra/nncc/CMakeLists.txt
This PR introduces STATIC_LUCI option to enable static build of luci libraries.
For #7759
=> [infra] Introduce STATIC_LUCI option

compiler/luci-interpreter/include/luci_interpreter/StaticMemoryManager.h, compiler/luci-interpreter/include/luci_interpreter/core/Tensor.h, compiler/luci-interpreter/src/CMakeLists.txt, compiler/luci-interpreter/src/StaticMemoryManager.cpp
This pr adds static memory manager to luci-interpreter.
issue: #7522
draft: #7573
=> [luci-interpreter] Add StaticMemoryManager

compiler/luci-interpreter/pal/mcu/PALConv2d.h
This PR suppresses warnings for unused variables in Conv2d PAL for MCU.
=> [luci-interpreter] Suppress warnigns for unused arguments in MCU PAL

compiler/luci-interpreter/pal/mcu/pal.cmake
This PR removes SYSTEM mode from TF headers in MCU PAL.
See [known issues](https://github.com/Samsung/ONE/pull/7764/files#diff-7c6fe0cbd157a73316fbb017ac971e989b0c3b0e714969307c8b24257c78cb7eR43-R51) for details
=> [luci-interpreter] Remove SYSTEM mode from TF headers

compiler/luci/CMakeLists.txt, compiler/luci/env/CMakeLists.txt, compiler/luci/export/CMakeLists.txt, compiler/luci/import/CMakeLists.txt, compiler/luci/lang/CMakeLists.txt, compiler/luci/log/CMakeLists.txt, compiler/luci/logex/CMakeLists.txt, compiler/luci/partition/CMakeLists.txt, compiler/luci/pass/CMakeLists.txt, compiler/luci/profile/CMakeLists.txt, compiler/luci/service/CMakeLists.txt, infra/nncc/CMakeLists.txt
This PR introduces option to select
shared/static type of generated library.
This is a cosmetic change, to suppress cmake warning in case we build with compiler that can not produce shared libraries.
I ran into this when compiled luci-interpreter for MCU (and used `arm-none-eabi-gcc`) #7288 
CMake still produces all libraries, it just forces them to have STATIC type.
This change is not mandatory, I can close it if we do not want this complication.
=> [luci] Configurable library type

infra/cmake/modules/ExternalSourceTools.cmake
This commit adds failure in cases when package is not extracted from archive.
--------------
Related with: #7783
=> [infra] Add failure when package not extracted

compiler/tfl-inspect/src/Reader.cpp, compiler/tfl-inspect/src/Reader.h
This will introduce builtin_code_neutral method to support tflite v3a schema.
=> [tfl-inspect] Introduce builtin_code_neutral

compiler/tflite2circle/src/CircleModel.cpp
This will revice circle description to 'ONE-tflite2circle' to reflect
this tool's name.
=> [tflite2circle] Revise description

infra/nnfw/cmake/packages/ARMComputeConfig.cmake
ARMCompute still build some tests. Let's remove remain test build.
=> [infra] Remove remain ARMCompute test build

compiler/luci-interpreter/src/loader/CMakeLists.txt, compiler/luci-interpreter/src/loader/GraphLoader.cpp, compiler/luci-interpreter/src/loader/nodes/Conv2D.cpp
This pr adds reading execution plan annotations to luci-interpreter.
Add reading execution order from node annotations in GraphLoader and reading offset also from node annotations for im2col temporary tensor.
issue #7522
=> [luci-interpreter] Add reading execution plan annotations.

compiler/one-cmds/one-quantize
This adds input_model_dtype to one-quantize.
---
Related to: https://github.com/Samsung/ONE/issues/7896
=> [one-cmds] Add input_model_dtype to one-quantize

compiler/luci/pass/CMakeLists.txt
This commit matches FlatBuffers find version with what actually linked.
=> [luci] Fix find version

compiler/luci/log/include/luci/Log.h, compiler/luci/log/src/Log.cpp
This commit revises logger to print proper log message.
From this PR, logger will do like this.
`LUCI_LOG=0` -> print nothing
`LUCI_LOG=1` -> print `FATAL(l)` things
`LUCI_LOG=2` -> print `FATAL(l)` + `ERROR(l)` things
`LUCI_LOG=3` -> print `FATAL(l)` + `ERROR(l)` + `WARN(l)` things
`LUCI_LOG=4` -> print `FATAL(l)` + `ERROR(l)` + `WARN(l)` + `INFO(l)` things
Related: #7893 
=> [luci] Revise logger

compiler/luci-interpreter/src/loader/nodes/Conv2D.cpp
This will revise Conv2D loader to correct for empty bias.
=> [luci-interpreter] Revise Conv2D for no bias

res/TensorFlowLiteRecipes/Part_Tanh_FC_nobias/test.recipe
- tflchef recope for model of Tanh - FC with no bias
- Reference model for #7920
=> Tanh_FC_nobias TFL recipe

compiler/luci/partition/src/PartitionMerge.cpp
This will revise partition merge logic to skip CircleOutputExclude node
like CircleConst to fix FullyConnected with no bias network.
=> [luci/partition] Fix for FC with no bias

res/TensorFlowLiteRecipes/Conv2D_005/test.recipe
This will introduce Conv2D_005 recipe that having no bias for Conv2D.
=> [res] Introduce Conv2D_005 recipe

compiler/luci/import/include/luci/Import/CircleReader.h, compiler/luci/import/src/CircleReader.cpp
This commit adds `_native_subgraph` and renames `_model_ptr` to `_native_model` in order to use them similar to `_model` and `_current_subgraph` members for direct API support.
=> [luci/import] Add and rename CircleReader members

compiler/luci/import/include/luci/Import/CircleReader.h, compiler/luci/import/src/CircleReader.cpp, compiler/luci/import/src/CircleReader.test.cpp
This commit adds VectorWrapper struct which helps to use `flatbuffers::Vector<>` from direct-access API.
ONE-DCO-1.0-Signed-off-by: Maksim Bronnikov max120199@gmail.com
---------------------
For: #7886
Draft: #7901
=> [luci/import] Add VectorWrapper helper struct

compiler/luci/import/include/luci/Import/CircleReader.h, compiler/luci/import/src/CircleReader.cpp
This commit adds helpers duplication for direct structures.
For: #7886
Draft: #7901
=> [luci/import] Duplicate helpers for direct structures

compiler/luci/import/src/Importer.cpp
This commit replaces usage of inputs(), outputs() and name() methods to direct-access prototypes.
-------------------
For: #7886
Draft: #7901
=> [luci/import] Use direct access for inputs, outputs and name

compiler/luci/import/src/CircleReader.cpp
This commit adds definitions for opcode_name and builtin_code methods.
--------------
For: #7886
Draft: #7901
=> [luci/import] Add opcode_name and builtin_code definitions

compiler/luci/import/src/CircleImportMetadata.cpp
This commit replaces usage of metadata() to native_metadata().
For: #7886
Draft: #7901
=> [luci/import] Use direct access for metadata

compiler/luci/import/src/GraphBuilder.cpp, compiler/luci/import/src/GraphBuilderMultiOutput.cpp, compiler/luci/import/src/Nodes/CircleCustom.cpp, compiler/luci/import/src/Nodes/CircleWhile.cpp
This commit replaces usage of opcodes() to native_opcodes() method.
-----------------
For: #7886
Draft: #7901
=> [luci/import] Use direct access for opcodes

compiler/luci/import/src/Importer.cpp
This commit replaces usage of operators() to native_operators() method.
---------------
For: #7886
Draft: #7901
=> [luci/import] Use direct access for operators

compiler/luci/import/include/luci/Import/CircleReader.h, compiler/luci/import/src/CircleReader.cpp
This commit fixes native_name methods in case of nullptr subgraph's name.
----------
Fix for importer tests.
=> [luci/import] Fix native_name with nullptr case

compiler/luci/import/src/Nodes/CircleCast.cpp, compiler/luci/import/src/Nodes/CircleConst.cpp, compiler/luci/import/src/Nodes/CircleDepthToSpace.cpp, compiler/luci/import/src/Nodes/CircleDepthwiseConv2D.cpp, compiler/luci/import/src/Nodes/CircleElu.cpp, compiler/luci/import/src/Nodes/CircleEqual.cpp, compiler/luci/import/src/Nodes/CircleExp.cpp, compiler/luci/import/src/Nodes/CircleExpandDims.cpp, compiler/luci/import/src/Nodes/CircleFloorDiv.cpp, compiler/luci/import/src/Nodes/CircleFloorMod.cpp, compiler/luci/import/src/Nodes/CircleGatherNd.cpp, compiler/luci/import/src/Nodes/CircleGreater.cpp, compiler/luci/import/src/Nodes/CircleGreaterEqual.cpp, compiler/luci/import/src/Nodes/CircleIf.cpp
This commit replaces tensors() to native_tensors() in all builders from CircleAbs to CircleIf.
For: #7886
Draft: #7901
=> [luci/import] Use direct-access tensors from Abs to If

compiler/luci/import/src/GraphBuilder.cpp, compiler/luci/import/src/GraphBuilderMultiOutput.cpp, compiler/luci/import/src/Importer.cpp, compiler/luci/import/src/ValidateHelpers.cpp
This commit replaces tensors() to native_tensors() in Importer, ValidateHelpers and GraphBuilders base classes.
For: #7886
Draft: #7901
=> [luci/import] Use direct-access tensors

compiler/luci/partition/src/PartitionPGroups.cpp
This will revise creating pgroup for multioutput virtual nodes to follow
group of the owner node.
=> [luci/partition] Revise pgroup for multioutput virt ndoes

infra/debian/runtime/changelog
Use 1.19.0 as debian pkg version
=> [onert] debian pkg verison 1.19.0

compiler/luci/partition/src/PartitionPGroups.cpp
This will remove unused codes in produce_pgroups method.
=> [luci/partition] Remove unused in produce_pgroups

compiler/luci-value-test/luci_eval_verifier.py
This will revise luci_eval_verifier python script to use variables.
- this is to prepare next revision to support SignatureDef
=> [luci] Revise eval_verifier

compiler/circle-part-value-test/parts/Net_UnpackAdd_001.001.part, compiler/circle-part-value-test/parts/Net_UnpackAdd_001.002.part, compiler/circle-part-value-test/parts/Net_UnpackAdd_001.part, compiler/circle-part-value-test/parts/Part_Split_Add_000.part, compiler/circle-part-value-test/test.lst
This will enable circle-partitioner value testing of multi-output node types.
=> [circle-partitioner] Value tests of multi-output nodes

compiler/luci-value-test/luci_eval_verifier.py
This will revise luci_eval_verifier to read SignatureDef and use
output tensor order according to the SignatureDef's outputs value.
=> [luci] Support SignatureDef in eval verifier

compiler/luci-pass-value-test/eval_result_verifier.py
This will revise eval_result_verifier.py using variables.
This is to apply tflite SignatureDef better.
=> [luci] Revise pass-value-test with variables

compiler/luci-pass-value-test/eval_result_verifier.py
This will revise eval_result_verifier to read tflite SignatureDef and
use output tensor order according to the SignatureDef's outputs value.
=> [luci] Support SignatureDef in pass value test

compiler/luci-pass-value-test/test.lst
This will enable value test with SignatureDef with multiple outputs.
=> [luci-pass] Value test with SignatureDef

compiler/circle-part-value-test/parts/SignatureDef_MultiOut_000.part, compiler/circle-part-value-test/parts/SignatureDef_MultiOut_001.part, compiler/circle-part-value-test/test.lst
This will enable value test with SignatureDef with multiple outputs.
=> [circle-partition] Value test with SignatureDef

compiler/luci/import/src/CircleImportMetadata.cpp, compiler/luci/import/src/Importer.cpp, compiler/luci/import/src/Importer.test.cpp
This PR enables import of graphs with with execution plan defined for
subset of operations.
related issue: #7831
for comment: https://github.com/Samsung/ONE/pull/7903#discussion_r740456803
=> [luci] Support import of partially defined execution plan

compiler/luci/import/src/Nodes/CircleLess.cpp, compiler/luci/import/src/Nodes/CircleLessEqual.cpp, compiler/luci/import/src/Nodes/CircleLog.cpp, compiler/luci/import/src/Nodes/CircleLogicalAnd.cpp, compiler/luci/import/src/Nodes/CircleLogicalNot.cpp, compiler/luci/import/src/Nodes/CircleLogicalOr.cpp, compiler/luci/import/src/Nodes/CircleLogistic.cpp, compiler/luci/import/src/Nodes/CircleMatrixDiag.cpp, compiler/luci/import/src/Nodes/CircleMatrixSetDiag.cpp
This commit replaces tensors() to native_tensors() in all builders from `CircleLess` to `CircleMatrixSetDiag`.
For: #7886
Draft: #7901
=> [luci/import] Use direct tensors from Less to MatrixSetDiag

compiler/luci/import/src/Nodes/CircleNonMaxSuppressionV4.cpp, compiler/luci/import/src/Nodes/CircleNonMaxSuppressionV5.cpp, compiler/luci/import/src/Nodes/CircleNotEqual.cpp, compiler/luci/import/src/Nodes/CircleOneHot.cpp
This commit replaces tensors() to native_tensors() in all builders from `CircleNonMaxSuppressionV4` to `CircleOneHot`.
--------------
For: #7886
Draft: #7901
=> [luci/import] Use direct tensors from NonMaxSuppression to OneHot

compiler/luci/import/src/Nodes/CircleReduceAny.cpp, compiler/luci/import/src/Nodes/CircleReduceProd.cpp, compiler/luci/import/src/Nodes/CircleReshape.cpp, compiler/luci/import/src/Nodes/CircleReverseSequence.cpp, compiler/luci/import/src/Nodes/CircleReverseV2.cpp
This commit replaces tensors() to native_tensors() in all builders from `CircleReduceAny` to `CircleReverseV2`.
--------------
For: #7886
Draft: #7901
=> [luci/import] Use direct tensors from ReduceAny to Reverse

compiler/luci/import/src/Importer.test.cpp
This PR changes suite name from TensorFlowLiteImport to CircleImport.
For https://github.com/Samsung/ONE/pull/7940#discussion_r746061209
=> [luci] Rename Import testsuite

res/PyTorchExamples/examples/BatchToSpaceND/__init__.py, res/PyTorchExamples/examples/PixelShuffle/__init__.py, res/PyTorchExamples/examples/SpaceToBatchND/__init__.py, res/PyTorchExamples/examples/SpaceToDepth/__init__.py
This PR adds examples:
- BatchToSpaceND
- SpaceToBatchND
- PixelShuffle (DepthToSpace)
- SpaceToDepth
Related issue:  #7939 
=> [res] PyTorch examples for spatial block rearrangement operations

res/PyTorchExamples/examples/MaxPool2d-am/__init__.py
This PR adds MaxPool2d with indeces output in PyTorch examples.
=> [res] MaxPool2d with argmax for PyTorch Examples

compiler/luci/import/src/Nodes/CircleRound.cpp, compiler/luci/import/src/Nodes/CircleRsqrt.cpp, compiler/luci/import/src/Nodes/CircleScatterNd.cpp, compiler/luci/import/src/Nodes/CircleSegmentSum.cpp, compiler/luci/import/src/Nodes/CircleSelect.cpp, compiler/luci/import/src/Nodes/CircleSelectV2.cpp, compiler/luci/import/src/Nodes/CircleSin.cpp
This commit replaces tensors() to native_tensors() in all builders from `CircleRound` to `CircleSin`.
For: #7886
Draft: #7901
=> [luci/import] Use direct tensors from Round to Sin

compiler/luci/import/src/Nodes/CircleSquare.cpp, compiler/luci/import/src/Nodes/CircleSquaredDifference.cpp, compiler/luci/import/src/Nodes/CircleTanh.cpp, compiler/luci/import/src/Nodes/CircleTile.cpp, compiler/luci/import/src/Nodes/CircleTopKV2.cpp
This commit replaces tensors() to native_tensors() in all builders from `CircleSquare` to `CircleTopKV2`.
------------
For: #7886
Draft: #7901
=> [luci/import] Use direct tensors from Square to TopKV2

compiler/luci/import/src/Nodes/CircleTransposeConv.cpp, compiler/luci/import/src/Nodes/CircleUnpack.cpp, compiler/luci/import/src/Nodes/CircleWhere.cpp, compiler/luci/import/src/Nodes/CircleWhile.cpp
This commit replaces tensors() to native_tensors() in all builders from `CircleTransposeConv` to `CircleWhile`.
---------------
For: #7886
Draft: #7901
=> [luci/import] Use direct tensors from TransposeConv to While

compiler/luci/import/include/luci/Import/CircleReader.h, compiler/luci/import/src/CircleReader.cpp
This commit removes `tensors_ptr` from CircleReader with related type aliases.
-------------------
For: #7886
Draft: #7901
=> [luci/import] Remove tensors_ptr from CircleReader

res/PyTorchExamples/ptem.py
This PR adds onnx version paramter supprot in PyTorchExamples.
=> [res] ONNX opset version parameter in PyTorchExamples

compiler/luci/import/include/luci/Import/CircleReader.h
This commit redefines num_subgraph() method using direct-access structures.
------------
For: #7886
Draft: #7901
=> [luci/import] Redefine num_subgraph with direct structures

compiler/luci/import/src/CircleImportMetadata.cpp, compiler/luci/import/src/Nodes/CircleConst.cpp
This commit replaces usage of buffers() to native_buffers() method.
For: #7886
Draft: #7901
=> [luci/import] Use direct access for buffers

res/PyTorchExamples/examples/interpolate/__init__.py
This PR adds interpolate PyTorch example with bilinear mode.
=> [res] interpolate PyTorch example

compiler/luci/import/include/luci/Import/CircleReader.h, compiler/luci/import/src/CircleReader.cpp
This commit removes UnPack API from CircleReader class.
-------------------------------
For: #7886
Draft: #7901
=> [luci/import] Remove UnPack API from CircleReader class

compiler/luci/import/include/luci/Import/CircleReader.h, compiler/luci/import/src/Importer.cpp
This commit removes native prefix from input, outputs, name and data_format methods.
--------------------
For: #7886
Draft: #7901
=> [luci/import] Rename inputs, outputs, name and data_format

compiler/luci-interpreter/pal/cmsisnn/PALConv2d.h
This commit introduces Conv2dS8 CMSIS-NN optimized kernel support.
=> [luci-interpreter] Support Conv2dS8 CMSIS-NN optimized kernel

compiler/luci/import/include/luci/Import/CircleReader.h, compiler/luci/import/src/CircleImportMetadata.cpp, compiler/luci/import/src/CircleReader.cpp, compiler/luci/import/src/GraphBuilder.cpp, compiler/luci/import/src/GraphBuilderMultiOutput.cpp, compiler/luci/import/src/Importer.cpp, compiler/luci/import/src/Nodes/CircleConst.cpp, compiler/luci/import/src/Nodes/CircleCustom.cpp, compiler/luci/import/src/Nodes/CircleWhile.cpp
This commit removes native_ prefix from other CircleReader's methods.
For: #7886
Draft: #7901
=> [luci/import] Remove native_ prefix from CircleReader methods

compiler/luci/import/include/luci/Import/CircleReader.h, compiler/luci/import/src/CircleReader.cpp
This commit returns source names for members of CircleReader.
------------
For: #7886
Draft: #7901
=> [luci/import] Remove native_ prefix from member names

compiler/luci/pass/src/PropagateQuantParamPass.cpp
This removes unnecessary successor check.
=> [luci] Remove unnecessary check in PropagateQuantParam

compiler/luci/partition/src/PartitionMerge.cpp
This will fix is_input_same method to check group value not the group ptr.
=> [luci/part] Fix is_input_same to check group value

compiler/luci/partition/src/PartitionMerge.cpp, compiler/luci/partition/src/PartitionPGroups.cpp
This will revise condition for CircleOutputExclude node as this node
type is treated in preparing PGroup objects.
=> [luci/part] Revise for OutputExclude

compiler/circle-part-value-test/parts/Part_Mul_Sqrt_FC_nobias_000_000.part, compiler/circle-part-value-test/parts/Part_Mul_Sqrt_FC_nobias_000_001.part, compiler/circle-part-value-test/parts/Part_Mul_Sqrt_FC_nobias_000_002.part, compiler/circle-part-value-test/parts/Part_Tanh_FC_nobias.part, compiler/circle-part-value-test/parts/Part_Tanh_FC_nobias_001.part, compiler/circle-part-value-test/parts/Part_Tanh_FC_nobias_002.part, compiler/circle-part-value-test/parts/Part_Tanh_FC_nobias_003.part, compiler/circle-part-value-test/test.lst
This will enable several tests for FullyConnected with no bias network.
=> [circle-part] Test for FullyConnected with no bias

compiler/luci-interpreter/pal/cmsisnn/pal.cmake
This commit adds CMSISNN sources to luci_interpreeter_cmsisnn_pal library.
=> [luci-interpreter] Add CMSISNN sources to luci_interpreeter_cmsisnn_pal library

compiler/luci-interpreter/pal/cmsisnn/PALDepthwiseConv2d.h, compiler/luci-interpreter/pal/linux/PALDepthwiseConv2d.h, compiler/luci-interpreter/pal/mcu/PALDepthwiseConv2d.h, compiler/luci-interpreter/src/kernels/DepthwiseConv2D.cpp
This commit introduces DepthwiseConv2dS8 CMSIS-NN optimized kernel support.
=> [luci-interpreter] Support DepthwiseConv2dS8 CMSIS-NN optimized kernel

compiler/luci-interpreter/pal/cmsisnn/PALFullyConnected.h, compiler/luci-interpreter/pal/linux/PALFullyConnected.h, compiler/luci-interpreter/pal/mcu/PALFullyConnected.h, compiler/luci-interpreter/src/kernels/FullyConnected.cpp
This commit introduces FullyConnectedS8 CMSIS-NN optimized kernel support.
=> [luci-interpreter] Support FullyConnectedS8 CMSIS-NN optimized kernel

compiler/one-cmds/one-prepare-venv
This will upgrade one-cmds venv to use TF2.6.0.
=> [one-cmds] Upgrade venv to TF2.6.0

compiler/luci-interpreter/pal/cmsisnn/PALAveragePool2d.h, compiler/luci-interpreter/pal/linux/PALAveragePool2d.h, compiler/luci-interpreter/pal/mcu/PALAveragePool2d.h, compiler/luci-interpreter/src/kernels/AveragePool2D.cpp
This commit introduces AveragePool2DS8 CMSIS-NN optimized kernel support.
=> [luci-interpreter] Support AveragePool2DS8 CMSIS-NN optimized kernel

compiler/circle-execution-plan/README.md, compiler/circle-execution-plan/src/CircleExecutionPlan.cpp, compiler/circle-execution-plan/src/ExecutionPlanner.cpp, compiler/circle-execution-plan/src/ExecutionPlanner.h
This pr makes some fixes in circle-execution-planner. It changes namespace, method naming, some comments and code style.
Fixes from previous pr with circle-execution-planner: #7813
=> [circle-execution-plan] Some fixes in execution planner

runtime/onert/backend/gpu_cl/ClTensorManager.h, runtime/onert/backend/gpu_cl/MemoryManager.h, runtime/onert/backend/gpu_cl/TensorManager.h, runtime/onert/backend/gpu_cl/ex/InferenceContextEx.h
This commit changes template class ClMemoryManager to general class and remove class alias MemoryManager.
=> [onert/gpu-cl] Revise ClMemoryManager

compiler/luci/pass/include/luci/CircleOptimizer.h, compiler/luci/pass/include/luci/Pass/PropagateQuantParamPass.h, compiler/luci/pass/src/CircleOptimizer.cpp, compiler/luci/pass/src/PropagateQuantParamPass.cpp
This supports TF-style MaxPool quantization.
---
Related to: #8055
Draft PR: #8056
=> [luci] Support TF-style MaxPool quantization

compiler/luci-interpreter/pal/cmsisnn/PALConv2d.h, compiler/luci-interpreter/pal/linux/PALConv2d.h, compiler/luci-interpreter/pal/mcu/PALConv2d.h, compiler/luci-interpreter/src/kernels/Conv2D.cpp, compiler/luci-interpreter/src/kernels/Conv2D.h, compiler/luci-interpreter/src/loader/nodes/Conv2D.cpp
Implement and use PAL interface for temporary buffers allocation for Conv2d.
This is first task from issue #7906 
=> [luci-interpreter] New PAL interface for Conv2d temporary buffers

compiler/luci-interpreter/pal/cmsisnn/PALDepthwiseConv2d.h, compiler/luci-interpreter/pal/linux/PALDepthwiseConv2d.h, compiler/luci-interpreter/pal/mcu/PALDepthwiseConv2d.h, compiler/luci-interpreter/src/kernels/DepthwiseConv2D.cpp, compiler/luci-interpreter/src/kernels/DepthwiseConv2D.h, compiler/luci-interpreter/src/kernels/DepthwiseConv2D.test.cpp, compiler/luci-interpreter/src/loader/nodes/DepthwiseConv2D.cpp
Implement and use PAL interface for temporary buffers allocation for DepthwiseConv2D.
This is the second task from issue #7906
=> [luci-interpreter] New PAL interface for DepthwiseConv2D temporary buffers

compiler/circle-execution-plan/src/ExecutionPlanner.cpp, compiler/circle-execution-plan/src/ExecutionPlanner.h
This pr adds support choosing different planning modes in execution planer.
related issue: #7906
=> [circle-execution-plan] Support different planning modes in execution planer

compiler/circle-quantizer/src/CircleQuantizer.cpp
This supports TF-style MaxPool Op.
---
Related to: #8055
Draft PR: #8056
=> [circle-quantizer] Support TF-style MaxPool Op

tools/tflitefile_tool/option_printer.py
model_parser prints strided_slice's 5 option fields like :
```
Output Tensors[45]
Tensor   45 : buffer 46    |  Empty | FLOAT32 | Memory 24.0K  | Shape [4, 1536] (b'strided_slice_3')
Options
begin_mask(5), end_mask(5), ellipsis_mask(0), new_axis_mask(0), shrink_axis_mask(2)
```
=> [tflitefile_tool] Print STRIDED_SLICE's option

compiler/luci-interpreter/pal/cmsisnn/PALAveragePool2d.h, compiler/luci-interpreter/pal/linux/PALAveragePool2d.h, compiler/luci-interpreter/pal/mcu/PALAveragePool2d.h, compiler/luci-interpreter/src/kernels/AveragePool2D.cpp, compiler/luci-interpreter/src/kernels/AveragePool2D.h, compiler/luci-interpreter/src/kernels/AveragePool2D.test.cpp, compiler/luci-interpreter/src/loader/nodes/AveragePool2D.cpp
Implement and use PAL interface for temporary buffers allocation for AvgPool2D .
This is the third task from issue #7906
=> [luci-interpreter] New PAL interface for AvgPool2D temporary buffers

compiler/luci-interpreter/include/luci_interpreter/Interpreter.h, compiler/luci-interpreter/src/Interpreter.cpp
This PR eliminates default value for memory_manager in interpreter constructors.
=> [luci-interpreter] Split interpreter constructor in two

compiler/one-cmds/one-quantize
This supports TF-style MaxPool Quantization.
---
Related to: #8055
Draft PR: #8056
=> [one-cmds] Support TF-style MaxPool Quantization

infra/nncc/CMakeLists.txt
This PR introduces NNCC_LIBRARY_NO_PIC option
to disable PIC for luci-interpreter related components.
related issue: #7288
=> [infra] Introduce NNCC_LIBRARY_NO_PIC option

compiler/luci-interpreter/src/kernels/Slice.cpp, compiler/luci-interpreter/src/kernels/Slice.test.cpp
This pr enables int8 Slice operation in luci-interpreter.
issue: #8075 
=> [luci-interpreter] Support INT8 Slice operation

compiler/luci-interpreter/src/kernels/Pad.cpp, compiler/luci-interpreter/src/kernels/Pad.test.cpp
This pr enables int8 Pad operation in luci-interpreter.
issue: #8075
=> [luci-interpreter] Support INT8 Pad operation

compiler/luci-interpreter/pal/cmsisnn/PALConv2d.h, compiler/luci-interpreter/pal/linux/PALConv2d.h, compiler/luci-interpreter/pal/mcu/PALConv2d.h, compiler/luci-interpreter/src/loader/nodes/Conv2D.cpp
This commit lets change data type for temporary tensors for Conv2d in PAL interface using new tensor method.
according to https://github.com/Samsung/ONE/pull/8047#discussion_r758394641 comment
=> [luci-interpreter] Let PAL cast temporary tensors for Conv2d

compiler/luci-interpreter/include/luci_interpreter/Interpreter.h, compiler/luci-interpreter/src/Interpreter.cpp
This PR removes _memory_manager field, because it is unused.
=> [luci-interpreter] Remove redundant field

compiler/locop/CMakeLists.txt
This commit adds NNCC_LIBRARY_NO_PIC option to have an opportunity to disable POSITION_INDEPENDENT_CODE property.
ONE-DCO-1.0-Signed-off-by: Vyacheslav Bazhenov slavikmipt@gmail.com
=> [locop] Add NNCC_LIBRARY_NO_PIC option to CMakeLists.txt

compiler/angkor/CMakeLists.txt
This commit adds NNCC_LIBRARY_NO_PIC option to have an opportunity to disable POSITION_INDEPENDENT_CODE property.
ONE-DCO-1.0-Signed-off-by: Vyacheslav Bazhenov slavikmipt@gmail.com
=> [angkor] Add NNCC_LIBRARY_NO_PIC option to CMakeLists.txt

compiler/hermes/CMakeLists.txt
This commit adds NNCC_LIBRARY_NO_PIC option to have an opportunity to disable POSITION_INDEPENDENT_CODE property.
ONE-DCO-1.0-Signed-off-by: Vyacheslav Bazhenov slavikmipt@gmail.com
=> [hermes] Add NNCC_LIBRARY_NO_PIC option to CMakeLists.txt

compiler/mio-tflite260/include/mio_tflite260/Helper.h, compiler/mio-tflite260/src/Helper.cpp
In case of `mio-circle` is updated, it would be better to introduce `mio::tflite` namespace.
For this, `tflite::*` for `schema_generated.h` is changed to `::tflite::*`.
---
Parent Issue :#8050
Draft : #8051
Inspired by, and thanks to https://github.com/Samsung/ONE/pull/8082#discussion_r762662258
=> [mio-tflite260] Add mio::tflite namespace

compiler/luci-interpreter/pal/cmsisnn/PALDepthwiseConv2d.h, compiler/luci-interpreter/pal/linux/PALDepthwiseConv2d.h, compiler/luci-interpreter/pal/mcu/PALDepthwiseConv2d.h, compiler/luci-interpreter/src/kernels/DepthwiseConv2D.cpp, compiler/luci-interpreter/src/loader/nodes/DepthwiseConv2D.cpp
This commit lets set data type for temporary tensors in PAL interface for DepthwiseConv2D kernel.
according to #8047 (comment) comment
=> [luci-interpreter] Let PALDepthwiseConv2d cast temporary tensors

compiler/luci-interpreter/src/kernels/Concatenation.cpp, compiler/luci-interpreter/src/kernels/Concatenation.test.cpp
This pr enables int8 Concatenation operation in luci-interpreter.
issue: #8075
=> [luci-interpreter] Support INT8 Concatenation operation

compiler/hermes/include/hermes/core/Message.h, compiler/hermes/include/hermes/core/MessageBuffer.h
This commit initializes severity member in hermes::Message.
Signed-off-by: Andrey Shedko <a.shedko@samsung.com>
=> [ONE/hermes] Initialize Severity in Message

compiler/circle-tensordump/CMakeLists.txt, compiler/circle-tensordump/src/Reader.cpp, compiler/circle-tensordump/src/Reader.h
This commit applies `mio-circle` helper functions to `circle-tensordump`.
---
Parent issue : #8096
Draft : #8097
=> [circle-tensordump] Apply mio-circle helper

compiler/luci-interpreter/src/kernels/OneHot.test.cpp
This commit adds another negative test case for OneHot's kernel.
-----------
For: https://github.com/Samsung/ONE/pull/8090/files#r763413826
=> [luci-interpreter] Add negative test for OneHot kernel

compiler/luci/lang/include/luci/IR/CircleQuantParam.h
This will expose copy_quantparam as IR method.
=> [luci/IR] Expose copy_quantparam method

res/PyTorchExamples/examples/RNN-bi/__init__.py, res/PyTorchExamples/examples/RNN-noinit/__init__.py
This PR:
- removes redundant array wrapper from input in RNN-noinit example
- fixes tensor dimensions in RNN-bi
related issue: #7939 
=> [res] Fix RNN examples in PyTorchExamples

compiler/one-cmds/CMakeLists.txt, compiler/one-cmds/tests/CMakeLists.txt
This PR introduces ENABLE_ONE_IMPORT_PYTORCH option in cmake
to enable installation of pytorch importer.
=> [one-cmds] Add optional installation of one-import-pytorch

res/PyTorchExamples/examples/SpaceToBatchND/__init__.py
This PR removes redundant prints from SpaceToBatchND example.
This is just a cleanup
=> [res] Remove redundant prints form PyTorchExamples

compiler/luci/pass/src/SubstituteSplitVToSplitPass.cpp, compiler/luci/pass/src/SubstituteSqueezeToReshapePass.cpp
This will restore using copy_quantparam method in pass.
=> [luci/pass] Use copy_quantparam

compiler/luci-interpreter/src/kernels/MirrorPad.cpp, compiler/luci-interpreter/src/kernels/MirrorPad.test.cpp
This commit adds valid implementation of MirrorPad kernel based on reference PadV2 implementation.
Issue: #6856 
Related: #7535 
=> [luci-interpreter] Implement MirrorPad kernel

compiler/luci/service/src/CircleNodeClone.cpp
This will revise copy_common_attributes method to use copy_quantparam method.
=> [luci/svc] Use copy_quantparam in copy_common_attriburtes

infra/nncc/CMakeLists.txt
This PR adds ENABLE_ONE_IMPORT_PYTORCH option in nncc root CMakeLists.txt.
continuation of #8118
=> [infra] Add ENABLE_ONE_IMPORT_PYTORCH option

compiler/luci/pass/src/SubstituteSplitVToSplitPass.cpp, compiler/luci/pass/src/SubstituteSqueezeToReshapePass.cpp
This will fix src, dst argument with calling copy_quantparam method.
=> [luci/pass] Fix src,dst of copy_quantparam

tools/tflitefile_tool/parser/model_parser.py, tools/tflitefile_tool/parser/tflite_parser.py
Let's introduce tflite_parser. Now model_parser doesn't have dependency
directly on tflite.
---
=> [tflitefile_tools] Introduce tflite_parser

compiler/one-cmds/CMakeLists.txt, compiler/one-cmds/one-import-onnx, compiler/one-cmds/one-import-pytorch, compiler/one-cmds/onnx_legalizer.py
This PR introduces onnx legalizer that replaces
unsupported operations with equivalent subgraphs.
related issue: #7939 
=> [one-cmds] Legalize onnx models

tools/cross/install_rootfs.sh
This commit updates install-rootfs.sh script.
Key feature
- Move `set -x` for pretty help print
- Remove boost version setting - use default version
=> [tools] Revise install-rootfs script

compiler/one-cmds/one-prepare-venv
This commit will allow to maintain latest pip and setuptools version.
Sometimes new library version installation requrires new pip version.
=> [one-cmd] Use latest pip and setuptools

tools/tflitefile_tool/model_parser.py, tools/tflitefile_tool/parser/model_parser.py, tools/tflitefile_tool/parser/tflite_parser.py
Let's revisit ModelParser and TFLiteParser so that there are now
parent(ModelParser) and child(TFLiteParser).
---
=> [tflitefile_tools] Revisit ModelParser and TFLiteParser

compiler/luci-interpreter/pal/cmsisnn/PALAveragePool2d.h, compiler/luci-interpreter/pal/linux/PALAveragePool2d.h, compiler/luci-interpreter/pal/mcu/PALAveragePool2d.h, compiler/luci-interpreter/src/kernels/AveragePool2D.cpp, compiler/luci-interpreter/src/loader/nodes/AveragePool2D.cpp
This pr lets set data type for temporary tensors in PAL interface for AveragePool2D kernel.
according to #8047 (comment) comment
=> [luci-interpreter] Let PALAveragePool2d cast temporary tensors

tools/tflitefile_tool/saver/config_saver.py
Let ConfigSaver use StringBuilder instead of printer.
---
=> [tflite_tools] Use StringBuilder instead of printer.

compiler/one-cmds/one-import-onnx
This PR makes onnx_legalize.py module optional for one-import-onnx.
related issue: #8152
=> [one-cmds] Make onnx_legalizer optional feature

compiler/luci-interpreter/src/kernels/Utils.cpp
This PR replaces assert with throw in case of wrong broadcast shapes.
=> [luci-interpreter] Throw exception in case of wrong brodcast

compiler/record-minmax/src/MinMaxObserver.cpp
This commit introduces skip of min/max recording for integer tensors.
-------------
For: #8065
Draft: #8171
=> [record-minmax] Skip minmax recording for integer tensors

compiler/record-minmax/src/RecordMinMax.cpp
This commit allows integer inputs in `profileDataWithRandomInputs`.
--------------------
For: #8065
Draft: #8171
=> [record-minmax] Allow random integer inputs

compiler/luci-interpreter/src/kernels/NotEqual.cpp, compiler/luci-interpreter/src/kernels/NotEqual.h, compiler/luci-interpreter/src/kernels/NotEqual.test.cpp, compiler/luci-interpreter/src/kernels/Utils.cpp
This PR enables NotEqual comparison of S32 and S64.
=> [luci-interpreter] Support Integer NotEqual

compiler/luci-interpreter/src/kernels/GreaterEqual.cpp, compiler/luci-interpreter/src/kernels/GreaterEqual.h, compiler/luci-interpreter/src/kernels/GreaterEqual.test.cpp, compiler/luci-interpreter/src/kernels/Utils.cpp
This PR enables integer GreaterEqual kernels.
=> [luci-interpreter] Support Integer GreaterEqual

compiler/luci-interpreter/src/kernels/LessEqual.cpp, compiler/luci-interpreter/src/kernels/LessEqual.h, compiler/luci-interpreter/src/kernels/LessEqual.test.cpp, compiler/luci-interpreter/src/kernels/Utils.cpp
This PR enables S32 and S64 LessEqual.
=> [luci-interpreter] Enable Integer LessEqual

compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
This commit fixes typos in error message and comment in `propagate_one_hot_quantparam` function.
Co-authored-by: Hyukjin Jeong <hj1.jeong@samsung.com>
Fix typo which made in: #8174
=> [luci/pass] Fix typos in error message and comment 

compiler/one-cmds/one-build, compiler/one-cmds/onecc, compiler/one-cmds/utils.py
This PR adds search path parameter to _detect_one_import_drivers.
Related issue: #8169.
=> [one-cmds] Add parameter to autodetect drivers

compiler/record-minmax/src/MinMaxObserver.cpp
This commit removes redundant ArgMax's case in MinMaxObserver.
For: https://github.com/Samsung/ONE/pull/8171#discussion_r770117180
=> [record-minmax] Remove redundant ArgMax case

tools/tflitefile_tool/model_parser.py, tools/tflitefile_tool/parser/model_parser.py, tools/tflitefile_tool/parser/tflite_parser.py
Let's fix ModelParser's hierarchy from `is-a` to `has-a`.
---
=> [tflitefile_tools] Fix ModelParser's hierarchy

compiler/luci-interpreter/src/kernels/Add.test.cpp
This PR fixes data types used in integer tests:
- int32_t was used for S64 test.
=> [luci-interpreter] Fix integer add tests

tools/tflitefile_tool/ir/graph_stats.py, tools/tflitefile_tool/model_parser.py, tools/tflitefile_tool/parser/subgraph_parser.py, tools/tflitefile_tool/parser/tflite_parser.py, tools/tflitefile_tool/saver/model_saver.py
Let's rename model and operator parser to subgraph.
---
=> [tflitefile_tools] Rename properly to subgraph

tools/tflitefile_tool/printer/string_builder.py, tools/tflitefile_tool/printer/subgraph_printer.py
Let's revise printer files.
- '\t' -> '  ' (two spaces)
- The only SubgraphPrinter has `verbose`
- '#', '%', or '&' instead of string
---
=> [tflitefile_tools] Revise printer/

compiler/luci-interpreter/src/kernels/Add.cpp, compiler/luci-interpreter/src/kernels/Div.cpp, compiler/luci-interpreter/src/kernels/Mul.cpp, compiler/luci-interpreter/src/kernels/Sub.cpp, compiler/luci-interpreter/src/kernels/Utils.h
This PR moves computation of min/max activation values from arithmetic kernels
to Utils.h for float, S32 and S64 types.
Simplify code added in #8155 
=> [luci-interpreter] Move common activation related code to utils

compiler/luci/export/src/CircleExporterUtils.cpp, compiler/luci/export/src/SerializedData.h
For now, there were two registering Opcode functions,
`registerBuiltinOpcode` and `registerCustomOpcode`.
However, they have duplicated logics to register Opcode.
This commit introduces a new function which unfies duplicate logics as one.
---
Draft : #8199
=> [luci/export] Introduce new registerBuiltinOpcode function

compiler/luci/pass/src/ConvertNCHWToNHWCPass.cpp
This will fix check_4d_reshape to check input rank is 4.
=> [luci/pass] Fix check_4d_reshape method

compiler/luci/export/src/CircleBuiltinTypesExtractor.h
This commit introduces `CircleBuiltinTypesExtractor`,
which creates Builtin types using `CircleNode`.
---
Draft : #8199
=> [luci/export] Introduce CircleBuiltinTypesExtractor

compiler/luci/export/src/CircleExporterUtils.cpp, compiler/luci/export/src/CircleExporterUtils.h
This commit will introduce following new util functions for export.
- `circle_builtin_operator`
- `circle_builtin_options`
- `circle_custom_code`
- `circle_custom_options`
---
Draft : #8199
=> [luci/export] Introduce new util functions

compiler/luci/export/src/CircleOperationExporterRule.cpp, compiler/luci/export/src/CircleOperationExporterRule.h
This commit introduces `CircleOperationExporterRule`,
which includes exporting rule for all CircleNode.
---
Draft : #8199
=> [luci/export] Introduce CircleOperationExporterRule

compiler/luci-interpreter/pal/cmsisnn/PALConv2d.h
This pr fixes setup scratchpad method in cmsisnn/PALConv2d.
=> [luci-interpreter] Fix PALConv2d setup scratchpad method

compiler/luci/export/src/CircleOperationExporter.cpp
This commit revise `exportNodes` function with following updates.
- Integrate `exportNode` into `exportNodes`
- Substitute `OperationExporter` with `OperationExporterRule`
---
Draft : #8199
=> [luci/export] Revise exportNodes function

tests/tools/nnpackage_run/src/args.cc
The `nnpackage_run` tool includes a parameter `-t` to tune the interval between runs. Under help, the until of this interval is specified as `ms`, and can be interpreted as milliseconds. This commit replaces `ms` to `us`, to correctly reflect microseconds as the unit of time.
Signed-off-by: dr-venkman<venkat.iyer@samsung.com>
=> [onert/nnpackage_run] Fix parameter help message for nnpackage_run

tools/tflitefile_tool/select_operator.py
Flatbuffers changes EndVector argument on 2.0.
Let's use workaround to support flatbuffers 1.12 and 2.0 for a while.
=> [tflitefile_tool] Use workaround for EndVector

.gitattributes
This commit updates .gitattributes file for basic format setting.
- Fix invalid language statics pattern
- Set default EOL type: LF
We can remove EOL type checker by this update.
=> [infra] Revise gitattributes

compiler/luci/pass/src/VerifyQuantizedNodeGranularity.cpp, compiler/luci/pass/src/VerifyQuantizedNodeGranularity.h
This commit introduces `VerifyQuantizedNodeGranularity`,
which is base class of `VerifyQuantizedChannelWiseGranularity` and
`VerifyQuantizedLayerWiseGranularity`.
---
Parent Issue : #8228
Draft : #8229
=> [luci/pass] Introduce VerifyQuantizedNodeGranularity

compiler/common-artifacts/CMakeLists.txt
This will split command to separate lines for better readability.
=> [common-artifacts] Split command for better readability

compiler/luci/pass/src/QuantizedModelVerifier.test.cpp
This commit adds more test cases to `QuantizedModelVerifierTest`.
---
Parent Issue : #8228
Draft : #8229
=> [luci/pass] Add more testcases to QuantizedModelVerifierTest

compiler/luci/pass/src/QuantizedModelVerifier.cpp
This commit replaces both `VerifyQuantizedNodeLayerWiseGranularity`
and `VerifyQuantizedNodeChannelWiseGranularity`
to `VerifyQuantizedNodeGranularity`.
---
Parent Issue : #8228
Draft : #8229
=> [luci/pass] Apply VerifyQuantizedNodeGranularity

res/TensorFlowLiteRecipes/Gather_000/test.recipe
This will remove graph input for indices in Gather_000 recipe
as indices is constant buffer.
=> [res] Fix Gather_000 recipe

res/TensorFlowLiteRecipes/Gather_001/test.recipe
This will introduce Gather_001 recipe that has both inputs of Gather
op as graph input with axis 3.
=> [res] Introduce Gather_001 recipe

compiler/common-artifacts/src/TestDataGenerator.cpp
This will fix generate_random_data typo.
=> [common-artifacts] Fix typo of method name

compiler/common-artifacts/CMakeLists.txt, compiler/common-artifacts/options.lst
This will enable to provide additional options for testDataGenerator
command per model.
=> [common-artifacts] Additional options for testDataGenerator

compiler/luci-interpreter/README.md
This commit fixes typo in `luci-interpreter` README.
ONE-DCO-1.0-Signed-off-by: yunjayh <yunjayh@gmail.com>
=> [luci-interpreter] FIX typo in luci-interpreter README

compiler/circledump/src/Load.cpp
This commit fixes typo in descriptor.
ONE-DCO-1.0-Signed-off-by: yunjayh <yunjayh@gmail.com>
=> [circledump] Fix typo in descriptor

compiler/tfldump/src/Load.cpp
This commit fixes typo in descriptor.
ONE-DCO-1.0-Signed-off-by: yunjayh <yunjayh@gmail.com>
=> [tfldump] Fix typo in descriptor

compiler/common-artifacts/src/TestDataGenerator.cpp
This will add node name is not empty assert check for all nodes.
=> [common-artifacts] Add node name not empty check

compiler/circle-execution-plan/CMakeLists.txt, compiler/circle-execution-plan/pal/TargetPlatform.h, compiler/circle-execution-plan/src/CircleExecutionPlan.cpp, compiler/circle-execution-plan/src/ExecutionPlanner.cpp, compiler/circle-execution-plan/src/ExecutionPlanner.h
This pr adds command line interface + TargetPlatform structure and it's usage in ExecutionPlanner. This is first part of changes for adding pal to circle-execution-planner. 
draft: #8128 
=> [circle-execution-plan] Add command line interface and TargetPlatform

compiler/luci-interpreter/pal/cmsisnn/PALDepthwiseConv2d.h
This commit removes assert and adds input_data_type checking setup scratchpad method in cmsisnn/PALDepthwiseConv2d.
=> [luci-interpreter] Fix PALDepthwiseConv2d setup scratchpad method

compiler/one-cmds/one-prepare-venv
This will revise one-prepare-venv so that we can override torch_stable.html URL.
=> [one-cmds] Enable override torch install URL

compiler/luci/import/include/luci/Import/GraphBuilderRegistry.h, compiler/luci/import/include/luci/Import/NodeBuilder.h, compiler/luci/import/src/GraphBuilderRegistry.cpp
This commit introduces NodeBuilder class for nodes which not handled by common builders.
--------------
For: #8042
Draft: #8190
=> [luci/import] Introduce NodeBuilder

compiler/luci/import/include/luci/Import/Nodes/CircleConst.h, compiler/luci/import/src/GraphBuilderRegistry.cpp, compiler/luci/import/src/Importer.cpp, compiler/luci/import/src/Nodes/CircleConst.cpp
This commit introduces builder for CircleConst node and extracts node creation to this builder.
For: #8042
Draft: #8190
=> [luci/import] Add node builder for CircleConst

compiler/circledump/src/OpPrinter.cpp
Add `circledump` support for SVDF operator
issue: #8203 
=> [circledump] SVDF add circledump support

compiler/tfldump/src/OpPrinter.cpp
Add tfldump support for SVDF operator
issue: #8203 
=> [tfldump] SVDF support for tfldump

compiler/tflchef/proto/tflchef.proto
This pr adds SVDFOptions to tflchef.proto
issue #8203 
=> [tflchef] add SVDFOptions to tflchef.proto

compiler/luci/pass/src/SubstituteStridedSliceToReshapePass.cpp
Let's fix unspecified uint type to uint32_t type.
---
draft https://github.com/Samsung/ONE/pull/8290
=> [luci/pass] Fix uint to uint32_t

infra/command/format
This commit removes end-of-line check from format command.
End-of-Line will be fixed automatically by .gitattributes.
=> [infra] Remove EOL check

compiler/luci/service/src/CircleShapeInferenceRule.cpp, compiler/luci/service/src/CircleTypeInferenceRule.cpp
This will enable shape and dtype inference of CircleVariable Node.
=> [luci/svc] Shape and dtype inference of CircleVariable

compiler/luci/import/include/luci/Import/Nodes.h, compiler/luci/import/include/luci/Import/Nodes/CircleVariable.h, compiler/luci/import/src/Importer.cpp, compiler/luci/import/src/Nodes/CircleVariable.cpp
This will enable import of variable tensor as CircleVariable Node.
=> [luci/import] Enable CircleVariable

infra/cmake/modules/ExternalSourceTools.cmake
Use RESULT_VARIABLE to get exact result status. ERROR_VARIABLE has some
content even when COMMAND prints warning.
---
draft https://github.com/Samsung/ONE/pull/8290
=> [infra/cmake] Fix to use RESULT_VARIABLE

compiler/luci-interpreter/include/luci_interpreter/GraphBuilderRegistry.h, compiler/luci-interpreter/src/CMakeLists.txt, compiler/luci-interpreter/src/import/CMakeLists.txt, compiler/luci-interpreter/src/import/GraphBuilderRegistry.cpp
This commit adds helper skeleton for import without constant copying.
For: #8042
Draft: #8190
First part of: #8315
=> [luci-interpeter] Add helper for import without copying

res/TensorFlowLiteRecipes/Sqrt_000/test.recipe
This commit removes constant operation's input from list of model's inputs.
For: https://github.com/Samsung/ONE/issues/8310#issuecomment-1018500541
=> [res] Fix Sqrt_000 recipe

compiler/mio-tflite260/src/Helper.cpp
Static analyzer says that `deprecated_builtin_code <= 127` is always true
because maximum value of `int8_t` is 127.
=> [mio-tflite260] Replace constant expression

compiler/luci/logex/src/FormattedGraph.cpp
This will enable summary log for CircleSVDF node.
=> [luci/log] Enable summary for CircleSVDF

compiler/luci/partition/src/PartitionPGroups.cpp
This will enable check for CircleVariable node is a virtual node and
virtual input node.
=> [luci/part] Check CircleVariable

compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
This supports BatchMatMul Op in quantizer.
---
Draft PR: #8334
Related to: #8325
=> [circle-quantizer] Support BatchMatMul Op

infra/command/format
This commit simplify file mode check by using "git ls-files -s" command.
File mode check is used for
- Remove symblic link file from checlist
- Check code file invalid execution permission
=> [infra] Simplify file mode check

compiler/luci-interpreter/src/import/Nodes/CircleReferencingConst.cpp, compiler/luci-interpreter/src/import/Nodes/CircleReferencingConst.h
This commit adds support of constants import via `CircleReferencingConst` custom node.
--------------------------
For: #8042
Draft: #8190
Second part of: #8315
=> [luci-interpreter] Add CircleReferencingConst import

compiler/luci-interpreter/src/loader/GraphLoader.cpp
This PR adds missing opcodes in isExecutableNode and isTensorProducingNode lists.
=> [luci-interpreter] Add missing multi-output nodes in lists

compiler/luci/pass/src/VerifyQuantizedNodeType.cpp, compiler/luci/pass/src/VerifyQuantizedNodeType.h
This commit introduces `VerifyQuantizedNodeType` which includes both
`VerifyQuantizedNodeU8Type` and `VerifyQuantizedNodeS16Type`.
---
Parent Issue : #8297
Draft : #8298
=> [luci/pass] Introduce VerifyQuantizedNodeType

compiler/luci/pass/src/VerifyQuantizedNodeType.h
This will revise VerifyQuantizedNodeTypeBase class to remove pure virtual.
=> [luci/pass] Revise VerifyQuantizedNodeTypeBase

compiler/luci/pass/src/VerifyQuantizedNodeType.h
This will sort VerifyQuantizedNodeU8Type and VerifyQuantizedNodeS16Type
in alphabetical order.
=> [luci/pass] Sort VerifyQuantizedNodeXXType

compiler/luci-interpreter/src/loader/GraphLoader.cpp
This commit adds support of CircleReferencingConst custom node to loader.
------------------------
For: #8042
Draft: #8190
=> [luci-interpreter/loader] Support CircleReferencingConst load

compiler/luci-value-test/luci_eval_verifier.py
This will revise luci_eval_verifier to accept float32 tolerance as optional arguments.
=> [luci/test] Verifier with tolerance

compiler/luci-interpreter/src/loader/GraphLoader.cpp
This commit replaces if-else statements with dynamic_cast to switch-case with opcodes.
--------------
For: https://github.com/Samsung/ONE/pull/8321#discussion_r792179741
=> [luci-interpreter] Use switch-case instead if-else

infra/debian/compiler/postinst
This commit adds -p option to postinst script that preserves current environment.
This change fixes a bug where current user env variables are not passed properly.
=> [debian] Add preserve environment option

infra/debian/compiler/one-compiler.install
This commit adds constant.py to install list.
Related: #8169
=> [debian] Add constant.py to install list

compiler/circle-execution-plan/pal/IScratchpadHelper.h, compiler/circle-execution-plan/pal/ScratchpadHelperCMSISNN.h, compiler/circle-execution-plan/pal/ScratchpadHelperLinux.h, compiler/circle-execution-plan/pal/ScratchpadHelperMCU.h, compiler/circle-execution-plan/src/ExecutionPlanner.cpp
This pr adds support calculation for DepthwiseConv2d, SVDF and AveragePool2d scratchpad tensors for circle execution planner.
issue #8354
=> [circle-execution-plan] Support calculation of scratchpad sizes for more operations

compiler/tflchef/tflite/src/Op/SVDF.cpp
This commit fixes handling of optional bias.
---------------------
For: #8203
Draft: #8365
=> [tflchef] Fix SVDF bias handling

compiler/luci/pass/src/VerifyQuantizedNodeType.cpp, compiler/luci/pass/src/VerifyQuantizedNodeType.h
This commit introduces helper function `group_has_type`,
which is for checking a node and it's inputs have same data type.
---
Parent Issue : #8297
Draft : #8298
=> [luci/pass] Introduce helper functions for VerifyQuantizedNodeType

compiler/tflchef/tflite/src/Op/SVDF.cpp
This commit adds assert for fixed SVDF's inputs size.
--------------------------
For: #8203
Draft: #8365
=> [tflchef] Add assert for SVDF inputs size

compiler/luci/pass/src/QuantizedModelVerifier.cpp
This commit applies `VerifyQuantizedNodeType` to `QuantizedModelVerifier`.
---
Parent Issue : #8297 
Draft : #8298
=> [luci/pass] Apply VerifyQuantizedNodeType

compiler/circle-execution-plan/pal/IScratchpadHelper.h, compiler/circle-execution-plan/pal/ScratchpadHelperCMSISNN.h, compiler/circle-execution-plan/pal/ScratchpadHelperLinux.h, compiler/circle-execution-plan/pal/ScratchpadHelperMCU.h, compiler/circle-execution-plan/src/ExecutionPlanner.cpp
This pr adds support calculation for BatchMatMul scratchpad tensors for circle execution planner.
issue #8354
=> [circle-execution-plan] Support scratchpad size for BatchMatMul

compiler/arser/tests/arser.test.cpp
This commit makes arser.test.cpp use Prompt header file for maintainability.
Related: #6592
=> [arser] Use Prompt header file

compiler/luci/service/include/luci/Service/CircleShapeInference.h, compiler/luci/service/include/luci/Service/CircleTypeInference.h
This will tidy shape/dtype inference header orders and remove unused.
=> [luci/svc] Tidy shape/dtype inference header

compiler/luci/pass/src/RemoveUnnecessaryReshapePass.cpp
This will add before/after graph comment for RemoveUnnecessaryReshapePass.
=> [luci/pass] Add comment for RemoveUnnecessaryReshapePass

compiler/luci-micro/CMakeLists.txt
This PR changes CMake message about missing arm compiler from Warning to Stats.
related issue: #8337
=> [luci-micro] Change CMake message mode

compiler/luci/pass/include/luci/Pass/QuantizeWithMinMaxPass.h, compiler/luci/pass/src/CircleOptimizer.cpp, compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
This reorders quantization steps to ensure input scale is not changed after bias is quantized.
---
Related to: #8385
Draft PR: https://github.com/Samsung/ONE/pull/8382
=> [luci] Fix bias scale quantization

compiler/luci/pass/src/ConvertNCHWToNHWCPass.cpp, compiler/luci/pass/src/ConvertNCHWToNHWCPass.test.cpp
This commit extends ConvertNCHWToNCHW pass with Elu op.
=> [luci/pass] Extend ConvertNCHWToNHWC with Elu

compiler/one-cmds/onnx_legalizer.py
This PR adds dedicated methods to create operations of particular type.
This change should improve readability and remove some code duplication.
Related issue: #8148
=> [one-cmds] Add dedicated builder methods for various operations

infra/debian/compiler/one-compiler.install
This commit adds make_cmd.py to install list.
Related: #8396 
=> [debian] Add make_cmd.py to install list

compiler/luci/pass/include/luci/CircleQuantizer.h, compiler/luci/pass/src/CircleQuantizer.cpp, compiler/luci/pass/src/CircleQuantizer.test.cpp
This commit introduces `CircleQuantizer` class in `luci/pass`.
---
Parent Issue : #8393
Draft : #8394
=> [luci/pass] Introduce CircleQuantizer

infra/debian/compiler/one-compiler.install
This commit modifies one-compiler.install for applying previous relocation of python lib.
=> [debian] Modify .install

compiler/luci/service/src/CircleShapeInferenceRule.cpp
This will replace similar method implementations with macro.
=> [luci/svc] Use macro for similar methods in shape inference

compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
This copies const inputs before quantization.
---
Related to: https://github.com/Samsung/ONE/issues/8406
Draft PR: https://github.com/Samsung/ONE/pull/8410
=> [luci] Copy quantized const inputs

compiler/luci/pass/src/QuantizedModelVerifier.cpp, compiler/luci/pass/src/VerifyQuantizedBiasScale.cpp, compiler/luci/pass/src/VerifyQuantizedBiasScale.h
This tests the scale of quantized bias.
---
This PR ensures bias scale = input scale * weights scale (related to: https://github.com/Samsung/ONE/issues/8385)
=> [luci] Add test for quantized bias scale

compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
This quantizes const input earlier than special activation.
---
Related to: https://github.com/Samsung/ONE/pull/8382
For reviewers: This PR reorders `QuantizeSpecialActivation` and `QuantizeConstInputActivation`. This is a missing part of https://github.com/Samsung/ONE/pull/8382.
=> [luci] Reorder quantization steps

compiler/tflchef/tests/CMakeLists.txt
This will remove nnkit dependency check for running tests.
=> [tflchef] Remove nnkit dependency for tests

compiler/tflchef/tests/CMakeLists.txt
This will revise to use mio_tflite260_validate as tflchef is using
mio_tflite260.
=> [tflchef] Use mio_tflite260

compiler/circle-quantizer/src/CircleQuantizer.cpp
This commit replaces `CircleOptimizer` to `CircleQuantizer` in `circle-quantizer`.
---
Parent Issue : #8393 
Draft : #8394
=> [circle-quantizer] Replace CircleOptimizer to circleQuantizer

compiler/one-cmds/tests/onnx-operations/CMakeLists.txt
This PR adds --unroll_rnn --unroll_lstm options in onnx_operations tests.
=> [one-cmds] Add onnx_legalize options in onnx tests

compiler/one-cmds/one-import-pytorch, compiler/one-cmds/tests/pytorch-operations/CMakeLists.txt
This PR adds --unroll_rnn --unroll_lstm options in
one-import-pytorch and pytorch_operations tests.
=> [one-cmds] Add onnx_legalize options in one-import-pytorch

compiler/circlechef/tests/CMakeLists.txt
This will revise to use cmake variables for circlechef-file and
circlechef-reverse tools.
=> [circlechef] Use cmake variable for tools command

compiler/luci/tests/CMakeLists.txt
This will revise to use cmake variables for circlechef-file,
tflchef-file and tflite2circle tools.
=> [luci/tests] Use cmake variable for tools command

compiler/luci/logex/src/CircleNodeSummaryBuilder.cpp, compiler/luci/logex/src/CircleNodeSummaryBuilder.h
This commit introduces `CircleNodeSummaryBuilder`,
which builds summary for `CircleNode`s.
---
Parent Issue ; #8357 
Draft : #8358
=> [luci/logex] Introduce CircleNodeSummaryBuilder

compiler/tflchef/tests/CMakeLists.txt
This will revise to use cmake variables for tflchef-file,
tflchef-reverse tools.
=> [tflchef] Use cmake variable for tools command

compiler/luci/lang/include/luci/IR/Nodes/CircleFullyConnected.h, compiler/luci/lang/src/Nodes/CircleFullyConnected.test.cpp
This commit adds `keep_num_dims` attribute to `CircleFullyConnected`.
---
Parent Issue : #8400
Draft : #8401
=> [luci/lang] Add keep_num_dims attribute to CircleFullyConnected

infra/command/format
This commit introduce DEFAULT_CLANG_FORMAT variable in format command and use for command and help message.
=> [infra] Use default clang format version

compiler/circlechef/CMakeLists.txt
This will add cmake skip message if required libraries are missing.
=> [circlechef] Skip message for CMakeLists

infra/nncc/CMakeLists.txt
This will fix indentation for nnas_find_package macro.
=> [infra] Fix indent for nnas_find_package macro

compiler/tflite2circle/src/BuildBuiltinOptions/FullyConnectedOptions.cpp
This commit adds `keep_num_dims` attribute to `FullyConnected`.
---
Parent Issue : #8400
Draft : #8401
=> [tflite2circle] Add keep_num_dims attribute to FullyConnected

compiler/luci/export/src/CircleBuiltinTypesExtractor.h
This commit adds `keep_num_dims` to `CircleFullyConnected`.
---
Parent Issue : #8400 
Draft : #8401
=> [luci/export] Add keep_num_dims to CircleFullyConnected

compiler/luci/import/src/Nodes/CircleFullyConnected.cpp
This commit adds `keep_num_dims` to `CircleFullyConnected`.
---
Parent issue : #8400 
Draft : #8401
=> [luci/import] Add keep_num_dims to CircleFullyConnected

compiler/circledump/src/OpPrinter.cpp
This commit adds `keep_num_dims` to `FullyConnectedPrinter`.
---
Parent Issue : #8400
Draft : #8401
=> [circledump] Add keep_num_dims to FullyConnectedPrinter

compiler/tflchef/core/src/Op/FullyConnected.cpp, compiler/tflchef/proto/tflchef.proto, compiler/tflchef/tflite/src/Op/FullyConnected.cpp
This commit adds `keep_num_dims` to `FulltConnectedOption`.
---
Parent Issue : #8400
Draft : #8401
=> [tflchef] Add keep_num_dims to FullyConnectedOption

compiler/luci-interpreter/src/core/KernelParams.h, compiler/luci-interpreter/src/kernels/FullyConnected.cpp, compiler/luci-interpreter/src/loader/nodes/FullyConnected.cpp
This commit adds `keep_num_dims` to `FullyConnected`.
---
Parent issue : #8400 
Draft : #8401
=> [luci-interpreter] Add keep_num_dims to FullyConnected

compiler/luci/pass/include/luci/Pass/QuantizeWithMinMaxPass.h
This removes deprecated member variables in QuantizeWithMinMax.
---
Related to: https://github.com/Samsung/ONE/issues/8454
=> [luci] Remove deprecated member variables in QWMM

compiler/luci/pass/include/luci/Pass/QuantizationParameters.h, compiler/luci/pass/include/luci/Pass/QuantizeWithMinMaxPass.h
This adds layer information to QuantizeWithMinMax context.
---
Draft PR: https://github.com/Samsung/ONE/pull/8460
=> [luci] Add layer info to QWMM context

compiler/luci/pass/include/luci/Pass/QuantizeWithMinMaxPass.h
This commit initializes `Context` member variables in `QuantizeWithMinMaxPass`.
=> [luci/pass] Initialize Context member variables

compiler/luci/logex/src/FormattedGraph.cpp
This commit applies `CircleNodeSummaryBuilder` to `FormattedGraph.cpp`.
---
Parent Issue : #8357 
Draft : #8358
=> [luci/logex] Apply CircleNodeSummaryBuilder to FormattedGraph

compiler/luci/service/src/CircleShapeInferenceRule.cpp
This commit updates shape inference logic of `CircleFullyConnected`
with new attribute `keep_num_dims`.
---
Parent Issue : #8400 
Draft : #8401
=> [luci/service] Update shape inference logic of CircleFullyConnected

compiler/luci/pass/src/QuantizeDequantizeWeightsPass.cpp
This applies fake quantization to visitor target, not args.
---
Related to: https://github.com/Samsung/ONE/pull/8470
=> [luci] Apply fake quantization to visitor target
