Samsung/ONE

- compiler/luci/pass/src/ConvertNCHWToNHWCPass.cpp
- compiler/luci/pass/src/ConvertNCHWToNHWCPass.test.cpp
This will revise to support Sub node in NCHWToNHWCPass.
> [luci] Support Sub in NCHWToNHWCPass

- res/TensorFlowLiteRecipes/Net_InstanceNorm_007/test.recipe
- res/TensorFlowLiteRecipes/Net_InstanceNorm_007/test.rule
This will introduce Net_InstanceNorm_007 recipe.
> [res] Introduce Net_InstanceNorm_007

- compiler/luci/pass/src/FuseInstanceNormPass.cpp
This will enable fusion of InstanceNorm pattern version 5.
> [luci] Enable FusetInstNorm Ver 5

- compiler/one-cmds/CMakeLists.txt
- infra/debian/compiler/one-compiler.install
- infra/debian/compiler/one-compiler.links
This commit installs onecc binary to /usr/share/one/bin.
This file is also linked to /usr/bin/.
> [onecc] Add to debian package

- compute/cker/include/cker/operation/FloorDiv.h
- runtime/onert/backend/cpu/KernelGenerator.cc
- runtime/onert/backend/cpu/ops/ElementwiseBinaryLayer.cc
- runtime/onert/backend/cpu/ops/ElementwiseBinaryLayer.h
- runtime/onert/core/include/ir/operation/ElementwiseBinary.h
- runtime/onert/core/src/ir/operation/ElementwiseBinary.cc
- runtime/onert/frontend/base_loader/include/base_loader.h
- tests/nnfw_api/src/CircleGen.cc
- tests/nnfw_api/src/CircleGen.h
- tests/nnfw_api/src/one_op_tests/FloorDiv.cc
Add FloorDiv operation for cpu backend.
Signed-off-by: venkat.iyer venkat.iyer@samsung.com
> [onert] Add FloorDiv operation for cpu backend

- compiler/one-cmds/tests/onecc_013.cfg
- compiler/one-cmds/tests/onecc_013.test
- compiler/one-cmds/tests/onecc_014.cfg
- compiler/one-cmds/tests/onecc_014.test
- compiler/one-cmds/tests/onecc_015.cfg
- compiler/one-cmds/tests/onecc_015.test
- compiler/one-cmds/tests/onecc_016.cfg
- compiler/one-cmds/tests/onecc_016.test
- compiler/one-cmds/tests/onecc_017.test
- compiler/one-cmds/tests/onecc_018.test
- compiler/one-cmds/tests/onecc_019.test
- compiler/one-cmds/tests/onecc_020.test
- compiler/one-cmds/tests/onecc_neg_007.test
- compiler/one-cmds/tests/onecc_neg_008.test
This commit adds some test cases for subcommand of onecc.
Draft PR: #7303
> [onecc] Add subcommand test cases

- compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
- compiler/luci/pass/src/QuantizedModelVerifier.test.cpp
- compiler/luci/pass/src/VerifyQuantizedNodeChannelWiseGranularity.h
- compiler/luci/pass/src/VerifyQuantizedNodeLayerWiseGranularity.h
- compiler/luci/pass/src/VerifyQuantizedNodeS16Type.h
- compiler/luci/pass/src/VerifyQuantizedNodeU8Type.h
This propagates qparam of Pack.
> [circle-quantizer] Propagate qparam of Pack

- compiler/luci/pass/src/ConvertNCHWToNHWCPass.cpp
- compiler/luci/pass/src/ConvertNCHWToNHWCPass.test.cpp
This commit adds support for NCHW-NHWC conversion of CircleMean
operation when keep_dims is set to false.
ONE-DCO-1.0-Signed-off-by: Andrey Kvochko <a.kvochko@samsung.com>
------
Related: #7329
> [luci] Support NHWC conversion for Mean with keep_dims=false

- compiler/tf2tfliteV2/tf2tfliteV2.py
It suppresses traceback from tf2tfliteV2.py.
> [tf2tfliteV2] Suppress trackback on error from tf2tfliteV2

- compiler/circle2circle/src/Circle2Circle.cpp
- compiler/luci/pass/include/luci/CircleOptimizer.h
- compiler/luci/pass/include/luci/Pass/FuseMeanWithMeanPass.h
- compiler/luci/pass/src/CircleOptimizer.cpp
- compiler/luci/pass/src/FuseMeanWithMeanPass.cpp
- compiler/luci/pass/src/FuseMeanWithMeanPass.test.cpp
This commit introduce FuseMeanWithMean pass to CircleOptimizer.
issue #7335
related PR  #7361
> [luci] Introduce FuseMeanWithMean pass to CircleOptimizer 

- res/TensorFlowLiteRecipes/Part_While_000/test.readme
- res/TensorFlowLiteRecipes/Part_While_000/test.recipe
- res/TensorFlowLiteRecipes/Part_While_000/test.rule
- res/TensorFlowLiteRecipes/Part_While_001/test.readme
- res/TensorFlowLiteRecipes/Part_While_001/test.recipe
This will introduce Part_While_000 and Part_While_001 recipes.
> [res] Introduce Part_While recipes

- compiler/luci/pass/src/CircleOptimizer.cpp
This does ConvertNHWCToNHWC before other optimizations are applied.
---
Related to: #7365
Draft PR: #7372
> [luci] Do ConvertNHWCToNHWC before other optimizations are applied

- compiler/luci/pass/src/ConvertNCHWToNHWCPass.cpp
This extends ConvertNCHWToNHWC to support more patterns.
Supported patterns
1. pre/post-Reshape
2. Multiple post-Transpose/Reshape for a single pre-Transpose/Reshape
---
Related to: #7365
Draft PR: #7372
> [luci] Extend ConvertNCHWToNHWC to support more patterns

- compiler/luci/service/src/CircleCloneNode.h
- compiler/luci/service/src/Nodes/CircleWhile.cpp
- compiler/luci/service/src/Nodes/CircleWhile.test.cpp
- compiler/luci/service/src/Nodes/CircleWhileOut.cpp
- compiler/luci/service/src/Nodes/CircleWhileOut.test.cpp
This will enable clone of While and WhileOut Op.
> [luci] Clone While, WhileOut Op

- compiler/one-cmds/onecc
This commit updates the usage and description of onecc.
> [one-cmds] Update usage and description of onecc

- compiler/luci-interpreter/src/kernels/CMakeLists.txt
- compiler/luci-interpreter/src/kernels/While.cpp
- compiler/luci-interpreter/src/kernels/While.h
- compiler/luci-interpreter/src/kernels/While.test.cpp
- compiler/luci-interpreter/src/loader/GraphLoader.cpp
- compiler/luci-interpreter/src/loader/KernelBuilder.cpp
This will enable execution of While Op.
> [luci-interpreter] Enable While

- compiler/luci/partition/src/PartitionPModules.cpp
This will surround block for IF node before adding others.
> [luci] Surround block for IF node

- compiler/luci/partition/src/PartitionPModules.cpp
This will enable build_graph for CircleWhile node.
> [luci-partition] Enable build_graph for CircleWhile

- compiler/luci-interpreter/src/kernels/While.cpp
This will extract tensor copy to a method a remove similar repeating codes.
> [luci-interpreter] Revise While kernel with copy method

- res/TensorFlowLiteRecipes/REGRESS_ONNX_Conv_BN_001/test.recipe
- res/TensorFlowLiteRecipes/REGRESS_ONNX_Conv_BN_001/test.rule
This will add regression test recipe with Conv+BN.
> [res] Regression test recipe with Conv+BN

- compiler/luci/pass/src/ConvertNCHWToNHWCPass.cpp
- compiler/luci/pass/src/ConvertNCHWToNHWCPass.test.cpp
This will enable convert to NHWC for CircleMaximu and CircleMinimum codes.
> [luci] Enable to NHWC for Maximum, Minimum

- compiler/common-artifacts/exclude.lst
This will enable generation of Part_While in common-artifacts.
> [common-artifacts] Enable Part_While

- res/TensorFlowLiteRecipes/REGRESS_ONNX_Conv_BN_MeanMean_001/test.recipe
- res/TensorFlowLiteRecipes/REGRESS_ONNX_Conv_BN_MeanMean_001/test.rule
- res/TensorFlowLiteRecipes/REGRESS_ONNX_Conv_BN_Relu6_001/test.recipe
- res/TensorFlowLiteRecipes/REGRESS_ONNX_Conv_BN_Relu6_001/test.rule
This will add more ONNX transformatio regression test models of CONV+BN.
> [res] More ONNX regression test of CONV+BN

- compiler/one-cmds/onecc
It fixes a typo in ImportError.
1 Approval Please.
> [onecc] Fix typo in error message

- infra/debian/compiler/docs/onecc.1
- infra/debian/compiler/one-compiler.manpages
This commit adds man page for onecc tool.
> [infra] Add man page for onecc

- compiler/one-cmds/one-quantize
This adds directory format to help message.
---
Related to: #7398
Draft PR: #7401
> [one-cmds] Update one-quantize help message

- tools/nnpackage_tool/model2nnpkg/model2nnpkg.sh
It writes error messages to stderr, not to stdout.
1 Approval Please
> [model2nnpkg] Write error to stderr, not to stdout

- compiler/luci/pass/src/ConvertNCHWToNHWCPass.cpp
- compiler/luci/pass/src/ConvertNCHWToNHWCPass.test.cpp
This will revise convert toNHWC of Mul to support scalar Constant.
> [luci] Revise toNHWC Mul to support scalar Const

- compiler/luci/pass/src/ConvertNCHWToNHWCPass.cpp
- compiler/luci/pass/src/ConvertNCHWToNHWCPass.test.cpp
This will revise convert toNHWC of Sub to support scalar Constant.
> [luci] Revise toNHWC Sub to support scalar Const

- compiler/luci/pass/src/ConvertNCHWToNHWCPass.cpp
- compiler/luci/pass/src/ConvertNCHWToNHWCPass.test.cpp
This will enable to support Logistic Op in convert to NHWC.
> [luci] Support Logistic in convert to NHWC

- compiler/luci/import/src/Nodes/CircleExp.cpp
This will enable import of Exp with quantized data type.
> [luci] Support quantized model with Exp

- compiler/luci/pass/include/luci/CircleOptimizer.h
- compiler/luci/pass/include/luci/Pass/FuseTransposeWithMeanPass.h
- compiler/luci/pass/src/CircleOptimizer.cpp
- compiler/luci/pass/src/FuseTransposeWithMeanPass.cpp
- compiler/luci/pass/src/FuseTransposeWithMeanPass.test.cpp
This commit adds FuseTransposeWithMean pass to luci.
Signed-off-by: Andrey Kvochko <a.kvochko@samsung.com>
-----
Issue: #7335 
Draft: #7437
> [luci] Add FuseTransposeWithMeanPass

- infra/command/gen-coverage-report
- All the ported code from tflite will be skipped
> Skip coverage test under open_cl folder

- runtime/onert/backend/gpu_cl/KernelGenerator.cc
- runtime/onert/backend/gpu_cl/KernelGenerator.h
- runtime/onert/backend/gpu_cl/open_cl/kernels/Pooling.cc
- runtime/onert/backend/gpu_cl/open_cl/kernels/Pooling.h
- runtime/onert/backend/gpu_cl/open_cl/selectors/SimpleSelectors.cc
- runtime/onert/backend/gpu_cl/open_cl/selectors/SimpleSelectors.h
- tests/nnfw_api/src/one_op_tests/AveragePool2D.cc
1. Add Pool2d operation.
2. Add testcases.
Signed-off-by: H. Kim hyunjun2.kim@samsung.com
Signed-off-by: sungho22.lee sungho22.lee@samsung.com
> [onert][gpu_cl] Add Pool2D operation.

- runtime/onert/backend/gpu_cl/KernelGenerator.cc
- runtime/onert/backend/gpu_cl/KernelGenerator.h
- runtime/onert/backend/gpu_cl/open_cl/kernels/Reshape.cc
- runtime/onert/backend/gpu_cl/open_cl/kernels/Reshape.h
- runtime/onert/backend/gpu_cl/open_cl/kernels/Reshapex4.cc
- runtime/onert/backend/gpu_cl/open_cl/kernels/Reshapex4.h
- runtime/onert/backend/gpu_cl/open_cl/selectors/SimpleSelectors.cc
- runtime/onert/backend/gpu_cl/open_cl/selectors/SimpleSelectors.h
- tests/nnfw_api/src/GenModelTests.cc
1. Add Reshape operation.
2. Add testcases.
Signed-off-by: H. Kim hyunjun2.kim@samsung.com
Signed-off-by: sungho22.lee sungho22.lee@samsung.com
> [onert][gpu_cl] Add Reshape operation.

- compiler/one-cmds/CMakeLists.txt
- compiler/one-cmds/one-profile
This commit adds one-profile.
It will execute profile of backend model file.
> [one-cmds] Add one-profile tool

- compiler/one-cmds/one-profile
This commit fixes typo in one-profile file.
> [one-cmds] Update one-profile usage

- compiler/one-cmds/dummy-driver/CMakeLists.txt
- compiler/one-cmds/dummy-driver/src/dummy-profile.cpp
- compiler/one-cmds/dummy-driver/src/help-profile.cpp
- compiler/one-cmds/tests/one-profile_001.test
- compiler/one-cmds/tests/one-profile_002.test
- compiler/one-cmds/tests/one-profile_003.test
- compiler/one-cmds/tests/one-profile_004.cfg
- compiler/one-cmds/tests/one-profile_004.test
- compiler/one-cmds/tests/one-profile_neg_001.test
This commit adds several test cases for one-profile.
This PR is related to #7360 .
> [one-cmds] Add test cases for one-profile

- compiler/one-cmds/tests/one-profile_003.test
This commit resolves the build break issue.
> [one-cmds] Fix the one-profile testcase

- compiler/luci/pass/include/luci/CircleOptimizer.h
- compiler/luci/pass/include/luci/Pass/ResolveCustomOpMaxPoolWithArgmaxPass.h
- compiler/luci/pass/src/CircleOptimizer.cpp
- compiler/luci/pass/src/ResolveCustomOpMaxPoolWithArgmaxPass.cpp
- compiler/luci/pass/src/ResolveCustomOpMaxPoolWithArgmaxPass.test.cpp
This commit adds resolving pass for MaxPoolWithArgmax op.
related issue: #7229
> [luci] Introduce MaxPoolWithArgmax resolving pass

- infra/debian/compiler/docs/one-profile.1
- infra/debian/compiler/one-compiler.manpages
This commit adds man page for one-profile tool.
> [infra] Add man page for one-profile

- compiler/tf2tfliteV2/tf2tfliteV2.py
This commit adds verbose option.
If the --verbose option is specified, it prints out the detail logs.
> [tf2tfliteV2] Add verbose operation

- compiler/circle2circle/src/Circle2Circle.cpp
This commit adds verbose option to circle2circle tool.
If the --verbose option is specified, it turns on LUCI_LOG env.
> [circle2circle] Add verbose operation

- res/TensorFlowLiteRecipes/MaxPoolWithArgmax_000/test.rule
- res/TensorFlowLiteRecipes/MaxPoolWithArgmax_001/test.rule
- res/TensorFlowLiteRecipes/MaxPoolWithArgmax_002/test.recipe
- res/TensorFlowLiteRecipes/MaxPoolWithArgmax_002/test.rule
This commit adds rules for dredd tests and makes test more variable.
related issue: #7229 
> [res] Improve MaxPoolWithArgmax tflite recipes

- compiler/tflite2circle/driver/Driver.cpp
This commit adds verbose option.
> [tflite2circle] Add verbose option

- compiler/one-cmds/onecc
This commit passes the verbose option to other tools.
> [one-cmds] Pass the verbose option to other tools

- compiler/luci/pass/src/SubstitutePadV2ToPadPass.test.cpp
This adds 2 positive and 5 negative tests for `SubstitutePadV2ToPadPass`.
For #7477
Draft #7478
> [luci] Add Tests for SubstitutePadV2ToPad pass

- infra/debian/compiler/docs/one-import.1
- infra/debian/compiler/one-compiler.manpages
This commit adds man page for one-import tool.
> [infra] Add man page for one-import

- infra/scripts/docker_build_nncc.sh
This commit makes docker_build_nncc script receive version argument.
> [infra] Update nncc build docker script

- infra/debian/compiler/docs/onecc.1
This commit adds the profile details in onecc man page.
> [infra] Update onecc man page

- infra/debian/compiler/docs/one-build.1
- infra/debian/compiler/docs/one-codegen.1
- infra/debian/compiler/docs/one-import-bcq.1
- infra/debian/compiler/docs/one-import-onnx.1
- infra/debian/compiler/docs/one-import-tf.1
- infra/debian/compiler/docs/one-import-tflite.1
- infra/debian/compiler/docs/one-import.1
- infra/debian/compiler/docs/one-optimize.1
- infra/debian/compiler/docs/one-pack.1
- infra/debian/compiler/docs/one-profile.1
- infra/debian/compiler/docs/one-quantize.1
- infra/debian/compiler/docs/onecc.1
This commit updates the man pages content to the current time.
> [infra] Update man page for release

- .ahub/tcchecker-tca/config.yaml
> Fix TCM fail

- docs/release/1.17/index.rst
- docs/release/1.17/release-note-1.17.0.md
> Release Note for 1.17.0

- infra/debian/compiler/changelog
This commit updates debian changelog.
> [infra] Update debian changelog for 1.17.0 release

- runtime/libs/ndarray/CMakeLists.txt
- runtime/libs/ndarray/example/CMakeLists.txt
- runtime/libs/ndarray/example/example_array.cpp
- runtime/libs/ndarray/example/example_no_array.cpp
- runtime/libs/ndarray/include/ndarray/Array.h
- runtime/libs/ndarray/include/ndarray/Common.h
- runtime/libs/ndarray/include/ndarray/ContiguousSpan.h
- runtime/libs/ndarray/include/ndarray/Shape.h
- runtime/libs/ndarray/src/Array.cpp
- runtime/libs/ndarray/src/ContiguousSpan.cpp
- runtime/libs/ndarray/src/detail/cxx14.h
- runtime/libs/ndarray/test/CMakeLists.txt
- runtime/libs/ndarray/test/ndarray_test.cpp
- Revert "[ndarray] Get rid of ndarray (#4304)"
+ This reverts commit fd854f1eee59a2cdffb2b276a4eb9e884701b34f.
- Add more test cases
> Add ndarray library

- compiler/luci-interpreter/src/kernels/Cast.test.cpp
- compiler/luci-interpreter/src/kernels/TestUtils.h
This PR adds more Cast tests to cover all cases at least once.
Related issue: #7368
> [luci-interpreter] Add more Cast tests

- compiler/circle2circle/src/Circle2Circle.cpp
This commit adds 'FoldDepthwiseConv2D' optimization option into circle2circle.
For #7505 
> [circle2circle] Add FoldDepthwiseConv2D optimization

- compiler/luci-interpreter/src/loader/CMakeLists.txt
- compiler/luci-interpreter/src/loader/KernelBuilder.cpp
- compiler/luci-interpreter/src/loader/KernelBuilder.h
- compiler/luci-interpreter/src/loader/KernelBuilderHelper.h
This commit refactors kernel builder for configurable build.
> [luci-interpreter] Refactor kernel builder for configurable build

- compiler/luci-value-test/README.md
Step 1 and Step 2's diagrams are shown in one line.
Now, it will be shown properly in mark-down view.
ONE approval please
> [luci-value-test] Update README.md

- .ahub/tcchecker-tca/config.yaml
- tests/nnfw_api/src/one_op_tests/ArgMinMax.cc
This commit changes ArgMinMax negative test to parameter test.
> [onert/test] Change ArgMinMax param test

- .ahub/tcchecker-tca/config.yaml
- tests/nnfw_api/src/one_op_tests/Softmax.cc
This commit changes Softmax negative test to parameter test.
> [onert/test] Change Softmax param test

- .ahub/tcchecker-tca/config.yaml
- tests/nnfw_api/src/one_op_tests/Concat.cc
This commit changes Concat negative test to parameter test.
> [oenrt/test] Update Concat test

- .ahub/tcchecker-tca/config.yaml
- tests/nnfw_api/src/one_op_tests/Slice.cc
This commit changes Slice negative test to parameter test.
> [onert/test] Update Slice test

- .ahub/tcchecker-tca/config.yaml
- tests/nnfw_api/src/one_op_tests/DepthToSpace.cc
This commit changes DepthToSpace negative test to parameter test.
> [onert/test] Update DepthToSpace test

- compiler/common-artifacts/CMakeLists.txt
This will revise to prepare and use TensorFlow 2.6.0 virtual environment.
> [common-artifacts] Use TF 2.6.0 virt-env

- .ahub/tcchecker-tca/config.yaml
- tests/nnfw_api/src/one_op_tests/Pad.cc
This commit changes Pad negative test to parameter test.
> [onert/test] Update Pad test

- compiler/luci-interpreter/src/kernels/SplitV.cpp
- compiler/luci-interpreter/src/kernels/SplitV.h
- compiler/luci-interpreter/src/kernels/SplitV.test.cpp
This commit adds SplitV kernel with unit tests.
------------------------
For: #7639
Draft: #7640
> [luci-interpreter] Add SplitV kernel

- compiler/circle-partitioner/README.md
Add description to README of circle-partitioner
> [doc] circle-partitioner supports grouping by opname

- compiler/luci-interpreter/include/luci_interpreter/MemoryManager.h
- compiler/luci-interpreter/include/luci_interpreter/SimpleMemoryManager.h
- compiler/luci-interpreter/include/luci_interpreter/core/Tensor.h
- compiler/luci-interpreter/src/CMakeLists.txt
- compiler/luci-interpreter/src/SimpleMemoryManager.cpp
This commit introduces memory manager interface and simple memory manager realization. This is first step of merging changes from pull request #7408 
issue #7355
> [luci-interpreter] Introduce MemoryManager Interface and SimpleMemoryManager

- compiler/tflite2circle/CMakeLists.txt
- compiler/tflite2circle/requires.cmake
This will rollback using mio-tflite260 to upgrade one by one.
> [tfltie2circle] Rollback mio-tflite260

- compiler/tfldump/CMakeLists.txt
- compiler/tfldump/requires.cmake
This will rollback using mio-tflite260 to upgrade one by one.
> [tfldump] Rollback mio-tflite260

- infra/packaging/res/tf2nnpkg.20210910
This will add tf2nnpkg.20210910 for new preset.
> [infra] Add tf2nnpkg.20210910

- infra/cmake/packages/FlatBuffersConfig.cmake
This will revise FlatBuffers build with adding PIC option.
> [infra] Enable PIC option for FlatBuffers

- infra/cmake/packages/FlatBuffersConfig.cmake
This will add message for FlatBuffersConfig when skipped.
> [infra] Message for FlatBuffersConfig

- compiler/arser/include/arser/arser.h
- compiler/arser/tests/arser.test.cpp
This supports the accumulated arguments.
---
> [arser] Support the accumulated arguments

- compiler/luci/pass/include/luci/Pass/ForceQuantParamPass.h
- compiler/luci/pass/src/ForceQuantParamPass.cpp
- compiler/luci/pass/src/ForceQuantParamPass.test.cpp
This adds ForceQuantParam pass to luci.
---
> [luci] Add ForceQuantParam pass to luci

- compiler/luci/pass/include/luci/CircleOptimizer.h
- compiler/luci/pass/src/CircleOptimizer.cpp
This supports ForceQuantParam in quantize.
---
> [luci] Support ForceQuantParam in quantize

- compiler/circle-quantizer/src/CircleQuantizer.cpp
This adds the force_quantparam option.
---
> [circle-quantizer] Add the force_quantparam option

- infra/cmake/packages/FlatBuffersConfig.cmake
This will add flatbuffers with 1.10 version suffix.
> [infra] Add flatbuffers with 1.10 suffix

- compiler/luci-interpreter/pal/linux/PALConv2d.h
- compiler/luci-interpreter/pal/mcu/PALConv2d.h
- compiler/luci-interpreter/src/kernels/Conv2D.cpp
- compiler/luci-interpreter/src/kernels/Conv2D.h
- compiler/luci-interpreter/src/kernels/Conv2D.test.cpp
This PR enables int8 quantizer depthwise conv2d.
Related issue: #7677 
> [luci-interpreter] Support int8 conv2d 

- compiler/luci-interpreter/src/core/Kernel.h
This commit reduce data copying with return vector by reference.
Signed-off-by: Maksim Bronnikov <max120199@gmail.com>
> [luci-interpreter] Return vector by reference

- compiler/mio-tflite260/CMakeLists.txt
This will revise version to use TensorFlow 2.6.0 and related packages.
> [mio-tflite260] Revise to use ver 2.6.0

- res/TensorFlowLiteSchema/2.6.0/schema.fbs
- res/TensorFlowLiteSchema/SCHEMA.lst
This will introduce TFlite 2.6.0 schema and revise download list.
> [res] Introduce tflite 2.6.0 schema

- compiler/luci/pass/include/luci/CircleOptimizer.h
- compiler/luci/pass/include/luci/Pass/FuseAddWithFullyConnectedPass.h
- compiler/luci/pass/src/CircleOptimizer.cpp
- compiler/luci/pass/src/FuseAddWithFullyConnectedPass.cpp
- compiler/luci/pass/src/FuseAddWithFullyConnectedPass.test.cpp
This supports the FuseAddWithFullyConnected pass.
---
Related to: #7724
Draft PR: #7746
> [luci] Support Fuse Add with FC

- compiler/tfldump/src/Dump.cpp
- compiler/tfldump/src/Read.cpp
- compiler/tfldump/src/Read.h
This will enable dump of signature_defs records.
> [tfldump] Dump signature_defs

- compiler/one-cmds/how-to-use-one-commands.txt
- compiler/one-cmds/utils.py
This adds the fuse_add_with_fully_connected option.
---
Related to: #7724
Draft PR: #7746
> [one-cmds] Add Fuse Add with FC option

- compiler/luci-interpreter/pal/linux/pal.cmake
- compiler/luci-interpreter/pal/mcu/pal.cmake
- compiler/luci-interpreter/src/CMakeLists.txt
- compiler/luci-interpreter/src/kernels/CMakeLists.txt
This PR moves platform specific sources and headers to PAL
and adds warning message.
related issue: #7288
> [luci-interpreter] fix pal related cmakes

- compiler/luci-interpreter/README.md
This PR introduces basic usage example and limitations of BuddyMemoryAllocator.
related issue: #7674 
> [luci-interpreter] Add BuddyMemoryAllocator documentation

- compiler/luci/pass/src/PropagateQuantParamPass.cpp
This propagates qparam of TConv op.
> [luci] Propagate qparam of TConv op

- packaging/nnfw.spec
Add missing license into spec file
> Add MPL-2.0 to spec file

- compiler/one-cmds/one-quantize
This improves help message of one-quantize.
---
Related to: https://github.com/Samsung/ONE/issues/7896
> [one-cmds] Improve help message of one-quantize

- compiler/one-cmds/one-quantize
This makes argument group for force_quantparam in one-quantize.
---
Related to: #7896
> [one-cmds] Make argument group for force_quantparam

- compiler/tflchef/proto/tflchef.proto
This will add SignatureDef and TensorMap in schema to tflite with
SignatureDef.
> [tflchef] Add SignatureDef in schema

- compiler/tflchef/core/src/ModelChef.cpp
This will revise cook_graph method to return symbol_table that will
be used to find tensor index from name for SignatureDef.
> [tflchef] Revise cook_graph to return symbol_table

- compiler/tfldump/src/Dump.cpp
This will revise tfldump for SignatureDef to follow format like others.
> [tfldump] Revise tfldump for SignatureDef

- compiler/tflchef/tests/signature_def_index/test.recipe
- compiler/tflchef/tests/signature_def_name/test.recipe
This will introduce two test recipes for SignatureDef.
> [tflchef] Test for SignatureDef

- res/TensorFlowLiteRecipes/SignatureDef_MultiOut_000/test.recipe
This will introduce recipe SignatureDef_MultiOut_000 with multiple outputs.
> [res] SignatureDef_MultiOut_000

- compiler/luci/import/include/luci/Import/CircleReader.h
This commit extends CircleReader with direct-access API methods.
For: #7886
Draft: #7901
> [luci/importer] Extend Reader with direct-access methods

- compiler/luci/import/CMakeLists.txt
- compiler/luci/import/src/Importer.test.cpp
This PR adds unit test for execution plan import.
Related issue: #7831 
> [luci] Test for import execution plan

- compiler/one-cmds/one-build
- compiler/one-cmds/one-codegen
- compiler/one-cmds/one-import-bcq
- compiler/one-cmds/one-import-onnx
- compiler/one-cmds/one-import-tf
- compiler/one-cmds/one-import-tflite
- compiler/one-cmds/one-optimize
- compiler/one-cmds/one-pack
- compiler/one-cmds/one-profile
- compiler/one-cmds/one-quantize
- compiler/one-cmds/onecc
- compiler/one-cmds/utils.py
This PR introduces mechanism for auto detecting available drivers.
This is "auto detect" feature I was talking in https://github.com/Samsung/ONE/pull/7879#issuecomment-951845839
> [one-cmds] Auto detect drivers

- compiler/luci/partition/src/PartitionPGroups.cpp
This will introduce append method extracted fom produce_pgroups for reuse.
> [luci/part] Introduce append for produce_pgroups

- infra/debian/compiler/changelog
This commit updates compiler changelog for 1.19.0.
Related: #7943 
> [infra] Update compiler changelog for 1.19.0

- docs/release/1.19/index.rst
- docs/release/1.19/release-note-1.19.0.md
This commit is a release note for 1.19.0.
Related: #7943
> Release note 1.19.0

- docs/conf.py
- packaging/nnfw.spec
- runtime/contrib/android/api/build.gradle
- runtime/onert/api/include/nnfw_version.h
> [onert] Bump to v1.20.0

- compiler/vconone/CMakeLists.txt
This commit bumps up to 1.20.0.
> [vconone] Bump to 1.20.0

- compiler/tflite2circle/src/CircleModel.cpp
This will revise to store circle input/output sequence with SignatureDef
to follow tflite ordering to make possible for evaluation.
> [tflite2circle] Revise to follow tflite order

- res/TensorFlowLiteRecipes/SignatureDef_MultiOut_001/test.recipe
This will introduce SignatureDef_MultiOut_001 that has different output
names in SignatureDef record.
> [res] Add SignatureDef_MultiOut_001

- compiler/circle-part-value-test/part_eval_one.py
This will revise part_eval_one using variables.
This is to apply tflite SignatureDef better.
> [circle-partition] Revise value test with variables

- compiler/circle-part-value-test/part_eval_one.py
This will revise part_eval_one to read tflite SignatureDef and
use output tensor order according to the SignatureDef's outputs value.
> [circle-partition] Support SignatureDef in value test

- compiler/luci/import/include/luci/Import/CircleReader.h
- compiler/luci/import/src/CircleImportMetadata.cpp
- compiler/luci/import/src/CircleReader.cpp
- compiler/luci/import/src/GraphBuilder.cpp
- compiler/luci/import/src/GraphBuilderMultiOutput.cpp
- compiler/luci/import/src/Importer.cpp
- compiler/luci/import/src/Nodes/CircleCast.cpp
- compiler/luci/import/src/Nodes/CircleConst.cpp
- compiler/luci/import/src/Nodes/CircleCustom.cpp
- compiler/luci/import/src/Nodes/CircleDepthToSpace.cpp
- compiler/luci/import/src/Nodes/CircleDepthwiseConv2D.cpp
- compiler/luci/import/src/Nodes/CircleElu.cpp
- compiler/luci/import/src/Nodes/CircleEqual.cpp
- compiler/luci/import/src/Nodes/CircleExp.cpp
- compiler/luci/import/src/Nodes/CircleExpandDims.cpp
- compiler/luci/import/src/Nodes/CircleFloorDiv.cpp
- compiler/luci/import/src/Nodes/CircleFloorMod.cpp
- compiler/luci/import/src/Nodes/CircleGatherNd.cpp
- compiler/luci/import/src/Nodes/CircleGreater.cpp
- compiler/luci/import/src/Nodes/CircleGreaterEqual.cpp
- compiler/luci/import/src/Nodes/CircleIf.cpp
- compiler/luci/import/src/Nodes/CircleWhile.cpp
- compiler/luci/import/src/ValidateHelpers.cpp
This commit returns reverted commits which related with direct-access API introduction.
-------------
Revert for fa8b9434f1bacf8d5928e1f7751cd50c20d8178e and then for c0c216943a795903633241ee70c9e961a611f5cd (to exclude auto-detect related changes)
Related with: #7965 and #7962
> [luci/import] Return reverted commits

- res/PyTorchExamples/examples/clamp/__init__.py
This PR adds clamp operation in PyTorchExamples.
Related issue: #7939
> [res] clamp example for PyTorch

- res/PyTorchExamples/examples/Conv2d-yuv2rgb/__init__.py
This PR adds YUV to RBG image conversion example.
> [res] YUV to RGB image convertion PyTorch example

- compiler/luci/partition/src/PartitionIRDump.cpp
This will revise partition related structure dump for better understanding.
> [luci/part] Revise dump for better info.

- compiler/luci/import/include/luci/Import/CircleReader.h
- compiler/luci/import/src/CircleReader.cpp
This commit removes unused helpers related to UnPack API from CircleReader.
--------------
For: #7886
Draft: #7901
> [luci/import] Remove helpers for UnPack from CircleReader

- res/PyTorchExamples/examples/strided_slice/__init__.py
This PR adds strided slice PyTorch example.
> [res] strided slice PyTorch example

- res/TensorFlowLiteRecipes/Part_Mul_Sqrt_FC_nobias_000/test.recipe
This will introduce Part_Mul_Sqrt_FC_nobias_000 tflite recipe for
circle-partitioner tests.
> [res] Part_Mul_Sqrt_FC_nobias_000 tflite recipe

- compiler/luci/partition/src/PartitionPGroups.cpp
This will extract group_from_partition method in produce_pgroups.
> [luci/part] Extract group_from_partition method

- compiler/hermes/include/hermes/core/Message.h
- compiler/hermes/include/hermes/core/MessageBuffer.h
- compiler/hermes/src/core/MessageBuffer.cpp
- compiler/hermes/src/core/Source.cpp
This commit passes Severity to Source::buffer.
> [hermes] Pass Severity to Source::buffer

- compiler/luci/partition/src/PartitionPGroups.cpp
This will revise append method that prepares initial PGroup that
also holds virtual nodes for multiple outputs.
> [luci/part] Revise append to hold virtual nodes

- compiler/luci/partition/src/PartitionPGroups.cpp
This will remove not used anymore FindGroupToFollow class.
> [luci/part] Remove not used anymore FindGroupToFollow

- compiler/luci/pass/src/PropagateQuantParamPass.cpp
- compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
This supports propagation of qparam for more Ops.
> [luci] Support propagation of qparam for more Ops

- compiler/luci/partition/src/PartitionMerge.cpp
This will revise merge PGroup case to skip if using nodes are in
differnt groups.
> [luci/part] Partition merge skip for same output

- compiler/hermes-std/include/hermes/ConsoleReporter.h
- compiler/hermes-std/src/ConsoleReporter.cpp
- compiler/hermes-std/src/ConsoleReporter.test.cpp
This commit introduces severity based colored console reporter.
> [hermes] Introduce severity based colored console reporter

- compiler/circle-partitioner/README.md
This will update readme with example and work todo.
> [circle-part] Update readme

- compiler/one-cmds/one-prepare-venv
This PR updates PyTorch version to 1.10.
related issue: #7939
> [one-cmds] Bump PyTorch version

- runtime/onert/backend/gpu_cl/TensorBuilder.cc
- runtime/onert/backend/gpu_cl/TensorBuilder.h
This commit changes template class ClTensorBuilder to general class and remove class alias TensorBuilder.
---
Related issue: #8054
> [onert/gpu-cl] Revise ClTensorBuilder

- runtime/onert/backend/gpu_cl/Backend.h
- runtime/onert/backend/gpu_cl/ClConstantInitializer.h
- runtime/onert/backend/gpu_cl/KernelGenerator.cc
- runtime/onert/backend/gpu_cl/KernelGenerator.h
- runtime/onert/backend/gpu_cl/TensorBuilder.cc
- runtime/onert/backend/gpu_cl/TensorRegistry.h
This commit changes template class ClTensorRegistry to general class and rename to TensorRegistry.
---
Related issue: #8054
> [onert/gpu-cl] Revise ClTensorRegistry

- compiler/record-minmax/src/RecordMinMax.cpp
This tidies code to apply clang-format.
> [record-minmax] Tidy code to apply clang-format

- runtime/onert/backend/gpu_cl/Backend.h
- runtime/onert/backend/gpu_cl/KernelGenerator.cc
- runtime/onert/backend/gpu_cl/KernelGenerator.h
- runtime/onert/backend/gpu_cl/TensorBuilder.cc
- runtime/onert/backend/gpu_cl/TensorBuilder.h
- runtime/onert/backend/gpu_cl/TensorManager.cc
- runtime/onert/backend/gpu_cl/TensorManager.h
- runtime/onert/backend/gpu_cl/TensorRegistry.h
This commit renames ClTensorManager to TensorManager.
> [onert/gpu-cl] Rename ClTensorManager

- compiler/mio-tflite260/CMakeLists.txt
- compiler/mio-tflite260/include/mio_tflite260/Helper.h
- compiler/mio-tflite260/src/Helper.cpp
By introducing utility functions for reading TFLite file, we may expect following things.
- Reduce duplicated codes
- Reduce code modifications When TFLite schema is updated
---
Parent Issue :#8050
Draft : #8051 
NOTE Implementation of each function is copied from original codes, not modified :)
> [mio-tflite260] Introduce utility functions for reading TFLite file

- compiler/mio-circle/CMakeLists.txt
- compiler/mio-circle/include/mio_circle/Helper.h
- compiler/mio-circle/src/Helper.cpp
By introducing utility functions for reading circle file, we may expect following things.
- Reduce duplicated codes
- Reduce code modifications When circle schema is updated
---
Parent issue : #8096 
Draft : #8097
> [mio-circle] Introduce utility functions for reading circle file

- compiler/one-cmds/one-import-pytorch
This PR adds pytorch frontend to one-cmds.
related issue: #7939
> [one-cmds] Add PyTorch frontend

- compiler/circledump/CMakeLists.txt
- compiler/circledump/src/Dump.cpp
- compiler/circledump/src/Read.cpp
- compiler/circledump/src/Read.h
This commit applies `mio-circle` helper functions to `circledump`.
---
Parent issue : #8096
Draft : #8097
> [circledump] Apply mio-circle helper

- compiler/one-cmds/tests/pytorch-operations/CMakeLists.txt
- compiler/one-cmds/tests/pytorch-operations/README.md
- compiler/one-cmds/tests/pytorch-operations/aux_generator.py
- compiler/one-cmds/tests/pytorch-operations/entire_model.test
- compiler/one-cmds/tests/pytorch-operations/example_generator.py
- compiler/one-cmds/tests/pytorch-operations/mar_state_dict_model.test
- compiler/one-cmds/tests/pytorch-operations/mar_torchscript_model.test
- compiler/one-cmds/tests/pytorch-operations/prepare_test_materials.sh
- compiler/one-cmds/tests/pytorch-operations/state_dict_model.test
- compiler/one-cmds/tests/pytorch-operations/torchscript_model.test
This PR adds tests that uses examples from res/PyTorchExamples.
related issue: #7939
> [one-cmds] Add PyTorch tests

- res/PyTorchExamples/examples/RNN-bi/__init__.py
- res/PyTorchExamples/examples/RNN-nobias/__init__.py
- res/PyTorchExamples/examples/RNN-noinit/__init__.py
- res/PyTorchExamples/examples/RNN-relu/__init__.py
This PR adds more RNN examples in res/PyTorchExamples.
Relates issue: #7939 
> [res] Add more PyTorch RNN examples

- compiler/luci/lang/include/luci/IR/CircleQuantParam.h
- compiler/luci/lang/src/CircleQuantParam.cpp
This will introduce copy_QuantParam method.
> [luci] Introduce copy_QuantParam

- tools/tflitefile_tool/ir/graph_stats.py
- tools/tflitefile_tool/parser/model_parser.py
- tools/tflitefile_tool/printer/graph_stats_printer.py
- tools/tflitefile_tool/printer/subgraph_printer.py
Let's separate GraphStats to data and printer.
> [tflitefile_tool] Separate GraphStats to data and printer

- compiler/luci/pass/src/SubstituteSplitVToSplitPass.cpp
- compiler/luci/pass/src/SubstituteSqueezeToReshapePass.cpp
This will revise to use copy_QuantParam in lang.
> [luci/pass] Use copy_QuantParam

- res/PyTorchExamples/examples/LSTM-bi/__init__.py
- res/PyTorchExamples/examples/LSTM-nobias/__init__.py
- res/PyTorchExamples/examples/LSTM-noinit/__init__.py
This PR adds more RNN examples in res/PyTorchExamples.
> [res] Add more PyTorch LSTM examples

- compiler/luci/lang/include/luci/IR/CircleQuantParam.h
- compiler/luci/lang/src/CircleQuantParam.cpp
This will tidy intermediate copy_QuantParam method.
> [luci/IR] Tidy intermediate copy_QuantParam

- res/PyTorchExamples/examples/normalize/__init__.py
This PR adds normalize with parameters corresponding to L2Normalize.
> [res] Add normalize in PyTorchExamples

- compiler/luci/lang/src/CircleQuantParam.test.cpp
This will introduce unit test for copy_quantparam method.
> [luci/IR] Introduce copy_quantparam test

- compiler/luci/pass/include/luci/CircleOptimizer.h
- compiler/luci/pass/include/luci/Pass/CopyQuantParamPass.h
- compiler/luci/pass/src/CircleOptimizer.cpp
- compiler/luci/pass/src/CopyQuantParamPass.cpp
This supports copy quantparam pass.
--
Related to: #8079
Draft PR: #8123
> [luci] Support copy quantparam pass

- tools/tflitefile_tool/model_parser.py
- tools/tflitefile_tool/parser/model_parser.py
This commit introduces Option class. The class is used instead of using
directly args.
> [tflitefile_tool] Introduce Option class

- compiler/circle-quantizer/src/CircleQuantizer.cpp
This supports copy qparam option.
---
Related to: #8079
Draft PR: #8123
> [circle-quantizer] Support copy qparam option

- compiler/one-cmds/one-prepare-venv
This will revise one-cmds-prepare to use latest version of pip and setuptools.
> [one-cmds] Revise version fix of pip, setuptools

- compiler/one-cmds/one-quantize
- compiler/one-cmds/utils.py
This supports copy qparam in one-quantize.
---
Related to: #8079
Draft PR: #8123
> [one-cmds] Support copy qparam in one-quantize

- tools/tflitefile_tool/printer/graph_stats_printer.py
- tools/tflitefile_tool/printer/operator_printer.py
- tools/tflitefile_tool/printer/option_printer.py
- tools/tflitefile_tool/printer/subgraph_printer.py
- tools/tflitefile_tool/printer/tensor_printer.py
This commit revisits printer. Minimize print functions and rename
function names along others.
---
Ref: https://wiki.python.org/moin/PythonSpeed/PerformanceTips
> [tflitefile_tools] Revisit printer

- tools/tflitefile_tool/printer/graph_stats_printer.py
- tools/tflitefile_tool/printer/operator_printer.py
- tools/tflitefile_tool/printer/option_printer.py
- tools/tflitefile_tool/printer/string_builder.py
- tools/tflitefile_tool/printer/tensor_printer.py
Let's introduce StringBuilder in printer. It helps building string for
each printer.
---
> [tflitefile_tools] Introduce StringBuilder in printer

- tools/tflitefile_tool/parser/model_parser.py
- tools/tflitefile_tool/printer/subgraph_printer.py
Let's Merge Printers classes to SubgraphPrinter.
---
> [tflite_tools] Merge Printers classes to SubgraphPrinter

- tools/tflitefile_tool/model_parser.py
- tools/tflitefile_tool/parser/model_parser.py
- tools/tflitefile_tool/parser/tflite_parser.py
Let's revise main and parser classes.
---
> [tflitefile_tools] Revise main and parser classes

- tools/tflitefile_tool/tests/README.md
- tools/tflitefile_tool/tests/main.py
- tools/tflitefile_tool/tests/test_setup.py
- tools/tflitefile_tool/tests/test_string_builder.py
- tools/tflitefile_tool/tests/test_tflite_parser.py
This commit introduces the basic unittest module.
--
> [tflitefile_tools] Introduce unittest

- compiler/circle-execution-plan/src/ExecutionPlanner.cpp
This pr adds to ExecutionPlanner possibility to find execution plan for nodes with multi-output nodes. Now ExecutionPlanner can find offsets for nodes with multi-output nodes.
> [circle-execution-plan] Add execution plan for multi-output nodes

- compiler/luci-interpreter/src/kernels/Add.cpp
- compiler/luci-interpreter/src/kernels/Add.h
- compiler/luci-interpreter/src/kernels/Add.test.cpp
- compiler/luci-interpreter/src/kernels/Utils.cpp
- compiler/luci-interpreter/src/kernels/Utils.h
This PR implements integer Add and related tests.
Related issue #8155 
> [luci-interpreter] Support integer Add

- compiler/record-minmax/src/RecordMinMax.cpp
This commit adds helper to generate integer random input data.
ONE-DCO-1.0-Signed-off-by: Maksim Bronnikov max120199@gmail.com
For: #8065
Draft: #8171
> [record-minmax] Add integer generator of random data

- compiler/one-cmds/one-build
- compiler/one-cmds/one-import-bcq
- compiler/one-cmds/one-import-onnx
- compiler/one-cmds/one-import-tf
- compiler/one-cmds/one-import-tflite
- compiler/one-cmds/onecc
- compiler/one-cmds/utils.py
This PR introduces auto detect of import drivers in one cmd tools.
For #7939 
> [one-cmds] Auto detect available import drivers

- compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
- compiler/luci/pass/src/QuantizedModelVerifier.test.cpp
- compiler/luci/pass/src/VerifyQuantizedNodeChannelWiseGranularity.h
- compiler/luci/pass/src/VerifyQuantizedNodeLayerWiseGranularity.h
- compiler/luci/pass/src/VerifyQuantizedNodeS16Type.h
- compiler/luci/pass/src/VerifyQuantizedNodeU8Type.h
This commit enables quantization of OneHot op.
-------------------
For: #8065
Draft: #8171
> [luci/pass] Enable OneHot quantization

- compiler/luci-interpreter/src/kernels/Equal.cpp
- compiler/luci-interpreter/src/kernels/Equal.h
- compiler/luci-interpreter/src/kernels/Equal.test.cpp
- compiler/luci-interpreter/src/kernels/Utils.cpp
This PR supports S32 and S64 Equal comparison.
> [luci-interpreter] Support Integer Equal

- compiler/luci-interpreter/src/kernels/Less.cpp
- compiler/luci-interpreter/src/kernels/Less.h
- compiler/luci-interpreter/src/kernels/Less.test.cpp
- compiler/luci-interpreter/src/kernels/Utils.cpp
This PR enables Less operation for S32 and S64.
> [luci-interpreter] Support Integer Less

- compiler/luci-interpreter/src/kernels/Div.cpp
- compiler/luci-interpreter/src/kernels/Div.h
- compiler/luci-interpreter/src/kernels/Div.test.cpp
This pr enables integer Div kernels.
Related issue: #8155
> [luci-interpreter] Support Integer Div

- compiler/luci-interpreter/src/kernels/Sub.cpp
- compiler/luci-interpreter/src/kernels/Sub.h
- compiler/luci-interpreter/src/kernels/Sub.test.cpp
This commit enables integer Sub kernels.
Related issue: #8155
> [luci-interpreter] Support Integer Sub

- tools/tflitefile_tool/ir/README.md
- tools/tflitefile_tool/ir/operator.py
- tools/tflitefile_tool/ir/subgraph.py
- tools/tflitefile_tool/ir/tensor.py
- tools/tflitefile_tool/tests/test_operator.py
- tools/tflitefile_tool/tests/test_subgraph.py
- tools/tflitefile_tool/tests/test_tensor.py
Let's introduce new IRs - Subgraph, Operator and Tensor.
---
> [tflitefile_tools] Introduce new IRs

- tools/tflitefile_tool/tests/test_setup.py
Let's use relative path from script path itself to get model path.
> [tflitefile_tool] Use relative path from script

- compiler/luci-interpreter/src/kernels/Mul.cpp
- compiler/luci-interpreter/src/kernels/Mul.test.cpp
This PR adds several negative tests for mul op.
> [luci-interpreter] Add negative tests for MUL op

- tools/tflitefile_tool/parser/tflite/tflite_enum_str_maps.py
- tools/tflitefile_tool/parser/tflite/tflite_operator.py
- tools/tflitefile_tool/parser/tflite/tflite_option.py
- tools/tflitefile_tool/parser/tflite/tflite_parser.py
- tools/tflitefile_tool/parser/tflite/tflite_subgraph.py
- tools/tflitefile_tool/parser/tflite/tflite_tensor.py
Let's introduce new tflite parser files. Now these file are not used
yet.
---
> [tflitefile_tools] Introduce new tflite parser files

- compiler/luci-interpreter/src/kernels/Greater.cpp
- compiler/luci-interpreter/src/kernels/Greater.h
- compiler/luci-interpreter/src/kernels/Greater.test.cpp
- compiler/luci-interpreter/src/kernels/Utils.cpp
This PR enables Integer Greater kernels.
> [luci-interpreter] Support Integer Greater

- infra/command/format
This commit speed ups format by using grep instead of bash loops.
Co-authored-by: Andrey Shedko <a.shedko@samsung.com>
> [infra] Speed up file search in format

- compiler/mio-tflite260/src/Helper.cpp
This commit updates implementation for helper functions,
which are related with BuiltinOperator.
---
Parent Issue : #8239 
Draft : #8240
> [mio-tflite260] Update implementation for BuiltinOperator helper functions

- compiler/mio-tflite260/CMakeLists.txt
- compiler/mio-tflite260/src/Helper.test.cpp
This commit adds testcases for helper functions.
---
Parent Issue : #8239 
Draft : #8240
> [mio-tflite260] Add testcases for helper functions

- compiler/common-artifacts/src/TestDataGenerator.cpp
This will introduce '--input_range' option to specify min,max range of
values for the random input for particular input.
> [common-artifacts] Introduce input_range

- compiler/luci/pass/src/PropagateQuantParamPass.cpp
- compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
This will enable quantization for Gather Op.
> [luci/pass] Quantize const for Gather

- compiler/luci-interpreter/pal/linux/PALGather.h
- compiler/luci-interpreter/src/kernels/Gather.cpp
This commit uses optimized_ops Gather instead of reference_ops.
Related comment: https://github.com/Samsung/ONE/pull/8255#discussion_r779323704
> [luci-interpreter] Use optimized_ops Gather

- compiler/common-artifacts/exclude.lst
This will exclude tests for SVDF Op.
> [common-artifacts] Exclude SVDF

- compiler/common-artifacts/exclude.lst
This will exclude tests for SVDF_001 recipe.
> [common-artifacts] Exclude SVDF_001

- compiler/luci/import/include/luci/Import/Nodes.h
- compiler/luci/import/include/luci/Import/Nodes/CircleSVDF.h
- compiler/luci/import/src/GraphBuilderRegistry.cpp
- compiler/luci/import/src/Nodes/CircleSVDF.cpp
Add import support for SVDF operator.
issue: #8203 
> [luci/import] SVDF support for import

- compiler/circledump/src/Dump.cpp
This will revise to show variable flag for each tensor.
> [circledump] Show tensor variable flag

- compiler/luci/logex/src/FormattedGraph.cpp
This will enable log of CircleVariable.
> [luci/logex] Enable CircleVariable

- compiler/luci/service/src/CircleCloneNode.h
- compiler/luci/service/src/Nodes/CircleVariable.cpp
- compiler/luci/service/src/Nodes/CircleVariable.test.cpp
This will enable clone of CircleVariable.
> [luci/svc] Enable clone of CircleVariable

- compiler/tfldump/src/Dump.cpp
This will revise to show variable flag for each tensor.
> [tfldump] Show tensor variable flag

- compiler/luci/export/src/CircleBuiltinTypesExtractor.h
- compiler/luci/export/src/CircleOps.lst
This will enable export of CircleSVDF node.
> [luci/export] Enable CircleSVDF

- compiler/luci/lang/src/Nodes/CircleSVDF.test.cpp
This will introduce unit test for CircleSVDF IR.
> [luci/lang] SVDF IR test

- compiler/luci/service/src/CircleCloneNode.h
- compiler/luci/service/src/Nodes/CircleSVDF.cpp
- compiler/luci/service/src/Nodes/CircleSVDF.test.cpp
This will enable clone of CircleSVDF node.
> [luci/svc] Enable clone of CircleSVDF

- compiler/luci/service/src/CircleShapeInferenceRule.cpp
- compiler/luci/service/src/CircleTypeInferenceRule.cpp
Add luci/service support for SVDF op
issue #8203 
> [luci/service] SVDF support for luci/service

- compiler/luci/import/src/Nodes/CircleConst.cpp
This will revise import of CircleConst to skip for variable.
> [luci/import] Check variable for CircleConst

- compiler/circle-execution-plan/CMakeLists.txt
- compiler/circle-execution-plan/pal/IScratchpadHelper.h
- compiler/circle-execution-plan/pal/ScratchpadHelperCMSISNN.h
- compiler/circle-execution-plan/pal/ScratchpadHelperLinux.h
- compiler/circle-execution-plan/pal/ScratchpadHelperMCU.h
- compiler/circle-execution-plan/src/ExecutionPlanner.cpp
- compiler/circle-execution-plan/src/ExecutionPlanner.h
This pr adds ScratchpadHelpers for linux, mcu and cmsisnn platforms and it's usage.
draft: #8128
> [circle-execution-plan] Add ScratchpadHelper and it's usage

- res/TensorFlowLiteRecipes/SVDF_000/test.recipe
- res/TensorFlowLiteRecipes/SVDF_001/test.recipe
Add SVDF recipe used for testing
issue: #8203 
> [recipe] SVDF add network recipe

- compiler/luci-value-test/luci_eval_verifier.py
This commit adds support of more data types in luci_eval_verifier.
-----------------
For: #8310
> [luci-value-test] Support more data types

- compiler/common-artifacts/exclude.lst
This will exclude tests for upcomming Part_Add_SVDF_000 recipe.
> [common-artifacts] Exclude Part_Add_SVDF_000

- compiler/luci/partition/src/ConnectNode.h
- compiler/luci/partition/src/Nodes/CircleVariable.cpp
This will enable connect for CircleVariable node.
- there is no action as there is no input.
> [luci/part] Enable connect for CircleVariable

- compiler/luci/partition/src/ConnectNode.h
- compiler/luci/partition/src/Nodes/CircleSVDF.cpp
- compiler/luci/partition/src/Nodes/CircleSVDF.test.cpp
This will enable connect for CircleSVDF node.
> [luci/part] Enable connect for CircleSVDF

- compiler/luci/partition/src/PartitionPGroups.cpp
This will introduce IsVirtualInputNode visitor to check virtual input
node CircleOutputExclude to prepare more nodes.
> [luci/part] Revise check for virtual input nodes

- compiler/luci-interpreter/src/kernels/Gather.test.cpp
This commit adds more tests for gather.
ONE-DCO-1.0-Signed-off-by: yunjayh <yunjayh@gmail.com>
> [luci-interpreter] Add tests for gather

- res/TensorFlowLiteRecipes/Part_Add_SVDF_000/test.recipe
This will introduce Part_Add_SVDF_000 tflite recipe for partition test.
> [res] Introduce Part_Add_SVDF_000 tflite recipe

- compiler/common-artifacts/exclude.lst
This will remove SVDF test items from exclude list to turn on tests.
> [common-artifacts] Include SVDF tests

- compiler/luci-value-test/evalverifytol.sh
This will introduce evalverifytol.sh script to support tolerance with value test.
> [luci/test] Introduce evalverifytol script

- compiler/one-cmds/CMakeLists.txt
- compiler/one-cmds/one-optimize
- compiler/one-cmds/python/constant.py
- compiler/one-cmds/utils.py
This commit introduces constant.py.
Related: #8169 
> [one-cmds] Introduce constant.py

- compiler/luci-value-test/evalverify.sh
This will revise how to use comment of evalverify.sh.
> [luci/test] Revise comment of evalverify.sh

- compiler/luci-value-test/CMakeLists.txt
- compiler/luci-value-test/test.lst
This will introduce testing with tolerance and enable SVDF with it.
> [luci/test] Enable SVDF test with tolerance

- compiler/common-artifacts/exclude.lst
This will enable generation and test of Part_Add_SVDF_000 recipe.
> [common-artifacts] Enable Part_Add_SVDF_000

- compiler/circle-partitioner-test/parts/Part_Add_SVDF_000.part
- compiler/circle-partitioner-test/test.lst
This will enable partitioner test for Part_Add_SVDF_000 recipe.
> [circle/part] Enable Part_Add_SVDF_000 test

- res/TensorFlowLiteRecipes/SVDF_001/test.recipe
This commit adds optional bias input to SVDF operator.
---------------------------
For: #8203
Draft: #8365
> [res] Fix SVDF_001 recipe

- compiler/luci-value-test/test.lst
This commit enables SVDF_001 test case.
For: #8203
Draft: #8365
> [luci-value-test] Enable SVDF_001 case

- compiler/record-minmax/src/RecordMinMax.cpp
This generates positive random int for indices.
> [record-minmax] Generate positive random int

- res/PyTorchExamples/examples/Conv2d-pad/__init__.py
This will introduce PyTorch example of Conv2D with different padding values.
> [res] PyTorch Conv2d with different padding

- compiler/luci/pass/src/QuantizedModelVerifier.test.cpp
This makes the test reload variables for copied const nodes.
---
Related to: #8406
Draft PR: https://github.com/Samsung/ONE/pull/8410
> [luci] Update quantized model verifier test

- compiler/one-cmds/onnx_legalizer.py
This PR adds more comments with some references to onnx documents.
Related issue: #8148 
> [one-cmds] Update onnx_legalizer.py docstrings

- compiler/one-cmds/onnx_legalizer.py
This PR:
- marks internal methods using underscore
- fixes stand-alone script mode (used as a stand-alone tool, not library)
- simplifies interface of some functions
- removes unused variables
Related issue: #8148 
> [one-cmds] Cleanup onnx_legalizer.py code

- infra/docker/bionic/Dockerfile
- infra/docker/focal/Dockerfile
This commit updates dockerfile to remove outdated comment and clang-format version.
> [infra] Update dockerfile for clang-fromat

- tests/nnfw_api/src/CircleGen.cc
- tests/nnfw_api/src/CircleGen.h
- tests/nnfw_api/src/one_op_tests/BatchToSpaceND.cc
Add simple test case for BatchToSpaceND both with crop and without crop
> [onert] Create BatchToSpaceND testcase

- infra/nncc/cmake/buildtool/config/config_armv7l-linux.cmake
- infra/nncc/cmake/buildtool/config/config_linux.cmake
- infra/nncc/cmake/buildtool/cross/toolchain_armv7l-linux.cmake
This will introduce CMake files needed for ARMv7l cross compile.
> [infra] CMake files for ARMv7l cross compile

- compiler/luci/pass/include/luci/Pass/QuantizeWithMinMaxPass.h
- compiler/luci/pass/src/CircleQuantizer.cpp
- compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
This introduces Context to QuantizeWithMinMaxPass.
---
Related to: https://github.com/Samsung/ONE/issues/8454
> [luci] Introduce Context to QuantizeWithMinMaxPass

- compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
This adds comments for how QuantizeWithMinMax works.
> [luci] Add comments for QuantizeWithMinMax

- compiler/luci/pass/src/QuantizeDequantizeWeightsPass.cpp
This extracts functions from QuantizeDequantizeWeights.
---
Related to: https://github.com/Samsung/ONE/pull/8470
> [luci] Extract functions from QuantizeDequantizeWeights

- infra/cmake/packages/JsoncppConfig.cmake
- infra/cmake/packages/JsoncppSourceConfig.cmake
- infra/nncc/CMakeLists.txt
This adds jsoncpp library to the project.
---
Draft PR: #8460
> [infra] Add jsoncpp library

- compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
This moves softmax quantization code to the right place.
> [luci] Move softmax quant code

- compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
This moves fused Tanh quantization code to the right place.
> [luci] Move fused Tanh quantization code

- compiler/luci/pass/src/QuantizeDequantizeWeightsPass.cpp
This applies fake quantization to cloned weights.
---
Related to: #8470
> [luci] Clone fake-quantized weights

- compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
This moves integer scale quantization to the right place.
> [luci] Move int scale quantization code

- docs/howto/how-to-build-compiler.md
- docs/howto/how-to-build-runtime.md
This commit updates document about ubuntu package installation for development environment setting.
> [doc] Update ubuntu package requirement

- compiler/luci/pass/include/luci/CircleQuantizer.h
- compiler/luci/pass/include/luci/Pass/QuantizeDequantizeWeightsPass.h
- compiler/luci/pass/src/CircleQuantizer.cpp
This adds layer parameter for quantization.
---
Draft PR: https://github.com/Samsung/ONE/pull/8460
> [luci] Add layer parameter for quantization

- infra/cmake/packages/ProtobufConfig.cmake
- infra/cmake/packages/ProtobufSource.patch
- infra/cmake/packages/ProtobufSourceConfig.cmake
This will apply patch for cross build from ProdobufSource.
> [infra] Cross build patch for ProtobufSource

- infra/cmake/packages/HDF5Config.cmake
- infra/cmake/packages/HDF5Source.patch
- infra/cmake/packages/HDF5SourceConfig.cmake
This will apply patch for cross build from HDF5Source.
> [infra] Cross build patch for HDF5Source

- compiler/one-cmds/tests/onnx_legalize_run_compare.py
This PR:
- fixes comment
- removes redundant import
fixes for #8431
> [one-cmds] Cleanup onnx_lagalize_run_compare script

- compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
This applies activation quantization to visitor target, not args.
> [luci] Apply activation quantization to visitor target

- infra/cmake/packages/JsoncppConfig.cmake
This will revise JsoncppConfig for cross build as disable test and find
only in overlay.
> [infra] Revise JsoncppConfig for cross build

- compiler/luci/pass/src/PropagateQParamBackwardPass.cpp
This PR tidies PropagateQParamBackwardPass.cpp file.
---
Related to comments in https://github.com/Samsung/ONE/pull/8515 and https://github.com/Samsung/ONE/pull/8509
> [luci] Tidy PropagateQParamBackwardPass.cpp file

- compiler/luci/pass/src/QuantizedModelVerifier.test.cpp
This will fix pass test with logging when LUCI_LOG is given.
> [luci/pass] Fix pass test with logging

- infra/cmake/packages/HDF5Config.cmake
This will add skip message in HDF5Config when HDF5Source not found.
> [infra] Skip message in HDF5Config

- compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
This applies QuantizeBias to visitor target.
---
> [luci] Apply QuantizeBias to visitor target

- compiler/luci/pass/src/CircleQuantizer.cpp
- compiler/luci/pass/src/QuantizedModelVerifier.cpp
- compiler/luci/pass/src/QuantizedModelVerifier.h
This introduces Context of QuantizedModelVerifier.
---
> [luci] Introduce Context of QuantizedModelVerifier

- compiler/luci-value-test/evalverify_ref.sh
- compiler/luci-value-test/evalverifytol_ref.sh
- compiler/luci-value-test/luci_eval_verifier_ref.py
This will introduce evaluation scripts with data from reference folder.
- these scripts are used to test for cross build binaries
> [luci/value-test] Evaluate scripts with reference

- res/TensorFlowLiteRecipes/Net_Conv_QuantDequant_000/test.recipe
This adds qparam to Conv_QuantDequant recipe.
---
Related to: https://github.com/Samsung/ONE/issues/8525
> [res] Add qparam to Conv_QuantDequant recipe.

- compiler/luci/pass/include/luci/Pass/QuantizeWithMinMaxPass.h
- compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
This uses layer info during quantization.
---
> [luci] Use layer info during quantization

- compiler/luci-value-test/CMakeLists.txt
This will revise test as for host and for target device.
> [luci/value-test] Revise test in target

- compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
This inserts Quantize Ops to mixed-precision points.
---
> [luci] Insert Quantize Op to mixed-precision point

- compiler/nnc/unittests/soft_backend/ModelAnalyzer.cpp
This commit adds "algorithm" header include.
---
Draft: #8572
> [nnc] Add header for unittest

- compiler/circle-part-value-test/part_eval_one.py
This commit supports int16 data type.
> [circle-part-value-test] Support int16 type

- compiler/luci-pass-value-test/eval_result_verifier.py
This commit supports int16 data type.
> [luci-pass-value-test] Support int16 type

- compiler/luci-value-test/luci_eval_verifier.py
- compiler/luci-value-test/luci_eval_verifier_ref.py
This commit supports int16 data type.
> [luci-value-test] Support int16 type

- compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
This removes redundant Quantize Ops generated during quantization.
---
> [luci] Remove redundant Quantize Op in QuantizeWithMinMax

- compiler/luci/pass/src/PropagateQParamForwardPass.test.cpp
This initializes pointers with nullptr.
> [luci] Initialize pointers with nullptr

- compiler/luci/pass/src/QuantizeDequantizeWeightsPass.cpp
This uses layer info during FakeQuantization.
---
Related to: https://github.com/Samsung/ONE/issues/8398
> [luci] Use layer info during FakeQuantization

- compiler/luci/pass/src/QuantizationUtils.cpp
- compiler/luci/pass/src/QuantizationUtils.h
This adds comments for quantization util functions.
> [luci] Add comments for quantization util functions.

- res/TensorFlowLiteRecipes/Quant_Conv_Mul_Add_002/test.qconf.json
- res/TensorFlowLiteRecipes/Quant_Conv_Mul_Add_002/test.recipe
- res/TensorFlowLiteRecipes/Quant_Conv_Mul_Add_002/test.rule
This adds quant test Quant_Conv_Mul_Add_002.
---
Related to: https://github.com/Samsung/ONE/pull/8618
> [res] Add quant test Quant_Conv_Mul_Add_002

- compiler/luci/pass/src/QuantizationUtils.cpp
- compiler/luci/pass/src/QuantizationUtils.h
- compiler/luci/pass/src/QuantizeActivation.cpp
This extracts code to quantize special activation.
---
Draft PR: https://github.com/Samsung/ONE/pull/8614
> [luci] Extract code to quantize special activation

- res/TensorFlowLiteRecipes/Quant_Conv_Mul_Add_001/test.qconf.json
- res/TensorFlowLiteRecipes/Quant_Conv_Mul_Add_001/test.recipe
- res/TensorFlowLiteRecipes/Quant_Conv_Mul_Add_001/test.rule
This adds quant test Quant_Conv_Mul_Add_001.
---
Related to: https://github.com/Samsung/ONE/pull/8618
> [res] Add quant test Quant_Conv_Mul_Add_001

- compiler/luci/pass/src/QuantizePreCheckerPass.test.cpp
This commit adds some tests for QuantizePreCheckerPass.
from https://github.com/Samsung/ONE/pull/8606#issuecomment-1063797186
for https://github.com/Samsung/ONE/issues/8580
> [quantizer] Add tests for QuantizePreCheckerPass

- compiler/luci/pass/src/PropagateQParamBackwardPass.cpp
- compiler/luci/pass/src/QuantizationUtils.cpp
- compiler/luci/pass/src/QuantizationUtils.h
- compiler/luci/pass/src/QuantizeActivation.cpp
- compiler/luci/pass/src/QuantizeBias.cpp
- compiler/luci/pass/src/QuantizeWeights.cpp
This extracts quant_const function to reduce duplicate codes.
> [luci] Extract function to reduce duplicate codes

- compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
This creates Quantize op by activation qtype.
---
Fix for https://github.com/Samsung/ONE/issues/8586
> [luci] Create Quantize op by activation qtype.

- compiler/luci-value-test/CMakeLists.txt
This will fix indentation of CMakeLists.txt file.
> [luci-value-test] Fix indentation

- compiler/circle-partitioner-test/CMakeLists.txt
This will revise to use circle-partitioner tool with hyphen.
> [cir-part-test] Use circle-partitioner

- compiler/pota-quantization-value-test/CMakeLists.txt
- compiler/pota-quantization-value-test/test_fake_wquant_with_config.sh
- compiler/pota-quantization-value-test/test_quantization_with_config.sh
This introduces mixed-precision qconfig tests.
---
Related to: https://github.com/Samsung/ONE/issues/8596
Draft PR: #8656
> [pota-quantization-value-test] Introduce qconfig test

- compiler/moco-tf/CMakeLists.txt
- compiler/moco-tf/src/Transforms.h
This will revise modo-tf to use loco-ex.
> [moco-tf] Include logo-ex

- res/TensorFlowLiteSchema/2.7.0/schema.fbs
- res/TensorFlowLiteSchema/2.8.0/schema.fbs
This will add tflite schema of version 2.7.0 and 2.8.0
> [res] tflite schema 2.7.0 and 2.8.0

- res/CircleSchema/0.3/circle_schema.fbs
This will add current circle schema as 0.3 version to res folder.
> [res] circle schema as 0.3

- compiler/mio-circle04/CMakeLists.txt
- compiler/mio-circle04/README.md
- compiler/mio-circle04/example.cpp
- compiler/mio-circle04/include/mio_circle/Helper.h
- compiler/mio-circle04/src/Helper.cpp
- compiler/mio-circle04/src/Helper.test.cpp
This will introduce mio-circle04 that provides model I/O of circle schema v0.4.
> [mio-circle04] Introduce mio-circle04

- compiler/circle-inspect/CMakeLists.txt
- compiler/circle-inspect/requires.cmake
- compiler/circle-inspect/src/Reader.cpp
This will revise to use mio-circle04.
> [circle-inspect] Revise to use mio-circle04

- compiler/circle-verify/CMakeLists.txt
- compiler/circle-verify/requires.cmake
This will revise to use mio-circle04.
> [circle-verify] Revise to use mio-circle04

- compiler/circledump/src/OpPrinter.cpp
This will enable to print InstNorm attributes.
> [circledump] Print InstNorm

- compiler/tflite2circle/CMakeLists.txt
- compiler/tflite2circle/requires.cmake
- compiler/tflite2circle/src/CircleModel.cpp
- compiler/tflite2circle/src/DataLookup.cpp
- compiler/tflite2circle/src/DataLookup.h
This will revise to use mio_circle04 to version up schema.
> [tflite2circle] Revise to use mio_circle04

- compiler/circledump/CMakeLists.txt
- compiler/circledump/README.md
- compiler/circledump/requires.cmake
- compiler/circledump/src/Dump.cpp
- compiler/circledump/src/Read.cpp
- compiler/circledump/src/Read.h
This will revise mio-circle04 to upgrade circle schema and show
SignatureDef attributes.
> [circle-dump] Revise to use mio-circle04

- compiler/luci/pass/src/ReplaceMulAddWithDepthwiseConvPass.cpp
- compiler/luci/pass/src/ReplaceMulAddWithDepthwiseConvPass.test.cpp
This supports rank4 gamma/beta in ReplaceMulAddWithDConv.
> [luci] Support rank4 in ReplaceMulAddWithDConv

- compiler/circle-tensordump/CMakeLists.txt
- compiler/circle-tensordump/requires.cmake
- compiler/circle-tensordump/src/Reader.cpp
This will revise to use mio-circle04.
> [circle-tensordump] Revise to use mio-circle04

- res/TensorFlowLiteRecipes/Net_Gather_SparseToDense_AddV2_000/test.recipe
This commit adds recipe for Gather/SparceToDense_AddV2/Cast pattern.
Draft: https://github.com/Samsung/ONE/pull/8674
for https://github.com/Samsung/ONE/issues/8375#issuecomment-1070126309
> [recipe] Add recipe for Gather/SparceToDense_AddV2/Cast pattern

- compiler/luci/import/include/luci/Import/CircleReader.h
- compiler/luci/import/src/CircleReader.cpp
This will tidy unused codes from using mio-circle04.
> [luci/import] Tidy unused codes

- infra/packaging/build
- infra/packaging/preset/20220323
- infra/packaging/preset/20220323_windows
- infra/packaging/res/tf2nnpkg.20220323
This will introduce preset 20220323 with mio-circle04 and set to use this.
> [infra] Compiler preset 20220323

- compiler/luci/pass/include/luci/CircleOptimizer.h
- compiler/luci/pass/include/luci/Pass/FoldGatherPass.h
- compiler/luci/pass/src/CircleOptimizer.cpp
- compiler/luci/pass/src/FoldGatherPass.cpp
- compiler/luci/pass/src/FoldGatherPass.test.cpp
This pr adds fold gather pass to luci/pass. This pass can remove Gather operation which can be folded.
draft: #8682
for issue: #8375 
> [luci] Add Fold Gather pass

- runtime/onert/frontend/base_loader/include/base_loader.h
- runtime/onert/frontend/circle/src/circle_loader.cc
- runtime/onert/frontend/circle_schema/include/circle_schema_generated.h
- runtime/onert/frontend/tflite/src/tflite_loader.cc
- runtime/onert/frontend/tflite/src/tflite_schema_generated.h
This commit update schema headers.
These headers are generated fron TFLite 2.7.0 schema and circle schema 0.4.
---
Related issue: #8712
> [onert/frontend] Update schema version

- compiler/luci/pass/include/luci/CircleOptimizer.h
- compiler/luci/pass/src/CircleOptimizer.cpp
This commit removes unused functions in `CircleOptimizer`.
---
Parent Issue : #8393
> [luci/pass] Remove unused functions

- infra/packaging/preset/20220323
- infra/packaging/preset/20220323_windows
This adds dio-hdf5 to preset.
---
For https://github.com/Samsung/ONE/issues/8586
> [infra] Add dio-hdf5 to preset

- compiler/circle-eval-diff/CMakeLists.txt
- compiler/circle-eval-diff/README.md
- compiler/circle-eval-diff/driver/Driver.cpp
- compiler/circle-eval-diff/requires.cmake
This first introduces circle-eval-diff module.
---
Related to: #8634
Draft PR: https://github.com/Samsung/ONE/pull/8741
> [circle-eval-diff] Introduce circle-eval-diff

- compiler/circle-eval-diff/CMakeLists.txt
- compiler/circle-eval-diff/src/MetricPrinter.cpp
- compiler/circle-eval-diff/src/MetricPrinter.h
- compiler/circle-eval-diff/src/MetricPrinter.test.cpp
This introduces MetricPrinter class and its tests.
---
Related to: https://github.com/Samsung/ONE/issues/8634
Draft PR: https://github.com/Samsung/ONE/pull/8741
> [circle-eval-diff] Introduce metric printer

- infra/nncc/cmake/CfgOptionFlags.cmake
- infra/nncc/cmake/options/options_x86_64-linux.cmake
This will enable to provide platform specific options.
> [infra/nncc] Provide platform specific options

- compiler/luci-interpreter/pal/linux/pal.cmake
- compiler/luci-interpreter/src/kernels/L2Pool2D.test.cpp
This will revise ARMv7l-linux PAL to support NEON with RUY.
> [luci-intp] Revise to support NEON for armv7l-linux

- infra/docker/bionic/Dockerfile
This will revise Dockerfile to install python3.8 to bionic.
> [infra/docker] Add python3.8 to bionic

- infra/docker/bionic/Dockerfile
This commit updates bionic dockerfile to fix build fail.
> [infra/dockerfile] Fix dockerfile

- compiler/common-artifacts/CMakeLists.txt
This will remove not used anymore venv_1_13_2.
> [common-artifacts] Remove venv_1_13_2

- infra/nnfw/cmake/packages/TRIXEngineConfig.cmake
- infra/nnfw/cmake/packages/TRIXEngineConfigVersion.cmake
- infra/nnfw/cmake/packages/TRIXEngineConfigVersion.extra.cpp
- infra/nnfw/cmake/packages/TRIXEngineConfigVersion.major.cpp
- infra/nnfw/cmake/packages/TRIXEngineConfigVersion.minor.cpp
This commit introduces cmake package config for npu-engine (trix-engine) package.
---
Related issue: #8768
Draft: #8769
> [infra] Introduce TRIXEngine package cmake config

- compiler/luci/pass/include/luci/CircleQuantizer.h
- compiler/luci/pass/src/CircleQuantizer.cpp
This supports fake quantization option.
---
Related to: https://github.com/Samsung/ONE/issues/8731
Draft PR: https://github.com/Samsung/ONE/pull/8765
> [luci] Support fake quantization option

- compiler/circle-quantizer/src/CircleQuantizer.cpp
This adds fake quantization option.
---
Related to: https://github.com/Samsung/ONE/issues/8731
Draft PR: https://github.com/Samsung/ONE/pull/8765
> [circle-quantizer] Add fake quantization option

- compiler/common-artifacts/CMakeLists.txt
This will remove to install specific pip, setuptools as the issue is not
reproduced anymore.
> [common-artifacts] Remove version for pip, setuptools

- nnpackage/spec/10_packaging_and_manifest.md
This commit updates nnpackage spec to support tvn type model.
---
Related issue: #8784
> [nnpackage] Add model type

- runtime/onert/core/include/compiler/LoweredGraph.h
- runtime/onert/core/src/compiler/LoweredGraph.cc
This commit merges LoweredGraph constructor duplicated code into lowerGraph().
---
Related issue: #8786
> [onert] Merge LoweredGraph constructor code

- compiler/luci/pass/src/ConvertToFakeQuantizedModelPass.cpp
This supports Add in fake quantization.
---
Related to: https://github.com/Samsung/ONE/issues/8797
Draft PR: #8798
> [luci] Support Add in Fake Quantization

- compiler/common-artifacts/CMakeLists.txt
This will prepare venv_2_8_0 virtual environment folder that will
provide TensorFlow 2.8.0
> [common-artifacts] Prepare venv_2_8_0

- compiler/dio-hdf5/src/HDF5Importer.test.cpp
This checks return value of remove.
> [dio-hdf5] Check return value of remove

- compiler/circle-quantizer-dredd-recipe-test/CMakeLists.txt
- compiler/circle-quantizer-dredd-recipe-test/test.lst
This supports test for fake quantization.
---
Related to: https://github.com/Samsung/ONE/issues/8797
Draft PR: https://github.com/Samsung/ONE/pull/8798
> [circle-quantizer-dredd] Support fake quantization test

- infra/docker/bionic/Dockerfile
- infra/docker/focal/Dockerfile
This will revise docker to use python3 for pip3 command.
> [infra] Revise docker to use python3 for pip3

- infra/docker/bionic/Dockerfile
This will revise dockerfile for bionic to install python 3.6 pip numpy.
> [infra] Install python 3.6 package on bionic dockerfile

- runtime/onert/backend/CMakeLists.txt
- runtime/onert/backend/acl_common/AclBackendContext.h
- runtime/onert/backend/acl_common/CMakeLists.txt
- runtime/onert/backend/cl_common/CMakeLists.txt
- runtime/onert/backend/cl_common/include/cl_common/BackendContext.h
- runtime/onert/backend/gpu_cl/BackendContext.cc
- runtime/onert/backend/gpu_cl/BackendContext.h
- runtime/onert/backend/gpu_cl/CMakeLists.txt
This commit introduces cl-common backend library.
It will be used by gpu-cl backend and acl-common library.
---
Related issue: #8786
Draft: #8808
> [onert/cl_common] Introduce cl-common library

- tools/nnpackage_tool/model2nnpkg/README.md
- tools/nnpackage_tool/model2nnpkg/model2nnpkg.sh
It updates model2nnpkg for trix.
- Update metadata version
- Update help message and README.md
Related: #8775
> [nnpackage_tool] Update model2nnpkg for trix

- infra/nnfw/config/gbs.conf
This commit changes tizen development package server name to IP.
> [infra] Change tizen package server name

- compiler/common-artifacts/exclude.lst
This will enable tests(remove from exclude list) that are working as of now.
> [common-artifacts] Enable tests

- infra/scripts/docker_build_test_x64.sh
This commit introduce BUILD_OPTIONS for CI script to pass build option. (ex. TRIX_ENGINE_PREFIX)
> [infra/script] Pass build option

- res/TensorFlowLiteRecipes/SignatureDef_MultiOut_000/test.recipe
- res/TensorFlowLiteRecipes/SignatureDef_MultiOut_001/test.recipe
This will temporary disable signature_def for build break.
> [res] Temporay disable signature_def

- compiler/one-cmds/how-to-prepare-virtualenv.txt
This will update how-to-prepare-virtualenv document for Windows.
> [one-cmds] Update document for Windows

- res/TensorFlowLiteRecipes/SignatureDef_MultiOut_000/test.recipe
- res/TensorFlowLiteRecipes/SignatureDef_MultiOut_001/test.recipe
This will re-enable signature_def test from tflite scehma v3a.
> [res] Re-enable signature_def test

- runtime/onert/core/src/compiler/Compiler.cc
This commit introduces option printing function to reduce code duplication.
---
Related issue: #8786
> [onert] Introduce option printing function

- runtime/onert/backend/cpu/ops/OperationUtils.cc
- runtime/onert/backend/cpu/ops/OperationUtils.h
- runtime/onert/backend/ruy/ops/OperationUtils.h
- runtime/onert/backend/xnnpack/ops/OperationUtils.h
- runtime/onert/core/include/util/CalculateActivationRange.h
This commit introduces CalculateActivationRange in core util.
---
> [onert] Introduce common CalculateActivationRange

- runtime/onert/core/src/ir/OperationDumper.cc
This commit reduces code duplication in OperationDumper.cc.
---
> [onert] Revisit OperationDumper

- runtime/onert/api/src/nnfw_api_internal.cc
This commit introduces fillTensorInfo function and updates shape setting implementation.
---
> [onert] Revisit tensorinfo API implementation

- runtime/onert/api/src/nnfw_api_internal.cc
It adds loading tvn type model using trix loader.
Draft: #8831
Related: #8775
> [onert/api] Support trix model type

- runtime/onert/frontend/nnapi/wrapper/OperationFactory.cc
This commit introduces getActivation in OperationFactory.
---
elated issue: https://github.com/Samsung/ONE/issues/8786
> [onert] Introduce getActivation in OperationFactory

- runtime/onert/backend/trix/DevContext.h
- runtime/onert/backend/trix/KernelGenerator.cc
- runtime/onert/backend/trix/KernelGenerator.h
- runtime/onert/backend/trix/ops/BulkLayer.cc
- runtime/onert/backend/trix/ops/BulkLayer.h
This commit adds BulkLayer on TRIX backend.
It uses trix-engine library to handle TRIX device.
draft pr: #8805
> [onert] Add BulkLayer on TRIX backend

- runtime/onert/frontend/base_loader/include/base_loader.h
This commit introduces helper function getCustomOpAttrMap to get custom op's attribute.
---
> [onert] Introduce getCustomOpAttrMap in BaseLoader

- compiler/cli/CMakeLists.txt
> [cli] Revise test with ENABLE_TEST

- tests/nnfw_api/src/one_op_tests/Equal.cc
This commit updates Equal GenModelTest to test more type.
> [onert/test] Revisit Equal test

- compiler/enco/CMakeLists.txt
- compiler/enco/core/CMakeLists.txt
- compiler/enco/frontend/caffe/CMakeLists.txt
- compiler/enco/frontend/tflite/CMakeLists.txt
> [enco] Revise test with ENABLE_TEST

- compiler/morph/CMakeLists.txt
> [morph] Revise test with ENABLE_TEST

- compiler/nest/core/CMakeLists.txt
> [nest] Revise test with ENABLE_TEST

- compiler/nike/CMakeLists.txt
> [nike] Revise test with ENABLE_TEST

- compiler/nnop/CMakeLists.txt
> [nnop] Revise test with ENABLE_TEST

- compiler/oneco/CMakeLists.txt
> [oneco] Revise test with ENABLE_TEST

- infra/packaging/preset/20220323
This will revise preset 20220323 to remove unused modules.
> [infra] Revise preset 20220323

- runtime/onert/backend/trix/CMakeLists.txt
- runtime/onert/frontend/trix/CMakeLists.txt
Let's assume that trix-engine support backend compatibility.
> [onert/trix] Build on higher version

- compiler/arser/include/arser/arser.h
This commit sets type default value.
> [arser] Set type default value

- compiler/arser/include/arser/arser.h
This will introduce Helper class for common version and verbose option.
> [arser] Helper for version and verbose

- .ahub/sam/exclude.txt
This will update sam/exclude.txt list file for compiler.
> [ahub] Update exclude list for compiler

- infra/command/gen-coverage-report
- runtime/libs/ndarray/test/CMakeLists.txt
- runtime/libs/ndarray/test/ndarray_test.cpp
This commit adds more test for ndarray library.
---
Related issue: #8935
> [onert/ndarray] Add more tests

- runtime/onert/core/src/exec/feature/nhwc/View.h
- runtime/onert/test/CMakeLists.txt
- runtime/onert/test/core/exec/feature/MockTensor.h
- runtime/onert/test/core/exec/feature/nchw/Reader.cc
- runtime/onert/test/core/exec/feature/nchw/View.cc
- runtime/onert/test/core/exec/feature/nhwc/Reader.cc
- runtime/onert/test/core/exec/feature/nhwc/View.cc
This commit adds Reader and View gtest.
> [onert/test] Add Reader and View test

- compiler/circle-quantizer/CMakeLists.txt
- compiler/circle-quantizer/requires.cmake
- compiler/circle-quantizer/src/CircleQuantizer.cpp
This will revise to use ImporterEx to reduce ducplicate codes.
> [circle-quantizer] Revise using ImporterEx

- compiler/circle-partitioner/CMakeLists.txt
- compiler/circle-partitioner/requires.cmake
- compiler/circle-partitioner/src/CirclePartitioner.cpp
This will revise to use ImporterEx to reduce ducplicate codes.
> [circle-part] Revise using ImporterEx

- compiler/circle-eval-diff/driver/Driver.cpp
> [circle-eval-diff] Revise arser usage

- compiler/circle-execution-plan/src/CircleExecutionPlan.cpp
> [circle-exec-plan] Revise arser usage

- compiler/circle-inspect/driver/Driver.cpp
This will revise arser usage to remove default value settings.
> [circle-inspect] Revise arser usage

- compiler/circle-partitioner/src/CirclePartitioner.cpp
> [circle-part] Revise arser usage

- compiler/circle-quantizer/src/CircleQuantizer.cpp
- use helper for version/verbose
> [circle-quant] Revise arser usage

- compiler/circlechef/tools/file/Driver.cpp
- compiler/circlechef/tools/reverse/Driver.cpp
This will revise arser usage to reduce duplicate codes; but not for scores
> [circlechef] Revise arser usage

- compiler/circle2circle/src/Circle2Circle.cpp
- use helper for version/verbose
> [circl2circle] Revise arser usage

- compiler/tflite2circle/driver/Driver.cpp
- use helper for version/verbose
> [tflite2circle] Revise arser usage

- .ahub/sam/exclude.txt
This will revise exclude list to check tools that are included in -dev package.
> [ahub] Revise exclude list

- compiler/circle-tensordump/driver/Driver.cpp
> [circle-tensordump] Revise arser usage

- compiler/circle-verify/src/Driver.cpp
> [circle-verify] Revise arser usage

- compiler/luci/pass/src/FuseInstanceNormPass.cpp
This will extract common code from pattern v1 and v5 of FuseInstanceNormPass.
> [luci/pass] Extract common code from FuseInstNorm

- compiler/luci/service/src/CircleShapeInferenceRule.cpp
This will introduce common code for shape infercnce of CircleArgMax and
CircleArgMin to reduce duplicate codes.
> [luci/svc] Common code for ArgMax, ArgMin

- compiler/luci/service/src/CircleShapeInferenceRule.cpp
This will introduce common code for shape infercnce of CircleResizeBilinear
and CircleResizeNearestNeighbor to reduce duplicate codes.
> [luci/svc] Common code for Resize

- compiler/circledump/driver/Driver.cpp
This will revise arser usage as default settings can be removed.
> [circledump] Revise arser usage

- compiler/record-minmax/driver/Driver.cpp
- use helper for version/verbose
> [record-minmax] Revise arser usage

- compiler/luci/pass/src/FuseInstanceNormPass.cpp
This will extract common code from pattern v3 and v4 of
FuseInstanceNormPass.
> [luci/pass] Extract more common code from FuseInstNorm

- compiler/tfl-verify/src/Driver.cpp
This will revise arser usage as default settings can be removed.
> [tfl-verify] Revise arser usage

- compiler/tfldump/driver/Driver.cpp
This will revise arser usage as default settings can be removed.
> [tfldump] Revise arser usage

- compiler/tfl-inspect/driver/Driver.cpp
This will revise arser usage as default settings can be removed.
> [tfl-inspect] Revise arser usage

- compiler/circledump/src/Read.cpp
This will revise to guard buffer pointers.
> [circledump] Guard buffers

- compiler/luci-interpreter/src/loader/nodes/Quantize.cpp
- compiler/luci-interpreter/src/loader/nodes/SVDF.cpp
This will add missing arity assert check in loader.
> [luci-inpt] Add missing arity check in loader

- .ahub/tcchecker-tca/config.yaml
This commit updates test root directory and test case condition.
> [infra] Revise TCM configuration

- compiler/mio-circle04/include/mio_circle/Helper.h
This will introduce as_index_vector method to helper to convert
flatbuffres Vector type to std vector.
> [mio-circle04] Introduce as_index_vector to helper

- compiler/circle-eval-diff/driver/Driver.cpp
- compiler/circle-eval-diff/include/CircleEvalDiff.h
- compiler/circle-eval-diff/src/CircleEvalDiff.cpp
- compiler/circle-eval-diff/src/MetricPrinter.cpp
- compiler/circle-eval-diff/src/MetricPrinter.h
- compiler/circle-eval-diff/src/MetricPrinter.test.cpp
This adds MAPE metric printer.
> [circle-eval-diff] Add MAPE metric printer

- compiler/mio-circle04/include/mio_circle/Reader.h
- compiler/mio-circle04/src/Reader.cpp
- compiler/mio-circle04/src/Reader.test.cpp
This will introduce simple Reader class as common codes.
> [mio-circle04] Introduce Reader

- tests/tools/nnpackage_run/src/rawformatter.cc
nnpackage_run can accept multiple inputs.
--load:raw in
will get input raw data from in.0, in.1, in.2,..., in.{N-1}
where N is number of inputs, determined by nnfw info query api.
#9012
```
$ tree add.q8
add.q8
├── add.q8.circle
├── add.q8.expected.0
├── add.q8.in.0
├── add.q8.in.1
├── add.q8.tvn
└── metadata
└── MANIFEST
$ BACKENDS="trix;cpu" ./Product/x86_64-linux.debug/out/bin/nnpackage_run \
--load:raw add.q8/add.q8.in \
--dump:raw add.q8/add.q8.out \
add.q8
( ... )
add.q8/add.q8.out.0 is generated.
===================================
MODEL_LOAD   takes 0.959 ms
PREPARE      takes 6.088 ms
EXECUTE      takes 331.659 ms
- MEAN     :  331.659 ms
- MAX      :  331.659 ms
- MIN      :  331.659 ms
- GEOMEAN  :  331.659 ms …
```
> [nnpackage_run] Support multiple input for load:raw option

- compiler/circledump/src/Dump.cpp
- compiler/circledump/src/OpPrinter.cpp
This will revise to use mio::circle::Reader helper class.
> [circledump] Use mio Reader

- compiler/circle-tensordump/src/Dump.cpp
This will revise to use mio::circle::Reader helper class.
> [circle-tensordump] Use mio Reader

- res/TensorFlowLiteRecipes/FullyConnected_007/test.recipe
- res/TensorFlowLiteRecipes/FullyConnected_007/test.rule
This PR adds Fully Connected test with non-const weight.
full draft: #8927 
Signed-off-by: a.shedko <a.shedko@samsung.com>
> [res] Add Fully Connected test with non-const weight

- compiler/circle-inspect/src/Dump.cpp
This will revise to use mio-circle Reader and Helper class.
> [circle-inspect] Use mio-circle for Reader

- compiler/circle-eval-diff/include/CircleEvalDiff.h
This adds comments for metric.
---
Related to: https://github.com/Samsung/ONE/pull/9015#discussion_r855726390
> [circle-eval-diff] Add comments for metric

- docs/release/1.20/index.rst
- docs/release/1.20/release-note-1.20.0.md
> Release Note for ONE 1.20.0

- infra/debian/compiler/changelog
- infra/debian/runtime/changelog
- Now, debian pkgs provides version 1.20.0
> [debian] Update version to 1.20.0

- res/TensorFlowLiteRecipes/Quant_Add_001/test.qconf.json
- res/TensorFlowLiteRecipes/Quant_Add_001/test.recipe
- res/TensorFlowLiteRecipes/Quant_Add_001/test.rule
- res/TensorFlowLiteRecipes/Quant_Add_002/test.qconf.json
- res/TensorFlowLiteRecipes/Quant_Add_002/test.recipe
- res/TensorFlowLiteRecipes/Quant_Add_002/test.rule
This adds resources to test mixed-precision quantization of ADD.
---
Related to: #9056 
Draft PR: #9057
> [res] Add resource to test mixed-precision of ADD

- docs/conf.py
- packaging/nnfw.spec
- runtime/contrib/android/api/build.gradle
- runtime/onert/api/include/nnfw_version.h
> [onert] update version to 1.21.0

- compiler/vconone/CMakeLists.txt
This will bump version to 1.21.0
> [vconone] Bump to 1.21.0

- compiler/luci/pass/src/FoldDequantizePass.cpp
- compiler/luci/pass/src/FoldDequantizePass.test.cpp
This commit is for supporting more dtype for `FoldDequatizePass`.
---
Parent Issue : #8731
> [luci/pass] Support more dtype for FoldDequantizePass

- compiler/circle-eval-diff/src/ModuleEvalDiff.cpp
This uses different modules for interpretation.
> [circle-eval-diff] Use different modules for interpretation

- compiler/circle-eval-diff/driver/Driver.cpp
- compiler/circle-eval-diff/include/CircleEvalDiff.h
- compiler/circle-eval-diff/src/CircleEvalDiff.cpp
- compiler/circle-eval-diff/src/ModuleEvalDiff.cpp
- compiler/circle-eval-diff/src/ModuleEvalDiff.h
This supports printing multiple metrics at once.
> [circle-eval-diff] Print multiple metrics at once

- compiler/one-cmds/one-build
- compiler/one-cmds/one-codegen
- compiler/one-cmds/one-import-bcq
- compiler/one-cmds/one-import-onnx
- compiler/one-cmds/one-import-tf
- compiler/one-cmds/one-import-tflite
- compiler/one-cmds/one-optimize
- compiler/one-cmds/one-pack
- compiler/one-cmds/one-profile
- compiler/one-cmds/one-quantize
This will tidy unused imports of command tools.
> [one-cmds] Tidy unused imports

- compiler/circle-part-value-test/CMakeLists.txt
This will temporary disable this test.
> [cir-part-val-test] Temporary disable test

- compiler/circle-partitioner-test/CMakeLists.txt
This will temporary disable this test.
> [cir-part-test] Temporary disable test

- compiler/circle-partitioner/src/CirclePartitioner.cpp
This will change positional to optional arguments.
> [circle-partitioner] Change to optional arguments

- compiler/luci/pass/src/ConvertToFakeQuantizedModelPass.cpp
This supports more ops in fake quantization.
> [luci] Support more ops in fake quantization.

- compiler/one-cmds/one-partition
This will introduce one-partition command tool.
> [one-cmds] Introduce one-partition

- compiler/circle-eval-diff/driver/Driver.cpp
- compiler/circle-eval-diff/include/CircleEvalDiff.h
- compiler/circle-eval-diff/src/CircleEvalDiff.cpp
- compiler/circle-eval-diff/src/MetricPrinter.cpp
- compiler/circle-eval-diff/src/MetricPrinter.h
- compiler/circle-eval-diff/src/MetricPrinter.test.cpp
This supports Mean PEIR metric.
> [circle-eval-diff] Support MPEIR metric

- infra/debian/compiler/one-compiler.install
This will revise debian to add one-partition in install.
> [infra] Add one-partition to debian install

- compiler/one-cmds/CMakeLists.txt
- compiler/one-cmds/one-build
- compiler/one-cmds/one-build.template.cfg
- compiler/one-cmds/onecc
- compiler/one-cmds/onecc.template.cfg
This will include one-partition into onecc, one-build and build list.
> [one-cmds] Include one-partition

- compiler/one-cmds/tests/prepare_test_materials.sh
This will add prepare test material for one-partition.
> [one-cmds] Add test material for one-partiton

- compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
This supports MPQ for LeakyRelu Op.
> [luci] Support MPQ for LeakyRelu Op

- compiler/luci/pass/src/ConvertToFakeQuantizedModelPass.cpp
This supports fake quantization of LeakyRelu and Transpose Op.
> [luci] Support fake quantization of LeakyRelu and Transpose

- compiler/circle-eval-diff/driver/Driver.cpp
- compiler/circle-eval-diff/include/CircleEvalDiff.h
- compiler/circle-eval-diff/src/CircleEvalDiff.cpp
- compiler/circle-eval-diff/src/ModuleEvalDiff.cpp
- compiler/circle-eval-diff/src/ModuleEvalDiff.h
This adds a new option to dump output as a file with prefix.
> [circle-eval-diff] Dump output with prefix

- compiler/circle-eval-diff/CMakeLists.txt
- compiler/circle-eval-diff/src/InputDataLoader.cpp
- compiler/circle-eval-diff/src/InputDataLoader.h
- compiler/circle-eval-diff/src/InputDataLoader.test.cpp
This commit introduces file data loader to the module.
Draft: #8830
Related: #8829 
> [circle-eval-diff] Introduce file data loader

- compiler/circle-partitioner/README.md
This will update README.md file to reflect argument changes.
> [circle-partitioner] Update README

- compiler/luci/pass/src/QuantizationUtils.cpp
This recursively finds activation qtype from node's input.
- For the case where activation qtype is determined by input.
---
Draft PR: https://github.com/Samsung/ONE/pull/9118
> [luci] Find activation qtype from node's input.

- compiler/one-cmds/one-partition
This will fix getattr with work_path.
> [one-cmds] Fix one-parititon

- runtime/onert/backend/acl_cl/Backend.h
- runtime/onert/backend/acl_neon/Backend.h
- runtime/onert/backend/cpu/ops/DetectionPostProcessLayer.cc
This commit resolves using moved object which may lead to an unexpected behavior.
> [onert/backend] Fix moved object usage

- compiler/circle-eval-diff/src/MetricPrinter.cpp
- compiler/circle-eval-diff/src/MetricPrinter.h
- compiler/circle-eval-diff/src/MetricPrinter.test.cpp
This introduces Top-K Match Printer.
---
Related to: https://github.com/Samsung/ONE/issues/9124
Draft PR: https://github.com/Samsung/ONE/pull/9141
> [circle-eval-diff] Introduce Top-K Match Printer

- compiler/one-cmds/tests/onecc_025.cfg
- compiler/one-cmds/tests/onecc_025.test
- compiler/one-cmds/tests/onecc_026.cfg
- compiler/one-cmds/tests/onecc_026.test
> [one-cmds] Fix test

- compiler/circle-execution-plan/CMakeLists.txt
- compiler/circle-execution-plan/src/CircleExecutionPlan.cpp
- compiler/circle-execution-plan/src/ExecutionPlanner.cpp
- compiler/circle-execution-plan/src/ExecutionPlanner.h
This pr adds creation of json file with memory allocation info in circle-execution-plan for visualization tool.
issue #9136 
> [circle-execution-plan] Add creation of json file with memory allocation info

- res/TensorFlowLiteRecipes/Quant_Slice_000/test.qconf.json
- res/TensorFlowLiteRecipes/Quant_Slice_000/test.recipe
- res/TensorFlowLiteRecipes/Quant_Slice_000/test.rule
- res/TensorFlowLiteRecipes/Quant_Slice_001/test.qconf.json
- res/TensorFlowLiteRecipes/Quant_Slice_001/test.recipe
- res/TensorFlowLiteRecipes/Quant_Slice_001/test.rule
- res/TensorFlowLiteRecipes/Quant_Softmax_000/test.qconf.json
- res/TensorFlowLiteRecipes/Quant_Softmax_000/test.recipe
- res/TensorFlowLiteRecipes/Quant_Softmax_000/test.rule
- res/TensorFlowLiteRecipes/Quant_Softmax_001/test.qconf.json
- res/TensorFlowLiteRecipes/Quant_Softmax_001/test.recipe
- res/TensorFlowLiteRecipes/Quant_Softmax_001/test.rule
- res/TensorFlowLiteRecipes/Quant_Tanh_000/test.qconf.json
- res/TensorFlowLiteRecipes/Quant_Tanh_000/test.recipe
- res/TensorFlowLiteRecipes/Quant_Tanh_000/test.rule
- res/TensorFlowLiteRecipes/Quant_Tanh_001/test.qconf.json
- res/TensorFlowLiteRecipes/Quant_Tanh_001/test.recipe
- res/TensorFlowLiteRecipes/Quant_Tanh_001/test.rule
- res/TensorFlowLiteRecipes/Quant_TransposeConv_000/test.qconf.json
- res/TensorFlowLiteRecipes/Quant_TransposeConv_000/test.recipe
- res/TensorFlowLiteRecipes/Quant_TransposeConv_000/test.rule
- res/TensorFlowLiteRecipes/Quant_TransposeConv_001/test.qconf.json
- res/TensorFlowLiteRecipes/Quant_TransposeConv_001/test.recipe
- res/TensorFlowLiteRecipes/Quant_TransposeConv_001/test.rule
- res/TensorFlowLiteRecipes/Quant_Transpose_000/test.qconf.json
- res/TensorFlowLiteRecipes/Quant_Transpose_000/test.recipe
- res/TensorFlowLiteRecipes/Quant_Transpose_000/test.rule
- res/TensorFlowLiteRecipes/Quant_Transpose_001/test.qconf.json
- res/TensorFlowLiteRecipes/Quant_Transpose_001/test.recipe
- res/TensorFlowLiteRecipes/Quant_Transpose_001/test.rule
This adds test for MPQ
- Slice, Softmax, Tanh, Transpose, TransposeConv
---
Related to: #9056
Draft PR: #9176
> [res] Add tests for MPQ

- res/TensorFlowLiteRecipes/Quant_AveragePool2D_000/test.qconf.json
- res/TensorFlowLiteRecipes/Quant_AveragePool2D_000/test.recipe
- res/TensorFlowLiteRecipes/Quant_AveragePool2D_000/test.rule
- res/TensorFlowLiteRecipes/Quant_AveragePool2D_001/test.qconf.json
- res/TensorFlowLiteRecipes/Quant_AveragePool2D_001/test.recipe
- res/TensorFlowLiteRecipes/Quant_AveragePool2D_001/test.rule
- res/TensorFlowLiteRecipes/Quant_BatchMatMul_000/test.qconf.json
- res/TensorFlowLiteRecipes/Quant_BatchMatMul_000/test.recipe
- res/TensorFlowLiteRecipes/Quant_BatchMatMul_000/test.rule
- res/TensorFlowLiteRecipes/Quant_BatchMatMul_001/test.qconf.json
- res/TensorFlowLiteRecipes/Quant_BatchMatMul_001/test.recipe
- res/TensorFlowLiteRecipes/Quant_BatchMatMul_001/test.rule
- res/TensorFlowLiteRecipes/Quant_Concatenation_000/test.qconf.json
- res/TensorFlowLiteRecipes/Quant_Concatenation_000/test.recipe
- res/TensorFlowLiteRecipes/Quant_Concatenation_000/test.rule
- res/TensorFlowLiteRecipes/Quant_Concatenation_001/test.qconf.json
- res/TensorFlowLiteRecipes/Quant_Concatenation_001/test.recipe
- res/TensorFlowLiteRecipes/Quant_Concatenation_001/test.rule
- res/TensorFlowLiteRecipes/Quant_Conv_003/test.qconf.json
- res/TensorFlowLiteRecipes/Quant_Conv_003/test.recipe
- res/TensorFlowLiteRecipes/Quant_Conv_003/test.rule
- res/TensorFlowLiteRecipes/Quant_Conv_004/test.qconf.json
- res/TensorFlowLiteRecipes/Quant_Conv_004/test.recipe
- res/TensorFlowLiteRecipes/Quant_Conv_004/test.rule
- res/TensorFlowLiteRecipes/Quant_DepthwiseConv2D_000/test.qconf.json
- res/TensorFlowLiteRecipes/Quant_DepthwiseConv2D_000/test.recipe
- res/TensorFlowLiteRecipes/Quant_DepthwiseConv2D_000/test.rule
- res/TensorFlowLiteRecipes/Quant_DepthwiseConv2D_001/test.qconf.json
- res/TensorFlowLiteRecipes/Quant_DepthwiseConv2D_001/test.recipe
- res/TensorFlowLiteRecipes/Quant_DepthwiseConv2D_001/test.rule
This adds MPQ tests for the below Ops.
- AvgPool2D, BatchMatMul, Concat, Conv2D, DConv2D
---
Related to: #9056
Draft PR: #9176
> [res] Add MPQ tests

- compiler/luci/pass/src/ConvertNCHWToNHWCPass.cpp
- compiler/luci/pass/src/ConvertNCHWToNHWCPass.test.cpp
This improves the way to detect NHWC Ops in ConvertNCHWToNHWCPass
- Intermediate ops do not contain pre-Reshape/Transpose
- Post-Reshape/Transpose should appear at the pattern
---
Related to: https://github.com/Samsung/ONE/issues/9171
> [luci] Improve NHWC Ops detection in ConvertNCHWToNHWCPass

- compiler/vconone/src/version.cpp
This will revise copyright year 2022.
> [vconone] Revise copyright year

- tools/nnpackage_tool/model2nnpkg/model2nnpkg.sh
This commit updates model2nnpkg.sh to package multiple models.
---
Related issue: #9155
> [tools/model2nnpkg] Package multiple model

- compiler/circle-operator/CMakeLists.txt
- compiler/circle-operator/driver/Driver.cpp
- compiler/circle-operator/requires.cmake
- compiler/circle-operator/src/Dump.cpp
- compiler/circle-operator/src/Dump.h
This will introduce circle-operator driver and empty dump run method.
> [circle-operator] Introduce driver

- compiler/crew/CMakeLists.txt
- compiler/crew/src/PConfigIni.cpp
- compiler/crew/src/PConfigIni.test.cpp
- compiler/crew/src/test_read_semicolon.ini
This will fix to read escape with semicolon sequence.
> [crew] Fix to read esc + semicolon

- compiler/circle-operator/README.md
This will introduce README file for circle-operator.
> [circle-operator] Introduce README

- compiler/circle-operator/src/Dump.cpp
This will implement dump operators.
> [circle-operator] Implement dump operators

- infra/scripts/compiler_modules.sh
This will add note of compiler_modules.sh file for better understanding.
> [infra] Note of compiler_modules

- compiler/circle-inspect/requires.cmake
This will add foder as requirement as it is used.
> [circle-inspect] Require foder

- compiler/circle-operator-test/CMakeLists.txt
- compiler/circle-operator-test/README.md
- compiler/circle-operator-test/requires.cmake
- compiler/circle-operator-test/src/circle-operator.test.cpp
This will introduce integration test for circle-operator tool.
> [circle-operator-test] Test for circle-operator

- infra/packaging/preset/20220323
- infra/packaging/preset/20220323_windows
This will include circle-operator tool to packaging list.
> [infra] Include circle-operator to packaging

- compiler/one-cmds/one-quantize
This uses Command to call record-minmax.
> [one-cmds] Tidy one-quantize command

- compiler/one-cmds/onecc.template.cfg
Let's revise onecc.template.cfg with commented options. This template
will be used by `one-init`.
> [one-cmds] Revise onecc.template.cfg with commented options

- nnpackage/schema/circle_schema.fbs
This commit updates circle schema in `nnpackage/schema`. (copy from `res/CircleSchema/0.4`)
We are already using this schema on runtime circle loader.
> [nnpackage] Update schema

- tests/scripts/command/prepare-model
This commit updates prepare-model test command.
- Remove invalid default server name
- Remove out-dated argument
- Update help message
> [onert/test] Update prepare-model

- packaging/nnfw.spec
This commit changes using hard-coded buildrequires devel package to pkgconfig.
> [infra/gbs] Use pkgconfig

- infra/scripts/docker_collect_nnpkg_resources.sh
This will tidy docker_collect_nnpkg_resources.sh with not used anymore modules.
> [infra] Tidy docker_collect_nnpkg_resources

- compiler/luci-interpreter/src/kernels/Shape.test.cpp
This commit adds test extension for Shape kernel in luci-interpreter.
according to https://github.com/Samsung/ONE/pull/9270#issuecomment-1160553839
> [luci-interpreter] Test extension for Shape kernel

- compiler/luci-interpreter/src/kernels/Fill.test.cpp
This commit adds test extension for Fill kernel in luci-interpreter
for https://github.com/Samsung/ONE/pull/9269#issuecomment-1160552597
> [luci-interpreter] Test extension for Fill kernel

- compiler/circle2circle/src/Circle2Circle.cpp
This will introduce add_switch method to simplify option settings.
- fold_add_v2 uses this to prevent unused function error
> [circle2circle] Introduce add_switch

- compiler/circle-eval-diff/src/InputDataLoader.cpp
This commit catches h5 exception. This is for static analysis tool.
> [circle-eval-diff] Catch h5 exception

- compiler/circle2circle/src/Circle2Circle.cpp
This will simplify option settings with add_switch method.
> [circle2circle] Simplify option settings

- compiler/common-artifacts/CMakeLists.txt
This commit update common-artifact to support OS on python's default version is greater than 3.8.
---
Draft: #9245
> [common-artifact] Support on ubuntu 20.04

- runtime/onert/api/src/nnfw_api_internal.cc
It introduces loadModel(path, type) to remove duplicated code and help
to find the main logic easily.
> [onert/api] Introduce loadModel helper

- compiler/circle-operator/README.md
- compiler/circle-operator/driver/Driver.cpp
- compiler/circle-operator/src/Dump.cpp
This will revise to enable both name and code option possible.
> [circle-operator] Enable both name code possible

- compiler/luci/pass/src/ConvertToFakeQuantizedModelPass.cpp
This moves code to preserve alphabetical order.
> [luci] Tidy ConvertToFakeQuantizedModelPass.cpp

- compiler/one-cmds/one-build
- compiler/one-cmds/one-import-bcq
- compiler/one-cmds/one-import-onnx
- compiler/one-cmds/one-import-pytorch
- compiler/one-cmds/one-import-tf
- compiler/one-cmds/one-import-tflite
- compiler/one-cmds/one-infer
- compiler/one-cmds/one-optimize
- compiler/one-cmds/one-partition
- compiler/one-cmds/one-quantize
- compiler/one-cmds/onecc
- compiler/one-cmds/onelib/constant.py
- compiler/one-cmds/onelib/make_cmd.py
- compiler/one-cmds/onnx_legalizer.py
- compiler/one-cmds/utils.py
This commit fixes python files by formatter.
---
for: #9351 
draft: #9352
> [one-cmds] Fix python files by formatter

- compiler/one-cmds/onecc
- compiler/one-cmds/onelib/CfgRunner.py
This commit introduces CfgRunner to one-cmds.
Related: #9360 
> [one-cmds] Introduce CfgRunner

- runtime/onert/frontend/trix/src/trix_loader.cc
- runtime/onert/frontend/trix/src/trix_loader_dummy.cc
- Rename subgraphs to model
- Remove loadSubgraphs()
> [onert] Revisit trix_loader to remove Subgraphs

- runtime/onert/backend/trix/DevContext.h
- runtime/onert/frontend/trix/src/trix_loader.cc
It fixes trix error message to use more general and proper name.
> [onert] Fix trix error message

- compiler/common-artifacts/CMakeLists.txt
This will add temporary fix for protobuf issue that requires old version.
---
Related issue: https://github.com/Samsung/ONE/pull/9382/files#r912667644
> [common-artifacts] Fix for protobuf issue

- infra/nnfw/cmake/CfgOptionFlags.cmake
- infra/nnfw/cmake/options/options_aarch64-android.cmake
- packaging/nnfw.spec
- runtime/service/CMakeLists.txt
- runtime/service/npud/CMakeLists.txt
- runtime/service/npud/core/main.cc
This commit adds an initial commit of npud.
It defines BUILD_NPUD and builds npud code when this option is on.
draft pr: #9267
> [npud] Add npud main

- compiler/one-cmds/CMakeLists.txt
- compiler/one-cmds/onecc
- compiler/one-cmds/onelib/OptionBuilder.py
- compiler/one-cmds/onelib/TopologicalSortHelper.py
- compiler/one-cmds/onelib/WorkflowRunner.py
This commit introduces workflow to one-cmds. You can see the usages in the test of below draft.
Related: #9192 
Draft: #9354 
> [one-cmds] Introduce workflow

- infra/debian/compiler/one-compiler.install
This commit adds workflow related things.
Related: https://github.com/Samsung/ONE/issues/9192
Draft: https://github.com/Samsung/ONE/pull/9354
> [debian] Add workflow things

- compiler/luci/pass/src/ConvertNCHWToNHWCPass.cpp
- compiler/luci/pass/src/ConvertNCHWToNHWCPass.test.cpp
This broadcasts const of MUL in ConvertNCHWToNHWC.
---
Related to: https://github.com/Samsung/ONE/issues/9401
> [luci] Broadcast const of MUL in ConvertNCHWToNHWC

- compiler/luci/pass/src/ConvertNCHWToNHWCPass.cpp
- compiler/luci/pass/src/ConvertNCHWToNHWCPass.test.cpp
This supports Softmax Op in ConvertNCHWToNHWC.
---
Related to: https://github.com/Samsung/ONE/issues/9417
> [luci] Support Softmax Op in ConvertNCHWToNHWC

- compiler/luci/pass/src/ConvertNCHWToNHWCPass.cpp
- compiler/luci/pass/src/ConvertNCHWToNHWCPass.test.cpp
This broadcasts const of ADD in ConvertNCHWToNHWC.
---
Related to: https://github.com/Samsung/ONE/pull/9418#issuecomment-1181335749
> [luci] Broadcast const of ADD in ConvertNCHWToNHWC

- compiler/luci/pass/src/ConvertNCHWToNHWCPass.cpp
- compiler/luci/pass/src/ConvertNCHWToNHWCPass.test.cpp
This supports SplitV in ConvertNCHWToNHWC.
---
Related to: https://github.com/Samsung/ONE/issues/9417
> [luci] Support SplitV in ConvertNCHWToNHWC

- compiler/exo/src/Conversion/DepthwiseConv2DConverter.cpp
> [exo] Make gcc-11 happy

- tools/cross/install_rootfs.sh
This commit updates rootfs script to install more packages.
- cmake
- libglib2.0-dev
> [infra] Update rootfs installation script

- res/TensorFlowLiteRecipes/StridedSlice_004/test.recipe
This will introduce StridedSlice_004 tflie recipe
> [res] Introduce StridedSlice_004 recipe

- compiler/luci/pass/src/QuantizeDequantizeWeightsPass.cpp
This fixes condition to apply QuantizeDequantizeWeights.
> [luci] Fix QuantizeDequantizeWeights condition

- compiler/mir2loco/src/mir2loco.test.cpp
This commit updates Conv2D_Test to use `loco::succs()` to find non-input and non-const node.
This will prevent unexpected result by `unordered_map`.
---
Related issue: #9382
> [mir2loco] Fix Conv2D_Test

- compiler/luci/pass/src/FuseBatchNormWithTConvPass.cpp
This will revise FuseBatchNormWithTConvPass to support fusion when bias exist.
> [luci/pass] Revise FuseBatchNormWithTConvPass

- compiler/one-cmds/one-init
This introduces early version of one-init.
parent issue: #9450
draft: #9421
ONE-vscode-DCO-1.0-Signed-off-by: Hyun Sik Yoon <hyunsik.yoon.1024@gmail.com>
> [one-cmds] Introduce one-init

- compiler/luci-interpreter/src/kernels/Pack.test.cpp
This PR Adds extends tests for Pack kernel with int8, int16, int32, int64 types.
related to #9316 
> [luci-interpreter] Extend tests for Pack kernel

- compiler/luci-micro/CMakeLists.txt
- compiler/luci-micro/standalone/CMakeLists.txt
This PR fixes standalone luci-micro building.
issue: #9468
> [luci-micro] Fix standalone luci-micro building

- runtime/service/npud/core/Server.cc
- runtime/service/npud/core/Server.h
This commit implements Server class to create main event loop.
> [npud] Add Server main loop

- compiler/common-artifacts/CMakeLists.txt
This will revise circle2circle option for optimization tests to include fold_dequantize.
> [common-artifacts] Revise circle2circle option

- runtime/service/npud/core/Server.cc
- runtime/service/npud/core/Server.h
- runtime/service/npud/core/Signal.cc
- runtime/service/npud/core/Signal.h
This commit introduces Signal class for handling sig event.
Related issue: #9304
> [npud] Introduce Signal class

- packaging/nnfw.spec
This commit updates nnfw.spec rpm build script to remove duplicated build on tizen test build.
> [infra/gbs] Build once on tizen test build

- compiler/luci/pass/src/FoldDequantizePass.cpp
- compiler/luci/pass/src/FoldDequantizePass.test.cpp
This enables to fold scalar with Dequantize Op.
> [luci] Fold scalar with Dequantize Op

- res/TensorFlowLiteRecipes/Net_Dequantize_Add_000/test.recipe
This will introduce Net_Dequantize_Add_000 recipe to test fold
dequantize with float16.
> [res] Introduce Net_Dequantize_Add_000

- compiler/luci/pass/src/FoldDequantizePass.test.cpp
This will introduce basic test of FoldDequantizePass with FLOAT16.
> [luci/pass] Test FoldDequantizePass with FLOAT16

- compiler/luci/pass/src/ConvertNCHWToNHWCPass.cpp
- compiler/luci/pass/src/ConvertNCHWToNHWCPass.test.cpp
This supports ReduceMax Op in ConvertNCHWToNHWC.
---
Related to: https://github.com/Samsung/ONE/issues/9459
> [luci] Support ReduceMax in ConvertNCHWToNHWC

- infra/nnfw/cmake/CfgOptionFlags.cmake
- infra/nnfw/cmake/options/options_armv7l-tizen.cmake
- packaging/nnfw.spec
- runtime/service/npud/CMakeLists.txt
- runtime/service/npud/core/Server.cc
- runtime/service/npud/core/Signal.cc
- runtime/service/npud/util/Config.lst
- runtime/service/npud/util/ConfigSource.cc
- runtime/service/npud/util/ConfigSource.h
- runtime/service/npud/util/EnvConfigSource.cc
- runtime/service/npud/util/EnvConfigSource.h
- runtime/service/npud/util/GeneralConfigSource.cc
- runtime/service/npud/util/GeneralConfigSource.h
- runtime/service/npud/util/IConfigSource.h
- runtime/service/npud/util/Logging.h
This commit adds Logging class and related config files.
It turns the log on and off using `NPUD_LOG_ENABLE` environment.
Related issue: #9304
> [npud] Add Logging class and related config files

- compiler/one-cmds/one-quantize
- compiler/one-cmds/tests/one-quantize_015.test
This adds fake quantization option to one-quantize.
> [one-cmds] Add fake quantization option to one-quantize

- compiler/luci/pass/src/ConvertNCHWToNHWCPass.cpp
- compiler/luci/pass/src/ConvertNCHWToNHWCPass.test.cpp
This supports LogSoftmax in ConvertNCHWToNHWC.
> [luci] Support LogSoftmax in ConvertNCHWToNHWC

- compiler/tfldump/src/Dump.cpp
This will revise to show binary data upto 8 items.
> [tfldump] Revise to show upto 8 items

- compiler/luci/import/include/luci/Import/Nodes.h
- compiler/luci/import/include/luci/Import/Nodes/CircleDensify.h
- compiler/luci/import/src/GraphBuilderRegistry.cpp
- compiler/luci/import/src/Nodes/CircleDensify.cpp
This will enable import of Densify operator.
> [luci/import] Enable import Densify

- compiler/souschef/include/souschef/Data/FP16.h
- compiler/souschef/src/Gaussian.cpp
This will extract external FP16 to separate header.
> [souschef] Extract FP16

- compiler/luci/pass/src/FoldDequantizePass.cpp
- compiler/luci/pass/src/helpers/FP16.h
This will extract external FP16 to separate header.
> [luci/pass] Extract FP16

- compiler/luci/export/src/CircleBuiltinTypesExtractor.h
- compiler/luci/export/src/CircleOps.lst
This will enable export of CircleDensify IR.
> [luci/export] Enable Densify

- compiler/tflchef/core/src/Convert.cpp
- compiler/tflchef/core/src/Convert.h
This will introduce FormatConverter to convert sparse vs dense tensors.
> [tflchef] Sparsity format converter

- compiler/tflchef/core/src/ModelChef.cpp
- compiler/tflchef/proto/tflchef.proto
This will enable to make a sparse operand from normal(dense) operand.
> [tflchef] Make sparse from dense operand

- compiler/tflchef/proto/tflchef.proto
This will introduce densify_options for Densify Operator.
> [tflchef] Introduce densify_options

- compiler/tflchef/tests/make_sparse/test.recipe
This will add test for operand make_sparse flag.
> [tflchef] Test for make_sparse

- compiler/luci/pass/include/luci/CircleOptimizer.h
- compiler/luci/pass/include/luci/Pass/FoldDensifyPass.h
- compiler/luci/pass/src/CircleOptimizer.cpp
- compiler/luci/pass/src/FoldDensifyPass.cpp
- compiler/luci/pass/src/FoldDensifyPass.test.cpp
- compiler/luci/pass/src/helpers/SparsityFormatConverter.cpp
- compiler/luci/pass/src/helpers/SparsityFormatConverter.h
This will introduce FoldDensifyPass that will convert spase tensor with
Densify Op to densor tensor.
> [luci/pass] FoldDensifyPass

- compiler/circledump/src/OpPrinter.cpp
This will add comment no option for Densify.
> [circledump] Add comment for Densify

- compiler/circle2circle/src/Circle2Circle.cpp
This will add fold_densify option.
> [circle2circle] Add fold_densify option

- compiler/common-artifacts/CMakeLists.txt
This will add '--fold_densify' option to circle2circle optimization test.
> [common-artifacts] Add fold_densify to optimization

- compiler/luci/service/src/CircleCloneNode.h
- compiler/luci/service/src/Nodes/CircleDensify.cpp
- compiler/luci/service/src/Nodes/CircleDensify.test.cpp
This will enable clone of CircleDensify IR.
> [luci/clone] Densify

- res/TensorFlowLiteRecipes/Densify_000/test.recipe
- res/TensorFlowLiteRecipes/Net_Densify_Add_000/test.recipe
- res/TensorFlowLiteRecipes/Net_Densify_Dequantize_Add_000/test.recipe
This will introduce tflite recipes for testing Densify
and mixed with Dequantize operator.
> [res] tflite recipe for Densify

- compiler/tflchef/tests/make_sparse_f16/test.recipe
This will introduce test recipe of make sparse with float16.
> [tflchef] Test recipe of make sparse float16

- compiler/luci-pass-value-test/CMakeLists.txt
This will enable to test with multiple optimization options.
> [luci-pass-value-test] Enable multiple options

- compiler/one-cmds/how-to-use-one-commands.txt
- compiler/one-cmds/onelib/constant.py
This will introduce fold_densify option for one-optimize.
> [one-cmds] Introduce fold_densify option

- compiler/luci/pass/src/helpers/SparsityFormatConverter.cpp
This will revise to use delete [] to make analysis tool happy.
> [luci/pass] use delete []

- compiler/souschef/CMakeLists.txt
- compiler/souschef/src/Explicit.cpp
- compiler/souschef/src/Gaussian.cpp
This will revise to use fp16 library from source package.
> [souschef] Use fp16 from package

- compiler/luci/pass/CMakeLists.txt
- compiler/luci/pass/src/FoldDequantizePass.cpp
This will revise to use fp16 library from source package.
> [luci/pass] Use fp16 from package

- compiler/luci/pass/src/FuseAddWithTConvPass.cpp
This supports fusion of Add+Relu and TConv.
> [luci] Support fusion of Add+Relu and TConv.

- compiler/onnx-tools/CMakeLists.txt
This will revise to install tools with install step.
> [onnx-tools] Install tools

- compiler/one-cmds/onelib/OptionBuilder.py
This enables to use correct optimization options.
> [one-cmds] Fix OptionBuilder

- compiler/one-cmds/tests/onecc_neg_023.test
- compiler/one-cmds/tests/onecc_neg_023.workflow.json
This commit adds workflow test where it checks if optimize options are applied well.
> [one-cmds] Add workflow test

- compiler/one-cmds/tests/onecc_neg_022.test
This commit fixes onecc_neg_022 test.
> [one-cmds] fix onecc_neg_022 test

- compiler/luci-interpreter/pal/cmsisnn/PALDequantize.h
- compiler/luci-interpreter/pal/cmsisnn/PALQuantize.h
- compiler/luci-interpreter/pal/cmsisnn/PALreference_ops.h
- compiler/luci-interpreter/pal/linux/PALreference_ops.h
- compiler/luci-interpreter/pal/mcu/PALDequantize.h
- compiler/luci-interpreter/pal/mcu/PALQuantize.h
- compiler/luci-interpreter/pal/mcu/PALreference_ops.h
This commit adds reference_ops.h to PAL (with fixes to support builds for cortex mcus).
- fixed errors like `"no matching function for call to 'min(const int&, long int)"`
needed for https://github.com/Samsung/ONE/issues/9468
ONE-DCO-1.0-Signed-off-by: Vyacheslav Bazhenov <v.bazhenov@partner.samsung.com>
> [luci-interpreter] Add reference_ops.h to PAL

- compiler/luci-interpreter/pal/mcu/PALreference_ops.h
This refactors licence in luci-interpreter\pal\mcu\PALreference_ops.h
ONE-DCO-1.0-Signed-off-by: Vyacheslav Bazhenov <v.bazhenov@partner.samsung.com>
> [luci-interpreter] Refactor licence in PALreference_ops.h

- tests/scripts/command/nnpkg-test
This commit updates argument parsing to use verbose option.
> [onert/test] Fix bug nnpkg-test

- runtime/onert/core/include/compiler/Compiler.h
- runtime/onert/core/include/exec/Execution.h
- runtime/onert/core/include/exec/Executors.h
- runtime/onert/core/include/exec/IExecutor.h
- runtime/onert/core/src/backend/builtin/KernelGenerator.cc
- runtime/onert/core/src/backend/builtin/KernelGenerator.h
- runtime/onert/core/src/backend/builtin/kernel/IfLayer.cc
- runtime/onert/core/src/backend/builtin/kernel/IfLayer.h
- runtime/onert/core/src/backend/builtin/kernel/WhileLayer.cc
- runtime/onert/core/src/backend/builtin/kernel/WhileLayer.h
- runtime/onert/core/src/compiler/Compiler.cc
- runtime/onert/core/src/compiler/ExecutorFactory.cc
- runtime/onert/core/src/compiler/ExecutorFactory.h
- runtime/onert/core/src/exec/Execution.cc
- runtime/onert/core/src/exec/Execution.test.cc
- runtime/onert/core/src/exec/ExecutionObservers.h
- runtime/onert/core/src/interp/InterpExecutor.test.cc
- runtime/onert/frontend/nnapi/execution.cc
- runtime/onert/frontend/nnapi/wrapper/ANeuralNetworksCompilation.h
- runtime/onert/frontend/nnapi/wrapper/ANeuralNetworksExecution.h
This commit introduces Executors class.
Executors object includes generated executors and additional information to use executors.
---
Draft: #9616
> [onert] Introduce Executors

- tests/nnfw_api/src/one_op_tests/Conv2D.test.cc
It adds Conv2D_U8_PerChannel to test per-channel quantized conv2d.
Related: #9609 
It is not completed version. I will adjust the values later.
#9609 will be tested by onert unittest.
```
$ Product/x86_64-linux.debug/out/unittest_standalone/nnfw_api_gtest --gtest_filter=*PerChannel
Note: Google Test filter = *PerChannel
[==========] Running 2 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 2 tests from GenModelTest
[ RUN      ] GenModelTest.OneOp_Conv2D_I8_PerChannel
[       OK ] GenModelTest.OneOp_Conv2D_I8_PerChannel (12 ms)
[ RUN      ] GenModelTest.OneOp_Conv2D_U8_PerChannel
nnfw_api_gtest: /home/gyu/z/ONE/runtime/onert/core/include/ir/TypeInfo.h:55: float onert::ir::TypeInfo::scale() …
```
> [onert/test] Add Conv2D per-channel uint8 test case

- tests/nnfw_api/src/one_op_tests/DepthwiseConv2D.test.cc
It adds testcase for dconv uint8 per-channel quantization.
- Parent Issue: #9609 
- It is the 3rd PR { test } of 3 { compute, runtime, testcase } from #9648
> [onert] Add testcase dconv uint8 per-channel

- runtime/onert/backend/trix/DevContext.h
- runtime/onert/backend/trix/ops/BulkLayer.cc
- runtime/onert/backend/trix/ops/BulkLayer.h
Implement Bulk's batch execution. It supports parallel execution with 2
trix cores.
> Bulk layer's batch execution

- infra/debian/compiler/changelog
- infra/debian/runtime/changelog
- update debian changelog of compiler/runtime
> Update debian changelog to 1.21.0

- docs/release/1.21/index.rst
- docs/release/1.21/release-note_1.21.0.md
> Release Note for 1.21.0

- docs/conf.py
- packaging/nnfw.spec
- runtime/contrib/android/api/build.gradle
- runtime/onert/api/include/nnfw_version.h
> Update runtime version to 1.22.0

- compiler/luci/pass/src/ExpandBroadcastConstPass.test.cpp
- compiler/luci/pass/src/FoldDepthwiseConv2DPass.cpp
- compiler/luci/pass/src/FoldDepthwiseConv2DPass.test.cpp
- compiler/luci/pass/src/ResolveCustomOpMaxPoolWithArgmaxPass.cpp
- compiler/luci/pass/src/ResolveCustomOpSplitVPass.cpp
> [luci] Add missing header <limits>

- compiler/luci-interpreter/src/kernels/Tanh.cpp
- compiler/luci-interpreter/src/kernels/TestUtils.h
- compiler/luci-interpreter/src/kernels/TransposeConv.cpp
> [luci-interpreter] Add missing header <limits>

- compiler/luci-micro/CMakeLists.txt
- compiler/luci-micro/luci-interpreter/pal/cmsisnn/PALDequantize.h
- compiler/luci-micro/luci-interpreter/pal/cmsisnn/PALQuantize.h
- compiler/luci-micro/luci-interpreter/pal/cmsisnn/PALreference_ops.h
- compiler/luci-micro/luci-interpreter/pal/mcu/PALDequantize.h
- compiler/luci-micro/luci-interpreter/pal/mcu/PALQuantize.h
- compiler/luci-micro/luci-interpreter/pal/mcu/PALreference_ops.h
This commit copies PAL from luci-interpreter to luci-micro.
ONE-DCO-1.0-Signed-off-by: Vyacheslav Bazhenov <v.bazhenov@partner.samsung.com>
> [luci-micro] Copy PAL from luci-interpreter to luci-micro

- compiler/luci-micro/luci-interpreter/pal/cmsisnn/PALFill.h
- compiler/luci-micro/luci-interpreter/pal/linux/PALFill.h
- compiler/luci-micro/luci-interpreter/pal/mcu/PALFill.h
- compiler/luci-micro/luci-interpreter/src/kernels/Fill.cpp
This commit adds Fill kernel to PAL.
ONE-DCO-1.0-Signed-off-by: Vyacheslav Bazhenov <v.bazhenov@partner.samsung.com>
> [luci-micro] Add Fill kernel to PAL

- compiler/one-cmds/tests/one-import_neg_001.test
- compiler/one-cmds/tests/one-import_neg_003.test
- compiler/one-cmds/tests/one-import_neg_004.test
- compiler/one-cmds/tests/one-import_neg_005.test
- compiler/one-cmds/tests/one-import_neg_006.test
- compiler/one-cmds/tests/one-import_neg_007.test
- compiler/one-cmds/tests/one-import_neg_008.test
- compiler/one-cmds/tests/one-import_neg_010.test
- compiler/one-cmds/tests/onecc_013.cfg
- compiler/one-cmds/tests/onecc_013.test
- compiler/one-cmds/tests/onecc_014.cfg
- compiler/one-cmds/tests/onecc_014.test
This will revise not do remove reused output circle file.
> [one-cmds-test] Do not remove reused circle file

- compiler/one-cmds/tests/one-import_002.test
- compiler/one-cmds/tests/one-quantize_002.test
- compiler/one-cmds/tests/one-quantize_003.test
- compiler/one-cmds/tests/rawdata2hdf5_001.test
This will revise tests to use variables.
> [one-cmds-test] Use variables

- infra/docker/bionic/Dockerfile
- infra/docker/focal/Dockerfile
This installs python dev libraries on CI workers.
---
> [infra] Install Python dev libraries

- compiler/dalgona/CMakeLists.txt
- compiler/dalgona/README.md
- compiler/dalgona/driver/Driver.cpp
- compiler/dalgona/requires.cmake
This adds below files to create dalgona module.
- CMakeLists.txt
- README
- Driver
- requires.cmake
---
> [dalgona] Initialize dalgona module

- compiler/dalgona/CMakeLists.txt
- compiler/dalgona/include/Dalgona.h
- compiler/dalgona/requires.cmake
- compiler/dalgona/src/Dalgona.cpp
This introduces Dalgona class, which invokes luci-interpreter.
---
> [dalgona] Introduce Dalgona class

- infra/command/format
This commit adds onecc-docker directory to code format items.
ONE-DCO-1.0.-Signed-off-by: Jiyoung Yun <jy910.yun@samsung.com>
related comment: https://github.com/Samsung/ONE/pull/9737#issuecomment-1250719414
> [infra] Add onecc-docker directory to code format items

- compiler/dalgona/README.md
This updates required Python version 3.8.
---
Related to: https://github.com/Samsung/ONE/pull/9743#discussion_r974868857
> [dalgona] Update required Python version

- compiler/dalgona/CMakeLists.txt
- compiler/dalgona/include/Dalgona.h
- compiler/dalgona/include/PythonHooks.h
- compiler/dalgona/src/Dalgona.cpp
- compiler/dalgona/src/PythonHooks.cpp
- compiler/dalgona/src/Utils.cpp
- compiler/dalgona/src/Utils.h
This adds python hooks to Dalgona.
---
> [dalgona] Add Python hooks

- compiler/luci/pass/src/ConvertNCHWToNHWCPass.cpp
- compiler/luci/pass/src/ConvertNCHWToNHWCPass.test.cpp
This supports ReduceMin in ConvertNCHWToNHWC.
---
Related to: https://github.com/Samsung/ONE/issues/9718
> [luci] Support ReduceMin in ConvertNCHWToNHWC

- compiler/luci-micro/CMakeLists.txt
- compiler/luci-micro/helpers/GenerateKernelsListHelper.cpp
- compiler/luci-micro/luci-interpreter/include/luci_interpreter/core/CircleMicroReader.h
- compiler/luci-micro/luci-interpreter/include/luci_interpreter/core/CircleMicroReaderHelper.h
- compiler/luci-micro/luci-interpreter/src/CMakeLists.txt
- compiler/luci-micro/luci-interpreter/src/core/CMakeLists.txt
- compiler/luci-micro/luci-interpreter/src/core/CircleMicroReader.cpp
- compiler/luci-micro/luci-interpreter/src/core/CircleMicroReaderHelper.cpp
- compiler/luci-micro/luci-interpreter/src/loader/CMakeLists.txt
- compiler/luci-micro/requires.cmake
- compiler/luci-micro/standalone/CMakeLists.txt
This PR removes mio-circle04 dependency.
issue: https://github.com/Samsung/ONE/issues/9468
> [luci-micro] Remove mio-circle04 dependency

- docs/howto/how-to-build-runtime.md
- docs/howto/how-to-cross-build-runtime-for-aarch64.md
- docs/howto/how-to-cross-build-runtime-for-arm.md
Documents are updated as recently makefile is revisited.
> [docs] Update make command from how to build runtime

- compiler/dalgona/src/PostOperatorHook.h
- compiler/dalgona/src/PreOperatorHook.h
- compiler/dalgona/src/StringUtils.cpp
- compiler/dalgona/src/StringUtils.h
- compiler/dalgona/src/StringUtils.test.cpp
- compiler/dalgona/tests/CMakeLists.txt
- compiler/dalgona/tests/SingleOperatorTest.py
- compiler/dalgona/tests/TestUtil.py
- compiler/dalgona/tests/test.lst
This supports hooks for Conv2D.
---
> [dalgona] Support Conv2D hooks

- tools/nnpackage_tool/nncc-tc-to-nnpkg-tc/README.md
It fixes wrong description in README.
> [tools/nncc-tc-to-nnpkg-tc] Update README

- runtime/onert/core/src/compiler/Compiler.cc
This commit enables lowering subgraphs for multiple model with controlflow. 
Executor generation and execution is not supported yet.
---
Related issue: https://github.com/Samsung/ONE/issues/9713
Draft: https://github.com/Samsung/ONE/pull/9716
> [onert] Lowering multiple model with controlflow

- infra/debian/compiler/one-compiler.install
This commit adds `circle-interpreter`to debian package.
---
for: #9634 
draft: #9635
> [infra] Add `circle-interpreter` to debain package

- compiler/dalgona/src/PostOperatorHook.h
- compiler/dalgona/src/PreOperatorHook.h
- compiler/dalgona/src/Utils.cpp
- compiler/dalgona/src/Utils.h
- compiler/dalgona/tests/SingleOperatorTest.py
This supports more operators.
- DConv, Add, FC, TConv, Instnorm
---
> [dalgona] Support more operators

- compiler/dalgona/CMakeLists.txt
- compiler/dalgona/src/Dalgona.cpp
- compiler/dalgona/src/PostOperatorHook.h
- compiler/dalgona/src/PreOperatorHook.h
This enables strict build mode.
---
Related to: https://github.com/Samsung/ONE/issues/9777#issuecomment-1255826040
> [dalgona] Enable strict build

- compiler/onecc-docker/docker/Dockerfile
This PR is a Dockerfile for Dockerizing onecc
ONE-DCO-1.0.-Signed-off-by: Dongwan Kim <asdf134652@gmail.com>
Co-authored-by: seunghui-lee <hithere1012@naver.com>
Co-authored-by: Junsu Kim <xofkdqkqh@naver.com>
issue: #9712, #9725
draft: #9736 
related_pr : #9772
> [onecc-docker] Dockerfile for onecc-docker

- runtime/onert/backend/trix/BatchThreadPool.cc
- runtime/onert/backend/trix/BatchThreadPool.h
- runtime/onert/backend/trix/Convert.cc
- runtime/onert/backend/trix/Convert.h
- runtime/onert/backend/trix/DevContext.cc
- runtime/onert/backend/trix/DevContext.h
- runtime/onert/backend/trix/ops/BulkLayer.cc
- runtime/onert/backend/trix/ops/BulkLayer.h
For issue #9207
Draft PR #9667
This commit suppors batch-parallel execution of trix models.
- Introduce BatchThreadPool
- Gather things related to device handle in DevContext
- Change ir::Shape::MAX_RANK to ir::Shape::ONERT_MAX_RANK
> [onert] Support batch-parallel execution of trix models

- tools/nnpackage_tool/qnf/qnf.md
- tools/nnpackage_tool/qnf/qnf.py
- tools/nnpackage_tool/qnf/requirements.txt
It introduces a tool named qnf, which is used for quantize and
dequantize using given circle model's input/output qparams.
It is the tools I've written for https://github.com/Samsung/ONE/issues/9609#issuecomment-1229664013.
It is okay not to merge this, I push it here mainly to make the test reproducible by someone (including future me) later.
> [nnpkg_tools/qnf] Introduce qnf

- infra/nnfw/cmake/packages/TensorFlowLite-2.8.0/TensorFlowLite/CMakeLists.txt
This commit revisits TFLite 2.8 build CMake to udate based on updated cmake in official tensorflow's cmake.
---
Draft: #9671
> [infra/runtime] Revisit TFLite 2.8 build

- compiler/onecc-docker/onecc-docker
This PR corrected exception handling and subtool related errors.
ONE-DCO-1.0.-Signed-off-by: Dongwan Kim <asdf134652@gmail.com>
issue: https://github.com/Samsung/ONE/issues/9712
> [onecc-docker] onecc subtool error fix

- compiler/onecc-docker/onecc-docker
This commit update dockerfile_path
ONE-DCO-1.0.-Signed-off-by: Junsu Kim <xofkdqkqh@naver.com>
/cc @Samsung/ootpg_docker
> [onecc-docker] Update dockerfile_path to onecc-docker

- compiler/dalgona/analysis/AnalysisTemplate.py
This adds template for analysis script.
---
Draft PR: https://github.com/Samsung/ONE/pull/3501
> [dalgona] Add template for analysis script

- compiler/one-cmds/one-init
This commit enables one-init to add sections and
input_path and output_path of each section.
---
From #9619
> [one-cmd] Add section, input_path, output_path for one-init

- compiler/onecc-docker/README.md
This commit has a README update.
Add the `requests` library to requirements.
ONE-DCO-1.0.-Signed-off-by: Dongwan Kim <asdf134652@gmail.com>
/cc @Samsung/ootpg_docker
> [onecc-docker]Update README

- runtime/onert/backend/trix/DevContext.cc
This commit adds some comments in DevContext.
> [onert] Add some comments in DevContext

- compiler/dalgona-test/.gitignore
- compiler/dalgona-test/CMakeLists.txt
- compiler/dalgona-test/GenH5RandomInputs.py
- compiler/dalgona-test/RandomDataGenerator.py
- compiler/dalgona-test/SingleOperatorTest.py
- compiler/dalgona-test/TestSingleOp.sh
- compiler/dalgona-test/TestUtil.py
- compiler/dalgona-test/requires.cmake
- compiler/dalgona-test/test.lst
This adds a module to test dalgona.
---
Related to: https://github.com/Samsung/ONE/issues/9710#issuecomment-1263099854
> [dalgona-test] Initialize dalgona test

- compiler/luci-micro/luci-interpreter/src/kernels/Logistic.cpp
- compiler/luci-micro/luci-interpreter/src/kernels/Logistic.h
This PR changes Logistic kernel to reduce memory consumptions.
issue: https://github.com/Samsung/ONE/issues/9468
> [luci-micro] Change Logistic kernel to reduce memory consumptions

- compiler/onecc-docker/onecc-docker
This commit add argparse to onecc-docker to handle with GitHub token
ONE-DCO-1.0.-Signed-off-by: Junsu Kim <xofkdqkqh@naver.com>
Co-authored-by: Dongwan Kim <asdf134652@gmail.com>
Co-authored-by: seunghui-lee <hithere1012@naver.com>
/cc @Samsung/ootpg_docker
> [onecc-docker] Add argparse to onecc-docker

- compiler/dalgona/CMakeLists.txt
- compiler/dalgona/src/Dalgona.cpp
- compiler/dalgona/src/RandomUtils.cpp
- compiler/dalgona/src/RandomUtils.h
- compiler/dalgona/src/RandomUtils.test.cpp
This uses bounded random input.
> [dalgona] Use bounded random input

- runtime/service/npud/CMakeLists.txt
- runtime/service/npud/core/Server.h
- runtime/service/npud/tests/core/Server.test.cc
- runtime/service/npud/tests/core/Signal.test.cc
This commit introduces test framework on npud.
It tests Server and Signal classes.
draft: #9767
> [npud] Introduce test framework

- infra/scripts/docker_build_cross_arm_compiler_debug.sh
This will introduce compiler ARM cross build script using Docker.
> [infra] Introduce compiler ARM cross build script

- infra/onert-micro/CMakeLists.txt
- infra/onert-micro/cmake/ApplyCompileFlags.cmake
- infra/onert-micro/cmake/CfgOptionFlags.cmake
- infra/onert-micro/utils.cmake
This PR introduce utils.cmake file to support common functions.
from draft: #9836
> [infra/onert-micro] Introduce utils.cmake

- runtime/onert/api/src/nnfw_api_internal.cc
- runtime/onert/core/include/exec/Executors.h
- runtime/onert/core/src/exec/Executors.cc
This commit updates Executors to support no branch multimodels execution.
---
Related issue: #9655
Draft: #9809
> [onert] Support no branch multimodels execution

- runtime/onert/core/src/exec/Executors.cc
This commit adds checking that model output is connected to other model. Current multi model execution is not supported yet when model output is not used
---
Related issue: #9655
> [onert] Check model output connection

- tests/tools/nnpackage_run/src/args.cc
- tests/tools/nnpackage_run/src/args.h
- tests/tools/nnpackage_run/src/nnpackage_run.cc
This commit introduces new option: single model file loading.
---
Related issue: #9864
> [onert/nnpackage_run] Introduce single model file loading

- compiler/visq/CMakeLists.txt
- compiler/visq/README.md
- compiler/visq/requires.cmake
- compiler/visq/visq
- compiler/visq/visqlib/DumpFP32FM.py
- compiler/visq/visqlib/DumpFakeQuantFM.py
- compiler/visq/visqlib/Palette.py
- compiler/visq/visqlib/QErrorComputer.py
- compiler/visq/visqlib/Util.py
This introduces visq for visualizing quantization error.
---
Related to: https://github.com/Samsung/ONE/issues/9694
Draft PR: #9868
> [visq] Introduce visq module

- compiler/visq/visqlib/Util.py
This fixes ndigits of pretty_float.
---
Related to: https://github.com/Samsung/ONE/issues/9694
Draft PR: https://github.com/Samsung/ONE/pull/9868
> [visq] Fix pretty_float ndigits

- compiler/visq/README.md
- compiler/visq/visq
- compiler/visq/visqlib/QErrorComputer.py
This adds Mean Squared Error metric.
---
Related to: https://github.com/Samsung/ONE/issues/9694
Draft PR: https://github.com/Samsung/ONE/pull/9868
> [visq] Add MSE metric

- compiler/visq/visq
> [visq] Fix name attr in meta

- res/TensorFlowPythonExamples/.gitignore
- res/TensorFlowPythonExamples/tfpem.py
This will revise TensorFlowPythonExamples to generate to output folder and ignore from git.
> [res] Revise TF examples to output folder

- compiler/dalgona-test/RandomDataGenerator.py
> [dalgona-test] Remove unused variable

- res/TensorFlowLiteRecipes/Net_Transpose_Add_000/test.recipe
This adds a recipe for Net_Transpose_Add.
---
Draft PR: https://github.com/Samsung/ONE/pull/9873
> [res] Add recipe for Net_Transpose_Add

- compiler/luci/pass/include/luci/CircleOptimizer.h
- compiler/luci/pass/include/luci/Pass/ForwardTransposeOpPass.h
- compiler/luci/pass/src/CircleOptimizer.cpp
- compiler/luci/pass/src/ForwardTransposeOpPass.cpp
- compiler/luci/pass/src/ForwardTransposeOpPass.test.cpp
This introduces Forward Transpose Op Pass.
---
Draft PR: #9873
> [luci] Introduce ForwardTransposeOpPass

- res/TensorFlowPythonExamples/tfpem.py
This will remove pbtxt mode option for TensorFlowPythonExamples.
> [res] Remove pbtxt option for TensorFlowPythonExamples

- res/TensorFlowPythonExamples/README.md
This will revise TensorFlowPythonExample README file.
> [res] Update TensorFlowPythonExample README

- res/TensorFlowPythonExamples/tfpem.py
This will revise TensorFlowPythonExamples to save keras and tflite model if possible.
> [res] Save keras and tflite models

- res/TensorFlowPythonExamples/examples/LSTM_unroll/__init__.py
This will revise LSTM_unroll script
- remove unused import
- add refer URL
> [res] Revise LSTM_unroll

- res/TensorFlowPythonExamples/examples/LSTM_batsize/__init__.py
- res/TensorFlowPythonExamples/examples/LSTM_retseq/__init__.py
- res/TensorFlowPythonExamples/examples/RNN_GRUCell_unroll/__init__.py
- res/TensorFlowPythonExamples/examples/RNN_LSTMCell_unroll/__init__.py
- res/TensorFlowPythonExamples/examples/SimpleRNN_unroll/__init__.py
This will introduce more Recurrent TF python examples.
> [res] More Recurrent TF examples

- res/TensorFlowPythonExamples/examples/GRU_unroll/__init__.py
This will introduce GRU_unroll TF python example.
> [res] GRU_unroll TF example

- compiler/luci-interpreter/src/core/KernelParams.h
This will introduce UnidirectionalSequenceLSTMParams.
> [luci-interpreter] Introduce UnidirectionalSequenceLSTMParams

- infra/onert-micro/cmake/options/options_armv8-m-generic.cmake
This PR adds options file for armv8-m architecture.
> [infra/onert-micro] Add armv8-m generic options

- tests/scripts/list/tflite_comparator.aarch64.acl_cl.list
- tests/scripts/list/tflite_comparator.armv7l.acl_cl.list
- tests/tools/tflite_comparator/src/tflite_comparator.cc
This commit allows small diff on quantization test by setting environment variable "TOLERANCE" on tflite_comparator.
> [onert/test] Allow small diff on quantization test

- runtime/onert/core/src/exec/Executors.cc
This commit allows using I/O buffers for all models on multimodel package. 
Intermediate executor output buffer should be used for next model executor.
> [onert] Allow using I/O buffer for all models

- compiler/luci-interpreter/pal/linux/PALUnidirectionalSequenceLSTM.h
- compiler/luci-interpreter/src/kernels/UnidirectionalSequenceLSTM.cpp
- compiler/luci-interpreter/src/kernels/UnidirectionalSequenceLSTM.h
This will implement UnidirectionalSequenceLSTM kernel configure method.
> [luci-interpreter] UnidirectionalSequenceLSTM configure

- compiler/luci-interpreter/src/kernels/UnidirectionalSequenceLSTM.cpp
This will fill implementation of evalFloat() method.
> [luci-interpreter] Implement evalFloat()

- compiler/luci-interpreter/src/kernels/UnidirectionalSequenceLSTM.cpp
This will fill implementation of check_input_tensor_dimensions() method.
> [luci-interpreter] Implement check_input_tensor_dimensions

- compiler/luci-interpreter/src/kernels/UnidirectionalSequenceLSTM.test.cpp
This will add some unit tests for UnidirectionalSequenceLSTM.
> [luci-interpreter] Unit test for UnidirectionalSequenceLSTM

- compiler/luci-interpreter/src/loader/nodes/UnidirectionalSequenceLSTM.cpp
This will enable UnidirectionalSequenceLSTM Op loader.
> [luci-interpreter] Enable UnidirectionalSequenceLSTM loader

- runtime/service/npud/core/Backend.h
- runtime/service/npud/core/ir/DataType.h
- runtime/service/npud/core/ir/Layout.h
This commit introduces NPU Backend interface.
Related issue: #9304
> [npud] Introduce NPU Backend interface

- compiler/common-artifacts/CMakeLists.txt
This will add notes about find_package python with platform versions.
> [cmn-arts] Note for python find_package

- infra/docker/jammy/Dockerfile
This commit introduces ubuntu 22.04 developer environment dockerfile. It will be used for CI infra environment setting.
> [infra] Introduce ubuntu 22.04 dev dockerfile

- compiler/circle-execution-plan/CMakeLists.txt
- compiler/circle-execution-plan/pal/TargetPlatform.h
- compiler/circle-execution-plan/src/CircleExecutionPlan.cpp
- compiler/circle-execution-plan/src/ExecutionPlanner.cpp
- compiler/circle-execution-plan/src/ExecutionPlanner.h
This PR adds support for onert-micro in circle-execution-plan.
for issue: https://github.com/Samsung/ONE/issues/9849
draft: https://github.com/Samsung/ONE/pull/9893
> [circle-execution-plan] Support execution plan for onert-micro

- compiler/visq/test/testQErrorComputer.py
This adds unittest for QErrorComputer.
> [visq] Add unittest for QErrorComputer

- compiler/visq/visqlib/QErrorComputer.py
This extracts code in QErrorComputer.py
> [visq] Extract code in QErrorComputer.py

- compiler/visq/test/testQErrorComputer.py
This adds tests for different fp32/fq data.
> [visq] Add tests for different fp32/fq data

- compiler/one-cmds/one-prepare-venv.u2204
This will introduce one-prepare-venv for Ubuntu22.04.
> [one-cmds] one-prepare-venv for Ubuntu22.04

- compiler/dalgona/src/PostOperatorHook.h
- compiler/dalgona/src/PreOperatorHook.h
This adds fused act to InstanceNorm hooks.
> [dalgona] Add fused act to InstanceNorm hooks

- runtime/service/npud/core/Core.cc
- runtime/service/npud/core/Core.h
- runtime/service/npud/core/DBus.cc
- runtime/service/npud/core/Server.cc
- runtime/service/npud/core/Server.h
This commit adds Core class.
DBus method requests to the core and the core returns the request execution result.
> [npud] Add Core Class

- runtime/service/npud/backend/CMakeLists.txt
- runtime/service/npud/backend/trix/CMakeLists.txt
- runtime/service/npud/backend/trix/TrixBackend.cc
- runtime/service/npud/backend/trix/TrixBackend.h
This commit implements trix backend.
> [npud] Add trix backend

- docs/howto/how-to-contribute.md
add ONE-DCO wiki page link to contribution guide
> [docs] Update how-to-contribute.md

- runtime/service/npud/core/Core.cc
- runtime/service/npud/core/DevManager.cc
- runtime/service/npud/core/DevManager.h
- runtime/service/npud/core/util/Config.lst
This commit adds DevManager class.
This class uses DEVICE_MODUEL_PATH env. to look for backend library.
Based on: #9990
> [npud] Add DevManager class

- compiler/luci/service/src/CircleShapeInferenceRule.cpp
This will tidy unused code in infer_fully_connected method.
> [luci/svc] Tidy unused code

- runtime/service/npud/backend/trix/TrixBackend.cc
- runtime/service/npud/backend/trix/TrixBackend.h
- runtime/service/npud/core/Backend.h
This commit updates the parameter name to follow the CamelCase style.
> [npud] Use CamelCase parameter name in Backend header file

- compiler/luci-interpreter/src/kernels/UnidirectionalSequenceLSTM.test.cpp
This will add more UnidirectionalSequenceLSTM unit tests
- batch major (false time_major)
- 1x1x1 input test for debugging
> [luci-interpreter] More UnidirectionalSequenceLSTM tests

- compiler/luci/import/src/Nodes/CircleBidirectionalSequenceLSTM.cpp
This will add some spaces between inputs for better readability.
> [luci/import] Add some spaces

- compiler/luci/logex/src/CircleNodeSummaryBuilders.cpp
This will add to_str() method for float and int32_t to fix calling wrong bool type.
> [luci/logex] Add float/int to_str

- res/TensorFlowLiteRecipes/UnidirectionalSequenceLSTM_003/test.recipe
- res/TensorFlowLiteRecipes/UnidirectionalSequenceLSTM_003/test.rule
- res/TensorFlowLiteRecipes/UnidirectionalSequenceLSTM_004/test.recipe
- res/TensorFlowLiteRecipes/UnidirectionalSequenceLSTM_004/test.rule
This will introduce more UnidirectionalSequenceLSTM recipes for testing unrolling pass.
> [res] UnidirSeqLSTM recipes for unroll pass

- compiler/dalgona/CMakeLists.txt
This will add notes about find_package python with platform versions.
> [dalgona] Note for python find_package

- compiler/luci/pass/include/luci/Pass/UnrollUnidirectionalSequenceLSTMPass.h
- compiler/luci/pass/src/UnrollUnidirectionalSequenceLSTMPass.cpp
- compiler/luci/pass/src/UnrollUnidirectionalSequenceLSTMPass.test.cpp
This will introduce empty UnrollUnidirectionalSequenceLSTMPass with comment explaing what it does.
> [luci/pass] Introduce UnrollUnidirectionalSequenceLSTMPass

- res/TensorFlowLiteRecipes/Net_Duplicate_Weights_000/test.recipe
- res/TensorFlowLiteRecipes/Net_Duplicate_Weights_000/test.rule
This PR adds test for RemoveDuplicateConstPass.
draft: https://github.com/Samsung/ONE/pull/10008
for issue: https://github.com/Samsung/ONE/issues/10009
> [res] Add test for RemoveDuplicateConstPass

- compiler/luci/pass/src/UnrollUnidirectionalSequenceLSTMPass.cpp
This will introduce UnrollLSTM structure for items used for transformation and some initial condition checks for CircleUnidirectionalSequenceLSTM node.
> [luci/pass] Introduce check and UnrollLSTM struct

- compiler/luci/pass/src/UnrollUnidirectionalSequenceLSTMPass.cpp
This will add first Transpose when timesteps is larger than 1.
> [luci/pass] UnrollLSTM first Transpose

- runtime/service/npud/core/ContextManager.cc
- runtime/service/npud/core/ContextManager.h
- runtime/service/npud/core/Core.cc
- runtime/service/npud/core/Core.h
This commit adds ContextManager to manange Context in npu daemon. It is used by Core class.
Draft PR: https://github.com/Samsung/ONE/pull/9989
> [npud] Add ContextManager class

- compiler/luci/pass/src/UnrollUnidirectionalSequenceLSTMPass.cpp
This will add first unpack with count of timesteps.
> [luci/pass] UnrollLSTM unpack

- compiler/luci/pass/src/UnrollUnidirectionalSequenceLSTMPass.cpp
This will add first MatMul(FullyConnected) with merged weights of LSTM.
> [luci/pass] UnrollLSTM MatMul

- runtime/service/npud/core/DBus.cc
This commit initializes local variables.
Resolves #10060
> [npud] Initialize local variable

- runtime/service/npud/core/DevManager.cc
- runtime/service/npud/core/DevManager.h
This commit invokes register and unregister function in Backend library.
> [npud] Implement register and unregister model in DevManager

- compiler/luci/pass/src/UnrollUnidirectionalSequenceLSTMPass.cpp
This will add Split after Matmul(FullyConnected).
> [luci/pass] UnrollLSTM add Matmul Split

- compiler/luci/pass/src/UnrollUnidirectionalSequenceLSTMPass.cpp
This will add first cell subgraph and produce Mul output.
> [luci/pass] UnrollLSTM first cell

- compiler/luci/pass/src/UnrollUnidirectionalSequenceLSTMPass.cpp
This will adding loop of cell subgraph with timesteps.
> [luci/pass] UnrollLSTM loop timesteps

- compiler/luci/pass/src/UnrollUnidirectionalSequenceLSTMPass.cpp
This will add assert for lstm object.
> [luci/pass] assert for unroll_lstm

- compiler/luci/pass/src/UnrollUnidirectionalSequenceLSTMPass.cpp
This will add ending reshape or transpose.
> [luci/pass] UnrollLSTM ending reshape/transpose

- compiler/luci/pass/src/UnrollUnidirectionalSequenceLSTMPass.test.cpp
This will add unit test for UnrollUnidirectionalSequenceLSTMPass.
> [luci/pass] Unit test for UnrollLSTM pass

- compiler/one-cmds/onelib/constant.py
- compiler/one-cmds/tests/one-optimize_003.test
This will add unroll_unidirseqlstm option for one-optimizer and the test.
> [one-cmds] Add unroll_unidirseqlstm option and test

- runtime/service/npud/backend/trix/TrixBackend.cc
This commit removes unnecessary line and bracket.
related comments: https://github.com/Samsung/ONE/pull/10063#discussion_r1027592668, https://github.com/Samsung/ONE/pull/10063#discussion_r1027593087
> [npud] Remove unnecessary codes in Trix backend

- compiler/luci/pass/include/luci/CircleOptimizer.h
- compiler/luci/pass/include/luci/Pass/FoldFullyConnectedPass.h
- compiler/luci/pass/src/CircleOptimizer.cpp
- compiler/luci/pass/src/FoldFullyConnectedPass.cpp
- compiler/luci/pass/src/FoldFullyConnectedPass.test.cpp
This adds FoldFullyConnectedPass to luci/pass.
---
Related to: https://github.com/Samsung/ONE/issues/10066
Draft PR: https://github.com/Samsung/ONE/pull/10081
> [luci] Add FoldFullyConnectedPass

- runtime/service/npud/CMakeLists.txt
- runtime/service/npud/backend/trix/TrixBackend.cc
This commit adds backend directory in cmake file.
> [npud] Add backend directory in cmake file

- runtime/service/npud/backend/trix/TrixBackend.cc
This commit creates and destroys Request using the given NpuContext.
> [npud] Create and destroy Request in Trix backend

- runtime/service/npud/backend/trix/TrixBackend.cc
This commit resolve build failure by struct new operation.
---
Related issue: #10100 #10101
> [npud] Fix build fail TrixBackend.cc

- compiler/circle2circle/src/Circle2Circle.cpp
This adds a fold_fully_connected option.
---
Related to: https://github.com/Samsung/ONE/issues/10066
Draft PR: https://github.com/Samsung/ONE/pull/10081
> [circle2circle] Add fold_fully_connected option

- compiler/one-cmds/onelib/constant.py
This adds a fold_fully_connected option.
---
Related to: https://github.com/Samsung/ONE/issues/10066
Draft PR: https://github.com/Samsung/ONE/pull/10081
> [one-cmds] Add fold_fully_connected option

- compiler/luci/pass/src/QuantizationUtils.cpp
This updates minimum scale of int16 quantization.
> [luci] Update minimum scale of int16 quantization

- runtime/service/npud/core/DevManager.cc
- runtime/service/npud/core/DevManager.h
This commit invokes create and destroy function in Backend library.
Draft pr: #9989
> [npud] Implement create and destroy request in DevManager

- res/TensorFlowLiteRecipes/Net_FullyConnected_Add_000/test.recipe
This adds TFLite recipe for fold_fully_connected.
---
Related to: https://github.com/Samsung/ONE/issues/10066#issuecomment-1324644518
> [res] Add TFLite recipe for fold_fully_connected

- compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
This pr tidies QuantizeWithMinMaxPass.cpp file.
- Rephrase comments
- Remove unused header
> [luci] Tidy QuantizeWithMinMaxPass.cpp

- compiler/luci-compute/CMakeLists.txt
- compiler/luci-compute/README.md
This will introduce luci-compute for computation kernels.
> [luci-compute] Introduce luci-compute

- infra/packaging/preset/20221125
- infra/packaging/preset/20221125_windows
- infra/packaging/res/tf2nnpkg.20221125
This will introduce new preset 20221125.
> [infra] Preset 20221125

- tests/tools/onert_run/src/allocation.h
- tests/tools/onert_run/src/args.cc
- tests/tools/onert_run/src/args.h
- tests/tools/onert_run/src/formatter.h
- tests/tools/onert_run/src/h5formatter.cc
- tests/tools/onert_run/src/h5formatter.h
- tests/tools/onert_run/src/nnfw_util.cc
- tests/tools/onert_run/src/nnfw_util.h
- tests/tools/onert_run/src/onert_run.cc
- tests/tools/onert_run/src/randomgen.cc
- tests/tools/onert_run/src/randomgen.h
- tests/tools/onert_run/src/rawformatter.cc
- tests/tools/onert_run/src/rawformatter.h
- tests/tools/onert_run/src/types.h
This commit updates header guard and namespace.
---
Draft: #10092
> [onert/test] Update name in onert_run source

- infra/packaging/build
This will revise default preset to 20221125.
> [infra] Revise default preset

- infra/packaging/preset/20221125_windows
This will fix typo in 20221125_windows preset.
> [infra] Fix 20221125_windows typo

- onert-micro/CMakeLists.txt
This PR adds option to choose pal (kernels) from command line.
> [onert-micro] Add option to choose pal

- onert-micro/CMakeLists.txt
This PR fixes CMAKE_TOOLCHAIN_FILE variable.
> [onert-micro] Fix CMAKE_TOOLCHAIN_FILE variable

- compiler/luci/pass/src/ReplaceNonConstFCWithBatchMatMulPass.cpp
This will revise ReplaceNonConstFCWithBatchMatMulPass for bias
- bias can be empty with CircleOutputExclude type
- only check dtype when type is CircleConst
> [luci/pass] Revise bias for ReplaceNonConstFCWithBatchMatMulPass

- tests/scripts/models/run_test.sh
This commit updates curl option for md5sum check to use same with download.
> [onert/test] Update md5 check curl option

- compiler/circle2circle-dredd-recipe-test/README.md
This will revise README file for text be inside 100 columns.
> [cir2cir-dredd-recipe-test] Revise README
