- infra/cmake/packages/ProtobufConfig.cmake
This will revise to use variable for protoc path.
> [infra] Use variable for protoc path

- infra/cmake/modules/ExternalSourceTools.cmake
This will introduce PATCH argument in ExternalSource_Download to apply
patch for download module.
> [infra] Introduce PATCH in ExternalSource_Download

- infra/cmake/packages/GTestConfig.cmake
This will add CMake status message when GTestSource was not found.
> [infra] GTest skip message when source not found

- compiler/luci/pass/include/luci/Pass/QuantizeDequantizeWeightsPass.h
- compiler/luci/pass/src/CircleQuantizer.cpp
- compiler/luci/pass/src/QuantizeDequantizeWeightsPass.cpp
- compiler/luci/pass/src/QuantizeDequantizeWeightsPass.test.cpp
This introduces Context struct to QuantizedDequantizeWeights.
---
Draft PR: https://github.com/Samsung/ONE/pull/8460
> [luci] Introduce Context to QuantizeDequantizeWeights

- res/TensorFlowLiteRecipes/FullyConnected_006/test.recipe
This commit adds `FullyConnected_006`, which includes
recipe of `FullyConnected` with `keep_num_dims`.
---
Parent Issue : #8400 
Draft : #8401
> [res] Add FullyConnected recipe with keep_num_dims

- compiler/one-cmds/one-prepare-venv
This will revise one-prepare-venv to split onnx and onnx-tf install
in separate command.
> [one-cmds] Revise one-prepare-venv to split onnx install

- compiler/luci/logex/CMakeLists.txt
- compiler/luci/logex/src/CircleNodeSummaryBuilder.cpp
- compiler/luci/logex/src/CircleNodeSummaryBuilder.test.cpp
- compiler/luci/logex/src/CircleNodeSummaryBuilders.cpp
- compiler/luci/logex/src/CircleNodeSummaryBuilders.h
- compiler/luci/logex/src/FormattedGraph.cpp
This commit replaces `SummaryBuilderLet::ABC` with `CircleNodeSummaryBuilders`.
---
Parent Issue : #8357 
Draft : #8358
> [luci/logex] Replace SummaryBuilderLet::ABC

- infra/cmake/modules/ExternalBuildTools.cmake
This will provide CMAKE_TOOLCHAIN_FILE for external CMake projects if defined.
> [infra] Provide CMAKE_TOOLCHAIN_FILE for external

- compiler/luci/pass/src/QuantizeDequantizeWeightsPass.cpp
- compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
This removes unnecessary return value of visitors
- QuantizeDequantizeWeights
- QuantizeActivation
- QuantizeWeights
- QuantizeBias
---
Related to: https://github.com/Samsung/ONE/pull/8474#discussion_r811485934
> [luci] Remove unnecessary return value of visitors

- compiler/circlechef/tests/CMakeLists.txt
This will enable override of circlechef tools with BUILD_HOST_EXEC
environment variable for cross compilation.
> [circlechef] Enable override of circlechef tools

- compiler/luci/tests/CMakeLists.txt
This will enable override tools to generate test models with
BUILD_HOST_EXEC environment variable for cross compilation.
> [luci/tests] Enable override of tools used

- compiler/tflchef/tests/CMakeLists.txt
This will enable override of tflchef tools with BUILD_HOST_EXEC
environment variable for cross compilation.
> [tflchef] Enable override of tflchef tools

- infra/nncc/CMakeLists.txt
This will introduce CMake macro nnas_find_package_folder() that will
find package in infra/cmake and also provided folder.
> [infra] Introduce macro nnas_find_package_folder

- compiler/luci/pass/include/luci/Pass/PropagateQParamForwardPass.h
- compiler/luci/pass/src/CircleQuantizer.cpp
- compiler/luci/pass/src/PropagateQParamForwardPass.cpp
- compiler/luci/pass/src/PropagateQParamForwardPass.test.cpp
- compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
This adds direction of propagation (Forward) to pass name.
> [luci] Rename Propagate QParam Pass

- compiler/souschef/CMakeLists.txt
This will close missing parenthesis in CMakeLists.txt message.
> [souschef] Close parenthesis in CMake

- compiler/common-artifacts/CMakeLists.txt
This will remove prepare of python venv of TF 2.3.0 as it's not used anymore.
> [common-artifacts] Remove prepare of venv of TF2.3.0

- compiler/luci/pass/include/luci/Pass/PropagateQParamBackwardPass.h
- compiler/luci/pass/src/PropagateQParamBackwardPass.cpp
- compiler/luci/pass/src/PropagateQParamBackwardPass.test.cpp
- compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
This introduces a pass to propagate qparam backward.
---
Related to: https://github.com/Samsung/ONE/issues/8497
Draft PR: #8500
> [luci] Introduce PropagateQParamBackward Pass

- infra/cmake/packages/GTestConfig.cmake
This will revise GTestConfig to manually set GTEST variables to
external build and run find_package only when external build fails.
> [infra] Revise GTestConfig with external build

- compiler/luci/pass/src/PropagateQParamBackwardPass.cpp
- compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
This moves propagate_concat_quantparam to PropagateQParamBackwardPass.
---
Related to: https://github.com/Samsung/ONE/issues/8497
Draft PR: https://github.com/Samsung/ONE/pull/8500
> [luci] Move propagation of concat qparam code

- compiler/circle-quantizer/CMakeLists.txt
- compiler/circle-quantizer/src/CircleQuantizer.cpp
This adds an option for quantization configuration file.
---
Draft PR: https://github.com/Samsung/ONE/pull/8460
> [circle-quantizer] Add --config option

- compiler/one-cmds/one-prepare-venv
This will revise to override TensorFlow package source with environment
variable EXT_TENSORFLOW_WHL.
> [one-cmds] Overide TensorFlow package source

- compiler/luci/pass/src/PropagateQParamBackwardPass.cpp
- compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
This moves backward propagation of qparam codes for PadV2, Pack, OneHot.
---
Related to: https://github.com/Samsung/ONE/issues/8497
Draft PR: https://github.com/Samsung/ONE/pull/8500
> [luci] Move backward propagation of qparam codes

- compiler/one-cmds/tests/onnx_legalize_run_compare.py
- compiler/one-cmds/tests/print_onnx_model.py
This PR adds onnx_legalize_run_compare.py and
print_onnx_model.py to test onnx_lagalizer correctness.
Related issue #8395
> [one-cmds] Add helper scripts for onnx_legalizer.py testing

- compiler/luci/pass/src/PropagateConcatenationQparam.test.cpp
- compiler/luci/pass/src/PropagateQParamBackwardPass.cpp
- compiler/luci/pass/src/PropagateQParamBackwardPass.test.cpp
This allows back propagation of qparam across the same operators.
> [luci] Allow backprop of qparam across the same operators

- compiler/luci/tests/CMakeLists.txt
This will add a note for tests CMake target as a reminder for cross build.
> [luci] Note for tests CMake target

- infra/cmake/packages/FlatBuffers-1.10/FlatBuffersConfig.cmake
- infra/cmake/packages/FlatBuffers-1.12/FlatBuffersConfig.cmake
This will revise FlatBuffersConfig for cross build as host build flatc
is needed for cross build.
> [infra] Revise FlatBuffersConfig for cross build

- compiler/luci-value-test/luci_eval_verifier.py
This will revise luci_eval_verfifier.py script to save input and output
dtypes and input shape that is needed for cross build value test.
> [luci/value-test] Save shape/dtype for input/outputs

- compiler/mio-circle/CMakeLists.txt
This will add skip message in CMakeLists when FlatBuffers is not found.
> [mio-circle] Skip message for flatbuffers not found

- compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
This removes duplicate codes in QuantizeBias.
---
Related to: https://github.com/Samsung/ONE/pull/8540#discussion_r817402140
> [luci] Remove duplicate codes in QuantizeBias

- compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
This adds min/max values when Quantize Op is created.
---
> [luci] Add min/max to new Quantize Op.

- compiler/common-artifacts/exclude.lst
This enables artifacts with Dequantize Op.
---
Related to: https://github.com/Samsung/ONE/issues/8525
> [common-artifacts] Enable artifacts with Dequantize Op

- infra/nncc/cmake/buildtool/config/config_armv7l-linux.cmake
This will temporary disable using NEON for ARM32 cross build.
> [infra] Temporary disable using NEON

- infra/nncc/CMakeLists.txt
- infra/nncc/cmake/ApplyCompileFlags.cmake
This will revise CMakeLists to include compilation flags depending on target platform.
> [infra] Revise to include compile flags

- compiler/luci/pass/src/QuantizedModelVerifier.cpp
- compiler/luci/pass/src/QuantizedModelVerifier.h
This passes layer info to QuantizedModelVerifier.
---
> [luci] Pass layer info to QuantizedModelVerifier

- compiler/luci/pass/include/luci/CircleOptimizer.h
- compiler/luci/pass/include/luci/Pass/RemoveRedundantQuantizePass.h
- compiler/luci/pass/src/CircleOptimizer.cpp
- compiler/luci/pass/src/RemoveRedundantQuantizePass.cpp
- compiler/luci/pass/src/RemoveRedundantQuantizePass.test.cpp
This commit adds new pass for removing redundant quantize operations in luci.
for issue: https://github.com/Samsung/ONE/issues/8526
first step of #8530
> [luci] Add RemoveRedundantQuantizePass

- infra/nncc/Makefile.arm32
This will introduce a Makefile for ARM32 cross build of some compiler modules.
> [infra] Makefile for ARM32 build of compiler

- docs/howto/how-to-build-compiler.md
This will update how-to-build-compiler with ARM32 cross build.
> [docs] Update how-to-build-compiler for ARM32

- compiler/circle2circle/src/Circle2Circle.cpp
This commit adds support of RemoveRedundantQuantizePass in circle2circle.
for issue: https://github.com/Samsung/ONE/issues/8526
second step of https://github.com/Samsung/ONE/pull/8530
> [circle2circle] Support RemoveRedundantQuantizePass in circle2circle

- compiler/luci/logex/src/CircleNodeSummaryBuilder.cpp
- compiler/luci/logex/src/CircleNodeSummaryBuilders.cpp
- compiler/luci/logex/src/CircleNodeSummaryBuilders.h
- compiler/luci/logex/src/FormattedGraph.cpp
This commit replaces `SummaryBuilderLet::WXYZ` with `CircleNodeSummaryBuilders`.
---
Parent Issue : #8357 
Draft : #8358
> [luci/logex] Replace SummaryBuilderLet::WXYZ

- compiler/luci/logex/CMakeLists.txt
This commit adds missing `ENABLE_TEST` checking logic to `CMakeLists.txt`.
---
Parent Issue : #8357 
Draft : #8358
> [luci/logex] Add missing ENABLE_TEST condition to CMakeLists.txt

- infra/nncc/Makefile.arm32
This will fix ARM32 Makefile build items of modules.
> [infra] Fix ARM32 build items of modules

- compiler/luci/import/src/CircleReader.cpp
This commit adds `nullptr` checking for `tensor->name()`.
> [luci/import] Add nullptr checking for tensor name

- res/TensorFlowLiteRecipes/Sqrt_000/test.recipe
This will revise Sqrt_000 recipe to have input as input not constant.
> [res] Revise Sqrt_000 recipe

- compiler/luci-interpreter/pal/cmsisnn/PALSVDF.h
- compiler/luci-interpreter/pal/linux/PALSVDF.h
- compiler/luci-interpreter/pal/mcu/PALSVDF.h
- compiler/luci-interpreter/src/kernels/SVDF.cpp
This commit fixes scale_1_b and scale_2_b types in SVDF kernel: int32_t to int.
> [luci-interpreter] Fix scale_1_b and scale_2_b types in SVDF kernel

- compiler/luci-interpreter/src/kernels/Quantize.cpp
This commit fixes shift type in Quantize kernel: int32_t to int.
> [luci-interpreter] Fix shift type in Quantize kernel

- compiler/common-artifacts/src/TestDataGenerator.cpp
This commit supports int16 data type.
Related: https://github.com/Samsung/ONE/pull/8573#issuecomment-1059150836
> [common-artifacts] Support int16 type

- compiler/luci/pass/src/PropagateConcatenationQparam.test.cpp
- compiler/luci/pass/src/PropagateQParamBackwardPass.cpp
- compiler/luci/pass/src/QuantizationUtils.h
This removes redundant argument from PropagateQParamBackward.
> [luci] Remove redundant argument from PropagateQParamBackward

- compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
- compiler/luci/pass/src/QuantizedModelVerifier.test.cpp
This adds test for quantization with layer info.
---
Related to: https://github.com/Samsung/ONE/pull/8558#issuecomment-1057792092
> [luci] Add test for quantization with layer info

- infra/nnfw/cmake/options/options_aarch64-tizen.cmake
- infra/nnfw/cmake/options/options_armv7hl-tizen.cmake
- infra/nnfw/cmake/options/options_armv7l-tizen.cmake
- infra/nnfw/cmake/options/options_i686-tizen.cmake
- infra/nnfw/cmake/options/options_x86_64-tizen.cmake
This commit disables downloading googletest source code on tizen gbs build.
---
Draft: https://github.com/Samsung/ONE/pull/8572
Related issue: https://github.com/Samsung/ONE/issues/8567
> [infra] Disable downloading googletest source code

- infra/nnfw/cmake/packages/CpuInfoConfig.cmake
- infra/nnfw/cmake/packages/GTestConfig.cmake
This commit removes tizen gbs build error by add_extdirectory macro and warning message.
> [infra] Fix gbs build error and warning

- res/TensorFlowLiteRecipes/Quantize_001/test.recipe
This commit adds network with redundant quantize operation to recipes.
for issue: #8526
> [recipe] Add network with redundant quantize

- infra/cmake/modules/ExternalBuildTools.cmake
This commit removes BUILD_STAMP to simplify external library build fix.
---
Related issue:  #8598
> [infra] Remove BUILD_STAMP

- compiler/one-cmds/how-to-use-one-commands.txt
- compiler/one-cmds/onelib/constant.py
This commit adds Remove redundant Quantize op optimization option.
for issue https://github.com/Samsung/ONE/issues/8526
> [one-cmds] Add Remove redundant Quantize op optimization option

- packaging/nnfw.spec
This commit updates nnfw.spec to use gtest-devel package on tizen gbs build.
---
Draft: #8572
> [infra] Use gtest package for gbs build

- compiler/circle-inspect/README.md
- compiler/circle-inspect/driver/Driver.cpp
- compiler/circle-inspect/src/Dump.cpp
- compiler/circle-inspect/src/Dump.h
- compiler/circle-inspect/src/Reader.cpp
- compiler/circle-inspect/src/Reader.h
This adds option to dump dtype of tensors.
---
Related to: https://github.com/Samsung/ONE/issues/8597
Draft PR: #8602
> [circle-inspect] Dump dtype of tensors

- compiler/dredd-rule-lib/rule-lib.sh
This adds rule to check tensor dtype.
---
Related to: https://github.com/Samsung/ONE/issues/8597
Draft PR: https://github.com/Samsung/ONE/pull/8602
> [dredd-rule-lib] Add rule to check tensor dtype

- compiler/luci/pass/include/luci/Pass/QuantizeWithMinMaxPass.h
- compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
- compiler/luci/pass/src/QuantizedModelVerifier.cpp
- compiler/luci/pass/src/QuantizedModelVerifier.h
- compiler/luci/pass/src/helpers/LayerInfoMap.cpp
- compiler/luci/pass/src/helpers/LayerInfoMap.h
- compiler/luci/pass/src/helpers/LayerInfoMap.test.cpp
This extracts code for layer info map to reduce duplication.
> [luci] Extract layer info map code

- compiler/luci/pass/include/luci/Pass/QuantizePreCheckerPass.h
- compiler/luci/pass/src/CircleQuantizer.cpp
- compiler/luci/pass/src/QuantizePreCheckerPass.cpp
This commit adds QuantizationPreCheckerPass for input model check before quantization.
for issue #8580 
> [quantizer] Introduce input model checker

- compiler/circle-quantizer-dredd-recipe-test/test.lst
This adds tests for mixed-precision quantization.
- Quant_Conv_Mul_Add_001
- Quant_Conv_Mul_Add_002
---
Related to: #8618
> [circle-quantizer-dredd-recipe-test] Add quant tests

- compiler/luci/pass/src/PropagateQParamForwardPass.cpp
- compiler/luci/pass/src/PropagateQParamForwardPass.test.cpp
This propagates qparam of Quantize op forward.
---
Draft PR: https://github.com/Samsung/ONE/pull/8614
> [luci] Propagate Quantize Op qparam forward

- compiler/luci/import/src/CircleReader.cpp
This commit removes under-bound check on opcode validation check function is_valid().
It makes build error on flatbuffers 2.0.
---
Draft: #8492
> [luci] Update opcode validation check function

- compiler/luci/pass/src/QuantizationUtils.cpp
- compiler/luci/pass/src/QuantizationUtils.h
- compiler/luci/pass/src/QuantizeActivation.cpp
This removes redundant checks in QuantizeActivation.
> [luci] Remove redundant checks in QuantizeActivation

- compiler/luci/import/src/CircleReader.cpp
This commit adds TODO comment for is_valid(OperatorCode) function.
---
Related issue: https://github.com/Samsung/ONE/pull/8627#discussion_r825793545
> [luci] Add TODO comment

- infra/cmake/packages/FlatBuffers-2.0/FlatBuffersConfig.cmake
It changes flatbuffers install path on overlay to remove versioning.
---
Related issue:  #8499
It will resolve build fail on version up and cross build.
> [infra] Change FlatBuffers install path on overlay

- compiler/luci/pass/src/helpers/LayerInfoMap.cpp
This excludes output layer from layer info map.
> [luci] Exclude output from layer info map.

- compiler/enco/frontend/tflite/CMakeLists.txt
This commit updates enco to use FlatBuffers 2.0.
---
Related issue: #8499
> [enco] Use FlatBuffers 2.0

- compiler/mio-tflite/CMakeLists.txt
This commit updates mio-tflite to use FlatBuffers 2.0.
---
> [mio-tflite] Use FlatBuffers 2.0

- compiler/luci-interpreter/src/kernels/ArgMax.test.cpp
- compiler/luci-interpreter/src/kernels/BatchToSpaceND.test.cpp
- compiler/luci-interpreter/src/kernels/Cast.test.cpp
- compiler/luci-interpreter/src/kernels/DepthToSpace.test.cpp
- compiler/luci-interpreter/src/kernels/FullyConnected.test.cpp
- compiler/luci-interpreter/src/kernels/L2Normalize.test.cpp
- compiler/luci-interpreter/src/kernels/LeakyRelu.test.cpp
- compiler/luci-interpreter/src/kernels/Logistic.test.cpp
- compiler/luci-interpreter/src/kernels/OneHot.test.cpp
- compiler/luci-interpreter/src/kernels/Pack.test.cpp
- compiler/luci-interpreter/src/kernels/ResizeBilinear.test.cpp
- compiler/luci-interpreter/src/kernels/ResizeNearestNeighbor.test.cpp
- compiler/luci-interpreter/src/kernels/ReverseV2.test.cpp
- compiler/luci-interpreter/src/kernels/Slice.test.cpp
- compiler/luci-interpreter/src/kernels/Softmax.test.cpp
- compiler/luci-interpreter/src/kernels/SpaceToBatchND.test.cpp
- compiler/luci-interpreter/src/kernels/SpaceToDepth.test.cpp
- compiler/luci-interpreter/src/kernels/Split.test.cpp
- compiler/luci-interpreter/src/kernels/SplitV.test.cpp
- compiler/luci-interpreter/src/kernels/Squeeze.test.cpp
- compiler/luci-interpreter/src/kernels/Transpose.test.cpp
- compiler/luci-interpreter/src/kernels/Unpack.test.cpp
This commit changes TYPED_TEST_CASE gtest macro to TYPED_TEST_SUITE.
TYPED_TEST_CASE will be deprecated.
---
Draft: #8572
Related issue: https://github.com/Samsung/ONE/issues/8567
> [luci-interpreter] Change TYPED_TEST_CASE macro

- compiler/mio-tflite260/CMakeLists.txt
This commit updates mio-tflite260 to use FlatBuffers 2.0.
---
> [mio-tflite260] Use FlatBuffers 2.0

- compiler/mir/src/mir_tflite_importer/CMakeLists.txt
This commit updates mir to use FlatBuffers 2.0.
---
> [mir] Use FlatBuffers 2.0

- compiler/circledump/CMakeLists.txt
This will remove direct link with flatbuffers as mio-circle will do.
> [circledump] Remove link with flatbuffers

- compiler/pota-quantization-value-test/CMakeLists.txt
This commit updates pota-quant to use FlatBuffers 2.0.
---
> [pota-quant] Use FlatBuffers 2.0

- infra/cmake/packages/TensorFlowLite-1.13.1/Lite/CMakeLists.txt
- infra/cmake/packages/TensorFlowLite-1.13.1/TensorFlowLiteConfig.cmake
This commit updates cmake for TFLite 1.13.1 to link flatbuffers-2.0.
---
> [infra] Use FlatBuffers 2.0 fo TFLite 1.13.1

- compiler/one-cmds/one-quantize
- compiler/one-cmds/tests/CMakeLists.txt
- compiler/one-cmds/tests/one-quantize_009.qconf.json
- compiler/one-cmds/tests/one-quantize_009.test
This adds an option for mixed-precision quantization and its test.
--
Related to: https://github.com/Samsung/ONE/issues/8398
> [one-cmds] Support mixed-precision quantization

- compiler/circle-partitioner/CMakeLists.txt
- compiler/circle-partitioner/README.md
This will add tool as circle-partitioner to follow other command naming
conventions. Old name will be removed after changing other codes.
> [circle-partitioner] Rename tool

- compiler/circle-part-value-test/CMakeLists.txt
This will revise to use circle-partitioner tool with hyphen.
> [cir-par-val-test] Use circle-partitioner

- infra/debian/compiler/one-compiler.install
This will revise to install circle-partitioner tool with hyphen.
> [infra/debian] Use circle-partitioner

- compiler/luci/pass/src/RemoveRedundantTransposePass.cpp
- compiler/luci/pass/src/RemoveRedundantTransposePass.test.cpp
This fixes a bug in RemoveRedundantTransposePass.
> [luci] Fix a bug in RemoveRedundantTransposePass

- compiler/luci/pass/src/BatchNormPatternFinder.cpp
- compiler/luci/pass/src/BatchNormPatternFinder.test.cpp
This supports rank4 add/mul in batchnorm finder.
> [luci] Support rank4 add/mul in batchnorm finder

- compiler/luci/pass/src/PropagateQParamBackwardPass.cpp
- compiler/luci/pass/src/VerifyQuantizedNodeGranularity.h
- compiler/luci/pass/src/VerifyQuantizedNodeType.cpp
This allows to concatenate indices in quantized model.
> [luci] Allow concatenating indices in quantized model

- res/CircleSchema/0.4/circle_schema.fbs
This will introduce circle schema 0.4 to follow TensorFlow 2.7.0 schema v3b.
> [res] circle schema 0.4

- compiler/exo/CMakeLists.txt
This will revise to use circle schema from res folder so that upgrading
will not break exo.
> [exo] Revise to use circle schema from res folder

- compiler/common-artifacts/exclude.lst
This commit adds recipe Net_Gather_SparseToDense_AddV2_000 to exlude.lst.
Draft: #8674
for https://github.com/Samsung/ONE/issues/8375#issuecomment-1070126309
> [common-artifacts] Add recipe Net_Gather_SparseToDense_AddV2_000 to exlude.lst

- compiler/mio-circle/CMakeLists.txt
This will revise to use circle schema from res folder so that upgrading
will not change version of mio-circle.
> [mio-circle] Revise to use circle schema from res folder

- compiler/circle-verify/CMakeLists.txt
This will show skip message if mio_circle04 target is not found.
> [circle-verify] Show skip message

- infra/debian/compiler/rules
This will revise debian rules to use preset 20220323 that includes mio-circle04.
> [infra] Revise debian to use preset 20220323

- res/TensorFlowLiteRecipes/Quant_Split_Add_000/test.qconf.json
- res/TensorFlowLiteRecipes/Quant_Split_Add_000/test.recipe
- res/TensorFlowLiteRecipes/Quant_Split_Add_000/test.rule
- res/TensorFlowLiteRecipes/Quant_Split_Add_001/test.qconf.json
- res/TensorFlowLiteRecipes/Quant_Split_Add_001/test.recipe
- res/TensorFlowLiteRecipes/Quant_Split_Add_001/test.rule
This commit adds test recipes with multiple-outputs nodes
draft: https://github.com/Samsung/ONE/pull/8673
issue: https://github.com/Samsung/ONE/issues/8654
> [res] Add test recipes with multiple-outputs nodes

- compiler/luci/pass/src/QuantizeDequantizeWeightsPass.cpp
- compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
- compiler/luci/pass/src/QuantizedModelVerifier.cpp
- compiler/luci/pass/src/helpers/LayerInfoMap.cpp
- compiler/luci/pass/src/helpers/LayerInfoMap.h
- compiler/luci/pass/src/helpers/LayerInfoMap.test.cpp
This updates LayerInfoMap to contain LayerInfo, not pointer.
---
Related to: https://github.com/Samsung/ONE/pull/8717#discussion_r833842255
> [luci] Update dtype of LayerInfoMap

- infra/packaging/preset/20220323
- infra/packaging/preset/20220323_windows
This will revise preset 20220323 to exclude mio-circle as it is not used anymore.
> [infra] Revise preset 20220323

- tests/nnfw_api/src/GenModelTests.cc
This commit fixes Reshape dynamic shape test output size.
Variable `i32` can be byte type by `flatc` 2.0.
---
Draft: #8713
> [onert/test] Fix reshape test

- compiler/circle2circle/src/Circle2Circle.cpp
This pr adds fold gather pass to circle2circle. This pass can remove Gather operation which can be folded
draft: https://github.com/Samsung/ONE/pull/8682
for issue: https://github.com/Samsung/ONE/issues/8375
> [circle2circle] Add Fold Gather pass to circle2circle

- runtime/onert/frontend/circle_schema/include/circle_schema_generated.h
- runtime/onert/frontend/tflite/src/tflite_schema_generated.h
This commit updates circle_schema_generated.h and tflite_schema_generated.h to use flatbuffers 2.0 flatc.
> [onert/frontend] Use flatc 2.0 for header generation

- compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
- compiler/luci/pass/src/helpers/LayerInfoMap.cpp
- compiler/luci/pass/src/helpers/LayerInfoMap.test.cpp
This commit adds support for mixed-precision in Ops with multiple outputs.
draft: #8673
issue: #8654
> [luci] Support mixed-precision in Ops with multiple outputs

- compiler/one-cmds/how-to-use-one-commands.txt
- compiler/one-cmds/onelib/constant.py
This pr adds fold gather pass to one-cmds. This pass can remove Gather operation which can be folded
draft: https://github.com/Samsung/ONE/pull/8682
for issue: https://github.com/Samsung/ONE/issues/8375
> [one-cmds] Add Fold Gather pass to one-cmds

- compiler/circle-quantizer-dredd-recipe-test/test.lst
This commit adds test recipes with multiple-outputs nodes
draft: https://github.com/Samsung/ONE/pull/8673
issue: https://github.com/Samsung/ONE/issues/8654
> [circle-quantizer-dredd-recipe-test] Add tests with multiple-output nodes

- compiler/luci/import/src/Nodes/CircleSquare.cpp
This allows more dtypes in Square.
> [luci] Allow more dtypes in Square.

- compiler/record-minmax/src/RecordMinMax.cpp
This checks input dimension before calibration.
> [record-minmax] Check input dimension before calibration

- compiler/circle-eval-diff/CMakeLists.txt
- compiler/circle-eval-diff/requires.cmake
- compiler/circle-eval-diff/src/Tensor.cpp
- compiler/circle-eval-diff/src/Tensor.h
- compiler/circle-eval-diff/src/Tensor.test.cpp
This introduces data structure for input/output tensor.
---
Related to: https://github.com/Samsung/ONE/issues/8634
Draft PR: https://github.com/Samsung/ONE/pull/8741
> [circle-eval-diff] Introduce Tensor data structure

- infra/nncc/CMakeLists.txt
- infra/nncc/cmake/CfgOptionFlags.cmake
This will extract cmake options to separate CfgOptionFlags.cmake file.
> [infra] Extract cmake options to separate file

- infra/nncc/Makefile.arm32
This will revise ARM32 Makefile to include dio-hdf5 module.
> [infra] Include dio-hdf5 for ARM32 build

- compiler/circle-eval-diff/CMakeLists.txt
- compiler/circle-eval-diff/requires.cmake
- compiler/circle-eval-diff/src/ModuleEvalDiff.cpp
- compiler/circle-eval-diff/src/ModuleEvalDiff.h
This introduces ModuleEvalDiff to compare results of two modules.
---
Related to: https://github.com/Samsung/ONE/issues/8634
Draft PR: https://github.com/Samsung/ONE/pull/8741
> [circle-eval-diff] Introduce ModuleEvalDiff class

- infra/nncc/cmake/options/options_armv7l-linux.cmake
This will introduce options_armv7l-linux.cmake for ARM32 configure
default options.
> [infra/nncc] Introduce options_armv7l-linux

- infra/nncc/cmake/buildtool/config/config_armv7l-linux.cmake
This will enable NEON compile option with BUILD_ARM32_NEON option.
> [infra/nncc] Enable NEON with option

- compiler/circle-eval-diff/src/ModuleEvalDiff.cpp
This enables various input dtypes.
> [circle-eval-diff] Enable various input dtypes

- compiler/tf2tfliteV2-conversion-test/CMakeLists.txt
This will revise test environment to use venv with TF2.6.0.
> [tf2tfliteV2] Revise to use venv_2_6_0

- compiler/record-minmax-conversion-test/CMakeLists.txt
This will revise test environment to use venv with TF2.6.0.
> [record-minmax] Revise to use venv_2_6_0

- compiler/common-artifacts/CMakeLists.txt
This revise to explictly use python3.8
- this is a preparation to use TensorFlow 2.8.0
> [common-artifacts] Use python 3.8

- res/TensorFlowLiteRecipes/Quant_Add_000/test.recipe
- res/TensorFlowLiteRecipes/Quant_Add_000/test.rule
This adds recipe and rule for Quant_Add_000 dredd test.
---
Related to: https://github.com/Samsung/ONE/issues/8797
Draft PR: https://github.com/Samsung/ONE/pull/8798
> [res] Add Quant_Add_000 dredd test.

- compiler/common-artifacts/exclude.lst
This will revise exclude list for ExpandDims Op.
> [common-artifacts] Revise exclude for ExpandDims

- infra/nncc/cmake/options/options_armv7l-linux.cmake
This will turn on NEON option for compiler ARM32 build.
> [infra] Enable NEON for compiler ARM32

- compiler/circle-part-value-test/CMakeLists.txt
> [circle-part-value-test] Use venv_2_8_0

- compiler/luci-pass-value-test/CMakeLists.txt
> [luci-pass-value-test] Use venv_2_8_0

- compiler/luci-value-test/CMakeLists.txt
> [luci-value-test] Use venv_2_8_0

- compiler/pota-quantization-value-test/CMakeLists.txt
> [pota-quan-val-test] Use venv_2_8_0

- compiler/record-minmax-conversion-test/CMakeLists.txt
> [record-minmax-cnv-test] Use venv_2_8_0

- compiler/tf2tfliteV2-conversion-test/CMakeLists.txt
> [tf2tflitev2-cnv-test] Use venv_2_8_0

- compiler/one-cmds/how-to-prepare-virtualenv.txt
- compiler/one-cmds/one-prepare-venv
This will revise one-prepare-venv to use python3.8 and latest packages
- add required and remove needless packages to follow updates
> [one-cmds] Upgrade to python3.8 and latest packages

- docs/howto/how-to-build-runtime.md
It fixes wrong url in how-to-build-runtime.md.
> [docs/howto] Fix broken link in how-to-build-runtime

- infra/nnfw/cmake/packages/TRIXEngineConfig.cmake
This commit changes trix-engine lib name: npu_engine -> trix_engine.
---
Related issue: https://github.com/Samsung/ONE/pull/8805#discussion_r847114294
> [infra] Change trix-engine lib name

- compiler/luci-interpreter/src/kernels/ExpandDims.cpp
This commit adds additional checking in configure for ExpandDims op.
for issue: #8838
> [luci-interpreter] Add additional checking for ExpandDims op

- packaging/nnfw.spec
This commit updates nnfw.spec to install trix-engine-dev.
We can skip trix-engine-dev install by gbs build argument "--define 'trxi_support 0'".
> [onert/gbs] Install trix-engine-dev package

- runtime/onert/core/src/compiler/ExecutorFactory.cc
- runtime/onert/core/src/compiler/ExecutorFactory.h
This commit introduces backend context preparation functions in ExecutorFactory.
It will reduce code duplication.
---
> [onert] Introduce backend context preparation functions

- runtime/onert/core/include/ir/DataType.h
- runtime/onert/core/src/ir/DataType.cc
Introduce QUANT_INT16_SYMM type
- QUANT_INT16_SYMM: int16 quantization operation input/output tensor data type
draft pr: #8888
> [onert] Introduce QUANT_INT16_SYMM type

- tests/tools/nnpackage_run/CMakeLists.txt
- tests/tools/nnpackage_run/src/args.cc
- tests/tools/nnpackage_run/src/args.h
- tests/tools/nnpackage_run/src/formatter.h
- tests/tools/nnpackage_run/src/nnpackage_run.cc
- tests/tools/nnpackage_run/src/rawformatter.cc
- tests/tools/nnpackage_run/src/rawformatter.h
It introduces reading and writing raw data for input and output respectively.
Two options are added:
--load:raw your_input_to_load_in_raw
--dump:raw your_output_dump_in_raw
RawFormatter is introduced
Formatter will also introduced as base class for H5Formatter and RawFormatter.
TODO: Support multiple raw inputs/outputs
Related: #8820
> [nnpackage_run] Introduce load and dump raw

- compiler/circle2circle-dredd-recipe-test/CMakeLists.txt
> [cir2cir-dredd-recipe-test] Enable skip test

- compiler/circle-quantizer-dredd-recipe-test/CMakeLists.txt
> [cir-quant-dredd-recipe-test] Enable skip test

- compiler/embedded-import-value-test/CMakeLists.txt
> [embedded-imp-val-test] Enable skip test

- compiler/luci/CMakeLists.txt
> [luci] Enable skip test

- compiler/luci-pass-value-test/CMakeLists.txt
> [luci-pass-value-test] Enable skip test

- compiler/luci-value-test/CMakeLists.txt
> [luci-value-test] Enable skip test

- runtime/onert/backend/trix/DevContext.h
- runtime/onert/core/src/exec/IPermuteFunction.h
- runtime/onert/frontend/trix/src/trix_loader.cc
This commit supports Q16 symmetric model on TRIX Backend.
draft pr: #8888
_Note_
_This patch does not have build dependency with #8905.
However, this is not executed Q16 model alone. #8905 PR is essential to perform Q16 model on TRIX device._
> [onert] Support Q16 SYMM model on TRIX Backend

- infra/packaging/build
This will introduce '--notest' option for nncc to disable test builds.
> [infra] Introduce notest option for nncc build

- compiler/mir/src/mir_onnx_importer/CMakeLists.txt
> [mir] Enable skip test

- compiler/mir2loco/CMakeLists.txt
> [mir2loco] Enable skip test

- infra/nnfw/cmake/options/options_x86_64-tizen.cmake
- Disable tensorflow-lite build on tizen x86_64
> [onert] Fix tizen x86_64 build fail

- compiler/record-minmax-conversion-test/CMakeLists.txt
> [record-minmax-conv-test] Enable skip test

- compiler/tf2circle-conversion-test/CMakeLists.txt
> [tf2cir-conv-test] Enable skip test

- compiler/tf2circle-dredd-pb-test/CMakeLists.txt
> [tf2cir-dredd-pb-test] Enable skip test

- compiler/tf2circle-dredd-pbtxt-test/CMakeLists.txt
> [tf2cir-dredd-pbtxt-test] Enable skip test

- compiler/tf2circle-model-test/CMakeLists.txt
> [tf2cir-model-test] Enable skip test

- compiler/tf2tflite-dredd-pb-test/CMakeLists.txt
> [tf2tflite-dredd-pb-test] Enable skip test

- compiler/tf2tflite-dredd-pbtxt-test/CMakeLists.txt
> [tf2tfl-dredd-pbtxt-test] Enable skip test

- compiler/tf2tfliteV2-conversion-test/CMakeLists.txt
> [tf2tflV2-conv-test] Enable skip test

- compiler/tf2tflite-value-pb-test/CMakeLists.txt
> [tf2tfl-value-pb-test] Enable skip test

- compiler/tf2tflite-value-pbtxt-test/CMakeLists.txt
> [tf2tfl-value-pbtxt-test] Enable skip test

- compiler/tflchef/CMakeLists.txt
> [tflchef] Enable skip test

- compiler/tflite2circle-conversion-test/CMakeLists.txt
> [tfl2cir-conv-test] Enable skip test

- compiler/tfl-inspect/CMakeLists.txt
This will revise to check with mio_tflite280.
> [tfl-inspect] Revise CMakeLists mio_tflite280 check

- compiler/cli/CMakeLists.txt
This will fix GTest_AddTest typo.
> [cli] Fix typo in CMakeLists

- compiler/logo/src/Passes/SimplifyDomainConversionPass.cpp
This will relocate encoder to match like others for preparation to
reduce duplicate codes.
> [logo] Relocate encoder

- compiler/tfl-verify/CMakeLists.txt
This will revise to check with mio_tflite280.
> [tfl-verify] Revise CMakeLists mio_tflite280 check

- runtime/libs/ndarray/test/ndarray_test.cpp
This commit adds more different type NDArray tests.
`ContiguousSpan<float, true>` and `ContiguousSpan<int32_t, false>` are used in DetectionPostProcessLayer.
---
Related issue: #8935
> [onert/ndarray] Add more NDArray tests

- tests/nnfw_api/src/CircleGen.cc
- tests/nnfw_api/src/CircleGen.h
- tests/nnfw_api/src/one_op_tests/NotEqual.cc
It adds tests for NotEqual based on Equal test.
It just negates the expected output of Equal test.
Related: #8935
> [onert] Add NotEqual Tests in one_op_tests

- tests/nnfw_api/src/one_op_tests/Less.cc
It adds tests for Less based on Equal test.
It is basically based on Equal.cc. Here are changes:
- It removes `bool` input type, which is not defined for inequality
- It changes some input/output values.
Related: #8935
> [onert] Add Less Tests in one_op_tests

- tests/nnfw_api/src/CircleGen.cc
- tests/nnfw_api/src/CircleGen.h
- tests/nnfw_api/src/one_op_tests/Greater.cc
It adds tests for Greater by negating LessEqual's expected output.
Related: #8935
> [onert] Add Greater Tests in one_op_tests

- tests/nnfw_api/src/CircleGen.cc
- tests/nnfw_api/src/CircleGen.h
- tests/nnfw_api/src/one_op_tests/LessEqual.cc
It adds tests for LessEqual based on Less test.
- Equal case's expected values are changed from false to true after
copying Less test.
Related: #8935
> [onert] Add LessEqual Tests in one_op_tests

- compiler/arser/include/arser/arser.h
This will extract common code print_usage_argto reduce duplicate codes.
> [arser] Extract common code print_usage_arg

- compiler/arser/include/arser/arser.h
This will extract common code print_help_args to reduce duplicate codes.
> [arser] Extract common code print_help_args

- tests/nnfw_api/src/CircleGen.cc
- tests/nnfw_api/src/CircleGen.h
- tests/nnfw_api/src/one_op_tests/GreaterEqual.cc
- tests/nnfw_api/src/one_op_tests/LessEqual.cc
It adds tests for GreaterEqual by negating existing Less test's expected
value.
Related: #8935
> [onert] Add GreaterEqual Tests in one_op_tests

- runtime/onert/frontend/base_loader/include/base_loader.h
- tests/nnfw_api/src/one_op_tests/Cast.cc
It adds more tests for uncovered input types (e.g. int64_t, uint32_t,
...) in Cast operator.
Related: #8935
> [onert] Add more test for Cast

- tests/nnfw_api/src/one_op_tests/Add.cc
It replaces typo net with neg in negative test name.
I found a typo while referencing negative test code.
> [onert] Fix typo in Add negative test

- compiler/circle-opselector/driver/Driver.cpp
> [circle-opselector] Revise arser usage

- compiler/common-artifacts/src/TestDataGenerator.cpp
This will revise arser usage to reduce duplicate codes, but not for scores
> [common-artifacts] Revise arser usage

- compiler/tflchef/tools/file/Driver.cpp
- compiler/tflchef/tools/reverse/Driver.cpp
This will revise arser usage to reduce duplicate codes, but not for scores
> [tflchef] Revise arser usage

- infra/packaging/preset/20220323
- infra/packaging/preset/20220323_windows
This will fix preset 20220323 to include modules for -dev, -test packages.
> [infra] Fix preset 20220323

- .ahub/sam/exclude.txt
This will exclude tflchef/tflite Op header files from analyis.
> [ahub] Revise exclude with tflchef header

- compiler/circledump/src/Read.cpp
This will revise to use mio::circle::builtin_code_neutral for correct
builtin_code.
> [circledump] Use mio::circle::builtin_code_neutral

- compiler/luci-interpreter/src/loader/nodes/Add.cpp
- compiler/luci-interpreter/src/loader/nodes/ArgMax.cpp
- compiler/luci-interpreter/src/loader/nodes/AveragePool2D.cpp
- compiler/luci-interpreter/src/loader/nodes/BatchMatMul.cpp
- compiler/luci-interpreter/src/loader/nodes/BatchToSpaceND.cpp
- compiler/luci-interpreter/src/loader/nodes/Cast.cpp
- compiler/luci-interpreter/src/loader/nodes/Concatenation.cpp
- compiler/luci-interpreter/src/loader/nodes/Conv2D.cpp
- compiler/luci-interpreter/src/loader/nodes/DepthToSpace.cpp
- compiler/luci-interpreter/src/loader/nodes/DepthwiseConv2D.cpp
- compiler/luci-interpreter/src/loader/nodes/Dequantize.cpp
- compiler/luci-interpreter/src/loader/nodes/Div.cpp
> [luci-interpreter] Use must_cast (A~D)

- compiler/luci-interpreter/src/loader/nodes/Elu.cpp
- compiler/luci-interpreter/src/loader/nodes/Equal.cpp
- compiler/luci-interpreter/src/loader/nodes/Exp.cpp
- compiler/luci-interpreter/src/loader/nodes/Floor.cpp
- compiler/luci-interpreter/src/loader/nodes/FloorDiv.cpp
- compiler/luci-interpreter/src/loader/nodes/FullyConnected.cpp
- compiler/luci-interpreter/src/loader/nodes/Gather.cpp
- compiler/luci-interpreter/src/loader/nodes/Greater.cpp
- compiler/luci-interpreter/src/loader/nodes/GreaterEqual.cpp
- compiler/luci-interpreter/src/loader/nodes/If.cpp
- compiler/luci-interpreter/src/loader/nodes/InstanceNorm.cpp
> [luci-interpreter] Use must_cast (E~I)

- compiler/luci-interpreter/src/loader/nodes/L2Normalize.cpp
- compiler/luci-interpreter/src/loader/nodes/L2Pool2D.cpp
- compiler/luci-interpreter/src/loader/nodes/LeakyRelu.cpp
- compiler/luci-interpreter/src/loader/nodes/Less.cpp
- compiler/luci-interpreter/src/loader/nodes/LessEqual.cpp
- compiler/luci-interpreter/src/loader/nodes/LocalResponseNormalization.cpp
- compiler/luci-interpreter/src/loader/nodes/LogSoftmax.cpp
- compiler/luci-interpreter/src/loader/nodes/LogicalAnd.cpp
- compiler/luci-interpreter/src/loader/nodes/LogicalNot.cpp
- compiler/luci-interpreter/src/loader/nodes/LogicalOr.cpp
- compiler/luci-interpreter/src/loader/nodes/Logistic.cpp
> [luci-interpreter] Use must_cast (L)

- compiler/luci-interpreter/src/loader/nodes/MaxPool2D.cpp
- compiler/luci-interpreter/src/loader/nodes/Maximum.cpp
- compiler/luci-interpreter/src/loader/nodes/Mean.cpp
- compiler/luci-interpreter/src/loader/nodes/Minimum.cpp
- compiler/luci-interpreter/src/loader/nodes/MirrorPad.cpp
- compiler/luci-interpreter/src/loader/nodes/Mul.cpp
- compiler/luci-interpreter/src/loader/nodes/Neg.cpp
- compiler/luci-interpreter/src/loader/nodes/NotEqual.cpp
- compiler/luci-interpreter/src/loader/nodes/PRelu.cpp
- compiler/luci-interpreter/src/loader/nodes/Pack.cpp
- compiler/luci-interpreter/src/loader/nodes/Pad.cpp
- compiler/luci-interpreter/src/loader/nodes/PadV2.cpp
- compiler/luci-interpreter/src/loader/nodes/Pow.cpp
> [luci-interpreter] Use must_cast (M~P)

- compiler/luci-interpreter/src/loader/nodes/Relu.cpp
- compiler/luci-interpreter/src/loader/nodes/Relu6.cpp
- compiler/luci-interpreter/src/loader/nodes/Reshape.cpp
- compiler/luci-interpreter/src/loader/nodes/ResizeBilinear.cpp
- compiler/luci-interpreter/src/loader/nodes/ResizeNearestNeighbor.cpp
- compiler/luci-interpreter/src/loader/nodes/ReverseV2.cpp
- compiler/luci-interpreter/src/loader/nodes/Rsqrt.cpp
- compiler/luci-interpreter/src/loader/nodes/Slice.cpp
- compiler/luci-interpreter/src/loader/nodes/Softmax.cpp
- compiler/luci-interpreter/src/loader/nodes/SpaceToBatchND.cpp
- compiler/luci-interpreter/src/loader/nodes/SpaceToDepth.cpp
- compiler/luci-interpreter/src/loader/nodes/Split.cpp
- compiler/luci-interpreter/src/loader/nodes/SplitV.cpp
> [luci-interpreter] Use must_cast (R~S)

- compiler/luci-interpreter/src/loader/nodes/Quantize.cpp
- compiler/luci-interpreter/src/loader/nodes/SVDF.cpp
- compiler/luci-interpreter/src/loader/nodes/Sqrt.cpp
- compiler/luci-interpreter/src/loader/nodes/Square.cpp
- compiler/luci-interpreter/src/loader/nodes/SquaredDifference.cpp
- compiler/luci-interpreter/src/loader/nodes/Squeeze.cpp
- compiler/luci-interpreter/src/loader/nodes/StridedSlice.cpp
- compiler/luci-interpreter/src/loader/nodes/Sub.cpp
- compiler/luci-interpreter/src/loader/nodes/Tanh.cpp
- compiler/luci-interpreter/src/loader/nodes/Transpose.cpp
- compiler/luci-interpreter/src/loader/nodes/TransposeConv.cpp
- compiler/luci-interpreter/src/loader/nodes/Unpack.cpp
- compiler/luci-interpreter/src/loader/nodes/While.cpp
> [luci-interpreter] Use must_cast (Q~W)

- compiler/tflchef/tflite/src/Op/NonMaxSuppressionV4.cpp
- compiler/tflchef/tflite/src/Op/NonMaxSuppressionV5.cpp
- compiler/tflchef/tflite/src/Op/PadV2.cpp
- compiler/tflchef/tflite/src/Op/ScatterNd.cpp
- compiler/tflchef/tflite/src/Op/SegmentSum.cpp
This will fix to use input tensor index not the input index.
> [tflchef] Fix fill_tensor index

- compiler/record-minmax/src/RecordMinMax.cpp
This will fix null ptr warning using model ptr.
> [record-minmax] Fix null ptr warning

- compiler/luci/pass/include/luci/CircleOptimizer.h
- compiler/luci/pass/include/luci/Pass/ReplaceNonConstFCWithBatchMatMulPass.h
- compiler/luci/pass/src/CircleOptimizer.cpp
- compiler/luci/pass/src/ReplaceNonConstFCWithBatchMatMulPass.cpp
- compiler/luci/pass/src/ReplaceNonConstFCWithBatchMatMulPass.test.cpp
This commit allows non-constant weight (B in AxB+C)
for FullyConnected Layer quantization.
This is needed in order to support Transformer-type models.
ONE-DCO-1.0-Signed-off-by: Andrey Shedko <a.shedko@samsung.com>
> [luci] Allow non-constant weight for FC

- compiler/tflchef/tflite/src/FillerHelper.cpp
- compiler/tflchef/tflite/src/FillerHelper.h
This will introduce fill_two_inputs method as common filler helper.
> [tflchef] Introduce fill_two_inputs helper

- compiler/tflchef/tflite/src/Op/Add.cpp
- compiler/tflchef/tflite/src/Op/Maximum.cpp
- compiler/tflchef/tflite/src/Op/Minimum.cpp
- compiler/tflchef/tflite/src/Op/Mul.cpp
- compiler/tflchef/tflite/src/Op/Sub.cpp
This will revise using fill_two_inputs to reduce duplicate codes.
> [tflchef] Revise using fill_two_inputs

- compiler/mio-circle04/include/mio_circle/Reader.h
- compiler/mio-circle04/src/Reader.cpp
This will add helper methods to get tensor name and dtype.
> [mio-circle04] Add helper methods for tensor

- infra/scripts/docker_build_test_x64.sh
This commit enables nnpackage_run on x64 runtime build test script.
> [infra] Enable nnpackage_run build on x64 runtime build

- compiler/luci/pass/src/CircleQuantizer.cpp
- compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
This supports float32 input/output in quantization.
---
Draft PR: #9030
> [luci] Support float32 input/output in quantization

- res/TensorFlowLiteRecipes/Quant_Conv_000/test.recipe
- res/TensorFlowLiteRecipes/Quant_Conv_000/test.rule
- res/TensorFlowLiteRecipes/Quant_Conv_001/test.recipe
- res/TensorFlowLiteRecipes/Quant_Conv_001/test.rule
- res/TensorFlowLiteRecipes/Quant_Conv_002/test.recipe
- res/TensorFlowLiteRecipes/Quant_Conv_002/test.rule
This adds recipes/rules to test fp32 input/output feature of circle-quantizer.
---
Draft PR: https://github.com/Samsung/ONE/pull/9030
> [res] Add recipes/rules for circle-quantizer-dredd-test

- compiler/one-cmds/one-quantize
This updates help message of one-quantize for float32 input/output.
---
Draft PR: https://github.com/Samsung/ONE/pull/9030
> [one-cmds] Support float32 input/output in one-quantize

- compiler/circle-quantizer/src/CircleQuantizer.cpp
This updates help message for float32 input/output type.
---
Draft PR: https://github.com/Samsung/ONE/pull/9030
> [circle-quantizer] Support float32 input/output type

- compiler/luci/pass/src/ConvertToFakeQuantizedModelPass.cpp
This supports 22 more Ops in ConvertToFakeQuantizedModelPass.
---
Related to: https://github.com/Samsung/ONE/issues/8731
> [luci] Support more Ops in ConverToFakeQuantizedModelPass.

- compiler/circle2circle/src/Circle2Circle.cpp
This PR adds ReplaceNonConstFCWithBatchMatMul option to circle2circle.
The pass allows us to compile FC with non-const weight to Batch MatMul.
Signed-off-by: a.shedko <a.shedko@samsung.com>
> [circle2circle] Add ReplaceNonConstFCWithBatchMatMul option

- compiler/circle-quantizer-dredd-recipe-test/CMakeLists.txt
- compiler/circle-quantizer-dredd-recipe-test/test.lst
This adds tests for fp32 input/output.
---
Draft PR: https://github.com/Samsung/ONE/pull/9030
> [circle-quantizer-dredd] Add tests for fp32 input/output

- compiler/luci-eval-driver/src/EvalDriver.cpp
This will fix major defect of not checking nullptr with calling existing
importVerifyModule method.
> [luci-eval-driver] Fix major defect

- tests/tools/nnpackage_run/src/rawformatter.cc
Multiple raw output dump is allowed.
`multiout.q8` is an nnpackage with 2 outputs model.
```
$ tree multiout.q8
multiout.q8
├── metadata
│   └── MANIFEST
├── multiout.q8.circle
├── multiout.q8.expected.0
├── multiout.q8.expected.1
├── multiout.q8.in.0
└── multiout.q8.tvn
```
```
$ BACKENDS="trix;cpu" ./Product/x86_64-linux.debug/out/bin/nnpackage_run \
--load:raw multiout.q8/multiout.q8.in \
--dump:raw multiout.q8/multiout.q8.out \
multiout.q8
...
E: Fail to run by runtime error:Only 1 output is supported for raw input
```
```
$ BACKENDS="trix;cpu" ./Product/x86_64-linux.debug/out/bin/nnpackage_run \
--load:raw multiout.q8/multiout.q8.in \
--dump:raw multiout.q8/multiout.q8.out \
multiout.q8
$ diff multiout.q8/multiout.q8.{out,expected}.0
$ …
```
> [nnpackage_run] Support multiple raw output dump

- infra/scripts/test_ubuntu_runtime_mixed.sh
Now AvgPool2D and MaxPool2D internal IR is merged to Pool2D.
So backend mapping is not working, and test uses cpu backend only.
This commit updates backend mapping on mixed test to use acl-cl and acl-neon backend.
> [onert/test] Fix mixed test

- compiler/circle-quantizer-dredd-recipe-test/test.lst
This adds mixed-quant tests for ADD Op.
---
Related to: https://github.com/Samsung/ONE/issues/9056
Draft PR: https://github.com/Samsung/ONE/pull/9057
> [quantizer-dredd] Add mixed-quant test for ADD

- compiler/luci/pass/src/QuantizationUtils.cpp
- compiler/luci/pass/src/QuantizationUtils.h
- compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
This PR logs warnings when weights cannot be accurately represented.
Another way to implement #8889
Signed-off-by: a.shedko <a.shedko@samsung.com>
> [luci] Issue warnings when weights cannot be accurately represented

- infra/debian/compiler/changelog
This commit fixes changelog trailer line.
```bash
dch: warning:     debian/changelog(l22): badly formatted trailer line
19:44:25  LINE:  -- seongwoo <mhs4670go@naver.com> Tue, 26 Apr 2022 12:00:00 +0900
```
> [debian] Fix changelog trailer line

- compiler/circle-partitioner/README.md
This will fix README file with circle-partitioner name.
> [circle-partitioner] Fix README

- compiler/circle-partitioner/CMakeLists.txt
This will remove creating binary with old name.
> [circle-partitioner] Remove old binary

- compiler/luci/pass/include/luci/Pass/RemoveRedundantDequantizePass.h
- compiler/luci/pass/src/RemoveRedundantDequantizePass.cpp
- compiler/luci/pass/src/RemoveRedundantDequantizePass.test.cpp
This introduces a pass to remove redundant Dequantize Ops.
> [luci] Introduce pass to remove redundant Dequantize Ops

- compiler/circle-partitioner-test/CMakeLists.txt
This will re-enable test with optional arguments.
> [circle-part-test] Enable test with optional arguments

- compiler/circle-part-value-test/CMakeLists.txt
This will re-enable test with optional arguments.
> [circle-part-val-test] Enable test with optional arguments

- compiler/luci/pass/src/CircleQuantizer.cpp
This removes redundant dequantize Ops generated during fake quantization.
---
Related to: https://github.com/Samsung/ONE/pull/9082#issuecomment-1114421500
> [luci] Remove redundant dequant in fake quantization

- runtime/onert/core/CMakeLists.txt
- runtime/onert/core/include/util/ObjectManager.h
- runtime/onert/core/src/util/Index.test.cc
- runtime/onert/core/src/util/ObjectManager.test.cc
- runtime/onert/core/src/util/ShapeInference.test.cc
This commit moves core/util unittest into "core/src/util".
---
Related issue; #9063
> [onert] Move core/util unittest

- compiler/circle-eval-diff/src/MetricPrinter.cpp
This throws exception if dtype/shape of outputs mismatch.
> [circle-eval-diff] Throw exception for dtype/shape mismatch

- compiler/one-cmds/tests/one-partition_001.test
- compiler/one-cmds/tests/one-partition_neg_001.test
- compiler/one-cmds/tests/one-partition_neg_002.test
This will introduce basick tests for one-partition tool.
> [one-cmds] Basic one-cmds tests for one-partition

- runtime/onert/core/include/compiler/BackendManager.h
- runtime/onert/core/src/compiler/BackendManager.cc
- runtime/onert/core/src/compiler/ExecutorFactory.cc
- runtime/onert/core/src/compiler/HEScheduler.h
- runtime/onert/core/src/compiler/pass/PermutationInsertionPass.cc
This commit changes BackendManager::getBuiltin() type to backend::Backend.
Builtin backend is not public header, so we cannot use backend::builtin::Backend type on public header "BackendManager.h".
This commit includes public/private header include fix and reorder.
> [onert] Change getBuiltin() type

- runtime/onert/core/src/compiler/HEScheduler.test.cc
- runtime/onert/core/src/compiler/pass/UnusedOperandEliminationPass.test.cc
This commit moves core/compiler unittest into "src/".
---
Related issue: #9063
> [onert] Move core/compiler unittest

- compiler/circle-eval-diff/src/Tensor.cpp
- compiler/circle-eval-diff/src/Tensor.h
- compiler/circle-eval-diff/src/Tensor.test.cpp
This commit adds createEmptyTensor method that literally creates empty tensor from existing CircleNode.
This function is from `compiler/circle-eval-diff/src/CircleEvalDiff.cpp` that will be removed soon.
Draft: https://github.com/Samsung/ONE/pull/8830
Related: https://github.com/Samsung/ONE/issues/8829
> [circle-eval-diff] Add creating empty tensor method

- compiler/luci/pass/src/QuantizationUtils.cpp
- compiler/luci/pass/src/QuantizationUtils.h
- compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
This allows to make pre-defined qparam using input of Quantize Op.
> [luci] Make pre-defined qparam using input of Quantize Op.

- compiler/circle-eval-diff/driver/Driver.cpp
- compiler/circle-eval-diff/include/CircleEvalDiff.h
- compiler/circle-eval-diff/src/CircleEvalDiff.cpp
This commit makes driver use input data loader.
Draft: https://github.com/Samsung/ONE/pull/8830
Related: https://github.com/Samsung/ONE/issues/8829
> [circle-eval-diff] Use Input data loader

- compiler/luci/pass/src/PropagateQParamForwardPass.cpp
- compiler/luci/pass/src/QuantizationUtils.cpp
- compiler/luci/pass/src/QuantizationUtils.h
- compiler/luci/pass/src/QuantizeActivation.cpp
- compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
This defines PreDefinedValues qtype for each op. This change makes
pre-defined qparam be made directly from ActivationQType.
---
Draft PR: https://github.com/Samsung/ONE/pull/9118
> [luci] Refactor activation qtype for pre-defined values

- compiler/one-cmds/onelib/constant.py
This enables support for replace_non_const_fc_with_batch_matmul option.
---
Related to: https://github.com/Samsung/ONE/pull/8874
> [one-cmds] Support replace_non_const_fc_with_bmm option

- compiler/one-cmds/utils.py
This suppresses warning message about line buffer.
---
Related to: https://github.com/Samsung/ONE/issues/9130
> [one-cmds] Suppress warning message about line buffer

- runtime/onert/core/src/ir/Graph.test.cc
- runtime/onert/core/src/ir/LayoutSet.test.cc
- runtime/onert/core/src/ir/OperandIndexSequence.test.cc
- runtime/onert/core/src/ir/Operands.test.cc
- runtime/onert/core/src/ir/Shape.test.cc
- runtime/onert/test/core/ir/Operations.test.cc
This commit moves ir unittest into "src/".
---
Related issue: https://github.com/Samsung/ONE/issues/9063
> [onert] Move ir unittest

- compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
This removes redundant Quantize Ops after quantization.
> [luci] Remove redundant Quantize Ops after quantization

- compiler/circle-eval-diff/CMakeLists.txt
This installs circle-eval-diff binary in the bin directory.
---
Related to: https://github.com/Samsung/ONE/issues/9124
Draft PR: https://github.com/Samsung/ONE/pull/9141
> [circle-eval-diff] Install circle-eval-diff binary

- runtime/onert/core/include/backend/basic/BackendContextHelpers.h
- runtime/onert/core/include/util/ObjectManager.h
This commit removes copy on unordered_map and vector iterate.
> [onert] Remove unneecessary copy

- compiler/circle-eval-diff/driver/Driver.cpp
- compiler/circle-eval-diff/include/CircleEvalDiff.h
- compiler/circle-eval-diff/src/CircleEvalDiff.cpp
This supports Top-1 and Top-5 match ratio.
---
Related to: https://github.com/Samsung/ONE/issues/9124
Draft PR: https://github.com/Samsung/ONE/pull/9141
> [circle-eval-diff] Support Top-1 and Top-5 match ratio

- compiler/one-cmds/one-quantize
- compiler/one-cmds/tests/one-quantize_011.test
This adds Top-1 and Top-5 metrics to evaluate quantized model.
---
Related to: https://github.com/Samsung/ONE/issues/9124
Draft PR: https://github.com/Samsung/ONE/pull/9141
> [one-cmds] Support Top-1 and Top-5 metrics in one-quantize

- compiler/one-cmds/onecc
This commit changes warning format in onecc.
Related: https://github.com/Samsung/ONE/issues/9125#issuecomment-1132583726
> [one-cmds] Change warning format

- infra/docker/bionic/Dockerfile
- infra/docker/focal/Dockerfile
Dockerfile to build developer image has bug removing /tmp directory. It will fix bug and remain /tmp directory.
> [infra] Fix developer dockerfile

- compiler/one-cmds/one-quantize
This allows to save intermediate files of one-quantize.
- Introduce save_intermediate option
- Revise meaningless names of intermediate files.
> [one-cmds] Save intermediate files of one-quantize

- compiler/circle-eval-diff/src/CircleEvalDiff.cpp
- compiler/circle-eval-diff/src/MetricPrinter.cpp
This checks output signature in init to reduce duplicate checks.
> [circle-eval-diff] Check output signature in init

- infra/nnfw/config/gbs.conf
This commit removes userinfo from gbs.conf.
Userinfo in config file makes fail on proxy environment.
> [infra/gbs] Remove userinfo

- compiler/luci/pass/src/ForwardReshapeToUnaryOpPass.cpp
- compiler/luci/pass/src/ForwardReshapeToUnaryOpPass.test.cpp
This supports Logistic in ForwardReshapeToUnaryOpPass.
> [luci] Support Logistic in ForwardReshapeToUnaryOpPass

- infra/scripts/docker_build_nncc.sh
- infra/scripts/docker_collect_nnpkg_resources.sh
This commit resolve build fail by mounting on docker container on docker version >= 20
When "TENSORFLOW_PREFIX" and "ONNXRUNTIME_PREFIX" has no value, "-d" test return true.
> [infra] Fix build script bug

- compiler/circle-eval-diff/src/CircleEvalDiff.cpp
This performs null check for circle model.
---
Related to: https://github.com/Samsung/ONE/issues/9195
> [circle-eval-diff] Do null check for circle

- compiler/circle-quantizer/src/CircleQuantizer.cpp
This supports multiple names in quant config.
---
Related to: https://github.com/Samsung/ONE/issues/9170
Draft PR: #9201
> [circle-quantizer] Support multiple names in quant config

- compiler/one-cmds/one-prepare-venv
This will add temporary fix for protobuf issue that requires old version
and environment set.
> [one-cmds] Fix for protobuf issue

- compiler/one-cmds/CMakeLists.txt
- compiler/one-cmds/one-infer
This commit introduces `one-infer` which executes backend inference tool.
---
for: #8970 
draft: #9122
> [one-cmds] Introduce `one-infer` to `one-cmds`

- compiler/one-cmds/tests/one-quantize_012.qconf.json
- compiler/one-cmds/tests/one-quantize_012.test
This adds test for multiple layer names in quantization configuration file.
---
Related to: https://github.com/Samsung/ONE/issues/9170
Draft PR: https://github.com/Samsung/ONE/pull/9201
> [one-cmds] Add test for multiple layer names in qconf

- compiler/mio-circle04/include/mio_circle/Reader.h
- compiler/mio-circle04/src/Reader.cpp
This will introduce method to get tensor index of Operator outputs.
> [mio-circle04] Operator outputs

- compiler/crew/src/PConfigIni.test.cpp
This will fix negative test with NEG suffix.
> [crew] Fix negative test as NEG

- infra/command/gen-coverage-report
This commit removes test files *.test.cc and files in directory tess/ from coverage report.
> [infra] Exclude more test code on coverage

- compiler/one-cmds/one-optimize
- compiler/one-cmds/tests/onecc_neg_011.cfg
- compiler/one-cmds/tests/onecc_neg_011.test
This generates errors for unrecognized optimization options.
---
Related to: https://github.com/Samsung/ONE/issues/9172
> [one-cmds] Generate error for unknown optimization options

- compiler/one-cmds/tests/one-build_008.cfg
- compiler/one-cmds/tests/one-build_009.cfg
- compiler/one-cmds/tests/onecc_008.cfg
- compiler/one-cmds/tests/onecc_009.cfg
This removes unrecognized opt option.
---
Related to: https://github.com/Samsung/ONE/issues/9154
> [one-cmds] Remove unrecognized option

- infra/scripts/unittest_compiler_xml.sh
This commit resolves coverage test fail by using absolute report path and executing test binary on each test directory.
> [infra] Fix compiler coverage report

- infra/debian/compiler/one-compiler.install
This will revise debian install list to include circle-operator tool.
> [infra] Add circle-operator to debian install

- compiler/one-cmds/one-prepare-venv
This will fix tensorflow_probability to match TF2.8.0.
> [one-cmds] Fix tensorflow_probability version

- compiler/one-cmds/one-quantize
This gives qconfig file when doing quantize_dequantize.
> [one-cmds] Give qconfig when quantize_dequantize

- runtime/libs/misc/include/misc/string_helpers.h
- runtime/libs/misc/src/string_helpers.test.cpp
This commit resolves "USE_AFTER_MOVE" warning.
It includes unittest for string helpers.
> [onert/misc] Resolve string helper warning

- compiler/one-cmds/one-quantize
- compiler/one-cmds/tests/one-quantize_013.qconf.json
- compiler/one-cmds/tests/one-quantize_013.test
- compiler/one-cmds/tests/one-quantize_neg_020.test
This uses default dtype/granularity in qconfig file.
> [one-cmds] Use default dtype/granularity in qconfig

- infra/debian/compiler/docs/one-infer.1
This commit fixes `one-infer` man page to include
enough information about the command itself.
---
Left is master and right is this pr's
I think one approval is enough :)
> [one-cmds] Fix `one-infer` man page

- compiler/circle-eval-diff/driver/Driver.cpp
- compiler/circle-eval-diff/src/InputDataLoader.cpp
- compiler/circle-eval-diff/src/InputDataLoader.h
This commit makes `circle-eval-diff` support directory input.
Related test is gonna be posted after this pr is merged.
Related: #9224 
> [circle-eval-diff] Support directory input

- runtime/onert/api/src/nnfw_api_internal.cc
Use explicit nullptr comparision in assert.
That is, assert(!ptr) to assert(ptr == nullptr)
Related: https://github.com/Samsung/ONE/pull/9271#discussion_r899673603
> [onert/api] Revise assert

- compiler/one-cmds/tests/one-quantize_014.test
This commit adds `one-quantize` test. This test tests if `circle-eval-diff` supports directory input.
Related: #9224 
> [one-cmds] Add one-quantize test

- runtime/onert/core/src/compiler/HEScheduler.test.cc
- tests/nnfw_api/src/one_op_tests/ArgMinMax.test.cc
- tests/nnfw_api/src/one_op_tests/AveragePool2D.test.cc
- tests/nnfw_api/src/one_op_tests/Concat.test.cc
- tests/nnfw_api/src/one_op_tests/DepthToSpace.test.cc
- tests/nnfw_api/src/one_op_tests/DepthwiseConv2D.test.cc
- tests/nnfw_api/src/one_op_tests/Fill.test.cc
- tests/nnfw_api/src/one_op_tests/If.test.cc
- tests/nnfw_api/src/one_op_tests/Pad.test.cc
- tests/nnfw_api/src/one_op_tests/Reduce.test.cc
- tests/nnfw_api/src/one_op_tests/ResizeBilinear.test.cc
- tests/nnfw_api/src/one_op_tests/Slice.test.cc
- tests/nnfw_api/src/one_op_tests/Softmax.test.cc
- tests/nnfw_api/src/one_op_tests/While.test.cc
This commit changes googletest TEST_CASE to TEST_SUITE.
TEST_CASE is deprecated to avoid confusing.
---
Related: http://google.github.io/googletest/primer.html#beware-of-the-nomenclature
> [onert/test] Rename TEST_CASE to TEST_SUITE

- runtime/onert/api/src/nnfw_api_internal.cc
- runtime/onert/api/src/nnfw_api_internal.h
- runtime/onert/core/include/compiler/Compiler.h
- runtime/onert/core/src/compiler/Compiler.cc
- runtime/onert/core/src/compiler/HEScheduler.test.cc
- runtime/onert/core/src/exec/Execution.test.cc
- runtime/onert/frontend/nnapi/wrapper/ANeuralNetworksCompilation.cc
- runtime/onert/frontend/nnapi/wrapper/ANeuralNetworksCompilation.h
CompilerOptions outlives Compiler.
CompilerOptions are prepared before Compiler::compile()
- nnfw_set_available_backecnds(), nnfw_set/get_config().
Related: https://github.com/Samsung/ONE/pull/9271#issuecomment-1158387870
> [onert] Get CompilerOptions out of Compiler

- runtime/onert/api/src/nnfw_api_internal.cc
Currently, Compiler is created immediately in load...().
Let's create Compiler just before compile in prepare().
Background: https://github.com/Samsung/ONE/pull/9244/files#r899671545
> [onert/api] Create Compiler in prepare(), not in load...()

- compiler/mio-tflite/README.md
This will update readme with note with this module is obsolete.
> [mio-tflite] Update readme with obsolete

- runtime/onert/api/src/nnfw_api_internal.cc
- runtime/onert/api/src/nnfw_api_internal.h
- runtime/onert/core/src/compiler/Compiler.cc
_compiler is used during compile().
Let's kick off _compiler out of nnfw_session.
From #9279
> [onert/api] Remove _compiler from nnfw_session

- runtime/onert/api/src/nnfw_api_internal.cc
- runtime/onert/api/src/nnfw_api_internal.h
- runtime/onert/core/include/compiler/Compiler.h
- runtime/onert/core/src/compiler/Compiler.cc
- runtime/onert/core/src/exec/Execution.test.cc
- runtime/onert/frontend/nnapi/wrapper/ANeuralNetworksCompilation.cc
- runtime/onert/frontend/nnapi/wrapper/ANeuralNetworksCompilation.h
This commit introduceCompilerArtifact class.
Compiler returns CompilerArtifact which includes ExecutorMap and TracingCtx.
---
Related issue: #9281
Draft: #9280
> [onert] Introduce CompilerArtifact

- runtime/onert/api/src/nnfw_api_internal.cc
_tracing_ctx from nnfw_session is not used any longer.
Now, it is created by compile(), and passed as a member of artifact.
Related: #9281
> [onert/api] Remove tracing_ctx from nnfw_session

- runtime/onert/frontend/nnapi/wrapper/ANeuralNetworksCompilation.cc
- runtime/onert/frontend/nnapi/wrapper/ANeuralNetworksCompilation.h
tracing_ctx is not created and managed by out-of-compiler.
It is created by compile(). Thus, it is not necessary.
Related #9281
> [onert/nnapi] Remove tracing_ctx from ANeuralNetworkCompilation

- .github/workflows/check-pr-commit.yml
This commit changes policy for draft.
- If PR is draft, skip commit message check
- If PR is changed from draft to ready-for-review, check commit message
> [infra] Ignore commit message check on draft

- runtime/onert/core/include/compiler/LoweredGraph.h
This commit adds comment why lowering uses graph copy.
> [onert] Add comment about graph copy on lowering

- runtime/onert/api/src/nnfw_api_internal.h
This commit removes tracing_ctx member in nnfw_session.
---
Related issue: https://github.com/Samsung/ONE/issues/9281
Draft: https://github.com/Samsung/ONE/pull/9280
> [onert] Remove unused member in nnfw_session

- runtime/onert/core/include/ir/Index.h
- $ubgraph should be Subgraph.
- It seems not much meaningful comment. Let's remove it.
> [onert/ir] Remove a typo in comment

- runtime/onert/core/src/interp/InterpExecutor.h
This commit updates interpreter to use copy of graph, not original graph reference.
Sometimes interpreter executor cannot refer original graph.
---
This PR is previous commit for #9308
> [onert] Use copy of graph in interpreter

- runtime/onert/core/include/util/TracingCtx.h
- runtime/onert/core/src/compiler/Compiler.cc
This commit updates TracingCtx constructor.
It removes graph set parameter, and create empty graph to index map.
Current constructor get original graph set as constructor's parameter.
But original graph is not used for tracing because executor can't refer original graph.
Tracing observer uses copied graph on lowering.
> [onert] Revisit TracingCtx constructor

- infra/nnfw/cmake/ApplyCompileFlags.cmake
- infra/nnfw/cmake/buildtool/config/config_aarch64-android.cmake
- infra/nnfw/cmake/buildtool/config/config_linux.cmake
- infra/nnfw/cmake/buildtool/config/config_x86_64-darwin.cmake
Instead of using old convention - linking pthread (`-lpthread`), let's use compiler build option (`-pthread`) by using cmake FindThread.
> [infra] Change using pthread option

- compiler/one-cmds/onecc
- compiler/one-cmds/onecc.template.cfg
- compiler/one-cmds/tests/onecc_027.cfg
- compiler/one-cmds/tests/onecc_027.test
This commit adds infer option to onecc.
Add, it contains test cases of onecc.
> [one-cmds] Add infer option to onecc

- runtime/onert/core/include/ir/Graph.h
- runtime/onert/core/src/compiler/Compiler.cc
- runtime/onert/core/src/compiler/ShapeValidator.cc
- runtime/onert/core/src/interp/InterpExecutor.test.cc
This commit removes model reference field in graph.
> [onert] Remove model reference in graph

- compiler/one-cmds/tests/onecc_neg_012.cfg
- compiler/one-cmds/tests/onecc_neg_012.test
This commit adds negative test for one-infer option in onecc
---
from: 
@yunjayh , in anotehr PR, please add negative test to check mutual exclusiveness is working as expected.
_Originally posted by @seanshpark in https://github.com/Samsung/ONE/pull/9321#issuecomment-1163886035_
> [one-cmds] Add negative test for onecc

- compiler/one-cmds/tests/onecc_neg_011.test
This commit adds exit code 255 to negative test.
---
from: 
I think `onecc_neg_011.test` needs also fix. if possible can you fix `onecc_neg_011.test` too ? (in another PR)
_Originally posted by @seanshpark in https://github.com/Samsung/ONE/pull/9324#discussion_r904671191_
> [one-cmds] Add exit code to test

- compiler/luci/partition/src/PartitionIR.cpp
- compiler/luci/partition/src/PartitionMerge.cpp
- compiler/luci/partition/src/PartitionPGroups.cpp
- compiler/luci/partition/src/PartitionPModules.cpp
- compiler/luci/pass/src/QuantizationUtils.cpp
This removes return with std::move(...) for local unique pointer.
It needs on old compiler version, but we don't use old compiler any more.
---
Same with https://github.com/Samsung/ONE/pull/9329
Draft: https://github.com/Samsung/ONE/pull/9245
> [luci] Remove return with std::move

- compiler/coco/core/src/IR/Module.cpp
- compiler/coco/generic/src/IR/Data.cpp
This commit removes return with std::move(...) for local unique pointer.
It needs on old compiler version, but we don't need this any more because we are using c++14 feature.
---
Draft: #9245
> [coco] Remove return with std::move

- compiler/enco/core/src/CppGen/Host.cpp
- compiler/enco/core/src/CppGen/Subnet.cpp
- compiler/enco/core/src/Transforms/Split.cpp
This removes return with std::move(...) for local unique pointer.
It needs on old compiler version, but we don't use old compiler any more.
---
Same with #9329 
Draft: https://github.com/Samsung/ONE/pull/9245
> [enco] Remove return with std::move

- compiler/moco/import/src/Importer.cpp
This removes return with std::move(...) for local unique pointer.
It needs on old compiler version, but we don't use old compiler any more.
---
Same with https://github.com/Samsung/ONE/pull/9329
Draft: https://github.com/Samsung/ONE/pull/9245
> [moco] Remove return with std::move

- infra/nnfw/cmake/CfgOptionFlags.cmake
- infra/nnfw/cmake/packages/ARMComputeConfig.cmake
This commit changes default ACL build type to release. If developer want to build debug type, set `DEBUG_ARMCOMPUTE=ON` on configure.
---
Related issue:  #9085
> [infra/onert] Set default ACL build type to release

- runtime/onert/api/src/nnfw_api_internal.cc
- runtime/onert/core/include/compiler/Compiler.h
- runtime/onert/core/src/compiler/Compiler.cc
- runtime/onert/core/src/compiler/HEScheduler.test.cc
- runtime/onert/core/src/exec/Execution.test.cc
- runtime/onert/frontend/nnapi/wrapper/ANeuralNetworksCompilation.cc
CompilerOptions(Model&) looks like it creates CompilerOptions using
Model. But it may be misleading. CompilerOptions is created from GlobalConfig values.
The parameter(Model&) is only used during ManualScheduler option validation.
`Model` is not stored in CompilerOptions at all also.
I would like to make it clear CompilerOptions are created using
GlobalConfig.
Draft: #9334
> [onert] Rename CompilerOptions(Model&) to fromGlobalConfig(Model&)

- runtime/onert/api/src/nnfw_api_internal.cc
- runtime/onert/core/include/compiler/Compiler.h
- runtime/onert/core/src/compiler/Compiler.cc
- runtime/onert/core/src/compiler/HEScheduler.test.cc
- runtime/onert/core/src/exec/Execution.test.cc
- runtime/onert/frontend/nnapi/wrapper/ANeuralNetworksCompilation.cc
It removes model parameter from ManualSchedulerOptions::setBackendMap
since model is only used to check the existence of operation index,
and same check is done during execution also.
After removing parameter from ManualSchedulerOptions, at last,
CompilerOptions::fromGlobalConfig() can kick off model parameter.
Please see 2nd commit only, the 1st commit is to be merged in #9337.
#9337 has to be landed first.
Related: #9328
> [onert] Remove model from ManualSchedulerOptions::setBackendMap

- runtime/onert/api/src/nnfw_api_internal.cc
CompilerOptions construction may throw exceptions (bad_alloc, out_of_range, ...).
Let's move all load statements into try block.
Related: #9328, https://github.com/Samsung/ONE/pull/9334/files#r905917895
> [onert/api] create CompilerOptions in try block

- compiler/circle-operator/src/Dump.cpp
This will revise multi output tensor to dump first output.
- this is to fix as node is single object
- add todo for if there is other cases
> [circle-operator] Revise multi output tensor

- runtime/onert/api/src/nnfw_api_internal.cc
load_model_from_modelfile() assumes that its model file will end with
either `.circle` or `.tflite`. It get its extension by getting last 7
characters. But it would be more generatl to find extension by last dot.
Related: https://github.com/Samsung/ONE/pull/9244#discussion_r896447982
I tested this change by running `tflite_comparator 1.tvn`.
Sure, it only succeeds to run `1.tvn`, and fails whille trying `1.tvn` with tflite interpreter. : )
But I confirmed this change works by seeing trix emulator's run log.
> [onert/api] Get file extension by searching ., not by fixed length

- runtime/onert/core/src/compiler/Compiler.cc
- runtime/onert/core/src/dumper/dot/DotDumper.cc
- runtime/onert/core/src/dumper/dot/DotDumper.h
This commit refines DotDumper.
- Seperate the method `dump()` of `DotDumper`
- Remove class members that might cause the problems with c++ lifetime
> [onert] Refine DotDumper

- runtime/onert/api/src/nnfw_api.cc
- runtime/onert/api/src/nnfw_api_internal.cc
- runtime/onert/api/src/nnfw_api_internal.h
This commit revisits session creation.
It introduces factory method for `nnfw_session`. Factory method handles different exception type and return different status.
To prevent using constructor directly, `nnfw_session`'s constructor is changed to private.
To initialize on session creation, `_coption` and `_kernel_registry` initialization is moved into factory method.
---
Related issue: https://github.com/Samsung/ONE/pull/9335#discussion_r906899854
> [onert] Revisit session creation

- runtime/onert/core/src/dumper/dot/DotDumper.cc
This commit removes an unused local variable from DotDumper.
> [onert] Remove an unused local variable

- compiler/circle-operator-test/src/circle-operator.test.cpp
This will remove test for both options as both options will be valid.
> [CirOpTest] remove test for both options

- compiler/circle-operator/README.md
This will fix README typo with argument.
> [circle-operator] Fix README typo

- compiler/one-cmds/one-prepare-venv
This will add torch install URL message for debugging for redirecting server.
- this will be removed after tracing is finished.
> [one-cmds] Add torch URL message

- runtime/onert/core/src/compiler/ShapeValidator.cc
- runtime/onert/core/src/compiler/ShapeValidator.h
This commit refines ShapeValidator.
- Remove unnecessary members
- Add deleted copy & move constructors to avoid copying or moving of ShapeValidator
> [onert] Refine ShapeValidator

- compiler/luci/pass/src/QuantizeBias.cpp
- compiler/luci/pass/src/QuantizeBias.test.cpp
This sets quantized dimension of CWQ bias.
- Test was added to check quantized_dimension is correct
> [luci] Set quantized dimension of CWQ bias

- infra/command/format
This commit fixes format checker to include `*.py` files in `one-cmds`
directory and few `one-cmds` scripts which are based on python.
---
This pr changes formatter script, and it might break CI until #9353 is merged. 
for: #9351 
draft: #9352
> Fix format checker for python

- compiler/one-cmds/one-infer
- compiler/one-cmds/tests/CMakeLists.txt
- compiler/one-cmds/tests/one-infer-test-post-process.py
- compiler/one-cmds/tests/one-infer_006.test
- compiler/one-cmds/tests/one-infer_neg_005.test
This commit adds `post-process` option to `one-infer` which will execute
given command after running backend driver inference.
---
draft: #9295
> [one-cmds] Introduce `post-process` option to `one-infer`

- compiler/one-cmds/one-infer
This commit fixes one-infer help message to clarify
its mutually exclusive options.
> [one-cmds] Fix one-infer help message

- compiler/one-cmds/tests/CMakeLists.txt
This commit renames wrong variables.
Related: https://github.com/Samsung/ONE/issues/9370#issuecomment-1171937926
> [one-cmds] Rename wrong variables

- runtime/onert/api/src/nnfw_api_internal.cc
- runtime/onert/api/src/nnfw_api_internal.h
nnfw_session has a container of CompilerOptions because it may have
multiple CompilerOptions if nnpkg has multiple models.
Draft: https://github.com/Samsung/ONE/pull/9292
Related: https://github.com/Samsung/ONE/issues/9206
> [onert/api] nnfw_session may have multiple CompilerOptions

- runtime/onert/api/src/nnfw_api_internal.cc
- runtime/onert/api/src/nnfw_api_internal.h
It uses NNPkg instead of Model to be ready for multiple models.
Draft: #9292
Related: #9206
> [onert/api] Use NNPkg in api internal

- runtime/onert/core/include/backend/ITensor.h
- runtime/onert/core/include/ir/Layout.h
- runtime/onert/core/include/util/CalculateActivationRange.h
From #9265
This commit fixes build fails on gcc-11.
- gcc-10: Some C++ Standard Library headers have been changed to no longer include the `<stdexcept>` header.
- gcc-11: Some C++ Standard Library headers have been changed to no longer include the `<limits>` header.
> [onert] Fix build fails on gcc-11

- runtime/onert/core/include/ir/NNPkg.h
pkg-inputs, pkg-outputs and model_edges are added.
> [onert/ir] Add fields for model connection and nnpkg IO in NNPkg

- runtime/onert/api/src/nnfw_api_internal.cc
It reads pkg-inputs, pkg-outputs and model-connects from nnpkg MANIFEST.
During backend implementation, internal structure for model-connects may
be changed.
Draft: https://github.com/Samsung/ONE/pull/9292
Related: https://github.com/Samsung/ONE/issues/9206
> [onert/api] Read pkg-inputs, pkg-outputs and model-connects

- compute/cker/include/cker/CpuBackendThreadpool.h
Related to #9265
This commit adds checking ruy::Context pointer to make gcc11 happy.
> [onert/cker] Check ruy::Context pointer to make gcc11 happy

- compute/ARMComputeEx/CMakeLists.txt
- packaging/nnfw.spec
Let's use python3 explicitly on ArmComputeEx build process.
> [ArmComputeEx] Use python3 explicitly

- compiler/luci-interpreter/src/loader/GraphLoader.cpp
This improves error message for unsupported custom op.
> [luci-interpreter] Improve error message for custom op

- runtime/onert/core/include/compiler/StaticShapeInferer.h
- runtime/onert/core/src/compiler/Compiler.cc
- runtime/onert/core/src/compiler/StaticShapeInferer.cc
- tests/nnfw_api/src/one_op_tests/While.test.cc
This commit refines StaticShapeInferer.
- Change StaticShapeInferer so that a StaticShapeInferer is assigned to each subgraph
- Add observers to call StaticShapeInferers recursively
> [onert] Refine StaticShapeinferer

- compiler/one-cmds/one-import-onnx
- compiler/one-cmds/onelib/make_cmd.py
- compiler/tf2tfliteV2/tf2tfliteV2.py
This will add experimental disable_batchmatmul_unfold option to
tf2tfliteV2 and one-import-onnx to support ONNX models having BatMatMul Ops.
> [one-cmds] Experimental disable_batchmatmul_unfold option

- runtime/onert/core/src/compiler/ExecutorFactory.cc
- runtime/onert/core/src/compiler/Fp32ToFp16Converter.cc
This commit changes unnecessary copies to use references.
> [onert] Change unnecessary copies to use references

- compiler/one-cmds/tests/one-optimize_001.test
- compiler/one-cmds/tests/one-optimize_002.test
- compiler/one-cmds/tests/one-optimize_neg_001.test
- compiler/one-cmds/tests/one-optimize_neg_002.test
- compiler/one-cmds/tests/one-optimize_neg_003.test
- compiler/one-cmds/tests/one-optimize_neg_004.test
This will revise not to use --O1 option and instead use --resolve_customop_add
for one-optimize test.
> [one-cmds] Do not use --O1 for one-optimize test

- compiler/luci/pass/include/luci/CircleOptimizer.h
- compiler/luci/pass/include/luci/Pass/ResolveCustomOpSplitVPass.h
- compiler/luci/pass/src/CircleOptimizer.cpp
- compiler/luci/pass/src/ResolveCustomOpSplitVPass.cpp
- compiler/luci/pass/src/ResolveCustomOpSplitVPass.test.cpp
This adds ResolveCustomOpSplitV pass and its tests.
---
Related to: https://github.com/Samsung/ONE/issues/9400
Draft PR: #9408
> [luci] Add ResolveCustomOpSplitV pass

- compiler/common-artifacts/CMakeLists.txt
This will revise not to use --O1 option and instead use --resolve_customop_add
for generating optimized circle with circle2circle.
> [cmn-arts] Do not use --O1

- compiler/circle2circle/src/Circle2Circle.cpp
This adds a ResolveCustomOpSplitV option.
---
Related to: https://github.com/Samsung/ONE/issues/9400
Draft PR: https://github.com/Samsung/ONE/pull/9408
> [circle2circle] Add ResolveCustomOpSplitV option

- runtime/onert/api/src/nnfw_api_internal.cc
- runtime/onert/core/include/ir/Graph.h
- runtime/onert/core/src/ir/Graph.cc
This commit adds explicit keyword to Graph default constructor and copy constructor to prevent unexpected copy.
> [onert] Add explicit keyword to Graph constructor

- compiler/one-cmds/onelib/constant.py
This enables a ResolveCustomOpSplitV option.
---
Related to: https://github.com/Samsung/ONE/issues/9400
Draft PR: https://github.com/Samsung/ONE/pull/9408
> [one-cmds] Support ResolveCustomOpSplitV option

- compiler/common-artifacts/CMakeLists.txt
This will add environment to enable pip install with trusted-host option.
- this is needed when behind proxy with self certificate
> [cmn-arts] Add option to enable pip trusted-host

- compiler/luci/pass/src/CircleOptimizer.cpp
This resolves custom Ops before nchw-to-nhwc conversion.
> [luci] Resolve custom Ops before nchw-to-nhwc conversion

- compiler/one-cmds/one-prepare-venv
This will fix PIP_OPTIONS to include also pypi.python.org for trusted-host.
and fix patch for protobuf==3.20.1 to use PIP_OPTIONS too.
> [one-cmds] Fix PIP_OPTIONS

- compiler/one-cmds/how-to-use-one-commands.txt
- compiler/one-cmds/onelib/constant.py
This will remove --O1 option from optimization list.
> [one-cmds] Remove --O1 option

- compiler/one-cmds/tests/one-import-onnx_002.test
- compiler/one-cmds/tests/prepare_test_materials.sh
This will add tests for 'experimental_disable_batchmatmul_unfold' option
with one-import-onnx tool.
> [one-cmds] Test for experimental_disable_batchmatmul_unfold

- compiler/one-cmds/tests/one-import-onnx_002.test
This will fix one-import-onnx_002.test to use circle-operator.
- circle-inspect tool is not a installed tool thus cannot use here
> [one-cmds] Fix one-import-onnx_002.test failure

- infra/packaging/res/tf2nnpkg.20220323
This commit changes usage of deprecated circle2circle --O1 option to --resolve_customop_add in tf2nnpkg.
> [infra] Change deprecated --O1 option

- compiler/one-cmds/dummy-driver/CMakeLists.txt
This commit adds lost file extension `cpp`.
> [one-cmds] Fix file name typo

- compiler/record-minmax/include/RecordFunction.h
- compiler/record-minmax/src/MinMaxObserver.cpp
> [record-minmax] Make gcc-11 happy

- compiler/luci-interpreter/src/kernels/MirrorPad.cpp
- compiler/luci-interpreter/src/kernels/Pad.cpp
- compiler/luci-interpreter/src/kernels/PadV2.cpp
> [luci-interpreter] Make gcc-11 happy.

- compiler/circle-eval-diff/src/MetricPrinter.cpp
> [circle-eval-diff] Make gcc-11 happy

- compiler/luci/pass/src/FoldSparseToDensePass.cpp
- compiler/luci/pass/src/PropagateQParamBackwardPass.cpp
- compiler/luci/pass/src/QuantizationUtils.cpp
- compiler/luci/pass/src/QuantizeBias.cpp
- compiler/luci/pass/src/QuantizeDequantizeWeightsPass.cpp
- compiler/luci/pass/src/QuantizeWeights.cpp
> [luci] Make gcc-11 happy

- compiler/kuma/src/IntervalSet.h
- Fix an error that ‘uint32_t’ is defined in header
> [kuma] Make gcc-11 happy

- compiler/moco/lang/src/IR/TFNode.cpp
> [moco] Make gcc-11 happy

- infra/nncc/CMakeLists.txt
From https://github.com/Samsung/ONE/issues/9432#issuecomment-1184412692
This commit updates cmake minimum requirement version to 3.3.
> [infra/compiler] Update cmake minimum requirement version to 3.3

- compiler/common-artifacts/CMakeLists.txt
This will remove preparation of python virtual environment with
TensorFlow 2.6.0, 'venv_2_6_0'.
> [common-artifacts] Remove prepare venv_2_6_0

- infra/scripts/docker_build_test_x64.sh
This commit updates x64 runtime build script to pass build option on CI.
---
This option was introduced by #8845 but removed by #9022 by mistake.
> [infra] Fix build option on x64 runtime build

- compiler/one-cmds/onelib/constant.py
This adds replace_sub_with_add into constant.py,
which was omitted by mistake when creating constant.py.
> [one-cmds] Add replace_sub_with_add into constant.py

- compiler/record-minmax/src/MinMaxObserver.cpp
This prints node name if tensor dtype is not float.
> [record-minmax] Improve error message

- compiler/luci/pass/src/ConvertNCHWToNHWCPass.cpp
This removes dead code from ConvertNCHWToNHWCPass.cpp.
> [luci] Tidy ConvertNCHWToNHWCPass.cpp

- compiler/luci/service/src/ShapeInfer_StridedSlice.cpp
This will tidy unused codes of shape inference for StridedSlice.
> [luci/svc] Tidy shape inference for StridedSlice

- compiler/luci/service/src/ShapeInfer_StridedSlice.cpp
This will fix StridedSliceParams to initialize where StridedSliceContext
uses but does not, to make analysis tool happy.
> [luci/svc] Make analysis tool happy

- res/TensorFlowLiteRecipes/Net_TConv_BN_003/test.recipe
- res/TensorFlowLiteRecipes/Net_TConv_BN_003/test.rule
- res/TensorFlowLiteRecipes/Net_TConv_BN_004/test.recipe
- res/TensorFlowLiteRecipes/Net_TConv_BN_004/test.rule
This will introduce two TransposeConv model with bias.
- 003 is based on 002 shape with rank 1 bias
- 004 has differnt shape with rank 4 bias
> [res] TConv with bias recipes

- res/TensorFlowLiteRecipes/Net_TConv_Add_000/test.recipe
- res/TensorFlowLiteRecipes/Net_TConv_Add_001/test.recipe
- res/TensorFlowLiteRecipes/Net_TConv_Add_002/test.recipe
- res/TensorFlowLiteRecipes/Net_TConv_BN_000/test.recipe
- res/TensorFlowLiteRecipes/Net_TConv_BN_001/test.recipe
- res/TensorFlowLiteRecipes/Net_TConv_BN_002/test.recipe
This will tidy unnecessary fields in Net_TConv_* recipes.
> [res] Tidy Net_TConv recipes

- runtime/onert/backend/cpu/KernelGenerator.cc
- runtime/onert/backend/ruy/KernelGenerator.cc
- runtime/onert/backend/xnnpack/KernelGenerator.cc
- runtime/onert/core/include/exec/FunctionSequence.h
- runtime/onert/core/src/backend/builtin/KernelGenerator.cc
- runtime/onert/core/src/exec/FunctionSequence.cc
DynamicTensorCtx doesn't need operations and op_idx.
An operator itself is enough.
> [onert] Tidy DynamicTensorCtx

- compiler/luci-interpreter/src/kernels/StridedSlice.cpp
This PR adds StridedSlice execute for S32 input in luci-interpreter.
from draft: https://github.com/Samsung/ONE/pull/9253
for issue https://github.com/Samsung/ONE/issues/9225
> [luci-interpreter] Add StridedSlice execute for S32 input

- compiler/one-cmds/one-init
- compiler/one-cmds/utils.py
This adds args list for one-init.
- Currently tflite and onnx models are supported.
- `-C config_file` and `-S section` are not args for one-init. So, they are excluded.
parent issue: https://github.com/Samsung/ONE/issues/9450
draft: https://github.com/Samsung/ONE/pull/9421
> [one-cmds] Add args list for one-init

- compiler/tflite2circle/src/CircleModel.cpp
This will fix to convert old tflite with opcode being 0.
> [tflite2circle] Convert old tflite with opcode

- compiler/tflite2circle/src/BuildBuiltinOptions/MaximumMinimumOptions.cpp
This will tidy MaximumMinimumOptions with unused variable.
> [tflite2circle] Tidy MaximumMinimumOptions

- compiler/luci/logex/src/CircleNodeSummaryBuilders.cpp
- compiler/luci/logex/src/CircleNodeSummaryBuilders.h
This will revise CircleConstSummaryBuilder to show dtype and shape for
CircleConst node.
> [luci/logex] Revise CircleConst

- tests/tools/tflite_vanilla_run/CMakeLists.txt
This commit resolves build fail by boost program_option linking bug.
> [tools] Fix tflite_vanilla_run

- compiler/luci/pass/src/QuantizedModelVerifier.test.cpp
- compiler/luci/pass/src/VerifyQuantizedNodeGranularity.h
- compiler/luci/pass/src/VerifyQuantizedNodeType.cpp
- compiler/luci/pass/src/VerifyQuantizedNodeType.h
This verifies quantization of ReduceMax Op.
---
Related to: https://github.com/Samsung/ONE/issues/9458
> [luci] Verify quantization of ReduceMax

- compiler/one-cmds/one-init
This adds `_verify_arg()` of `one-init`, which verifies args of `one-init`.
parent issue: https://github.com/Samsung/ONE/issues/9450
draft: https://github.com/Samsung/ONE/pull/9421
> [one-cmds] Add _verify_arg of one-init

- compiler/loco/include/loco/IR/DataTypeTraits.h
This will introduce FLOAT16 data type.
> [loco] Introduce FLOAT16 data type

- compiler/souschef/include/souschef/Data/Gaussian.h
- compiler/souschef/src/Gaussian.cpp
This will enable guaussian data chef of float16 type.
> [souschef] Enable guaussian data chef of float16

- compiler/tflchef/core/src/Convert.cpp
- compiler/tflchef/core/src/DataChef.def
- compiler/tflchef/core/src/ModelChef.cpp
- compiler/tflchef/proto/tflchef.proto
- compiler/tflchef/tflite/src/Convert.cpp
This will support limited FLOAT16 with tensor.
> [tflchef] Support limited FLOAT16

- compiler/luci/import/src/Nodes/CircleConst.cpp
- compiler/luci/lang/src/Nodes/CircleConst.cpp
This will support limited FLOAT16 with FLOAT16 CircleConst.
> [luci] Support FLOAT16 CircleConst

- compiler/luci/pass/src/ConvertToFakeQuantizedModelPass.cpp
This supports fake quantization of ReduceMax.
---
Related to: https://github.com/Samsung/ONE/issues/9458
> [luci] Support fake quantization of ReduceMax Op

- compiler/one-cmds/one-init
This adds early version of _generate() into one-init.
- introduce functions to construct cfg file
- introduce class handling cfg where comment can be stored.
Why comment is important?
cfg file will be used by human. Therefore we'd better leave human-readable description inside cfg for them to fix cfg
in easier way.
For example, we can make cfg like the following:
```
[one-optimize]
; onnx only option
convert_nchw_to_nhwc = True
; add more option below
```
parent issue: https://github.com/Samsung/ONE/issues/9450
draft: https://github.com/Samsung/ONE/pull/9421
> [one-cmds] Adds early version of _generate() into one-init

- compiler/luci/export/src/CircleTensorExporter.cpp
This will add a comment why FLOAT16 tensor is not exported.
> [luci/export] Comment for FLOAT16

- compiler/luci/pass/src/ConvertToFakeQuantizedModelPass.cpp
This supports fake quantization of more Ops
- StridedSlice, Sqrt, RSqrt, Div, LogSoftmax, Cast,
SplitV, ArgMax, Gather
> [luci] Support fake quantization of more Ops

- compiler/luci/pass/src/FoldDequantizePass.cpp
This will revise FoldDequantizePass to support FLOAT16 type.
> [luci] Revise FoldDequantizePass to support FLOAT16

- compiler/luci-pass-value-test/test.lst
This will add Net_Dequantize_Add_000 test with fold_dequantize option.
> [luci/pass-value-test] Test for Net_Dequantize_Add_000

- compiler/souschef/src/Gaussian.cpp
This uses numeric_limits::lowest for min cap.
> [souschef] Use numeric_limits::lowest for min cap

- compiler/luci/service/src/CircleShapeInferenceRule.cpp
This supports shape inference of ArgMin/Max with negative axis.
> [luci] Support shape inference of ArgMin/Max with negative axis

- res/TensorFlowLiteRecipes/ArgMax_004/test.recipe
This adds recipe for ArgMax with negative axis.
---
Related to: https://github.com/Samsung/ONE/pull/9515
> [res] Add recipe for ArgMax with negative axis

- compiler/one-cmds/one-import-onnx
This will introduce fix_io_order option to adjust I/O names be in order
for one-import-onnx.
> [one-cmds] Introduce fix_io_order option in one-import-onnx

- compiler/one-cmds/one-import-onnx
This will fix one-import-onnx with fix_io_order option
to ignore initializers as inputs.
> [one-cmds] Fix one-import-onnx with fix_io_order

- compiler/one-cmds/one-import-onnx
This will introduce keep_io_order option to replace name of fix_io_order.
> [one-cmds] Add keep_io_order in one-import-onnx

- compiler/circle-eval-diff/driver/Driver.cpp
- compiler/circle-eval-diff/include/CircleEvalDiff.h
- compiler/circle-eval-diff/src/CircleEvalDiff.cpp
- compiler/circle-eval-diff/src/MetricPrinter.cpp
- compiler/circle-eval-diff/src/MetricPrinter.h
- compiler/circle-eval-diff/src/MetricPrinter.test.cpp
This supports MSE printer in circle-eval-diff.
---
Related to: https://github.com/Samsung/ONE/issues/9528
> [circle-eval-diff] Support MSE printer

- compiler/one-cmds/one-quantize
This adds print_mse option in one-quantize.
---
Related to: https://github.com/Samsung/ONE/issues/9528
> [one-cmds] Support print_mse in one-quantize

- compiler/tfldump/src/OpPrinter.cpp
This will add comment for Densify operator
> [tfldump] comment for Densify

- infra/nnfw/config/gbs.conf
This commit removes internal repo definition in gbs.conf.
We will find different way for package sync when version up.
This commit includes clean up gbs.conf file.
> [infra/gbs] Remove gbs.conf internal repo

- compiler/one-cmds/one-import-onnx
This will remove fix_io_order that was replaced with keep_io_order.
> [one-import-onnx] Deprecate fix_io_order

- compiler/luci/service/src/CircleShapeInferenceRule.cpp
- compiler/luci/service/src/CircleTypeInferenceRule.cpp
This will enable shape/dtype inferenece for CircleDensify IR.
> [luci/svc] Shape/dtype inference for Densify

- compiler/souschef/include/souschef/Data/Explicit.h
- compiler/souschef/src/Explicit.cpp
This will enable explict to provide float16 type for filler.
> [souschef] Provide float16 explcit for filler

- compiler/tflchef/core/src/DataChef.def
This will enable explicit data chef for float16 type.
> [tflchef] explicit float16 data chef

- compiler/common-artifacts/exclude.lst
This will add exclude recipes for Densify operator.
> [common-artifacts] Exclude for Densify

- compiler/luci/partition/include/luci/ConnectNode.h
- compiler/luci/partition/src/Nodes/CircleDensify.cpp
- compiler/luci/partition/src/Nodes/CircleDensify.test.cpp
This will enable partitioner to handle CircleDensify operator.
> [luci/part] Enable Densify

- compiler/luci-pass-value-test/test.lst
This will enable Densify and Dequantize tests.
> [luci-pass-value-test] Enable Densify and Dequantize

- runtime/onert/api/include/nnfw.h
It fixes a typo (execeed -> exceed) and a grammar error.
> [onert/api] Fix typos

- runtime/onert/api/src/nnfw_api_internal.cc
- runtime/onert/backend/cpu/ExternalContext.h
- runtime/onert/backend/ruy/ExternalContext.h
- runtime/onert/core/include/util/ConfigSource.h
- runtime/onert/core/src/backend/builtin/ExternalContext.h
- runtime/onert/core/src/util/ConfigSource.cc
This commit moves setConfigKeyValues function from frontend nnfw_api_internal.cc to core ConfigSource.h/cc.
By this, we can hide `config_source` and `config_source_ext` function and header include, so reduce header depdency.
---
Draft: https://github.com/Samsung/ONE/pull/9571
Related issue: https://github.com/Samsung/ONE/issues/9576
> [onert] Move setConfigKeyValues

- runtime/service/npud/util/ConfigSource.cc
- runtime/service/npud/util/ConfigSource.h
This commit removes `_source_ext` and related implementation.
Runtime requires this feature to initialize config in nnpackage, but npud doesn't need this.
---
Draft: #9571
Related issue: #9576
> [npud] Simplify config implementation

- compiler/tflchef/core/src/ModelChef.cpp
This will remove unused fp16 header include.
> [tflchef] Remove unused fp16 header

- compiler/luci/pass/src/FoldDensifyPass.cpp
This will remove unused fp16 library include in FoldDensifyPass.
> [luci/pass] Remove unused fp16 library

- compiler/luci/pass/src/ConvertNCHWToNHWCPass.test.cpp
This commit checks if casted ptr is nullptr.
This is for resolving static analysis tool issue.
> [luci] Check if nullptr after dynamic casting

- runtime/onert/api/CMakeLists.txt
- runtime/onert/backend/cpu/CMakeLists.txt
- runtime/onert/core/CMakeLists.txt
This commit changes nnfw_lib_misc link to onert_core private.
This commit includes explict link to api and cpu backend.
---
Draft: https://github.com/Samsung/ONE/pull/9571
Related issue: https://github.com/Samsung/ONE/issues/9576
> [onert] Change nnfw_lib_misc to private link

- compiler/circle-quantizer/src/CircleQuantizer.cpp
This turns on clang-format in CircleQuantizer.cpp.
> [circle-quantizer] Tidy CircleQuantizer.cpp

- compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
This turns on clang-format in QuantizeWithMinMaxPass.cpp.
> [luci] Tidy QuantizeWithMinMaxPass.cpp

- compiler/luci/pass/src/FuseAddWithFullyConnectedPass.cpp
This reshapes fused_bias in FuseAddWithFullyConnectedPass.
> [luci] Reshape fused_bias in FuseAddWithFullyConnectedPass

- compiler/luci/pass/src/CircleOptimizer.cpp
This performs fuse_add_with_fc earlier than ConvertNCHWToNHWC.
> [luci] Perform fuse_add_with_fc earlier than ConvertNCHWToNHWC

- compiler/luci/pass/include/luci/Pass/RemoveUnnecessaryReshapeNetPass.h
- compiler/luci/pass/src/CircleOptimizer.cpp
- compiler/luci/pass/src/RemoveUnnecessaryReshapeNetPass.cpp
- compiler/luci/pass/src/RemoveUnnecessaryReshapeNetPass.test.cpp
This introduces a RemoveUnnecessaryReshapeNet Pass.
---
Related to: https://github.com/Samsung/ONE/issues/9600
> [luci] Introduce RemoveUnnecessaryReshapeNetPass

- tests/tools/nnpackage_run/src/nnpackage_run.cc
It will show the error message only without boost exception message
when --nnpackage is missing.
```
$ Product/out/bin/nnpackage_run
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::program_options::required_option> >'
what():  the option '--nnpackage' is required but missing
Aborted (core dumped)
```
```
$ Product/out/bin/nnpackage_run
E: the option '--nnpackage' is required but missing
```
> [nnpkg_run] Suppress raw exception message on missing --nnpackage

- compiler/one-cmds/one-init
This adds missing import statement.
parent issue: https://github.com/Samsung/ONE/issues/9450
draft: https://github.com/Samsung/ONE/pull/9421
> [one-init] Add missing import

- tests/scripts/command/nnpkg-test
This commit update nnpkg-test command to support verbose off and fix flag usage bug.
ONE-DCO-1.0-ONE-DCO-1.0-Signed-off-by: Hyeongseok Oh <hseok82.oh@samsung.com>
> [onert/test] Update nnpkg-test command

- runtime/onert/api/src/nnfw_api_internal.cc
- runtime/onert/core/include/ir/NNPkg.h
This commit renames model I/O operand description struct OperandDesc to IODesc because it includes IOIndex.
> [onert] Rename model connect description struct

- compute/cker/include/cker/operation/reference/Conv.h
It is modified based on Conv int8_t kernel in same file.
- Issue #9609
- I will make 3 PRs from Draft #9613. It is the 1st PR of 3.
- Tested on #9613 
```
$ Product/x86_64-linux.debug/out/unittest_standalone/nnfw_api_gtest --gtest_filter=*PerChannel
Note: Google Test filter = *PerChannel
[==========] Running 2 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 2 tests from GenModelTest
[ RUN      ] GenModelTest.OneOp_Conv2D_I8_PerChannel
[       OK ] GenModelTest.OneOp_Conv2D_I8_PerChannel (7 ms)
[ RUN      ] GenModelTest.OneOp_Conv2D_U8_PerChannel
[       OK ] GenModelTest.OneOp_Conv2D_U8_PerChannel (1 ms)
[----------] 2 tests from GenModelTest (9 ms total)
[----------] Global test environment …
```
> [onert] Add Conv2D per-channel Q8u kernel

- compute/cker/include/cker/operation/Conv.h
- compute/cker/include/cker/operation/reference/Conv.h
There are only a few different lines between uint8 and int8.
- Related Issue: #9609
- extra (optional?) PR of after #9613
- Tested on #9613 
Most codes are identical between uint8 and int8 except for the following:
```diff
@@ -1,7 +1,9 @@
inline void Conv(const ConvParams &params, const int32_t *output_multiplier,
-                 const int32_t *output_shift, const Shape &input_shape, const int8_t *input_data,
-                 const Shape &filter_shape, const int8_t *filter_data, const Shape &bias_shape,
-                 const int32_t *bias_data, const Shape &output_shape, int8_t *output_data)
+                 const int32_t *output_shift, const Shape &input_shape, const uint8_t *input_data,
+                 const Shape …
```
> [onert] Use template to reduce duplicated in Conv2d

- compute/cker/include/cker/operation/Conv.h
- runtime/onert/backend/cpu/ops/ConvolutionLayer.cc
- runtime/onert/backend/cpu/ops/ConvolutionLayer.h
- runtime/onert/core/include/ir/TypeInfo.h
- Remove invalid assert of quantization is always per-layer.
- Support Q8 per-channel
- Related Issue: #9609
- 2st PR of 3 from #9613
- Tested on #9613
> [onert] Support conv2d per-channel uint8 quantization

- runtime/onert/core/include/compiler/Compiler.h
- runtime/onert/core/include/ir/NNPkg.h
- runtime/onert/core/src/compiler/Compiler.cc
This commit introduces Compiler constructor for NNPkg and option vector.
For NNPkg compilation, model field is changed to nnpkg field, and option reference field is changed to option pointer vector field.
This commit includes bug fix on NNPkg.h header file.
---
Draft: https://github.com/Samsung/ONE/pull/9616
Related issue: #9610
> [onert] Introduce Compiler contructor for NNPkg

- infra/cmake/packages/NEON2SSESourceConfig.cmake
- infra/nnfw/cmake/packages/TensorFlowLite-1.13.1/TensorFlowLite/CMakeLists.txt
- infra/nnfw/cmake/packages/TensorFlowLite-2.3.0/TensorFlowLite/CMakeLists.txt
This commit updates TensorFlowLite cmake for x64 build to resolve debug build fail by setting flag TF_LITE_DISABLE_X86_NEON.
> [infra/runtime] Set flag for NEON2SSE debug build

- infra/cmake/packages/AbseilConfig.cmake
This commit adds absl::status on abseil library build.
This is used on runtime gpu-cl backend.
---
Related issue: https://github.com/Samsung/ONE/issues/9605#issuecomment-1220338156
Used on header `runtime/onert/backend/gpu_cl/TensorBuilderHelper.h`
> [infra] Add absl::status on abseil library

- compiler/one-cmds/one-init
This removes useless code:
1. remove `_add_from_backend_cfg()`
- Previously, there were two cfg output files:
One was output of one-init, and another was output of backend-init.
In this approach, after bckend-init creates its own cfg,
one-init reads the cfg file of backend-init and write them into the output of one-init. --- (A)
`_add_from_backend_cfg()` was created for (A) and it is now useless.
Now, the changed way works like this:
output cfg of one-init is used as input of backend-init,
and backend-init generates the final output cfg.
2. remove `_gen_profile()`
Let's not handle this at the current version.
Comment at L242 already mentioned this.
3. handling 'command' arg was copied from other file
and not used in one-init.
for https://github.com/Samsung/ONE/issues/9450
draft …
> [one-cmd] Remove useless code from one-init

- runtime/onert/core/include/exec/Executors.h
- runtime/onert/core/src/exec/Execution.cc
- runtime/onert/core/src/exec/Executors.cc
This commit abstracts accessing I/O information and inference on Executors object.
By this change, Execution object does not need to know Executors object comes from multi model or not.
---
Draft: https://github.com/Samsung/ONE/pull/9616
Related issue: https://github.com/Samsung/ONE/issues/9610
> [onert] Abstract accessing I/O info and execute

- runtime/onert/api/src/nnfw_api_internal.cc
- runtime/onert/core/include/exec/Executors.h
- runtime/onert/core/include/ir/NNPkg.h
- runtime/onert/core/src/compiler/Compiler.cc
- runtime/onert/core/src/exec/Executors.cc
This commit introduces Executors constructor for multimodel.
To get edge information, this commit introduces ModelEdge struct and generate and pass on Compiler::compile method.
---
Draft: https://github.com/Samsung/ONE/pull/9616
Related issue: https://github.com/Samsung/ONE/issues/9610
> [onert] Create Executors for multimodel

- runtime/onert/core/include/exec/Executors.h
- runtime/onert/core/src/exec/Executors.cc
This commit updates Executors to support simple multimodel package execution.
---
Draft: https://github.com/Samsung/ONE/pull/9616
Related issue: https://github.com/Samsung/ONE/issues/9610
> [onert] Support simple multimodel package execution

- runtime/onert/core/include/exec/Executors.h
- runtime/onert/core/include/ir/NNPkg.h
- runtime/onert/core/src/compiler/Compiler.cc
This commit moves ModelEdges struct into ir/NNPkg.h and share struct.
---
Related issue: https://github.com/Samsung/ONE/pull/9636#discussion_r957018961
> [onert] Move ModelEdges

- runtime/onert/backend/cpu/ops/DepthwiseConvolutionLayer.cc
- runtime/onert/backend/cpu/ops/DepthwiseConvolutionLayer.h
It is the first step for introducing dconv per-channel uint8 kernel.
> [onert] Renames methods in dconv to more proper names

- tools/nnpackage_tool/gen_golden/gen_golden.py
It changse the default range for float random input.
Previosly, [0, 1) to [-5, 5), which is the same to RecordMinMax.
Related: https://github.com/Samsung/ONE/issues/9609#issuecomment-1227983715
The range for random input depends on each model. As I remember, some model expected the input [0, 1.0).
In spite of this fact, I am trying to use the same one to `RecordMinMax` which is the tool we use to quantize tflite float to circle because I am guessing it is more likely to meet a value test error, and it may be hard to find the reason who is not familiar with our internal tools.
> [nnpkg_tools/gen_golden] Use same range for float random

- runtime/onert/core/include/util/Config.lst
This commit adds trix backend to default backend list.
> [onert] Update default backend list

- runtime/onert/core/src/exec/Executors.cc
This commit updates Executors::executeEntries to support simply partitioned multimodel package execution.
Simply partitioned multimodel package
- Package has two model
- Package's all inputs = 1st model's all inputs (same order)
- Package's all outputs = 2nd model's all outputs (same order)
- 1st model's all outputs = 2nd model's all inputs (same order)
---
Related issue: #9646
> [onert] Support simply partitioned multimodel execution

- runtime/onert/backend/cpu/ops/ConvolutionLayer.cc
It adds `s` to fix a typo in comment.
> [onert] Fix a typo in Convolution layer comment

- tests/nnfw_api/src/one_op_tests/Conv2D.test.cc
It changes the zeropoint for output of uint8 per-channel conv testcase
from negative to [0, 255].
> [onert] Use non-negative zeropoint for conv2d uint8 output

- tests/nnfw_api/src/GenModelTest.h
This commit changes GenModelTest fail message to use "expected" and "actual" for readability.
> [onert/test] Update GenModelTest fail message

- compute/cker/include/cker/operation/DepthwiseConv.h
- compute/cker/include/cker/operation/reference/integer_ops/DepthwiseConvUInt8.h
It introduces DepthwiseConvUInt8.h from tflite/reference/integer_ops
based on TensorFlow lite uint8 reference implementation.
It can handle per-channel quantized q8 weights.
- Parent Issue: #9609 
- It is the 1st PR { compute } of 3 { compute, runtime, testcase } from #9648
- Unit Test passed from #9648 
- MobileNet is tested locally (f32 tflite vs per-channel quantized q8 circle)
> [onert] Introduce dconv per-channel q8 uint kernel

- runtime/onert/core/include/ir/operation/Bulk.h
- runtime/onert/frontend/trix/src/trix_loader.cc
To enable shape inference of Bulk Operation, new fields are added in
Bulk op.
> Add field for Model's IO shapes in Bulk op

- runtime/onert/backend/cpu/ops/DepthwiseConvolutionLayer.cc
- runtime/onert/backend/cpu/ops/DepthwiseConvolutionLayer.h
It makes a way for dconv per-channel uint8 in operation layer.
- Parent Issue: #9609 
- It is the 2nd PR { runtime } of 3 { compute, runtime, testcase } from #9648
> [onert] Support dconv per-channel uint8

- runtime/onert/core/include/compiler/StaticShapeInferer.h
- runtime/onert/core/src/compiler/StaticShapeInferer.cc
Note that Bulk's Static Shape Inferer assumes :
- new input shape has new batch size if it is different from model's
original input shape. Other dimension is not allowed to be changed.
- All new input shapes have the same batch. Thus, it is sufficient to
check 1st input's batch dim.
> StaticShapeInferer for Bulk

- compiler/vconone/CMakeLists.txt
This commit bumps up to 1.22.0.
> [vconone] Bump up to 1.22.0

- compiler/circle-quantizer/src/CircleQuantizer.cpp
argparse is not used anywhere and misleading.
It removes argparse and related comment.
> [circle-quantizer] Remove unused argparse

- compiler/souschef/src/Gaussian.cpp
> [souschef] Add missing header <limits>

- compiler/tf2tflite/src/CustomopConfLoader.cpp
> [tf2tflite] Add missing header <limits>

- compiler/tf2circle/src/CustomopConfLoader.cpp
> [tf2circle] Add missing header <limits>

- compiler/luci-micro/CMakeLists.txt
This PR adds -DTARGET_ARCH variable, fixes EXT_OVERLAY_DIR variable to the correct path to the overlay dir.
issue: #9468
> [luci-micro] Enable luci-micro standalone build

- compiler/circle-execution-plan/src/ExecutionPlanner.cpp
> [circle-execution-plan] Add missing header <limits>

- Makefile.template
- infra/scripts/docker_build_cross_aarch64_runtime.sh
- infra/scripts/docker_build_cross_arm_runtime.sh
- infra/scripts/docker_build_cross_arm_runtime_release.sh
- infra/scripts/docker_build_cross_coverage.sh
- infra/scripts/docker_build_test_x64.sh
This commit cleans up "Makefile.template" used on runtime CI infra.
- Change default target: build -> install
- Remove unused environment variable setting on CI infra
- Rename target for test suite and packaging
- Hide coverage build setting
- Set coverage build when target is coverage test suite
- Remove stamp file for build step
> [infra/runtime] Clean up makefile

- compiler/circle-operator-test/src/circle-operator.test.cpp
This commit fixes typo in class name.
> [circle-operator-test] Fix typo in test class name

- compiler/one-cmds/tests/one-optimize_001.test
- compiler/one-cmds/tests/one-optimize_002.test
- compiler/one-cmds/tests/one-optimize_neg_003.test
- compiler/one-cmds/tests/one-pack_001.test
- compiler/one-cmds/tests/one-quantize_001.test
- compiler/one-cmds/tests/one-quantize_002.test
- compiler/one-cmds/tests/one-quantize_007.test
- compiler/one-cmds/tests/one-quantize_008.test
- compiler/one-cmds/tests/one-quantize_009.test
- compiler/one-cmds/tests/one-quantize_010.test
- compiler/one-cmds/tests/one-quantize_neg_001.test
- compiler/one-cmds/tests/one-quantize_neg_002.test
- compiler/one-cmds/tests/one-quantize_neg_003.test
- compiler/one-cmds/tests/one-quantize_neg_004.test
- compiler/one-cmds/tests/one-quantize_neg_007.test
- compiler/one-cmds/tests/one-quantize_neg_008.test
- compiler/one-cmds/tests/one-quantize_neg_009.test
- compiler/one-cmds/tests/one-quantize_neg_010.test
- compiler/one-cmds/tests/one-quantize_neg_011.test
- compiler/one-cmds/tests/one-quantize_neg_012.test
- compiler/one-cmds/tests/one-quantize_neg_013.test
This will remove unnecessary preparation of inception_v3.circle file as this file is prepared in prepare_test_materials script.
> [one-cmds-tests] Remove unnecessary preparation

- compiler/luci/pass/src/ConvertNCHWToNHWCPass.cpp
- compiler/luci/pass/src/ConvertNCHWToNHWCPass.test.cpp
This supports non-const inputs of Maximum Op in ConvertNCHWToNHWC.
---
Related to: https://github.com/Samsung/ONE/issues/9719
> [luci] Support non-const inputs of Maximum in ConvertNCHWToNHWC

- runtime/onert/core/include/exec/Execution.h
- runtime/onert/core/include/exec/Executors.h
- runtime/onert/core/include/exec/IExecutor.h
- runtime/onert/core/src/backend/builtin/kernel/IfLayer.cc
- runtime/onert/core/src/backend/builtin/kernel/WhileLayer.cc
- runtime/onert/core/src/exec/ExecutorBase.h
- runtime/onert/core/src/interp/InterpExecutor.h
This commit changes Executors::at() return type to simplify usage and avoid missreading about ownership.
This commit includes additional const keyword to resolve compile issue.
---
Draft: #9716
> [onert] Change Executors::at() return type

- compiler/luci/pass/src/ConvertNCHWToNHWCPass.cpp
- compiler/luci/pass/src/ConvertNCHWToNHWCPass.test.cpp
This sets correct inputs for Maximum/Minimum Ops in ConvertNCHWToNHWC.
---
Related to: https://github.com/Samsung/ONE/pull/9729#discussion_r973897656
> [luci] Set correct inputs for Maximum/Minimum in ConvertNCHWToNHWC

- runtime/onert/frontend/base_loader/include/base_loader.h
- tests/scripts/list/tflite_comparator.aarch64.acl_cl.list
- tests/scripts/list/tflite_comparator.aarch64.acl_neon.list
- tests/scripts/list/tflite_comparator.armv7l.acl_cl.list
- tests/scripts/list/tflite_comparator.armv7l.acl_neon.list
This commit updates base loader to support lookup operators (embedding lookup, hashtable lookup). These operators are supported on NNAPI.
---
Draft: #9724
> [onert] Support Lookup operator loading

- compiler/dalgona/CMakeLists.txt
- compiler/dalgona/include/PythonHooks.h
- compiler/dalgona/src/PostOperatorHook.h
- compiler/dalgona/src/PreOperatorHook.h
- compiler/dalgona/src/PythonHooks.cpp
- compiler/dalgona/src/StringUtils.cpp
- compiler/dalgona/src/StringUtils.h
- compiler/dalgona/src/StringUtils.test.cpp
- compiler/dalgona/src/Utils.cpp
- compiler/dalgona/src/Utils.h
This adds pre/post-operator hooks on interpreter.
---
> [dalgona] Add Pre/Post-Operator Hooks

- runtime/onert/backend/acl_common/AclTensorBuilder.h
- runtime/onert/core/include/ir/Shape.h
- runtime/onert/core/src/ir/Shape.cc
- runtime/onert/core/src/ir/Shape.test.cc
- runtime/onert/core/src/util/ShapeInference.cc
This commit changes ir::Shape::MAX_RANK to ir::Shape::ONERT_MAX_RANK to avoid duplicated declaration.
> [onert] Change ir::Shape::MAX_RANK to ir::Shape::ONERT_MAX_RANK

- compiler/circle-interpreter/src/CircleInterpreter.cpp
This commit changes shown error message if given data's size doesn't meet with model's input tensor size.
---
for https://github.com/Samsung/ONE/issues/9634#issuecomment-1248914693
> [circle-interpreter] Show error message if input tensor size mismatches

- compiler/luci-micro/CMakeLists.txt
- compiler/luci-micro/helpers/GenerateKernelsListHelper.cpp
This PR removes arser and foder dependencies from GenerateKernelsListHelper, also makes small refactors.
according to https://github.com/Samsung/ONE/pull/9702#pullrequestreview-1110506802
Note: mio_circle04 dependency will be removed in separate PR
> [luci-micro] Remove arser and foder from GenerateKernelsListHelper

- runtime/onert/core/src/exec/ExecutorBase.cc
- runtime/onert/core/src/exec/ExecutorBase.h
Now, `handleDynamicInputTensor` is used only one place, and it can be done by invoking applyShape directly.
Related: #1714
> [onert] Remove handleDynamicInputTensor

- runtime/onert/core/include/exec/Execution.h
- runtime/onert/core/include/exec/Executors.h
- runtime/onert/core/src/exec/Execution.cc
- runtime/onert/core/src/exec/Executors.cc
- runtime/onert/core/src/interp/InterpExecutor.test.cc
This commit introduce entryExecutor to abstract 1st running executor.
Method executeEntries is renamed to executeModels to avoid confusion.
---
Draft: #9716
> [onert] Introduce entryExecutor

- compiler/one-cmds/tests/onecc_027.cfg
- compiler/one-cmds/tests/onecc_neg_012.cfg
- compiler/one-cmds/tests/onecc_neg_012.test
This fixes onecc infer tests as -b option is removed.
---
Related to: https://github.com/Samsung/ONE/issues/9710
> [one-cmds] Fix onecc infer tests

- compiler/luci-interpreter/src/BuddyMemoryManager.cpp
This commit adds an exception of memroy limit exceeded.
This is for resolving warning of static analysis tool.
Related: https://github.com/Samsung/ONE/pull/7720#discussion_r714474107
> [luci-interpreter] throw error when the memory limit exceeded

- tools/tflitefile_tool/select_operator.py
Related issue : #8747
This commit removes duplicated buffer indices to avoid allocating incorrect buffer indices.
> [tools/tflitefile_tool] Remove duplicated buffer indices

- compiler/dalgona/CMakeLists.txt
This sets visibility option to hidden.
---
Related to: https://github.com/Samsung/ONE/issues/9777
> [dalgona] Suppress warning message

- infra/cmake/packages/GTestConfig.cmake
This prints gtest log only when not found.
> [infra] Suppress gtest log

- docs/howto/how-to-build-compiler.md
This will revise how-to-build-compiler document with package python3.8-venv to install.
> [docs] Revise how-to-build-compiler

- runtime/onert/core/include/exec/Executors.h
- runtime/onert/core/src/compiler/Compiler.cc
- runtime/onert/core/src/exec/Executors.cc
- runtime/onert/core/src/interp/InterpExecutor.test.cc
This commit updates executor map in Executors to use ModelIndex and SubgraphIndex pair as key.
---
Related issue: https://github.com/Samsung/ONE/issues/9713
Draft: https://github.com/Samsung/ONE/pull/9716
> [onert] Use ModelIndex on executor map

- runtime/onert/api/src/nnfw_api_internal.cc
- runtime/onert/core/include/exec/Executors.h
- runtime/onert/core/include/ir/Index.h
- runtime/onert/core/include/util/Index.h
- runtime/onert/core/src/compiler/Compiler.cc
This commit changes ModelIndex value type from uint32_t to uint16_t.
This commit includes updating hash function for ModelIndex-SubgraphIndex pair.
---
Related issue: https://github.com/Samsung/ONE/pull/9791#discussion_r979557008
> [onert] Change ModelIndex value type

- runtime/onert/core/include/exec/Executors.h
- runtime/onert/core/src/backend/builtin/KernelGenerator.cc
- runtime/onert/core/src/backend/builtin/KernelGenerator.h
- runtime/onert/core/src/backend/builtin/kernel/IfLayer.cc
- runtime/onert/core/src/backend/builtin/kernel/IfLayer.h
- runtime/onert/core/src/backend/builtin/kernel/WhileLayer.cc
- runtime/onert/core/src/backend/builtin/kernel/WhileLayer.h
- runtime/onert/core/src/compiler/Compiler.cc
- runtime/onert/core/src/compiler/ExecutorFactory.cc
- runtime/onert/core/src/compiler/ExecutorFactory.h
This commit updates builtin backend to support multiple model on controlflow.
---
Related issue: https://github.com/Samsung/ONE/issues/9713
Draft: https://github.com/Samsung/ONE/pull/9716
> [onert] Support multiple model on builtin backend

- compiler/luci/pass/src/ConvertToFakeQuantizedModelPass.cpp
This uses different names for fake-quantized nodes.
> [luci] Use different name for FQ node

- runtime/onert/core/src/compiler/StaticShapeInferer.cc
This commit changes valid batch size check for bulk operation on static shape inference.
---
For #9670
> [onert] Change Bulk shape inference batch check

- compiler/luci/pass/src/QuantizationUtils.cpp
- compiler/luci/pass/src/QuantizationUtils.h
- compiler/luci/pass/src/QuantizeActivation.cpp
- compiler/luci/pass/src/QuantizedModelVerifier.test.cpp
This quantizes fp32 nodes only.
> [luci] Quantize fp32 nodes only

- tests/nnapi/CMakeLists.txt
- tests/nnapi/include/NeuralNetworksWrapper.h
- tests/nnapi/src/TestNeuralNetworksWrapper.h
This commit removes depdency with boost on NNAPI gtest. To remove depdency, NNAPI gtest build uses c++17.
> [onert/test] Remove boost dependency on NNAPI gtest

- compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
- compiler/luci/pass/src/QuantizedModelVerifier.test.cpp
- compiler/luci/pass/src/VerifyQuantizedNodeGranularity.h
- compiler/luci/pass/src/VerifyQuantizedNodeType.cpp
This skips type/granularity checks for index-typed Add.
---
Related to: https://github.com/Samsung/ONE/issues/9798
> [luci] Skip checks for S32/S64 Add

- compiler/onecc-docker/debian/onecc-docker.install
This commit changes debian file locations to build in root directory.
/cc @Samsung/ootpg_docker
> [onecc-docker] Change debian file locations

- compiler/onecc-docker/debian/rules
This PR corrects a permission error when using onecc-docker after installing onecc-docker debian package.
ONE-DCO-1.0.-Signed-off-by: seunghui-lee hithere1012@naver.com
Related Issue : [#9750]
> [onecc-docker] onecc-docker permission error fix

- runtime/onert/api/src/nnfw_api_internal.cc
- runtime/onert/api/src/nnfw_api_internal.h
- runtime/onert/core/include/ir/NNPkg.h
This commit introduces I/O size getter in nnfw_api_internal.cc and NNPkg.h to reduce code duplication. 
New getters support multimodel and pipeline.
> [onert] Introduce I/O size getter for package

- runtime/onert/core/include/ir/Index.h
- runtime/onert/core/src/compiler/Compiler.cc
- runtime/onert/frontend/base_loader/include/base_loader.h
It changes type for value from uint32 to uint16.
tflite and circle schema define Subgraphs as following:
```
subgraphs:[SubGraph];
```
It can have 2^32 Subgraphs.
But onert assumes the number of subgraph does not exceed 2^16.
We will remove the assumption when we encounter such case.
> [onert] Change SubgraphIndex value type

- compiler/dalgona/src/Dalgona.cpp
This performs cast before doing arithmetic to avoid svace defect.
> [dalgona] Cast before performing arithmetic

- infra/nncc/Makefile.arm32
This will revise Makefile.arm32 to accept BUILD_JOBS for parallel build.
> [nncc] Revise Makefile.arm32 to accept BUILD_JOBS

- onert-micro/standalone/CMakeLists.txt
This PR revisits standalone CMakeLists.txt.
from draft: https://github.com/Samsung/ONE/pull/9836
> [onert-micro] Revisit standalone CMakeLists.txt

- runtime/onert/core/include/exec/Executors.h
- runtime/onert/core/src/exec/Executors.cc
This commit introduces checkSupportedMultimodel() method to split supported multi model check.
> [onert] Split supported multimodel check

- runtime/onert/api/src/nnfw_api_internal.cc
Previously, nnfw_session::create checks only from new nnfw_session(). Now, it covers CustomKernelRegistry and more.
> [onert] nnfw_session::create covers more allocation failures

- infra/onert-micro/CMakeLists.txt
This PR defines TARGET_ARCH, TARGET_CPU and TARGET_CPU options for onert-micro
> [infra/onert-micro] Define build options

- onert-micro/CMakeLists.txt
This PR defines TARGET_ARCH, TARGET_CPU options for onert-micro.
> [onert-micro] Change TARGET_CPU and TARGET_ARCH options

- infra/cmake/modules/IdentifyPlatform.cmake
This PR adds armv7-r TARGET_ARCH to build to support artik 053 board.
> [infra] Add armv7-r TARGET_ARCH

- runtime/onert/core/include/exec/IExecutor.h
IExecutor doesn't need IExecutionObserver in its header.
> [onert] Remove forward declaration IExecutionObserver

- runtime/onert/backend/trix/BatchThreadPool.cc
- runtime/onert/backend/trix/DevContext.cc
- runtime/onert/backend/trix/DevContext.h
For issue https://github.com/Samsung/ONE/issues/9207
Draft PR https://github.com/Samsung/ONE/pull/9667
This commit adds handling of errors that occur within threads of `BatchThreadPool`.
> [onert] Add handling of errors that occur within threads of `BatchThreadPool`

- tests/tools/tflite_run/src/tflite_run.cc
This commit removes NNAPI frontend usage on tflite_run.
---
Related issue: #9864
> [onert] Remove NNAPI usage on tflite_run

- .github/workflows/check-format.yml
- .github/workflows/check-pr-commit.yml
This commit updates github actions workflow to use latest version of the actions. It will resolve warning by node.js 12.
---
Related issue: #9880
> [CI] Update workflow with latest actions version

- docs/howto/how-to-build-compiler.md
This will revise how-to-build-compiler document for ARM32 with prerequsite packages.
> [doc] Revise how-to-build-compiler for ARM32

- infra/command/format
This adds visq to format checker.
---
Related to: https://github.com/Samsung/ONE/issues/9694
Draft PR: https://github.com/Samsung/ONE/pull/9868
> [infra] Add visq to check format

- compiler/luci/pass/src/ConvertToFakeQuantizedModelPass.cpp
This supports SpaceToDepth, DepthToSpace Ops in fake quantization.
---
Related to: https://github.com/Samsung/ONE/issues/9881
Draft PR: https://github.com/Samsung/ONE/pull/9896
> [luci] Support S2D, D2S in fake quantization

- res/TensorFlowLiteRecipes/Quant_DepthToSpace_000/test.recipe
- res/TensorFlowLiteRecipes/Quant_DepthToSpace_000/test.rule
- res/TensorFlowLiteRecipes/Quant_SpaceToDepth_000/test.recipe
- res/TensorFlowLiteRecipes/Quant_SpaceToDepth_000/test.rule
This adds test recipes and rules for SpaceToDepth and DepthToSpace.
---
Related to: https://github.com/Samsung/ONE/issues/9881
Draft PR: https://github.com/Samsung/ONE/pull/9896
> [res] Add S2D, D2S recipes and rules

- compiler/circle-quantizer-dredd-recipe-test/test.lst
This adds SpaceToDepth, DepthToSpace fake quantization tests.
---
Related to: https://github.com/Samsung/ONE/issues/9881
Draft PR: https://github.com/Samsung/ONE/pull/9896
> [circle-quantizer-dredd] Add S2D, D2S fake quant tests

- compiler/circle2circle/src/Circle2Circle.cpp
This adds a forward_transpose_op option.
---
Draft PR: https://github.com/Samsung/ONE/pull/9873
> [circle2circle] Add forward_transpose_op option

- res/TensorFlowPythonExamples/tfpem.py
This will fix Path is not defined error in TensorFlowPythonExamples.
> [res] Fix Path is not defined

- infra/nncc/Makefile.arm32
This commit changes the way removing whispace in Makefile.arm32.
> [onecc] Change the way removing whitespace in Makefile.arm32

- compiler/luci/pass/src/helpers/SparsityFormatConverter.h
This commits adds including `cstddef` to fix the error "'size_t' does not name a type".
> [onecc/luci] Include `cstddef` in SparsityFormatConverter.h

- res/TensorFlowPythonExamples/examples/LSTM_unroll/__init__.py
This will introduce LSTM_unroll in TensorFlowPythonExamples
- LSTM with unroll
- use known(1) batch size
> [res] Introduce LSTM_unroll for TF examples

- infra/nnfw/cmake/packages/TensorFlowLite-2.8.0/TensorFlowLiteConfig.cmake
This commit updates TensorFlowLiteConfig.cmake to use pre-installed TFLite 2.8.0 on Tizen.
---
Draft: #9671
> [infra] Check pre-installed TFLite 2.8.0

- compiler/luci-pass-value-test/test.lst
This adds a test for ForwardTransposeOpPass.
---
Draft PR: https://github.com/Samsung/ONE/pull/9873
> [luci-pass-value-test] Add ForwardTransposeOpPass test

- compiler/one-cmds/onelib/constant.py
This adds forward_transpose_op optimization option.
---
Draft PR: https://github.com/Samsung/ONE/pull/9873
> [one-cmds] Add forward_transpose_op optimization option

- runtime/service/npud/core/Server.cc
This commit remove exception when server is already running or stopped. It returns quietly.
> [npud] Do not throw errors when server is already running or stopped

- compiler/luci/lang/include/luci/IR/Nodes/CircleUnidirectionalSequenceLSTM.h
- compiler/luci/lang/src/Nodes/CircleUnidirectionalSequenceLSTM.test.cpp
This will introduce output_state attribute in CircleUnidirectionalSequenceLSTM to replace activation_state attribute.
> [luci/lang] Introduce output_state for LSTM

- compiler/luci/import/src/Nodes/CircleUnidirectionalSequenceLSTM.cpp
This will fix CircleUnidirectionalSequenceLSTM import with order of inputs.
> [luci/import] Fix import LSTM

- compiler/luci-interpreter/src/kernels/SVDF.cpp
- compiler/luci-interpreter/src/kernels/Utils.cpp
- compiler/luci-interpreter/src/kernels/Utils.h
This will relocate get_tflite_activation method as getTfLiteActivation from SVDF kernel to Utils. Method name is changed to match naming convention of Utils.
> [luci-interpreter] Relocate getTfLiteActivation

- compiler/luci/lang/include/luci/IR/Nodes/CircleUnidirectionalSequenceLSTM.h
This will remove not used anymore activation_state attribute from CircleUnidirectionalSequenceLSTM.
> [luci/lang] Remove activation_state

- tests/scripts/models/run_test.sh
This commit updates run_test.sh to retry download test model when download failed.
---
Maybe help to resolve issue #9934
> [onert/test] Retry test model download

- infra/cmake/modules/IdentifyPlatform.cmake
This PR adds armv8-m TARGET_ARCH to build to support rtl8721csm board for onert-micro.
> [infra] Add armv8-m TARGET_ARCH

- compiler/luci/pass/src/QuantizeWeights.cpp
This quantizes weights on the fly if qparam was not pre-computed.
---
Draft PR: https://github.com/Samsung/ONE/pull/9948
> [luci] Quantize weights on the fly

- compiler/luci-interpreter/src/kernels/UnidirectionalSequenceLSTM.cpp
- compiler/luci-interpreter/src/kernels/UnidirectionalSequenceLSTM.h
This will introduce initial empty UnidirectionalSequenceLSTM kernel.
> [luci-interpreter] Initial UnidirectionalSequenceLSTM kernal

- res/TensorFlowLiteRecipes/Quant_Conv_005/test.recipe
- res/TensorFlowLiteRecipes/Quant_Conv_005/test.rule
- res/TensorFlowLiteRecipes/Quant_Conv_006/test.recipe
- res/TensorFlowLiteRecipes/Quant_Conv_006/test.rule
This adds tests for quantization without QuantizeDequantizeWeights.
---
Related to: https://github.com/Samsung/ONE/pull/9950
> [res] Add test for quant without QuantizeDequantizeWeights

- compiler/circle-quantizer-dredd-recipe-test/CMakeLists.txt
- compiler/circle-quantizer-dredd-recipe-test/test.lst
This adds tests for quantization without QuantizeDequantizeWeights.
---
Draft PR: https://github.com/Samsung/ONE/pull/9948
> [circle-quantizer-dredd-test] Add test for quant without QuantizeDequantizeWeights

- compiler/loco/src/IR/Graph.test.cpp
This will fix unit test not to double destory with a single node object.
> [loco] Fix test not to double destroy with node

- compiler/one-cmds/tests/one-partition_neg_001.test
This will revise one-partition_neg_001.test to check for Debug build.
- debug will throw runtime_error
> [one-cmds] Revise one-partition_neg_001.test

- compute/cker/include/cker/operation/Reduce.h
- tests/scripts/list/tflite_comparator.aarch64.cpu.list
- tests/scripts/list/tflite_comparator.armv7l.cpu.list
- tests/scripts/list/tflite_comparator.x86_64.cpu.list
This commit resolves quantized ReduceSum and ReduceSum kernel  bug.
---
Related issue: #9957
> [compute/cker] Fix Reduce kernel

- compiler/common-artifacts/exclude.lst
This will enable test for UnidirectionalSequenceLSTM_001 as it is now possible to run UnidirectionalSequenceLSTM Op.
- UnidirectionalSequenceLSTM_000 is not enabled this is just for creation of this Op
> [common-artifacts] Enable UnidirectionalSequenceLSTM_001

- compiler/common-artifacts/exclude.lst
This will revise comment for UnidirectionalSequenceLSTM_000 exclusion.
> [common-artifacts] Revise comment for UnidirectionalSequenceLSTM_000

- compiler/luci/import/src/Nodes/CircleUnidirectionalSequenceLSTM.cpp
This will add some empty lines to CircleUnidirectionalSequenceLSTM import for better readability.
> [luci/import] Better readability

- infra/nnfw/cmake/packages/TensorFlowLite-2.8.0/TensorFlowLiteConfig.cmake
This commit updates TensorFlowLiteConfig.cmake for TFLite 2.8 to prevent multiple definition.
> [infra/runtime] Prevent multiple build TFLite 2.8

- runtime/service/npud/core/Server.h
This commit disables copy constructors and assignment operator.
> [npud] Disable copy constructor and assignment operator

- compiler/one-cmds/one-prepare-venv
This will fix trusted host name for files.pythonhosted.org
> [one-cmds] Fix trusted host name

- compiler/circle-execution-plan/pal/TargetPlatform.h
- compiler/circle-execution-plan/src/CircleExecutionPlan.cpp
- compiler/circle-execution-plan/src/ExecutionPlanner.cpp
- compiler/circle-execution-plan/src/ExecutionPlanner.h
This PR adds luci-interpreter runtime.
for issue: https://github.com/Samsung/ONE/issues/9849
draft: https://github.com/Samsung/ONE/pull/9893
> [circle-execution-plan] Add luci-interpreter runtime

- runtime/onert/core/include/compiler/Compiler.h
- runtime/onert/core/src/compiler/Compiler.cc
- runtime/onert/frontend/nnapi/compilation.cc
- runtime/onert/frontend/nnapi/wrapper/ANeuralNetworksCompilation.cc
- runtime/onert/frontend/nnapi/wrapper/ANeuralNetworksCompilation.h
This commit removes compiler state variable setting on Compiler. It is used on NNAPI only, and it can be maintained on frontend.
> [onert] Remove compiler state variable

- runtime/service/npud/core/CMakeLists.txt
- runtime/service/npud/core/Core.cc
- runtime/service/npud/core/DevManager.cc
- runtime/service/npud/core/DynamicLoader.cc
- runtime/service/npud/core/DynamicLoader.h
This commit adds DynamicLoader class.
This class loads a backend library and provides a function to get Backend class in shared library.
Related issue: #12583
> [npud] Add DynamicLoader to load a backend library

- infra/nncc/CMakeLists.txt
- infra/nnfw/CMakeLists.txt
This commit updates compiler and runtime cmake minimum requires. 
It includes removing deprecated comments.
---
Related issues: #10015
> [infra] Update cmake version

- compiler/luci/pass/include/luci/CircleOptimizer.h
- compiler/luci/pass/include/luci/Pass/RemoveDuplicateConstPass.h
- compiler/luci/pass/src/CircleOptimizer.cpp
- compiler/luci/pass/src/RemoveDuplicateConstPass.cpp
- compiler/luci/pass/src/RemoveDuplicateConstPass.test.cpp
This PR adds pass to remove duplicate consts node from model to luci.
for issue: https://github.com/Samsung/ONE/issues/10009
draft: #10008
> [luci/pass] Add RemoveDuplicateConstPass to luci/pass

- compiler/luci-interpreter/src/kernels/UnidirectionalSequenceLSTM.cpp
This will tidy unnecessary pragma that was unintentionally added.
> [luci-interpreter] Tidy unnecessary pragma

- compiler/luci-interpreter/src/kernels/UnidirectionalSequenceLSTM.cpp
This will clear also sp_scratch_buffer values to zero.
> [luci-interpreter] Clear also sp_scratch_buffer

- compiler/luci-interpreter/src/loader/nodes/UnidirectionalSequenceLSTM.cpp
This will fix argument order of creating UnidirectionalSequenceLSTM kernel.
> [luci-interpreter] Fix argument order of UnidirSeqLSTM

- compiler/circle-inspect/driver/Driver.cpp
- compiler/circle-inspect/src/Dump.cpp
- compiler/circle-inspect/src/Dump.h
This PR adds option to dump names of constant tensors.
for issue: #10014
draft: #10008
> [circle-inspect] Dump constant names

- compiler/dredd-rule-lib/rule-lib.sh
This PR adds rule to check constant tensor count.
for issue: https://github.com/Samsung/ONE/issues/10014
draft: https://github.com/Samsung/ONE/pull/10008
> [dredd-rule-lib] Add rule to check constant tensor count

- runtime/service/npud/core/DBus.cc
- runtime/service/npud/core/DBus.h
- runtime/service/npud/org.tizen.npud.xml
This commit adds context_create and context_destroy dbus methods.
Draft PR: https://github.com/Samsung/ONE/pull/9989
> [npud] Add context_create and context_destroy dbus methods

- infra/nnfw/cmake/CfgOptionFlags.cmake
- infra/nnfw/cmake/options/options_aarch64-android.cmake
- infra/nnfw/cmake/options/options_armv7hl-tizen.cmake
- infra/nnfw/cmake/options/options_armv7l-tizen.cmake
- infra/nnfw/cmake/options/options_x86_64-linux.cmake
- infra/nnfw/cmake/options/options_x86_64-tizen.cmake
It is only enabled in arm tizen, x86_64 tizen and linux.
> [npud] Disable Build NPU daemon by default

- runtime/service/npud/backend/trix/TrixBackend.cc
- runtime/service/npud/core/DevManager.cc
- runtime/service/npud/core/DevManager.h
This commit creates and destroys NpuContext in Trix backend.
The DevManager invokes these functions.
Related PR: #10021 
> [npud] Create and destroy NpuContext in Trix backend

- infra/nnfw/cmake/packages/ARMComputeConfig.cmake
This commit resolves build fail on android by checking header files in ARMCompute's  src/ directory.
---
Related issue: #10052
> [infra/runtime] Find ARMCompute header in src

- runtime/service/npud/core/Core.cc
- runtime/service/npud/core/Core.h
- runtime/service/npud/core/DBus.cc
The Core function invokes the dev manager to get npu context and invokes the context manager to create npu daemon context. The npu daemon context internally contains npu context.
> [npud] Implement create and destroy context in core class

- compiler/luci/pass/src/UnrollUnidirectionalSequenceLSTMPass.cpp
This will add assert for input parameter of first_transpose.
> [luci/pass] UnrollLSTM first_transpose assert input

- compiler/luci/pass/src/FuseAddWithFullyConnectedPass.cpp
- compiler/luci/pass/src/FuseAddWithFullyConnectedPass.test.cpp
This prevents Add from being fused with FC with non-const bias.
> [luci] Add guard code to FuseAddWithFullyConnectedPass

- compiler/luci/pass/include/luci/CircleOptimizer.h
- compiler/luci/pass/src/CircleOptimizer.cpp
This will add UnrollUnidirSeqLSTM option to enable UnrollUnidirectionalSequenceLSTMPass.
> [luci/pass] Add UnrollUnidirSeqLSTM option

- compiler/circle2circle/src/Circle2Circle.cpp
This will add unroll_unidirseqlstm option to unroll UnidirectionalSequenceLSTM operator.
> [circle2circle] Add unroll_unidirseqlstm

- infra/nnfw/cmake/options/options_aarch64-tizen.cmake
This commit enables npud build on aarch64 tizen build, like armv7l, armv7hl and x86_64.
> [infra/npud] Enable tizen aarch64 npud build

- compiler/luci-pass-value-test/test.lst
This will add value tests for unroll_unidirseqlstm option.
> [luci-pass-value-test] UnrollLSTM

- infra/nncc/Makefile.arm32
This will disable NEON not to use RUY with ARM32 cross build.
> [infra/nncc] Disable NEON

- runtime/service/npud/core/Core.cc
- runtime/service/npud/core/Core.h
- runtime/service/npud/core/DBus.cc
The Core function checks whether the given context id is valid or not and get the npu context. Then it invokes the dev manager to register and unregister the given model using the npu context.
> [npud] Implement create and destroy network in core class

- runtime/service/npud/backend/trix/TrixBackend.cc
- runtime/service/npud/backend/trix/TrixBackend.h
This commit registers a given model. If the same model is already registered, it shares the model information data.
Each NpuContext has own model list.
> [npud] Implement register and unregister model in Trix backend

- compiler/one-cmds/tests/prepare_test_materials.sh
This will add preparation of UnidirSeqLSTM.tflite test material.
> [one-cmds] prepare UnidirSeqLSTM.tflite

- compiler/mio-tflite280/CMakeLists.txt
This supports ruy in mio-tflite280.
---
Related to: https://github.com/Samsung/ONE/issues/10066
Draft PR: #10081
> [mio-tflite280] Support ruy library

- infra/nncc/cmake/buildtool/config/config_armv7l-linux.cmake
This will move '-ftree-vectorize' option into NEON block.
> [infra/nncc] Relocate tree-vectorize

- compiler/luci-interpreter/pal/cmsisnn/PALBatchToSpaceND.h
- compiler/luci-interpreter/pal/mcu/PALBatchToSpaceND.h
This will fix header include guard typo.
> [luci-interpreter] Fix guard typo

- infra/nncc/Makefile.arm32
This will revise Makefile.arm32 with NEON build ON again.
> [infra/nncc] Revise Makefile.arm32 NEON ON

- runtime/service/npud/core/Signal.cc
This commit removes the SIGSEGV signal handler.
When program segfaults, the Linux kernel will sometimes write a core dump to disk. To use this operation, it does not handle SIGSEGV signal.
> [npud] Do not handle SIGSEGV signal

- runtime/service/npud/core/DynamicLoader.cc
This commit fixes a segfault issue related to the _backend shared_ptr. The _backend shared_ptr must be explicitly deleted before the dynamic library handle is released.
> [npud] Fix segfault issue related to _backend shared pointer

- res/TensorFlowLiteRecipes/Net_FullyConnected_Add_000/test.rule
This adds a dredd test rule for fold_fully_connected.
> [res] Add dredd test rule for fold_fully_connected

- compiler/circle-eval-diff/src/InputDataLoader.cpp
This fixes byte size of directory input.
> [circle-eval-diff] Fix input data size

- onert-micro/luci-interpreter/pal/cmsisnn/PALBatchToSpaceND.h
- onert-micro/luci-interpreter/pal/mcu/PALBatchToSpaceND.h
This will fix header include guard typo.
> [onert-micro] Fix guard typo

- compiler/mio-tflite280/CMakeLists.txt
This will remove mio_tflite280_inc target that has been moved to luci-compute.
> [mio-tflite280] Remove mio_tflite280_inc

- infra/cmake/modules/ExternalSourceTools.cmake
This commit updates CMake ExternalSourceTools to support download server ID and password. 
It will be used on CI infra to use mirror server.
> [infra] Set external source server ID/PWD

- compiler/luci/service/src/Validate.cpp
This will introduce validate_multi_outs method to validate for multi-output nodes.
> [luci/svc] Validate for multi-output nodes

- compiler/luci/service/src/Validate.cpp
This will implement validate_multi_outs method to check multiple output IRs has valid successor type.
> [luci/svc] Implement validate_multi_outs

- infra/cmake/modules/ExternalSourceTools.cmake
This commit fixes invalid variable name in ExternalSourceTools. 
It includes reducing file download implementation.
> [infra] Fix external download tool bug

- runtime/service/npud/core/Core.cc
- runtime/service/npud/core/Core.h
- runtime/service/npud/core/DBus.cc
The Core function invokes the dev manager to create and destroy request. The npu daemon will do the job with a given model id using backend library.
> [npud] Implement create and destroy request in core class

- compiler/loco/include/loco/IR/Graph.h
Make output_nodes helper accept const loco::Graph* instead of loco::Graph*.
Signed-off-by: a.shedko <a.shedko@samsung.com>
> [loco] Refactor output_nodes in IR Graph

- tests/scripts/models/run_test.sh
This commit updates test model download script to use `curl` instaed of `wget`.
> [onert/test] Use curl for test model download

- docs/howto/how-to-build-runtime.md
- docs/howto/how-to-cross-build-runtime-for-arm.md
update how-to-build-runtime related documents.
- update old log in how-to documents 
- add glib2.0 library in build requirements which is needed for npud compile
> [docs] update how-to-build-runtime documents

- packaging/nnfw.spec
- runtime/service/npud/tests/CMakeLists.txt
This commit changes the name and install path of npud gtest.
Related comments: https://github.com/Samsung/ONE/pull/10179#discussion_r1044058190
> [npud] Change install directory of npud gtest

- infra/scripts/test_ubuntu_npud.sh
This commit adds ci test script.
It copies the dbus configuration file to dbus directory and run npud unittiest.
Related pr: #9952
> [infra/npud] Add ci test script

- runtime/service/npud/backend/trix/TrixBackend.cc
- runtime/service/npud/backend/trix/TrixBackend.h
This commit adds NpuContext vector in Trix device. Trix device manages NpuContext when it is created and destroyed.
> [npud] Add NpuContext vector in Trix device

- runtime/service/npud/tests/core/Signal.test.cc
This commit removes segfault test case.
Npud removes the segfault signal handler few days ago. Thus, this test case will cause a real segfault error while running unittest.
Related PR: https://github.com/Samsung/ONE/pull/10107
> [npud] Remove segfault test case

- infra/scripts/test_ubuntu_npud.sh
This commit restarts dbus service to apply npud dbus configuration file before running gtest.
> [npud] Restart dbus service before running gtest

- compiler/luci/pass/src/QuantizeActivation.cpp
- compiler/luci/pass/src/QuantizeActivation.h
- compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
This pr adds support Abs quantization: add QuantizeConstInputActivation and InsertQuantizeOp(for mpq)
for issue: #10185
> [luci/pass] Support Abs quantization

- compiler/luci/pass/src/FuseBatchNormWithTConvPass.cpp
This will add assert check in FuseBatchNormWithTConvPass for Activation is None.
> [luci] Assert check for Activation None

- compiler/luci/service/src/CircleTypeInferenceRule.cpp
This will revise CircleOutputExclude dtype interference to be FLOAT32 when Unknown.
> [luci/svc] Revise OutputExclude dtype inference

- compiler/luci/import/src/GraphBuilder.cpp
- compiler/luci/import/src/GraphBuilderMultiOutput.cpp
- compiler/luci/import/src/Nodes/CircleSVDF.cpp
- compiler/luci/import/src/Nodes/CircleTransposeConv.cpp
- compiler/luci/pass/src/FuseBCQPass.cpp
- compiler/luci/pass/src/ResolveCustomOpMatMulPass.cpp
- compiler/luci/pass/src/UnrollUnidirectionalSequenceLSTMPass.cpp
- compiler/luci/pass/src/UnrollUnidirectionalSequenceLSTMPass.test.cpp
This will tidy dummy dtype settings for OutputExclude nodes.
> [luci] Tidy OutputExclude dtype settings

- compiler/record-minmax/driver/Driver.cpp
- compiler/record-minmax/include/RecordMinMax.h
- compiler/record-minmax/src/RecordMinMax.cpp
This pr revises record-minmax to prepare to using multiple instance of luci-interpreters and observers.
for issue https://github.com/Samsung/ONE/issues/10133
draft: #10132
first step according to https://github.com/Samsung/ONE/pull/10132#discussion_r1034138863
> [record-minmax] Revise to prepare to multiple instance

- runtime/onert/core/include/compiler/Compiler.h
- runtime/onert/core/include/compiler/CompilerOptions.h
- runtime/onert/core/src/compiler/Compiler.cc
- runtime/onert/core/src/compiler/CompilerOptions.cc
- runtime/onert/frontend/nnapi/wrapper/ANeuralNetworksCompilation.cc
This commit revisits CompilerOptions.
- Move class implementation to CompilerOptions.h/cpp
- Move option seting methods into CompilerOptions
- Move enableToFp16 into CompilerOptions
- Introduce forceInternalOptions method
- Move verboseOptions into CompilerOptions
> [onert] Revisit CompilerOptions

- runtime/service/npud/core/DBus.cc
- runtime/service/npud/core/DBus.h
- runtime/service/npud/org.tizen.npud.xml
This commit adds buffers_create and buffers_destroy dbus method. This buffer will be used in set_request_data dbus method.
> [npud] Add buffers_create and buffers_destroy dbus method

- Makefile.template
This commit adds shebang to Makefile.template to help code editor.
> [infra/runtime] Add shebang to Makefile.template

- compiler/common-artifacts/CMakeLists.txt
This commit updates CMakeLitsts.txt to use python model2nnpkg.py. 
Bash script model2nnpkg.sh will be deprecated.
> [common-artifacts] Use python model2nnpkg

- compiler/tf2circle-value-pbtxt-remote-test/CMakeLists.txt
- compiler/tf2circle-value-pbtxt-remote-test/testall.sh
This commit updates CMakeLitsts.txt and testall script to use python model2nnpkg.py. 
Bash script model2nnpkg.sh will be deprecated.
> [tf2circle-value-pbtxt-remote-test] Use python model2nnpkg

- tools/nnpackage_tool/model2nnpkg/model2nnpkg.py
This commit fixes metadata on python script to generate config json array.
---
Related issue: https://github.com/Samsung/ONE/issues/10240#issue-1510528294
> [model2nnpkg] Fix diff between bash and python script

- .ahub/tcchecker-tca/config.yaml
This commit adds npu test directory in TCM runtime configuration.
> [infra] Add npud test in TCM configuration

- infra/scripts/test_ubuntu_npud.sh
- runtime/service/npud/tests/core/DBus.test.cc
This commit adds the test cases below.
- add dbus test case of `context_create` and `context_destroy`.
- add dbus test case of `network_create` and `network_destroy`.
- add dbus test case of `request_create` and `request_destroy`.
This PR requires #10199 PR.
Trix engine does not release the request id. So the user must request to remove the request before terminating. Otherwise, the program will be stuck.
The #10199 PR resolved this issue.
> [npud] Add dbus test case of npud functions

- tools/nnpackage_tool/model2nnpkg/model2nnpkg.py
This commit adds new line at end of output json files.
---
Related issue: https://github.com/Samsung/ONE/issues/10240#issue-1510528294
> [tools/model2nnpkg] Add new line at end of output json files

- compiler/luci/pass/src/ReplaceNonConstFCWithBatchMatMulPass.cpp
- compiler/luci/pass/src/ReplaceNonConstFCWithBatchMatMulPass.test.cpp
This inserts Reshape Op to keep the original shape of FC.
---
Related to: #10241
> [luci] Fix ReplaceNonConstFCWithBatchMatMulPass

- compiler/circle2circle-dredd-recipe-test/test.lst
This adds a FullyConnected_008 test.
---
Related to: https://github.com/Samsung/ONE/issues/10241
> [cir2cir-dredd-recipe-test] Add FullyConnected_008 test

- runtime/onert/core/include/compiler/StaticShapeInferer.h
- runtime/onert/core/src/compiler/Compiler.cc
- runtime/onert/core/src/compiler/StaticShapeInferer.cc
This commit moves static shape infere map creation from Compiler.cc to StaticShapeInferer.cc because it may be reused.
---
Draft: #10004
> [onert] Move static shape inferer map creation

- docs/howto/how-to-build-runtime.md
This commit updates how-to-build-runtime.md 's outdated "Run test" part.
> [doc] Update runtime howto: run test

- compiler/one-cmds/CMakeLists.txt
Let's install model2nnpkg script in one-cmds cmake.
---
Draft: #10235
> [one-cmds] Install model2nnpkg

- runtime/onert/api/src/nnfw_api_internal.cc
- runtime/onert/core/include/compiler/Compiler.h
- runtime/onert/core/include/compiler/CompilerFactory.h
- runtime/onert/core/include/compiler/ICompiler.h
- runtime/onert/core/src/compiler/CompilerFactory.cc
This commit introduces ICompiler and CompilerFactory. 
CompilerFactory is introduced to separate Compiler type with frontend implementation.
---
Draft: #10004
> [onert] Introduce ICompiler and factory

- compiler/one-cmds/one-pack
This commit updates one-pack to use python model2nnpkg.
---
Draft: https://github.com/Samsung/ONE/pull/10235
> [one-cmds] Use python model2nnpkg in one-pack

- compiler/circle-mpqsolver/src/bisection/Quantizer.test.cpp
This adds fusedActivationFunction to resolve #10270.
---
Related to: https://github.com/Samsung/ONE/issues/10270
> [circle-mpqsolver] Add fusedActivationFunction

- infra/doxygen/Doxyfile
This commit updates doxygen config file
- Update project name: nnas -> ONE
- Reduce page size
- Restrict input files
- Exclude test files and README.md on each directory
- Change main page: roadmap.md -> README.md
- Simplify graph generation
- Remove dot path setting: use default
---
Related issue: #10103
> [doxygen] Update doxygen config file

- compiler/one-cmds/CMakeLists.txt
Let's install python model2nnpkg script instead of deprecated bash script for one-pack.
> [one-cmds] Install python model2nnpkg

- runtime/onert/core/src/compiler/MultiModelCompiler.h
This commit fixes inclusion guard `__ONERT_COMPILER_MULTI_MODEL_COMPILER_H__`.
> [onert] Fix inclusion guard typo

- tools/nnpackage_tool/model2nnpkg/model2nnpkg.py
This commit updates model2nnpkg python script exception handling.
- Exit with error code and show exception message, but don't print stack trace
- Fix invalid exception message when model file does not exist
> [model2nnpkg] Handling exception

- runtime/onert/core/include/compiler/ICompiler.h
- runtime/onert/core/include/exec/Execution.h
- runtime/onert/core/include/exec/IExecutors.h
- runtime/onert/core/src/backend/builtin/KernelGenerator.h
- runtime/onert/core/src/backend/builtin/kernel/IfLayer.cc
- runtime/onert/core/src/backend/builtin/kernel/IfLayer.h
- runtime/onert/core/src/backend/builtin/kernel/WhileLayer.cc
- runtime/onert/core/src/backend/builtin/kernel/WhileLayer.h
- runtime/onert/core/src/compiler/Compiler.cc
- runtime/onert/core/src/compiler/ExecutorFactory.cc
- runtime/onert/core/src/compiler/ExecutorFactory.h
- runtime/onert/core/src/compiler/MultiModelCompiler.cc
- runtime/onert/core/src/exec/Execution.cc
- runtime/onert/core/src/exec/Execution.test.cc
- runtime/onert/core/src/exec/ExecutionObservers.h
- runtime/onert/core/src/exec/Executors.cc
- runtime/onert/core/src/exec/Executors.h
- runtime/onert/core/src/interp/InterpExecutor.test.cc
- runtime/onert/frontend/nnapi/execution.cc
- runtime/onert/frontend/nnapi/wrapper/ANeuralNetworksCompilation.h
- runtime/onert/frontend/nnapi/wrapper/ANeuralNetworksExecution.h
This commit introduces IExecutors.
`Executors.h` is moved into `src/` directory, so it is not public header.
---
Draft: #10004
> [onert] Introduce IExecutors

- compiler/one-cmds/one-pack
Python version model2nnpkg requires model input argument "-m".
> [one-cmds] Add model input argument

- infra/packaging/res/tf2nnpkg.20221125
Python version model2nnpkg requires model input argument "-m".
> [infra] Fix tf2nnpkg.20221125

- compiler/dalgona-test/CMakeLists.txt
- compiler/dalgona-test/requires.cmake
This uses pics instead of flatc.
---
Draft PR: https://github.com/Samsung/ONE/pull/10283
Related to: https://github.com/Samsung/ONE/issues/10281
> [dalgona-test] Use pics module

- compiler/visq/CMakeLists.txt
This performs tests in binary tree, instead of source tree.
> [visq] Test in binary tree

- compiler/one-cmds/one-prepare-venv
This installs pydot on venv for visq.
---
Related to: https://github.com/Samsung/ONE/issues/10277
Draft PR: https://github.com/Samsung/ONE/pull/10291
> [one-cmds] Install pydot on onecc venv

- runtime/onert/core/include/ir/NNPkg.h
- runtime/onert/core/src/exec/Executors.cc
This commit makes onert support multi-model based on always `model2 > model1` if edges `model1 -> model2`.
- Use IOTensor instead of IODesc for inputs/outputs executors
- Use sharing buffers instead of moving buffers between executors.
---
For #10002 
Draft #10041
> [onert] Enhance supporting multi-model

- runtime/onert/core/include/exec/IExecutors.h
- runtime/onert/core/src/exec/Executors.cc
- runtime/onert/core/src/exec/Executors.h
This commit updates IExecutors and derivered classes.
- Add override keyword
- Update inputInfo/outputInfo to return reference with method const keyword
> [onert] Revisit IExecutors and derivered

- compiler/record-minmax/CMakeLists.txt
This PR creates record-minmax-for-thread-test target.
for issue https://github.com/Samsung/ONE/issues/10133
from draft: https://github.com/Samsung/ONE/pull/10132
> [record-minmax] Create record-minmax-for-thread-test target

- compiler/record-minmax/CMakeLists.txt
This builds thread test only in 64bit arch.
---
Related https://github.com/Samsung/ONE/issues/10313
> [record-minmax] Build thread test in 64bit arch

- compiler/one-cmds/one-build
- compiler/one-cmds/one-codegen
- compiler/one-cmds/one-import
- compiler/one-cmds/one-import-bcq
- compiler/one-cmds/one-import-onnx
- compiler/one-cmds/one-import-pytorch
- compiler/one-cmds/one-import-tf
- compiler/one-cmds/one-import-tflite
- compiler/one-cmds/one-infer
- compiler/one-cmds/one-init
- compiler/one-cmds/one-optimize
- compiler/one-cmds/one-pack
- compiler/one-cmds/one-partition
- compiler/one-cmds/one-profile
- compiler/one-cmds/one-quantize
- compiler/one-cmds/onecc
- compiler/one-cmds/onelib/CfgRunner.py
- compiler/one-cmds/onelib/Command.py
- compiler/one-cmds/onelib/WorkflowRunner.py
- compiler/one-cmds/onelib/make_cmd.py
- compiler/one-cmds/utils.py
This commit removes first underscore of each functions in utils.py.
Single underscore starting from functions means internal use indicator. But, utils.py's funcitons are not internal use. It better be removed.
Related: #9359
> [one-cmds] Revisit function naming in utils.py

- runtime/onert/core/src/compiler/Compiler.cc
- runtime/onert/core/src/exec/Executors.cc
- runtime/onert/core/src/exec/SingleModelExecutors.cc
- runtime/onert/core/src/exec/SingleModelExecutors.h
- runtime/onert/core/src/interp/InterpExecutor.test.cc
This commit separates implementation file for Executors and SingleModelExecutors.
> [onert] Separate IExecutors derive classes

- runtime/libs/benchmark/src/Phases.cpp
- runtime/libs/profiling/src/profiling/time.cpp
This commit uses `clock_gettime` instead of `gettimeofday`. POSIX.1-2008 marks gettimeofday() as obsolete,
and recommending the use of `clock_gettime` instead. https://man7.org/linux/man-pages/man2/settimeofday.2.html
> [onert] Change the time measurement method

- infra/debian/compiler/one-compiler.install
This commit moves utils.py into onelib dir during installation.
This PR is merged with #10330.
> [debian] Move utils.py into onelib dir

- compiler/one-cmds/onelib/utils.py
This commit fixes the function to get the opt list correctly.
Related: https://github.com/Samsung/ONE/issues/10323#issuecomment-1381113666
> [one-cmds] Get right optimization list

- onert-micro/luci-interpreter/pal/mcu/PALBatchToSpaceND.h
- onert-micro/luci-interpreter/pal/mcu/PALConv2d.h
- onert-micro/luci-interpreter/pal/mcu/PALResizeBilinear.h
- onert-micro/luci-interpreter/pal/mcu/PALResizeNearestNeighbor.h
- onert-micro/luci-interpreter/pal/mcu/PALSoftmax.h
- onert-micro/luci-interpreter/pal/mcu/PALSpaceToBatchND.h
- onert-micro/luci-interpreter/src/kernels/DepthwiseConv2D.cpp
- onert-micro/luci-interpreter/src/kernels/TransposeConv.cpp
- onert-micro/luci-interpreter/src/kernels/Utils.cpp
This PR does some fixing for building on armv8-m: add _t to int types and disable not supported kernels.
> [onert-micro] Fix building on armv8-m

- infra/command/gen-coverage-report
This commit updates coverage report command to update excluded file list because `runtime/onert/backend/gpu_cl/open_cl/` is removed.
> [infra] Update excluded files on coverage report

- compiler/onecc-docker/debian/onecc-docker.install
This commit changes the docker file path.
The dockerfile will be placed in the bin directory.
> [onecc-docker] Change docker file path

- compiler/one-cmds/tests/prepare_test_materials.sh
This commit updates `prepare_test_materials.sh` script to use `wget`'s `-nv` option when script tries to download materials.
This is introduced for easy error check on CI.
> [one-cmds] Use no-verbose option for materials download

- compiler/visq-unittest/test/testDotBuilder.py
- compiler/visq/visqlib/DotBuilder.py
> [visq] Use quoted node name

- runtime/onert/core/src/exec/IPermuteFunction.cc
- runtime/onert/core/src/exec/IPermuteFunction.test.cc
This commit enables IPermuteFunction to support nchw layout in type-aware quantization.
---
For #10002
Draft #10329
> [onert] Support NCHW layout for type-aware quantization

- res/PyTorchExamples/ptem.py
This will extract onnx_model_path from ptem.py as common path for onnx model.
> [res] extract onnx_model_path

- compiler/luci/pass/src/helpers/NodeFiller.h
This will add with_args_of helper method without commutative for Sub/Div.
> [luci/pass] NodeFiller with_args_of helper

- compiler/visq-unittest/test/testUtil.py
This removes redundant print in the test code.
> [visq-unittest] Remove redundant log

- compiler/circle2circle/src/Circle2Circle.cpp
This will add fuse_prelu option to fuse some sort of subgraph to CirclePRelu Op.
> [circle2circle] Add fuse_prelu option

- compiler/one-cmds/how-to-use-one-commands.txt
- compiler/one-cmds/onelib/constant.py
This will enable fuse_prelu option to one-cmds optimize.
> [one-cmds] Enable fuse_prelu

- compiler/one-cmds/one-prepare-venv.u2204
This will add pydot package to be installed in Ubuntu2204 venv.
> [one-cmds] Add pydot in one-prepare-venv.u2204

- onert-micro/luci-interpreter/src/core/RuntimeGraph.cpp
- onert-micro/luci-interpreter/src/core/RuntimeGraph.h
- onert-micro/luci-interpreter/src/loader/GraphLoader.cpp
- onert-micro/luci-interpreter/src/loader/GraphLoader.h
- onert-micro/luci-interpreter/src/loader/ModuleLoader.cpp
This PR adds support of variable and intermediate tensors in onert-micro.
for issue: https://github.com/Samsung/ONE/issues/10375
from draft #10376
> [onert-micro] Support variable and intermediate tensors

- runtime/onert/core/include/exec/IExecutor.h
- runtime/onert/core/src/backend/builtin/IOTensor.h
- runtime/onert/core/src/exec/Execution.test.cc
- runtime/onert/core/src/exec/ExecutorBase.h
- runtime/onert/core/src/exec/Executors.cc
- runtime/onert/core/src/exec/Executors.h
- runtime/onert/core/src/interp/InterpExecutor.h
This commit applies type-aware quantization to multi-model.
- Support type-aware quantization for multi-model
- Add unittest for multi-model
---
For #10002
Draft #10329
> [onert] Support type-aware quantization for multi-model

- compiler/CMakeLists.txt
This will revise compiler CMakeLists file to aquire Ubuntu codename and a flag for jammy.
> [compiler] Get codename and flag for jammy

- compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
- compiler/luci/pass/src/QuantizeWithMinMaxPass.test.cpp
This allows to quantize inactive (unused) inputs.
> [luci] Quantize inactive inputs

- compiler/circle-mpqsolver/README.md
This commit fixes details of qerror_ratio parameter in 'README.md'.
Issue: #10387
> [circle-mpqsolver] Fix 'README.md' for qerror_ratio parameter

- onert-micro/luci-interpreter/src/core/KernelParams.h
This commit introduces UnidirectionalSequenceLSTMParams structure.
for issue https://github.com/Samsung/ONE/issues/10375
from draft https://github.com/Samsung/ONE/pull/10376
> [onert-micro] Introduce UnidirectionalSequenceLSTMParams

- onert-micro/luci-interpreter/src/kernels/Utils.h
This commit introduces getTfLiteActivation function.
for issue https://github.com/Samsung/ONE/issues/10375
from draft https://github.com/Samsung/ONE/pull/10376
> [onert-micro] Introduce getTfLiteActivation

- compiler/one-cmds/CMakeLists.txt
This will revise to install one-prepare-venv per platform.
- one-prepare-venv.u2204 is for jammy
> [one-cmds] Install one-prepare-venv per platform

- runtime/onert/core/src/exec/SingleModelExecutors.cc
- runtime/onert/core/src/interp/InterpExecutor.cc
- runtime/onert/core/src/interp/InterpExecutor.h
This commit changes getting IO information to get it from io tensors instead of Graph.
---
For #10002
Draft #10329
> [onert] Revisit `SingleModelExecutors`

- compiler/dalgona-test/CMakeLists.txt
> [dalgona-test] Enable test jammy/venv_2_10_1

- compiler/luci-pass-value-test/CMakeLists.txt
> [luci-pass-value-test] Enable test jammy/venv_2_10_1

- compiler/pota-quantization-value-test/CMakeLists.txt
> [pota-quant-val-test] Enable test jammy/venv_2_10_1

- compiler/record-minmax-conversion-test/CMakeLists.txt
> [record-minmax-conv-test] Enable test jammy/venv_2_10_1

- compiler/record-minmax-thread-safety-test/CMakeLists.txt
> [rec-minmax-t-safety-test] Enable test jammy/venv_2_10_1

- compiler/luci-value-test/CMakeLists.txt
> [luci-value-test] Enable test jammy/venv_2_10_1

- compiler/tf2tfliteV2-conversion-test/CMakeLists.txt
> [tf2tflitev2-conv-test] Enable test jammy/venv_2_10_1

- compiler/visq-unittest/CMakeLists.txt
> [visq-unittest] Enable test jammy/venv_2_10_1
