runtime/service/npud/core/Server.cc, runtime/service/npud/core/Server.h, runtime/service/npud/tests/core/DBus.test.cc
This commit executes Server using child thread and sends a dbus method from main test thread to Server.
=> [npud] Add DBus test code

infra/nnfw/config/gbs.conf
This commit updates gbs.conf to use new repo addr and name.
=> [gbs] Update gbs.conf

tools/tflitefile_tool/select_operator.py
Add an argument `--store-metadata` to `select_operator.py` that allows metadata to be stored.
=> [tools] Add an argument `--store-metadata` to `select_operator.py`

runtime/service/npud/core/Backend.h, runtime/service/npud/core/DBus.cc, runtime/service/npud/core/DBus.h, runtime/service/npud/org.tizen.npud.xml
This commit adds request_set_data dbus method.
=> [npud] Add request_set_data dbus method

infra/scripts/test_ubuntu_npud.sh
This commit installs model files for npud_gtest.
=> [infra/npud] Install model files for npud_gtest

compiler/circle-mpqsolver/CMakeLists.txt, compiler/circle-mpqsolver/README.md, compiler/circle-mpqsolver/requires.cmake, compiler/circle-mpqsolver/src/CircleMPQSolver.cpp
This PR introduces MPQSolver for the task of automatic mixed precision quantization.
=> [mpqsolver] Introduce MPQSolver

tools/nnpackage_tool/model2nnpkg/model2nnpkg.sh
It adds quotes and fix wrong quotes.
=> [tools/model2nnpkg] Put missing and fix wrong quotes

onert-micro/CMakeLists.txt, onert-micro/eval-driver/CMakeLists.txt, onert-micro/eval-driver/Driver.cpp, onert-micro/luci-interpreter/src/CMakeLists.txt, onert-micro/luci-interpreter/src/core/CMakeLists.txt, onert-micro/luci-interpreter/src/core/reader/CMakeLists.txt, onert-micro/luci-interpreter/src/kernels/CMakeLists.txt
This pr adds eval driver for onert-micro.
=> [onert-micro] Introduce eval driver

compiler/luci/pass/src/FuseBatchNormWithTConvPass.cpp
This will revise FuseBatchNormWithTConvPass also to support ReLU.
=> [luci/pass] Support ReLU in FuseBatchNormWithTConvPass

compiler/luci/pass/src/FuseBatchNormWithTConvPass.cpp
This will revise FuseBatchNormWithTConvPass with switch instead of if-else.
=> [luci/pass] Revise FuseBatchNormWithTConvPass with switch

compiler/luci/pass/src/FuseBatchNormWithTConvPass.cpp
This will extract common codes replace_with_relu() from FuseBatchNormWithTConvPass.
=> [luci/pass] Extract replace_with_relu

compiler/circle-mpqsolver/CMakeLists.txt, compiler/circle-mpqsolver/requires.cmake, compiler/circle-mpqsolver/src/bisection/DepthParameterizer.cpp, compiler/circle-mpqsolver/src/bisection/DepthParameterizer.h, compiler/circle-mpqsolver/src/bisection/DepthParameterizer.test.cpp, compiler/circle-mpqsolver/src/bisection/TestHelper.h
This commit introduces DepthParameterizer for the task of automatic mixed precision quantization.
=> [mpqsolver] Introduce DepthParameterizer

compiler/record-minmax/CMakeLists.txt, compiler/record-minmax/driver/Driver.cpp, compiler/record-minmax/include/RecordFunction.h, compiler/record-minmax/include/RecordMinMax.h, compiler/record-minmax/src/RecordMinMax.cpp
This updates code to use nncc_common.
---
Related to: https://github.com/Samsung/ONE/pull/10146#issuecomment-1360557336
=> [record-minmax] Use nncc_common

runtime/service/npud/backend/trix/TrixBackend.cc, runtime/service/npud/backend/trix/TrixBackend.h, runtime/service/npud/core/Backend.h
This commit uses id only in NpuContext. The real data will be managed in Backend library.
=> [npud] Use id only in NpuContext

compiler/circle-mpqsolver/CMakeLists.txt, compiler/circle-mpqsolver/src/bisection/Quantizer.cpp, compiler/circle-mpqsolver/src/bisection/Quantizer.h, compiler/circle-mpqsolver/src/bisection/Quantizer.test.cpp
This commit introduces Quantizer for the task of automatic mixed precision quantization.
=> [mpqsolver] Introduce Quantizer

runtime/service/npud/core/DBus.cc
This commit updates npud to comment out unreachable code yet.
=> [npud] Comment out unreachable code

runtime/service/npud/backend/trix/TrixBackend.cc
This commit adds initialization to local variable.
=> [npud] Initialize variable

runtime/service/npud/core/DBus.cc, runtime/service/npud/core/DBus.h, runtime/service/npud/org.tizen.npud.xml
This commit adds execute_run dbus method.
=> [npud] Add execute_run dbus method

tools/tflitefile_tool/README.md, tools/tflitefile_tool/select_operator.py
This commit adds io info of original model to generated io file.
=> [tools/tflitefile_tool] Add io info of original model to io file

tools/nnpackage_tool/model2nnpkg/README.md, tools/nnpackage_tool/model2nnpkg/model2nnpkg.py
This commit adds an option to support connection information of multi-model.
=> [tools/model2nnpkg] Support connection information of multi-model

res/TensorFlowLiteRecipes/FullyConnected_008/test.recipe, res/TensorFlowLiteRecipes/FullyConnected_008/test.rule
This adds recipe and test rule for ReplaceNonConstFCWithBatchMatMulPass.
---
Related to: https://github.com/Samsung/ONE/issues/10241
=> [res] Add FullyConnected_008

tools/tflitefile_tool/select_operator.py
This commit adds new line at end of output json files.
=> [tools/tflitefile_tool] Add new line at end of output json files

compiler/luci/pass/src/ForwardTransposeOpPass.cpp, compiler/luci/pass/src/ForwardTransposeOpPass.test.cpp
This commit reduces duplicates of ForwardTransposeOpPass.
Related : #9947 
=> [luci/pass] Reduce duplicates of ForwardTransposeOpPass

compiler/circle-mpqsolver/CMakeLists.txt, compiler/circle-mpqsolver/src/CircleMPQSolver.cpp, compiler/circle-mpqsolver/src/MPQSolver.cpp, compiler/circle-mpqsolver/src/MPQSolver.h, compiler/circle-mpqsolver/src/bisection/BisectionSolver.cpp, compiler/circle-mpqsolver/src/bisection/BisectionSolver.h
This commit introduces BisectionSolver for the task of automatic mixed precision quantization.
=> [mpqsolver] Introduce BisectionSolver

compiler/luci/pass/src/ConvertToFakeQuantizedModelPass.cpp
This support fake quantization of ABS Op.
---
Related to: https://github.com/Samsung/ONE/issues/10185
=> [luci] Fake quantize ABS Op

infra/debian/compiler/one-compiler.install, infra/packaging/res/tf2nnpkg.20221125
This commit adds new model2nnpkg script to packaging.
---
Draft: #10235
=> [infra] Use new model2nnpkg script

compiler/luci-eval-driver/CMakeLists.txt, compiler/luci-eval-driver/requires.cmake, compiler/luci-eval-driver/src/EvalDriver.cpp
This will tidy dependency and remove unnecessary headers.
=> [luci-evel-driver] Tidy dependency

tools/nnpackage_tool/model2nnpkg/model2nnpkg.py
This commits fixes incorrectly generating metadata.
=> [tools/model2nnpkg] Fix incorrectly generating metadata

runtime/onert/core/include/compiler/Compiler.h, runtime/onert/core/src/compiler/Compiler.cc, runtime/onert/core/src/compiler/CompilerFactory.cc
This commit introduces MultiModelCompiler to separate single and multi model nnpackage compilation.
---
Draft: #10004
=> [onert] Introduce MultiModelCompiler

runtime/onert/core/src/compiler/Compiler.cc, runtime/onert/core/src/compiler/CompilerFactory.cc, runtime/onert/core/src/compiler/MultiModelCompiler.cc, runtime/onert/core/src/compiler/MultiModelCompiler.h
This commit separates MultiModelCompiler class in MultiModelCompiler.h/cc files.
---
Draft: #10004
=> [onert] Separate MultiModelCompiler class

compiler/common-artifacts/CMakeLists.txt
This will remove dependency from folder as it doesn't work correctly.
=> [common-artifacts] Tidy CMake

compiler/pics/CMakeLists.txt, compiler/pics/README.md
This introduces a pics module.
---
Draft PR: https://github.com/Samsung/ONE/pull/10283
Related to: #10281
=> [pics] Introduce pics module

tools/nnpackage_tool/nncc-tc-to-nnpkg-tc/nncc-tc-to-nnpkg-tc.sh, tools/nnpackage_tool/sth2nnpkgtc/pb2nnpkgtc.sh, tools/nnpackage_tool/sth2nnpkgtc/tflite2nnpkgtc.sh
This commit updates tools using model2nnpkg to use python script with "-m" argument.
=> [tools] Update using model2nnpkg

infra/docker/bionic/Dockerfile, infra/docker/focal/Dockerfile, infra/docker/jammy/Dockerfile
This installs flatbuffers to docker image.
---
Related to: https://github.com/Samsung/ONE/issues/10287
=> [infra] Install flatbuffers to docker image

tools/nnpackage_tool/model2nnpkg/README.md, tools/nnpackage_tool/nncc-tc-to-nnpkg-tc/README.md
This commit updates nnpackage tools' doc to add python prerequisite.
=> [tools/doc] Add prerequisite for model2nnpkg

compiler/common-artifacts/CMakeLists.txt
This installs pydot for visq.
---
Related to: https://github.com/Samsung/ONE/issues/10277
Draft PR: #10291
=> [common-artifacts] Install pydot libraray

compiler/pota-quantization-value-test/CMakeLists.txt, compiler/pota-quantization-value-test/test_parallel_record_minmax.sh
This PR adds parallel record-minmax test.
for issue https://github.com/Samsung/ONE/issues/10133
from draft: https://github.com/Samsung/ONE/pull/10132
=> [pota-quantization] Add parallel record-minmax test

compiler/one-cmds/dummy-driver/CMakeLists.txt, compiler/one-cmds/dummy-driver/src/dummyEnv-compile.cpp, compiler/one-cmds/onecc.template.cfg, compiler/one-cmds/onelib/CfgRunner.py, compiler/one-cmds/tests/onecc_042.cfg, compiler/one-cmds/tests/onecc_042.test
This commit introduces Environment section to one-cmds.
Related: #10177 
=> [one-cmds] Introduce Environment section

runtime/onert/core/include/exec/IExecutors.h
This commit adds comment for IExecutors.
=> [onert] Add comment in IExecutors.h

compiler/one-cmds/one-quantize, compiler/one-cmds/onelib/Command.py, compiler/one-cmds/utils.py
This commit introduces Command.py to one-cmds.
Related: #8169
=> [one-cmds] Introduce Command.py

infra/debian/compiler/one-compiler.install
This commit adds Command.py to install list.
This PR should be merged after #10315 
=> [debian] Add Command.py to install list

compiler/visq/CMakeLists.txt, compiler/visq/requires.cmake, compiler/visq/test/testDotBuilder.py, compiler/visq/visqlib/DotBuilder.py
This adds DotBuilder module and its tests.
---
Related to: https://github.com/Samsung/ONE/issues/10277
Draft PR: https://github.com/Samsung/ONE/pull/10291
=> [visq] Add DotBuilder module

infra/packaging/preset/20221125, infra/packaging/preset/20221125_windows
This adds pics module to preset.
---
Related to: https://github.com/Samsung/ONE/issues/10323
=> [infra] Add pics to preset

compiler/visq/README.md, compiler/visq/visq
This adds an option to dump dot graph.
---
Related to: https://github.com/Samsung/ONE/issues/10277
Draft PR: https://github.com/Samsung/ONE/pull/10291
=> [visq] Add --dump_dot_graph option

compiler/luci/pass/src/ConvertToFakeQuantizedModelPass.cpp
This PR supports fake quantization of ReduceProd Op.
for issue: #10305
=> [luci] Fake quantize ReduceProd Op

compute/cker/include/cker/operation/Quantize.h, compute/cker/include/cker/operation/Round.h, runtime/onert/core/src/exec/IPermuteFunction.cc
This commit introduces optimized kernels for quantization.
---
For #10002
Draft #10329
=> [cker] Introduce optimized kernels for quantization

runtime/onert/core/src/exec/IPermuteFunction.cc
This commit enables type-aware quantization of non-portable tensors
---
For #10002
Draft #10329
=> [onert] Support type-aware quantization of non-portable tensors

runtime/onert/core/src/exec/IPermuteFunction.test.cc
This commit introduces `IPermuteFunction` unittest.
---
For #10002
Draft #10329
=> [onert] Introduce `IPermuteFunction` unittest

compiler/circle-mpqsolver/CMakeLists.txt, compiler/circle-mpqsolver/src/bisection/BisectionSolver.cpp, compiler/circle-mpqsolver/src/bisection/Evaluator.cpp
This commit fixes compiler warnings in mpqsolver.
=> [mpqsolver] Fix warnings

compiler/visq/visqlib/QErrorComputer.py
This computes qerrors for multiple data.
---
Draft PR: https://github.com/Samsung/ONE/pull/10352
=> [visq] Support multiple data

compiler/visq-unittest/test/testQErrorComputer.py
This adds test for multiple data.
---
Draft PR: https://github.com/Samsung/ONE/pull/10352
=> [visq-unittest] Add multi data test

res/TensorFlowLiteRecipes/Net_Conv_PReluGraph_000/test.recipe, res/TensorFlowLiteRecipes/Net_Conv_PReluGraph_000/test.rule
This will introduce Net_Conv_PReluGraph_000 recipe that has Conv with exploded subgraph of PReLU from ONNX example.
=> [res] Net_Conv_PReluGraph_000 recipe

res/PyTorchExamples/examples/PReLUwConv1d/__init__.py, res/PyTorchExamples/examples/PReLUwConv2d/__init__.py
This will introduce PyTorchExamples of PReLU with Conv.
=> [res] PyTorchExamples of PReLU with Conv

compiler/luci/pass/include/luci/Pass/FusePReluPass.h, compiler/luci/pass/src/FusePReluPass.cpp, compiler/luci/pass/src/FusePReluPass.test.cpp
This will introduce initial FusePReluPass.
=> [luci/pass] Initial FusePReluPass

compiler/luci/pass/src/FusePReluPass.cpp, compiler/luci/pass/src/FusePReluPass.test.cpp
This will implement FusePReluPass to fuse certain subgraph to CirclePRelu Op.
=> [luci/pass] Implement FusePReluPass

res/PyTorchExamples/ptem.py
This will add shape inference to show shapes in PyTorchExamples result ONNX files.
=> [res] Add shape inference for PyTorchExamples

compiler/luci/pass/src/ForwardReshapeToUnaryOpPass.cpp
This will revise ForwardReshapeToUnaryOpPass to handle CircleAbs.
=> [luci/pass] Revise ForwardReshapeToUnaryOpPass

compiler/luci/pass/include/luci/CircleOptimizer.h, compiler/luci/pass/src/CircleOptimizer.cpp
This will enable optimizer with FusePReluPass.
=> [luci/pass] Enable FusePReluPass

onert-micro/luci-interpreter/src/loader/GraphLoader.cpp
This PR fixes inplace optimization in GraphLoader.
=> [onert-micro] Fix inplace optimization loader

compiler/one-cmds/how-to-prepare-virtualenv.txt
This will update how-to-prepare-virtualenv file which is way out-dated.
=> [one-cmds] Update how-to-prepare-virtualenv

compiler/one-cmds/one-prepare-venv.u2204
This will revise package versions for Ubuntu22.04 venv.
=> [one-cmds] Revise package versions

compiler/common-artifacts/CMakeLists.txt
This will prepare additional venv for jammy with TF2.10.1.
=> [cmn-arts] Prepare venv for jammy

compiler/nnc/tests/soft_backend/test_main.def
This will fix test error from Ubuntu22.04.
=> [nnc] Fix test error from Ubuntu22.04

runtime/onert/core/src/exec/Execution.test.cc
This commit fixes Execution unittest for multi-model.
=> [onert] Fix Execution unittest for multi-model

compiler/circle-part-value-test/CMakeLists.txt
=> [circle-part-value-test] Enable test jammy/venv_2_10_1

runtime/onert/core/src/exec/Executors.cc, runtime/onert/core/src/exec/Executors.h
This commit introduces EdgeTensor for edges of multi-model.
---
For #10002
Draft #10329
=> [onert] Introduce `EdgeTensor`

compiler/luci/pass/src/ConvertNCHWToNHWCPass.cpp, compiler/luci/pass/src/ConvertNCHWToNHWCPass.test.cpp
This removes softmax/log_softmax from ConvertNCHWToNHWCPass
=> [luci] Remove softmax/log_softmax from ConvertNCHWToNHWCPass

compiler/circle-opselector/src/OpSelector.cpp
This commit fixes the bug to make it set valid output.
=> [circle-opselector] Set proper output

compiler/visq/visq
This will fix single quite pair count that seems a typo.
=> [visq] Fix single quote pair

compiler/circle-opselector/src/OpSelector.cpp
This commit supports multioutput nodes.
Related: #10436 
=> [circle-opselector] Support multioutput nodes

compiler/luci-value-test/luci_eval_verifier.py, compiler/luci-value-test/luci_eval_verifier_ref.py, compiler/luci-value-test/test.lst
This will revise YUV_TO_RGB_U8_000 to test with tolerance
- revise value compare with tolerance for integer too
=> [luci-value-test] Revise YUV_TO_RGB_U8_000 to use tolerance

compiler/luci-value-test/luci_eval_verifier.py, compiler/luci-value-test/luci_eval_verifier_ref.py
This will revise verify script to dump tensors when there is error for better debugging.
=> [luci-value-test] Dump diff when error

runtime/onert/api/src/nnfw_api_internal.cc, runtime/onert/core/include/ir/NNPkg.h, runtime/onert/core/src/exec/Execution.test.cc, runtime/onert/core/src/exec/Executors.cc
This commit apply type-aware quantization to nnpkg io.
---
For #10002
Draft #10329
=> [onert] Support type-aware quant for nnpkg io

infra/docker/bionic/Dockerfile, infra/docker/focal/Dockerfile, infra/docker/jammy/Dockerfile
This commit updates dockerfiles to add sudoers user name, not only user group.
Jenkins requires user names in sudoer to run sudo on docker container.
=> [infra/dockerfile] Add sudoers username

onert-micro/helpers/GenerateKernelsListHelper.cpp, onert-micro/luci-interpreter/pal/mcu/PALUnidirectionalSequenceLSTM.h, onert-micro/luci-interpreter/src/core/KernelParams.h, onert-micro/luci-interpreter/src/kernels/UnidirectionalSequenceLSTM.cpp, onert-micro/luci-interpreter/src/kernels/UnidirectionalSequenceLSTM.h, onert-micro/luci-interpreter/src/kernels/Utils.cpp, onert-micro/luci-interpreter/src/kernels/Utils.h, onert-micro/luci-interpreter/src/loader/nodes/UnidirectionalSequenceLSTM.cpp
This PR adds integer UnidirectionalSequenceLSTM support to onert-micro.
for issue https://github.com/Samsung/ONE/issues/10375
from draft #10376
=> [onert-micro] Add Integer UnidirectionalSequenceLSTM

runtime/onert/core/src/exec/Executors.cc
This commit fixes io tensors of nnpkg for type-aware quantization to manage inputs and outputs separately.
---
For https://github.com/Samsung/ONE/issues/10002
Draft https://github.com/Samsung/ONE/pull/10329
=> [onert] Fix io tensors of nnpkg for type-aware quantization

compiler/one-cmds/onelib/utils.py
This removes duplicate codes in utils.py.
=> [one-cmds] Tidy utils.py

compiler/one-cmds/one-optimize, compiler/one-cmds/onelib/constant.py, compiler/one-cmds/onelib/utils.py
This adds --O1 for basic optimization options.
---
Related to: https://github.com/Samsung/ONE/issues/10381
Draft PR: #10463
=> [one-cmds] Support O1 optimization option

runtime/onert/core/src/exec/Executors.cc, runtime/onert/core/src/exec/Executors.h
This commit fixes the wrong creation of type-aware quantization.
- Fix what doesn't work if there are more than 2 `from` in a model
- Renaming `type_aware_quant` to `edge_quant`
---
For https://github.com/Samsung/ONE/issues/10002
Draft https://github.com/Samsung/ONE/pull/10329
=> [onert] Fix the wrong creation of type-aware quantization.

compiler/luci/pass/src/ForwardTransposeOpPass.cpp
This will revise ForwardTransposeOpPass to support Unary Abs Op.
=> [luci/pass] Revise ForwardTransposeOpPass with Abs

res/TensorFlowLiteRecipes/Net_Transpose_Abs_000/test.recipe
This will introduce Net_Transpose_Abs_000 recipe.
=> [res] Introduce Net_Transpose_Abs_000

compiler/luci/pass/src/ConvertToFakeQuantizedModelPass.cpp
This adds the following Ops fake quantization
- Pack
- UnPack
=> [luci] Support more Ops for fake quantization

compiler/luci/pass/src/ForwardTransposeOpPass.test.cpp
This will add unit tests for ForwardTransposeOpPass Unary ABS Op.
=> [luci/pass] Test for ForwardTransposeOpPass Unary ABS

compiler/visq/visqlib/QErrorComputer.py
This commit introduces optional split of 'run' into 'advance_on' and 'get_final_result'.
Draft: #10432
Related to: #10393 
=> [visq] Optional split of 'run' into 'advance_on' and 'get_final_results'

tests/scripts/common.sh, tests/scripts/test_scheduler_with_profiling.sh
This commit updates onert profiling mode test script.
---
Related issue: #9877
Draft: #10496
=> [onert/test] Update profiling mode test script

tests/scripts/command/prepare-model, tests/scripts/command/unittest, tests/scripts/command/verify-tflite, tests/scripts/onert-test
This commit adds test command common variable "CACHE_PATH" and use common variables on commands.
---
Draft: #10496
=> [onert/test] Set test command common variables

compiler/visq/visq
This commit introduces 'batch' mode for `visq` component.
Draft: #10432
Related to: #10393
=> [visq] Introduce 'batch' mode

compiler/visq/visq
This commit fixes 'visq' script.
Draft: #1505
Related: #1491
=> [visq] Fix 'visq' script

compiler/visq-unittest/test/testQErrorComputer.py, compiler/visq/visq, compiler/visq/visqlib/QErrorComputer.py
This commit adds Total Absolute Error metric.
Draft: #10432
Related: #10393
=> [visq] Add TAE metric

onert-micro/standalone/CMakeLists.txt
reference : https://gitlab.kitware.com/cmake/cmake/-/issues/19693
=> Fix build error for luci_interpreter_micro_arm Target

tests/scripts/benchmark_nnpkg.sh, tests/scripts/merge_result_of_benchmark_nnpkg.py
This commit updates nnpackage test scripts.
---
=> [onert/test] Update nnpackage test script

compiler/luci/pass/src/CircleQuantizer.cpp, compiler/luci/pass/src/helpers/Strings.cpp, compiler/luci/pass/src/helpers/Strings.h, compiler/luci/pass/src/helpers/Strings.test.cpp
This parses input/output_type and canonicalize them.
---
=> [luci] Canonicalize user-given input/output_type

tests/scripts/benchmark_nnapi.sh, tests/scripts/common.sh
This commit updates runtime backend operator kernel test script.
---
=> [onert/test] Revive operator kernel test script

compiler/luci/log/src/Log.cpp
This will tidy disabled code with directives.
=> [luci/log] Tidy disabled code

compiler/circle-quantizer/src/CircleQuantizer.cpp
This update help message to handle multiple input/output_type.
---
=> [circle-quantizer] Revise help message

compiler/circle-mpqsolver/src/bisection/VISQErrorApproximator.cpp, compiler/circle-mpqsolver/src/bisection/VISQErrorApproximator.h
This commit introduces VISQErrorApproximator.
=> [circle-mpqsolver] Introduce VISQErrorApproximator

compiler/circle-opselector/src/OpSelector.cpp
This commit fixes static analysis warning.
=> [circle-opselector] Fix static analysis warning

infra/debian/compiler/changelog
This commit updates changelog for release.
Related: #10540 
=> [debian] Update changelog

infra/debian/compiler/one-compiler.install
This commit installs optimization folder.
Related: https://github.com/Samsung/ONE/issues/10555#issuecomment-1484736456
=> [debian] Install optimization folder

docs/release/1.22/index.rst, docs/release/1.22/release-note-1.22.0.md
This commit is a release note for 1.22.0.
Related: #10540 
=> Release note 1.22.0

docs/conf.py, packaging/nnfw.spec, runtime/contrib/android/api/build.gradle, runtime/onert/api/include/nnfw_version.h
This commit updates runtime version into 1.23.0.
=> Update runtime version to 1.23.0

compiler/circle-mpqsolver/CMakeLists.txt, compiler/circle-mpqsolver/src/bisection/VISQErrorApproximator.cpp, compiler/circle-mpqsolver/src/bisection/VISQErrorApproximator.test.cpp
This commit implements visq parsing.
=> [circle-mpqsolver] Implement visq parsing

res/PyTorchExamples/ptem.py
This will revise PyTorchExamples genegation script without verbose information.
=> [res] Remove verbose from PyTorchExamples

compiler/circle-mpqsolver/src/bisection/VISQErrorApproximator.cpp, compiler/circle-mpqsolver/src/bisection/VISQErrorApproximator.h
This commit improves messaging on failure.
=> [circle-mpqsolver] Revisit visq parsing

compiler/circle-mpqsolver/src/bisection/Evaluator.cpp
This updates usage of readTensor.
---
=> [circle-mpqsolver] Update readTensor

compiler/circle-eval-diff/src/InputDataLoader.cpp
This updates use of readTensor.
---
=> [circle-eval-diff] Update readTensor

compiler/dalgona/src/Dalgona.cpp
This updates usage of readTensor.
---
=> [dalgona] Update readTensor

compiler/record-minmax/src/RecordMinMax.cpp
This updates usage of readTensor.
---
=> [record-minmax] Update readTensor

compiler/visq/visq, compiler/visq/visqlib/DumpFakeQuantFM.py, compiler/visq/visqlib/QErrorComputer.py
This introduces a new metric SRMSE.
---
Related to: https://github.com/Samsung/ONE/pull/10524
Draft PR: https://github.com/Samsung/ONE/pull/10525
=> [visq] Introduce SRMSE metric

compiler/visq/visqlib/QErrorComputer.py
This uses defaultdict instead of dict for simplicity.
=> [visq] Use defaultdict

compiler/visq-unittest/test/testQErrorComputer.py
This adds tests for SRMSE metric.
---
Related to: https://github.com/Samsung/ONE/issues/10524
Draft PR: https://github.com/Samsung/ONE/pull/10525
=> [visq-unittest] Add test for SRMSE

compiler/circle-mpqsolver/src/bisection/BisectionSolver.cpp
This commit replaces ErrorApproximator with VISQErrorApproximator.
=>  [circle-mpqsolver] Replace ErrorApproximator with VISQErrorApproximator

compiler/circle-mpqsolver/src/CircleMPQSolver.cpp
This commit introduces 'visq_file' parameter and uses it.
=> [circle-mpqsolver] Introduce visq_file.

compiler/circle-opselector/driver/Driver.cpp
This commit removes assert statement for release build.
=> [circle-opselector] Remove assert

compiler/one-cmds/onelib/utils.py
This commit removes deprecated function.
=> [one-cmds] Remove deprecated function

compiler/luci/pass/src/QuantizedModelVerifier.test.cpp, compiler/luci/pass/src/VerifyQuantizedNodeGranularity.h, compiler/luci/pass/src/VerifyQuantizedNodeType.cpp, compiler/luci/pass/src/VerifyQuantizedNodeType.h
This verifies quantization of Sum Op.
---
Related to: https://github.com/Samsung/ONE/issues/10531
=> [luci] Verify quantization of Sum

compiler/luci/pass/src/ConvertToFakeQuantizedModelPass.cpp
This adds more Ops in fake quantization.
=> [luci] Add more fake quantization Ops

compiler/luci/pass/src/ConvertNCHWToNHWCPass.cpp
This clones a constant when expanding it to rank 4.
=> [luci] Fix bug in ConvertNCHWToNHWCPass

res/TensorFlowLiteRecipes/REGRESS_ONNX_Mul_Mul_000/test.recipe, res/TensorFlowLiteRecipes/REGRESS_ONNX_Mul_Mul_000/test.rule
This adds REGRESS_ONNX_Mul_Mul recipe and rule.
---
Related to: https://github.com/Samsung/ONE/pull/10611#issuecomment-1500083991
=> [res] Add REGRESS_ONNX_Mul_Mul recipe and rule

infra/nnfw/cmake/CfgOptionFlags.cmake, infra/nnfw/cmake/options/options_aarch64-android.cmake, infra/nnfw/cmake/options/options_aarch64-tizen.cmake, infra/nnfw/cmake/options/options_armv7hl-tizen.cmake, infra/nnfw/cmake/options/options_armv7l-tizen.cmake, infra/nnfw/cmake/options/options_i686-tizen.cmake, infra/nnfw/cmake/options/options_x86_64-tizen.cmake, runtime/onert/core/CMakeLists.txt, runtime/onert/core/src/dumper/h5/Dumper.cc, runtime/onert/core/src/dumper/h5/Dumper.h, runtime/onert/core/src/dumper/h5/MinMaxDumper.cc, runtime/onert/core/src/dumper/h5/MinMaxDumper.h
It introduces h5 dumper for minmax.
Related: #10604
=> [onert] Introduce h5/{Dumper,MinMaxDumper}

res/CircleSchema/0.5/circle_schema.fbs
This introduces circle schema 0.5.
---
Draft PR: #10643
=> [res] Introduce circle schema 0.5

compiler/mio-circle05/CMakeLists.txt, compiler/mio-circle05/README.md, compiler/mio-circle05/example.cpp, compiler/mio-circle05/include/mio_circle/Helper.h, compiler/mio-circle05/include/mio_circle/Reader.h, compiler/mio-circle05/src/Helper.cpp, compiler/mio-circle05/src/Helper.test.cpp, compiler/mio-circle05/src/Reader.cpp, compiler/mio-circle05/src/Reader.test.cpp
This introduces mio-circle05 (w/ circle schema 0.5).
---
=> [mio-circle05] Introdue mio-circle05

infra/packaging/preset/20230413, infra/packaging/preset/20230413_windows
This adds preset 20230413 with mio-circle05.
---
=> [infra] Add preset

tests/nnfw_api/src/one_op_tests/StridedSlice.test.cc
=> [onert] Add negative TC for StridedSlice

tests/nnfw_api/src/one_op_tests/Reverse.test.cc
=> [onert] Add negative TC for Reverse

infra/debian/compiler/rules, infra/packaging/build
This updates preset to 20230413.
---
=> [infra] Update preset

infra/packaging/res/tf2nnpkg.20230413
This commit adds tf2nnpkg for preset 20230413.
Related: https://github.com/Samsung/ONE/issues/10608#issuecomment-1510543418
=> [infra] Add tf2nnpkg for preset 20230413

compiler/circle-verify/CMakeLists.txt, compiler/circle-verify/requires.cmake
=> [circle-verify] Upgrade circle schema to 0.5

compiler/tflite2circle/CMakeLists.txt, compiler/tflite2circle/requires.cmake
---
Related to: #10629
Draft PR: #10643
=> [tflite2circle] Upgrade circle scheam to 0.5

res/TensorFlowLiteSchema/2.10.1/schema.fbs, res/TensorFlowLiteSchema/SCHEMA.lst
This adds TFLite schema 2.10.1.
---
=> [res] Add TFLite schema 2.10.1

compiler/visq/visq, compiler/visq/visqlib/QErrorComputer.py
This commit fixes some typos in visq.
I'm trying to update my draft on visq_runner for one-vscode.
=> [visq] Fix typos

compiler/circle-mpqsolver/src/core/Quantizer.cpp, compiler/circle-mpqsolver/src/core/Quantizer.h
This commit introduces QuantizerHook and uses in Quantizer.
Its correctness is tested in #10655
Draft: #10655
Related: #10634 
=> [circle-mpqsolver] Introduce QuantizerHook

docs/release/1.22/release-note-1.22.1.md
This commit adds a release note for 1.22.1
---
Copy from release/1.22.0 branch
=> [onert] Release note for 1.22.1

compiler/tflite2circle/src/CircleModel.cpp
This supports extended builtin ops.
---
=> [tflite2circle] Support extended builtin ops

compiler/luci/import/include/luci/Import/Nodes.h, compiler/luci/import/include/luci/Import/Nodes/CircleGelu.h, compiler/luci/import/src/GraphBuilderRegistry.cpp, compiler/luci/import/src/Nodes/CircleGelu.cpp
This supports import of Gelu Op.
---
=> [luci] Support Gelu import

compiler/luci/export/src/CircleBuiltinTypesExtractor.h, compiler/luci/export/src/CircleOps.lst
This supports Gelu in export.
---
=> [luci/export] Support Gelu

compiler/luci/service/src/CircleCloneNode.h, compiler/luci/service/src/CircleShapeInferenceRule.cpp, compiler/luci/service/src/CircleTypeInferenceRule.cpp, compiler/luci/service/src/Nodes/CircleGelu.cpp, compiler/luci/service/src/Nodes/CircleGelu.test.cpp
This supports Gelu in luci service.
---
=> [luci/service] Support Gelu

compiler/luci-interpreter/pal/linux/pal.cmake, compiler/luci-interpreter/src/kernels/Sub.cpp
This upgrades TF version to 2.8.0.
---
=> [luci-interpreter] Upgrade TF version 2.8.0

compiler/arser/CMakeLists.txt
This will tidy whitespace in CMakeLists.txt file.
=> [arser] Tidy whitespace

res/TensorFlowLiteRecipes/Gelu_000/test.recipe
This adds recipe for Gelu.
---
=> [res] Add Gelu_000

compiler/luci/pass/src/ConvertNCHWToNHWCPass.cpp
This supports Gelu in ConvertNCHWToNHWCPass.
---
=> [luci] Support Gelu in ConvertNCHWToNHWCPass

runtime/onert/core/include/util/Utils.h
This commit eliminates unnecessary code generation by making ShapeLoop simpler.
=> [onert] Revisit ShapeLoop

compiler/luci/pass/src/CircleOptimizer.cpp
This fuses Gelu Op before convert_ncwh_to_nhwc.
---
=> [luci] Fuse Gelu before convert_nchw_to_nhwc

runtime/onert/backend/trix/DevContext.cc
There is potential memory leak. It fixes the case.
=> [onert] Fix potential resource leak from trix DevContext

compiler/one-cmds/CMakeLists.txt, compiler/one-cmds/onelib/backends.py
This will introduce onelib/backends for common one commands backend list.
=> [one-cmds] Introduce onelib/backends

onert-micro/luci-interpreter/src/kernels/MISOKernel.h
=> [onert-micro] Fix MISO kernel

infra/debian/compiler/one-compiler.install
This will add backends.py file to one-compiler.install list.
=> [infra/debian] Revise one-compiler.install

compiler/one-cmds/one-codegen, compiler/one-cmds/one-infer, compiler/one-cmds/one-init
This will revise to use common backends module.
=> [one-cmds] Use common backends

compiler/one-cmds/one-codegen, compiler/one-cmds/one-infer, compiler/one-cmds/one-init
This will tidy unused codes for backends list.
=> [one-cmds] Tidy unused codes for backends list

compiler/one-cmds/one-prepare-venv.u2204
This will revise one-prepare-venv.u2204 to match tensorflow addon packages version.
=> [one-cmds] Revise one-prepare-venv.u2204

compiler/luci-eval-driver/src/EvalDriver.cpp
This will fix for analysis report warning.
=> [luci-eval-driver] Fix for analysis report

onert-micro/luci-interpreter/src/kernels/CMakeLists.txt
This pr enables test coverage statistics.
for issue: #10774
=> [onert-micro] Enable test coverage

compiler/circle-mpqsolver/src/bisection/BisectionSolver.cpp
This commit implements intermediate dumping at bisection solver.
=> [circle-mpqsolver] Use dumping hooks

.github/workflows/run-onert-micro-unit-tests.yml
This commit introduce onert-micro unit-tests workflow.
=> [infra] Introduce onert-micro unit-tests workflow

.github/workflows/build-onert-micro-arm.yml
This commit introduces onert-micro ARM build check workflow.
=> [infra] Introduce onert-micro ARM build check workflow

compiler/luci-interpreter/include/luci_interpreter/core/Tensor.h
This will add initialization for Tensor members.
=> [luci-intp] Initialze Tensor members

docs/release/1.23/index.rst, docs/release/1.23/release-note-1.23.0.md
This commit is a release note for 1.23.0.
Related: https://github.com/Samsung/ONE/issues/10802
=> Release note 1.23.0

onert-micro/README.md
- Rename luci-micro to onert-micro in onert-micro/REAME.md file
- Remove unnecessary parts
=> Rename luci-micro to onert-micro in onert-micro/README.md

onert-micro/README.md
=> onert-micro README update

compiler/one-cmds/one-import-onnx
This will revise one-import-onnx to support running extension.
=> [one-cmds] Support one-import-onnx-ext

compiler/one-cmds/tests/one-import-onnx_ext_001.test
This will add test for one-import-onnx extension.
=> [one-cmds/test] Test for one-import-onnx extension

docs/conf.py, packaging/nnfw.spec, runtime/contrib/android/api/build.gradle, runtime/onert/api/include/nnfw_version.h
This commit updates runtime version to 1.24.0.
=> [onert] Update version to 1.24.0

onert-micro/luci-interpreter/src/kernels/Utils.h
- Fix WGID 1682015, 1682019, 1682009, 1682011
=> Fix DIVIDE_BY_ZERO defect

compiler/one-cmds/tests/onecc_046.test
This commit removes dummy driver that should be removed.
=> [one-cmds] Fix minor bug in test

onert-micro/luci-interpreter/include/luci_interpreter/onert-micro-version.h
- It reserves the location for version file of onert-micro
=> Add version file for onert-micro

runtime/onert/core/include/compiler/ILoweredGraph.h, runtime/onert/core/include/compiler/LoweredGraph.h, runtime/onert/core/src/compiler/ExecutorFactory.cc, runtime/onert/core/src/compiler/ExecutorFactory.h, runtime/onert/core/src/compiler/Linear.cc, runtime/onert/core/src/compiler/pass/LoweredOperandPass.h, runtime/onert/core/src/compiler/pass/LoweredOperationPass.h, runtime/onert/core/src/compiler/pass/PermutationEliminationPass.cc
This commit introduces ILoweredGraph
=> [onert] Introduce ILoweredGraph

runtime/onert/core/include/ir/train/TrainableOperationVisitor.h
This commit introduces TrainableOperationVisitor.
=> [onert] Introduce TrainableOperationVisitor

compiler/luci/pass/src/PropagateQParamBackwardPass.cpp, compiler/luci/pass/src/PropagateQParamBackwardPass.test.cpp
This propagates QParam backward across Reshape/Transpose.
---
Related to: #10871
=> [luci] Propagate QParam backward across more Ops

runtime/onert/core/include/backend/train/ITrainableBackend.h
This commit introduces ITrainableBackend.
=> [onert] Introduce ITrainableBackend

runtime/onert/core/src/compiler/pass/IPass.h, runtime/onert/core/src/compiler/pass/Pass.h, runtime/onert/core/src/compiler/pass/PassRunner.cc
This commit introduces IPass.
- Introduce IPass
- Change PassRunner to use IPass
=> [onert] Introduce IPass

runtime/onert/core/include/ir/Graph.h, runtime/onert/core/include/ir/IGraph.h, runtime/onert/core/src/ir/Graph.cc
This commit introduces IGraph interface that can be used by session.
=> [onert] Introduce IGraph

runtime/onert/core/include/ir/train/Operations.Include.h, runtime/onert/core/include/ir/train/Operations.lst
This commit introduces operation list for training.
=> [onert] Introduce operation list for training

runtime/onert/api/src/nnfw_api_internal.cc, runtime/onert/core/include/ir/NNPkg.h
This commit prevents non-const operands from being directly modified externally.
=> [onert] Encapsulate NNPkg

runtime/onert/core/include/ir/Graph.h, runtime/onert/core/include/ir/OperandIndexSequence.h, runtime/onert/core/include/ir/train/TrainableGraph.h, runtime/onert/core/src/ir/Graph.cc, runtime/onert/core/src/ir/OperandIndexSequence.cc, runtime/onert/core/src/ir/train/TrainableGraph.cc
This commit introduces TrainableGraph that has trainable operations.
=> [onert] Introduce TrainableGraph

runtime/onert/core/src/compiler/train/pass/Pass.h
This commit introduces Pass for training.
=> [onert] Introduce Pass for training

runtime/onert/core/src/compiler/Compiler.cc, runtime/onert/core/src/compiler/ExecutorFactory.cc, runtime/onert/core/src/compiler/ExecutorFactory.h, runtime/onert/core/src/compiler/MultiModelCompiler.cc
This commit introduces ExecutorFactoryArgs.
=> [onert] Introduce ExecutorFactoryArgs

runtime/onert/core/include/exec/train/TrainableFnSequence.h, runtime/onert/core/include/exec/train/TrainableSequence.h
This commit introduces TrainableFnSequence that has trainable functions.
=> [onert] Introduce TrainableFnSequence

runtime/onert/core/include/backend/train/TrainableBackendContext.h
This commit introduces TrainableBackendContext.
- Introduce TrainableContextData
- Introduce TrainableBackendContext
=> [onert] Introduce TrainableBackendContext

runtime/onert/core/include/compiler/train/TrainableCodeMap.h
This commit introduces CodeMap for training.
=> [onert] Introduce CodeMap for training

runtime/onert/api/src/nnfw_api_internal.cc, runtime/onert/api/src/nnfw_api_internal.h, runtime/onert/core/include/ir/Model.h, runtime/onert/core/include/ir/NNPkg.h, runtime/onert/core/src/compiler/Compiler.cc, runtime/onert/core/src/compiler/MultiModelCompiler.cc, runtime/onert/core/src/compiler/MultiModelCompiler.h
This commit applies IGraph to Model.
- Apply IGraph to Model
- Add a method to check whether the model has only one type of Graph
=> [onert] Apply IGraph to Model

runtime/onert/core/include/ir/train/Operations.Include.h, runtime/onert/core/include/ir/train/Operations.lst, runtime/onert/core/include/ir/train/operation/Permute.h, runtime/onert/core/src/ir/train/operations/Permute.cc
This commit introduces Permute operation for training.
=> [onert] Introduce Permute operation for training

runtime/onert/core/src/backend/builtin/train/KernelGenerator.cc, runtime/onert/core/src/backend/builtin/train/KernelGenerator.h, runtime/onert/core/src/backend/builtin/train/kernel/PermuteLayer.cc, runtime/onert/core/src/backend/builtin/train/kernel/PermuteLayer.h
This commit adds PermuteLayer for training.
=> [onert] Add PermuteLayer for training

runtime/onert/core/include/ir/Operations.Include.h, runtime/onert/core/include/ir/Operations.lst, runtime/onert/core/include/ir/operation/Loss.h, runtime/onert/core/include/ir/train/Operations.lst, runtime/onert/core/include/ir/train/operation/Loss.h, runtime/onert/core/src/ir/operation/Loss.cc, runtime/onert/core/src/ir/train/operation/Loss.cc
This commit introduce Loss operation.
- Introduce Loss
- Change Operation and ITrainableOperation to inherit virtual IOperation
=> [onert] Introduce Loss operation

runtime/onert/core/include/compiler/train/LoweredTrainableGraph.h, runtime/onert/core/src/compiler/train/LoweredTrainableGraph.cc, runtime/onert/core/src/dumper/text/GraphDumper.cc, runtime/onert/core/src/dumper/text/GraphDumper.h
This commit introduces LoweredTrainableGraph lowering TrainableGraph.
=> [onert] Introduce LoweredTrainableGraph

runtime/onert/core/include/compiler/train/TrainingInfo.h
This commit adds batch_size variable in TrainingInfo class.
=> [onert] Add batch_size in TrainingInfo

runtime/onert/backend/train/BackendContext.cc, runtime/onert/backend/train/BackendContext.h, runtime/onert/core/include/backend/basic/BackendContextHelpers.h, runtime/onert/core/include/backend/basic/train/TrainableBackendContextHelpers.h
This commit adds helper functions for TrainableBackendContext.
=> [onert] Add helper functions for TrainableBackendContext

runtime/onert/core/include/backend/basic/train/TrainableBackendContextHelpers.h, runtime/onert/core/src/backend/builtin/train/BackendContext.cc, runtime/onert/core/src/backend/builtin/train/BackendContext.h
This commit introduces builtin backend's BackendContext for training.
=> [onert] Introduce builtin backend's BackendContext for training

runtime/onert/core/src/compiler/TensorRegistries.h
This commit enables to create TensorRegistries for TrainableBackendContexts.
=> [onert] Create TensorRegistries by using TrainableBackendContexts

tests/tools/onert_train/CMakeLists.txt, tests/tools/onert_train/src/rawdataloader.cc, tests/tools/onert_train/src/rawdataloader.h, tests/tools/onert_train/test/rawdataloader.test.cc
This commit introduces RawDataLoader class and unittest.
This class loads user data appropriately according to batch size and data length.
=> [tools/onert_train] Introduce RawDataLoader

runtime/onert/core/src/backend/builtin/Backend.h, runtime/onert/core/src/backend/builtin/TensorBuilder.cc, runtime/onert/core/src/backend/builtin/TensorBuilder.h
This commit make `buildin` backend create its `TrainableBackendContext`.
=> [onert] Create `TrainableBackendContext` of `builtin` backend

compiler/visq/visq
This improves error message from subprocess.
=> [visq] Improve error message

runtime/onert/backend/train/Backend.h, runtime/onert/backend/train/BackendContext.h, runtime/onert/backend/train/KernelGenerator.cc, runtime/onert/backend/train/KernelGenerator.h
This commit introduces trainable kernel generator into train backend.
=> [onert] Introduce trainable kernel generator into train backend

infra/nnfw/cmake/CfgOptionFlags.cmake, infra/nnfw/cmake/options/options_aarch64-tizen.cmake, infra/nnfw/cmake/options/options_armv7hl-tizen.cmake, infra/nnfw/cmake/options/options_armv7l-tizen.cmake, infra/nnfw/cmake/options/options_i686-tizen.cmake, infra/nnfw/cmake/options/options_x86_64-tizen.cmake, runtime/onert/api/src/nnfw_api.cc, runtime/onert/api/src/nnfw_api_internal.cc, runtime/onert/api/src/nnfw_api_internal.h, runtime/onert/backend/CMakeLists.txt, runtime/onert/core/CMakeLists.txt, runtime/onert/core/src/compiler/CompilerFactory.cc, runtime/onert/core/src/compiler/TensorRegistries.h, runtime/onert/core/src/dumper/text/GraphDumper.cc, runtime/onert/core/src/dumper/text/GraphDumper.h
This commit introduces training feature build flag to disable on tizen build.
---
Test build on ubuntu: `make OPTIONS=-DENABLE_ONERT_TRAIN=OFF'
=> [onert] Introduce training feature flag 

compiler/dalgona/src/PostOperatorHook.h, compiler/dalgona/src/Utils.cpp, compiler/dalgona/src/Utils.h
This supports multi-out default hooks.
---
Related to: https://github.com/Samsung/ONE/issues/10949
Draft PR: https://github.com/Samsung/ONE/pull/10950
=> [dalgona] Support multi-out default hooks.

compiler/visq/visqlib/DumpFP32FM.py, compiler/visq/visqlib/DumpFakeQuantFM.py
This supports profiling multi-out nodes.
---
Related to: https://github.com/Samsung/ONE/issues/10949
Draft PR: https://github.com/Samsung/ONE/pull/10950
=> [visq] Support multi-out nodes

runtime/onert/core/src/backend/builtin/Backend.h
This commit fixes gbs build error.
=> [onert] Fix gbs build error

runtime/onert/backend/train/Backend.h, runtime/onert/backend/train/BackendContext.cc, runtime/onert/backend/train/BackendContext.h, runtime/onert/backend/train/KernelGenerator.cc, runtime/onert/backend/train/KernelGenerator.h
This commit makes `train` backend's context trainable.
=> [onert] Apply TrainableBackendContext to `train` backend

runtime/onert/core/include/util/Set.h, runtime/onert/core/src/compiler/ExecutorFactory.cc, runtime/onert/core/src/compiler/ExecutorFactory.h
This commit make ExecutorFactory create trainable executors.
=> [onert] Create trainable executors

runtime/onert/core/src/compiler/ExecutorFactory.cc, runtime/onert/core/src/compiler/train/TrainingCompiler.cc
This commit implements the compile method of TrainingCompiler.
=> [onert] Implement TrainingCompiler

runtime/onert/api/src/nnfw_api_internal.cc
This commit implements train_prepare nnfw api details.
It creates TrainingCompiler using the given train information.
waiting #10931
=> [onert] Implement train_prepare nnfw api

compiler/circle2circle/src/Circle2Circle.cpp
This PR adds --dynamic_batch_to_single_batch option.
---
Related to: https://github.com/Samsung/ONE/issues/8739
Draft PR: https://github.com/Samsung/ONE/pull/10974
=> [circle2circle] Add --dynamic_batch_to_single_batch option

runtime/onert/core/src/exec/train/TrainableFnSequence.cc
This commit implements forward and backward functions in TrainableFnSequence.
Train backend kernel will append trainable functions using this append api.
waiting #10972
=> [onert] Implement forward and backward functions in TrainableFnSequence

runtime/onert/backend/train/ops/ConvolutionLayer.h, runtime/onert/backend/train/ops/PoolLayer.h, runtime/onert/core/include/backend/train/KernelGeneratorBase.h, runtime/onert/core/include/exec/train/ITrainableFunction.h, runtime/onert/core/include/exec/train/TrainableFnSequence.h, runtime/onert/core/src/backend/builtin/train/kernel/PermuteLayer.h
This commit adjusts the position of ITrainableFunction.h.
=> [onert] Adjust the position of ITrainableFunction.h

runtime/onert/backend/train/TensorRegistry.h
This commit introduces TensorRegistry into train backend.
=> [onert] Introduce TensorRegistry into train backend

runtime/onert/core/src/compiler/ExecutorFactory.cc
This commit fixes incorreclty created TensorRegistries for training.
=> [onert] Fix incorreclty created TensorRegistries

runtime/onert/backend/train/MemoryManager.h
This commit introduces MemoryManager into train backend.
=> [onert] Introduce MemoryManager into train backend

runtime/onert/core/src/compiler/train/TrainableOperationConverter.cc, runtime/onert/core/src/compiler/train/TrainableOperationConverter.h
This commit enables converting some operations to trainable operations.
- Conv2D
- Reshape
- Softmax
=> [onert] Convert some operations to trainable.

runtime/onert/backend/train/BackendContext.cc
This commit generates trainable sequence for training backend.
=> [onert] Generate trainable sequence

runtime/onert/backend/train/TensorRegistry.h
This commit separates NativeTensor of TensorRegistry into NonConstTensor and TrainableTensor in train backend.
=> [onert] Separate NativeTensor of TensorRegistry in train backend

runtime/onert/backend/train/Tensor.cc, runtime/onert/backend/train/Tensor.h, runtime/onert/core/include/backend/train/ITrainableTensor.h
This commit introduce TrainableTensor into train backend.
=> [onert] Introduce TrainableTensor

infra/nncc/cmake/buildtool/config/config_aarch64-linux.cmake, infra/nncc/cmake/options/options_aarch64-linux.cmake
- add cmake buildtool configuration
- add cmake options
for: #11036 
draft: #10564
=> Add nncc cmake configurations for aarch64

runtime/onert/backend/train/Backend.h, runtime/onert/backend/train/BackendContext.cc, runtime/onert/backend/train/BackendContext.h, runtime/onert/backend/train/KernelGenerator.cc, runtime/onert/backend/train/KernelGenerator.h, runtime/onert/core/include/backend/train/TrainableBackendContext.h, runtime/onert/core/src/backend/builtin/Backend.h, runtime/onert/core/src/backend/builtin/train/BackendContext.cc, runtime/onert/core/src/backend/builtin/train/BackendContext.h, runtime/onert/core/src/backend/builtin/train/KernelGenerator.cc, runtime/onert/core/src/backend/builtin/train/KernelGenerator.h, runtime/onert/core/src/compiler/ExecutorFactory.cc, runtime/onert/core/src/compiler/TensorRegistries.h, runtime/onert/core/src/compiler/train/StaticDerivativeShapeInferer.cc, runtime/onert/core/src/compiler/train/StaticDerivativeShapeInferer.h, runtime/onert/core/src/compiler/train/TrainingCompiler.cc, runtime/onert/core/src/dumper/dot/DotDumper.cc
This commit changes the names from gradient to derivative.
=> [onert] Rename gradient

runtime/onert/backend/train/TensorManager.cc, runtime/onert/backend/train/TensorManager.h
This commit introduces TensorManager into train backend.
=> [onert] Introduce TensorManager into train backend

runtime/onert/frontend/base_loader/include/base_loader.h
This commit adds hybrid quantization loading with type fix for Conv and DepthwiseConv.
---
Related issue: #11047
=> [onert] Support hybrid quantization type fix on loader

tests/tools/onert_train/src/onert_train.cc
This commit prepares input and expected data for nnfw_train.
~~waiting #10988~~
=> [tools/onert_train] Prepare input and expected data for nnfw_train 

compiler/one-cmds/CMakeLists.txt, compiler/one-cmds/one-prepare-venv.u1804.aarch64
- intruduce one-prepare-venv.u1804.aarch64
for: #11036 
draft: #10564
=> Update one-cmds script for aarch64 support

runtime/onert/backend/train/Tensor.cc, runtime/onert/backend/train/Tensor.h, runtime/onert/core/include/backend/train/ITrainableTensor.h
This commit refines TrainableTensor.
- Introduce derivative tensor into TrainableTensor
- Remove applyGradient
=> [onert] Refine TrainableTensor

compiler/luci/pass/src/FuseGeluPass.cpp
This PR introduces GeluPatternBase class.
=> [luci/pass] Introduce GeluPatternBase

docs/howto/how-to-build-compiler.md
This will revise how-to-build-compiler file depending on different Ubuntu versions.
=> [docs] Revise how-to-build-compiler

tests/tools/onert_train/src/onert_train.cc
This commit trains a model by the number of epochs. One epoch performs repeated operations as much as the total data divided by batch_size, and each for loop trains the model using the nnfw_train function.
=> [tools/onert_train] Run nnfw_train

runtime/onert/api/src/nnfw_api_internal.cc
This commit implements train_run function.
This change invoke train or execute function depending on the user setting value for update_weights.
~~waiting #11030~~
=> [onert] Implement train_run function in nnfw internal api

runtime/onert/core/include/backend/train/ITensorRegistry.h
This commit introduces ITensorRegistry for training.
- Introduce ITensorRegistry for training
- Introduce a template for ITensorRegistry.
=> [onert] Introduce ITensorRegistry for training

runtime/onert/core/include/exec/train/optimizer/OptimizerCode.h, runtime/onert/core/src/exec/train/optimizer/OptimizerCode.cc
This commit introduces OptimizerCode.
=> [onert] Introduce OptimizerCode

runtime/onert/core/src/compiler/train/TensorRegistries.h
This commit introduces TensorRegistries for training.
=> [onert] Introduce TensorRegistries for training

runtime/onert/core/include/exec/train/optimizer/Optimizer.h
This commit introduces Optimizer to be the base class of optimizers.
=> [onert] Introduce Optimizer

runtime/onert/core/src/exec/train/optimizer/OptimizerHelpers.h
This commit intorudces Optimizer helper functions.
=> [onert] Intoroduce OptimizerHelpers

runtime/onert/core/include/exec/train/optimizer/SGD.h, runtime/onert/core/src/exec/train/optimizer/SGD.cc
This commit introduces SGD optimizer.
=> [onert] Introduce SGD optimizer

runtime/onert/backend/train/BackendContext.cc
This commit allocates derivative tensors in train backend.
Draft: #11035
=> [onert] Allocate deriv tensor in train backend

compiler/luci-interpreter/pal/linux/pal.cmake
- Select kernel source by TARGET_ARCH or CMAKE_SYSTEM_PROCESSOR
=> [luci-interpreter] Revise arm target architecture selection method during kernel build

runtime/onert/core/include/compiler/train/TrainingInfo.h, runtime/onert/core/src/compiler/train/TrainingCompiler.cc
This commit makes TrainingCompiler create SGD optimizer.
- Introduce TrainingInfo
- Create default SGD optimizer
=> [onert] Create SGD optimizer

runtime/onert/core/src/backend/builtin/train/KernelGenerator.cc, runtime/onert/core/src/backend/builtin/train/kernel/PermuteLayer.cc, runtime/onert/core/src/backend/builtin/train/kernel/PermuteLayer.h
This commit implements train Permute kernel.
=> [onert] Implement train Permute kernel

runtime/onert/backend/train/Backend.h, runtime/onert/backend/train/BackendContext.cc, runtime/onert/backend/train/BackendContext.h, runtime/onert/backend/train/KernelGenerator.cc, runtime/onert/backend/train/KernelGenerator.h, runtime/onert/backend/train/Tensor.h, runtime/onert/backend/train/TensorBuilder.cc, runtime/onert/backend/train/TensorBuilder.h, runtime/onert/backend/train/TensorManager.cc, runtime/onert/backend/train/TensorManager.h, runtime/onert/backend/train/TensorRegistry.h
This commit introduces unified TensorBuilder into train backend.
=> [onert] Introduce unified TensorBuilder into train backend

docs/release/1.24/index.rst, docs/release/1.24/release-note-1.24.0.md
This commit is a release note for 1.24.0.
Related: #11085 
=> Release note 1.24.0

compiler/luci/pass/src/FuseGeluPass.cpp
This PR revises FuseGelu class to use GeluPatternBase class
=> [luci/pass] Revise FuseGelu class

runtime/onert/api/src/nnfw_api_internal.cc
This commit sets optimizer as SGD.
=> [onert] Set optimizer as SGD

runtime/onert/backend/train/Backend.h, runtime/onert/backend/train/KernelGenerator.cc, runtime/onert/backend/train/KernelGenerator.h, runtime/onert/core/include/backend/train/TrainableBackendContext.h, runtime/onert/core/src/compiler/ExecutorFactory.cc, runtime/onert/core/src/compiler/ExecutorFactory.h, runtime/onert/core/src/compiler/train/TrainingCompiler.cc
This commits makes KernelGenerator in train backend can use optimizer.
=> [onert] Pass optimizer to KernelGenerator

runtime/onert/core/src/compiler/train/StaticDerivativeShapeInferer.cc
This commit adds inferring derivative shape of Permute.
=> [onert] Infer derivative shape of Permute

runtime/onert/backend/train/KernelGenerator.cc, runtime/onert/backend/train/KernelGenerator.h, runtime/onert/backend/train/ops/ElementwiseActivationLayer.cc, runtime/onert/backend/train/ops/ElementwiseActivationLayer.h
This commit introduces ElementwiseActivationLayer in train kernel.
Draft: #11035
=> [onert] Introduce ElementwiseActivationLayer in train kernel

compiler/tflchef/core/src/CustomOp/Erf.cpp, compiler/tflchef/core/src/CustomOp/Erf.h
This will introduice two ErfChef and ErfChefFactory classes to chef Custom(Erf).
=> [tflchef] Introduce ErfChef and ErfChefFactory

res/TensorFlowLiteRecipes/Net_Gelu_000/test.recipe, res/TensorFlowLiteRecipes/Net_Gelu_000/test.rule, res/TensorFlowLiteRecipes/Net_Gelu_001/test.recipe, res/TensorFlowLiteRecipes/Net_Gelu_001/test.rule
This will introduce Net_Gelu recipes for FuseGeluPass testing.
=> [res] Introduce Net_Gelu for FuseGeluPass test

compiler/luci/pass/src/FuseGeluPass.cpp
This PR introduces GeluPattern2.
from draft: #11016
=> [luci/pass] Introduce GeluPattern2

compiler/luci/pass/src/RequantizePass.cpp
This removes unnecessary codes in the file.
---
Related to: #11109
=> [luci] Remove unnecessary codes

compiler/luci/pass/src/FuseAddWithFullyConnectedPass.test.cpp, compiler/luci/pass/src/QuantizeBias.test.cpp, compiler/luci/pass/src/ReplaceNonConstFCWithBatchMatMulPass.test.cpp, compiler/luci/pass/src/RequantizePass.test.cpp, compiler/luci/pass/src/ResolveCustomOpMatMulPass.cpp, compiler/luci/pass/src/SubstituteSplitVToSplitPass.test.cpp, compiler/luci/pass/src/helpers/CreateCircleConst.cpp, compiler/luci/pass/src/helpers/CreateCircleConst.h
This extracts create_const_node function to reduce duplicate codes.
=> [luci] Extract create_const_node function

compiler/luci/pass/include/luci/Pass/RequantizePass.h, compiler/luci/pass/src/RequantizePass.cpp
This revises RequantizePass.
- Add comments
- Use proper casting
=> [luci] Revise RequantizePass

runtime/onert/backend/train/BackendContext.cc, runtime/onert/core/include/backend/basic/train/TrainableBackendContextHelpers.h
This commit initialize TrainableTensors in train backend.
=> [onert] Initialize TrainableTensors in train backend

runtime/onert/api/src/nnfw_api_internal.cc, runtime/onert/api/src/nnfw_api_internal.h, runtime/onert/backend/train/ops/ConvolutionLayer.cc, runtime/onert/backend/train/ops/ConvolutionLayer.h, runtime/onert/backend/train/ops/ElementwiseActivationLayer.cc, runtime/onert/backend/train/ops/ElementwiseActivationLayer.h, runtime/onert/backend/train/ops/PoolLayer.cc, runtime/onert/backend/train/ops/PoolLayer.h, runtime/onert/core/include/exec/Execution.h, runtime/onert/core/include/exec/train/ITrainableFunction.h, runtime/onert/core/include/exec/train/TrainableFnSequence.h, runtime/onert/core/src/backend/builtin/train/kernel/PermuteLayer.cc, runtime/onert/core/src/backend/builtin/train/kernel/PermuteLayer.h, runtime/onert/core/src/exec/Execution.cc, runtime/onert/core/src/exec/train/TrainableExecutor.cc, runtime/onert/core/src/exec/train/TrainableExecutor.h, runtime/onert/core/src/exec/train/TrainableExecutors.cc, runtime/onert/core/src/exec/train/TrainableExecutors.h, runtime/onert/core/src/exec/train/TrainableFnSequence.cc
This commit introduces training step.
- Introduce training step into nnfw_session
- Pass training step to ITrainableFunction
=> [onert] Introduce training step

compiler/luci/pass/src/FuseGeluPass.cpp, compiler/luci/pass/src/FuseGeluPass.test.cpp
This PR enables GeluPattern2 and adds tests.
=> [luci/pass] Enable GeluPattern2

compiler/tflchef/tflite/src/Op/PRelu.cpp
This adds filler to PRelu.
---
Draft PR: #11155
=> [tflchef] Add filler to PRelu

compiler/souschef/include/souschef/Data/Gaussian.h, compiler/souschef/src/Gaussian.cpp, compiler/souschef/src/LexicalCast.cpp
This supports int8 data generation.
---
=> [souschef] Support int8 data generation

runtime/onert/backend/train/KernelGenerator.cc, runtime/onert/backend/train/KernelGenerator.h, runtime/onert/backend/train/ops/GradientApplier.cc, runtime/onert/backend/train/ops/GradientApplier.h
This commit introduces GradientApplier layer.
- Introduce GradientApplier
- Add generating GradientApplier for Conv2D
=> [onert] Introduce GradientApplier layer

infra/debian/compiler/one-compiler.install
This installs visq DotBuilder.py lib.
=> [infra] Install visq Dot builder lib

compiler/circle-quantizer-dredd-recipe-test/CMakeLists.txt, compiler/circle-quantizer-dredd-recipe-test/test.lst
This adds tests for requantize.
---
=> [circle-quantizer-dredd] Add requantize tests

docs/conf.py, packaging/nnfw.spec, runtime/contrib/android/api/build.gradle, runtime/onert/api/include/nnfw_version.h
This commit updates runtime version to 1.25.0.
=> [onert] Update version to 1.25.0

compiler/one-cmds/one-quantize
This adds requantize option to one-quantize.
---
=> [one-cmds] Add requantize option to one-quantize

runtime/onert/api/src/nnfw_api_internal.cc
This commit uses try block in train_prepare.
Draft: #11035
=> [onert] Use try block in train_prepare

runtime/onert/api/src/nnfw_api_internal.cc
This commit compares tensor size in train_set_input to verify that the tensor info has changed. If the tensor info is changed, it is not supported in this case.
draft: #11035
=> [onert] Compare tensor size in train_set_input

compiler/onecc-docker/onecc-docker
This commit sets
- 5 sec timeout for github api request to get release version
- 30 set timeout for docker image build
----
Related to #11134
=> [onecc-docker] Set timeout

runtime/onert/api/src/nnfw_api_internal.cc
This commit sets loss info to training info.
Draft : #11035 
~~waiting: #11118~~
=> [onert] Set loss info to training info 

infra/nncc/cmake/buildtool/config/config_aarch64-tizen.cmake, infra/nncc/cmake/buildtool/config/config_armv7hl-tizen.cmake, infra/nncc/cmake/buildtool/config/config_armv7l-tizen.cmake, infra/nncc/cmake/buildtool/config/config_i686-tizen.cmake, infra/nncc/cmake/buildtool/config/config_x86_64-tizen.cmake, infra/nncc/cmake/options/options_aarch64-tizen.cmake, infra/nncc/cmake/options/options_armv7hl-tizen.cmake, infra/nncc/cmake/options/options_armv7l-tizen.cmake, infra/nncc/cmake/options/options_i686-tizen.cmake, infra/nncc/cmake/options/options_x86_64-tizen.cmake
This commit introduces nncc cmake build option and toolchain config for tizen gbs build.
---
Related issue: #11117
Draft: #11050
=> [infra] Introduce nncc tizen build option and config

runtime/onert/backend/train/KernelGenerator.cc, runtime/onert/backend/train/ops/LossLayer.cc, runtime/onert/backend/train/ops/LossLayer.h
This commit introduces LossLayer in train kernel.
draft: #11035
=> [onert] Introduce LossLayer in train kernel

runtime/onert/core/src/compiler/train/TrainingCompiler.cc
This commit inserts default derivative operands into trainable graph.
=> [onert] Insert default derivative operands

runtime/onert/api/src/nnfw_api_internal.cc
This commit sets optimizer info to training info.
Draft: #11035
=> [onert] Set optimizer info to training info

compiler/luci/export/src/CircleBuiltinTypesExtractor.h, compiler/luci/export/src/CircleOps.lst
Support HardSwish operation in luci/export
---
=> [luci/export] Support HardSwish operation

infra/debian/compiler/one-compiler.install
This adds circle python interface to package.
=> [infra] Install circle python interface

compiler/luci/import/include/luci/Import/Nodes.h, compiler/luci/import/include/luci/Import/Nodes/CircleHardSwish.h, compiler/luci/import/src/GraphBuilderRegistry.cpp, compiler/luci/import/src/Nodes/CircleHardSwish.cpp
Support HardSwish operation in luci/import
---
=> [luci/import] Support HardSwish operation

compiler/luci/service/include/luci/Service/CircleShapeInference.h, compiler/luci/service/include/luci/Service/CircleTypeInference.h, compiler/luci/service/src/CircleCloneNode.h, compiler/luci/service/src/CircleShapeInferenceRule.cpp, compiler/luci/service/src/CircleTypeInferenceRule.cpp, compiler/luci/service/src/Nodes/CircleHardSwish.cpp, compiler/luci/service/src/Nodes/CircleHardSwish.test.cpp
Support HardSwish operation in luci/service
---
=> [luci/service] Support HardSwish operation

compiler/luci/import/src/GraphBuilderRegistry.cpp
Some of comments have been cleaned up
- Commas deleted
- Unnecessary comments deleted
---
=> [luci/import] Clean up some comments

infra/docker/focal/Dockerfile
This commit installs android sdk in ubuntu focal image. 
It is installed in ubuntu bionic but we will be end to support ubuntu bionic image.
=> [infra/docker] Install android sdk

runtime/onert/core/src/compiler/ExecutorFactory.cc, runtime/onert/core/src/exec/train/TrainableExecutor.cc
This commit restores IOTensors for outputs of graph.
=> [onert] Restore IOTensors for outputs of graph

res/TensorFlowLiteRecipes/HardSwish_000/test.recipe
Support HardSwish operation in res
---
=> [res] Support HardSwish operation

compiler/visq/visq
This commit revisits 'visq' batch mode for `rawData`.
Draft: #11179
Related: #11146 
=> [one-cmds] Revisit 'visq' batch mode

compute/cker/include/cker/operation/ReLU.h, compute/cker/src/Relu.test.cc
This commit introduces a kernel that computes gradient of relu.
=> [cker] Introduce a kernel that computes gradient of relu

runtime/onert/core/src/compiler/ExecutorFactory.cc
This commit adds derivatives into partial graphs for each backend.
=> [onert] Add derivatives into partial graphs for each backend

runtime/onert/backend/train/KernelGenerator.cc, runtime/onert/backend/train/KernelGenerator.h
This commit applies FullyconnectedLayer for training.
=> [onert] Apply FullyconnectedLayer for training

compute/cker/include/cker/train/operation/Loss.h, compute/cker/src/train/Loss.test.cc, runtime/onert/backend/train/ops/LossLayer.cc
This commit implement Loss MSE function for training. And it introduces Loss cker and implement MSE function.
Draft: #11035
=> [onert] Implement Loss MSE function for training

tools/cross/install_rootfs.sh
This commit updates install_rootfs.sh.
- Remove tizen rootfs install argument
- Change default ubuntu version
=> [tools/rootfs] Update rootfs install script

compiler/luci/pass/include/luci/CircleOptimizer.h, compiler/luci/pass/include/luci/Pass/DecomposeHardSwishPass.h, compiler/luci/pass/src/CircleOptimizer.cpp, compiler/luci/pass/src/DecomposeHardSwishPass.cpp, compiler/luci/pass/src/DecomposeHardSwishPass.test.cpp
Decompose the HardSwish operation to Add, Mul and Relu6 operations.
--- 
Draft PR: #11220
=> [luci/pass] Support HardSwish decomposing pass

tests/tools/onert_train/src/onert_train.cc
This commit runs whole training step in EXECUTE benchmark phase to measure memory and time usage of whole training step.
Draft: #11035
=> [tools/onert_train] Run whole training in EXECUTE benchmark phase

runtime/onert/core/include/exec/Execution.h, runtime/onert/core/src/exec/Execution.cc
This commit implements getLoss function in Execution.
Draft: #11035
=> [onert] Implement getLoss function in Execution

docs/howto/how-to-cross-build-runtime-for-arm.md
This commit updates runtime cross build how-to documentation.
=> [doc] Update onert cross build documentation

runtime/onert/backend/cpu/ops/ElementwiseActivationLayer.h, runtime/onert/backend/train/ops/ElementwiseActivationLayer.cc, runtime/onert/backend/train/ops/ElementwiseActivationLayer.h
This commit applies ReLUGrad to ElementwiseActivationLayer.
=> [onert] Apply ReLUGrad to ElementwiseActivationLayer

compiler/common-artifacts/CMakeLists.txt
This will prepare python venv with TensorFlow 2.12.1.
=> [common-artifacts] Prepare venv with TF2.12.1

compiler/luci-value-test/CMakeLists.txt
This will upgrade test environment TF to 2.12.1.
=> [luci-value-test] Upgrade TF to 2.12.1

compiler/dalgona-test/CMakeLists.txt
=> [dalgona-test] Upgrade TF to 2.12.1

compiler/visq-unittest/CMakeLists.txt
This will upgrade test environment TF to 2.12.1.
=> [visq-unittest] Upgrade TF to 2.12.1

compiler/dalgona-test/CMakeLists.txt
=> [dalgona-test] Tidy test on Jammy

compiler/luci-value-test/CMakeLists.txt
=> [luci-value-test] Tidy test on Jammy

compiler/circle-part-value-test/CMakeLists.txt
=> [circle-part-value-test] Tidy test on Jammy

compiler/luci-pass-value-test/CMakeLists.txt
=> [luci-pass-value-test] Tidy test on Jammy

compiler/luci/pass/include/luci/CircleQuantizer.h, compiler/luci/pass/src/CircleQuantizer.cpp
It introduces QuantizeWeights algorithm with empty implementation.
Related: #11073, #11057
=> [luci/pass] Introduce Algorithm:QuantizeWeights

compiler/record-minmax-conversion-test/CMakeLists.txt
=> [record-minmax-conv-test] Tidy test on Jammy

compiler/record-minmax-thread-safety-test/CMakeLists.txt
=> [record-minmax-thread-safety-test] Tidy test on Jammy

compiler/visq-unittest/CMakeLists.txt
=> [visq-unittest] Tidy test on Jammy

compiler/one-cmds/one-prepare-venv
This will update one-prepare-venv packages.
- related packages version are fixed to follow TF release date
=> [one-cmds] Update one-prepare-venv packages

compiler/common-artifacts/CMakeLists.txt
This will remove Jammy specific python environment.
=> [one-cmds] Remove Jammy specific python environment

compiler/one-cmds/one-import-onnx
This will refactor _remap_io_names method with new TidyIONames class.
=> [one-cmds] Refactor _remap_io_names

tests/tools/onert_train/src/onert_train.cc
This commit shows average loss value per epoch.
Draft: #11035
=> [tools/onert_train] Show average loss per epoch

compiler/circle-quantizer/src/CircleQuantizer.cpp
It introduces --quantize_weights option in circle-quantizer. It parses args and set parameters for luci/circle-quantizer pass.
Related: https://github.com/Samsung/ONE/pull/11073, https://github.com/Samsung/ONE/issues/11057
=> [circle-quantizer] Introduce --quantize_weights option

compiler/common-artifacts/CMakeLists.txt
This will remove preparartion of venv with TF2.8.0.
=> [common-artifacts] Remove venv with TF2.8.0

runtime/onert/backend/train/ops/FullyConnectedLayer.cc
This commit fixes wrong shapes in FullyConnectedLayer for training.
- Fixes transposed tensors to have correct shape.
=> [onert] Fix wrong shapes in FullyConnectedLayer for training

packaging/nnfw.spec
This commit updates build command to use parallel build option.
- Use 'nproc' define gbs build option
- Otherwise, use default '_smp_mflags' and 'jobs' value based on number of system threads
=> [infra/gbs] Use parallel build option

compiler/tflite2circle/src/CircleModel.cpp
This will tidy reserved format changes.
=> [tflite2circle] Tidy format changes

compiler/circledump/src/OpPrinter.cpp
This will rename variable to follow like other ops.
=> [circledump] Rename variable

tests/tools/onert_train/src/onert_train.cc
This commit changes the variable name from num_sample to num_step.
=> [tools/onert_train] Change variable name

nnpackage/schema/circle_schema.fbs
This commit updates schema to support more ops and options.
---
Related issue: #11381
=> [nnpackage] Update circle schema to 0.6

res/TensorFlowLiteSchema/2.12.1/schema.fbs
This will introduce tflite schema from 2.12.1.
=> [res] Introduce tflite schema from 2.12.1

res/CircleSchema/0.6/circle_schema.fbs
This will introduce circle schema 0.6.
=> [res] Introduce circle schema 0.6

tools/generate_datafile/tf_dataset_converter/README.md, tools/generate_datafile/tf_dataset_converter/argparser.py, tools/generate_datafile/tf_dataset_converter/datasets.py, tools/generate_datafile/tf_dataset_converter/main.py, tools/generate_datafile/tf_dataset_converter/requirements.txt
This commit introduces a tool, tf dataset converter, which converts tensorflow datasets to datasets for `onert_train`. In this commit only mnist datasets were tested.
=> [tools] Introduce tf dataset converter

runtime/onert/api/include/nnfw_experimental.h, runtime/onert/api/src/nnfw_api.cc, runtime/onert/api/src/nnfw_api_internal.cc, runtime/onert/api/src/nnfw_api_internal.h
This commit introduces online weight quantization nnfw API.
---
Related issue: #11391
Draft: #11298
=> [onert] Introduce weight quantization API

compiler/record-minmax/driver/Driver.cpp, compiler/record-minmax/include/RecordMinMax.h, compiler/record-minmax/src/RecordMinMax.cpp
This removes unused function and arguments.
=> [record-minmax] Remove unused code

compiler/circle-inspect/CMakeLists.txt, compiler/circle-inspect/requires.cmake
=> [circle-inspect] Revise to use mio-circle06

compiler/circledump/CMakeLists.txt, compiler/circledump/README.md, compiler/circledump/requires.cmake
=> [circledump] Revise to use mio-circle06

compiler/circle-operator/CMakeLists.txt, compiler/circle-operator/requires.cmake
=> [circle-operator] Revise to use mio-circle06

compiler/circle-verify/CMakeLists.txt, compiler/circle-verify/requires.cmake
=> [circle-verify] Revise to use mio-circle06

compiler/circle-tensordump/CMakeLists.txt, compiler/circle-tensordump/requires.cmake
=> [circle-tensordump] Revise to use mio-circle06

compiler/tflite2circle/CMakeLists.txt, compiler/tflite2circle/requires.cmake, compiler/tflite2circle/src/CircleModel.cpp
This will revise to use new mio-circle06, mio-tflite2121.
=> [tflite2circle] Revise to use new mio

packaging/nnfw.spec
This commit adds to mio-circle06 build list to prepare circle version up.
=> [infra/gbs] Update nncc build list for mio-circle06

compiler/record-minmax/CMakeLists.txt, compiler/record-minmax/include/RecordFunction.h, compiler/record-minmax/src/RecordFunction.cpp
This separates RecordFunction.h to .h and .cpp.
---
Related to: https://github.com/Samsung/ONE/pull/11410#issuecomment-1700518870
=> [record-minmax] Separate RecordFunction.h

compiler/pics/CMakeLists.txt, compiler/pics/requires.cmake
=> [pic] Revise to use mio-circle06

compiler/circledump/src/OpPrinter.cpp
This will enable to print TransposeConv activation function.
=> [circledump] Print TransposeConv ActFunc

compiler/tflchef/core/src/Op/TransposeConv.cpp, compiler/tflchef/proto/tflchef.proto, compiler/tflchef/tflite/src/Op/TransposeConv.cpp
This will revise to support TransposeConv activation.
=> [tflchef] Support TransposeConv activation

res/TensorFlowLiteRecipes/Net_TConv_Add_000/test.recipe, res/TensorFlowLiteRecipes/Net_TConv_Add_001/test.recipe, res/TensorFlowLiteRecipes/Net_TConv_Add_002/test.recipe, res/TensorFlowLiteRecipes/Net_TConv_BN_000/test.recipe, res/TensorFlowLiteRecipes/Net_TConv_BN_001/test.recipe, res/TensorFlowLiteRecipes/Net_TConv_BN_002/test.recipe, res/TensorFlowLiteRecipes/Net_TConv_BN_003/test.recipe, res/TensorFlowLiteRecipes/Net_TConv_BN_004/test.recipe, res/TensorFlowLiteRecipes/Net_TConv_BN_005/test.recipe, res/TensorFlowLiteRecipes/Quant_TransposeConv_000/test.recipe, res/TensorFlowLiteRecipes/Quant_TransposeConv_001/test.recipe, res/TensorFlowLiteRecipes/Quant_TransposeConv_I8_000/test.recipe, res/TensorFlowLiteRecipes/TransposeConv_000/test.recipe, res/TensorFlowLiteRecipes/TransposeConv_001/test.recipe
This will add activation option to TransposeConv recipes.
=> [res] Add activation to TransposeConv recipes

compute/cker/include/cker/PortableTensorUtils.h
It introduces PortableAsymmetricQuantizeFloats.
Implementation is copied from TensorFlow.
Related: https://github.com/Samsung/ONE/issues/11454, https://github.com/Samsung/ONE/pull/11318
=> [onert/cker] Introduce PortableAsymmetricQuantizeFloats

compiler/record-minmax/include/MinMaxComputer.h, compiler/record-minmax/include/MinMaxObserver.h, compiler/record-minmax/include/RecordMinMax.h, compiler/record-minmax/src/MinMaxComputer.cpp, compiler/record-minmax/src/RecordMinMax.cpp
This updates function signature of update_qparam.
=> [record-minmax] Update function signature

onert-micro/luci-interpreter/pal/common/PALReduceCommon.h, onert-micro/luci-interpreter/src/kernels/ReduceCommon.cpp
- Remove problematic parts from source
- Move unused variable inside function
=> [onrt-micro] Fix buffer overflow warning in svace

runtime/onert/api/src/nnfw_api_internal.cc, runtime/onert/api/src/nnfw_api_internal.h, runtime/onert/core/include/ir/NNPkg.h, runtime/onert/core/include/odc/QuantizeManager.h, runtime/onert/core/src/odc/QuantizeManager.cc, runtime/onert/core/src/odc/QuantizeManager.test.cc
This commit introduces QuantizeManager.
It is uses by nnfw API.
---
Related issue: https://github.com/Samsung/ONE/issues/11391
Draft: https://github.com/Samsung/ONE/pull/11298
=> [onert] Introduce QuantizeManager

runtime/onert/backend/train/ops/ConvolutionLayer.cc, runtime/onert/backend/train/ops/ConvolutionLayer.h, runtime/onert/backend/train/ops/ElementwiseActivationLayer.cc, runtime/onert/backend/train/ops/ElementwiseActivationLayer.h, runtime/onert/backend/train/ops/FullyConnectedLayer.cc, runtime/onert/backend/train/ops/FullyConnectedLayer.h, runtime/onert/backend/train/ops/LossLayer.cc, runtime/onert/backend/train/ops/LossLayer.h, runtime/onert/backend/train/ops/PoolLayer.cc, runtime/onert/backend/train/ops/PoolLayer.h, runtime/onert/backend/train/ops/ReshapeLayer.cc, runtime/onert/backend/train/ops/ReshapeLayer.h, runtime/onert/core/include/exec/train/ITrainableFunction.h, runtime/onert/core/include/exec/train/TrainableFnSequence.h, runtime/onert/core/src/backend/builtin/train/kernel/PermuteLayer.cc, runtime/onert/core/src/backend/builtin/train/kernel/PermuteLayer.h, runtime/onert/core/src/exec/train/TrainableFnSequence.cc
This commit removes training step from ITrainableFunction.
=> [onert] Remove training step from ITranableFunction

onert-micro/luci-interpreter/include/luci_interpreter/TrainingSettings.h
This commit introduces TrainingSettings class.
=> [onert-micro] Introduce TrainingSettings class

compiler/tflite2circle/src/BuildBuiltinOptions/TransposeConvOptions.cpp
This will enable to set TransposeConv activation.
=> [tflite2circle] Set TransposeConv activation

infra/packaging/preset/20230907, infra/packaging/preset/20230907_windows, infra/packaging/res/tf2nnpkg.20230907
This will introduce preset 20230907 and corresponding tf2nnpkg.20230907.
=> [infra] preset 20230907

docs/release/1.25/index.rst, docs/release/1.25/release-note_1.25.0.md
This commit is a release note for 1.25.0.
---
Related issue: #11484
=> Release note 1.25.0

onert-micro/luci-interpreter/include/luci_interpreter/onert-micro-version.h
- Update onert-micro version file to use version 1.0
=> [onert-micor] Update onert-micro verison to 1.0

docs/release/onert-micro/1.0/release-note-1.0.0.md
- Release Note added for onert-micro 1.0
=> [onert-micr] Release Note for 1.0.0

runtime/onert/core/src/exec/IPermuteFunction.test.cc
This commit merges similar test functions in IPermuteFunction.test.cc.
---
For reviewer: Please use "Hide whitespace" option to reduce diff.
=> [onert/test] Merge test function

infra/debian/compiler/rules, infra/packaging/build
This will revise compiler preset to use 20230907.
=> [infra] Revise compiler preset

onert-micro/luci-interpreter/include/luci_interpreter/TrainableWeightStorage.h, onert-micro/luci-interpreter/src/core/CMakeLists.txt, onert-micro/luci-interpreter/src/core/TrainableWeightStorage.cpp
This commit introduces Trainable weight storage class.
=> [onert-micro] Introduce Trainable weight storage

runtime/onert/api/src/nnfw_api_internal.cc, runtime/onert/core/include/compiler/train/TrainingInfo.h, runtime/onert/core/include/ir/train/OptimizerCode.h, runtime/onert/core/include/ir/train/OptimizerInfo.h, runtime/onert/core/src/compiler/train/TrainingCompiler.cc, runtime/onert/core/src/ir/train/OptimizerCode.cc
This commit moves OptimizerCode and OptimizerInfo into ir.
=> [onert] Move OptimizerCode and OptimizerInfo into ir

onert-micro/luci-interpreter/src/core/CMakeLists.txt, onert-micro/luci-interpreter/src/core/GradientCalculationStorage.cpp, onert-micro/luci-interpreter/src/core/GradientCalculationStorage.h
This commit introduces Gradient calculation storage class.
=> [onert-micro] Introduce Gradient calculation storage

compiler/onecc-docker/README.md, compiler/onecc-docker/debian/control, compiler/onecc-docker/docker/Dockerfile, compiler/onecc-docker/onecc-docker
This commit updates `onecc-doecker` command.
- Change ubuntu version to 20.04
- Update python version requirement
=> [onecc-docker] Revisit onecc-docker command

onert-micro/luci-interpreter/src/kernels/FullyConnected.train.cpp
This commit introduces FullyConnected train kernel.
=> [onert-micro] Introduce FullyConnected train kernel

compiler/q-implant/CMakeLists.txt, compiler/q-implant/driver/Driver.cpp, compiler/q-implant/include/QImplant.h, compiler/q-implant/requires.cmake
This will introduce the initial driver implementation for q-implant.
ONE-DCO-1.0-Signed-off-by: Minyoung Jeong <darkard37@gmail.com>
=> [q-implant] q-implant Driver Implementation

onert-micro/CMakeLists.txt, onert-micro/eval-driver/CMakeLists.txt, onert-micro/eval-driver/TrainingDriver.cpp, onert-micro/luci-interpreter/CMakeLists.txt
This commit introduces TrainingDriver module for onert-micro.
=> [onert-micro] Introduce TrainingDriver

compiler/q-implant/README.md, compiler/q-implant/src/QImplant.cpp
This commit will enable `q-implant`.
ONE-DCO-1.0-Signed-off-by: Jaehong Ju <wnwoghd22@gmail.com>
=> [q-implant] q-implant implementation

compiler/circle-mpqsolver/src/bisection/DepthParameterizer.test.cpp, compiler/circle-mpqsolver/src/core/Quantizer.test.cpp, compiler/circle-mpqsolver/src/core/TestHelper.h
This commit uses NHWC layout in tests.
Draft: #11452
=> [circle-mpqsolver] Fix layout in tests

onert-micro/luci-interpreter/pal/cmsisnn/PALSoftmax.h, onert-micro/luci-interpreter/pal/common/PALSoftmaxCommon.h, onert-micro/luci-interpreter/pal/common/Params.h, onert-micro/luci-interpreter/pal/mcu/PALSoftmax.h, onert-micro/luci-interpreter/src/kernels/Softmax.cpp
This commit adds cmsis-nn Softmax kernels for onert-micro.
for issue: #11211 
=> [onert-micro] Add cmsis-nn Softmax kernels

infra/nnfw/python/README.md, infra/nnfw/python/nnfwapi/__init__.py, infra/nnfw/python/nnfwapi/libnnfw_api_pybind.py, infra/nnfw/python/pack.sh, infra/nnfw/python/setup.py
This commit adds code for making and publishing nnfwapi package including NNFW Python API module.
for #11368 
ONE-DCO-1.0-Signed-off-by: KangInyeong kiyoog02@gmail.com
Co-authored-by: jaemaning lovesay00@naver.com
Co-authored-by: phj799 phj799@naver.com
Co-authored-by: seohhh shy1624@naver.com
Co-authored-by: blue4683 an4683@gmail.com
Co-authored-by: jeonghwanin jhpc0128@naver.com
=> [onert] Add Package of NNFW Python API

compiler/circle-quantizer/src/CircleQuantizer.cpp
This will revise to use LayerParams alias.
=> [circle-quantizer] Use LayerParams

res/TensorFlowLiteRecipes/Net_FC_Gelu_FC_000/test.recipe, res/TensorFlowLiteRecipes/Net_FC_Gelu_FC_000/test.rule
This adds recipe and rule for Net_FC_Gelu_FC_000.
---
=> [res] Add Net_FC_Gelu_FC_000

onert-micro/luci-interpreter/pal/mcu/PALMinimum.h
This commit renames include guard in PALMinimum.h
=> [onert-micro] Rename include guard in PALMinimum.h

compiler/luci/pass/src/CircleQuantizer.cpp
This will explictly include std headers.
=> [luci/pass] Explicit include std headers

compiler/luci/pass/include/luci/Pass/ReplaceWithFCGeluFCPass.h, compiler/luci/pass/src/ReplaceWithFCGeluFCPass.cpp, compiler/luci/pass/src/ReplaceWithFCGeluFCPass.test.cpp
This introduces ReplaceWithFCGeluFCPass and its test.
---
Draft PR: #11604
=> [luci] Introduce ReplaceWithFCGeluFCPass 

compiler/circle-quantizer/src/CircleQuantizer.cpp
This will extract QConfReader for reading qconf json file.
=> [circle-quantizer] Extract QConfReader

compiler/circle-quantizer/src/CircleQuantizer.cpp
This will tidy unused code that was replaced with QConfReader.
=> [circle-quantizer] Tidy unused code

compiler/circle2circle/src/Circle2Circle.cpp
This adds a new replace_with_fc_gelu_fc option.
---
=> [circle2circle] Add replace_with_fc_gelu_fc option

compiler/q-implant/README.md
This commit updates the additional description and structure of qparam.json and npy files on q-implant README.md.
ONE-DCO-1.0-Signed-off-by: Junyeong Kang kjy6135@naver.com
=> [q-implant] q-implant README update

compiler/one-cmds/onelib/constant.py
This adds a new optimization option replace_with_fc_gelu_fc.
---
=> [one-cmds] Add replace_with_fc_gelu_fc optimization option

compiler/luci/pass/src/CircleQuantizer.test.cpp
This will add some unit tests for layer_params_set() and quantize.
=> [luci/pass] Add unit tests for layer_params_set

compiler/luci/pass/src/ReplaceWithFCGeluFCPass.cpp, compiler/luci/pass/src/ReplaceWithFCGeluFCPass.test.cpp
This supports FC with bias pattern in ReplaceWithFCGeluFCPass.
---
=> [luci] Support FC with bias in ReplaceWithFCGeluFCPass

compiler/q-implant-qparam-test/CMakeLists.txt, compiler/q-implant-qparam-test/README.md, compiler/q-implant-qparam-test/q_implant_qparam_test.py, compiler/q-implant-qparam-test/q_implant_qparam_test.sh, compiler/q-implant-qparam-test/q_implant_validator.py, compiler/q-implant-qparam-test/requires.cmake, compiler/q-implant-qparam-test/test_utils.py
This introduces q-implant-qparam-test to check qparam is correctly implanted.
ONE-DCO-1.0-Signed-off-by: Seonguk Park tjddnr011012@gmail.com
=> [q-implant-qparam-test] Introduce q-implant-qparam-test

runtime/onert/backend/train/Backend.h, runtime/onert/backend/train/BackendContext.h, runtime/onert/backend/train/KernelGenerator.cc, runtime/onert/backend/train/KernelGenerator.h, runtime/onert/backend/train/TensorBuilder.cc, runtime/onert/backend/train/TensorBuilder.h, runtime/onert/backend/train/ops/GradientApplier.h, runtime/onert/backend/train/optimizer/OptimizerHelpers.h, runtime/onert/backend/train/optimizer/Optimizers.h, runtime/onert/backend/train/optimizer/SGD.cc, runtime/onert/backend/train/optimizer/SGD.h, runtime/onert/core/include/backend/train/TrainableBackendContext.h, runtime/onert/core/src/compiler/ExecutorFactory.cc, runtime/onert/core/src/compiler/ExecutorFactory.h, runtime/onert/core/src/compiler/train/TrainingCompiler.cc
Thsi commit moves SGD optimizer into train backend.
=> [onert] Move SGD optimizer into train backend

compiler/luci/pass/src/ConvertToFakeQuantizedModelPass.cpp
This support fake quantization of Maximum/Minimum Ops
=> [luci] Fake quantize Maximum/Minimum

compute/cker/include/cker/eigen/training_ops.h, compute/cker/include/cker/train/optimizer/Adam.h, compute/cker/src/train/Adam.test.cc
This commit brings Adam optimizer kernel from tensorflow v2.12.1.
=> [cker] Bring Adam kernel from tensorflow v2.12.1

runtime/onert/core/include/exec/MinMaxMap.h, runtime/onert/core/src/dumper/h5/MinMaxDumper.cc, runtime/onert/core/src/dumper/h5/MinMaxDumper.h, runtime/onert/core/src/exec/MinMaxRecorder.cc, runtime/onert/core/src/exec/MinMaxRecorder.h
It adds subgraph input recording.
Related: #11517
=> [onert] Record subgraph input's minmax

runtime/onert/backend/train/TensorBuilder.cc, runtime/onert/backend/train/optimizer/SGD.h, runtime/onert/core/include/exec/train/optimizer/Optimizer.h
This commit allocates tensors for optimizer variables.
=> [onert] Allocate tensors for optimizer variables

compiler/luci/pass/src/ConvertToFakeQuantizedModelPass.cpp
This supports fake quantization of Exp op.
=> [luci] Fake quantize Exp

runtime/onert/backend/train/optimizer/Adam.cc, runtime/onert/backend/train/optimizer/Adam.h, runtime/onert/backend/train/optimizer/Optimizers.h
This commit introduces and applies adam optimizer.
=> [onert] Introduce and apply adam optimizer

compiler/circle-mpqsolver/src/bisection/BisectionSolver.cpp
This commit renames variable for clarity.
=> [circle-mpqsolver] Tidy BisectionSolver

infra/debian/runtime/rules
This commit updates debian build script to revive debuild build.
=> [infra/runtime] Revise debian build

compute/cker/include/cker/eigen/training_ops.h, compute/cker/include/cker/train/optimizer/SGD.h, compute/cker/src/train/SGD.test.cc
This commit brings Gradient Descent kernel from tensorflow v2.12.1.
=> [cker] Bring SGD kernel from tensorflow v2.12.1

infra/command/build-docker-image
This commit updates docker build command
- Default ubuntu codename: bionic -> focal
- Remove reduntant variable: DOCKER_TAG
- Update help message
=> [infra] Update docker build default setting

tests/tools/onert_train/src/measure.h, tests/tools/onert_train/src/onert_train.cc
This commit implements memory profiling functions. It also has been updated the output result form.
=> [tools/onert_train] Implement memory profiling functions

compiler/minmax-embedder/CMakeLists.txt, compiler/minmax-embedder/README.md, compiler/minmax-embedder/driver/Driver.cpp, compiler/minmax-embedder/requires.cmake
It introduces minmax-embedder driver.
=> [CFE/minmax-embedder] Introduce driver

infra/docker/focal/Dockerfile
This commit updates android sdk installation on docker image
- Install in user home
- Update install process for easy sdk and ndk version up
- Update openjdk version to 11 (default on 20.04)
---
Draft: #11712
=> [infra/docker] Update android sdk installation

docs/howto/how-to-cross-build-runtime-for-aarch64.md, docs/howto/how-to-cross-build-runtime-for-arm.md, tools/cross/install_rootfs.sh
This commit updates install_rootfs.sh script.
- Update default ubuntu version: use host codename
- Install python3-dev package for python API
- Fix hdf5 library symbolic link creation
- Update documentation
=> [tools] Revisit install_rootfs.sh

compiler/circle-mpqsolver/src/core/ErrorMetric.cpp
This commit improves accuracy of MAE metric and computes it as mean over mean output errors.
=> [circle-mpqsolver] Improve MAE

res/TensorFlowLiteRecipes/All_000/test.recipe, res/TensorFlowLiteRecipes/BatchMatMulV2_000/test.recipe, res/TensorFlowLiteRecipes/BatchMatMulV2_001/test.recipe, res/TensorFlowLiteRecipes/BroadcastTo_000/test.recipe, res/TensorFlowLiteRecipes/MatMul_000/test.recipe, res/TensorFlowLiteRecipes/MatrixBandPart_000/test.recipe, res/TensorFlowLiteRecipes/MaxPoolWithArgmax_000/test.recipe, res/TensorFlowLiteRecipes/MaxPoolWithArgmax_001/test.recipe, res/TensorFlowLiteRecipes/MaxPoolWithArgmax_002/test.recipe, res/TensorFlowLiteRecipes/Net_BroadcastTo_AddV2_000/test.recipe, res/TensorFlowLiteRecipes/Net_BroadcastTo_AddV2_001/test.recipe, res/TensorFlowLiteRecipes/Net_FC_Gelu_FC_000/test.recipe, res/TensorFlowLiteRecipes/Net_Gather_SparseToDense_AddV2_000/test.recipe, res/TensorFlowLiteRecipes/Net_Gelu_000/test.recipe, res/TensorFlowLiteRecipes/Net_Gelu_001/test.recipe
This introduces extype and custom_code for custom operators.
---
=> [res] Introduce extype and custom_code for custom operators

onert-micro/luci-interpreter/pal/common/PALL2Pool2D.h, onert-micro/luci-interpreter/src/kernels/DepthToSpace.cpp, onert-micro/luci-interpreter/src/kernels/Softmax.cpp, onert-micro/luci-interpreter/src/kernels/SpaceToDepth.cpp
- WID 1733311
- WID 1733310
- WID 1733309
- WID 1733308
=> Fix coverity defects

onert-micro/luci-interpreter/pal/common/PALL2Pool2D.h
=> Fix svace defect

compiler/common-artifacts/exclude.lst
This will enable to tcgen Cos,Sin and Tile.
=> [common-artifacts] Include Sin,Cos,Tile

res/TensorFlowLiteRecipes/Tile_001/test.recipe, res/TensorFlowLiteRecipes/Tile_002/test.recipe
This will add more Tile recipies.
=> [res] Add more Tile recipes

runtime/onert/backend/cpu/ops/SoftMaxLayer.h, runtime/onert/backend/train/KernelGenerator.cc, runtime/onert/backend/train/KernelGenerator.h, runtime/onert/backend/train/ops/SoftMaxLayer.cc, runtime/onert/backend/train/ops/SoftMaxLayer.h
This commit introduces SoftMaxLayer in train backend.
Draft: #11742
=> [onert] Introduce SoftMaxLayer in train backend

runtime/onert/backend/train/ops/ElementwiseActivationLayer.h, runtime/onert/core/include/compiler/train/TrainingInfo.h
This commit initializes ElementwiseActivationLayer and TrainingInfo class fields.
=> [onert/train] Initialize class field for train

res/CircleSchema/0.6/circle_schema.fbs
This adds comment for min/max values of QuantizationParameters.
=> [res] Update circle schema comment

compiler/luci/pass/include/luci/Pass/CommonSubExpressionEliminationPass.h, compiler/luci/pass/src/CommonSubExpressionEliminationPass.cpp, compiler/luci/pass/src/CommonSubExpressionEliminationPass.test.cpp, compiler/luci/pass/src/PassTestGraphs.h, compiler/luci/pass/src/helpers/ExpressionCache.cpp, compiler/luci/pass/src/helpers/ExpressionCache.h, compiler/luci/pass/src/helpers/ExpressionCache.test.cpp
This adds a new pass CommonSubExpressionEliminationPass.
---
Draft PR: #11824
=> [luci] Add CommonSubExpressionEliminationPass

compiler/rawdata2hdf5/rawdata2hdf5
This supports multi-input list to support multi-input circle models.
---
Related to: https://github.com/Samsung/ONE/issues/11724
Draft PR: https://github.com/Samsung/ONE/pull/11831
=> [rawdata2hdf5] Support multi-input list

compiler/record-minmax/src/RecordMinMax.cpp
This improves list format to accept space-delimitered multiple inputs.
---
Related to: https://github.com/Samsung/ONE/issues/11724
Draft PR: #11831
=> [record-minmax] Support multi-input list format

infra/nnfw/cmake/options/options_aarch64-tizen.cmake, infra/nnfw/cmake/options/options_armv7hl-tizen.cmake, infra/nnfw/cmake/options/options_armv7l-tizen.cmake, infra/nnfw/cmake/options/options_i686-tizen.cmake, infra/nnfw/cmake/options/options_x86_64-tizen.cmake
This commit enables training feature on gbs build.
=> [infra/gbs] Enable training feature

compute/cker/src/train/SoftMax.test.cc
This commit changes SoftMaxGrad test suite name to CKer_Operation.
=> [onert] Change SoftMaxGrad test suite name

compiler/one-cmds/one-quantize
This uses lower column limit in one-quantize.
=> [one-cmds] Use lower column limit in one-quantize

compiler/luci/import/include/luci/Import/Nodes.h, compiler/luci/import/include/luci/Import/Nodes/CircleCumSum.h, compiler/luci/import/src/GraphBuilderRegistry.cpp, compiler/luci/import/src/Nodes/CircleCumSum.cpp
This adds support for CumSum operation in luci importer.
---
Realated w/ : https://github.com/Samsung/ONE/issues/11842
Draft PR : https://github.com/Samsung/ONE/pull/11810
=> [luci/import] Support CumSum operation

compiler/luci/service/src/CircleCloneNode.h, compiler/luci/service/src/CircleShapeInferenceRule.cpp, compiler/luci/service/src/CircleTypeInferenceRule.cpp, compiler/luci/service/src/Nodes/CircleCumSum.cpp
This adds support for CumSum operation in luci service.
---
Realated w/ : https://github.com/Samsung/ONE/issues/11842
Draft PR : https://github.com/Samsung/ONE/pull/11810
=> [luci/service] Support CumSum operation

compiler/luci/pass/src/CommonSubExpressionEliminationPass.test.cpp, compiler/luci/pass/src/helpers/ExpressionCache.cpp
This supports CSE on Transpose Op.
---
Related to: https://github.com/Samsung/ONE/issues/11726
Draft PR: https://github.com/Samsung/ONE/pull/11869
=> [luci] Support CSE on Tranpose Op

compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
This reduce the number of newly created Quantize Ops.
---
Draft PR: https://github.com/Samsung/ONE/pull/11912
=> [luci] Improve multi-input mpq pattern

res/TensorFlowLiteRecipes/Quant_Mul_002/test.qconf.json, res/TensorFlowLiteRecipes/Quant_Mul_002/test.recipe, res/TensorFlowLiteRecipes/Quant_Mul_002/test.rule
This adds recipe and rule for Quant_Mul_002.
---
Draft PR: https://github.com/Samsung/ONE/pull/11912
=> [res] Add Quant_Mul_002

tools/generate_datafile/tf_dataset_converter/argparser.py
It fixes typo: training -> test
=> [tf_dataset_converter] Fix wrong help in argparser

nnpackage/schema/circle_schema.fbs
This updates comment for min/max in QuantizationParameters.
---
Related to: https://github.com/Samsung/ONE/pull/11822
=> [nnpackage] Update circle schema comment

compiler/luci/partition/include/luci/ConnectNode.h, compiler/luci/partition/src/Nodes/CircleCumSum.cpp, compiler/luci/partition/src/Nodes/CircleCumSum.test.cpp
This adds support for CumSum operatino in luci partition.
---
Realated w/ : #11842 
Draft PR : #11810
=> [luci/partition] Support CumSum Operation

onert-micro/CMakeLists.txt, onert-micro/examples/speech_recognition/DISCO_F746/mbed-os/CMakeLists.txt
This commit adds build example application target.
=> [onert-micro] Add build example application target

compiler/luci-value-test/test.lst
This enables CumSum operation in luci value test.
---
Realated w/ : #11842 
Draft PR : #11810
=> [luci-value-test] Enable CumSum operation

compiler/luci/service/src/Nodes/CircleCumSum.test.cpp
This adds a test for CumSum operation regarding to luci service.
---
Realated w/ : #11842 
Draft PR : #11810
=> [luci/service] Add CumSum test

compiler/circle-mpqsolver/src/CircleMPQSolver.cpp
This improves message for solver selection.
=> [circle-mpqsolver] Improve message

compiler/luci/pass/include/luci/CircleOptimizer.h, compiler/luci/pass/include/luci/Pass/RemoveUnnecessaryTransposeNetPass.h, compiler/luci/pass/src/CircleOptimizer.cpp, compiler/luci/pass/src/RemoveUnnecessaryTransposeNetPass.cpp, compiler/luci/pass/src/RemoveUnnecessaryTransposeNetPass.test.cpp
This commit introduces RemoveUnnecessaryTransposeNetPass.
* to resovle : https://github.com/Samsung/ONE/issues/11654 
* from draft : #11891 
=> [luci/pass] Introduce RemoveUnnecessaryTransposeNetPass

compute/cker/include/cker/train/operation/MaxPool.h, compute/cker/src/train/MaxPool.test.cc
This commit renames using the term "derivative" to the term "grad" or "incoming".
=> [cker] Rename derivative to grad or incoming

runtime/onert/backend/train/KernelGenerator.cc, runtime/onert/backend/train/ops/ConvolutionLayer.cc, runtime/onert/backend/train/ops/ConvolutionLayer.h, runtime/onert/backend/train/ops/OperationUtils.h
This commit applies Conv2D kernel for training to train backend.
=> [onert] Apply Conv2D kernel for training

runtime/onert/core/src/compiler/ExecutorFactory.cc, runtime/onert/core/src/compiler/train/StaticBackPropShapeInferer.cc
This commit changes index copy to reference.
---
Draft: #12013
=> [onert] Remove index copy

compiler/luci/pass/include/luci/Pass/FuseMulWithConvPass.h, compiler/luci/pass/src/FuseMulWithConvPass.cpp, compiler/luci/pass/src/FuseMulWithConvPass.test.cpp
This commit introduces FuseMulWithConvPass
for fusing Mul with Conv if possible.
Its correctness is tested in #11991.
Draft: #11991
Related: #11897
=> [luci/pass] Introduce FuseMulWithConvPass

compiler/luci/service/src/CircleCloneNode.h, compiler/luci/service/src/CircleShapeInferenceRule.cpp, compiler/luci/service/src/CircleTypeInferenceRule.cpp, compiler/luci/service/src/Nodes/CircleBroadcastTo.cpp, compiler/luci/service/src/Nodes/CircleBroadcastTo.test.cpp
This supports BroadcastTo in luci service.
---
=> [luci/service] Support BroadcastTo

onert-micro/luci-interpreter/pal/common/Broadcast.h, onert-micro/luci-interpreter/pal/common/PALMinimumCommon.h, onert-micro/luci-interpreter/src/kernels/Minimum.cpp
This commit refactors Minimum kernel.
=> [onert-micro] Refactor Minimum kernel

onert-micro/luci-interpreter/src/core/RuntimeGraph.cpp, onert-micro/luci-interpreter/src/kernels/Add.cpp, onert-micro/luci-interpreter/src/kernels/BinaryOpCommon.h, onert-micro/luci-interpreter/src/kernels/Div.cpp, onert-micro/luci-interpreter/src/kernels/FullyConnected.cpp, onert-micro/luci-interpreter/src/kernels/Mul.cpp, onert-micro/luci-interpreter/src/kernels/Reshape.cpp, onert-micro/luci-interpreter/src/kernels/Sub.cpp
This commit supports more dynamic shapes cases.
=> [onert-micro] Support more dynamic shapes cases

Makefile.template, infra/buildtool/CMakeLists.txt, runtime/onert/odc/CMakeLists.txt
This commit updates build infra to support ODC cross build.
=> [onert] Support ODC cross build

compiler/circle-mpqsolver/src/core/TestHelper.h, compiler/circle-mpqsolver/src/core/TestHelper.test.cpp
This commit introduces getSampleInput for using in tests.
=> [circle-mpqsolver] Introduce getSampleInput

infra/buildtool/CMakeLists.txt
This commit adds reading environment variable for mirror server login.
=> [infra] Set external mirror server login

onert-micro/luci-interpreter/pal/cmsisnn/PALFullyConnected.h, onert-micro/luci-interpreter/pal/common/PALFullyConnectedCommon.h, onert-micro/luci-interpreter/pal/common/PALUnidirectionalSequenceLSTMCommon.h, onert-micro/luci-interpreter/pal/mcu/PALFullyConnected.h, onert-micro/luci-interpreter/src/kernels/FullyConnected.cpp
This commit supports keep_dims in FullyConnected.
fixes: #12078
=> [onert-micro] Support keep_dims in FullyConnected

compiler/luci/pass/src/FoldAddV2Pass.cpp, compiler/luci/pass/src/FoldGatherPass.cpp, compiler/luci/pass/src/FoldSparseToDensePass.cpp
This will tidy unnecessary header includes.
=> [luci/pass] Tidy unnecessary header includes

compiler/luci-compute/src/ConvertTypes.cpp, compiler/luci-compute/src/ConvertTypes.h
This will introduce tflite_shape to convert shape.
=> [luci-compute] Introduce tflite_shape

runtime/onert/api/src/OpMap.lst, runtime/onert/core/include/ir/operation/ElementwiseBinary.h, runtime/onert/core/src/ir/operation/ElementwiseBinary.cc, runtime/onert/frontend/base_loader/include/base_loader.h
This commit introduces FloorMod operator.
- Load BuiltinOperator_FLOOR_MOD
- Introduce FloorMod IR into ElementwiseBinary
- Register FloorMod into OpMap
=> [onert] Introduce FloorMod operator

runtime/onert/backend/train/KernelGenerator.cc, runtime/onert/backend/train/ops/LossCategoricalCrossentropyLayer.cc, runtime/onert/backend/train/ops/LossCategoricalCrossentropyLayer.h, runtime/onert/core/include/ir/train/LossInfo.h
This commit introduces LossCategoricalCrossentropy layer and param structure.
=> [onert] Introduce LossCategoricalCrossentropy layer

compiler/luci-compute/include/luci_compute/DepthwiseConv2D.h, compiler/luci-compute/include/luci_compute/Types.h, compiler/luci-compute/src/DepthwiseConv2D.cpp
This will introduce initial compute code for DepthwiseConv2D.
=> [luci-compute] Introduce initial DepthwiseConv2D

compiler/luci-compute/src/DepthwiseConv2D.cpp
This will enable to compute output and padding for DepthwiseConv2D.
=> [luci-compute] DWConv2D compute output/padding

compiler/luci-compute/src/ConvertTypes.cpp, compiler/luci-compute/src/ConvertTypes.h, compiler/luci-compute/src/DepthwiseConv2D.cpp
This will enable to convert padding_type.
=> [luci-compute] DWConv2D enable convert padding_type

compiler/luci-compute/include/luci_compute/FullyConnected.h, compiler/luci-compute/include/luci_compute/Types.h, compiler/luci-compute/src/FullyConnected.cpp
This will introduce initial compute code for FullyConnected.
=> [luci-compute] Introduce initial FullyConnected

compiler/common-artifacts/CMakeLists.txt
This commit installs pytest package into venv.
Draft: #12162
Related: #12071 
=> [common-artifacts] Install pytest

compiler/luci/pass/src/helpers/Compute.cpp, compiler/luci/pass/src/helpers/Compute.h
This will introduce to_compute conversion helper methods.
=> [luci/pass] Introduce to_compute helper methods

runtime/onert/frontend/circle/src/circle_loader.cc, runtime/onert/frontend/circle_schema/include/circle_schema_generated.h
This commit updates circle loader to support schema v0.7.
---
Related issue: #12130 #12167
=> [onert] Update circle loader for schema v0.7

compiler/luci-interpreter/src/kernels/Select.cpp, compiler/luci-interpreter/src/kernels/Select.h
This commit removes broadcast feature from Select op.
ONE-DCO-1.0-Signed-off-by: ragmani ragmani0216@gmail.com
---
For #12148
=> [luci-interpreter] Remove broadcast feature from Select op

res/CircleSchema/0.7/circle_schema.fbs
This will introduce circle schema v0.7.
=> [res] Introduce circle schema v0.7

compiler/luci/pass/src/FoldFullyConnectedPass.cpp
This will revise FoldFullyConnectedPass with luci-compute.
=> [luci/pass] Revise FoldFullyConnectedPass with luci-compute

tools/generate_datafile/tf_dataset_converter/README.md, tools/generate_datafile/tf_dataset_converter/argparser.py, tools/generate_datafile/tf_dataset_converter/datasets.py, tools/generate_datafile/tf_dataset_converter/main.py
This commit helps convert imagenet datasets to onert_train data format.
=> [tools/tf_dataset_converter] Support imagenet dataset

compiler/mio-circle07/CMakeLists.txt, compiler/mio-circle07/README.md, compiler/mio-circle07/example.cpp, compiler/mio-circle07/include/mio_circle/Helper.h, compiler/mio-circle07/include/mio_circle/Reader.h, compiler/mio-circle07/src/Helper.cpp, compiler/mio-circle07/src/Helper.test.cpp, compiler/mio-circle07/src/Reader.cpp, compiler/mio-circle07/src/Reader.test.cpp
This will introduce mio-circle for v0.7
=> [mio-circle07] Introduce mio-circle for v0.7

compiler/luci-pass-value-py-test/CMakeLists.txt, compiler/luci-pass-value-py-test/README.md, compiler/luci-pass-value-py-test/conftest.py, compiler/luci-pass-value-py-test/requires.cmake, compiler/luci-pass-value-py-test/test.lst, compiler/luci-pass-value-py-test/test_luci_eval.py
This commit introduces a pytest for luci-pass-value-test.
Related: #12071
=> [luci-pass-value-py-test] Introduce pytest

compiler/circle-inspect/CMakeLists.txt, compiler/circle-inspect/requires.cmake
This will revise to use mio-circle07.
=> [circle-inspect] Revise to use mio-circle07

compiler/circle-operator/CMakeLists.txt, compiler/circle-operator/requires.cmake
This will revise to use mio-circle07.
=> [circle-operator] Revise to use mio-circle07

compute/cker/include/cker/operation/BinaryArithmeticOps.h, compute/cker/include/cker/operation/reference/BinaryArithmeticOps.h, compute/cker/src/Mul.test.cc
This commit makes the kernel for Mul support boolean type too.
- Add mul op unit tests
- Support bool type
=> [cker] Make Mul support bool type

compiler/circle-verify/CMakeLists.txt, compiler/circle-verify/requires.cmake
This will revise to use mio-circle07.
=> [circle-verify] Revise to use mio-circle07

Makefile.template, packaging/nnfw.spec
This commit updates luci build phase on runtime build to add mio-circle07.
=> [infra/onert] Add mio-circle07 for luci build

compiler/tflite2circle/CMakeLists.txt, compiler/tflite2circle/requires.cmake, compiler/tflite2circle/src/CircleModel.cpp
This will revise to use mio-circle07.
=> [tflite2circle] Revise to use mio-circle07

compiler/luci-compute/src/FullyConnected.test.cpp
This will introduce unit test for FullyConnected.
=> [luci-compute] Introduce unit test for FullyConnected

infra/packaging/preset/20230907, infra/packaging/preset/20230907_windows, infra/scripts/compiler_modules.sh
This will remove mio-circle06 from compiler build list.
=> [infra] Remove mio-circle06 from compiler list

compiler/circle-mpqsolver/src/core/DumpingHooks.h, compiler/circle-mpqsolver/src/core/TestHelper.h
This commit redeclares protected memebers as private for final classes.
=> [circle-mpqsolver] Revise protected

compute/cker/include/cker/operation/BinaryArithmeticOps.h, runtime/onert/backend/cpu/ops/BinaryArithmeticLayer.cc, tests/nnfw_api/src/one_op_tests/Mul.test.cc
This commit applies bool type kernel of Mul op.
- Apply the kernel to onert
- Modify the kernel so that it can be called implicitly too
---
for #12127
=> [onert] Apply bool type kernel of Mul op

compiler/luci/pass/src/ConvertNCHWToNHWCPass.cpp
This creates a new axis rather than in-place update.
---
Related to: https://github.com/Samsung/ONE/issues/12248
=> [luci] Fix SplitV bug in ConvertNCHWToNHWC

res/TensorFlowLiteRecipes/Net_Mul_Div_000/test.recipe, res/TensorFlowLiteRecipes/Net_Mul_Div_000/test.rule
This commit adds models for testing mul div pattern fusion.
from draft #12124
=> [res] TensorFlowLiteRecipes for mul div pattern

compiler/luci/pass/include/luci/CircleOptimizer.h, compiler/luci/pass/include/luci/Pass/FuseMulWithDivPass.h, compiler/luci/pass/src/CircleOptimizer.cpp, compiler/luci/pass/src/FuseMulWithDivPass.cpp, compiler/luci/pass/src/FuseMulWithDivPass.test.cpp
This commit introduces FuseMulWithDivPass pass.
=> [luci/pass] Introduce FuseMulWithDivPass

compiler/luci/pass/src/RemoveUnnecessaryTransposeNetPass.cpp, compiler/luci/pass/src/RemoveUnnecessaryTransposeNetPass.test.cpp
This commit extends RemoveUnncessaryTransposeNetPass to handle reshape/shape with -1 value.
related : https://github.com/Samsung/ONE/issues/12266
=> [luci/pass] Add shape inference to RemoveUnneccessaryTransposeNetPass

compiler/circle-interpreter-test/requires.cmake
This commit updates requires.cmake.
=> [circle-interpreter-test] Update requires.cmake

tests/tools/onert_train/src/onert_train.cc
This commit implements basic skeleton code of validation. It requires several implementations about data generator for validation, metric functions and validation argument how much to split data.
=> [tools/onert_train] Implement basic skeleton code of validation

runtime/onert/api/src/nnfw_api.cc, runtime/onert/api/src/nnfw_api_internal.cc, runtime/onert/api/src/nnfw_api_internal.h, runtime/onert/backend/CMakeLists.txt, runtime/onert/core/CMakeLists.txt, runtime/onert/core/include/exec/Execution.h, runtime/onert/core/src/backend/builtin/Backend.h, runtime/onert/core/src/compiler/CompilerFactory.cc, runtime/onert/core/src/compiler/ExecutorFactory.cc, runtime/onert/core/src/compiler/ExecutorFactory.h, runtime/onert/core/src/dumper/text/GraphDumper.cc, runtime/onert/core/src/dumper/text/GraphDumper.h, runtime/onert/core/src/exec/Execution.cc
This commit removes ONERT_TRAIN flag.
---
Related issue: #12293
=> [onert] Remove ONERT_TRAIN flag

compiler/luci-compute/include/luci_compute/DepthwiseConv2D.h, compiler/luci-compute/include/luci_compute/FullyConnected.h
This will initialize class struct type member to make analyzer tool happy.
=> [luci/compute] Initialize class struct member

runtime/3rdparty/half/README.md, runtime/3rdparty/half/include/half/ChangeLog.txt, runtime/3rdparty/half/include/half/LICENSE.txt, runtime/3rdparty/half/include/half/README.txt, runtime/3rdparty/half/include/half/include/half.hpp
This commit updates half library to version 2.2.0 and adds README.md.
=> [onert] Update half library

runtime/onert/core/include/compiler/train/TrainingInfo.h, runtime/onert/core/include/ir/train/OptimizerInfo.h
This PR add an OptimizerInfo default constructor.
=> [onert] Add OptimizerInfo default constructor

tests/tools/onert_train/src/dataloader.h, tests/tools/onert_train/src/onert_train.cc, tests/tools/onert_train/src/rawdataloader.cc, tests/tools/onert_train/src/rawdataloader.h, tests/tools/onert_train/test/rawdataloader.test.cc
This commit introduces DataLoader class and inherit it from RawDataLoader.
Draft: #12265
=> [tools/onert_train] Introduce DataLoader class

tests/tools/onert_train/README.md
This commit adds the required software tools to README.md file.
=> [tools/onert_train] Add the required software tools to readme file

tests/tools/onert_train/src/onert_train.cc
This commit applies the validation split value.
If the user sets the validataion split value, the data geneator splits the given dataset into train and validation datasets. Then, the training process uses the train dataset, and the validation process uses the validation dataset.
Draft: #12265
=> [tools/onert_train] Apply validation split value

runtime/onert/core/src/ir/train/TrainingInfo.cc
This PR update TrainingInfo::isValid() condtion to check learning_rate has positive value.
=> [onert] Update TrainingInfo::isValid() condition

compiler/one-cmds/CMakeLists.txt, compiler/one-cmds/one-create-quant-dataset, compiler/one-cmds/tests/one-create-quant-dataset_001.test, compiler/one-cmds/tests/one-create-quant-dataset_002.test, compiler/one-cmds/tests/one-create-quant-dataset_neg_001.test, compiler/one-cmds/tests/one-create-quant-dataset_neg_002.test, compiler/one-cmds/tests/one-create-quant-dataset_neg_003.test, compiler/one-cmds/tests/one-create-quant-dataset_neg_004.test, compiler/one-cmds/tests/one-create-quant-dataset_neg_005.test
This commit introduces one-cretae-quant-dataset to one-cmds.
---
=> [one-cmds] Introduce one-create-quant-dataset

runtime/onert/api/include/nnfw_experimental.h
This PR enhances nnfw_train_set_traininfo description by adding some details.
=> [onert/api] Enhance nnfw_train_set_traininfo description

runtime/onert/backend/train/KernelGenerator.cc, runtime/onert/backend/train/KernelGenerator.h, runtime/onert/backend/train/ops/MeanLayer.cc, runtime/onert/backend/train/ops/MeanLayer.h
This commit implements ReduceMean train backend.
Draft: #12358
=> [onert] Implement ReduceMean train backend

compiler/luci/pass/src/FoldCastPass.cpp
This will revise empty lines of FoldCastPass for better readability.
=> [luci/pass] Revise empty lines of FoldCastPass

compiler/circle2circle/src/Circle2Circle.cpp
This commit adds resolve_former_customop to circle2circle2.
---
=> [circle2circle] Add resolve_former_customop

tests/tools/onert_train/src/args.cc
This commit revisits args code to fix typo and remove unnecessary new lines.
=> [tools/onert_train] Revisit args in onert_train

compiler/luci/export/src/CircleExportMetadata.cpp, compiler/luci/import/src/CircleImportMetadata.cpp, compiler/luci/partition/src/PartitionIRDump.cpp, compiler/luci/pass/src/CircleQuantizer.cpp, compiler/luci/pass/src/CopyQuantParamPass.cpp, compiler/luci/pass/src/SubstituteSqueezeToReshapePass.cpp, compiler/luci/pass/src/helpers/LayerInfoMap.cpp, compiler/luci/service/src/ChangeOutputs.cpp, compiler/luci/service/src/ShapeInfer_StridedSlice.cpp
This will revise to use auto reference to fix static analysis warnings.
=> [luci] Use auto reference for static analysis warnings

onert-micro/luci-interpreter/src/kernels/Abs.cpp, onert-micro/luci-interpreter/src/kernels/Logistic.cpp
This commit changes some kernels to use SISOKernel.
---
For #11744
=> [onert-micro] Change some kernels to use SISOKernel

infra/cmake/packages/Pybind11SourceConfig.cmake, runtime/onert/python/api/src/nnfw_api_wrapper.cc
This commit updates Pybind11 to v2.11.1.
---
Related issue: #12496
=> [infra] Update Pybind11

infra/docker/bionic/Dockerfile, infra/docker/focal/Dockerfile, infra/docker/focal/Dockerfile.aarch64
This commit removes unused packages on docker image
- 18.04: android build environment
- 20.04 x64 & aarch64: clang-format 8
=> [infra] Remove unused packages on docker image

onert-micro/luci-interpreter/src/kernels/PadCommon.cpp
This commit reduces duplicate code in PadCommon.cpp.
---
For #11744
=> [onert-micro] Reduce duplicate code in PadCommon.cpp

compute/cker/include/cker/train/operation/BinaryArithmetic.h, compute/cker/src/train/BinaryArithmetic.test.cc
This commit introduces Add gradient kernel.
From draft https://github.com/Samsung/ONE/pull/12417
=> [cker] Introduce Add gradient kernel

onert-micro/onert-micro/include/OMConfig.h, onert-micro/onert-micro/include/OMInterpreter.h, onert-micro/onert-micro/include/OMStatus.h, onert-micro/onert-micro/src/OMInterpreter.cpp
This commit introduces user interface entities.
from draft #12426
=> [onert-micro] Introduce user interface entities

compiler/luci/pass/include/luci/Pass/FoldShapePass.h, compiler/luci/pass/src/FoldShapePass.cpp, compiler/luci/pass/src/FoldShapePass.test.cpp
This commit introduces a pass to fold Shape op
---
Draft: #12407
=> [luci/pass] Introduce the pass to FoldShape

compiler/luci/pass/include/luci/CircleOptimizer.h, compiler/luci/pass/src/CircleOptimizer.cpp
This commit introduces FoldShape option
---
Draft: #12407
=> [luci] Introduce FoldShape

compute/cker/src/train/BinaryArithmetic.test.cc
This PR fixes typo on liscense.
=> [cker] Fix typo on license

compiler/souschef/include/souschef/TensorFiller.h
This pr adds clear tensor filler methods.
for issue https://github.com/Samsung/ONE/issues/12506
from #12516
=> [souschef] Add clear tensor filler methods

compute/cker/include/cker/train/operation/BinaryArithmetic.h, compute/cker/src/train/BinaryArithmetic.test.cc
This commit introduces Subtract gradient kernel.
---
From draft #12417
=> [cker] Introduce Subtract gradient kernel

compiler/circle2circle/src/Circle2Circle.cpp
This commit adds an option to fold Shape op to circle2circle
---
Draft: #12407
=> [circle2circle] Add option to fold Shape op

res/TensorFlowLiteRecipes/Net_Shape_Add_000/test.rule
This commit adds a dredd test rule for fold_shape
---
Draft: #12407
=> [res] Add dredd test rule for fold_shape

tools/generate_datafile/tf_dataset_converter/README.md, tools/generate_datafile/tf_dataset_converter/argparser.py
This commit updates the models help message to make them easier to recognize.
=> [tools/tf_dataset_converter] Update models help message

compiler/tflchef/tflite/src/Op/While.cpp, compiler/tflchef/tflite/src/Op/include/While.h, compiler/tflchef/tflite/src/TFliteOpChefs.h, compiler/tflchef/tflite/src/TFliteOpRegistry.h
This pr adds while op to the tflite op chefs.
from https://github.com/Samsung/ONE/pull/12516
=> [tflchef] Add While op

compiler/tflchef/tflite/src/RecipeChef.cpp, compiler/tflchef/tflite/src/TFliteImport.cpp
This pr supports multiple subgraphs in tflchef.
for issue https://github.com/Samsung/ONE/issues/12506
from https://github.com/Samsung/ONE/pull/12516
=> [tflchef] Support multiple subgraphs

compiler/luci/pass/src/ResolveCustomOpAddPass.cpp
This commit revises ResolveCustomOpAddPass to introduce num_of_broadcast_to.
---
=> [luci/pass] Revise ResolveCustomOpAddPass to introduce num_of_broadcast_to

compute/cker/include/cker/train/operation/BinaryArithmetic.h, compute/cker/src/train/BinaryArithmetic.test.cc, runtime/onert/backend/train/ops/BinaryArithmeticLayer.cc
This commit introduces Multiply gradient kernel.
---
From draft #12417
=> [cker] Introduce Multiply gradient kernel

compiler/one-cmds/how-to-use-one-commands.txt, compiler/one-cmds/onelib/constant.py
This commit supports FoldShape pass in one-cmds
---
Draft: #12407
=> [one-cmds] Support for FoldShape pass

onert-micro/onert-micro/include/core/OMRuntimeContext.h, onert-micro/onert-micro/include/core/OMRuntimeGraph.h, onert-micro/onert-micro/include/core/OMRuntimeModule.h, onert-micro/onert-micro/include/core/OMRuntimeShape.h, onert-micro/onert-micro/include/core/OMRuntimeStorage.h, onert-micro/onert-micro/include/core/OMUtils.h, onert-micro/onert-micro/src/core/CMakeLists.txt, onert-micro/onert-micro/src/core/OMRuntimeContext.cpp, onert-micro/onert-micro/src/core/OMRuntimeGraph.cpp, onert-micro/onert-micro/src/core/OMRuntimeModule.cpp, onert-micro/onert-micro/src/core/OMRuntimeStorage.cpp, onert-micro/onert-micro/src/core/OMUtils.cpp
This pr adds core part of the new onert-micro.
=> [onert-micro] Add core part

runtime/onert/api/nnfw/src/nnfw_api_internal.cc, runtime/onert/core/include/loader/ModelLoader.h, runtime/onert/core/src/loader/ModelLoader.cc
This commit introduces plugin model loader managing function.
---
Related issue: https://github.com/Samsung/ONE/issues/12482
Draft: https://github.com/Samsung/ONE/pull/12563
=> [onert] Support plugin model loader

runtime/onert/core/src/ir/train/TrainableGraph.cc, runtime/onert/core/src/ir/train/TrainableGraph.test.cc
This commit fixes TrainableGraph btopolSortOperations.
=> [onert] Fix btopolSortOperations

onert-micro/onert-micro/include/optimize/BuildPass.lst, onert-micro/onert-micro/include/optimize/OMGraphStatus.h, onert-micro/onert-micro/include/optimize/OMOptimizePassesBuilder.h, onert-micro/onert-micro/include/optimize/OMOptimizer.h, onert-micro/onert-micro/src/optimize/CMakeLists.txt, onert-micro/onert-micro/src/optimize/OMOptimizer.cpp, onert-micro/onert-micro/src/optimize/pass/FindInplaceOpPass.cpp
This pr adds optimize entities part to the onert-micro
=> [onert-micro] Add optimize part

res/TensorFlowLiteRecipes/Net_Add_FloorMod_Gather_000/test.recipe, res/TensorFlowLiteRecipes/Net_Add_FloorMod_Gather_000/test.rule
This will introduce Net_Add_FloorMod_Gather_000 for remove_gather_guard.
=> [res] Introduce Net_Add_FloorMod_Gather_000

onert-micro/onert-micro/src/CMakeLists.txt
This pr adds src onert-micro Cmake file.
=> [onert-micro] Add src Cmake file

compiler/luci/pass/include/luci/Pass/RemoveGatherGuardPass.h, compiler/luci/pass/src/RemoveGatherGuardPass.cpp, compiler/luci/pass/src/RemoveGatherGuardPass.test.cpp
This will introduce RemoveGatherGuardPass to remove Add/FloorMod guard ops of Gather.
=> [luci/pass] Introduce RemoveGatherGuardPass

compiler/luci/pass/include/luci/CircleOptimizer.h, compiler/luci/pass/src/CircleOptimizer.cpp
This will add RemoveGatherGuard to enable RemoveGatherGuardPass.
=> [luci/pass] Add RemoveGatherGuard

compiler/circle2circle/src/Circle2Circle.cpp
This will add remove_gather_guard to remove Gather guard ops.
=> [circle2circle] Add remove_gather_guard option

compiler/one-cmds/how-to-use-one-commands.txt, compiler/one-cmds/onelib/constant.py
This will add remove_gather_guard optimization option.
=> [one-cmds] Add remove_gather_guard optimization option

runtime/onert/core/include/util/Index.h, runtime/onert/core/src/ir/train/TrainableGraph.cc
This commit adds index comparison operator.
---
From draft https://github.com/Samsung/ONE/pull/12621
=> [ONERT] Add index comparison operator

compiler/luci/pass/src/CircleQuantizer.cpp, compiler/luci/pass/src/FoldFullyConnectedPass.cpp, compiler/luci/service/src/CircleShapeInferenceRule.cpp
This commit removes object copy by auto.
=> [luci] Remove copy by auto

runtime/onert/backend/trix/KernelGenerator.cc, runtime/onert/core/src/compiler/StaticShapeInferer.cc
This commit removes object copy by auto.
---
Draft: #12648
=> [onert] Remove copy by auto

res/TensorFlowLiteRecipes/Net_Conv_Add_000/test.recipe, res/TensorFlowLiteRecipes/Net_Conv_Add_000/test.rule, res/TensorFlowLiteRecipes/Net_Conv_Add_001/test.recipe, res/TensorFlowLiteRecipes/Net_Conv_Add_001/test.rule, res/TensorFlowLiteRecipes/Net_Conv_Add_002/test.recipe, res/TensorFlowLiteRecipes/Net_Conv_Add_002/test.rule
This will introduce Net_Conv_Add recipes for Conv2D+Add fusion.
=> [res] Introduce Net_Conv_Add recipes

compiler/luci/pass/include/luci/Pass/FuseAddWithConvPass.h, compiler/luci/pass/src/FuseAddWithConvPass.cpp
This will introduce FuseAddWithConvPass that will fuse Add into Conv2D.
=> [luci/pass] Introduce FuseAddWithConvPass

tests/nnfw_api/CMakeLists.txt, tests/nnfw_api/lib/CirclePlusGen.cc, tests/nnfw_api/lib/CirclePlusGen.h
Let's introduce CirclePlusGen class for nnfw_api to test train cases.
---
draft: https://github.com/Samsung/ONE/pull/12665
=> [tests/nnfw_api] Introduce CirclePlusGen class

compiler/luci/pass/src/FuseAddWithConvPass.test.cpp
This will add unit test for FuseAddWithConvPass.
=> [luci/pass] Test for FuseAddWithConvPass

tests/nnfw_api/lib/GenModelTest.h, tests/nnfw_api/lib/GenModelTrain.h, tests/nnfw_api/src/GenModelTests/General.test.cc
This commit introduces GenModelTrain class and others for it.
---
draft: https://github.com/Samsung/ONE/pull/12665
=> [tests/nnfw_api] Introduce GenModelTrain class

docs/runtime/backend-api.md, docs/runtime/compute.md, docs/runtime/controlflow-operations.md, docs/runtime/core.md, docs/runtime/executors.md, docs/runtime/heterogeneous-execution.md
This commit corrects punctuation, typos and style.
ONE-DCO-1.0-Signed-off-by: Piotr Fusik <piotr@fusion-lang.org>
=> [doc] Minor improvements of the runtime docs

compiler/one-cmds/how-to-use-one-commands.txt, compiler/one-cmds/onelib/constant.py
This will add one-optimize fuse_add_with_conv option.
=> [one-cmds] Add fuse_add_with_conv

tools/generate_datafile/tf_dataset_converter/datasets.py
This PR adds a mnist tensorflow dataset to the tf_dataset_converter.
from draft : https://github.com/Samsung/ONE/pull/12694
=> [tools/dataset_converter] Add the mnist dataset

compiler/mio-circle08/CMakeLists.txt, compiler/mio-circle08/README.md, compiler/mio-circle08/example.cpp, compiler/mio-circle08/include/mio_circle/Helper.h, compiler/mio-circle08/include/mio_circle/Reader.h, compiler/mio-circle08/src/Helper.cpp, compiler/mio-circle08/src/Helper.test.cpp, compiler/mio-circle08/src/Reader.cpp, compiler/mio-circle08/src/Reader.test.cpp
This will introduce mio-circle for v0.8
from draft: #12707
=> [mio-circle08] Introduce mio-circle for v0.8

compiler/circle-inspect/CMakeLists.txt, compiler/circle-inspect/requires.cmake
=> [circle-inspect] Revise to use mio-circle08

compiler/circle-operator/CMakeLists.txt, compiler/circle-operator/requires.cmake
=> [circle-operator] Revise to use mio-circle08

compiler/circle-verify/CMakeLists.txt, compiler/circle-verify/requires.cmake
=> [circle-verify] Revise to use mio-circle08

compiler/circledump/CMakeLists.txt, compiler/circledump/README.md, compiler/circledump/requires.cmake
=> [circledump] Revise to use mio-circle08

compiler/pics/CMakeLists.txt, compiler/pics/requires.cmake
=> [pics] Revise to use mio-circle08

compiler/tflite2circle/CMakeLists.txt, compiler/tflite2circle/requires.cmake
=> [tflite2circle] Revise to use mio-circle08

runtime/onert/api/python/CMakeLists.txt, runtime/onert/loader/trix/CMakeLists.txt, runtime/onert/odc/CMakeLists.txt, runtime/service/npud/backend/trix/CMakeLists.txt
This commit strips installed libraries to reduce binary size.
=> [onert] Strip installed libraries

Makefile.template, packaging/nnfw.spec
This commit updates luci build phase on runtime build to add mio-circle08.
=> [infra/onert] Revise to use mio-circle08 for luci build

Makefile.template, packaging/nnfw.spec
This will update luci build phase on runtime build to remove mio-circle07.
=> [infra/onert] Remove mio-circle07 for luci build

infra/packaging/preset/20230907, infra/packaging/preset/20230907_windows, infra/scripts/compiler_modules.sh
This will remove mio-circle07 from compiler build list.
=> [infra] Remove mio-circle07 from compiler list

compiler/circlechef/core/src/Convert.test.cpp
This will reorder convert test tensortype for better readability.
=> [circlechef] Reorder convert test tensortype

res/CircleSchema/0.8/circle_schema.fbs
This will add UINT4 datatype in circle_schema v0.8.
=> [res] Add UINT4 in circle_schema

compiler/souschef/include/souschef/Data/Constant.h, compiler/souschef/include/souschef/Data/Explicit.h, compiler/souschef/src/Explicit.cpp
This will introduce Constant/Explict DataChef for INT4 and UINT4.
=> [souschef] Introduce DataChef for INT4, UINT4

compiler/tflchef/core/src/ModelChef.cpp
This will enable to pack for INT4 data.
=> [tflchef] Pack for INT4

compiler/loco/include/loco/IR/DataType.h, compiler/loco/include/loco/IR/DataTypeTraits.h, compiler/loco/src/Service/TypeInference.test.cpp
This will introduce S4/U4 DataType to support 4bit int/uint.
=> [loco] Support S4/U4 for int4/uint4 data type

compiler/luci/lang/include/luci/IR/DataTypeHelper.h
This will introduce DataTypeHelper with size() of DataType.
=> [luci/lang] Introduce DataTypeHelper

compiler/luci-interpreter/pal/linux/pal.cmake, compiler/luci-interpreter/src/kernels/SelectV2.cpp, compiler/luci-interpreter/src/kernels/TransposeConv.cpp
This will revisee to use kernel from TF 2.12.1.
=> [luci-interpreter] Revise to use kernel from TF 2.12.1

compiler/luci/export/src/CircleExporterUtils.cpp, compiler/luci/export/src/CircleTensorExporter.cpp, compiler/luci/import/src/CircleReader.cpp, compiler/luci/import/src/Nodes/CircleConst.cpp, compiler/luci/lang/src/Nodes/CircleConst.cpp, compiler/luci/logex/src/CircleNodeSummaryBuilders.cpp, compiler/luci/pass/src/RemoveDuplicateConstPass.cpp, compiler/luci/pass/src/ResolveCustomOpAddPass.cpp, compiler/luci/pass/src/helpers/Strings.cpp, compiler/luci/pass/src/helpers/Strings.test.cpp, compiler/luci/service/src/Nodes/CircleConst.cpp, compiler/luci/service/src/Nodes/CircleConst.test.cpp
This will revise to enable INT4/UINT4 data type.
=> [luci] Support INT4/UINT4

compiler/locop/src/FormattedGraph.cpp
This will enable to get string for S4, U4 DataType.
=> [locop] Support str for S4, U4

compiler/luci/pass/src/DecomposeHardSwishPass.cpp, compiler/luci/pass/src/TransformMinMaxToRelu6Pass.cpp, compiler/luci/pass/src/TransformMinReluToRelu6Pass.cpp, compiler/luci/pass/src/UnrollUnidirectionalSequenceLSTMPass.cpp
This will tidy unnecessary header includes.
=> [luci/pass] Tidy unnecessary headers

compiler/luci-interpreter/src/kernels/Utils.cpp, compiler/luci-interpreter/src/loader/GraphLoader.cpp
This will revise to support INT4 data type.
=> [luci-interpreter] Support INT4

compiler/luci-interpreter/src/kernels/Utils.cpp, compiler/luci-interpreter/src/loader/GraphLoader.cpp
This will revise to support UINT4 data type.
=> [luci-interpreter] Support UINT4

compiler/luci/export/src/CircleTensorExporter.cpp
This will introdue encodeOpBufferPack4bit to replace two encodeOpBufferByDType implementations for S4 and U4 to reduce duplicate codes.
=> [luci/export] Introduce encodeOpBufferPack4bit

res/CircleRecipes/CircleBatchMatMul_I4_000/test.recipe, res/CircleRecipes/CircleBatchMatMul_U4_000/test.recipe, res/TensorFlowLiteRecipes/FullyConnected_I4_000/test.recipe, res/TensorFlowLiteRecipes/FullyConnected_I4_001/test.recipe
This will introduce circle and tflite recipe with INT4/UINT4 data types.
=> [res] circle/tflite recipes with INT4/UINT4

compiler/luci/import/src/Nodes/CircleConst.cpp
This will introduce common copy_data_4 for S4/U4.
=> [luci/import] Introduce copy_data_4

compiler/luci/pass/src/QuantizationUtils.cpp, compiler/luci/pass/src/QuantizationUtils.h, compiler/luci/pass/src/QuantizeOnnxQDQPass.cpp, compiler/luci/pass/src/QuantizeOnnxQDQPass.h, compiler/luci/pass/src/QuantizeOnnxQDQPass.test.cpp
This introduces a pass to quantize ONNXQuantize/Dequantize pattern.
---
=> [luci/pass] Introduce QuantizeOnnxQDQPass

compiler/luci-interpreter/src/kernels/FullyConnected.cpp, compiler/luci-interpreter/src/kernels/FullyConnected.h, compiler/luci-interpreter/src/kernels/FullyConnected.test.cpp, compiler/luci-interpreter/src/loader/nodes/FullyConnected.cpp
This commit adds support of INT4 quantized weights in FullyConnected kernel.
For #12767
=> [luci-interpreter] Support Hybrid INT4 weights FullyConnected kernel

compiler/luci/pass/src/QuantizeOnnxDequantizeLinearPass.cpp, compiler/luci/pass/src/QuantizeOnnxDequantizeLinearPass.h, compiler/luci/pass/src/QuantizeOnnxDequantizeLinearPass.test.cpp
This introduces a pass to quantize with OnnxDequantizeLinear Op.
---
=> [luci/pass] Introduce QuantizeOnnxDequantizeLinearPass

compiler/luci/pass/include/luci/CircleQuantizer.h, compiler/luci/pass/src/CircleQuantizer.cpp
This enables to quantize onnx-fq model.
---
=> [luci/pass] Quantize Onnx-fq model

compiler/circle-quantizer/src/CircleQuantizer.cpp
This adds an option to quantize Onnx fq model.
---
=> [circle-quantizer] Add quantize_onnx_fq_model option

compiler/luci/pass/src/RequantizePass.cpp
This fixes a wrong quantized_dimension in the input model.
---
Request from @lemmaa
=> [luci] Fix quantized_dimension during Requantization

compiler/luci-value-py-test/test_luci_eval.py, compiler/luci-value-py-test/test_luci_eval_ref.py
This will reduce duplicate error messages.
=> [luci-value-py-test] Reduce duplicate messages

compiler/luci-pass-value-py-test/test_luci_eval.py
This will reduce duplicate error messages.
=> [luci-pass-value-py-test] Reduce duplicate messages

compiler/circle-opselector/driver/Driver.cpp, compiler/circle-opselector/src/OpSelector.cpp
This commit checks if given operators from users include If or While.
Related: #12828
=> [circle-opselector] Check if given operators include If or While

compiler/luci-ref-value-py-test/CMakeLists.txt, compiler/luci-ref-value-py-test/README.md, compiler/luci-ref-value-py-test/conftest.py, compiler/luci-ref-value-py-test/requires.cmake, compiler/luci-ref-value-py-test/test.lst, compiler/luci-ref-value-py-test/test_luci_eval.py
This will introduce initial version of luci-ref-value-py-test that does value test with given reference values.
=> [luci-ref-value-py-test] Introduce initial version

compiler/circlechef/core/src/Op/FullyConnected.cpp, compiler/circlechef/core/src/Op/FullyConnected.h, compiler/circlechef/core/src/OpChef.def, compiler/circlechef/core/src/OpChefs.h, compiler/circlechef/proto/circlechef.proto
This will enable chef for FullyConnected Op.
=> [circlechef] Enable FullyConnected

infra/docker/bionic/Dockerfile, infra/docker/focal/Dockerfile, infra/docker/jammy/Dockerfile
This commit updates dockerfile
- Update sdb version
- Remove clang-format on 18.04
- Install gbs & sdb on 22.04
=> [infra] Update dockerfile

res/TensorFlowLiteRecipes/Net_Mul_Div_001/test.recipe, res/TensorFlowLiteRecipes/Net_Mul_Div_001/test.rule
This will introduce Net_Mul_Div_001 with Mul-Div.
=> [res] Introduce Net_Mul_Div_001

compiler/luci/pass/src/FuseMulWithDivPass.test.cpp
This will revise FuseMulWithDivPass test to focus on test as;
- relocate comment just above TestGraph
- relocate mul/div settings to Graphlet
- remove mul/div shape settings as it's unnecessary for testing
=> [luci/pass] Revise FuseMulWithDivPass test

res/TensorFlowLiteRecipes/Net_Mul_Div_000/test.recipe
This will revise Net_Mul_Div_000 recipe with smaller size.
=> [res] Revise Net_Mul_Div_000 recipe

compiler/luci/pass/src/QuantizeOnnxDequantizeLinearPass.cpp
This removes unused code OnnxDequantizeLinearPatternV2.
=> [luci] Remove unused code.

compiler/luci/pass/src/FuseMulWithDivPass.cpp, compiler/luci/pass/src/FuseMulWithDivPass.test.cpp
This will revise FuseMulWithDivPass with new fuse_mul_with_div_to_mul method to fuse to Mul Op.
=> [luci/pass] Revise FuseMulWithDivPass for Mul

compiler/luci/pass/src/FuseMulWithDivPass.cpp
This will revise existing fuse_mul_with_div to fuse_mul_with_div_to_div and,
- use luci::fill()
- check activation is NONE
- replace Div with new Div instead of updating
=> [luci/pass] Revise FuseMulWithDivPass for Div

runtime/onert/backend/trix/DevContext.cc
This commit changes trix backend supporting version: 2.3 ->2.4
=> [onert] Change trix backend version

.github/workflows/run-onert-micro-unit-tests.yml, onert-micro/CMakeLists.txt, onert-micro/eval-driver/CMakeLists.txt, onert-micro/eval-driver/Driver.cpp, onert-micro/externals/CMakeLists.txt, onert-micro/onert-micro/include/OMStatus.h, onert-micro/standalone/CMakeLists.txt
This commit switches project to new refactored version.
=> [onert-micro] Switch project to refactored version

nnpackage/schema/circle_schema.fbs
This commit updates circle schema to 0.8.
It's a copy from  `res/CircleSchema/0.8`.
=> [nnpackage] Update circle schema

runtime/libs/circle-schema/include/circle_schema_generated.h
This commit updates circle schema generated file to v0.8.
=> [onert] Update circle schema generated file

compiler/circle2circle/src/Circle2Circle.cpp
This adds a new option fold_squeeze.
---
=> [circle2circle] Add fold_squeeze option

compiler/one-cmds/onelib/constant.py
This adds fold_squeeze option to one-optimize.
---
=> [one-cmds] Add fold_squeeze option

infra/nnfw/cmake/options/options_aarch64-tizen.cmake, infra/nnfw/cmake/options/options_armv7hl-tizen.cmake, infra/nnfw/cmake/options/options_armv7l-tizen.cmake, infra/nnfw/cmake/options/options_i686-tizen.cmake, infra/nnfw/cmake/options/options_x86_64-tizen.cmake, packaging/nnfw.spec
This commit disables npud build on tizen.
=> [infra] Disable NPU daemon build on tizen

infra/nnfw/config/gbs.conf
This commit changes gbs.conf url from latest to reference.
=> [infra/gbs] Change gbs.conf url to reference

runtime/onert/api/nnfw/include/nnfw_experimental.h, runtime/onert/api/nnfw/src/nnfw_api_internal.cc, runtime/onert/core/include/odc/IQuantizer.h, runtime/onert/core/include/odc/QuantizeManager.h, runtime/onert/core/include/odc/QuantizeType.h, runtime/onert/core/src/odc/QuantizeManager.cc, runtime/onert/core/src/odc/QuantizeManager.test.cc, runtime/onert/odc/Quantizer.cc, runtime/onert/odc/Quantizer.h, runtime/onert/odc/Quantizer.test.cc
It uses quantize type internally.
It includes #11494. This PR may be landed as whole. Then, I will close #11494.
=> [onert] Use quantize type instead of bool

runtime/onert/backend/train/TensorRegistry.h
This commit introduces DisposableBackPRopTensor into TensorRegistry of train backend. DisposableBackPropTensor is temporary tensor where back-propagating gradient is caculated and stored before it is accumulated into the actual tensor to be back-propagated.
=> [onert] Introduce DisposableBackPropTensor into TensorRegistry

compiler/one-cmds/one-prepare-venv, compiler/one-cmds/one-prepare-venv.aarch64, compiler/one-cmds/one-prepare-venv.u1804
This will revise one-prepare-venv to install torch 2.1.2+cpu.
And extract version to variable.
=> [one-cmds] Revise to install torch 2.1.2+cpu

compiler/circledump/src/OpPrinter.cpp
This will add a comment for RELU_0_TO_1 Option.
=> [circledump] Comment for RELU_0_TO_1

compiler/tfldump/src/OpPrinter.cpp
This will add a comment for RELU_0_TO_1 Option.
=> [tfldump] Comment for RELU_0_TO_1

res/TensorFlowLiteRecipes/ReLU0To1_000/test.recipe
This will introduce ReLU0To1_000/ tflite recipe.
=> [res] Introduce ReLU0To1_000 tflite recipe

tests/tools/onert_run/src/args.cc, tests/tools/onert_run/src/onert_run.cc
This commit adds more quantization type argument for onert_run to support full quantization.
---
Draft: #12903
=> [tools/onert_run] Add more quantization type

compiler/luci/pass/src/QuantizeWithPredecessorPass.cpp
This removes unused header and add used one.
=> [luci] Use proper header

compiler/luci/pass/src/QuantizeWithPredecessorPass.cpp, compiler/luci/pass/src/QuantizeWithPredecessorPass.test.cpp
This quantizes Square Op (Mul) with predecessors.
---
This is to fill missing qparams in the models quantized by external tools.
=> [luci] Quantize Square with predecessors

compiler/luci/pass/src/FuseAddWithFullyConnectedPass.cpp, compiler/luci/pass/src/FuseAddWithFullyConnectedPass.test.cpp
This fuses s16 add with s16 FC.
---
Related to: https://github.com/Samsung/ONE/issues/12988
=> [luci] Fuse s16 add with s16 FC

compiler/luci/pass/include/luci/CircleOptimizer.h, compiler/luci/pass/include/luci/Pass/FuseRsqrtPass.h, compiler/luci/pass/src/CircleOptimizer.cpp, compiler/luci/pass/src/FuseRsqrtPass.cpp, compiler/luci/pass/src/FuseRsqrtPass.test.cpp
This adds a new pass FuseRsqrtPass.
---
Related to: https://github.com/Samsung/ONE/issues/12987
Draft PR: #12998
=> [luci] Introduce fuse_rsqrt pass

compiler/circle2circle/src/Circle2Circle.cpp
This adds a new fuse_rsqrt option.
---
Related to: https://github.com/Samsung/ONE/issues/12987
Draft PR: https://github.com/Samsung/ONE/pull/12998
=> [circle2circle] Add fuse_rsqrt option

tools/circle_plus_gen/lib/train_param.py, tools/circle_plus_gen/lib/utils.py
This PR extends namer to support multiple naming.
This is to accept various string while loading json file.
* related issue : https://github.com/Samsung/ONE/issues/12650
=> [tools/circle_plus_gen] Extend Namer to support various naming

Makefile.template, infra/debian/runtime/rules, packaging/nnfw.spec
This commit updates build scripts to strip the binaries using cmake install command.
=> [infra] Strip using cmake command

compiler/circle2circle/src/Circle2Circle.cpp
This adds a new option (fold_reshape).
---
Related to: https://github.com/Samsung/ONE/issues/13016
Draft PR: https://github.com/Samsung/ONE/pull/13019
=> [circle2circle] Introduce fold_reshape

tests/libs/tflite/include/tflite/Diff.h, tests/libs/tflite/include/tflite/InterpreterSession.h, tests/libs/tflite/src/Diff.cpp, tests/libs/tflite/src/RandomInputInitializer.cpp
This commit updates tflite library namespace and included headers.
---
Related issue: #13009
=> [onert/testlib] Update tflite namespace and headers

runtime/onert/odc/Quantizer.cc
This commit updates quantizer to prepare full quantization parameter for CircleQuantizer and call fake quantization.
---
Draft: #12903
Related issue: #12904
=> [onert/odc] Prepare full quantization parameter

runtime/onert/core/src/compiler/HEScheduler.cc
This commit removes dead code in HEScheduler.cc
=> [onert] Remove dead code in HEScheduler

tools/circle_plus_gen/example/train_tparam.json, tools/circle_plus_gen/lib/json_parser.py, tools/circle_plus_gen/lib/train_param.py, tools/circle_plus_gen/main.py
This PR add a json loader to parse a json file of training hyper parameters and construct TrainParam instance. 
ONE-DCO-1.0-Signed-off-by: seunghui youn <sseung.youn@samsung.com> 
* related issue : https://github.com/Samsung/ONE/issues/12650
=> [tools/circle_plus_gen] Add training parameters json loader 

runtime/onert/api/nnfw/src/nnfw_api.cc, runtime/onert/api/nnfw/src/nnfw_api_internal.cc, runtime/onert/api/nnfw/src/nnfw_api_internal.h
This commit adds function to set workspace path string to session.
---
Draft: #12903
=> [onert] Set workspace to session

tests/tools/tflite_comparator/src/tflite_comparator.cc
This commit updates tflite comparator to print number value, not charater on uint8_t type.
=> [onert/test] Print number value on tflite comparator

compiler/luci-compute/CMakeLists.txt
This commit updates kernel version to TFLite v2.16.1.
=> [luci-compute] Update compute kernel version

infra/debian/runtime/nnfw.install, packaging/nnfw.spec, runtime/onert/backend/acl_cl/CMakeLists.txt, runtime/onert/backend/acl_neon/CMakeLists.txt, runtime/onert/backend/cpu/CMakeLists.txt, runtime/onert/backend/ruy/CMakeLists.txt, runtime/onert/backend/train/CMakeLists.txt, runtime/onert/backend/trix/CMakeLists.txt, runtime/onert/backend/xnnpack/CMakeLists.txt, runtime/onert/core/CMakeLists.txt, runtime/onert/loader/trix/CMakeLists.txt
This commit introduces new install path for backend and loader libraries.
---
Related issue: #13074
=> [onert] Change backend and loader install path

runtime/onert/core/src/exec/MinMaxData.cc, runtime/onert/core/src/exec/MinMaxData.h, runtime/onert/odc/MinMaxReader.cc, runtime/onert/odc/MinMaxReader.h
This commit updates minmax data file format to add mgic code and version.
---
Related issue: https://github.com/Samsung/ONE/pull/13047#discussion_r1618134348
=> [onert] Introduce magic code and version to minmax data file

tools/circle_plus_gen/README.md, tools/circle_plus_gen/example/tparam_sgd_scce.json, tools/circle_plus_gen/how-to-write-tparam-json.md, tools/circle_plus_gen/lib/json_parser.py
This PR adds a document for describing hyperparameters json file.
=> [tools/circle_plus_gen] Add document for json file

tools/circle_plus_gen/lib/json_parser.py
This PR fix regular expression in json parser.
=> [tools/circle_plus_gen] Fix regular expression in json parser

infra/docker/android-sdk/Dockerfile
This commit introduces docker image to install android sdk and related packages.
Android sdk in focal will be removed.
=> [infra] Introduce android sdk docker

runtime/onert/core/src/ir/train/operation/UntrainableOperation.test.cc
This commit adds unit tests for `UntrainableOperation`.`
=> Add unit tests for `UntrainableOperation`

runtime/onert/core/include/ir/train/TrainingInfo.h, runtime/onert/core/src/loader/TrainInfoLoader.cc
This commit adds version variable to the TrainingInfo structure.
Draft: #13014
=> [onert] Add version to the TrainingInfo strcture

tests/nnfw_api/lib/GenModelTrain.h, tests/nnfw_api/src/GenModelTests/one_op_trains/Conv2D.test.cc
This commit revisits GenModelTrain in nnfw_api_tests.
- Change TrainCaseData to mean one dataset
- Allow TrainCaseData to add data by step or dataset
- Apply changed TrainCaseData to Conv2D tests
---
Draft PR #12985
=> [onert] Revisit GenModelTrain

tests/tools/onert_train/src/onert_train.cc
If the user gives a `--metric` property to the onert_train during training, it writes the metric result to the standard output device.
Draft: #13062
=> [onert_train] Print metric result during training

compiler/one-cmds/CMakeLists.txt, compiler/one-cmds/onelib/argumentparse.py
This commit introduces argumentparse lib.
Draft: #13161 
=> [one-cmds] Introduce arguemntparse lib

runtime/onert/api/nnfw/src/nnfw_api_internal.cc, tests/nnfw_api/src/NNPackageTests/AddModelLoaded.test.cc, tests/nnfw_api/src/NNPackageTests/AddSessionPrepared.test.cc
This commit adds validation check and unittest for workspace.
=> [onert] Add validation check unittest for workspace

.ahub/sam/exclude.txt
This commit updates execlude.txt for code quality analysis.
=> [infra] Update exclude.txt

runtime/onert/backend/train/optimizer/Optimizers.test.cc
This commit revises wrong comments in optimizer tests.
=> [onert] Revise wrong comments

runtime/onert/core/include/exec/Execution.h, runtime/onert/core/include/exec/ExecutionContext.h, runtime/onert/core/include/exec/IExecutor.h, runtime/onert/core/include/exec/IExecutors.h, runtime/onert/core/src/exec/Execution.cc, runtime/onert/core/src/exec/ExecutorBase.cc, runtime/onert/core/src/exec/ExecutorBase.h, runtime/onert/core/src/exec/MultiModelExecutors.cc, runtime/onert/core/src/exec/MultiModelExecutors.h, runtime/onert/core/src/exec/SingleModelExecutors.cc, runtime/onert/core/src/exec/SingleModelExecutors.h, runtime/onert/core/src/exec/train/TrainableExecutor.cc, runtime/onert/core/src/exec/train/TrainableExecutor.h, runtime/onert/core/src/exec/train/TrainableExecutors.cc, runtime/onert/core/src/exec/train/TrainableExecutors.h
This commit introduces ExecutionContext struct.
It includes IODescription and execution options to be used by executor.
---
Draft: #13013
=> [onert] Introduce ExecutionContext

compiler/one-cmds/dummy-driver/CMakeLists.txt, compiler/one-cmds/dummy-driver/src/dummy-compiler.cpp, compiler/one-cmds/onelib/argumentparse.py, compiler/one-cmds/tests/onecc_064.cfg, compiler/one-cmds/tests/onecc_064.py, compiler/one-cmds/tests/onecc_064.test
This commit support boolean type in the command schema.
=> [one-cmds] Support boolean type in the command schema

onert-micro/onert-micro/include/core/train/OMCheckpointLoader.h, onert-micro/onert-micro/include/core/train/OMCheckpointSaver.h, onert-micro/onert-micro/src/core/train/OMCheckpointLoader.cpp, onert-micro/onert-micro/src/core/train/OMCheckpointSaver.cpp
This pr introduces OMCheckpointLoader and OMCheckpointSaver entities.
=> [onert-micro] Introduce OMCheckpointLoader and OMCheckpointSaver

compiler/luci/pass/src/ForwardTransposeOpPass.cpp
This will revise ForwardTransposeOpPass to check I/O rank are same.
=> [luci/pass] Revise ForwardTransposeOpPass

compiler/one-cmds/tests/one-codegen_005.cfg, compiler/one-cmds/tests/one-codegen_005.test, compiler/one-cmds/tests/one-codegen_006.cfg, compiler/one-cmds/tests/one-codegen_006.test, compiler/one-cmds/tests/one-codegen_007.cfg, compiler/one-cmds/tests/one-codegen_007.test, compiler/one-cmds/tests/one-codegen_008.test, compiler/one-cmds/tests/one-profile_005.test, compiler/one-cmds/tests/one-profile_006.test, compiler/one-cmds/tests/one-profile_007.test, compiler/one-cmds/tests/one-profile_008.test, compiler/one-cmds/tests/onecc_060.cfg, compiler/one-cmds/tests/onecc_062.test, compiler/one-cmds/tests/onecc_063.test, compiler/one-cmds/tests/onecc_064.test
This commit revisits recently introduced tests.
=> [one-cmds] Revisit the tests

compiler/one-cmds/one-codegen, compiler/one-cmds/one-profile, compiler/one-cmds/tests/one-codegen_009.cfg, compiler/one-cmds/tests/one-codegen_009.ini, compiler/one-cmds/tests/one-codegen_009.py, compiler/one-cmds/tests/one-codegen_009.test, compiler/one-cmds/tests/one-profile_009.cfg, compiler/one-cmds/tests/one-profile_009.ini, compiler/one-cmds/tests/one-profile_009.py, compiler/one-cmds/tests/one-profile_009.test, compiler/one-cmds/tests/onecc_065.cfg, compiler/one-cmds/tests/onecc_065.ini, compiler/one-cmds/tests/onecc_065.py, compiler/one-cmds/tests/onecc_065.test
This commit allows command key for gradual change of target option.
=> [one-cmds] Allow command key for gradual change

tools/circle_plus_gen/main.py
This PR updates main.py to reuse 'print_training_hparameters'.
=> [tools/circle_plus_gen] Update main to reuse print function

runtime/onert/odc/MinMaxReader.cc
This commit removes analyzer warning in MinMaxReader.
- Adds more check for fseek
- Use explicit static_cast to cast uint64_t std::fseek argument
- Use int32_t for data_size to remove signed-to-unsigned casting
- Add std namespace to std::fclose and std::fread
---
It removes 4 major defect warnings.
=> [onert] Remove warning in MinMaxReader

compiler/one-cmds/one-import-onnx
This will revise to disable one-import-onnx-ext with environment variable.
=> [one-cmds] Disable one-import-onnx-ext with env.var.

compiler/one-cmds/one-import-onnx
This will fix default disable_ext value to true if given.
=> [one-cmds] Fix disable_ext default value

onert-micro/eval-driver/CMakeLists.txt, onert-micro/eval-driver/TrainingDriver.cpp
This pr enables TrainingDriver to test OMTrainingInterpreter.
=> [onert-micro] Enable TrainingDriver

tests/nnfw_api/src/GenModelTests/nontrainable_op_trains/MaxPool2D.test.cc
This PR adds more test cases(with stride=2 and negative cases) for MaxPool2D.
Co-authored-by: ragmani <ragmani0216@gmail.com>
=> [onert] Add more unit tests for MaxPool2D op
